### ISSUE TITLE
Redstone In Motion computer reboot.

### ISSUE THREAD

**Issue by trevor403** [MightyPirates/OpenComputers#10]
Computers seem to turn off every time a carriage controller moves the computer, I've been using a support carriage for the sake of keeping all the components together and every time i call a move command it occurs successfully then the computer turns off. Also i noticed a bug that if you call the move command for the carriage component it returns true even if only one argument is given and the carriage doesn't move. When you execute cc.move("up", false, false) it moves for real. Okay hope you get this worked out, its the only reason i migrated from ComputerCraft, thanks!

**Comment by fnuecke** [comment]
Hmm, I can't reproduce the rebooting. Does it happen all of the time? Does the computer shut down or reboot? If it shuts down, does using the Analyzer on the computer print an error message? Anything in the logs?

As for `move()` always returning true, that is by design. As [described in the wiki](https://github.com/MightyPirates/OpenComputers/wiki/Component-RedstoneInMotion) the call is essentially asynchronous. All `move()` does is queue the move which is then performed in the next server tick. To check whether the move actually succeeded you'll need to wait for the `carriage_moved` signal directly after calling `move()`.

**Comment by fnuecke** [comment]
I'll have to assume this was a user error since there's no additional feedback.
I I'm wrong let me know and I'll reopen the issue.

**Comment by JJSax** [comment]
It happens every time for me too.  I came here to report it then found this.  It seems like once the frames move the computer it restarts the computer.  I'm not sure what an Analyzer is.  How do I try this out?  I'm on a server, but I will ask the owner of it to check the logs when I move it and I'll get back to you with that one. I'll show some short code in case it's something I'm doing wrong.

p = peripheral.wrap("back")
p.move(1, false, false)

PS.  I'm pretty good at responding.  So if you need more info, just ask for it.

**Comment by lordjoda** [comment]
Well it appears you are using ComputerCraft computers not OpenComputers... with CC this is not a bug as their computers are not persistent...

**Comment by JJSax** [comment]
I don't fully understand.  The motor tooltip says computercraft not openComputers.  Is there a way to get around this?

**Comment by lordjoda** [comment]
You are using ComputerCraft http://www.computercraft.info but you are posting in the Issues for OpenComputers http://www.minecraftforum.net/topic/2201440-opencomputers-v120-pre3-v200-pre1/ 
So either you ask the server owner to add OpenComputers (if it is not already installed) and then use our computers if you want to use computers with RiM. Or you can try something else with CC. But all future issues with ComputerCraft should go into http://www.computercraft.info/forums2/index.php?/forum/14-ask-a-pro/ .. and as I said the reboot is not a ComputerCraft bug... so you will not get any help there...

**Comment by JJSax** [comment]
Um, can I just say that I'm an idiot.  In my haste to find the redstone in motion github or other similar type page, I didn't check what mod this was for.  Dang.  I feel stupid now.  Sorry to waste your time.  *Facepalm!
