### ISSUE TITLE
Scanners, detectors, imaging and NORMAL 2D printers.

### ISSUE THREAD

**Issue by SeniorFight** [MightyPirates/OpenComputers#1000]
Although it's already in side-mods, I would like this to be implented to the core-mod:

scanners - when right clicked, returns an event called "scanner", with player name and other goodies.
detectors - acts like a radar, scans a region in search of mobs/players and returns a table (this time as external API).

Now, something new and more complicated:

imaging - module allowing to report, in a precise ray (like in the side-mods), what blocks are on view, with IDs, so we can set a colour. Also detect mobs/players. If possible, report nearest hex code to the ray end hit, so we could just put a pixel with the colour!

connected with imaging, I would love to print an image made in the computer using the "camera" module, into paper using a 2d printer (simple printer), then put it into a wall (item frames?). It's quite hard, but would be veeery useful and fancy!

I don't know if, but it would be easier to make like a "screenshot" from the camera and send info through a table with each pixel (minecraft's pixel, not normal monitor pixel).

Don't start raging at me, creativity is what we need ;)

**Comment by gjgfuj** [comment]
Why double work when its already in the addons. There's no point. And then
that will lead to no one using the addons which will upset their authors.

**Comment by fnuecke** [comment]
As long as the respective addons are maintained (which, AFAIK, they are), I don't see much sense in adding such features to OC itself (with exceptions, as always). If the respective mods' authors are willing to PR their stuff into OC, I'd be fine with - no, happy about - that, of course. As long as it's polished enough (I'm picky ;-)).

**Comment by flarn2006** [comment]
Belated congratulations on 1,000 bugs! :tada:
