### ISSUE TITLE
You should be able to eat Chamelium (I could code this in,  but I dont know scala)

### ISSUE THREAD

**Issue by MFernflower** [MightyPirates/OpenComputers#1001]
#410

**Comment by fnuecke** [comment]
Hrm. Maybe you'll be able to chew on it, but never really eat it :P

**Comment by MyNameIsKodos** [comment]
Maybe make it poison for 10 seconds, restore half a shank of hunger, but only usable once every minute or two?

**Comment by Vexatos** [comment]
I second @fnuecke's idea.

**Comment by MFernflower** [comment]
Good ideas everyone!

**Comment by fnuecke** [comment]
I think this makes the most physical sense, given the nature of Chamelium :P
Also, you can disable it in the config if you don't like it.
