### ISSUE TITLE
How to add a dependency

### ISSUE THREAD

**Issue by KJA1582** [MightyPirates/OpenComputers#1005]
I'm stumped about this.

Adding as Ivy hosted on my own server I still get the message that the.pom couldn't be downloaded from libraries.minecraft.net, even though I have a .pom right next to the jar.

**Comment by fnuecke** [comment]
I believe that message just mentions the last/first(?) server it tried. Add `--info` / `--debug` when running Gradle for more info. Check for typos. Compare to existing dependencies.

That said, please go to `#ForgeGradle` on the Esper IRC network or so, for general help with Gradle.
