### ISSUE TITLE
@Callback not available in-Game

### ISSUE THREAD

**Issue by KJA1582** [MightyPirates/OpenComputers#1006]
http://pastebin.com/xpsYcmn5

It gets initialized just fine, but I can't access the @Callback in-game.

**Comment by fnuecke** [comment]
You probably aren't registering the driver.

Also, please use the IRC channel or forums for support, the issue tracker is meant for bug reports and feature discussions.

**Comment by KJA1582** [comment]
I call it an Issue since using the logging function, it clearly shows that it somehow gets to the point.

This  OpenComputers.log.info("INIT FLAXBEARD")  added behind the callback does get called.

**Comment by fnuecke** [comment]
Check your log, if it actually gets registered an instantiated, if anything is wrong with the implementation it should warn you about that in the log.

**Comment by fnuecke** [comment]
Also, just to make sure the computer isn't holding an old wrapper of the component, reboot it or re-place the adapter block.

**Comment by KJA1582** [comment]
Replacing the actual block and reassigning the variable in lua doesn't do this??

**Comment by fnuecke** [comment]
Components are cached (for performance, very noticeable) by address, so there's a chance the GC didn't run, cleaning the weak entries from the cache, thus the old proxy being re-using.

**Comment by KJA1582** [comment]
Aha. You were right. It now works as intended. Thanks again.

PS: I'm not very comfortable with IRC., nor did I ever use it before.

**Comment by fnuecke** [comment]
Great :-)

Consider registering on the forum then. The main reason I'd like to avoid the issue tracker being used for support is that I'd like to keep notifications on, to be able to quickly react to bugs; but don't want my inbox swarmed with questions, which can often be answered by others.

**Comment by KJA1582** [comment]
I felt more of it beeing a bug though, but ok. Hope you might consider merging it once I'm comfy enough to call it somewhat complete.

**Comment by fnuecke** [comment]
Sure!
