### ISSUE TITLE
Add additional interface to put on Environments for controlling if a Callback may be used

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#1010]
Just a reminder for @fnuecke. Maybe some interface that has a `shouldAddCallback(world, x, y, z, callbackname)` or something like that, you probably already have a better idea. Just make sure it also works for ManagedEnvironments added by Drivers.

**Comment by fnuecke** [comment]
Added an interface implemented by `Environment`s, `FilteredEnvironment`. Provides a single method, `boolean isCallbackAvailable(String name)`, takes only the name of the callback to test for, since all other info should be available in the env itself.
