### ISSUE TITLE
transparency for 3d printed objects

### ISSUE THREAD

**Issue by lifeNerd** [MightyPirates/OpenComputers#1011]
I´ve printet obects with glass texture, but the texture wasn´t transparent. Instead, the obect was filled with black. Is this a feature or a bug?

**Comment by fnuecke** [comment]
MC 1.7 or 1.8? Because I'm pretty sure I had this working, but I'm not sure if I tested transparency in both versions.

**Comment by lifeNerd** [comment]
i´ve made yesterday my first steps in OC with MC 1.8 and OC 1.5.4.9.
The following line is content of my object:
{0,6,0,16,7,8,texture = "glass"}

**Comment by fnuecke** [comment]
Thanks, I'll look into it!
