### ISSUE TITLE
Connecting OpenPeripherals causes component spam and weirdness

### ISSUE THREAD

**Issue by Arminius** [MightyPirates/OpenComputers#1012]
Hi,

I'm using OpenComputers 1.7.10-1.5.5.12 and OpenPeripheral 1.7.10-AIO-1.
every time I connect something like a chest with OpenPeripheral installed to an adapter, numerous read-only filesystem components appear on the computer, each of which contains the same programs docs, twitter, github and multipheral (those programs don't even work because they're written for Computercraft, not OpenComputers).

Now, I'm not sure if it's these filesystem that are causing it, but connecting an OpenPeripheral to an adapter can cause a lot of components to appear that count against the CPU's component limit, which can quickly overload a computer.
For instance, connecting a chest creates somewhere between 1-2 components, a furnace between 2-3 components, and an ME controller from AE2 gets anywhere between 1 or 5 components.

That's the other gripe I have, the number of components created by a block seems to fluctuate whenever it is broken and replaced. Sometimes, components even seem to linger after the block or adapter has been removed. I've got an empty computer case connected to absolutely nothing that somehow has 2 components (after creating and breaking a connection to an ME controller several times); [here's](http://imgur.com/a/QGJmN) a few pictures of it.

I don't know how much of this is actually under control by OpenComputers, but I thought I'd report it here rather than to OpenPeripheral because those guys just target ComputerCraft, not OpenComputers.

**Comment by Vexatos** [comment]
Just wait for OpenPeripheral 0.6 to be released, it will have native and full OC support.

**Comment by fnuecke** [comment]
If you want to help them test, try using the very latest versions from their Jenkins - keeping in mind that those may not be compatible with some other mods, yet, because it's a WIP. If it still happens with those, this is something you may want to report to them. As @Vexatos said, they're currently working on OC integration (which is awesome). If that sounds too messy for you, just sit tight and get hyped for 0.6 ;-)

Leaving this open until OpenPeripheral 0.6 is out, to make it easier to find for others running into these issues.

**Comment by Arminius** [comment]
I see, I didn't know the OpenPeripheral folks were working on OC integration. I'll wait for that then and just keep breaking and replacing my computer cases whenever I have trouble.

**Comment by Vexatos** [comment]
Warning: Do not use OpenPeripheral 0.6 together with Computronics. Until OpenPeripheral 0.6 is officially released, I won't update integration to the new version which means it will most likely crash one way or another.

**Comment by fnuecke** [comment]
New version of OpenPeripheral - with OC support - is out now!
