### ISSUE TITLE
Turning off unexistent server in rack resulted in non-loadable world

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1014]
Log:
http://pastebin.com/Yh3M8yzE
I can provide a world save (backuped).

**Comment by ghost** [comment]
More info:
Steps to reproduce:
1) Create Server rack item, place it power it etc
2) Place a working server inside of a Rack. (didn't have an OS yet though)
3) Turn on a server.
4) When server is still on, pull it out, push "Off" button.

This is not reproducible in singleplayer, but easily reproducible in multiplayer due to network lag.

**Comment by fnuecke** [comment]
I cannot reproduce this. Furthermore, the log you pasted does not mention OC anywhere, making me doubt it's actually related to OC. Please post a full crashlog.

**Comment by KJA1582** [comment]
I'm gonna try to recreate these circumstances and post a full failure log, once I get a server running with decent net lag.

**Comment by KJA1582** [comment]
@nekoexmachina How bad was your speed connection to the server? I got mine to freeze twice now, no log however (didn't crash, was unresponsive). Running the server on Debian 6 with Java 7

**Comment by ghost** [comment]
@KJA1582, i've toyed around with lags & stuff. Opis seems to ve the main issue in this bug, not opencomputers. Without opis, no crash, while with opis, about 2 od 10 tries result in crash.
Sorry for wrong bug!

**Comment by fnuecke** [comment]
OK, if it turns out to be OC after all, let me know and I'll reopen this for further investigation.

@KJA1582 regarding the freezes, did you have a look with VisualVM what was hanging? If that's OC, please open a new issue for that, and let me know where it hangs, thanks!

**Comment by KJA1582** [comment]
I tried this for about 4 or 5 hours, it is very elusive. It could be OC since, theoretically, by trying to shut down a removed server it basically is sender a call to a nonexistent object, which potentially can hang any program.
