### ISSUE TITLE
3d printed blocks does not separate Project Red cables.

### ISSUE THREAD

**Issue by Cruor** [MightyPirates/OpenComputers#1015]
3d printed blocks in iron, FMP strips/covers in light blue stained clay.

![image](https://cloud.githubusercontent.com/assets/2391698/6992239/c1dabbc4-dac2-11e4-931c-c559879ad4cc.png)

**Comment by fnuecke** [comment]
Looks like the part has to implement `TSlottedPart`, which is... interesting for user defined shapes :P But after some initial testing it looks feasible.
