### ISSUE TITLE
Using rm /* on HDD doesn't delete the tooltip

### ISSUE THREAD

**Issue by KJA1582** [MightyPirates/OpenComputers#1021]
I used said command to wipe  an HDD containing OpenOS. While it did clean the drive, it didn't remove the ToolTip saying OpenOS, which is somewhat intriguing.

**Comment by KJA1582** [comment]
EDIT, I may not have the permissions to delete the bin/boot/lib folder, maybe the information is stored in there.

**Comment by Vexatos** [comment]
To wipe an HDD, just hold it in your hand and shift-right click.

**Comment by KJA1582** [comment]
That got changed in one of the latest commits :/

**Comment by fnuecke** [comment]
@Vexatos not anymore, by popular demand. To avoid people accidentally erasing their data.

@KJA1582 The tooltip has nothing to do with the data on the disk. You can change the label using the `label` program.

**Comment by KJA1582** [comment]
Aha. Still interesting that an empty disk has to be manually labeled as e.g Empty.

**Comment by Vexatos** [comment]
@fnuecke Right, shift-rightclicking is far too 2014. Nowadays, people use RAIDs to wipe HDDs. :dancer:

**Comment by fnuecke** [comment]
:+1:
