### ISSUE TITLE
computer.beep produces no sound

### ISSUE THREAD

**Issue by Omega-Haxors** [MightyPirates/OpenComputers#1023]
I'm not sure why, but  I cannot hear anything when I run this function.

I can hear all of the other sound effects fine, and all volume settings are at 100%. It's only the computer.beep sound that fails to play. I also have the beepVolume config set to 32.

There is no error given in the console, it just won't play the sound at all.

**Comment by KJA1582** [comment]
Beeps for me. Maybe your system can't find(play the sound file (rather strange though)?

**Comment by Omega-Haxors** [comment]
It seems the sound file is missing completely! It's not in the assets folder. I even checked the latest download from Curse and it's just not there.

This leads me to believe that either

A) Somebody forgot to ship the sound in the latest update
or
B) The beep sound is generated in run-time or located in a different folder

**Comment by Kubuxu** [comment]
@Omega-Haxors it is generated during runtime.

**Comment by KJA1582** [comment]
@Omega-Haxors Which OS are you using? Could be something more Platform specific.

**Comment by fnuecke** [comment]
The beeps are generated in-memory, yes. Please double-check your log - if the sound generation fails it'll only log that once, and then disable it, to avoid spamming the log.

**Comment by Omega-Haxors** [comment]
What sort of things would prevent the sound from being generated?

**Comment by KJA1582** [comment]
I'd guess user permission (specifically Mac OS X and Linux) can prevent applications to write to disk, but since this in-memory it could be insufficient memory allocated to the JVM.

**Comment by Omega-Haxors** [comment]
I restarted my client and found this error when playing the sound:

[OpenComputers]: Couldn't play computer speaker sound because your sound card ran out of memory. Either your sound card is just really low-end, or there are just too many sounds in use already by other mods. Disabling computer speakers to avoid spamming your log file now.

Which is strange because no sounds were playing and I have a somewhat reasonable sound card.

**Comment by KJA1582** [comment]
Did you have any other sound outputting applications like iTunes et. al. open and playing music et. al. while running minecraft?

**Comment by Omega-Haxors** [comment]
Only teamspeak.

**Comment by KJA1582** [comment]
Try without teamspeak. It _could_ fill up your sound card's memory.

**Comment by Omega-Haxors** [comment]
I've closed literally any application that could create a sound, including my web browser, and tried it.

It still gives me the error, and still will not generate the sound. This should not be possible.

**Comment by KJA1582** [comment]
On to the generic stuff:
1. Restart Client - you did that, didn't help
2. Restart PC
3. Update Drivers
4. Get the latest version of OC
5. Only have OC as a mod, no others

**Comment by fnuecke** [comment]
Do you play with a bunch of other mods? Some load sounds into memory and keep them there, to avoid lag when they have to be played.

**Comment by Omega-Haxors** [comment]
You were right fnuecke. The modpack I was using had a lot of mods, so there were a lot of sounds precached. Removing all but opencomputers allowed me to hear the beep sound as intended.

Do you think you could add an actual beep.ogg sound that automatically activates if the error is present? That should help a ton with issues regarding this.

**Comment by Kubuxu** [comment]
@Omega-Haxors if the generated sound didn't fit into the memory ogg won't for sure.

**Comment by fnuecke** [comment]
That's exactly why there's no fallback, yet, because that's my suspicion, too. Unless MC's sound lib is smart and swaps sounds out... ha ha. Ha. Ha. (I doubt it)

And if I preload it, some other sound will likely fail to load - what's more important, computers beeping or that creeper hiss behind you? ;-)

**Comment by Omega-Haxors** [comment]
Okay. Hopefully this issue will be sorted out eventually.

**Comment by Omega-Haxors** [comment]
I just had a thought. Wouldn't it be possible to use an existing sound effect as a replacement for the beep? Sure it wouldn't be a proper beep but at least it would be something rather than nothing.

The fire.ignite sound is somewhat tolerable, and would be a massive improvement over silence.

**Comment by Kubuxu** [comment]
Omega, if OC is not able to load its small sound file, there are probably many more missing.

**Comment by Omega-Haxors** [comment]
I haven't noticed any sound effects going missing, this is literally the only effect that will not play.

Out of all of my time playing, this is the ONLY sound effect that does not play. Each and every other sound effect is perfectly fine and not a single one plays oddly or cuts off. This is the only one that won't work.

Is there a way to playsound like openperipherals addon has? I could just use that in place of the beep command.
