### ISSUE TITLE
3D prints with arbitrary redstone strength

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#1025]
Instead of providing a boolean, redstone output can now also be set as an integer value (0-15), to emit custom strengths. Can be useful to differentiate which print was activated in a single multipart blockspace.

**Comment by Vexatos** [comment]
Maybe an extra upgrade like the b(e)acon bases?

**Comment by fnuecke** [comment]
To adjust the strength post-print? Hrm. Maybe a shaped crafting recipe with one redstone dust, similar to how Gregtech chipsets are configured with a screwdriver? As an addition, though, I don't think it's a real balance/whatever issue to allow directly configuring blocks to emit _weaker_ signals than the default.

**Comment by Vexatos** [comment]
It kind of is as other mods make semi-expensive blocks to do exactly that (including Microcontrollers).

**Comment by fnuecke** [comment]
Ehh, but those are dynamic. And potentially support bundled redstone. Here it's still just an on-off thing. One you could emulate with some redstone on the floor, anyway. I really don't think this comes close to anything worthy of comparison to MCUs? On the contrary, I kinda feel like making it configurable - any which way - makes it more powerful, even.

What would your suggestion be then? Have them be 0/15 by default, add redstone to increment/decrement value by one? Feels like it's over-complicating things a bit to me.

**Comment by Vexatos** [comment]
I actually like the gregtech way, just make sure NEI tells :smile:

I do think it should require _some_ extra resource, for example BuildCraft gates require the Comp Chipset (made with a redstone comparator) to be able to read/output specific redstone strength values. So how about crafting it with a comparator in a certain pattern?

**Comment by fnuecke** [comment]
But that would have to be a one-time cost. It makes no sense to consume one comparator each time you change the output (after it's been crafted with a comparator once). And no, I don't want an extra GUI for that. And I don't want to add extra book-keeping for that, to spit out a comparator when crafting if one was already used previously.

**Comment by Vexatos** [comment]
I second this. No GUI is always a good idea.You just need to find a clever way to add the comparator.

**Comment by fnuecke** [comment]
Hmm?

**Comment by fnuecke** [comment]
Actually, come to think of it... I'll just make it consume more material to print if it uses an output in [1,14]. Simple as that.

**Comment by Vexatos** [comment]
That's actually pretty clever.
