### ISSUE TITLE
Refactor configuration

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#1028]
This is something I keep forgetting, so here's an issue for it. For the next breaking update, split the configuration in parts, by section basically. May or may not work similarly to recipes, in that they get included into a single `user.conf`. Then the individual files may get overwritten on changes to the defaults, user overrides would go into that file.

**Comment by payonel** [comment]
at this point, people know where to find data in the one config file, it's too old to redo - we'll leave it
