### ISSUE TITLE
Add a MountPointAware interface for robot rendering

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#1034]
``` java
public interface MountPointAware {
  public boolean canUseMountPoint(MountPointPosition pos);

  public static enum MountPointPosition {
    BACK_BOTTOM,
    BACK_TOP,
    FRONT,
    LEFT_BOTTOM,
    LEFT_TOP,
    RIGHT_BOTTOM,
    RIGHT_TOP;
  }
}
```

For `IItemRenderer`s.
Because why not.

**Comment by fnuecke** [comment]
I'm closing this, also, since this can be inferred from the mount-point passed to the render callback added for #1038.

(Edit: well, not the `canUse` part, but that'd make things unnecessarily complicated, IMHO)
