### ISSUE TITLE
Add API package allowing integration with the Manual

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#1039]
Stuff to add new tabs, new pages and so on.

**Comment by Pwootage** [comment]
This would be a very convenient place for me to hook in for my API doc generator for IDEs (and, possibly, a static website generator).

**Comment by fnuecke** [comment]
Done. Will see if / when / how Lua / component documentation will go into the manual.

**Comment by KJA1582** [comment]
How about tabs (read it somewhere)?

**Comment by fnuecke** [comment]
Are already in :-)

**Comment by KJA1582** [comment]
I'll dig myself into it, let's see what I can figure out.

**Comment by KJA1582** [comment]
Where does the initial file, i.e. index.md get set as the initial?

**Comment by fnuecke** [comment]
[Here](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/client/Manual.scala#L90), why?

**Comment by KJA1582** [comment]
Just looking' for it

**Comment by KJA1582** [comment]
Yeah, I could get started with a new tab and .md files for the LUA api/ methods (like NEI used to be).

**Comment by fnuecke** [comment]
Ah, that's what you mean. I don't think this should be filled out by hand, instead it should be populated from the `@Callback` docstrings, because otherwise we have duplicate documentation again, which is bad, because it'd definitely go out of sync sooner or later.

Main problem being, this may (most likely) need new annotations to properly automate.

**Comment by Vexatos** [comment]
@fnuecke I don't think the full dynamic API documentation should be in the manual, it's just too much...

If you wanted to add it, just make a new ContentProvider reading all the EnvironmentAware stuff and putting those into a prefabricated base markdown file being the index listing all the APIs. I don't think you should do that, though.

**Comment by KJA1582** [comment]
Basic should suffice. After getting used to OC and the Manual, most will likely change to 'man' anyway.

**Comment by KJA1582** [comment]
Actually, looking at how MANY drivers there are, dynamic would be A LOT faster (and easier)...

**Comment by fnuecke** [comment]
_If_ this gets added, then yeah, it'll somehow be using the EnvironmentAware stuff, sure. But at the moment that is only available on query when you already have an item to query it for. If it were to be displayed in a list in the manual, we'd somehow have to know which items are relevant and provide said environments. For now, I don't think it has a very high priority, but if API docs go in, when they do it should be automated.
