### ISSUE TITLE
Add Smartphones

### ISSUE THREAD

**Issue by gjgfuj** [MightyPirates/OpenComputers#1041]
We have tablets already, how about smartphones. They will have smaller screens.

Also, they will have a reasonable complexity cap but will have a large number of slots for cards and upgrades. Including some t3 slots. The complexity cap would need to balance for this.

**Comment by Vexatos** [comment]
Smartphones are smaller than Tablet, in no way they could have more slots for cards/upgrades than those, that wouldn't make any sense. Also, I do not see any point in adding yet another portable computer, it would be pretty much exactly like a tablet, just worse due to being smaller.

**Comment by gamax92** [comment]
I agree, a "Smartphone" being smaller than a Tablet would have to be worse, not better. So, just put lesser capable things in a Tablet and well, there you go. This doesn't really make much sense

**Comment by gjgfuj** [comment]
Note: this was a semi-joke.

**Comment by fnuecke** [comment]
It's getting hard to tell which issues are for real and which aren't, let's move the silly back to IRC :P

To answer the demi-non-joke, though: my first though also was "more capacity than a tablet but smaller, that doesn't make much sense". And I don't really think a higher tier tablet is really needed, honestly. Sure, some want linked cards in them, but the lore of the linked cards is that they suck a lot of energy, so having them in tablets wouldn't make sense anyway. And I really don't think the mobile devices should be that powerful, anyway. Not in "vanilla" OC, anyway.
