### ISSUE TITLE
EEPROMS/ Lua Bios copying in BC adv crafting tables

### ISSUE THREAD

**Issue by n00b7** [MightyPirates/OpenComputers#1044]
![bug](https://cloud.githubusercontent.com/assets/11874683/7072602/af6d1dea-debb-11e4-965a-dbfc9a9f528f.png)

Hello, I am using 
(forge 1291 for 1.7.10)
Open Computers v1.5.6.13
Buildcraft v6.4.8

I think that I have discovered a bug, so i was going to let you know about it.

When i put a eeprom or a Lua bois into an advanced crafting table from BuildCraft. I put the Eeprom or Lua bois into the top of the table. (material crafting area) (the amount doesnt seem to matter.) and I have more stacks down in the slots below. It will make/add more copies of itself if you continue to move the stacks around.

I don't know if this is an issue with BuildCraft or Open computers,
 but i am going to post this in both places. 

Thank you for taking the time to look at this error. :)

**Comment by fnuecke** [comment]
Strange. Will try to look into this tomorrow.

**Comment by n00b7** [comment]
Buildcraft 6.4.9 and 6.4.10 fix this issue

**Comment by n00b7** [comment]
sorry for closing this it might happen with buildcraft 7.0.0 so i reopend this

**Comment by n00b7** [comment]
sorry for closing this it might happen with buildcraft 7.0.0 so i reopend this

**Comment by n00b7** [comment]
i reopend this because it could happen with buildcraft 7.0.0 beta

**Comment by Vexatos** [comment]
@asiekierka probably already fixed it for BC 7 as well.

**Comment by fnuecke** [comment]
Oh, it is? Cool then. And yes, I'd very strongly assume those changes will also be in 7. If not you can re-open it when it comes out and you see the issue re-appearing. Although, seeing as it seems to have been an issue in BC, it'd make more sense to open it on BC's issue tracker, then?
