### ISSUE TITLE
Feature Request: Block Update event

### ISSUE THREAD

**Issue by nf404** [MightyPirates/OpenComputers#1045]
It would be cool if you add a block update event and send it from blocks, attached to Adapter.
Maybe this feature require some card in adapter

**Comment by Vexatos** [comment]
Since Block Updates aren't really something that the player is supposed to notice (in vanilla you only notice it by abusing certain bugs), I am not sure about whether that's actually a good idea...

**Comment by nf404** [comment]
Extra Utilities mod have this 2 cool things:
http://wiki.skcraft.com/extra-utilities/block-update-detector
http://wiki.skcraft.com/extra-utilities/block-update-detector-advanced

This is very convenient not to rescan block by timer but only scan on update

**Comment by fnuecke** [comment]
So basically have the adapter emit "block_changed" signals when a block next to it performs a block update? Not too big a fan of the idea, honestly. And while there's precedent, that doesn't mean it's a particularly fitting idea for this mod.

What would be some actual use-cases where this would provide a big improvement?

**Comment by Vexatos** [comment]
@nf404 I know Extra Utilities adds blocks for that, as do some other mods. As I said, you are not supposed to notice block updates and you can't without abusing bugs _in vanilla_. Of course there are mods detecting them, but it does not fit into Minecraft. That's the same reason why the Navigation Upgrade uses relative coordinates. You aren't supposed to know the absolute coordinates of your position without opening the debug screen.

**Comment by fnuecke** [comment]
After some soul-searching I don't think this should be in "vanilla" OC, even if there are one or two valid use-cases for this. Easy enough to add such a block in an addon.
