### ISSUE TITLE
Bauble Computers

### ISSUE THREAD

**Issue by gjgfuj** [MightyPirates/OpenComputers#1046]
This one's completely for real this time.

A while back a person who I can't quite recall the name of suggested bauble computers in the IRC, which I attempted to add in my addon, but that didn't work since I was getting confused by the api.

anyway, what I'm saying is that we should be able to have ring, necklace and belt computers.
The ring is purely limited to t1 stuff, with slots for like 2 upgrades and 1 card. It can possibly interface with the player's inherant magical essence, as a default, as a ring is a magical item.
The necklace is a bit more powerful, having a slightly higher complexity cap on it, but still not a whole lot of things. It will also have the ability to interface with the essence.
The belt is capable of having t2 stuff, at a higher complexity cap, but it would also be unable to interface with the essence.

If equipped with a network card, they would be capable of interfacing with the other baubles.

**Comment by MFernflower** [comment]
This could be expanded even further - The internet of things in OC?

**Comment by gjgfuj** [comment]
Pretty much yeah.

**Comment by gjgfuj** [comment]
Also, I would be willing to implement this in my addon if I was able to get some help with how Machine, and the assembler recipes work.

**Comment by dashkal16** [comment]
I was involved in that initial discussion on the feature.

To expand on the "essence" bit:
Rings and amulets could slot in 'sensors'.  Sensors could read things about the player.  Things like health and hunger, but also magical properties like Thaumcraft warp or LP from Blood Magic.

The belt's purpose is to be the 'bridge', allowing a network card so rings could network to nearby computers.  Without one, a player could instead use a tablet computer.

All bauble computers would have a sort of near field networking (think bluetooth).

For example: A ring could read player warp, then send that via bluetooth to the belt, which then sends the information via wireless network card elsewhere.

**Comment by gjgfuj** [comment]
yeah, that sorta thing.

**Comment by Vexatos** [comment]
Uuh, and, well, how does it fit into OpenComputers again? I don't see much magic in this mod at all. This sounds like something you'd make an addon out of, not a feature for this mod.

**Comment by dashkal16** [comment]
Those specific sensors, certainly.  Wearable computers, on the other hand, would be handy in general for similar reasons to why they're useful in the real world.

**Comment by Vexatos** [comment]
> why they're useful in the real world

So no reason at all? :suspect:

Also, uuh, sensors? Sounds quite weird to me, I don't think that could work, I mean, how is a sensor supposed to know how hungry or hurt you are? Doesn't really make much sense.

Again, if it is doing anything with magic, it's made for some addon, not OpenComputers itself. If you really want it, make an addon.

**Comment by dashkal16** [comment]
Hungry?  Blood sugar.  And that's just tech we actually have.

**Comment by Vexatos** [comment]
Again, I don't think this fits into OpenComputers at all. Specifically because you want integration with magic mods, this should be in an OC addon rather than OC. Why don't you just make it yourself or ask someone else to do it? It really does not belong into OC.

**Comment by fnuecke** [comment]
While this sounds cool in theory, I'm not quite convinced about its practicality. Either way, this goes a bit beyond the level of mod integration I think is reasonable in OC itself, but as an addon, sure, why not. 

After finishing the ingame manual stuff I may find the time to write an example project on the usage of the Machine API, that should then be a good start.

Assembler recipes are relatively simple, in comparison, you just pass an appropriately formatted NBT tag via IMC to OC. For example code [see the tablet template](http://git.io/FVQJ), for documentation [see the wiki](http://ocdoc.cil.li/tutorial:modding_imc) (though that needs updating wrt. disassembly).

**Comment by gjgfuj** [comment]
If you could have an example project that adds a new machine and has it be
assembled using no dependencies on Oc core, cool. My issue with the inbuilt
recipes are that they very clearly have helpers within oc, which I feel at
a heavy disadvantage for lacking. If you could include an AssemblyHelper
class in the api, that'd help a lot.

**Comment by fnuecke** [comment]
All right, Machine example is done: https://github.com/MightyPirates/OC-Example-Machine
This demonstrates how to create, update and destroy a machine. It's the same principle for entity and item based devices, except that for items you'll have to be a bit more creative in how you track the actual machine state, since item stacks can change in any number of ways. So if you want to go that route, you'll have to track them in some tick-handler based manager, and update "validity" of the individual devices via the item's update method (which is only called while the stack is in a player's inventory).

I'm not really sure an example for the assembler is needed, because the few internal things that are referenced in the templates in OC itself aren't really all that relevant. I might do one just for completion's sake later, but this should cover the more important part.

And with this, I'll leave implementation of more item-based devices to someone else :P

**Comment by gjgfuj** [comment]
Thank you, I'll have a go at that soon.
