### ISSUE TITLE
In v1.5.6 the Robot specifig methodes are not working

### ISSUE THREAD

**Issue by TheKingDave** [MightyPirates/OpenComputers#1050]
Like robot.Up() and robot.Down() are not wirking instead you have to use robot.move(direction)

**Comment by gjgfuj** [comment]
Uh, itd be robot.moveUp if it did exist but it probably doesn't because its
unnecessary.

**Comment by TheKingDave** [comment]
I habe only reporter this because its in the wiki

**Comment by TheKingDave** [comment]
http://ocdoc.cil.li/api:robot

**Comment by gjgfuj** [comment]
There is no robot.move in that api, that is the openos api, are you sure
you aren't confusing it with component.robot?

**Comment by gjgfuj** [comment]
Also all methods are lowercase so that could be the problem. Nonetheless
its your issue not part of oc. As far as I can tell.

**Comment by TheKingDave** [comment]
![2015-04-10_14 22 51](https://cloud.githubusercontent.com/assets/9198553/7087614/7d4d2602-df8d-11e4-8931-158ba9e9de38.png)
This is my issue

**Comment by KJA1582** [comment]
Just run for k,v in pairs(robot) do print(k,v) end to get 
all available functions.

**Comment by Vexatos** [comment]
@dave3004 Do not use the robot component, use the robot API, i.e. don't do `component.robot` but `require("robot")` instead, although you only need that making your own programs, not inside the Lua interpreter.

**Comment by fnuecke** [comment]
What Vexatos said.
