### ISSUE TITLE
Manual scrolling escaping GUI

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#1051]
Happens quite often when clicking a link to another manual page and then starting to scroll.
![2015-04-10_12 50 39](https://cloud.githubusercontent.com/assets/4135064/7086403/ecc30f36-df80-11e4-941a-2beb2271aa14.png)
![2015-04-10_12 55 27](https://cloud.githubusercontent.com/assets/4135064/7086419/07e76262-df81-11e4-820d-ba9a66ff0905.png)

**Comment by KJA1582** [comment]
Can't recreate that.

**Comment by Kubuxu** [comment]
It might be driver/GFX specific.

**Comment by Vexatos** [comment]
Oh, I should note I run Minecraft with the java argument "-Dforge.forceNoStencil=true". It could be related to the problem.

**Comment by Kubuxu** [comment]
Sangar uses depth buffer to mask out a region so it shouldn't happen.

**Comment by KJA1582** [comment]
What does that argument do?

**Comment by Kubuxu** [comment]
Disables stencil buffer in MC's rendering.

**Comment by Vexatos** [comment]
What @Kubuxu said, it makes Minecraft not crash with certain _very old_ GPUs and old OpenGL versions.

**Comment by KJA1582** [comment]
ah ok. OpenGL 2 get any benefits of this?

**Comment by Kubuxu** [comment]
It makes OpenGL2.1only GPUs work with MC.

**Comment by Vexatos** [comment]
There is literally no benefit at all except for old GPUs not crashing.

**Comment by fnuecke** [comment]
Uhhhh, that... should be impossible. Great.

What I'm essentially doing is flattening the depth buffer, then punch a hole in it and render in that hole. Anything outside it shouldn't render. This indicates either the GL state gets messed with somewhere, or... or I don't know, honestly.

**Comment by Vexatos** [comment]
Well, I am quite sure it's somehow related to this java argument because of [the scrolling stuff in CodeChickenCore](https://github.com/Chicken-Bones/CodeChickenCore/blob/1.7.10/src/codechicken/core/GuiModListScroll.java#L39) (Yes, I see this warning in the log because of this java argument).

**Comment by Kubuxu** [comment]
@Vexatos ChickenBones uses stencil buffer.
Can you post a GL compatibility report? http://sourceforge.net/projects/openglreport/

**Comment by fnuecke** [comment]
That. I don't use the stencil buffer. I wanted to, but it seems to be disabled by default, even, so I dropped that idea.

**Comment by Vexatos** [comment]
The website wasn't working for me, but I managed to use a different tool and it gave me this: http://pastebin.com/4iAkfnLF

Maybe I should note that taking a screenshot using F2 fixes it until I randomly click links again.

**Comment by fnuecke** [comment]
Just to anyone who cares, this is fixed now. Throwing in a `GL11.glDisable(GL11.GL_ALPHA_TEST)` fixed it.
