### ISSUE TITLE
Add "Missing Texture" Texture to default image renderers on Manual pages

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#1053]
Maybe make it common for all image renderers, or maybe just for the default ones (item, block and oredict). Some texture that shows there is a missing texture (preferably not magenta and black) so you could for instance add a tag for a block or item that may not be available in your mod pack and it wouldn't show ugly errors on the manual page.

**Comment by Vexatos** [comment]
For instance, the Abstract Bus card of StarGateTech isn't there currently just spams this to the log: http://pastebin.com/z2Ni8fv6

**Comment by fnuecke** [comment]
Gah, right.
