### ISSUE TITLE
Code syntax highlighting (in-line/multi-line)

### ISSUE THREAD

**Issue by rashdanml** [MightyPirates/OpenComputers#1054]
Not sure if it's already implemented (not seeing it in the examples), and since Markdown has the feature, would be a great addition. I'm writing up a basic OpenOS and Lua Programming guide, and having the feature would be nice for example code.

**Comment by fnuecke** [comment]
I'll probably add this by making code segments render using OC's font renderer (i.e. the one used for screens). For now I made it so that code segments are rendered as italic (single ` only, ``` won't work and probably never will, because I parse line-by-line). So go ahead using those `s now, then the rendering can be fixed whenever I find the time! :-)
