### ISSUE TITLE
Norton Anti-Virus is recognizing your mod as a threat?

### ISSUE THREAD

**Issue by lilmoefow** [MightyPirates/OpenComputers#1055]
Im playing the TPPI2 pack which has opencomputersmod-1.5.3.455-dev-native.64.dll in it.. and Norton is recognizing it as a threat? why would that be

I included the details of the Virus pop up in a pastebin link http://pastebin.com/SmDSw3n1

**Comment by fnuecke** [comment]
It's a false positive. All of the code is open source, if you want to check it out yourself. Otherwise you'll have to trust me and all the other people that have looked over the source code. Not really much I can do about false positives.

**Comment by samis** [comment]
Additionally, the detection isn't even a threat. 'WS.Reputation.1' is not a virus. To quote Symantec themselves: 'WS.Reputation.1 is a detection for files that have a low reputation score based on analyzing data from Symantec’s community of users and therefore are likely to be security risks'. Considering your link, it's basically saying 'I don't like this file. I'm going to flip the fuck out and say it's a threat and automatically remove it.'

**Comment by lilmoefow** [comment]
Yeah its not the trust issue its just me bringing it to your attention that it happens.. sorry for the inconvenience and sorry if i offended anyone.

**Comment by fnuecke** [comment]
Oh, no worries, if anything, you offended your computer for running Norton on it ;-)

Seriously, though, I don't know what I could do to avoid this. If there's anyway in the software for you to report it as trusted, that might help. Otherwise, it is what it is. Still, good to know, in case others run into this.

**Comment by LizzyTrickster** [comment]
It's Norton, what do you expect?
Also I don't have any problems with Avast!

**Comment by Vexatos** [comment]
You won't have any problems with any proper antivirus software. That's the thing.
