### ISSUE TITLE
crash with craftbukkit 1.8.3 

### ISSUE THREAD

**Issue by BogusCurry** [MightyPirates/OpenComputers#1058]
I use the version craftbukkit 1.8.3, this version make a error http://paste.md-5.net/visiqutero.vbs The version make over the buildingtool from spigotmc.org I hope that is enough infos for you ;D

**Comment by asiekierka** [comment]
It's not a plugin, it's a mod; it will never work with Bukkit, you need Forge.

**Comment by fnuecke** [comment]
Indeed, you'll need Forge and will have to put it in the `mods` directory, instead.
