### ISSUE TITLE
Shut-down robots show equipped tool twice

### ISSUE THREAD

**Issue by dgelessus** [MightyPirates/OpenComputers#1059]
A powered robot correctly shows only one tool though.

In case it matters, this is on Minecraft 1.8, OC version 1.5.6.13, Forge 11.14.1.1341.
![Double pickaxe](https://cloud.githubusercontent.com/assets/6641959/7106055/163c4a0c-e135-11e4-9230-c0493dc944d3.png)
![Double workbech](https://cloud.githubusercontent.com/assets/6641959/7106054/163c5e98-e135-11e4-87f5-b3cf08dbcce3.png)
![Double torch](https://cloud.githubusercontent.com/assets/6641959/7106053/163ae680-e135-11e4-8b5c-011b07777fbf.png)

**Comment by fnuecke** [comment]
Fixed, thanks for reporting!
