### ISSUE TITLE
fs.mount does not check if the mount path exists

### ISSUE THREAD

**Issue by pingbird** [MightyPirates/OpenComputers#106]
![selection_053](https://f.cloud.github.com/assets/2466461/2021895/a858b244-8845-11e3-9213-03f34d870bea.png)
![selection_054](https://f.cloud.github.com/assets/2466461/2021901/c1499bd8-8845-11e3-8a39-56ceee46cb1d.png)

**Comment by fnuecke** [comment]
That's in 1.1.x, though, isn't it? In 1.2 (devbuilds) that is fixed. Or should be. At least I can't reproduce in the latest devbuild.
