### ISSUE TITLE
Dyeable computers

### ISSUE THREAD

**Issue by Ionaru** [MightyPirates/OpenComputers#1060]
I'd love the ability to dye computer cases and monitors. I use the t2 and t3 computers and the gold/diamond looks really out of place sometimes. My idea is that dyes will change computer cases and monitors into that dye's colour. This could get extended to include robots and other components.

For example:
![2015-04-13_01 55 052](https://cloud.githubusercontent.com/assets/3472373/7108247/7f53134a-e180-11e4-9524-b2ad17fe01fd.png)

**Comment by fnuecke** [comment]
They already are dyable, and have been for a looooong time ;-)
Just right-click them with a dye.

**Comment by Ionaru** [comment]
Boy, do I feel stupid... I've only tried shift-click and assumed it wasn't implemented. xD
