### ISSUE TITLE
Disable mixing memory tiers.

### ISSUE THREAD

**Issue by sulljason** [MightyPirates/OpenComputers#1068]
Real computers are unable to use two types of memory like you can't put a DDR2 module in with a DDR3 one even if the board has slots for both. So for realisms sake it would be nice if in game computers mirrored this behaviour.

**Comment by Vexatos** [comment]
Don't know, this might go a little too far. Not sure though.

**Comment by skyem123** [comment]
This would make OpenComputers less fun for me.

**Comment by magik6k** [comment]
-1, tiers are about capacity, not technology(i.e. memory doesent make computer any faster). Maybe as a config option

**Comment by sulljason** [comment]
As memory got faster in real life the capacities did increase, so I'm not necessarily wrong. But if you guys aren't into the idea that's perfectly fine just putting it out there as an idea.

**Comment by fnuecke** [comment]
Nah, I think this goes against the general theme of _mix all the things_ in OC, and would be hard to visually communicate in the GUI. People keep missing the tier indicators in the slots already, so adding another non-obvious reason for not allowing stuff to go into a slot (or another "silent" boot failure requiring an analyzer) doesn't seem like a good idea. Finally, it'd also easily break existing builds, which isn't worth it, IMHO. All previous breaking changes (I can think of) at least added new functionality or increased flexibility. This is the opposite.
