### ISSUE TITLE
Wireless Network.

### ISSUE THREAD

**Issue by TheRealKANi** [MightyPirates/OpenComputers#107]
Hi..

I have currently made a small wifi setup just for testing a remote-redstone-activated forcefield. ;-) 

This is the setup.
![2014-01-30_12 06 46](https://f.cloud.github.com/assets/1286819/2039287/9f754aca-899e-11e3-8dd0-3f64f9fd8f2b.png)

I setup computer one quite simple.. (Let's us just call them one and two..)
![2014-01-30_12 08 18](https://f.cloud.github.com/assets/1286819/2039308/db15f1ce-899e-11e3-8c8f-f04b93a96295.png)

And simple again with computer two..
![2014-01-30_12 09 27](https://f.cloud.github.com/assets/1286819/2039318/ffacff3c-899e-11e3-9c62-0356e55e0d1f.png)

And before you ask, here is the contents of the basic case's.
Computer one again:
![2014-01-30_12 10 22](https://f.cloud.github.com/assets/1286819/2039330/2226c836-899f-11e3-9e87-21a6a7c14b07.png)

And two:
![2014-01-30_12 10 58](https://f.cloud.github.com/assets/1286819/2039334/32e54044-899f-11e3-927e-91a1f864f354.png)

I have NO errors in the console what-so-ever..
Only the error in computer two.. The sender..
Computer one -Receiver- just waits for the message. 

If i use the cables and create a small LAN, everything works perfectly.. 
What can I be doing wrong..?

**Comment by TheRealKANi** [comment]
BTW.. I have traced down the specific func_72444_a, ~~It's used for distance calculation.~~ --I do not know.
Here is a straight copy/paste from the Vec3.class

``` Java
public Vec3 subtract(Vec3 par1Vec3)
  {
    return this.myVec3LocalPool.getVecFromPool(par1Vec3.xCoord - this.xCoord, par1Vec3.yCoord - this.yCoord, par1Vec3.zCoord - this.zCoord);
  }
```

Hope it helps..

**Comment by pingbird** [comment]
in the config, set logCallbackErrors=true
it should make the proper error show in console

**Comment by fnuecke** [comment]
Got it, thanks for pointing this out. I hate it when they randomly make methods client side only... and hide the annotation above the comments -.-

Edit: OK, I have to rant about this some more. There are almost _no_ client side methods in the vector class, except for `subtract`, `crossProduct` and ... `rotateAroundZ`. But. But! `rotateAroundX` and `rotateAroundY` aren't client side only! Seriously? Seriously!? Why? What the hell is the pattern? -.-
