### ISSUE TITLE
Building newest commit.

### ISSUE THREAD

**Issue by TheRealKANi** [MightyPirates/OpenComputers#108]
Hi.. 
I'm sorry to sound like an ass ;-)
But I have setup forge and installed it as well. 
I ran the Startclient.sh sucessfully, client started perfectly.

But how the h**\* do I compile your mod from git source.
I know how to clone down from git, but where do a place OpenComputers source, and where can I find the compiled jar/zip/whatever ready for mods folder. 
Again sorry to sound like an idiot, but I have searched for any tutorial that explains it just somewhat step by step. And regrettably without any luck.

Thanks in advance.

**Comment by SpiritedDusty** [comment]
If you aren't changing anything and you just want the latest git build then you can use OC's Jenkins build server. http://ci.cil.li/job/OpenComputers/

**Comment by TheRealKANi** [comment]
Well thanks.. ;-)
Didn't know you had Jenkins..
Works perfectly..
