### ISSUE TITLE
OC Wrench should not count as Crowbar

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#1081]
Currently, you are implementing the Railcraft crowbar interface on your Wrench, you should not do that as crowbars are supposed to only be actual crowbars (even if you can only use it to break tracks, it still shouldn't be able to). If you add a wrench, it should only count as a wrench. Similarly, `EventHandlerRailcraft` should not exist, why would you disassemble a Computer using a crowbar? There is a reason Railcraft adds a Crowbar and NOT a wrench.

**Comment by fnuecke** [comment]
> even if you can only use it to break tracks

This is false. You cannot. They are not flagged with the appropriate tool-class. The _only_ thing they can be used for, is to rotate blocks, which, IMHO, is just consequent. Conversely, RC crowbars can only be used to rotate OC blocks.

So _all_ the interaction there is, is for block rotation, aka the part where crowbars don't lose durability. I don't think that is a problem, really.

Taking that into consideration, is there still a reason why you'd like to remove that integration? And if so, what would that be?

**Comment by Vexatos** [comment]
Again, Crowbars should not be able to break OC blocks either, it shouldn't work in either direction, and, again, there is a reason why Railcraft does NOT add a wrench but a Crowbar, it is a completely different tool and should not be usable as a substitute for a wrench.

**Comment by fnuecke** [comment]
> Crowbars should not be able to break OC blocks either

Again, what makes you think they _can_? Where does this assumption come from? Because they **cannot**.  As I said,

> So all the interaction there is, is for block rotation, aka the part where crowbars don't lose durability.

**Comment by Vexatos** [comment]
Meh, nevermind.
