### ISSUE TITLE
GPU foreground color affects rendering of certain blocks

### ISSUE THREAD

**Issue by dgelessus** [MightyPirates/OpenComputers#1083]
Look at the chest and assembler on the left side. These effects disappear when the screen is no longer visible.
![Seems alright](https://cloud.githubusercontent.com/assets/6641959/7215497/8063707c-e5db-11e4-831c-bd7af35ce241.png)
![huh?](https://cloud.githubusercontent.com/assets/6641959/7215498/8066e7fc-e5db-11e4-98a9-747372c011c4.png)
![wat](https://cloud.githubusercontent.com/assets/6641959/7215499/80671c04-e5db-11e4-9d3a-f23e2f0eb2ce.png)
![waat](https://cloud.githubusercontent.com/assets/6641959/7215501/80682c84-e5db-11e4-9639-e96ab910b37f.png)
![all the wat](https://cloud.githubusercontent.com/assets/6641959/7215500/8068040c-e5db-11e4-8cac-c3bb0bda9b1a.png)

Game stats:
Minecraft 1.8
Java 8 Update 40, 64-bit
Forge 11.14.1.1341
OC 1.5.7.17
Graphics thing: Intel HD Graphics 4000

**Comment by fnuecke** [comment]
Should be fixed in [build 109](http://ci.cil.li/job/OpenComputers-dev-MC1.8/), please give that a try and let me know, thanks!

**Comment by dgelessus** [comment]
It works, almost. Most of the time it looks alright, but every now and then the blocks become tinted again for a frame or so.

**Comment by fnuecke** [comment]
Hrm. Will need to double check if the list is executed somewhere else, too... though I don't think it is, odd.

**Comment by dgelessus** [comment]
It seems that the flickers happen (almost) every time OpenOS redraws the cursor. On my wonderful [test BIOS](https://github.com/dgelessus/oc-stuff/blob/master/test_bios.lua) for example I don't have any issues.

Also worth mentioning that this only happens when the cursor is on the last line.

**Comment by fnuecke** [comment]
That indicates it's actually only when the list is re-created. Please try the next build, that should fix it.

**Comment by dgelessus** [comment]
OK, it seems to be working now. Thanks for the quick fix :)

**Comment by fnuecke** [comment]
Thanks for confirming!
