### ISSUE TITLE
Right-clicking server rack will cause a crash

### ISSUE THREAD

**Issue by henrik645** [MightyPirates/OpenComputers#1085]
![2015-04-18_20 35 50](https://cloud.githubusercontent.com/assets/1142482/7216792/d20573e6-e60b-11e4-8ff1-56c36bb2bbaa.png)

When I right click a server rack, minecraft crashes with the following crash report: http://pastebin.com/QWBKbnwq

I am not using any mods other than the latest OpenComputers (MC1.8-1.5.7.17-universal). My Forge version is Forge11.14.1.1375 for Minecraft 1.8.

**Comment by fnuecke** [comment]
Can you reproduce this reliably, or does it happen randomly?
(Because I can't reproduce it.)

This kind of indicates the GUI is rendered by MC before it's initialized, which, if true, will break a ton of other stuff, too...

**Comment by henrik645** [comment]
It happens every time I place down a server rack and right-click it, regardless of how I do it. There is no other block I have found that also causes the problem.

**Comment by fnuecke** [comment]
All right, let me know if [build 113](http://ci.cil.li/job/OpenComputers-dev-MC1.8/) fixes this.

**Comment by henrik645** [comment]
Hmm, still doesn't work. It seems to be a problem with something else than Minecraft as a reinstall didn't fix the problem.

**Comment by fnuecke** [comment]
Could you post the new crashlog? Or is it the exact same?

**Comment by henrik645** [comment]
Here is the new crash log: http://pastebin.com/wQkqMwMG

**Comment by fnuecke** [comment]
So yeah, seems the GUI is drawn before it's initialized. I've been digging through MC's code a bit, and from what I can tell, the _only_ way this could happen, is if some mod intercepts a certain event... if OC is really the only mod present, it should, by all means, be impossible for this to happen...

Is the rack the only block this happens for you with? What about computer cases, for example?

**Comment by henrik645** [comment]
The only mods I have installed (as per the in-game mods list) is Minecraft Coder Pack v9.05, Forge Mod Loader v8.0.76.1375, Minecraft Forge v11.14.1.1375, OpenComputers Core v1.0.0, and OpenComputers v1.5.8.113-dev.

I have not found any other block that also causes the problem.

**Comment by fnuecke** [comment]
Huh, well then... I have no idea how this could happen. I've added a check to avoid rendering completely until that specific GUI is initialized. Please give the next build a try. The alternative possibility now is that the GUI won't be rendered at all...

**Comment by dgelessus** [comment]
Tried this with the same Forge version as @henrik645 and couldn't reproduce this either. My OC dev build is from before any of @fnuecke's fixes. The only differences would be the Java version (mine is 8u40 rather than 8u25) and the graphics card. I also have a few extra mods installed, but that shouldn't make it _less_ likely to crash...

**Comment by fnuecke** [comment]
Thanks for that info. I was running on 1.8.0_05 in my dev-env, so unless that specific version of Java (i.e. u25) does something... very weird, that shouldn't be it, either. I can see now way how the graphics card could influence the actual order in which stuff gets initialized (i.e. the order in which the Java code is executed), so I have to doubt that's it, either. I tested without any other mods, as well with NEI present. So yeah, this is quite mysterious.

**Comment by henrik645** [comment]
I just checked, and just like you said it doesn't render at all now.

Also, it seems that only the server rack causes these problems, and not any other blocks with a GUI.

**Comment by fnuecke** [comment]
Uhh... okay. That means its GUI is _never_ initialized. At all. And that's not something that I have any influence over, AFAIK. So... huh. Could you try updating Java, just to make sure? (Also security updates yada yada)

**Comment by henrik645** [comment]
I updated my Java to the latest version, but it still doesn't work. I have no idea what could be the problem.

**Comment by fnuecke** [comment]
I'm manually initializing the GUI now, if it's being rendered and wasn't already initialized. Note that this is a workaround at best, and stuff like resizing the game window will probably visually break the GUI, meaning you'd have to re-open it.

I frankly do not understand how this can happen in the first place, so I'm afraid that's the best I can do.
