### ISSUE TITLE
Make a robot return home no matter where it is

### ISSUE THREAD

**Issue by ashwinmenezes** [MightyPirates/OpenComputers#1091]
Heyy!
I'm trying to create a program that will make a robot return to its 'home coordinates' no matter where it is in the world. 

What I intend to do is to create a function that moves one step per call. As long as the current coordinates are not equal to the home coordinates, it will keep calling the 'move' function recursively. (I'm still relatively new to this mod, but I've done a bit or programming before... ^^) 

I haven't taken into account about the direction that the robot is facing, Ill keep the direction constant while testing, and will work on that later...
For now, this is my code:

local robot = require("robot")

//these are the 'home coordinates'
x=-23
y=63
z=142

```
function move(
    curX = debug.getX()
    curY = debug.getY()
    curZ = debug.getZ()
    if curX = x and curY = y and curZ = z then
        return
    elseif curX < x then
        robot.forward()
    elseif curX > x then
        robot back()
    elseif curY < y then
        robot.down()
    elseif curY > y then
        robot.up()
    elseif curZ < z then
        robot.left()
    elseif curZ > z then
        robot.right()
    return move
    end
)
```

move()

This probably looks like lousy programming, but I'm still trying to learn Lua, I'm more used to Java programming ^^.
Anyways, my problem is that when I try to run this, it keeps giving me and error saying:

return:7: ')' expected near '='
(return is the name of the script)

Could anyone help correct this error and any other errors in this script please?
Much appreciated!!!
Ash :3

**Comment by ashwinmenezes** [comment]
Also, if you have any ideas as to how to go about programming the part which takes the robot's direction into account, then by all means please share :3

**Comment by dgelessus** [comment]
If you need programming help, it's better to ask in the [Programming](http://oc.cil.li/index.php?/forum/31-programming/) section of the OC forums. The GitHub issue section is for reporting issues with the mod, as the name indicates.

**Comment by ashwinmenezes** [comment]
-_- sorry ill go there right away
xD
sorry!!!
