### ISSUE TITLE
MC 1.8, OC 1.5.7.17 Piston upgrade NoSuchMethodException

### ISSUE THREAD

**Issue by CaitlynMainer** [MightyPirates/OpenComputers#1096]
```
c = require("component")
local sides = require("sides")
print(c.piston.push(sides.front))
```

results in java.lang.NoSuchMethodException: net.minecraft.blocl.BlockPistonBase.i(net.minecraft.world.World, int, int, int, int) reported in the robot's screen, no trace of it in the log.  MC 1.8, Forge 1.8-11.14.1.1375, OC MC1.8-1.5.7.17-universal.
The issue was reported in IRC by KurikAmudnil, I just confirmed it, OC is the only mod loaded in this MC instance.

**Comment by fnuecke** [comment]
Thanks! Fixed in 8a31eba5c31dae9a0c1bceee943fc8ab22a5d81f, there were some uses of reflection still lingering around, which weren't updated to 1.8 properly. Using the AT now, to avoid that in the future.
