### ISSUE TITLE
Crashing in Creative mode on startup

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1099]
Newest forge 1.8 for the version for 1.8 and crashing. No other mods. Java 1.8. Intel HD 4000, Intel core i5 sandy bridge dual core 1.8GHz 4GB R.A.M. fully updated firmware.

**Comment by dgelessus** [comment]
Logs or it didn't happen. ;) If you're using the normal Minecraft launcher, you can right-click the log text field, click Copy All Text, upload it to [Pastebin](http://pastebin.com) and post the link here.

**Comment by ghost** [comment]
http://pastebin.com/jRhEEXhu

**Comment by fnuecke** [comment]
It's funny how, by now, when I see `Could not initialize class li.cil.oc.util.ItemCosts$` I immediately know `Java Version: 1.6.0_65, Apple Inc.` will follow.

Update your Java. That version is broken.
