### ISSUE TITLE
Screen does not turn off on computer shutdown

### ISSUE THREAD

**Issue by civilwargeeky** [MightyPirates/OpenComputers#11]
I'm not sure if this is a bug or not, but all text remains on the screen when it is shut down.
I would imagine that when you turn a computer off it stops outputting to the screen.

**Comment by fnuecke** [comment]
This is actually intentional. Screens are a little like ePaper with backlight: they won't change what they display until told to. Except for a few special cases. If it turns out this is confusing for/annoys a lot of people I may consider changing this, though.
