### ISSUE TITLE
Read/write chat messages using debug card

### ISSUE THREAD

**Issue by MoonlightOwl** [MightyPirates/OpenComputers#1100]
Debug cards is a useful thing for "admin stuff": scripts, world modification e.t.c.
For something like "strong language filter" or custom commands handler, would be nice to be able to read or write messages from game chat.

**Comment by fnuecke** [comment]
Hrm, sure, wouldn't mind that. I have no idea which events / hooks to use for that, though. Maybe @Vexatos has some insight from working on the chatbox block, and could have a look at this / share some insight?

**Comment by Vexatos** [comment]
Well, there is the Creative Chat Box, able to read every message said and able to send messages up to 32767 blocks in radius, not quite sure. Message receiving works interdimensionally, sending does not.

**Comment by fnuecke** [comment]
What about the filtering though? Is there a way to intercept/cancel chat messages to do that?

**Comment by MyNameIsKodos** [comment]
This would be a neat addition to the Creative Chat Box, rather than something added to the Debug Card, since it seems the framework is there.  I'll wait for Vex's response though before I weigh in any more.  I generally don't know how the internals of Computronics work, so I'm probably wrong and sounding like an idiot, as is usually the case =P

**Comment by Vexatos** [comment]
Hmmm, @fnuecke, thanks to FilteredEnvironment, something like .addFilter("badmessage", "finemessage") would work, problem is that it would require processing Lua string Patterns. Another problem would be that the way the chat box is listening to chat messages would have to change. Biggest problem really being the Lua Patterns.

**Comment by Kubuxu** [comment]
It could be also solved by callback system.

**Comment by fnuecke** [comment]
If this gets added to Computronics, let me know and I'll close the issue. Otherwise anyone that wants to have a go at it is invited to; I won't, but PRs are welcome as usual.

**Comment by Vexatos** [comment]
I won't add it to the creative chat box, it doesn't really fit into the block, in my opinion. Better use some actual mod doing this (see [ChitChat by Pahimar](https://github.com/pahimar/ChitChat)).

**Comment by fnuecke** [comment]
Hmm, I suppose that would not be as... customizable, since no custom Lua scripts to handle the filtering, but I agree that a proper mod would make more sense for this, if only from a performance point of view. If nobody wants to take a shot at it anyway, I'll be closing this.

**Comment by CoolCat467** [comment]
Should close issue I think; It's been open for five years now.
