### ISSUE TITLE
persistent mode does not work - debian 76 wheezy 64bit

### ISSUE THREAD

**Issue by Terpo** [MightyPirates/OpenComputers#1102]
http://176.9.155.173/minecraft/fml-server-latest.log

[21:28:45] [Server thread/TRACE] [OpenComputers/OpenComputers]: Could not load native library 'OpenComputersMod-1.5.8.17-native.64.so'.
[21:28:45] [Server thread/WARN] [OpenComputers/OpenComputers]: Unsupported platform, you won't be able to host games with persistent computers.

I'm using OC the first time on my server and was wondering why the persistend lua mode does not work on my root server. All I get ingame is the message that the native lua libraries could not be loaded.

**Comment by Kubuxu** [comment]
In MC's folder you should find `OpenComputersMod-1.5.8.17-native.64.so` can you run for example `ldd OpenComputersMod-1.5.8.17-native.64.so`. It is blind shot bit might help.

**Comment by Terpo** [comment]
On my client (windows 7 64bit) it works well. I can't find "OpenComputersMod-1.5.8.17-native.64.so" or something similar on the server. To make sure it was not a copy paste problem, I deleted the whole configs around open computers and the "OpenComputersMod-1.5.8.17-native.64.dll" on the server which it created on the windows side. But still after deleting everything, it does not create the "OpenComputersMod-1.5.8.17-native.64.so"

**Comment by Kubuxu** [comment]
It can be also in `/tmp/`. Also check whether user running the server have write access in server directory and `tmp`.

**Comment by Terpo** [comment]
The user has write access to the /tmp folder, but there is also nothing OC related.

**Comment by Kubuxu** [comment]
And the server folder? Just checking.

**Comment by Terpo** [comment]
No, I checked the server folder.

**Comment by fnuecke** [comment]
I just got around to grabbing the live CD of Debian 7.6, grabbed Forge and OC, and it works just fine in the VM. So I'm pretty sure this is some rights issue. You could try setting the config option `logFullNativeLibLoadErrors` to `true`, see what that prints. Also, by default, OC tries to extract the lib into the server directory. You can try making it use the tmp directory instead by setting `nativeInTmpDir` to `true`.

**Comment by Terpo** [comment]
first: http://pastebin.com/jerFVjTc
Operation not permitted .... seems you are right

second with: nativeInTmpDir true
[18:18:09] [Server thread/INFO] [OpenComputers/OpenComputers]: Initializing OpenComputers API.
[18:18:09] [Server thread/INFO] [OpenComputers/OpenComputers]: Found a compatible native library: 'OpenComputersMod-1.5.8.17-native.64.so'.
[18:18:09] [Server thread/INFO] [OpenComputers/OpenComputers]: Done with pre init phase.

Works fine now :)

**Comment by fnuecke** [comment]
Great :-)

**Comment by Kubuxu** [comment]
@Terpo so how did you finally fixed it. Just for people with similar problem.

**Comment by Vexatos** [comment]
@Kubuxu Apparently with setting `nativeInTmpDir` to `true`.
