### ISSUE TITLE
Add support for BluePower's bundled redstone

### ISSUE THREAD

**Issue by AuoroP** [MightyPirates/OpenComputers#1103]
I dump'd (http://www.luafaq.org/#T1.15) the redstone component and I've got to agree it is nil:

{ ["getWirelessOutput"] = { ["address"] = 5ec559d3-7bb6-4cb2-902e-1e696c737b68,["name"] = getWirelessOutput,} ,["getWirelessFrequency"] = { ["address"] = 5ec559d3-7bb6-4cb2-902e-1e696c737b68,["name"] = getWirelessFrequency,} ,["type"] = redstone,["getOutput"] = { ["address"] = 5ec559d3-7bb6-4cb2-902e-1e696c737b68,["name"] = getOutput,} ,["address"] = 5ec559d3-7bb6-4cb2-902e-1e696c737b68,["setWakeThreshold"] = { ["address"] = 5ec559d3-7bb6-4cb2-902e-1e696c737b68,["name"] = setWakeThreshold,} ,["getInput"] = { ["address"] = 5ec559d3-7bb6-4cb2-902e-1e696c737b68,["name"] = getInput,} ,["getWakeThreshold"] = { ["address"] = 5ec559d3-7bb6-4cb2-902e-1e696c737b68,["name"] = getWakeThreshold,} ,["setWirelessFrequency"] = { ["address"] = 5ec559d3-7bb6-4cb2-902e-1e696c737b68,["name"] = setWirelessFrequency,} ,["slot"] = 1,["setWirelessOutput"] = { ["address"] = 5ec559d3-7bb6-4cb2-902e-1e696c737b68,["name"] = setWirelessOutput,} ,["getWirelessInput"] = { ["address"] = 5ec559d3-7bb6-4cb2-902e-1e696c737b68,["name"] = getWirelessInput,} ,["setOutput"] = { ["address"] = 5ec559d3-7bb6-4cb2-902e-1e696c737b68,["name"] = setOutput,} ,} 

I'm using Java 7 final update on Windows 7 x64; FTB's third party pack Pathfinder recommended (1.03) with OpenComputers updated to OpenComputers-MC1.7.10-1.5.7.564-dev-universal and RFTools updated to rftools-2.72 and I've added NotEnoughResources-1.7.10-0.1.0.96.jar.

**Comment by fnuecke** [comment]
What bundled redstone mod are you using? Project Red, Redlogic, MFR? Is this a redstone block or card? If it's a card, what device is it in (case, server)?

**Comment by AuoroP** [comment]
I'm pretty sure the only bundled cables in Pathfinder are from BluePower-1.7.10-0.2.892-universal.

**Comment by fnuecke** [comment]
Well, that'd explain it. I'll look into adding support for BluePower's API.

**Comment by AuoroP** [comment]
Thanks for the quick reply and good luck!

**Comment by AuoroP** [comment]
Thanks!
