### ISSUE TITLE
Calling various functions in computer api with no value causes a NPE

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#1104]
It's a captured and handled error, but a NPE none the less:

computer.pushSignal
computer.addUser
computer.removeUser

(also addUser doesn't seem to error, it'll return nil, "Java.lang.NullPointerException" or nil, "bad argument 1 (string expected, got blah)")

**Comment by fnuecke** [comment]
That... actually looks like it might be a bug in JNLua. It tries to get the type at the top of the stack (for the `x expected, got y` message), but if the stack is empty it gets `null` for the type, but then blindly `toString`s it. Will probably fix that when I get around to updating the natives to 5.2.4.
