### ISSUE TITLE
[Bug] New Forge will break ASM

### ISSUE THREAD

**Issue by aschmois** [MightyPirates/OpenComputers#1108]
Recently there were issues with mods using Mixin Framework that were conflicting. There was a patch to Forge that was merged today that breaks the SimpleComponent (my guess because ASM is now excluded) someone that knows a little better should take a look at it.

Merge in question: https://github.com/MinecraftForge/FML/pull/650

What will probably need to happen is that Mixin will need to be implemented to work with all other ASM mods. 

Note: there is no official build with this new merge but it is coming, and it will break ASM loading.

**Comment by StoneLegion** [comment]
I tested this with in fact forge 1395 with just the patch. Was using Forge 1395 before without the patch and everything was working fine. Looks like ASM is the past now. The build should be showing up anytime live.

**Comment by Kubuxu** [comment]
@aschmois If you read this patch carefully you will see that the only thing changed was exclusion from Class Transforming classes of ASM Framework which is being used by everyone. I have no idea how this could break something.

**Comment by aschmois** [comment]
Well, with the patch installed, SimpleComponent fails to load. Let me see if I can find some logs.

**Comment by StoneLegion** [comment]
I also tried searching anything SimpleComponent related with spaces and without and can't find anything in the latest forge log.

**Comment by aschmois** [comment]
Ignore my stupid, unrelated issue.
