### ISSUE TITLE
Getting access to memory crafted with servers.

### ISSUE THREAD

**Issue by sulljason** [MightyPirates/OpenComputers#1109]
The servers take memory modules to craft and as far as I could tell I couldn't use the memory included with the recipe. This really bummed me out with my pretty expensive tier 3 server, especially since I'll probably be working with large sets of data. It would be cool if we could use the memory included in the recipe. :)

**Comment by Kubuxu** [comment]
You can right click the server to add more memory.

**Comment by sulljason** [comment]
I know... But when I call totalMemory() I don't see the 3.5 module for crafting included in the total of available working memory. And if you try to boot without any of the additional DIMMs filled it says to add memory when it should already have  what the 3.5 module provides because it was needed for crafting, so I was expecting to have that memory be usable.

**Comment by Vexatos** [comment]
@sulljason Remember that the recipe may be changed in the config file, so it's virtually impossible to include that.

**Comment by dgelessus** [comment]
@Vexatos Maybe add a config setting for how much built-in memory the servers have? That way players can adjust it according to their recipes and RAM sizes, and it can be disabled entirely if necessary.

**Comment by Vexatos** [comment]
@dgelessus I don't think that's a good idea. It's just a crafting recipe, it's got nothing to do with the internals of a server. There is literally no way to make it work that would make any sense. The entire point of computers and servers is being modular, and suddenly you have servers with RAM you can't extract?

**Comment by gjgfuj** [comment]
Yeah, its just a component required to craft the computer, if you feel you
don't wanna put inaccessible ram into your computer, just change the recipe.

**Comment by sulljason** [comment]
Forgot you could change the recipes in the config. It makes sense not to include it then even if it kind of sucks.
