### ISSUE TITLE
Non-blocking computer.beep()

### ISSUE THREAD

**Issue by SolraBizna** [MightyPirates/OpenComputers#1112]
I'm working on... something semi-secret. It would greatly benefit from a way to beep without blocking the whole machine. Currently, `computer.beep()` blocks until the beep is finished.

Two possible approaches:
- Make `computer.beep()` work differently somehow; for instance, blocking only until the _previous_ beep has concluded.
- Add an API that would let an Architecture module emit its own beeps, requiring the Architecture module to do whatever bookkeeping/throttling makes sense for that Architecture.

I, personally, would prefer the second method as it would grant a great deal of flexibility.

Flood of other issues coming soon, after the semi-secret thing is released :)

**Comment by Vexatos** [comment]
Check out the Computronics Beep Card. It does up to 8 beeps at the same time with different lengths, also the calls are non-blocking. For looking for how to use it, you may want to check out my [Song API](https://github.com/OpenPrograms/Vexatos-Programs/blob/master/song/song.lua) which allows playing whole songs with this card (See the comment in the first lines for how to use it if you are interested).

**Comment by fnuecke** [comment]
For now you can work around this by using OC's internal `li.cil.oc.server.PacketSender.sendSound` methods. I guess I could add them to the API somehow. Either globally or via the `Machine` interface... the former obviously being more flexible, but needing some kind of `Util` API thinger, which I kind of dislike, because that'll attract clutter like a supermagnet :P

**Comment by SolraBizna** [comment]
Vexatos: The Beep Card is in an addon mod, though, and I'd prefer a solution that doesn't require one. _However_, now that I know it exists, I won't design polyphonic sound into my Architecture; and I'll be adding optional support for the Beep Card (for improved sound quality) to the semi-secret thing... assuming, that is, I can _find_ a copy of Computronics, as the website seems to be down...

fnuecke: It makes more sense conceptually to put it in the Machine interface, I think. Meanwhile, I'll try using `PacketSender.sendSound`.

**Comment by fnuecke** [comment]
Yeah, the old Computronics page has been dead for a while now, but a lot of stuff still links there.
Current one is http://wiki.vex.tty.sh/

**Comment by Vexatos** [comment]
I changed the URL everywhere I have acess to, sorry for the inconveience...

If you are interested, [this](https://github.com/asiekierka/Computronics/blob/master/src/main/java/pl/asie/computronics/oc/DriverCardSound.java#L129-L162) is how Computronics handles beeping.

**Comment by igorkll** [comment]
use, computer.beep("------") LOL))
