### ISSUE TITLE
Save Killer: BluePower Bundled Cable

### ISSUE THREAD

**Issue by AuoroP** [MightyPirates/OpenComputers#1114]
Placing BluePower bundled cable next to my OpenComputer crashes the world so hard reloading cannot recover: http://pastebin.com/hANUda7s

**Comment by fnuecke** [comment]
Thanks. Try updating BluePower, they apparently did a breaking API change. I'll add a check to avoid loading the BP integration if the installed version is too old.

**Comment by AuoroP** [comment]
I will. Thanks!
