### ISSUE TITLE
Strange crash with key bindings overhaul 1.1

### ISSUE THREAD

**Issue by Elix-x** [MightyPirates/OpenComputers#1115]
Okay, so:
I'm main creator of key bindings overhaul, and while testing new 1.1 version found that it's in some strange way incompatible with open computers...
First 4 lines of crash report, if you are interested:

``` java
java.lang.NullPointerException: Unexpected error
    at code.elix_x.coremods.keysoverhaul.keys.InputHandler.isKeyDown(InputHandler.java:35)
    at code.elix_x.coremods.keysoverhaul.keys.KeyBindingHandler$AdvancedKeybinding.update(KeyBindingHandler.java:163)
    at code.elix_x.coremods.keysoverhaul.keys.KeyBindingHandler.updateKeys(KeyBindingHandler.java:24)
    at code.elix_x.coremods.keysoverhaul.keys.events.ClientTickEvent.onTick(ClientTickEvent.java:19)
```

Meanwhile, on this line is method retrieving press value (boolean) from integer (key id), and somehow with your mod installed, it cathes NullPointerException, or via integer being null (impossible), or via value not found being casted (strange, all keys of keyboard and mouse are scanned)...

If you are interested, InputHandler:

``` java
public class InputHandler {

    public static IntHashMap keyStates = new IntHashMap();

    public static void updateStates() {
        for(int i = 0; i < Keyboard.getKeyCount(); i++){
            keyStates.addKey(i, Keyboard.isKeyDown(i));
        }
        for(int i = 0; i < Mouse.getButtonCount(); i++){
            keyStates.addKey(i - 100, Mouse.isButtonDown(i));
        }
    }

    public static boolean isKeyDown(Integer i) {
        return (Boolean) keyStates.lookup(i);
    }
}
```

Oh, and also: you cannot download this version, it is not released yet...

**Comment by Vexatos** [comment]
... this is not ComputerCraft. Do you mean OpenComputers?

**Comment by Elix-x** [comment]
Yes, sorry miswrote, i mean open computers

EDIT: updated comment, changed /^\

**Comment by fnuecke** [comment]
OC only has [two keybinds](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.8/src/main/scala/li/cil/oc/client/KeyBindings.scala#L38-L40), and they're [properly registered in init](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.8/src/main/scala/li/cil/oc/client/Proxy.scala#L73-L74). So I don't think I'm doing anything wrong? No clue what's going wrong there. Have you tried setting a breakpoint to step through that code, see what's actually `null` in there and all that?

**Comment by Kubuxu** [comment]
There are two places your code can throw NPE:
- During unboxing of parameter `i`
- During unboxing of return value.

Check them and then follow step by step.

**Comment by Elix-x** [comment]
I will check that, but i'm interested: where from this problem comes? Because KBO works fine alone or with any other mod that add new key bindings, but problem occurs when i install open computers... 2 these mods alone gave me this crash (while one or other of them separetly or with others don't), that's why i'm here...

**Comment by fnuecke** [comment]
Dunno, maybe it's a duplicate binding (as in same key used for different functions) that doesn't occur otherwise?

**Comment by Elix-x** [comment]
Nope, for sure no, updateStates is called each tick, and updates all pressing values. Then boolean is retrieved from map by each key to check if it is pressed, but boolean is still there. That's part of mod -  being able to bind to one key/key combo multiple uses...

**Comment by Keridos** [comment]
@elix-x I saw your mod is listed under CC License, would you mind to put the source up here on github so I could take a look at it, maybe help a bit with developing?

**Comment by Elix-x** [comment]
Ok, i'll upload it...

**Comment by Elix-x** [comment]
Okay, i changed the code and it seems to be working now... Still don't now how this was occuring and how gl managed to deal with it...
