### ISSUE TITLE
Crash when searching in NotEnoughItems

### ISSUE THREAD

**Issue by lischetzke** [MightyPirates/OpenComputers#1116]
My minecraft crashes all the time I would list all the items from OpenComputers. Also when I go to the OpenComputers Tab in creative. 

Minecraft 1.8 Forge 11.14.1.1334
OpenComputers 1.5.9.22-RC.1

Crash report: http://pastebin.com/eNnXs9da

Hope it will be fixed.

**Comment by fnuecke** [comment]
Can't reproduce, neither in dev-env, nor obf, single player nor multiplayer, using the exact same versions.

Please verify this also happens if OC and NEI are the only mods present, because if it doesn't, it's some other mod interfering.

**Comment by lischetzke** [comment]
I tested it now with only CodeChickenCore, NEI and OC and you're right. 
I found the mod which makes problems: ShaderMod
