### ISSUE TITLE
AE Controller getCraftables bug

### ISSUE THREAD

**Issue by Keridos** [MightyPirates/OpenComputers#1117]
On appliedenergistics2-rv2-beta-30 and OpenComputers-MC1.7.10-1.5.8.17-universal the object that is given back when you .request a crafting job does not list isDone() == true when the job actually finishes with in the AE system.

**Comment by fnuecke** [comment]
Hmm, works fine for me, though I did test with beta-31 and OC latest (1.5.9-rc.1). Could you try updating?

**Comment by Keridos** [comment]
I will try that.
