### ISSUE TITLE
Redstone-In-Motion carriage controller return values

### ISSUE THREAD

**Issue by Mordenkainen** [MightyPirates/OpenComputers#112]
I'm seeing some issues with interacting with the carriage controller.

Using the following program:

```
local component = require("component")
local event = require("event")
local car = component.carriage

car.move("north")
local result, reason = event.pull("carriage_moved")
if not result then
  print(reason)
else
  print("pass")
end
```

If the carriage can move, the program never completes. It appears to hang waiting for the event and never gets it.
If the carriage can not move because it is obstructed, the program does complete, but reports "pass". It appears in this case, that the event does get thrown, but does not report the failure. Printing the "reason" in this case prints the address of the carriage.

If car.move is changed to car.simulate, then the program completes in all cases, but always reports "pass", even if the simulation should fail.

**Comment by fnuecke** [comment]
Interesting. Seems like I'll have to delay the signal a bit. Thanks for reporting!

Oh, regarding the evaluation: it's wrong. I derped the wiki entry. That `event.pull` gives the following: signalName, address, result, reason[, x, y, z]. So it should be:
`local _, _, result, reason = event.pull("carriage_moved")`
