### ISSUE TITLE
New version ideas

### ISSUE THREAD

**Issue by AMIDIBOSS** [MightyPirates/OpenComputers#1120]
hi, i'm Adrian. Can you include my ideas in new version? I'll be so Happy!
1. Computers components are making heat, more components - more heat.
Too high temperature brokes the components. Heat can be reduced by adding case fans.
But more fans - more power consumcion
2. Add a quiet, fast flash disks, such as SSD
3. Add an case or computer type with a 2 CPUs or even 4 CPUs!
4. Add a external copnents case - for more disks, ram, expansion cards.

**Comment by rashdanml** [comment]
1. See #1043 
2. 
3. Server Racks can hold up to 4 servers, each with 1 CPU. The rack itself, if properly programmed, should be able to do parallel processing. A server board being able to hold more than 1 CPU would be interesting, albeit not completely necessary. 
4. The RAID exists for storage. Some expansion cards already have external equivalents (network card = switch, wireless network = access point, redstone card = redstone i/o block, etc). External memory sounds a bit silly, personally.

**Comment by fnuecke** [comment]
1. No. Also see #1043 
2. Ehh, nah. You can use a raid and place it far away, if the access sound bothers you.
3. Something like this has been suggested before; I'd rather not. Reason one, multitasking, simply doesn't make much sense for how things are implemented, reason two, speed, is something I may, if at all, allow bumping via component buses.
4. Short version: nope. Long version: heeeeeeell nope.

Edit: bloody ninjas everywhere!

**Comment by fnuecke** [comment]
Even longer version for 4: for cards and memory this would completely break any real or perceived balance. Utterly. Also, slight correction to @rashdanml's comment: redstone block, yes, absolutely an equivalent to a tier 1.5 redstone card, switch and access points not so much, because you'll still need a network card to send and receive network messages.

**Comment by AMIDIBOSS** [comment]
Yeah, Now when i think about it I see my ideas where bad, anyway I don't play minecraft anymore :)

**Comment by Vexatos** [comment]
~~Computronics will have SSDs in the next version.~~
