### ISSUE TITLE
Suggestion: double buffering for screens (GPU), method flip()

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#1123]
GPU may have a setting to be in double buffering or not. When they are in double buffering, they doesn't update the screen attached to them until the method flip() are called, to avoid flash and keep screens fluid, because GPU have limited action at a time.

New methods suggested:
- isDoubleBuffered()
- setDoubleBuffered(bool: active)
- flip()

Without double buffering, each output are directly transmitted to the screen. With double buffering, data are stored in the GPU buffer and sent to the screen only when flip() is called. Another idea can be that GPU can bind another screen just after flip() and do flip again to make the second screen displays exactly what the first one displays. Actually the double buffering mode would works on the GPU buffer instead of the screen directly.

**Comment by fnuecke** [comment]
See #779 and referenced/referencing issues.
