### ISSUE TITLE
Suggestion: search for screens directly next to the computer first

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#1124]
In OpenOS, my suggestion would be make that OpenOS searches for screen directly next to it before to search on the rest of the network, as a priority. Like that, if you have a computer with many screens, and only one directly next the computer case, you will be sure that it will be selected. But if you have more than one screen next to the computer case, you cannot make sure which one will be selected, and if no screen is directly next to the computer case, the screen selection acts as usual. Screens with keyboard should have priority, but I think it's already the case.

**Comment by Vexatos** [comment]
This is not possible. All components are added to the network at the same time, no matter where they are.

**Comment by fnuecke** [comment]
As Vexatos said, this is not possible. The Lua side of things has no concept of "location" for components. On the Java side, sure, there are world coordinates but that's not really what you want, you'd want "network distance" for this to make sense. And that's much too inefficient, I'm afraid. The way the networks are currently stored is optimized for random access.
