### ISSUE TITLE
Suggestion: portable computers

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#1125]
Another suggestion, yes I know I've made a lot this day. Sorry if this one is already submitted.

Portable computers would acts like tablets but can be placed in the world as a block, and then receive power from cables directly next to them. When they are item, they acts exactly like tablets, and when they are placed in the world, they acts like a screen, because their content is not accessible, only modifiable if dissasembled. Portables tier 2 would be able to read floppy disk too, and maybe why not tier 3 would be able to detect, with two new events (or signal if you prefer that name), when they are picked up and placed. All tiers should be able to know when they are plugged on power or not though. When placed, they're also able to interact with the rest of the network they are plugged to. ^^

**Comment by ExDomino** [comment]
Ah, I forgot to say, a portable computer can join a network only if next to a cable, so not next to a screen or a computer case or any other component, for security reasons, and will not be able to control other computer with the computer API (for example close them), even if their address is known. Same thing for others computers on the network about portable computers, they cannot control portables via computer API. A config in the setting could be enable that though.

**Comment by Vexatos** [comment]
Sounds quite useless to me...

**Comment by SaphireLattice** [comment]
Hm, reminds me of all those "suggestions" about 1-in-all computers.

**Comment by gjgfuj** [comment]
Yayyyyyyyyy, (if you want that use computer craft or robots.)

**Comment by fnuecke** [comment]
Eh, I'd like to keep the distinction between portable and stationary devices. Also, [insert a bunch of technical reasons here].
