### ISSUE TITLE
Suggestion: global network card

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#1129]
The idea is a global network card that allows computers to send network messages to all computers (and robots and tablets) that also have the card, even between dimensions. All other things about normal and wireless network cards are the same, for example ports that can be opened and closed. That allows creating a kind of in-game "internet". That card would be a tier 3 card and consume more power per message sent than the wireless card.

**Comment by Vexatos** [comment]
That's... quite powerful, it'd pretty much completely remove the need for repeater setups, linked cards and alike. Especially linked cards would be easily replaced by this. If this gets added, it should be creative-mode-only so server admins would have to give them to the players, in my o(pi)nion.

**Comment by gjgfuj** [comment]
Yeah, the internet IRL requires infrastructure to work, and isn't just
magic. The idea is for you to build the internet yourself.

**Comment by fnuecke** [comment]
Yeah, this is pretty much linked cards in boring ;-) Use those to connect remote networks, then build a normal local network using network cards, wireless network cards, switches and access points. Have the machine with the linked card act as a gateway. Et voila, internet. FWIW, a couple of people have worked on transparent networking libs to achieve this already; if you don't feel like implementing this yourself, check the forums or ask on IRC.

**Comment by ExDomino** [comment]
Is it possible to have them for creative computers then? As a tier 3 card. It would be really useful.

**Comment by LizzyTrickster** [comment]
Spawn a linked card in creative and it gets the "creative" channel. Good luck with packet routing though

**Comment by ExDomino** [comment]
Ah, it's already the case then. Ok thanks.
