### ISSUE TITLE
Suggestion: colored cables (for different networks)

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#1130]
In order to pass two cables from two separate network one next to each other without have them merged into the same network, the cables could be colored with different colors.

**Comment by gjgfuj** [comment]
They already can be, right click on them with dye......

**Comment by LizzyTrickster** [comment]
This has been in since OC1.4

**Comment by Techokami** [comment]
This. Use a dye on the cable in the world. Default color connects to all.

Sent from my Windows Phone

**Comment by ExDomino** [comment]
Lol, really sorry. XD
