### ISSUE TITLE
Doesn't Support Python #92

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1131]
Still writing support python on OpenComputers (Last update @ 2015-05-05)
It is continued work from #92

https://github.com/EcmaXp/mpoc
https://github.com/EcmaXp/micropython
- Multi instance in one process: IMPOSSIBLE (while lua can do that)
- Limit Execute CPU / Memory are finish!
- Pauseable VM: 99%
  - Now micropython vm can stop everywhere. (by hard, soft, safe limiting)
  - TODO: Check soft pause still work on exception handling.
  - in Eris Lua, vm can stop only coroutine.yield point
    in MicroPython, vm can stop any time if special method are not called (eg. `__getitem__`)
    (but exc_limit and safe_limit will help us.)
- Persist program: 10% (just use stackless version of micropython!)
  - Not yet starting.
  - persist microthread and code_state and fun_bc and modules and etc thing.
  - when i can finish them. almost work are finish.
- Micro thread: 80% (or write MC <-> Python on C)
  - Write microthread management code. [OK]
  - Just switch if paused. [OK]
  - Easy write MC <-> Python support?
- MC <-> Python: 3%
- Python own library: 12% (very simple bios + microthread)
  - simple bios (i will extend)
  - umsgpack (like json, currently basic error handling included and packing by buffer)
  - microthread (python's coroutine with limit cpu and access object.)
- Make simple main program with pass almost testcase in micropython
- Fallback system: Jython?
- Currently i can't develop java side because i don't have permission to play game. (Army)

When i finish this work, i will request the apply patch.

**Comment by fnuecke** [comment]
Once you're able to work on the Java side again, please make sure to implement it as an addon Mod first, like the [Javascript](http://oc.cil.li/index.php?/topic/455-javascript-for-open-computers/) and [ARM](http://oc.cil.li/index.php?/topic/572-mc1710oc15xarm-architecture-extremely-alpha/) architectures people have worked on. If it proves stable over time, I _may_ consider accepting a PR into OC itself, but I won't promise that. My main concern being that I won't be able to maintain it, i.e. can't guarantee fixes in a timely fashion, so it'd make more sense to have it in a separate project.

Also, while I really do appreciate the progress update, I don't think OC's issue tracker is quite the right place. Please consider making a thread on the [forums](http://oc.cil.li/index.php?/index). Until you have a working alpha/beta, prefer posting it to the Lounge, after that, by all means, post it to the addon showcase!

Good luck with getting this to work, quite a few people would be very happy for this, I'm sure!
