### ISSUE TITLE
AE2 Spatial integration

### ISSUE THREAD

**Issue by SaphireLattice** [MightyPirates/OpenComputers#1132]
What is said in description. It isn't possible to move OC blocks (at least screen,charger and computer case) using AE2's Spatial with latest AE2 and OC (AE2 is rc2.beta-33 which is nearly latest but close enough and OC is dev build 618).

**Comment by fnuecke** [comment]
Yes, I had a look at this some time ago, and computer states didn't handle the quick save-load across dimensions very well. I'll give it another go some time.

**Comment by LizzyTrickster** [comment]
That's probably because of AE2 sanity checks to make sure it doesn't break
stuff by moving it

**Comment by LizzyTrickster** [comment]
Whoops didn't see @fnuecke's reply

**Comment by fnuecke** [comment]
Done as of eee133dfede762cee5a7fe7f4a58d5c5cf4646bf.
