### ISSUE TITLE
ME regulating Inventory

### ISSUE THREAD

**Issue by Keridos** [MightyPirates/OpenComputers#1133]
Is there a proper way to automate regulating an inventory (setting to put item x with stacksize n in slot y of an inventory) with the ME drivers or at least with opencomputers somehow?

**Comment by fnuecke** [comment]
Yes, using an export bus that's "disabled" (via redstone), and an inventory controller. Use the controller to check the inventory contents, use the export buses `exportIntoSlot` callback (also via adapter) to keep inventory stocked as desired.

For future reference, please prefer using the forum for questions, thanks!

**Comment by Keridos** [comment]
OK thanks, sorry for the inconvenience. Will use the forums in the future.
