### ISSUE TITLE
Bundled cables

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#1134]
Add some kind of "bundled" network cable. Allows connecting multiple subnetworks over a longer distance using only one cable. Subnetworks can be merged/split from the bundle using normal, colored cables. Basically like most bundled redstone cabling works.

Bundled cables will _not_ connect to normal machines. They will connect to servers, though, and servers will get a new configuration option, allowing to specify the _color_ a server is connected to. My current idea is to expand the "side" list with the colors, so servers can connect to either a single side, or a color - not sure if connecting normal colored cables will then allow connecting them from multiple sides, or just via bundled cables... we'll see.

This will be a good bit of work, in particular the rendering side of things. Will need to pull out some common functionality from the existing cables and all that. No ETA.

**Comment by dgelessus** [comment]
Since microcontrollers seem to be (partially) meant as advanced programmable switches, should they be allowed to access _all_ colors from a bundled cable? Or maybe only tier 2 microcontrollers?

**Comment by fnuecke** [comment]
Hrm, I suppose. And allow them to programmatically select what colors to "output" to, similar to the way sides can be selected now.

**Comment by magik6k** [comment]
Maybe use modems that'd use normal cables to send wrapped data from subnetworks and extract it on other end. They should have some sort of channel selectable.

**Comment by jeffreykog** [comment]
Maybe another option is implementing the way vlans work in real-life networking into OC. This will also add a more expensive internet card that can send vlan tagged packets over the cables, so it can connect to multiple networks.

Maybe a bit too complicated, but it would be cool if it could work.

**Comment by HiTECNOLOGYs** [comment]
@jk-5 you could simply implement VLANs on top of current networking stack using custom BIOS and some programming magic to glue it together. There's no need for adding "hardware" support for them (not that I'd mind it, though, as having stuff built-in and standardized is usually good). However, running into component limit on one cable is a problem which VLANs don't solve.

**Comment by Kubuxu** [comment]
If you want to relay only messages then there are switches and network program which is already floppy in OC (if you ask Magik6k nicely, he might implement vlan protocol into it) but it can be created as separate service. If you want to access component from other network then use component-over-network program. I think that someone already created one.

Also VLAN can be created as separate service from network. Just depending on it.

**Comment by n00b7** [comment]
maybe a command to pull which color the bundled cable like:
bundledCable.pull(color)

**Comment by magik6k** [comment]
Colored cables might play nicely with server racks from #1323 if it would extract the rails. Some sort of cable rack to avoid mess when connecting 2-3 bundled cables would be nice too.

**Comment by setsunafseiei** [comment]
Why not bundle cables will act like in Project RED? 
This won't create a mess or displaying much of cable or you can just hide it with Forge Multiblock, but this will be helpful in power distribution from far.
You cannot connect a bundle cable to Computer Case. Bundle cable will treat red cable and blue cable and other cables as a one block type for no much space will be needed

**Comment by setsunafseiei** [comment]
This is my reason why using bundle cables are useful

![image](https://cloud.githubusercontent.com/assets/18274831/14307536/732a71f6-fc02-11e5-8e97-7d261abe1cd1.png)

![image](https://cloud.githubusercontent.com/assets/18274831/14307539/7632f940-fc02-11e5-8af1-ec4e7458b7d9.png)

Too much SPACE

**Comment by Shazuli** [comment]
Umm, this was accepted as a feature accept over three years ago. Will this ever be implemented or has the idea died?
