### ISSUE TITLE
Automatically enable peaceful recipes when on peaceful difficulty

### ISSUE THREAD

**Issue by dgelessus** [MightyPirates/OpenComputers#1136]
This seems to be possible - Extra Utilities allows an extra recipe for the [Watering Can](http://ftbwiki.org/Watering_Can) based on difficulty. Would this be possible for OC's peaceful recipe set as well?

**Comment by gjgfuj** [comment]
Extra utilities does it by registering both recipes and having a recipe
handler that checks the difficulty. Both therefore show up in nei. OC
registers the recipe set that's given however. So it wouldn't be possible
without some reasonably sized rewrites and changes.

**Comment by fnuecke** [comment]
Yep, not really doable with the current implementation. As things currently are, all recipes (except for "recrafting" stuff, like swapping EEPROMs) are simply pulled from a single source - the `user.recipes` file. Whether the recipes in there are peaceful friendly or not wholly depends on the includes and defines in there. So it's not possible to dynamically switch those recipes.

Adding a `user-peaceful.recipes` might be an option to allow providing two sets that get chosen from in a recipe handler based on current difficulty, I guess. Just not quite sure I like that implementation.

**Comment by fnuecke** [comment]
I'm afraid the effort and code changes (thus potential instability) for this doesn't quite justify the number of people this would effect, sorry.
