### ISSUE TITLE
Server Mount Micro Controller

### ISSUE THREAD

**Issue by tlf30** [MightyPirates/OpenComputers#1138]
Hello,
I was thinking that we already have server racks that we can put servers in, and we have tier two micro controllers that can can act as a form of switch, it would be really cool to have them (or a modified recipe of them) mountable in the server racks.

Just a thought,
Trevor

**Comment by fnuecke** [comment]
I don't see a reasonable and logical way of doing this. I also don't quite see the point in it?
If you can give a few good use-cases of how this would be an improvement over servers / standalone MCUs I might reopen this, but like this it doesn't sound like something that'd make a whole lot sense.

**Comment by tlf30** [comment]
Mostly it would be convenient considering I have several situations where I have a server rack with only one server in it and a microcontroller sitting next to it. It would be nice to only need to take up one block. Also, because the tier two microcontroller can select an output side with multiple networking cards, it could act as a way to 'override' the switching mechanism in the server rack. It would also give the server rack a use other then just housing servers. 

I am not saying to modify the functionality of the microcontroller, only to be able to rack mount it.

**Comment by Vexatos** [comment]
Isn't the point of OpenComputers to _not_ have everything in one block mostly?

**Comment by fnuecke** [comment]
I understand the desire for compact builds, but in this case I don't really think it makes much sense, sorry. FWIW, you can use multiple servers and internal switching mode to control on which side network messages are sent, so you might not even need an MCU.
