### ISSUE TITLE
The left and right block textures on a monitor is reversed on the east face

### ISSUE THREAD

**Issue by Cisien** [MightyPirates/OpenComputers#114]
http://paste.cisien.com/f/70d99ad9.png

This screen shot shows the front of the monitor on the bottom, and the back of the monitor on the top.

Forge 1024
OC 2.0.0-pre1

**Comment by fnuecke** [comment]
It's a bug in Minecraft itself: https://bugs.mojang.com/browse/MC-37106
Won't be doing anything about it, it's just a matter of time until Forge updates ;-)

I'll keep this open until then, though, to avoid people reporting duplicates.
