### ISSUE TITLE
Computer Case doesn't accept energy directly without a power converter

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#1141]
The computer case doesn't accept energy directly from an EU cable. It needs a power converter between the cable and itself. But the wiki indicates that computer cases can take the power directly.

**Comment by fnuecke** [comment]
Works fine for me. What versions of OC and IC2 are you using? Which cables?

**Comment by ExDomino** [comment]
OpenComputer 1.5.9.21
IndustrialCraft 2-2.2.713
ThermalExpansion 4.0.0RC7-141

Tryed with a computer case tier 1 and a copper cable (128 eu/t). And another time with a creative computer case and a creative energy cell (each sides set in blue, output mode). In all case, the computer case doesn't take its power directly (says not enough energy [imagine that with a protoss voice xd]) and needs a power converter between the computer case and the cable/energycell to do so.

**Comment by LizzyTrickster** [comment]
Mind taking a screenshot? seems like your computer is drawing too much
power for it to convert

On 10 May 2015 at 20:02, ExDomino notifications@github.com wrote:

> OC 1.5.9
> IndustrialCraft 2-2.2.713
> ThermalExpansion 4.0.0RC7-141
> 
> Tryed with a computer case tier 1 and a copper cable (128 eu/t). And
> another time with a creative computer case and a creative energy cell (each
> sides set in blue, output mode). In all case, the computer case doesn't
> take its power directly (says not enough energy [imagine that with a
> protoss voice xd]) and needs a power converter between the computer case
> and the cable/energycell to do so.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MightyPirates/OpenComputers/issues/1141#issuecomment-100681858
> .

## 

Regards,
Josh Green

**Comment by fnuecke** [comment]
Have you used an analyzer on the case? What does it say about power in the network? Creative cases generate power on their own, so those won't accept external power (and if, only very rarely, very small amounts).

**Comment by ExDomino** [comment]
My creative computer case have shown "not enough energy" when I tryed to run it.
I needed to use a power distributor and a creative enegy cell. The energy cell alone didn't work.

**Comment by fnuecke** [comment]
> Have you used an analyzer on the case? What does it say about power in the network?

Still need an answer for this. In particular, what does it say if it's only the case? Because if in that case the max energy capacity in the network is zero, something is... weird. In that case adding a capacitor should also help as a workaround.

**Comment by fnuecke** [comment]
Closing due to lack of feedback and still not being able to reproduce.

**Comment by ExDomino** [comment]
I just tested and I belive the reason is that because without Power Converter, the computer has no energy buffer and cannot being started. I can use either a Power Converter, as I said, or power the computer directly if I have at least one Capacitor in my network to store energy. Without any way to provide an energy buffer, the computer will not start.

**Comment by LizzyTrickster** [comment]
The computer case only converts energy at a slow rate (50/1 I think? @fnuecke ) and the power converter converts at 500/1 or something like that. The case has a buffer but if it cannot convert enough energy to keep it's buffer filled it will stop

**Comment by fnuecke** [comment]
> I belive the reason is

Did you actually use the analyzer on the case to check as I asked? (Because that sounds like you didn't.)

Also @LizzyTrickster makes a good point. Try removing anything that draws power (like screens and other components) and see if the buffer in the case fills then (if there is one, again, just in case, analyzer).

**Comment by ExDomino** [comment]
I'm using Waila. ^^

**Comment by fnuecke** [comment]
Waila tells me 0/5000 for each case when I place it down, single- and multiplayer. If that's not the case for you (with the latest versions, at least of OC), it might be some mod-interaction (though I really don't know how), so see if it happens with OC only. Otherwise might be something in your config? (Buffer size for cases is configurable after all)

**Comment by ExDomino** [comment]
I didn't modify anything in the config, except the part to disable the give of the manual for freshly new players. I believe that setting does no matter with the energy. I will retry with the analyser.
