### ISSUE TITLE
Allow multiple lines in NEI Component API documentation

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#1143]
Firstly, the regex pattern `^function(\([^)]*\)[^-]*); (.*)$` in `li.cil.oc.integration.nei.CallbackDocHandler` should be changed to `^function(\([^)]*?\)[^-]*?); (.*)$` to properly split the string (similarly `^function(\([^)]*\)[^-]*) -- (.*)$` should be changed to `^function(\([^)]*?\)[^-]*?) -- (.*)$`). Secondly, every semicolon in the second capture should be replaced with `"\n  "` (a new line and two free spaces for proper indentation) to make the component API documentation in NEI look much better.

**Comment by asiekierka** [comment]
![](http://i.stack.imgur.com/MC2wS.png)

**Comment by Vexatos** [comment]
Exactly. :+1:

**Comment by Vexatos** [comment]
Apparently, the regex patterns can be improved even more using `^function(\(.*?\).*?); (.*)$` and `^function(\(.*?\).*?) -- (.*)$`, respectively.
