### ISSUE TITLE
[Suggestion] Disk drive blocks have their own component

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#1144]
My idea is to make that disk drive blocks have their own address, in order to know in which of them a floppy disk is insered or removed. And a new component with few methods : isDiskIn(), getFileSystem() if a floppy is in, nil if not, and maybe eject() to eject the floppy disk, if any.

This idea would be useful to, for example, create a card-read system when you insert a floppy disk, the computer detects it and open a door before to eject the disk after have read it. For now you have to build a computer for each of them.

**Comment by fnuecke** [comment]
Hrm, so basically making the disk drive a component? I can see the use in that. But it could break existing setups if they're running at the exact component limit, so it'll have to wait for OC 1.6.

**Comment by fnuecke** [comment]
From the Q&A at BTM: velocity parameter for eject.
