### ISSUE TITLE
[Suggestion] Tablet would persist when player is offline or when travel dimension

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#1145]
When the player that have a tablet is offline, the tablet restarts, same when traveling in dimensions. I know it's not a bug, but my idea is to make tablets persist, but only persist, they are not keept active, they just restart at the point they are stopped when the player become online.

If this suggestion is refused, I reported a bug related to it: https://github.com/MightyPirates/OpenComputers/issues/1146

**Comment by gjgfuj** [comment]
There is an issue with how saving works in inventories, and the
persistence. So, sadly, impossible. Or at the very least, hard.

**Comment by fnuecke** [comment]
I wanted to revisit this for some time anyway. I think I have this somewhat working... it's kind of a hack, but then again, tablets are one big hack anyway. so yeah.

**Comment by gjgfuj** [comment]
Ooh, interesting.
