### ISSUE TITLE
Crash with Forge 1403

### ISSUE THREAD

**Issue by Tedyhere** [MightyPirates/OpenComputers#1150]
I run the Davy Jones' Locker modpack and some people are getting a crash while others aren't, and I can't place the cause on anyone but OpenComputers is the only mod besides Forge that comes up in the crash report.  If you could take a peek and see if I am missing something?

http://pastebin.com/Zz46ZiCt

**Comment by fnuecke** [comment]
People with that crash have missing libraries. Sometimes the Forge installer fails to download some (presumably when the Mojang (?) servers are unresponsive). Have them re-install Forge, or have someone with all libs send those with missing ones their `.minecraft/libraries` directory (or equivalent).
