### ISSUE TITLE
Motion sensor & mobs

### ISSUE THREAD

**Issue by fagci** [MightyPirates/OpenComputers#1155]
I have prepared some slime chunk levels with motion sensors at ceiling. Wrote program for broadcasting messages over wifi about movement. This system works well when I close to slime chunk, but if I can't see mobs, this system does not work =(
Maybe motion sensors need to act as dummy player / mob entity for proper sensors work?
I tested it by placing some chickens.

**Comment by fnuecke** [comment]
Is the area with the entities chunk loaded? Also keep in mind that entities in chunks that represent the "border" of the loaded area (e.g. if you have a 3x3 chunkloaded area, the 8 outer ones) do not update.

**Comment by fagci** [comment]
As I understood, I need to make chunk loaded to use motion sensor?
I saw couple of tutorials for how to make a chunkloaded area by hopper, but can I leave it loaded by wire to player? (where endpoint device is, there manually loaded chunk)
And how wifi can work without loaded chunk with it?
I will check precisely chunk with PC+WiFi, same with mobs or not.

**Comment by gjgfuj** [comment]
Uhh, mods add chunkloaders, including oc. What mods do you have in your
pack?

**Comment by fnuecke** [comment]
Wireless networking will work as long as the chunks of the target and source devices are loaded, can't say much more without knowing more about your actual setup, though. As @gjgfuj mentioned, there are actual solutions (usually blocks) explicitly for keeping chunks loaded, which is what I meant. E.g. ChickenChunks, Railcraft's world/player anchors, OC's chunkloader upgrade for robots/drones.

**Comment by fagci** [comment]
My setup is pretty simple: AromaBackup, OpenComputers. Set too tiny because MC v1.8 ;)
Anyway, @fnuecke, I will check chunk with mobs soon.

**Comment by fagci** [comment]
**Exactly my server setup is:**
`Linux host 3.0.36+ #2 SMP PREEMPT Sun Dec 8 13:01:00 PDT 2013 armv7l`
`Ubuntu 14.04.2 LTS`

MC 1.8 + forge-1.8-11.14.1.1402-universal
Config: http://pastebin.com/azExni70
Other configs except AromaBackup by default.

**Mods:**
- Aroma1997Core-1.8-1.0.3.4
- AromaBackup-1.8-0.0.1.0
- Dynmap-2.1-forge-1.8.0
- OpenComputers-MC1.8-1.5.9.23-universal

---

**Client side - same version + mods:**
- CodeChickenCore_1.8
- LaserLevel-1.8-2.0.0.3-universal
- Light_Level_Overlay_Reloaded_Mod_1.8
- LunatriusCore-1.8-1.1.2.26-universal
- Not_Enough_Items_1.8
- OpenComputers-MC1.8-1.5.9.23-universal
- OptiFine_1.8.0_HD_U_D1

---

**Ingame:**
- PC with installed wifi at chunk with mobs.
- 2 motion sensors at ceiling of every room connected by wires with PC.
- Wireless test (without sensoring) passed successfully, distance between wireless modules 60.7 blocks.
- Wireless broadcast (without sensoring) recieved even if I away from:
  - Transmitter - 4-5 chunks
  - Receiver - 1 chunk (using note block signaling)
    **Program close to:**

``` lua
while true do
  event.pull("motion")
  modem.broadcast(20,"there is some live")
end
```

Or I need to use some async event queries and broadcast periodically about "movement" / "no movement"?

**Comment by Vexatos** [comment]
If I recall correctly, some monsters stop wandering around when there's no player nearby. Not sure if that's relevant.

**Comment by fagci** [comment]
@Vexatos, tested it now, they are moving if visible so far (3-4 chunks for me)
Will test with walls at local server

**Comment by fagcinsk** [comment]
Sooo strange=)
I made a room 16*16 (size of chunk) in creative mode, placed into it PC+WiFi+motion_sensor,
At 59 blocks away from 1st wifi I built 2nd wireless PC as receiver.
And...viola, it works=)
..but on linux dedicated server not =(

**Comment by fagci** [comment]
On local server everything works fine, already moved worldspawn to 5000, 5000 away from -600, -1600 spawn chunks.
Have no idea, why it doesn't works at dedicated server.

**Comment by fnuecke** [comment]
DId you move away from spawn when testing in single player? Because spawn chunks always stay loaded after all.

**Comment by fagci** [comment]
I test it at spawn area, but then I move worldspawn away and test it again

**Comment by fnuecke** [comment]
Haven't seen any issues with this other than this post (keeping in mind that in the outermost loaded chunk entities don't update), so I'll have to assume something else was going on here, sorry.
