### ISSUE TITLE
[Suggestion] Download a file from pastebin (with the internet card)

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#1161]
A new program in OpenOS could be a way to easily download a file from pastebin. It would takes 2 parameters: the pastebin ID and the local filename to write in. A flag option -e could be added to auto-execute the script after being succesfully downloaded, and the -o flag to override the file if it already exists. If the download fails, the reason is shown, for example there is no internet card in the computer, pastebin is down or the paste isn't found. If the file already exists, without -o, there would be a prompt to ask if you want to override the existing file or not, and if no, -e makes no effect.

**Comment by Vexatos** [comment]
... There is a built-in pastebin program. It will appear once you insert the Internet Card. There also is a wget program. Both have existed for far over a year now. Supports downloading and running from as well as uploading to pastebin. Just run "pastebin" to get a list of things you can do with it.

**Comment by gjgfuj** [comment]
Yeah.... Its there if you put an internet card in.

**Comment by dgelessus** [comment]
If you have autorun disabled in the `filesystem.cfg`, the internet card files are not automatically loaded, in which case you need to manually run the internet card's autorun script, or manually copy all files to your boot drive.

**Comment by Techokami** [comment]
[The pastebin program is here in the mod's resource files.](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/lua/component/internet/bin/pastebin.lua)

**Comment by fnuecke** [comment]
As mentioned, already exists.
