### ISSUE TITLE
Running script & screen

### ISSUE THREAD

**Issue by fagci** [MightyPirates/OpenComputers#1164]
If you run some infinity script, as example:

``` lua
while true do
  event.pull("...")
end
```

and reconnect to the server, screen will be black until you stop it by Contol-Alt-C.

Maybe it is not a bug, but why screen doesn't saves self state?

**Comment by fnuecke** [comment]
Hrrrmm, I'm sure I had fixed this at some point, guess it's a regression. If it's the same thing as back then, the state _is_ saved, it's just not correctly sent to the client on initialization. I'll look into it.

**Comment by fagci** [comment]
I have 1.5.9.23, maybe I need to update?

**Comment by fnuecke** [comment]
Don't think so, I think this was way back, but you can try. Anyway, I'll see if I can reproduce it later today.

**Comment by Kubuxu** [comment]
@fnuecke is it possible that I broke it while rewriting `event.lua`? This change will be hunting me forever.

**Comment by fnuecke** [comment]
Nah, this would have to be something on the Scala side, no worries ;-)

**Comment by fnuecke** [comment]
Hrm, I actually cannot reproduce this. Are you running a normal Forge server or Cauldron? FastCraft or any other tweak mods of note?

**Comment by fagci** [comment]
May be need more long time disconnected?
I have pure Forge server with no tweak mods. Only AromaBackup and Dynmap.
But on client I have OftiFine...

**Comment by fnuecke** [comment]
Maybe, but I did some testing with a severely throttled connection, and I still couldn't reproduce it.
Could you try if this also happens with _just_ OC? And also if it happens in a new world?

**Comment by fagci** [comment]
For now it works at server, will close issue.
