### ISSUE TITLE
Blocks not displaying properly

### ISSUE THREAD

**Issue by ibovangeffen** [MightyPirates/OpenComputers#1167]
![screen](https://cloud.githubusercontent.com/assets/10371224/7774261/3c390fda-00aa-11e5-9243-af1006fca273.jpg)
As you guys can see the opencomputers mod blocks are not displayed properly. I'm playing minecraft on a late 2012 iMac hackintosh, so maybe that's the problem. I don't know.

**Comment by fnuecke** [comment]
Any other mods present? If so, does it also happen if not? Any warnings in the log? Can you reproduce this on different machines, or just this particular one?

**Comment by ibovangeffen** [comment]
When I switch to Windows on the same machine I can't even install Minecraft Forge. It says it needs jre, but it's present. When I reinstall it, and reboot my pc it gives the same message. And this is the only pc which is capable of running minecraft I have at my disposal. So, no I'm not able to reproduce it on another machine or OS.

EDIT: I downloaded another universal installer, and now the opencomputers mod is working on Windows. Maybe, I don't know, maybe the mod is in one way or another not supported by OS X? That seems strange to me but I don't know if it's possible

**Comment by fnuecke** [comment]
Huh, so OC is the only mod for which this happens on your OS X installation?

**Comment by ibovangeffen** [comment]
Actually, yes. It's the only mod. I installed OS X on my system because everything is laggfree, on windows I have a lot of sudden freezes, so I hope it's possible to make the mod work on my OS X installation. Could the graphical card driver have anything to do with this? Because it's a non-apple one. It's patched by the hackintosh.zone community.

**Comment by GitBranch** [comment]
I have a legit mac... I'll try to replicate this.

EDIT: Give me some specs, and settings and I'll set them up.
