### ISSUE TITLE
*Probably rejected but somehow accepted suggestion* Creative APUs

### ISSUE THREAD

**Issue by GitBranch** [MightyPirates/OpenComputers#1169]
Here's an idea: Creative APUs! (from the same guy who suggested APUs)
It'll have both a tier 3 grahpics card and tier 3 CPU, both of which will operate at tier 3 speed.
It'll have no crafting recipe and will only be accessible within creative.
Maybe and a Internet Card / Wireless Network Card too... but probably not.

**Comment by gjgfuj** [comment]
well that sounds pretty useful imo, since it's creative no need to worry about balance.

**Comment by skyem123** [comment]
This does sound useful.

**Comment by fnuecke** [comment]
Eh, for creative, why not. Not the additional stuff, though :P

**Comment by GitBranch** [comment]
Thanks... Now I have to rename this...

**Comment by GitBranch** [comment]
![screen shot 2015-05-24 at 5 10 32 pm](https://cloud.githubusercontent.com/assets/7165071/7787349/ae2b4708-0239-11e5-8411-0e34dea3b374.png)

Irony.

EDIT: DARK VERSION:
![screen shot 2015-05-24 at 5 22 48 pm](https://cloud.githubusercontent.com/assets/7165071/7787348/9c4a266c-0239-11e5-826f-476fe07230f2.png)

EDIT: PHOTOSHOPPED TO LOOK LIKE OLD TITLE DARK VERSION:

![screen shot 2015-05-24 at 5 22 48 pm](https://cloud.githubusercontent.com/assets/7165071/7787363/7e5f1f12-023a-11e5-9b6f-b229adb7bfee.png)

**Comment by fnuecke** [comment]
Ewww, not using [GitHub Dark](https://userstyles.org/styles/37035/github-dark).

**Comment by GitBranch** [comment]
Didn't know about it... Looks really cool... _Switches_

EDIT: Why can't I get it for iOS Chrome? WHYYYYYYY???????
