### ISSUE TITLE
Hover boots backwards charge graphics

### ISSUE THREAD

**Issue by KurikAmudnil** [MightyPirates/OpenComputers#1170]
when crafting the new hoverboots, I received one without charge but it had used the full green bar suggesting a full charge.  When placed in the charger, the green bar decreases (appears to be discharging) until a full charge is reached with a display of an empty bar.

NEI shows both states available (recipe mode) which I find a little strange since battery upgrades do not show both charged and uncharged states in the NEI panel.

--Using MC 1.8, Forge 11.14.1.1404, others--

**Comment by fnuecke** [comment]
Ah, right, the display damage logic was inverted in 1.8 I think. Should work fine internally, just shows the buffer state inverse. The second "version" in the creative tab is for creative use, to allow cheating in a fully charged pair of boots.
