### ISSUE TITLE
OpenComputer Crashed Version 1.8-1.5.11.28-universal using forge 11.14.1.1412

### ISSUE THREAD

**Issue by SJS184** [MightyPirates/OpenComputers#1172]
![doc_1](https://cloud.githubusercontent.com/assets/11613529/7786789/262285ec-01b2-11e5-917f-bbbded1bc842.png)
![doc_2](https://cloud.githubusercontent.com/assets/11613529/7786783/eef79e90-01b1-11e5-835e-504f33c01db0.png)
![doc_3](https://cloud.githubusercontent.com/assets/11613529/7786784/eefe6a5e-01b1-11e5-95fb-7d24532fe318.png)
![doc_4](https://cloud.githubusercontent.com/assets/11613529/7786785/ef0617d6-01b1-11e5-9404-285eb9eb35af.png)

**Comment by fnuecke** [comment]
> Java Version: 1.6.0_65, Apple Inc.

That Java version is broken, update to Java 1.7.

**Comment by dgelessus** [comment]
Or even better, update to Java 8 right away. Java 7 is no longer supported by Oracle, and there's basically no reason to not use Java 8.

**Comment by SJS184** [comment]
Ok i will thank you. Also I love opencomputer it is so fun in the past it is a lot more difficult then computercraft please keep it that way its not fun if it is too easy.

**Comment by SJS184** [comment]
i ment ofr difficult
