### ISSUE TITLE
Ability to turn on/off robots/drones via adapter/charger.

### ISSUE THREAD

**Issue by gjgfuj** [MightyPirates/OpenComputers#1173]
Basically, expose a component with the ability to power a robot or drone on or off. (unless there's already a way to turn a robot or drone on or off via the computer in which case, nevermind.)

**Comment by fnuecke** [comment]
Robots do expose a component that does allow starting them, but they have to be adjacent to a case for that IIRC (which was mostly to avoid passing-by robots to cause fluctuation in the component count of networks IIRC).

Alternatively it might be possible to "shift-click" them with a robot, i.e. `robot.use(sides.blah, true)` them with another robot. Don't think I ever tested if that actually works, though, or if only real players can do that.

**Comment by SaphireLattice** [comment]
What about using adapter or charger (one of its sides) to control them?

**Comment by Vexatos** [comment]
Chargers shouldn't get a component as it would mess up most Computer Networks (You usually have quite a lot of chargers in a network when you're playing with drones and robots).

**Comment by SaphireLattice** [comment]
No, make robots that stand near charger appear as component, not the chargers themself.

**Comment by fnuecke** [comment]
I've fixed the sneak-use-to-power-on thing so robots can power each other on now (except for creative robots, too special-case-ish, cba). For stationary stuff there's wake on redstone and wake on LAN.
