### ISSUE TITLE
APU free up component count (in addition to slot)

### ISSUE THREAD

**Issue by MaHuJa** [MightyPirates/OpenComputers#1174]
Perhaps it should be left like this,
but I'd like to make sure it will remain before I rely on it.

Classic setup: cpu2, memory1 x2, graphics1: 3 Component slots taken.
APU setup: apu1, memory1 x2. 2 Component slots taken.

For apu2 that's two more component points available for comparable ability.

**Comment by fnuecke** [comment]
You mean for device complexity computation? Since with APUs you're basically getting less power for a higher tier CPU, I think that's fine. So yes, it'll stay this way for the foreseeable future.
