### ISSUE TITLE
Server Rack Causes Crash on Place and on World Load

### ISSUE THREAD

**Issue by KennethDev** [MightyPirates/OpenComputers#1175]
Whenever I place down a Server Rack in Minecraft 1.8 with the latest build (or any build for that matter) in my world, it crashes immediately and when I load the world again, it crashes immediately as well.

Crash Log:
https://gist.github.com/KennethDev/d84ba07885da9a53a54e

Any help would be very much appreciated.

**Comment by MyNameIsKodos** [comment]
Are you able to replicate this with just Forge and OpenComputers?

**Comment by fnuecke** [comment]
Next time, please be specific (i.e. mention you're placing it at y-level 0, instead of "whenever"), I only guessed that because the log contained the player coordinates... could have saved me some time. Thanks for reporting nonetheless!

**Comment by KennethDev** [comment]
I wasn't at Y-Level 0. I was in the top of a skyscraper in a city map when this first happened and the log is from superflat. I doubt it had anything to do with the coordinates.

**Comment by fnuecke** [comment]
Huh. That's odd. The only case I could reproduce it with was at y-level 0 (and 255). Please see if the latest build fixes this for you then. If it doesn't, I have no idea what's going on. If it does, I also have no idea what _was_ going on, but at least the fix worked :P
