### ISSUE TITLE
[Version: 1.5.11.149-dev] APU Textures Weird

### ISSUE THREAD

**Issue by GitBranch** [MightyPirates/OpenComputers#1178]
![1](https://cloud.githubusercontent.com/assets/7165071/7811714/0b71d19c-03df-11e5-9add-9bfbe14f8b84.png)
Here's the computer screen of mine. Notice the hotbar. Yeah, I have keyboards and a tier 3 monitor. But notice the APUs. No, I didn't fool you by placing a block with purple texture (I thought APUs were items!). The Tier 1 APU looks fine. But see the tier 2 APU:
![2](https://cloud.githubusercontent.com/assets/7165071/7811772/729d8e24-03df-11e5-98a7-bcb697a55c51.png)
Weird. It has the texture of the Creative APU.
And here, ladies and gentlemen, is the Creative APU:
![3](https://cloud.githubusercontent.com/assets/7165071/7811791/9d2edd0a-03df-11e5-9561-2ef007f4ea9e.png)
Why is it a purple BLOCK? I thought an APU was an item!

**Comment by fnuecke** [comment]
Ah, that's 1.8 I presume? Forgot to add the model file.

**Comment by GitBranch** [comment]
Yep. 1.8.
