### ISSUE TITLE
Beep radius is very low

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#1180]
I forgot to ask you on IRC so have an issue, why is the beep radius so low, 12 blocks is very little. That's like, I can still see a robot but not hear the robot.

**Comment by fnuecke** [comment]
Because I felt it was quite enough and built-in speakers weren't quite that loud, anyway. But I suppose I could add a setting for that (which would be client side, so you could change that to whatever you like even when playing on a server).

> That's like, I can still see a robot but not hear the robot.

Well, yeah, that's how reality usually works ;-)

**Comment by gamax92** [comment]
Also as a side note, doesn't using 3D audio to play the beep sound at the computer apply volume changes respective to distances itself, then your own volume radius on top of that further decreases the audio

(also even when I removed the code for decreasing the audio it still cut's off around 16)

**Comment by Kubuxu** [comment]
@gamax92 it is MC's sound engine.

**Comment by fnuecke** [comment]
It's cut off at 16 because the server won't send it to clients further away currently.

**Comment by fnuecke** [comment]
Oooor not. Well, also. But I had expected to work around MC's rolloff using `AL_MAX_DISTANCE`. Seems I can't. If noone has any other ideas...

**Comment by fnuecke** [comment]
Nevermind, setting the `AL_REFERENCE_DISTANCE` to the max distance allows faking the rolloff myself, which is good enough for the duration of beeps.
