### ISSUE TITLE
RFC / Redstone Circuitry

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1182]
RFC
So I had an idea that I quite like, looking forward to see what the community thinks.
Proposed changes (skip down if you want examples xD):
- A way to make printed blocks conduct redstone (make them behave like redstone wire)
  - Conducting shapes that touch the outside of a block that is powered by redstone will conduct the power of that side through them (and other conducting shapes that they touch).
  - If they don't touch the outside, they don't care if the block is powered by redstone.
  - Conducting shapes that don't touch the outside can be powered by touching other shapes that conduct and are powered and/or powered by shapes that emit redstone power.
- A way to have shapes have certain redstone levels, not only whole blocks.
  - Shapes touching the outside of a block will emit their redstone levels into that direction, shapes that don't touch the outside won't emit
- 2 new special materials/shape types
  - Emitter: Emits either a certain or a full-powered redstone level
  - Emitter-Disabler: if those receive redstone power they will disable emitters that touch them, otherwise emitters emit.
- Conducting shapes that touch other 3D Prints on a side of a block transfer their conducted power to the other 3D Printed block, if it is a fully conducting block. If it isn't, they will transfer their conducted power to other conducting shapes in the other block, should they touch them.

Those changes would allow redstone circuitry.
For example a simple and-gate (view from top). If I1 is touching a redstone wire, shape of another printed block that is conducting power, or receiving power on that side, it will conduct that power too. That way it would allow the Emitter-Disabler shape on its side to disable the Emitter Shape. If both side do that, the bottom conductor on the top won't be powered anymore, thus allowing the emitter on the top to emit and conduct redstone out of the top of the block.
![andgate](https://cloud.githubusercontent.com/assets/1077971/7843647/406584d0-04ab-11e5-9099-d797b67cbf16.png)

Another example, 2 prints touching each other to route various redstone lines through a 2 block space. Using the third dimension to "cross wires".
![routing](https://cloud.githubusercontent.com/assets/1077971/7843667/6a1bdeb4-04ab-11e5-83ec-e0acd5e0c03e.png)

Also with the change of shapes being able to emit arbitrary redstone power and only emitting into a side they touch, it would be possible to make a block that e.g. emits a power of 3 north and of 6 south. etc.

**Comment by fnuecke** [comment]
This would make prints _massively_ more complex than they are now, which honestly isn't what I was aiming for with them (intended to be decorative blocks more than anything). But we'll see what others think. It won't be me implementing that, though, that I can say in advance :P Frankly, I think this would make sense as a separate mod -- in fact, there [already is](https://github.com/Victorious3/Integrated-Circuits/) ;-)

**Comment by cinder1992** [comment]
I think a good way to implement this (without stealing IC mod's thunder)  would to have it be i/o only, so you could right click on a part of the print and it'd output a redstone signal from X side with Y power and Z cable color (Bundled Cables), allowing multiple inputs per block.

**Comment by LeiserGeist** [comment]
You're just full of good ideas huh?
Would surely be quite complex, but creating large scale processors with it would be sick.

I had a decent suggestion for this going along with what fnuecke said, but I forgot!

Edit: I just noticed how old this is, muh bad.

**Comment by fnuecke** [comment]
Been a while and I still think this is overkill for the 3D prints; use Integrated Circuits or some other mod geared towards that.
