### ISSUE TITLE
System with more than 1 GPUs (Including APUs) uses the First GPU in the Expansion Slot, even though if there's a better GPU avaliable

### ISSUE THREAD

**Issue by GitBranch** [MightyPirates/OpenComputers#1185]
It uses the first GPU in the expansion slot instead of the best one. Is this intentional?
Computer spec for reproduction (Tier 3 Monitor on top)
![rep](https://cloud.githubusercontent.com/assets/7165071/7857939/13c5b820-0567-11e5-92b5-ca73c380a411.PNG)

**Comment by fnuecke** [comment]
Yes, this is intentional. The first of a certain _type_ is used, where possible, the tier is ignored, because it's not necessarily a common concept (and there's no getter for it).

**Comment by GitBranch** [comment]
(BTW A Glass pane would stick to a keyboard and text appears to be floating) 
![2015-05-28_18 29 54](https://cloud.githubusercontent.com/assets/7165071/7858031/ad95d282-0567-11e5-9436-ad9cb2f98255.png)

**Comment by fnuecke** [comment]
The text offset is necessary to avoid z-fighting, the way things are handled currently, the glass thing I'll fix ([bloody tenthousand different methods needed to define whether a block is solid or not](https://twitter.com/FyberOptic/status/602670739582545920)).
