### ISSUE TITLE
OC versions MC1.8-1.5.10.24+ crash on Creative Tab or NEI

### ISSUE THREAD

**Issue by jpastuszek** [MightyPirates/OpenComputers#1187]
https://gist.github.com/jpastuszek/5f81a0d043de2a24f6bb
Sometimes NEI won't display at all instead of crashing the game but clicking OC creative tab crashes always.
Crashes with all versions up to 1.8-1.5.12.29-universal.jar including.
Version 1.8-1.5.9.23 works fine.

**Comment by fnuecke** [comment]
Could you please test if [build 156](http://ci.cil.li/job/OpenComputers-dev-MC1.8/) fixes this for you? Sounds related to #1186, as it errors when creating the OpenOS floppy in the creative robot.

**Comment by jpastuszek** [comment]
OK I got it working with the latest normal release by not adding my own assets (I forgot to mention I have a few floppies of my own).
I got it working with my floppies again by extracting and updating new loot.properties which has changes slightly since.

What I was using that caused the error was:

```
# This file contains the list of floppy disks that can be found as loot.
# Each entry is a mapping of folder name to disk label. Parameters are
# the 'weight' of an item in the random generation process and the color
# of the floppy. The default weight is one. For example, a disk with
# weight 2 is two times as likely to be generated than an item with
# weight 1. The color defaults to gray. It must be a dye's ore-dict name.
BetterShell=besh
Builder=build:1:dyeCyan
MazeGen=maze:1:dyeBrown
Network=network:1:dyeYellow
OpenIRC=irc:1:dyeRed
OpenLoader=openloader:1:dyeOrange
OpenOS=openos:1:dyeGreen
OPPM=oppm:1:dyeLime
# Higher chance to find the dig program, because it has the most immediate
# use - OpenOS is craftable and IRC can be downloaded once an internet card
# is available - which one needs anyway, to use the program...
TheDig=dig:3:dyeBlue
# JPastuszek's stuff
Extras=extras:2:dyeLightGray
Agriculture=agriculture:2:dyeMagenta
Reactor=reactor:2:dyePurple
```

So apparently some colors and weights were changed and BetterShell was removed.

I think that what you should do to prevent this kind of issues is perhaps splitting the vanilla config from custom configs by for e.g. creating a loot.d dir where user could put it's own loot properties files (like loot.d/jpastuszek.properties).
Also you may need to add some more checks in the code.

Thank you!

**Comment by fnuecke** [comment]
Ehh, that shouldn't be able to cause this, though. I'll look into it anyway.
