### ISSUE TITLE
Integration with vanilla not working

### ISSUE THREAD

**Issue by jpastuszek** [MightyPirates/OpenComputers#1188]
Hi,

I am trying to use Node Block or Furnace with Adapter block but they won't appear in components list. Also 'ocpiano' won't see Note Block:

![2015-05-23_20 18 18](https://cloud.githubusercontent.com/assets/20052/7891914/5aed02c6-0648-11e5-910a-146c63cd977d.png)
![2015-05-23_20 17 43](https://cloud.githubusercontent.com/assets/20052/7891915/5aed4b32-0648-11e5-8013-3b558d3b84c6.png)

Not sure if I am not doing it right?
Tried on version 1.8-1.5.9.23 and 1.8-1.5.11.28 (not 100% sure).

I would test this with Network Debugger if I could remember the /give command name for it! Somehow NEI won't tell you the name and /give won't work with block ID... :/

**Comment by fnuecke** [comment]
Oops, derped the adapter. Thanks for reporting this!
