### ISSUE TITLE
Missing redstone reset when breaking a redstone emitting 3d print

### ISSUE THREAD

**Issue by aglx** [MightyPirates/OpenComputers#1193]
Print a custom block using print3d and the following source

```
{
  emitRedstone = true,
  shapes = {
    { 5, 0, 6, 11, 6, 10, texture="gold_block" }
  }
}
```

Placing the printed block on a solid block adjacent to redstone dust correctly poweres that dust.
![2015-06-01_04 31 08](https://cloud.githubusercontent.com/assets/12689308/7905393/218fbd26-0818-11e5-8326-8520f5ac47bf.png)
However, breaking the printed block does not reset the power level of the redstone dust.
![2015-06-01_04 31 21](https://cloud.githubusercontent.com/assets/12689308/7905398/2e74b618-0818-11e5-8948-f550c9beb52c.png)
The same applies if we specify a custom power level `emitRedstone = 14`, or if we replace the redstone dust by redstone transmitters from other mods, e.g., by wires from ProjectRed. The problem does not occur if the 3d print and the redstone dust are on the same y-level.

**Comment by Vexatos** [comment]
Also, @fnuecke, this might be related: When placing a redstone-emitting print next to one working like a door and rightclick the redstone-emitting one, the door-like one only changes after you disable the redstone-emitting one again... Seems to be an issue with wrong block updates.
