### ISSUE TITLE
1.8 builds fail

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#1195]
```
scala/li/cil/oc/client/renderer/tileentity/RobotRenderer.scala:392: type mismatch;
 found   : net.minecraft.client.renderer.block.model.ItemCameraTransforms.TransformType(THIRD_PERSON)
 required: net.minecraft.client.renderer.block.model.net.minecraft.client.renderer.block.model.
            itemRenderer.renderItem(Minecraft.getMinecraft.thePlayer, stack, TransformType.THIRD_PERSON)
```

When I try to build master-MC1.8 or OC1.5-MC1.8 I get the above error.
It's not just me, you can see the same thing here:
https://travis-ci.org/MightyPirates/OpenComputers/builds/64973364

Tested and got the error on Oracle 1.6, Oracle 1.7, and OpenJDK 1.7

**Comment by fnuecke** [comment]
Ah, right, that. I asked about that on #ForgeGradle quite some time ago, but forgot to keep track of it. The workaround is to run `setupDecompWorkspace` once, after that it works. I'll reproduce just in case and report it again.

**Comment by Kubuxu** [comment]
@fnuecke it is remarkably similar to my error with scala and Java's generics. Scala breaks on raw-types.

**Comment by fnuecke** [comment]
Huh, not entirely sure what you mean, but since it's apparently some missing classes or something (because `sDecW` fixes it), I'm not sure it's related?

**Comment by Kubuxu** [comment]
If method is using as argument generic class but it does not specify its generic signature(is using raw type) scala can't fit specific generic class. `sDecW` probably fixes this by removing raw typing. It is just blind shot. I can't check if this method is using generics at all, I am on the phone.

**Comment by fnuecke** [comment]
Hrm, don't think that's related then. `renderItem` is not generic, nor are the arguments - which are `EntityLivingBase`, `ItemStack` and `ItemCameraTransforms.TransformType`, where `ItemCameraTransforms` is a plain class and `TransformType` is a plain enum in that class.

**Comment by Kubuxu** [comment]
Ok.

**Comment by gamax92** [comment]
Ahh okay, I'm used to just running build because generally that works for most things. It is sorta weird that scala decided to take `net.minecraft.client.renderer.block.model.` and double it.
Running setupDecompWorkspace does fix it indeed, thanks

**Comment by fnuecke** [comment]
Good news, it got fixed.
