### ISSUE TITLE
EEPROM (Lua Bios) is impossible to create

### ISSUE THREAD

**Issue by PaulGWebster** [MightyPirates/OpenComputers#1199]
Open Computers manual + plain eeprom = another plain eeprom

So the computers will not start with: no bios found; install a configured eeprom!

**Comment by PaulGWebster** [comment]
Latest version

**Comment by PaulGWebster** [comment]
1.5.12.26

**Comment by gamax92** [comment]
More specifically, EEPROM's that have an UUID already (Say they were put into a case) cannot be crafted with the OC Manual to get a Lua BIOS, instead you get another blank EEPROM
