### ISSUE TITLE
Robot gains excessive amounts of power from energy net

### ISSUE THREAD

**Issue by civilwargeeky** [MightyPirates/OpenComputers#12]
I have a bunch of capacitors in a bank next to a converter and a charger. There is an activated lever on top of the charger. When I place a new turtle next to the charger, instead of being able to store the expected 50,000 power, it can store 255,400 power. This is even more strange because the power net itself could only initially store 55,400 power.
Here is a picture of my setup: http://i.imgur.com/AKa2s6f.png

**Comment by fnuecke** [comment]
Confirmed, looking into it.
