### ISSUE TITLE
1.5.9 doesn't know 1.5.1x is later version

### ISSUE THREAD

**Issue by SolraBizna** [MightyPirates/OpenComputers#1200]
I missed the last several updates because the ingame update check didn't notify me that a new version was available. Since OpenComputers uses FML's ComparableVersion class, I assume this isn't actually a bug in OC's code...

**Comment by fnuecke** [comment]
Hrm, `ComparableVersion` handles such cases fine (in 1.7.10 anyway, just tested), so it has to be something else. I'll test it when I can - for the time being, if you haven't already, could you have a look at your logs and see if anything seems out of place (stack traces from update check or something)? Thanks.

**Comment by fnuecke** [comment]
Broke it when I simplified the build script... so the `@VERSION@` it compared against to avoid checking in dev-env got replaced with the actual version, so it never checked. Oops.
