### ISSUE TITLE
Allow Microcontroller/Drone/Robot with no RAM on supporting architectures

### ISSUE THREAD

**Issue by SolraBizna** [MightyPirates/OpenComputers#1201]
My ARM architecture module is far enough along that I've started using it in my own Minecraft play for various simple tasks. The first one I did was a 1Hz redstone clock microcontroller that needed only 20 bytes of RAM. I wanted it to use the 256-byte SRAM for that purpose, and in fact wrote the ROM to do so... only to find that it wouldn't let me assemble a microcontroller with no RAM installed.

This restriction makes perfect sense for the Lua architecture, but with the ARM architecture it is actually possible to make a useful computer without any RAM modules installed. On top of being an interesting challenge, this can free up a precious complexity point.

I suggest allowing architectures to specify somehow whether they require RAM modules.

**Comment by gamax92** [comment]
In the mean time, you could add a recipe that is a microchip and a piece of dirt for non functional memory  (gives 0 bytes)

**Comment by SolraBizna** [comment]
That might be possible. I'll look into it.

**Comment by gjgfuj** [comment]
That wouldn't free up a complexity spot I don't think though.

**Comment by SolraBizna** [comment]
I'm thinking it might be possible to make a component that sits in a RAM slot and satisfies the assembler but has a complexity cost of 0 and isn't actually a RAM module. I haven't looked into that code yet, so I'm not sure if it can be set up this way.

**Comment by gjgfuj** [comment]
Complexity is sorta a cheat. Its just the tier of the component with maybe
a few other calculations here and there.

**Comment by gamax92** [comment]
Tier 0 memory chip? :P

**Comment by SolraBizna** [comment]
From what I remember of the code, when the Lua architecture is determining the amount of RAM in the system, it clamps the "item tier" to 0--5, where 5 maps to "tier 3.5" and 0 maps to "tier 1". So the question is whether it's possible to make an item that satisfies the assembler that there's RAM installed, but isn't recognized by the Architecture as a RAM module.

**Comment by fnuecke** [comment]
I'll add an annotation that can be added to architectures to flag them as not requiring memory; that should cover this and similar cases, I think?

**Comment by fnuecke** [comment]
All right, try adding `@NoMemoryRequirements` to your arch in the next build (will push in a bit). Disclaimer: I haven't actually tested this, so let me know if it doesn't work, it'll most likely not be your fault :P

**Comment by SolraBizna** [comment]
Sorry for the delay, was just able to test it. (I didn't test it with drones, only microcontrollers.)

I attempted to make a microcontroller with a `@NoMemoryRequirements` Architecture and no RAM. It still said to "Insert some RAM", but it allowed me to hit the button and successfully make a microcontroller. Also, the `@NoMemoryRequirements` annotation isn't inherited, but that isn't a big problem.

**Comment by fnuecke** [comment]
Ah, yeah. Will fix that momentarily, overlooked that the status message generation was kind of a separate thing. As for the inheritance, are you sure? I thought `getAnnotation` also checked parent ones, whereas `getDeclaredAnnotations` was the one that only returned the annotations actually on the specific class?

**Comment by Kubuxu** [comment]
@fnuecke You have to add `@Inherited` to the annotation but it still does not inherit from interfaces.

**Comment by fnuecke** [comment]
Ahh, I see, thanks for the info! I agree that it's not really a problem either way, but I'll slap it on there.
