### ISSUE TITLE
Asynchronous signal signalling?

### ISSUE THREAD

**Issue by SolraBizna** [MightyPirates/OpenComputers#1202]
The emulator at the core of my ARM architecture has support for asynchronous IRQs/FIQs. I intend to use one to indicate the presence of a signal, and the other to indicate the arrival of a certain Minecraft world time. The latter can be simulated adequately without extra support from OpenComputers, but the former has a large amount of response latency if it can only be updated at `runThreaded()` boundaries, and burns a lot of cycles if it must be polled.

I propose adding a method to the Architecture interface that is called (from the delivering thread) whenever a signal is delivered to the machine. The Architecture would be responsible for any synchronization or special handling necessary to make this work. The computer would still need to pull the signal by existing means to find out anything about it; this call would merely signal that a signal exists. The Lua architecture (and most others, I imagine), lacking any way to support asynchronous signalling of the running program, would simply ignore the call. The ARM architecture, on the other hand, could make use of this information to provide more "snappy" signal response.

This is low priority. Asynchronous IRQ delivery is hardly a killer feature, and I still haven't even gotten Lua working well on the emulated machine. (P.S. Heap corruption is a lot harder to track down in a new kernel than in a program for an existing OS...)

**Comment by fnuecke** [comment]
Hmhm, so if I understand correctly, basically a new method in the Architecture interface, let's call it `interrupt`, that gets called by the Machine's `signal` method? Sounds simple enough. Due to the API change it'll have to wait for 1.6, though.

Really looking forward to a Lua VM running an ARM VM running in the Java VM :D

**Comment by SolraBizna** [comment]
You understand correctly, and waiting for 1.6 is a good idea.

(And I'm looking forward to that too. :P)
