### ISSUE TITLE
Robot's occasionally lockup

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#1203]
The robots occasionally will look like they are powered off and be impossible to open without breaking and placing back down, I know they aren't powered off because a currently running program moving the robot around will still be moving the robot around.

Minecraft 1.8, latest 1.8 official verison
No power mods installed

**Comment by fnuecke** [comment]
Will the robot still graphically move, i.e. update its position correctly? Or is it a full desync, i.e. the client losing track of the robot's actual state and position?

Oh, and if it's on a server, does relogging fix it?

**Comment by gamax92** [comment]
It'll still be moving around in the world, so yes. I also forgot to mention that the tool stops rendering until I right click on the robot.

EDIT: Relogging did not fix the issue, it'll look locked up when it returns to me, and then still be locked up when I rejoin

**Comment by n00b7** [comment]
this normally happens when your in survival trying to open the gui of the
robot made with a creative case.

**Comment by gamax92** [comment]
Which is not relevant since the robot doesn't have a creative case

**Comment by n00b7** [comment]
can you post the game output

**Comment by fnuecke** [comment]
wat

**Comment by gamax92** [comment]
He's stealing your job!

Also I'm just going to close this since I've only replicated it in a single MC version with a specific mod pack, and am no longer playing said MC version or mod pack. Attempts to do it in other versions or with OpenComputers alone has given no results.

**Comment by fnuecke** [comment]
Oh well then. If it pops up again in newer versions let me know.
