### ISSUE TITLE
Items are misplaced when a drone drops them into a trapped chest

### ISSUE THREAD

**Issue by SolraBizna** [MightyPirates/OpenComputers#1205]
I have a drone moving stuff around a tightly packed double chest setup. (They are aligned along the Z axis and the drone approaches from the -Z side, if it matters.) Half of the double chests are trapped chests, to allow tight packing. I've frequently observed the drone to carry something up to a trapped chest, and attempt to `drop(side)` the item in the chest, only to have the item disappear forever... and since I turned this drone on, I've never observed it to put anything _successfully_ into a trapped chest. It works fine with regular double chests.

**Comment by SolraBizna** [comment]
Aha... They weren't disappearing, the drone was just putting them into an adjacent (-X) non-trapped chest.

**Comment by SolraBizna** [comment]
Further experimentation shows that they are confused by trapped chests next to regular chests in general, including when reading and manipulating inventories.

**Comment by fnuecke** [comment]
I'm inclined to blame this on Minecraft's implementation of the double chests, which is quite horrible... I'll see how best to work around it.

**Comment by fnuecke** [comment]
Hah, it's not. It's me being a derp. Double chest implementation is still horrible though :P

**Comment by SolraBizna** [comment]
Sorry once more for the delay. I can confirm that the setup that was problematic before is working now. As for whether the bug is completely fixed... who knows? Minecraftian double chests are subtle and quick to anger... :P

**Comment by fnuecke** [comment]
Indeed, [they can start doing odd things out of nowhere](http://imgur.com/qaMmBSv,rsm1RIJ) :P
