### ISSUE TITLE
Make Adapter consume energy per attached component?

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#121]
This is just an idea that's been floating around for a while, and I'm not really sure I want to go ahead with it. Basically the idea is to make the Adapter block consume energy per tick, a constant amount per attached component.

What makes me hesitant to add this is that
- the number of components is limited by CPUs anyway.
- components may use energy themselves, as necessary.

This would obviously a config option like everything else. Feedback welcome.

**Comment by SpiritedDusty** [comment]
I don't think this should be added because if components use energy themselves then adding energy per tick to the adapter blocks would just be wasting power.
