### ISSUE TITLE
Solar upgrade makes battery life DRAIN even when robot is turned off

### ISSUE THREAD

**Issue by PaulGWebster** [MightyPirates/OpenComputers#1211]
Time difference: 10 seconds ish

http://i.imgur.com/Jjzzuq2.png
http://i.imgur.com/WFeL55C.png

Version: 1.5.12
Forge: 1374

Bot spec: Tier 2 case, Tier 1 monitor, keyboard, Tier 1 NIC, Tier 1 Hover upgrade, Inventory and Storage update, Tier 1 cpu, tier 1 hard disk, tier 1.5 ram

**Comment by PaulGWebster** [comment]
I just had a second to think about this and I think ANOTHER earlier bot I had, had this issue (without the solar upgrade) meaning the candidates would be:

Hover Tier 1 update,
Monitor
Keyboard
HDD T1
Storage update
Inventory update

I would actually Bet on the hover T1 update not enough resources to confirm atm

**Comment by fnuecke** [comment]
Does the screen still display something after turning the robot off? Because then it'll most likely continue to draw power.

**Comment by Vexatos** [comment]
@fnuecke It also does for normal Screen blocks when you just click the "turn off" button, all screens just remember the state they were last in.

**Comment by fnuecke** [comment]
Yes, as intended, that's why I'm asking ;-)

**Comment by PaulGWebster** [comment]
@fnuecke indeed but surely thats a bug anyhow :)

The other issue is though, the solar panel even in day does not offset the small draw from one tier1 screen, that cannot be right

**Comment by Vexatos** [comment]
@PaulGWebster While the Computer is turned off, the Solar Generator doesn't run at all. Also, it is meant to not be able to power a single robot, you'd need to use quite a few of them. It does work well for drones, though.
This bug is still weird.

**Comment by PaulGWebster** [comment]
@Vexatos ok for the solar upgrade, but even so if the robot is off there should be no energy loss at all

**Comment by fnuecke** [comment]
Screens keeping their contents unless cleared is intended behavior. Shutting down the computer/robot via `shutdown` will clear it, thus avoiding power consumption. In fact, when the screen is cleared, the buffer will fill, because the solar upgrade will keep generating energy even when the robot is powered off (and yes, I just tested this to make absolutely sure).
