### ISSUE TITLE
[Suggestion]hologram print3d models

### ISSUE THREAD

**Issue by n00b7** [MightyPirates/OpenComputers#1216]
i think you could make a program for the hologram projector to show print3d models with a hologram projector

**Comment by fnuecke** [comment]
I already [made a program to render previews](https://twitter.com/SangarWasTaken/status/583963043899539456) ([code](https://github.com/OpenPrograms/Sangar-Programs/blob/master/print3d-view.lua)). I'll leave this to someone else. Shouldn't be that hard, after all.
