### ISSUE TITLE
No obvious public equivalent to Settings.get.ignorePower

### ISSUE THREAD

**Issue by SolraBizna** [MightyPirates/OpenComputers#1217]
I'm implementing the `computer` API for my ARM implementation of OpenComputers' Lua environment. I reached `computer.energy()` and wanted to handle the infinite energy case, but found no obvious public way to do it. The LuaJ `ComputerAPI` class (the source to which, along with its siblings, has been _amazingly helpful_*) uses [`li.cil.oc.`]`Settings.get.ignorePower` to determine whether energy is in use, but this class is not present in the API.

*Transitioning from the other terrible code I work with on a day-to-day basis to OpenComputers code still messes with my head. I didn't (and don't) know any Scala, but the code is still readable and straightforward. You can have no idea how much it brightens my day to work with this code. Seriously.

**Comment by fnuecke** [comment]
In general, you can access OC's config via the `li.cil.oc.API.config` variable. But that doesn't cover the computed value based on mod presence, which I probably didn't think of when I decided to do it this way...

I'll see if I can find a nice (i.e. not copy-paste-heavy) way to generate a new config from the actual, validated values (e.g. stuff where it's set to `config.getXYZ() max a min b`) and set the computed value for `power.ignorePower` in there.

(And thanks for the kind words :-)
