### ISSUE TITLE
autostart.lua seems to never get read

### ISSUE THREAD

**Issue by shawniac** [MightyPirates/OpenComputers#1222]
## Issue

It seems like the autostart.lua never gets read for me. (auto mount example from the wiki doesn't work)
To test this I setup a simple print()-statement in the file "autostart.lua" in the root of a harddrive.
Removing and inserting the drive into the computer does not print anything, and thus the autostart.lua is never executed.
## Screens

![preparation](http://chunk.io/f/694826f12c9a4a259c06f1abe9282418)
![removing and inserting drive](http://chunk.io/f/3f1f9c4ef70949bab2a4f32035aacad8)
## Details

OS: Archlinux x64 (Kernel: 4.0.5-1)
Minecraft version: 1.8 

| Mod | Version |
| --- | --- |
| Minecraft Coder Pack | 9.05 |
| Forge Mod Loader | 8.0.99.99 |
| Minecraft Forge | 11.14.3.1446 |
| CodeChicken Core | 1.0.5.36 |
| Not Enough Items | 1.0.5.104 |
| OpenComputers (Core) | 1.0.0 |
| OpenComputers | 1.5.12.29 |

**Comment by gamax92** [comment]
Isn't it called `autorun.lua` and not `autostart.lua`

**Comment by dgelessus** [comment]
This _might_ be because the file needs to be called `autorun.lua` (optionally starting with a dot). ;)

**Comment by CaitlynMainer** [comment]
What they said, I didn't even notice that in IRC... -_-

**Comment by shawniac** [comment]
Everything is working fine now ._.

P.S.: eternal shame will haunt me now i guess
