### ISSUE TITLE
insertItem always returns "no inventory"

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1228]
The title says it all. I tried using insertitem but it wasn't working so I putted it in a print statment and it returned nil no inventory. I tried placing a chest, a furnece, a player everything yet it always return the same. The coordinates are correct because I putted them in a variable and also used the same variable to spawn the chest.

**Comment by fnuecke** [comment]
I'm assuming you mean the debug card? Works fine for me, make sure you got the correct coordinates.
