### ISSUE TITLE
"Crecopter" does not contain a BIOS chip

### ISSUE THREAD

**Issue by flarn2006** [MightyPirates/OpenComputers#1229]
I gave myself one of the default creative-spawnable drone, "Crecopter", and placed it on the ground. When I tried to turn it on, it beeped and didn't go on. I clicked it with the analyzer, and it said the reason was that no configured EEPROM was installed. Sure enough, after putting it in a disassembler, there was no EEPROM among the components, not even a blank one. I'm guessing Crecopter was added before the EEPROM was a requirement, and you simply forgot to add it to the list of components.

This may or may not be the case with the default microcontroller, robot, and tablet as well; I haven't tested.

**Comment by gjgfuj** [comment]
You're supposed to craft it with an eeprom before using it.

**Comment by gjgfuj** [comment]
It couldn't have been added before the eeprom requirement as drones only
work with eeproms.

**Comment by flarn2006** [comment]
Oh, that makes sense. Thanks for clarifying.
