### ISSUE TITLE
Glowing prints

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1232]
So yeah, we got light-emitting prints, but ones that can glow in the dark would be pretty nice :D

**Comment by fnuecke** [comment]
You mean have it ignore actual lighting, such as the text on screens? Eh, I dunno, just make it emit light and it'll be lit up :P Actually, I'm not sure this is even doable without a TESR...

**Comment by Kubuxu** [comment]
@fnuecke it is.
`tessellator.setBrightness` and argument is `skyLight << 20 | blockLight << 4`

EDIT: Oh, without the TESR... reading comprehension.

**Comment by Inari-Whitebear** [comment]
Well yeah, that it would ignore light conditions and always appear bright.
Like e.g. the Xycraft Ores did

**Comment by fnuecke** [comment]
Hrm, apparently one can also change the tessellator state in the block renderer to do that (that's what [AE2 does for the controller](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/client/render/blocks/RenderBlockController.java#L162-L163) anyway). That feels... pretty hacky, but I guess that could work. For 1.8 there's an extra field in the baked data for the brightness, so I'm guessing that'd work there, too... we'll see.

**Comment by fnuecke** [comment]
So I gave what I linked a quick try, but that didn't work for some reason. If someone else wants to take a look into this, be my guest.
