### ISSUE TITLE
(Even) Better Gregtech 5U Integration

### ISSUE THREAD

**Issue by Timeslice42** [MightyPirates/OpenComputers#1233]
There were a few important details left out of the resolution for #760 (see my last two comments). While it would be great to see the recipes modified to support these new machines, at the very least the GT recipe config file should support the following machines (as detailed at http://bit.ly/1N6id6f):
AssemblerLiq (Liquid support for the Assembler)
FormingPress
PrecisionLaser
SawLiq (Liquid support for the Cutting Machine)
and possibly these:
ChemicalReactorLiq
FluidCanner

As far as recipes go what I'd like to see is a cutting wire and raw board recipe similar to what I had in #760, for all of the assembler recipes use molten lead, tin, ore solderingalloy like the GT ones do, and either an assembly recipe for the boards that takes a cooked board, the gold, and some sulfuric acid, or a forming press recipe that takes the board and etched high voltage wiring. However if you get the support into the config file then we can do that ourselves.

**Comment by lordjoda** [comment]
Liquid Support for Assembler is already included, same for the Cutting Machine and the Chemical Reactor. I will take a look at the rest. Please create a Pull request for the recipes once I added the support for the required machines. Thanks

**Comment by Timeslice42** [comment]
Does the file format support multiple recipes for the same item? Also, which circuit board recipe do you favor, assembly machine, or forming press? Traditionally GT uses the assembly machine for finished circuit parts, and the precision laser and forming press for intermediate circuit parts.

**Comment by fnuecke** [comment]
The current implementation only supports one recipe per item.

**Comment by Timeslice42** [comment]
That's kind of an issue then, as each of the Assembler circuit recipes can use tin, lead, or soldering alloy, but they are three different recipes.

The Cutting Machine is similar, being able to accept water, distilled water, or lubricant.

If worst comes to worst though we can just use the soldering alloy and lubricant recipes, as they are the ideal materials.

**Comment by fnuecke** [comment]
Having multiple recipes would probably not be _that_ hard to add in a backward compatible way. I'll see when I can have a look at that.
