### ISSUE TITLE
edit can be crashed through find (ctrl-f)

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#1234]
If you open up find, and type in either a [ or a (, the editor will crash since string.find is being used in pattern mode. Perhaps find should instead be used in plain matching mode, or if patterns are desired, to be validated before using them

Also, happy 1234th issue! :D

**Comment by fnuecke** [comment]
I don't think patterns are necessary there (though I didn't implement that, so I can't be sure if that was originally even a consideration). Feel free to make a PR, otherwise I'll hopefully have the time to take a look over the weekend.
