### ISSUE TITLE
Network Enhancement : Gateways, a simplist computer that relay packets like switches but is progamable.

### ISSUE THREAD

**Issue by alwaeles** [MightyPirates/OpenComputers#1236]
A gateway is a little computer. It can transmit packet between switch-formed networks by a program in its EEPROM.
It can allow creating firewalls, routing, etc.

May you can implement this in your mod ?

Thank you.
Axelandre42 !

**Comment by dgelessus** [comment]
AFAIK that's what microcontrollers are for. They can send and receive packets on specific sides, which allows writing custom switches/routers.

**Comment by alwaeles** [comment]
How I can do this ? Have you a doc ?

**Comment by MaHuJa** [comment]
I don't know if the microcontroller will work - probably does - but the server rack supposedly will (in internal mode).

It receives a packet, and then it can send a copy of it. There is, however, no way to keep from sending that copy back out where it came from as well. Note the new packet will have the 'firewall' as its address origin.

There's no "send on this side" or "received on this side" mechanic in the networking.

**Comment by dgelessus** [comment]
Okay, it seems that this is not really documented anywhere, but microcontrollers have methods to toggle network message sending for specific sides. I'll need to look into where exactly those can be accessed, since apparently microcontrollers do _not_ register an extra component like e. g. robots. Probably the `computer` component has those methods on a microcontroller.

(Not going to lie, I never actually used that functionality. I just knew it existed and assumed it was documented somewhere.)

**Comment by dgelessus** [comment]
Annnd I was wrong. All methods defined [here](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/common/tileentity/Microcontroller.scala#L80) are available on the `microcontroller` component. `setSideOpen` can be used to change on which sides network messages are sent, though it seems that there is no way to tell from which side a message comes.

How do I test these things? Like this!

``` lua
return modem.broadcast(1337, "for k, v in pairs(component.proxy(component.list('microcontroller')())) do modem.broadcast(1338, tostring(k), tostring(v)) end")
```

(Interactive testing on things with no real OS is hard...)

**Comment by fnuecke** [comment]
Indeed, you can use microcontrollers for that. Or servers.

Someone should really add the microcontroller stuff to the wiki :P
