### ISSUE TITLE
Crash in assembler with NEI search "upgrade"

### ISSUE THREAD

**Issue by CaitlynMainer** [MightyPirates/OpenComputers#1237]
Opened assembler GUI, typed "Upgrade" into NEI search crashed: http://paste.pc-logix.com/view/96256d59
Using OpenComputers-MC1.7.10-1.5.13.27-pre.1
NEI: NotEnoughItems-1.7.10-1.0.4.107

**Comment by fnuecke** [comment]
Looks like it's crashing because of a _very_ old driver, using a version of the OC API older than half a year or something (which is when the relevant parts of the API last changed).

**Comment by fnuecke** [comment]
OC will (well, should) now log a message telling you which driver it is that implements the old API instead of crashing.
