### ISSUE TITLE
Allow a print to have no collision box in the active state

### ISSUE THREAD

**Issue by MatthiasMann** [MightyPirates/OpenComputers#1238]
This would allow building large complex doors using prints

**Comment by Vexatos** [comment]
I guess keep the bounding box, but remove collision. Should be some reasonably expensive upgrade added by crafting.

**Comment by fnuecke** [comment]
Hrm, interesting, so have them behave like actual vanilla levers, for example?

While the suggested usecase of doors would be nicer if the bounding boxes would be gone completely, that could easily lead to... "lost" prints, which I'm not too keen on. Also, to have a second state it has to contains _something_, so the implementation I'm considering is having a flag for solidity/passability for both states, and to have them "vanish" require a transparent texture, basically. Is there one in vanilla MC? If not I guess I'll just make `transparent` a reserved texture name or something :P

**Comment by MatthiasMann** [comment]
a transparent texture sounds great - otherwise I would have used something like fuzed quartz.
