### ISSUE TITLE
Screen blank after leave

### ISSUE THREAD

**Issue by zzzzzx** [MightyPirates/OpenComputers#1239]
Screen blank after leave the computer. But the computer still on
code http://puu.sh/izrwg/d1fd351b4e.txt

only happen in server (the server use cauldron)
OpenComputers-MC1.7.10-1.5.12.26-universal.jar

**Comment by gjgfuj** [comment]
Syncing issues? Maybe? Or cauldron could have messed something up, as normal
.

**Comment by MyNameIsKodos** [comment]
If you can reproduce this without using Cauldron, that would be great.

**Comment by fnuecke** [comment]
Haven't had that pop up in quite a while. As suggested, could you please verify this also happens with a Forge server, and ideally that it still happens with 1.5.13/latest dev build? Thanks.

**Comment by payonel** [comment]
I've hit this. I run a forge server and have a case w/ monitor on one side and a server w/ monitor (only running 1 slot in rack) The case never loses screen, the server does. side by side, chunk loaded.
I have not pinpointed a repro, I can update this post if I do.
forge-1.7.10-10.13.3.1408-1.7.10-universal.jar
OpenComputers-MC1.7.10-1.5.13.27-pre.1-universal.jar

**Comment by fnuecke** [comment]
I saw it happen during BTM preparations and I tried patching this just before it went live :P Didn't see it happen again after that, so: could you please see if you still run into this in dev-builds 687 or higher? It might just be fixed/worked around now.

**Comment by Nex4rius** [comment]
I have the same bug on a server and on singleplayer.
https://www.youtube.com/watch?v=9PupwdrowKo&feature=youtu.be
The computer is still on and the programm is also working.
The screen shows stuff again after it gets updated from my programm.

OpenComputers-MC1.7.10-1.5.13.28-universal
Infitech2 modpack v3.1.3

**Comment by fnuecke** [comment]
As mentioned above, this may already be fixed. Unless you can also reproduce it in 1.5.14+ I'll not look into this anymore for now.

**Comment by Nex4rius** [comment]
Its fixed in singleplayer in 1.5.14 but still happens when I'm on a server.

**Comment by fnuecke** [comment]
Fixed a way screens could blank out until a first change, so I'm hoping this is fixed for good now.
