### ISSUE TITLE
robot.use() doesn't recognize the equipment slot is empty

### ISSUE THREAD

**Issue by Mr-Turing** [MightyPirates/OpenComputers#124]
Ex nihilo adds a block (sieve) that allows you to right click with gravel, sand or dust (added by it) to add it to the block, it doesn't have an inventory though, so suck, place or pipes/hoppers don't work.
robot.use() does though, it places the item in as expected and if used on a loop it`ll place and activate the block as a player would, just need to place a stack of items in the equipment slot.
Except, once the stack is over, it''ll keep using it, it'll still render the item as being held by the robot and if you place a new stack it'll remove however many ghost items it use.

inventory is now empty
http://i.imgur.com/vO74MBY.png
robot still using item
http://i.imgur.com/NYDVxJ3.png
place a stack in the equipment slot
http://i.imgur.com/Tu3l0fE.png
and it "deduces" the blocks it used while empty
http://i.imgur.com/6voG512.png

edit: link for Ex Nihilo mod page http://www.minecraftforum.net/topic/1981778-164forge-ex-nihilo-the-skyblock-companion-mod/

**Comment by fnuecke** [comment]
Interesting case, didn't consider the held stack could be changed in a block activation. Thanks for reporting!
