### ISSUE TITLE
Feature: add swap partition

### ISSUE THREAD

**Issue by kevinkk525** [MightyPirates/OpenComputers#1240]
Would it be possible to add a feature working like real swap partitions?
like insert a 2nd harddisk and format it as swap so the ram rises from original 3MB to as many harddisk as you have, so that e.g. 12MB are available. You could still limit that amount and say that the OC architecture only support a max of 12MB (like 32-bit systems only support 4GB).

**Comment by Vexatos** [comment]
Adding swap to an OS would be doable, however, it'd massively slow down the OS.

**Comment by gjgfuj** [comment]
That sounds like it'd horribly unbalance everything.

**Comment by kevinkk525** [comment]
why would it slow down the os if you have more RAM?

**Comment by gjgfuj** [comment]
He is referring to coding the swap functionality as part of the os in lua.

**Comment by GitBranch** [comment]
Sounds Unrealistic. I mean, Formatting Entire Hard Drives for Swap? Having a 1TB swap sounds absurd. And 1TB of RAM sounds even MORE absurd. Speaking of Hard Drives, do we have Partitions?

**Comment by kevinkk525** [comment]
well on your real PC you could create 1TB swap, would be stupid but doable. So with OC why not create 12MB swap (a limit could/must be coded of course). Of course this is probably a lot more work than adding another tier of RAM.

**Comment by MyNameIsKodos** [comment]
If you want more RAM, why not just adjust the configs?

**Comment by kevinkk525** [comment]
yeah that would be a dirty "solution". but only for a server i own. As I write programs that i publish, i want to have a normal environment. But it was just a suggestion, if it was not good, so be it.

**Comment by fnuecke** [comment]
While interesting, this would be so much effort to implement it's just not feasible. Doing actual physical swapping is virtually impossible, so let's disregard that completely. The alternative is to "lock down" a disk and increase the actually available RAM. But actual memory access speed can't be throttled, so the swap space would be just as fast as normal RAM, no downsides. Sure, component access speeds could be throttled, but that's pretty meh.

So, interesting idea, but not really feasible I'd say.
