### ISSUE TITLE
[1.8] Displayed charge on Tablets is also backwards

### ISSUE THREAD

**Issue by KurikAmudnil** [MightyPirates/OpenComputers#1241]
I have noticed that the displayed charge on tablets is also backwards (full shows empty bar, empty shows full bar).  Tested multiple versions of Forge, OC, and both Tiers of tablets.

currently using forge-1.8-11.14.3.1468, OC v1.5.12 / OC v1.5.13 Prerelease 1

**Comment by fnuecke** [comment]
Gah, missed that one. Thanks!
