### ISSUE TITLE
Documentation vs Tractor Beam upgrade in tablets

### ISSUE THREAD

**Issue by KurikAmudnil** [MightyPirates/OpenComputers#1242]
Tractor Beam upgrade is currently available to tablets, it works (sucked items go to player inventory), but the documentation only mentions robots/drones.  If this is intended behavior, then I think that the documentation should be updated.

**Comment by fnuecke** [comment]
That is working as intended, yes. In the ingame documentation (tooltip and manual) there's no mention of it _only_ working in robots/drones. If you're referring to the wiki, then by all means, please do clarify that (wiki is open for registration and can be edited by all users).
