### ISSUE TITLE
"Item Hoppers": Allow single-stack item movement

### ISSUE THREAD

**Issue by eslachance** [MightyPirates/OpenComputers#1244]
As has been discusssed: 
http://oc.cil.li/index.php?/topic/614-inventory-moving-accessing/
http://oc.cil.li/index.php?/topic/579-tiered-adapterblocks-with-more-upgrade-slots/

Essentially, the idea of giving the ability to move a single item stack from one location to the other that is adjacent (aka not through the network or the computer in any way) programmatically. This can either be with an Adapter + Inventory Controller Upgrade, or a new block that gives this possibility (but of course we would still need the ability to read inventory contents, so maybe a new upgrade inside a Tier 2 Adapter?)

This would enable some amount of auto-crafting, for example having a chest and an Inscriber to autocraft Circuits, which require something like 10 item movements between the chest and inscriber. This is, of course, the whole point, and stays within the philosophy of the mod assuming items are only moved to adjacent inventories and not through the network to a different adapter (or through a Linked card especially!).

**Comment by jansamohyl** [comment]
I'd love to have such "Inventory router" too. It wouldn't even need to output to inventory slots, just output the item from the side (for example into the pipe or other machine) should be sufficient.

There could also be upgraded version that would paint items for Buildcraft routing. That could greatly remove the need to program robots to move around the world and so it would simplify builds. (I am currently building an automated bee breeding system and this would really make it easier to move bees around.)

Although I haven't tried it, there is I believe CC Sorting Upgrade in Logistic Pipes, which let's you route items programmatically. But it's a hassle to build LP system just for a couple destinations.

**Comment by Kubuxu** [comment]
You can already paint  BC items. Just use gates with comparator upgrade and emit different strengths of signal.

And isn't there a config option to enable inventory manipulation?
Here: https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/application.conf#L1186

**Comment by gjgfuj** [comment]
Um... Can't you just use a robot. They don't have to move yknow.

**Comment by jansamohyl** [comment]
> You can already paint BC items

That's an interesting suggestion, but requires lots of tricky synchronization if you want to have more than one painting place.

> config option to enable inventory manipulation

Well, first I thought that it allows Adapter to work without Inventory Controller upgrade, so I missed this option. But I gave it a try and I can't get it to work. What upgrade do I need to put into the Adapter? I can't put in Inventory Upgrade. Without Inventory Controller nothing happens, with Inventory Controller I get the same functions (reading items only) regardless of the option setting.

> Can't you just use a robot. They don't have to move yknow.

Cost and flexibilty aside, with computer you could easily control more than one "inventory router". With robots you would need multiple, setup some networking, etc. Perhaps it's easy but sounds a bit more complicated for my taste.

Anyway, thanks for suggestions!

**Comment by Voidi** [comment]
Just want to mention that normal item sorting solutions do not cover very special cases.
For example: I want to move rf chargeable items that are not fully loaded in a charger.
To achieve this i read the NBT Data via Converter and if energy < maxenergy i move the item.

**Comment by UltraHex** [comment]
There is this: https://github.com/thraaawn/CCFactoryManager
