### ISSUE TITLE
Not overriding certain F-key functionaity

### ISSUE THREAD

**Issue by magik6k** [MightyPirates/OpenComputers#1245]
Most of function keys work fine except F2, F6, F11, which still have their actions and they still push keydown/up signals.

**Comment by fnuecke** [comment]
So here's the problem: from what I can see, I can either disable all of that, or none of it, since all of it is handled in one callback in MC itself. And I really don't like removing F2 / screenshotting, since that's proved tremendously helpful for debugging.

Thoughts?

**Comment by payonel** [comment]
I don't think we should be interception more mc key hits - there are plenty of key events we do get

**Comment by skyem123** [comment]
maybe just make OC input ignore certain keys that are known to be used by Minecraft, such as F2?
