### ISSUE TITLE
Multi-Computer Screen Graphical Spazzing

### ISSUE THREAD

**Issue by lucian2004** [MightyPirates/OpenComputers#1247]
When **connecting multiple computer cases** via cable, then linking that to a screen, the screen will glitch and sometimes spaz out.

**Comment by gjgfuj** [comment]
Well... Yeah. Both computers are trying to write to the screen. It'd mess
everything up.

**Comment by lucian2004** [comment]
I know. It would be nice if they could make a system to access more than one computers on a screen, though.

**Comment by gjgfuj** [comment]
You could write one? Yknow, there's a lot of capabilities there.

**Comment by lucian2004** [comment]
I could, but I need to learn more about Lua and OpenComputers. I'm still a pretty big noob at it.

**Comment by fnuecke** [comment]
Well, then take it to the forums ;-) This is not a bug and not something that'll change anytime soon, so you'll have to learn how to work around it. And the issue tracker is not for that kind of support, that's what the forums are for.

**Comment by lucian2004** [comment]
I know. I'll check out the forums
