### ISSUE TITLE
Using Raid - multiple issues..

### ISSUE THREAD

**Issue by prozacgod** [MightyPirates/OpenComputers#1249]
... so I guess there's not good instructions on how to raid/peripheral interactions etc.....

I have [keyboard]->[monitor]->[computer]->[raid]->[computer]->[monitor]->[keyboard]

The raid has openos installed and I'm booting off of it.

If I try to boot a computer, the left screen gets bound during bios/init steps then the right screen for terminal access or vice versa

okay, well ... I looked at init.lua and realized that it prioritized screens with keyboards, slapped a keyboard on one, and viola! it uses that screen/keyboard.

Then you try to boot the other, and .... I'm no longer sure what's happening...

okay so keyboards off slap keyboard on left screen, boot left computer... binding complete....

remove keyboard, slap keyboard on right monitor boot right computer... booting works!!

okay type on keyboard... oh for the love of .....

it's typing on both machines simultanously.

raid is not very useful, if it propagates peripheral messages ... oooorrr maybe I'm hooking it up wrong, but I don't know how else to do it.

**Comment by LizzyTrickster** [comment]
RAIDs do act as cables, if you want to share raids you're going to need to do some advanced networking for it

**Comment by prozacgod** [comment]
Where would there be documentation for connecting a raid device to 2 machines, in a way that doesn't propagate message through it?  Or do you have a few pointers to throw my way, there doesn't seem to be an obvious solution.

My initial thought was to somehow force the binding of the screens/keyboards is that the appropriate way to handle it>

**Comment by natedogith1** [comment]
There isn't a way to connect a RAID to 2 machines, unless you want to do networked file systems.
I'd also think that binding the screens/keyboards would be a good idea, however OpenOS largely doesn't pay attention to whether or not an event comes from a primary device. (as a matter of fact, it seems that term.read fails if _any_ non-primary device queues an event).

The simplest way I can think of would be to override event.pull or computer.pullSignal to ignore events from a non-primary keyboard.

**Comment by fnuecke** [comment]
The raid is working as intended, if you're unhappy with the wording in the tooltips/documentation, by all means make a suggestion to change it, e.g. make a pull request :)
