### ISSUE TITLE
Servers not useing power?

### ISSUE THREAD

**Issue by MFernflower** [MightyPirates/OpenComputers#125]
That is all.

**Comment by fnuecke** [comment]
Can't reproduce. What setup do you have (screenshots), what mods, ...?

**Comment by MFernflower** [comment]
The server will still boot even if it says 0 power. 
Does the system check if your in creative or survival, if it does then I am a derp. But if it doesn't, I tried connecting to a TE system to it with and without a power converter. This is on mc 1.6.4

**Comment by fnuecke** [comment]
OC doesn't check for creative mode, no. It does however require UE3 Core to accept power from all the other mods (which I mentioned pretty much everywhere). There should even be a message on login if it's missing (the mod goes to 'ignorePower' mode if UE3 Core isn't present, so robots and normal computers should also start up without power, for example). If that isn't it, I have no idea what's going on.

**Comment by MFernflower** [comment]
ok
