### ISSUE TITLE
Swappable EEPROM for drones

### ISSUE THREAD

**Issue by eslachance** [MightyPirates/OpenComputers#1253]
Would it be possible to implement the ability to remove and replace the EEPROM in a Drone? It seems somewhat counter-intitive to have to deconstruct a drone to modify its programming - there's been removable media in mobile devices and electronics since... forever.

Alternatively, there could be the ability to remove specific parts in the constructor or deconstructor, so as to change its parts individually. Like tinkering with an actual drone in a workbench ;)

**Comment by Vexatos** [comment]
Can't you just right click a drone with a new EEPROM to swap it?

**Comment by fnuecke** [comment]
The right-click to insert thing only works with Microcontrollers IIRC, but as with pretty much all devices you can craft it with another EEPROM to install that one (and get the one in it, if any, back).
