### ISSUE TITLE
Power Converter not Accepting Energy

### ISSUE THREAD

**Issue by shelbykauth** [MightyPirates/OpenComputers#1254]
I might just be doing it wrong, but I don't know.  I just started playing around with OpenComputers, and have become very frustrated with the power issues.  I tried buildcraft but decided that I didn't like the crafting recipes.  I switched over to IC2, and found that I like the recipes better, so I'm going to stick with that.

I am playing mostly in survival, peaceful.  But I do have cheats on and I give myself 9 stacks of every raw material I need, then continue in survival.
I built a tier-1 computer, complete with keyboard.  I built a bunch of capacitors, OC cables, and one power converter.  After switching to IC2, I built a batbox and a generator.
I was able to power the converter, before I put a batbox in, but then it stopped powering.  Currently, I have a full batbox and am trying to move power into the converter, but I'm not familiar enough with IC2 to know if I'm doing that wrong or messing up on the OC end.

Any help would be appreciated (including moving this to a better location if need be).

**Comment by fnuecke** [comment]
As far as OC is concerned, any power accepting block (those that mention how fast they can accept energy in the tooltip, so not only the converter but also computers and some others) can be hooked up directly to whatever emits energy in all the supported energy mods (which are... most of them, I'd say). So for IC2 connecting a wire or batbox/MFE/MFSU to those blocks should "just work" (and did last time I checked). Try breaking and re-placing the batbox/power converter. If you're using a batbox or such, make sure you're connecting to the right face. Post some screenshots and the exact versions of the mods.

**Comment by shelbykauth** [comment]
Yeah... I'm sorry.  After reading about 5 tutorials on IC2, I finally found one pointing out that a batbox accepts energy in on 5 sides, but only sends energy out one face.  Thank you, though!

**Comment by fnuecke** [comment]
No worries :-)

**Comment by cincpac1967** [comment]
Hi. I have a similar problem. I am running Minecraft 1.10.2 and OC 1.6.0.2-beta4. IC2 cables do not connect to the power converter. I have tried using a batbox directly, with the output face connected to the power converter, and directly to a computer, with no luck. 
![snap](https://cloud.githubusercontent.com/assets/24752982/21467089/599ec036-c9af-11e6-8c41-81dbc8588376.jpg)

**Comment by xarses** [comment]
Update to latest. If it's still a problem create a new issue.
