### ISSUE TITLE
OpenComputer can't boot with Screen Controller from RFTools

### ISSUE THREAD

**Issue by feldim2425** [MightyPirates/OpenComputers#1255]
I don't know if it is a Issue in RFTools or OC but if I start a Computer from OC with a Screen Controller it says "Unrecoerable Error machine:1146: no such method" on the Computer Screen.
If I first start the Computer and then connect the Controller it works fine.

RFTools 3.10
OC 1.5.13

**Comment by Vexatos** [comment]
@McJty may or may not have called its Screen Controller component `"screen"` instead of the more obvious `"screen_controller"`...

**Comment by McJty** [comment]
The component name is "screen_controller". Is that wrong?

**Comment by fnuecke** [comment]
Nah, OpenOS/I'm at fault here; `component.list` (and hence primaries) by default return the the component of which the name _starts with_ the requested component name. So I'll have to go through OpenOS and replace all the `component.list(blah)` calls with `component.list(blah, true)` to enforce exact matching. I'll look into it in the evening.
