### ISSUE TITLE
Errors running the class transformer (1.7.10)

### ISSUE THREAD

**Issue by NoX-programer** [MightyPirates/OpenComputers#1256]
The mod asked me to submit the server FML log due to errors. Here is the log: http://rghost.ru/6hx4nzrlq
I was cut it to the time 1st player connected. Please ignore the fact, that server core is KCauldron-1.7.10-1448.121-server.jar - because I have the same warning when server core was Forge.

**Comment by fnuecke** [comment]
Update to 1.5.13, should already be fixed.
