### ISSUE TITLE
Make default RAM values for 64-bit and downscale for 32-bit

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#1257]
We're on the 64-bit era, so we should expect 64-bit by default. Downscale as needed.

**Comment by Kubuxu** [comment]
What is the difference apart from breaking configs?

**Comment by SoniEx2** [comment]
How about, migrating to being primarily 64-bit?

I mean, pretty much every professional Minecraft server out there is 64-bit already. (if yours isn't, run...)

**Comment by Kubuxu** [comment]
It is doing breaking change for sake of doing it.

**Comment by dgelessus** [comment]
The change isn't totally useless - at the moment if you're running the game on a 64-bit JVM (which you REALLY REALLY should be) and want to know how much actual RAM 256 KB of in-game RAM uses, you need to factor in the 64-bit upscaling. Because most people are using 64-bit Java, this upscaling needs to happen more often than not, it's only reasonable to use 64-bit as the standard and provide 32-bit backwards compatibility.

The change wouldn't be breaking either, to convert the upscaling-to-64-bit factor to a downscaling-to-32-bit one, invert it (1/x).

**Comment by Kubuxu** [comment]
@dgelessus Point is that you don't have to know how much exactly 256kB takes because LuaC and MC compact take much more.

**Comment by fnuecke** [comment]
It's not that necessarily breaking, because the config is versioned, so I can just force new values if this gets in; it'll only be breaking for those that previously increased the limit and rely on that. If at all, this might make it in in OC 1.6.

**Comment by SoniEx2** [comment]
You can still update the old configs by doing the 1/x thing, I think. Maybe also change the config values for the RAM amounts. (It only breaks downgrading.)

**Comment by dgelessus** [comment]
(yay for necrobump)

Here are some quick numbers on how the change would affect the RAM sizes, assuming an upscaling factor of 1.8 (the default).

| Tier | 1 | 1.5 | 2 | 2.5 | 3 | 3.5 |
| --- | --- | --- | --- | --- | --- | --- |
| Native 32-bit | 192 | 256 | 384 | 512 | 768 | 1024 |
| Upscaled to 64-bit | 345.6 | 460.8 | 691.2 | 921.6 | 1382.4 | 1843.2 |
| Suggestions for native 64-bit | 384 | 512 | 768 | 1024 | 1536 | 2048 |
| Downscaled to 32-bit (rounded) | 213.3 | 284.4 | 426.7 | 568.9 | 853.3 | 1137.8 |

**Comment by SoniEx2** [comment]
Just automagically update the old configs. But yeah I think those are good new defaults. :+1:

**Comment by payonel** [comment]
reviewing old tickets: this doesn't add much user experience. testing lua vms myself and measuring the memory load per oc instance actually maps incredible close as it currently stands

**Comment by SoniEx2** [comment]
64-bit should be the default, not 32-bit.
