### ISSUE TITLE
robot:invisible block

### ISSUE THREAD

**Issue by ewmiter** [MightyPirates/OpenComputers#1258]
hello I was playing around with robots and I found a bug. when I try to go up to a specific block with robot.up() it returns "imposable move" and it fails even though there is nothing above it. help me!

**Comment by Vexatos** [comment]
See [this](https://github.com/MightyPirates/OpenComputers/issues/1113#issuecomment-97731965).

**Comment by ewmiter** [comment]
thanks this helped alot
