### ISSUE TITLE
server crashes upon connection of power converter to TE network (Screenshot and crash report)

### ISSUE THREAD

**Issue by MFernflower** [MightyPirates/OpenComputers#126]
Whenever I do this:
![2014-02-20_12 09 58](https://f.cloud.github.com/assets/3164942/2220829/1665aaa8-9a52-11e3-8c15-aef199d0600a.png)

I crash with this error (server-side only):
(This is on forge 965)

http://pastie.org/8752627

**Comment by Belgabor** [comment]
Why was this closed? I don't see any reference that it's fixed and the same thing just happened to me so it doesn't seem to be a one-time issue.

**Comment by fnuecke** [comment]
Was discussed on IRC, it had already been resolved with #122, but that's still only in the dev builds, hence the report (I'll push 1.2.1 soon, probably tomorrow).

**Comment by Belgabor** [comment]
Literally just meant to report that =)
Saw #122 and installed the dev build to test.
