### ISSUE TITLE
Question: Minecraft 1.8 build - which power should...could I use?

### ISSUE THREAD

**Issue by C0rish** [MightyPirates/OpenComputers#1260]
The minecraft 1.8 build of this mod runs smooth for me, but the supported power mods are all 1.7.10... so how can I power the computers?

I mean (its the first time I use this mod)... there seems to be a dependency on other "not 1.8 mods", which makes this mod... unplayable?

Or do I understand something wrong :)

**Comment by Kubuxu** [comment]
If there are no power mods computers do not require power. There is also config option to disable power manually.

**Comment by Soultron** [comment]
If I might add.. The 1.8 version of Progressive Automation has an RF
generator.  Use FluxDucts to get it there.  Also here in an update or so
there will be support for Power Advantage which has its own form of energy.

**Comment by fnuecke** [comment]
Yup, nothing more I could add to the above :)
