### ISSUE TITLE
[SEVERE] [BUG] Textures highly broken

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1261]
I'm running OpenComputers on OS X 10.10.3, Java 8 Update 45 (Note: Had to run Minecraft from the command line (`java -jar /Applications/Minecraft.app/Contents/Resources/Java/Bootstrap.jar`) to get it to run under Update 45). When I open the OpenComputers tab in Creative mode, this horrible mess of broken textures pops up:
![oc-bug](https://cloud.githubusercontent.com/assets/2061796/8492269/5c111100-2115-11e5-9490-da0a137bb02c.png)
It seems to be taking from random text I've seen in Safari recently... I'm not sure how.

**Comment by fnuecke** [comment]
This seems to be an [issue with Minecraft / Forge](https://github.com/MinecraftForge/MinecraftForge/issues/1829), nothing I can do about it I don't think.
