### ISSUE TITLE
[suggestion] new piston upgrade features!

### ISSUE THREAD

**Issue by n00b7** [MightyPirates/OpenComputers#1262]
i think adding a few new functions to the piston upgrade would be great so i want a
function that pulls a block within a block radius of 2 
microcontrollers will only pull toward there front
drones will pull towards any side
robots will pull towads the front
component.piston.pull()
and
computers should be able
to use pistons if an adapter has a piston upgrade installed in its database and
pistons are connected
and 
the tier 2 piston upgrade in the database would controll both pistons and sticky pistons
so thats all

**Comment by fnuecke** [comment]
Hrm so kind of a sticky-piston upgrade? Maybe.

**Comment by n00b7** [comment]
one that pushes and pulls things using 
component.piston.push()
and component.piston.pull()
which will pick up a block within a block radius of two
microcontrollers will pull from the front sides
drones will pull from any side
robots will pull from the front

if you read the whole thing both  upgrades have a usage in the adapter

**Comment by n00b7** [comment]
https://github.com/MightyPirates/OpenComputers/labels/feature-suggested

**Comment by TheRealOrangus** [comment]
Would be nice if you'll add both:
Sticky-piston upgrade and Piston upgrade(tier 2) which compounds features of both Sticky-piston upgrade, and Piston upgrade(tier 1).

**Comment by Doyan** [comment]
With a reservation for the case that I just haven't looked hard enough... But anyway, what I can see from the manual and the method description of the piston upgrade there is currently no way to push in the y-axis. Is there a deliberate reason for this? If not then I think it would be a nice feature to have, maybe something like component.piston.push(side) in a manner similar to the component.robot.compare and detect methods?

**Comment by fnuecke** [comment]
Hrm, I can't remember that being a deliberate choice. I'll add a parameter to allow front/down/up.
Tho down wont work in tablets held by players, because it's based on eye-height, and I won't add special case stuff for that, just so you're warned :p

Edit: actually, I might... because I still need special handling for drones anyway >_>
Edit 2: and done.

**Comment by n00b7** [comment]
what if the syntax for push and pull is like
pull(side)
push(side)

**Comment by n00b7** [comment]
ok i know what your talking about cause im uh java dev
eg, case 0;

**Comment by fnuecke** [comment]
@n00b7 please stop making comments that do not contribute to the discussion. And on that note, don't open zero-effort issues. If you keep this going I will block you.

**Comment by payonel** [comment]
closed by #61ad60b97353b538dcd42113fe134c7b66ad6e33
