### ISSUE TITLE
pipe loses arguments when  intermediate does not io.write anything

### ISSUE THREAD

**Issue by payonel** [MightyPirates/OpenComputers#1263]
if you have 3 programs (compatible with the io input and ouput for piping): p1, p2, and p3
and p2 does NOT write anything via io.write, not even an empty string
then p3 does not see the correct command line arguments, but instead sees p1's

e.g.
p1 a | p2 | p3 b
p3 will see 'a' and not 'b' as the 1 and only command line argument

if p2 simply calls io.write(""), then p3 sees 'b'

**Comment by fnuecke** [comment]
Closed via b60c784eedfc822386f46cd4ba51a06db5d752c0.
