### ISSUE TITLE
quiet preceding commands in pipe never resume subsequent commands

### ISSUE THREAD

**Issue by payonel** [MightyPirates/OpenComputers#1265]
This is similar to issue #1263 which was closed by commit b60c784
In this case consider: p1 | p2
where p1 does a read, and no output, and p2 has output and then a read
Well, because p1 gets to a non-piped read, it waits for user input and p2 never is resumed

I actually have a fix...which also would have resolved issue #1263 with less code!
I'll make the PR soon and reference this issue

**Comment by fnuecke** [comment]
Closed via 6683a5bd493297eb8eb978e6c33331c5e5dbdede. Thanks again!
