### ISSUE TITLE
piped commands that end early break preceding commands from further output

### ISSUE THREAD

**Issue by payonel** [MightyPirates/OpenComputers#1267]
p1 | p2
where p1 outputs multiple strings but p2 reads only 1 and ends (coroutine dead) causes p1 to set its memoryStream.closed = true
subsequent calls from p1 to io.write will error that you should not write to an closed stream
however, p1 should be able to write all it wants - and the values should be thrown away (not buffered)

**Comment by fnuecke** [comment]
Closed via 6683a5bd493297eb8eb978e6c33331c5e5dbdede. Thanks again!
