### ISSUE TITLE
3D Prints and Tools (and more?)

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1270]
So, since I read that it would be hard to balance 3D Printed tools...
I think most people just care about the visuals, customized looking tools (possibly even armor?) and not so much about printing tools that would have different stats depending on shape (or even predefined stats by OC).
So just having the abiility to craft:
`<any tool A>`  + `<any print B>` = `<A with visuals of B>`
would be pretty nice... should ideally support TiCon tools too, if possible :)

As said, could extend the same idea to armor even.

**Comment by Vexatos** [comment]
Maybe an option to make it render like a tool, but do nothing else? It would be a completely useless tool (it's plastic), but it'd look like one so it'd be a nice piece of decoration.

Maybe a `setType()` with "block", "tool", "helmet", "chestplate", "leggings" and "boots"? It'd really just change the way/place it's rendered/the armour slot it may go in (and whether it's place-able), nothing else.

**Comment by gjgfuj** [comment]
3d printed armor++

**Comment by Inari-Whitebear** [comment]
Wonder if Armor would need a bigger shape count though xD

**Comment by gjgfuj** [comment]
Armor and tools wouldn't need anywhere near the limit blocks have. They'd
only get rendered when equipped and all.

**Comment by fnuecke** [comment]
They wouldn't be rendered as efficiently as static in-world blocks without a good amount of work, though. Just keep that in mind. Aside from that, crafting it together with something will work for simple tools, but wrapping more complex items, i.e. forwarding all the calls and such except for rendering... could get messy. If there's a hook for rendering contents of equipment slots, maybe "social slots" as are common in lots of MMOs (and even Terraria) could be an option? If there's a mod that adds that already, even better, then the prints really just can do near to nothing on their own :P

**Comment by Vexatos** [comment]
Armourer's Workshop has Tool/Armour overlays. You might be able to use those but I'd still suggest tools and armour being virtually useless (no properties, but also no durability), so they'd only be for decoration. It would save quite a bit of effort trying to make them craftable with actual tools/armour.

**Comment by Inari-Whitebear** [comment]
Yeah, but needing another mod that no modpack ever has would be kinda pointless then :P

**Comment by gjgfuj** [comment]
The helmet slot at least will render any block that's put into it by
default.

**Comment by payonel** [comment]
reviewing old tickets - 3d print features abound and this one is interesting but I given the age of this ticket and the pace on oc things ... it would be best to close this
