### ISSUE TITLE
Toggle cable thinger

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#1273]
So, while @Vexatos' solution at BTM was awesome in its own right, it's probably a good idea to provide an easier way of connecting / disconnecting subnets without breaking blocks. Basically two ideas are currently being considered:
- Have a block that can be toggled using redstone, in one state it acts as a cable, in the other it... doesn't. As in, it disconnects the networks on its different sides.
- Have something slightly more involved, like a KVM switch, where applying redstone toggles which sides get connected to each other (e.g. one fixed "input" side, other five sides are cycled per redstone pulse / selected via signal strength).

I'm strongly leaning towards the former, mostly because it'd be much easier to implement, and can be used to cover the second use-case by simply throwing more of them at the problem.

Feedback welcome.

**Comment by dgelessus** [comment]
I'd vote for the first variant. BuildCraft's Iron Pipes had switch-output-side-on-redstone-pulse back in ye olde Beta 1.6 days, that was a terrible mess and made it impossible to use redstone to control them. In most cases you had three sides, one input and two outputs, but the dumb pipe couldn't tell the difference and kept cycling through all three. And analog signals aren't very usable either. The second option would be better done as a component, but I'd consider that "too meta". :P

By the way, what is this BTM thing you keep talking about? I feel like I've missed something.

**Comment by Techokami** [comment]
Seconding the question about BTM. What the heck was that???

**Comment by fnuecke** [comment]
[BetterThanMinecon](http://asie.pl/btm15.html).

**Comment by Vexatos** [comment]
I would also vote for the former solution.

**Comment by fnuecke** [comment]
Oh, also: naming. If you have any naming ideas, let me know. Current candidates are 
- toggle cable
- impenetrable firewall
- network controller
- network splitter (aka *.net *.splitter :P)
- network partitioner

**Comment by LizzyTrickster** [comment]
Quantum Cable Detacher

**Comment by Vexatos** [comment]
I vote for "Impenetrable Firewall".

**Comment by magik6k** [comment]
I'd like to see the former, but I can imagine a KVM switch as upgrade for the switch as more complex alternative(Dunno if possible to implement). If it would turn out to be possible, connecting inserted network cards to created networks would be really neat.

**Comment by fnuecke** [comment]
Sudden idea I got earlier today, which might be a nice in-between of the two: the former, essentially (pure toggle), but allow toggling the sides using a wrench. Redstone signal inverts connectivity of all sides. That should still be simple enough, IMHO, but offer a good bit more flexibility.

**Comment by dgelessus** [comment]
So with a scrench you can flip individual sides, and with redstone you can flip all at once?

**Comment by fnuecke** [comment]
That'd be the idea, yes. I feel like that's a good middle ground between what robot+dye offers and a script-all-the-things block.
