### ISSUE TITLE
Possibility to play minecraft sounds

### ISSUE THREAD

**Issue by Voidi** [MightyPirates/OpenComputers#1274]
After watching this [Sheep with Drones over the shoulder](https://youtu.be/GbAV2_L0ZyI?t=28s).
Can we have something that play a selectable minecraft sounds like the sounds of mobs and walking?
Maybe as a upgrade?

**Comment by MyNameIsKodos** [comment]
This is possible with an addon called MassSound.  Tagging @gamax92 because that's his addon.

EDIT: Seeing as gamax hasn't responded, here's the link https://github.com/gamax92/masssound
