### ISSUE TITLE
Add newlines to sha256sum, md5sum, etc for readability

### ISSUE THREAD

**Issue by MyNameIsKodos** [MightyPirates/OpenComputers#1275]
I was going to PR this in, but I wasn't sure which branch to use, which files all needed the newlines, etc.

As it stands, it looks like http://puu.sh/iRfPk/7483976908.png but I tested with md5sum.lua and a '\n' is all that's needed at the end, just concate it on.

EDIT: I should note that the newline is needed since you can check multiple files at once, e.g. md5sum /bin/*

**Comment by Mrrraou** [comment]
The same thing should be done on sha256sum.lua, btw

**Comment by fnuecke** [comment]
Hrm, @Kubuxu seems to have deliberately used `\t`. Do the "normal" versions of those (i.e. what you'd find in a Linux distribution) use tabs or newlines?

**Comment by Mrrraou** [comment]
![951e6592fa](https://cloud.githubusercontent.com/assets/12371401/8605879/6f373520-2688-11e5-983b-42460098e3e8.png)
Seems like they use newlines.
On the md5sum source (main function, it is such a mess to read...):
![056afe4f59](https://cloud.githubusercontent.com/assets/12371401/8606151/27741f8a-268a-11e5-86fa-5e82773c282e.png)

**Comment by fnuecke** [comment]
Oh hang on, I reading comprehension failed again. The `\t` is between hash and filename. Yeah, looks like the `\n` is missing at the end there. I'll add it.

**Comment by Kubuxu** [comment]
Yeah, I was using `print` at first which adds `\n` on default then switched to `io.write`.
