### ISSUE TITLE
os.date() errors on day 365

### ISSUE THREAD

**Issue by Mrrraou** [MightyPirates/OpenComputers#1278]
The day number is the one NEI says when you change time.
![066896665a](https://cloud.githubusercontent.com/assets/12371401/8596606/a681302c-2650-11e5-8295-ff163ad2f32b.png)
The day 364 is 12-31-1970 and the day 366 is 1-1-1971.
There must be an error in the date parsing function.

**Comment by fnuecke** [comment]
Congratulations, you found OC's Y2K!

...

Allright, allright, it's a bug. I'll look into it.
