### ISSUE TITLE
Changing the component limit to make sense.

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1279]
So, since our total number of components can already be higher than the number of active components (with having a robot that breaks/places cables, or if #1277 gets in), and I don't quite like how it seems to be a magically working limit... here's an idea to discuss.

(activated below meaning "attached, seen by the old component function, and usable")

I'm not fully sure what the best way would be to do that, but I think one way would be:
machine.lua:
- component.active is a table of 16 keys ranging from 1 to 16.  entries may be nil. It represents the addresses that are currently activated (and thus can be seen by component.list, used by component.proxy, component.invoke etc)
- a new function (component.scan? component.explore?) that can explore and list all connected (active and not active) components, and their types and return the data. probably with the same filter option that component.list and such have
- activating and deactivating components... been thinking about how to do that, was wondering if you would just stick their addresses into the component.active table and they get activated... but maybe have a component.load(address) and component.unload(address) (or .activate/.deactivate) function would be better

Anyway, OpenOS could handle activating new components automatically, and just not activate more if theres already enough to be at the component limit. That way old software also wouldn't break (except for hardware-level software or other OSes). 
It would imo be a good way to have PCs be able to only use X components at once, but still be able to switch for other components (while deactivating the unused ones). Which can already be done with cable destroying and such, but this would be nicer. It also gives the address limit a reason for being there (limit address memory/ports/something in the PC) rather than just being enforced by scala for no obvious reason.

**Comment by gjgfuj** [comment]
I like the overloading....

**Comment by Vexatos** [comment]
it is not a "magical limit" per se... Think of it as a limited number of USB ports on your computer case, and cables being bundles of USB wire. You can add component buses to your server to increase the number of components, i.e. "add more USB ports".
Furthermore, you are rarely ever going to use all connected components at once, so removing this hard limit would really remove quite a big balance point (and a huge advantage for server racks).

**Comment by fnuecke** [comment]
The reason is, as Vex points out, one of balance. It's why higher tier engines generate more energy in other mods. It's why higher tier tools have more durability. So no, I really don't want to remove those limits, and in the progress make a part of the mod _truly_ pointless.

That said, if/when #1273 gets implemented one can, with a sane amount of effort, and not quite as "hacky" as with cable replacing/-coloring, implement this component switching on a hardware level, by having a redstone i/o or device with redstone card next to one of those new blocks.
