### ISSUE TITLE
Allow upgrading robots

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#128]
Implement some mechanic to make it possible to increase the amount of RAM in robots. Maybe even allow a built-in hard drive?

One possibility would be to craft a robot together with the item to upgrade it with. Not too keen on that, because I don't like crafting handlers all that much (due to how I'd like to implement storing the upgrades that'd be necessary).
Alternatively there could be a new block - let's call it the Upgrade Station [WIP] for now - that would work kind of like an anvil, except that it'd take a robot instead of tools and a component (e.g. RAM) instead of a book. And quite possibly require some time to finish the upgrade and consume (quite a bit of) energy while applying it.

**Comment by rmellema** [comment]
I like the idea of an Upgrade Station. Maybe make it like an enchantment table for robots, possibly dependent on their level(without consuming it, since you can only upgrade once I guess) and other upgrades they have.

**Comment by Belgabor** [comment]
I agree. Further upgrade ideas:
- More internal upgrade/extension/tool slots
- Self-modification upgrade (ref #87)
- Use component upgrade and/or inventory interaction upgrade (like openperipheral chests)
- Storage upgrade

**Comment by fnuecke** [comment]
## Robot overhaul

This has been talked about on the IRC a little. I'm planning to rework how robots work / are built in version 1.3. The goal is to make them more customizable, and therefore more flexible. This particularly includes things like RAM and storage, which is very limited in the current implementation. Allowing you to place RAM in the upgrade slot is really just a stopgap solution.

Here is how it could work: there would be a new block, the Robot Assembler (name subject to change), which would be used to 'configure' robot and then assemble it into the actual robot. This is a - very early - mockup of how its GUI might look:
![Robot Assembler](http://i.imgur.com/DWvSeS6.png)

The concept would be: place a normal computer case in the center slot. This determines how many card, RAM, HDD and upgrade slots there are. In addition, there would be a "complexity" limit (simlar to StevesCarts), meaning you can place potentially fewer items in there as there are slots. For example, if the basic case were to provide a complexity limit of 5, and an item would introduce as much complexity as its tier, you could put in 1 CPU, 2 RAM, 1 Card and 1 HDD, but nothing more than that. No second card or HDD, no upgrades. These are not the final numbers by any means, it's something I'd like to have a discussion about, actually. A display for the current vs. total complexity is missing in the mockup, but would of course be present.

Once configured, assembling would take a little while, and require some energy, the actual amount depending on the robot's complexity.

All the parts in that GUI will hard-wired into the constructed robot. They cannot be removed dynamically. There would be an option to disassemble a robot - with some chance of parts breaking in the process (similar to Modular Powersuits' salvage functionality).

_However_, there would then be 'upgrades' that allow housing items that can be hot-swapped. For example, there would be an upgrade that allows inserting/removing cards, floppies and upgrades the way it is now possible in robots. These upgrades could come in the three tiers, and would introduce more complexity than hard-wiring an item of the equivalent tier (twice?).
You can see that three of the upgrade slots in the GUI are 'separate'. Those would be for those 'wrapper' upgrades. They'd be limited to three (for all tiers) so I don't have to change the robot GUI ;-) (subject to change, but I think that is enough flexibility, and forces people to build more specialized robots, which is what I want to encourage).

All in all, the 'complexity' system would serve as the balancing factor, forcing people to build either more flexible robots with fewer slots, or more specialized ones with more functionality.

Robots would _always_ have a (single) 'dynamic' tool slot. I don't think this should be changed to be an upgrade. If you feel differently, let me know and why!

Some open questions:
- What happens to a robots' XP when it is disassembled?
- Allow adding components to a robot without disassembling it first?
- What should be configurable. "All the things" might be overkill, and more importantly require major changes to the GUI code, but I'll keep an open mind on that for now. Some possibilities include:
  - Inventory
  - Display / Screen
  - Experience
  - Energy storage
  
  What I mean by that is, that unless an appropriate upgrade is not installed in the robot, these systems will not be available. So if the robot does not have an inventory upgrade, it won't have an inventory (aside from the tool slot or slots for other swappable components). If it doesn't have a screen upgrade the screen in the GUI will not display anything/will not be present. If the energy storage upgrade is not present, the energy capacity will be tiny (that of normal computers, 500 per default I think). You get the idea.

There have been some other ideas discussed previously, but this is what I'm currently planning to do. I'd be happy for some feedback and suggestions before I get started, though, which is why I'm posting this. Input on this is more than welcome. Since it's a pretty major and potentially breaking change, let's try to do it right. Thanks! :-)

**Comment by rmellema** [comment]
I like this idea. Gives a lot of flexibility and allows people to build robots "their way"(slave robots in a dynamic system don't need GUI's). Still I would like to propose a slightly different system, with the reasoning behind it while I answer your question. 

The Robot assembler stays the same, but instead of building whole robots, it builds robot cases, which cannot be edited after they are created. They hold things like the computer case and screens for example. Kinda like how you create tools in a crafting table. Once a tool is there, you can change it a little, but a pickaxe will never become a sword. 

Then there should be a robot workstation, that can take a robot case(with or without cards) that can change the internals of the case. So you create a case in the robot assembler and you stick the cards in a case in the robot workstation. A robot can be disassembled into its components, but a case will always stay the same. 

This does introduce a new point, what should be part of the case and what should be changeable after creation? I don't have answers for that yet, but certainly someone can find good arguments for specific upgrades.

If XP is going to be an upgrade, the XP should be stored in said upgrade and stay there, even if the robot is disassembled. So the XP should go on the card, which can be reused in other configurations/robots. This could lead to grind farms for robots, but that is fun in its own right :P A solution to that could be skills, so task specific XP.

The robot workbench idea would allow you to insert certain components, while others can't be added. Consider, for example, a screen. Adding one would be impossible since you would have to drill a hole in the robot. Removing a navigation upgrade or an internet card would still be fine though.

**Comment by fnuecke** [comment]
Hmm, what's the advantage over the 'hot-swap-slot' upgrades and disassembling+reassembling the robot? It seems like simply adding another step to me? Hmm, or would that be like what I wrote but instead of being able to hot-swap things on the fly (in the hot-swap upgrades) you'd need the workbench?

As for the XP, having that stored in the upgrade sounds good. Going more in depth there _could_ be interesting, but designing skilltrees is a lot of work, and I'm not sure if enough interesting ones are possible to make it worth it. If there are, this could be a really fun "minigame" though!

**Comment by rmellema** [comment]
The advantage is that you don't need to drag the robot to a robot workstation every time you want to change something. The workstations could be expensive and the reassembling/disassembling could take time. And since most of the blocks in OC require energy, the workstation could use energy as well.

**Comment by fnuecke** [comment]
To clarify, do you mean it'd be too easy/cheap to be able to just swap out parts on the go, and it should be necessary to use the workstation to modify them, or do you mean it'd be too difficult otherwise because disassembly/reassembly takes time and energy?

**Comment by rmellema** [comment]
No, I mean that there are hot swap upgrades like you mentioned before, and to get those in, you would need the workstation. If you don't have the hot swap upgrades, you would need the workstation to remove/replace upgrades and cards.

**Comment by fnuecke** [comment]
Right, sorry for being unclear, that's what I meant with the first part :-)

Hmm, I don't know, I kind of like the ability to change some things "in the field". Maybe require a tool (more expensive wrench? screwdriver?) to do those changes, though, as sort of a compromise?

**Comment by MaHuJa** [comment]
Going from the mockup above, the lower three upgrade slots correspond to the ones in the robot's gui, right? So, what exactly can be placed in them in that screen?
A floppy drive would seem obvious, allowing you to place a floppy into that slot of its gui.
A "hotplug port" could allow you to insert any card/upgrade in the field.
If the slot was left empty you could not use it for anything.

**Comment by LordFokas** [comment]
I like the idea of needing a screwdriver to change a robot's guts in the field.
That's what you do with computers / laptops IRL, all you need to change parts is a screwdriver.

Not that I always prefer to mirror real life, but in this case it makes a lot of sense...

**Comment by rmellema** [comment]
Sangar: If I wasn't unclear to start with, the question wasn't necessary ;)

A screwdriver makes good sense indeed. If you want to build a robot that you can upgrade, the slots for that wouldn't be on the inside, but closer to the surface. Then disassembling isn't necessary just to give it internet access :P
