### ISSUE TITLE
Servers have no disadvantages.

### ISSUE THREAD

**Issue by gjgfuj** [MightyPirates/OpenComputers#1280]
Servers are really good, way more powerful than cases and the only disadvantage I can see of them is that they have to be pulled out of racks to be modified. Which is really not a huge deal. I think they should have some disadvantage. Maybe make them assembled?

**Comment by Vexatos** [comment]
You can only connect components to one side per server, depending on your setup this is a disadvantage.

**Comment by gjgfuj** [comment]
That's still a really small disadvantage.

**Comment by dgelessus** [comment]
> the only disadvantage I can see of them is that they have to be pulled out of racks to be modified

Keep in mind that this means no "plug and play" components. To modify the component setup, the server has to be shut down. (Admittedly switching out components while the computer is running sounds like a really bad idea, and I never do it for anything but floppies.)

**Comment by fnuecke** [comment]
Well, they're meant to be better. Servers are also more expensive to craft, after all, aren't they?

**Comment by gjgfuj** [comment]
From memory they're not /that/ expensive, though I'd have to check.

**Comment by gjgfuj** [comment]
My main request here is to have them be assembled in an assembler if
possible.

**Comment by Kubuxu** [comment]
It'd make them very inflexible, also IRL servers have even hot-swap mechanics.

**Comment by Vexatos** [comment]
I am pretty sure that Servers are way more expensive than Cases.

**Comment by fnuecke** [comment]
I don't really want them to be assembled devices, so some more reasoning than "because I want" would be necessary ;-)

Also what @Kubuxu said.

I also feel servers are a bit too special case-ish to fit the assembled-device pattern. Since they can't run "on their own" (they need to be in a rack).

**Comment by gjgfuj** [comment]
Mmm, OK I guess so. I still feel that there should be some more sorta
disadvantage to using servers that makes them not inherently better than
using a case except for a few minor reasons. This is assuming resources
aren't an issue.

**Comment by dgelessus** [comment]
Making servers an assembly sounds like a bad idea. It makes no sense from a logic/realism point of view (who would hardwire all components of a rack server) and it would not be a good balancing mechanic either. It would only make servers take time to be assembled, make it harder to upgrade parts, and it might impose an arbitrary complexity limit. Robots and drones obviously can't hold tons of complex upgrades, but servers are meant to have many components installed on them.

**Comment by gjgfuj** [comment]
Yeah, okay.
