### ISSUE TITLE
cannot read bees properly, Forestry API deprecated isIrregularMating() 

### ISSUE THREAD

**Issue by jansamohyl** [MightyPirates/OpenComputers#1283]
I had problem reading bees from the computer with latest Forestry (3.6.2.19 or development version). 

An exception at:
java.lang.NoSuchMethodError: forestry.api.apiculture.IBee.isIrregularMating()Z
        at li.cil.oc.integration.forestry.ConverterIIndividual.convert(ConverterIIndividual.java:248)
will happen if you read bee details with inventory controller. In particular, the interesting fields with the genome individual.active and individual.inactive will be null when that happens.

Forestry API deprecated IBee.isIrregularMating(), as described here:
https://github.com/ForestryMC/ForestryAPI/commit/2ad2ee6d7c4997cb463ca0a73b1463f1e6b47a2f

I think all that's needed is to remove the call to the method in ConverterIIndividual.java that causes the exception. Thanks!

**Comment by fnuecke** [comment]
Will fix, thanks for reporting it.

**Comment by DarkApothecary** [comment]
I'm having this same problem, with most recent versions: forestry_1.7.10-3.6.3.20, ComputerCraft1.73, OpenModsLib-1.7.10-0.8 and OpenPeripheral-1.7.10-AIO-5.

Anytime I try to query information about bee-containing slots I get: 

lua:1: forestry.api.apiculture.IBee.isIrregularMating()Z
