### ISSUE TITLE
screen.getAspectRatio() is slightly off

### ISSUE THREAD

**Issue by dgelessus** [MightyPirates/OpenComputers#1284]
Currently `screen.getAspectRatio` returns the width and height of the screen, in blocks. For non-square screens, this doesn't accurately represent the aspect ratio of the screen's actual display surface - the screen has a two pixel border on every side, which is not part of the display. This means that e. g. the aspect ratio of a 3 \* 2 screen is not 3/2, but (14 + 16 + 14)/(14 + 14). 14 pixels for "border" blocks, and 16 for "middle" blocks.

The correct formula for one "side" (width or height) would be 16 \* (blocks-2) + 28.

**Comment by fnuecke** [comment]
Blame it on my terrible naming sense; it's in fact meant to return the size of the screen in blocks :-/

For tablets it's 1:1, for example.

Can't really think of a nice design to take the actual one into account in a generic fashion, too... maybe as 3rd + 4th return value? But then again, the component itself is actually agnostic about whether it's a screen/tablet/in a robot/... so...

**Comment by dgelessus** [comment]
It would of course make more sense for `getAspectRatio` to return the exact ratio, and have a new method like `getBlockSize` to get the size in blocks, but that could cause problems with programs that rely on `getAspectRatio` returning a block size. (If there are any such programs, I can't think of any situation where the difference would be significant.) Extra return values would be a more safe and backwards-compatible solution.

**Comment by Alaberti** [comment]
Is this still a thing?

**Comment by payonel** [comment]
nope
