### ISSUE TITLE
String's metatable's __index doesn't point at string library

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#1285]
In standard Lua, `getmetatable("").__index == string` returns `true`, meaning the string's metatable points at the string library. This means that if you add things to the string library, you can call it either by `string.foo("bar")` or by `("bar"):foo()`, the latter not being possible in OpenComputers.

**Comment by fnuecke** [comment]
As mentioned on IRC, not possible because metatables of primitives aren't persisted.

**Comment by Jomik** [comment]
Is this also why my library doesn't work?
http://pastebin.com/M5e8wpGG
I am quite new to Lua... I get nothing of the "vector" metatable together with the variable when I load
`local vector = require("vector")
local a = vector(1,2,3)`
simply gives a table {x=1,y=2,z=3}, without any of the methods I (believe) I created for the table.
