### ISSUE TITLE
Preload a robot with code

### ISSUE THREAD

**Issue by TinkerWorX** [MightyPirates/OpenComputers#1287]
Is it possible, either through the OC API or ingame to make a robot that is preloaded with specific code?

I'm looking for a way to give a player a robot with specific code, but in a world that doesn't have the robot harddisk registerred yet. It should also be possible to give out 10 robots which each will become their own instance once placed.

**Comment by Techokami** [comment]
Custom BIOS? Or, use a Tier 3 case and pre-populate the floppy slot with a loot disk?

To elaborate: Loot disks hold specific files (code) that are "pre-loaded" and won't actually exist as an instance in the OC data folder for the world until it is first read.

**Comment by TinkerWorX** [comment]
So I could create a loot disk and then a robot with said disk loaded? Would the player be able to remove the disk?

**Comment by Techokami** [comment]
If it's assembled into the robot, no.

**Comment by gjgfuj** [comment]
If they disassembled the robot, yes, but otherwise no. Also this would be
better suited for the forums.
