### ISSUE TITLE
Are cross-world UUID collisions acceptable?

### ISSUE THREAD

**Issue by makkarpov** [MightyPirates/OpenComputers#1288]
Not an issue, just a question.

I wrote a system that implements 'forked worlds' — it can be useful, for example, for multiplayer adventure maps because players are not interfering with each other. But if I put a computer to a master world, it will be copied to all derived worlds with same UUID. Forked worlds have same dimension ID (1), but have different world objects. Is this acceptable or I should implement UUID regeneration on copy?

**Comment by Pwootage** [comment]
To clairfy, are you speaking of different minecraft servers or about some mod I haven't heard of that allows multiple "worlds" in the same server (rather than just multiple dimensions)?

**Comment by makkarpov** [comment]
These worlds exists in a single server instance and can be dynamically created and unloaded on per-user basis (single isolated world per user). When a new world is first created, it gets populated from a 'master world', so all UUID's remains the same.

**Comment by fnuecke** [comment]
The only place where this could become an issue, is if the component networks actually become connected - and at least in OC on its own there's no way this would happen, I think (even linked cards are not connected directly, but communicate over a separate layer, so to speak). One way this could potentially happen is via the OC P2P bus in AE2 (rv3) when using QNBs.

So in general this should be safe. Even when networks with duplicate UUIDs get connected, what'll happen is that all but one of the duplicates will simply get assigned a new ID, which will usually not be  an issue.

**Comment by fnuecke** [comment]
Come to think of it, another way this could be noticeable is in the sender address of network packets. But that also shouldn't be a big issue, I think?

**Comment by Pwootage** [comment]
Another place it may matter (indirectly) is the static list of server racks (which I have no idea what is used for). I do believe that disks/computers are stored per-world and per-dimension so that shouldn't be an issue (to the best of my knowledge)

https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/common/tileentity/ServerRack.scala#L497-L506

**Comment by makkarpov** [comment]
Thanks everyone for answers. So I will just avoid usage of server racks and linked cards.

**Comment by fnuecke** [comment]
Oh, f... completely forgot about file systems. If you've got hard drives in those, and they keep their addresses, they'll all share the same real-world directory for storage, which could lead to really funky side-effects.

**Comment by makkarpov** [comment]
Yeah, I already thought about it. They are intended to be read-only, computer will store all data in memory or /tmp and use persistence.

**Comment by Kubuxu** [comment]
The UUID has entropy of `2^122bits` and uses Java's secure random. If you find a collision let me know, I will give you my all money to put it on some lottery.

Seriously, don't worry about that, this is not something that should happen.

**Comment by fnuecke** [comment]
~~Read up :P He's copying the data. So the saved UUID will by definition be duplicated.~~ I was too quick a smartass :X

**Comment by Kubuxu** [comment]
Yeah, wrote it, posted and then read it again...
Old post: http://hastebin.com/jobobopaco.md
