### ISSUE TITLE
Creative pre-equipped PC

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1289]
So yeah, that has always be one of my gripes :p Whenever I make a test world to test, or make a new PC in a testworld, I have to spawn in:
- CPU
- Case
- Memory
- Lua Bios
- GPU
- Screen
- Keyboard
- HDD
- OpenOS Floppy

Then place all that, install OpenOS, and then throw all of the things in the inventory away...
Would be nice if there was a Creative Case that was prefitted with the best GPU, CPU, Memory, HDDs Lua Bios and OpenOs Floppy :)

**Comment by gjgfuj** [comment]
+1 to this.

**Comment by Vexatos** [comment]
Instead of CPU and GPU, better have a Creative APU.

**Comment by fnuecke** [comment]
Hrm. Maybe as a command that spawns a case + that + screen + keyboard on the block you're looking at or so?

**Comment by Inari-Whitebear** [comment]
Hm, that would be great actually ^^ Was originally thinking of having a case that has the stuff in already (but that wouldn't get rid of having to get Screen+Keyboard and such of course)
