### ISSUE TITLE
(2 minors bugs) screen's inverted mode doesn't work for multi block screen & apu show a wrong amount of component

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1291]
**"screen's inverted mode doesn't work for multi block screen" part:**

The method `screen.setTouchModeInverted()` only invert the screen directly refered by it address.  
In a screen multiblock, every screen keep their individual address and only one of them is currently sens by the network while the other aren't (this way, a 3x4 screen is only perceived once).  
Because of those two fact, when you set a multiblock screen in inverted mod, only one of the screen is actually inverted.

Possible fix:
- adding a special case in the method `screen.setTouchModeInverted()` when the screen is a part of a multiblock to properly set the touch mode to all the screen.
- show all the screen to the computer (just kidding, if you do that, the component limit will be way to easily reach)

**"apu show a wrong amount of component" part :** The description of the APU and the analyzer show different component count. The description show the amount of component corresponding to the cpu used in the craft and the analyzer show the amount of component corresponding to a cpu with the same tier (i.e. for a APU tier 1 = 8 component because a CPU tier 1 = 8 component).

P.S.: talking about component limit, why does the creative APU only have 16 component ? Sure, I understand that having a lot of component is more harmful toward a server that having many component in a robot but it is a creative component.

**Comment by MyNameIsKodos** [comment]
I'm not sure about the second bit of your issue, but as for the first one, I actually like this being a thing because you can have a portion of the screen specifically for a touch-sensitive area, rather than the entire thing. This opens up a few ideas for programs, I would think.

**Comment by dgelessus** [comment]
@Aredrih

> why does the creative APU only have 16 component ?

The creative APU is like a tier 3 CPU and GPU combined. It's a creative item for balance reasons, otherwise there would be no advantage to using a dedicated CPU/GPU instead of an APU. If you want tons of components, get a server.

@Kodos-Atoz

> because you can have a portion of the screen specifically for a touch-sensitive area, rather than the entire thing

If at all, that should be a per-character thing and not based on screen blocks. The current behavior is clearly a bug.

**Comment by MyNameIsKodos** [comment]
Fair enough, I suppose a gpu.setTouchSensitiveArea(xStart,yStart,w,h,true/false) could be a thing.  Or something to that effect.

**Comment by dgelessus** [comment]
`screen.setTouchModeInverted(enabled, x, y, width, height)` - no extra method, but fully backwards compatible. Except for the return value - what is the previous state for an area with mixed touchyness? Maybe just return the old state at `x, y` no matter what `width` and `height` are.

**Comment by ghost** [comment]
@dgelessus 

> If you want tons of components, get a server.

Yes indeed, I'd completely forgot what server are for while writing this issue. >.>  
And it make way more sens that way. Thanks

@Kodos-Atoz 

> you can have a portion of the screen specifically for a touch-sensitive area, rather than the entire thing

Well, the inverted mode isn't related with the touch sensitivity, but with what trigger the computer's gui (right-click in no-inverted mode and shift right-click in inverted).  
IMHO, the inverted mode help define which kind of interaction the program have with it user. When you want to interact with a screen, you rather use a right-click than a shift right-click:
- In not-inverted mode, it will open a gui which allow typing text but immobilize the player.
- In inverted mode, it's triggering a touch event and let the player isn't immobilized by a gui which is what you would except of a button screen or any other program witch require half a second of interaction.

In both case, if you really want, you can open the gui which is touch sensitive so _once the gui is open, there no real reason to close it until the player leave_. Having a partial inverted mode would rather confuse players and I think they can shift right-click if they really want to type some text or the program can switch back the inverted mode.

Also, it's up to you to choice which touch event you chose to handle and which ones you won't.
