### ISSUE TITLE
Net Splitter texture issues

### ISSUE THREAD

**Issue by dgelessus** [MightyPirates/OpenComputers#1294]
![2015-07-13_02 15 24](https://cloud.githubusercontent.com/assets/6641959/8640788/346cd98e-2905-11e5-9e86-64cf816df8fe.png)

Yes, that is supposed to be a net splitter. And with Optifine it looks fine, without it, not so much. Relevant system specs are on the F3 overlay.

**Comment by MyNameIsKodos** [comment]
Is this with -just- Forge and OC?

**Comment by dgelessus** [comment]
It's on 1.8, so basically yes. The other mods I have installed are mostly the usual client mods like NEI, plus a few content mods like Random Things. If necessary I can post the full list tomorrow. (The 38 mods number is not entirely accurate, mod count inflates quite a bit because of dependencies and mods that magically split themselves.)

**Comment by MyNameIsKodos** [comment]
I was just gonna say, see if it happens with JUST OC installed, and if not, find out which mod is interacting badly with it

**Comment by dgelessus** [comment]
Okay, it is caused by the other mods. Sort of. Depending on how many mods I have installed, the broken texture looks different. With OpenComputers alone it looks correct, adding more mods breaks the texture in most cases.

Mod list as dumped by Forge:

```
AS_Ruins@14.9
AS_UpdateCheck@1.1.7
ArmorStatusHUD@1.8
Aroma1997Core@1.0.3.4
Aroma1997CoreHelper@1.0.3.4
Aroma1997sDimension@1.0
Baubles@1.1.1.0
Chameleon@1.8-0.1.0
CodeChickenCore@1.0.5.36
DamageIndicatorsMod@3.3.3
DirectionHUD@1.8
FML@8.0.99.99
Forge@11.14.3.1450
HelpFixer@1.1.9
InGameInfoXML@2.8.1.78
IronChest@6.0.103.753
LaserLevel@2.0.0.4
LunatriusCore@1.1.2.28
NotEnoughItems@1.0.5.104
OpenComputers@1.5.14.181-dev
OpenComputers|Core@1.5.14.181-dev
RandomThings@3.5.3
SlimevoidLib@3.0.0.4-beta-1.8
StatusEffectHUD@1.8
StorageDrawers@1.8-2.0.2
VeinMiner@0.26.1_build.unknown
VeinMinerModSupport@0.26.1_build.unknown
VeinMiner_coremod@0.26.1_build.unknown
VersionChecker@1.2.2
Waila@1.6.0_B1
WirelessRedstone@2.0.0.1-alpha-1.8
bowinfinityfix@rv1
bspkrsCore@7.01
denseores@1.0
hopperducts@1.4.5
inventorytweaks@1.60-dev-8-65e0900
mcp@9.05
redstonepaste@1.7.1
```

**Comment by gjgfuj** [comment]
I'd say that it's caused by one mod messing up the sprite sheet?

**Comment by fnuecke** [comment]
I suspect the texture atlas changes after the block model is first initialized, which is where I pre-bake the static part of the thing, so the UVs used there are invalidated... guess I'll just have to do the static stuff each time it's rendered as well. Less performant, but oh well.

**Comment by Kubuxu** [comment]
You can use `TextureStitchEvent.Post` to rebind textures to new UV. Not sure if it will help in this case but for sure it works with resourcepack change.

**Comment by fnuecke** [comment]
Good point. I'll give that a shot.
