### ISSUE TITLE
Computer active range

### ISSUE THREAD

**Issue by womayhem** [MightyPirates/OpenComputers#1299]
By this I mean the range at which computers will run even while there are no players around.
Because what I want to do is have computers automatically send messages over a long cable that will connect to another computer even while there aren't any players around, so basically I want to have computers running 24/7 even if there are no players near.  I tried using World Anchors, which keeps the chunk with the computer loaded, but while far away from the computer, the program sending the messages was suspended until I become near again.

Is there anything I can do about this?

**Comment by gjgfuj** [comment]
Um... If it's chunkloaded, it'll run. So clearly you're not chunk loading
them properly.

**Comment by gjgfuj** [comment]
Buuut, if its cable based, you probably should chunkloaded the cable.

**Comment by womayhem** [comment]
Yes, everything is chunkloaded.  The cable, the computers, everything.

The thing is the computers suspend the application while I'm not near them.  The chunks are loaded.  What I did to test this was I sent messages infinitely and put switches down so I knew where the messages were reaching.  I found that the messages were reaching all of the switches.  But the computer would not receive or send them while I wasn't near them.  With my render distance up, I could see all switches were receiving, but the computers weren't.  And the computer also stopped sending whenever I wasn't near.  

It's got to be something else, right?

**Comment by MyNameIsKodos** [comment]
Are you playing on a server? If so, does the server host have persistence enabled?

**Comment by womayhem** [comment]
Yes this is on a server.  It's on Minecraft Forge 1.7.10 1291.

I assume you mean persistence as in OpenComputers.cfg, disablePersistence.
I didn't change any config settings, I left everything default, and disablePersistence is set to false.
The computer doesn't reboot when I come close to it again, it just resumes the execution.

**Comment by MyNameIsKodos** [comment]
Did you use World Anchors, or Admin Anchors?  IIRC World and Personal require by default Ender Pearls as fuel to function

**Comment by womayhem** [comment]
I'm using Admin Anchors from Railcraft.  I just noticed though, that they'e red, and not blue, however.  Why is this? Is there an anchor limit?  I know we have quite a few in anchors in the world.

**Comment by MyNameIsKodos** [comment]
I believe so, yes.  I'd check the config, or even ask in #railcraft over on Espernet

**Comment by womayhem** [comment]
Yep, that did it.  Removing world anchors in the world made them function again.  Thanks for your help.

**Comment by MyNameIsKodos** [comment]
No problem =) Don't forget to close this issue
