### ISSUE TITLE
OreDict woes

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1303]
2 things :3
- I can't seem to figure any way to get the oredict name of an item, database doesn't seem to have such a function and the stack given by inv controller doesn't have any field for it... would be nice to get something like that, or is there?
- Make it possible for crafting to choose the output... that is, if there are 5 types of iron nuggets, add a value to the crafting command that lets you pick which to get or something of the sort.

**Comment by Vexatos** [comment]
Hmmm... This seems to belong into the "itemstack inspection" config option as it would reveal internal data, which OC shouldn't do... Maybe some Ore Dictionareader Card allowing comparing a database entry to an oredict tag? Still would rely on internal data...

**Comment by dgelessus** [comment]
The most "in-character" way to handle the oredict would be to have a function that returns whether two items are oredict-equivalent. That would be sufficient for most use cases - store all ingots you need in a database and compare items in the robot inventory with those.

> Ore Dictionareader Card

*badum disch*

**Comment by makkarpov** [comment]
> This seems to belong into the "itemstack inspection" config option as it would reveal internal data, which OC shouldn't do...

I don't think that oredict lookup reveals internal data. It just determines a type of item.

**Comment by Kubuxu** [comment]
Maybe:

``` lua
function isSimilar(stack): boolean -- returns whether item belongs to same ore dict group
```

**Comment by Vexatos** [comment]
@Kubuxu Something like `compareStacks` on the inventory controller checking for ore dictionary "similarity" would probably the best way to go.

**Comment by Kubuxu** [comment]
Yeah, that is what I meant. I've forgot how DB worked...

**Comment by fnuecke** [comment]
I suppose it'd make sense on the inv controller. Though I'd prefer to have the naming convey the sense that it's not an equality check more, e.g. something more like `isEquivalentTo`. Alternatively `compareTo` could get a boolean parameter that when true does an oredict check instead of an equality check. Though that'd be "built-in" then, ofc (which wouldn't be too bad IMHO, but limit it to agentsl, which'd kinda suck).

**Comment by Vexatos** [comment]
I'd prefer it being a feature of the inventory controller.
