### ISSUE TITLE
Servers in Server Racks are slower than actual computers

### ISSUE THREAD

**Issue by womayhem** [MightyPirates/OpenComputers#1304]
I put a server rack in external mode that has a simple echo program in a single server.
Now, when I use a computer that is connected directly to the server rack, the messages are sent significantly slower than a standard computer.  I tried using a switch with fully upgraded hardware, and all of the servers in the rack have the top tier hardware as well.  Overall the servers are WAY slower than actual computers when dealing with networking.  Is this a bug or am I just doing something wrong?

**Comment by MyNameIsKodos** [comment]
I'm curious to see your setup as well as the code you're using to test this.

**Comment by fnuecke** [comment]
Hm, for the side it's connected to that shouldn't be the case. For all other sides the rack itself already acts as a switch - a non-upgradable one - so that'd explain the delay you're seeing?

**Comment by MyNameIsKodos** [comment]
That's what I was thinking as well.

**Comment by Kubuxu** [comment]
It really hurts.
Right now we are using `ssh` to connect to servers inside a rack. It is tenths times worst than computer to computer.

**Comment by fnuecke** [comment]
I'd say we'll solve this one way or another via #1323.

**Comment by fnuecke** [comment]
Actually, I'll just add a setting in the meantime.

**Comment by Kubuxu** [comment]
Thanks, now I can scrap our fork.
