### ISSUE TITLE
[Bug] tablet screen is freezed when you die

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#1309]
After being die, the tablet screen is freezed. You have to quit and rejoin the game to fix the problem.
But I think the tablet continue to work, just the screen is freezed.

**Comment by fnuecke** [comment]
With keepInventory or after picking it back up?

**Comment by ExDomino** [comment]
With KeepInventory.

**Comment by payonel** [comment]
does not repro, we might have fixed in by now
