### ISSUE TITLE
robot.use() doesn't grab dropped blocks

### ISSUE THREAD

**Issue by Belgabor** [MightyPirates/OpenComputers#131]
If robot.use() results in the block being dropped (eg sneak-use with a TE crescent hammer) the block is dropped into the world and not grabbed by the robot. This makes it pretty much useless as a mechanic =)

**Comment by fnuecke** [comment]
Why does every mod have to drop its items/blocks in a different fashion... oh well, time to rework and generalize item drop detection. Thanks for reporting.
