### ISSUE TITLE
[Bug] Program "edit" and help in the bottom of the screen

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#1310]
The "Edit" program don't show propely its help about Ctrl+S and Ctrl+W in the bottom of the screen when you type on Ctrl. You have to press on Ctrl and then press any other key to see it.

**Comment by fnuecke** [comment]
Not sure what you mean?

**Comment by Shuudoushi** [comment]
Press 'ctrl' doesn't automatically show the 'help' (i.e. "Save: [Ctrl+S] Close: [Ctrl+W] Find: [Ctrl+F]" http://puu.sh/jbEnJ/628b92bfab.png)

I think he's asking for it to be made dynamic with the press of ctrl.

**Comment by fnuecke** [comment]
But... why? It's displayed again on document changes anyway. It's not like this is CC's edit, where you press them after each other, so this doesn't really make sense to me. I honestly think it's fine the way it is.

**Comment by Shuudoushi** [comment]
It doesn't bother me that much myself, it's not like the buttons change every so often.
