### ISSUE TITLE
component.robot.detect() and component.geolyzer.analyze() are slow

### ISSUE THREAD

**Issue by tuxmark5** [MightyPirates/OpenComputers#1314]
These calls are used by more advanced navigation algorithms to reconstruct world map that then can be used by various pathfinding algorithms. For a robot to be able to fully scan the environment, it needs to make 6 of detect() or analyze() calls per movement. However, these invocations are particularly slow and slow down robot movement considerably. Small benchmark shows that making even 100 of these calls in quick succession can take upwards to 5 seconds.

It would be great if:
1. These calls could be somehow optimized. 
2. Or at least detecting all 6 sides could be grouped into a single call. However, this would not increase speed of hole mining scripts which check if there is a block in front that can be mined.

**Comment by Inari-Whitebear** [comment]
Well, as you already figured and said, "to reconstruct world map". Basically meaning you only have to get the data once and then you can use it forever (unless you need to make corrections).
So I don't think it is that slow?

**Comment by tuxmark5** [comment]
It is slow, because you still need to keep scanning map for changes. As a result every move call is followed up by 6 analyze() calls, which slows down overall movement by ~30-40%

Also, the issue #1313 might be related to this, as robots seem to use similar block detection code to check if there is a block in front. It seems that blockContent function of WorldAware trait might be the culprit.

**Comment by fnuecke** [comment]
I disagree. It's one tick per `analyze` (which it has to be because it interacts with the world, so it must be synchronized). Scanning all sides at once sure could speed it up, but I don't like that, as it breaks the common pattern of how agents interact with the world, and I honestly don't think it's a problem anyway (I'm reasonably happy with the performance of my mining program, which scans all the things, and I didn't even try to optimize that).

Sure, it may be slower than just digging out everything with a BC Quarry, and certainly slower than using a Digital Miner, for example, but comparing an all-rounder tool with a highly specific tool is never a good idea anyway :P

**Comment by tuxmark5** [comment]
Geolyzer already does not follow the common pattern by having method geolyzer.scan, which returns information about a single column. I would strongly suggest adding either new a method to geolyzer that allows scanning all 6 sides at the same time, thus making geolyzer more useful (as right now it seems to exist by solely complementing hologram projector), or to add a new "vision" upgrade that has such method. The vision addon could return 3x3x3 block information. While I'm sure that not many people would use such addon, it would make a nice addition to OC nonetheless.

**Comment by Inari-Whitebear** [comment]
Why does your robot that moves need to keep updating the map data anyway? It will mostly be static, and a special mapping robot can handle the mapping.

**Comment by fnuecke** [comment]
The geolyzer upgrade is fine as it IMHO. I find it to be tremendously useful, in being able to just check _what exactly something is_ versus blindly digging or having to keep a whitelist of blocks in a robot's inventory. Some may already call that OP :P

**Comment by tuxmark5** [comment]
While it is true that most of the map is static, but the user's base is usually not. And that's where robot navigation is most important as I don't want my robot to destroy my base - that's why I use A\* to navigate my stuff.

In addition, my bots assume that the unmapped regions are filled with free space, thus alleviating the need for designated mapper bots.

@fnuecke How exactly is it OP for a robot to be able to observe the world? If the player has vision, I don't see any reason why the robot shouldn't be able to see it too - that's one of the things I don't get about ComputerCraft, whose author seems to be afraid of adding ability to identify blocks. I have yet to see a single OP script that somehow breaks the balance of the game.

**Comment by Inari-Whitebear** [comment]
So make your A\* smarter ;) a separate geolyzer can keep track of where what is and send that info the the robots
If a robot finds itself blocked it can tell the main computer about that and it marks the blocks as used, then the robot can reroute

**Comment by tuxmark5** [comment]
Nah, I prefer the way it is. My current method allows robots to roam anywhere they want and works optimally in open spaces. 

I would still have a "proper" vision upgrade. If some feel that it might be OP, then it just a matter of adding a config option to settings file to disable it.

**Comment by Inari-Whitebear** [comment]
Well, your loss :3
And doubt that will make it in, but who knows

**Comment by fnuecke** [comment]
> If the player has vision, I don't see any reason why the robot shouldn't be able to see it too 

Simple: the player is a client side creature, the robot is a server side creature ;-) (Yes I'm aware that's not the kind of vision you were referring to.)

The next best thing you're gonna get for the foreseeable future is Computronics' camera upgrades.

**Comment by tuxmark5** [comment]
@Inari-Whitebear Yes, let's celebrate lack of progress.

**Comment by fnuecke** [comment]
> let's celebrate lack of progress in the direction I as a minority want.

FTFY ;-)

**Comment by tuxmark5** [comment]
Fine, I'll implement it myself.
