### ISSUE TITLE
[request] T3 Drone case

### ISSUE THREAD

**Issue by Tcll** [MightyPirates/OpenComputers#1320]
alot of thought was put into this one to make the most out of the drone's capabilities ;)

upgrade slots:
T3 T2 T2
T1
my idea for something here:
[chunk loader] [solar] [battery]
[geolyzer]

card slots:
T3 (I could put a linked card here (note the battery upgrade))
T2 (and an internet card here)

T2 CPU (for processing speed, and because the T2 case uses a T1 CPU for some reason)

RAM: (at least enough to process a 5x5 chunk area)
T2.5
T2.5

with this, I won't have to explain my idea to server admins and ask for a creative drone case.

what is my idea exactly?
basically, imagine being able to write your own character or entity.

it requires OCGlasses to see the model...

basically the drone will hover at y:256 loading the chunks around the character's position and sending back any updated data on call.
the 1GB memory would store and update the chunk data as well as leave a good amount of room for optional processing. (this is for speedy data transfer as well)
the linked card for obvious reasons.
the internet card would be for linking to a raw script I could edit with an outside IDE (synced via copy.com)

I would've suggested a T3 CPU for the power, and to make the case and CPU match, but a T2 CPU might work decently for updating the data at a decent callback rate.

would be cool if I could make my character kill mobs >.>
(the drone shoots an invisible laser or something)

**Comment by Vexatos** [comment]
I think what you are requesting here is essentially a creative drone, and it's creative for a reason.

**Comment by SaphireLattice** [comment]
Wasn't there already an issue about high-tier drones?

**Comment by Tcll** [comment]
there's many major differences between a creative drone and the drone I'm requesting:
- a creative drone can have 9 T3 upgrades, where my request can only have 1 (or 2 if you wish to modify).
- a creative drone can have a T3 CPU, where my request was limited to a T2 (something other drones don't have)
- a creative drone can have 3 T3 cards, where mine can only have 1 and a T2
- a creative drone can have 2GB of memory, where mine can only have 1GB at max

I'd have to say my request is still pretty far from a creative drone.

EDIT:
I'm trying to request something legit so I don't have to ask server admins for a creative drone.
(I understand drones are limited, so I'm keeping my request within range compared to the creative drone)

**Comment by SaphireLattice** [comment]
It's still very OP. Drone is not made for heavy load and processing, it's not a computer, is it?
And you are basically asking for _slightly_ nerfed T3 robot.

**Comment by Inari-Whitebear** [comment]
So what prevents you from having a PC store the chunk data and talk to the drone to update the script etc?

**Comment by Tcll** [comment]
> It's still very OP. Drone is not made for heavy load and processing, it's not a computer, is it?

it's a T3, isn't it supposed to be more OP than a T2??
and it's still not really that OP considering the T2 CPU and T2.5 RAM with only 1 T3 upgrade and card slot

> So what prevents you from having a PC store the chunk data and talk to the drone to update the script etc?

that's inefficient, and doesn't quite provide enough space for multiple instances.
I'm using servers to manage the drones, but really those are only bridges...
the co-processing between them would be too much work to code and would be very inefficient.

**Comment by Inari-Whitebear** [comment]
But it would work :)

**Comment by Tcll** [comment]
it would just be very slow and probably cause server lag

EDIT:
I did say I'd put alot of thought into this request ;)

**Comment by SaphireLattice** [comment]
Look, OC is about using what resources you have and utilizing them in most efficient way (code- and crafting-wise). Not walking to devs and yelling "Hey, add stationary-case-level powerful flying _micro_-computer".

**Comment by LizzyTrickster** [comment]
Unless you managed to have enough drones/servers to effectively hammer the (seperate) worker threads without getting killed for using too much cpu time, it wouldn't cause that much lag compared to minecraft mods in general.

Also not sure if you made a typo with the "1GB memory" but sure, lets give these 4 drones 1GB of ram each for the sandboxes, oh, you're out of ram.

**Comment by Tcll** [comment]
> Look, OC is about using what resources you have and utilizing them in most efficient way (code- and crafting-wise). Not walking to devs and yelling "Hey, add stationary-case-level powerful flying micro-computer".

it's a request, and a well thought out one at that, I'm not yelling at anyone >_>

> Unless you managed to have enough drones/servers to effectively hammer the (seperate) worker threads without getting killed for using too much cpu time, it wouldn't cause that much lag compared to minecraft mods in general.

it's an _interpreted_ LUA stream...
knowing interpreted languages are slow as is, I'm pretty sure the stream alone would cause a bit of lag.
(but only a bit at that, compared to AE2, it's minor, but the impact is still there)
^ the inefficiency would only multiply the impact of the TPS drop

> Also not sure if you made a typo with the "1GB memory" but sure, lets give these 4 drones 1GB of ram each for the sandboxes, oh, you're out of ram.

I get your point, but you're putting down the entire mod, not just the drones.

**Comment by LizzyTrickster** [comment]
> it's an interpreted LUA stream...
> knowing interpreted languages are slow as is, I'm pretty sure the stream alone would cause a bit of lag.
> (but only a bit at that, compared to AE2, it's minor, but the impact is still there)
> ^ the inefficiency would only multiply the impact of the TPS drop

The interpretation is done in (by default) 5 separate worker threads, not in the main thread. It is unlikely that it will cause issues for the main server thread because of the restrictions that are in place ( @fnuecke can correct me if I am wrong ).

> I get your point, but you're putting down the entire mod, not just the drones.

1GB modules is still infeasible for most servers out there, hosting with RAM sizes larger than 4GB can get quite expensive. Modded minecraft will need at the very least 1GB ( and that's pushing it ).

**Comment by Tcll** [comment]
> 1GB modules is still infeasible for most servers out there, hosting with RAM sizes larger than 4GB can get quite expensive. Modded minecraft will need at the very least 1GB ( and that's pushing it ).

if it can be limited to T2 without T2.5, I can accept
but that doesn't say the same for multiple T3 Cases, Robots, or Servers, which can still have quite an impact (especially with servers), basically rendering this argument near invalid.

**Comment by LizzyTrickster** [comment]
> if it can be limited to T2 without T2.5, I can accept
> but that doesn't say the same for multiple T3 Cases, Robots, or Servers, which can still have quite an impact, basically rendering this argument near invalid.

You do realise that the memory modules (T3.5 being 1024k, not 1024m (1GB) ) installed in a device affect what size heap is given to that sandbox, right? Plus there's also a little bit more used for overhead stuff.

**Comment by Tcll** [comment]
oh, alright my mistake, so it's not as bad as I thought, T2.5 should be ok :)

**Comment by Kubuxu** [comment]
@Tcll it won't happen. Drones are designed not as flying computing platforms but as fast and small world interactors. 

If you want to create complex system focus more on other solutions in OpenComputers.

You have drones that are fast and small but limited. Send a robot with them that will act as mobile computing platform which communicates via wirelesses modem with drones telling them where to go and what to do.

If you want the data to be available and stored in one place give the robot a linked card and put second in a server in your base. It can store, compute. With a lot of data think about RAIDs or maybe storing them on tapes (the biggest one is 30MB). If you want to access it create a terminal which can be simple computer case or you might want to use tablet and access points.

In OC not only programming counts but also system design. It isn't CC where everything is cheap and can do almost anything, it's limited with purpose of inducing creativity (of more real life solutions) and creating more complex builds.

This is main reason why I am using OC. The limits make me think about problems and find solutions for them. Its same reason why I use bare Atmel ATmega (which I program usually in ASM) instead Arduino or RPi (apart from fact that it is 10 times cheaper) whenever I can. If I were to compare your request to a real life scenario, it is like you wanted to put a Raspberry Pi B rev 2 in each power outlet to monitor energy usage of intelligent house.

**Comment by Tcll** [comment]
I guess I'll have to have a server admin straighten you guys out...

I'm just requesting a stronger drone (since everything else goes up to T3)

and I can deal with the limitations of a T3 drone, which what I've requested shouldn't be all that bad for T3 standards when it comes to a drone's limitations.

if I was requesting anything bigger, a T3 case would be requested to have 2 T3 card slots.
but I believe I'm keeping my request sane, it's not like I'm requesting 3 card slots for a drone, or 6 upgrade slots (better suited for a robot).

**Comment by Kubuxu** [comment]
Everyone here said: Drones are limited with purpose.

**Comment by ds84182** [comment]
If you want stronger drones so bad, why don't you modify the mod, since it's Open Source?

**Comment by Tcll** [comment]
> If you want stronger drones so bad, why don't you modify the mod, since it's Open Source?

I would if it were Python

**Comment by ds84182** [comment]
Well, sorry bud, can't make mods in Python can we?

**Comment by Tcll** [comment]
exactly

**Comment by gamax92** [comment]
But we can, using the power of PythonForge! or ... MinecraftPython, ... name pending.

**Comment by LizzyTrickster** [comment]
> Well, sorry bud, can't make mods in Python can we?

If you can get it to run in the JVM, there's no reason why it shouldn't work. Might not be that efficient mind you...

Also this issue is starting to turn into a war...

**Comment by ds84182** [comment]
:bomb: Launch the nukes! :D

**Comment by Tcll** [comment]
getting back on topic

> Everyone here said you. Drones are limited with purpose.

and I'm respecting that

> But we can, using the power of PythonForge! or ... MinecraftPython, ... name pending.

that sounds interesting >.>

EDIT:

> Might not be that efficient mind you...

yea, python is anything but efficient :P
I would know... lol

**Comment by Kubuxu** [comment]
So if you are respecting that why are you requesting stronger drones?

**Comment by Tcll** [comment]
I'm requesting a stronger drone while respecting the drone's limitations.

I don't understand what's so bad about my request... my entire skype group agrees with me, and I can get the server admins here as well who also agree my request is sane.

**Comment by vifino** [comment]
Look.

You aren't getting anywhere here. Your request is - as stated above - not following the style and intended limitations.
I doubt you'll get a flying micro-supercomputer.
You can have many people agreeing with you, but unless they show us why, I doubt it will help the slightest bit.

**Comment by LizzyTrickster** [comment]
At this point in time I think it would be best to wait for @fnuecke to comment on this. Though his response is most likely going to be similar to what the rest of us have said here (with the added "you're free to PR it in" possibly added )

**Comment by dangranos** [comment]
I think everything was already milked out of issue, lets calm down and wait until the response of main dev and not run in circles with same argument(s).
Also, just because **your** community likes that idea, doesn't means that other community would like it too.

**Comment by Tcll** [comment]
better to have and not need than to need and not have ;)

EDIT:
personally though, I'm waiting for fnuecke to respond.

**Comment by LokeYourC3PH** [comment]
I actually think this isnt a bad idea after all. Consider this: You would want to do many tasks at fast as possible with the ability to go fast where you want remotely, wouldnt it be much easier having the drone completing the task on its local machine rather than stressing out distance performance and having to communicate alot with other machines? I think this is a very good idea, because i also have the same problem, asking server owners or using on my own server creative drones, when a simple small upgraded drone would do the job. I support the idea, hate me or follow along with it.

**Comment by gamax92** [comment]
You're basically just saying you want a creative drone but have it not be creative, and are trying to mask that by making it a little bit less powerful than a creative drone. Why not just stop avoiding your server admins and just ask them.

**Comment by SaphireLattice** [comment]
@gamax92 , he doesn't avoids them, he is ready (or so he says) to get admins to help him with this issue. And i think we started running in circles on issue.

**Comment by Tcll** [comment]
you might want to rephrase that and say alot less powerful than a creative drone.

but because of the word **creative** some admins might say no, so this is to give people something **legit** since **creative** is **not legit**

**Comment by LokeYourC3PH** [comment]
Actually no, as already mentioned by Tcll, it is quite a bit from that to the Creative version, so its not slightly underpowered, it is actually a fair amount if you mind reading his idea of it. There is a difference between unlimited powers and 2-3 Tiers behind.

**Comment by Kubuxu** [comment]
Read my post again. Drones being limited is the design of OC. It is like you asked Vazkii to add RF to mana conversion.

**Comment by fnuecke** [comment]
This is going nowhere so I'm locking this. All has been said, pretty much, but I'll just say it again so you know it's how I see it, too: drones are fine the way they are. They're a tool for a certain kind of job, and that job is not what you want them to do.

That said, if you already have the admins on your side, have them add a minetweaker recipe for the creative drone or something, if that makes you feel better using something that's not meant to be used in a way that fits into the normal gameplay of the mod.

_That_ said, OC is not only open source, it's also highly extensible. If you have so many people agreeing with you, I"m sure you'll find someone to implement an addon mod that adds such a T3 drone.

[/end of discussion, please]
