### ISSUE TITLE
Lag when starting Minecraft with OpenComputers

### ISSUE THREAD

**Issue by ThePuzzlemaker** [MightyPirates/OpenComputers#1325]
Whenever I start Minecraft with OpenComputers it seems to lag the title screen, making Windows think that it is not responding and closing Minecraft.

Log: http://pastebin.com/da9Q3M78
- OC 1.5.14.30 1.7.10

**Comment by Kubuxu** [comment]
Do you use new MinecraftForge splash screen? With old one it is perfectly normal, it will happen with any mod depending how fast the computer is, how long mod loads or nomber of mods. Just don't close minecraft let it process.

**Comment by ThePuzzlemaker** [comment]
I disabled the new MinecraftForge splash screen.

**Comment by Kubuxu** [comment]
This is why the window is not responding. Just give it time. It will load just fine. Due to mod loading, which happens in same thread as window signal processing, windows thinks that program just hanged up.

PS: You can close the issue.

**Comment by ThePuzzlemaker** [comment]
Ok

**Comment by ThePuzzlemaker** [comment]
I've already gave it about 2 minutes and it is still not responding.

**Comment by Kubuxu** [comment]
Hmm, weird. Are you sure that it is OC doing it? You have other mods also.

**Comment by ThePuzzlemaker** [comment]
When I try it without OC it worked fine.

**Comment by makkarpov** [comment]
Please post full list of mods you're using.

**Comment by ThePuzzlemaker** [comment]
ComputerCraft, OC, MrCrayfish's Furniture Mod

**Comment by makkarpov** [comment]
If you manage to open Java inside native Windows console, not MC Launcher one, you will be able to take thread dump and post it here to tell what exactly is causing such delay. Also you may try to remove furniture mod and run MC only with CC and OC.

Also, please post MC and Forge versions.

**Comment by ThePuzzlemaker** [comment]
It's been doing this since the 1.8 updates. It might just be something with this computer.
