### ISSUE TITLE
[suggestion] Keyboard enhancements (uses for the button-group keyboard crafting components)

### ISSUE THREAD

**Issue by MrEldritch** [MightyPirates/OpenComputers#1333]
Currently, the microcrafting components involved in crafting the OpenComputers keyboard - the Arrow Keys, Button Group, and Number Pad - don't do anything. They exist only to provide crafting complexity.

In Minecraft machinery, there is a rather large input gap. You either set up a full computer with monitor and keyboard, or you allocate an entire block to every individual lever and button of binary redstone input. This absolutely cries out for a middle tier - the keypad.

My suggestion is that the keyboard components should also be placeable in the world, like the keyboard itself. When placed, they would render as models with physical, pressable buttons. These could either be connected to computers (with or without monitors) or bundled redstone inputs.

This would be astoundingly useful, both in terms of aesthetics and in terms of filling a much-needed gap in input between "massive walls of stone buttons" and "full command-line interface, or write a GUI - often one whose only purpose is to emulate having a few buttons to press." Keycode locks and elevator controls are the obvious application, but an enormous number of control tasks in Minecraft machinery could be made far simpler and more compact by simply having a one-block keypad to play with. They'd be ideal for controlling Microcontrollers.

I suggest that they work as follows:
-Button Group: A pad with up to 9 buttons. Each can be colored and labeled with a single character, to help make it less confusing which button does what. Can be opened as a GUI with a Scrench to configure output mappings: Each button can be set to output an OpenComputers event, a specific bundled redstone color, or an analog redstone strength. 

If it's not too difficult, ability to place them with varying numbers of buttons would be nice - maybe for small numbers of buttons, like two or three, they could be made larger to fill the same amount of space, opening the possibility of labeling them with whole words.

-Numeric Keypad: Comes in 10-button decimal, 12-button telephone, and 16-button hexadecimal. "Enter" and "Cancel" keys may also be included. Like the Button Group, it can be labeled, colored, and its output mappings set: However, it includes additional options for working with numbers - entered numbers (digit strings terminated by Enter) may be converted to analog strength or 16-bit bundled redstone binary, or passed directly to the computer.

-Arrow Keys: A pad with just four buttons with arrows on them. Useful for tasks involving direction, such as the control of Frame machines. 

If implemented, this would simultaneously give the keyboard's rather oddly complex crafting a purpose, as well as providing an extremely useful mid-tier form of control input. Also very aesthetically useful, for builds with a more "industrial" or "lower-tech" aesthetic than having monitors everywhere would imply.

**Comment by Shuudoushi** [comment]
Holy crap the amount of thought put into that, well done! Not going to lie, i would love to see most if not all of that put into OC, though I'm sure it's something that will be for 1.6.

**Comment by gjgfuj** [comment]
Or 1.7.

**Comment by Vexatos** [comment]
event should be `button_pressed`, shipping the address and the index of the button, maybe even the player name (not sure about that one).

Microcontrollers probably wouldn't be able to access these components since Microcontrollers cannot access external components at all. If the Numeric Keypad emits bundled redstone, it would probably work. But a keypad with _n_ buttons should also use _n_ buttons in the crafting recipe...

**Comment by fnuecke** [comment]
(At the risk of repeating myself, the keyboard recipe was a joke that stuck. And I've actually considered changing it, but this might make me not change it :P)

Interesting idea. But the parts when placed should IMHO only have as many buttons as were used to craft them. So the button group has 6, keypad 9, arrows 4 (so here we agree :P).

As for how they work, sure, they can work as components, but as Vex mentioned, I suppose they should also emit a redstone signal, with the strength encoding which button was pressed; that way microcontrollers can use them.

**Comment by makkarpov** [comment]
It also should emit bundled signals with full strength, it's usually easier to decode, much less distance-sensitive and can be used to control plain circuits, not only microcontrollers.

**Comment by Shuudoushi** [comment]
How about making it so you can place a num pad and an arrow pad within the same block space to make some sort of multi-block part? (Number pad goes down as one would expect, but the arrow keys invert and they seem to become one thing, or something to that effect.)

**Comment by TheRealOrangus** [comment]
You think a lot what would a keyboard emit, didn't think how the index of actual real-life keyboard would be translated into index of keyboard in your minecraft world.

**Comment by MalkContent** [comment]
numpad with 9 buttons would be stupid, since it doesn't allow for 0-9 :| i see the need for 12
also a hexadecimal pad (4 keypads?) would be a treat because it's nice to have a 4x4 button layout and because it would play very well with bundled cables

**Comment by Techokami** [comment]
The Project:Red addon Project Blue adds a control panel that can be used as a hex keypad with bundled redstone...

**Comment by MalkContent** [comment]
That is very good for the Project:Red addon Project Blue...

**Comment by S0ZDATEL** [comment]
#2567

**Comment by payonel** [comment]
I've decided to leave this ticket open, unlike how I closed 2567 - but open-for-adoption, which means OC devs don't plan to do this, but if someone in the community works on it and we like the PR, it would likely be merged
The event should be the same key_down/key_up events that full keyboards emit today

**Comment by payonel** [comment]
closing this in favor of os_keypad: https://github.com/PC-Logix/OpenSecurity/wiki/Keypad
if people want this, i recommend including open security in your pack
