### ISSUE TITLE
[feature-request]  linked switches

### ISSUE THREAD

**Issue by kevinkk525** [MightyPirates/OpenComputers#1334]
At the moment we have switches and wireless access points. What I would love to see are linked switches, so basically a switch with a linked card in it. 2 of those are linked together by their linked cards. 
They can be crafted in pairs with 2 linked cards or just twice the resources needed for a linked card. 

Especially useful if you have more worlds an don't want to program a proxy and have an additional pc just for proxying in each world.

**Comment by magik6k** [comment]
There is network floppy which you just install onto OpenOS and it uses all network interfaces(Network cards, Linked cards, Wireless, other things). You install it by using `installNetwork` program on all computers that are intended to use/route data(Also note that Plan9k has this API built-in as it's intended to be network-enabled OS). Your setup would look like: 

`computer(Network card) <-switch-> computer(Network, Linked card) ~~~ computer(Network, Linked card) <-switch-> computer(Network card)`.

You can give names to computers in network by doing `hostname [name]` and rebooting. To test connectivity you do `ping host --c=1 -v`. For some stats there is `ifconfig`. Only downside is that you'd have to rewrite your programs to use network [API](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/Network/data/usr/man/network). It should be possible to create fake component on UDP protocol.

**Comment by kevinkk525** [comment]
Thanks for that hint. Did not think about that API but to be honest, it is easier if I write a proxy by myself than changing programs to use the network API after I already wrote a modem API that uses the normal modem_message system. The proxy program probably isn't more than 60 lines of code. 

But linked switches would still be awesome. Of course that block should take an incredible amount to of energy.

**Comment by skyem123** [comment]
To be honest, I don't see any reason for or against this, as it would be useful, yet at the same time, it could be overpowered.

**Comment by kevinkk525** [comment]
Why could it be overpowered? It could be costly if it uses a lot of power. Much like contacting the ISS :D 
Probably it is a question of how much efford it is to program as not many seem to want this block or find it useful.

**Comment by skyem123** [comment]
I would probably use this if it was available.

On 2015-07-29 12:03, kevinkk525 wrote:

> Why could it be overpowered? It could be costly if it uses a lot of
> power. Much like contacting the ISS :D
> Probably it is a question of how much efford it is to program as not
> many seem to want this block or find it useful.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MightyPirates/OpenComputers/issues/1334#issuecomment-125920186.

---

This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by magik6k** [comment]
Maybe switches could get card slot in GUI which would allow insertion of wireless/linked cards. This way access points would be redundant, which is nice IMO as this mod is about modularity and not about having 1000 types of blocks that do slightly different things.

As I don't want to create a separate issue for that: Putting optional eeprom into eeprom/card slot in switch to change the way it works, as some protocols allow learning computer addresses, etc.

**Comment by kevinkk525** [comment]
You are right about that, a general switch that is upgradeable by network cards (cable,wireless,linked) would be great.

**Comment by TheRealOrangus** [comment]
It would be really awesome with a card slot, specially to put a Linked Card there, and from a computer send/recieve data just to/from the switch, across any distance and across dimensions.

**Comment by fnuecke** [comment]
Ehh, I kinda like the idea of upgrading a switch with a WLAN card; as for linked cards... as long as it's still just for network messages (i.e. not actually merging the two networks), maybe...

**Comment by kevinkk525** [comment]
yes only to send network messages, not merging two networks. that would be awesome, thanks
