### ISSUE TITLE
Common substrings (e. g. "Tier") should be translatable more efficiently

### ISSUE THREAD

**Issue by dgelessus** [MightyPirates/OpenComputers#1335]
There are a number of words and substrings that are used many times, such as "Tier" or item stats like "Supported components". Translating these involves a lot of copy-pasting to try to make them consistent.

For example, here are a few lines from the current `en_US.lang` file:

```
item.oc.ComponentBus0.name=Component Bus (Tier 1)
item.oc.ComponentBus1.name=Component Bus (Tier 2)
item.oc.ComponentBus2.name=Component Bus (Tier 3)
item.oc.CPU0.name=Central Processing Unit (CPU) (Tier 1)
item.oc.CPU1.name=Central Processing Unit (CPU) (Tier 2)
item.oc.CPU2.name=Central Processing Unit (CPU) (Tier 3)

oc:tooltip.ComponentBus=This expansion allows servers to communicate with more components at the same time, similar to how CPUs do.[nl] Supported components: §f%s§7
oc:tooltip.CPU=An essential component of all computers. The clock rate is a bit unreliable, but what do you expect when it runs on a pocket sundial?[nl] Supported components: §f%s§7
```

My suggestion would be to restructure the strings like this. (The identifiers are temporary - you should probably choose new names yourself, I don't know anything about how these strings are used internally.)

```
oc.commonstrings.TierSuffix=(Tier %d)
oc.commonstrings.SupportedComponents=Supported components: §f%s§7

# These are for all three tiers - a single tier's name is generated by appending the tier suffix.
item.oc.ComponentBus.name=Component Bus
item.oc.CPU.name=Central Processing Unit (CPU)

# The "Supported components" line is appended automatically.
oc:tooltip.ComponentBus=This expansion allows servers to communicate with more components at the same time, similar to how CPUs do.
oc:tooltip.CPU=An essential component of all computers. The clock rate is a bit unreliable, but what do you expect when it runs on a pocket sundial?
```

The general layout of the strings is the same, e. g. in tooltips the item stats always come after the general description. This means that the accuracy of the translation would not suffer because of this change. (I'm not suggesting that sentences should be "ripped apart" by translating single words, but that logically separate text sections should be separate in the lang files.)

**Comment by Vexatos** [comment]
Don't forget the grammar part. there will need to be a `item.oc.ComponentBus.grammar=%1$s (%2$s)` to determine the order while the tier suffix would then be `Tier %d`. This is necessary because certain languages have different ordering of words. Additionally, custom hardcoded strings would still be necessary (something like `item.oc.ComponentBus.1.name`) because some languages are weird. You could use `StatCollector.canTranslate(key)` for this.

**Comment by fnuecke** [comment]
Uhh, how does grammar come into play with a suffixed-in-braces bit of additional info? It could just as well be on a new line.

That aside, I'm skeptical that this'll be worth it. Currently it's a little bit of copy-paste, sure, but actually more flexible. One issue that immediately comes to mind are the "(Creative)" things. Internally they're just another tier/number.

**Comment by magik6k** [comment]
Also it seems to be really hard to implement in way that'd be compatible with for example Polish language where we have tons of grammar that may not be included there.

**Comment by makkarpov** [comment]
English grammar is pretty simple (for machine processing) compared to national ones. If you look at Chinese language file, you will notice that tier notation does not use digits and parentheses at all and tiers are prefixed to item.

**Comment by dgelessus** [comment]
@makkarpov Re. the Chinese translation: Google Translate tells me that the Computer Case tiers are really translated like this:
- Base chassis
- Advanced Chassis
- Super Chassis

Before you blame Google Translate, http://leo.org/ gives me similar meanings for the first two characters. They are certainly not numbers, but correspond to "base", "higher" (in various contexts) and "super".

Surely there are numbers in Chinese? Then again, maybe "Tier 1" is not something you would/could write in Chinese. Anyone around here who speaks Chinese?

@magik6k Would you put "(Tier 1)" elsewhere than after the item name in Polish?

Assuming that the tier suffix is something that cannot be generalized easily, things like "Maximum resolution" or "Supported components" could be separated though, right? They are part of the "stats" section of the tooltip, which is _always_ after the general description.

**Comment by Kubuxu** [comment]
As I started doing Polish translations just now, `Tier` it is not that bad. Main problem would be if we wanted to be 100% grammatically correct, some things need `Poziom` other might need `Poziomu`. But on the other hand you should choose one and keep it consistent unless I am missing something (I was never best in Polish)
IMHO it is good enough in current state. It isn't like every item in OC has tiers nor there is 500 of them.

**Comment by makkarpov** [comment]
I also think that currently lang system is flexible enough to hold national language features and does not require a lot of copy-pasting work because there are not so many tiered items.

The real improvement would be to move language definitions to translation service like crowdin, so translators will not have to submit separate PRs for each improvement.

**Comment by Kubuxu** [comment]
I have to agree with that. I've started translation but I am missing few words. Now I would have to send PR so other Polish seekers can discuss it.

**Comment by fnuecke** [comment]
The last time I looked at crowdin I saw prices and closed the tab; just saw they offer it for free to open source projects, so that's indeed a possibility I guess. If there's interest I can look into setting that up, I suppose OC is kind of at the size where that can make sense.

**Comment by fnuecke** [comment]
Oh right, this is still open. So yeah, been convinced that crowdin is a bad idea by a certain someone, and still think the current system is really quite good enough.
