### ISSUE TITLE
bit32 is missing under Lua 5.3

### ISSUE THREAD

**Issue by Techokami** [MightyPirates/OpenComputers#1338]
This breaks programs that use it, like wocchat. :disappointed:

**Comment by magik6k** [comment]
It's deprecated in Lua 5.3, Plan9k(MPT, not (yet) the floppy version) has compatibility code by default.

Workaround code:

``` lua
--lua 5.3 <-> 5.2 compat
local bit32 = bit32 or load([[return {
    band = function(a, b) return a & b end,
    bor = function(a, b) return a | b end,
    bxor = function(a, b) return a ~ b end,
    bnot = function(a) return ~a end,
    rshift = function(a, n) return a >> n end,
    lshift = function(a, n) return a << n end,
}]])()
```

It's missing one or two functions IIRC, but it is enough for 99% of programs

**Comment by Vexatos** [comment]
"deprecated" meaning it's been completely removed from Lua 5.3. A workaround to re-add it would probably be good for compatibility, but I am not sure whether it should be done.

**Comment by Techokami** [comment]
Good to see that Plan9k uses it, shame that a lot of programs are made for OpenOS and haven't been ported over (like the aformentioned wocchat).
I'll try adding the compat code as a lib for the time being.

**Comment by Techokami** [comment]
Okay that code did not help:
![screenshot 197](https://cloud.githubusercontent.com/assets/1530728/8938733/60ffbc3e-352e-11e5-9d41-5469db17bfb1.png)

**Comment by dgelessus** [comment]
If `load` returns `false` that means the code could not be compiled. What does `print(load([[the code]]))` show?

**Comment by fnuecke** [comment]
Eh, I suppose OpenOS could live with a compatibility lib in case it's 5.3, given how hot-swappable everything else is.

**Comment by fnuecke** [comment]
In OpenOS as of f7386842d8a4ef957f1d2fecba594a8f1ab87b50. Someone might want to test this, I only did very rudimentary checking...

**Comment by Techokami** [comment]
I'll give it a spin later on.

**Comment by Techokami** [comment]
It seems to be working well! :grinning:
