### ISSUE TITLE
Modems should use IPv4 addresses - Network Stacks?

### ISSUE THREAD

**Issue by womayhem** [MightyPirates/OpenComputers#1339]
Hey guys, thanks for your help with my past 2 issues.

I think there should also be an option in the config to use IPv4 addresses instead of the much longer addresses that are used now for modems, so that when you want to send messages directly to a modem, the IP is much easier to remember, especially when using the lua prompt.

**Comment by makkarpov** [comment]
No. If you don't like to remember UUIDs, store them, use broadcast or write some resolving daemons. Modems are low-level layer, if you want to build some network, you should use some networking stack anyway.

**Comment by skyem123** [comment]
This might get confusing...

**Comment by fnuecke** [comment]
Yeah, the modem addresses are more like rl MAC addresses, I suppose. There already exist some network stacks that build on top of the existing hardware to facilitate networking (there's even a loot disk).

**Comment by womayhem** [comment]
Where can I find these Network Stacks?  I already coded a resolver and it works it's just that I wanted shorter identifiers.

**Comment by gjgfuj** [comment]
The network loot disk in OC, and you can write a map between uuids and any
ids you want.

**Comment by riddlea** [comment]
Cool, but are the UDP and TCP functions used for in-game servers/computers?
