### ISSUE TITLE
Random idea: Right-click GUIs for floppies

### ISSUE THREAD

**Issue by dgelessus** [MightyPirates/OpenComputers#1340]
This might be a little more gimmicky than actually useful, but here goes. Floppies could have a GUI that shows on right-click (or shift-right-click) that looks somewhat like this:

![bigger_floppy](https://cloud.githubusercontent.com/assets/6641959/8973101/4323ccb2-3661-11e5-849d-336dbace371f.png) ![big_floppy](https://cloud.githubusercontent.com/assets/6641959/8973027/49fd280e-3660-11e5-8db4-b12342ba1472.png)

The label field would show the disk's label at the top, and the space below that would be a user-editable text field that can be used for a short description of what's on the floppy. Clicking the write-protection thing in the bottom left corner would do what you'd expect.

**Comment by Voidi** [comment]
Why Github has no Thumps up or Voting feature for Issues?
No more words needed. Totally a interesting and usefull feature.

**Comment by skyem123** [comment]
Well... It sounds cool, and I guess it is realistic.

On Wed, Jul 29, 2015 at 6:23 PM -0700, "Tobias Wohlfarth" notifications@github.com wrote:
Why Github has no Thumps up or Voting feature for Issues?
No more words needed. Totally a interesting and usefull feature.

---

**Comment by Inari-Whitebear** [comment]
That would be cool :o

**Comment by UltraHex** [comment]
I like it. Perhaps also show description in tool-tip while holding shift.

**Comment by fnuecke** [comment]
Sounds like a nice and (probably) easy addition, I'll look into it.

> Why Github has no Thumps up or Voting feature for Issues?

So much this, would help prioritizing features so much :/

**Comment by Inari-Whitebear** [comment]
Well one could use labels as priorities xD

**Comment by fnuecke** [comment]
If one is a contributor, sure :P
The point of voting would be that everyone (with a Github account) could vote.

**Comment by Techokami** [comment]
Why isn't Github itself open source? Then something like this could be PR'd in.

Sent from my Windows Phone

**Comment by makkarpov** [comment]
Github isnt, Gitlab is.

**Comment by dgelessus** [comment]
By the way @fnuecke if you want to you can use the images from my first post, though I doubt they would be usable directly. Compared to most inventory GUIs the "big floppy" is too low-res, and the lines on the label field are probably not large enough for the normal Minecraft font.

**Comment by fnuecke** [comment]
Yeah, I'll probably go for something with that look, but with some adjustments here and there.

**Comment by ExDomino** [comment]
Just a question: is it already possible to lock in readonly mode a floppy? Or this feature will be released when this suggestion will be made?

**Comment by dgelessus** [comment]
Loot disks from the mod jar or the world folder are inherently read-only, other than that all floppies are read-write AFAIK.

**Comment by fnuecke** [comment]
Yeah, there's currently no way to make normal floppies read-only (only loot disks are, as mentioned above). Might look into that though.

**Comment by ExDomino** [comment]
Sneak click? With a message in the chat: Floppy is now in read-only mode.

**Comment by payonel** [comment]
we've since this request built a UI for floppy disks in which you can switch managed mode, and set it readonly (called "locked"). We are using the icon like a disk, and it shows its label, but you can only set this in vai the setLabel api
