### ISSUE TITLE
Getting modem_message events on a closed port

### ISSUE THREAD

**Issue by tghartland** [MightyPirates/OpenComputers#1342]
I have been able to reproduce this on a clean minecraft install with only forge/optifine and opencomputers, so I'm moving this from the IRC to here.
#### Preface

My aim is to be able to connect a full network between dimensions, so I have a central server that all network traffic is routed through. All network messages are broadcast on port 1 with the first parameters of the packet being 
- **originalModem**: the modem address to return to, i.e _modem.address_ when sending
- **switchList**: a list of the microcontroller/switches the packet has been through
- **deliver**: a boolean of whether the packet is to be delivered
- **forAddr**: the target address, or "all" for broadcasting
- **forPort**: the target port
- The rest of the packet data

When a packet is sent, _switchList_ is an empty string and _deliver_ is false. The packet is forwarded by microcontrollers, which add their address to _switchList_ so they know not to resend it when the next microcontroller along broadcasts the packet. When the packet reaches the central server, _deliver_ is set to true, _switchList_ is set back to empty, and it sends the packet back out to the network and to linked cards in other dimensions.

The same process happens with the packet going back, only when it comes to a microcontroller not only is it forwarded, but because _deliver_ is true, it also attempts to send the packet on _forAddr_ and _forPort_. (Or broadcast on _forPort_, if _forAddr_ is "all").

I came across this issue while writing code for a small multi-user chat program for testing purposes. Here are the files you will need to recreate my network.
[bios.lua](http://pastebin.com/kKKcDRER)
[networkserver.lua](http://pastebin.com/TYLCDgZs)
[chatserver.lua](http://pastebin.com/A98SAQLZ)
[chat.lua](http://pastebin.com/7CVhkycB)
#### These are the steps I took to reproduce the issue on a clean install.
- In case it is relevant I am using java 8u31 on windows 8.0.
- Create new vanilla minecraft instance in ATLauncher (or manually)
- Install forge and opencomputers
- (versions 10.13.2.1291 and 1.5.14.30)
- in opencomputers config, set network packets max parts to 16
- start new world
- setup tier3 computer/screen with network card (**cmp1**)
- install openos from floppy
- setup tier3 computer/screen for other tasks (**cmp2**)
- install openos from floppy
- place assembler next to cmp2
- copy bios.lua to **cmp2**
- flash bios.lua to an eeprom
- make a tier2 microcontroller with network card, tier1.5 memory, and the eeprom. this acts as a switch
- place a server rack
- use cmp2 to install openos to two tier3 hard drives
- make a tier3 server with a tier3 gpu, **two** network cards and one of the hdds (**netserver**)
- copy networkserver.lua to **netserver**
- place a second server rack
- create a tier3 server with a tier3 gpu, one network card and the other hdd (**chatserver**)
- place microcontrollers connecting **cmp1** to **netserver** and **chatserver**, as shown below
- copy chatserver.lua to **chatserver** and chat.lua to **cmp1**
- run networkserver.lua on **netserver** and chatserver.lua on **chatserver**
- run "chat abc xyz" on **cmp1**

![diagram](https://cloud.githubusercontent.com/assets/11710676/8997048/21b731e0-3715-11e5-953f-5e17bca3df03.png)
#### Result

chat.lua outputs information about all the messages it receives.
**To repeat the test, chatserver.lua must also be restarted.**

Six messages arrive. Four of the messages arrive on port 1. **Port 1 is not open**. For the messages on port 1, the local address that they arrive to (the second returned value of _event.pull("modem_message")_) **is not the address of the network card in cmp1**. So what is this address? By destroying the microcontroller directly connected to **cmp1** and replacing it with a new one, this address changes. This could mean that the microcontroller is triggering events in **cmp1**.

**Message from: .........** outputs the address of the modem that sent the packet, and is also different for the messages on port 1. This means that these messages were not sent by **the only thing that could possibly send a network message to cmp1**.

Hopefully this should be enough to reproduce the bug, but I can give a download link for the world I made to test this if needed. 

Here is exactly what I see.

![](http://puu.sh/jjoHO/d34a4b457a.png)

**Comment by magik6k** [comment]
You said that your network works on port, and those messages appear to be from it. OpenOS don't have per 'process' event/component separation. The address is most likely address of network card in switch. If you want some more advanced zeroconf network, try using the network floppy as it looks somewhat like what you did. Only downside is that it has no uC implementation because of its complexity.

**Comment by tghartland** [comment]
Alright, I'll take a look at the network floppy disk later. If this isn't likely to be changed then I at least have two workarounds. The first thing I thought of was just ignoring all packets on port 1 where I don't want them. The second way is to put a switch block between any computer/server and the microcontroller they're connected to. This breaks the component connection and only actual network events are triggered. (However it also increases network latency by a considerable amount, which is why I used microcontrollers to begin with).

Thanks.

**Comment by fnuecke** [comment]
Thanks for writing this up in such detail... but... could you please try to create a more minimal testcase? This looks like it'll take quite some time to set up, and is so complex that it'll be hard to actually track that down...

**Comment by fnuecke** [comment]
If you manage to create a _minimal_ repro-case, let me know and I'll reopen this.
