### ISSUE TITLE
(Suggestion) CD-ROM's and CD drives

### ISSUE THREAD

**Issue by flarn2006** [MightyPirates/OpenComputers#1343]
CD-ROM's would be another way to store data, which shouldn't come as a surprise. Crafted with just a disk platter and a glass pane, they'd be cheaper than floppies (not _that_ much cheaper, cause floppies are already quite cheap) and also able to store more data. The downside, as you might have guessed, would be that they can only be written to once.

I'm not quite sure of a good recipe for a CD drive, but I'm thinking it would probably use glowstone and glass. Maybe red stained glass. CD drives can only read CD's, not write to them. But you could craft a CD burner using a CD drive as an ingredient, as an upgrade.

Maybe the CD drive could also play vanilla music discs.

**Comment by skyem123** [comment]
Hm... This idea has already been suggested in issue #714, but that was closed... :cry:

My personal opinion is that CD drives would be cool, as they add more possibilities and things to play with.
I also want CDs to have the ability to both work as a read only file system or a blob of data, depending on how it was created.

**Comment by gjgfuj** [comment]
The issue with that is that they weren't really different enough.

**Comment by skyem123** [comment]
Meh... I want to say I actually like the idea of a CD being able to be "formatted" as a blob of data or as a filesystem. :sweat_smile: 
Actually, the ability to partition the CD to have both at the same time would be quite cool...

**Comment by gjgfuj** [comment]
Yeah, that would be cool. But you can already get both. Floppies and tape
drives.

**Comment by skyem123** [comment]
The thing is that is that tape drives are part of another mod... :sweat_smile:

On 2015-08-01 02:16, Sandra wrote:

> Yeah, that would be cool. But you can already get both. Floppies and tape
> drives.
> 
> On Sat, 1 Aug 2015 11:15 am Skye notifications@github.com wrote:
> 
> > Meh... I want to say I actually like the idea of a CD being able to be
> > "formatted" as a blob of data or as a filesystem. [image: :sweat_smile:]
> > Actually, the ability to partition the CD to have both at the same time
> > would be quite cool...
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/MightyPirates/OpenComputers/issues/1343#issuecomment-126843662
> > .
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/MightyPirates/OpenComputers/issues/1343#issuecomment-126844084.

---

This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by flarn2006** [comment]
@gjgfuj Tape drives? Is that in a pre-release version or something? Because I don't have those.

**Comment by MyNameIsKodos** [comment]
See #714

**Comment by skyem123** [comment]
@flarn2006, tape drives are added by another mod, called [computronics](https://github.com/asiekierka/Computronics).

**Comment by Techokami** [comment]
It's in an addon mod called Computronics, which adds a lot of extra awesome things too.

Sent from my Windows Phone

**Comment by fnuecke** [comment]
I don't think there's a place for CD-ROMs in the mod. I did add an unmanaged mode to HDDs and floppies, though, where they behave as a different component that offers just a large, raw usable chunk of storage (with write/readByte and such).
