### ISSUE TITLE
`java.lang.Number` support for signals

### ISSUE THREAD

**Issue by boq** [MightyPirates/OpenComputers#1345]
In OpenPeripheral I have class `Index`, which is used to uniformly handle integration with languages with 0-based and 1-based indices.

It implements `java.lang.Number` interface, but unfortunately `Context.signal(...)` supports only few built-in sub-classes, so using this class as signal arguments returns `nil`.

Would it be possible to extend support to any number?

**Comment by fnuecke** [comment]
Ah, sure, I can do that. I'm not sure why I even have the explicit stuff in there... I assume it's OK to just `doubleValue()` it to pass it along to Lua?

**Comment by boq** [comment]
Yes, it will work that way.

**Comment by Kubuxu** [comment]
Probably because `long` and `int` (not sure, should make no difference but it would be nice) in case of 5.3 should be passed as Integer not Double.

**Comment by fnuecke** [comment]
Good point, they'll actually get potentially messed up right now... I really need to have another look at pushing queued stuff to Lua right away to get id of that redundant persistence code in the machines...

**Comment by fnuecke** [comment]
Should work now!
