### ISSUE TITLE
Conflict with OpenPeripherals

### ISSUE THREAD

**Issue by Xelat84** [MightyPirates/OpenComputers#1349]
When trying to use proxy with vanilla chest, it uses methods from OpenPeripherals.
And in case with forestry bees it's still cause an issue with deprecated IBee.isIrregularMating().

**Comment by gjgfuj** [comment]
That's because open peripheral supports OC. It would be helpful if OC stuff
overrode open peripheral stuff.

**Comment by fnuecke** [comment]
Uhh... poke @Vexatos because you know more about integration than me at this point >_>

As for that deprecation, that should've been fixed already, what version are you on?

**Comment by Xelat84** [comment]
I'm using OC 1.5.14.30, and it fixed in OC, but it still not fixed in OpenPeripherals.

**Comment by Vexatos** [comment]
@Xelat84 The inventory functions are being added by OpenPeripheral on both the ComputerCraft and the OpenComputers side, even though OC already has an Inventory Controller Upgrade to manage inventories. I talked to @boq, and this won't change. However, you can download [build 65 or later](http://ci.openmods.info:8080/job/OpenPeripheralIntegration/) of OpenPeripheral-Integration and have two new config options containing "inventory". If you disable those, OpenPeripherals' Inventory manipulation functions should not be added to the game.

**Comment by fnuecke** [comment]
As for the deprecated method, better report that to OpenPeripheral then.
