### ISSUE TITLE
Mousing over the power buttons in the gui (Computers, drones, etc) disable lighting.

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1350]
The title explains it all. Im using optifine, which might be the issue.

Also, a secondary issue, the network splitter texture is screwed up (It shows the atlas of every loaded texture, and is partially transparent), might also be an optifine thing.

**Comment by dgelessus** [comment]
The lighting oddities come from Optifine. There were some issues with the Network Splitter textures when it was first added, but they were fixed in the following update. Check that you're using the latest version of the mod.

**Comment by jadenPete** [comment]
I'm using Optifine HD U 5 (the latest) and i can confirm i have this issue too.
