### ISSUE TITLE
Crashing issue with class not being found?

### ISSUE THREAD

**Issue by MJRLegends** [MightyPirates/OpenComputers#1352]
http://pastebin.com/r5q0wL48 Someone who is playing my mod pack thats has this mod sent this to me, thats why its lacking details.

**Comment by Kubuxu** [comment]
Tell them to force update their client. A lib that is installed by forge by default is missing.

**Comment by MJRLegends** [comment]
How do you force update their client?

**Comment by fnuecke** [comment]
Reinstall Forge.
