### ISSUE TITLE
Config options eepromDataSize and eepromSize have identical descriptions

### ISSUE THREAD

**Issue by UltraHex** [MightyPirates/OpenComputers#1353]
In the config file eepromDataSize and eepromSize have the exact same description.

This is from a freshly generated config from OC 1.5.14.30.

```
...
[140]
[141]    # The maximum size of the byte array that can be stored on EEPROMs.
[142]    eepromDataSize=256
[143]
[144]    # The maximum size of the byte array that can be stored on EEPROMs.
[145]    eepromSize=4096
[146]
...
```

Additionally, what's the difference between these anyway? It's obviously fairly subtle, but it should be explained in the config just like everything else.

**Comment by dgelessus** [comment]
The 4 KiB are the EEPROM's executable code, which is loaded by the CPU when the computer is started. This part can also be locked as read-only. The 256 bytes of "data" are like NVRAM and can be used to store a small amount of configuration data. This is used by the default Lua BIOS to store the default boot medium's component address.
