### ISSUE TITLE
[feature-request]  Advanced 3D Printing

### ISSUE THREAD

**Issue by SyrupThinker** [MightyPirates/OpenComputers#1355]
The idea is to have more attributes for 3d prints like conductive (transmits data, Rf etc.) or wearable  (like hats or boots).  A block rotator would also be neat  (or forge multipart like tile placement)

**Comment by Vexatos** [comment]
... "Advanced prints" don't make sense in any way at all.

**Comment by SyrupThinker** [comment]
Well then i think "improved" would be better, right?

**Comment by Vexatos** [comment]
Why would prints be able to transmit data or RF? They're just a blob of colured plastic.

**Comment by SyrupThinker** [comment]
Well i forgot about that... but that also applies to Redstone and Light emissions so i think that should be fine.

**Comment by fnuecke** [comment]
Redstone is in the recipe of Chamelium. Redstone also glows. To get it brighter you need to craft it with glowstone. So it's all "logical", as far as gamey logic goes (I mean, levers emit redstone signals and don't contain any redstone, either, for example).

In general I don't really want prints to get more "functional" than they already are (with the two states). If anything I might look into how feasible it'd be to "reskin" blocks using prints. But probably not anytime soon.

**Comment by SyrupThinker** [comment]
Alright. Thanks for the nice explanation. Look forward for more awesome stuff coming.
