### ISSUE TITLE
Wireless Charging Upgrade

### ISSUE THREAD

**Issue by gudenau** [MightyPirates/OpenComputers#1356]
I would like to have a wireless charging upgrade for the tablets, I was working on a repeater for CC that I wanted to have work without maintenance, but having to manually charge the tablets prevents that.

**Comment by dgelessus** [comment]
IIRC you can install a solar panel upgrade in a tablet, though I'm not sure how much energy that generates and whether that is enough to sustain a running tablet.

**Comment by gudenau** [comment]
Does not keep up.

**Comment by fnuecke** [comment]
Hrm, since the charger is already sorta-kinda wireless charging in a 3x3x3 area I might look into making it also charge OC items in players' inventories when they stand close to it. That would be in that same radius tho, i.e. you'd have to stand next/on it for that to work.

**Comment by payonel** [comment]
open for adoption to charge items in player inventory
