### ISSUE TITLE
Remote Charging

### ISSUE THREAD

**Issue by TheRealOrangus** [MightyPirates/OpenComputers#1357]
So I suggest this:

The Radio Charger
it will charge devices remotely, but they will get the less part only of the energy, used by the Radio Charger, the other part will be lost, due energy would just spread around.

The Radio Charger is a separate block, which is the same to Power Distributor, as Access Point to Switch, or it could be Power Distributor with Wireless Network Card inside, or some upgrade.

The Tunnel Charger
it will charge devices using a tunnel, the same one used by Linked Cards, the charging device will get some piece of the energy used by the Tunnel Charger, but the tooken energy is independent to the distance and can go cross dimensions(obviousely).

The energy from the tunnel would be recieven through Linked Card, or some new "Tunnel Energy Card".
The Tunnel Charger is a separate block which crafted of Linked Card(or "Tunnel Energy Card") inside, or with a slot for it.
The Tunnel Charger could be not a separate block, but a Power Distributor with a slot for card, and something like "Tunnel Energy Upgrade".

**Comment by SaphireLattice** [comment]
Tunnel Charging seems "a little" overpowered.
Radio Charger would also look better if it could charge devices with an receiver upgrade installed in it. And perhaps make Charger constantly emit energy while on and distribute it trough every receivers equally (equally as in equally emitted not received, because distance losses).
Also, i think #1356 should be closed in favor of this issue.

**Comment by Vexatos** [comment]
This seems to belong into [OpenRadio](https://github.com/XDjackieXD/OpenRadio)...

**Comment by fnuecke** [comment]
Remote charging over arbitrary distances seems a little... too much for OC IMHO. There's a dead addon that added tesseract upgrades IIRC, someone might be interested in updating/rewriting that. Or, as mentioned, possibly via OpenRadio (some day?).

I might make the charger charge stuff in inventories of near entities, but that'd be very short-distance; the tunnel-thing is much too tesseract-y, sorry.
