### ISSUE TITLE
[Feature-Request] Wireless Screens

### ISSUE THREAD

**Issue by aschmois** [MightyPirates/OpenComputers#1358]
I've always wanted to setup a wireless monitor so that I didn't have to ruin the walls surrounding the monitor. I tried to look for a way around this but I can't find anything. Wired monitors are just too much of a hassle.

Maybe an AIO screen could be feasible as well. Computer + Screen built in and extra monitors extend it, but the computer and one screen takes up one block only.

**Comment by gjgfuj** [comment]
1: you can cover cables.
2: you can run cables into the back or the bottom of screens.
Wired cables aren't that hard.

And the second one? Been discussed many times. Not happening.

**Comment by fnuecke** [comment]
There are enough ways of hiding cables, IMHO, as pointed out by @gjgfuj. You can even make 3D-Prints that act as special-tailored covers, if normal ones aren't good enough.
