### ISSUE TITLE
Multi core Processors

### ISSUE THREAD

**Issue by TheRealOrangus** [MightyPirates/OpenComputers#1362]
Each time when I want more than 1 thread of execution, I have to make a server rack with more than 1 server inside, which is not nice. 
# The idea

CPUs and APUs would have more than 1 core, and provide `processor` componen/API?
The number of cores in a processor is the tier number of it(Creative APU would have 3 cores).

The `processor` component/API description:
`processor.run(luacode: string[, core: number = 1]): boolean[, string]` - runs a lua string on the specified core, returns true on success, false and error string otherwise.
The eeprom code is executed on the core 1.
The core cannot start execution of a new program, if it's already running a process.
`processor.status([core: number = current]): boolean, string` - returns whether specified `core` is running a process or not, and string containing information(error for example) about the core process.
`processor.informate(status: string)` - set's the information status string of the current core, the exactly that string which is returned by `processor.status()` if this core is running.
`processor.cores(): number` - returns the number of processor cores.
`processor.core(): number` - returns the core this core process is running on.
`processor.stop([core: number = 1]): boolean[, string]` - stops execution of the core process on the specified `core` instantly, returns true on success, false and error string otherwise.
After calling this function, the core would be able to run a new process on it via `processor.run()`.
`processor.pause([core: number = 1]): boolean[, string]` - pauses execution on the specified `core`.
After calling this function, the core would be able to continue execution via `processor.run()` with no arguments passed.
If the core index is out of range, false and the error string _"Invalid core index"_ is returned.

The processor energy usage is multiplied by amount of running cores. So as an example, the process which is running 3 of 3 cores requires 3 times more energy than the same processor kind which is running only 1 of 3 cores.

**Comment by fnuecke** [comment]
Aside from the fact that in this concept there's no method for the separate cores to communicate, why can't you use coroutines / events? If OpenOS feels to limiting wrt. parallelism, have a look at plan9k.

If communication between the cores is not needed I feel having multiple computers (e.g., as mentioned servers) is the more appropriate solution in the context of OC, tbh.

**Comment by TheRealOrangus** [comment]
The difference to server rack is that, that all the components and even RAM shared between all of the cores, and each of them has access to lua context, for example:
```lua
-- core1
function foo() print "foo" end
```
```lua
-- core2
while type(foo) ~= "function" do end -- wait until function "foo" would be created
foo() --> "foo"
```
the execution of cores wouldn't be _thread save_.
but sure, thread save program can be created via `load()` with custom `_ENV` field:
```lua
-- some core
protected_thread = load('print "foo"', "protected_thread", "bt", {})
protected_thread() -- this function would have no access to variables of other environments, as other environments would have no access to context of this function(in this case).
```

**Comment by TheRealOrangus** [comment]
> Aside from the fact that in this concept there's no method for the separate cores to communicate

There is no need for this, because they are not different computers, and they would _share_ same components and same RAM, for example:

``` lua
-- core 1
sleep(10) -- some abstract function to wait 10 seconds
function foo() print "bar" end
```

``` lua
-- core 2
while not foo do end -- wait until "foo" would be created
foo() --> "bar"
```

But thread save programs would still be possible:

``` lua
-- some core
protected_thread = load('print "bar"', "protected_thread", "bt", {}) -- table constructor as paremeter, would disallow to access context of this function
protected_thread() -- thread save execution
```

**Comment by magik6k** [comment]
For that, try Plan9k. It has io.popen, os.spawn functions, as well as demon manager and the 'command&' shell syntax to spawn things in background. For os.spawn syntax look there: http://lua-users.org/wiki/ExtensionProposal (Note that passing a function to os.spawn will spawn it as a thread with shared environment, etc. ). To see what threads are running, there is 'ps' command

**Comment by magik6k** [comment]
And yes, with threading your code would work, except you'd have to put os.sleep(0) in loop waiting for foo, and another sleep after foo definition(os.sleep(0) in plan9k costs almost nothig, there are much more methods to yield to kernel(IPC, signals, etc.))

**Comment by TheRealOrangus** [comment]
> except you'd have to put os.sleep(0) in loop waiting for foo, and another sleep after foo definition

Not sure it's the thing I need..

> more methods to yield to kernel

Yielding... just like in coroutines, the problem is that I don't need it to be yielded, because In my system there are "interface drivers", a wrappers for some user-defined interfaces, and allowing drivers to just stuck the system is a sequrity issue, like it allows to create malicious software...
Because in my system, there is main computer, database and 8 terminals, terminals is used to create and share the stuff, players just put their lua codes there, and if player could just to create a thing which would stuck a terminal host for ever..

I can't describe all parts of the system and how it works, because it's too hard..
you see, I need a system with fluent lua code execution sperately and independetly to it's code(like servers)..
And same time sharing its data(like coroutines)..

Sure the system has different solutions, and I made 2 system cases per terminal and each time hard code some program for gpu usage synchonisation through the network, because on it's GUI there's a `[run/stop]` button which runs/stops the execution independently to it's code, but starting a program requires some time and that system case stuff, it's quite hard to enchance and debug the system..

**Comment by magik6k** [comment]
Well, the busy loop would crash the program without yielding anyways. The only way for now to really hang plan9k multiprocessing module is via calling some component in a loop, and I can easily fix that. Aside that, plan9k seem to fit your use case, so I'd suggest looking into it. Also, sorry for lack of the docs. Most stuff works as in OpenOS, except gpu component, which should be used via vt100 codes, so that telnet/ssh works.

**Comment by TheRealOrangus** [comment]
> Well, the busy loop would crash the program without yielding anyways.

But it would stuck for some time before to crash anyway.

> hang plan9k multiprocessing module is via calling some component in a loop, and I can easily fix that. Aside that, plan9k seem to fit your use case, so I'd suggest looking into it. Also, sorry for lack of the docs. Most stuff works as in OpenOS, except gpu component, which should be used via vt100 codes, so that telnet/ssh works.

As I said, I already have working system(used 2 system cases per terminal), but such things like multi-computering, manual thread switchers(yielding, like in plan9k) and code parsers(you could implement that, btw), these things are just _"spikes"_. Mutli core processors won't do new stuff, yes, but do datacards do? it just makes things a lot of times easier, just allow programmer to omit implementing very hard things.

**Comment by Kubuxu** [comment]
Problem is that your idea brings new level of complexness.

It is not easy to make two lua workers work on same context, if at all possible. It might be nice user code wise but it is hardly possible implementation wise.

As for something that `won't do new stuff` it would require crazy amount of man-hours to make concurrent workers in one lua context work also it would be too lua oriented and Oc allows for custom archs.

**Comment by fnuecke** [comment]
What Kubuxu said, this would require a lot of time to implement, and to get right (because more threading means more potential threading issues, of course \o/).

So yeah, but no. Just use plan9k and yield where it makes sense :P
