### ISSUE TITLE
Assembled components (aka complexity ^2)

### ISSUE THREAD

**Issue by Aleszp** [MightyPirates/OpenComputers#1366]
<h3>Introduction</h3>

While playing OC and later while mingling in real PC (with MS-DOS 6.22) I got a little idea that probably would fit in OC and make computers even more customizable.

<h3>What do I mean</h3>

Components (and other computer parts such as CPU, APU, etc) could instead of tiered recepies (in crafting grid) be assembled like drones/micro-controllers/robots do.
I don't mean tedious complications such as those: https://github.com/MightyPirates/OpenComputers/issues/1043 (and btw. battery AFAIK doesn't hold eeprom data, but CMOS data which is separate).
I'll try explain what I mean by few examples:

<h3>Examples and possibilities:</h3>

<h5>Graphics card</h5>

Let's look at graphics card which each tier has its operations speed, maximum color depth and resolutions. Instead card could consist of chipset (VPU is still proper name in non-accelerated graphics card?) which would define it's speed and of memory from which both resolution and color depth would depend (as like in CGA/EGA/VGA etc where lower resolution meant more colors, on VGA 640x480 was in 4bit, 320x240 in 8bit, because memory didn't support more).
It could be used to fulfill https://github.com/MightyPirates/OpenComputers/issues/779 too. 
(Screens could define colors and resolution, though why couldn't 2x2 T1 screen allow using doubled yet still monochromatic resolution?)

<h5>Network card (aka NIC) </h5>

Another example could be NIC which could now differ with it's parameters (like switches and access points already do with upgrades). If we crafted it with cheapest parts than it would be slower, if with better ones than faster/send more data/etc.

<h5>Redstone card</h5>

Redstone cards could also differ as there could be cheap redstone card with only digital redstone, redstone card enhanced with comparator (which would support analog) or enhanced/replaced with bundled redstone controller (to support bundled redstone) (upgrades could be mixed to allow reading analog bundled redstone or both analog redstone and analog bundled redstone).

<h5>CPU and APU</h5>

This way APUs could be crafted in a way CPU is crafted (but of course with extra graphics components). Now there could be slow (like T1 CPU) CPU which control many components and fast T3 like CPU that supports few components (if somebody doesn't need many components and can't afford full 486like T3 CPU why not use overclocked 286 which is like T1+ ?)

<h3>How to assemble component</h3>

The way of assembling would be: 

<ol><li>User puts card base/cpu control unit (or whatever would be it's base). </li>
<li>User chooses what type of card (or whether CPU or APU) he(or she) wants to assemble (probably from some kind of combo-box). Assembler tells which parts are necessary to construct it and what optional parts can be added/altered.</li>
<li>User adds required parts such as control unit for graphics card or CPU. In some cases user may alter them with higher/lower tier parts to get card with better features (more VRAM to increase resolution/color depth in video card) or cheaper card (like slower video processing unit which would make card work slower).</li>
<li>User adds optional such as analog controller or bundled redstone socket to redstone card (or both upgrades). </li>
<li>User clicks "START" in assembler.</li>
<li>???</li>
<li>Profit! </li>
</ol>

<h3>What would happen to existing components?</h3>

There could be ready presets that would hint user what to put to get something useful (already existing tiered parts which would be transformed to new system as cards made out of parts that would let them keep identical functionality). 
T1 graphics card would have T1 chipset and 800 bytes memory (or 1600 bytes if it uses 2 bytes per char), T2 card would have T2 cipset and 8kB (or 16kB if it uses 2 bytes per char) etc... 

<b>tl;dr:</b>
Instead of tiered components let's have modular components made out of tiered parts.

@skyem123: Splitted into paragraphs, added headings, etc.... I hope it's now more understandable.

**Comment by gjgfuj** [comment]
I like.

**Comment by SaphireLattice** [comment]
The looks pretty nice, modularity all the way down to the cards? I like it.

**Comment by skyem123** [comment]
I'm sorry, but I cannot read it when it is a big wall of text, can you split it up into paragraphs and add headings?

**Comment by Techokami** [comment]
Huh, this sounds like an interesting concept. Possibly something for OpenComputers 1.7?

**Comment by TheRealOrangus** [comment]
It's a nice idea, I actually wanted to create a such issue ;D
If a card would have GPU, then you could put more than 1 ALU to define it's speed.

**Comment by fnuecke** [comment]
While in principle this sounds nice, there's two issues I see with this:
1. It sorta-kinda smells like microcrafting / throws another step in the way of getting started. Specifically, you'd now actually _need_ an assembler to build your first _computer_.
2. The assembler is not designed to support generic items, it's specifically designed for assembling devices (i.e. it has slots for upgrades, containers, cards and the other components that go into a case). In particular this also means the API does not support this, meaning it'd need changing. And I usually try to avoid API changes, to avoid breaking stuff, obviously.

Finally, I'm not quite convinced this brings enough benefits over the current tier system to justify the effort it'd need for this to be implemented.

**Comment by fnuecke** [comment]
After some more thought, too much complexity for what it brings IMHO. Should be doable via an addon mod, though, so if someone wants to make something like GregTech for OC, I think that's where it'd fit in :P
