### ISSUE TITLE
Change the tablet_use event to (also) fire on left click

### ISSUE THREAD

**Issue by h3po** [MightyPirates/OpenComputers#1367]
To trigger the tablet_use on right-clickable blocks like chests, one has to press shift-right-click, which reboots the tablet. What keeps us from having the event fire on a left click?

related: Tablets cannot be opened when looking at a block #905 

Here's what I used to play around with the tablet_use event, could add it to the wiki if you like it as an example:

```
local event = require("event")
local term = require("term")

function printblockinfo(eventname, data)
  term.clear()    
  for name, info in pairs(data) do
    print(name .. ": " .. info)
  end
end

print("listening for tablet_use events")
event.listen("tablet_use", printblockinfo)

event.pull("interrupted")
event.ignore("tablet_use", printblockinfo)
print("done")
```

**Comment by dgelessus** [comment]
Alternatively fire `tablet_use` for both punch and use, and pass an extra integer with the event that says which of the two happened. Similar to how the screen `touch` event has the mouse button number as event data.

**Comment by fnuecke** [comment]
You have to keep holding the right mouse button and wait for the _beep_, otherwise yes, it'll open the tablet's inventory. But if it beeped (meaning the block was scanned and the event was triggered), the tablet's inventory won't be opened an the tablet won't stop. Sooo, no cause for action I think.

But for the heck of it, other random reasons:
- Right click is the de-facto standard of how things are "used" in Minecraft.
- AFAIK there's no "onLeftClickOnBlock" callback in items. (there's `onBlockStartBreak` but unless I'm mistaken that's only called when the block would actually break, not when first clicking on it)

**Comment by gjgfuj** [comment]
There is a left click event somewhere in item, I'm sure of because I've
used it before.

**Comment by h3po** [comment]
@fnuecke It may be a timing issue depending on the tickrate, but I'm definitely not able to shift-right-click a chest without the tablet restarting. After holding the keys down long enough, it beeps and then restarts. I've tried holding shift for a shorter time than the right mouse, but then it doesn't register the tablet_use.

**Comment by fnuecke** [comment]
Uhh, that's unlikely; what version are you on? And which Minecraft version?

**Comment by fnuecke** [comment]
Tested it again on both versions of MC, works fine on both. When you say "it beeps then restarts", do you mean the right-click GUI opens so it stops, or does it reboot right away? In that case I strongly suspect some bug in usercode that causes the tablet to reboot...

**Comment by fnuecke** [comment]
Also please do make sure you're on the latest version of OC, because that's obviously what I'm testing with.

**Comment by natedogith1** [comment]
I seem to be having this issue as well. 
To reproduce:
  take a tablet (only tested with creative)
  shift-right click (opens the floppy gui thing)
  close the gui
  right-click
  hear beep and watch tablet restart

**Comment by fnuecke** [comment]
That is how it's supposed to work. Unless you mean shift-rightclick (and holding! never forget the holding) opens the GUI even when looking at the block. In which case, please let me know what block that is, because that's not happening for anything I try with, and I'll re-open this.
