### ISSUE TITLE
modem.setWakeMessage and multiple arguments

### ISSUE THREAD

**Issue by etnpce** [MightyPirates/OpenComputers#1368]
Currently, using a wake message requires the sender to send only one data parameter, I feel that either setWakeMessage should be able to take multiple arguments to match to the sent data, or should ignore additional parameters sent to the modem with the wake message
for example, using `component.modem.setWakeMessage("tst","arg2");component.modem.open(1);computer.shutdown()` and then having another computer do `component.modem.broadcast(1,"tst","arg2")` does not wake the first computer, because the second argument of setWakeMessage is ignored, while the second data argument of the recieved message isn't.

**Comment by fnuecke** [comment]
Uhh, why? In your example you're just using the API wrong, so that's really not a reason to change anything. Unless you can provide an actual use-case I see no need to change this behavior.

**Comment by etnpce** [comment]
Well, really, this would be a convenience thing, so I'll close this if you don't think it needs to be changed, but the thing I was going to use this for was a simple networked filesystem.  I was going to make the first argument of all the related messages `"FS"`, and make the server auto-shutdown when not in use.  I was originally planning to wake it with a message `"FS","wake"` but that doesn't work, so I had to change it to `"FS:Wake"` instead, also changing every other command,  I would like this change so that my server could start either (depending on which route you want to take) when it receives `"FS","wake"` or just whenever it receives a message in the format `"FS",...`

**Comment by fnuecke** [comment]
Ah, well. I don't really want to make it match any prefix by default, because that makes it less precise than it is now, but I guess I could add an option to allow it triggering regardless of number of parameters, something like `setWakeMessage(blah, true)`.
