### ISSUE TITLE
Computers not turning on

### ISSUE THREAD

**Issue by KFAFSP** [MightyPirates/OpenComputers#137]
I'm running OC with a modified FTB Monster Server (works perfectly fine on singleplayer) on a Windows Server 2003 RC2 x64bit SP2 Operating System. I cant turn on computers in-game (nothing happens except for the button turning green), and OC claims that there are no native libs available (as said on the frontpage - Srv 2003 is Win XP Codebase).

I can get behind the no persistency thing, but why won't anything happen at all?

I cannot provide logs with meaningful content, since the ForgeLog on the server neither contains errors nor any other entries regarding OC apart from the init events.

**Comment by fnuecke** [comment]
Totally forgot to re-test the fallback recently... sorry about that. [Dev build 164](http://ci.cil.li/job/OpenComputers/) should fix it, please give it a try. Thanks for reporting!
