### ISSUE TITLE
Tier 2 and tier 3 eeproms

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#1371]
My idea is to create two tiers of eeprom: tier 2 and a tier 3.

Actual eeproms have 4 kB for their program and 256 k for their memory.
Tier 2 would have 8 kB and 512 k (x2).
Tier 3 could have 16 kB and 1024 k (x4).

I have had this idea when I sent my idea about microcontrollers: #1369

**Comment by Vexatos** [comment]
There is a reason EEPROMs are so small... µControllers and Drones are supposed to provide a challenge of coding with limited space (Or for instance utilizing the RAM by using netbooting programs, etc.).

**Comment by ExDomino** [comment]
You can make them really expansive, but 4 kB is really too small. But an idea could be to make that eeprom of tier 2 and 3 can only work inside a computer of the good tier.

**Comment by Kubuxu** [comment]
@Vexatos 4k it is really a little.

**Comment by Vexatos** [comment]
@Kubuxu So far, I have never felt the need for something bigger than that. µCs and drones are there to accomplish the most simple of tasks, for anything else, there's computers and robots. It is _meant_ to provide a challenge for you (proper space management).

**Comment by BlackHatJack** [comment]
@ExDomino 4k isn't actually that small, especially if you take a network bootloader approach.

If you out grow a EEPROM, you may wand to up your case to a computer/robot, and utilize floppy/HDD space.

**Comment by ExDomino** [comment]
BlackHatJack: Yep, you're right. I really like when you help me finding a way to do what I want without the need of waiting for my suggestion to being accepted. Really, I'm not sarcastic, thank. ^^

**Comment by fnuecke** [comment]
If anything, the idea of tiering the EEPROM slots and only allowing the higher tiers in computers / servers might be something I could be convinced of. But this would make MCUs even more niche than they already are (vs. using a T1 or so case), which I'm not so happy with.

**Comment by ExDomino** [comment]
For now, MicroControllers have only 2 tiers, so they will be limited to 8k of memory (eeprom of tier 2 in the MicroController case of tier 2), and 512 byte of variable memory.

---

But if you really want to keep the low storage of eeproms, you could do the same than with Battery, so tier 1 is 4k, tier 2 could be 6k (the maximum possible in a MicroController) and tier 3 could be 8k. For their variable memory: 256 bytes, 384 bytes and 512 bytes. Like this, only an addition of 2k would be available for MicroControllers and everyone will be happy. ^^

Tier 1: 4k and 256 bytes.
Tier 2: 6k and 384 bytes.
Tier 3: 8k and 512 bytes.

Since there is no tier 3 MicroController case, you cannot use tier 3 eeproms with 8k on them.

**Comment by fnuecke** [comment]
> everyone will be happy

If only it were that simple :P

**Comment by magik6k** [comment]
I don't feel need for it, netbooting uC does the trick, and with a little effort one can boot whole OpenOS on it.

**Comment by fnuecke** [comment]
Will stick with EEPROM as it is for now. If someone wants more, make an addon :P
