### ISSUE TITLE
Small screens for microcontrollers

### ISSUE THREAD

**Issue by TheRealOrangus** [MightyPirates/OpenComputers#1374]
#### The Idea

I think it would be realstic if minecrocontrollers would have a small screen like 8x3 on it and 2-4 pallete colors that is configurable when it's assembled, and not via API.
#### Purpose

Is just for simplest output and control of it(maybe like touch screen), as **microwaves** and **washing machines** do.

**Comment by fnuecke** [comment]
For rendering it in world, the "display" area of the MCUs is just way too small, and I don't want to give them a GUI. Sorry, just slap a sign on them.
