### ISSUE TITLE
Useradd could be used to determine if a player is online or not

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#1376]
At this moment, the useradd function only work for online players, so if you try to add another player to the protection list of user for a computer and then check if this player has been added or not, you could be able to determine without creative computer and debug card if that player is online or not. If the player was sucessfully added, that means he's online and then the program has just to remove him instantately.

**Comment by fnuecke** [comment]
Then listing the users would still have that issue. In what scenario is this a problem anyway? I wasn't even aware there was a way to hide players in the player list.

**Comment by makkarpov** [comment]
Such way exists using Bukkit and plugins, but I do not think that "leakage" of online users is an issue here.

**Comment by fnuecke** [comment]
So yeah, since I don't think there's a good way around this besides tracking every login into some file/tag (to remember that the user exists), which is kinda overkill IMHO, and I don't really see this as an actual issue anyway, I'll be closing this.
