### ISSUE TITLE
Touch screen events

### ISSUE THREAD

**Issue by XFactHD** [MightyPirates/OpenComputers#1378]
I have two questions on touch screen events:
1: Is it possible to make two parallel loops to not slow down the updating of the screen by pulling an event?
2: I have a program with some rather small buttons. At first I tried to use fixed coordinates in an if statement and then I used a range for the coordinates in the if statement but it still doesn't work for me. Here is the relevant code: http://pastebin.com/KJmUsgD7

**Comment by dgelessus** [comment]
Questions about code and how to do something are best asked on the OpenComputers forums at http://oc.cil.li/, the GitHub issue tracker is meant for bugs and suggestions.

**Comment by XFactHD** [comment]
Ok, then I'll ask there.
