### ISSUE TITLE
Tier 3 Case built-in floppy drive, recepie change sugggestion:

### ISSUE THREAD

**Issue by Aleszp** [MightyPirates/OpenComputers#1380]
Current T3 case is:
[[diamond, "oc:circuitChip3", diamond]
[fenceIron, chest, fenceIron]
[diamond, "oc:materialCircuitBoardPrinted", diamond]]  easy
or:
[[diamond, "oc:circuitChip3", diamond]
["oc:circuitChip3", "oc:case2", "oc:circuitChip3"]
[diamond, "oc:materialCircuitBoardPrinted", diamond]] hard

As it comes with built-in FDD shouldn't recipe include it?
We could replace one ironFence (easy) and one "oc:circuitChip3" (hard) with disk-drive so it would make more sense.

I personally set: 
[[diamond, "oc:circuitChip3", diamond]
[fenceIron, chest, "oc:diskDrive"]
[diamond, "oc:materialCircuitBoardPrinted", diamond]]
as I'm using easy recipes.

Won't you agree that recipe included FDD instead of magically spawning makes sense?

**Comment by payonel** [comment]
this has been done :)
