### ISSUE TITLE
Switches don't seem to relay ComputerCraft messages from or to them

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#1381]
I tryed to relay a network message from an computer from OpenComputer to a computer from ComputerCraft with a switch, but the message doesn't pass. The other way neither, the message doesn't pass from ComputerCraft to OpenComputers. But two computers from OpenComputers connected to the same switch are able to comunicate togheter. ComputerCraft modems are well red (open and connected). Ports are also well open.

**Comment by gjgfuj** [comment]
I think CC computers have to be right next to a switch to relay but I can't
recall. Is the switch next to the CC computer?

**Comment by ExDomino** [comment]
No, the switch is a bit far of the CC computer and relayed by two modems and wire cables.

**Comment by h3po** [comment]
you should be able to wrap an oc switch instead of a computercraft modem, then your network is compatible

**Comment by fnuecke** [comment]
Worked and works fine for me, as long as the switch (now relay) is next to the CC computer, so try that and just use OC's wires instead.

**Comment by ExDomino** [comment]
ComputerCraft is really... Seriously, I will NOT install it on my future server!
