### ISSUE TITLE
Cyber Glove

### ISSUE THREAD

**Issue by TheRealOrangus** [MightyPirates/OpenComputers#1382]
The Cyber Glove would be a wireless component, activated when it's picked in the hand.
It triggers messages with the user's eye direction when the user presses or releases LMB or RMB, that way the user could select some points and areas, it could be a way to interact with holograms as touches to tier 2 and 3 screens, but not just holograms, also a way to interact with robots and drones, and much more!

**Comment by gjgfuj** [comment]
I.... Like it, but dunno how feasible it is to implement. Pretty sure the
answer is "Not Very."

**Comment by Vexatos** [comment]
Well, you could already do that with a Tablet and the Computronics Camera Upgrade, I'd think.

**Comment by TheRealOrangus** [comment]
How could this be implemented with Computornics Camera Upgrade?
The glove would trigger direction and relative position when it's used, nothing about raycasting.

**Comment by dgelessus** [comment]
But how would you translate the player's view angles to xyz coordinates in the hologram? There's no way to tell where the player stands, especially not with the necessary precision for this purpose. For less exact point selection you can already use tablets.

**Comment by gjgfuj** [comment]
You can actually.... The position is good enough for most purposes. It's a
float. The exact view is a bit harder, but could probably be sent from
client to server.

**Comment by dgelessus** [comment]
What I mean is that there is no way for an in-game computer to know the player's position with the necessary position. (Or do navigation upgrades output float coordinates?)

**Comment by gjgfuj** [comment]
Oh yeah... I was referring to if the cyber glove existed, it could output
float coordinates. Navigation upgrades wouldn't output position that well,
but the camera upgrade could tell rotation I think?

**Comment by Techokami** [comment]
Computronics adds a Radar block that, with the right setting in the mod configuration, will get in-world positions of mobs and players.

Sent from my Windows Phone

**Comment by TheRealOrangus** [comment]
> But how would you translate the player's view angles to xyz coordinates in the hologram? There's no way to tell where the player stands, especially not with the necessary precision for this purpose. For less exact point selection you can already use tablets.

It could be a floating point xyz of the entity.

> (Or do navigation upgrades output float coordinates?)

Yeah, that would be nice.

> but the camera upgrade could tell rotation I think?

I guess it wouldn't be rotation, rather a vector I suppose.
Nothing about cameras.

**Comment by fnuecke** [comment]
Interaction with holograms would get somewhat... messy, in particular now that they can rotate. Anything else, maybe ask the OpenGlasses people if they want to add that in, kinda feels like it'd fit.
