### ISSUE TITLE
SSD, SSHD and DDHS as alternatives to HDD

### ISSUE THREAD

**Issue by TheRealOrangus** [MightyPirates/OpenComputers#1383]
The idea is to add SSD(Solid-state drive) as alternative to HDD.
They would store more memory(2 times more?) and would have higher speed of read and write.
And certainly 4-8 times higher cost.
And make SSHD(Solid-state hybrid drive) and DDHS(Dual-drive hybrid system) and similar to be assemblable out of SSDs and HDDs..
And allow to place them to raids too.
An SSHD made of 1 tier 3 HDD and 1 tier 1 SSD would use the internal SSD to achieve higher speed on "Jumping paging" and less "Ping".

**Comment by Vexatos** [comment]
Uhm... Why would an SSD have more space than a HDD? That doesn't really make sense compared to drives nowadays. I don't see a need for any of these things.

**Comment by Aleszp** [comment]
Man, OpenComputers components look like from late 80s... SSD/SSHD are rather a little bit modern. (I'd like to see real computer with 256k RAM and SSD XD).
And also: Why SSD should be bigger? O_o

**Comment by skyem123** [comment]
If I recall correctly, the (stupid expensive) largest SSDs are larger than the largest HDDs.
But still... OC doesn't really need SSDs.

**Comment by fnuecke** [comment]
I'm pretty strongly opposed to adding larger storage than the T3 HDDs to OC, in particular none that are _faster_ than what exists already. For one because, well, there are tapes, and for two, I haven't heard of a single sensible usecase where you'd actually _need_ more space (or speed) than you can get with HDDs/a RAID. So, unless you can give me one that isn't "because it'd be cool", I'll be closing this :P

**Comment by Kubuxu** [comment]
Top tier tape is 192MB so if you need that size of storage there is FAT12 filesystem in MPT's (it is down momentary) Plan9k. It is possible just to mount file or block device as folder.

Only thing lacking is format program.
EDIT: Not 192 but 32. Thanks magik.

**Comment by magik6k** [comment]
Largest tape is 32Mb, mpt is up, and the FAT driver is by gamax :p. I'm going to have more free time soon so plan9k may get proper fstab, working unmanaged disk driver, network block devices and software raid.(+chroot/cgroups, but this needs time too)

**Comment by Vexatos** [comment]
FAT on tapes? Yes please. :cookie:
