### ISSUE TITLE
Redstone signal does not say which channel changed

### ISSUE THREAD

**Issue by LizzyTrickster** [MightyPirates/OpenComputers#1385]
The redstone changed signal should have an extra parameter to indicate which channel changed when using supporting cards (tier 2 RS card). While iterating through the channels with getBundledInput is fine for slow changing signals, it will not work for situations where there are potentially mutiple signals changing at once

**Comment by mpmxyz** [comment]
You can leave out the color parameter when using getBundledInput/setBundledOutput. Then you can receive/pass tables with the states of all colors at once.
see: #958

**Comment by xarses** [comment]
+1 As I noted in #1818 its actually quite easy to end up not being able to determine which channel changed.

**Comment by MalkContent** [comment]
I want to tag on that it would be neat to have a signal "comparator input changed"

**Comment by Talon24** [comment]
For others who stumble over this, there is a [Code Snippet](https://gist.github.com/Talon24/71221bc026ea72d8245a830bc6785317) you can use as a workaround until this feature will be implemented.

**Comment by payonel** [comment]
I wonder if https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/common/tileentity/traits/BundledRedstoneAware.scala#L63 is the place to make this change
