### ISSUE TITLE
Command - add Minetweaker recipes

### ISSUE THREAD

**Issue by Alaisx** [MightyPirates/OpenComputers#1387]
It would be pretty great if OC could add scripts/recipes to Minetweaker via a command. I believe this might be possible, having read this: http://minetweaker3.powerofbytes.com/wiki/Mod_Script_Execution

Examples of uses:
- Unlock recipes progressively as the player reaches milestones
- Allow a sort of tech-tree, where the player must choose which branches to unlock first
- Modify recipes based on choices (e.g. easier recipes if a certain "perk" is chosen)
- Disable recipes if certain criteria are met (not sure if the inter-mod capabilities of Minetweaker allow for removal of scripts, if not you could perhaps overwrite an existing script as a form of deletion)

These ideas may seem a little fanciful given the limitations of Minecraft, but I really think some of them might work if this command were available.

**Comment by gjgfuj** [comment]
I'm sure that has nothing to do with OC at all, and is really something you
should request of minetweaker and activate with the debug card.

**Comment by Alaisx** [comment]
Yeah, on second reading this request does seem kind of out of place on the OC github. I had read that minetweaker allowed external mods to add recipes via a forge intermod message, and I just thought it would be cool if OC was able to hook into that. 

The reason it might not be especially attractive for minetweaker to add an in-game command is that ordinary players wouldn't really have a use for it. They can simply paste their scripts in the appropriate folder. A command would only really be used for automation by mods like OC, and it could be argued that using commands intended for players, rather than the already-implemented  inter-mod method, is a somewhat indirect way to go about it.

Just my thoughts on this. Comments are welcome!

**Comment by fnuecke** [comment]
Feels a bit too out-of-scope in OC. If there were a command you could use the debug card, but since it's explicitly IMC I don't think this is the place to "bridge" that.

**Comment by gjgfuj** [comment]
There's a command that lets you enable/disable scripts iirc? So maybe.
