### ISSUE TITLE
[Request] The ability to prevent MineTweaker from removing loot disks from the loot table

### ISSUE THREAD

**Issue by Techokami** [MightyPirates/OpenComputers#1389]
I need the option to preserve loot disks in the loot table if Minetweaker erases the loot table to be rebuilt for modpack balance purposes. This is the reason why I have to creative most of my loot disks on my server, and why I created [this issue](https://github.com/stanhebben/MineTweaker3/issues/190) with Minetweaker, since I can't reconstruct the method @fnuecke used to have a dynamic list of loot items while only taking up one entry in the table. However, I got nowhere with my issue there.

**Comment by fnuecke** [comment]
I have no idea how Minetweaker interacts with loot generation, and honestly don't feel like digging into that, sorry :/ If someone wants to PR in an integration module that handles this, be my guest.

**Comment by payonel** [comment]
if minetweaker is removing recipes, doesn't seem like it is smart to hack in an item that someone is trying to remove. and if you need more control over which recipes are removed, sounds like an issue with their mod, not ours.
