### ISSUE TITLE
unpack() is missing/nil

### ISSUE THREAD

**Issue by KFAFSP** [MightyPirates/OpenComputers#139]
The standard lua method unpack() is missing. It can't be called, but is not listed in the wiki under NonStandardLuaLibs. So even if this is inteded and unpack should not be available, I suggest at least listing it there. Because this requires me to implement a fallback solution myself ( :D )

``` Lua
function unpack(ATable, AStart, AEnd, APosition)
    if ATable == nil then return end
    if AStart == nil then AStart = 1 end
    if AEnd == nil then AEnd = #ATable end
    if APosition == nil then APosition = AStart end

    if (APosition > AEnd) or (AStart > AEnd) then return end

    return ATable[APosition], unpack(ATable, AStart, AEnd, APosition + 1)
end
```

But this is of course very slow and recursive, therefore unsafe in certain cases.

**Comment by rmellema** [comment]
Try `table.unpack`
Lua 5.2 moved unpack into the table module

**Comment by KFAFSP** [comment]
I am sorry. I should really pay more attention to the changes in Lua 5.2.
Thank you very much. Just porting my ComputerCraft programs and encountered this problem.
