### ISSUE TITLE
Method to switch cpu architecture

### ISSUE THREAD

**Issue by magik6k** [MightyPirates/OpenComputers#1390]
It would be nice, since Lua 5.2 is the default architecture and 5.3 brings integer operations and string.pack, etc. etc. 

```
computer.switchArchitecture(arch: String): Boolean
```

It would reboot the machine if architecture was switched, return true if computer is already running specified architecture and false if unknown architecture is specified.
Having some write-only area in EEPROM to specify architecture would be nice too, as non-lua code could be booted too(inb4 API method should still be a thing as systems can boot using the Lua BIOS).

**Comment by fnuecke** [comment]
Probably also

```
computer.getArchitectures(): table -- of strings
```

To know what you can switch to. Don't really think the setter has to return anything at all - if it worked, the program won't continue executing after all :P

**Comment by MyNameIsKodos** [comment]
I'm not sure how to explain this suggestion other than to post relevant code pertaining to what I'm trying to suggest.

Similar to how `io.open` works in the example seen here:

``` lua
local file, err = io.open("myFile","w")
  if not file then
   return nil, err
  end
```

We should get something like:

``` lua
swaparch, err = computer.switchArchitecture("Lua 5.3")
if not swaparch then
return nil, err
end
```

I have no idea if/how this would actually work, but it's the only way I could explain it =D

**Comment by Vexatos** [comment]
Honestly, it doesn't make much sense for the (BI)OS to be able to change the computer architecture, but I can see it'd be a useful thing to have...
Changing the architecture forces a shutdown of the computer, so you need some way of telling whether it should reboot or not.

**Comment by magik6k** [comment]
It just doesn't reboot if it has already switched
