### ISSUE TITLE
Inventory-Controller, Add "sneaky" access

### ISSUE THREAD

**Issue by Nonsanity** [MightyPirates/OpenComputers#1391]
Some slots can only be accessed from certain sides of a block. As moving a robot all around a block to access those slots isn't always possible (and slows interaction down significantly), adding a "sneaky" mode to inventory access would improve robot inventory access. This tricks the block into thinking access is coming from the indicated side as opposed to the side the robot is actually on. This could be implemented as a new function or an additional (optional) parameter to existing functions, whichever makes more sense design-wise.

suckFromSlotSneaky( robot-side:number, inv-side:number, inv-slot:number[, count:number] ):boolean[, string]

suckFromSlot( robot-side:number, inv-slot:number[, count:number[, inv-side:number]]):boolean[, string]

The first option is probably better since the second uses two optional parameters, but the second would work if adding more unique function names needs to be avoided. Sneaky versions of most of the functions would be needed.

**Comment by fnuecke** [comment]
Hrm, I suppose it'd be fair enough to add this to the inventory controller... I'll think about it.

**Comment by dgelessus** [comment]
Might be helpful to name this feature something other than "sneaky". I like the reference to that one old BuildCraft addon, but in the case of OC robots "sneaky" means "as if it were a sneaking player". Just a naming/terminology thing.

**Comment by fnuecke** [comment]
Well, there's no context in which "normal" sneaking would make sense in extract/insert, but yeah, it'll probably be an additional argument and in the documentation it'd be called something like 'interactionSide' or so.
