### ISSUE TITLE
Virtual keyboard support in OpenOS

### ISSUE THREAD

**Issue by TheRealOrangus** [MightyPirates/OpenComputers#1392]
I suggest to make so that OpenOS would support something like GUI-Touch keyboard, that will draw keyboard, and touches would allow to type text there there, for tier 2 and tier 3 screens of cource.

**Comment by magik6k** [comment]
IMO OpenOS is not about UI at all, so this wouldn't fit, neither is plan9k(except loading bar) nor most of other OSes I'm aware of. IIRC There is one UI-based OC system, but I'm not sure about that. Yet it can be done using gamax92 vcomponent, bit of hackery and few dozens of lines

**Comment by TheRealOrangus** [comment]
Well it could be good, specially for tablets...
_Yet another "increasing realism" idea_

**Comment by fnuecke** [comment]
Yeah, well, while I don't disagree that this would be useful for tablets, I also think it'd be kinda out of place for OpenOS, at least built-in, in particular because it'd need some kind of layouting of the screen. Would better fit a custom OS / be implemented as a downloadable program I think.
