### ISSUE TITLE
Add ability to draw directly to pixels using color cells

### ISSUE THREAD

**Issue by WebFreak001** [MightyPirates/OpenComputers#1395]
I've recently watched a video about how old-school graphics worked ([Link](https://www.youtube.com/watch?v=Tfh0ytz8S0k))

They used lots of interesting techniques that could be easily implemented in OpenComputers. For example right now everything already uses some kind of color cells because of the mono-spaced font, but an optional "draw" mode in the GPU where you had the ability to set each pixel of one cell to either foreground or background would be neat. Then these could be used just like regular characters, drawable by the id (char code).

This should be allocatable by the user as the RAM is very limited (as it were back then) and you don't necessarily need the space for more than 200 tiles. However the RAM should be counted as you would use bits there (8 colors per row per cell = 8 bit instead of 8 numbers \* lua number size = 72 byte). This would result in 64 bit (or 8 byte) per color cell which could be stored using just one unsigned long.

**Comment by skyem123** [comment]
Yeah, this sounds interesting and can also fit in here: https://github.com/MightyPirates/OpenComputers/issues/779

**Comment by fnuecke** [comment]
Yeah, the video card general thread is #779, I'd suggest reading through everything in there, then post in there, if you still think it hasn't been discussed in some form or another already :P
