### ISSUE TITLE
Robot cannot suck item from Extractor of  Rotary Craft

### ISSUE THREAD

**Issue by exzhawk** [MightyPirates/OpenComputers#1398]
Common pipe (e.g. BuildCraft) can only suck items from last slot of extractor. I want to use robot to get items in middle slot.
Extractor GUI
![2015-09-02_18-25-39](https://cloud.githubusercontent.com/assets/7038938/9628849/f4b9de80-51a0-11e5-9c62-8378a58b8691.png)
Trying to do this with Creatix. Robot do detect correct item count in slot 2 but can not suck items.
![2015-09-02_18-25-26](https://cloud.githubusercontent.com/assets/7038938/9628854/fddbee18-51a0-11e5-9df2-fb657d0e35a6.png)

![2015-09-02_18-25-52](https://cloud.githubusercontent.com/assets/7038938/9628886/2e4d2a08-51a1-11e5-98c2-08fe1e578b17.png)

Mod Version:
Forge 1492
Rotary Craft v8c
OpenComputer 1.5.16.735

**Comment by gjgfuj** [comment]
That is because RotaryCraft blocks access to other slots. OC cannot
override this.
