### ISSUE TITLE
Could not unpersist computer; Exception are fired.

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#14]
2013-12-20 10:50:07 [WARNING] [OpenComputers] Could not unpersist computer.
com.naef.jnlua.LuaRuntimeException: bad permanent value (no value)      at

One line log, with no full exception.
When chunk are unloaded with long time. that exception are fire, short time (less than 1 minute) unloading don't make this issue.

uname -a : Linux *******\* 3.8.0-33-generic #48-Ubuntu SMP Wed Oct 23 09:16:58 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
and that is server. not client (single-play)

I tryed get NBT infomation from tileentiry (Basic Casing), it was failed. so no extra infomation, sorry. but if you give debug tool, i will give infomation (look's like freeze tool? http://www.zdnet.com/blog/security/cryogenically-frozen-ram-bypasses-all-disk-encryption-methods/900 )

**Comment by fnuecke** [comment]
Thanks, I can reproduce the issue and will look into it!
