### ISSUE TITLE
Computer Turns off When Leaving the Chunk

### ISSUE THREAD

**Issue by jadenPete** [MightyPirates/OpenComputers#1405]
Whenever I leave the world, the persistence works, but if I leave the chunk, the computer turns off, and  the screen shows what is was showing. In case your wondering, i'm running Windows 7 Profesional, 64 bit.

**Comment by katur239** [comment]
Pretty sure that is intended behavior. You'll need a chunk loader upgrade to keep it loaded.

**Comment by LizzyTrickster** [comment]
The persistance should work even when leaving the chunk, it won't do anything whilst it's unloaded but should resume when the chunk is loaded again. Try using an analyzer on the computer to see if it gives a reason for it turning off

**Comment by jadenPete** [comment]
Nope, no error. It has enough energy, it's powered by my whole frickin factory xD. It even says so. I'm running the latest version (1.5.17.36, not a jenkins build). Try and see if it works 4 u.

**Comment by jadenPete** [comment]
I have a feeling it has to do with my factory. In my factory, and only in, my minimap won't update.
EDIT: Nope, i'm wrong, it happens everywhere. Whenever I place a computer, run it, go away from the chunk, it turns off when I come back.

**Comment by fnuecke** [comment]
Works fine for me. Check your logs for anything fishy. Try spawning a creative one (`/oc_spawnComputer`) somewhere, see if it happens for that, too.

**Comment by jadenPete** [comment]
This happens to the creative computer too. Give me some time to check my logs... Btw, is the oc jenkins server down? I can't connect to it.

**Comment by jadenPete** [comment]
Nope, nothing suspicous being reported by OpenComputers in the log. It's 25,047 KB, so I'm not gonna scroll or search through the whole thing to see if any of my 90 other mods are saying anything.

**Comment by fnuecke** [comment]
No clue then. Please give it a shot with OC only (i.e. no other mods present).

As for Jenkins, should be up again, looks like it froze. Thanks for letting me know.

**Comment by jadenPete** [comment]
Ok, I will try this, but I must use Optifine (I get 0 fps without it)

**Comment by jadenPete** [comment]
It works :(

**Comment by jadenPete** [comment]
If you can't find the solution to this problem, it's ok, i'll just add a lever and a redstone card to my computers, make an autorun.lua with require("component").redstone.setWakeThreshold(15), and flip  the lever every time i enter the chunk.

**Comment by makkarpov** [comment]
You can run binary search - remove half of mods and see whether will it work. If it will work - remove half of the half, if will not - remove other half of the mods.

**Comment by jadenPete** [comment]
I know what you mean. I guess I could do that, and I will if it really bugs me, but since OpenComputers is like my favorite mod for mc, i don't think i'll be leaving that chunk :)

**Comment by fnuecke** [comment]
Well, if you ever find out what mod caused it, let me know, might still be an issue on OC's side.
