### ISSUE TITLE
My Suggestions for OpenComputers

### ISSUE THREAD

**Issue by jadenPete** [MightyPirates/OpenComputers#1406]
These are my suggestions for OpenComputers:
#1: A sound card or some realistic form of audio. Ok, I know this has been requested before, but could u make like a speaker block, a sound card, or some api that can play real mp3's, ogg's, and wav's. And I know u can add sounds to mc, and play them with a command block, but that's a pain. I like the MIDI player, but let's be honest. It doesn't sound that great with just beep's and note blocks. I'm not saying u have to add tape recorders and all that, but please. Plus, there are not any addons for 1.8.
#2: Can I turn on computers with a redstone signal, or have a config option for this?

Thanks, I love the effort you have put into this mod, so keep up the good work!

**Comment by LizzyTrickster** [comment]
1. Computronics has the tape drive, as for playing sounds MassSound might be able to help you there (I am not sure if either are updated for 1.8)
2. There's the WoR or Wake on Redstone for this, check the wiki http://ocdoc.cil.li as it might have the information on it.

**Comment by makkarpov** [comment]
#2 - use `setWakeThreshold` method of `redstone` component, or use network card and `setWakeMessage` if you want to wake computer with another computer.

**Comment by jadenPete** [comment]
SetWakeThreshold Worked! Thank u. As for playing sounds, Computronics isn't updated, but MassSound is. I guess i'll just add my sounds to the sounds folder. Thank u!
