### ISSUE TITLE
Diagonal 3d Printing

### ISSUE THREAD

**Issue by jadenPete** [MightyPirates/OpenComputers#1408]
I know this completely goes against the mc rendering system, but how about a 3d printer function and an addition to the print3d program with the following syntax (I add spaces so it's easier to read):

shapes = {{0,0,0, 0,0,16, 16,0,16, 16,0,0, 0,16,0, 0,16,16, 16,16,16, 16,16,0 texture="diamond_block", mode="advanced"}}

Basically I specify four spots where it starts, and four where it ends. So in this model, I'm filling the whole shape by specifying a flat, laying down square on y level 0, and the same on y level 16. So it draws from square 1 to square 2. Sorry if it's super complicated or extremely hard to implement, but this would add so much more possibilities.

**Comment by fnuecke** [comment]
You mean something along the lines of arbitrary polygons? That's not something I want to add really; for one, it'd be kind of a pain to add, for two I like the concept of the printer just printing smaller blocks :P Maybe some day I'll be ready to add a T2 printer or something like that, but not for now, sorry.

**Comment by jadenPete** [comment]
Ok. Maybe Someday :)
