### ISSUE TITLE
Custom Loot Disks

### ISSUE THREAD

**Issue by jadenPete** [MightyPirates/OpenComputers#1409]
Ok, so I have some programs that I made that are extremely useful, and I want to use on multiple disks. So I think, hmmm, Ooo floppies! So I make one and I tried duplicating via NEI but it assigns the same id and totally screwes it up. So can we add custom loot disks via resource pack? The folder name would be the name of the disk. This would be really helpful, because u can grab it out of a creative inventory and it will assign a random id. It would be assets/opencomputers/loot/SomeRandomName/AndHereIsYourProgram.lua
Anything in that folder is on the disk.

**Comment by magik6k** [comment]
It's already doable but not clearly documented. you basically make a `loot` directory in opencomputers in your world directory, with loot.properties in format of integrated loot, which is there: https://github.com/MightyPirates/OpenComputers/tree/master-MC1.7.10/src/main/resources/assets/opencomputers/loot

**Comment by makkarpov** [comment]
If both resourcepacks X and Y overwrite `loot.properties` will it discover both versions and merge or discover only version of higher-priority resourcepack? Has Minecraft resource manager some method to enumerate conflicting files?

**Comment by Aleszp** [comment]
Maybe adding custom loot disks the way customs recepies are added would avoid problem that @makkarpov mentioned.

**Comment by makkarpov** [comment]
Custom recipes are added into user recipe file that by default includes default recipes. This system wasn't designed to handle concurrent file changes because resourcepacks do not (and cannot) add recipes. Java ClassLoader can enumerate all the resources known with given name, for example, Akka uses this ability to provide default `reference.conf` for each module. But I do not know whether MC ResourceManager can enumerate conflicting files or not.

**Comment by Techokami** [comment]
You can also compile a custom build of OpenComputers with your loot disks available. That's what I normally do.

Optionally and additionally, have you considered setting up a repository to use with [OpenPrograms](http://openprograms.github.io/)? That way, other people can enjoy the programs you wrote via the OpenPrograms Package Manager (oppm) with an Internet Card present in their computer. :smile:

**Comment by jadenPete** [comment]
Oh ok, thanks. And yes, I will upload some of my programs to github (OpenPrograms), when I have the time.

**Comment by fnuecke** [comment]
Someone might want to add that info to the wiki for future reference ;-)

@Techokami FYI, it might be more maintainable to write a tiny addon mod that [adds the loot disks via the API](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/java/li/cil/oc/api/Items.java#L69), so you can just use the official OC builds. If that's all you change.
