### ISSUE TITLE
Mirror all API dependencies

### ISSUE THREAD

**Issue by makkarpov** [MightyPirates/OpenComputers#1412]
Because when another sh**ty maven like `dl.tsr.me` dies one more time (it seems to be hosted on ATTiny13 and connected via dialup modem, so it dies on a regular basis) the whole build goes down.

```
16:19:16.476 [DEBUG] [org.apache.http.headers] >> GET /artifactory/libs-release-local//forgeSrc/1.7.10-10.13.4.1448-1.7.10/forgeSrc-1.7.10-10.13.4.1448-1.7.10.pom HTTP/1.1
16:19:16.477 [DEBUG] [org.apache.http.headers] >> Accept-Encoding: gzip,deflate
16:19:16.477 [DEBUG] [org.apache.http.headers] >> Host: dl.tsr.me
16:19:16.477 [DEBUG] [org.apache.http.headers] >> Connection: Keep-Alive
16:19:16.477 [DEBUG] [org.apache.http.headers] >> User-Agent: Gradle/2.3 (Linux;3.16.0-33-generic;amd64) (Oracle Corporation;1.8.0_45;25.45-b02)
> Building 0% > :compileApiJava > Resolving dependencies ':apiCompile'
```

(this log was taken at 16:22)

**Comment by fnuecke** [comment]
Uhhh... if you pack them up for me in a ZIP file so I can just dump them in the maven directory, sure, why not I guess.

**Comment by makkarpov** [comment]
I could write a script that will collect them from original sources and place into single maven. Unfortunately I cannot create ZIP because a) `dl.tsr.me` is still down and I have no cache for it b) it would require manual update, which is a little bit annoying, I think.

**Comment by fnuecke** [comment]
So what do you suggest (in particular for point b)?

**Comment by makkarpov** [comment]
I suggest some script (written in Scala or even in PHP) that will scan mavens at some time intervals and cache results. I will try to write it.

**Comment by makkarpov** [comment]
Looks like the most easy way to dump dependencies is from gradle itself. So I written a `build.gradle` snippet that produces results like that: http://pastebin.com/raw.php?i=WMHwGCc3. It's better than nothing, but there are still duplicate transitive files.

**Comment by makkarpov** [comment]
Finally figured it out - current snippet dumps dependencies in a `group:id:version:ext` format and writes path to JAR file. Correctly handles transitive dependencies. Unfortunately I do not know which format is better to copy to the maven, so here it is - the snippet:

```
def dependencyTraverse(dep, level) {
    if (dep.moduleArtifacts.size() != 1)
      throw new IllegalArgumentException("Illegal artifact count ${dep.moduleArtifacts.size()}: ${dep.moduleGroup}:${dep.moduleName}:${dep.moduleVersion}")

    def indent = (" " * (level * 4 + 2))
    def artifact = dep.moduleArtifacts.first()

    println "${indent}- dep id: ${dep.moduleGroup}:${dep.moduleName}:${dep.moduleVersion}:${artifact.classifier ?: ""}"
    println "${indent}- stored: ${artifact.file.canonicalPath}"

    dep.children.each { dependencyTraverse(it, level + 1) }
}

task copyDependencies << {
    def conf = configurations.provided.resolvedConfiguration

    println "Dependency tree: "
    conf.firstLevelModuleDependencies.each { fld -> dependencyTraverse(fld, 0) }
}
```

Sample output: http://pastebin.com/raw.php?i=WMAv4abm (it still has duplicates related to `getChildren`, but these should be easy to remove, I think)

**Comment by skyem123** [comment]
ehee... I know someone who has a maven mirror that his friends use for their mods.
_pokes @RX14_

**Comment by RX14** [comment]
I have a jenkins and artifactory hosted on my dedicated server, I would be happy to donate them.  
[artifactory](http://mvn.rx14.co.uk/)  
[artifactory repo](http://mvn.rx14.co.uk/repo/)  
[jenkins](http://ci.rx14.co.uk/)

The artifactory repo listing seems slow when browsing, because it has to HTTP GET every repository it aggregates from every cache miss, but when it has it in the [local repository](http://mvn.rx14.co.uk/local/), it's really speedy. Also I think I have great uptime, and I get notifications on my phone when it goes down so I usually fix things really fast.

**Comment by makkarpov** [comment]
Hmm, looks good, but under what conditions it caches code? For example, [this file](http://mvn.rx14.co.uk/repo/com/google/inject/extensions/guice-multibindings/4.0-SNAPSHOT/guice-multibindings-4.0-SNAPSHOT.jar) sometimes gives me a JSON error and sometimes a correct JAR

**Comment by RX14** [comment]
I have no idea why that file is so tempremental, it's cached from http://maven.magik6k.net/ which is currently down, might have something to do with it. It still should return from the cache however... odd.

**Comment by RX14** [comment]
The issue with using my maven is that it cannot cache ivy patterns, what I usually do is create jobs for all the dependencies which do not have a maven on my jenkins server. Obviously this does not work with closed-source mods... What I can do is give you a maven repository on my server where you can upload anything you want, so rehosting some of your dependencies might be possible if the licence allows it.

**Comment by fnuecke** [comment]
Hosting isn't really an issue, since I have a maven running for OC already anyway. I just need to know how I can populate it (and ideally keep it up to date) :P

**Comment by makkarpov** [comment]
I think that when you have all four dependency ID parts (`group:id:version:ext`) and file location, it should be pretty easy to populate mirrored maven with deps. I never worked with Maven on an upload side, so I cannot do anything here, but I can modify gradle script so it will create ZIP with all jars with `group/id/version/id-version-ext.jar` directory structure.

**Comment by fnuecke** [comment]
Hmm, since having the JARs in the right place should be good enough I suppose that'd do.

**Comment by makkarpov** [comment]
But there are POMs. Or Maven will generate it automagically?

**Comment by makkarpov** [comment]
So, here is the first draft: https://github.com/makkarpov/OC-Dep-Mirror. It does not create POMs, however.

**Comment by RX14** [comment]
Pom files are not strictly necessary, they are useful for resolving transitive dependencies, but not otherwise.

**Comment by fnuecke** [comment]
Finally remembered to actually do this >_> Thanks again for the script. Ran it and dumped the stuff on my maven as a fallback! Let's hope that avoids such issues in the future.
