### ISSUE TITLE
Fix all your getStackInSlotOnClosing

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#1414]
These: https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/common/inventory/Inventory.scala#L70

See also ModCoderPack/MCPBot-Issues#32

**Comment by LizzyTrickster** [comment]
Instead of making demands why don't you explain whatever the problem is and why it should be "fixed"?

**Comment by SoniEx2** [comment]
It should remove stacks from slots. If you look at all the implementations they're mostly copypasted, except for the player inventory. That one handles both normal inventory and armor inventory, which takes a bit more effort than copypasting. Thus, it is safe to assume that method is meant for removing stacks from slots.

Sure, it's only ever called by vanilla when removing stacks on container close, but that doesn't make it any less of a removeStackFromSlot.

**Comment by fnuecke** [comment]
From my understanding this is for stuff like the crafting table, i.e. 'temporary' inventories. AKA nothing in OC. If you can point me to a single use-case (in vanilla) that says otherwise, please do.

**Comment by SoniEx2** [comment]
It's only /used/ that way, but it's ALWAYS implemented in the exact same way: If the slot is empty return null, otherwise return whatever is in there, while setting it to null.

Also, it wouldn't do any harm to implement it that way.

The fact that both player inventories and beacons have specialized implementations (instead of copypaste and/or being left unimplemented) and the fact that all implementations remove stack from slot makes me believe it's supposed to be named removeStackFromSlot instead of getStackInSlotOnClosing.

**Comment by fnuecke** [comment]
Hmm, interesting, that indeed sounds likely. It'd also explain why it never caused any issues in over two years; nobody's actually calling that because of the weird name :P Since it at least isn't called from anywhere within OC, I suppose I might as well change it.

**Comment by fnuecke** [comment]
af49402d670a2f0df23a2d0d7727c138d9007452
