### ISSUE TITLE
End Stone block added by your mod, but already present in Vanilla Minecraft

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#1415]
Your mod add its own End Stone, but End Stone is already added by Vanilla Minecraft and already craftable with few other mods, for example ThermalExpansion, Mariculture, TinkerConstruct, etc. You should remove that bloc and make that your recipe allow to create the Vanilla End Stone instead.

**Comment by fnuecke** [comment]
No. It was explicitly added not to mess with balance of other mods using endstone. If other mods decide to add recipes for vanilla endstone, that's their decision. Also, I really don't see how this is a problem, since you can use either in OC's recipes.
