### ISSUE TITLE
Error indicator LED

### ISSUE THREAD

**Issue by magik6k** [MightyPirates/OpenComputers#1416]
It would be nice to have those red LEDs on computers/servers to indicate system error, as It may be sometimes annoying to look for erroring part of GPU-less server maze. It would share space with power LED, just like many OEM/laptop cases do it.

As it seems fairly simple to implement, I may try to do it in some of my free time and PR.

**Comment by jadenPete** [comment]
That's what an analyzer's for, but I guess that would be kinda useful.

**Comment by fnuecke** [comment]
Hmm, would need syncing the error state to the client and adding an overlay image, nothing too hard aye. If you'd like to PR it, all the better :-)

**Comment by MyNameIsKodos** [comment]
What about the ability to set the light to one of the 16 colors from the color API?

**Comment by makkarpov** [comment]
Color API is just mapping between wool colors and numbers. If there will be ability to use arbitrary color, then it will be RGB, I think.

**Comment by MyNameIsKodos** [comment]
I just used color api as an example, that's what I meant though is being able to swap between the 16 basic colors

**Comment by Vexatos** [comment]
That should actually be a different light. There is usually one for the computer state and one to use as an indicator.

**Comment by fnuecke** [comment]
Yeah, this here would purely be for error indication in the same space as the power indicator. Anything else _might_ share the space with the HDD indicator, but I'm not sure I'd actually want that...

**Comment by MFernflower** [comment]
What about a front mounted RGB led? (think of something like a WS2812)

**Comment by makkarpov** [comment]
There is a new modular rack system, scheduled to v1.6. The RGB leds may appear as rack addition.
