### ISSUE TITLE
[Suggestion] Make the transposer usable as Microcontroller Upgrade.

### ISSUE THREAD

**Issue by sylphio** [MightyPirates/OpenComputers#1425]
Hi, 

The new transposer is really useful and i think it would be great to allow it to be used as a upgrade for microcontoller so we can MCU as sorting marchine, buffer, precise stack splitter, etc..

The transposer is a controller upgrade ++ so it would make sense if the block also behave as a upgrade (similar to geolyser). 

I am unsure if this potential upgrade can be meaningful for robot but for MCU it may really increase their usefulness without necessary giving them access to external component.

Another transposer suggestion, when we use the transferItem method with a explicit source slot, the function also require a destination slot. For a lot of purpose, we really care with the item we move but we don't want to scan the entire destination chest to find a available destination slot. In such case, supporting call with only "transferItem(sideIn, sideOut, count, source)" would be great.

Thank for the mod

**Comment by MyNameIsKodos** [comment]
+1 for transposers as MCU upgrades.

**Comment by sylphio** [comment]
Thank you :)

**Comment by fnuecke** [comment]
Thanks for the suggestion ;-) (and pointing out the transferItem derpiness)
