### ISSUE TITLE
External mod emulator

### ISSUE THREAD

**Issue by scj643** [MightyPirates/OpenComputers#1428]
A system to run the mod outside of Minecraft to make development easier.

**Comment by Techokami** [comment]
I think there is already an emulator available; check the forums.

Sent from my Windows Phone

**Comment by magik6k** [comment]
Just look for ocemu by @gamax92

**Comment by fnuecke** [comment]
Yeah, an emulator is what you're looking for. OC itself is too interwoven with MC to just "rip it out".
