### ISSUE TITLE
Robots render only first 2 layers of tools.

### ISSUE THREAD

**Issue by SilentChaos512** [MightyPirates/OpenComputers#1429]
For tools with multiple render passes, it seems only the first two layers are rendered on robots. Examples include Silent's Gems tools (only the rod and rod decoration are rendered), drills from Super Multi-Drills (chassis and battery gauge, but not head), and Tinker's Construct tools (completely invisible, at least for tools that aren't upgraded).

![2015-09-06_02 58 05](https://cloud.githubusercontent.com/assets/5721949/9891975/2e5fab0e-5bd0-11e5-8623-b08a79dc3401.png)

**Comment by fnuecke** [comment]
Then I'd gess TileEntities get fewer render passes than entity/normal item rendering. Hrm. Might be enough to manually "emulate" the passes in the last pass the TE gets.
