### ISSUE TITLE
[Suggestion]: Robots deploy drones

### ISSUE THREAD

**Issue by bbgott** [MightyPirates/OpenComputers#1430]
I absolutely love this mod!  I would like to propose a feature request.  Currently, robots can simulate a sneaking right click on other robots, which powers them on.  It would be neat for robots to power on drones as well.  Currently, I have been able to place drones with robots, but they are placed in their powered off state.  The idea I had in mind was a recon robot carrying a few drones.  The robot could fly to an opponent's base, deploy the drones to scan the base sending the data back to the robot.  It could then retrieve the drones and return home with the collected data. 

One idea I had for how to implement this would require changing the way drones work a little bit.  Instead of a sneak right click returning drones to an item form, a sneak right click with a wrench would do that.  An empty handed sneak right click would power on the drone in a similar manner to robots.  Then a robot could wrench sneak right click the drones to return them to item form to then suck them up.  Currently, when a robot tries to sneak right click a drone, it does nothing.

In my testing for this feature I did trip a Null Pointer exception when attempting to have a robot sneak right click another robot with an analyzer equiped.

I did my testing with:
MC 1.7.10
Forge 10.13.4.1448
OC 1.5.17.33

**Comment by fnuecke** [comment]
Done, and thanks for the pointer to the nullpointer ;-)
