### ISSUE TITLE
Error with the Class Transformer

### ISSUE THREAD

**Issue by fwolle30** [MightyPirates/OpenComputers#1433]
Hi, I've got a chet message telling me, that someting went wrong.

Here is the Error Log

http://paste.ee/p/KGOIP

**Comment by fnuecke** [comment]
Update OC.

**Comment by fwolle30** [comment]
Srry, I just wanted to close the Ticekt, because as you mentioned it, i saw that I've accidentaly downgraded OC. But thanks for the reply

**Comment by fnuecke** [comment]
No worries :)
