### ISSUE TITLE
Serious FileSystem bug when using unbuffered mode

### ISSUE THREAD

**Issue by KFAFSP** [MightyPirates/OpenComputers#144]
Whenever you switch filesystem.bufferChanges to false (because I want to modify files on the in-game computers with outside editors as already mentioned by #50) the complete io and filesystem api stops working. All accesses to files that are actually stored on your harddrive (excluding /tmp, /bin and /lib) cannot be opened anymore. To reproduce, just change the setting and try to save with the standard editor program. You will get this exception (passed also from io.open and fs.open):

Illegal mode "w" must be one of "r", "rw", "rws" or "rwd"

This seems to be quite a severe bug.

**Comment by fnuecke** [comment]
Confirmed, looking into it.

**Comment by KFAFSP** [comment]
That definitely did the trick. 

Just as post scriptum note: I really hate opening tickets, but I think this is a really awesome mod. And I just couldn't stand it being unusable to me (and other people aswell, don't get me wrong). I would contribute to it myself, but it seems to be next to impossible to setup an fml-environment 1.6.4 (where they use the ssl-incapable-downloader) on Windows. I miss the old days of ModLoader...

**Comment by fnuecke** [comment]
Thanks a lot for reporting this, it's pretty much impossible for me not to forget some cases to test, so reports like this are necessary (and very much appreciated!), so if you find any oddities, don't hesitate to.
