### ISSUE TITLE
New Robot Names

### ISSUE THREAD

**Issue by jadenPete** [MightyPirates/OpenComputers#1440]
How bout Johnny Five from Short Circuit 2, or Wall-E?

**Comment by Techokami** [comment]
Make a PR with the changes?

**Comment by jadenPete** [comment]
Sorry, but how do u make a pull request?

**Comment by LizzyTrickster** [comment]
Both are already in there:
https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/robot.names Lines 62 & 96

**Comment by jadenPete** [comment]
Really? Wow, u guys have good taste in movies :D
