### ISSUE TITLE
[Idea] Very expansive way to link a third (and more) linked card

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#1442]
My idea is a way to link a third (and more) linked card with using one of these obtained by the original receipe with a nether star and some other components, like a card base of course, to obtains a third linked card linked to the two others. ^^

**Comment by MyNameIsKodos** [comment]
Personally I think current behavior works fine. If anything, use a server with multiple linked cards as a master/control server that receives data from all other linked devices, and then deals with whatever messages it receives as necessary.

**Comment by ExDomino** [comment]
How to make a computer relay a message that is not addressed to it if OpenComputers make that all modem messages that the receiver address is not the computer id are ignored?

**Comment by MyNameIsKodos** [comment]
I'm confused... What do you mean?

**Comment by ExDomino** [comment]
When a computer receive a modem message, it cannot handle it if the receiver address is not the same as the computer id. OpenComputers make that there is impossible for a third computer to spy network transmissions between two other computers, so if a computer B would act as a switch between a computer A and a computer C, and computer A send a modem message with computer C as receiver, computer B will not be able to handle the message in order to transmit it to the computer C, that will never receive the message. In this example, computer A and C are far from each other and linked to computer B with two pairs of linked cards. How do you expect that computer B can do its job?

**Comment by Kubuxu** [comment]
Use proper networking like that one from network disc. OC's networking is Data Link layer which connects two nodes together, you can route packets with use of higher level networking code like `network` loot disc.

It works by discovering path from A to C by B and relaying messages in host B.

**Comment by fnuecke** [comment]
Linked cards are meant to be point-to-point. I think even the name suggests that. Either use a proper networking protocol as suggested above, or have a look at Computronics' spoofing card.
