### ISSUE TITLE
[Nanomachines] Tree felling

### ISSUE THREAD

**Issue by Dylanavo** [MightyPirates/OpenComputers#1444]
I just had a look at the nanomachines video and heard you were looking for ideas. I thought a good effect would be to allow a player to chop down a whole tree at once with the nanomachines active. Basically the same way as a Tinkers' Construct lumber axe cuts down trees if you are familiar with the mod (chop the bottom of the trunk and the whole thing comes down).

PS: I hope this is the correct place to post this. Apologies in advance if this isn't correct.

**Comment by MyNameIsKodos** [comment]
Soo some sort of lumberjack hidden effect?  Sounds interesting.

**Comment by fnuecke** [comment]
Hrm, interesting idea. Probably not instant like TC, if at all, spawning a "swarm" that'll slowly chew through the tree or so?

**Comment by Dylanavo** [comment]
Yeah, I think the swarm is a great idea, particularly if you could get a few swarms going on different trees.

**Comment by Vexatos** [comment]
@Daraketh That wouldn't make much sense since the things probably should have a fairly short range (maybe only trees right in front of you (<2 blocks)?)
Also, I have no idea what exactly those swarms would consist of... Nanomachines themselves would make no sense since they are made for neural interfacing, not flying towards trees... But then again the disintegration effect already exists, even though that one could be explained with increased body strength.

**Comment by Dylanavo** [comment]
@Vexatos Ah fair enough. I guess I was kind of thinking you could "touch" a tree, leaving some machines there to cut (chew) the tree down, then returning for them (and the wood) shortly after. If this doesn't make sense with the theme of the machines then please disregard. :)

My original idea was something along the lines of the nanomachines giving you greater strength to fell the tree in one mighty swing (well, breaking the bottom block as you usually would, but the whole tree comes down).

I haven't actually played with the nanomachines, so I don't really have a feel yet for what they are meant to be. My server runs a modpack that hasn't updated to the latest OC yet, much to my disappointment.

**Comment by Vexatos** [comment]
@Daraketh That indeed would work (explaining it again with greater pysical strength). Just saying that a "swarm" is not a good idea.
