### ISSUE TITLE
[CreativeMode] Change assembled things.

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1447]
Well, just thinking it would be nice if - when in Creative Mode (& Cheats enabled?) - you could take e.g. an already assembled robot and stick it into the assembler input slot, which then turns the item in the input slot back into a case and fills all slots with the things the robot has been assembled with, that way you can easily edit a robot in creative-mode without having to re-assemble a new one or disassemble the current etc.

**Comment by dgelessus** [comment]
You mean like when placing it into a disassembler that is next to an assembler? `;)`

(Though IIRC disassembers aren't instant and still have the item loss chance even if the user is in creative mode, so your point is still valid, kind of.)

**Comment by fnuecke** [comment]
That. Also, they're instant if you're in creative mode. Not sure about the loss chance, though, but I could remove that for instant disassemblies if it happens.

**Comment by Inari-Whitebear** [comment]
Ah, forgot about that interaction :P But yeah, no item loss would be good then.
