### ISSUE TITLE
[Request] Separate sneaky from robot.use

### ISSUE THREAD

**Issue by Aedda** [MightyPirates/OpenComputers#1448]
There are a number of mod tools and weapons which react to sneaking left click, an ability currently impossible for Robots. It would be very useful to separate the sneaky parameter into its own callback that toggles the Robot into and out of sneaky mode for either right or left click.

**Comment by fnuecke** [comment]
How's that different, behavior-wise, from the boolean parameter that already exists?

**Comment by Aedda** [comment]
robot.swing does not have that parameter, at least according to the wiki. This would make the sneaky mode separate from left and right clicking. It could be added to robot.swing also of course instead of becoming its own callback.

**Comment by fnuecke** [comment]
Someone should update the wiki then, because it does >_>

**Comment by Aedda** [comment]
_grin_ Well that is good to know :)

**Comment by fnuecke** [comment]
Done.
