### ISSUE TITLE
Robot inventory: Last line broken

### ISSUE THREAD

**Issue by Namarius** [MightyPirates/OpenComputers#1449]
Tested with OpenComputers-MC1.7.10-1.5.18.34-universal

robot.compareTo and robot.count does not work on the last line in the inventory. The last inventory line behave like it is always empty. I've tested this with both Lua versions and robots with one inventory controller and one inventory upgrade so that the last line consists of the slots 12 to 16.

**Comment by fnuecke** [comment]
Oops, thanks for the report. Will probably make a hotfix release tomorrow.
