### ISSUE TITLE
[Nanomachines] See into inventory ability

### ISSUE THREAD

**Issue by bbgott** [MightyPirates/OpenComputers#1452]
An idea for a special nanomachines ability would be to be able to see the inventory of a chest or other tileentity without having to open it. I know there's a mod out there that lets you do that, I don't like it for a survival game so much. But having it as a special ability you could get could make it fun. Kind of along the idea of the inventory controller upgrade for robots and drones. But unlike drones and robots, you would still have to open the inventory to interact with it. You would just be able to see the contents floating maybe. I honestly don't know how much work this would involve, so I will understand if it doesn't happen.

**Comment by payonel** [comment]
i feel this is a pretty big ask and something slightly out of the normal behavior of nanomachines that communicate via modem_messages - but we appreciate the suggestion
