### ISSUE TITLE
OC 1.7.10 - 1.5.17.33 - Commands available to nonOP users

### ISSUE THREAD

**Issue by AnodeCathode** [MightyPirates/OpenComputers#1453]
The oc_sc command is usable by non OP players.

**Comment by fnuecke** [comment]
Well then, this is embarrassing. Will fix immediately.

**Comment by AnodeCathode** [comment]
This is unacceptable! You must first argue that I'm mistaken; using the wrong version; doing it wrong. Then you must show me in code how I must be wrong. Then I have to submit a PR showing you the fix. Only then can you admit the issue might be real and quickly fix it. 

Thanks :)

**Comment by fnuecke** [comment]
Hahaha, that's another project ;-)

Thanks for reporting it!
