### ISSUE TITLE
Move component-filesystems to driver floppies

### ISSUE THREAD

**Issue by 1n5aN1aC** [MightyPirates/OpenComputers#1456]
So, there is a very real possibility that this is some sort of user error, but I really can't figure it out, and some folks on IRC said It'd alright to create an issue for it, so here goes:

I cannot for the life of me figure out why sometimes the autorun.lua file (located on a floppy) works in a robot, and sometimes, it does not.

In all cases, the autorun.lua file is situated in the root directory.

The reason I'm so confused is after editing the file on a diamond-tier computer, I save it, shutdown, take the floppy out, and it is indeterminate whether or not the screen-less robot I insert it into and turn on will run it after booting.  sometimes it does, sometimes not.

I hacked together a file to try and fix the autorun issues, perhaps the autorun was turned off with filesystem.setAutorunEnabled(false)  So here's the script:

```
local filesys = require("filesystem")
print (filesys.isAutorunEnabled())
filesys.setAutorunEnabled(true)
print (filesys.isAutorunEnabled())
```

the weird thing is that it prints "true"  "true"  leading me to believe that autorun is not disabled on the device, yet sometimes this appears to fix it.  (Though I have a sneaking suspicion that it really didn't do anything, and something else fixed it.)

Anyways, am I missing something fundamental, or is there something wrong with booting autorun off of floppies in robots?

**Comment by 1n5aN1aC** [comment]
UPDATE:

I had a robot which was running a program for the purposes of generating cobble, and it was working fine.  It's pick broke, I turned it off with the power button, and now when I come back to it, and turn it back on with a new pick in it, it doesn't work.

Literally no other changes than that.  I never even took the floppy out or anything, just turned it off, and turned back on with a new pick in it.

**Comment by fnuecke** [comment]
Hrm, maybe check if `/tmp/event.log` exists, and if so, what it says (contains errors from event handlers, such as the autorun handler). I'm guessing something errors in your script in certain conditions. If it's not top-secret, pastebin/gist/something your script.

**Comment by 1n5aN1aC** [comment]
The program I mentioned earlier, which randomly stopped working, (and seems to still not work the majority of the time) was just a simple 'mine-until-obsidian-then-drop' cobble-generator robot:

``` LUA
local robot = require("robot")
local os = require("os")

local function mineToObby()
  robot.select(1)
  while not robot.compare() do
    robot.swing()
    robot.forward()
  end
  robot.turnAround()
end

while true do
  mineToObby()
  mineToObby()

  robot.select(2)
  robot.dropDown()

  os.sleep(1)
end
```

I really don't have any idea what causes it to be so indeterminate.

**Comment by MyNameIsKodos** [comment]
``` lua
local robot = require("robot")
local os = require("os")

local function mineToObby()
  robot.select(1)
  while not Obby do
    robot.swing()
    robot.forward()
    if robot.compare() then Obby = true end
  end
  robot.turnAround()
end

while true do
  mineToObby()
  mineToObby()

  robot.select(2)
  robot.dropDown()

  os.sleep(1)
end
```

Try using that.  I'm not 100% it works, but I don't think your `while not robot.compare do` was working.

**Comment by 1n5aN1aC** [comment]
well, I think the code was slightly flawed, but it ran once, mining forward till it hit obby, then just constantly turning around.  Thinking about how to fix that.  But... that's not what I'm worried about.

I then broke the robot, moved it back to the starting area, made NO CHANGES AT ALL, put the floppy, pick, and obby back into slot one, clicked power on, and it boots up to absolutely nothing.  Same symptoms as before.

Additionally, the Analyzer doesn't seem to show anything of any use, leading me to believe that it's not a bug in my code causing it to crash, but rather that the program is never running to begin with.

**Comment by gjgfuj** [comment]
Well an analyzer wouldn't show anything from autorun programs, and neither
does the console log on a screen.

**Comment by MyNameIsKodos** [comment]
It might be turning around constantly because you're calling mineObby() twice in a row in your loop.

**Comment by 1n5aN1aC** [comment]
@MyNameIsKodos Yes, because I want it to go all the way to obby, then all the way back to another obby, then drop it's good below it before continuing onwards.  I highly doubt that the issue is with the program, as I've had this issue with all sorts of programs, as has @sulljason .  Furthermore, one program will work completely fine, then after a power-cycle, cease working, only to seemingly randomly begin working again later.

@fnuecke does /tmp/event.log actually get written to a floppy that is being booted off?  And if so, does it get cleared on reboot, or just when something else would write to it?   I ask, because the majority my code & this testing is on a robot with no screen or Keyboard, so I do the programming with the disk in a floppy drive attached to a computer instead.

**Comment by gjgfuj** [comment]
It's written to the temporary partition thats cleared on reboot.

**Comment by 1n5aN1aC** [comment]
Alright, so here's what I've found out:  

I put the floppy into a robot with screen as well as other luxuries. :)   I then power cycled the robot twice to get it to work.  The autorun program worked, it started running.  I turned it off with the power button, and boom!  It did not run, and booted up to the console.  I then typed:  `more /tmp/event.log`

Here's what I got:
![untitled](https://cloud.githubusercontent.com/assets/735325/10093329/c252d354-6305-11e5-891a-fa3e2eac7943.png)

Would you look at that.  module 'robot' is not being found.  But... only some of the time.  how in the world does that happen?!

**Comment by gjgfuj** [comment]
Ahhhh. Yes.

**Comment by gjgfuj** [comment]
Crap I sent that too early. Anyway, its because the robot api is loaded by
an autorun file. And the autorun files are loaded semi-randomly on boot.

**Comment by 1n5aN1aC** [comment]
> And the autorun files are loaded semi-randomly on boot.

:scream_cat: ....But how does that even make sense?

Shouldn't the autorun only run once the OS is completely loaded?  How does it even make sense to be running them before the rest of the OS is loaded?

I suppose I could add a delay to my script before doing anything....  No wait I might not be able to even do that, because I have to import OS before I can use os.sleep(), and for all I know os isn't fully loaded yet, since it's so indeterministic.

I suppose if that really is the case, I'd like to request that autorun be delayed until the os is fully loaded, unless there's a good reason for it to not be..

**Comment by gjgfuj** [comment]
The robot api isn't part of the OS. It's part of the robot, which the OS
loads using an autorun script. So sometimes that loads before your one and
sometimes it loads after. It is /only/ the robot API that is loaded with
autorun. The rest of it is loaded with openos so you'll have that. And
you'll definitely have access to the robot component.

**Comment by 1n5aN1aC** [comment]
Alright, thanks for that @gjgfuj.  I can definitely work around that.

But still.....  That's very non-intuitive behavior.  Is there any way that behavior could be changed to make sure it's loaded before executing the autorun script?

**Comment by gjgfuj** [comment]
Um, you could possibly load the other autorun script from yours.... But I'm
sure sangar could make it load the robot API before other autorun scripts.

**Comment by fnuecke** [comment]
I kinda can't without super-special-case-code (yuck) or adding a priority system to autorun scripts (complex). I'll probably do the latter, but I can't promise when. For now, my suggested approach would be to just put/install the whole stuff on a writable medium and copy `/lib/robot.lua` over once.

**Comment by dgelessus** [comment]
Another reason to get rid of the magic filesystems for robots and such. `;)`

**Comment by 1n5aN1aC** [comment]
@fnuecke I can confirm copying /lib/robot.lua to the same directory as the script works great, thanks for that.

So I can work around the issue now, though I still think it's rather un-intuitive, and have seen several other people making the same mistake.  So I would say the behavior should still be changed when you get the time to do so.

Anyways, thanks!

**Comment by skyem123** [comment]
Hm... I agree with @dgelessus. Get rid of the magic filesystems!

**Comment by fnuecke** [comment]
I've had a quick chat with @payonel yesterday, and he'll be looking into merging the autorun functionality into the rc system. So the magic file systems will remain (for now), but the order will be less... arbitrary. That's the plan, anyway!
(Since that'll be a breaking change that'll go into 1.6, whenever I'll find the time for that...)

**Comment by skyem123** [comment]
:<

**Comment by payonel** [comment]
@skyem123 why sad? This is great news! Super awesome rc coming! :) To be honest, upgrading rc is the best course of action for this. Anything else would be a hack-fix.

**Comment by skyem123** [comment]
Magic filesystems are bad.

**Comment by dgelessus** [comment]
Any chance that the code for magic filesystems could be changed so that they create new loot disks named "$componentname Drivers" instead? The functionality would be the same, except that they need to be inserted by hand and should probably be installed onto the boot drive. Perhaps those floppies could have an automatic crafting recipe (blank floppy + component -> driver disk for that component) as well? Or are components not linked to their items in any way?

**Comment by skyem123** [comment]
Why not have the drives built into OpenOS?

**Comment by dgelessus** [comment]
That could (and probably should) also be done for OC's own components, but if this were possible then addon components with magic filesystems would not become completely unusable.

**Comment by makkarpov** [comment]
Addons can distribute needed files via OPPM or via loot disks.

**Comment by skyem123** [comment]
Hm... @dgelessus's idea sounds good, then...

**Comment by fnuecke** [comment]
The driver disk thing might be an option, yeah. Just felt somewhat... annoying way back when. We'll see.

**Comment by mpmxyz** [comment]
I don't like having to use many floppies to setup a computer.
I once had a mobile internet USB stick with an included driver installer.
Maybe it should be more like that thing?
To make it easier to use you could include an install checker in an autorun.lua file:
`No drivers for component 'Internet' found - continue installing? (y/n)`

To avoid redundant installer files it would be good to add a small driver installing utility to OpenOS itself.
Is it possible to use oppm here?

**Comment by skyem123** [comment]
well... an included installer is kinda almost what the magic filesystems already are. I don't like them.

**Comment by mpmxyz** [comment]
But what is the advantage of driver floppies?
Their disadvantage is that you have to use a lot of them to setup a computer with several components generating a lot of work for you. (extreme case: robot with data card, internet card and generator upgrade)

**Comment by gjgfuj** [comment]
Well, remember that drivers are optional, and you can still use the
component without it. This way, it reduces clutter, and only is used if you
want it to.
