### ISSUE TITLE
idea: Computer controlled potion machine.

### ISSUE THREAD

**Issue by MFernflower** [MightyPirates/OpenComputers#1457]
After my failed attempts with the freshly added nanobots; I had an idea.. What if opencomputers had a computer controlled potion making machine that could make mixed effect potions and potions with some of the new nanobot potion effects - But with out the risk and long duration of "being one with the machine"/other nasty side effects When a potion wears off you would simply brew a new one (provided you have the right datastream from the PC and the power and ingredients ofc) - People could swap there "chemical structures" (data table needed to make the potion or whatever)  around servers and make custom potions for various things. Even maybe make a pharmacy or something similar for when the going gets tough. If you're interested I have a few ideas that may work. But I am not a good coder by any-means!

**Comment by gjgfuj** [comment]
So what... Nanobots but temporary? Why exactly? What's really different
between this and nanomachines?

**Comment by MyNameIsKodos** [comment]
Use a Transposer and a Potion Stand, problem solved =P

**Comment by scj643** [comment]
It's different in the fact that it cost resources to get the effects you want.

**Comment by Vexatos** [comment]
But... Nanomachines cost resources too, just different ones. Also, Kodos is right.

**Comment by fnuecke** [comment]
On a basic level, exactly what Kodos said. On a "pharmacy" level, try Minechem or so.
