### ISSUE TITLE
Mac players and screens

### ISSUE THREAD

**Issue by excelcrafter** [MightyPirates/OpenComputers#1458]
I have two friends, they play exactly same modpack as me.

I play on laptop, no problem.
They play on Mac, they cant see whats on OC screens, screens are blank for them.

**Comment by LizzyTrickster** [comment]
What modpack do you play with? saying "the same as me" doesn't help when we don't know what you play with

Java / OC versions?
Screenshots?

**Comment by dgelessus** [comment]
Would also be useful to know their versions of OS X and what graphics cards they have. I assume they've already checked for system updates through the Mac App Store (or Software Update on old OS X versions)?

**Comment by 31trainman** [comment]
I'm seeing this same issue I'm running mac os x version 10.10.5. My graphics card is a NVIDIA Geforce GT 330m. My java version is 8 update 60. I'm running open computers version 33 for 1.7.10 forge version 1492.
![2015-09-24_19 53 26](https://cloud.githubusercontent.com/assets/3371136/10091193/9f86674e-62fd-11e5-9ab3-da2396be50e9.png)

**Comment by fnuecke** [comment]
IIRC for other people that had that issue (also on Mac, always and only on Mac), it resolved itself, though I can't quite remember how; possibly by doing a forced texture reload (F3+t) or so. See if there's an update for your graphics card drivers maybe. That said, I know that even plain Forge had issues with textures on Mac time and again... maybe try disabling the new splash screen (there's some Forge config file somewhere), and if that doesn't help disable the stencil buffer (that was a command line flag I think, can't remember exactly how it went right now).

**Comment by XFactHD** [comment]
@fnuecke the command line flag you are looking for is -Dforge.forceNoStencil=true.

**Comment by fnuecke** [comment]
That's the one, thanks.

**Comment by excelcrafter** [comment]
Minecraft version: 1.7.10
Java: asap
Forge: 1492
Optifine: enabled, disabled, same result ( OptiFine_1.7.10_HD_U_C1 )
OC version: OpenComputers-MC1.7.10-1.5.17.33-universal
Modpack: http://technicpack.net/modpack/proton-colony

Platform: Mac
OS: 10.10.5
GPU: asap

Java version and GPU asap, these players are from USA, so bit difficult to catch them

**Comment by xobzoo** [comment]
I'm on a Mac (OS X 10.10.5, Java 8 1.8.0_60) with the same problem, except only lowercase letters were missing; uppercase, numbers, and symbols all showed fine.  Fortunately, our Minecraft sysadmin found this page which saved the day!

The **`F3+t` trick** is only thing I had to try.  Immediately (well, after the several-second delay as it reloaded things) everything worked fine.

Thanks, @fnuecke!  I'm not sure how long we would've fumbled around with different combinations if you hadn't mentioned that.

(For those who have never done it:  while in-game, hold `F3` and press `t`.
Minecraft will freeze for a few seconds while it reloads the textures, but then everything will be back to better-than-normal.)

**Comment by payonel** [comment]
insufficient repro and interest. will not fix and there is evidence it is not opencomputers specific
