### ISSUE TITLE
MCU with transposer shutdown for no apparent reason

### ISSUE THREAD

**Issue by sylphio** [MightyPirates/OpenComputers#1459]
I have a mcu who run the following test program!  The MCU do not lack of energy and is connected to a chest who contain few item but nothing change in the chest.

http://pastebin.com/EqQ0BdhC

--pseudocode
repeat
  transposer.getStackInSlot(side, slot) 
  computer.pullSignal(5)

After few hour, the MCU just shutdown for no reason
I cannot get any explanation from the analyser but i suspect that for a strange reason the getStackinSlot returned an exception.

**Comment by fnuecke** [comment]
If something in the Lua code errored, I'm pretty sure that's show up in the analyzer. Could you please check your MC log when this happens again, see if anything suspicious pops up in there (such as errors/warnings from OC, stacktraces, ...).

**Comment by sylphio** [comment]
Sure, i will do another test pass. Thank for looking into it.

**Comment by sylphio** [comment]
Nothing in the log but i got a "no such component" lua error on the Analyser. It took a long time to get the mcu to crash and the server automatically reboot every 4h. So it may be related.

**Comment by fnuecke** [comment]
Is the transposer across a chunk border or so? Either way, most certainly a loading (order) issue then, add a safeguard to avoid crashing if the component isn't there and try again after a second or so.

**Comment by sylphio** [comment]
The transposer is "inside" the mcu so it cannot be across the chunk border.  Either way, i used a vanilla chest over the mcu and i am 2 block aways from the chunk border. The whole base is chunk loader so in theory only server restart can cause chunk loading.

I will update to the new test version and test if i can reproduce it Thank you :)

Otherwise, I tested the same program on a normal computer and i dont get this error even after days

**Comment by fnuecke** [comment]
I'm a derp, of course it is. Hohum. Weird, I'll have to look into that. Lemme know if it still happens on latest.

**Comment by sylphio** [comment]
Right now, i have a 100% repeat ratio in ~8h. I will update the server tonight and see.. anyways i need to test this saveconfiguration feature for nanomachine ;p

**Comment by sylphio** [comment]
Just retested with the last dev version of open computer (786). I got the same "no such component error". 

I have a lots of mods in this modpack but it really look like something internal to OC.

This "no such component" only affect mcu. Never got the error on the computer + transposer doing the same job (i was trying to replace the computer with a mcu when i got the bug the first time).

Any idea of what i can do to give you some more info?

**Comment by fnuecke** [comment]
One thing to try: instead of storing the proxy, rebuild it on-demand, see if that fixes it.
If you have access to the server logs, look for `didn't save its node`. If that pops up (if at all, hopefully only for the transposer >_>) let me know, that could explain it (and make the workaround work until I can fix it).

**Comment by sylphio** [comment]
You where right ;p for the log. I will try the workaround later. Thank.

Console : [16:03:23] [Server thread/WARN] [OpenComputers]: A component of type 'transposer' disappeared (d90b9aa2-d41b-4a11-a3a9-45c9efd52605)! This usually means that it didn't save its node.
Console : [16:03:23] [Server thread/WARN] [OpenComputers]: A component of type 'eeprom' disappeared (eaf1ae34-42f4-4148-a73e-5cb51dc64944)! This usually means that it didn't save its node.

**Comment by fnuecke** [comment]
All right, thanks for confirming that! I'll try to fix it as soon as I can.

**Comment by fnuecke** [comment]
Hrm, what's the exact configuration of the MCU? Can't reproduce it :/ (neither SP nor MP)
Also, can you reproduce this in single player?

**Comment by sylphio** [comment]
Got it on the last version! My mcu was extremely simple.

MCU case tier 1
Transposer
Memory tier 1.5 x1
CPU tier 1
Program eeprom (the eeprom vas changed multiple time with the crafting recipe??)

For more details : nbt binary of the crashed MCU
http://www.sylphid.ca/download/OpenComputer_Bug_1459_NBTEdit.dat

**Comment by sylphio** [comment]
Got another "no such component" on a tier 2 mcu but with the modem this time. 
Look systematic on my server after a reboot.

It is only me that got this problem or people avoid mcu because they are hard to use?
(p.s did a really nice in-game ide for mcu ;p )
