### ISSUE TITLE
[Suggestion] Ability to do Nanomachine "research"

### ISSUE THREAD

**Issue by ZeekDaGeek** [MightyPirates/OpenComputers#1462]
At the moment Nanomachines seem a little bit annoying to work with because of one major reason, you have no ability to save decent Nanomachines or traits or anything like that once you find them. The current system feels like you're rolling dice over and over again and just hoping that you get something good.

It would be nice if you were able to remove a set of nanomachines from yourself without destroying them, maybe the offset is that in order to do it you need to be killed in the process for it work seeing as the nanomachines fuse with you in such a way that they're impossible to separate from living tissue otherwise. Possibly making a block that you stand on that spins you very quickly until you suddenly die, the nanomachines separated out. Death could be a configuration option for those who want to change the balance.

An alternative way of separation could be giving  Drones with leads the ability to spin people around quickly or something.

Such a system would encourage users to create a program for identifying the nanomachines easily and saving their data for later, then separating themselves from the nanomachines and cataloging the resulting nanomachines. People would also need to make a station for easily stripping themselves of all of their gear and refitting themselves once they've got the new set of nanomachines.

You then have a set of nanomachines you can use depending on the task, a nether set for fire resist, regen set for wither fights, disintegration set for when you want to strip mine by just walking around, etc.

Additionally the Nanomachines at the moment don't change their address when you consume a new set of Nanomachines which would probably need to be fixed so that the such a program can store the Address along with the effects of the Nanomachines.

**Comment by Vexatos** [comment]
> The current system feels like you're rolling dice over and over again and just hoping that you get something good.

That's exactly what it's supposed to be. Once you have a good network, you won't ever have to do it again, which is why it's supposed to be random and expensive.

> It would be nice if you were able to remove a set of nanomachines from yourself without destroying them

which would break the most important balance point of nanomachines as you could just get rid of all the inputs connected to bad behaviors.

> Such a system would encourage users to create a program for identifying the nanomachines easily

Once, then upload it to pastebin for anyone else to easily OPify themselves.

Long story short: The two balance points of the otherwise quite overpowered nanomachines are that they are random and expensive to reconfigure and that you have negative effects too. Getting rid of both or any of them makes no sense whatsoever. If you don't like the negative behaviours, you can just remove the bad potion effects in the config to already get rid of a great part of them. Some other ones will stay in though. Always remember that nanomachines are basically potion effects and better things _for free_ (almost) once you have a good configuration.

**Comment by ZeekDaGeek** [comment]
The way things are set up at the moment has minimal interaction though Vexatos and it's disappointing honestly. I've got a Resistance set of nanomachines, I got it my second try, there's nothing more to do with it because in general it's one of the most well rounded effects.

If I wanted to go mining with the disintegration effect I'm not going to stand around for 15 minutes attempting to eat 64 sets of nanomachines in order to potentially get it having to go through a configuration process every single time, that seems ridiculous but that's the way the current system is set up and as a result that's probably how they will get used which is a shame.

I like the idea of outfitting yourself with specific nanomachines prior to tasks depending on what you need. It's not like I'm saying make it so nanomachines have all of the potion effects, you're still at max going to have 2 positives, it would just be nice to be able to save that set of nanomachines for future use.

**Comment by MyNameIsKodos** [comment]
Might I suggest using the mod Sync?  I've been storing shells with good nanomachine sets, rather than just coping with having the one good effect.

**Comment by MFernflower** [comment]
https://github.com/MightyPirates/OpenComputers/issues/1457

**Comment by fnuecke** [comment]
How about this: the functionality to pre-configure a kit of nanomachines in the player's inventory to the configuration of the currently active ones. I.e. some command "saveConfiguration" and that'll pick the first unconfigured kit of nanomachines in the inventory and preconfigures it. This way there's still some balance via requiring a new set of nanomachines, but you could store one particularly nice configuration for later. In that case I think I'd even default to losing them on death.

(Also I think it's awesome it works with Sync like that, I didn't even think of that :X)

**Comment by Vexatos** [comment]
Hmm... This way you would still have to use the resources and it is still random and you can still get bad effects, but you can store good ones. I like that idea.

**Comment by ZeekDaGeek** [comment]
That seems like a fairly good way of handling it fneuku.

Possibly also adding a return for the address assigned to the nanomachines that they were saved to, that way you can easily load the input information the next time you consume a set of nanomachines.

**Comment by Vexatos** [comment]
@ZeekDaGeek I am pretty sure every modem message received has the sender address as one of its parameters, so you could just probe it by sending any command you want.

**Comment by fnuecke** [comment]
He means the one in the inventory, that the config gets saved to, which wont respond to messages until consumed.

Hm. I guess why not, would be useful and doesn't really open other issues. Alternatively I might just also bake the old address in there, since, well, they'll be identical behavior-wise anyway.

**Comment by Vexatos** [comment]
Aah, so an addition to the ItemStack converter, maybe? Or making it place-able into the Adapter? Sounds fine, I guess.

**Comment by fnuecke** [comment]
More as the return value of the method, but adding a converter in addition might also be a good idea, to allow automatically storing and retrieving them.

**Comment by xarses** [comment]
Looking this over, there was no update added to the manual. Am I right in reading that the new function is `saveConfiguration`, it has no args, and requires at least one nanomachines in your inventory.

**Comment by fnuecke** [comment]
You are indeed right! Will update the manual.

**Comment by xarses** [comment]
I can put together a PR, looks like we also need to update the wiki

**Comment by xarses** [comment]
hot damn, you already fixed it =)

**Comment by fnuecke** [comment]
Ah yeah, would be great if you could update the wiki entry, thanks!
