### ISSUE TITLE
[Suggestion] Cyberspace Dimension

### ISSUE THREAD

**Issue by databeast** [MightyPirates/OpenComputers#1463]
Now, although the possibilities get a little crazy here..the core concept is pretty straightforward.

Give me a void dimension (like AE's cell spaces),where none of my inventory comes with me (like witchery's Spirit World) where I have creative-like powers to place any blocks I want, and worldedit-style select/cut/copy/paste tools. Let me use cyberspace's 'creative mode' to physically assemble coordinates that can be saved to a coordinates text file on the computer I'm inside, to use for things like robots, the hologram  projector, the 3D printer (ie.. blocks in cyberspace are voxels on these devices). 

So before we get all TRON on this. the idea of a void dimension where survival players have some limited creativemode/worldedit tools, in a way that relates back to OC datafiles and code, seems to have a lot of potential.

**Comment by Techokami** [comment]
This seems to be waaaaaaaaaay beyond the scope of the mod.

**Comment by databeast** [comment]
codebase-wise, yeah,, I agree, thinking about it though, it's a one-block, one-item, one dimension addon mod....lemme see if I can find some free time soon to maybe take a crack at it.  Tl;Dr I just like the idea of being able to build voxel sets in-game, without typing out raw numbers.

**Comment by jadenPete** [comment]
This would be a good addon xD
