### ISSUE TITLE
Drone physics broken

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1464]
(For OC 1.5.16.726-dev, will see if i can test new version later, but I didn't see anything regarding this in updates? Or maybe its a printer issue, not sure)

Was messing about with testing of drones can go into 3D printed glass tubes or if they need too much space. Seems the latter.. but during testing this odd thing happened (the surrounding blocks are glass, the block on the top is the glass-tube) (sorry for the bad quality ^^):
https://dl.dropboxusercontent.com/u/18783800/Something%20%2802%29.mp4

(Model used for the tube: https://gist.github.com/Inari-Whitebear/609c5be7e93c05a6e3e6)

**Comment by fnuecke** [comment]
Uhh... I don't even. Kinda leaning towards "welp, Minecraft physics!" but I'll have a look when I can ;-)

**Comment by fnuecke** [comment]
Since I've had pretty much the same thing happening to me with (other mods' :P) cables in tight spaces (also teleported to the next higher floor, which was through 5 or so layers of solid rock, if not more) I'll consider this "Minecraft physics" after all. Working as intended :X
