### ISSUE TITLE
Consuming nanomachines keeps address

### ISSUE THREAD

**Issue by natedogith1** [MightyPirates/OpenComputers#1465]
This is a minor bug, but when you consume a new set of nanomachines they don't get a new address.

**Comment by jymcd** [comment]
I think the address is from the player and not the nanomachines.

**Comment by fnuecke** [comment]
That's somewhat open to interpretation. It can make sense either way. Truth is I didn't really give it any thought yet. I suppose generating a new GUID would make more sense with the "the nanomachines get replaced" logic... I'll think about it.

**Comment by ZeekDaGeek** [comment]
Getting a new address when you consume a new set of Nanomachines would go a long way to making automated programs for figuring out the inputs. Any time an untracked address shows up then you can start the configuration process.

**Comment by sylphio** [comment]
How can you even read the address? It is not available from the nanomachine network protocol?

**Comment by sylphio** [comment]
Ha yes, from the answering network card.  sorry ;p
