### ISSUE TITLE
Odd interactions between Robots and Magnanimous Tools

### ISSUE THREAD

**Issue by Aedda** [MightyPirates/OpenComputers#1467]
I've noted an unusual interaction between Robots and MagTools. In that Robots will accept these modded tools and sometimes attempt to use them but in most/all? cases the tools fail to function as expected or at all.

MagTools rely on the players experience pool for adjusting the stats of the individual tools. In the case of Robots this pool obviously does not exist. As such some MagTools cause the Robot to act as if there was no tool installed, others quickly burn through their durability as the Robot rapidly tries using them without any actual blocks breaking.

I'm not sure where the responsibility of correcting this interaction lies nor if there is actually any responsibility to resolve it. I wanted to bring it up regardless however as it is something that exists and may be worth looking into.

**Comment by gjgfuj** [comment]
Iirc the experience upgrade exists and gives the robot an experience pool?

**Comment by fnuecke** [comment]
The XP upgrade doesn't provide "actual" XP to the fake player though.

I'll try to grab the mod soon-ish and see what's going on in dev-env.

**Comment by fnuecke** [comment]
Hmm, what cases exactly does it not seem to work in? Because in my simple test case everything works as expected: http://gfycat.com/ImpureSingleDutchshepherddog

**Comment by Aedda** [comment]
Interesting, I'll run additional tests in a clean instance and let you know.

**Comment by Aedda** [comment]
Ok I finally got it to reproduce. In the 3x3 grid if the top center block is air then the tools operate incorrectly. Filling that 9th space with any block restores normal function to the tools.

**Comment by Aedda** [comment]
I just found something even more strange. Create a solid 3x3x3 dirt structure, remove the front center 2 blocks, as if you were going to place a door. Using the Earth Mover dig the center block. A 3x3x1 area will be broken as expected. Now repeat with a Robot and the area broken is turned 90 degrees.

**Comment by fnuecke** [comment]
Couldn't repro the second thing anymore, but I didn't try before the fix, so you might want to verify that.
