### ISSUE TITLE
Gregtech (IC2 components) recipes file need to be updated

### ISSUE THREAD

**Issue by Dream-Master** [MightyPirates/OpenComputers#1468]
After Ic2 using Meta Ids  for Heat Vents the Gregtech recipes maybe need to be updated. (Need Metadata 1 because 0 isn't raftable anymore)

```
case2 {
  input: [[screwStainlessSteel , "oc:materialCircuitBoardPrinted", craftingToolWrench]
          [{item="ic2.reactorVentGold", subID=1}, "oc:case1", {item="ic2.reactorVentGold", subID=1}]
          [screwStainlessSteel, "oc:circuitChip2", craftingToolScrewdriver]]
}
case3 {
  input: [[screwTitanium , "oc:materialCircuitBoardPrinted", craftingToolWrench]
          [{item="ic2.reactorVentDiamond", subID=1}, "oc:case2", {item="ic2.reactorVentDiamond", subID=1}]
          [screwTitanium, "oc:circuitChip3", craftingToolScrewdriver]]
}
serverRack {
  input: [[craftingToolScrewdriver, "oc:wlanCard", craftingToolWrench]
          [{item="ic2.reactorVentDiamond", subID=1}, chest, {item="ic2.reactorVentDiamond", subID=1}]
          ["oc:relay", "oc:materialCircuitBoardPrinted","oc:powerDistributor"]]
}
```

I try put this recipes in the user recipes but it shows me an error

```
Line 34059: [01:15:07] [Server thread/DEBUG] [DREAMCRAFT/]: Something weird happend with item OpenComputers:case3
```

**Comment by Dream-Master** [comment]
Did i something wrong maybe ?

**Comment by Dream-Master** [comment]
I change the recipes with minetweaker and hope some one can look inside this.
Thanks

**Comment by fnuecke** [comment]
`Line 34059` of... what? Your log? That message doesn't come from OC, at least I can't find the string `Something weird` anywhere in all of OC's source code... so I don't know what that's about. I'll update the IC2 in my dev-env when I can to update the recipes.

**Comment by Dream-Master** [comment]
I using Gregtech recipes (the Open Computer ones) in my modpack. The Case 2 and 3 need Heat Vents from Ic2.
I can't craft the recipes because Ic2 using now Meta Data for the Heat Vents.
old ic2 = IC2:reactorVentDiamond
new ic2 Version 780 = IC2:reactorVentDiamond:1

**Comment by Vexatos** [comment]
Basically, make it metadata-independent. I guess.

**Comment by Dream-Master** [comment]
In your gregtech.recipes file i see some items using meta data 
line 40
{item="gt.metaitem.01", subID=32762}
thats why i thought i can fix it with the user.recipes adding only subID=1
but this not working for me.

**Comment by fnuecke** [comment]
Which versions are you talking about? I just grabbed latest IC2 and GT5 [1] and the recipes are working fine for me?

[1] `industrialcraft-2-2.2.780-experimental` and `gregtech_1.7.10-5.09.06`

**Comment by Dream-Master** [comment]
industrialcraft-2-2.2.780-experimental and gregtech_1.7.10-5.08.30 i am using.
But in a modpack with other mods.

Modlist here:
https://github.com/GTNewHorizons/NewHorizons/blob/master/README.md

**Comment by fnuecke** [comment]
That's... a long list. I have no idea what other mod in there might lead to the IC2 recipes, much less _items themselves_ changing so that they don't work in OC's recipes any longer. Given it's apparently an issue in your modpack / in combination with some other mod, since you can work around it with Minetweaker I'd say that's a good enough solution, sorry.

**Comment by Dream-Master** [comment]
No problem for me. Have to look wich mod cause this error. Thanks
