### ISSUE TITLE
cp command defaults to using -i

### ISSUE THREAD

**Issue by snowTH** [MightyPirates/OpenComputers#1469]
The copy command (cp) automaticly gets the interactive (-i) flag set to true, even if it is not specified.

In this screenshot, I modified /lib/shell.lua to print it's arguments, and the returned option table.

http://puu.sh/kwulY/1dc4d65a30.png

**Comment by fnuecke** [comment]
[`cp` is aliased to `cp -i` by default](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/OpenOS/boot/94_shell.lua#L16), to make it less likely to accidentally delete stuff.
Remove the alias if you don't like it (`unalias cp`).

**Comment by snowTH** [comment]
Right, I forgot about aliases. This makes sense. Thanks!
