### ISSUE TITLE
Add compatibilty for BuildCraft builder

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#1472]
Allow storing OC's blocks in blueprints via architect table to be placed back into the world via builder.
- [x] Add block definition JSON files.
- [ ] Add item filter JSON files (waiting for item filter implementation).

**Comment by CoolCat467** [comment]
That sounds like it theoretically could work, but would just be tedious to do for every item if they aren't being derived from a base class somewhere

**Comment by gatoborrachon** [comment]
also, i guess that this will not be possible for 1.12, right? 
sad

**Comment by CoolCat467** [comment]
1.12 is starting to be outdated. Time moves on. Better things are coming with future versions. No one really does anything with 1.7.10 anymore, yet that was a huge modding scene at the time. Time moves on.

**Comment by gatoborrachon** [comment]
oh well, with my question i meant that this is impossible because:
First: The builder is on "Beta" and it will ever be in 1.12
Second: Sadly, they are moving to fabric
