### ISSUE TITLE
Allow filling components into servers

### ISSUE THREAD

**Issue by Kubuxu** [MightyPirates/OpenComputers#1474]
Ideas:
- assembler
- robots
- BC Builder and server requirement split into separate components.

**Comment by fnuecke** [comment]
- Possibly add a generic way for the inventory controller to interact with item inventories. For one, an internal API / interface, but might also add integration for other mods item inventories (backpacks).

**Comment by fnuecke** [comment]
dbb710b708203261daf53be895120b6e0976774b
