### ISSUE TITLE
Add BuildCraft Programming Table integration

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#1475]
- https://github.com/BuildCraft/BuildCraft/blob/7.1.x/api/buildcraft/api/recipes/IProgrammingRecipe.java

To allow generating loot disks. Floppy in, Loot Disk out.

**Comment by Vexatos** [comment]
> B..but that's cheaty! Generating dungeon loot out of thin air! You cheater! How dare you!

...Not sure I like this idea... Aren't they supposed to at least be a little rare?

**Comment by fnuecke** [comment]
I'll make it use a gigantillion units of energy, happy? :P (No I won't)

(Longterm goal here would actually be to allow adding in some "starter loot disks" (something like dig for tree felling, farming-ish thing) to allow getting into OC a bit more easily, software-wise, when you're not in it for writing your own OS or such :P (without having to have a recipe for each, which would get annoying as all hell :X And isn't really feasible for user added loot disks anyway)).
