### ISSUE TITLE
Robot Floppy Swapping

### ISSUE THREAD

**Issue by natedogith1** [MightyPirates/OpenComputers#1476]
It seems at the moment there isn't really a way for a robot to swap its own floppy. I've read in #87 that you can pull the floppy out from the back (though I don't think that's documented anywhere), but that requires you to have two robots or some non-vanilla item movement. I was personally hoping to be able to (at least theoretically) beat the game by placing a creative robot, turning it on, and issuing a pastebin run command, however the inability to change floppies causes an issue. (basically, you'd need a drone to change dimensions, which needs to be assembled; to start the assembler you need a computer, to tell the computer what to do the robot needs to be able to write code to a removable media)

Sorry if that's a bit hard to read / wall of text-y. Basically, it'd be nice for large-scale automation if a robot could swap it's floppy.

**Comment by payonel** [comment]
you can add the disk drive component to a robot as a work around
