### ISSUE TITLE
BIOS should be installed on the motherboard, not the harddrive

### ISSUE THREAD

**Issue by TeamDman** [MightyPirates/OpenComputers#1479]
My friend was playing with the mod and he found it silly that you would have to install a BIOS on a harddrive, so I thought I would let you guys know.

**Comment by jymcd** [comment]
How did you manage to install the bios on a hard disk and get it to work without an eeprom?

**Comment by LizzyTrickster** [comment]
Care to elaborate on how you install the BIOS onto the HDD? unless you're playing OC 1.2 (in which case i suggest you update) the BIOS (EEPROM) is a seperate chip from the hdd itself

**Comment by Xfel** [comment]
I think he is talking about the visual appearance of the computer GUI. While the EEPROM sits in an own slot on the left side, all other parts are grouped on the right side on a motherboard-like background. It's true that this separation is a bit strange.

**Comment by skyem123** [comment]
there also appears to be the mix up of "hard drive" and "computer case"...

**Comment by fnuecke** [comment]
So the... nitpick is that I was too lazy to adjust the GUI background when adding the EEPROM slot?
