### ISSUE TITLE
Nanomachine Debug Command issues

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#1482]
1. The debug log starts indexing at 0, it should start at 1 (so index 13 in server log actually is the index 13 when sending commands to nanomachines)
2. `controller.getInputCount()` returns 0 on any behavior (including active ones).

**Comment by fnuecke** [comment]
1. Well, for the Lua API, yes. For the Java API they start at 0. Soo... meh.
2. Works fine for me (tested on pfx behavior, `li.cil.oc.api.Nanomachines.getController(player).getInputCount(this)` returns 1 in `update` as expected.

**Comment by Vexatos** [comment]
I did [exactly the same](https://github.com/asiekierka/Computronics/blob/master/src/main/java/pl/asie/computronics/integration/forestry/nanomachines/SwarmBehavior.java#L77) and it returned 0 for me...

I still think the index count should start at 1 since the debug log is meant to be used for Lua commands.

**Comment by payonel** [comment]
@Vexatos i'll let you decide if we need to make changes for this or not. close as you see fit

**Comment by payonel** [comment]
closing as "meh" for index at 1
and no repro for getInputCount
