### ISSUE TITLE
Game freezing at main menu when starting game

### ISSUE THREAD

**Issue by levicc00123** [MightyPirates/OpenComputers#1483]
[Full startup logs](https://gist.github.com/levicc00123/db6b145799181afc7160)

Client info: Forge: 10.13.4.1517 MCF: 9.05 FML: 7.10.99.99

System Info: OS Windows 10 Home 64-bit CPU: Intel Core 13 @ 1.9GHz RAM: 6GB Video: Intel HD Video Driver: 10.18.15.4279

I'm using a custom pack containing:
- DragonAPI v9b
- RotaryCraft v9b
- ReactorCraft v9b
- ElectriCraft v9b
- Applied Energistics 2 rv2 Stable build 10
- AE2 Stuff 0.5.0.52
- BDLib 1.9.2.102
- Chisel 2 2.5.1.44
- Carpenter's blocks 3.3.7
- BiblioCraft 1.11.1
- CodeChickenCore 1.6.43
- ChickenChunks 1.3.4.19
- NEI 1.0.4.107
- Dense Ores 1.6.2
- EnderStorage 1.7.4.33
- Extra Cells 2.2.73b129
- Extra Utilities 1.2.11
- fastcraft 1.21
- Inventory Tweaks 1.59-dev-152
- Iron Chest 6.0.62.742
- JABBA 1.2.1a
- Journey Map 5.1.0
- Mystcraft 0.3.00
- OpenBlocks 1.4.4
- OpenModsLib 0.8
- OpenComputers 1.5.18.36
- OpenPeripheral AIO-5
- ProjectRed 4.7.0pre9.92
- Steve's Factory Manager A93

And probably a few other mods I'm forgetting.

Is there any other information I can provide to improve this crappy bug report?

**Comment by Vexatos** [comment]
And why do you think OpenComputers is related to this error? There is an error, but it mentions Remote IO...

**Comment by levicc00123** [comment]
I've been using [Remote IO](http://minecraft.curseforge.com/projects/remote-io?gameCategorySlug=mc-mods&projectID=67593) for a long time, and I've never had any problem with it. What made me suspect OpenComputers was the culprit here is the last three lines in the logfile I linked ablove, and removing OpenComputers fixed my problem.

**Comment by fnuecke** [comment]
Does this happen with _only_ OC? If not, could you please try and figure out in combination with which mod(s) this happens (i.e. remove half of them, then the other half, for the one it still freezes, repeat).

**Comment by levicc00123** [comment]
Okay, so I created a new MultiMC instance containing Minecraft 1.7.10, forge, and OpenComputers, and I still have the same problem, which makes me wonder if its something in Windows 10 that's causing a problem.

**Comment by dgelessus** [comment]
The "Unable to access any field" thing is a non-error error AFAICT, it seems to be fairly common. Could you perhaps upload the full Forge log (fml-client-latest.log) to Gist with only Forge and OpenComputers? That would make it much easier to see anything that could be wrong with OC. (Perhaps also try to disable Forge's loading screen in the splash.properties, that is sometimes related to hangs/crashes while launching.)

**Comment by fnuecke** [comment]
I'm having no issues on my Win10 machine, so I doubt it's that. Do try disabling the new loading screen like @dgelessus said tho, that does indeed cause hangs for people sometimes.

**Comment by levicc00123** [comment]
The logfile @dgelessus asked for, with only forge, OpenComputers, and the splash screen turned off has been added to my [original gist](https://gist.github.com/levicc00123/db6b145799181afc7160) as a new file.

**Comment by fnuecke** [comment]
Since you're running the JDK, have you ever worked with JVisualVM? Attaching that to MC to see if some threads are in a deadlock, and if so which and where would be super helpful.

**Comment by levicc00123** [comment]
From looking at the thread visualization tab, it looks like it's a problem between OpenComputers and the sound system, but I don't know for sure. I've created a thread dump and attached it to my original gist.

**Comment by wischi-chr** [comment]
I've the exact same problem on my new notebook win10 x64.

Installed minecraft, forge for 1.10.2 and the latest 1.6.2 OC and it freezes on the main menu.

My desktop (running the same versions) works fine.

**Comment by payonel** [comment]
@wischi-chr this bug report is too old, make a new issue and make sure you are testing with only OC and forge. confirm it does not repro with forge alone

thanks

**Comment by wischi-chr** [comment]
@payonel 

Forge alone worked (even started a game and played for about 10 minutes to make sure)
After adding OC (no other mods) it froze at main menu (not responding)

After installing JDK (only installed JRE at first) it finally works.

**Comment by payonel** [comment]
please make a new ticket, this one is too old to be of relevance
in your new ticket, give host os version, oc version, and forge version.
thanks
