### ISSUE TITLE
TransformerLoader shouldn't be a DummyModContainer

### ISSUE THREAD

**Issue by simon816** [MightyPirates/OpenComputers#1485]
This is causing an incompatibility between OC and SpongeForge, see https://github.com/SpongePowered/Sponge/issues/362

`TransformerLoader` causes the class `DummyModContainer` to load before all tweakers are even registered.
SpongeForge uses the [Mixin](https://github.com/SpongePowered/Mixin) to modify `DummyModContainer` (it [adds an implementation](https://github.com/SpongePowered/Sponge/blob/master/src/main/java/org/spongepowered/mod/mixin/core/fml/MixinModContainer.java#L41) of SpongeAPI's [`PluginContainer`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/plugin/PluginContainer.java))

I suggest removing the `DummyModContainer` from it and make it load in the normal mod load cycle.

(related OC commit: https://github.com/MightyPirates/OpenComputers/commit/0b7eb7a57841b719e78d7194ee68deae891484e2)

**Comment by fnuecke** [comment]
Not sure I understand what you mean by

> and make it load in the normal mod load cycle

Would removing the inheritance from `DummyModContainer` and having that in an extra class, the type of which would be returned by `TransformerLoader.getModContainerClass` fix the issue?

**Comment by simon816** [comment]
I think that would fix it. By loading in the normal mod cycle I mean to let FML create the mod rather than loading it when the coremod initializes.
Make sure to use a literal string for `getModContainerClass`, by using Class.getName() it will load it too early

**Comment by fnuecke** [comment]
Allright then, give the next build a try.

**Comment by simon816** [comment]
Need it for MC 1.8, is it possible to merge it into your 1.8 branch please?

**Comment by fnuecke** [comment]
Ah, right. Done. Building now.

**Comment by simon816** [comment]
It works, thanks!

**Comment by Zidane** [comment]
Thanks a lot for this @fnuecke . Really appreciated.

**Comment by fnuecke** [comment]
No problem, thanks for confirming :)
