### ISSUE TITLE
Bridging OC and CC

### ISSUE THREAD

**Issue by scj643** [MightyPirates/OpenComputers#1489]
Don't hate on me for this. There are some people that have been using CC for a long time and aren't confertable with OC. We should make it so it's possible to allow OC to expose peripherals to CC.

**Comment by fnuecke** [comment]
Already possible and has been for a long time, use a switch next to a CC computer. It exposes OC components as remotes (just make sure it shows up as `modem` to CC, if it doesn't some other mod is screwing with things and you'll have to work around that).
