### ISSUE TITLE
OpenComputers not picking up on changes from external text editors

### ISSUE THREAD

**Issue by Moltenkore** [MightyPirates/OpenComputers#149]
Like the title says, when I save a change from notepad++ to the hardrive of computer it doesn't change. When I run edit in-game the file is still what is was before I made the external change.

Not sure if this is a bug or if I'm doing something wrong.

**Comment by Moltenkore** [comment]
Pulling the hardrive seems to work, but again not sure if this is intended.

**Comment by SpiritedDusty** [comment]
Take a look at issue #50

**Comment by Moltenkore** [comment]
Oh okay, thanks. Guess I'm going blind, didn't see that issue.
