### ISSUE TITLE
Console Spam (Not sure its OC)

### ISSUE THREAD

**Issue by Dyonovan** [MightyPirates/OpenComputers#1490]
Getting this come up every couple of seconds.

http://pastebin.com/0vYYKyC4

List of mods:

http://pastebin.com/zRPRYWXF

**Comment by fnuecke** [comment]
Looks like something (from `vswe.production`, so maybe SFM or so?) fires a crafting event without an associated player (or a fake player without an associated world). Will add a null check.

**Comment by Dyonovan** [comment]
Thanks. this has been driving me nuts for a LONG time and vswe hasnt updated sfm in forever

**Comment by fnuecke** [comment]
No problem, thanks for letting me know :-)

**Comment by gjgfuj** [comment]
BTW, if you want a more updated version of SFM, check out Advanced Systems
Manager by Hilburn, it is a much more stable clone.
