### ISSUE TITLE
[Suggestion] Reboot in case of too long without yielding

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#1491]
When a computer is too long without yielding, it stops to working and sometimes that bug occurs when server lags and some of these computers are required to prevent another things to for example explode. My idea is to reboot these computers when they are too long without yielding. Can you add a new option in the config to do so please?

**Comment by makkarpov** [comment]
Or maybe to `computer` API. Since yield timer acts as watchdog, something like `resetOnWatchdog(x: boolean)` might be useful and will let program writers decide what they should do if something hangs.

You can also catch yielding errors with `pcall` and simply restart your code.

**Comment by dgelessus** [comment]
`pcall` is probably the best solution here. A config or computer option for this doesn't seem necessary for something that can easily be done in plain Lua. If you're using OpenOS, it should also just drop you back to the shell and not crash the computer entirely.

**Comment by fnuecke** [comment]
Yeah, the first time when it goes too long without yielding is a soft error (i.e. catchable with `pcall`), so use that and immediately long yield (`computer.pullSignal`) if it happens. As a fallback, have a redstone card with wake on redstone and use a comparator to trigger it when the computer turns off.
