### ISSUE TITLE
getTileNBT returns writeToNBT method

### ISSUE THREAD

**Issue by natedogith1** [MightyPirates/OpenComputers#1492]
The debug card's getTileNBT method seems to return nil and the tile entity's writeToNBT method, instead of the expected actual nbt data.

To reproduce open up the lua prompt on a computer with a debug card and run 

``` lua
=component.debug.getWorld().getTileNBT(math.floor(component.debug.getX()),math.floor(component.debug.getY()),math.floor(component.debug.getZ()))
```

**Comment by fnuecke** [comment]
Try some other block than the one with the card in it. It probably errors because the computer executing that command is trying to persist itself.

**Comment by natedogith1** [comment]
This happens as well with a chest.

**Comment by fnuecke** [comment]
Are you absolutely sure your coordinates are right? Because it works for me.

**Comment by natedogith1** [comment]
I'm sure. Surrounded the creative computer with chests and ran

``` lua
=component.debug.getWorld().getTileNBT(math.floor(component.debug.getX()),math.floor(component.debug.getY()),math.floor(component.debug.getZ())+1)
```

![2015-10-17_05 59 55](https://cloud.githubusercontent.com/assets/1638163/10558170/629bb016-7494-11e5-90b8-6e8a55e4fbd5.png)
![2015-10-17_05 59 58](https://cloud.githubusercontent.com/assets/1638163/10558172/64dc68d4-7494-11e5-8f70-25d1251075c1.png)

**Comment by fnuecke** [comment]
I have no clue what'd be different from your world.
![2015-10-17_12 09 57](https://cloud.githubusercontent.com/assets/514903/10558220/b02e6420-74c8-11e5-80d3-d331bb401f42.png)

Maybe check your MC logs for a full stacktrace or so?

**Comment by fnuecke** [comment]
Ohhh, wait. You're not in a dev-env, are you? Goddammit. Yeah, I think I know what's going on.
