### ISSUE TITLE
Miecraft has crash with OpenComputers

### ISSUE THREAD

**Issue by ComBlockWither** [MightyPirates/OpenComputers#1495]
If I run Minecraft 1.6.4 version with LATEST version of Forge and ONE mod (OpenComputers), Minecraft crashed. Java 7, Windows XP.

**Comment by fnuecke** [comment]
Sorry, I no longer support neither MC 1.6.x nor Windows XP.

**Comment by ComBlockWither** [comment]
Okay... I test 1.7.10
