### ISSUE TITLE
World edit and debug.runCommand

### ISSUE THREAD

**Issue by Alessandro404** [MightyPirates/OpenComputers#1497]
Hi, when I try to paste in world a schematic file loaded from a debug card (linked to a OP player) nothing happens.

I've used the example here https://github.com/MightyPirates/OpenComputers/issues/892
for  testing the basic functionalities of world edit and opencomputer with success (I was able to turn a building to glowstone asd).

So, I've tried to see if 
print(debug.runCommand("//schematic list"))  turned something, and indeed the command printed the list of the currently saved schematics on the server.

So i thought that 
debug.runCommand({"//schematic load test.schematic", "//paste"}) would work, but I was wrong. No errors, no logs... nothing. 

I have very little experience with Opencomputer, and I'm sure at 99%  that it's my fault. If so, sorry.

**Comment by fnuecke** [comment]
To experiment, does it work if you manually load the schematic (or whoever is the player the card is bound to) and then run just the paste command? Does it maybe work if you do it in two separate `runCommand`s?

Other than that, no idea. Maybe someone with more experience with WE than me has a clue?

**Comment by Alessandro404** [comment]
When the computer try to load a schematic, it loads on my clipboard a different schematic, noted this after a while... but no, different runCommands doens't make a difference.

mmmm I tried to ask for a log when i was on the server.
My friend told me that my player correctly loaded  the right schematic, and after that the console throwed an error with this.

GRAVE [WorldEdit] An unexpected error while handling a WorldEdit command java.lang.reflect.invocationTargetException.

I'll try to obtain the complete error log if You think you need it
