### ISSUE TITLE
MySQL connector

### ISSUE THREAD

**Issue by scj643** [MightyPirates/OpenComputers#1499]
A MySQL database connector component that would be able to easily access MySQL databases using the Internet card.

**Comment by makkarpov** [comment]
No. It
1. Out of scope of this mod
2. Would require MySQL JDBC library on classpath which no one will use
3. Can be done in plain Lua w/ Internet card (MySQL protocol is relatively simple)
4. Can be done with addon.
5. Can be done on server side by implementing HTTP API

**Comment by Kubuxu** [comment]
6 . Could be done by normal Lua Database solution, especially with Lua's 5.3 `string.pack`.

**Comment by fnuecke** [comment]
Pretty much all has been said :P

**Comment by LukeTech2006** [comment]
> No. It
> 
>     1. Out of scope of this mod
> 
>     2. Would require MySQL JDBC library on classpath which no one will use
> 
>     3. Can be done in plain Lua w/ Internet card (MySQL protocol is relatively simple)
> 
>     4. Can be done with addon.
> 
>     5. Can be done on server side by implementing HTTP API

Then please explain HOW THE FRICK THIS WOULD WORK AND NOT JUST SAY "IT WORKS"!
