### ISSUE TITLE
Ridiculously large filesystems can cause crashes

### ISSUE THREAD

**Issue by SentientTurtle** [MightyPirates/OpenComputers#1500]
Seemingly, the config's filesystem (or specifically: HDDs, more testing required to determine which) size value is not capped, allowing extremely large values to overflow and cause issues.

Crash log, scenario and config file provided by jhagrid77:
  Crash log: http://pastebin.com/B2L16k8K
  Occurs when: Inserting oversized HDDs  into a raid.
  Config file: http://pastebin.com/xGHFXV7r

My debugging assumption (This may be completely false):
this may be caused by a filesystem size over 2,147,484 kB overflowing into a negative number, and then being used as an array size, throwing a NegativeArraySizeException.

**Comment by dgelessus** [comment]
Best commit message automatic line break, \010/10 would \n again.
