### ISSUE TITLE
crash client to the server

### ISSUE THREAD

**Issue by SvEgiiVEteR** [MightyPirates/OpenComputers#1504]
crash client to the server. I wrote in the chat command and press Tab
http://hastebin.com/ohahefuvel.md

**Comment by Ionaru** [comment]
"crash client to the server" = Client crashes when on server

Same issue here, writing part of the command and using Tab to autocomplete crashes the client. 
Commands do work normally when fully typed-out.
This only happens in multiplayer.

Forge version: 10.13.4.1418
KCauldron verion: 1418.144
Opencomputers version: 1.5.19
Opencomputers addons: 
Computronics 1.5.7
Opensecurity 1.0-66
OpenPeripheral Core 1.2
OpenPeripheral Addons 0.4
OpenPeripheral Integration 0.3

Glorious crash report: http://pastebin.com/FPMzMJ8S

**Comment by fnuecke** [comment]
Didn't actually test this, so if you could, that'd be great ;-)
