### ISSUE TITLE
Ability for Robots to turn on PC´s

### ISSUE THREAD

**Issue by Erumaaro** [MightyPirates/OpenComputers#1505]
It is possible for a player to sneak-activate a PC with a Screwrench, which causes the PC to turn on.
But I haven´t been able to make a robot do it.
(i used: component.robot.use(sides.front,front,true)   )
I believe this is the correct way, but maybe it takes a player to boot a computer.
If that is the case, than the robot could act as a proxy for the player who build it.

If a robot could boot a PC, it could become possible for a robot to replicate on its own.
-> robot can controle an assembler via self build PC...

**Comment by MyNameIsKodos** [comment]
You could always use wake on redstone or network message via a wireless network card

**Comment by Erumaaro** [comment]
Could you explain this to me?
(I`m new  to OC)

**Comment by Erumaaro** [comment]
I want this to work with a brand new PC(neither OS nor anything)
And i doubt a floppy with a custom OS that contains the code necessary to wake-up the PC would do anything, since you have to boot the PC first ,no?

**Comment by Erumaaro** [comment]
i just checked some code ( component/NetworkCard.scala )
and found that wakeMessage is initialized as: None
which i suppose means  nil  in Lua
=> could a robot send an empty message ("") to a just placed+assembeled PC and cause it to boot, or are all ports closed by default?

**Comment by MyNameIsKodos** [comment]
Ports are closed when the device is off, anyway. But you don't need an open port when doing the wake bit.  Not sure how to do what you're doing with it offhand, it's late and I've been awake entirely way too long.

**Comment by gjgfuj** [comment]
No, you should be able to turn a robot on with another robot. I was able to
do that in the past and so it is a bug.

**Comment by gjgfuj** [comment]
I.e. using the use command. When I did it was before the scrench however,
so it may have changed. It should still be possible though.

**Comment by Erumaaro** [comment]
@MyNameIsKodos Could you please tell me what has to be done in order to "wake-on-message" a computer in detail, so that i can figure out wether or not a robot could do it?
Edit: IRL, "wake-on-signal" is controled by the BIOS => EEPROM in OC.
Does a PC with an empty HD require a custom EEPROM to be able to "wake-on-signal"(message/redstone).

@gjgfuj "empty-handed" robot.use() (normal and sneaky) does nothing to a PC, havent tested it on a robot jet.
EDIT: "empty-handed" component.robot.use(sides.front,front,true) turns on a robot alright!!
(my OC version:1.5.19.37-universal)
but it has no effect on a PC...bummer.

**Comment by Erumaaro** [comment]
I GOT IT!!
I tried it with a CREATIVE Case all this time!!
A robot can sneak-activate a regular case(i tried tier 1) with "an empy hand" and the PC will boot!!
This makes things infinitly more simple.
Thanks anyway.
PS: I still would like to know about the "wake-bit", if you please...
