### ISSUE TITLE
Spawn (copy) floppy disks with a command

### ISSUE THREAD

**Issue by Ionaru** [MightyPirates/OpenComputers#1507]
For a while I've been playing with Opencomputers on my server and while copying floppy disks and handing them out works fine, sometimes I'd like to just use a command for it.

My suggestion is to add a command to Opencomputers, similar to the /give command of bukkit/essentials. But it would only be for floppy disks (and maybe hard drives).
The command would use 3 parameters: target player, target floppy template, and quantity.

Example format: /oc_give {player} {target floppy disk ID} {quantity}
Example command: /oc_give Ionaru 8771ac67-b22e-4268-a357-511f72f4dd00 1

This would create a new floppy disk (with a different ID) and copy the contents of the template floppy disk to the new one. This was the new floppy can be edited without messing with the original.

Thanks for reading my suggestion and have a nice day! o/

**Comment by MyNameIsKodos** [comment]
You could easily set up a computer with 2 disk drives, and just set up a simple copy program to copy from drive A to drive B when ran. A command would be not only tedious to code but one that would copy a disk's contents would be difficult at best.

**Comment by Ionaru** [comment]
For me it would be really useful to be able to give out floppy disks with programs using the command line. 

The contents of floppy disks and harddrives are saves in separate folders in world/opencomputers. So copying one using the folders wouldn't be difficult at all. 

As for the code part, I believe it would be fairly simple. 
1. Give the player a new floppy disk with a new ID. 
2. Fetch the ID of the new floppy disk. 
3. Use that ID to copy the contents of the original floppy folder to the new one. (Using Java file IO or just straight out copy everything)

**Comment by fnuecke** [comment]
Couldn't you use a custom loot disk for this?
