### ISSUE TITLE
1.7.2 Screen texture with no anisotropic filtering

### ISSUE THREAD

**Issue by Snakybo** [MightyPirates/OpenComputers#151]
The screen texture seems to be acting weird when Anisotropic Filtering is set to 0.

No other mods, All settings maxed except Anisotropic Filtering, Forge 1024

![2014-03-08_01 57 09](https://f.cloud.github.com/assets/3172140/2364007/255c2318-a65d-11e3-9486-1c6e5f7da666.png)

**Comment by SpiritedDusty** [comment]
I have the same Forge and settings setup as you, but mine's working. Maybe it's your texturepack?

EDIT: Nevermind. I'm having problems as well but it only occurs with multiple monitors and AF set to 16.

![2014-03-07_19 33 34](https://f.cloud.github.com/assets/2245442/2364413/b7f8eb10-a672-11e3-8db9-56ec98bce735.png)

**Comment by fnuecke** [comment]
See #114 regarding the flipped textures.

Seeing how much they messed up the rendering in MC1.7.2 I'll be waiting for 1.7.4 before having another look at the issue related to AF. I can confirm it, though, have seen this once but couldn't reproduce it since.
