### ISSUE TITLE
[minor glitch] When the relay have zero energy, it still "glow" when it receive a packet.

### ISSUE THREAD

**Issue by sylphio** [MightyPirates/OpenComputers#1511]
Not critical but it really give the impression that the relay is actively retransmitting but in fact,  it is not doing anything. It can be a little bit misleading ;p

Thank

**Comment by LizzyTrickster** [comment]
It generally only needs power for wireless or linked card message sending
iirc

**Comment by sylphio** [comment]
K, Good to know. it explain why it was not working when connected directly to a mcu (that i wasn't expecting to give energy to the relay)

**Comment by sylphio** [comment]
k, finally understood why it was not working all time for me. 

Just in case somebody else read this issues ;p 
The relay have one energy buffer per side... so even if you power the relay... if you have a MCU on one side.. it will not be wirelessly relayed because the mcu-side is not "energized" by the mcu.  So you need to connect a additionnal power converter on the mcu-side cable each time if you want to relay a message wirelessly from a microcontroller.

**Comment by fnuecke** [comment]
Soo, resolved?

**Comment by sylphio** [comment]
For me yes... ;p

The "one energy buffer per side" thingy  is not so intuitive but it is your call ;p
Thank

**Comment by fnuecke** [comment]
Hrm, it's currently explicitly that way, not sure if there was a deeper reason than wanting to avoid iterating all sides every time. Will see.
