### ISSUE TITLE
Client disconnect with odd server error.

### ISSUE THREAD

**Issue by CaitlynMainer** [MightyPirates/OpenComputers#1512]
I've been trying to track down an odd issue with one server in a rack it doesn't seem to affect any other server/rack combos and I've replaced both the server, and the rack a number of times.  The server will randomly crash in string:lower() and will no longer boot until the server is removed from the rack, the CPU is pulled and the arch switched.  As soon as you put the server back in the rack the server disconnects the player putting the rack in with http://paste.pc-logix.com/view/cc9ed624  Upon logging back in sometimes the other servers in the rack will not render except for the status light: http://i.imgur.com/SL1mQi7.png  (The top server is installed, it is also the one having issues).  After this initial crash every time you remove/replace the server it will repeat this same set of actions, and I have to replace the rack/server to get it to stop.

Server config: http://i.imgur.com/5nO3S2U.png

OC Version 1.7.10-1.5.19.37
Forge: 1517

**Comment by fnuecke** [comment]
Since the config itself doesn't seem to be what's causing it (can't reproduce it), is there anything in the logs when you load into the world / chunk or when inserting the server into the rack? What happens when you try to power up the first server? (because this basically means its machine has a `null` address for its node, which... should sorta be impossible :/)

Edit: also, that log isn't something that would lead to a disconnect, is there anything else before / during the disconnect?

**Comment by CaitlynMainer** [comment]
http://paste.pc-logix.com/view/cc9ed624 is what happens when placing the machine in the rack, trying to power it on continues with the same crash in string:lower()  I'll try to get the error in a bit.  All of the servers in this rack are running @Shuudoushi's SecureOS, but it's only ever the server in the top slot.

**Comment by Shuudoushi** [comment]
I've narrowed the string.lower() crash to not having a monitor/terminal hooked up to the computer, which for the most part seems to be unrelated to the issue at hand, but it is a handy indicator as to what's happening. The rack in question seems to be setting all component addresses to nil/null, which would explain quite a bit. As to why it's setting all the addresses to nil/null, no clue... (Sorry if this is a bit incoherent, I just woke up...)

**Comment by Shuudoushi** [comment]
All servers in the rack in question are running a dev build of SecureOS (0.70), the line the error happens on is [line 29 of the login script](https://github.com/Shuudoushi/SecureOS/blob/dev/boot/z_login.lua#L29).

**Comment by CaitlynMainer** [comment]
"Edit: also, that log isn't something that would lead to a disconnect, is there anything else before / during the disconnect?"  No that is the only thing printed when the disconnect happens server side.  Nothing is printed client side to the log.   It just drops me the "Internal Server Error" Dirt screen.

Edit:
I was able to get this: http://paste.pc-logix.com/view/20fdf87d  But I get the same exact thing anytime a user disconnects for an unknown reason.

Edit 2: http://michi.pc-logix.com/Minecraft_1.7.10_2015-11-06_16-00-04.png  Is the NBT of the server in question.  there IS a RAID connected to the proper side, with a totally bootable OS install despite the "No bootable medium" error.  If you need to see any other NBT on the block let me know, I won't fix this rack for now.

**Comment by fnuecke** [comment]
Yeah, that log is just client connections dying without saying goodbye properly.

On that screenshot things seem to render correctly tho? The sided-config in the rack is correct? Is there a way you could dump the full NBT of the rack (with the server in it in the broken state) and send it to me (and can I load it without manipulating the NBT of the region files) using whatever that is you're using to view it?

**Comment by CaitlynMainer** [comment]
The servers not rendering only happens right after the disconnect, if I reconnect they render fine, same for if I remove them and replace them.  I don't think I can dump the NBT with the nbtedit mod I'm using...  If you'd like I can whitelist you and give you our server pack so you can investigate in game?

**Comment by fnuecke** [comment]
If it's still sitting there, sure. I'll probably have some time this weekend, will let you know on IRC.
