### ISSUE TITLE
nanomachines not responding correctly to input commands

### ISSUE THREAD

**Issue by Rosethorns** [MightyPirates/OpenComputers#1514]
sometimes for unknown reasons nanomachines will stop responding properly to commands.

for example.

the player has index 13 enabled (speed) and the command worked correctly to enable it.

But then the player wants to disable it so they input

=component.modem.broadcast(1, "nanomachines", "setInput" 13, false)
The console returns "True"

But the effect is not removed.

They wait maybe 30 minutes or log out and back in, and try the command again.

It works properly and removes the effect.

**Comment by Vexatos** [comment]
nanomachines take roughly 0.5 seconds to process a command. Any message sent during that period may be lost.

**Comment by Rosethorns** [comment]
I don't think you understand, this is a period of silence and only one incoming command. It is the only thing the nanos could possibly be waiting on or processing

**Comment by MyNameIsKodos** [comment]
Also keep in mind the range on nanomachines' broadcasts are super short, so you're best off using a tablet for interacting with nanomachines.

**Comment by Rosethorns** [comment]
Yes, this has been found using a tablet :P I wouldn't bother reporting it if I wasn't taking these simple things into account

**Comment by sylphio** [comment]
Are you in the overworld? For some reason, it do no semb to work after a dimension change?

**Comment by Rosethorns** [comment]
Yep overworld

**Comment by Rosethorns** [comment]
I'll take the time to get a video of it for you fnuecke

**Comment by fnuecke** [comment]
Since there was an issue when changing dimension that I just fixed, please give the latest build a try, might have been related, who knows.

**Comment by payonel** [comment]
no repro no update

**Comment by guillaumearm** [comment]
Same issue here, it's weird nanomachines just not responding to my messages : 

```
component.modem.open(1);
event.listen("modem_message", print)
=component.modem.broadcast(1, "nanomachines", "getHealth");
```

Am I doing it wrong ?

Edit: Oups, I've forgotten to setResponsePort
