### ISSUE TITLE
Boot problems

### ISSUE THREAD

**Issue by jhagrid77** [MightyPirates/OpenComputers#1517]
So I have a server, that has a total of 40 components total, I would assume it should be able to handle it, as it has a creative APU, and full tier 3 Component Buses, I have edited the config file so that each allows 80 components. The problem is that when I start up the computer it loads funny, or doesn't want to boot, so I have to get rid of the ones next to the cable and then put them back after it is done loading.

**Comment by magik6k** [comment]
If you have other computers(and their screens) in the same network, you should separate them from it with a relay. If not, more details(Images, gif/video) would be really useful.

**Comment by jhagrid77** [comment]
I would, but sadly I had to reinstall my Ubuntu and I lost it all. It was practically hooked up with Disk Drives, as there was a total of 40 each.

**Comment by fnuecke** [comment]
Without a specific repro case I'll have to assume it was an issue with how you had it set up, not an actual bug.
