### ISSUE TITLE
Server rack slow

### ISSUE THREAD

**Issue by noahmcdo** [MightyPirates/OpenComputers#1519]
When I connect a server in a rack to a network, it is slow AF. the fub

**Comment by LizzyTrickster** [comment]
want to add anything else? like setups, how it's slow. mod versions, etc?

**Comment by noahmcdo** [comment]
Now it wont work at all!

**Comment by noahmcdo** [comment]
We are connecting a server directly to a computer, and not it wont even ping!

**Comment by noahmcdo** [comment]
All we did was disconnect it, and connect it again.

**Comment by noahmcdo** [comment]
You know what now it is!

**Comment by fnuecke** [comment]
Please don't spam so much .-.

I'm assuming you mean the delay introduced by the rack acting as a relay. You can tweak the config to make that faster if you like. In 1.6 this will probably cease to be an issue due to the rack rework.
