### ISSUE TITLE
Server crash with chargers

### ISSUE THREAD

**Issue by Fureniku** [MightyPirates/OpenComputers#1522]
I've found a server crash when using the chargers.

A user was trying to place a row of chargers to quickly charge a swarm of robots he's using. Apparently he'd placed 4 or 5 side-by-side when the server crashed, and it now freezes and crashes again whenever he logs in.
Worth noting they were not connected to any form of power but were touching robots.

Crash report:
http://pastebin.com/6LvBuSPD

Pastebin wouldn't let me post the whole thing, but the last lines were just repeated over and over. Whole file is about 780kb so I can .zip it and upload somewhere if you really need it.

(Also if there's any sort of config quick-fix I can do that'd be useful in the mean time, as that user can't log in now)

**Comment by fnuecke** [comment]
Gah, forgot the hashcode override. Thanks for letting me know. Grab the next dev build (from ci.cil.li).
