### ISSUE TITLE
Add Ability to Check Enchantments on Items

### ISSUE THREAD

**Issue by natedogith1** [MightyPirates/OpenComputers#1523]
It'd be nice (and I assume easy to implement) to be able to check the enchantments on items.

**Comment by Pyeroh** [comment]
Isn't it integrated with the inventory controller upgrade, which allows you to get NBT informations about an item ?

**Comment by natedogith1** [comment]
Do you mean the thing that's disabled by default that let's you read all of the NBT data of an item?

**Comment by Pyeroh** [comment]
Probably... But if a feature exists, even if it's disabled by default, why another item with the same feature should be created ?

**Comment by Kubuxu** [comment]
No, the NBT reading is not the way to go. There should be item converter for that.

(NBT reading was done, it requires inflating the NBT and parsing it and you won't get enchantment but only enchant ID).
