### ISSUE TITLE
Relays add extra latency

### ISSUE THREAD

**Issue by womayhem** [MightyPirates/OpenComputers#1525]
Using Magik6k's Ping application we get 700ms extra latency added for each relay block.  Is this intentional?  If so, can you add a configuration option to change it?  When creating large networks this becomes a big issue.

**Comment by fnuecke** [comment]
It's intentional that there's some delay, yes. You can upgrade the relays (open their inventory, put stuff in slots). 700ms seems extreme, I'm guessing that's because the queue is running full and there's some packets that have to be processed before the ping one goes through.

**Comment by tubs06** [comment]
YOu fucking cunt.

**Comment by tubs06** [comment]
pls scrubscribe

**Comment by womayhem** [comment]
The relay was fully upgraded in fact it was set a lot higher in bandwidth capacity, there was no additional traffic besides the ping.  It was nowhere near full capacity and it's consistently adding a ton of latency.  This really needs to have an option.  Each relay adds 700ms.  Not sure why you closed this issue so early.

**Comment by fnuecke** [comment]
Are you sure those aren't "ingame" milliseconds? Because then it'd be 10 real ms, which sounds more realistic.

**Comment by womayhem** [comment]
Magik6k's ping application is in seconds.  Therefore each ping through a relay is 0.80 seconds, while without a relay it is 0.1 - 0.05.

Here's an example (with a relay):
https://gyazo.com/16fecfa619a5fe1bb220d026a7cffca5

Here's an example (without a relay):
https://gyazo.com/a2b1e7f6da8b332438ffe884dedc36a6

**Comment by womayhem** [comment]
The ping application uses computer.uptime() - start

so if that uses in-game time then I suppose so.

**Comment by Kubuxu** [comment]
Magik6k is rewriting networking currently. Current scheme's performance isn't best which can play role here.

**Comment by fnuecke** [comment]
Did some testing, and the 0.7 I can confirm with a relay that is _not_ upgraded, for computer <-> relay <-> computer. Adding another relay does not add another 0.7s, though. In particular not an upgraded one. That said, fully upgraded relays are still a tad slower than they should be, because of what looks to be a good old off-by-one error, which I'll fix in a moment.
