### ISSUE TITLE
Robot is ignoring NBT data when breaking crops

### ISSUE THREAD

**Issue by NoX-programer** [MightyPirates/OpenComputers#1526]
When robot doing swing on Agricraft crop sticks where grows some seed with growth/gain/strength=a/b/c, it is collecting seed with a/b/c - no problem. But when robot breaking another next crop sticks with same type of seed with growth/gain/strength=x/y/z, it collects that seed as a/b/c by just stacking it with first one. Looks like stacking algorithm is not checking NBT, but just id:meta. In some cases (maybe not only Agricraft crops) this behavior is wrong.

Versions: OpenComputers-MC1.7.10-1.5.19.37, AgriCraft-1.7.10-1.4.3

**Comment by fnuecke** [comment]
Ah, the joys of duplicate (and old) code. Thanks for letting me know!
