### ISSUE TITLE
1.6 Feature request:  Crafting dyed cables

### ISSUE THREAD

**Issue by CaitlynMainer** [MightyPirates/OpenComputers#1529]
As the title suggests, the ability to craft cables with dyes to get a cable that is already dyed.  This would be great for long cables runs of a dyed cable.

**Comment by jhagrid77** [comment]
A few feature requests that go along with this:

1.) When dying monitors they won't disconnect from each other if they are different colors.

2.) Kinda the same with 1, but with the cables (maybe make it toggle-able like shift-right click).
