### ISSUE TITLE
Feature request: Components requiring more than one component 'slot'

### ISSUE THREAD

**Issue by SentientTurtle** [MightyPirates/OpenComputers#1531]
Feature request for letting components require more than 1 component slot. (i.e. the slots provided by CPUs and component busses)

Currently (block) components can be used by any tier computer/server. (Items can still be restricted via inventory slots)
Allowing components to use more than 1 component will allow block-components to be restricted to higher tier computers/servers with sufficient component slots.

Note: This is about the jvm component api, i.e., for addons and mods.

**Comment by XFactHD** [comment]
I doubt this is a good approach for what you want to achieve. I would rather suggest being able to directly restrict this to a certain tier of computer if it is possible to check what tier the connected computer is.

**Comment by MyNameIsKodos** [comment]
I actually like this idea, but would like to expand on it.

Perhaps a 'Component Complexity' system.  This would encourage the user to plan what computers/servers will operate what, and make a proper server infrastructure a viable choice. That way, someone couldn't just pile everything into one server and be done with it.

Naturally, the entire concept of the complexity system should have a config option, so those who don't want it can shut it off.  Not sure how much of a pain that would be though.

**Comment by SentientTurtle** [comment]
@XFactHD 
While just locking components to various tiers of computers would just require looking at the computers' tier. (Likely the CPU's tier, if looking that up is even possible from a callback)
It would still allow dozens of components to be attached to a single computer, whereas limiting the amount of 'complex' components, as Kodos said, will require the user to plan out infrastructure across multiple computers/servers to accomodate many complex components.

@MyNameIsKodos 
I agree, what I described would be a barebones implementation, and a properly designed way of doing component complexity would provide better gameplay.

**Comment by XFactHD** [comment]
Using up more than one "data channel" on the computer doesn't really make sense to me. If you consider the real life example of USB, if you use a controller you can connect more than one component to a single data bus, theoretically even an unlimited amount.
Also, what would you consider as complex components that should use more than one component bus?
PS: I am not completely against the suggestion but I don't really get the sense.

**Comment by SentientTurtle** [comment]
Think of bandwidth, while you can connect several harddrives to a single usb connector, you can't use all of them at the same time.

A 'proper' real world example would be PCIe; Where the CPU provides a maximum amount of lanes(bandwidth), with higher end processors providing more lanes.  And these lanes can be used in various configurations of PCIe cards (ingame, Components), e.g. a CPU providing 16 lanes, which can be used in 4 4-lane cards, or 2 8-lane cards, but the total amount of lanes cannot be more than the CPU provides.

**Comment by XFactHD** [comment]
Ok, makes sense, but as I asked before, which components would you consider complex as of needing more than one component bus?

**Comment by SentientTurtle** [comment]
Mainly things that are either laggy in large numbers, or things that should require more infrastructure to be used in large numbers than a lua script with an extra loop in it.

A vanilla OC example of the former could be the hologram projector. An example of the latter could be Big Reactors, where you can control a large amount of reactors with only a single computer/server.

**Comment by jhagrid77** [comment]
So like RAIDs and Disk Drives would be one of the "complex" (I experience some problems with them in large numbers, but then again I like editing my config file lol). Also since we are talking about "complex components" I think it might be cool to have different RAID levels, just thinking.

**Comment by skyem123** [comment]
From experience, you can't really do much with a Tier 1 CPU anyway... so all this would do is make is harder.

**Comment by payonel** [comment]
the current tier and complexity system we feel is sufficient, thanks for the suggestion
