### ISSUE TITLE
Griefing with robot

### ISSUE THREAD

**Issue by cyber01** [MightyPirates/OpenComputers#1533]
Hello, I have long seen this problem with the help of a robot can steal things from other players, regardless of whether you install a plug-in a private area or not.
The robot can not break the block, but it can "suck" all things from the trunk, which can easily drive (if the house or the player has a hole into which the robot can climb), and pull out all components of the computer. Those. The result is that the robot can not break / put blocks, but the interaction with the units it can carry. The same applies to drones. Whether it is possible or to prohibit the robots to interact with objects until they are entered into a private area? By analogy with the ability to break / set blocks.
As far as I know, at the moment none of the plugin this query can not provide complete protection from robots and drones in terms of theft of resources from the chests, but the ability to break / blocks set within a private area available

**Comment by fnuecke** [comment]
The robots and drones [do an `inventory.isUseableByPlayer` check ](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/component/traits/InventoryWorldControl.scala#L76), _and_ [fire an event to check for permission](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/component/traits/WorldAware.scala#L40), so if both of those aren't handled by the permission system, someone will need to tell me what else I can do in Forge to check for permissions.

**Comment by LemADEC** [comment]
Are you using a fake player or the actual player owning that robot?

**Comment by RuinTD** [comment]
Fake player, it seems.

**Comment by LemADEC** [comment]
Handling private areas requires to use owning players, with the related implication, notably when owner is offline or in another dimension.

**Comment by fnuecke** [comment]
It uses a fake player that by default uses the GUID of the owning player. From my testing and what I've heard this has worked without problems with WorldGuard. The GUID and fake player names can be adjusted in the OC config, so recommend messing with that, too, if it doesn't work.

**Comment by cyber01** [comment]
Unfortunately this only works (!) In WorldGuard, for example GriefPrevention robots can not dig a foreign private, but easily can get the contents of the chests or remove blocks from the IC

**Comment by fnuecke** [comment]
Sounds like an issue with GriefPrevention then though? Because there's no explicit integration for WorldGuard in OC, WG apparently just uses the appropriate (Forge) events (which OC fires) / magic to make it work, while GriefPrevention doesn't?

**Comment by cyber01** [comment]
Perhaps, but it is unfortunately used by WG can not everywhere (with a large number of players and / or privates heavy load on the server). And the port a few thousand privats very hard..

**Comment by LemADEC** [comment]
GriefPrevention allows certain action like right clicking by default (for example JABBA barrels are accessible by default). Try moving to GPP or adjusting your configuration. Make sure you test with Vanilla chests first and bot owner is an actual player, not OP nor Creative.

**Comment by cyber01** [comment]
What is GPP?

**Comment by LemADEC** [comment]
GriefPreventionPlus

**Comment by cyber01** [comment]
Wow, did not know that it exists

**Comment by cyber01** [comment]
Unfortunately with GPP robot also removes easily with a wrench (IC) all units and can easily pick up all the contents of the chest

**Comment by LemADEC** [comment]
but the access itself is fixed?

**Comment by cyber01** [comment]
Which access?

**Comment by LemADEC** [comment]
can the robot access content of the chest, without the wrench?

**Comment by cyber01** [comment]
Yes, robot can access to chest without wrench. With robot.suck() robot gets all the contents of the chest (chest in private)

**Comment by cyber01** [comment]
Unfortunately Replacement GP to GPP (GP+) had no effect

**Comment by Landrash** [comment]
@cyber01 The easiest way would be to contact the folk behind the Grief prevention mod your using and as them how they prefer interaction such as these are handled.
 Solving it from the side of one mod can quickly make things complicated.

I've been a tester for these use cases on a few servers and it's next to impossible for the Admins to prevent all kinds of abuse without restricting use of some items.

**Comment by dangranos** [comment]
You know, you could just put more computers and interconnect them using
networking.

**Comment by fnuecke** [comment]
Yeah, please get in touch with the GP folks. If there's any Forge event I'm not firing yet / firing incorrectly let me know, until then I'll put his on hold as not-my-fault ;-)

**Comment by cyber01** [comment]
GPP uses ForgeRestrictor for extend events

**Comment by cyber01** [comment]
You said that with WG everything is working correctly, and I can learn exactly what version? To check

**Comment by fnuecke** [comment]
I honestly can't remember, it's been too long; IIRC ForgeEssentials ships WorldGuard for its protection stuff, tho, so try with that.

**Comment by sameer** [comment]
Hi, this will be fixed in Thermos B49 (https://github.com/TCPR/Thermos). FakePlayer events will be wrapped from ForgeEventFactory.onPlayerInteract into Bukkit interactions.

**Comment by cyber01** [comment]
@Robotia hmm, but not. I checked on the OC 1.5.22, thermos (48 build and 1492 Forge), GriefPrevention +.
I have included a disregard for private, put in the player's chest private session (which put the stack of diamonds), as well as the next set MFSU (IC2 Exp). Then I shut ignoring privates, creativity and deprived himself of rights than OP lowered their rights to the average player. Then I tried to use suck () on the chest, as well as the use of use () key on the MFSU. As a result, I pulled out all the contents of the chest, and took it MFSU. Therefore, I can say that your patches have not helped :(

**Comment by sameer** [comment]
@cyber01 

>  Hi, this will be fixed in Thermos B49 (https://github.com/TCPR/Thermos). FakePlayer events will be wrapped from ForgeEventFactory.onPlayerInteract into Bukkit interactions.

It **will** be fixed, it is not fixed yet. :wink:

**Comment by cyber01** [comment]
@Robotia It's a pity :(

**Comment by sameer** [comment]
@cyber01 Fixed by https://github.com/TCPR/Thermos/commit/3ca312388a14127cc6e99d734c2767c34084799e so when 49 is released it should be OK. One person on TCPR Discord has tested and confirmed it is working.

**Comment by cyber01** [comment]
@Robotia thanks
