### ISSUE TITLE
Server not working.

### ISSUE THREAD

**Issue by WerySkok** [MightyPirates/OpenComputers#1536]
Use a "forge-1.8-11.14.4.1572-universal" and "OpenComputers-MC1.7.10-1.5.20.38-universal" and "worldedit-forge-mc1.8-6.1".
[fml-server-latest.txt](https://github.com/MightyPirates/OpenComputers/files/40864/fml-server-latest.txt)

**Comment by fnuecke** [comment]
> forge-1.8-11.14.4.1572-universal
> OpenComputers-MC1.7.10-1.5.20.38-universal
> 
> forge-1.8
> OpenComputers-MC1.7.10
> 
> 1.8
> 1.7

Well, yeah. Get the right version of OC ;-)
