### ISSUE TITLE
Idea: Colo(u)r sensor

### ISSUE THREAD

**Issue by MFernflower** [MightyPirates/OpenComputers#1537]
Something like this: http://www.hitechnic.com/cgi-bin/commerce.cgi?preadd=action&key=NCO1038

**Comment by Vexatos** [comment]
Sooo for something like map colour? Because that's the only colour I could think of not depending on resource packs.

**Comment by fnuecke** [comment]
Exactly, no reliable color info on the server besides that. And that's already [covered by the Geolyzer](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/common/event/GeolyzerHandler.scala#L54).
