### ISSUE TITLE
Transposer bug, OpenComputers 1.5.19.37 Gregtech 5.09.11 Bug 

### ISSUE THREAD

**Issue by Rosethorns** [MightyPirates/OpenComputers#1538]
I have filmed the bug please follow the link below to watch the report.
I have filmed this due to it being far easier to show and tell than type.

IMPORTANT: I forgot to mention in the report that this occurs in Multiplayers situations and /not/ single player.

Also I cannot tell from playing where the bug lays here. So I have also brought this to gregtech 5u's attention

https://www.youtube.com/watch?v=bBwgMiFx4hs

**Comment by fnuecke** [comment]
Odd, will have a look when I can (probably over the weekend).
Out of curiosity, what happens when you don't specify the source and sink slots?

**Comment by Rosethorns** [comment]
This is a GT issue.

"The check for it being the right item fails. You need the add in the fluid in the recipe first for it to work. That is a function to prevent insertion of items that are not part of the same recipe. I could not find a way to match the two items first and the fluid last so far."

I'm not entirely sure what the purpose in such a restriction is when manual insertion is still possible but what ever thats Asps prerogative.
