### ISSUE TITLE
OC 1.5.20.38 - Bug Or Feature? - Dye is not used up when dying a case or monitor.

### ISSUE THREAD

**Issue by MFernflower** [MightyPirates/OpenComputers#1541]
![Because I did not have a body message](https://cloud.githubusercontent.com/assets/3164942/11464096/f80c8892-96f8-11e5-9856-ddb79877af8b.png)

**Comment by fnuecke** [comment]
Feature, the reasoning being that the color is not retained when the block is broken.
For cables this will probably change in 1.6 if #1529 makes it in.
