### ISSUE TITLE
3 GregTech Recipes broken

### ISSUE THREAD

**Issue by JasonMcRay** [MightyPirates/OpenComputers#1542]
IC2 sometime ago updated with little change, where when you craft reactor items (Vents and Platings) they come with meta :1 Unfortunately gregtech.recipes script asks for these reactor items without metadata making the items not craftable in latest versions of GT and IC2.

Affected items are Computer Case (Tier2 and Tier3) and Server Rack.

```
case2 {
  input: [[screwStainlessSteel , "oc:materialCircuitBoardPrinted", craftingToolWrench]
          ["ic2.reactorVentGold", "oc:case1", "ic2.reactorVentGold"]
          [screwStainlessSteel, "oc:circuitChip2", craftingToolScrewdriver]]
}
case3 {
  input: [[screwTitanium , "oc:materialCircuitBoardPrinted", craftingToolWrench]
          ["ic2.reactorVentDiamond", "oc:case2", "ic2.reactorVentDiamond"]
          [screwTitanium, "oc:circuitChip3", craftingToolScrewdriver]]
}
serverRack {
  input: [[craftingToolScrewdriver, "oc:wlanCard", craftingToolWrench]
          ["ic2.reactorVentDiamond", chest, "ic2.reactorVentDiamond"]
          ["oc:relay", "oc:materialCircuitBoardPrinted","oc:powerDistributor"]]
}
```

where `"ic2.reactorVentGold"` and `"ic2.reactorVentDiamond"` should be changed to `{item="ic2.reactorVentGold", subID=1}` and `{item="ic2.reactorVentDiamond", subID=1}`

**Comment by fnuecke** [comment]
Thanks!
