### ISSUE TITLE
idea: Reverse power converter (OC internal power ---> RF)

### ISSUE THREAD

**Issue by MFernflower** [MightyPirates/OpenComputers#1543]

**Comment by Techokami** [comment]
Nope. It's been discussed before, the devs don't want to turn OpenComputers into a power converter mod.
If you don't want your computer network to suck up all your RF, engineer a better power distribution setup, or add redundant power generation to offset things :wink:

**Comment by gjgfuj** [comment]
OpenAutomation, my Mod, includes one if you want one anyway.
