### ISSUE TITLE
Monoblock Computers

### ISSUE THREAD

**Issue by DeInfernal** [MightyPirates/OpenComputers#1544]
I suggest to add monoblock PC.
https://www.google.ru/search?newwindow=1&safe=off&biw=1920&bih=949&tbm=isch&sa=1&q=monoblock+apple&oq=monoblock+apple&gs_l=img.3..0i24.3631.5216.0.5347.11.10.1.0.0.0.125.857.9j1.10.0....0...1c.1.64.img..1.10.761.vOVSOEUbDos#imgrc=Ovv0wPnT2NXuPM%3A

It is the same as PC + Monitor block.
It can be edited with Shift+LMB (set new pieces and stuff), through, it comes with graphics card pre-installed. 3 tiers as well.
Can be locked with special tool (after 'lock', can't be Shift-clicked).
Still needs keyboard nearby monitor to write letters, and disc drive nearby to install OpenOS.

From Pros:
- Now you can create even more interesting stuff in one block, like 'no-visible-wires-code-lock'.
- With 'wireless energy' (or, if power consumption setted to 0) becomes almost best block in the game (but tablets are better : P), allowing to do impressive things.

From Cons:
- Should be kinda harder to craft.
- Users may prefer this over the standart Tower+Monitor, just because of compactness. 
  - Possible solution: Make less slots to install stuff (like, pay perfomance for compactness)

**Comment by gjgfuj** [comment]
the number of times this has been discussed are MADDENING. the answer is
no, every time.

**Comment by Vexatos** [comment]
Short answer: This is not how OC works/is designed.
Long answer: #936 and various others, I guess.

**Comment by magik6k** [comment]
This actually gave me an idea: How about flat screens, like 1/2 or 1/4 of block(up to T2, no T3). It would save some space and would allow for more compact builds while not introducing magic blocks.

**Comment by dgelessus** [comment]
What would you do with the space though if it's not a full block? Sure, you could put cables behind them, but screens already function as cables, like any other OC block...

**Comment by gjgfuj** [comment]
You could put... Other oc stuff behind them? Or a wall? Or anything so you
can't see it from the other side.

**Comment by dgelessus** [comment]
My point was that there is no other OC stuff that I can think of (except cables, which are not necessary here) that could fit behind a flat screen. Integrating it into a wall with microblocks is one use case though I suppose.

**Comment by gjgfuj** [comment]
You could fit... A computer case? A... Anything? Especially if the screen
still carried component logic.

**Comment by dgelessus** [comment]
Those are full blocks though. If the flat screen were a FMP part (like AE2's various screen things) you could only place it together with other FMP parts that leave enough space.

**Comment by gjgfuj** [comment]
What /I/ mean by flat screen is a screen that takes up like a 5th of a
block. I.e. one that juts out from walls, but doesnt take up a full block.

**Comment by fnuecke** [comment]
Say no to omniblocks! Seriously though, nah. As for the derailing other suggestion, flat screens: for those to work like you imagine those'd have to be explicitly FMP, or I'd have to write my own multi-part system, neither of which options I really like.
