### ISSUE TITLE
Option: Bilinear scaling applied only when the screen is scaled down, not up

### ISSUE THREAD

**Issue by asiekierka** [MightyPirates/OpenComputers#1548]
From IRC

**Comment by Kubuxu** [comment]
It probably is here: https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/client/renderer/font/DynamicFontRenderer.scala#L98

GL_LINEAR here would probably make it better. Mipmapping and GL_LINEAR_MIPMAP_LINEAR would probably be overkill.

Also in other place there is: `if (Settings.get.textLinearFiltering)`
