### ISSUE TITLE
Play Floppy Drives

### ISSUE THREAD

**Issue by OmegaHaxors** [MightyPirates/OpenComputers#1549]
Simple: A command similar to computer.beep which allows floppy drives to spin up at different frequencies.

Tl;DR This https://youtu.be/yHJOz_y9rZE but for OpenComputers.

**Comment by SaphireLattice** [comment]
Use computronics tape drives.

**Comment by fnuecke** [comment]
As this would only have the purpose of making different noises, nah. As @dangranos, use tape drives for advanced sound generation.
