### ISSUE TITLE
Holographic Projector Rendering Issue

### ISSUE THREAD

**Issue by awsmazinggenius** [MightyPirates/OpenComputers#155]
I've encountered a rendering issue with the Holographic Projector. The projector is connected to the computer via a Cable on it's bottom side. The issue basically involves only part of the projector rendering when any full, opaque block (like dirt or stone, **not** anything that does not take up a full block, like an enchanting table, torch, or something else) is above the projector. This [imgur album](http://imgur.com/a/i2K8a) shows the issue with various blocks.

**Comment by fnuecke** [comment]
Oh, it probably thinks it's solid on top. Should be easy to fix. Thanks for reporting!
