### ISSUE TITLE
Request: Disable Nanomachine Particles

### ISSUE THREAD

**Issue by Stalkstalks** [MightyPirates/OpenComputers#1550]
Hey, I was just trying OC out as an alternative to ComputerCraft, and taking a look at your distinguishing features.

The nanomachine system is pretty interesting, though I do wish it was a bit more customizable.

I play with someone who has a system that can barely handle multi-mod environments. We'd like to keep particles on his system to a minimum. Would it be possible to add config options to disable the "particle" effects on nanomachine systems, as well as the default particles that spawn from anyone who has consumed nanomachines?

**Comment by mpmxyz** [comment]
Did you already try the minecraft option to disable particles or does OC not react?

**Comment by Stalkstalks** [comment]
They can be disabled if all particles are disabled, but I'd like to be able to disable them specifically so that particles from other mods that are more gameplay-relevant can be left on. (The portal particles spawned by nanomachines are at best a vague measure of how much energy is left in someone else's nanomachine system, and the particles spawned by the nanomachine neural networks are pretty much just for show other than being "dead" effects for a given input.)

**Comment by fnuecke** [comment]
Ehh, I guess a client-side setting can be added.
