### ISSUE TITLE
Crash with Forestry 4.2

### ISSUE THREAD

**Issue by mezz** [MightyPirates/OpenComputers#1551]
Hello,
There seems to be an error with OC's integration with the Forestry's Analyzer. There may be other problems too, some internals were shifted around this version.
Here's the original report: https://github.com/ForestryMC/ForestryMC/issues/997

**Comment by fnuecke** [comment]
Hrm, what he posted in there doesn't say which OC version was used.

@adamsonich, were you on OC 1.5.20? Because that should be compatible with Forestry 4.x. If you were on 1.5.20, let me know, if not, update please!

**Comment by exmex** [comment]
Using Forestry 4.2 myself with OC 1.5.20.38. No problems whatsoever.

**Comment by fnuecke** [comment]
Assuming outdated OC version then.
