### ISSUE TITLE
Documentation errors in components

### ISSUE THREAD

**Issue by Pwootage** [MightyPirates/OpenComputers#1553]
I've been working on a [javascript architecture](https://github.com/Pwootage/oc-js), and as part of that I have been writing typescript interfaces for the various components in OC. While doing this, I have come across at least one documentation error, and thus created this issue to keep track of them as I come across them.
### EEPROM
- getSize():string -> getSize():number

**Comment by fnuecke** [comment]
Oh, you mean on the wiki? Mind creating an account and fixing whatever errors you find yourself? :3

**Comment by Pwootage** [comment]
Sure, I'll fix the wiki. It's also wrong in the `@Callback` annotation (which is probably why the wiki is wrong).

[EEPROM.scala](http://git.io/v0XDL)

``` scala
  @Callback(direct = true, doc = """function():string -- Get the storage capacity of this EEPROM.""")
  def getSize(context: Context, args: Arguments): Array[AnyRef] = result(Settings.get.eepromSize)
```
