### ISSUE TITLE
Lua derps when trying to file.flush

### ISSUE THREAD

**Issue by sctjkc01** [MightyPirates/OpenComputers#1554]
Starting from a fresh `lua` session...

```
lua> plog = io.open("player.log", "w")
lua> =plog
{bufferMode="full",
 bufferRead="",
 bufferSize=8192,
 bufferWrite="",
 mode={w=true},
 readTimeout=math.huge,
 stream={fs={address="<insert valid disk addy here>",
   close=function(handle:numb...
...
lua> plog.write("herpaderp")
lua> plog.flush()
/lib/buffer.lua:36: attempt to index local 'self' (a nil value)
stack traceback:
         machine:743: in function '__index'
         /lib/buffer.lua:36: in function 'flush'
         stdin:1: in main chunk
         [C]: in function 'xpcall'
         machine:738: in function 'xpcall'
         /bin/lua.lua:131: in main chunk
         (...tail calls...)
```

`lua` was called from the `/usr` directory, on a Creative Server with the following components:
EEPROM with the Lua BIOS
- Internet Card
- Graphics Card
- Debug Card
- Creative APU
- 3x Component Bus T3
- 4x Memory T3.5
- 2x HDD T3

One of the Hard Drives has the contents of OpenOS on it, and the other is configured to auto-mount to `/usr/strg`.

Mod List:
- AE2 RV2 Stable 10
- AsieLib 0.4.5
- CodeChickenCore 1.0.7.47
- CoFHCore 3.0.3-303
- Computronics 1.6.0
- InventoryTweaks 1.59-dev-152
- NEI 1.0.5.118
- OpenComputers 1.5.20.38
- Waila 1.5.10

**Comment by sctjkc01** [comment]
...guess who's a dummy?

**Comment by Techokami** [comment]
Please tell us what you did wrong, in case someone else makes the same mistake! :smiley:

**Comment by makkarpov** [comment]
Used `plog.write` instead of `plog:write`

**Comment by Playermet** [comment]
Not only `plog.write`, but also `plog.flush`.

**Comment by dgelessus** [comment]
I think you mean `plog:flush()` instead of `plog.flush()`. If you write `plog.flush()` the implicit `self` parameter of `flush` is `nil` and you get an error.
