### ISSUE TITLE
[Suggestion] CCTV

### ISSUE THREAD

**Issue by ReTeYeZ** [MightyPirates/OpenComputers#1555]
I'm looking for a CCTV mod for quite a while now but the ones I found found where cancelled
(it's cursed) or for old versions. I think it would fit perfect in this mod, thats why I made the suggestion here.

Not sure how to handle the monitors but it would probably be the best to add extra monitors only for the cameras.

I'm aware that this is quite a big suggestion/challenge and I only wanted to get this out here. Maybe something for the future when there's nothing else to do.

**Comment by fnuecke** [comment]
SecurityCraft has cameras since a few updates back I'm pretty sure?

**Comment by ReTeYeZ** [comment]
Wow thanks for the hint. Those models are great. Though it'd be nice if they can somehow work as a peripheral. I'll ask in the SC thread what he thinks about this.

**Comment by fnuecke** [comment]
Sure, though I'm not sure how useful they could be as components/peripherals - it'd be very unlikely you'd be able to get actual image data, since that's only present on the client; the closest thing there would be Computronics' cameras.
