### ISSUE TITLE
OpenOS Piping between processes only functions if process uses io.write, not io.stdout:write

### ISSUE THREAD

**Issue by Aerolivier** [MightyPirates/OpenComputers#1557]
When piping the output of a process to the input of another, `io.write` seems to work fine.

However, when the process in question outputs using `io.stdout:write` (such as in `print`), the process doesn't receive the output.

I have attached two simple programs that can quickly demonstrate what I mean.
One is called 'luaeval' and it simply executes the Lua code passed as an argument.
The other is called 'tee' and is aiming to replicate the behaviour of 'tee' seen on UNIX OSes, i.e. copies data from stdin to stdout and file(s).

Running the following command lines with those programs available on the PATH demonstrates the issue:

`luaeval "io.write('This will be piped properly.\n') io.flush()" | tee -f test1.txt`

`luaeval "io.stdout:write('This will not be piped properly.\n') io.stdout:flush()" | tee -f test2.txt`

`luaeval "print('This will not be piped properly either.')" | tee -f test3.txt`

test1.txt will contain the text, but test2.txt and test3.txt will not.
(print seems to use io.stdout:write under the hood, so the 3rd one is no surprise if the 2nd one does not work either).

I'm using OpenOS 1.5 from OpenComputers OpenComputers-MC1.7.10-1.5.20.38-universal.jar and I updated OpenOS after installing this version using the install script.

[luaeval_and_tee.zip](https://github.com/MightyPirates/OpenComputers/files/60608/luaeval_and_tee.zip)

Thank you in advance.

**Comment by fnuecke** [comment]
@payonel is working on improving and rewriting a good portion of OpenOS, he might either have already (accidentally?) fixed this. If not, @payonel mind having a look into it?

**Comment by payonel** [comment]
Piping is definitely something that is important to me and I get really excited when other members look for (expect?) *nix like behavior from OpenOS! This particular io issue should be working in my bash-dev branch (not on github) of openos, but I'll add in your two sample programs as part of my unit tests as added quality assurance. I'll return and report after testing.

Also, @Aerolivier, although I did not plan to include /bin/tee in the next OpenOS update, if I were to include tee, would you mind if I used any part of your attach source files? I haven't reviewed the code but I may use it as a starting point. OpenOS will have a few more gnuutils niceties in /bin, such as head, grep, and find. There might be room for tee :). (no promises!)

**Comment by payonel** [comment]
I've added a test case with your code and confirmed this is fixed for 1.6. io.write(), io.stdout:write(), print(), and term.write() all write to the same stream - even in the middle of process piping.

**Comment by Aerolivier** [comment]
Absolutely, feel free to take tee and include it!

Thanks for your response.

**Comment by payonel** [comment]
@fnuecke this can be closed now
