### ISSUE TITLE
[MC 1.8] OC crashing with latest Waila

### ISSUE THREAD

**Issue by GirafiStudios** [MightyPirates/OpenComputers#1559]
OpenComputers is crashing with latest version of Waila (1.6.0-B2_1.8) for 1.8 due to Waila API changes.

Crashlog: https://gist.github.com/GirafiStudios/dd7ab215c7a32da8da72

**Comment by fnuecke** [comment]
Thanks for the heads-up, I'll look into it.

**Comment by oddstr13** [comment]
Additional crashlog with more verbosity; https://paste.ee/p/lCG3U

Also see related bug report on Waila tracker; https://bitbucket.org/ProfMobius/waila/issues/233/crash-at-lodding-18 Not much information, other than mention of API changes

**Comment by fnuecke** [comment]
As a temporary workaround, add `Waila` to the `integration.modBlacklist` in the OC config.
