### ISSUE TITLE
1.6 Feature request, ability to use computers in unison on same monitor(s)

### ISSUE THREAD

**Issue by jhagrid77** [MightyPirates/OpenComputers#1564]
As the title says, could this be possible, as in made?
Most people would say to use a server, but think about playing in survival, some people might find it hard to make a server and all the components, but they might be able to make lots of say tier 1 computers and components. I just think it would be cool to have multiple computers working together.

**Comment by fnuecke** [comment]
What do you mean by "working together"?

**Comment by jhagrid77** [comment]
Like say putting them next to each other around a monitor (or connected by cables), instead of each input being on the same monitor they all take commands from that one AND they kinda work like a server. I wouldn't mind the same being done on servers too.

**Comment by fnuecke** [comment]
I still don't understand what you want that isn't possible with some Lua coding already?

**Comment by jhagrid77** [comment]
Oh, see I haven't started any coding, so I just use basic or pre-built coding I find around here, so I don't understand whats possible, whats not and how to do something.

**Comment by fnuecke** [comment]
I'll assume this is possible already then, for now ;)
