### ISSUE TITLE
1.6 Feature request, ability to "rent out" servers and computers.

### ISSUE THREAD

**Issue by jhagrid77** [MightyPirates/OpenComputers#1565]
I think this might be cool, I mean think about it say every week (configurable) the person renting enters an object into a special "component slot" and it will go to the owner's chest. The person renting could go anywhere in the world and using a RT can use it (instead of the so many blocks and it cuts off) or enter a special floppy/hard drive that they make from the renting server/computer. Configurable or not, I just want to put my idea out there.

**Comment by makkarpov** [comment]
Out of scope of this mod, I think

**Comment by magik6k** [comment]
This is doable just fine now. I in plan9k for 1.6 I have fully functional, secure ssh program. We(starchasers) have also developed cryptocurrency(starkoin) which allows automatic payments and trading station upgrade for robots. Rest is all about creative automation and/or role-play.

**Comment by fnuecke** [comment]
I agree, I don't think there needs to be anything additional in OC to support this what isn't there already, or other mods could provide, given a bit of creativity.
