### ISSUE TITLE
[Suggestion] Rendering Websites?

### ISSUE THREAD

**Issue by mura3277** [MightyPirates/OpenComputers#1566]
Would it be possible to support rendering live websites on the monitors? I know this is a pretty big suggestion and I'm not sure if it's even possible, but I thought I'd throw the question out there.

Thanks.

**Comment by magik6k** [comment]
If you write such parser/renderer, then why not. Lynx like thinger shouldn't be actually super hard.

**Comment by jhagrid77** [comment]
I think this would be kinda cool, but think of putting it on an OS with a GUI and you could open say this forum and the wiki, sure some people might say just open it up on your computer, but what if you don't want to take the time of going through everything. Another thing could be that if you use say: "man tier 3" it would show pages from the forum and wiki about it. I'm just thinking.

**Comment by mura3277** [comment]
It could also be a collaboration thing too. What I would be doing if this was a thing would be playing youtube videos (very hopeful I know) or keeping a google sheet open on the monitor on a server.

@magik6k I don't have the programming knowledge to actually do this, but I was simply just throwing the question in here for people to comment on.

**Comment by fnuecke** [comment]
If you mean something like a text-based browser, doable like @magik6k said, and if someone does it I wouldn't mind that being on a loot disk. If you mean something more like an actual browser (and if you say youtube videos I must assume you do), that'd have to be done completely client side, at which point it doesn't have anything to do with OC anymore (there's a mod for that using awesomium IIRC).
