### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1567]
It seems to be unable to find:
ProjectRed
NotEnoughKeys
ResonantEngine
when I try to build according to the github readme instructions

**Comment by jhagrid77** [comment]
Is this when trying to play or when trying to start the "launcher"?
Either way I would try to make sure you have the latest versions for the MC your trying to play and then report what you find.

**Comment by Kubuxu** [comment]
It is probably problem with dependences that moved. Regular devs do not have problem with that as they have dependencies cached.

**Comment by Inari-Whitebear** [comment]
@Kubuxu: it is, hence I'm saying it needs to be updated :D

@jhagrid77 Its when updating the gradle project (and thus failing to compile)

**Comment by jhagrid77** [comment]
@Inari-Whitebear Ahh, I didn't know what you meant by "build" as I build things, not scripts, btw OC uses Python right?.... Might have to start...

**Comment by Inari-Whitebear** [comment]
Uh, OC uses Scala and Java. And the scripts in Lua xD

**Comment by jhagrid77** [comment]
Lua isn't a scripting language is it?....

**Comment by Inari-Whitebear** [comment]
It is

**Comment by jhagrid77** [comment]
Could you recommend me any good ways to practice and learn Lua?

**Comment by Kubuxu** [comment]
This isn't place for discussion like that. Please join #oc on EsperNet or the OC Forum.

**Comment by Inari-Whitebear** [comment]
Seemed fine in 1.6 btw :P Either stuff got fixed (I think buildscript changed too) or it cached them now for me

**Comment by fnuecke** [comment]
Or the hosting Maven is back up. Good to hear. There's also this issue #1412, so I'll be closing this one.
