### ISSUE TITLE
1.6 Feature Request, (maybe) OC Map (Read for information)

### ISSUE THREAD

**Issue by jhagrid77** [MightyPirates/OpenComputers#1568]
I think it would be cool, that when you download OC there is a map that helps you learn old and new things about OC, and it could include a nice base for a Data Center (big or small) and maybe a secret one already built. It would be pretty cool to me, what do you guys/gals think?

**Comment by SaphireLattice** [comment]
You mean an infographic about features of OC? GLHF finding an artist.

**Comment by SaphireLattice** [comment]
Nevermind that, bad idea to answer issues half-asleep. I guess you could
make a map and post it on forums. Maps are too heavy to include in mod btw.
And i think it's more of 'user created' content type.

**Comment by jhagrid77** [comment]
I didn't mean like right in the mod, I mean like make a zip and have one folder for mods and one for maps. Although I could ask around and see if people could create a map for it.

**Comment by fnuecke** [comment]
The forums or IRC would be a better place to discuss this.
