### ISSUE TITLE
Can only access first server's contents via right clicking front face

### ISSUE THREAD

**Issue by MyNameIsKodos** [MightyPirates/OpenComputers#1571]
Using build 815 from the jenkins, only a server in the first slot of a rack has its contents accessible via right clicking the front face of the rack, all other slots require you to remove the blade and access it via right clicking, as was the case prior to 1.6

**Comment by fnuecke** [comment]
Odd. Will test over the weekend; are you sure it's not just somewhat inaccurate hit detection?

**Comment by magik6k** [comment]
I have the same issue, I may look into it today.

**Comment by fnuecke** [comment]
Great, thanks!
