### ISSUE TITLE
Computer + Command Block = Exception in console

### ISSUE THREAD

**Issue by cyber01** [MightyPirates/OpenComputers#1575]
Hello, I am using computers from opencomputers together with command units. When the command (lika a /tell <username> <text>) in the command blocks by the computer it is running, but the console will receive the following: 
http://pastebin.com/wBg0nuei
or
http://pastebin.com/WBu4er0d

**Comment by fnuecke** [comment]
Thanks. This happens when command blocks are disabled in your server config (`enable-command-block` in `server.properties`). I'll make this error more gracefully (return `nil, message` from the callback instead, will avoid logspam).
