### ISSUE TITLE
wrong material cost in the tooltip when using gregtech.recipes

### ISSUE THREAD

**Issue by Zer0id** [MightyPirates/OpenComputers#1579]
wrong material cost in the tooltip when using gregtech.recipes

![2015-12-22_13 03 30](https://cloud.githubusercontent.com/assets/14043791/11953948/5ab30dae-a8b5-11e5-9eaa-97c96a9d74bc.jpg)

**Comment by Kubuxu** [comment]
This Floppy is quite pricey I would say. :smiley:

**Comment by MyNameIsKodos** [comment]
I dunno, it's Gregtech. That may be an accurate list of required materials.

**Comment by fnuecke** [comment]
Yeah, no big surprise there. The built-in cost computation is rather basic, so it doesn't take into account tools (i.e. ingredients that get _partially_ used up / take damage), and it doesn't know about most advanced machine recipes. I had a separate mod in the works that fleshed this feature out a bit, but got stuck several times on various issues (it's an annoyingly complex problem to solve efficiently). So yeah. Just ignore this.
