### ISSUE TITLE
[Suggestion] Redstone I/O facing indicator

### ISSUE THREAD

**Issue by exmex** [MightyPirates/OpenComputers#1581]
Can we please have an indicator for the Redstone I/O (if there are more direction specfic them too?)

It's really hard to know what side to output a redstone or bundled cabling if you placed the redstone I/O block. I know it's the same direction method as the computer, but where is the front on the redstone I/O? (All sides are the same...)

**Comment by makkarpov** [comment]
Redstone IO block has no front side, all sides are indexed absolutely (`sides.up`/`down`/`west`/... or `sides.negx`/`posy`/`negz`)

**Comment by exmex** [comment]
What..? lol.. That's.. new to me? But.. Thanks xD. I've always used sides.front, sides.left, sides.right...
