### ISSUE TITLE
AE2 Feature Request: Crafting Access

### ISSUE THREAD

**Issue by MyrddinE** [MightyPirates/OpenComputers#1583]
I'd like to be able to iterate through the available recipes that are installed (with input and output arrays of itemid:dam) into interfaces in an ME system and initiate crafting requests on those recipes.

Nice to have, but not core to the request, would be the ability to differentiate between normal and machine based recipes, control the CPU a request is executed on, and check the status of existing crafting requests on the CPUs.

**Comment by fnuecke** [comment]
Getting the list of craftables and submitting requests is already possible; use an adapter next to a controller or interface, either inspect the component ingame or refer to [the code](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/integration/appeng/NetworkControl.scala). Getting a list of CPUs (but not what _exactly_ they're doing right now) is also possible, as is the list of stored items in the system.
