### ISSUE TITLE
Weird Client "lag"

### ISSUE THREAD

**Issue by exmex** [MightyPirates/OpenComputers#1584]
http://www.minecraftforge.net/forum/index.php/topic,35671.msg187783.html#msg187783

(MC 1.7.10)
I narrowed it down to openComputers. I installed the direwolf20 pack, and removed some mods from it, and added only openComputers.

(Purple is removed)
![](http://i.imgur.com/cjShNKq.png)
![](http://i.imgur.com/yX0glWK.png)

**Comment by fnuecke** [comment]
Hmm, never seen this before, nor heard of it. Does this also happen if OC is the only mod present? If it doesn't, add mods back bit by bit to figure out in combination with which other mod this might happen.

**Comment by Kubuxu** [comment]
Reading the forum it might be overload problem. If you saw that OC was causing problem keep removing other mods. It might turn out that no mod is responsible just combination of them or just raw count of them.

**Comment by exmex** [comment]
Hmm I didn't tested OC alone. Man.. That sucks XD. I have to do that with 120 mods.. fine! I'll report back.

**Comment by LordFokas** [comment]
With a binary search you should be able to test 120 mods in 7 steps :)

**Comment by fnuecke** [comment]
Will assume it's been one of the above alternatives, not strictly speaking OC on its own. If you find out it is after all, lemme know.
