### ISSUE TITLE
Modulo (division remainder) causes syntax error

### ISSUE THREAD

**Issue by Holi0317** [MightyPirates/OpenComputers#1585]
According to [Lua 5.1 reference](http://www.lua.org/manual/5.1/manual.html), section 2.5.1, modulo is supported.

Under lua 5.3.2 in real computer, using modulo causes the following output

```
Lua 5.3.2  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> = 5%10
5
> 3%9
3
> 
```

However, when environment changes to OpenComputers, the output is unexpected.

![2015-12-29-15 40 36-screenshot](https://cloud.githubusercontent.com/assets/6838982/12031066/9e2d8cac-ae42-11e5-8749-932aa5e4edcb.png)

**Comment by fnuecke** [comment]
You have a stray space before your `=5%10` there. All the other other erroring ones are to be expected because they're missing a `=` or `return` in front, hence are illegal Lua.
