### ISSUE TITLE
TIS Manual shows OpenComputers manual pages

### ISSUE THREAD

**Issue by feldim2425** [MightyPirates/OpenComputers#1588]
If I open the TIS-3D Manual it shows the main page from the OC Manua
![2015-12-29_21 04 01](https://cloud.githubusercontent.com/assets/6705744/12041236/c9335ad0-ae6f-11e5-8342-eb7372f18052.png)

EDIT: If I press the Home button, it will also show the OC manual page

**Comment by fnuecke** [comment]
~~Gah, the issue of re-using code :X Will fix in TIS-3D.~~ Nevermind, can fix in OC.
