### ISSUE TITLE
Log spam with AE2 controller and tables

### ISSUE THREAD

**Issue by XFactHD** [MightyPirates/OpenComputers#1589]
After adding the following code (http://pastebin.com/D3gKJVeT) to my Base Control Program (http://pastebin.com/RrgJFXUz) and then restarting the game (SSP), the log got spammed with "[21:35:38] [Server thread/WARN] [OpenComputers]: Type converter threw an exception.
java.lang.NullPointerException" every 10 ticks. I didn't shut the OC computer down before saving the world.
MC version: 1.7.10
OC version: MC1.7.10-1.5.20.38
Screenshot:
![2015-12-29_22 11 21](https://cloud.githubusercontent.com/assets/11262040/12042232/376e968c-ae79-11e5-8a3f-5582e2542ac2.png)

**Comment by fnuecke** [comment]
Is there a stacktrace in that log message?

**Comment by XFactHD** [comment]
No, that's the problem. Neither the console of the launcher nor the fml-client-latest.log contains any stacktraces. But when looking at the code that throws this error, I don't see how it should even print a stacktrace.

**Comment by fnuecke** [comment]
Darn. What AE2 version?

**Comment by XFactHD** [comment]
rv2 stable 10

**Comment by XFactHD** [comment]
This time the log also contained a stacktrace: http://pastebin.com/QxMjY1yG. The ME system contained an empty "Safari Net (Single Use)" from MFR. After taking it out, OC stopped spamming the log.

**Comment by XFactHD** [comment]
Awesome, do you have a publicly available dev build I can use to test the fix?

**Comment by fnuecke** [comment]
http://ci.cil.li/

Just beware that the 1.6 build has the new server racks, so if you use racks anywhere, those will stop working until reconfigured (shouldn't lose their contents/servers tho).

I'll cherry-pick it into the 1.5 branches later.

**Comment by XFactHD** [comment]
That's a problem. Because of the component limit of computer cases I need to use a server for the task. I am going to wait until you cherry-picked the fix.

**Comment by skyem123** [comment]
Wait... @fnuecke... server racks don't automatically migrate? D:
