### ISSUE TITLE
[Request] What about printing doors in 3D Printer?

### ISSUE THREAD

**Issue by miuirussia** [MightyPirates/OpenComputers#1592]
Please, add this feature. Maybe it will be useful. Or make more redstone control parameters (Direction as example, and if direction selected, don't block redstone control)

**Comment by Techokami** [comment]
3D prints exist in a single, 1x1x1 block space. You could look at how the trapdoors are made, and create a pair of half-doors? Or get Malisis' Doors and use its custom door tools.

**Comment by gjgfuj** [comment]
It's fairly easy to make one. You just print two half-doors, and you can
use redstone signal trickery to make both open at once.

**Comment by fnuecke** [comment]
Indeed. There'll be a tiny delay between the first and second one, but hey. I'm pretty sure @Vexatos even had a gfy of exactly such a setup sometime...
