### ISSUE TITLE
[Feature Request] Rack-Mountable Adapter/Upgrades

### ISSUE THREAD

**Issue by MyNameIsKodos** [MightyPirates/OpenComputers#1594]
As per IRC:

> [04:03] Kodos: Also
> [04:03] Kodos: A rack mountable adapter (For upgrade use) would be amazeballs
> [04:04] Sangar: hrm. maybe built from upgrade containers specifically.
> [04:04] Sangar: make an issue as a reminder

This could be useful for things like tank/inventory controllers, as well as upgrades like the chat upgrade from Computronics, allowing use of a chatbox without needing an extra block tacked on.  Maybe even a rack-mounted Geolyzer for keeping track of the mining progress of a robot, or to possibly send a robot to specific coordinates based on reported block hardness.

**Comment by jhagrid77** [comment]
I like this, but I think that since lots of new upgrades are coming for the servers, I think we should get a larger server rack, or like monitors they expand.

**Comment by MyNameIsKodos** [comment]
Larger server racks, if they happen at all, will be later down the road. Given how BTM went, I look forward to seeing what's in store in the near future.

**Comment by jhagrid77** [comment]
Yes I agree.

**Comment by LizzyTrickster** [comment]
For merging / larger server racks: see @fnuecke's comment here https://github.com/MightyPirates/OpenComputers/issues/1323#issuecomment-124570070
