### ISSUE TITLE
Crash when trying to open OpenComputers inventory in creative.

### ISSUE THREAD

**Issue by jhagrid77** [MightyPirates/OpenComputers#1596]
When trying to open OpenComputer's inventory in creative (the thing where you can spawn stuff) while having Immbis' core active the game will crash here is my computer details:
Processor: 4x Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz
Memory: 3993MB (3170MB used)
Operating System: Ubuntu 14.04.3 LTS

Minecraft details:
MultiMC: 0.4.6
Version: 1.7.10
Forge: 10.13.14.1614
OpenComputers version: 1.6.0839
Immbis' Core version: 59.1.4

Crash log:
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 1/3/16 12:55 AM
Description: Rendering item

java.lang.IncompatibleClassChangeError: Found class mods.immibis.core.api.multipart.IMultipartSystem, but interface was expected
    at mods.immibis.microblocks.coremod.MSTHooks.overrideRenderType(MSTHooks.java:39)
    at li.cil.oc.common.block.Cable.func_149645_b(Cable.scala)
    at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:409)
    at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
    at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:488)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at mods.immibis.microblocks.coremod.MSTHooks.overrideRenderType(MSTHooks.java:39)
    at li.cil.oc.common.block.Cable.func_149645_b(Cable.scala)
    at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:409)

-- Item being rendered --
Details:
    Item Type: li.cil.oc.common.block.Item@693fd112
    Item Aux: 0
    Item NBT: null
    Item Foil: false
Stacktrace:
    at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
    at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:488)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)

-- Screen render details --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
    Mouse location: Scaled: (133, 193). Absolute: (267, 93)
    Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['jhagrid7'/224, l='MpServer', x=-269.79, y=90.62, z=108.45]]
    Chunk stats: MultiplayerChunkCache: 25, 34
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-242,64,111), Chunk: (at 14,4,15 in -16,6; contains blocks -256,0,96 to -241,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 2899 game time, 2899 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 6 total; [EntityClientPlayerMP['jhagrid7'/224, l='MpServer', x=-269.79, y=90.62, z=108.45], EntitySquid['Squid'/162, l='MpServer', x=-231.50, y=53.38, z=69.50], EntitySquid['Squid'/163, l='MpServer', x=-225.72, y=57.38, z=81.13], EntityChicken['Chicken'/134, l='MpServer', x=-261.53, y=81.00, z=118.53], EntityChicken['Chicken'/135, l='MpServer', x=-266.19, y=76.10, z=149.25], EntityItem['item.tile.doublePlant.paeonia'/127, l='MpServer', x=-285.59, y=63.13, z=118.88]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 3.19.0-42-generic
    Java Version: 1.8.0_66, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 757958656 bytes (722 MB) / 1210056704 bytes (1154 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 2 total; -Xms512m -Xmx2048m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_C1 68 mods loaded, 68 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
    UCHIJAAAA   appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   ImmibisMicroblocks{59.0.5} [Immibis's Microblocks](immibis-microblocks-59.0.5.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.3.74} [Not Enough Items](Not-Enough-Items-1.7.10.jar) 
    UCHIJAAAA   OpenComputers|Core{1.6.0.839-dev} [OpenComputers (Core)](minecraft.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   FastCraft{1.22} [FastCraft](fastcraft-1.22-ctest17.jar) 
    UCHIJAAAA   securitycraft{v1.7.4.1} [SecurityCraft]([1.7.10] SecurityCraft v1.7.4.1.jar) 
    UCHIJAAAA   appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCHIJAAAA   ae2ee3emcaddon{1.7.10-b5-universal} [AE2 EE3 EMC Addon](ae2ee3emcaddon-1.7.10-b5-universal.jar) 
    UCHIJAAAA   bdlib{1.9.4.109} [BD Lib](bdlib-1.9.4.109-mc1.7.10.jar) 
    UCHIJAAAA   ae2stuff{0.5.0.56} [AE2 Stuff](ae2stuff-0.5.0.56-mc1.7.10.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCHIJAAAA   BuildCraft|Core{7.1.14} [BuildCraft](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.1.14} [BC Builders](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.1.14} [BC Transport](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.1.14} [BC Energy](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.1.14} [BC Silicon](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.1.14} [BC Robotics](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.1.14} [BC Factory](buildcraft-7.1.14.jar) 
    UCHIJAAAA   ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UCHIJAAAA   ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
    UCHIJAAAA   BuildCraft|Compat{7.1.3} [BuildCraft Compat](buildcraft-compat-7.1.3.jar) 
    UCHIJAAAA   ComputerCraft{1.65} [ComputerCraft](ComputerCraft1.65.jar) 
    UCHIJAAAA   IC2{2.2.810-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.810-experimental.jar) 
    UCHIJAAAA   MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   OpenComputers{1.6.0.839-dev} [OpenComputers](OpenComputers-MC1.7.10-1.6.0.839-dev-universal.jar) 
    UCHIJAAAA   CompactMachines{1.7.10-1.21} [Compact Machines](compactmachines-1.7.10-1.21.jar) 
    UCHIJAAAA   endercore{1.7.10-0.2.0.31_beta} [EnderCore](EnderCore-1.7.10-0.2.0.31_beta.jar) 
    UCHIJAAAA   EnderIO{1.7.10-2.3.0.422_beta} [Ender IO](EnderIO-1.7.10-2.3.0.422_beta.jar) 
    UCHIJAAAA   enderioaddons{0.10.0} [Ender IO Addons](EnderIOAddons-1.7.10-2.3.0.422_beta-0.10.0.042_beta.jar) 
    UCHIJAAAA   eureka{@VERSION@} [Eureka](Eureka-1.7.10-1.0.jar) 
    UCHIJAAAA   extracells{2.3.7} [Extra Cells 2](ExtraCells-1.7.10-2.3.7b176.jar) 
    UCHIJAAAA   advgenerators{0.9.19.120} [Advanced Generators](generators-0.9.19.120-mc1.7.10.jar) 
    UCHIJAAAA   iCraft{0.7} [iCraft](iCraft-0.7.jar) 
    UCHIJAAAA   IGWMod{1.1.11-32} [In-Game wiki Mod](IGW-Mod.jar) 
    UCHIJAAAA   ImmibisCore{59.1.4} [Immibis Core](immibis-core-59.1.4.jar) 
    UCHIJAAAA   intellie{2.1.4.554} [IntelliE](IntelligentEnergistics-1.7.10-2.1.4.554-universal.jar) 
    UCHIJAAAA   appaero{2.1.4.554} [AppliedAerodynamics](IntelligentEnergistics-1.7.10-2.1.4.554-universal.jar) 
    UCHIJAAAA   appaeronei{2.1.4.554} [AppliedAerodynamicsNEI](IntelligentEnergistics-1.7.10-2.1.4.554-universal.jar) 
    UCHIJAAAA   journeymap{5.1.3} [JourneyMap](journeymap-1.7.10-5.1.3-unlimited.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   cfm{3.4.8} [�9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.8%281.7.10%29.jar) 
    UCHIJAAAA   RedstonePasteMod{1.6.2} [Redstone Paste](RedstonePasteMod-1.7.10-1.6.2.jar) 
    UCHIJAAAA   Redstonic{1.4.10} [Redstonic](Redstonic-v1.4.11.jar) 
    UCHIJAAAA   ropebridge{1.1} [Rope Bridge](RopeBridge-v1.2-mc1.7.10.jar) 
    UCHIJAAAA   tis3d{0.8.1.60} [TIS-3D](TIS-3D-MC1.7.10-0.8.1.60.jar) 
    UCHIJAAAA   worldedit{6.0-beta-01} [WorldEdit](worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
    GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 10.5.9' Renderer: 'Mesa DRI Intel(R) Sandybridge Mobile '
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.0.3-303
    ThermalFoundation: -[1.7.10]1.2.0-102
    ThermalExpansion: -[1.7.10]4.0.3B1-218
    MineFactoryReloaded: -[1.7.10]2.8.0-104
    List of loaded APIs: 
        \* appliedenergistics2|API (rv2) from appliedenergistics2-rv2-stable-10.jar
        \* Baubles|API (1.0.1.10) from ThermalFoundation-[1.7.10]1.2.0-102.jar
        \* BuildCraftAPI|blocks (1.0) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|boards (2.0) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|core (2.0) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|crops (1.1) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|events (2.0) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|facades (1.1) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|filler (4.0) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|gates (4.1) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|items (1.1) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|library (2.0) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|lists (1.0) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|power (1.3) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|recipes (3.0) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|statements (1.1) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|tablet (1.0) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|tiles (1.2) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|tools (1.0) from buildcraft-7.1.14.jar
        \* BuildCraftAPI|transport (4.1) from buildcraft-7.1.14.jar
        \* CoFHAPI (1.7.10R1.0.2) from compactmachines-1.7.10-1.21.jar
        \* CoFHAPI|block (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHAPI|core (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHAPI|energy (1.7.10R1.0.2) from compactmachines-1.7.10-1.21.jar
        \* CoFHAPI|fluid (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHAPI|inventory (1.7.10R1.0.1) from buildcraft-compat-7.1.3.jar
        \* CoFHAPI|item (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHAPI|modhelpers (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHAPI|tileentity (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHAPI|transport (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.422_beta.jar
        \* CoFHAPI|world (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|audio (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|gui (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|gui|container (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|gui|element (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|gui|element|listbox (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|gui|slot (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|inventory (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|render (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|render|particle (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|util (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|util|helpers (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|util|position (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|world (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|world|feature (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* ComputerCraft|API (1.65) from ComputerCraft1.65.jar
        \* ComputerCraft|API|FileSystem (1.65) from ComputerCraft1.65.jar
        \* ComputerCraft|API|Lua (1.65) from ComputerCraft1.65.jar
        \* ComputerCraft|API|Media (1.65) from ComputerCraft1.65.jar
        \* ComputerCraft|API|Peripheral (1.65) from ComputerCraft1.65.jar
        \* ComputerCraft|API|Redstone (1.65) from ComputerCraft1.65.jar
        \* ComputerCraft|API|Turtle (1.65) from ComputerCraft1.65.jar
        \* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.3.0.422_beta.jar
        \* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.3.0.422_beta.jar
        \* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.7.10-2.3.0.422_beta.jar
        \* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.3.0.422_beta.jar
        \* IC2API (1.0) from industrialcraft-2-2.2.810-experimental.jar
        \* OpenComputersAPI|Component (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.839-dev-universal.jar
        \* OpenComputersAPI|Core (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.839-dev-universal.jar
        \* OpenComputersAPI|Driver (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.839-dev-universal.jar
        \* OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.839-dev-universal.jar
        \* OpenComputersAPI|Event (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.839-dev-universal.jar
        \* OpenComputersAPI|FileSystem (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.839-dev-universal.jar
        \* OpenComputersAPI|Internal (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.839-dev-universal.jar
        \* OpenComputersAPI|Machine (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.839-dev-universal.jar
        \* OpenComputersAPI|Manual (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.839-dev-universal.jar
        \* OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.839-dev-universal.jar
        \* OpenComputersAPI|Prefab (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.839-dev-universal.jar
        \* tis3dAPI (0.8.1.60) from TIS-3D-MC1.7.10-0.8.1.60.jar
    EnderIO: Found the following problem(s) with your installation:
                  \* Optifine is installed. This is NOT supported.
                  \* The RF API that is being used (1.7.10R1.0.13 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from compactmachines-1.7.10-1.21.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
    AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Launched Version: MultiMC5
    LWJGL: 2.9.1
    OpenGL: Mesa DRI Intel(R) Sandybridge Mobile  GL version 3.0 Mesa 10.5.9, Intel Open Source Technology Center
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by fnuecke** [comment]
Can't reproduce, I'm afraid.

Given it crashes in immibis core code though, and OC only uses the "please inject your stuff" approach to IM integration (i.e. there's nothing I can change, really), consider reporting this to immibis instead, sorry.
