### ISSUE TITLE
[Suggestion] Packet Sniffing Card for Evil and Advanced Networking

### ISSUE THREAD

**Issue by skyem123** [MightyPirates/OpenComputers#1597]
This is an idea that has been running around in my head.

There should be three "types" of packet sniffing:
- Passive: would only work when a the "sniffing" computer is directly connected to a link a packet passes through (e.g. connected to the connection between two switches).
- Active: would get packets from sent to (or sent from) a _single_ network address. Maybe it should also have some other serious limitation...
- Fallback: would get packets that would have been sent to a selection of network addresses which are not on the network.

The first two uses would be an interesting gameplay challenge, along with a reason for people to design secure network protocols! **:D**

The last use would be useful for making a "custom switch" that could be coded manually using computers, so allowing advanced networking! **:D**
This would require the packet sniffing card would also have the ability to spoof addresses, but it would be an interesting challenge if the packet sniffing card and spoofing card were separate (though that might mean that the spoofing card would have to somehow be moved from Computronics to OC, sorry @Vexatos!).

**Comment by Vexatos** [comment]
:cry:

**Comment by skyem123** [comment]
@Vexatos, maybe Computronics would hide it's spoofing card if the OC spoofing card was available, and convert existing cards into new ones?

**Comment by Vexatos** [comment]
Maybe no sniffing at all? :grin: After all, this looks quite... (too) powerful to me...

**Comment by fnuecke** [comment]
If @Vexatos wants to PR the card into OC (say, in MC 1.8 because someone's too lazy to port it for the tape drives and such to 1.8? :P) sure, otherwise I'm not very comfortable with deprecating stuff in (popular and in active development) addon mods.

**Comment by skyem123** [comment]
:P
The thing is that I want to be able to make custom switches that don't need a high-level networking protocol, and I also find it to be an interesting multiplayer gameplay element if people could packet sniff. It might be more realistic if you didn't have the "active" mode, I guess?

**Comment by Vexatos** [comment]
@fnuecke Computronics for 1.8 is definitely planned as soon as there is sufficient code to port (around 70% of the mod cannot be ported due to the mods it interfaces with not being ported).

@skyem123 I do still think it is quite... overpowered. using a rack or MCU as a switch, you can already intercept broadcasts and direct messages should have some sense of security to them, in my opinion.

**Comment by skyem123** [comment]
In the real world, the network is not secure, and the "fallback" mode allows me to make custom switches, which would allow me to make a VPN without needing software on each computer on the network.

**Comment by Vexatos** [comment]
~~In the real world, Computers aren't made of diamonds.~~

Direct messages are "hard to use" in a way that they don't work across custom switches and require you to know the receiver's (and probably sender's) address. I think that's good enough of a trade-off.

**Comment by skyem123** [comment]
The thing is that networking seems too "perfect" as a system, especially in a mod where you have to cope with EEPROMs and boot disks.

**Comment by Vexatos** [comment]
That's what spoofing is for!

**Comment by skyem123** [comment]
Spoofing is useless for me unless you can get the response to the spoofed packet. :P

**Comment by skyem123** [comment]
Would this be more balanced if the "active" snooping didn't exist?

**Comment by magik6k** [comment]
This seems mostly doable with a little trick: grab a pair of linked cards, put one in computer and the other in a relay connected to network. Then using linked card you can send messages as anyone to anyone. To see message structure just  send one from network and see what arrived to the computer.

**Comment by skyem123** [comment]
Interesting...
While that trick is kind of what I want, I do not really like how it requires a trick like that (and is also more expensive than reasonable, as linked cards are meant for cross dimension communication).

Maybe, instead of using custom network cards, it could be done by putting a network switch into a special mode (or a special "advanced" switch) where it can be directly controlled by a computer to do both packet spoofing and packet sniffing, in a way that does not make OC need to have a clone of @Vexatos' spoofing card.

**Comment by rhjobe** [comment]
I'm all for this.

**Comment by fnuecke** [comment]
> Maybe, instead of using custom network cards, it could be done by putting a network switch into a special mode (or a special "advanced" switch) where it can be directly controlled by a computer to do both packet spoofing and packet sniffing, in a way that does not make OC need to have a clone of @Vexatos' spoofing card.

Not a clone of a card because it's a block, or am I missing something?

**Comment by skyem123** [comment]
@fnuecke, well, it's not a clone of a card because (1) it's a block, and (2) it has some different functionality. Both of those mean that it will not be a direct replacement.

**Comment by fnuecke** [comment]
Then you'll need to explain again to me what it'd do, because it sounds like it'd have the exact same functionality as the spoofing card :P

**Comment by skyem123** [comment]
Well... for one, it would also have the ability to sniff packets, which is needed allowing people to create custom / advanced networks, and it being in a block would make sure that it is impractical to use for general purpose networking.

**Comment by jcc10** [comment]
So here is my opinion. (This is also similar to how it works in real life)

1: Make a sniffing card that can only listen to network messages, it can't transmit at all. (IRL it's called monitor mode)  
2: Make a card where you can change it's address. (but it can still only have one address)
3: Quit arguing if this is OP or not, people should build programs from the ground up with security in mind, adding it in at the last second is how you get hacked.

I would actually like a add-on mod with this functionality for a server I'm building (It's cyber war games), I think that OpenComputers is superior to ComputerCraft except you have this issue that you can't hack.

Or if I couldn't just disable direct connections, both would be wonderful.

**Comment by skyem123** [comment]
@jcc10: Well... @Vexatos's computronics has an address spoofing card. All that's needed is a sniffing card. :P

**Comment by jcc10** [comment]
skyem123 But 1.8!

But really with OC I don't actually need 1.8... I _do_ need the sniffing card. (And spoofing)

Also this is the type of card I would love to see in the regular mod... Possibly disabled by default but definitely there.

Does @Vexatos spoofing work on wireless networks? (Also I'm a bit of a noob on all of this)

Oh and lastly, I vote for only option 1, options 2 and 3 are just more limited versions of option 1.

**Comment by Vexatos** [comment]
@jcc10 it does if you use a relay.

**Comment by ghost** [comment]
if modem supports injection of files and remote running you might be able to connect a modem to a computer and place a daemon-like specific-network-message script to automaticly reply to the message with extern info like where is it at, what is the ip, which processes are running.

magik6k:
"This seems mostly doable with a little trick: grab a pair of linked cards, put one in computer and the other in a relay connected to network. Then using linked card you can send messages as anyone to anyone. To see message structure just send one from network and see what arrived to the computer."
@skyem123 
sounds like mitm method (man-in-the-middle)



btw skyem simple maybe possible spoofing method:
install a backdoor on your target and send info about connection and stuff you want to know or sniff it and then make your computer send like this:

to server:
hey im (ip or mac from other computer)!
(info from other computer)
etc.

thats like spoofing or spoofing method 2

send to other computer:

hey im (server info or some) and you are not allowed here!
or 
hey im the real (router or acces point or where you are connected to) dont use (real router info) but me!!!

basic tricking:
hey im (fake router) dont use (real router) but me im way safer!!!

hey im (server or router) and you are not allowed/disconnected from here

that what you wanted to know? i dont know if this all is possible but it might be with a handy backdoor and magik6k's mitm trick

**Comment by payonel** [comment]
it's a cool idea, but i suggest users use computronics for this if they want this feature

**Comment by skyem123** [comment]
Aw, though I guess since most installs of OC include Computronics, I don't need to nag anymore. :P
