### ISSUE TITLE
Feature Request - Adapter block as an upgrade for robots?

### ISSUE THREAD

**Issue by dieselfuelonly** [MightyPirates/OpenComputers#1598]
I'm sure there is a specific reason that robots can't currently interface with external components, but what about an expensive (tier 3?) upgrade that would allow them to do so?  Case in point - the Mekanism Digital Miner has all kinds of methods that allow a computer to start/stop the miner as well as program the ore filter, etc.  I was hoping to find some way to use a robot to place/break and move the digital miner around as well as control it.  Since a computer is stationary, I can't really do that with an adapter block.  Thoughts?

**Comment by Kubuxu** [comment]
Already discussed in #1004.

**Comment by fnuecke** [comment]
That. Also, in this particular case: if the miner doesn't support redstone to stop/start it, I'd say that'd be a better feature request, since it'd allow a lot more possibilities of automating it (and that could be triggered by robots, too).
