### ISSUE TITLE
Weird redstone signals?

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1599]
I'm not sure if I'm just being dumb here or what...
(Thats on OpenComputers-MC1.7.10-1.5.20.38-universal, in ATLauncher Revolution Pack)
Setup: ![](https://dl.dropboxusercontent.com/u/18783800/ShareX/2016/01/2016-01-04_23-04-18_JQvEjl.png)
PC is standard creative-spawned (/oc_sc) PC with a tier 1 redstone card added
Clearly notes 10 on left: ![](http://akari.in/pinky_5Lbz8)

Using my test program which toggles the power on side 5 between 0 and 15 when I click x and outputs the redstone_changed events, measures the actual value on getInput on their sides and sets a timer to measure it again 2s later:
![](http://akari.in/pinky_mVx3o)
So it claims both sides change to 15, and then when turning off back to 10 for side 4 and 0 for side 5...
Waila and redstone textures say side 4 stays 10 though?

(Test program: https://gist.github.com/Inari-Whitebear/d00498b6767b1f9fa3c1 )

**Comment by fnuecke** [comment]
Hm, can't reproduce in either 1.5.21 nor 1.6-dev. Mind testing on those?

**Comment by Inari-Whitebear** [comment]
Seems to happen with OC and redlogic

**Comment by fnuecke** [comment]
Let's assume it's something in the integration then... I'll look into it.
