### ISSUE TITLE
Robot "already moving" (low tickrate)

### ISSUE THREAD

**Issue by MaHuJa** [MightyPirates/OpenComputers#1601]
I'm hitting 
https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/component/Robot.scala#L72
fairly consistently.
It has the characteristics of a race condition. This is happening on a server running a tppi derivative, oc version 1.5.16.726-dev. The issue affects all programs that call `component.robot.move` such as through `robot.forward()`, like the 'go' program.

I believe the triggering factor has to do with tickrate. (We may have a volatile tick rate.)
From the observed behavior, I assume the execution delay is in wallclock time. A miscalculation (like assuming 20 tps, or that you know how long the ticks will be) will allow it to resume before the move is complete.

I've been using
`repeat res,err = robot.forward() until res or err ~= "already moving";`
to work around this issue; I'm looking into patching the robot library on my robots. (Which will still break whatever uses the component directly.)

I'm thinking a 'proper' fix would involve having these sleeps be indefinite until woken up by the main thread when it has been asleep for long enough.

**Comment by payonel** [comment]
i think this is normal behavior for moving our robots, it is typical to retry move in this error case, by design we aren't blocking the lua state from loading
