### ISSUE TITLE
Crash with Rotarycraft

### ISSUE THREAD

**Issue by QVBA** [MightyPirates/OpenComputers#1605]
http://pastebin.com/JbKLrsiQ

Crashed when placing a block adapter next to Rotarycrafts extractor. I see that forestry is also messing up here, but I can't understand why forestry is involved. I'm not sure that this is a fault on your end, but I'm putting an error report on all three involved mods.

**Comment by fnuecke** [comment]
`OpenComputers{1.5.9.21}`

Please update. Forestry integration has been fixed a few versions back.

**Comment by QVBA** [comment]
Will do, thanks for the (ridiculously) fast response :).

**Comment by fnuecke** [comment]
What can I say, it's the weekend :P
