### ISSUE TITLE
You can eat all the CPU time from a __gc hook.

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#1606]
So, this is a Lua issue, but this freezes everything:

``` lua
setmetatable({}, {__gc=function(t)
      while true do
      end
    end})
```

In lgc.c, there is this function:

``` c
809 static void GCTM (lua_State *L, int propagateerrors) {
810   global_State *g = G(L);
811   const TValue *tm;
812   TValue v;
813   setgcovalue(L, &v, udata2finalize(g));
814   tm = luaT_gettmbyobj(L, &v, TM_GC);
815   if (tm != NULL && ttisfunction(tm)) {  /* is there a finalizer? */
816     int status;
817     lu_byte oldah = L->allowhook;
818     int running  = g->gcrunning;
819     L->allowhook = 0;  /* stop debug hooks during GC metamethod */
820     g->gcrunning = 0;  /* avoid GC steps */
821     setobj2s(L, L->top, tm);  /* push finalizer... */
822     setobj2s(L, L->top + 1, &v);  /* ... and its argument */
823     L->top += 2;  /* and (next line) call the finalizer */
824     status = luaD_pcall(L, dothecall, NULL, savestack(L, L->top - 2), 0);
825     L->allowhook = oldah;  /* restore hooks */
826     g->gcrunning = running;  /* restore state */
```

Now, the way "allowhook" works is that **when it's set to 0 you literally cannot run _any_ hooks**. This is the same flag used by the debug-hook-to-Lua-function mechanism. (i.e. `debug.sethook(function() ... end, "clr")`)

So... basically... well, yeah...
# **_Bring on the DoS :P**_

(And yes this affects a bit more than just OC doesn't it... Also you guys should probably get a uhh... less public way to report these issues...)

**Comment by dgelessus** [comment]
Think I saw you post this on the Lua mailing list. `;)`

**Comment by iamgreaser** [comment]
Suggested solution: Sanitise all calls to setmetatable - the metatable must not have a metatable of its own, and it must not have a __gc hook.

**Comment by SoniEx2** [comment]
There's nothing wrong with the metatable having a metatable, it's using rawget() anyway. And __gc hooks are used by base OC.

**Comment by fnuecke** [comment]
Yeah, the `__gc`s for file handles are sorta-kinda required-ish (yes, in a perfect world everybody closes them correctly and nothing before the close throws an error, but still). The quick-fix for this would be an option to disable in-sandbox GC callbacks I guess, though I'd lean towards leaving that enabled by default, and leave it to concerned server admins to disable that. The long-term-fix would probably be rewriting file handles as userdata instead, and use their (not-accessible-via-the-sandbox) GC callback (which is already relayed to the Java side as `Value.dispose`). Problem is I don't have a lot of time to sink into this at the moment. If someone wants to take a shot before next weekend, be my guest. That's when I expect to be able to look into implementing a fix/workaround for this.

**Comment by SoniEx2** [comment]
Why not fix it in Lua? You're already patching it up with Eris, anyway.

**Comment by Kubuxu** [comment]
I suppose that there is some reason for disabling hooks in GC methods.

**Comment by SoniEx2** [comment]
I KNOW HOW TO FIX IT!

So basically you add a finalizer queue. When __gc is called, you add the object to that queue. When the thread yields, you run through that queue with the stricter time hooks, then restore the original hooks. (idk the effects of this on weak tables, but Lua does call queued __gc even if you permanently ressurect a queued object)

e.g.

``` lua
local processgc
local gcqueue = { [1] = {}, [2] = {} } -- this [1] and [2] thing is so __gc can be called while we process queued __gc's, without causing issues. see also mojang's WorldServer.sendQueuedBlockEvents.
setmetatable(gcqueue, {__gc=function() processgc(false) end}) -- we can assume that when gcqueue gets collected, the Lua state is being closed
local gcindex = 1

processgc = function(canReturn)
  -- next 4 lines courtesy of mojang's WorldServer.sendQueuedBlockEvents
  while gcqueue[gcindex][1] do
    local i = gcindex
    gcindex = (gcindex % 2) + 1 -- 5.2-friendly
    for k,v in ipairs(gcqueue[gcindex]) do -- ipairs doesn't check for modification so we can clear "seen" slots
      table.remove(gcqueue[gcindex], k) -- clear seen slot
      if not pcall(getgc(v), v) and canReturn then return end -- TODO check/use return values. Lua just delays the other finalizers when one of them errors. when closing the state it ignores errors, so you have to pass canReturn=false in that case.
    end
  end
end
```

**Comment by iamgreaser** [comment]
Here's my argument for shimming setmetatable and preventing people putting in their own __gc hooks, as opposed to queueing the garbage collector:

```
do; local derp={}; function derp.__gc() print("HONK"); local k={}; setmetatable(k,derp); return k; end; setmetatable({},derp); end
```

That's a one-liner that you can shove into the Lua shell, and while it doesn't actually break, you do end up with a memory leak when you exit. Your OS will clean up the memory leak by way of just freeing the whole unshared process space, but you don't get that luxury when it's a thread running in Minecraft and you want to actually keep Minecraft running.

I cannot think of a legitimate purpose for exposing __gc to user programs. I can, however, think of it as a horrible way of hiding memory-resident viruses, as well as leaking a metric arseload of memory, and/or freezing and/or crashing Minecraft.

A shim like this could work (of course you'd write it in C or Java instead):

```
do
  local s_setmetatable = setmetatable
  function setmetatable(t, mt)
    if rawget(mt, "__gc") ~= nil then error("__gc hooks forbidden from user code") end
    return s_setmetatable(t, mt)
  end
end
```

**Comment by Inari-Whitebear** [comment]
"I cannot think of a legitimate purpose for exposing __gc to user programs."

To clean up data when things get gc'd?

**Comment by iamgreaser** [comment]
Except the data that needs cleaning up is already handled by the GC anyway, and any userdata objects ideally should have __gc hooks set from non-Lua code already.

**Comment by SoniEx2** [comment]
@iamgreaser Actually that doesn't leak memory because you can't queue more objects for finalization when closing the Lua state.

From the manual:

> When you close a state (see lua_close), Lua calls the finalizers of all objects marked for finalization, following the reverse order that they were marked. **If any finalizer marks objects for collection during that phase, these marks have no effect.**

**Comment by SoniEx2** [comment]
@iamgreaser Also what about virtual ("unmanaged") FS?

**Comment by iamgreaser** [comment]
I'd probably just tell people to code properly.

Or option B is to add the object to a queue "in user space" that gets polled periodically - you add it when you do something that requires syncing and it's not in the queue already, and then when it gets picked up from the queue the sync is done and it gets dropped from the queue.

**Comment by Inari-Whitebear** [comment]
iamgreaser: Libraries may want to delete resources though. Say when I have a library and a user calls myLib.new and I make some intenral entries and hand back a table that acts as an object. When that gets destroyed i want to clean up its internal entries. Sure you can claim one should code properly and have a obj:dispose() method that whoever got the object has to call, but we've seen how well that works in programming xD

**Comment by iamgreaser** [comment]
@Inari-Whitebear You could actually do this creatively using weak tables.

Have a core object in a proper table, then have it wrapped and stored in a weak-value table, and return the wrapped object. These will both have the same key for each table. Periodically, check the two tables, sweep through the tables, and for any keys that are in the regular table but not in the weak table, clean them up and then remove them from the regular table.

It's much safer than a __gc hook.

**Comment by Inari-Whitebear** [comment]
Forgot lua had weak tables. But I'd still prefer a __gc hook to just clean as needed instead of having to periodically search fro what needs to be cleared

**Comment by iamgreaser** [comment]
And I'd prefer to have a protected-mode OS and use the API rather than the dangerous convenience of being able to replace interrupt vectors directly. Especially if it's a server.

Either way, it's simple enough that you can make this into an API and forget __gc ever existed. Something that looks a bit like, well, maybe this:

```
wrapped_obj = gc_object(base_object, function(base)
    do_something_with(base)
end)
return wrapped_obj
```

**Comment by Inari-Whitebear** [comment]
Uh, I'm not saying don't fix this, I'm just saying it would be preferably to keep the __gc and fix the issue properly

**Comment by payonel** [comment]
io.popen (new in openos 1.6) uses __gc to close (run to end) a leaked piped process. If a user calls close on the popen handle, there is nothing for __gc to do. But checking for this on __gc was the correct way. Without __gc, popen handles could leak. Yes this is the user's fault ultimately, they should be closing their handles. I just thought I'd mention this.
