### ISSUE TITLE
Add debug.getlocal and debug.getupvalue to retrieve local and upvalue names

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#1607]
This could be used by the Lua interpreter to give more info about a function, e.g.

```
lua> function f(a, b, c, ...) if a == b then print (c) else print(...) end end
lua> =f
function f(a, b, c, ...)
lua>
```

A simple way to wrap it is `function(...) return debug.getlocal(...), nil end` (the `, nil` makes it return only the first value)

**Comment by gamax92** [comment]
You can also just wrap the function in ()'s, which forces it to return only the first value. Your method technically returns two values, the second is just nil though.

**Comment by SoniEx2** [comment]
@gamax92 debug.getlocal is supposed to return 2 values, at least if the first value is not `nil`.

**Comment by Inari-Whitebear** [comment]
But uh, isn't that the same though? xD If you don't return a second value it is nil

**Comment by SoniEx2** [comment]
No, because of the stack.

``` lua
function a() return nil, nil end
function b() return nil end
function c() return end
print(select('#', a())) -- 2
print(select('#', b())) -- 1
print(select('#', c())) -- 0
```

**Comment by Inari-Whitebear** [comment]
Well not sure that matters for any actual usage, but I guess

**Comment by SoniEx2** [comment]
Just trying to keep the results faithful to what real Lua /might/ return. (real Lua /might/ return string, nil, so returning nil on the second value is fine, even if it doesn't reflect the internal state. This is similar to the sandboxed debug.getinfo not returning `func`)

**Comment by payonel** [comment]
also adding feature-accepted as if i get to it, i'll investigate
