### ISSUE TITLE
[1.8.9] ID glitch when using FlatColoredBlocks by AlgorithX2

### ISSUE THREAD

**Issue by SwordKorn20** [MightyPirates/OpenComputers#1608]
I have submitted an issue for this with AlgorithmX2 already but as it seems to only affect your blocks, I wanted to open one here as well. With both of these mods installed, a placed in world screen block gets forcibly overriden to be a Lime Block from the FCB mod. I first noticed it in a testing world where my tier 3 screen got turned into a Dark Lime Block #353.

I'm not blaming either of you for this issue, but I wanted to make you both aware of it as 1.8.9 modding starts to pick up speed.

**Comment by RuinTD** [comment]
Can confirm. Also happens with Thaumcraft, in which the screens are overwritten with loot crates.

**Comment by fnuecke** [comment]
See #1600.

**Comment by SwordKorn20** [comment]
Thank you very much Sangar! Your mods are quickly becoming my favourites and I favour OpenComputers over Computercraft massively these days! Sorry to have made a duplicate issue but I wasn't aware it was affecting anyone else.

**Comment by fnuecke** [comment]
No worries, thanks for reporting it!
