### ISSUE TITLE
Cables don't work with Optifine

### ISSUE THREAD

**Issue by MariuszPL55** [MightyPirates/OpenComputers#1614]
Game is crashing everytime when I place a cables. They render, but after a few secs whole game crashes. Bug is because of Optifine, confirmed, because without this mod everything is going smooth..

[crash-2016-01-14_23.34.00-client.txt](https://github.com/MightyPirates/OpenComputers/files/91109/crash-2016-01-14_23.34.00-client.txt)

**Comment by LordFokas** [comment]
Yes, that would be expected. Optifine is that one mod that breaks anything non-vanilla. It has been like that for 3 years or so and no one is expecting it to ever change. The issue is at OF's end and I don't think any modder ever went out of their way to give it better support (as in working around OF's flaws).

**Comment by XFactHD** [comment]
The problem is that it is not possible to work around the problems, for example because there is no API.

**Comment by MariuszPL55** [comment]
Then Optifine is shame. Then guys, anybody knows how mod can make graphics.. nicer?
Just test new update for Optifine.. still don't work ;c

**Comment by XFactHD** [comment]
In which way? Make it more fluent? If so, you could try CoFHTweaks. If you want shaders, there is a way to replace the crappy vanilla shaders via resource packs.

**Comment by Inari-Whitebear** [comment]
FastCraft can also help with performance

**Comment by XFactHD** [comment]
But it also sometimes causes problems and is closed source too.

**Comment by MariuszPL55** [comment]
If you can tell me how to replace shades via resource packs I will be happy. You can via mail if here is spam: mariuszpl5400@hotmail.com

**Comment by XFactHD** [comment]
You can look it up yourself on the Minecraft wiki.

**Comment by Inari-Whitebear** [comment]
Sure, but causes less issues than optifine ;)

**Comment by XFactHD** [comment]
That's true. :)

**Comment by MariuszPL55** [comment]
What about another mods, I mean mods that provide power in OpenComputer's, they still are in version 1.7.10.. why?

**Comment by XFactHD** [comment]
If you want a mod that adds another OC cable, there is none because there is no need.

**Comment by MariuszPL55** [comment]
No, I want mod that provide power, so we need first make power to make computer work

**Comment by XFactHD** [comment]
You can disable the need for power in the config.

**Comment by MariuszPL55** [comment]
No man, I already have that option disabled, but I want this because this is more funny

**Comment by XFactHD** [comment]
The RF API wasn't ported to 1.8 until now but Buildcraft has a 1.8 version. I don't know if this would work.

**Comment by fnuecke** [comment]
Looks like Optifine making some wrong assumptions I'm guessing. Unless proven otherwise, will close as not my fault, sorry.
