### ISSUE TITLE
Some links on the in-game documentation crash the game

### ISSUE THREAD

**Issue by RuinTD** [MightyPirates/OpenComputers#1615]
Two of these link include the link to the Tablets page on the [Items page](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/doc/en_US/item/index.md) and the link to the Drones page on the top of the [main page](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/doc/en_US/index.md).

**Comment by RuinTD** [comment]
Also, the "crash" is the game no longer responding, so I have no crash log. I'll try to reproduce the crash later and check the log, but I can't right now.

**Comment by fnuecke** [comment]
OC version?

**Comment by FayneAldan** [comment]
The latest version for MC 1.8.9 available on CurseForge.

**Comment by RuinTD** [comment]
1.5.21.1 for Minecraft 1.8.9

**Comment by fnuecke** [comment]
Hmm, can't reproduce I'm afraid :/ If you find out anything relevant to reproducing this (custom font renderer? UI scaling? Other mods?) that'd be great, otherwise... this will be nearly impossible to debug for me.

**Comment by RuinTD** [comment]
I tried in [OpenComputers 1.5.21.1](http://minecraft.curseforge.com/projects/opencomputers/files/2273126/download) with [Minecraft Forge 11.15.0.1699](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.8.9-11.15.0.1699/forge-1.8.9-11.15.0.1699-installer.jar) running in a new folder (with OC in the mods folder, of course). So, the only mod running is OpenComputers and all my settings are default (except render distance, because my PC is old). After opening the manual and clicking the drones link on the top of the main page, this happens:
![image](https://cloud.githubusercontent.com/assets/1149870/12369653/a29ad690-bbb8-11e5-9be9-aa0793c5405b.png)
However, nothing relevent is written to log. The last line in the log is:
`[18:24:34] [Server thread/INFO]: Changing view distance to 2, from 12`

After some further testing, I have found the cause to be the image on the page. After removing the image on the md file in the jar, the page would load correctly. If there's any way I could help furthur debug and test, I'm willing to help. I just need to know what to do.

**Comment by RuinTD** [comment]
Any further word on this? I tried to comment out some lines in li.cil.oc.client.renderer.markdown.segment.render.ItemStackImageRenderer to find the cause, but I encounter Java heap space in :decompileMc when building.

**Comment by RuinTD** [comment]
If I had to make a **GUESS**, I would say it's caused by trying to use a GL12 constant as a parameter for a GL11 function: [`GL11.glEnable(GL12.GL_RESCALE_NORMAL)`](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.8.9/src/main/scala/li/cil/oc/client/renderer/markdown/segment/render/ItemStackImageRenderer.scala#L25)

**Comment by RuinTD** [comment]
EDIT: Nevermind what this said before about a possible cause. I don't know anything about Scala.
If you need any help testing, I can test out compiled builds. If you have Skype, my username is darkspinesonic1.

**Comment by Techokami** [comment]
> If you need any help testing, I can test out compiled builds. If you have Skype, my username is darkspinesonic1.

Uh, the people here generally talk in real time with IRC. Join us on irc.esper.net in #oc

**Comment by fnuecke** [comment]
Given by you poking in the code I'm assuming you have at least rudimentary coding experience? Could you try setting up a dev-env, run it there and if it also happens try pausing to see where it hangs?

Basic steps on how to set up and OC dev-env are [in the readme](https://github.com/MightyPirates/OpenComputers#opencomputers).

**Comment by RuinTD** [comment]
So, I just wasted about 2 hours trying to debug until I found out I was on the master-MC1.7.10 branch. If it makes you feel better, the bug seems to be 1.8.9 only.

**Comment by fnuecke** [comment]
Sorry to hear that, and welcome to branches ;) On 1.7.10, does it also not happen in the release builds (i.e. OC 1.5)? I.e. might it have been fixed somewhere in OC 1.6?

**Comment by RuinTD** [comment]
Well, I can no longer test for this bug, as I replaced my old crappy laptop with a new desktop. I'll close this for now and if anyone else has this problem, maybe point them this way?
