### ISSUE TITLE
Logging chunkloaders

### ISSUE THREAD

**Issue by cyber01** [MightyPirates/OpenComputers#1616]
It is possible to add chunkloaders logging in OC? It is required to monitor chunkloaders in robots. On the server, a lot of robots and chunkloaders in them and it is very difficult to trace some of the robots is to blame for stress. And then it turns out that the robot with a laser from the IC digging a huge space, which loads the server. If it were logging, you could even make a card where a robot.

I would like to see the following data: the nickname of the owner, the coordinates of the robot, and perhaps even some data.
I think people who have a public server with the OS will support me.

**Comment by XFactHD** [comment]
This sounds very useful. Also, I like your example with the IC2 mining laser, I once lagged an empty SP world from 120 down to 1 FPS by firing a full charge from the mining laser in scatter mode ;)

**Comment by cyber01** [comment]
That's the problem that the laser is quite loads the server, and keep track of the robots, which can be anywhere in the world with chunkloader - impossible

**Comment by XFactHD** [comment]
Yes and if I didn't miss anything, the OC robot is the only one that can chunkload itself.

**Comment by fnuecke** [comment]
Aren't there existing solutions for visualizing loaded chunks already? IIRC Opis/Mapwriter can do that, no?

**Comment by cyber01** [comment]
Unfortunately, there does not always have the opportunity (or need to put Opis), it is very convenient to make such a system in Dimmensional Anchors, but this mod again used relatively little. Opis may show downloaded chunks, but Opis will not be the same for the entire server to rush in search of a robot that loads the chunks. It is much more convenient it would be something like a log file so the name of the robot and its actual coordinates (only for those robots, which set chunkloader)

**Comment by LemADEC** [comment]
Railcraft dumps its chunkloaders at boot, it would be useful to have the same in OC.
Other solution is to download the map and NBT edit it to find chunkloaders, it's hardly practical.

**Comment by Landrash** [comment]
Equivalent code that @LemADEC is referencing is in [Railcrafts code](https://github.com/CovertJaguar/Railcraft/blob/8356a14862b894e83341bac885d0f47f8f66095b/src/main/java/mods/railcraft/common/util/misc/ChunkManager.java)  

It basically prints out each chunkloader with type and x,y,z coordinates. In this use case it might be interesting to print out each something like "Chunkloaded Robot owned by X found at x,y,z".

Using Railcraft as inspiration it would also be good to see to that this is a setting and not a default to prevent log bloat.

**Comment by fnuecke** [comment]
So basically dump out the chunkloader positions on server start? Or always when they're enabled? Or rather via a command?

**Comment by LemADEC** [comment]
I would say dump at server start with coordinates and owner name.

**Comment by cyber01** [comment]
On server start and via a command to update the coordinates on the current (since the start of the server).
Like:
Name of robot,Maybe name of Owner, x,y,z,world

**Comment by cyber01** [comment]
I think it is necessary to make in the configuration file (the ability to enable or disable logging).
And if it is possible - to make the function work chunkloader only when the player is in the network (and to enable / disable this through the configuration file)

**Comment by cyber01** [comment]
Thanks
