### ISSUE TITLE
1.8.9 Errors running the clas transformer.

### ISSUE THREAD

**Issue by Dyonovan** [MightyPirates/OpenComputers#1618]
As requested: http://teambrmodding.com/logs/fml-server-latest.log

**Comment by fnuecke** [comment]
Context?

**Comment by Dyonovan** [comment]
When I log into the server it asks me to report that with full server log.

**Comment by Dyonovan** [comment]
https://gyazo.com/156e7228196b87989cd0ea4dd4094348

**Comment by fnuecke** [comment]
Hrm, can you please post your client's log file, too? Thanks.

**Comment by Dyonovan** [comment]
Not a problem

Client Log: http://teambrmodding.com/logs/fml-client-latest.log

**Comment by fnuecke** [comment]
Ah, was blind, got it. Thanks for reporting!

**Comment by BBoldt** [comment]
@fnuecke Still not fixed, latest Buildcraft and OC:
https://gist.github.com/9f1e8943f7a33fe7a23f
