### ISSUE TITLE
Unable to send signals from custom block

### ISSUE THREAD

**Issue by LemADEC** [MightyPirates/OpenComputers#1619]
I'm having trouble sending signals from my mod blocks to an OC computer.
Computer is able to access my blocks methods, but signals are never received.
I can't seem to find a practical exemple of sending signals from custom blocks in the wiki.

I've tried using

```
OC_node.sendToVisible(eventName, arguments);
```

and

```
OC_node.sendToReachable(eventName, arguments);
```

On the computer, I'm using the dmesg script provided natively.

**Comment by fnuecke** [comment]
Messages on that level are not the same as computer signals. To trigger a computer signal, do:
`node.sendToReachable("computer.signal", eventName, arguments...)`
