### ISSUE TITLE
Cannot break out of infinite loop

### ISSUE THREAD

**Issue by wooky** [MightyPirates/OpenComputers#162]
I cannot break out of a simple program with an infinite loop, such as

```
while true do
  print("Hi")
end
```

I tried every possible combination, Ctrl-C, Ctrl-D, Ctrl-Alt-C, or what have you, but am still unable to break out. Also, since I wrote that program to autorun, the hard disk is pretty much trashed.

Is the terminate keybind broken? Is there even one? Or am I missing something?

**Comment by SpiritedDusty** [comment]
You can only do the terminate key combo if you are listening for a signal inside of the loop.

**Comment by wooky** [comment]
I managed to figure that out, but it's still pretty terrible, especially if someone writes a program and doesn't know about it.

**Comment by fnuecke** [comment]
Weeeeell, that's what the power button is there for ;-)

At least until I decide upon a non-terrible way to do interrupts elsewhere (the only ideas I've had so far involve ugly cross-dependencies from kernel into user code to get the key states). I'll leave this open as a reminder.

**Comment by wooky** [comment]
A power button is useful only in the case that the offending program wasn't named autorun.

Speaking of power buttons, I think having a reset button for these situations would also be nice. :P

**Comment by SpiritedDusty** [comment]
Well you could just remove the harddrive and disable autorun, then just put the drive back in.

**Comment by Vexatos** [comment]
How to disable autorun without changing the configs? Some terminate/break button should really be implemented.

**Comment by fnuecke** [comment]
```
# lua
lua> filesystem.setAutorunEnabled(false)
```

I might make a program to allow doing `autorun off/on` from the shell when my immediate ToDo list has shrunk down a bit.

**Comment by fnuecke** [comment]
After some more thinking I'd say just make sure to write your programs accordingly (use os.sleep and/or event.pull occasionally), and use the power button in the worst case. The main problem with allowing to interrupt from anywhere is that key presses are signals, so to detect those one has to event.pull(), and automating that would lead to signals getting lost.
