### ISSUE TITLE
Add more slots on creative computer case

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1620]
When designing a computer to be used to help run a server, it would be very helpful to have more slots in a creative computer case for expansion cards, hard drives and i also thing you should add an admin hard drive, which has lots of storage and an admin ram stick

**Comment by jhagrid77** [comment]
I do think that more slots would be nice. About the hard drives and ram sticks, you could edit the config file, I have max hard drive having 1024MB space, and max ram 4096MB (I think maybe it's kb).

**Comment by XFactHD** [comment]
RAM is kb, hard drive is MB. I don't get why you would need that much storage. How do you want to fill 4MB of space on the hard drive with data?

**Comment by fnuecke** [comment]
I don't plan on adding more slots; use multiple networked computers that provide functionality to each other.

For more storage, consider a RAID. If you need more than 12 megs, disable buffering in the config and dump your data to the drive externally. I've yet to hear a usecase generating that much data in a _single file_ (hint: use multiple raids) ingame.

**Comment by ghost** [comment]
What i ment is i would like to be able to fit a debug card, internet card, spoofing card, data card and probably others into the creative computer case
