### ISSUE TITLE
Robot changing name repeatedly after Server Restart

### ISSUE THREAD

**Issue by duartebarbosadev** [MightyPirates/OpenComputers#1621]
I recorded it
https://www.youtube.com/watch?v=wCdba4Kv4ww&feature=youtu.be
Edit:
I broke the robot and the name is Robot.name and has no components

**Comment by fnuecke** [comment]
Looks like the state got corrupted, look in your log if there's any errors during save/load. Without stacktrace of some error or a way to reproduce it I'm afraid there's nothing I can do about this, sorry.

**Comment by DarkholmeTenk** [comment]
I've also had this. Seems to be reproducible if the server gets restarted while the robot is partly through a move operation.

There are no error logs produced and this is on 1.7.10 with the latest forge version.

As a result, all of my backups (made by doing save-off save-all copying the files, then save-on) seem to have a robot with a corrupted state.

**Comment by xarses** [comment]
I can second that I had a remote mining robot operating during a number of server restarts and got stuck in a similar state. I will attempt to reproduce.

**Comment by rao000** [comment]
I am experiencing a similar issue on my linux based server, although mine happens whenever placing the robot, as above the name changes wildly and the inventory is not accessible. using
OpenComputers-MC1.7.10-1.6.1.11-universal
forge-1.7.10-10.13.4.1558-1.7.10-universal

**Comment by payonel** [comment]
adding 'bug-cannot-reproduce' given insufficient repro steps

**Comment by payonel** [comment]
open new ticket with specific repro if you find this bug again
i cannot repro
