### ISSUE TITLE
minecraft version 1.8.9 Tier III Screen will not place

### ISSUE THREAD

**Issue by Micro-Steve** [MightyPirates/OpenComputers#1623]
I have tried to place one several times now to no avail.  It just never appears.  I have tried right/left clicking, shift right/left clicking, placing directly on the tier III chassis as well as to the side, nothing.  The screen shows in hand for placing, I get the clicking thud for placement but nothing is there.  

Minecraft is not crashing so I do not where to look.

Any help would be appreciated.  Thanks!

**Comment by Micro-Steve** [comment]
Addendum...seems to be that the screen must be in a certain position facing with the semblence of a cooling fan.  Well that is not a good way to start.  Sorry for the inconvenience.

**Comment by fnuecke** [comment]
Are you on 1.5.22? If not please, update.

**Comment by Micro-Steve** [comment]
Un-able to find your ,22 update.  I am running 1.8.9-1.5.21.1.  I found out, I'm guessing here, that the monitor only faces in a N/S U/D relation?

**Comment by fnuecke** [comment]
Find it on [Jenkins](http://ci.cil.li).

**Comment by fnuecke** [comment]
Now also on Github (Releases tab) and Curse.
