### ISSUE TITLE
Vanishing keyboards

### ISSUE THREAD

**Issue by ShadowDrakken** [MightyPirates/OpenComputers#1624]
Using 1.5.21.1 (you mentioned a 1.5.22 in another report, but I can't find it)

Keyboards seem to be heavily bugged. They seem to place fine on top of things, and on north and south faces, but they only vanish from the inventory with no block on north and south faces, while still registering to the computer as an available component (and eating up the limited number of component slots). This makes it possible to place another block in the same location, and it also causes the keyboard to simply vanish with no way to recover it.

There's a few odd graphical glitches that can sometimes occur as a result as well, such as when placing a keyboard on a south face, then placing another block in the same location, a skinless transparent block ends up being placed instead.

This problem persists through saving and closing out of Minecraft, so it's not simply a rendering bug.

**Comment by fnuecke** [comment]
1.5.22 is available on [Jenkins](http://ci.cil.li), please try with that, see if it still happens, pretty sure it's related.

**Comment by fnuecke** [comment]
Now also on Github (Releases tab) and Curse.
