### ISSUE TITLE
pairs() consided harmful (Metatable with metatable)

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#1625]
This code behaves differently in OC vs the standalone Lua interpreter:

``` lua
local t = {}
local mt = {
  __index = {"1", "2", "3", test="hi"}, -- index 
  __gc = function() end -- dummy __gc, to trigger bug
}
local mtmt = {
  __pairs = function() -- dummy __pairs that returns an empty iterator
    return next, {}, nil
  end
}
setmetatable(mt, mtmt) -- needs to be done first
setmetatable(t, mt) -- trigger bug
-- ok so now let's test our __index shall we?
print(t[1], t[2], t[3], t.test) -- nil, nil, nil, nil
-- wait what?! it doesn't work!
```

Proposed solution: change setmetatable() to use `for k, v in next, t do`.

**Comment by RyanSquared** [comment]
I lost all faith in you the second I saw you write "pairs() considered harmful" - it's not harmful, it's just not usable in this spot.

**Comment by SoniEx2** [comment]
@ChickenNuggers I know but extortion tactics.

**Comment by skyem123** [comment]
You do know, when people get annoyed at you (like most OC people), titles like this are more likely to make them ignore it...

**Comment by SoniEx2** [comment]
@skyem123 Really? Because people started paying attention when I changed it to this...

**Comment by RyanSquared** [comment]
I mainly just called you an idiot because I saw you mention it elsewhere, a channel we unfortunately share.

**Comment by skyem123** [comment]
I would have checked it anyway... >_<

**Comment by fnuecke** [comment]
Next time, just make a PR, and don't be a passive-aggressive dick about it.
