### ISSUE TITLE
Add API for calling synchronous methods through a queue and events (non-blocking I/O)

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#1627]
Synchronous methods, or methods which need to run on the main thread, are currently blocking and halt all processing on a computer. I propose a queue API which lets programs asynchronously _queue_ methods to be called in the main thread, and then receive the results in events when the methods do get called. This will allow programs to better utilize CPU time, and then I can _finally_ port [NBSPlayer](https://github.com/SoniEx2/NBSPlayer) to use OpenComputers + OpenPeripherals.

I feel this will benefit more people than just me, especially with non-blocking I/O.

(Btw banning me from the IRC channel means I can't talk about the idea and plan a good idea first, I need to fill the issue tracker with working drafts. And I will, because I might get something good out of that.)

**Comment by Vexatos** [comment]
Actually, it's a good balance point for non-direct calls to take time. Those usually are the more "expensive" methods anyway, those that interact with the world in some way. You suggestion seems very much not worth the effort.

**Comment by SoniEx2** [comment]
Non-blocking I/O. And being able to play note block songs (without computronics).

**Comment by SoniEx2** [comment]
Also there's still the call limit. But not having to wait 50msec between EACH note would be really nice. (Songs aren't made of single notes after all)

**Comment by Vexatos** [comment]
Change API and add a mostly redundant "feature" just for note blocks? :suspect: 
I honestly can't see how this would be useful at all.

**Comment by SoniEx2** [comment]
Non-blocking I/O. Aka queue-dostuff-read I/O. Hell this is just a Lua-side API change, and it's just a new method.

**Comment by skyem123** [comment]
Would this be possible at all by replacing code in OpenOS?

**Comment by SoniEx2** [comment]
It's really simple:
1. Add the function and arguments to a queue (yes this does mean you might be able to change a table after queuing it).
2. Wait for a yield.
3. Optionally repeat from 1.
4. Run queued functions with arguments, push the results into events.
5. Events are processed by the program.

Alternatively you can change the API and completely remove main thread Lua code execution.

**Comment by skyem123** [comment]
well... can you implement this yourself? :P

**Comment by SoniEx2** [comment]
Well yes but I can't do copy-on-write tables.

**Comment by skyem123** [comment]
how will they help? can't you use metatables?

**Comment by SoniEx2** [comment]
If you modify the table between the queue and the call, we can keep the queued state while allowing the modification to happen. Altho this requires changing the Lua interpreter.

**Comment by skyem123** [comment]
well, can do you what you want without the copy-on-write tables?

**Comment by SoniEx2** [comment]
I can do it for my own methods, yeah. I can't do it for other mods' methods.

**Comment by skyem123** [comment]
why not?

**Comment by SoniEx2** [comment]
Because the API won't let me.

**Comment by skyem123** [comment]
you have to be more descriptive than that...

**Comment by fnuecke** [comment]
While I can see a few uses for this (queuing `setBlocks` from the debug card come to mind), I don't think explicit support in OC's API is necessary for this beyond what's there already. This would add yet another layer of complexity to the callback logic, which is already pretty complicated, so in my estimate it's more likely to add a bunch of new hard to debug bugs than do good.

I'd suggest having a custom queuing system in the few particular cases you need it, i.e. push jobs to a locally held queue and process it in the component's regular update call. If you need in-depth status information on each job, spawn a userdata per job, otherwise have a general `getResults` callback that returns info on processed jobs.
