### ISSUE TITLE
missing a portion of cofh libs causes adapters to break

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#1630]
Initially, I added OC to my pack and found that when placing a adapter and then connecting it to a cable with no network route the server faults. As it turns out, this really isn't the issue.
# Main Issue

It turns out that while initializing we see that there is a caught exception with loading the cofh `DriverEnergyInfo` `cofh/api/tileentity/IEnergyInfo`.(https://gist.github.com/xarses/9a9aed7cdbe802f1b7c2)

While I have a couple of mods that use RF, none provide the IEnergyInfo tileentity (https://gist.github.com/xarses/3879c7d81d0d90f07ca1)
Mods list: https://gist.github.com/xarses/6a941455a9ed49bfc76a

When this occurs, it appears to leave the adapter in an odd state, and causes the blow symptoms
## Driver based components don't show up

Putting down an adapter next to a integration driver (F.E `gregtech.api.interfaces.tileentity.IBasicEnergyContainer`) should result in an instance of `DriverEnegryContainer` (https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/integration/gregtech/DriverEnergyContainer.java) being available from components, when in fact it is not. (I only have buildcraft which comes alphabetically before cofh, and am not shure if it's drivers function)
## Placing the adapter issue

Steps to reproduce:
- Place adapter with no other OC blocks around
- Place a cable off of any side of the adapter, this will form a network with no route (only occurs on first cable placed adjacent to the adapter, additional cables off the first don't crash, this also occurs if any cables cable connecting to the adapter has other segments that don't route)
  (server halts)

(It may also fault joining a complete network, but the cable isn't always lost when you restart the server)

Expected result:
Can continue to place cables until it forms a valid network
Client and server should not fault.

Server Crash log: https://gist.github.com/xarses/212b42786999989fe0fe
Console Log: https://gist.github.com/xarses/f06f8418c75c34311052
OC: OpenComputers-MC1.7.10-1.5.21.41-universal.jar

**Comment by xarses** [comment]
does not reproduce with:
* floppy drive
* monitors (Tier 1, 2, 3)
* switch
* geolizer

does reproduce:
* when breaking a adapter immediately adjacent to another adapter

**Comment by xarses** [comment]
possibly related, the driver for gregtech doesn't appear to be operable, looking back through the logs, I see https://gist.github.com/xarses/9a9aed7cdbe802f1b7c2 repeated a few times

**Comment by xarses** [comment]
updated issue based on findings and help of the folks on IRC

**Comment by xarses** [comment]
found that magneticraft-0.3.3.jar is the source of the incomplete cofh titleentity api, updating to magneticraft-0.5.1.jar resolves this problem as the cofh api is not included anymore.

I'd still like to see the fault handled gracefully.

**Comment by fnuecke** [comment]
So in short, someone shipped a partial `CoFHAPI|tileentity` API? Then crashing is to be expected; because that's just wrong. I won't handle special handling for potentially partial APIs, sorry.
