### ISSUE TITLE
Charger won't charge if set too high in config

### ISSUE THREAD

**Issue by twothe** [MightyPirates/OpenComputers#1631]
If the Charger is set to a charging rate beyond a certain level it will no longer charge anything at all.

For example, if the config is set like

```
chargerChargeRate=1000
chargerChargeRateTablet=1000
```

The Charger will charge neither items nor Nanomachines.

**Comment by jhagrid77** [comment]
Maybe it can't do quadruple digits?

**Comment by fnuecke** [comment]
You'll also need to adjust the chargers internal buffer then. Or plop down a bunch of capacitors. There's a piece of code used to keep not-useful charge updates low, to avoid the chargers eating ticktime when possible, and that's tied to the charge-rate-to-global-buffer-ratio.

**Comment by twothe** [comment]
I actually did update the buffer as well, according to my math they should have been at 2k storage with 1k charge ticks, but effectively it just didn't work.

I'd suggest to at least auto-correct the charge rate downwards instead of just not working at all.
