### ISSUE TITLE
BlueScreen after update to v1.5.22

### ISSUE THREAD

**Issue by twothe** [MightyPirates/OpenComputers#1633]
After updating to v1.5.22 all computers can no longer boot.

BlueScreen message:

```
init:90: boot/01_process.lua:2: module 'process' not found:
  no field package.preload['process']
  /lib/buffer.lua:32: attempt to index field 'stream' (a boolean value)
```

**Comment by twothe** [comment]
This issue is related to the old hard-disk installs.

Booting from a new disk and installing from that new disk makes the computers usable again.

**Comment by jhagrid77** [comment]
I would recommend using one of the new disks coping those files that are missing over to the old disk (in the required places of course) tell me what happens after that.

**Comment by twothe** [comment]
Copying the files from a new disk solves the issue, however that means I had to disassemble, re-install and re-assemble each tablet and robot on the server to access the hard disk.

**Comment by fnuecke** [comment]
I'm afraid I don't see how this could be related to [any of the changes between 21 and 22](https://github.com/MightyPirates/OpenComputers/compare/v1.5.21...v1.5.22), but I'll try to reproduce when I have the time.

**Comment by magik6k** [comment]
Looks like filesystem component got rewritten to userdata which breaks plan9k COW fs(overlay fs) implementation.

**Comment by jhagrid77** [comment]
Sangar, is it possible to access hard drives like this easier? Such as a program for remote access? Just thinking.

**Comment by fnuecke** [comment]
Fixed, hotfix incoming. Terribly sorry about this.

(Caused by the new GC sandboxing, at least it wasn't me, but I still should have caught it in testing.)

**Comment by twothe** [comment]
Thanks for the fix! =)

**Comment by SoniEx2** [comment]
Terribly sorry about this as well. Oops.

We need unit tests...
