### ISSUE TITLE
[Feature-Request] MCMultipart support

### ISSUE THREAD

**Issue by bbgott** [MightyPirates/OpenComputers#1634]
I realize this may not be an easy under taking, so I'm just floating this idea. One of the fun aspects of the MC 1.7.10 version is the multipart support. With more and more mods starting to upgrade to 1.8, multipart support appears to be finally provided by at least one mod, MCMultipart. Are there plans to investigate this? I love being able to tuck my cables under a multipart cover. Also the multipart support for 3d prints is great in MC 1.7.10.

**Comment by jhagrid77** [comment]
What about forge multipart, or immbis microblocks.

**Comment by bbgott** [comment]
When searching, it didn't appear that either of them had updated to MC 1.8.9 yet. I could be mistaken, but the only multipart api that I could find that was compatible with MC  1.8.9 was the MCMultipart library.

**Comment by Landrash** [comment]
Theres been mentions on the forgecraft sever of Chisel and Bits potentially being part of forge in someway. Heard it several times in conversations on Direwolf20's videos.

If this come to pass it might be the best option but it could complicate the 3D printers. since each block then is a block of 16x16x16 smaller blocks.

**Comment by gjgfuj** [comment]
@Landrash, I don't think c&b would. MCMP will most likely be merged into
forge though.

Also, wrt fmp and immibis microblocks, mcmp successfully makes both of them
horribly bad in comparison.

I'm surprised mcmp support isn't already there tbh.

**Comment by fnuecke** [comment]
MCMP is something I do plan on looking into after porting the OC1.6 changes over to MC1.8.

**Comment by bbgott** [comment]
Awesome! I was guessing it was likely to be a 1.6 feature plan. Thanks for the update and thanks for the great mod!

**Comment by fnuecke** [comment]
Done.
