### ISSUE TITLE
Plan9k Panic on oc1.8-1.5.22.46

### ISSUE THREAD

**Issue by codelacuna** [MightyPirates/OpenComputers#1635]
Plan9k panics on boot after updating to 1.5.22.46

**Comment by jhagrid77** [comment]
Can you define "panics" please?

**Comment by codelacuna** [comment]
http://imgur.com/rE2G2ve

**Comment by Kubuxu** [comment]
@magik6k can you take look at it?

**Comment by magik6k** [comment]
I have no idea about this one. Looks like outdated disc, but can't say for sure as you cut the most important part of the error.

**Comment by fnuecke** [comment]
Might be related to #1633, though I'm rather clueless as to why that might happen (haven't had the time to try and reproduce that, yet).

**Comment by codelacuna** [comment]
Wow yeah apologies on that, here's the full image: http://imgur.com/A0PlUcV

For reference, I downloaded oc from the link provided on this github and installed on a fresh install of minecraft with forge 11.14.4.1577

**Comment by magik6k** [comment]
Looks like filesystem component got rewritten to userdata which breaks plan9k COW fs(overlay fs) implementation.

**Comment by jhagrid77** [comment]
I wonder what is up with these issues... I never had any.

**Comment by fnuecke** [comment]
Most likely same as #1633, the new GC sandboxing essentially broke setmetatable when a __gc field was set on the table.
