### ISSUE TITLE
[Feature(?) Request] OreDict support for diamonds in recipes

### ISSUE THREAD

**Issue by MyNameIsKodos** [MightyPirates/OpenComputers#1637]
After a long time avoiding it, I put together a pack using IC2 today, and I went to craft some T3 OC Items with Industrial Diamonds and... it didn't work.

I propose oredict support for anything oredicted as a diamond, as I can think of, offhand, two items that can act as a vanilla MC diamond, including an IC2 industrial diamond.

**Comment by fnuecke** [comment]
Guess I'll have to s/diamond/gemDiamond/ in the recipes. If someone wants to make a (tested) PR to speed that up, that'd be great.

**Comment by natedogith1** [comment]
Might I ask what the other item that acts as a diamond is? Also, how did you get industrial diamonds? I thought those weren't obtainable (other than through creative or the like).

**Comment by MyNameIsKodos** [comment]
Industrial diamonds have an elaborate recipe in Experimental. The other item is a cut diamond from RSMC
