### ISSUE TITLE
Drone recipe

### ISSUE THREAD

**Issue by JasonMcRay** [MightyPirates/OpenComputers#1638]
Just a little request.... would it be possible to add some sort of information about how to make OC drones either into NEI (maybe just a text about player needs to make them in assembler with necessary parts) or add just tooltip to the drone about it? (with that also other parts, that doesnt have NEI recipe and are written in manual only)

I was trying to make a Drone, but was unable to find the recipe, then my friend who knows a lot about OC pointed out, that I need to check the ingame book, or in-game wiki mod.

I think it will be more usefriendly this way. I know a lot of players, who dislike reading in extensive books on how to make stuff. Its fine for how to use them, but making of them should be somewhat better seen.

Thanks

**Comment by gjgfuj** [comment]
Isnt it simple enough to take it as "you put a drone case in an assembler
to make a drone"?

**Comment by hron84** [comment]
OpenComputers has a full In-Game-Wiki mod integration and already provides a very detailed step-by-step howto for creating drones, robots and these stuffs. I think there is no other information needed.

**Comment by gjgfuj** [comment]
The point of this is to /not/ have to look in the book.

Assembler integration for nei/jei would be interesting though. Like roughly
show the input/output of an assembler recipe.

**Comment by fnuecke** [comment]
If someone would like to supply NEI/JEI handlers, that'd be great. I may look into JEI myself at some point, but NEI is a tad too... much of a headache for me I'm afraid.

**Comment by payonel** [comment]
adding "open for adoption" for anyone that wants to add nei/jei handlers for the more complex assembler crafts
