### ISSUE TITLE
[Cosmetic Bug] Robots do not change tint at level 10/20

### ISSUE THREAD

**Issue by McSharidan** [MightyPirates/OpenComputers#1639]
MC: 1.7.10
OC: 1.5.22.42

Robots equipped with the experience upgrade are supposed to change tint to a gold-like "look" when they reach level 10 and a diamond-like "look" when they reach level 20.

The robot entity model, does not change tint until either destroyed and placed back or the chunk where the robot sits gets reloaded. In short, the robot model has to be refreshed / reloaded for the tinting to take effect.

**Comment by magik6k** [comment]
Having list of other mods and nearby blocks seems to be required as it's most likely caused by other mod doing rendering wrong.

**Comment by fnuecke** [comment]
Was caused by the experience upgrade's level not being synced to the client immediately.
