### ISSUE TITLE
Extremely(!) primitive Holo API

### ISSUE THREAD

**Issue by skarlitz** [MightyPirates/OpenComputers#164]
http://hastebin.com/medadiwufa.lua

This is my work on a very(!) primitive Holo API. It lets you set the specific XYZ positions of voxels in the hologram projector. To use it, do something like this:
http://hastebin.com/ketejajoqi.lua
The setXYZ method is the only one that is added by wrapping the projector. Also, remember that the hologram projector only supports values up to 32!! NOT 38, like the Wiki says/said/I misread.
Also, the API does NOT work with a Z value of 32. It just doesn't. My binary knowledge is limited.
ALSO, the API will JACK UP if you set a voxel to false that is ALREADY FALSE. This is because it doesn't take into account that the voxel is already false. Similarly, if a voxel is already true, setting it to true again will screw it up.(Hence it's a primitive API. It needs a lot of work. If I had access to the b32 library in Lua then I could probably get around this but alas I have not figured it out.)

THINGS TO REMEMBER
- Only values 1 - 31 are supported.
- This API doesn't take into account any voxels that are false. Be absolutely sure the voxel you're turning off is TRUE in the first place, else the ENTIRE SELECTED COLUMN will be filled. This is the same with setting an already-true voxel to true again.

Have fun making buggy holograms!

I was thinking you could improve upon this API that I made and make it a bit smarter (Most likely with the b32 lib that I can't seem to work), it should help make a more comfortable API for the hologram projector.

**Comment by fnuecke** [comment]
Cool! Thanks for the work on this. But please post APIs and such [on the forum](http://oc.cil.li/index.php?/forum/35-libraries-apis/) instead of in the bug tracker, where people might actually be looking for them :-) Thanks again.

**Comment by skarlitz** [comment]
Oh, I didn't know there was a forum :L
