### ISSUE TITLE
Placing a server rack crashes game, breaks world.

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1642]
Placing a server rack crashes Minecraft, and breaks the world as the game crashes when it loads.
Running latest Forge, and OC version on Minecraft 1.8.9.

[Crashlog Pastebin](http://pastebin.com/TknWR01r)

**Comment by ghost** [comment]
The issue appears to be Optifine related, as it no longer persists with Optifine disabled.

**Comment by fnuecke** [comment]
Yeah, sorry, can't reproduce and OC isn't even in the stacktrace, so I'll have to ask you to tell OF to fix it then :/ (Or have them tell me what OC does that breaks their stuff.)
