### ISSUE TITLE
Errors with Class Transformer

### ISSUE THREAD

**Issue by jhagrid77** [MightyPirates/OpenComputers#1646]
https://docs.google.com/document/d/1v_i1puV-KR-GqOmGsSqSuIL45JaG8Yxmjxbc_riYkdU/edit?usp=sharing

Sorry I have to share it like this since it's 2.2 MB, if it doesn't work here is the file:

[fml-client-latest.txt](https://github.com/MightyPirates/OpenComputers/files/122337/fml-client-latest.txt)

**Comment by LabGoblin** [comment]
i also got this error.
https://www.dropbox.com/s/08j1d93rnsr95qg/latest.log?dl=0
there is my file if needed

**Comment by fnuecke** [comment]
Could you please check if this happens without AcademyCraft, thanks. If it does, let know, otherwise I'll consider this a duplicate of #1509.

@bushbaby1234 Your log doesn't contain any relevant info, I'll need the full one. if you have AcademyCraft installed, see above.
