### ISSUE TITLE
Switch not detected by ComputerCraft (1.8,1.8.9)

### ISSUE THREAD

**Issue by Alaisx** [MightyPirates/OpenComputers#1653]
The OC Switch is not detected as a peripheral by ComputerCraft in Minecraft 1.8 or 1.8.9. There is no issue in 1.7.10. Since this is cross-mod functionality I am not sure which side has the problem, but I am posting here as the Switch is from OC.

The versions I have tested are:
MC 1.8.9 with OC 1.8.9-1.5.22.6 and CC 1.78 - does not work
MC 1.8.0 with OC 1.8-1.5.22.47 and CC 1.76 - does not work
MC 1.7.10 with OC 1.7.10-1.5.16.32 and CC 1.74 - works fine

**Comment by Techokami** [comment]
Gonna take a guess and say that the CC API needs to be re-added for the 1.8.x branches, since CC having any 1.8.x builds is something fairly recent, and OC has been on 1.8.x since modding for that version was possible.

**Comment by MyNameIsKodos** [comment]
Switches are deprecated. Try using a Relay, and see if that works. If not, then yeah, the API might need updating.

**Comment by Alaisx** [comment]
I am at work right now so I can't test a relay, but I did test the Access Point, which had the same results (fine in 1.7.10, not fine in 1.8.x). As you say, it's most likely the CC API.

**Comment by MyNameIsKodos** [comment]
Access Points are deprecated, too. Both were replaced by the Relay, which is upgradable.

**Comment by Alaisx** [comment]
Tested relays just now, same issue. Thanks for the heads up on deprecation though.

**Comment by fnuecke** [comment]
8d45fc41c6fa1951fea44ffc46edb7d98e90de60

**Comment by Alaisx** [comment]
ComputerCraft version 1.80 (beta) is out for Minecraft 1.9.4. The OC relay is once again not detected by this new CC version (I assume the same problem as last time... new CC API?). No rush, but it would be pretty great to have both mods playing together in MC 1.9.4.
