### ISSUE TITLE
thaumcraft api is outdated

### ISSUE THREAD

**Issue by MalkContent** [MightyPirates/OpenComputers#1655]
doesn't interact with tc5 :|

**Comment by Techokami** [comment]
Is TC5 marked stable?

**Comment by MyNameIsKodos** [comment]
The API will likely be updated once the OC dev is finished porting OC 1.6 to 1.8.9, assuming TC5's API is finished or at least stable by then.

**Comment by fnuecke** [comment]
4c5806eb1a9ddafae2dce86245365961c0fd5912
