### ISSUE TITLE
Suggestion: allow picking up computer cases without ejecting hardware

### ISSUE THREAD

**Issue by MalkContent** [MightyPirates/OpenComputers#1656]
I know ejecting items from inventories when their blocks are broken is normal behaviour, but it feels silly to me that I can't carry a tower around while keeping the hardware inside of it.
Of course the same goes for chests and so on, but these are inventories that are generally meant for and capable of storing a lot of items so it would be a potential balance issue. In the case of computers you are generally creating a more or less permanent unit. :|

**Comment by XFactHD** [comment]
Why not make them wrenchable? Or is that already possible?

**Comment by Vexatos** [comment]
I think this shouldn't be a thing. It's fine that they spill their contents just like chests, in my opinion. If you want a computer that doesn't, use a robot.

**Comment by jhagrid77** [comment]
To be honest I agree with Vexatos, I mean at least it doesn't wipe the HDD's and everything. Besides a few components isn't that bad, unless you have a full inventory.

**Comment by Techokami** [comment]
I'd suggest Jabba integration to use a dolly, but then I remembered that there's no API for dollies, and you have to get a patch manually approved in Jabba's BitBucket repo.

**Comment by MalkContent** [comment]
How about a "Vendor Seal" that finalizes the case and remembers the player who did so, until it's removed.
You could give prebuilds to other players and when they ask for support and the seal is missing you can go "WELL IT WAS WORKING WHEN I GAVE IT TO YOU"
Maybe the added ressource cost (broken seals obviously just vanish) makes portable cases a little more enticing.

**Comment by Vexatos** [comment]
Feel free to make an addon that does that or get someone else to do so. It sounds like something that should rather be an addon.

**Comment by jhagrid77** [comment]
We need more addons.

**Comment by Techokami** [comment]
We need more 1.8.9 compatible addons, that is. ;) (btw good work on the migration of Computronics, Vex)

**Comment by MalkContent** [comment]
Well I wouldn't ask for it here if I thought it would feel like it should rather be in an addon to me.
OCs scrench is available for pick up, in case regular breaking feels to violent. Or just seal it with a good ol' bit o clay and make the inventory inaccessible alltogether.

**Comment by xarses** [comment]
@MalkContent Do you wan't to fold this into #1915 in that we'd work to make it so OC doesn't crash when another mod moves them? If so we can close this.

**Comment by MalkContent** [comment]
nah. it's almost the same but not quite. mighty pirates can feel free to close this any time though

**Comment by payonel** [comment]
there was a suggestion to have a computer case resist the pick axe a bit more, and I suggested we then allow the scrench to "pop" the computer case up more quickly. I think that leaves this request on its own -- so we'll drop it. That and there is the request to have jabba integration. Thanks for bringing this up however
