### ISSUE TITLE
Robot can wrench IC2 machines by an IC2 wrench in plugin-protected areas

### ISSUE THREAD

**Issue by Noire86** [MightyPirates/OpenComputers#1657]
Well, times ago I requested a player-binding for robots to make them griefless for Bukkit claiming plugins.

That works fine for block breaking and using tools by a robot for a large amount of mods, but.. not IC2.

For ex. robot cannot wrench or rotate blocks from TE4, mekanism and others using wrenches from these mods.

But when robot is equipped by an IC2 wrench - he can wrench and rotate machines, no matter which mod from.

So, please, can you check out what it could be? The main thing is that the players themself can safely use wrenches from IC2 on a claimed land - they are working fine and do not any griefing.

My server is techy-oriented with OC priority, and it would be a bad news for everyone that robots are banned now.

Thanks in advance!

**Comment by Noire86** [comment]
In addition: I am using Factions plugin

**Comment by Noire86** [comment]
UPD: Robots can suck items from chests that are protected with the plugin.

**Comment by gjgfuj** [comment]
Probably an ic2 issue I guess. If you pop a ic2 wrench in an autonomous
activator will it work?

**Comment by Landrash** [comment]
@NoireMann Have a look at #1533 Griefing with Robot. 
There's a discussion there about protection from root griefing. In general @fnuecke is attempting to fire any relevant Forge event. If there's any events that has been missed I would suggest asking the creator of factions.

After a quick look I see that you created a issue ticket at the Factions Github.

**Comment by Noire86** [comment]
It is possible to use BlockBreakEvent (or PlayerInteractEvent, but it can be incompatible sometimes), which will need to transfer Fakeplayer and block coordinates. In case of WG or Factions interaction restriction - it is possible to cancel prohibited action. Example of the BlockBreakEvent usage is here:  http://pastebin.com/5L3Cts41

**Comment by sameer** [comment]
Hi, this will be fixed in Thermos B49 (https://github.com/TCPR/Thermos). FakePlayer events will be wrapped from ForgeEventFactory.onPlayerInteract into Bukkit interactions.

**Comment by payonel** [comment]
fixed by update to thermos
