### ISSUE TITLE
Gregtech recipes unavailble 

### ISSUE THREAD

**Issue by warior4356** [MightyPirates/OpenComputers#166]
If I change my recipes to the gregtech set 13 of the blocks/items do not exist. I manage to re enable 5 of them through coping the recipes from the default to user. However a few don't have an entry in the default directory, such as the access point for example.

**Comment by fnuecke** [comment]
Could it be you commented the line including the default recipes? I.e. your user.recipes reads

```
#include file("default.recipes")
include file("gregtech.recipes")
```

?

If so, could you please see if

```
include file("default.recipes")
include file("gregtech.recipes")
```

works as it should? Thanks!

**Comment by warior4356** [comment]
include file("default.recipes")
#include file("gregtech.recipes")
will include all 63 recipes
I even tried switching to the dev build, no change

**Comment by fnuecke** [comment]
Ah, no, I meant keep both enabled - the ones defined later on will overwrite the earlier ones. I'll set up an environment to test it later today, but it'd be nice to have it confirmed directly.

**Comment by warior4356** [comment]
so wait what is the correct way to enable gregteech resipies could you put your user file down I seem to be doing it wrong.

**Comment by warior4356** [comment]
oh wow im a moron i figured it out sorry for bothering you

**Comment by fnuecke** [comment]
So having both lines enabled works? Sorry if that was unclear in the config's comments. I'll add an include for the defaults in the hardmode set, to avoid others falling into the same trap.
