### ISSUE TITLE
oppm installation

### ISSUE THREAD

**Issue by voodoo12** [MightyPirates/OpenComputers#1665]
I can't seem to install oppm onto my computer

**Comment by voodoo12** [comment]
and this ---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.8-1.5.21.42-universal.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 21/02/16 12:50 PM
Description: Unexpected error

java.util.ConcurrentModificationException
    at com.google.common.collect.HashBiMap$Itr.checkForConcurrentModification(HashBiMap.java:339)
    at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:345)
    at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:239)
    at net.minecraft.client.audio.SoundHandler.func_73660_a(SourceFile:195)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2101)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1028)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.google.common.collect.HashBiMap$Itr.checkForConcurrentModification(HashBiMap.java:339)
    at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:345)
    at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:239)
    at net.minecraft.client.audio.SoundHandler.func_73660_a(SourceFile:195)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['voodoo12'/253, l='MpServer', x=11.14, y=74.00, z=321.71]]
    Chunk stats: MultiplayerChunkCache: 210, 210
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: -56.00,64.00,252.00 - World: (-56,64,252), Chunk: (at 8,4,12 in -4,15; contains blocks -64,0,240 to -49,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 24117 game time, 2713 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 83 total; [EntityBat['Bat'/128, l='MpServer', x=12.22, y=21.10, z=354.75], EntityRabbit['Rabbit'/129, l='MpServer', x=15.16, y=71.00, z=370.50], EntityRabbit['Rabbit'/130, l='MpServer', x=0.84, y=92.00, z=381.47], EntityZombie['Zombie'/141, l='MpServer', x=30.63, y=29.00, z=245.38], EntitySpider['Spider'/142, l='MpServer', x=27.50, y=40.00, z=259.50], EntitySpider['Spider'/143, l='MpServer', x=23.16, y=39.00, z=259.81], EntityVillager['Villager'/144, l='MpServer', x=16.81, y=70.00, z=299.38], EntityVillager['Villager'/145, l='MpServer', x=27.34, y=68.00, z=292.66], EntitySkeleton['Skeleton'/146, l='MpServer', x=26.06, y=50.00, z=316.44], EntityVillager['Villager'/147, l='MpServer', x=21.69, y=70.00, z=306.47], EntitySkeleton['Skeleton'/148, l='MpServer', x=22.28, y=11.00, z=335.69], EntitySpider['Spider'/149, l='MpServer', x=31.94, y=55.00, z=322.69], EntitySpider['Spider'/150, l='MpServer', x=19.69, y=51.11, z=320.28], EntitySkeleton['Skeleton'/278, l='MpServer', x=-42.50, y=40.01, z=323.50], EntityRabbit['Rabbit'/151, l='MpServer', x=29.63, y=72.00, z=333.25], EntitySkeleton['Skeleton'/279, l='MpServer', x=-41.50, y=40.01, z=322.50], EntityEnderman['Enderman'/152, l='MpServer', x=21.50, y=32.00, z=344.50], EntityBat['Bat'/162, l='MpServer', x=32.25, y=30.91, z=292.10], EntityVillager['Villager'/163, l='MpServer', x=37.41, y=70.00, z=302.72], EntityVillager['Villager'/164, l='MpServer', x=44.25, y=71.00, z=311.31], EntityZombie['Zombie'/165, l='MpServer', x=45.58, y=63.34, z=310.72], EntitySkeleton['Skeleton'/37, l='MpServer', x=-64.50, y=41.00, z=273.50], EntitySkeleton['Skeleton'/166, l='MpServer', x=41.91, y=63.00, z=329.44], EntitySkeleton['Skeleton'/38, l='MpServer', x=-66.50, y=41.00, z=272.50], EntityZombie['Zombie'/167, l='MpServer', x=36.49, y=69.60, z=324.14], EntityCreeper['Creeper'/168, l='MpServer', x=34.69, y=41.00, z=376.69], EntityRabbit['Rabbit'/40, l='MpServer', x=-64.81, y=63.00, z=274.38], EntityCreeper['Creeper'/169, l='MpServer', x=33.72, y=41.00, z=375.78], EntityRabbit['Rabbit'/170, l='MpServer', x=44.25, y=75.00, z=387.16], EntityZombie['Zombie'/42, l='MpServer', x=-68.50, y=19.00, z=312.50], EntityCreeper['Creeper'/174, l='MpServer', x=56.46, y=34.00, z=255.03], EntityBat['Bat'/175, l='MpServer', x=62.93, y=35.21, z=281.55], EntityVillager['Villager'/176, l='MpServer', x=54.44, y=69.00, z=295.78], EntitySkeleton['Skeleton'/48, l='MpServer', x=-68.50, y=57.00, z=356.50], EntityRabbit['Rabbit'/177, l='MpServer', x=58.47, y=72.13, z=370.92], EntitySkeleton['Skeleton'/49, l='MpServer', x=-68.50, y=57.00, z=357.50], EntityRabbit['Rabbit'/182, l='MpServer', x=64.34, y=72.00, z=356.34], EntityRabbit['Rabbit'/58, l='MpServer', x=-60.91, y=64.00, z=271.53], EntityRabbit['Rabbit'/60, l='MpServer', x=-63.81, y=63.00, z=273.56], EntitySquid['Squid'/62, l='MpServer', x=-49.87, y=60.52, z=280.28], EntityBat['Bat'/63, l='MpServer', x=-53.77, y=22.56, z=318.39], EntityCreeper['Creeper'/64, l='MpServer', x=-53.50, y=45.00, z=304.50], EntityCreeper['Creeper'/65, l='MpServer', x=-50.28, y=39.00, z=310.28], EntitySpider['Spider'/193, l='MpServer', x=87.50, y=18.00, z=265.50], EntityZombie['Zombie'/194, l='MpServer', x=83.78, y=36.00, z=307.84], EntityZombie['Zombie'/195, l='MpServer', x=90.50, y=17.00, z=379.50], EntityBat['Bat'/69, l='MpServer', x=-49.42, y=25.38, z=347.60], EntityBat['Bat'/70, l='MpServer', x=-48.24, y=26.88, z=346.73], EntityBat['Bat'/71, l='MpServer', x=-50.47, y=25.55, z=345.46], EntityRabbit['Rabbit'/73, l='MpServer', x=-36.69, y=67.00, z=270.31], EntityRabbit['Rabbit'/74, l='MpServer', x=-35.50, y=67.00, z=267.50], EntitySquid['Squid'/75, l='MpServer', x=-44.22, y=60.89, z=287.79], EntitySquid['Squid'/76, l='MpServer', x=-47.01, y=62.29, z=290.42], EntitySquid['Squid'/77, l='MpServer', x=-45.82, y=61.02, z=295.26], EntityRabbit['Rabbit'/78, l='MpServer', x=-33.66, y=63.00, z=297.69], EntityCreeper['Creeper'/79, l='MpServer', x=-32.50, y=25.00, z=311.50], EntitySkeleton['Skeleton'/80, l='MpServer', x=-34.50, y=28.00, z=318.50], EntityBat['Bat'/81, l='MpServer', x=-46.02, y=24.65, z=351.27], EntityZombie['Zombie'/82, l='MpServer', x=-36.50, y=53.00, z=351.50], EntitySkeleton['Skeleton'/83, l='MpServer', x=-33.50, y=25.00, z=374.50], EntityRabbit['Rabbit'/86, l='MpServer', x=-19.69, y=69.00, z=263.69], EntityRabbit['Rabbit'/87, l='MpServer', x=-24.50, y=68.00, z=269.72], EntityRabbit['Rabbit'/88, l='MpServer', x=-18.69, y=69.00, z=283.31], EntityRabbit['Rabbit'/89, l='MpServer', x=-25.00, y=67.00, z=299.47], EntityRabbit['Rabbit'/90, l='MpServer', x=-28.47, y=64.00, z=291.53], EntityBat['Bat'/91, l='MpServer', x=-29.53, y=26.10, z=309.47], EntitySkeleton['Skeleton'/92, l='MpServer', x=-20.50, y=34.00, z=337.50], EntityBat['Bat'/361, l='MpServer', x=9.33, y=23.01, z=347.58], EntityRabbit['Rabbit'/106, l='MpServer', x=-15.44, y=69.00, z=277.53], EntityItem['item.item.bone'/107, l='MpServer', x=-13.19, y=68.00, z=286.72], EntityItem['item.item.arrow'/108, l='MpServer', x=-13.69, y=68.00, z=285.31], EntitySkeleton['Skeleton'/109, l='MpServer', x=-2.72, y=25.00, z=292.59], EntitySkeleton['Skeleton'/110, l='MpServer', x=-1.89, y=25.00, z=292.38], EntityEnderman['Enderman'/111, l='MpServer', x=-12.50, y=53.00, z=337.50], EntityEnderman['Enderman'/112, l='MpServer', x=-13.50, y=53.00, z=337.50], EntityBat['Bat'/121, l='MpServer', x=8.34, y=31.10, z=257.75], EntityRabbit['Rabbit'/122, l='MpServer', x=11.44, y=65.13, z=276.11], EntityRabbit['Rabbit'/123, l='MpServer', x=15.41, y=70.00, z=288.56], EntityVillager['Villager'/124, l='MpServer', x=1.28, y=70.00, z=321.69], EntityVillager['Villager'/125, l='MpServer', x=2.31, y=70.00, z=321.59], EntityPlayerSP['voodoo12'/253, l='MpServer', x=11.14, y=74.00, z=321.71], EntitySkeleton['Skeleton'/126, l='MpServer', x=14.50, y=42.00, z=345.50], EntityEnderman['Enderman'/127, l='MpServer', x=14.50, y=32.00, z=343.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:374)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 182365640 bytes (173 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 5 mods loaded, 5 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8-11.14.4.1563.jar) 
    UCHIJAAAA   Forge{11.14.4.1563} [Minecraft Forge](forge-1.8-11.14.4.1563.jar) 
    UCHIJAAAA   OpenComputers|Core{1.5.21.42} [OpenComputers (Core)](minecraft.jar) 
    UCHIJAAAA   OpenComputers{1.5.21.42} [OpenComputers](OpenComputers-MC1.8-1.5.21.42-universal.jar) 
    Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.8-1.5.21.42-universal.jar)
  li.cil.oc.common.asm.ClassTransformer
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.2.11931 Compatibility Profile Context' Renderer: 'ATI Radeon HD 5400 Series'
    Launched Version: 1.8-forge1.8-11.14.4.1563
    LWJGL: 2.9.1
    OpenGL: ATI Radeon HD 5400 Series GL version 4.2.11931 Compatibility Profile Context, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
```

**Comment by jhagrid77** [comment]
What do you mean you cannot install OPPM?

**Comment by jhagrid77** [comment]
Is there an error or something?

**Comment by fnuecke** [comment]
I'm afraid this is a pretty useless report. You'll have to provide some more details, context, how to reproduce etc.
