### ISSUE TITLE
component.gpu.reverse()

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#1668]
component.gpu.reverse() should swap foreground and background color. It should be much faster than getting+setting bg/fg, as it uses less packet data. This would be useful to make a less stupid cursor.

This _does_ work tho: http://sprunge.us/YUNN

**Comment by payonel** [comment]
your example code is similar to what we now have in term: https://git.io/v21v9

**Comment by fnuecke** [comment]
I don't know. I don't really see any other usecases besides the cursor thinger, and for that it seems a little excessive to add a new method and all the overhead that entails (networking and so on).

Do you have more examples where this might be actually useful?

**Comment by SoniEx2** [comment]
It can be used as an optimization when drawing ASCII art, as the callrate would be higher.

**Comment by MyNameIsKodos** [comment]
It would also be useful for having flashing text, such as an urgent warning or something.

**Comment by skyem123** [comment]
Honestly, I want it because it seems like a nice thing to have, and it's another thing that people can use to squeeze more performance out of OC.

**Comment by SoniEx2** [comment]
Also, most terminals have an escape sequence called "reverse video", which swaps foreground and background. (ANSI uses `\e[7m` for reverse on and `\e27m` for reverse off, see [here](https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_codes), the "SGR (Select Graphic Rendition) parameters" section)

**Comment by payonel** [comment]
the benefit of adding the api is too small for the complexity increase to our gpu api

**Comment by skyem123** [comment]
Would it really be that complex? O_o
