### ISSUE TITLE
[Feature-request] 3d printing expansion

### ISSUE THREAD

**Issue by Aedda** [MightyPirates/OpenComputers#1670]
Before I start I am aware of issues #1355 and #1592

This request may overlap aspects of those requests. I've been having a lot of fun with 3d printing and it is really amazing as it is but I could not help but think of some things that I would find nice if included.

Also to note I am not suggestion the addition of states, keeping the On or Off, True/False system that is already in place.

1) Doors, as mentioned. Or rather a setting on a print to share its state with named counterparts. e.g. shared_state="Door Oak" inside the model file for each "piece" then whatever state one is changed to it would carry over to the others with the same shared_state name. This would allow for an extensive amount of creativity such as 1x1 to 12x12 doors. Draw bridges, and vanishing catwalks.

2) Setting for being climbable like vines, ladders, etc. tied to the default state would allow for ladders that could be walked through in one state, climbable in the other. Would allow for mock rope ladders that hang down in one state and vanish in the other when combined with 1 above.

3) Setting for touch trigger, player, mob, monster, item. same as activating it as a button/etc.

**Comment by gjgfuj** [comment]
I agree, these ideas are great! the 3rd one I'm not sure about, but the top two are good. Good on you.

**Comment by Belgabor** [comment]
Let me add a few =)
I want to support fluid bits in Belgabor/ChiselsBytes#2, for that I'd like (if possible)

4) Semi-translucency, possibly on a per shape basis
5) Separate textures per side per shape (still on top, flowing on the side)
6) Not absolutely necessary, but would be nice: collision per shape. Swimming effect I don't really consider necessary, but would certainly make it perfect.

**Comment by payonel** [comment]
we prefer to not add more functions to 3d prints. there have been a huge number of very creative ideas and we appreciate the feedback. I think expanding the 3d printing is going to have be an add-on
