### ISSUE TITLE
Architecture.onSignal can cause an easy deadlock for Architecture programmers

### ISSUE THREAD

**Issue by ds84182** [MightyPirates/OpenComputers#1672]
Currently onSignal gets called while the signal queue is synchronized/locked. This is a problem because someone may choose to lock an object inside their Architecture in order to properly deliver an event to whatever their arch is asynchronously (since the calling thread for onSignal can be unpredictable). When working on my ARM arch, I encountered a deadlock between the Server Thread and a Computer thread by attempting to pop a signal in the Computer thread while attempting to lock my ARM core so I can issue an interrupt.

This can be fixed by moving the onSignal call outside of the synchronization block in Machine.signal.

**Comment by fnuecke** [comment]
Makes sense, done!
