### ISSUE TITLE
[Feature Request] Boot Device Key/Better Mounts

### ISSUE THREAD

**Issue by Elsys656** [MightyPirates/OpenComputers#1673]
or configurable post keys in standard eeprom. Standard case would be a floppy and hard drive or 2 hard drives and a floppy. A post key configurable that can select device to boot from explicitly on boot. Also a key combination to reset the eeprom to default in case operating system install fails for some reason like a game crash.

Better mounting utility that can mount a directory as a separate drive think linux mounts or logical partitions.

**Comment by jhagrid77** [comment]
I like most of this, but Tier 1 case shouldn't have the floppy, as back then if you bought a computer you needed to buy a floppy drive too (look at the Commodore 64).

**Comment by dgelessus** [comment]
Isn't there a boot manager called OpenLoader that basically allows you to do this? It comes with Plan9k by default, but you can use it with any operating system. Only difference to what you're suggesting is that the selection prompt is displayed on every boot and not just when you press a specific key.

Resetting an EEPROM can be done by clearing it and crafting it back into a standard Lua EEPROM.

What exactly do you mean with mounting a directory as a separate drive? You can already mount drives anywhere in the filesystem like on Unix, and to "redirect" directories you have symlinks.

**Comment by jhagrid77** [comment]
I guess I didn't read everything, but @dgelessus is right.

**Comment by Elsys656** [comment]
Boot device selection would run as a part of the eeprom before anything else loads, idea is to make the system recoverable in case a primary device fails. Unless this is already possible somehow like BIOS in most modern pc's work.

as for the boot devices themselves being available they are only present if actually available for use

moreover the reason this is in the bugtracker is so that if such an addition is accepted it can be added as a standard feature

**Comment by magik6k** [comment]
There is OpenLoader floppy with opl-flash program which will flash custom eeprom with boot selection.

**Comment by fnuecke** [comment]
Wonderful, use that then :)
