### ISSUE TITLE
class transformer errors

### ISSUE THREAD

**Issue by kotoroshinoto** [MightyPirates/OpenComputers#1676]
game informed me that I should report this.

[fml-client-1.log.txt](https://github.com/MightyPirates/OpenComputers/files/149874/fml-client-1.log.txt)

this one should have the same information as the current one, been seeing the message for a while.

If you need more or a different log just let me know.

**Comment by fnuecke** [comment]
> Missing implementations for interface buildcraft.api.tools.IToolWrench

Should be fixed in the latest builds.
