### ISSUE TITLE
Infinite Filesystem Issue

### ISSUE THREAD

**Issue by Reginald-Halifrax** [MightyPirates/OpenComputers#1677]
While trying to make a backup of a world i used open computers in i ran into a "Source path too long" error, i moved everything in the folder away till it wouldn't allow me any further. to find a directory from opencomputers was the one at fault.

With a directory reading /mnt/c90/mnt/c90/mnt/c90/ (Etc...) which presumably was from me attempting to copy over the contents of a hard disk to another so i could upgrade. presumably this was because it caused a copy paste loop.

Any chance that could be a easy fix? perhaps make a copy lock for how much you can do at any one time? and then maybe just have a easier way to move data from one to another?

I'd greatly appreciate it.

**Comment by gjgfuj** [comment]
i wonder if the copy could not copy through mount points......

**Comment by Reginald-Halifrax** [comment]
Well from my guess somehow when i was copying from the mount into the system IN the mount... which i guess could potentially start looping

**Comment by payonel** [comment]
Can you try using cp -x to not copy across mount points? Also, OpenOS 1.6 cp -x is improved, we may need to test your use case against the updated cp.

**Comment by fnuecke** [comment]
Wait, are we talking in-game or out-of-game? If the latter, I'm assuming a recursion loop happened ingame and the result then got saved to the real FS. I suppose adding a max nesting depth for directories enforced by OC itself could make sense and prevent stuff like this.

**Comment by payonel** [comment]
`cp -x ...` definitely protects from this scenario.
