### ISSUE TITLE
RAM size doesn't update when RAM changed in a running server

### ISSUE THREAD

**Issue by iamgreaser** [MightyPirates/OpenComputers#1678]
Fairly self-explanatory: while yanking out all the RAM from a running case will make it crash, yanking it out of a running server does nothing.

Making your in-game computer crash in this way is actually useful for debugging stuff in OCMIPS.

**Comment by XFactHD** [comment]
I don't understand how you get the RAM out of the server without taking the server out of the rack?

**Comment by iamgreaser** [comment]
You can right-click on the server while it's on the rack.

**Comment by XFactHD** [comment]
Oh, didn't know that.

**Comment by gjgfuj** [comment]
It's a relatively new feature, so doesn't surprise me that they don't check
for removal of RAM in a server.

**Comment by fnuecke** [comment]
The thing is, it does, at least for me :P greaser mentioned (on IRC) he's on an older version, so I'm hoping just updating will fix it.

**Comment by fnuecke** [comment]
@iamgreaser had a chance yet to check if this still happens on the latest builds?

**Comment by iamgreaser** [comment]
Yeah, it seems to be fixed, sorry I forgot to mention it here.
