### ISSUE TITLE
Robot getting reporting "impossible" while attempting to move vertically in open air

### ISSUE THREAD

**Issue by WhatDaFoxx** [MightyPirates/OpenComputers#1682]
Most up to date version of OpenComputers being used in Infinity pack

I have a robot miner with a chunk loading upgrade that can mine horizontally for as many blocks as I tell it to as well as vertically down but when the robot attempts to return to its' starting point along the vertical path it will get stuck at seemingly random spots. It will report:

nil, "impossible" when i manually instruct it to robot.up() in the Lua prompt.

If I cause a block update in directly below the robot by placing a torch then the robot is able to move fine and continues upward until getting stuck again.

**Comment by Dylanavo** [comment]
Is this possibly due to the robot flight height limitations? Unless you change the config setting or have a hover upgrade, the robot can only move 8 blocks high from a surface. Placing a torch below it is possibly giving it another surface to ascend from.

**Comment by WhatDaFoxx** [comment]
My apologies, that was exactly the issue.
