### ISSUE TITLE
Bad Mod Interaction with Thaumcraft

### ISSUE THREAD

**Issue by MalkContent** [MightyPirates/OpenComputers#1683]
no idea who/what's at fault, but I thought I'd draw you in on it

in short: one of thaumcraft's guis is messed up when opencomputers is present

https://github.com/Azanor/thaumcraft-5/issues/464

**Comment by fnuecke** [comment]
OC's TC integration was completely disabled in MC1.8*, so I doubt it was related, but either way, updated the API and reenabled the integration in 4c5806eb1a9ddafae2dce86245365961c0fd5912.

**Comment by MalkContent** [comment]
I don't think this issue had to do with api problems. Anyways, it's solved on TC side.
