### ISSUE TITLE
Crash at Open robot interface

### ISSUE THREAD

**Issue by Scornexon** [MightyPirates/OpenComputers#1685]
when i place a robot on the ground and try to open the inteface of the robot my minecraft crash.
it dont happend everytime, but i cant figure out why it sometimes crashes.
here is the crash log i get: http://pastebin.com/TzCbZ8K7

**Comment by Landrash** [comment]
Does it crash without optifine?

**Comment by fnuecke** [comment]
That

>  at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)

in the traceback sounds very trustworthy :P In all seriousness though, mind trying if this still happens without that?

**Comment by Rohrschneider** [comment]
hallo it crash to without optifine.

**Comment by Landrash** [comment]
@Rohrschneider Can you provide the crash log you get without optifine? The first one indicates that optifine had a hand in your problem and it's unlikely that you will get the same problem without it.

**Comment by fnuecke** [comment]
Please see if this still happens in the latest build.
