### ISSUE TITLE
__gc is still not fully fixed

### ISSUE THREAD

**Issue by ds84182** [MightyPirates/OpenComputers#1686]
In reference to c762129.

If you run this code, it should still run the GC callback:

``` lua
local gc_mt = {}
local gc_breakout = setmetatable({}, gc_mt)
function gc_mt.__gc()
print("GC!")
end
```

In fact, this code is even more broken because it could potentially affect every single OC version, since __gc() doesn't run with the debug hooks applied when set like this.

I have no clue how you could fix this, other than wrapping ALL tables inside a proxy metatable that always returns nil for "__gc" and proxies the rest to the underlying metatable. The current setmetatable proxy breaks a lot of behavior pertaining to updating a metatable after setting it.

I would also suggest that you override gc callbacks and insert gc calls into a queue to be processed, and a weak table that would keep the gc callback state (since the gc callback would have to be called twice to actually clean up the object)... The table of weak tables to GC state are cleared out in case the GC actually fails (for example, an __gc method that makes a strong reference to the object being collected).

Reference Implementation of GC Queue:

``` lua
local gc_queue = {}
local weak_gc_keys = setmetatable({}, {__mode="k"})
local function enqueue_gc(v)
    if not weak_gc_keys[v] then -- if we already processed the gc queue func and can still remove the table... don't add it to the gc queue
        gc_queue[#gc_queue+1] = {getmetatable(v).mt.__gc, v}
        weak_gc_keys[v] = true
    end
end
local function gc_queue_mt_index(t, i)
    if i == "__gc" and t.mt.__gc then return enqueue_gc end
    return t.mt[i] -- Or something way more secure...
end

function newsetmetatable(v, mt)
    local newmt = setmetatable({mt=mt}, {__index=gc_queue_mt_index}) -- In the real impl you would cache this metatable above. I'm just lazy~
    return setmetatable(v, newmt)
end

-- then in newgetmetatable, you do the same metatable unboxing magic as before~ (except you check to see if the metatable's metatable is correct

-- then all the way down at where collectgarbage is, process and empty the gc_queue
for i=1, #gc_queue do
    local gcqo = gc_queue[i]
    gc_queue[i] = nil
    gcqo[1](gcqo[2]) -- You should totally pcall here, but w/e~
end
-- collect garbage like normal
collectgarbage()
-- then unset all the values in weak_gc_keys that still exist
for o in pairs(weak_gc_keys) weak_gc_keys[o] = nil end
```

The one flaw that I see right now is that gc callbacks are processed one collectgarbage invocation late... But hey, GC is a bit "random", right?

**Comment by payonel** [comment]
You have truly thought this out, and I enjoy this discussion. I fear I'm horribly oversimplifying something, but why not override setmetatable in machine.lua to do this:

```
function sandbox.setmetatable(user_table,mt)
  setmetatable(user_table,{mt=mt,__index=function(_,key)
    if key == "__gc" then return end
    return mt[key]
  end})
end

function sandbox.getmetatable(user_table,mt)
  local rt = getmetatable(user_table)
  return rt and rt.mt
end
```

_EDIT_ please note that I know there is more to set|getmetatable, I'm just trying to focus on just this gc issue

**Comment by ds84182** [comment]
@payonel __index would get called for accesses in user_table with that code

**Comment by ds84182** [comment]
I just tested that part though, and it seems that metamethods for a metatable do not get called at all. I'll devise a better way to do the metatable proxy then.

**Comment by payonel** [comment]
HA, yeah oops, I over simplified my idea :) I meant to set the meta table on the meta table... I'd edit and fix to show what I meant, but -- well, that ship has sailed.

THE SHAME!

**Comment by payonel** [comment]
I also tested this, and I have the same conclusion, meta-metas are not called :(
In fact, rawget isn't even used on metatables (I read it is code in the lua interpreter for efficiency)

So what about something like this:

```
local function setmt(_tbl, _mt)
  if type(_mt) ~= "table" then return setmetatable(_tbl, _mt) end

  local function gen(key)
    return function(...)
      local handler = _mt[key]
      if type(handler) == "function" then return handler(...) end
      return handler
    end
  end

  local rt = {mt=_mt}
  rt.__pairs = gen("__pairs")
  rt.__ipairs = gen("__ipairs")
  rt.__index = gen("__index")
  rt.__newindex = gen("__newindex")
  rt.__len = gen("__len")

  return setmetatable(_tbl, rt)
end

local function getmt(_tbl)
  local rt = getmetatable(_tbl)
  return rt and rt.mt
end
```

The idea is to just not map __gc -- yes there are other metamethods, thought this was a reasonable demonstration.

**Comment by SoniEx2** [comment]
This shouldn't happen. The Lua manual says __gc only works if it exists at the time of setmetatable().

Edit: Did you actually test? Oh and __gc doesn't run with debug hooks AT ALL. See #1606 and #1632

**Comment by ds84182** [comment]
@SoniEx2 Did you even read the fucking issue? Sure, __gc only works at the time at setmetatable, but there are still two other problems.

**Comment by payonel** [comment]
i've decided that oc will not support custom gc for user code (we already don't, i'm just saying i'm not going to add a queue of gc calls)
there is no issue with our current gc intercept, the same mt table provided is kept on the object, we simply drop the gc from the registry for the object
the sample code on this ticket does not invoke a gc call - not in our machine nor in real lua
