### ISSUE TITLE
Deprecate built-in HTTP, reimplement in software, add TLS wrappers

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#1687]
So can we get a "built-in" (on the crypto card) TLS socket wrapper and deprecate HTTP (reimplement it with raw sockets)?

That way you'd need a crypto card to be able to do HTTPS which sounds reasonable, also less config options which makes OC easier to configure.

**Comment by SoniEx2** [comment]
Notes on wrapping to TLS vs connecting to TLS:
- Wrapping lets you switch to TLS mid-connection. See StartTLS.
- Wrapping is more realistic.
- You can still implicitly wrap to TLS when connecting. (e.g. a boolean argument that when set to true automatically wraps for you)

**Comment by skyem123** [comment]
To be honest, if it's just access to the internet, TLS shouldn't be treated differently to raw sockets, because it makes no difference in gameplay (and HTTPS should be used everywhere on the **real** internet, and in fact, some sites, such as dropbox, block non HTTPS traffic!).

**Comment by SoniEx2** [comment]
We have no TLS currently.

Oh and the crypto card is too slow for practical TLS/reimplementing OpenSSL in OC. Not counting the lack of real life time source... (needed for cert stuff and things like that)

**Comment by skyem123** [comment]
It has (limited) HTTPS currently, though.

**Comment by SoniEx2** [comment]
How about a solution which lets you decide whether you want safe (read: validated) HTTPS or unsafe (read: cert returned with request, together with a "valid" flag) HTTPS?

Hint: TLS Wrappers.

Also what if I need StartTLS/StartSSL?

**Comment by skyem123** [comment]
You're seeming to suggest HTTPS that requires an extra card besides the internet card, though. (shown by the "Deprecate")

**Comment by SoniEx2** [comment]
We could have TLS wrapping as part of the internet card, but still deprecate HTTP and HTTPS for a Lua-based version. That way we can also throw functions, tables, coroutines around and stuff.

**Comment by skyem123** [comment]
In that case, I agree that TLS wrapping should be part of the internet card. Though I do think that moving HTTP(S) to Lua only would break things, **but** it would be _very_ nice if it was possible to HTTP and HTTPS (and other TLS based protocols) with Lua.

**Comment by payonel** [comment]
if we add ssl support, it would be on top of the current `request` and `connect` api for the internet card. https methods could then be supports
see #761 and #1938
