### ISSUE TITLE
[BUG] Immersive Engineering MV and HV capacitor is not queryable

### ISSUE THREAD

**Issue by hron84** [MightyPirates/OpenComputers#1688]
I'm trying to make a universal energy storage reader API, but ImmersiveEngineering's capacitors behaves weird.
LV capacitor can be read without any issue, but MV or HV capacitors returns with `nil` and "unknown error" when I try to use  `object.getEnergyStored()` or `object.getMaxEnergyStored()` calls.

ImmersiveEngineering 0.7.3
OpenComputers 1.5.22.46

**Comment by gjgfuj** [comment]
Wouldn't this be IE's side?

**Comment by hron84** [comment]
I have absolute no idea. All the capacitors otherwise works a correct RF provider/receiver, just OC has an issue with them. But I remember Calculator had a very similar issue with interaction between its wireless energy transmitter devices and IE capacitors, these capacitors behave a bit weird.

**Comment by gjgfuj** [comment]
RF provider and receiver, sure. But that's not getEnergyStored. IE iirc
works on IF, which is different to RF in some way I believe. I'd have to
look at it to make sure, but its very likely IE not supporting
getEnergyStored getMaxEnergyStored properly.
Though I wonder why it works with the LV but not others.....

**Comment by hron84** [comment]
@gjgfuj If I remember correctly, Immersive moved to IF only in 1.8, for 1.7 it is still uses RF and thus it should provide all RF interfaces to work.

**Comment by gjgfuj** [comment]
What version are you running?

**Comment by gjgfuj** [comment]
Wait nvm.

**Comment by gjgfuj** [comment]
Ok, the IE code implements getEnergyStored and getMaxEnergyStored just
fine. So it's not that. Does anything show up in the server log when you
call it?

**Comment by hron84** [comment]
Yeah, a NPE from [here](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/util/compat/opencomputers/CapacitorDriver.java#L84)

**Comment by gjgfuj** [comment]
Oh, so that /is/ on IE's side. Well in that case, report it to IE.

**Comment by fnuecke** [comment]
TIL IE has native integration with OC :P But yeah, in that case this needs a null-check / fix on IE's end, please report it to them, thanks!

**Comment by hron84** [comment]
Reported, BluSunrize/ImmersiveEngineering#1014
