### ISSUE TITLE
[QUESTION] Tank infos?

### ISSUE THREAD

**Issue by hron84** [MightyPirates/OpenComputers#1690]
I'm just wonder if there is any integration with generic fluid containers (Forge [FluidTanks](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fluids/FluidTank.java), since I cannot get info for them.

For CC, [this is how it is implemented](https://github.com/OpenMods/OpenPeripheral-Integration/blob/master/src/main/java/openperipheral/integration/vanilla/AdapterFluidTank.java)

**Comment by gjgfuj** [comment]
There is, apparently. "Fluid_tank.getInfo()", and
"fluid_handler.getTankInfo(side)"

**Comment by Vexatos** [comment]
1) OpenPeripheral works with OC too
2) There is a tank controller upgrade. Tank Controller Upgrades and Transposers are there for this purpose.

**Comment by gjgfuj** [comment]
1. No it doesn't.
2. Oh yeah that exists, use that.

**Comment by Vexatos** [comment]
@gjgfuj It does. OpenPeripheral has had an OpenComputers integration for months.

**Comment by gjgfuj** [comment]
It technically does. But it doesn't, really.

**Comment by fnuecke** [comment]
Also, for future reference, please keep support questions (as opposed to bugs/feature requests) to IRC or the forums, thanks.

**Comment by hron84** [comment]
So I need OpenPeripherals for tank support? OC does not support on its own?

**Comment by gjgfuj** [comment]
No, you put the tank controller upgrade in your adapter and you can access
the tank through that.

**Comment by hron84** [comment]
Cool, thx.
