### ISSUE TITLE
Reika's mods power support

### ISSUE THREAD

**Issue by RobertCochran** [MightyPirates/OpenComputers#1695]
Support for RotaryCraft shaft power and/or ElectriCraft electric power would be nice.

**Comment by gjgfuj** [comment]
I thought there was a reason it wasn't accepted.....

**Comment by fnuecke** [comment]
The only reason I remember was that it is kinda weird plugging a shaft into a computer; but frankly it's a power system like any other, and ideally you'd use a power converter anyway, so whatever.
