### ISSUE TITLE
[Suggestion] A few small suggestions

### ISSUE THREAD

**Issue by JomerDev** [MightyPirates/OpenComputers#1697]
This is a small collection of a few suggestions I have.
Most of them enable robots to do more, maybe even enabling them to replicate themself (Robot Colonies anyone?) 
- Allow robots to edit servers (meaning the could add components to servers, maybe with the assembler)
- Add server rack functions, so the connections from each server to a side can be done with methods. 
  Maybe also add functions to start a specific server

Also, it would be so great if #450 could become reality.

I don't really care if these suggestions cost a great ammount of ingame ressources, as long as they are obtainable by robots :D

**Comment by fnuecke** [comment]
- The inventory controller allows interacting with supported item inventories in 1.6 (which includes servers) via `ic.dropIntoItemInventory`/`ic.suckFromItemInventory`.
- Ehh, I don't want magically self-reconfiguring server racks, and robots, well, they can't interact with external APIs anyway, so. Even if, I prefer to keep the racks "hand-configured", frankly.
- Mobile holos would be wonderful, I agree. If only it weren't such a PITA to implement :P
