### ISSUE TITLE
The Power Converter

### ISSUE THREAD

**Issue by xJon** [MightyPirates/OpenComputers#1702]
Can the [Power Converter](http://ocdoc.cil.li/block:power_converter) also be used to convert RF to other kinds of power?
As I see it, it can only be used to convert other kinds of power to RF. But why? it can be really useful to have a power converter block from OpenComputers.

**Comment by LizzyTrickster** [comment]
The power converter block in OC converts RF/MJ/EU/Stuff into OC's
electrical unit that can't be
 converted to any other types of power

**Comment by MyNameIsKodos** [comment]
Fun fact: You can stick stuff in an OC Charger to charge them. I use my OC charger for things like Mekanism Energy Cubes, various tools, etc

**Comment by LizzyTrickster** [comment]
Huh, didn’t know that

**Comment by MyNameIsKodos** [comment]
![Yep!](http://puu.sh/nQYRR/b3f3eada57.png)

**Comment by fnuecke** [comment]
Yeah, it supports a number of power storing items. This is the midway I decided to accept for "outputting" energy again. I don't want OC to be an explicit power conversion mod, so this is the best you'll get out of me :P
