### ISSUE TITLE
Suggestion: Make OpenComputers a Realistic Mod

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1703]
MAKE IT A REALISTIC MOD
1.  RAID Controller (Expansion Card)
Description: An expansion card which takes over the storage devices (HDDs and SSDs) to install in a RAID Type of Storage.
Function: Controlling and Modifying RAID within the system.
Changes: Internal type of RAID or replacing old RAID 0 Block. RAID 0, 1 and 10 (4 HDD/SDD Slot) Support
2.  Optical Disk Drive
Description: Second Tier type of Removable storage
Function: Carries more than floppy disk (2x)
3.  USB Port
Description: Third Tier type of Removable Storage + Adapter Type of connection
Function: Carries more than Optical Disk Drives can (1.5x)
4.  Multi-GPU or SLI / AMD Crossfire
Description: Carries more processes and more output
Function: Gives boost within color, and resolution
5.  Multi-CPU
Description: Give more power or performance especially for background apps
6.  Dual-/Triple-/Quad-Channel RAM
Description: RAID 0 type of RAM but priorities more on performance
7.  Multi-Monitor
Description: Better for Editing within long or wide range of stuff.
8.  CPU
Changes: Added supported background running codes limits
9.  FAN and Temperature
Description: Add temperature within the casing of a computer for limitations and explosion
10. Audio Card
Description: Add .ogg playback within other music other than minecraft
11. Motherboard
Changes: Different Features like number of Expansion Supported, CPU supported, RAM slots and HDD. Better separate Motherboard from computer case.
12. SSDs
Addition: Less storage but more speed in reading files
13. Laptop
Description: Portable and more powerful than Tablet but power consumes more than Tablet

**Comment by ghost** [comment]
It sound good

**Comment by ghost** [comment]
yeah it is better

**Comment by ghost** [comment]
I know right

**Comment by ghost** [comment]
Hahaha

**Comment by ghost** [comment]
I hope @fnuecke  will change it

**Comment by ghost** [comment]
Yah right

**Comment by ghost** [comment]
So Cool

**Comment by fnuecke** [comment]
#1043
