### ISSUE TITLE
looking for help

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1704]
im looking for someone to help me setup a computer and run some of the open programs. im new to this mod and it seems to be awesome if i can just figure out some thin.

**Comment by Landrash** [comment]
Use the forums instead. The github Issue tracker is for reporting bugs, suggestions of features etc.
Forum is available at [oc.cil.li](https://oc.cil.li/index.php?/index)

**Comment by fnuecke** [comment]
^ That. Please use the forums or IRC (#oc on esper.net) for this.

**Comment by lordjoda** [comment]
Or to make shameless self advertisement ;) have a look at our YouTube Tutorial Series: https://youtu.be/KDqXJzacdQQ?list=PLcZKee5-koAC2-pKrE6NOycvfX-KMm013
