### ISSUE TITLE
Parts of the file name validation are turned off alongside buffering when it is disabled.

### ISSUE THREAD

**Issue by Lymia** [MightyPirates/OpenComputers#1707]
[Some of the code for sanitizing file names](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/fs/FileSystem.scala#L165) is in the class for buffered filesystems. This results in some of the file name checking being skipped when buffering is off. These checks should probably be moved to FileSystem.clean or something.

When buffering is disabled on Linux servers, combined with #1708, this can be used to delete the files in all computers in the world. On Windows servers, the same configuration change lets you outright read and write any file to the server the Minecraft server has access to, since com.google.common.io.Files.simplifyPath doesn't handle filenames using \ as the path seperator instead of /.

**Comment by fnuecke** [comment]
Thanks for reporting this. Pulled the validation out of the buffered system and using it all over the place now (well, where necessary). Review would be appreciated. Thanks again!
