### ISSUE TITLE
li.cil.oc.server.component.FileSystem.clean does not handle the string ".." correctly.

### ISSUE THREAD

**Issue by Lymia** [MightyPirates/OpenComputers#1708]
[li.cil.oc.server.component.FileSystem.clean](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/component/FileSystem.scala#L321) doesn't properly filter out the string "..", as com.google.common.io.Files.simplifyPath("..") == "..", which it does not check for.

**Comment by fnuecke** [comment]
Ah, guess I assumed it'd append the `/` in that case. Thanks for pointing that out!
