### ISSUE TITLE
Creative-Tier Computer Case

### ISSUE THREAD

**Issue by MyNameIsKodos** [MightyPirates/OpenComputers#171]
I'd like to see a creative-tier computer case, which would basically be the same as a Tier 3, except the 2nd HDD slot would be T3, as would the 2 secondary card slots.  Perhaps in the future, make additional cards that would require T3 slots, but would be for use by a server admin for use on SMP. I dunno.  I'm mainly posting this because I want two T3 HDDs in my computer because I'm OCD and different colors make me nuts.

**Comment by awsmazinggenius** [comment]
"I'm OCD and different colors make me nuts."
Then use Tier 2 equipment.

**Comment by MyNameIsKodos** [comment]
I've used T2, and I prefer the power and potential of T3.  Thank you for that utterly useless advice, though.

**Comment by asiekierka** [comment]
We should integrate the OpenBlocks Painter with Computer Cases.

Or add Metallurgy support.

**Comment by fnuecke** [comment]
Hmm, it should be relatively easy to make blocks and items dyeable (the first until broken - I'd like to avoid NBT in item blocks - the second more permanent). It might look crappy unless I adjust the textures, though, to work well with custom color multipliers. I'll look into it when I have the time.

**Comment by asiekierka** [comment]
Idea: Make them dyeable with mod metals. Would make them immensely more useful.

**Comment by MyNameIsKodos** [comment]
XU uses a system that somehow pulls a color for whatever liquid, and uses that for its drums.  No idea if this info is helpful in any way, just thought I'd throw it out there.

**Comment by fnuecke** [comment]
XU is Extra Utilities? I'd wager that's hard-coded, but I might be wrong. Either way, for a start it'll only be vanilla dyes. Might add support for other stuff later on.
