### ISSUE TITLE
Mod interaction - robot.swing() and Draconic Evolution blocks

### ISSUE THREAD

**Issue by DrifterOfTime** [MightyPirates/OpenComputers#1710]
Robots will not mine Draconium Blocks, Charged Draconium Blocks, and Awakened Draconium Blocks.

Tested on versions:
MC 1.7.10, OC 1.5.21.41, DE 1.0.2-snapshot_9 (in Resonant Rise 3.3.0.1)
MC 1.7.10, OC 1.5.22.46, DE 1.0.2
MC 1.7.10, OC 1.6.0.1-beta, DE 1.0.2

Tested with equipped Draconic Staff of Power, Draconic Pickaxe and tinkers' construct pickaxes of mining level cobalt and above.  Players can mine these blocks with these tools and the tools will mine other blocks when equipped to robots.

Hope that's enough information.  Never posted an issue before.

**Comment by fnuecke** [comment]
What does `=robot.swing()` in the Lua interpreter print out? Anything in the Minecraft/server log?

**Comment by DrifterOfTime** [comment]
Thanks for your reply!

=robot.swing() outputs:
false    "block"

There's nothing in the log pertaining to the event, though.

**Comment by payonel** [comment]
these swing operations now work - not sure when this was fixed, but i've confirmed this is all working now
