### ISSUE TITLE
CC integration

### ISSUE THREAD

**Issue by Alaisx** [MightyPirates/OpenComputers#1714]
In reference to 8d45fc4 (issue #1653)

I tested the relay with OC beta 1.6.0 and CC 1.78, and CC still does not detect the relay as a peripheral (access point or switch also are not detected).

Also a couple of questions on convention:
Do issues on pre-release versions belong here and/or need any special tagging? 
Is a new issue the right way to report that a closed issue is still causing problems?

**Comment by gjgfuj** [comment]
They belong here, and it would be better to reply to the closed issue, as
they can be reopened.

**Comment by fnuecke** [comment]
I'm a derp -.-

As for tagging, not really, mentoning the exact version is fine (and should be done for any issue ever anyway). As for closed issues, my rule of thumb is if it's older than a week or two, feel free to create a new issue, otherwise prefer adding to the old one.

**Comment by Alaisx** [comment]
Tested this out using the latest dev build for 1.8.9 (#35) and CC 1.78, and it almost works. The one thing that doesn't work, is getting CC to receive a via the OC Relay. Here are the things I have tested:

Using OC Relay:
Send using OC, receive using OC - works
Send using OC, receive using CC - does not work in 1.8.9, works in 1.7.10 (same scripts & setup)
Send using CC, receive using OC - works
Send using CC, receive using CC - does not work in 1.8.9, works in 1.7.10 (same scripts & setup)

Using CC Wired Modem (to check CC receive script is valid for CC in 1.8.9, not just 1.7.10):
Send using CC, receive using CC - works
