### ISSUE TITLE
[IDEA] Mouse integration, COM PORTS & UPGRADED NETWORKS, advanced hard disk, UAC, Shared Folders(Network Drives)!

### ISSUE THREAD

**Issue by n00b7** [MightyPirates/OpenComputers#1715]
might increase complexity a little( #1043 ).
------MOUSE INTEGRATION------
I think there should be some sort of mouse integration with oc somehow.
there should be events like whenmouseclicked([button side]) or
whenmousescroll([direction like up or down]) or getmousecursorpos()
and there would be things added like
"PS/2 MOUSE" AND
"SERIAL MOUSE" AND
"PORT MOUSE" AND
"USB MOUSE".
------end of mouse integration section------

------COM PORTS & upgraded networks------
back then they had COM ports
these were used for things like
lan networks and TELNET connections
also there were
"PORT KEYBOARDS"
"SERIAL KEYBOARDS"
"USB KEYBOARDS"
there should be a com port api/component
and also tcp/ip
------END OF COM PORTS & upgraded networks------

------ADVANCED HARD DISKS------
today we don't have the old way of booting (using ntldr to boot or command.com)
so i was wondering if there could be a bootsector??
and filesystems(readonlymemory, networkingfilesystem, fileallocationtable32, fileallocationtable12/16)
and sector properties(sectorspertrack , sectersperfileallocationtable)
in the config there would be options to disable this
(advancedsectordata = true/false)
------END OF ADVANCED HARD DISKS------

------UAC------
since we have users on oc why not have a user account control(UAC)
THIS WOULD ALSO ADD TYPES OF ACCOUNTS SUCH AS
ADMINISTRATOR , STANDARD USER
------END OF UAC------

------Shared Folders(Network Drives)------
Shared folders and network drives would allow users
to access data by connecting a computer via ethernet cable
there would be a comand to share called share [dirname] [user types allowed to acess like administrator or user1,user2,user3, and so on or everyone]
and mountnetdrv [network drive name] [shared dir name]
then users connected to that computer via an ethernet cable
------END OF Shared Folders(Network Drives)------

**Comment by MyNameIsKodos** [comment]
Most of what you have listed here is either already implemented in some form, or easily done in Lua on the software side.

**Comment by Techokami** [comment]
> MOUSE INTEGRATION

Already implemented in OpenComputers. With a Tier 2 or 3 display, you can use the right mouse button in the overworld while sneaking on the screen to create a `touch` event, or use the left mouse button while interfacing with the screen with a keyboard to create a `touch` event. These events are essentially mouse clicks.

> COM PORTS

No, I don't think that'd work well with the current peripheral system.

> upgraded networks

Did you find the "Network" loot disk? That contains software for making advanced networks in OpenComputers.

> ADVANCED HARD DISKS

You mean, unmanged HDDs? Take an HDD (not one you care about!) and sneak + right click. From here you can change it into Unmanaged mode, where the disk is just a big binary blob. Now, you'll have to make a custom BIOS to mount the disk and get the operating system started, like ntldr, but you'll have to do this one youself.

> UAC

If you want multiple users on a single computer with logins, check out OpenSecurity and the OpenOS fork it comes with called SecureOS. It adds this.

> Shared Folders(Network Drives)

Set up a RAID on the network. It'll be visible to all connected computers.

**Comment by fnuecke** [comment]
What they said!

**Comment by n00b7** [comment]
thank you

**Comment by Shuudoushi** [comment]
@Techokami SENPAI NOTICED ME!!! I'm done.

**Comment by Shuudoushi** [comment]
Oh, and @n00b7, [SOS](https://github.com/Shuudoushi/SecureOS) doesn't require OS to work.
