### ISSUE TITLE
[Feature-Request] Add CurrentPowerConsumption and MaxPowerConsumption

### ISSUE THREAD

**Issue by yannick9906** [MightyPirates/OpenComputers#1718]
I know it could be hard to implement, but it would be very nice to have the methods `getCurrentPowerConsumption()` and `getMaxPowerConsumption()` from all Blocks that require power and to the blocks holding power (e.g. Capacitor Banks) the methods `getCurrentInput()` and `getCurrentOutput()` (maybe `getCurrentIO()`)

**Comment by fnuecke** [comment]
Hmhm. Should be doable, but it's not quite... trivial. First change required would be to make nodes always notify their network when power is consumed/injected, not just when their local energy buffer under/overflows. The other problem is that networks and nodes on their own don't tick. So I suppose a new block/component that does the measuring would make sense (don't really want to cram that in the machine... might then even rip out the getters that are there now in a next major update). Will see if I can come up with something better...

**Comment by yannick9906** [comment]
That would also by a nice idea, to have a energy flow sensor, where you can attach a energycable on both sides and read out the flow. (Maybe also for items/fluids). Maybe you could also limit the amount going trough the block... :)

**Comment by MyNameIsKodos** [comment]
Computer-controlled energy/fluid sensor valves? Yes please.

**Comment by payonel** [comment]
I don't think this large of a change is a good idea at this point.
