### ISSUE TITLE
internet.request location property

### ISSUE THREAD

**Issue by Fingercomp** [MightyPirates/OpenComputers#1726]
That would be useful if request gets redirected so I could easily get an URL it was redirected to. Ex.:

``` lua
request = internet.request(url)
location = request.location
```

**Comment by fnuecke** [comment]
Can't you get that [from the response headers](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/component/InternetCard.scala#L302)?

```
local _,_,headers = request.response()
doSomethingWith(headers['Location'])
```

Or something like that?

**Comment by Fingercomp** [comment]
OpenComputers automatically redirects requests if a server tells so.
![Screenshot of OC screen with me trying to get "Location" header](http://i.imgur.com/Ug2s0Zx.png)
There is no "Location" header. And none of those headers contain URL.

**Comment by fnuecke** [comment]
Uhh, that's Java's doing then though, dunno if that can be disabled?

**Comment by Kubuxu** [comment]
Looks like you can: http://stackoverflow.com/a/2659022

**Comment by fnuecke** [comment]
Cool. Then the only remaining question is: new parameter or make that the default? Probably the former for less breakage, I guess.

**Comment by payonel** [comment]
I'd actually prefer we not try to handle redirects ourselves. I suppose if someone PRs this and the work looks reliable I'd consider it. But I'd prefer we leave it alone

**Comment by skyem123** [comment]
@payonel, it sounds like you misread this one, this is kinda about letting OC _not_ do the redirect. :P

**Comment by payonel** [comment]
@skyem123 i understand, but I didn't explain myself well. If java doesn't do the redirect, then OC will have to, or openos will, or user code will. Someone will, and I'd prefer to leave that to our java libraries we are using.

**Comment by skyem123** [comment]
True, but why not make it an optional thing? Allows a level between "raw TCP" and "HTTP doing everything automagicaly". :p
