### ISSUE TITLE
A slight issue with 'wget'

### ISSUE THREAD

**Issue by Shuudoushi** [MightyPirates/OpenComputers#1728]
As I just discovered while working on SecureOS, if you use 'wget -f' to download an existing file (like you're updating it or something), and there is an error in wget itself (like it gets a 503 error), it deletes the file outright. Which a big issue when it's a system file from /boot or something.

A small amount of 'protection' can be added to wget to combat this issue. Even something as 'simple' as waiting to see if it errors before removing the existing file.

**Comment by payonel** [comment]
this should be resolved with https://github.com/MightyPirates/OpenComputers/pull/1758

**Comment by fnuecke** [comment]
If it's not, yell at payo! :P
