### ISSUE TITLE
Check is inventory is full [Robot]

### ISSUE THREAD

**Issue by danshat** [MightyPirates/OpenComputers#1731]
Add a method to Robot API to check is robot's inventory is full?
or maybe _an event_?

**Comment by fnuecke** [comment]
Just check all slots?

**Comment by danshat** [comment]
It's just an enhancement to simplify the code :) It's not really important right?

**Comment by MyNameIsKodos** [comment]
It wouldn't be hard to just write a function that checks all slots, and have it return true if all slots are filled, and false otherwise.

**Comment by fnuecke** [comment]
Sorry, but then no. Write a helper method in Lua. I'd like to avoid cluttering the API.
