### ISSUE TITLE
LuaJ doesn't call user defined metamethods __pairs nor __ipairs

### ISSUE THREAD

**Issue by payonel** [MightyPirates/OpenComputers#1735]
It appears that tab completion does not work in the lua prompt on LuaJ archs, and further investigation finds that the reason is because the environment is failing to supply a list of available keywords -- and the reason appears to be that user defined __ipairs and __pairs metamethods are NOT called (__len and __index are). I have not tested other metamethods.

**Comment by fnuecke** [comment]
Paging LuaJ master @gamax92.

**Comment by dgelessus** [comment]
I think `__ipairs` is deprecated since Lua 5.3, because `ipairs` now respects `__index`. `__pairs` isn't though.

**Comment by payonel** [comment]
Without looking it up, I'll agree that sounds familiar :)
I felt it worth noting that the tab-completion bug needs __pairs fixed, not __ipairs.
