### ISSUE TITLE
A network switch which allows a computer to see only the components on the other side

### ISSUE THREAD

**Issue by samwalls** [MightyPirates/OpenComputers#1736]
Imagine this: a type of network switch which allows a computer/server etc. to see the components on the other side, but only on the other side, for instance if this was the setup

[computer] <-> [new switch] <-> [monitor] <-> [new switch] <-> [disk drive]

In this case, the computer would be able to see the monitor, but not the disk drive, because it can only see components on the other side of the switch block.

The real advantage of this comes as such:

[computer A] <-> [new switch] <-> [RAID] -> [new switch] <-> [computer B]

Computer A can access the RAID, and so can computer B, but the computers will no longer interfere with each other! If this is possible, you could in theory have as many computers as you like connect to and use the RAID. Now, I don't really know how the internals of the filesystem would handle this, whether the possibility of two computers trying to access the raid at once would break something or not, but would something like this be possible?

EDIT: the switches could also relay signals in the usual way, perhaps be configurable to do so or not.

**Comment by MyNameIsKodos** [comment]
Your RAID example can, and should, be done on the software side. Proper binding of GPU, screen, keyboard, etc components will resolve any issues you get with networking a raid between two computers.

**Comment by samwalls** [comment]
@MyNameIsKodos But why _should_ it be done this way..? I mean, I've never found out how to do what you said as of yet :) but if it could be made easier, why not?

EDIT: I did try the networking filesystem [here](https://oc.cil.li/index.php?/topic/844-serverfs-host-a-filesystem-over-the-network/) for example, but it appears to be broken for now.

**Comment by fnuecke** [comment]
Sorry, but that's not really possible with how OC's internal networking works. I would like to redesign that one day maybe, but that would probably have to be OC2, which is, realistically speaking, unlikely to ever happen.
