### ISSUE TITLE
multi-block monitors map incorrectly when broken

### ISSUE THREAD

**Issue by GopherAtl** [MightyPirates/OpenComputers#174]
when you have a multi-block monitor connected to a computer and break one piece, causing it to separate into smaller monitors, the part still connected to the top-left-most block of the original monitor array remains the active monitor.

To reproduce: set up any computer, power, etc, and give it a 2x2 monitor on top, with the bottom-right monitor on top of the computer, so the whole thing sticks out to the left. with it running, break the bottom-left monitor; the 2x2 will split, with the top two staying connected as a 2x1 and the bottom-right that is connected to the computer by itself. The shell will still be displayed on the top monitor, though, despite it not being connected to the computer. If the keyboard was on one of those two monitors, it will still remain usable this way until you turn the computer off.

**Comment by Vexatos** [comment]
It's magic :star2:

**Comment by fnuecke** [comment]
You mean like this?
![](http://i.imgur.com/jpNytie.png)

That's expected behavior. Connectivity in OC works similar to AE, i.e. each block acts as a direct 'connection' except for the power distributor and the switch/access point, which keep sub-networks separated.

**Comment by GopherAtl** [comment]
that... is some seriously unexpected expected behavior, but if you say so. Just checked and found that, yes, even if it finds the one directly connected first and makes it primary, the screen on top is still discovered connected after a reboot. So.. huh.
