### ISSUE TITLE
1.8.9 hologram component issue

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1741]
i ran Sangar's holo-flow program and got an error on line 6: component.hologram does not exist.

**Comment by payonel** [comment]
You need this block http://ocdoc.cil.li/block:hologram_projector adjacent or connected with wires to the computer case.

**Comment by setsunafseiei** [comment]
LoL.. using holo program or command without hologram projector

**Comment by ghost** [comment]
No, I had one next to the case, i'm not stupid

**Comment by Fingercomp** [comment]
Hologram projector can be only connected from a bottom side.

**Comment by fnuecke** [comment]
Yeah, what Fingercomp said is probably it. Make sure to connect it from the bottom (tip: in general, if a cable doesn't visually connect to a side of a block component, nothing will).

**Comment by setsunafseiei** [comment]
@GiantNuker 
Maybe it can work above the case, rather in the side

**Comment by ghost** [comment]
@Fingercomp Thanks, I had it next to the computer :P
