### ISSUE TITLE
[Suggestion-Modification] The PROCESSING Hardwares

### ISSUE THREAD

**Issue by setsunafseiei** [MightyPirates/OpenComputers#1742]
## Motherboard
1. Different PCI-E Slot tier is measured of size of a PCI-E Slot 
   E.g. PCI-E x4 = PCI-E tier 1
      PCI-E x8 = PCI-E tier 2
      PCI-E x16 = PCI-E tier 3
2. A Custom Hardware which has different levels of  Complexity (for Server, Robot, Micro Controller and    Computer PC) and levels of portability (for Tablet, drone, and robot) 
   E.g. a tier 1 PC motherboard which has a maximum of Complexity of **20**, 
   a tier 2 PC motherboard which has a maximum of Complexity of **30** and,
   a tier 3 PC motherboard which has a maximum of Complexity of **55**
   ++==++==++
   a tier 1 Server motherboard which has a maximum of Complexity of **40**, 
   a tier 2 Server motherboard which has a maximum of Complexity of **65** and,
   a tier 3 Server  motherboard which has a maximum of Complexity of **75**
3. Component slots have equivalent complexity.
   e.g. A PCI-E slots = 3 (Tier 1) | 4 (Tier 2) | 5 (Tier 3)
   A RAM Slot = 1 (Tier 1) | 3 (Tier 2) | 5 (Tier 3)
   A CPU Slot = 3 (Tier 1) | 4 (Tier 2) | 5 (Tier 3)
   Storage Slot = 2 (Tier 1 HDD) | 3 (Tier 2 HDD) | 4 (Tier 3 HDD) | 2 (FLOPPY Disk Drive)
   Component Card Slot = 3 (Tier 1) | 4 (Tier 2) | 5 (Tier 3) SERVER ONLY
   If 2 X Tier 2 installed = 8 complexity
4. Different Motherboard has limit on number of maximum type of component slot
   e.g.  FOR PC Motherboard
   A PCI-E Slots = 2 (on tier 1) | 3 (on tier 2) | 4 (on tier 3)
   A RAM Slot = 2 (on tier 1 - 3)
   A CPU Slot = 1 (on tier 1 - 2 ) | 2 (on tier 3)
   Storage Slot = 2 (Tier 1) | 3 (Tier 2) | 4 (Tier 3)

FOR SERVER Motherboard
A PCI-E Slot = 3 (on tier 1) | 4 (on tier 2 and 3)
A RAM Slot = 4 (on tier 1 - 4)
A Component Card Slot = 3 (on tier 1) | 2 (on tier 2 and 3)
A CPU Slot = 1 (on tier 1) | 2 (on tier 2 and 3)
Storage Slot = 3 (Tier 1) | 4 (Tier 2 - 3) NO FLOPPY DISK  DRIVE SUPPORT
## Central Processing Unit - Modification

SPECS for each different PC CPU tiers
1. Cycle Rate: 125 kHz (Tier 1) | 250 kHz (Tier 2) | 500 kHz (Tier 3)
2. # PCI-E Slot: 2 (Tier 1) | 3 (Tier 2) | 4 (Tier 3)
3. # of Core/Thread: 1/2 (Tier 1) | 2/4 (Tier 2) | 4/4 (Tier 3)
SPECS for each different SERVER CPU tiers
1. Cycle Rate: 250 kHz (Tier 1) | 500 kHz (Tier 2) | 500 kHz + 125 kHz (Tier 3)
2. # PCI-E Slot: 3 (Tier 1) | 4 (Tier 2) | 4 (Tier 3)
3. # of Core/Thread: 2/2 (Tier 1) | 4/8 (Tier 2) | 4/8 + 2/2 (Tier 3)
## Graphics Processing Unit - Modification

SPECS for each different Single GPU tiers
1. Cycle Rate: 750 kHz (Tier 1) | 1.25 MHz (Tier 2) | 1.5 MHz (Tier 3)
2. PCI-E Slot Tier: Tier 2 | Tier 3 | Tier 3
3. # vRAM: 2 X Tier 2 (Tier 1 GPU) | Tier 2 + 3 (Tier 2 GPU)  | 2 X Tier 3 (Tier 3 GPU)
SPECS for each different Multi-GPU tiers
1. Cycle Rate: 750 kHz + 250 kHz (Tier 1) | 750 kHz + 500 kHz (Tier 2) | 1.25 MHz + 125 kHz (Tier 3)
2.  PCI-E Slot Tier: 2 X Tier 2 (Tier 1) | Tier 3 + Tier 2 | 2 X Tier 3
3. # vRAM: 3 X Tier 2 (Tier 1 GPU) | 2 X Tier 2 + 3 (Tier 2 GPU)  | 3 X Tier 3 (Tier 3 GPU)
## Accelerated Processing Unit - Modification

SPECS for each different PC APU tiers
1. CPU Cycle Rate: 150 kHz (Tier 1) | 275 kHz (Tier 2) | 400 + 125 kHz (Tier 3) | 450 + 125 kHz (Tier 3 M-APU)
2. # PCI-E Slot: 2 (Tier 1) | 3 (Tier 2) | 4 (Tier 3)
3. # of Core/Thread: 2/2 (Tier 1) | 2/4 (Tier 2) | 2/4 + 2/2 (Tier 3) | 3/6 + 2/2
4. GPU Cycle Rate: 500 kHz (Tier 1) | 1.00 MHz (Tier 2) | 1.25 MHz (Tier 3) | 1.25 MHz + 125 kHz
5. # vRAM: 1 X Tier 2 (Tier 1 GPU) | Tier 1 + 2 (Tier 2 GPU)  | 2 X Tier 2 (Tier 3 GPU)
SPECS for each different SERVER CPU tiers
1. Cycle Rate: 200 kHz (Tier 1 APU) | 225 kHz + 125 kHz (Tier 2 M-APU) | 250 kHz + 150 kHz (Tier 3 M-APU)
2. # PCI-E Slot: 3 (Tier 1) | 4 (Tier 2) | 4 (Tier 3)
3. # of Core/Thread: 2/2 (Tier 1) | 2/4 + 1/2 (Tier 2) | 2/4 + 2/2 (Tier 3)
4. GPU Cycle Rate: 550 kHz (Tier 1) | 1.15 MHz (Tier 2) | 1.35 MHz + 150 kHz (Tier 3)
5. # vRAM: 1 X Tier 2 (Tier 1 GPU) | Tier 1 + 2 (Tier 2 GPU)  | 2 X Tier 2 (Tier 3 GPU)
- M- (Multi)

**Comment by setsunafseiei** [comment]
How's my idea?
@fnuecke

**Comment by Shuudoushi** [comment]
OC computers are based off of late 80's to early 90's PCs, so your suggestions make little to no sense...

**Comment by payonel** [comment]
@setsunafseiei thanks for all the excitement you have! I don't make the calls on the computer components for OC, but I do think this is probably beyond the scope of what OC is about.

**Comment by payonel** [comment]
@setsunafseiei also, you don't need to @ the author, he gets pinged of all of this activity regardless :) Also, please don't open and close issues with repetition.

**Comment by gamax92** [comment]
How does one put a clock rate on Lua, it's not a clock driven machine, just a virtual high level machine.

**Comment by fnuecke** [comment]
Some of this is already present in a simplified form, and making it more complicated does not serve any goal but making the mod less accessible and less fun to work with, IMHO, so to me this feels like it belongs to #1043, sorry.

**Comment by setsunafseiei** [comment]
what is the difference of Lua 5.2 and 5.3?
is it like x86 (32 bit) vs x86-64 (64 bit)?

**Comment by Kubuxu** [comment]
@setsunafseiei no it isn't, it is just small upgrade in language capabilities.

**Comment by setsunafseiei** [comment]
@Kubuxu soo you are saying 5.3 is updated type of Lua 5.2? soo... Lua 5.2 can run on 5.3? then Lua 5.1 can run on both 5.2 and 5.3?

**Comment by Kubuxu** [comment]
No, Lua 5.2 can mostly run on Lua 5.3 but Lua 5.1 can only hardly run on Lua5.2

This isn't place to discuss it, those sorts of questions should be placed in IRC or Forums

**Comment by setsunafseiei** [comment]
@Kubuxu well, can i run snake from computercraft on opencomputers without a single problem?

**Comment by Fingercomp** [comment]
There are a lot of differences between ComputerCraft and OpenComputers, not only Lua versions. I'm almost (99.9%) sure that no.

**Comment by setsunafseiei** [comment]
No way to convert?? like alongtimeago running on opencomputer? the error is: notenoughmemory.. :( but will it run on high memory???

**Comment by fnuecke** [comment]
Forums or IRC, _please_!
