### ISSUE TITLE
x86 Architecture Virtualization

### ISSUE THREAD

**Issue by setsunafseiei** [MightyPirates/OpenComputers#1745]
Just a random idea and question.
Can you run visualization inside minecraft? Inserting like a virtual machine (x86 support) inside a game.

would this be possible?

**Comment by Techokami** [comment]
It is possible to add new architectures to OpenComputers via add-on mods. Someone was working on an x86 arch, but haven't heard of any progress on it lately.

Sent from my Windows Phone

**Comment by setsunafseiei** [comment]
@Techokami but wouldn't eat much of processing cores and RAM, well computers are x86 based processor, in which you can run Operating System within a Operating System in a minimal processes and speed
Lol, is like asking my ownself

**Comment by fnuecke** [comment]
For the most part, additional architectures are best done as addons, the way it is right now.
If there'll come along a particularly fleshed out and robust and useful one, and the author is interested, I'll gladly consider merging it into OC itself. But in general that's not the case, so please keep this to the forums.
