### ISSUE TITLE
next BETA release?

### ISSUE THREAD

**Issue by setsunafseiei** [MightyPirates/OpenComputers#1746]
When is the next beta release?
Can i be a beta tester for bug? For a maximum of $0.00. 
Hahaha :+1: :+1: :100:

**Comment by Techokami** [comment]
"Beta" releases can be gotten from the build server. See the readme in the repo for the link.
Also, you do realize that we have a forum for random questions and discussion? It's also linked from the readme.

Sent from my Windows Phone

**Comment by setsunafseiei** [comment]
@Techokami K! Sorry! NOOB HERE!
Didn't find the readme

**Comment by fnuecke** [comment]
When it's done (TM). Seriously though, stop abusing the issue tracker please.

Also how can you not find the readme... it's literally _right there_ when you come to this repository.
