### ISSUE TITLE
Program Suggestions

### ISSUE THREAD

**Issue by setsunafseiei** [MightyPirates/OpenComputers#1747]
1. LUA Editor+ (similar to the newest Computercraft (Advance Computer) Editor
2. (For programmers in opencomputer program makers) Windows (Windows-95 or 98) based Operating system
   A User Friendly type of OS which isn't like OpenOS or MS-DOS (command prompt)
   A GUI for all of the list of programs available
   A Explorer GUI for searching and exploring system files
   A Settings to switch users, to change resolution, to manage devices, or to update OS
   A Consumer Grade type of OS (non-in-game programmer). Only using available apps in the internet and built in
   A Pastebin for just pasting or entering the code and downloading some apps
3. 3D Printer Program
   A Program to create a custom 3D Items, or Block and to print it.
   Like a Hologram Program, creating hologram with help of GUI and displaying command and module for consumer type of players
4. Stress Tester
   Why not use a stress tester in which you can test various or all of the components, and command and even program to test some bugs and error within the program
5. Games or Entertainment (ComputerCraft based)

**Comment by Techokami** [comment]
I don't think any of these will be part of the mod itself, but people are working on making such things already.

Sent from my Windows Phone

**Comment by setsunafseiei** [comment]
I mean it isn't necessary if @fnuecke will do all the job. I mean if people (a programmer) see my request and they are willing to do this, or if someone can tell them to request this programs.. I mean @fnuecke will do the mod items and block and other related to minecraft modification, while the other people will handle this request. Like in iOS, Windows, Android and OS X and other OS, the company will do the OS while the programmers do the programs outside the OS like google chrome, it isn't from microsoft. If @fnuecke is willing to do some, then wouldn't be grateful?

**Comment by fnuecke** [comment]
Please keep discussing Lua programs to the forums.
