### ISSUE TITLE
Printer (Paper and the actual consumer printer)

### ISSUE THREAD

**Issue by setsunafseiei** [MightyPirates/OpenComputers#1748]
Why not create a printer and a word or document editor.

**Comment by Fingercomp** [comment]
There is already an OC addon adding such printers: [OpenPrinter](https://oc.cil.li/index.php?/topic/54-mc-164172-oc-12-openprinter/).

**Comment by setsunafseiei** [comment]
@Fingercomp there is a document editor program, which can also print just pressing the print button??

**Comment by fnuecke** [comment]
Please take this to the forums.
