### ISSUE TITLE
Computercraft programs crossover or cross platform or compatibility or virtualization

### ISSUE THREAD

**Issue by setsunafseiei** [MightyPirates/OpenComputers#1749]
Why not computercraft programs will able to be used on OpenComputers like alongtimeago floppy disk movie?
Idea on methods
(1) Virtualization 
A PROGRAM or a BUILT-IN support on both LUA 5.2 and LUA 5.3
If through BUILT-IN, the creator of the mod should able to make LUA 5.1 usable in his LUA 5.2 and 5.3 versions
If through PROGRAM, the owner of the program able to read LUA 5.1 and to virtual or in background converting it but only within the program is being player and after using the program will be back from the past and original copy of the PROGRAM codes
(2) Crossover or compatibility (ONLY FOR PROGRAM CREATORS)
A PROGRAM able to run LUA 5.1 on LUA 5.2 or 5.3
*NOT SURE IF THIS CAN BE APPLIED
A PROGRAM with different platform types (like saying some x86 program cannot run on x64 and all x64 programs cannot run x86)

**Comment by fnuecke** [comment]
People have worked on "emulators" for running CC programs in OC (and vice versa possibly?), please ask such things on the forums or on IRC.
