### ISSUE TITLE
OpenComputers as cash registers?

### ISSUE THREAD

**Issue by setsunafseiei** [MightyPirates/OpenComputers#1750]
Well why not, they aren't powerful enough even and Cash register wouldn't eat much of a process, am i right?

**Comment by Fingercomp** [comment]
This could be made as a program.
OpenComputers programs should be requested [here](https://oc.cil.li/index.php?/forum/42-requests/). The issue tracker is for bugs, features requests, etc.

**Comment by fnuecke** [comment]
Exactly.
