### ISSUE TITLE
Method to change names of components

### ISSUE THREAD

**Issue by gdude2002** [MightyPirates/OpenComputers#1751]
For when you have a bunch of components of the same type; it would be nice to be able to rename them so you can address them a little easier in a development repl or script, and easily see which are connected by looking at the components list.

I would accept either:
- Outright changing the component name
- A separate "tag" for the component that is displayed separately

Some possible methods:
- Anvil renaming (May only be possible for item components)
- Some kind of API method
- A tool similar to the analyzer that can rename block components

Note that to be fully complete, this should also support components exposed by the adapter block.

**Comment by iamgreaser** [comment]
It would be better if this had a separate tag and if OpenOS added an alias to the `component` API with this tag. In at least some important cases it _is_ important that the type is kept.

An API method would be your best bet.

**Comment by gdude2002** [comment]
Yeah, that sounds like the most likely approach to me as well. A `component` API alias is a must too.

**Comment by skyem123** [comment]
So basically custom aliases for components? Sounds interesting, and it could be useful.

**Comment by payonel** [comment]
component label support (though experimental) added in builds >= 1000
http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/

the `label` command can assign a label to any component, not just filesystems
These labels persist after reboot if your rootfs is writable
You can request a component by label using
`local dev_proxy = require("devfs").getDevice("/dev/components/by-label/{YOUR_LABEL}/device")`

This code is experimental and may change slightly in future updates, and simplified api may be added alter (such as `devfs.getDeviceByLabel(label)`)

Using `label` with no args respects component labels
`mount` does not (it only lists the fs labels directly from the fs proxy)

You can make label rules to specific IDs (address) by creating files in /etc/udev/rules.d/. The format is an array of tables with address and label values.

e.g. 
`{ { address="f4501a9b-9c23-1e7a-4afe-4b65eed9b88a", label="custom_label" } }`

With this, a device with that id will be listed under: /dev/components/by-label/custom_label
You can grab a proxy to it using: `local proxy = require("devfs").getDevice("/dev/components/by-label/custom_label/device")`
