### ISSUE TITLE
Tier 2 Internet Card

### ISSUE THREAD

**Issue by setsunafseiei** [MightyPirates/OpenComputers#1752]
Why not use computers for internet explorer.
You can go to the forum and download such things..
You can also chat some moderator at _http://webchat.esper.net/?channels=#oc_ 
without accessing outside minecraft, like the ingame manual.
A program which have ingame support and ingame internet connection...
Playing youtube and flash players, why not..

**Comment by payonel** [comment]
OpenComputers is a mod for minecraft that "adds programmable computers and robots to the game". I took that quote from OpenComputer's front page on this github. While your enthusiasm and interest in using computers in minecraft is good, you are misunderstanding the intent of this mod. The idea is to give you a virtual toolbox with a reasonable set of scripts to get you going and programming and building your own computers and robots, albeit in a virtual world. It is not the purpose of the mod to give you your real life personal desktop inside the minecraft world. If you are unsure what the purpose of this mod is for, please visit the forums: https://oc.cil.li/index.php?/index

**Comment by system86** [comment]
OP is autistic

**Comment by purplemonday** [comment]
system86 commented
OP is autistic
--
will you keep your generalizations to yourself please you rasistic prick.

**Comment by payonel** [comment]
I've decided to remove a couple of comments on this thread that I considered to be impolite. Please respect one another and at the very least, do not use our issue tracker to attack each other.
