### ISSUE TITLE
All in One PC and Flat Screen

### ISSUE THREAD

**Issue by setsunafseiei** [MightyPirates/OpenComputers#1753]
I would request for a laptop but i know what you will say..

> Their is already a tablet and it would be useless if their would be laptop. There is no point of putting laptop in opencomputers.

So why not All in One PC?
AiO pc.. like iMac, all its components like motherboard is installed behind or rather in within the screen, just add keyboard, why not?

Flat screens
Why not have a flatscreen like a size of a microblock by forge...
So thin that it is like wall mounted or thin that it won't occupy the whole one block of table...

**Comment by Vexatos** [comment]
See #1544 and #936.
