### ISSUE TITLE
[BUG-FOR REAL] OpenComputers-dev-MC1.7.10

### ISSUE THREAD

**Issue by setsunafseiei** [MightyPirates/OpenComputers#1755]
OK... Booting up my system took so long plus it reduces my FPS rating from 40 FPS into 5 FPS and sometimes 1 or 2 FPS

And it ran on BlueScreen Error... it says "took so long"

**Comment by fnuecke** [comment]
Sounds like you're running MC on a Raspberry Pi. Seriously though, unless you can provide some more actual useful info, I'll close this as "your computer is too crappy". Don't you think if this happened for everyone (including me), all the time, this'd have gotten attention already?

**Comment by setsunafseiei** [comment]
Nope... Same Server type in minecraft
TEST #1 
First I ran my server from the latest OpenCOmputers 1.6 beta 1 on Minecraft 1.7.10
Ok no bugs at all
TEST #2  - OpenComputer 1.6 DEV 892
I ran the same server. I reboot it and stuck waiting at the booting screen, then bluescreen of errors showed up...
I will upload a proof ok?

**Comment by setsunafseiei** [comment]
@fnuecke i have it recorded in both TEST
You'll see!

**Comment by Landrash** [comment]
@setsunafseiei Why are you referencing a feature request and a pull request from 2013? I would highly recommend you learn some common Github syntax and try to follow a proper code of conduct.
Your post contain just about no usable information for anyone to work on as is.

**Comment by setsunafseiei** [comment]
I will upload the whole information. it is a form of a video

**Comment by setsunafseiei** [comment]
https://drive.google.com/file/d/0B9AH0a-EGBzTMXI1WTl2WmRqZms/view?usp=sharing (BETA-1)
https://drive.google.com/file/d/0B9AH0a-EGBzTazZDeHVLNlJfVzg/view?usp=sharing (OpenComputers-MC1.7.10-1.6.0.892-dev-universal.jar)

**Comment by setsunafseiei** [comment]
@Landrash what!
TEST #1 or 1st TEST not referencing on issue #1 DUMB @##
A guy who doesn't understand clearly on English language
I am just a person fan about computers... you comment like you are "the perfect one".

**Comment by bauen1** [comment]
@setsunafseiei Just saying whit such language skills and common sense you will probably get your self blocked from this repository

**Comment by fnuecke** [comment]
Landrash was giving good advice, @setsunafseiei; referencing other issues without actually meaning it is quite annoying, so you should've taken his advice instead of insulting him and doing it again. I'll take this opportunity to ask you to stop posting like a frenzied madman. If you keep this up, I _will_ block you.

**Comment by Landrash** [comment]
@setsunafseiei I'm sorry if I came of rude. It was not meant like that and where mere suggestions.
