### ISSUE TITLE
SecurityCraft API

### ISSUE THREAD

**Issue by setsunafseiei** [MightyPirates/OpenComputers#1756]
Description:
SecurityCraft
(http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291001-v1-8-1-securitycraft-security-cameras-retinal)
Adding securitycraft as a compatible component of opencomputers, not just using of fancy REDSTONE
Like CCTV implement on Opencomputers which can be viewed...
The maker of the SecurityCraft won't release an update yet and no plans yet. So, why not ask them to configure their support of OpenComputers in your mod.
Function
a CCTV Monitor for Surveillance Cameras, it would be the base of the CCTV cameras, a computer which manage all of the camera..

**Comment by Techokami** [comment]
Ask the creator of SecurityCraft to add support for OpenComputers.

**Comment by setsunafseiei** [comment]
Why me? No one agreed yet!

**Comment by LizzyTrickster** [comment]
You were the one who suggested it...

**Comment by Forecaster** [comment]
@setsunafseiei You might want to look up the OpenComputers addon OpenSecurity instead.

**Comment by setsunafseiei** [comment]
OpenSecurity lacks CCTV in which SecurityCraft makes it more interesting...

**Comment by setsunafseiei** [comment]
@LizzyTrickster Is it already approved by sir @fnuecke ?

**Comment by gdude2002** [comment]
@setsunafseiei There is a lack of interest in supporting this in the OC community; You should suggest this to the author of SecurityCraft and have them add support for OC instead.

**Comment by bauen1** [comment]
@gdude2002 He already did and got denied, look at his activity, he made 6 issues (on multiple repository) in 11 hours

**Comment by setsunafseiei** [comment]
I am interested in OpenComputers... but come on suggestion is just suggestion!

**Comment by bauen1** [comment]
actually, an issue tracker is for bug reports, the opencomputercraft forums are for suggestions

**Comment by gdude2002** [comment]
The general concensus on IRC is that this would not be a useful addition to OC. Personally, I can't see any use for it either. The suggested API is so tiny, if SC doesn't want to add OC support, then I really can't see it being added here either.

I would suggest closing this issue.

**Comment by setsunafseiei** [comment]
I know that but, both mod needs to work together

**Comment by LizzyTrickster** [comment]
@setsunafseiei please enlighten me as to where @fnuecke endorsed _any_ of the issues you've posted?

Discussions like this are best suited for the forums at https://oc.cil.li

**Comment by setsunafseiei** [comment]
OK FINE!

**Comment by setsunafseiei** [comment]
Dont worry i wont suggest anymore... Waste of EFFORT and IDEA!

**Comment by bauen1** [comment]
@setsunafseiei Please stop if your being told to stop and don't just go to the next repository and make another issue

**Comment by setsunafseiei** [comment]
# THAT IS WHAT AM I DOING, I WONT CREATE ANYMORE REQUEST OR WHAT SO EVER! I LIKE THE MOD BUT I DONT LIKE THE PEOPLE

**Comment by fnuecke** [comment]
Thank goodness.
