### ISSUE TITLE
Rack crash

### ISSUE THREAD

**Issue by Fingercomp** [MightyPirates/OpenComputers#1757]
Steps to reproduce:
1. Spawn a computer.
2. Place a rack next to it.
![A screenshot of that setup](http://i.imgur.com/6X1M2ca.png)
3. Throw at least 2 non-server things (terminal servers, for example).
![4 non-server-things](http://i.imgur.com/JPWVXlQ.png)
4. Connect both of them to the side where the computer is.
That's all.
[Log](http://pastebin.com/y3cUrCmy)
[Crash report](http://pastebin.com/whG3YrMt)
_Version_: 1.6.0.892-dev (the latest one)

**Comment by fnuecke** [comment]
Thanks a lot for reporting! Was a follow-up error initially caused by the rack's reconnect logic hiccuping.
