### ISSUE TITLE
get/setBackground, get/setForeground not returning correct values

### ISSUE THREAD

**Issue by GopherAtl** [MightyPirates/OpenComputers#176]
according to the wiki docs, gpu.setForeground and setBackground return the actual color set in the call, presumably after mapping to some best-fit for the bit depth. After testing, what they actually return is the previous value passed in to the functions. 
Not, notice, the previous actual color, but the previous unmodified argument. Demonstrate at lua like this:
lua> for i=1,4 do print(gpu.setBackground(c)) end gpu.setBackground(0)

this will print 0,1,2, and 3, assuming your background was black to begin with. 
Further testing shows that getBackground is returning the unprocessed argument as well, rather than the actual color being used. 

I suppose you could call this a documentation error and fix it there, but it threw me a bit.

**Comment by fnuecke** [comment]
Oh, yeah. The documentation is faulty there, sorry about the confusion. I'll correct it.
