### ISSUE TITLE
May I generate a offline copy of the API doc with Dash?

### ISSUE THREAD

**Issue by xingrz** [MightyPirates/OpenComputers#1762]
Hi all,

[Dash](https://kapeli.com/dash) is a widely used documentation Mac OS X app by developers. I was wondering if I'm permitted to make a copy of the OC API docs to be used in Dash, so people developing with OC would have a better experience of quick-searching any API usage whenever they need.

**Comment by gjgfuj** [comment]
The docs are public domain, (at least the ones on ocd.cil.li) so go for it!

**Comment by Landrash** [comment]
For those none Apple developers there are alternatives like [Zealdocs](https://zealdocs.org/)

I'm not aware whats needed for either in form of files but if @xingrz creates that copy then I highly recommend sharing the end results for others to use =)

**Comment by xingrz** [comment]
Thank you @gjgfuj @Landrash .

**Comment by fnuecke** [comment]
As for the API, sure, go ahead! Never actually thought about it, but I suppose it'd fall under MIT together with the code.
