### ISSUE TITLE
Contents of a drive's world/opencomputers/ folder should be cleared out.

### ISSUE THREAD

**Issue by Kreidos** [MightyPirates/OpenComputers#1764]
The contents of an HDD or floppy's world/opencomputers/<UUID> folder, and the folder itself, should be removed when the drive is erased by dropping it in the crafting window. Likewise for drives that are placed in the disassembler and drives in tablets, thusly disposed of. If possible, also for any drive or device that is disposed of via another method, e.g. burning in lava, throwing in trash can, etc.

These old folders have no hooks into the game any longer and simply persist indefinitely, cluttering up the world file and wasting space. (Albeit only 0.5 -> 4MB each, but it adds up.)

To my knowledge, once a drive loses it's UUID, there is no way to re-associate a drive<->folder pair in the future, so is there some reason to keep these folders hanging around?

**Comment by gjgfuj** [comment]
Presumably, in case you've got data on there that you meant not to lose but
accidentally erased. I do get your point though, because these can easily
pile up and take up a fair amount of space.

**Comment by Kreidos** [comment]
I considered that, but recovering it would require access to the server's raw files; which most players do not. Consider, as well, that there may be hundreds of folders in the OC folder. I hope you remember your UUID. ;)

And, Just as-in real life, the onus should be on the user. Make backups of important data, especially before taking your only tablet lava-surfing.

**Comment by dgelessus** [comment]
I do like how the leftover folders can act as a sort of backup. After all, modded Minecraft is not exactly the most bug-free thing in the world, and there are many ways you could lose your HDD item that are not caused by user carelessness. I also doubt that OC could easily detect when a HDD item is "destroyed" - how would it know the difference between a normal BuildCraft pipe and a void pipe, and which one counts as "destroying"?

Maybe it should look at the folders' last modification dates and delete any filesystem folders that were not touched since X days. That could also be fragile though - what if a HDD lies in an unloaded chunk for weeks? There's no way to tell the difference between it being unloaded forever and it being actually gone. And I don't think "natural loss of magnetization" is a valid excuse for that.

**Comment by Kreidos** [comment]
> I also doubt that OC could easily detect when a HDD item is "destroyed" - how would it know the difference between a normal BuildCraft pipe and a void pipe, and which one counts as "destroying"?

True, but it definitely can tell when a user has crafting-gridded it, or placed it in a dissembler. These methods are deliberate acts of destruction, not carelessness or bugs. In these cases, at least, it would be safe to remove the folders.

I'm not sure if it's possible, but a periodic "garbage collection" could detect otherwise-destroyed drives. Every X minutes OC checks if a folder has an associated item in-game; if not, it can be removed.

**Comment by LordFokas** [comment]
> I'm not sure if it's possible, but a periodic "garbage collection" could detect otherwise-destroyed drives. Every X minutes OC checks if a folder has an associated item in-game; if not, it can be removed.

That would imply a save-wide scan for data storage items. I don't think so.

**Comment by Kreidos** [comment]
Raid-based storage already behaves this way; upon removing a drive from the array the actual folder is wiped out. At the very least, disassembled drives and crafting-gridded drives/floppies should do the same.

**Comment by fnuecke** [comment]
I agree that removing the storage when formatting them via crafting and disassembling could make sense, everything else is a no because it's just too unreliable or expensive to check. However, I also kinda like that there's still a chance to recover the data... will see.

**Comment by skyem123** [comment]
Maybe make a list somewhere of addresses of FSes that will be cleared of data after some time and after the data folder gets too big, so there is a chance to recover data, but it should have time for people to go "oh wait ****! UNDO!" if they wipe something important.

**Comment by Vexatos** [comment]
How about a new block like the disassembler, the "shredder" or something? Just a random suggestion.
Would obviously only allow intentional file deletion in that case.

**Comment by Kreidos** [comment]
If the argument is that we shouldn't delete folders because drives might be accidently deleted... Why would making a 'shredder' get around this issue? You could 'accidently' shred them just as easily as disassembling.

In that case, I suggest we should make a third block called a "Super-for-real-this-time DeGausser" that actually deletes folders.

**Comment by MaHuJa** [comment]
- Config setting (under filesystem? what about unmanaged?) for how long the folder is kept around, default 7 days. (maybe 1000 days, practically defaulting to current behavior)
- When OC detects a drive goes away forever, if config says 0 then delete immediately, else add its uuid to a "deleteddrives" file in the save together with the timestamp.
- On startup (only?) run through the deleteddrives file, deleting that which is older than the config.

Best of both worlds.

**Comment by SaphireLattice** [comment]
How do you p;an to 'detect deletion'? Short of somehow marking every single
used drive and keeping track of them. And there is a problem of things like
NEI, that allows duplicating or deleting an item.

**Comment by LordFokas** [comment]
You cannot reliably implement it without resorting to ridiculously expensive save-wide scans, and even then, it's likely you cannot search every container in the save and delete folders for drives that still exist in the game. This is especially true if you play with more mods, or any mods at all that add any kind of item storage. You'd probably have to patch the very core of the vanilla game, and it wouldn't be a small patch either. There may be something I'm missing, but even though I'm always in favor of this kind of optimizations I cannot see any way where this would be possible nor reliable.

**Comment by MaHuJa** [comment]
"When oc detects" means exactly what I wrote. When it detects. Not whenever a drive goes away, when oc detects it happening. 

> but it definitely can tell when a user has crafting-gridded it, or placed it in a dissembler. 

Or a raid insertion, raid removal, un/managed mode change.

Yes, that does mean you don't get to remove everything that's gone, some will fall through the cracks. As you correctly point out, it's not feasible to detect everything. Problem is it's also a strawman: I never said otherwise.

**Comment by skyem123** [comment]
The thing is, the fact that it's possible to recover data is quite nice.

**Comment by payonel** [comment]
I personally don't think it'll be safe to remove files automatically - and they really don't take up much real space. When things go wrong it's a nice recovery option
