### ISSUE TITLE
"Errors running the class transformer" on 1.8

### ISSUE THREAD

**Issue by jcc10** [MightyPirates/OpenComputers#1765]
So I am also getting this message both on my client and on my server.

![image](https://cloud.githubusercontent.com/assets/1398636/14513204/4c5a09a4-019a-11e6-94fc-20e6b752a122.png)

I will assume that it is because of a mod they both are running (I have some Server Side mods and some Client Side mods.)

[Mod list](http://minecraft.jcc10.net/mods/)
[Server Log](https://gist.github.com/anonymous/db71c8d7fc49db56276199168a342d75)
[Client Log](https://gist.github.com/jcc10/b945b2541cb7fb464b11cc4bd267d6bc)
[Client Log with just build-craft](https://gist.github.com/jcc10/e20c2f10f4c952d66016583c6aebe9c2)

I do not have academy craft, I do have build-craft, also I am on 1.8. #1509 also has build-craft, this may be the issue. (I made a new issue since I am on a different version of minecraft.)

**Comment by fnuecke** [comment]
Thanks for reporting, will update to support new wrench API.
