### ISSUE TITLE
Crash when placing second screen

### ISSUE THREAD

**Issue by ultrasn0w** [MightyPirates/OpenComputers#1769]
When trying to connect 2 screens my server instantly crashes throwing out this error:
https://gist.github.com/ultrasn0w/5ff67ad7c4b471e7739894b525066979
This might have something to do with:
https://github.com/MightyPirates/OpenComputers/commit/e45acd967be9fb5461cc58f5ade6cd4df63d681e

using OC MC1.7.10-1.6.0.2-rc.1

**Comment by payonel** [comment]
I could not repro this using the same version. Can you give specific steps?
mc 1.7.10
forge 10.13.4.1558
oc OpenComputers-MC1.7.10-1.6.0.2-rc.1-universal

/oc_sc a computer down, place 2nd screen, no crash

**Comment by fnuecke** [comment]
;lnasdglmasdg;lknsad

Right. That's why that wasn't going through the resources system before -.-

**Comment by fnuecke** [comment]
Allrighty, time to push a hotfix.
