### ISSUE TITLE
Color palette change? (suggestion)

### ISSUE THREAD

**Issue by GopherAtl** [MightyPirates/OpenComputers#177]
the current setup seems to use a 2-4-2 palettes for 4bit and 8-8-4 palette for 8bit colors; both of these share the distinct downside of having no true grays. 8-8-4 has 2 colors that are approximately gray, but 2-4-2 has nothing remotely gray. 

The 8-8-4 palette is a fine palette for photos and full-color images in 8bits, but that seems not to be a very practical or likely application of OC computers, where drawing a 160x50 resolution color image a character at a time, changing background color and doing gpu.set for each "pixel" takes around 75 seconds. More likely are programs manually selecting colors, and for that, grays would be more valued. So I'd suggest for the 8-bit pallet using a 6-8-5 palette instead, with the spare 16 colors dedicated to shades of gray. 

As for 4bit, either some variant of the common RGBI palette used in ANSI, or the minecraft palette as used with dyes, would again better fit expectations and include at least some shades of gray. I'd be happy with either, tho I'd prefer the minecraft palette in this case, just for a sort of thematic consistency with the minecraft world.

Either of these would introduce make grays available while not having a too much impact on existing programs using colors, which, at least imo, would be beneficial in constructing text-mode gui elements in OC programs.

**Comment by fnuecke** [comment]
It's 1.2.1 and 3.3.2, actually. 8.8.4 would be 20 bit? The reasoning was not having to differentiate in code between the actual supported color depth, but I suppose the difference of available colors is too big to make this feasible anyway.

I'll hijack this issue as a reminder for me, for the rewrite of the screen rendering I have planned. I'd like to avoid changing the default palette, so as not to break existing stuff, but if it's feasible I'm hoping to make it possible to support custom palettes. This won't happen very soon, though. I won't have time to work on the mod over the next two or three weeks, except for fixing bugs, maybe. After that, we'll see.

**Comment by awsmazinggenius** [comment]
On the topic of color, I'm making an image editor for CC and OC and I noticed an anomaly.
This screenshot shows that I want to set the color to #4c4c4c, ComputerCraft's colors.gray, but it will not change to that color. It says that it _is_ #4c4c4c though (just in decimal format not hexadecimal), but in reality it is #434300.
![image](https://cloud.githubusercontent.com/assets/5460420/2530682/30df08ba-b529-11e3-875b-b83a29fa5695.png)

**Comment by GopherAtl** [comment]
feunke, 8-8-4 is what it's conventionally called, 3 bits = 8 levels of red/green, 2 bits = 4 levels of green. They don't refer to it by the bits because not all palettes use even bits per channel. 6-8-5 is not using even numbers of bits per channel, just has 6 levels of red, 8 of green, and 5 of blue, which gives 6_8_5=240 colors, leaving 16 unused by the core palette.

The palettes are pretty similar, I'd be surprised if the change (Well, the 8-bit) had much effect on existing programs, excepting those that are using the two tiny islands of almost-gray available in the current one - and those of us doing so would be happy for the change if it means more and truer grays! - and it gives you those extra 16 colors that can be customized independently of the rest of the palette. This last feature is what made it a popular choice for master palettes back when 8bit palettes were a bigger thing than they are now. Costs a bit more to convert from hex codes, but it's not that bad, can translate directly to an index in the 240-color space and then only have to do squared distance checks against that one plus the 16 custom colors at the end.

and awsmazinggenius, there are 2 colors that can pass for gray in the current available palette, one is centered around 0xb4b4b4, the other around 0x5a5a5a. Since I was posting anyway thought I'd share that, but don't reply, 'cause this is a bit tangent to the issue.

**Comment by fnuecke** [comment]
Ah, right, I wasn't thinking in palette terminology, was too focused on the current implementation.

Thanks for the feedback and information. I'll definitely come back to this when I have more time!

**Comment by fnuecke** [comment]
Done in local branch. As suggested, 8 bit uses 6-8-5 with 16 shades of grey (excluding black and white), 4 bit uses Minecraft's color palette (slightly tweaked to be more vibrant). Old way of calling methods still works (picks best match in 4 bit mode), but setForeground/setBackground now takes a second parameter, a boolean, which if true means the first value is a palette index as opposed to a color. In addition there are two new methods, `getPaletteColor(index:number)` and `setPaletteColor(index:number, color:number)`.
