### ISSUE TITLE
[Feature Request] Rack-Mounted Toggle Switches (Example incl.)

### ISSUE THREAD

**Issue by MyNameIsKodos** [MightyPirates/OpenComputers#1770]
I was thinking the other day, since we can get the click position on the front of rack, how hard would it be to make a rackmounted rocker switch-like thing.  Example:

![Rocker Switches](http://imagehost.vendio.com/preview/a/35010908/aview/RockerSwitch1small.jpg)

Obviously 10 switches would be hard to do, but maybe four 2x1 pixel switches arranged in a similar manner to the Computronics Light Board. I can provide a picture of that if need be, but I didn't want to stick a bunch of pictures in this suggestion.

Note that this wouldn't be redstone-toggling switches, but rather switches used completely in code, with maybe a texture change on right click.

EDIT: Changed the title because confusion

**Comment by Vexatos** [comment]
So a program could then query `board.isActive(2)` for the second switch, for instance?
I like that idea... One could even make the switches coloured if that wasn't what the light board was doing... How would it look in the world? little cuboids sticking out of the rack, glowing red if on? I don't think it should have multiple modes like the light board but instead have a set number of switches for balance. It'd definitely look pretty neat.

**Comment by MyNameIsKodos** [comment]
Yeah, definitely. I don't know about doing the cuboids sticking out unless that's something that Sangar could add in the code. As for a texture, I had a couple ideas in mind. Not sure how I feel about it glowing red, as you could just use a lightboard for that. And yeah, no mode switching, just a basic 4 switch setup.

**Comment by brisingraerowing** [comment]
This looks interesting.

**Comment by MyNameIsKodos** [comment]
After some further contemplation, I'd also like to see these things fire an event when a switch is flipped, returning the index of the switch that was flipped, as well as the new state  (true/false)

**Comment by Vexatos** [comment]
That does sound like a good idea.

**Comment by SaphireLattice** [comment]
But there will be methods to get the state, right? In case of reboot.
Or will it reset when the controlling server reboots?

**Comment by Vexatos** [comment]
Well it's supposed to consist of physical switches, so yes, the state will be retained. The colour may not in case they'd become colourable.

**Comment by MyNameIsKodos** [comment]
I'd really like to leave coloring them out. Light boards exist, and should be used imo because they're nice.

**Comment by xarses** [comment]
uhh, not to be 'that' guy but what's wrong with coding buttons onto a T2+ screen?

**Comment by SaphireLattice** [comment]
Because the request is about the /rack-mounted/ buttons. Unless you're
implying that there should be rack-mounted screen. And a touch-screen,
that's available from outside.

**Comment by gjgfuj** [comment]
I mean, a rack mounted touch screen /would/ allow for both readout and
buttons. (interesting, give it like a 10x1 display.)

**Comment by SaphireLattice** [comment]
10 by 1 screen sounds a little bit small.. Maybe it should be bigger but be
controlled only with 'physical' buttons. Maybe with a GUI but everything
being available from outside?

**Comment by Vexatos** [comment]
The light board from Computronics already supports up to 14x3 pixels.

**Comment by gjgfuj** [comment]
10×1 characters is a large size, that probably would be a bit big for a
server rack. That is to say, an ultimate resolution higher than the light
board. That way, it works just like a typical screen component but with a
very small screen size, so as it can still have all the features of a t2
screen but a limited size, because it's supposed to fit on a server
rack.... (Since, Y'know.... There's not a lot of room there), and you can
allow for touchscreen interaction using just the screen ways.
10x1 is possibly too big or too small widthwise, that should be adjusted so
it can work properly. However, I would not go above *x2, and no taller than
1, really.

Allows for both readout and touch interaction without being too powerful.

**Comment by Vexatos** [comment]
I'd rather have an actual board of switches like just like @MyNameIsKodos suggested. It sounds like a nice idea to me.

**Comment by gjgfuj** [comment]
That's fair. A touchscreen is just an option.

**Comment by fnuecke** [comment]
This is in Computronics now, isn't it? Can I close this? @Vexatos?

**Comment by Vexatos** [comment]
I still need a model for the mountable; apart from that it's implemented.

**Comment by MyNameIsKodos** [comment]
Looks like Computronics is adding this. Closing.
