### ISSUE TITLE
[Feature-Request] Modify an AE2-Interace output settings with the AE2-Interface itself

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1772]
I know i can get an table with itemstacks from an AE2-Interface. Why cant i use this itemsstacks to modify the AE2-Interface output itself? Why do i have to use a database-upgrade, which I only can modify without the use of an inventory-controller and a drone/chest full of items?

Maybe it is possible to add a feature to modyfi the AE2-Interface with itself, or (and) the database-upgrade with an AE2-Interface. Somthing like:
`interface.itemToOutput(slotOfItem)` the slot would be the same (i guess) as the index of the item from the itemstack table
OR
`interface.storeInDatabase(slotOfItem, dbAddress, dbSlot)`

BlankWolf

**Comment by fnuecke** [comment]
The [interface driver](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/integration/appeng/DriverBlockInterface.scala#L26) [provides a `store` method](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/integration/appeng/NetworkControl.scala#L79), which allows configuring a database with items queried from the AE2 system.
