### ISSUE TITLE
[Request] Different speed wired cables/wireless

### ISSUE THREAD

**Issue by sykoboss** [MightyPirates/OpenComputers#1773]
While I've seen not too much use for cables in general (haven't been around the forums much), I think that there should be different speed network cables, just for variety and for the various tiered networks (or something). With this in mind, there could also potentially be different wireless speeds, like three tiers or something akin to that. I didn't see any suggestions for this, so I decided to put it here.

**Comment by gjgfuj** [comment]
As networking is instantaneous (ish) these wouldn't really fit. Different
speed network cards and relays, sure, but network cable would probably
require a full overhaul of the network code.

**Comment by Vexatos** [comment]
Well, there is a limit on the size of a network message (8kB by default)... So for really really large data, this _would_ matter. 8kB is a lot, though.

**Comment by payonel** [comment]
seems to be an arbitrary limiter - interesting idea but really only reduces usability at this point.
