### ISSUE TITLE
Wrong backspace symbol in OpenOS shell

### ISSUE THREAD

**Issue by IgorTimofeev** [MightyPirates/OpenComputers#1775]
I'm using OpenComputers-MC1.7.10-1.6.0.3-rc.1-universal.jar mod version and OS X version of Minecraft. When i try to press backspace in shell, i get following:

![2016-04-24 23 51 35](https://cloud.githubusercontent.com/assets/11760002/14770337/46424538-0a80-11e6-9a14-02b02b32bd52.png)

But it edit.lua everything's okay - is seems like shell uses wrong key_down event data. Hope this will be fixed soon, thanks.

**Comment by payonel** [comment]
This looks like a mac-specific problem. I'll look into this promptly.

**Comment by payonel** [comment]
@IgorTimofeev could you help me by testing a couple things?
in-game, start lua prompt. then enter this command:
lua>=event.pull("key_down")

Press enter once (the blinking cursor should go away) and then press the same key you are having problems with (that you opened this ticket for) - which you are calling the "backspace"

You should then see some information printed, and the lua prompt returns. Here is what I see when I press backspace:
"key_down"      "d8a526bb-ad4c-40dc-b721-df7790134e46"   8       14
The long GUID value I do not need, just the 2 digits after that. In my case 8 and 14

Thanks

**Comment by IgorTimofeev** [comment]
@payonel There's no need for such detailed instructions, I know how the event system works, thanks :D 
But here is your event data:

![2016-04-25 9 31 19](https://cloud.githubusercontent.com/assets/11760002/14775564/36e510e2-0ad1-11e6-9763-8c245c2b68ec.png)

The problem is that shell uses **3rd** key_down event argument instead of **4th**.

![2016-04-25 9 34 25](https://cloud.githubusercontent.com/assets/11760002/14775590/7472ace4-0ad1-11e6-8710-53cf39f28048.png)

Personally, I've fixed this problem by adding the following code in the **lib/term.lua** file:

![2016-04-25 9 51 36](https://cloud.githubusercontent.com/assets/11760002/14775925/b5f6c540-0ad3-11e6-81cd-7ca342802635.png)

**Comment by payonel** [comment]
The problem i have with this is that 8 is CORRECT ascii for backspace, 14 is not. 14 and 15 are SO and SI codes (old-school control key). And 127 is actually the delete key. I am not checking the wrong return, your keyboard is sending SO-DEL on backspace it seems. I think this may be a Russian keyboard layout issue.

I'll study this situation more and provide feedback and PR later.

**Comment by payonel** [comment]
Let me rethink this.
That first return is the input string. Your backspace is sending char(127) as the one and only char in the input string (strange! -- is this a type of escape sequence perhaps?) And a keyboard code of SO (14). The two together might represent "backspace" for your keyboard layout. Again, I'll review this more before I make any changes.

**Comment by Vexatos** [comment]
@IgorTimofeev is correct, you should not be checking the "char" returned but instead the key code.

**Comment by payonel** [comment]
Trusting keyboard code 14 to uniquely and universally mean backspace is entirely new information to me. This whole situation is odd to me that we cannot use ascii \8 for "backspace" -- but I'm learning. Also, Vex just linked http://minecraft.gamepedia.com/Key_codes to me. I'll review and update appropriately.

**Comment by fnuecke** [comment]
I'm told this is closed via #1782.
