### ISSUE TITLE
some components don't register

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#1777]
some of the components don't register when they are added to a robot or tablet. Registration is needed, even if they don't have any methods, as it is useful to know what components exist so that you may determine if you want to take action based on their presence

these don't emit component_[added|removed] events and otherwise are invisible
solar generator
hover

these can be seen otherwise, but dosen't fire the component events
tank upgrade
inventory upgrade 
batteries

**Comment by payonel** [comment]
there is device info for all of these now
