### ISSUE TITLE
solar generator should have some methods

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#1778]
related to #1777, the solar generator has no methods, but it should

I think we should be able to identify if the component has the correct light level to produce a charge.

something along the lines of
canSeeSky() bool - has line of sight to sky
hasLight() bool - has enough light to charge
isCharging() bool - is producing energy

the end result would be that we can determine that we have the correct parts to run the generator

**Comment by Vexatos** [comment]
That would be yet another component to keep in mind when choosing a CPU. I don't think this is very useful. You can simply probe the energy storage twice and check how much it changed to see if it is running.

**Comment by xarses** [comment]
by that logic
- you have to already be in a sleep loop as it doesn't generate enough power to notice while you are doing anything else
- you will want to keep track of time of day so you know you can stop to charge
- you will have to keep track of your ability to see the sky, so you will need to keep a geolizer running to see if this is a good place to stop
- #1777 is addressed so we know we have a solar generator

**Comment by SaphireLattice** [comment]
Maybe make that toggleable? Like an 'interface switch' on the panel itself,
toggled by shift-clicking.
Or there could be an upgraded version of the solar panel that will be a
component (and that upgrade should be relatively cheap as the power
generation is not touched, because balance).
