### ISSUE TITLE
batteries in upgrade containers behave, well weird

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#1780]
batteries out side of upgrade container, appear to follow standard item damage as charge that most mods follow (no dmg indicated == fully charged and the dmg line indicates charge level)

however, when a battery is placed into an upgrade container, instead of slowly taking damage related to remaining charge, the dmg bar reflects 0, and seems to update oddly. I think it's progressing from 0/100 dmg == full to 100/100 dmg to being discharged, but I can't tell for certain.

If you pick the battery from the upgrade slot, the damage bar inverts again, but not necessarily at the level expected. (probably due to below)

finally, batteries in upgrade containers are consumed last making it difficult to remove when they are the only charge left in the bot.

**Comment by fnuecke** [comment]
I'm relatively sure what you're observing is just the sporadic updating of the visualization on the client. In a singleplayer world you could check this by hitting escape to save the world and force an update. If you're sure that's not it I'll have a look.

**Comment by xarses** [comment]
Forcing the update doesn't do anything nor does completely reloading the world / restarting the client

Here are some pictures for your enjoyment

Fully charged battery
![2016-07-19_15 22 13](https://cloud.githubusercontent.com/assets/2107834/16968784/d9fec2fa-4dc5-11e6-8452-ef1d777ca490.png)

Fully Charged battery in upgrade container
![2016-07-19_15 22 15](https://cloud.githubusercontent.com/assets/2107834/16968794/e9d15738-4dc5-11e6-85cd-2e5db310c1ac.png)

Partially drained battery in inventory
![2016-07-19_15 30 05](https://cloud.githubusercontent.com/assets/2107834/16968825/143dc90c-4dc6-11e6-8c2f-40ec4db87ef9.png)

Partially drained battery in upgrade container
![2016-07-19_15 30 07](https://cloud.githubusercontent.com/assets/2107834/16968837/21c6ee8c-4dc6-11e6-9d35-816622e74ff4.png)

**Comment by xarses** [comment]
Doesn't repro in 1.6.x
