### ISSUE TITLE
MFU

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#1781]
Code is done I believe? Things left to do:
- [x] Tooltip.
- [x] Manual entry.
- [x] Texture.
- [x] Rendering a highlight on the block (and face?) it's bound to while holding it in hand.

Anything else, @Vexatos?

**Comment by Vexatos** [comment]
@MyNameIsKodos suggested the texture changing some LED colour depending on if it is bound at all (blue if not), if it is in the right dimension (red if not) and if it is sufficiently nearby (yellow if not); not sure if useful. The overlay would definitely be nice. I guess the best idea would be... to add those things to [this branch](https://github.com/Vexatos/OpenComputers/tree/mfu) so they it can be merged at once.

**Comment by MyNameIsKodos** [comment]
Green = In Range and Right dimension
Yellow = Not In Range, Right Dimension
Red = Wrong Dimension
Blue = Not Bound
