### ISSUE TITLE
Sincere apologies

### ISSUE THREAD

**Issue by ebragas** [MightyPirates/OpenComputers#1789]
Hi @fnuecke 

I am having a very difficult time getting in touch with an admin of the OpenComputers forum. I really apologize for reaching out in such an inappropriate location, however nothing else has worked.

I am running into login issues.

If you can please contact me at ericbragas412@gmail.com, I'd appreciate the help.

**Comment by LizzyTrickster** [comment]
Hi,

What kind of login issues are you getting? I manage the forums at current so I'm probably in the best position to help you.

**Comment by ebragas** [comment]
Hi @LizzyTrickster 

I'm both unable to login with a new account as well as reset my password on an existing one. The account email I would like to use is: ericbragas412@gmail.com. 

Several attempts at using the password reset did not work. I tried all options and my email was rejected when responding to the admin address.

**Comment by LizzyTrickster** [comment]
Have you checked your email's Spam filters? I'm not sure why emails get put in there, but it might be in there.

As for the admin address; can you tell me the address? I can't see where it's defined in the settings :/

**Comment by ebragas** [comment]
I actually did receive the email each time I requested it. The trouble was that when I would reset my password using the options they provided (eg. link, link + verification codes), and then attempt to login using the new password, it would still fail.

I responded to the password reset email, and received the following failure to send notice from gmail:

Delivery to the following recipient failed permanently:

```
 noreply@cil.li
```

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain cil.li by mail.nuecke.de. [188.165.236.185].

The error that the other server returned was:
550 5.1.1 noreply@cil.li: Recipient address rejected: User unknown in virtual mailbox table

**Comment by LizzyTrickster** [comment]
Well the fact that it says "noreply" might be a giveaway as to why it rejects it.

I've restarted the processes responsible for providing the forums (web, database, etc), can you try doing the password reset again? I can see 2 usernames for you, badcode (using a designmind.com email) and badcode9 (using your Gmail one). Try both of them and tell me if you can get in :)

**Comment by ebragas** [comment]
I should've noticed that :)

I used the link in the email to reset the password, and per the reset page this is successful, but when I attempt to login it fails again.

When I use Option #2 in the email and provide my User ID and Validation Key, the reset fails per the page.

Attempted both options for both accounts.

**Comment by LizzyTrickster** [comment]
I can reset your password for you manually, if you let me know which account you want it for and I'll reset the password to a random one then email it to the address with that username. I'll also delete the one you don't want to keep

**Comment by ebragas** [comment]
That would be much appreciated. Please reset it for the account: ericbragas412@gmail.com.

Thank you!

**Comment by LizzyTrickster** [comment]
@ebragas I've sent you an email with the password in it, Should come from "lizzy@theender.net".

This issue can probably be closed now that we're potentially conversing over email :)
