### ISSUE TITLE
External Drive Bays

### ISSUE THREAD

**Issue by XeonSquared** [MightyPirates/OpenComputers#179]
I generally like to use Tier 3 computers over server racks, and the reason why is that they can connect to external components such as tape drives and printers. There is something I would like though, to expand my computer setups, and that is external drive bays. If you've seen a server rack, there were probably drive bays external to the server machines themselves. Alternatively, there are docks for SATA drives, which can be bought fairly easily. Either way, it expands the computer's storage ability externally, by adding more hard drives. Now, depending on the tier, there should be 4, 9 or 16 drives in each bay, based on the fact a Tier 3 server can hold 4, and you can put 4 Tier 3 servers in a block. As a possible Tier 3.5 expansion, perhaps a RAID array, which combines the drives in the bays into a single filesystem, for easier access.
Maybe? :D, that'd be awesome, because then I could expand my setups even more, including tape drives as storage. Thanks o/
(Also it's ShadowKatStudios from IRC)

**Comment by fnuecke** [comment]
I think this was discussed in some other issue before... yeah, [here](https://github.com/MightyPirates/OpenComputers/issues/133#issuecomment-37096571). But it makes sense to have an extra ticket for it.

Note that servers _can_ connect to external components. They're just limited to one side (as configured in the rack) to avoid accidentally "short-circuiting" them, leading to a component overload.

**Comment by asiekierka** [comment]
Considering adding HDD arrays to Computronics. Four drives in an array, configurable to duplicate or unionize them.

**Comment by fnuecke** [comment]
Well, if anything it'd be interesting to see if the API is good enough to make it work, so I'd say go for it. I think it's special-case enough so it doesn't have to be in the core.

**Comment by MaHuJa** [comment]
I was thinking to do achieve this with a different method.
Have you seen how many drive slots you have in the t3 servers?
... and thought "file server!" ?
I did. (No idea what I'd use all that space for, yet. I have yet to max out a tier1 disk.)

Now, would we have to override the entire filesystem table (and keep them from getting the original through require) or is there another way to hook into it at a lower level - like a software defined component? Actually I'll bring that to a separate issue if I can't find a way to do it.
