### ISSUE TITLE
[GT5u] Lable's don't resolve correctly in MP

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#1793]
MC 1.7.10
gregtech-5.09.21
industrialcraft-2-2.2.817-experimental
Forge 1566

When running `inventory_crontroller.getStackInInternalSlot()` on my usual MP haunt, I was finding that I was going to have problems dealing with the gregtech mod items as they weren't giving the 'correct' data, but after comparing that to SP, where the data is resolved correctly, I see that there is actually an issue between the two.

GT5u uses a shared item for tools and another for items, and yet another for ores, then using metadata and dmg magic it resolves to a friendly name.

With these meta-things, we see that they are not properly resolving in MP but, do resolve as expected in SP. (Although I'd like to see some of the missing metadata properly (material, tier, and proper damage for non-electric tools) This is secondary to the fact that we don't get the correct labels back, so it becomes impossible to find the right type of tool with out 1) creating separate systems for MP and SP, 2) Hard coding item ID's in MP to get it to work.

We can see this issue quite clearly in the GregTech provided Clay Dust

Clay Dust (SP)

```
{
  name="gregtech:gt.metaitem.01",
  tier=2147483647,
  lable="Clay Dust",
  charge=0,
  maxSize=64
  size=1,
  maxDamage=0,
  hasTag=False
  canProvideEnegery=false
  transferLimit=0,
  maxCharge=0,
  damage=2805
}
```

Clay Dust (MP)

```
{
  name="gregtech.metaitem.01",
  tier=2147483647,
  size=1,
  maxDamage=0,
  maxSize=64,
  canProvideEnergy=false,
  lable="gt.metaitem.01.2805.name",
  transferLimit=0,
  hasTag=false,
  charge=0,
  maxCharge=0,
  damage=2805,
}
```

And a selection of tools for Illustration
Osmium Pickaxe (SP)

```
{
  name="gregtech:gt.metatool.01",
  tier=2147483647,
  label="Pickaxe"
  charge=0,
  maxSize=1,
  size=1,
  maxDamage=0,
  hasTag=true,
  canProvideEnergy=false
  transferLimit=0,
  maxCharge=0
  damage=2
}
```

Cobalt Pickaxe 5177:2 (MP)

```
{
  name="gregtech:gt.metatool.01",
  tier=2147483647,
  size=1,
  maxDamage=0,
  maxSize=1,
  canProvideEnegry=false
  lable="gt.metatool.01.2.name",
  transferLimit=0,
  hasTag=ture,
  charge=0,
  maxCharge=0,
  damage=2
}
```

Blue Steel Wire cutter 5177:26 (MP)

```
{
  name="gregtech:gt.metatool.01",
  tier=2147483647,
  size=1,
  maxDamage=0,
  maxSize=1,
  canProvideEnergy=false,
  label="gt.metatool.01.26.name",
  transferLimit=0,
  hasTag=true,
  charge=0,
  maxCharge=0
  damage=26
}
```

**Comment by fnuecke** [comment]
Then I guess those items' labels do some fancy custom localization that only works on the client. Nothing I can do about that I don't think, sorry.

**Comment by xarses** [comment]
I worked through this some with the help of GT folks IRC, the problem isn't really that the label is resolving funny. (Although we came to the conclusion that the because it makes no sense to localize the server side, the client giving us the localized value is wrong in the sense that we should be getting the same result, if we cant localize the server, we shouldn't do the client either)

The problem appears to be two fold. First the items "name" which confused me at first is the MC internal name, however because GT makes use of the meta items to reduce , the name is not correct as it stops before the `damage` is applied . This makes `gregtech:gt.metaitem.01` generic while we can see in MP we attempt to access the `label` `gt.metaitem.01.2805.name` while the .name lookup must fail because its doing something with locale, we see that here the `damage` `2805` was applied into the string that we did get back. This makes me believe that we are missing some data that should be applied to the name. This also means that for GT items `robot.damage()` is probably wrong since `item.damage` is the meta id, not the NBT tags for damage that GT uses.

On the other side, IC2, IHL, Railcraft, GT, others make extensive use of oredict to help enable inter-mod compatibility, if we switch or add the oredict common name, then we don't care what any of the internal names are as we get the common name for it's oredict parent.

clay dust

``````
Ore entries for <ore:dustClay> :
    <IC2:itemDust:1>
    <gregtech:gt.metaitem.01:2805>```
``````

Wire Cutter

```
Ore entries for <ore:craftingToolWireCutter> :
    <IC2:itemToolCutter:*>
    <gregtech:gt.metatool.01:26>
    <ihl:item.ihlTool:2>.withTag({"GT.ToolStats": {MaxDamage: 2000}})
```

Pick Axe

```
Ore entries for <ore:craftingToolPickaxe> :
    <gregtech:gt.metatool.01:2>
    <IC2:itemToolBronzePickaxe>
```

**Comment by SaculRennorb** [comment]
this issue still presists for at least GT comunity edition, and mbe some other mods too - @fnuecke did you ever take a second look at this after @xarses found out what might be the problem?

to be a bit more precise; OC resolves _a_ name for GT items, but just not the correct one

**Comment by payonel** [comment]
@SaculRennorb i'm the maintainer now. try enabling item ids in the configs
`insertIdsInConverters=true`
and test that the ids match between SP and MP

**Comment by SaculRennorb** [comment]
@payonel the item ids match in sp and mp, GT only uses one id for groups of items e.g. all dusts have id `5922` with different damage values (/metadata?) 
OC reads the correct item name (gergtech:meta_item_1) but fails to translate it to the corect lable e.g. all dusts have the lable 'Draconium Lense' (i spose this name is specific for my pack, mitght be different in other modpacks) 
after enabeling the ids this hasnt changed, but now an additional `oreNames` column gets put in the item table wich (i suppose) is the oreDict name(s) for the item, which is resolved correctly and some column just named `n`

**Comment by payonel** [comment]
i recommend you play with that settings enabled to true and work with that. we have that default false for those that prefer to keep some of the mystery of immersion with in-game items.

**Comment by SaculRennorb** [comment]
hm, alright i already got that from the issues on nbt data, but i'd say the lables not resolving correctly is certainly a bug.
