### ISSUE TITLE
OpenComputers-OpenModularTurrets-IC2 incompatibilities

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [MightyPirates/OpenComputers#1795]
Hello,

I have open computers and open modular turrets installed ( recommended forge for 1.7.10 ), as a reference check this issue:

https://github.com/OpenModularTurretsTeam/OpenModularTurrets/issues/221

When I remove OpenCC the game stops crashing (client crash) when placing turret bases from open modular turrets, IC2 not installed off course, I could install IC2 as a work around but is a work around.
Might there be anything wrong on your side that could be fixed?

Thank you for your time.

**Comment by LizzyTrickster** [comment]
It's OpenComputers, not OpenCC. As far as I know OC doesn't ship the api for IC2.

In the issue you referenced they asked you to try and see what mod was causing the issue, which lead you to OC. Could you provide the crashlog that just has OMT and OC?

**Comment by Ganjalf-Amsterdoom** [comment]
Apologies for the wrong acronim.

Full log: http://pastebin.com/kAVPTZ1y

Crash log: http://pastebin.com/KVi6cVzv

Way to reproduce: install opencomputers and open modular turrets (maybe nei and cofh libraries :P) but do not install ic2, give yourself a turrets base tier 1 and place it in the world, client crash (but server does not)

**Comment by fnuecke** [comment]
Replied in the referenced issue.

**Comment by payonel** [comment]
related ticket was closed with latest forge
