### ISSUE TITLE
New interface to allow creating block drivers from env blocks

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#1802]
The adapter currently doesn't check tile entities that are environments (since it's assumed they'd provide components that way). In some cases to allow being more selective without losing the blocks' connectivity it can be desirable to only provide a component via the block driver (specifically: RotaryCraft [and family?]). This can then avoid the component overload that currently quickly introduces.

The format suggested is an additional interface with a stateful check (which needs to be re-checked on block updates).

**Comment by Vexatos** [comment]
[This line](https://github.com/MightyPirates/OpenComputers/blob/22495b9e50b3e7a03392471668326abd2a1d2634/src/main/scala/li/cil/oc/common/tileentity/Adapter.scala#L51) suggests it only applies to TEs implementing the internal environment trait and not environments in general.

**Comment by fnuecke** [comment]
Huh, I completely forgot about that. Interesting. Wouldn't that mean just having a different driver for each state would already do the trick?

**Comment by fnuecke** [comment]
So from what I understand this is a non-issue after all.
