### ISSUE TITLE
[1.7.10] Server rack crashing client when open ( not every time ) 

### ISSUE THREAD

**Issue by maestrous** [MightyPirates/OpenComputers#1805]
nothing to describe. Crash report: 
[crash-2016-05-13_21.29.21-client.txt](https://github.com/MightyPirates/OpenComputers/files/263958/crash-2016-05-13_21.29.21-client.txt)

**Comment by fnuecke** [comment]
There's always something to describe ;-) What was the setup of the rack, i.e. what items were in it? What was the configuration of those items (e.g. items in servers in the rack). What was the configuration of the rack itself? (screenshot is fine)
