### ISSUE TITLE
[1.9] Random Things issues.

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1807]
Getting a crash, presumably from randomthings+OC as it works fine without OC:
https://gist.github.com/Inari-Whitebear/b04155c8c4a9b2de8970b314ba79f447

And some errors regarding that maybe:
https://gist.github.com/Inari-Whitebear/8cb496ce1e0e7a18bc08ee7b5522a0b9

**Comment by fnuecke** [comment]
For the crash, try updating MCMP to 1.2.whateverislatest.

For the log thingers... yep. Forget updating those each MC version :P Will fix.
