### ISSUE TITLE
coloredlightscore.us.to unreachable, alternate no longer working

### ISSUE THREAD

**Issue by LemADEC** [MightyPirates/OpenComputers#1808]
I had to rebuild my dev space, and I've hit an issue with ColoredLight API not downloading.
It appears the fix #1612 is no longer working. Any alternate location/fix to get that API and compile master-MC1.7.10 ?

**Comment by fnuecke** [comment]
Considering it's mirrored on my Maven, I don't see why this wouldn't work. Mind trying again? Maybe it was some random connectivity issue that's resolved now.

**Comment by LemADEC** [comment]
It was failing for a couple days than started to work again.

**Comment by fnuecke** [comment]
Allright, then all is well.
