### ISSUE TITLE
setResolution does not return values as the documentation says

### ISSUE THREAD

**Issue by iamgreaser** [MightyPirates/OpenComputers#1809]
Ref: http://ocdoc.cil.li/component:gpu

Docs say it returns `true` if the resolution was set and `false` if it wasn't.

In reality, it returns `false` if the resolution was set and throws an error if it wasn't.

`setDepth`, on the other hand, _does_ follow the `true`/`false` scheme as documented.

Is it worth maintaining this as a quirk for "backwards compatibility" (that is, change the docs) or would it be better to make it more consistent with the other stuff (that is, change the implementation)?

**Comment by fnuecke** [comment]
Ah, I think that might actually a regression introduced with the viewport logic. Will push what I believe to be the fix in a moment.
