### ISSUE TITLE
Crashing when starting a server

### ISSUE THREAD

**Issue by applejag** [MightyPirates/OpenComputers#181]
Not tested it so much so I do not know exactly when it happens but I think it happens when I use the server rack and servers.
I tried in an totally empty world so it could not be anything else crashing me and each time I boot the computer like 5 seconds later I crash.

Crash report
http://pastebin.com/VNJAP8Tz

**Comment by fnuecke** [comment]
Try updating CalCore.

**Comment by applejag** [comment]
Yea you're right that seem to fixed it. Have not crashed since! Ty for quick reply
You can mark this as closed
