### ISSUE TITLE
1.6 release

### ISSUE THREAD

**Issue by SaphireLattice** [MightyPirates/OpenComputers#1810]
It has been a long time since any stable release on the blog or anywhere else. Is there some kind of milestone for 1.6 or is it just a 'when it's done' release? Point is, will the 1.6 be released any time soon? (and not as a release candidate)

Sorry if I'm asking something stupid.

**Comment by fnuecke** [comment]
I'm waiting for MCMP to be merged into Forge proper (which I hear is supposed to happen tomorrow), then update the 1.9.4 branch and then throw out a new beta (beta due to the ports to 1.9(.4) being virtually untested right now).

**Comment by SaphireLattice** [comment]
I was mostly interested in the 1.7.10. Thanks for the information.

**Comment by fnuecke** [comment]
Yeah, but I'd like to release them at the same time to avoid confusion.
