### ISSUE TITLE
Kicked by AFK while using computers

### ISSUE THREAD

**Issue by Polyana-Fontes** [MightyPirates/OpenComputers#1811]
If a server has `player-idle-timeout=5` configured on server.properties the players will be kicked for AFK even when they are actively interacting with computers.

Minecraft: 1.7.10
OpenComputers: 1.6.0.3-rc.1

**Comment by SaphireLattice** [comment]
It's an issue of afk-detection, it's not really related to OC. All that
detection knows is that you're not moving at all. Nothing to be done on the
side of OC, though I might be wrong here.

**Comment by Polyana-Fontes** [comment]
It is related with OpenComputers because the AFK detection is vanilla and is present on any forge server setup.

The vanilla detection resets the AFK timer when it receives a packet generated from a player interaction to the game, since OpenComputers uses custom packets to handle interactions to the monitor GUIs it needs to reset the timer when that packets are received.

**Comment by Polyana-Fontes** [comment]
I looked into the OpenComputers source code and I think that all is needed to do is to add `p.player.func_143004_u()` to methods executed on player interactions on [the PacketHandler class](https://github.com/MightyPirates/OpenComputers/blob/399e0f44e6e6088a8b95f011011d817cbec45177/src/main/scala/li/cil/oc/server/PacketHandler.scala#L130), the methods are already described on [the PacketType class](https://github.com/MightyPirates/OpenComputers/blob/399e0f44e6e6088a8b95f011011d817cbec45177/src/main/scala/li/cil/oc/common/PacketType.scala#L69)

A good example can be found on `net.minecraft.network.NetHandlerPlayServer` in the methods `processPlayerDigging(), processPlayerBlockPlacement(), processHeldItemChange(), etc`

**Comment by fnuecke** [comment]
Thanks for the pointers, should be fixed now!
