### ISSUE TITLE
Tab-completion can break the Lua prompt.

### ISSUE THREAD

**Issue by bawr** [MightyPirates/OpenComputers#1813]
Steps to reproduce:
0. Have or spawn a computer with OpenOS.
1. Type "lua" and confirm with [Enter] in the OS prompt.
2. Type "os.c" in the Lua prompt.
3. Press [Tab]. This will correctly complete to os.clock().
4. Press [Tab] again. This will crash the Lua prompt. ;_;

**Comment by fnuecke** [comment]
#1815
