### ISSUE TITLE
Right-clicking a microcontroller / computer with an EEPROM doesn't work in 1.8.9

### ISSUE THREAD

**Issue by bawr** [MightyPirates/OpenComputers#1814]
Hey - I'm using the latest build for 1.8.9  (1.6.0.54-dev).

While I was porting my old EEPROM writer code, I discovered a crippling bug - right-clicking with an EEPROM in hand, in the world, no longer swaps it around with the installed EEPROM.

It's not _terrible_ for normal computers, because there's a GUI, but it's also broken for microcontrollers. So now I have to break my uC block every single time I want to check out a new ROM.

And I _already_ had a fun setup for using a dedicated EEPROM-writer microcontroller, which I drove over the network, basically setting a "target image" once, and having it write out a new copy every time a new EEPROM is inserted. Which was super handy, let me tell you.

So... is there any chance the right-click-to-swap functionality may get reinstated? ;_;

**Comment by Vexatos** [comment]
Furthermore, shift-right clicking a computer case to make it boot doesn't seem to work either.

**Comment by fnuecke** [comment]
Fixed the MCU issue in 1.8.9+.

Can't reproduce the issue that computers can't be started with shift-rclick, works fine for me in all versions (make sure you're in creative if you try to turn on a creative case...).
