### ISSUE TITLE
[request] add bundle id on redstone_changed signals

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#1818]
currently, the `redstone_changed` signal only provides the `address`, `side`, `oldvalue`, and `newvalue` with the signal.

In cases where this is a T2 card, or Redstone I/O block and the input is from a mod that provides bundle / channel ID (BluePower, RedLogic, etc...) Then we loose information about which bundle/channel sent the signal.

via testing, I find while it is possible to scan for which channel changed to the value within the duration of a button pulse, it also shows at the same time that there is data loss opportunity in this implementation. This is present when multiple channels have the same value, which is more likely to occur on the transition back to 0

``` side=3
while not event.pull(0.5, 'key_down') do
    _, _, _, _, val = event.pull(10, 'redstone_changed')
    for i=1, 15 do
        sig=component.redstone.getBundledInput(side,i)
        if sig == val then
            print(i, val)
            break
        end
    end
end
```

result

```
14    236
1     0
```

I can imagine another implementation where all states of all channels are actively monitored, but this seems overly complicated.

I'd propose that we just add a possible additional value on the end to represent the channel when the input comes from a bundled cable and we have the T2 / I/O block

**Comment by fnuecke** [comment]
This is basically  #1385, no?

**Comment by xarses** [comment]
Yes, it's a dupe
