### ISSUE TITLE
[suggestion] OC A.K.A OpenComputers needs to be more modular 

### ISSUE THREAD

**Issue by n00b7** [MightyPirates/OpenComputers#1820]
# for oc 1.6

modular floppy disk:
supports being in managed and unmanaged mode and has 3.5[1.44m], high density[2.88M], and 5.25 floppy disk modes
meaning there could be a floppy disk manager block that you can change the format of a normal floppy disk by inserting a film disk[format type]
Modular disk drives:
supports changing between 3.5, 2.25, or high density modes while a normal disk drive can be crafted with a floppy disk tray[format type] to change disk type
creative cpu:
supports switching between 286, 386, 486, and 586 modes whilist the tier 1 cpu is 286, tier 2 is 386, and tier 3 is 486

new architectures:
in the config the following line enables/disables assembly architecture
# DEFAULT = FALSE

enableasm=false
# end of config strip

there would be a bootsectc command the args would be:
[file to make bootsector with] [format of disk] [compiled(true or false)] [hdd(true-or-false)]
there would also be a asmcompile command with the following args:
[uncompiled asm file] [output location] [format(Optional)(default=.bin)]

modular/creative monitor:
supports configuring resolution by having a control panel hooked up automaticly on the side to right-click to change resolution color depth.

sound card:
right-click to set
max volume,
card type(Eg, sound blaster pro 1, soundblaster 16)

modular harddisk:
right click:
configure size
supports up to a max of 6 mb disk and minimum of 50kb disk
shift right-click:
bootsector type(lua or assembly)
allocated or non-allocated (maganed or not managed)

**Comment by Techokami** [comment]
All this should be done from a separate mod, tbqh
Also, you do realize the default architectures in OC are just Lua interpreters and not an x86 emulator? (though someone is working on such an addon, dunno if it's being actively developed or not...)

**Comment by jhagrid77** [comment]
I agree with @Techokami .

**Comment by fnuecke** [comment]
Go to #1043.
