### ISSUE TITLE
[mc 1.7.10(unsure about mc 1.8.x)] [oc v1.5.22] cannot boot from plan9k disk

### ISSUE THREAD

**Issue by n00b7** [MightyPirates/OpenComputers#1821]
when i boot it up form the plan 9k disk it loads and eventuly says:
lib/modules/base/06_cowfs.lua:166:cannot perform arithmetic on local value hnd
(src)lib/modules/base/06_cowfs.lua:166: hnd = hnd \* 2
then beeps like crazy!!!!!!!!

**Comment by LizzyTrickster** [comment]
Oc version?
Mc version?

**Comment by LizzyTrickster** [comment]
Disregard my previous comment

**Comment by fnuecke** [comment]
Fixed in 1.6.
