### ISSUE TITLE
[mc 1.7.10 unsure about 1.8] [oc 1.5.22] monitor tier 3 does not display certain english(Us) letters correctly

### ISSUE THREAD

**Issue by n00b7** [MightyPirates/OpenComputers#1822]
it only happens when one  of the letters is printed on the screen  in a certain space

**Comment by LizzyTrickster** [comment]
Oc version?
Mc version?
Letters in question?

**Comment by gamax92** [comment]
It's probably just that your IRL screen is too small or GUI scale setting too high and is causing T3 to have to scrunch itself to fit. Try reducing your GUI scale setting or decrease the OC Screen resolution using the resolution command: `resolution 80 25`

**Comment by LizzyTrickster** [comment]
Ignore my previous comment, it's in the title

**Comment by fnuecke** [comment]
What gamax92 said. Otherwise, you'll have to get a _lot_ more specific than this.
