### ISSUE TITLE
[Suggestion] Make install.lua support installing any connected loot disk.

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#1827]
Just an idea. @fnuecke's suggestion was adding a `.lootprop` file to every loot disk and having `install.lua` check that. Maybe it could contain installation instructions. This would allow installing all this new loot disk software more easily.

**Comment by fnuecke** [comment]
All right, so. For the uninitiated: the motivation of this is to make driver disks as user-friendly as possible, to make the transition from magic built-in filesystems easier.

So here's my proposal for how `install` should behave when encountering a `.lootprop` file.

If the file is empty, just copy everything from the loot disk to the target file system.

If the file isn't empty, `os.execute(...)` it, passing source and target paths (probably as paths in `mnt` would be the easiest). This allows full control from the `.lootprop` file, be it as simple as running `os.execute("cp -r ...")` followed by a `os.execute("rm blah")` or whatever people might come up with. A slightly simpler variant would be to `os.execute` each line in the `.lootprop` file, with two env vars being set (`INSTALL_SRC` and `INSTALL_DST` or so?). Not sure if that'd be powerful enough tho.

**Comment by SaphireLattice** [comment]
Uh, are the drivers available on oppm, by the way?

**Comment by payonel** [comment]
work is in progress.

**Comment by skyem123** [comment]
I think that it shouldn't be a script, because then what would happen if (theoretically) someone reorganised the FS structure, (for example, if someone wanted `/usr/` to exist)

**Comment by payonel** [comment]
@skyem123 brings up a good point and my solution is to provide a $ROOT path that the lootprops should respect. If we are concerned this would be hard for custom lootprop implementers to use (it really shouldn't be) I can sandbox the filesystem. However -- even that could be circumvented if the lootprop dev really wanted to.

**Comment by fnuecke** [comment]
Yeah, giving a target root path sounds good to me (env var?).

**Comment by payonel** [comment]
Yes, env vars. This work is in progress, here is my current man page for install: https://git.io/voeGp
The wording, and the code, is still very wip -- I do plan to clean up the grammar. Essentially, all options passed to install will be set as env vars for the .lootprop script to choose to handle.

**Comment by fnuecke** [comment]
Sounds good.
