### ISSUE TITLE
[Suggestion] Inserting an EEPROM could make a sound

### ISSUE THREAD

**Issue by bawr** [MightyPirates/OpenComputers#1828]
Kinda like inserting a floppy does. Vaguely related to #1814 now that it's fixed.

**Comment by fnuecke** [comment]
Sure. If anyone has a good, _free_ (CC ideally) sound in mind, please do suggest it here.

**Comment by evgkul** [comment]
https://www.freesound.org/people/MrAuralization/sounds/259293/

**Comment by skyem123** [comment]
The thing is, it's not a floppy disk. :P
Maybe the sound of putting a DIP chip in a socket, or an SD card into a socket, they'd be quiet, though.

**Comment by bawr** [comment]
Right, but honesty - if it wasn't _called_ a floppy disk sound, would you be _sure_ that's what it is?

I think it's better to have something audible and characteristically tech-slot-inserty than to be accurate.

**Comment by Techokami** [comment]
That click sound actually sounds really good for the use of a [ZIF](#) socket.

**Comment by skyem123** [comment]
maybe have the heart-stopping sound of pins on an intel motherboard bending when you close the ZIF socket! >:D

**Comment by Diklabyte** [comment]
Well, my old Asrock Mainbaord has an extra security protection, such as RAM slots.
And this had an extra 'clack' sound.
I have a little 'example' for this sound. ( http://seadiver.bplaced.de/assets/tmp/eeprom_example.ogg )
This is selfmade and well, maybe not the best, but my old Asrock-BIOS-protection sounds about that :D

**Comment by Techokami** [comment]
I like the sound Diklabyte provided!
