### ISSUE TITLE
Computer keeps beeping after it's been turned off.

### ISSUE THREAD

**Issue by bawr** [MightyPirates/OpenComputers#1829]
If you do computer.beep(200, 10), it will beep for the full 10 seconds even if you turn the power off. Potentially a bad problem if you do beep(..., AbsurdlyHighNumber).

Also applies to microcontrollers.

**Comment by Vexatos** [comment]
Pretty sure that there is a duration limit on the beeps.

**Comment by fnuecke** [comment]
It's capped to 5 seconds. So not a real issue.

**Comment by bawr** [comment]
Heh, my bad, I test with an absurdly long delay. Awesome!
