### ISSUE TITLE
Server side seems to be inverted

### ISSUE THREAD

**Issue by applejag** [MightyPirates/OpenComputers#183]
In the server block you can set the side a server will see components from (i think it is), but if I choose left is sees the stuff thats at right.
[(code used)](http://pastebin.com/inn9kkrk)

First I had the setup looking like this

![alt text](http://i.imgur.com/ceKPj1e.png?1?9221)
![alt text](http://i.imgur.com/CBr5q2c.png)

And this was my result
![alt text](http://i.imgur.com/qS2zNeE.png?1)

2nd try, this is my setup (still set to right)
![alt text](http://i.imgur.com/80ctdL2.png)

And this was my new result
![alt text](http://i.imgur.com/dVcl8Dw.png?1)

**Comment by BigRenegade** [comment]
In OC the way the sides are determined is which side are they on if you are facing the same direction as the computer.  So if you face the same direction as the computer, then what might seem right to you is actually left to the computer.  this only affects the right/left.  Think of it as looking in a mirror.  :)
