### ISSUE TITLE
Turning computers off by right-click doesn't work.

### ISSUE THREAD

**Issue by bawr** [MightyPirates/OpenComputers#1830]
With an empty hand, I can turn a computer _on_if I right-click on it, but I can't turn it _off_.

Neither works with a block in hand - that I don't mind much, I guess.

**Comment by Vexatos** [comment]
That's intentional. You shouldn't be able to shut down your base by accidentally right clicking on a case.

**Comment by fnuecke** [comment]
Exactly.

**Comment by bawr** [comment]
I don't really mind, I was just posting a few things that got my attention today... but just to be sure - we are clear that to turn a computer on a _shift_ and right-click is required? I kinda skipped that. xD

**Comment by fnuecke** [comment]
Yes, computers (and robots) are totally turned on by sneaky right clicks.
