### ISSUE TITLE
The network stack disk install is broken.

### ISSUE THREAD

**Issue by bawr** [MightyPirates/OpenComputers#1831]
When I run installNetwork.lua, it puts stuff on my drive, but it's all under the /data directory.

As in, /data/bin/... is created, and /data/usr/..., etc. I needed to copy the files one level higher by hand.

**Comment by fnuecke** [comment]
Uhh, that was @magik6k's I believe? Don't know if that was by design?

**Comment by bawr** [comment]
It has stuff that needs to put in /boot, not /data/boot, if it is to work correctly.

The issue had been present on 1.6 even before the loot disk commit, but I didn't re-check OC 1.5.

I definitely remember it working correctly at one point in 1.5 on 1.7.10, though.

**Comment by payonel** [comment]
@fnuecke assign to me

**Comment by fnuecke** [comment]
Gladly :)
