### ISSUE TITLE
Expose components' capabilities

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#1837]
Allow components to provide capabilities, make them available to the outside (i.e. have cases, racks, robots, drones forward them).

**Comment by Vexatos** [comment]
Tablets too, maybe?

**Comment by fnuecke** [comment]
FTR: needs ItemStack capabilities which is not possible with the way tablet machines/components are currently handled in OC. Will look into that again at a later point, when I restructure that.

**Comment by gjgfuj** [comment]
How would you handle if multiple components expose the same capability?

**Comment by fnuecke** [comment]
First one with `hasCapability==true` wins, pretty sure that's how it's for MCMP (which in this case is quite comparable), too.

**Comment by gjgfuj** [comment]
Mcmp has sides, because they're still technically blocks. Items wouldn't
provide sides. Also, that sounds like a flaw in mcmp, unless there's a
order that makes sense.

**Comment by fnuecke** [comment]
> Items wouldn't provide sides.

Tell that to whoever decided to use the same interface for ItemStacks >_> (yes, the capabilities for items also take an EnumFacing parameter).

**Comment by gjgfuj** [comment]
I'd still suggest including a priority system for forwarding capabilities,
or not providing it at all. (Forwarding item capabilities when you have >1
item non-sided is fundamentally different to forwarding caps in a block
space.)
