### ISSUE TITLE
color packing/unpacking not stable

### ISSUE THREAD

**Issue by GopherAtl** [MightyPirates/OpenComputers#184]
the hex colors passed in are floored when converting to an 8bit representation, then floored again when expanded back. The result is that colors are not stable; starting from some hex value passed to setBackground or setForeground, gpu.get will return the actual value this generated when packed and unpacked. That much is expected.

However, you would reasonably expect /that/ hex value, passed back to setBackground, to produce the same color, and it does not.

You can demonstrate this with the following loop...

```
local c=0xb4b4b4 --this gives a light bluish-gray
local gpu=require("component").gpu
for i=1,10 do
  gpu.setBackground(c)
  gpu.set(1,1," ")
  _,_,c=gpu.get(1,1)
  gpu.setBackground(0)
  print(string:format("c=0x%06x",c))
end
```

which will go from 0xb4b4b4 at the start through0x9191aa, 0x6d6daa, 0x4747aa, and 0x2424aa before stabilizing at 0x0000aa.

It will be stable for all 256 possible 8-bit packed values if you change the logic to rounding rather than flooring. I don't know scala, but I accidentally reproduced the exact same instability listed above in my own conversion functions, and this change made the system stable and consistent across all inputs. 

Looking at https://github.com/MightyPirates/OpenComputers/blob/master/src/main/scala/li/cil/oc/util/PackedColor.scala, the toInt seems to do the conversion from float to int and floor in the process, so adding +.5 first ought to fix the issue, changing the inflate and deflate functions to:

```
def inflate(value: Int) = {
  val r = ((((value & rMask) >>> rShift) * rScale + .5).toInt << rShift32) & rMask32
  val g = ((((value & gMask) >>> gShift) * gScale + .5).toInt << gShift32) & gMask32
  val b = ((((value & bMask) >>> bShift) * bScale + .5).toInt << bShift32) & bMask32
  r | g | b
}

def deflate(value: Int) = {
  val r = ((((value & rMask32) >>> rShift32) / rScale + .5).toInt << rShift) & rMask
  val g = ((((value & gMask32) >>> gShift32) / gScale + .5).toInt << gShift) & gMask
  val b = ((((value & bMask32) >>> bShift32) / bScale + .5).toInt << bShift) & bMask
  r | g | b
}
```

Of course, this may be moot if a significant overhaul of the color and render systems as hinted at in issue #177

**Comment by fnuecke** [comment]
Thanks for this! Since it's a simple fix and I don't know for sure when I'll find the time for the overhaul in it goes :-)
