### ISSUE TITLE
[ForgeMultiPart] Some sizes can't be removed by robot

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#1840]
ForgeMicroBlock (FMB) blocks (From FrogeMultiPart) of 1/8 (corner) or 1/16th (nook) can not be removed by a robot with `robot.swing()` with an empty tool or any tool that should harvest the block. 

Having a slab (1/2, side) or panel (1/4, side) in the block will allow for any other smaller FMB pieces to be harvested in the same action as expected. 

I haven't tried covers (1/8, side) but I'd guess they preform the same as corners in that they can't be removed.

```
=robot.swing()
false "air"
```

MC 1.7.10
OpenComputers-MC1.7.10-1.5.22.42-universal
ForgeMultipart-1.7.10-1.2.0.345-universal
Forge 1566

**Comment by fnuecke** [comment]
Hrm, I suppose when all sides fail it could call back to a getBlock for the block in the general facing, yeah. Will look into.
