### ISSUE TITLE
[Request]: Drones upgrade that allows item use

### ISSUE THREAD

**Issue by Stalkstalks** [MightyPirates/OpenComputers#1841]
Drones are interesting, but a bit disappointing. It feels that while microcontrollers are able to handle a pretty wide range of simple computer functions, drones are kind of limited to moving items around, bucketing liquids, and picking up critters with the leash upgrade. They're so mobile and conceptually cool, I'd really like to be able to use them for more things, under sort of a "central servers command and control while drones execute" paradigm.

To that end, can we get an upgrade for drones that allows them to use items, in the standard left and right click sort of way? I understand that you don't want them stepping on the toes of robots too much, so perhaps having a "tool" slot could be mutually exclusive with having a general inventory - a drone with an item equipped would be a dedicated platform for moving around and applying their item, unable to collect drops and needing to return to base if their item needs to be swapped out. (I'd almost say that the item should be permanently affixed as part of the drone, but that would make it impossible to recharge/refuel most of the items in a modded environment, and drones are a bit too expensive to be single-use consumables. Though if you really want to lock them into whatever they're given, it could require the disassembler to swap the item out - though doing so shouldn't destroy whatever they were using, and I don't know how to deal with experience upgrades under that path.)

**Comment by xarses** [comment]
> bucketing liquids

As far as I've been able to work they can't use most things, like buckets (they also turn off when they hit a fluid)

I'd be happy to start with being able to use any right click item, even things like using a lever result in its state going back (probably a bug).

From there, we probably should have an tool slot upgrade., we could work around the makes robots useless, by removing the ability for the drone to equip it's own tool slot, instead making it an inventory slot that something else has to put something there. Alternatively it could be expensive enough that you probably can't/won't have an inventory upgrade and/or inventory controller so the point might just be moot.

**Comment by fnuecke** [comment]
Well, they can also place blocks and break hand-breakable ones ;) I feel allowing them to use all items like robots can might be a bit... too much. _If_ this ever makes it, it'd probably have to be a more or less "exclusive" upgrade,  in which case use of drones would become pretty similar to that of BC robots, I suppose (with specialized roles). It's probably not something I'll look into super-soon, but I'll not say "never" for now ;)

> even things like using a lever result in its state going back (probably a bug).

Can't reproduce that (tested 1.7 and 1.9), are you sure it's not a bug in your script?

**Comment by Vexatos** [comment]
Maybe something like assembling an upgrade containing a tool into the drone so it has to be disassembled to be changed? Not sure, I think drones should not be able to use tools.

**Comment by xarses** [comment]
@Vexatos why though? if we have no ability for the drone to equip it's own slot isn't this net the same effect?

**Comment by gjgfuj** [comment]
Well no, drones could say use a wrench or something. Or some other kind of
tool.

**Comment by S0ZDATEL** [comment]
In this case, a lasso upgrade would be useless, because the drone will be able to take and use the normal lasso.

**Comment by payonel** [comment]
no movement on this thus i think we'll keep drones limited as they are
