### ISSUE TITLE
[BUG] 3D printed blocks and opencomputers coponment

### ISSUE THREAD

**Issue by Shiranuit** [MightyPirates/OpenComputers#1844]
Some printed blocks lose their data and become invisible and non physic for players, i can pass through, i can't drop an item through, because a physical force push him
when i check if there is a block the value returned is true.

Some computer case lose their components sometimes

ALL of this bugs were produced in a FTBUtilities Chunk and appear when the Chunk is load by the mod and when the Chunk is not load by the mod

**Comment by fnuecke** [comment]
Versions? Anything in the logs? Exact steps to reproduce?

**Comment by Shiranuit** [comment]
OpenComputer version :  1.5.22.6
FTBUtilities version : 2.0.2
Minecraft version : 1.8.9

There is no logs about it

To reproduce it, place a opencomputer or a printedblock in a FTBUtilities chunk and unload the chunk and load the chunk, with a little luck the block has lost her NBTTags, This bug doesn't appear all the time but sometimes appear

When I have some logs for this bug I'll post here

**Comment by fnuecke** [comment]
Could you please test if this still happens with the latest 1.6 build? (beta 2 or http://ci.cil.li/)
Thanks.

**Comment by Shiranuit** [comment]
Ok, this bugs still happens in OC 1.6.0.8, and it appear more frequently than the OC 1.5.22.6 but there is no logs about it, the only thing i can see is the block datatags lose his "label", "stateOn" and "stateOff"
