### ISSUE TITLE
Feature Request/Suggestion - ANSI color code support

### ISSUE THREAD

**Issue by brisingraerowing** [MightyPirates/OpenComputers#1847]
How about adding support for ANSI color sequences in the term library?

**Comment by payonel** [comment]
Stuff like this: https://linuxtidbits.wordpress.com/2008/08/11/output-color-on-bash-scripts/ ?
I thought we already had a feature requested issue for this, but a short search did not find it. I'm fine with @fnuecke marking this feature-requested. Not sure when I'll add it, but I support this type of feature.

Or are you just asking a method/param to term.write to write chars in a specific color? If so, I'd have to give that some more thought.

**Comment by fnuecke** [comment]
Yeah, I think we talked about this some time ago, and the consensus was "possibly some day, if it doesn't bog down draw speeds too much".

**Comment by skyem123** [comment]
I think that @magik6k uses ANSI codes for their Plan9k terminal emulator.

**Comment by brisingraerowing** [comment]
@payonel Pretty much.

@fnuecke I am not sure how this would affect draw speeds. If push comes to shove, I could probably write a simple term wrapper that handles these codes.

**Comment by fnuecke** [comment]
Switching background/foreground colors it, like most GPU operations, limited to a certain number per tick. For few color switches I imagine it wouldn't be too bad, but for excessive mixed colored text this would certainly be noticeably slower than for plain text.

**Comment by magik6k** [comment]
Yup, plan9k implements this indeed, and it doesn't need to invoke gpu at all from most of it's programs. Renderer code -> http://hastebin.com/mecuxuquyi.lua
