### ISSUE TITLE
[SOLVED] While using computer, surrounding blocks start to glitch out.

### ISSUE THREAD

**Issue by iancbogue** [MightyPirates/OpenComputers#1848]
Hello. While I was using my new computer, I came into a problem. Every now and then, I'd have the computer screen GUI up, and surrounding blocks would glitch out. I deleted my computer, but the problem persists when I go to place any other blocks. Doesn't crash as far as I know. Will try to get screenshots. Thanks!

EDIT: Also, I should note, I put the lights in after (they're from electrical age). I have these mods installed:
- Cars & Drives Mod
- CodeChickenCore
- Connected Glass
- Custom NPCs
- Damage Indicators
- Decocraft 2
- Decorative Marble
- Electrical Age
- Immibis Core
- Immibis' Microblocks
- Lattice Mod
- Looking Glass (for SecurityCraft)
- Malisis Core
- Malisis Doors
- Master Chef Mod
- Monoblocks
- Mr. Crayfish's Furniture Mod
- NotEnoughItems
- NEI Addons
- NEI Integration
- OpenBlocks
- OpenMods
- **Open Computers (of course!)**
- Optifine
- Richard's Coffee & Tea Mod
- RoadWorks
- SecurityCraft

![2016-06-04_19 31 54](https://cloud.githubusercontent.com/assets/18062067/15803290/05b45c10-2a8b-11e6-8acd-a0e421751139.png)
![2016-06-04_19 33 11](https://cloud.githubusercontent.com/assets/18062067/15803317/bccba97a-2a8c-11e6-9005-f72a2587aefc.png)
![2016-06-04_19 33 15](https://cloud.githubusercontent.com/assets/18062067/15803320/bcd827ea-2a8c-11e6-9c5c-6133003a60ff.png)
![2016-06-04_19 36 51](https://cloud.githubusercontent.com/assets/18062067/15803318/bccc35ca-2a8c-11e6-81e1-094d0cbb6f69.png)
![2016-06-04_19 36 56](https://cloud.githubusercontent.com/assets/18062067/15803319/bcd16180-2a8c-11e6-9de6-845c7d14fb2c.png)
![2016-06-04_19 37 07](https://cloud.githubusercontent.com/assets/18062067/15803321/bcdd17e6-2a8c-11e6-935c-f65e5bbff388.png)
![2016-06-04_19 37 12](https://cloud.githubusercontent.com/assets/18062067/15803322/bcdd31f4-2a8c-11e6-9d24-aec129986da0.png)

**Comment by fnuecke** [comment]
Versions? Also, which blocks are the ones turning invisible? The screen blocks? Some other mods' blocks? All blocks in a fixed radius of... what?

**Comment by iancbogue** [comment]
The whole building is 64x64x64 and made out of stone. At the beginning, I guess it was one chunk. I don't really know. Once it happened, whenever I went to place a block _anywhere_  it would do this. The only way to get rid of it is to do F3+A. I also updated with all the mods I use. Could it be OptiFine?

Sorry, forgot versions. Here is the OpenCOmputers version: 1.5.22.46

**Comment by xarses** [comment]
Pretty much any texture issue should go straight to OptFine if you're using it.

I've seen similar glitches with Chisel blocks + OptFine, you likely need to change some of the settings as your gfx card doesn't like something it's trying to do.

I'm using OptiFine_1.7.10_HD_U_D3

settings of note

> ofOcclusionFancy
> ofFastMath
> ofFastRender
> ofLazyChunkLoading
> ofChunkUpdatesDynamic

in that these are the most likely to cause issues with other mods visually. 

My Settings for lower end GPU https://gist.github.com/xarses/951c58d82a754857ed940c36726a5df6

**Comment by iancbogue** [comment]
Thanks. I had used OptiFine once before. It would keep flickering out. Before you commented, I actually deleted optifine and it worked!

**Comment by dgelessus** [comment]
FWIW, I had flickering issues (with random parts of the world, not directly related to any mod) when I had multi-core chunk loading enabled in the Optifine settings. You could try switching that to single-core and see if that helps.

**Comment by iancbogue** [comment]
Thanks, dgelessus, it appears that that solved the problem.
