### ISSUE TITLE
Errors running the class trasnformer

### ISSUE THREAD

**Issue by pikkon38** [MightyPirates/OpenComputers#1853]
Got an error in my chat on world load saying there were errors running the class transformer, and to report it with full log. I had to zip it up as github was saying it doesnt support .log files. So here ya go!

[fml-client-latest.zip](https://github.com/MightyPirates/OpenComputers/files/301538/fml-client-latest.zip)

**Comment by fnuecke** [comment]
Thanks for reporting! Duplicate of #1849.
