### ISSUE TITLE
Gradle takes a really long time because of all the dependencies and repositories.

### ISSUE THREAD

**Issue by skyem123** [MightyPirates/OpenComputers#1858]
Due to the nature of Gradle, it takes way too long to download all the dependencies, and it wants to check every single repository for every single dependency.

I think it's possible to speed this up by having your own mirror of all the dependencies on a Maven repositories, which somehow (sorry, I'm unsure about how to set it up) becomes the first thing that Gradle uses to download, which should speed things up.

Even with a mirror, I think you can keep the main repos in the Gradle script, just in case your mirror goes down.

Sorry for being a bit vague, if you want, I can contact someone who has more experience in this.

**Comment by fnuecke** [comment]
I already am mirroring most (all?) of the deps on my maven, and thought it'd check that first anyway due to it being first in the list. The others I just left in as fallbacks... pretty much what you suggest :P

If that's actually the cause of 1.7 builds being so abysmally slow, guess we'll just throw those out (mind testing that?).

**Comment by SaphireLattice** [comment]
Can confirm that trying latest matter 1.7.10 is impossibly allow. I just
ctrl+c the progress after few hours.

**Comment by skyem123** [comment]
@fnuecke: the problem is that I haven't got the time, it's still trying to make the idea stuff!

**Comment by SaphireLattice** [comment]
Hotfix: *master *slow. Sorry, writing from phone.

**Comment by fnuecke** [comment]
OK, I'll test it myself when I'm home and have the time then.

**Comment by skyem123** [comment]
I'm testing it without any repos besides yours, it's faster, though I'm worried about it not completing properly.

**Comment by skyem123** [comment]
@fnuecke: I have done some testing, and I have discovered that you are not mirroring some repos.

**Comment by fnuecke** [comment]
Do you have a list of which ones?

**Comment by skyem123** [comment]
If I recall correctly, it's the NotEnoughKeys, CodeChicken, and Thaumic Energistics

**Comment by payonel** [comment]
after 1.7.10 the dependencies are reduced. We don't to fix 1.7.10 for this
