### ISSUE TITLE
Capsule Mod intercompatibility

### ISSUE THREAD

**Issue by Lythom** [MightyPirates/OpenComputers#1859]
Hello !

I'm the author of Capsule Mod (http://minecraft.curseforge.com/projects/capsule) wich allow players to move blocks and tile entities from the world into a capsule, then eventually from the capsule to the world elsewhere.

I got a crash report from a player trying to move an OpenComputers robot : http://pastebin.com/pbqkFTdN.

On the capsule side, it crashes at the nbt data copy (from old pos to new pos). The code used is :

`NBTTagCompound nbt = new NBTTagCompound();
srcTE.setPos(destPos);
srcTE.setWorldObj(destWorld);
srcTE.writeToNBT(nbt);
destTE.readFromNBT(nbt); // it crashes here at line 201`

complete source (if needed) : https://bitbucket.org/Lythom/mccapsule/src/971488e9019f4106ee983b2ebd8a8467c34c2933/src/main/java/capsule/Helpers.java?at=master&fileviewer=file-view-default#Helpers.java-191

I don't know how readFromNBT works for the robot so I can't really debug this part of the code. Can you inspect to see if there is a way to prevent the NullPointerException
- either on OC side and still have the nbt data read correctly
- either something I can do on the capsule side (without having to include an explicit dependency to OpenComputer) so that the readFromNBT works without error.

Thank you for your feedback =)

(Link to original player report : https://bitbucket.org/Lythom/mccapsule/issues/4/crash-with-opencomputers-robot-server)

**Comment by Vexatos** [comment]
Oh, that's ugly.... Oh... Evil things are happening... Pretty sure noone should ever be doing such a thing...

Hm... Apparently the network is null.

**Comment by fnuecke** [comment]
Hrm, while the robot save/load code _is_ a little special indeed (as are cases or anything hosting a machine, really, because the actual machine state is stored in an extra file, not the NBT), it should still work as expected; at least it worked with AE2 spatial storage :P 

Could you give me a quick rundown of how the capturing works? Do you create a fake world, or why is there a `sourceWorld` and a `destWorld` parameter?

**Comment by Lythom** [comment]
Yes, I currently use a dimension to store the contents so the blocks are transfered from overworld to capsule dimension then back.

How it currently works :
1. All IBlockState (not nbt) are copied in memory for the region.
2. All IBlockState are transfered one by one
   1. Transfer the IBlockState only, from memory, using some low level functions from minecraft Chunk to "raw write" a state (to prevent BlockBreak hooks and so on)
   2. Check if the block arrived in the same state (ie. can be false if redstone is placed on a not copied yet block)
   3. If same state, source and destination tileEntity's are available -> copy the nbt from source world TileEntity to dest world TileEntity then destroy the source block (remove entity + setBlockState to air).
   4. if different state, pass the block and retry later (ie. block placed at first iteration, redstone get correct state at 2nd iteration)

In this crash case :
- The blockState get copied properly in the first iteration.
- The TileEntitys are existing for both source and destination blocks after the IBlockState copy in the 1st iteration.
- The crash occurs when copying nbt data from source TileEntity to dest TileEntity during the write process.
- Might be relevant (or not) : just after each IBlockState is "raw chunk copied" (step 2.I.), world.notifyBlockUpdate and world.updateBlockTick are called once on the block in order to preserve the redstone state. Wich cause the block to tick once before getting the source NBTData.

**Comment by Lythom** [comment]
Hi !

I've been invastigating further while devlopping the 1.10.2 version of capsule. I changed the transfer mechanics to something more "standard" : structure blocks saves and load.

Using version MC1.10-1.6.0.2-beta.4 on forge 12.18.1.2045, I tried to save a robot using a structure block (no error), but on load elsewhere there is an error logged by the structure block. The robot does appear in the world but I believe it might be corrupted since the load ended early because of the thrown exception.

here is the stacktrace : http://pastebin.com/33DZz6M2

As for the Capsule mod I won't be invastigating further. Deploying a robot, as with a structure block, will fail and log a technical error. As soon as a robot will be able to be copied / moved using structure blocks, they will get compatible the capsules since the capture/deploy mechanics match exactly the save/load mechanics of the structure block.

Since I studied them a bit, feel free to ask questions about the structure blocks mechanics if you need.
