### ISSUE TITLE
Raw drive (aka EEPROM)

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#186]
It would be cool to have a raw EEPROM drive which you can read/write at random addresses (using drive:seek("<cur/set/end>",x) or something)
Seeking changes the sector index (or returns it if you do seek("cur",0)), reading returns a 512 bytes long string which's the whole sector, writing takes a 512 bytes long string and writes it to the sector.

While I do understand ppl like to be able to copy their code around, this is an advanced, end-game thing which probably won't be used by your basic user unless they use a program which requires it.

**Comment by BigRenegade** [comment]
I believe the developer of the mod told you on irc earlier today to use Computronics if you wanted something like this.

**Comment by SoniEx2** [comment]
So I guess I'll have to go back to bugging @asiekierka to implement something that works like this... (no tapes don't work the way I want/need them to)

(actually I'm just using this as an excuse to ping them)

**Comment by fnuecke** [comment]
How do they not work the way you want? The way you describe it tapes can absolutely be used to emulate this, just wrap the seek, write and read methods to jump to multiples of 512 and read/write 512 bytes at a time. Either way, this is a little too... special case to make it very high on the priority list, so even if this were to be added it wouldn't be any time soon. Adding this to an addon mod would indeed be the more reasonable solution I guess (note that item components can specify their slot type as 'disk' so they can be inserted into the same slots the built-in hard disks are).

**Comment by pingbird** [comment]
he said it was because they diddnt support strings, but you can easialy do that:
string.char(unpack(tape.read(num)))
tape.write({string.byte(str,1,#str)})

**Comment by GopherAtl** [comment]
so he wants low-level disk access, but tapes are _too_ low-level for him? Bit of a Goldilocks request, isn't it?

**Comment by SoniEx2** [comment]
@Gopher42 tapes aren't sector based

**Comment by fnuecke** [comment]
Well, then make them :-/ As I said, just read/write/seek in multiples of 512.
I honestly don't see the benefit in this over tapes, sorry.
