### ISSUE TITLE
"Errors Running the Class Transformer" in 1.9.4

### ISSUE THREAD

**Issue by Aliervo** [MightyPirates/OpenComputers#1860]
This lovely error is showing itself again... I tried looking through the logs myself, but I am completely clueless.  I thought it might be either TechReborn or IC2, but I still got the errors after removing them so I put them back in... [Here is the log!](https://gist.github.com/Aliervo/c9488af6792cff02784a548f420fd608)

[Mod List](https://gist.github.com/Aliervo/5f0f16ac14a875d51fe7fd5c1c117f18)

Not sure if this is caused by the same thing as #1765 or #1509 since I am running the 1.9.4 version

Hope this info helps!

**Comment by AlphaKintari** [comment]
Also Running 1.9.4.  Do not have TechReborn installed. only IC2. Disabiling IC2 does not resolve the issue.  Attached is the log. 
[2016-06-09-3.log.gz](https://github.com/MightyPirates/OpenComputers/files/306767/2016-06-09-3.log.gz)

**Comment by fnuecke** [comment]
99% sure it's the same things as #1849, please grab the latest dev build [from Jenkins](http://ci.cil.li/job/OpenComputers-dev-MC1.9.4/) that should fix it for you. If it doesn't, let me know, thanks!

**Comment by AlphaKintari** [comment]
yep. This seems to have resolved the error. Thanks.
