### ISSUE TITLE
Odd error with custom module

### ISSUE THREAD

**Issue by jackmaco** [MightyPirates/OpenComputers#1862]
Hey there I amde my own moduel to help me with some robot stuff and keep getting an odd error,

My main code is here:

local robot = require("robot")
local rtools = require("rtools")

local posx = -281
local posy = 70
local posz = 344
local posd = "east"

robot.forward()
posd = rtools.face("north")
robot.forward()
robot.back()
posd = rtools.face("east")
robot.back()

And my module is here (rtools.lua):

local component = require("component")

local rtools = {}

function rtools.test ()
  io.write("YO")
end

function rtools.face (cpos,tpos)
  if cpos == tpos then
    return tpos
  elseif cpos == "east" then
    if tpos == "south" then
      component.robot.turnRight()
    elseif tpos == "west" then
      component.robot.turnAround()
    else
      component.robot.turnLeft()
    end
  elseif cpos == "south" then
    if tpos == "west" then
      component.robot.turnRight()
    elseif tpos == "north" then
      component.robot.turnAround()
    else
      component.robot.turnLeft()
    end
  elseif cpos == "west" then
    if tpos == "north" then
      component.robot.turnRight()
    elseif tpos == "east" then
      component.robot.turnAround()
    else
      component.robot.turnLeft()
    end
  else
    if tpos == "east" then
      component.robot.turnRight()
    elseif tpos == "south" then
      component.robot.turnAround()
    else
      component.robot.turnLeft()
    end
  end
  return tpos
end

return hacks

The error returned when I use it is:

attempt to index local 'rtools' (a boolean value)
terminated

I can't see why.

**Comment by jackmaco** [comment]
Small update on the master script:

local robot = require("robot")
local rtools = require("rtools")

local posx = -281
local posy = 70
local posz = 344
local posd = "east"

robot.forward()
posd = rtools.face(posd,"north")
robot.forward()
robot.back()
posd = rtools.face(posd,"east")
robot.back()

**Comment by jackmaco** [comment]
Fixed by rebooting robot

**Comment by xarses** [comment]
When you use a 'require', its cached on the computer in `package.loaded.<module>`

if you want to completely reload the module (because you changed it) you need to unset it `package.loaded.rtools=nil`

**Comment by payonel** [comment]
xarses is right
But may I add, if you have a library-like script that SHOULDN'T be cached, I recommend `dofile` as opposed to `require`. `dofile` does not use the library path, it requires a relative/absolute path, but it won't cache the file in package.loaded.
