### ISSUE TITLE
have a .detect() for left and right (for robots)

### ISSUE THREAD

**Issue by jackmaco** [MightyPirates/OpenComputers#1863]
As subject

**Comment by Inari-Whitebear** [comment]
I still disagree. Meanwhile you can emit redstone on the side and check the input level, only works for solid bocks though :3

**Comment by jackmaco** [comment]
I am writing a robot to fill a large floor area with non straight edges, every block check I ahve to turn left turn right and detect separately, its an inanely long process and totally silly when there is a detect up and down, there should be a detect left and right or alternatively there should be no detectup/detectdown either.

**Comment by Inari-Whitebear** [comment]
Theres the camera for example if you have computronics. Among other options, such as the redstone method I mentioned.
detect up/down is a thing because robots cannot turn that way

**Comment by jackmaco** [comment]
Perhaps I do see the point, but that is to be saying, there is an up and down method because robots cannot rotate on the Y Axis, but the logic would follow if they can detect objects on the y axis they should be able to detect on the X or Z axis too (from a robotics perspective)

**Comment by Inari-Whitebear** [comment]
From a robotics perspective they could only have a sensor on top/bottom and front xD Especially as the sides may be reserved for Tool Holding rather than sensors

**Comment by Inari-Whitebear** [comment]
Ideally, I'd like if we had customized robots, then you could have the sensors you'd need. But sadly we don't ^^

**Comment by Vexatos** [comment]
It might be possible to use a Geolyzer to detect blocks on the sides.

**Comment by fnuecke** [comment]
Yeah, the geolyzer is currently the recommended tool for this. I suppose it might be an option to add a "detect" method to the geolyzer tho, that - unlike analyze - doesn't consume energy, but only returns the limited info robots' detect does (i.e. block/air/...).

**Comment by jackmaco** [comment]
the thing really making this a challange is im limiting to tier1 case robots :)

**Comment by Vexatos** [comment]
Aren't geolyzers tier 1 upgrades?

**Comment by fnuecke** [comment]
They are, so that should still be feasible I think :)

**Comment by payonel** [comment]
"open-for-adoption" to extend geolyzer to detect presence of blocks
