### ISSUE TITLE
[1.6.0.x] Unable to place cables on multiplayer server

### ISSUE THREAD

**Issue by SamTellings** [MightyPirates/OpenComputers#1864]
When playing singleplayer I am able to place down cables just fine. But when I join on a server I am unable to place down cables. Right clicking just does nothing.

All other cables work fine (IC2, BC). I have tried in creative and survival, OP'ed, etc.. Verified friend could also not put down cables.

This is only in 1.6 though, 1.5 cables work as expected (but had no IC2 support, so we had to switch to 1.6).

**Comment by fnuecke** [comment]
Which Minecraft version?

**Comment by SamTellings** [comment]
Woops, knew I forgot something!
MC 1.8.9 OC version 1.6.0.5

**Comment by fnuecke** [comment]
Hmm, works fine for me. Mind seeing if it works for you with just OC? If yes, please try throwing in half your mods, then the other half, and keep narrowing it down that way to what mod in combination with this happens, that'd be a big help, thanks!

**Comment by SamTellings** [comment]
The problematic mod seems to be "MCMultiPart-1.0.9-universal". As soon as I add that in, cables stop working. Again they DO work with this in SP and 1.5 also worked with it.

Thanks for helping and I hope this was of use to you!

**Comment by fnuecke** [comment]
Oh, right, MCMP was on 1.8 too, not just 1.9 :X Completely forgot about that.
Yeah, that does change placement logic. Thanks, will look into it!

**Comment by SamTellings** [comment]
You're doing gods work fnuecke! Love the mod so far, and its a good excuse to learn Lua :P
