### ISSUE TITLE
"Driver" disks are not intuitive at all right now

### ISSUE THREAD

**Issue by skyem123** [MightyPirates/OpenComputers#1866]
So... I've had to walk someone though installing a "driver", and it was not fun.
So I have a list of things that, if solved, would make it a lot more intuitive.
1. How does one get these disks. I know it's possible to do by cycling loot disks, but that means that they're impossible to get if that setting is disabled. Maybe craft a disk with a component, with the component staying in the crafting grid?
2. There are probably too many disks. :P OC should just have one driver disk, as that'd make driver installation a lot easier.
3. This also means that there needs to be some way for driver disks to detect what hardware there is and refusing to install (unless forced) if it isn't present.
4. Also, there should be an easy way of installing drivers. Suggestion for @payonel: there should be a utility that scans for loot / driver disks and prompts the user to install them.

Sorry if this sounds a bit rude, I'm tired and I thought that I should write this down before I forget it.

**Comment by payonel** [comment]
the work on installer is nearly done, but it takes more than just a couple nights. Sorry for the delay. But the new install tool will HELP. Let's discuss these pain points individually, and I'll speak to what is already solved with the upcoming install
1. Sangar has added an api that I can call from OpenOS to help find what disk is need. When someone tries to run **xyz**, and the file is not found on their system, I can check a lookup table and report what disk they need to craft. I haven't resolved everything you're saying in your item 1, but this is part of the same problem I feel. [OpenOS support of this feature will not be available in the openos-1.6.-rc, but an update following it]
2. I have nothing in the works to resolve this, but we talked in irc about having a driver folder in the openos loot disk that would NOT install by default. We could check what components are already in the system during the main os install, and include needed drivers (this would be easy). We could also rescan the system every time install is run with the openos disk (also easy, but doing this may not be as intuitive to users).
3. This is definitely doable. The next update to openos will introduce support for "driver disks" to provide custom .install scripts. The .install script can be hand tailored to achieve this purpose. Though I'm not sure it is necessary. But it doesn't matter to me what component driver devs do with their own .install (note .install is OPTIONAL, there is definitely default behavior that /bin/install can perform that is absolutely valid)
4. That is exactly the work in progress. I think you'll like it. I have something in the works locally that is already better, but here is the current PR of the next install (again, this is now outdated, a better upgrade even is soon to come [probably this weekend]): https://git.io/voZWU

**Comment by skyem123** [comment]
Yay for the installer!

**Comment by fnuecke** [comment]
1. Crafting them with the components has been suggested by asie a while back and is something I want to do, just haven't gotten around to yet!
2. Eh, if the above gets added I'm not sure if it'll be so bad. If complaints keep coming even with the new install and crafting, we'll see. For... rarely used stuff, I don't think it'll be much of an issue. For the internet related programs / lib, I'm still on the fence of just throwing it into OpenOS itself, tbh.
3. I... don't think that's a good idea. Why not allow preinstalling drivers? Would allow building a kitchen-sink OS on a simple computer for example.
4. What payonel said, that's why [that new IMC was added](https://github.com/MightyPirates/OpenComputers/commit/cf43ca1d8671ad22067c066bbab2b5be6a730e07#diff-46d2669192fd43fb9066b1311392a66bR401) :)

**Comment by skyem123** [comment]
@fnuecke, well, it would warn users that the programs / drivers installed may not work with out the component, but they can force installation.

**Comment by payonel** [comment]
@fnuecke assign to me?
this is either fixed or won't fix in 1.6 beta 3 methinks (though, there are still a few bug fixes in latest PR)

**Comment by fnuecke** [comment]
So for recap, left to do here is
1. @payonel adding the program -> disk suggestion logic to OpenOS.
2. me adding component + disk -> disk crafting logic.

**Comment by skyem123** [comment]
@fnuecke, it's worth noting that the documentation should probably be updated as well. :stuck_out_tongue:

Though, once those are in, it should be easier to use than currently.

**Comment by payonel** [comment]
I suggest this ticket be solely for @fnuecke adding "component + disk -> disk crafting logic"
We have the "missing program disk suggestion" in #1882

**Comment by payonel** [comment]
closed with #2109
