### ISSUE TITLE
[1.9.4 - Crash]: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/typesafe/config/ConfigMergeable

### ISSUE THREAD

**Issue by Lanse505** [MightyPirates/OpenComputers#1867]
OC: 1.9.4-1.6.0.1-Beta.2
Forge: 12.17.0.1954

Crashlog:
https://gist.github.com/Lanse505/23441fb9acee21f84317b5a88598fb26

**Comment by Lanse505** [comment]
I can provide a full mod list incase the base information is not enough and provide future help through mod testing (aka process of elimination).

**Comment by fnuecke** [comment]
Your Forge installation is missing at least one library. Reinstall Forge / the modpack, or copy the missing libraries from a working installation.

(Continuing the reference trail, also see #1850.)
