### ISSUE TITLE
[OC 2.0] Robots using GUI

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1869]
So this might be a consideration for 2.0: Have robots be able to use the UI of Machines (open[side]/close[side]/click[x,y], etc). I'm not sure how exactly this would be implemented, and it may be bit hacky :p

One idea is to start a fake client on the server that can handle the UI stuff, similar to fake players but more advanced, the downside obviously is that it would use a lot more resources on the server machine.

Not sure if there are any other good ways unless Forge gets modified or OC does some asm injection stuff, to be able to use UIs on the server?

**Comment by Vexatos** [comment]
`net.minecraft.client` does not exist on servers. It is virtually impossible to do this.

**Comment by Inari-Whitebear** [comment]
Virtually, so not actually :D

**Comment by fnuecke** [comment]
It's practically impossible, too. There'd have to be a version specific custom handler for every single GUI, at which point it makes more sense just to have a normal component API, the way it is now ;)

I'll leave it open for a bit in case someone has a good idea how to do it anyway, but I'm highly doubtful it'd be possible (in a way that's not too unstable and hacky :P)

**Comment by payonel** [comment]
i've decided we'll not add this, thanks for the suggestion
