### ISSUE TITLE
Feature Request: Printer peripheral

### ISSUE THREAD

**Issue by Techokami** [MightyPirates/OpenComputers#187]
Quite simply, it is a block that turns blank paper into printed documents using an ink source (dyes), similar to the printers in ComputerCraft. I'm honestly surprised this isn't present, as it seems kind of simple and straightforward.
Though, to differentiate, how about also having an Advanced Printer that requires multiple dyes, but prints color images to maps? Might be trickier, but rewarding in allowing people to use a drawing app on a Tier 3 computer to make a picture, then print it out and hang it on their wall with an item frame.

**Comment by fnuecke** [comment]
Have a look at the [OpenPrinter](https://github.com/PC-Logix/OpenPrinter) project.

**Comment by Techokami** [comment]
Huh, didn't even know this existed. Never saw anything for it on the forums... Thank you!
