### ISSUE TITLE
Allow fetching multiple signals

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1870]
I'd like some way to fetch multiple signals with a single yielding. Maybe somehow specifying how many signals should be pulled? (Since passing a single number already means  "sleep x ticks" maybe as a {n=2}) or something of the sort...

Could even see about implementing it, but wanted to ask first haha :) Would mostly be useful to get all new events quickly after being force-yielded for a while from draw calls or the like I guess, but also to just get new events quickly if a lot occur.

Or maybe just a function that ends up scalaside and passes back a table with signals?

**Comment by Vexatos** [comment]
`event.pullMultiple`?

**Comment by Inari-Whitebear** [comment]
That doesn't even pull multiple signals, it just lets you specify multiple things to look for I think?

**Comment by Inari-Whitebear** [comment]
Since I've been asked this on IRC too: pullMultiple seems to just mean "hand me an event that is 'key_down', 'key_up' or 'touch'". In contrast to pullEvent where you can only specify a single event to get back.

What I mean is, I want all events that are still in the queue, not getting them one-by-one by yielding.

**Comment by gjgfuj** [comment]
If you wish to pull multiple, you could probably code that lua side in your
program. Just call event.pull multiple times. :P

**Comment by Inari-Whitebear** [comment]
@gjgfuj Which yields multiple times. Or: not what I want

**Comment by gjgfuj** [comment]
Well considering the way signals are implemented internally.... have fun
with that.

**Comment by Inari-Whitebear** [comment]
Hence why heres a request/suggestion to make that possible :P

**Comment by payonel** [comment]
Not sure why you get the attitude; it's a fair suggestion. I have a few solutions but the tradeoffs are simple API for the machine with pretty complex change to the internals, or a simple change to the internals with a fairly unsafe potential scenario for the machine. Anyways, I just wish to confer with Sangar about this as I think this can be done, just want to know which way he'd prefer.

**Comment by fnuecke** [comment]
Actually doing this in one go (i.e. not just pulling multiple times, which you could just do yourself already) would need some changes very deep in the machine code, which I'm somewhat... reluctant to do, in fear of breaking things :P If someone wants to poke at it and heavily test it afterwards, be my guest, I won't ;)

**Comment by payonel** [comment]
@Inari-Whitebear after some review of the code and how this would affect your performance inside the vm...and some testing of changes to this workflow in emulation, I've concluded this type of change actually would have nearly no improvement. The cost of yielding when there are still signals in queue is negligible. Yes there is a cost, but it is very small. When you yield on an empty signal queue, yes, you see at least a tick lost. But this change would at best save the time to marshal from the C interface of the Lua state and the jvm, which is small.

So yes, performance would improve, but it would be tiny at the cost of considerable rework in the java side to support signal filtering outside the vm. In addition, this change would be incompatible with any event.listeners with custom filtering.
