### ISSUE TITLE
EEPROM ram (and maybe cpu cache?)

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1871]
Would be interesting if you could run a PC without any RAM installed, and it uses the data part of the EEPROM as ram instead. (probably in the process disabling manual read/write of that)

Though maybe this would need to be part of a bigger change then, where the CPU has a cache and all, but that sounds a bit overkill :f

Actually I like the concept though... have a cpu component:
`getCacheAmounts()` - returns amount of cache variables available in this cpu as table of {datatype=cacheAmount}, so.. {number=3, string=1} or the like, everythign unspecified is 0
`setCache(index, value)` - set cache to (type-checking and errors when you try to set a wrong value type)
`getCache(index)` - returns the cache value
`getType(index)` - returns the cache type

Maybe all caches could just be numbers, meaning could do away with more complex type checking and specifying cache types, since all is just "number". But then theres lua integers, so..

**Comment by Inari-Whitebear** [comment]
This is more of a discussion currently I suppose :P at least for the cpu part. IRC is nice, but I like discussions on here since you can keep a log of whats been suggested...

I suppose in light of this it would be interesting to separate the storage used for bytecode from the actual data stored by the architecture

**Comment by skyem123** [comment]
It would be interesting, but what would it be useful for?

**Comment by Inari-Whitebear** [comment]
Low-memory applications and microcontrollers pretty much :p

**Comment by SaphireLattice** [comment]
IIRC, someone made such thing with custom arch. An arm arch.

**Comment by Inari-Whitebear** [comment]
Yeah well, that arch isnt available/in OC yet though from all I've seen :D

**Comment by fnuecke** [comment]
IMHO this would make more sense to implement in an architecture specifically that can actually use this. For the Lua archs this is not really feasible at all.

**Comment by Techokami** [comment]
But EEPROM isn't RAM, it's a type of ROM. To change data, you erase cells then rewrite them.
As someone who gives a damn about electrical engineering, this leaves me feeling confused.
![:psyduck:](http://junks.holenet.info/SA_emotes/emot-psyduck.gif)

**Comment by Inari-Whitebear** [comment]
@Techokami theres a data part. and well... thats pretty much what RAM is :P Some storage to write to and later read from

**Comment by XFactHD** [comment]
There is a massive difference between writing to a RAM and a ROM. The biggest difference is the read/write speed.

**Comment by Inari-Whitebear** [comment]
So, its slower... still better than just having the smaller cpu registers :p

From what I read with EEPROMs you can erase, read and write individual bytes. Shouldn't be too unfeasible to use as some sort of Memory, and from the perspective of the CPU as RAM

**Comment by Inari-Whitebear** [comment]
I mean, not that I hugely care, was just a random idea I had while tinkering with stuff. I agree with Sangar though, and I disagree with that a EEPROM couldn't be used RAMlike

**Comment by bauen1** [comment]
I'm not quite sure, but _standard_ lua 5.3 uses 22kb ram and we only have 4kb of eeprom available so it can't really fit in there at the moment.

**Comment by Inari-Whitebear** [comment]
Well, since the PC code runs in its own lua state I was assuming the lua state itself doesn't use ram :P

**Comment by payonel** [comment]
I think to keep things simple, it could be argued that this is just another type of RAM, and we already had RAM in the memory sticks.
