### ISSUE TITLE
Own power source

### ISSUE THREAD

**Issue by ivanich-fmf** [MightyPirates/OpenComputers#1872]
In that mod you support energy system. But your own power sources can supply energy only for robots. Why aren't add your own power source for computers, besides power converter?

**Comment by gjgfuj** [comment]
Because it relies on other mods to provide power?

**Comment by ivanich-fmf** [comment]
Ok. It may be wise to give up power at all by default.

**Comment by Vexatos** [comment]
It does, though. If no power mod is installed, nothing needs power.

**Comment by ivanich-fmf** [comment]
Good. And what if I play without mods producing energy, but want to use the limited energy supply computers. In raw minecraft amount of resources it is very HUGE and would be nice to still be able to use them to ensure the power of computers.

**Comment by Vexatos** [comment]
You can change any power requirements in the config file as much as you want.

**Comment by ivanich-fmf** [comment]
But without power source it's not need.
If I install other mods with energy generators I can change it, but I have use energy limits without that mods.
Oops. But I can't run any crafted computer **without warning**.

**Comment by ivanich-fmf** [comment]
Explain why there is no power source for stationary computers, but there is enough support for the detailed energy system and energy sources robots. Just add a source like furnace (fuel burn - get energy, profit)
I do not propose to make the main source of power, which will replace the current need for modes of generating energy, but only propose to add a generator (if not the most efficient) to operate the power system without these mods. Like Applied Energetics/Applied Energetics 2 and GalacticCraft have own power sources.

**Comment by Vexatos** [comment]
OC wasn't really meant to have power generation. The two generator upgrades in robots are there because robots may work far away from any actual power source. If you want power requirements, just add any power mod.
