### ISSUE TITLE
Persistence/Reboot not working in 1.8.9

### ISSUE THREAD

**Issue by Pizzn** [MightyPirates/OpenComputers#1873]
Whenever a unloaded chunk is reloaded the computers in that chunk are switched off and the screens show the last output. Tested this for every release/beta version for 1.8.9 and used forge versions 1902 and 1761. Just out of curiosity I fired up 1.7.10 using OC 1.6.0.4-beta.2-universal and latest forge 1614 and persistence worked fine. 
This is true for multiplayer games as well as singleplayer games. Additionally, in singleplayer games after logging out in the chunk where a computer is placed, the computer is still running but the screen shows the last output but is not updated anymore.

**Comment by fnuecke** [comment]
Anything in the logs?

**Comment by fnuecke** [comment]
Nevermind, was able to reproduce. Looks like as of 1.8 onChunkUnload is called _before_ writeToNBT. Great -.-

Thanks for reporting!

**Comment by Pizzn** [comment]
Thanks for the quick fix! Unfortunately this didn't do it entirely. Loading unloaded chunks is working now but loading game in SP/restarting server generates the same behavior as above. Robot's persistence is working fine btw.
Tested with #80 1.6-dev build.

**Comment by RealGrep** [comment]
It does the same thing in OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar after a server restart. Screen shows the last output, but I have to reboot it to get it to work. Just so you know. :)

**Comment by Pizzn** [comment]
Did some additional testing, again with #80 dev-build, MC 1.8.9: SP seems to work, tested that only briefly. In MP the persistence works across server restart too, if the chunk was not loaded when the server was stopped. If it was loaded while stopping, screens "freeze" and computers are shut off. Hope this helps.

Edit: Apparently, its random whether the computer is turned off. Sometimes the computers are still on, haven't figured when/why this happens.
