### ISSUE TITLE
keypad return is not accepted as linefeed

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#1877]
When using a keyboard with a key/numpad, all of the keypad elements [0-9]+-/\* are properly handled as their respective characters on the keyboard, except for the return which is not accepted as a linefeed character

![screenshot from 2016-06-12 13-52-00](https://cloud.githubusercontent.com/assets/2107834/15993773/50775afc-30a5-11e6-8640-45040e32491b.png)
These are codes for enter, 1 ,1 (pad), 2, 2(pad), enter, enter(pad)

MC 1.7.10
OpenComputers-MC1.7.10-1.5.22.42-universal

**Comment by fnuecke** [comment]
I _think_ this is fixed already? @payonel?

**Comment by payonel** [comment]
closed by bcadcdb21e342624dacde1c5e983a1b4b059a5d4
