### ISSUE TITLE
Sunrise bugging out while having a screen open.

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1879]
Tested in 1.9.4#32 and 1.9.4#28 build... No optifine or fastcraft. Just OC, JEI, Computronics, AsieLib

Tested on forge 1954 and 1960

(Pics take a moment to load in)
Normal sunrise:
![Pic takes a moment to load](http://akari.in/pinky_IfRLp)

While screen open:
![Pic takes a moment to load](http://akari.in/pinky_eTnLL)

**Comment by payonel** [comment]
sorry no repro, at least not anymore
