### ISSUE TITLE
wen suported mods are not installed the game crashes

### ISSUE THREAD

**Issue by xadaemon** [MightyPirates/OpenComputers#188]
its gets an class not found error I would like to help adding a config to deactivate the support for these mods but I'm a java newbie.

**Comment by SpiritedDusty** [comment]
Please include a crash log.

**Comment by xadaemon** [comment]
ok some details this happens when I remove any of the mod blocks I will post the crash log in just no time

**Comment by fnuecke** [comment]
Since this sounds very similar to some other reports, please try with the latest [dev build](http://ci.cil.li/), which will probably fix it.
