### ISSUE TITLE
OC-Tan

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1883]
# OS-Tans

```
  (scroll to "OC-Tan" header to skip this)
```

A OS-tan, is a mascot (usually female, I think male ones are suffixed with -kun instead) for an operating system: a personification.
There are also app-tans (Firefox-tan, Chrome-tan) and ones for programming languages and all that kinda stuff.
The concept of having "tans" is somewhat popular currently; even Microsoft made official OS-Tans for 
Windows 7, 8, and 10.
Most of the OS-tans are however community made and range from DOS over 95/98 over ME and on. Of course there are ones for Unix, Firefox, Chrome, and a lot of other things too.

I'm not sure what the design process of the official Microsoft OS-tans was, but the community ones seem mostly influenced by both the artist's tastes and what the community sees in the OS and its specs. Some (i.e. firefox) of course follow a specific style or theme. Firefox-tan is usually a foxgirl, Windows-tans usually have the Windows colours/logo and so on.

As for specs, its a bit more vague but I think people argued XP-tan should have a big chest-size due to supporting more RAM or something... Or since ME was notoriously buggy, ME-tan has been depicted as a clumsy girl in maid uniform and glasses/braids (since thats usually the "clumsy character" trope in anime I think? well at least the glasses/braids)
## Examples

Just as some examples (to note: for the unofficial ones often there are multiple designs floating around, I'm not going to link all of them, go google them)
### Windows

[Official Windows 7-tan, Nanami Madobe](http://static.zerochan.net/Madobe.Nanami.full.1149596.jpg)
[Official Windows-8-tans, Ai and Yuu Madobe](http://assets.vr-zone.net/17605/madobe_ai_madobe_yuu.jpg)
[Official Windows-10-tan, Touko Madobe](http://www.windowscentral.com/sites/wpcentral.com/files/styles/larger/public/field/image/2015/05/windows-10-japanese-mascot.jpg?itok=fco4G9Cw)
[Unofficial XP-tan](http://img00.deviantart.net/62a1/i/2006/285/b/5/windows_xp_tan_by_lorddiablo006.jpg)
### Linux

[Unofficial Linux-tan](http://img12.deviantart.net/8fcb/i/2005/062/f/a/os_tan_fanart__linux_tan_by_juzo_kun.jpg)
### Browsers

[Unofficial Firefox-tan](https://dncache-mauganscorp.netdna-ssl.com/thumbseg/525/525471-bigthumbnail.jpg)
[Unofficial Chrome-tan](http://blog-imgs-42-origin.fc2.com/v/i/r/virtbm/img200_file.jpg)
### Others

[Buildcraft-tan](https://twitter.com/VicNightfall/status/730847163803181059)

[Personified Programming Languages](https://lh4.googleusercontent.com/-NDxrfUQATIo/VGPWun7-dsI/AAAAAAAAAbw/owQ2pDp_Zts/w1200-h1800/1415828640832.png) (I think there was one with more of them, but can't find that)
# OC-tan

So I believe we should have a OC-Tan. And this would be for discussion on:
1. Do people agree we should have one? And if they don't care, would they at least not mind?
2. How should she be integrated? Something in OpenOS? Just a mascot without real integration? (The Windows tans got official themes for example)
3. How should she look? Which qualities of OC do you want to personify? How would you personify them (i.e. how would they be pictured in the mascot) etc...

**Comment by skyem123** [comment]
Hey, @Victorious3, what do you think? :P

**Comment by Forecaster** [comment]
She'd definitely need to have a shoulder-robot

**Comment by Forecaster** [comment]
Does OC have an official color theme?

**Comment by skyem123** [comment]
```
<Skye> Temia, Inari, Saphire: OC Tan, Robot Tan, and Drone Tan?
<Inari> Skye: sounds good
<Temia> Also sounds good
```

**Comment by elfifae** [comment]
Of course, Drone-tan has to be an adorable fairy with drone wings.

**Comment by Inari-Whitebear** [comment]
If there drone or robot-tan... OC-tan should be their big sister

**Comment by Victorious3** [comment]
I could try in a week, no time at my hands currently, finals

**Comment by jhagrid77** [comment]
I think this would be awesome!

**Comment by skyem123** [comment]
OC-tan should wear the drone shoes and should be holding a tablet. Maybe she should be sitting on a computer?

**Comment by Inari-Whitebear** [comment]
As per IRC:
I still vote for cool big-sis char with slightly big boobs (not overly big, but not small either) :P

Maybe with a Drone-chan little sis later? Something like that :P

**Comment by gamax92** [comment]
Per IRC:

```
<gamax92> black hair with pink stripe?
<Temia> Glasses! Cool big sis look!
<Temia> Anyway Megumi sounds like a nice name.
<Temia> I like Megumi on its own merits, It sounds dignified.
<Temia> Totally needs to be written with the kanji for love too if we're going with bespectacled cool big sis.
```

A thing that still needs to be pointed out is a hair style and clothing style.

**Comment by skyem123** [comment]
Should there be one tan for all of OC, or more than one? As @lamialily wanted the drone-tan to be a fairy.
Hmm... Maybe OC-tan could represent the computers, and the tablets (as they are compatible) and OC-tan in a (small!) mech could be the robot?
Then we'd have a smaller one for the MCU and that same smaller one with drone wings for... drones?

**Comment by Inari-Whitebear** [comment]
Well, as this is already a OC symbol, OC-tan clearly needs a small robot floating on her shoulder

Also maybe she should wear hover boots?

**Comment by skyem123** [comment]
Yeah! The little robot is just cosmetic, though.

**Comment by scj643** [comment]
Have it be the size of https://images.hologfx.com/Doki/Shinryaku!%20Ika%20Musume/Shinryaku!%20Ika%20Musume%20-%20Vol%206.png

**Comment by skyem123** [comment]
@scj643, thats for the drone/microcontroller

**Comment by skyem123** [comment]
So... people want her to wear glasses, from what I understand.

**Comment by skyem123** [comment]
Also I recall people from IRC wanting her to wear a skirt.

**Comment by skyem123** [comment]
I would like her to wear a shirt with this logo on it: https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/textures/gui/logo.png

**Comment by Inari-Whitebear** [comment]
I don't want her to wear glasses personally :P But I think I might be in the minority there haha

**Comment by Victorious3** [comment]
@Inari-Whitebear Oh, I'd prefer no too... I don't know about skirt, sounds very generic, so far I've seen no suggestions to make clear that she's OC-tan. Also, the name. I think most were okay with Megumi, but she needs a last name, still.

**Comment by skyem123** [comment]
to make it clear, she should be wearing a shirt with the OC logo.
also... she should have a shoulder robot (special thinger) that important OC contributors have.

**Comment by Inari-Whitebear** [comment]
Yeah shoulder-robot was a thing... I don't feel like just putting a shirt with the Logo on does it justice, but if we can't come up with anythign else...

**Comment by skyem123** [comment]
OC-tan should have Lua programming books. also C programming books because OC has natives that Sangar hacked. :P

**Comment by Inari-Whitebear** [comment]
C-tan, Java-tan, Scala-tan and Lua-tan could be part of her family :p

**Comment by skyem123** [comment]
hahahah. Good point.
