### ISSUE TITLE
MCU's fail to start at server startup (again)

### ISSUE THREAD

**Issue by Forecaster** [MightyPirates/OpenComputers#1886]
1.7.10 - 1.6.0.907-dev

> bios:23: attempt to index global 'scan' (a nil value)

The MCU's appear to error with this during server startup, but start up fine when manually started after that.

"scan" is a method in the geolyzer of course.

This is the program used: http://pastebin.com/2kDZFK07
The MCU needs to contain a geolyzer and a redstone card for it to work correctly.

**Comment by payonel** [comment]
no-repro, sorry
if this happens to someone else. please open new ticket and provide repro details
