### ISSUE TITLE
Walk/Touch events for bumping head into screen above

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1887]
So... yeah, basically if theres a screen above you, pointing down, and you jump up at it... there should be a walk or touch or something event? :D

**Comment by payonel** [comment]
what are you making, super mario?

**Comment by Inari-Whitebear** [comment]
I think it came up as a concept for that, yeah. A button that activates when you boop into it from below... But it wasn't me who wanted it, I just liked the idea and felt it should be a thing :)

**Comment by SaphireLattice** [comment]
Can't you just use tripwire with screen above it?

**Comment by Inari-Whitebear** [comment]
Depends on your space. If it's like
S
O
O

S=Screen, O=Nothing, then there isn't really a place to put it...
