### ISSUE TITLE
Disassembler

### ISSUE THREAD

**Issue by Cronosus** [MightyPirates/OpenComputers#1893]
When i disassemble thermal cloth from galacticraft, disassembler output wool with nonvanilla subID
this wool is almost useless
maybe do it with other things too..

![2016-06-19_00 22 47](https://cloud.githubusercontent.com/assets/5349950/16174061/19109aba-35b4-11e6-9bb6-b80772c60c67.png)

**Comment by xarses** [comment]
I'm not sure if it's the same, but I tend to get trapped chests back, If so, I think it's an ore-dict thing, and probably unavoidable if so

**Comment by fnuecke** [comment]
That's why without a config change the disassembler cannot disassemble non-OC stuff. It's unsupported and weird things may happen :P

As for trapped chests, if an ingredient is specified via the oredict, any of the aliases can be returned, so that's what that is (most likely).
