### ISSUE TITLE
[1.8.9] Option to make Internet card software come preinstalled

### ISSUE THREAD

**Issue by Ristellise** [MightyPirates/OpenComputers#1894]
Yup found an internet card software (floppy). wished there was a setting to make it craftable...

**Comment by payonel** [comment]
The internet card is craftable: http://ocdoc.cil.li/item:internet_card

what version of opencomputers are you running?

**Comment by Ristellise** [comment]
latest version of Opencomputer for 1.9.4 : OpenComputers-MC1.9.4-1.6.0.2-beta.3
FYI : installing internet card does not give me pastebin...

**Comment by payonel** [comment]
First of all, I recommend using the latest builds, we have an updated version of openos that is better than the beta 3: http://ci.cil.li/job/OpenComputers-dev-MC1.9.4/ [download the OpenComputers-MC1.9.4-1.6.0.35-dev.jar file, or click this: http://ci.cil.li/job/OpenComputers-dev-MC1.9.4/lastSuccessfulBuild/artifact/build/libs/OpenComputers-MC1.9.4-1.6.0.35-dev.jar ]

Secondly, we are still working out how best to provide the software floppies. We have a few ideas. FOR NOW -- place a loot disk (any loot disk, e.g. OpenOS loot disk) and a wrench (e.g. OC's scrench) into a crafting table and you can "rotate" or "recraft" the disks. That is, you can pull out the disk from the output of the craft, put it back into the crafting grid next to the scrench and repeat, until you get the internet disk. For me, internet came after oppm. Though I'm on 1.7.10, the order could be different for you.

I haven't updated the wiki ( http://ocdoc.cil.li/ ) yet to give a wonderfully detailed explanation about how to use the new `install` program that you get with openos, but essentially, it'll let you EASILY install the software for the internet disk
1. put the internet software disk into your computer
2. run `install`
3. you should be prompted: "Install internet? [Y/n]"

Just press enter (capital "Y" meaning that is the default response if you enter nothing) and it'll install the internet software package off the floppy into your root filesystem.

THIS method is how you will install `pastebin` and `wget` from now on. Though we aim to improve the experience moreso. After you have finished the install, you no longer will need the floppy.

**Comment by Ristellise** [comment]
thanks for the detailed explaination  :)

**Comment by Joshwoo70** [comment]
thanks for the detailed explaination  :)
