### ISSUE TITLE
[1.9.4] Client froze placing screen on case

### ISSUE THREAD

**Issue by kwpugh** [MightyPirates/OpenComputers#1895]
Forge: 1968
Mod: OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar

I went to place a screen on top of a case (both Tier 1) and my client froze and timed out.

**Comment by fnuecke** [comment]
Can't reproduce. Any other mods installed? If so, does it only happen with only OC?
Does this happen every time, or just sometimes? Singleplayer or multiplayer?
