### ISSUE TITLE
Dual wielding does not work properly.

### ISSUE THREAD

**Issue by skyem123** [MightyPirates/OpenComputers#1897]
This seems to affect any OC item with a special right click action.
For example, you cannot use the tablet if it's in your alternate hand.
You also cannot put floppy disks in drives if it's in the alternate hand.

The alternate hand is supposed to perform a right click action if the right click action didn't work in the main hand.

**Comment by n00b7** [comment]
i found this line in the disk drive code:
val isHoldingDisk = drive.isItemValidForSlot(0, player.getHeldItem)
 player.getHeldItem dosn't return whats in your alternate hand

#bug minor

**Comment by skyem123** [comment]
👍
