### ISSUE TITLE
[feature/suggestion] Basic interpreter disk PLZ.

### ISSUE THREAD

**Issue by n00b7** [MightyPirates/OpenComputers#1899]
back then dos came with a basic interpreter like qbasic or viualbasic i think a basic interpreter would be a neat feature to add basic interpreters.

example of a basic program:

SCREEN 7
PRINT "TEST"

**Comment by skyem123** [comment]
I agree that there should be alternate languages for systems, though I don't think anyone has the time and motivation to finish such a large project. (someone started marking a FORTH interpreter).

**Comment by Inari-Whitebear** [comment]
A basic interpreter sounds doable in Lua :P Just make one and PR it

**Comment by xarses** [comment]
lua has `goto` so just do it already

**Comment by fnuecke** [comment]
Feel free to make one and add it to OpenPrograms (or _maybe_ PR it as a loot disk). Further discussion on this seems to be better suited for the forums or IRC.
