### ISSUE TITLE
Empty whitelist in the config by default

### ISSUE THREAD

**Issue by benanders** [MightyPirates/OpenComputers#19]
I'd like to suggest that by default you make the whitelist of URLs accessible by the HTTP API empty, so that any domain can be accessed. Having the blacklist by default block 127._, 192._, and 10.\* is a really good idea.

I can understand why you'd limit the API to Pastebin and GitHub Gist by default, but in my eyes this severely limits creativity and the functionality of the API. It completely prevents any program from being able to automatically update from a private server or a GitHub repository. It prevents people from making really cool things like cloud file storage systems, cross server web browsers, email systems, multiplayer games, and cross server data storage for even simple applications like to do list managers and notes applications. All these applications would require a connection to a private server (PHP webhost, Node.js, etc.).

For me personally, this sort of thing is a game changer on whether I really get into this mod or not (as I had done for ComputerCraft, but I've since gone off that due to the (in my opinion) deteriorating community). I don't want to go up to every server admin and try and convince them to change their config settings - something I can imagine many people being reluctant to do - for players to be able to use a potential program, nor do I want to convince players in single player to do the same. 

Could I also suggest implementing a socket API to create TCP and UDP connections to a socket server? That'd be really cool for making Skype-like IM applications.

Sorry for the wall of text. I have difficulty getting my point across in a succinct manner :)

**Comment by fnuecke** [comment]
Well, I thought of those more like... example values? But I see your point, it's easier not to change a config, after all. I might move those to the comments.

As for the socket API... that'd involve some limitations. The first one that comes to mind: connections would break when the computer gets resumed. Unlike file handles, which can be sneakily restored as long as the files are still there, socket connections cannot (it'd be impossible to restore the socket state on the server in a generic manner). There might be other things I can't think of right now.

If that's acceptable behavior - and you'd have to handle disconnects some way or another anyway - I'll think of a way of adding this in. This would probably make the HTTP API go away as it is now. I'm thinking adding a new component, basically an alternative/improved wireless network card that would offer an API for socket connections, might be a clean way to separate this out. One could then write a minimalistic reimplementation of what the HTTP API does now on top of that.

**Comment by LordFokas** [comment]
>  I'm thinking adding a new component, basically an alternative/improved wireless network card that would offer an API for socket connections, might be a clean way to separate this out. One could then write a minimalistic reimplementation of what the HTTP API does now on top of that.

You'd be reinventing a flawed and square wheel. I think it'd be best to use Java's HTTP stuff and using a blacklist with 10._, 127._, 172.16.\* and 192.168.\* in there by default.

172.16.\* is actually a /12 netmask, so you'd need to do a bit of math to block all private addresses on that network.

**Comment by fnuecke** [comment]
Yeah, well, it's not like the whole mod hasn't been one big reinvention of multiple wheels so far ;) I'll have to see how far one could get with a simple `GET` query to fetch some HTML. The API-minimalist in me really would like to go that way, but I agree that it might not be feasible. HTTP can be one hell of a beast to tackle.

As for netmasks... that's a very good point. There's got to be some library for Java (possibly built-in?) that would allow doing this in a clean and effortless manner. I'd be surprised if not.

**Comment by ghost** [comment]
If the whitelisting is going to stay as it is now, I'd suggest just simply adding github (as a whole) and dl.dropboxusercontent.com to the bundle, as I utilize github's Raw functionality and Dropbox's Synchronization to do fast testing and updating.

**Comment by fnuecke** [comment]
Since the original topic of this issue has been resolved, I created a new one purely for the socket API stuff: #29 
Feel free to discuss details on that feature in the new issue.
