### ISSUE TITLE
Crash bug when TE is installed without BC

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#190]
INFO] [STDERR] Caused by: java.lang.NoSuchMethodError: li.cil.oc.common.tileentity.traits.power.BuildCraft.getPowerProvider()Lbuildcraft/api/power/PowerHandler;

We put a computer down, the server then crashed.  When the chunk gets loaded the server crashes again.
The only server-side mods installed are OpenComputers and Thermal Expansion (on forge)

**Comment by fnuecke** [comment]
Could you try if this also happens in the latest [dev build](http://ci.cil.li/), because it doesn't for me. Thanks.

**Comment by ghost** [comment]
Tried OpenComputers-MC1.6.4-1.2.5.310-universal.jar, and the bug has been fixed.
Thanks a bunch! :D

**Comment by fnuecke** [comment]
Great :-)
