### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by TheMrCaveman** [MightyPirates/OpenComputers#1905]
See http://pastebin.com/nr3Uxixf

**Comment by fnuecke** [comment]
Uhh, I have no idea what this is. Does it also happen if OC is the only mod? If not, as soon as adding which mod does it happen?

Also, when does this happen? Randomly? When typing/displaying something specific on a screen?

**Comment by TheMrCaveman** [comment]
Nevermind!!! This was a random weird thing happening apparently everyone that connected got a crash report related to different mods;) a world reset fixed that.

**Comment by fnuecke** [comment]
OK, glad to hear it :)
