### ISSUE TITLE
Serial Interfaces for Microcontrollers

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1909]
So, this spawned from someone mentioning in the IRC that they would like for Microcontrollers to have a small screen of like 1 or 2 lines. It could be used to display small messages. In their specific case I think they wanted to do stuff like, have it measure when a locomotive passes through (using detectors from Railcraft) and then display on the screen how many minutes has passed since one came through.

Something that isn't quite enough to want a full blown computer, and one doesn't quite want to set up a central location the MCUs will transmit back to either.

I however disagree with having screens on them. Not strongly, I'd be fine if it was added, but on the other side I can see people crying for balance and that MCUs are supposed to have only niche applications.

So I propose another concept: serial interfaces. A way to hook a tablet up to a MCU and communicate with it. Something like USART or such, but obviously in the context of the mod, more simplified. Of course the connection would be terminated once you move too far away.

Possibly just a rate-limited write/read. Possibly as a component.microcontroller.write/read in the tablet and as a io.read/io.write for stdout/stdin in the MCU code.

**Comment by LizzyTrickster** [comment]
perhaps also have it need to be standing near the mcu? maybe 5 block
radius, any further should probably be using wireless cards or something?

**EDIT**: Didn't see @Inari-Whitebear's edit through email...

On 25 June 2016 at 18:16, Inari-Whitebear notifications@github.com wrote:

> So, this spawned from someone mentioning in the IRC that they would like
> for Microcontrollers to have a small screen of like 1 or 2 lines. It could
> be used to display small messages. In their specific case I think they
> wanted to do stuff like, have it measure when a locomotive passes through
> (using detectors from Railcraft) and then display on the screen how many
> minutes has passed since one came through.
> 
> Something that isn't quite enough to want a full blown computer, and one
> doesn't quite want to set up a central location the MCUs will transmit back
> to either.
> 
> I however disagree with having screens on them. Not strongly, I'd be fine
> if it was added, but on the other side I can see people crying for balance
> and that MCUs are supposed to have only niche applications.
> 
> So I propose another concept: serial interfaces. A way to hook a tablet up
> to a MCU and communicate with it. Something like USART or such, but
> obviously in the context of the mod, more simplified.
> Possibly just a rate-limited write/read. Possibly as a
> component.microcontroller.write/read in the tablet and as a
> io.read/io.write for stdout/stdin in the MCU code.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/MightyPirates/OpenComputers/issues/1909, or mute the
> thread
> https://github.com/notifications/unsubscribe/ADmcIXG0dAiIJliyynj_tN8Lq-rGJcy1ks5qPWJZgaJpZM4I-Y3v
> .

## 

Regards,
Lizzy Green

**Comment by Inari-Whitebear** [comment]
Yeah ^^ Already put that in too~

**Comment by Forecaster** [comment]
I think only being able to display one line at a time is pretty niche in itself : P

And yes, the use case was to use it with a detector (reading a redstone signal) to keep track on how long ago the last train passed by to help with noticing if one has gotten stuck somewhere, which is not something I'd want to set up an entire computer for.

**Comment by skyem123** [comment]
I think it would be interesting to have a general purpose serial interface for communication between stuff like robots and microcontrollers. Of course, if there is a serial interface, there should be serial terminals.

**Comment by MyNameIsKodos** [comment]
Screens for microcontrollers has been discussed to death afaik. Use a sign upgrade if you need a display of some kind. Or network messaging to a server handling updating a screen.

**Comment by Forecaster** [comment]
A sign would trigger extra world updates though. And I'd like it to stay as self-contained as possible. That is one of the advantages of a microcontroller after all.

I don't think it's unreasonable since LCD's are common with real microcontrollers. Basically this: http://pic-microcontroller.com/wp-content/uploads/2015/06/rtc-microcontroller.jpg

**Comment by Inari-Whitebear** [comment]
I think serial interfaces are nicer. :) But I'm also not against screens, as said

**Comment by XDjackieXD** [comment]
serial interfaces would be interesting and fun (for extra coolness render something like a leash when connected)

**Comment by skyem123** [comment]
Maybe the serial interface could be the same as the TIS-3D serial interface?

**Comment by payonel** [comment]
for uC the sign upgrade is what we'll support in-mod (tiny lcd sounds cool, imo)

**Comment by skyem123** [comment]
A way for a connection without any switching / routing / relaying going on like a real serial connection would be interesting I think

**Comment by xarses** [comment]
perhaps a use for the new t1 wireless card

**Comment by purplemonday** [comment]
i actualy played with airduno's and compared to how microcontrollers work on opencomputers..
its a real pain swapping the eeprom to program it. or to expose its data that using mc's basicly is tomuch of a hassle

with airduno's its an USB hookedup serial interface that allows you to reprogram, restart or even readout values.  this is all done having a second-front mcp chip dealing with reprogramming and having a console

the current situation Linkingup a microcontroller to a computer will show the microcontroler as a component however the mirco controler cant see the computer. (quite intresting behavour fyi)
but only limited features are exposed 
isRunning
isSideOpen
lastError
setSideOpen
start
stop
would be great to have a "write" and "getEnv" or such amongst these.
perhapse a mounted filesystem with the eeprom data i dunno

the manual labour in swapping the eeprom and then not easy to debug makes it realy hard to use these microcontrollers, would be realy sweet to see this get some love in making it easyer to program/readout values on demand.

i like also to mention microcontrollers have pins. in and out pins. much like redstone. i think that redstone should be enabled on default for them.

**Comment by Inari-Whitebear** [comment]
A microcontroller doesn't necessarily need to have GPIO pins, so I think it's fine that you add a redstone card for them.

Some sort of serial port might be nice to communicate with the Microcontroller from/to other devices though, I agree. Theres has actually been talk of a serial card for that.

As you said, the "connect to PC and reprogram" way for microcontrollers is achieved through a programmer - Arduino's have one onboard I think. Theres nothing that really prevents you from setting up a contraption to flash a MC's EEPROM on the fly so long as you have it around. Could even use a wireless network card and have it load the code from a PC while you're still programming.
Though a serial port would make that a bit easier, yeah.

**Comment by xarses** [comment]
some pointers
1. you can swap the eeprom with a shift click in hand
2. You can actually code the eeprom to support wireless updates

I do like the idea of extending the component to support reading and writing the eeprom, however if added it would need the current eeprom to have set the computer to allow it. It would remove the need of adding a whole new serial interface to accommodate the existing component hooks

**Comment by payonel** [comment]
so i closed this ticket because the discussion was lacking a real list of features we needed for uC, then me closing this ticket got everyone really excited about thinking of specific things we need to add.

my advise -- keep talking in this closed ticket to brainstorm or discuss uC ideas, but then spin off specific, small scope, feature requests for uC. If i like them (and i probably will) i'll mark them open for adoption or maybe i'll work on it myself

**Comment by skyem123** [comment]
What about a simple serial bus / cable that can only be used to send bytes? Support could be built into computers and microcontrollers, and they wouldn't "route" any data sent using them? Speed could just be limited by inherent OC execution limitations...

**Comment by Inari-Whitebear** [comment]
Bit odd if it can only send xD

**Comment by skyem123** [comment]
Send and receive bytes in order. :P

**Comment by xarses** [comment]
do we need a serial bus because we want to xmit data, if so why aren't we just using network?

I thought this was about being able to re-program a uC?
and maybe getting a io stream
 
I like the idea of adding these missing bits to the component that already shows up on the cabled network.

Now I read back to the OP, I strongly like the idea of the tablet being able to interface to the uC w/o using a cabled network, but reflecting on that, I would rather that right-click opening a tablet on ANYTHING on a component network connected the tablet to that network (maybe with a required component or jack cable in inventory) allowing for much grater productivity / debugging with tablets and re-enforcing their function as a mobile computer

**Comment by skyem123** [comment]
I like the idea of having a serial cable that can be separate but also built in to everything because then you have another way to communicate, but with pretty heavy disadvantages, but also an advantage that would interest crazy people like me.

**Comment by xarses** [comment]
Well, from an implementation standpoint it would likely take much more work to add an explicit serial interface than to extend the existing uC component with the missing interfaces, and allow tablets to jack into a component network, and on the tablet side this could be quite useful addition

**Comment by skyem123** [comment]
But if stuff was added as part of the component, wouldn't it then be part of the component network, which is a pain to use in just for communication. :P
