### ISSUE TITLE
Class Transformer 1.10 

### ISSUE THREAD

**Issue by Vasa200** [MightyPirates/OpenComputers#1910]
Errors running class transformer

Forge Mod Loader version 12.18.0.1996 for Minecraft 1.10
TransformerLoader (OpenComputers-MC1.10-1.6.0.2-beta.4.jar

[fml-client-latest.zip](https://github.com/MightyPirates/OpenComputers/files/333341/fml-client-latest.zip)

**Comment by fnuecke** [comment]
Thanks, yeah, not surprised :P The bot didn't have the 1.10 mappings yet, so I couldn't update those yet.
