### ISSUE TITLE
[1.9.4-1.6.0.3-beta.4] Robots can't swing?

### ISSUE THREAD

**Issue by L00Cyph3r** [MightyPirates/OpenComputers#1912]
Just deployed Creatix, gave him a pickaxe, told him to swing (up/down/front) but no blocks are being broken.
Return for the command is:
`nil` `net.minecraft.world.storage.WorldInfo.getGameType()Lnet/minecraft/world/WorldSettings$GameType;`
Also tried manually fabricating a robot, but still the same issue.
FYI, Running `MC1.9.4-1.6.0.3-beta.4`

**Comment by LordTy** [comment]
II have the same problem.
It does not happen in beta.3

**Comment by fnuecke** [comment]
Please update to the latest dev build and update your version of Forge. At least I couldn't reproduce it with that anymore.
