### ISSUE TITLE
After death, nano machines still consume power

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#1914]
[writes out a stub]

I recently noticed that my nanomachines have no active inputs, but I get particle effects and battery drain. I noticed that this appears to happen after dying. I need to poke at it more

MC 1.7.10
Forge 1566
OpenComputers-MC1.7.10-1.5.22.42-universal

**Comment by payonel** [comment]
it is by design to continue to drain power, but it shouldn't make particle effects

**Comment by payonel** [comment]
I'm not finding any issues with nanomachine power and particles (though, particles might be a bit too often, and it would be nice if the gamerule about particles also applied to nanomachines, but there is a ticket about that)

Note that a hunger effect will recharge the nanomachine if set active. i know your original ticket says all were set inactive, but ... it's something to consider if you try to repro this
