### ISSUE TITLE
[request] Pick up computers and robots with moving mods like JABBA's dolly

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#1915]
I'd like to be able to move computers and robot's around without needing to spill their contents everywhere. Mod's like JABBA make this easy to do with their dolly item, it would be awesome if we could support this mechanic or otherwise have something similar

I'd like to have the state saved so I could handily capture and re-locate a robot that is running (a suspend/resume event would probably be needed) to fix them when they go run off with out having to completely re-set them and start the bugger over but I could live w/o it as not having to re-fill it's inventory is my primary request.

**Comment by Inari-Whitebear** [comment]
I somewhat disagree with a reset/resume event for this case. Mostly because you could just put that into the robot program itself. In your software make "press X to pause" and "press X again to resume". And it makes no sense for the robot to know about the dolly or other like item I think.
Being able to move them around would be nice though, yeah.

**Comment by xarses** [comment]
If we consider support for #1936 then we should fire an event so that we can properly handle it in the program, otherwise the we should at least have to end back at the shell, if not powered off.

**Comment by Inari-Whitebear** [comment]
Hm? I'm saying I don't think there should be such a magical event, as you can just make a "press X to pause" and pause the robot before you move it.

**Comment by xarses** [comment]
So we should be able to pick up the robot, in the middle of it executing and let it continue on it's marry way resuming its previous stack at a new coord? That simply won't work well. Think about how you move a computer, you unplug it, it looses state and you have to reboot it when you set it back up.
Then think about what happens when you move your laptop (assuming you close the lid as to be able to easily move it, you don't put it in your backpack open) you close the lid, the laptop generates a AMPI suspend event, the OS has a chance to respond to it and put the unit into a low power state. When you open it again, you get resume event. Now, think about what happens when you turn off the screen of your phone. when you press the button, the open app is going to be send a suspend event allowing it to tidy up things, when you turn it back on it gets woken back up. Allowing it to understand things like, oh I probably moved, lets re-acquire our location, refresh that feed, etc...

Possible ways to deal with being moved:

We power off the unit as it's being picked up, and you have to restart it after you place it(and preferably, we should still get a shut-down event).

OR we add suspend/resume event, in which case only registered callbacks of the suspend event must finish before suspending. We can quibble over if smacking it with a dolly causes this or something more in OC does this like whacking it with a wrench and a button in the GUI (button may not be the only option, I want to avoid the GUI, which is part of the point at all here)

OR we generate an event post placing being moved along the lines of `position_changed` this way also makes sense, since a similar event is also useful if this also allows us moving the unit in other ways (like with a piston)

**Comment by Inari-Whitebear** [comment]
I mean sure, but robots have no such "sleep" feature as far as I'm aware :P
Not that it would work well with the lua architecture either...

So probably just restart, yeah.

**Comment by xarses** [comment]
No, we don't have a 'sleep' feature exactly, however, if we are going to do anything to keep the state, then I'd guess we'd be doing or even reusing the code paths that work with the chunk [un|]lloading so the architecture shouldn't care.

**Comment by Inari-Whitebear** [comment]
I suppose, but then theres no event as it would just continue where it left off

**Comment by Techokami** [comment]
FYI, adding support for using JABBA dollies requires modifying JABBA. Which isn't on GitHub. And Prof. Mobius likes to sit on PRs for a long time before doing anything. This is stuff discovered by the creator of Storage Drawers after I suggested a similar thing!

Now, there's a thing in Mekanism called the Cardboard Box, that allows the packaging and relocation of blocks, complete with their tile entities and container contents. However, when I tested it out with the latest release of OpenComputers, I managed to crash the server I was playing on when I tried to unpack a running computer... oops. :sweat_smile:

**Comment by MalkContent** [comment]
https://github.com/MightyPirates/OpenComputers/issues/1656

**Comment by MalkContent** [comment]
I'm gonna tag this on here :)
https://github.com/MightyPirates/OpenComputers/issues/1656

**Comment by payonel** [comment]
if we add this, we'll support them with a scrench "pop" to pick up items quickly, see #2578

**Comment by xarses** [comment]
so this was to cover two problems
1) When a item moving mod tries to pick up a OC computer, they need to be able to suspend / resume the computer in such a way that MC doesn't crash (the OC computer is open for discussion)

2) That the computer and possibly drone & robot can be "popped" without all of their guts spilling every which way.

it seems that #2578 doesn't account for either?

**Comment by payonel** [comment]
To your points
1. That sounds like an integration incompatibility with a mod, like jabba, that wants to move our entities. I thought this ticket was about a feature for OC to do this
2. The requirement I have for #2578 is that the pop won't spill the guts

**Comment by xarses** [comment]
No guts everywhere is good for me
