### ISSUE TITLE
Microcontrollers don't share their power to the network

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#1916]
So I wanted to make some self contained microcontrollers and noted that I produce more power (solar generator) on average than I consume, so I figured I could plop down some capacitors to ensure I could have enough power for the night, rare times I needed it, or bad weather. However I came to find that they don't emit any of their power to the network.

MC 1.7.10
Forge 1566
OpenComputers-MC1.7.10-1.5.22.42-universal

**Comment by fnuecke** [comment]
That's intentional. They're not power distributors ;)

Use battery upgrades for a larger internal energy buffer or use external power generation.
