### ISSUE TITLE
[request] make microcontrollers great Again...

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#1917]
[Title is a play on "Make America great again" campeign slogan]

So micro controllers... I felt there is such promise here but gaps everywhere then, when coupled with the higher cost, I've begun to feel there is no benefit over a regular computer. My interpretation is that a micro controller is supposed to represent a purpose built device like a IOT device, Sling Box, WiFi Router, Industrial controller etc. The primary deterrents to using using them as GP compute are the packaged form and the lack of a dedicated hard-disk, I think that and arguably coupled with a reduction in supported components, we could expose more combinations of them to greatly increase the places where a micro controller makes sense.

Use case one remote display controller.
Pattern, take a message from the [wireless] network and update a screen nearby. (could be extended into a VT100 terminal w/keyboard)
Issues:
- no components network.
- can't connect to a screen.
- can't use a graphics card.

Use case two, self contained GPS station
Pattern: respond to wireless message, generate and store own power
Issues:
- solar generator doesn't work in foul weather
- can't store excess energy (#1916)
- T2 Micro controller requires diamonds, which is awful expensive for the limited number of slots ( I could probably make this work with the generator and a battery upgrade)
- requires a bunch of extra support since it can't generate power consistently.

Use case three, remote industrial probe//controller
Pattern use an adapter and or transposer to interact with another machine, controlled by [wireless] network
Issues
- Can't use an adapter
- Wireless card makes cost impractical
- Simply more cost effective to drag fugly cable everywhere and use a normal computer

**Comment by Inari-Whitebear** [comment]
Well as far as I know, they are supposed to be useful only in niches?

**Comment by xarses** [comment]
> I think that and arguably coupled with a reduction in supported components,

Should read

 I think that and arguably coupled with a reduction in components capacity (IE divide the number of components per CPU by 2),

**Comment by 4thdwarflord** [comment]
Every issue described here seems true of microcontrollers IRL. What you are describing in real life is much closer to an embedded system, which IRL costs more.

Microcontrollers IRL are more useful for interacting with electronics, so I would think that that is the intent in this case (I.E. shrinking redstone circuits). That said, it would make more sense in this case not to require a redstone card, so I don't know.

**Comment by MalkContent** [comment]
I would already be happy if the T1 MCU could take a T2 and a T1 card and the T2 MCU could take a T3 and a T2 card.
Aaaand if they could receive inventory/tank controller upgrades. Aaand could generally act as an adapter so they can read info from blocks of other mods.

**Comment by Vexatos** [comment]
But then you might just use a tier 1 case instead. That's what they're there for. Just don't put any hard drive and graphics card into it and you have your MCU.

**Comment by MalkContent** [comment]
That wouldn't work for the cards though and be a at least 2 block solution with the additional adapter.
Not asking for access to external components, just a "smart adapter". (that can possibly use linked cards in t2 so i can implement a protocol to forward messages for my tablet with a network, because a linked card in a relay and a tablet doesn't do the trick and building a t3 case/ t2 server for just that seems overkill)

**Comment by Vexatos** [comment]
OC has never been about "single blocks doing everything". The entire point is that you have more than one block, that's why the MCUs, the actual "magic blocks", are so limited.

**Comment by Inari-Whitebear** [comment]
The actual "magical" block, that can't do anything without interacting with other blocks, but is restricted from doing so? ;)

**Comment by Vexatos** [comment]
It can interface with networks and redstone, that's what it is made for.

**Comment by gjgfuj** [comment]
But... That has no actual use? Like there's 1, maybe 2 use cases there.
Like they can't be too powerful obviously but just... I would suggest an
upgrade that allows you to access one side. That's my suggestion for a long
time. Just permanently lock the MCU to access only a single alternate
component. That's all they need, then they will actually have a use.
There's no point if all they can do is network and Redstone, you may as
well just run a wire to a Redstone io block from the original computer!
Less powerful than a T1 case, but actually useful.

**Comment by MalkContent** [comment]
I'd argue it'd remain quite limited, just a bit more purposeful. No access to external components, T1 ram and an eeprom full of instructions will do that for you.
And a standalone computer case would still not lose its purpose, even with the same hardware, /because/ it can access external components.
The difference is a computer case is good for tons of things, while a microcontroller barely has any application at all and it'd be nice if they did.

**Comment by payonel** [comment]
we might need to discuss a rework on uC eventually to make them solve problems other machines can't do as well - but I don't think this ticket needs to be the ticket for that discussion

**Comment by xarses** [comment]
huh?

Seriously, what are the usable cases for a uC, I still haven't found one that is worth the effort

**Comment by payonel** [comment]
What I meant was -- if we come up with specific ideas for uC to make them great, we should make those tickets. No more ideas had been gathered here for over a year so I felt this discussion had wound down.

As you've pointed out, the upcoming T1 wireless card will make uC more practical.
