### ISSUE TITLE
Setup of robots is gone after a while

### ISSUE THREAD

**Issue by dustpuppy** [MightyPirates/OpenComputers#1918]
Hi,
don't know how to describe this. I had 7 robots harvesting differend things. In the evening times everything was working fine. I let the game run over night and in the morning 3 of 7 robots had changed their name. One to E.V.E. and one to no name. No inventory in the gui. I've put one of them into a disassembler and there was only an empty tier 1 case. They where made with creative cases and a lot of other things.

![bildschirmfoto34](https://cloud.githubusercontent.com/assets/1313596/16414469/ad38f890-3d2f-11e6-91f3-fa4818756e8f.png)
![bildschirmfoto35](https://cloud.githubusercontent.com/assets/1313596/16414470/ad40e078-3d2f-11e6-8a77-cdc489e6ae33.png)
![bildschirmfoto36](https://cloud.githubusercontent.com/assets/1313596/16414471/ad4e0938-3d2f-11e6-84a4-f4a8ea234964.png)
![bildschirmfoto37](https://cloud.githubusercontent.com/assets/1313596/16414472/ad57e7a0-3d2f-11e6-98fc-8fced007dc08.png)
![bildschirmfoto38](https://cloud.githubusercontent.com/assets/1313596/16414473/ad5b20c8-3d2f-11e6-92be-e1b9c2cb7660.png)

**Comment by xarses** [comment]
I managed to have a somewhat similar experience with 1.5.22 in creative mode, restarting the server resolved the problem at that point. I find that this misbehavior occurs more if you place multiple instances of the same robot. I.E. Don't break and replace many instances of the same robot, get new ones from the assembler.

**Comment by Inari-Whitebear** [comment]
If you play in creative, I believe you can get copies of the same robot but them being different robots if you use some type of creative inventory (like a creative barrel).

Just basically pipe it from the assembler into that inventory (this is important, don't do it by hand, once you touch it, it gets a UUID and all. let the pipes do it). and then once you take it form the barrel it gets its ID then.

**Comment by Inari-Whitebear** [comment]
Dustpuppy said he cloned them btw (in IRC), so that may be the issue, as @xarses mentioned.
