### ISSUE TITLE
(feature request) recipe for the command block

### ISSUE THREAD

**Issue by 0Navis0** [MightyPirates/OpenComputers#1919]
It would be nice if OpenComputer added a recipe for the Minecraft command block. I know that ComputerCraft did it and I had finded this idea interesting. ;)

**Comment by miyoyo** [comment]
Computercraft has command-enabled computers, but it requires to have enabled command blocks on the server to work, and it does NOT have any crafting recipe. [I'm pretty sure here is already an interface to connect to command blocks](http://ocdoc.cil.li/block:adapter).

**Comment by LizzyTrickster** [comment]
The debug card can do command block commands

**Comment by fnuecke** [comment]
No. Use Minetweaker or such if you need a craftable command block or debug card.
