### ISSUE TITLE
Open Computers crashes minecraft

### ISSUE THREAD

**Issue by Kinnalory** [MightyPirates/OpenComputers#192]
Description:

When entering another dimension different than the "normal" world, or breaking a charger, the game crashes. Never happenned before with other versions of Open Computers and never happened before updating Open Computers mod. It happens  a lot when entering the twilight forest portal.

Server Info:

Minecraft Version: 1.7.2
Forge Version: 1.7.2-10.12.0.1024

Mods Intalled:

Open Computer Version: 1.2.4.97
Buildcraft 5.0.4.67
Iron Chests 6.0.5.714
Archimedes Ships 1.5.2
Bibliocraft 1.6.3
Twilight Forest 2.0.3
Custom NPC's 1.7.2

Log:

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 1/04/14 19:19
Description: Exception ticking world entities

java.lang.NoSuchMethodError: li.cil.oc.common.tileentity.traits.power.IndustrialCraft2$class.onChunkUnload(Lli/cil/oc/common/tileentity/traits/power/IndustrialCraft2;)V
    at li.cil.oc.common.tileentity.PowerConverter.li$cil$oc$common$tileentity$traits$Environment$$super$onChunkUnload(PowerConverter.scala:8)
    at li.cil.oc.common.tileentity.traits.Environment$class.onChunkUnload(Environment.scala:25)
    at li.cil.oc.common.tileentity.PowerConverter.onChunkUnload(PowerConverter.scala:8)
    at net.minecraft.world.World.func_72939_s(World.java:2008)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:512)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:657)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:568)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:705)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at li.cil.oc.common.tileentity.PowerConverter.li$cil$oc$common$tileentity$traits$Environment$$super$onChunkUnload(PowerConverter.scala:8)
    at li.cil.oc.common.tileentity.traits.Environment$class.onChunkUnload(Environment.scala:25)
    at li.cil.oc.common.tileentity.PowerConverter.onChunkUnload(PowerConverter.scala:8)
    at net.minecraft.world.World.func_72939_s(World.java:2008)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:512)

-- Affected level --
Details:
    Level name: Stormlabs 101_2
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 1080 Drop: 241
    Level seed: 1044914262
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-136,64,208), Chunk: (at 8,4,0 in -9,13; contains blocks -144,0,208 to -129,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 36933 game time, 25185 day time
    Level dimension: 7
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 156205 (now: false), thunder time: 59206 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:657)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:568)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:705)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_09, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1300786920 bytes (1240 MB) / 1775894528 bytes (1693 MB) up to 3817799680 bytes (3640 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G
    AABB Pool Size: 10513 (588728 bytes; 0 MB) allocated, 8646 (484176 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP v9.01-pre FML v7.2.116.1024 Minecraft Forge 10.12.0.1024 18 mods loaded, 18 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.2.116.1024} [Forge Mod Loader](forge-1.7.2-10.12.0.1024.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.12.0.1024} [Minecraft Forge](forge-1.7.2-10.12.0.1024.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{rc_} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{rc_} [Not Enough Items](NotEnoughItems-1.7.2-rc2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArchimedesShips{1.7.2 v1.5.2} [Archimedes' Ships](ArchimedesShips.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.6.3} [BiblioCraft](BiblioCraft[1.6.3][MC1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{5.0.4} [BuildCraft](buildcraft-5.0.4.67.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{5.0.4} [BC Builders](buildcraft-5.0.4.67.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{5.0.4} [BC Energy](buildcraft-5.0.4.67.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{5.0.4} [BC Factory](buildcraft-5.0.4.67.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{5.0.4} [BC Transport](buildcraft-5.0.4.67.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{5.0.4} [BC Silicon](buildcraft-5.0.4.67.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    customnpcs{1.7.2} [CustomNpcs](CustomNPCs_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{6.0.5.714} [Iron Chest](ironchest-1.7.2-6.0.5.714-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers|Core{1.0.0} [OpenComputers (Core)](OpenComputers-MC1.7.2-1.2.4.97-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers{1.2.4.97} [OpenComputers](OpenComputers-MC1.7.2-1.2.4.97-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest{2.0.3} [The Twilight Forest](twilightforest-1.7.2-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 2386 (133616 bytes; 0 MB) allocated, 566 (31696 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['Kinnalory'/344, l='Stormlabs 101_2', x=2889,00, y=35,50, z=328,00]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by fnuecke** [comment]
I think this _should_ be fixed in the recent builds, please try [the latest dev build](http://ci.cil.li/) and let me know.

**Comment by Kinnalory** [comment]
Downloaded the Universal 1.7.2-1.2.5.111. Made a lot of tests. Worked great!! The problem was effectively solved.

**Comment by fnuecke** [comment]
Good to hear :-)
