### ISSUE TITLE
Extend open computers

### ISSUE THREAD

**Issue by n00b7** [MightyPirates/OpenComputers#1920]
remember the com/scsi and ps/2 ports from the apple mac classic
and the lpt[Line PrinTer] pots on older pc's
could those maybe implemented into oc?
or maby through a card that allows the use of 1l lpt/scsi/com/ps2 port?
and maby a printer that can make written books/papers(or printed)and external hard disks[or flashdrive] and ther could be different tiers of usb like tier 1[1.0/1.1] and tier 2[2.0] and maybe
tier 3[3.0] 
and make cpu's have heat sinks and even gpu heat sink's 
and ip adresses? like 127.0.0.1???

**Comment by LizzyTrickster** [comment]
For printing stuff, there's OpenPrinter.

As for the rest, what would it add to OC that isn't already present in OC itself or established addon mods?

**Comment by miyoyo** [comment]
Ports are mainly useless as OC uses a UUID peripheral system connected with a single cable, you can see it as a similar to SCSI system.
Multiple speed of ports are completely useless as we don't have direct memory copy here, nor do we have fast enough drives (18 seconds to write \0 on an entire 4mb drive in unmanaged mode, it's really slow) so there won't be any benefits to make it more "realistic" and OC has a (vanilla) technology level of around the 1970-80 (if you single out the holograms, touch screen and you justify the robots by minecraft physics) so USB of multiple speed wouldn't make sense at all (except if we get HDDs bigger than 4mb, outside of raids)
Heat sinks would also be another time waster, and losing time around building a fan, a heat dispersion array and thermal paste would kill the fun of some.
IP adresses can be simulated in software.

**Comment by fnuecke** [comment]
"Vanilla" OC is, at the moment anyway, too high-level for such things to make sense. And even if the low level API makes it in, this sounds like it would the task for an addon mod implementing a low level arch.
