### ISSUE TITLE
getCpus method of ME Controller returns wrong number of Crafting CPUs

### ISSUE THREAD

**Issue by Yepoleb** [MightyPirates/OpenComputers#1921]
The getCpus method ignores CPUs that have the exact same properties as another one. If you have multiple Crafting CPUs with the default name and the same amount of storage and Co Processors, it only returns a single entry.

I understand that you may not want to support unnamed processors because crafting requests require a name too. In that case you shouldn't return any results instead of wrong ones and state that in the documentation. Otherwise I'd suggest adding an ID property or using the ID as the name, which could also be used in crafting requests.

**Comment by fnuecke** [comment]
If they're not in the list returned by getCPUs, that indicates they're not returned by the API, so nothing I can do there. For requesting a crafting operation, the name is _optional_. Not passing it uses the first-best CPU (which is done internally by AE2, when passing `null`).

**Comment by Yepoleb** [comment]
I just tested this with CC + OpenPeripherals and it returns 4 entries instead of a single one like OC. There must be something that removes duplicates either intentionally or as a side effect of hash maps.

**Comment by fnuecke** [comment]
Hrm, that's very odd then... I'll need to debug it step by step then. I'll look into it.

**Comment by Yepoleb** [comment]
Thanks for the fix!
