### ISSUE TITLE
opencomputer adds his own endstone

### ISSUE THREAD

**Issue by 0Navis0** [MightyPirates/OpenComputers#1922]
I'm not sure if it's normal, but OpenComputer adds his own endstone. I'm not sure to understand the utility of that when it exists Minecraft Vanilla version, and it removes compatibility with other mods.

**Comment by Inari-Whitebear** [comment]
Uhm, I'm fairly sure it doesn't add redstone...

It has the redstone i/o block to communicate with redstone and that kinda it? Not sure what you mean

**Comment by 0Navis0** [comment]
I said ENDstone, not redstone.

**Comment by Inari-Whitebear** [comment]
Oh, my bad. Misread :P

And yeah, it's just fake endstone to be able to craft the stuff that requires it more easily I think. Without giving you the possibility to get easy endstone for other mods

**Comment by 0Navis0** [comment]
But why not use the Vanilla endstone itself, it's simpler.

**Comment by Inari-Whitebear** [comment]
Because you have to get to the end to use that I guess? No clue :P

**Comment by Techokami** [comment]
iirc it is to allow for using Endstone in certain recipes without needing to travel to The End. Remember: you have to kill the Ender Dragon before an exit portal back to the overworld will generate in The End. Requiring the player to slay a dragon to make drone cases is a bit... much.

Fake Endstone is oredict'd with real Endstone, and the recipes should be accepting both kinds. If it is preventing you from using real Endstone in the OpenComputers recipes that use Endstone, _THEN_ we have a problem that could either be with the oredict, the recipe config files, or a conflicting mod.

**Comment by 0Navis0** [comment]
I saw that it was possible to craft this particular endstone, but why not just add a recipe to the vanilla endstone for being able to craft it, it would solve all the problems. And yeah it goes in kinda conflicts with other mods wich interact with the endstone.

**Comment by gjgfuj** [comment]
Because some mods want to enforce endstone being only available after
killing the dragon. So there's no problem. (is this endstone called "Fake
Endstone" or some other way of showing that it is actually the fake stuff
rather than the real stuff.)

**Comment by Inari-Whitebear** [comment]
It's just called End Stone. I agree calling it something else might be better though.

**Comment by skyem123** [comment]
It's called endstone, but there is a tooltip about it being fake, IIRC

**Comment by fnuecke** [comment]
It has a tooltip, so it should be obvious it's not the same as vanilla one (even moreso if you have a mod that adds the mod name to the tooltip). And yes, it's there to allow crafting drones before going to the end without messing with other mods' balance.
