### ISSUE TITLE
Network signals from microcontrollers are being forwarded to connected computers.

### ISSUE THREAD

**Issue by funmaker** [MightyPirates/OpenComputers#1926]
Minecraft: 1.7.10
FTB: 1.4.12
OC: MC1.7.10-1.5.22.46-universal

![09ef591623](https://cloud.githubusercontent.com/assets/3338680/16520905/a6198316-3f93-11e6-8de9-38a3889664d6.png)

When microcontroller receive network message, it forwards the signal to attached computers. Computers can't even detect or use the component that received the message. It makes programming networking based on routers instead of relays harder, waste computer's resources and is not expected behavior in my opinion.

![c54cb8a56d](https://cloud.githubusercontent.com/assets/3338680/16521038/66a40818-3f94-11e6-9ddd-1d48ad0015ce.png)

obe - microcontroller's network card
6bi - computer's network card
f8b - microcontroller's left side

**Comment by LizzyTrickster** [comment]
what code is the MCU running?

**Comment by funmaker** [comment]
The one that was printed on console.
It opens port 123 and then it just consume signals.

**Comment by Inari-Whitebear** [comment]
The only issue I see here is that the computer gets the broadcast message, but I'm not sure if it's intended that the sender gets the message even though it didn't open that port
