### ISSUE TITLE
[1.9.4] Robot can't move through "passable" block

### ISSUE THREAD

**Issue by HammerDave** [MightyPirates/OpenComputers#1927]
Running 1.9.4 beta 2.  Trying to move past a torch on the ground.  robot.detect() returns true, "passable", but robot.forward() fails to move and returns nil,"passable".  So there is a block there, it should be passable, but can't move into it despite it being passable.

**Comment by Inari-Whitebear** [comment]
Well Robots are blocks/tile entities. So I wouldn't "passable" probably means drones and players can go through it?

**Comment by fnuecke** [comment]
Yes. Passable means it's a non-solid block (one entities can walk through). But not robots, unless it's a `replaceable` block (like grass). So this is working as intended. Robots can only move through `replaceable` and `air`/nothing.
