### ISSUE TITLE
[request] Light Level for based on state for 3d models

### ISSUE THREAD

**Issue by primetoxinz** [MightyPirates/OpenComputers#1929]
not sure how possible this is, but if lightlevel could be switched, even if from 0 to (lightLevel) when clicked, it would allow for lamps and other cool models

**Comment by Inari-Whitebear** [comment]
Would be very handy :D

**Comment by fnuecke** [comment]
I gave up on having screens have dynamic light levels (no light when off), so I won't sink any more time into this I'm afraid. If someone else wants to give this a shot and can make it work reliably, I'll gladly take a pull request.
