### ISSUE TITLE
Deprecate power converter, make more blocks accept power directly

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#193]
@Gopher42 brought this up earlier, by expecting Chargers to directly accept power.

Which blocks accept power and which don't currently is a bit... inconsistent. Originally only the power converter accepted energy from other mods, but because it kind of made sense in my head, and allows to get started more quickly I made computer cases and server racks also accept power. Which leaves us where the mod is now.

I'm thinking I'd like to eventually make all blocks to accept power directly for which it somehow 'makes sense' to, and possibly even deprecate the power converter block. Additional blocks where I feel it would make sense are basically blocks that intuitively and actually use power:
- Charger
- Screen
- Power Distributor
- Maybe: Capacitor.

I'd like to get some feedback before I go ahead with this, though, so some sharing of thoughts would be appreciated! Thanks.

**Comment by GopherAtl** [comment]
Obviously, I support the idea XD I could see the logic of having a converter block, but it seems like an all-or-nothing thing to me, either everything should require it or nothing should. Some devices could still receive power only through other computer blocks; for example, you don't even think about power for a keyboard or other usb device irl, it just gets power from the computer it's connected to. The transmission between all connected oc blocks seems a reasonable analogue to the cables that would do this irl.

Of course, going the other direction that thinking, high-powered devices like monitors generally /don't/ daisy-chain power from the computer they're connected to, but require a direct power connection of their own. The inconvenience of this, especially for the basic monitor-on-computer setup, is a strong mark against it, but in the case of chargers, whose whole purpose is to store and release large amounts of power quickly, it would not seem unreasonable to me if they did require an actual power connection of their own, and couldn't just suck power through attached computers/monitors/etc.

**Comment by fnuecke** [comment]
I've decided to go with the following: if it's a block that requires energy to work, but does not require a computer to work, it can accept power directly. So in 1.3 in addition to the computer and server rack the charger, robot assembler and disassembler will accept power directly. Things like the screen, hologram projector and geolyzer require a computer to be used anyway, so they're expected to be powered via said computer. This seems like a simple enough and relatively intuitive rule.
