### ISSUE TITLE
[request] soft-shutdown

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#1936]
So I was thinking about #1915 some and I realized that we don't have a soft-shutdown function.

We could add (or modify the power buttons) so that there is a way to differentiate between a soft-shutdown (shot-press) and a hard-poweroff (long-press) Then when a soft press is triggered we can emit a shutdown event and either delay the shutdown or probably better, require all registered callback functions to finish.

**Comment by fnuecke** [comment]
So... redstone card + button and some Lua code? ;-)

**Comment by xarses** [comment]
`>.<` 

More like a uniform way to do it on computers, robots, drones, possibly even MCU's so that they are given the chance to save their state prior to being shut off. I was reminded of it while working on the same for dealing with low power, at least in that case, I don't have to rely on extra components and external influence

**Comment by skyem123** [comment]
It would be neat to have it in the GUI.

**Comment by SwiftCoderJoe** [comment]
I think this would be a great idea! I think they should have different buttons in the GUI though

**Comment by xarses** [comment]
You used to have different button's on your IRL computer too, but you don't anymore and for good reason. I'd prefer to have short-press vs long-press as it follows current IRL usage

**Comment by payonel** [comment]
I think we should use the shutdown event for calling code on shutdown (we have this)
And I think a program should call screen.turnOff() to go to a low power state
