### ISSUE TITLE
More HTTP request methods

### ISSUE THREAD

**Issue by Fingercomp** [MightyPirates/OpenComputers#1938]
Some websites (e.g., github API) require to use HTTP request methods different from GET and POST, e.g., `PUT`, `PATCH`, or `DELETE`. It'd nice if OC programs could send such HTTP requests.

**Comment by SaphireLattice** [comment]
Use raw TCP for that? Though, the lack of SSL might be a problem here.

**Comment by skyem123** [comment]
It would be useful to have more HTTP methods.
It would also be useful to allow using SSL in a more generic way, however, it would be quite tricky.

**Comment by xarses** [comment]
raw TCP isn't a solution, as you noted it lacks SSL support, which is mandatory for HTTP connections now days.

I didn't realize the methods where filtered, we need to have both header and full method support to do fun things with API's
