### ISSUE TITLE
Debug Card setGameType

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#1939]
When I try to do (in lua prompt or in equivalent code)

```
d = component.debug
p = d.getPlayer("_Inari")
=p.setGameType("creative")
```

I just get:

```
nil    net.minecraft.world.WorldSettings$GameType.func_77142_a(Ljava/lang/String;)Lnet/minecraft/world/WorldSettings$GameType;
```

and no change occurs

**Comment by XDjackieXD** [comment]
~~This only happens if the server is set to "force-gamemode=true" in the server settings (just tried it in my dev env)~~

Edit: Forget what I said. It breaks on the server and works on singleplayer

**Comment by fnuecke** [comment]
```
        @SideOnly(Side.CLIENT)
        public static WorldSettings.GameType getByName(String gamemodeName)
```

ffs mojang -.- will fix when I'm back from vacation.
