### ISSUE TITLE
bucket dupe, interaction with TE's mechanist workbench

### ISSUE THREAD

**Issue by GopherAtl** [MightyPirates/OpenComputers#194]
Not sure which mod this applies to, actually, will see if I can find some other recipes with buckets of water to test with, but when crafting grog at a mechanist's workbench, two different things happen.

First, using it normally, crafting once pulls the "ghost" bucket out of the crafting grid, breaking the recipe, as well as returning an empty bucket to the workbench's inventory. So when you use the grog to craft PCBs, you get back a copy of the bucket.

if you shift-click to make as many as possible at once, it makes only one, breaks the recipe as before, but instead of giving you an empty bucket, it doesn't actually consume a full bucket, letting you just keep the bucket of water.

**Comment by GopherAtl** [comment]
actually can't think of anything else that crafts with a bucket of water and doesn't give back the bucket...

**Comment by fnuecke** [comment]
Always with the special cases :-/ I might just make it use a cauldron...

**Comment by GopherAtl** [comment]
Just throwing this out there, but you could just give the bucket back when crafting the grog, instead of when using the grog to craft a PCB. Then your recipe isn't a special case, and should work with any crafting systems anyone can think of. Alternately, use bottles of water instead of buckets; those are expected to go away when crafted, and that seems to be the bit giving the mechanist table fits, not the giving it back when crafting a PCB. Or just don't give the bottles back; grog's only in hardmode, one more glass to the cost won't change much.

**Comment by fnuecke** [comment]
Well the reason it's like it is is that the grog still has to be _in_ something :-P At least visually it is, after all. In something metal-ish at that. Because that's how I remember it from Monkey Island.
I'll give it some thought. I don't really feel it's very pressing, because I don't think many people use the hardmode recipes anyway (I might be wrong?)

**Comment by GopherAtl** [comment]
afaik just me, and I threw away the duplicated buckets, because I'm honest like that.
