### ISSUE TITLE
All lines Please Help!

### ISSUE THREAD

**Issue by SwiftCoderJoe** [MightyPirates/OpenComputers#1940]
Please Help I Cannot Play With This!
on the screen, all it shows is lines. no text, just lines. I can't even use opencomputers anymore please help! I am using the Galactic Science pack.  ps i can't use computer craft either.
screenshot:
![2016-07-11_08 50 33](https://cloud.githubusercontent.com/assets/20341514/16731174/b50ea460-4744-11e6-8d99-3c70869e56b2.png)
link to the Galactic Science pack: 
http://forum.feed-the-beast.com/threads/listed-1-7-10-hqm-survival-galactic-science-something-fresh.86203/
I hope you all can fix this as I cannot use computerCraft until this is fixed.

**Comment by SwiftCoderJoe** [comment]
should I give a screenshot?

**Comment by xarses** [comment]
There is zero information here that we can use to help you with the problem. Please include screenshots and any relevant logs, and mod versions, or link to the pack you are using

**Comment by payonel** [comment]
Also, there is not a justified reason for all caps, bold text, and 7 exclamation marks. Consider not using sms-message spelling of words like "PLZ" - this is the official github issues for OpenComputers, not a quick chat to your _bruh_

**Comment by SwiftCoderJoe** [comment]
I am sorry about that. I will give a screenshot, and a link to the pack. I will also edit the message. I was very annoyed and couldn't help myself. I am currently on a vacation and do not have a computer right now. I am on mobile so I can't edit the massage, or get any other information. I should get back to you in about three days. I am sorry for any inconvenience and annoyance that I may have put upon you. Hopefully thou can help. Thanks so much.

**Comment by SwiftCoderJoe** [comment]
can you guys PLEASE help? i still can't use OC

**Comment by payonel** [comment]
@joeyyellow2005 Typically there is about a day or so delay until we can work on issues. I, for one, am at work. But I'll look into this when I can.

In the meantime, could you try using a tier 1 screen and seeing what the text looks like?

**Comment by xarses** [comment]
Lets start you off by disabling  your texture pack. I don't see optfine in the pack, but if you added it, try disabling it, next up is the voxel ones (hopefully nothing else depends on them). Try disabling one thing at a time and let us know what the result is.

Also, does it look the same when you open the gui? what about a 1 block screen in stead of 4

Also, it might be useful to get your full log, that may be some odd fallback font.

**Comment by SwiftCoderJoe** [comment]
@xarses i have the default texture pack should I still disable it?

**Comment by payonel** [comment]
you would test by disabling all BUT the default - if default is the only one, move on, test next thing suggested; e.g. disable optifine

also, how does the screen look if your right click? how does the screen look using other screen tiers (1 or 2)

**Comment by SwiftCoderJoe** [comment]
I installed a new texture pack and it worked fine. must have been something with the old one..?... but anyway it was fixed whatever. Thanks for all of your help!
