### ISSUE TITLE
[1.10] There were errors running the class transformer..

### ISSUE THREAD

**Issue by NanayaQ** [MightyPirates/OpenComputers#1950]
I just install OC today and got this class transformer error message so here I am reporting it. This is SSP.

latest.log file
http://pastebin.com/SyRtZdSf

fml-client-latest.log file
[fml-client-latest.txt](https://github.com/MightyPirates/OpenComputers/files/355790/fml-client-latest.txt)

Mod use
http://imgur.com/0dIg605

**Comment by fnuecke** [comment]
Thanks, should already be fixed in latest dev build.
