### ISSUE TITLE
[1.10] Raw Circuit Board recipe broken

### ISSUE THREAD

**Issue by mickkay** [MightyPirates/OpenComputers#1951]
Hi folks,

I just installed OpenComputers 1.6.0.2-beta.4 using Forge 12.18.0.2000 and MC 1.10.
I tried to craft a raw circuit board, but nothing happens when I place
 1x Clay (Block) 
 1x Gold nugget
 1x Cactus Green
onto the crafting table.

Cheers
MickKay

**Comment by Fingercomp** [comment]
Use gold _ingot_, not nugget.

**Comment by mickkay** [comment]
Alright, that works.
Thanks.

Seems that http://ocdoc.cil.li/item:materials needs an update then.
Cheers
MickKay

**Comment by payonel** [comment]
@mickkay please close this issue if you find that it is resolved.
Thank you for pointing out the discrepancy in our documentation. I've updated it. Revisit the docs to consider the changes.
