### ISSUE TITLE
[1.7.10] Cobweb is "passable" in robot.detect()

### ISSUE THREAD

**Issue by Georggi** [MightyPirates/OpenComputers#1952]
Well, title says everything, doing robot.detect() returns "passable" as a second parameter(I guess because it is passable for player) but unlike liquids robot cannot go through. Should return "solid" instead.

**Comment by Fingercomp** [comment]
`passable` means passable for player, not robot. Robots can only go through `air` and `replaceable` blocks (e.g., grass). Also see #1927.

**Comment by Georggi** [comment]
Ok, thx then, gonna close this.
