### ISSUE TITLE
[Suggestion:] Tablet docking station.

### ISSUE THREAD

**Issue by WhiteScholar** [MightyPirates/OpenComputers#1953]
I know there have been a fair amount of requests regarding portable computers/laptops ect... the fact that we have tablets is great, and they are fun to use and play with.

I'd like to expand on tablets a little, in the form of a docking station. Laptops's and Tablets as well as PDAs ect have had docks for just about forever in our world so that we can take that portable device and connect it to other things it normally can't connect to.

My thought here would be to have a special case, that could possibly be one of several that would have space for one or two expansion cards, and maybe a single slot for memory. [maybe not, need to keep things balanced as to prevent this from taking over the dedicated computer space.] But the idea would be to have a spot where the normally portable only tablet could have access to components. Such as a floppy drive or adapter connected to noteblocks ect...

This would let you have your tablet with you on the go and also use it for more tasks at the home/base/fort/mining facility that you have setup.

**Comment by Forecaster** [comment]
You can already access the hard drive of a tablet when it is in a charger

**Comment by cloakable** [comment]
And if the connected computer doesn't have an os installed, it will boot from the tablet hard drive

**Comment by WhiteScholar** [comment]
@Forecaster Not really the point of the suggestion.

@cloakable I honestly hadn't thought of that. I guess that works too, but that's building a whole computer sans HDD. at that point you might as well just throw the hdd in there too and call it a day.

**Comment by gjgfuj** [comment]
I could agree with this. However, I wouldn't make the docking station
accept any additional components. Just the tablet, and anything connected
to the docking station. I could see good useful features of this.

**Comment by JanSzumotalski** [comment]
@Forecaster how to do that
