### ISSUE TITLE
issue for OpenComputer mod 1.7.10

### ISSUE THREAD

**Issue by runescapejon** [MightyPirates/OpenComputers#1956]
can you add event cancelled status to support GriefpreventionPlus because i don't want people messing with the computer more information can be found here 
https://github.com/KaiKikuchi/GriefPreventionPlus/issues/102

**Comment by Inari-Whitebear** [comment]
If it is not disabled on your server, there is the adduser stuff to protect computer input.

**Comment by runescapejon** [comment]
If your talking about "canComputersBeOwned=true"" its default and users can still right click it

**Comment by payonel** [comment]
@runescapejon it is default `true`, yes, but means nothing unless a computer has a non-empty list of users. An empty list of users (default) means all-can-access

see http://ocdoc.cil.li/computer_users

in short, if I want to lock a computer to be ONLY accessible to me, i would run openos and type in the shell:

`useradd payonel`

**Comment by Inari-Whitebear** [comment]
In addition, as far as I recall, people will still be able to "open" screen by rightclicking, but can't input commands or such?

**Comment by runescapejon** [comment]
Thanks i got it @Inari-Whitebear  yea they can't write any commands
