### ISSUE TITLE
Request: Small 3D printed Block additions.

### ISSUE THREAD

**Issue by WhiteScholar** [MightyPirates/OpenComputers#1957]
Just 2 small Printed block features I myself think would be helpful, and make 3d prints more of a utility than just a Decoration. Being able to push/pull a 3d print with a piston/sticky piston. And being able to set a 3d print to only toggle states when a red stone signal is applied.

Had some really nice doors designed with the idea I'd have a sticky piston push them into porition and pull them away. only to find out that you cant move the 3D print blocks. made for some serious sadness.

**Comment by gjgfuj** [comment]
Unfortunately pistons and sticky pistons can't push TEs.... so they can't
push them. There might be a way to hack that in but Y'know.

**Comment by WhiteScholar** [comment]
I figured as much, at least locking the state switch to a redstone signal would be nice.. like iron doors. :3

**Comment by gjgfuj** [comment]
Yeah. Or just to the right click, that'd appeal to me. Or the ability to
share states with 3d prints next to it.

**Comment by WhiteScholar** [comment]
Ooo I like that. :100:

**Comment by payonel** [comment]
we've decided to limit the scope of 3d print feature scope
