### ISSUE TITLE
[1.10.2] SimpleComponent crash in a Dev Environment on NBT write

### ISSUE THREAD

**Issue by feldim2425** [MightyPirates/OpenComputers#1963]
OC Version : MC1.10.2-1.6.0.15-dev
Forge Version : 1.10.2-12.18.1.2014

As the Tile : 
I made a TileEntity that implements SimpleComponent and ManagedPeripheral. Placed the Block down connected it to a cabel and when I exit the World Mincraft crash and it doesn't save the Address.

Crash Log (At least the bottom part) : https://pastebin.com/d4ttjHA1

EDIT: Might be usefull. I added the api version to the project and copied the normal version into the run/mods folder

**Comment by fnuecke** [comment]
> func_74782_a

Looks like something's not getting mapped correctly. What mappings are you on? Maybe try updating them?

**Comment by feldim2425** [comment]
Updated to mapping snapshot_20160720

Now crashes when the world is loaded:
https://pastebin.com/er5XGsjC

**Comment by feldim2425** [comment]
Updated to snapshot_20160720 (Should be the latest if 20160721 is not already build)

Crash on world load: https://pastebin.com/cqn2U3Pw

**Comment by payonel** [comment]
no repro
