### ISSUE TITLE
[1.10.2] Computers left frozen after traveling past render distance

### ISSUE THREAD

**Issue by SirDavidLudwig** [MightyPirates/OpenComputers#1966]
So I went to test some stuff with the computers at long distances, and I noticed that, while it's running, if you go far enough away for the chunks to unload, the computer will be completely frozen when you return, and remain frozen until you reboot it.  This is really weird to me because it's obviously something from the chunks unloading, but if I exit the server long enough for the chunks to unload and return, the computer is not frozen.  This is the case on both single player and multiplayer.  Unfortunately, no log is generated, so I have no idea as to what could be causing this...

**Comment by payonel** [comment]
what version of oc are you using? i've made some improvements to the stability of openos in the very lastest build: http://ci.cil.li/job/OpenComputers-dev-MC1.10/lastSuccessfulBuild/artifact/build/libs/OpenComputers-MC1.10.2-1.6.0.15-dev.jar

This very well could be a chunk loading issue, in which case something @fnuecke is more experienced in fixing than myself. But I thought it would be worth trying the latest updates to openos which greatly improve detecting components, which may be differently occurring during chunk load as you describe.

**Comment by SirDavidLudwig** [comment]
I'm currently running the latest commit [ad82071] from the 'master-MC1.10' branch.  I just tested the build you gave me, rather than freezing, it just shuts down; which I suppose is much better, but the screen retains its content even though the computer is off.

**Comment by miyoyo** [comment]
This also sometimes happens after reloading the world.
The cursors won't move, but strangely when trying to type something the computers will have high disk activity forever

**Comment by Vexatos** [comment]
Does this still occur using OpenComputers 1.6.2?

**Comment by fnuecke** [comment]
Should have been fixed in 2751cec8c1526d489976627b4ffa0d6731616ee5. If not, please reopen.
