### ISSUE TITLE
Internet read method uses wrong argument index

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#1972]
Both read(n) in sockets and http use the index 1 which is wrong since they start from 0.

**Comment by feldim2425** [comment]
~~I think read(n) uses the system from lua. In lua arrays also start with index 1 and not 0~~

EDIT: Oh Sorry misunderstood that :D

**Comment by gamax92** [comment]
That doesn't change the fact that the documentation says `function([n:number]):string` yet you have to put it in the second argument slot to be able to actually get it to apply, like `read(nil, n)`
