### ISSUE TITLE
Support for Item Names

### ISSUE THREAD

**Issue by maxss** [MightyPirates/OpenComputers#198]
Sorry If this is supported already. In that case I did not find it in the documentation.

It would be really neat if there was a funciton or which gave you the name of an item in the inventory and the blocks in the outside world.

local blocking, type, name = robot.detect()

and robot.itemName(slot: number): string

**Comment by fnuecke** [comment]
An upgrade for robots that allows more 'precise' inventory interaction has been talked about in some other issue, I believe. It's somewhere on my todo list anyway ;-) For computers you can use [OpenComponents](https://github.com/MightyPirates/OpenComponents) plus an Adapter block next to an inventory.

For block type detection, have a look at [Computronics' camera](http://mc.shinonome.ch/doku.php?id=wiki:computronics:camera).
