### ISSUE TITLE
Make deviceComplexityByTier configurable

### ISSUE THREAD

**Issue by ctxnop** [MightyPirates/OpenComputers#1982]
I would like to configure complexity by tier.
To do so, you can make theses changes :
- delete this line : /src/main/scala/li/cil/oc/Settings.scala#L428
- add this code somewhere around this line : /src/main/scala/li/cil/oc/Settings.scala#L110

``` scala
  val deviceComplexityByTier = (Array(config.getIntList("robot.deviceComplexityByTier"): _*) match {
    case Array(tier1, tier2, tier3) =>
      Array(tier1: Int, tier2: Int, tier3: Int)
    case _ =>
      OpenComputers.log.warn("Bad number of robot complexity tiers, ignoring.")
      Array(12, 24, 32)
  }) ++ Array(9001)
```
- At /src/main/scala/li/cil/oc/common/template/Template.scala#127, replace

``` scala
Settings.deviceComplexityByTier(caseTier)
```

by

``` scala
Settings.get.deviceComplexityByTier(caseTier)
```
- You can add the setting in application.conf

**Comment by MRLokop** [comment]
Any changes pls?
