### ISSUE TITLE
Computers only accept OpenOS and Plan9k floppy disks

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#1983]
All other floppy disks give a error related to init.lua file
I'm using the 1.10-1.6.0.2beta4 version

**Comment by Fingercomp** [comment]
OpenOS and Plan9k disks are _bootable_, i.e., you can use them without installing an OS.
All other loot disks are not, and you need a computer running OpenOS to use them.
Insert the OpenOS floppy into the disk drive, boot the computer, and type `install`.

**Comment by payonel** [comment]
fingercomp is correct. Imagine you have a computer without a hard drive (or a brand new and blank hard drive you just bought from the computer store), and you put a microsoft office install dvd in the dvd drive -- and then wonder why the computer cannot boot. It needs an operating system. OpenOS and Plan9k are operating systems for OpenComputers found on loot disks. OpenOS is the "standard" OS that the documentation anticipates you have installed.
