### ISSUE TITLE
robots consume power when shutoff

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#1985]
When a robot is turned off by means other than the GUI shutdown button or world placement, it continues to consume power at approximately the sleep rate.

This occurs when `computer.shutdown()` is invoked, or if the robot runs out of power, and is recharged (it shutdown adjacent to a off-charger)

![2016-07-18_20 25 13](https://cloud.githubusercontent.com/assets/2107834/16960212/497d2f46-4d9d-11e6-8289-2f8c84650fbf.png)
![2016-07-18_20 25 16](https://cloud.githubusercontent.com/assets/2107834/16960213/497ea894-4d9d-11e6-8f43-42c05b02e52f.png)

(no testing has been done to correlate but it's maybe be related to #1914 )

**Comment by xarses** [comment]
This doesn't reproduce in SP, the computer takes an extra power tick, and then stops consuming energy.

**Comment by xarses** [comment]
Also impacts servers and computers, but in a different and possibly expected way.

For a computer you need to disconnect the power source and let it run out, eventually the computer will post to the screen the out of power and then both will flicker off, if you re-add power the screen comes back on, and since it has a wall of text the screens continue to consume power, while the computer case itself doesn't. You can cause a similar thing to happen when a server looses power and then is restored, the screen will continue to consume power from the network.

**Comment by fnuecke** [comment]
That it goes down once more is normal, that's just the delayed synchronization of the display values (only sent every so often because actual realtime values are not really needed).

As for it going down more after that, I'm afraid I can't reproduce that :/ Might be some component installed in the robot. I did throw a good variety in there without being able to reproduce it still, though.

**Comment by payonel** [comment]
@xarses I'm not sure what has changed or been fixed, but, this definitely doesn't repro anymore (yes, tested multiplayer)
