### ISSUE TITLE
[1.10.2] Crashes when right-clicking case

### ISSUE THREAD

**Issue by mzx987** [MightyPirates/OpenComputers#1987]
Not sure if anyone else is having this same issue, but I will submit it anyway.

As the title says, I crash when I right click a case.
The version I use is the latest dev version of OpenComputers for 1.10.2 (at the time of writing this post): OpenComputers-MC1.10.2-1.6.0.20-dev

Here is the crash report: http://pastebin.com/g9NSbjSa

**Comment by Vexatos** [comment]
You need to update JEI to 3.7.7.233 or later.

**Comment by mzx987** [comment]
Huh. Guess I should've read the crash report in more detail. Didn't realize the GUI and JEI was a part of the issue.

Thanks again!
