### ISSUE TITLE
[OpenOS] Stack traces cannot be redirected to a file

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#1995]
@payonel 
If a program crashes, the stack trace from it doesn't appear to go to stderr and cannot be captured into a file.

This can be important if say, the stack trace is too large to fit on the screen, removing the top of the trace, or the important part.

**Comment by payonel** [comment]
work around: run a child shell redirecting its stderr, in which you can run your crashy program
`sh 2>crash.log`
in which you can run your crashy program
`crashalots.lua`

Note that the file handle to crash.log is still open. you'll need to exit before you can see the report
`exit`
`cat crash.log`

I will investigate how we SHOULD be handling this. Thanks for reporting

**Comment by payonel** [comment]
fixed in 917befcd0e8e256bc52abb038f86bc04f236645a
