### ISSUE TITLE
Type of any component method is table

### ISSUE THREAD

**Issue by Fingercomp** [MightyPirates/OpenComputers#1997]
![Screenshot](https://cloud.githubusercontent.com/assets/9285212/17283232/60660f80-57d8-11e6-9df6-a3312bbeff6e.png)

**MC version**: 1.9.4
**OC version**: 1.6.0.66-dev

**Comment by dgelessus** [comment]
Yes, this is normal. Component methods are not real Lua functions, they are just tables with a custom `__call` metamethod that redirects to `component.invoke`.

**Comment by Fingercomp** [comment]
Okay, thanks. Found the code in `machine.lua` that wraps component methods in tables, and assigns `__call` and `__tostring` metamethods.
