### ISSUE TITLE
OpenComputers' overridden string.gsub fails on non-string inputs

### ISSUE THREAD

**Issue by asiekierka** [MightyPirates/OpenComputers#1999]
Apparently, Lua 5.2 will automatically run tostring() on all "string" inputs for the gsub/etc. string functions overriden by OC, thus making OC's implementation incompatible when a non-string input is given. Other functions overridden by machine.lua must be checked in the same manner.

Also, why do you override lower and not upper?

**Comment by fnuecke** [comment]
Doesn't for me?

```
derp ~ # lua
Lua 5.2.1  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> =string.gsub(false, "f", "")
stdin:1: bad argument #1 to 'gsub' (string expected, got boolean)
stack traceback:
        [C]: in function 'gsub'
        stdin:1: in main chunk
        [C]: in ?
> return string.gsub("false true", false, "")
stdin:1: bad argument #2 to 'gsub' (string expected, got boolean)
stack traceback:
        [C]: in function 'gsub'
        stdin:1: in main chunk
        [C]: in ?
>
```

Are you sure? Also not sure what you mean by not overriding upper?

**Comment by Vexatos** [comment]
Can confirm; the behaviour @fnuecke observed occurs on Lua 5.3.1 as well.

**Comment by asiekierka** [comment]
Try numeric inputs.

```
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
> =string.gsub("f23", 2, 4)
f43 1
> 
```

**Comment by fnuecke** [comment]
Ah, so it's a numbers thing. Blergh.
