### ISSUE TITLE
[1.10.2] [1.6.0.3-rc.1] Error running class transformer

### ISSUE THREAD

**Issue by Alaberti** [MightyPirates/OpenComputers#2000]
Log: https://gist.github.com/Alaberti/ebd3a5d00b5835649b0806c1813ed6b3

I wish I knew what the key phrase in these logs was.

**Comment by payonel** [comment]
congrats on getting issue #2000 btw! \o/
// balloons fall
// sirens go off

**Comment by Vexatos** [comment]
:balloon: :balloon: :balloon: 
:tada: :tada: :tada: 
:mega: :mega: :mega:

**Comment by weeryan17** [comment]
I have the same issue and from the looks of it it has something to do with ender io being installed based on the crash i get any time I try to open a opencomputers gui. for the sake of him seeing the crash as well here you go:
http://pastebin.com/h1awfBcJ

**Comment by weeryan17** [comment]
I get the same issue. sadly i myself haven't been able to track it down yet.

**Comment by AffeAli** [comment]
I think my [pull request](https://github.com/MightyPirates/OpenComputers/pull/2004) fixes the problem.

**Comment by fnuecke** [comment]
Thanks. I always miss a spot... the perils of ASM.
