### ISSUE TITLE
"No inventory" when accessing computer cases

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#2003]
Tried with a transposer and a robot with inventory controller, both just say "no inventory" when I try to access an OC case (to swap out EEPROMs). Is this intended?

OC Version 1.6.0.67-dev, MC Version 1.9.4, Forge Version 12.17.0.1976

**Comment by gjgfuj** [comment]
I know I've used the inventory controller on an oc case before.

**Comment by fnuecke** [comment]
Have you tried with non-creative tier cases? Because those require the player to be in creative mode, and the fake player isn't.
