### ISSUE TITLE
I know this isn't the right place for this...

### ISSUE THREAD

**Issue by brisingraerowing** [MightyPirates/OpenComputers#2008]
...but I haven't gotten a response on the forums (I posted Jul 20), and my computer, for some reason, hates IRC (never could get ANY client working. Random crashes galore!).

I was wondering about getting an @OpenPrograms repo set up to share some of the stuff I am writing for OC.

**Comment by Vexatos** [comment]
1) No, this is not the right place, the forums and IRC are the correct places to ask.
2) I sent you a message on the forums over a month ago, On July 6.
