### ISSUE TITLE
error()

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2009]
which stores the source code error function?

**Comment by dgelessus** [comment]
`error` is a standard Lua function implemented in C. If you really want to see its source code, look [here](https://github.com/lua/lua/blob/master/src/lbaselib.c#L102).

But if I were to guess you are actually having a different problem or question. We might be able to help you better if you ask your main question directly. `:)`

**Comment by ghost** [comment]
The fact that I wanted to customize the error screen (blue screen), but have not found anything to change it. :(

**Comment by dgelessus** [comment]
Ah, that's somewhere in `machine.lua` I think, which is the computer BIOS. This is even lower-level than the EEPROM, so you cannot replace the actual blue screen code, though you could write a custom `init.lua` or EEPROM that executes all further Lua code using `pcall` to catch errors, and display a custom error screen if an error happens.

**Comment by ghost** [comment]
Thank you and good luck! :)
