### ISSUE TITLE
error in class transformer

### ISSUE THREAD

**Issue by Dragonfire300** [MightyPirates/OpenComputers#2013]
When opening a world OpenComputers prints to the chat:

`[09:27:55] [Client thread/INFO]: [CHAT] §aOpenComputers§f: There were §cerrors§f running the class transformer. Please report this, together with your (full!) FML §alatest.log§f/§afml-server-latest.log§f logfile, thank you!`

This happens with only `OpenComputers 1.6.0.3-rc.1`, `OpenComputers (Core)`, `Minecraft Forge 12.18.1.2050`,`Forge Modloader 8.0.99.99` and `MC Coder Pack 9.19` installed, but also with other (power providing) mods installed.

MC Version 1.10.2
Installed using Curse Client

[latest.log](http://pastebin.com/tzMXVfdY)

[fml-client-latest.log](http://pastebin.com/MbGR0qv8)

**Comment by fnuecke** [comment]
Same as  #1998.
