### ISSUE TITLE
Errors runnig the class transformer

### ISSUE THREAD

**Issue by AndCriS** [MightyPirates/OpenComputers#2014]
Just installed this today (OpenComputers-MC1.10.2-1.6.0.3-rc.1) and when opening a new world it comes up with error.

[latest](http://pastebin.com/HZ8heWmm)

[fml-client-latest](https://paste.ee/p/C7sGh)

**Comment by Alaberti** [comment]
Also having this problem (again) - however, mine didn't occur until I added Mekanism for 1.10.2. Same version of OC.

Log: https://gist.github.com/Alaberti/c5a4f2f3ae0496de2c754b50d88cdc1a

**Comment by BlackEagle007** [comment]
Every Time i join the server i get noticed to report of course errors running the class transformer:

OpenComputers-MC1.10.2-1.6.0.3-rc.1
[latest](https://dl.dropboxusercontent.com/u/5370999/CrazyCrafters/CrazyTechCC/latest.log)

[fml-server-latest](https://dl.dropboxusercontent.com/u/5370999/CrazyCrafters/CrazyTechCC/fml-server-latest.log)

**Comment by HendrikJ79** [comment]
Also having this problem in Singleplayer (not tested on a server)

OpenComputers-MC1.10.2-1.6.0.3-rc.1
[latest](https://gist.github.com/HendrikJ79/413df6fda85a3b48296bb1b414896e49)

**Comment by utoc** [comment]
Also having this issue

fml-client-latest: https://gist.github.com/utoc/09f79ed5e9ac4b248c4c1d507c205cdb
latest: https://gist.github.com/utoc/c561caabcfdf80ee7c01b1b6683232c3

Running FML 2073, OpenComputers 1.6.0.3-rc.1

**Comment by fnuecke** [comment]
Partially same as #1998.

```
[10:34:30] [Client thread/WARN] [OpenComputers/OpenComputers]: Missing implementations for interface mekanism.api.IMekWrench, skipping injection.
[10:34:30] [Client thread/WARN] [OpenComputers/OpenComputers]: Missing implementation of canUseWrench(Lnet/minecraft/item/ItemStack;Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/util/math/BlockPos;)Z
```

Will fix.
