### ISSUE TITLE
Computer Case Problem

### ISSUE THREAD

**Issue by jackiedorland** [MightyPirates/OpenComputers#2017]
Hi! I have a problem with the Creative computer case/ any other Computer case! So, what happened is any time i open the GUI for the cases, Minecraft would crash. Always, i have my crash log here:

**---LOG---**
Also btw i am using MultiMC
http://paste.ee/p/nkfep

This is getting really anoyying! I need help! Thx - JackHydra

**Comment by Thurii** [comment]
Try updating JEI

**Comment by jackiedorland** [comment]
This is the newest version i believe.

**Comment by jackiedorland** [comment]
(of JEI)

**Comment by Thurii** [comment]
The latest release version is 242. You're using 221.

**Comment by jackiedorland** [comment]
oh
Is it for 1.10.2 MC?

**Comment by Thurii** [comment]
If you go to the [download page](https://minecraft.curseforge.com/projects/just-enough-items-jei/files/2322707) it will show you what versions are supported.

**Comment by ghost** [comment]
I was also having this error, for some reason Curse installed JEI version 219.  Upgrading to 244 resolved the issue.
