### ISSUE TITLE
Massive Memory Storage

### ISSUE THREAD

**Issue by TheHIV44** [MightyPirates/OpenComputers#202]
A Way To Get A Massive Amount Of Memory Storage With Open Computers Would Be To Use A Black Hole/Singularity To Store And Infinite Amound Of Memory Within The Event Horizon Of The Black Hole/Singularity But Also Being Highly Expensive To Make The Device To First Make The Black Hole/Singularity And Hold It Open While Also Canceling The Gravitational Effects

**Comment by fnuecke** [comment]
Thanks for the suggestion, but I don't see that happening. Also, capitalizing every word makes your text incredibly hard to read... please don't.
