### ISSUE TITLE
Nanomachines getName() crashes minecraft

### ISSUE THREAD

**Issue by Itggot-Lucas-Glimfjord** [MightyPirates/OpenComputers#2021]
Minecraft crashes every time the nanomachines receive the getName command

**Comment by xarses** [comment]
Please provide version information

**Comment by Itggot-Lucas-Glimfjord** [comment]
I'm using 1.6.0.3-rc.1

**Comment by fnuecke** [comment]
Can't reproduce, crash log please.

**Comment by Vexatos** [comment]
Duplicate of the (more recent) #2220 and fixed via https://github.com/MightyPirates/OpenComputers/commit/52a032ff63aea6ada292da1a47ec8caa958521f6.
