### ISSUE TITLE
robot.compareFluidDown() returns false when it should return true.

### ISSUE THREAD

**Issue by IsaacWorkman** [MightyPirates/OpenComputers#2023]
I'm using robot.compareFluidDown() to make sure the liquid below the robot is the same as in its tank before sucking it up. When a lava source block is below the robot, and a bucket of lava is in the robots tank, robot.compareFluidDown() seems to be returning false rather than true.

Additionally, robot.detectDown() seems to return "replaceable" rather than "liquid".

This isn't a problem when run from the lua prompt, only during my programs. I'm not sure what is causing it.

Running the command several times (Such as in a loop that exits once it returns true) will work some of the time, but it unreliable at best. I believe this error may be related to #2015, but i can't be certain.

**Comment by Vexatos** [comment]
Pretty sure the robot needs a tank upgrade to get an internal tank, and `compareFluid` then compares to the fluid in that tank. It is completely unrelated to buckets in the robot's item inventory as that requires an Inventory upgrade.

**Comment by IsaacWorkman** [comment]
Oops, I meant to say a bucket of lava was in the robot's _tank_ not inventory! As in, 1000 mB, not 1 item bucket.

I've edited to original post.
