### ISSUE TITLE
[1.10.2]Error running class transformer

### ISSUE THREAD

**Issue by dsmall3303** [MightyPirates/OpenComputers#2025]
Upon launching a brand new 1.10.2 pack, I received a message asking me to submit the message saying that there were errors running the class transformer along with the latest.log file:

[latest.zip](https://github.com/MightyPirates/OpenComputers/files/421769/latest.zip)

**Comment by Aeronica** [comment]
I'll add my fml-client latest too.
http://pastebin.com/rtuVucui

**Comment by fnuecke** [comment]
Same as #1998.
