### ISSUE TITLE
errors running class transformer

### ISSUE THREAD

**Issue by atsbusinessandgames** [MightyPirates/OpenComputers#2027]
Here is the [fml-client-latest.txt](https://github.com/MightyPirates/OpenComputers/files/424101/fml-client-latest.txt) as requested (renamed to be a .txt file so I could uplaod it).

**Comment by 7OOTnegaTerces** [comment]
I had the same error.  My issue was fixed by updating to this OC build: http://ci.cil.li/job/OpenComputers-dev-MC1.10/lastSuccessfulBuild/artifact/build/libs/OpenComputers-MC1.10.2-1.6.0.31-dev.jar

**Comment by fnuecke** [comment]
Same as #1998.
