### ISSUE TITLE
IP Address blacklist doesn't include IPv6-based local addresses.

### ISSUE THREAD

**Issue by LizzyTrickster** [MightyPirates/OpenComputers#2029]
Pointed out by Miyoyo in the IRC channel, IPv6 based local addresses are not in the blacklist as he was able to run `lua component.internet.connect("[::1]",80)` successfully.

While not all hosts will have IPv6 internet connectivity, it will still most likely be present on the host OS and thus could still be used. I can submit a PR adding IPv6 local addresses in if needed, just unsure of how to write them (my guess would be like [::1])

https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/application.conf#L937

**Comment by xarses** [comment]
Oh, ya we should block the ipv6 loop back all semi-recent network stacks will result in there being one, and would result in exposing localhost by default. I guess the local unicast range `FC00::/7` There aren't any RFC1918 similar network spaces besides the local unicast so ipv6 users would have to explicitly block their local networks if that's something they want to do. 

for the address match it should match with out brackets (I've no idea where those came from). and to be specific, we should include the mask `::1/128`

**Comment by LizzyTrickster** [comment]
hmm, looking at the code (to see if i could PR it in), it seems that [this line](https://github.com/LizzyTrickster/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/Settings.scala#L585) would need to be changed to allow for matching the IPv6 addresses as well as the lines of logic underneath it. I can't do this as I don't know Scala and can only just work out what it's doing

**Comment by skyem123** [comment]
The square brackets are because the : could get confused with the port thing.
