### ISSUE TITLE
[Request] Potential, Actually Doable Solution to Complaining about Lack of Python

### ISSUE THREAD

**Issue by Ratione** [MightyPirates/OpenComputers#2030]
Could we get a sticky Pointing people to either
- [Lunatic Python](https://labix.org/lunatic-python) or 
- [MCPiAPI](https://github.com/kbsriram/mcpiapi) w/ instructions to use the command block attachment?

Both of these solutions allow people to code in python using OpenComputers, and it might stop the incessant bitching, followed by complete lack of research. Just Thought it might be helpful.

**Comment by xarses** [comment]
Lunatic might by the only option this is truly a requirement, but I don't see how we could include it any python parser with out significantly complicating everything, ie lots of duplicate code paths, that many probably don't care to support. An option may be to replace the parser entirely with lunatic, but in either case, we would have to work out how to run it in java (pure lua was easier because it's been done many times before). Also, we'd need to work out how to adapt the execution safeties that fnuecke has given us that make the current implementation awesome.

As a multi-lingual programmer that prefers Python, My general response here is learn Lua, its easy enough, and very common dynamic language in games and regardless you're a better programmer for knowing multiple languages.

**Comment by Ratione** [comment]
I don't disagree with your point, but i don't get the impression that people who are making those comments are far enough along for that to a nontrivial task.

I was looking out of curiosity/laziness, and I am a "multi-lingual programmer that prefers Python" as-well, and that really screws with the motivation to continue a project. I was not against learning Lua, and since have been, but that can be the difference between someone learning to program and not...

Many of the resources i had looked in to simply told people, in varying degrees of niceness, to either learn lua, or f**\* off. I simply think that it's better to point people in the direction of a semi-solution, instead of simply telling them it's not possible, not that i suggest that you specifically are doing that. 

In my experience, OpenComputers/ComputerCraft and MinePi are fairly commonly used to learn programming for the first time. If the overall thought process is "More Programmers = More Cool Stuff", I don't think it would be bad to point them in that direction, especially if we added the caveat that some stuff will not work and we don't support it.

**Comment by payonel** [comment]
@Ratione opencomputers indeed tries to not restrict users from experimenting with custom environments and custom archs. We definitely are "lua out of the box", but to contrast us from the other similar mods I would say opencomputers is more **encouraging** of alternative solutions. May I simply point to [OCMIPS](https://github.com/iamgreaser/ocmips) as a great example.

I'm definitely not going to police or babysit the internet :) that said, where there are instances of mature sincerity and effort being met with flippant and explicit disregard, that is NOT what opencomputers stands for nor promotes.

Now, to your question about "getting a sticky" -- I honestly recommend you write a how-to or a what-is-available page on our wiki: http://ocdoc.cil.li/ -- seriously, please do. Then in the future, any python related questions will allow us to redirect users there, to your page. When you've finished the wiki page, feel free to insert a link to it in this issue, and close this issue.

Thanks!

**Comment by Ratione** [comment]
@payonel Lol. Ill see what i can do. I'll play around with it and see if i can get something semi-stable up and running. If i do, ill gladly write a how-to

**Comment by dgelessus** [comment]
@Ratione Do any of these actually run Python in a way that is reasonably useful for OC? Lunatic Python is a bridge between Python and Lua written in C, and MCPiAPI's `/py` command only invokes the system's default `python` binary. I don't see how these are useful in bringing Python to OC. If anyone were to write a Python arch for OC, it would be much easier to use CPython or Jython as a base and drop Lua entirely.

**Comment by Ratione** [comment]
@dgelessus MCPiAPI adds a way to implement a variety of changes using python code, and OpenComputers has a Command Block attachment. At a basic level, OC already allows for people to write programs in python to do stuff in game, but that only has basic functionality.

As for Lunatic Python, I suggested that because it provides another direction to go, if someone was looking something along these lines. It may be possible, for instance, for someone to create a python interpreter in lua that can work on the existing OS, but regardless, it gives another place to go to. It stops the idea from ending at "It cant be done at your level"

But that goes back to my previous point about values and crap.

**Comment by fnuecke** [comment]
There are no stickies on Github, so yeah, a well written page in the wiki, and possibly on the forums (or referencing the page from the forums) would be the best.

**Comment by Martmists-GH** [comment]
For those still interested, there is an [effort underway](https://GitHub.com/hargoniX/OC-Jython) to add Jython 2.7.1 as Architecture.
