### ISSUE TITLE
[Feature Request]: parking drones

### ISSUE THREAD

**Issue by MalkContent** [MightyPirates/OpenComputers#2032]
Basically just a an animation that parks drones against a neighboring surface (floor/ceiling/walls), when drone.park(side) is called.
And i guess it could lower passive powerdrain a bit because it doesn't need to hover anymore, but who cares :D
Oh, maybe it could be a requirement to park against charging stations rather than just fly next to it to get charged.
Idk, I just want to have drones at the wall tbh ^^

**Comment by S0ZDATEL** [comment]
You may need a special drone-port. On it the drone can be charged. And another cool idea - the drone can communicate with all components connected to the drone-port. Imagine - flies drone, parked on the drone-port, and receives control over some mechanism (a monitor or code lock). It's cool!
