### ISSUE TITLE
[Feature request] IDE with completion and color

### ISSUE THREAD

**Issue by Zethalion** [MightyPirates/OpenComputers#2033]
I'd like to see an IDE which both has code completion and highlighting. Lua does code completion, the shell does completing commands. The shell uses nice colors. Can these things be combined into an editor in-game so for novices like me can get a jump start programming Lua? A second window with an instance of the Lua interpreter at the bottom of the screen would be the best addition to test code like they did it in old school qbasic ;)

**Comment by LizzyTrickster** [comment]
This kind of request would probably be best suited for the forums

**Comment by Zethalion** [comment]
Ah, I assumed this is the place for a request.
As Sangar wrote:

> Please make sure your idea has not been submitted on Github before, when posting suggestions for OpenComputers itself here. In general, prefer to make feature requests for OpenComputers over on Github, unless the idea is still pretty vague and has room for a lot more discussion. Thanks! 
> https://oc.cil.li/index.php?/topic/3-feature-requests-for-opencomputers/

Should I repost on the forum anyway?

**Comment by xarses** [comment]
While this request has merit, constructing an IDE is quite difficult, we can't easily merge the two together and get anything that would result in an improvement. We've discussed some lighter enhancements to get `edit` a bit beyond the intelligence of notepad (and closer to `vi`), but that's about where it is.

On top of that, the processing power in MC is weak as compared to what most modern IDE's require to do many of the basic functions you would expect from an IDE

If your looking for a IDE experience Now, it would probably be more effective for you to do this on your local system than in MC. There are some ways to work this way:
- In SP you can edit the lua files directly on disk
- You can `wget`, `pastebin`, or simply paste smaller programs into the terminal
- You can build a package in a git repo and install it with  [oppm](http://ocdoc.cil.li/tutorial:program:oppm)
- You could write a remote executor (like many do for [drones](https://gist.github.com/fnuecke/6bcbd66910b946b54ec7) in game) and then set it up so you can send code/commands over TCP from your desktop to the computer/drone/robot in game.

**Comment by Zethalion** [comment]
Thank you for this elaborate answer. It wouldn't matter to me if it it in-game or on the desktop. I know how to get code to game. I understand what I asked is not something small in any way but if not possible inside the mod, is there any desktop IDE that can be configured like OC Lua with code completion and/or highlighting? It would be an extremely useful tool to get people coding for OC. 

Something like an add-on for np++ or similar and option as an alternative maybe? I'm afraid I'm too much a novice to make something like this yet.

**Comment by MyNameIsKodos** [comment]
ComputerCraft had something like this a long time ago. I have no idea how long it's been since it's been touched, but iirc it was called LuaIDE and it was written by GravityScore. You could probably go poke around on the OC forums and see if anyone would be interested in porting it.

Original source for LuaIDE can be found [here](https://pastebin.com/vyAZc6tJ)

**Comment by Zethalion** [comment]
Thanks for the link. I'll try to port myself as a good exercise and if I need help, I'll try to post it on the forum and ask for help there.

**Comment by magik6k** [comment]
There is also web IDE called mpt: https://oc.cil.li/index.php?/topic/92-mpt-minecraft-packaging-tool/

**Comment by DarianLStephens** [comment]
> Thanks for the link. I'll try to port myself as a good exercise and if I need help, I'll try to post it on the forum and ask for help there.

I know this was... absolute _ages_ ago, but was there ever any progress on this?
I've just started using OC over CC, and I am seriously missing the basic things like highlighting, autocomplete, and auto-indent.
