### ISSUE TITLE
[1.10.2] Incorrect color/lighting on 3D printed blocks.

### ISSUE THREAD

**Issue by VermillionX** [MightyPirates/OpenComputers#2034]
All 3D-printed blocks all appear darker on the sides. It seems to be applying shading from the bottom to the sides, but not to the top of blocks. it makes it impossible to blend 3D printed blocks with normal blocks.
Seen below is the source block (small sandstone tiles from Chisel) on either side of a 3D-printed block using the same texture.
![2016-08-24_18 52 04](https://cloud.githubusercontent.com/assets/10645298/17921137/9469ddf0-6a2c-11e6-81d3-4ffe17a0da59.png)

**Comment by fnuecke** [comment]
Versions?

**Comment by VermillionX** [comment]
OpenComputers-MC1.10.2-1.6.0.3-rc.1 You know? Because there's no other version for 1.10.2

Additional problem with 3D printed blocks: Slab-shaped blocks with collisions turned off causes the block to be unbreakable. Any attempts to remove the printed slabs simply go right through it and hit the ground beneath, like trying to punch a water block.
