### ISSUE TITLE
[Maybe non-issue] Experience upgrade can  .consume() when at max level

### ISSUE THREAD

**Issue by MalkContent** [MightyPirates/OpenComputers#2035]
Might be intentional or "uhhh... not a bug, but a feature!", but my thoughts were that it might just not consume the item then and return false when at max level.
Also: experience upgrade returns the result (Unit, "<error message>") for other "can't consume" cases and Unit appears to be always nil. Might be me being stupid, but maybe that should just be a false instead of Unit.

**Comment by fnuecke** [comment]
Yeah, Unit is equivalent to null is equivalent to nil. And Lua convention is to return `nil, error_message`, so at least that part is as it should be. The overachieving part is... suboptimal, true :P

**Comment by MalkContent** [comment]
i think i only complained about the return being nil instead of false because it returned true if it was successful
would have to check

**Comment by fnuecke** [comment]
Hmm, in that case I suppose one could argue that it should be false, agreed. But in an if Lua treats them the same anyway, so eh.

**Comment by MalkContent** [comment]
~~true~~ not nil :)
