### ISSUE TITLE
Create FUSE Card

### ISSUE THREAD

**Issue by gudenau** [MightyPirates/OpenComputers#2037]
I would like to have a FUSE system in OpenComputers, it could create some very interesting capabilities. Remote file access, encrypted drives, etc.

(FUSE: Filesystem in userspace)

**Comment by payonel** [comment]
We wouldn't need a hardware device (a card) to do this, it can be done entirely in user space (just as you say). You can write a custom filesystem and mount it via require("filesystem").mount(obj, path) see http://ocdoc.cil.li/api:filesystem

By the way, this is how the dev filesystem works, it is a virtual filesystem that runs entirely in memory and handles filesystem events dynamically to do special operations. It mounts at boot via https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/openos/boot/10_devfs.lua, and runs the devfs library code when used: https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/openos/lib/devfs.lua

Also, I just published the beta version of my oppm project "psh" (just `oppm install psh`) It is inspired by ssh, but psh for payo, and there is no encryption. But you login to remote machines (full shell, or just run remote commands) and psh comes bundled with `pcp` (name inspired by scp) for copying files [at the time of  this writing `pcp` is still wip and `psh` is definitely beta).

This would be a good project for oppm, It is out of scope for openos.

**Comment by gudenau** [comment]
Oh, good to know! From how the documentation that I read it looked like there needed to be a hardware backed device.

Would be cool to have a disket added with my implemintation!

**Comment by payonel** [comment]
@gudenau a fun way to test out what is needed is to use this test code

```
local my_fs = setmetatable({},
{
  __index=function(tbl, key)
    error("need implementation for: " .. key)
  end
})
require("filesystem").mount(my_fs, "/tmp/my_fs")

```

And then go try to use your new directory.

**Comment by gudenau** [comment]
Away from home for now, thanks!
