### ISSUE TITLE
IC2 integration: reactor components no longer use damage/maxDamage

### ISSUE THREAD

**Issue by WazWaz** [MightyPirates/OpenComputers#2039]
It appears the IC2 reactor items (eg. fuel rods) no longer use standard damage/maxDamage to store their decay state. Not really an OC bug (other items appear to work fine), but makes it hard to make a useful OC reactor controller. Perhaps the Reactor could have an accessor for this? Or ConverterItemStack could handle it magically?

IC2 industrialcraft-2-2.6.37-ex110
OC OpenComputers-MC1.10.2-1.6.0.3-rc.1

**Comment by payonel** [comment]
I can provide the damage, but not the max damage
you might have to create a mapping using the itemStack name and known max damage
