### ISSUE TITLE
Portable computer.

### ISSUE THREAD

**Issue by ruifung** [MightyPirates/OpenComputers#204]
Something like maybe a "laptop" computer or a tablet computer in item format for portable usage, this would fill a similar role as the "pocket computer" from computercraft.

**Comment by Vexatos** [comment]
Well, it should still be a block, just portable, so you have 1 item to place down, access, and break again.

**Comment by ruifung** [comment]
why a block? I like the concept of having a item computer with a built in wireless card.

**Comment by MaHuJa** [comment]
And a floppy drive; my headless controllers will log stuff including errors to a file on the disk, which I then have to bring to a full computer. I'd be willing to choose between floppy and wireless.

There are a few factors that make computercraft hard to actually replace (as in, removing it entirely), and this will be one of them.

**Comment by Techokami** [comment]
Well, what about using a server with a remote terminal? This effectively gives you something akin to a Pocket Computer, though you are limited to a certain range.

**Comment by ruifung** [comment]
Thats the problem, range.

**Comment by ktole1999** [comment]
what about a wireless tower. Based on height would determine coverage. 7 block tower would give a 7 block radius, etc.

**Comment by ruifung** [comment]
Uh huh, would still be nice to have a standalone portable computer item. For remote control on the fly or other things.

**Comment by fnuecke** [comment]
I've been thinking of making access points act as relays for remote terminals for a while now, but it's not trivial. That might relax the distance issue to a degree where it doesn't matter anymore, though?

**Comment by ruifung** [comment]
just an idea that i had: A "quantum entanglement" relay that is created in pairs, and works cross dimension as a point to point relay... hmm..just an idea.

**Comment by Wuerfel21** [comment]
Maybe a laptop-thing which you can open and close with shift-click, when open you could open the gui with screen and stuff, and when closed you can right-click to take it with you. when closed or in an inventory it should enter standby-mode(only if it is on(duh)), in which it will stop execution, but persist and consume a small amount of energy from its internal battery (which it could recharge from ic2 solar helmets and such). Those laptops should be more expansive than a computer and have less slots(aka only 1 RAM slot for tier 1 and so on(But an integrated floppy drive)), and should compatible with some robot upgrades(like orientation or solar), and to interface to external components you need to place the laptop on a laptop-dock(which also charges the laptop). Also we should have a graphing calculator-like thing(i have one at home, they are so useful), which never interface to external components(an item), but have an internal memory which is half the size of a floppy which is interfaceable to external computers using a calculator-adapter-block.Also a calculator could have another memory only writeable using the calc-adapter that is just the size of a floppy and the place where the os should go. tier 1 + tier 2 should have 1-bit inverted(FFFFFF is black) screens while tier 3 could have a 16-color one(all without mouse). All screen s should have a 2:1 resolution(like a real one). Also calculators have an internal battery which they consume veeeeerrryyy sloooooow. Thats how i would do it!So a last comparsion:
Laptop vs. Calc
only works when placed vs. works as an item in inventory
connects to networks using a dock vs. not able to connect to networks other than wireless ones(maybe only tier 3)

so no win-win- situations here, would love to see this implemented

**Comment by Vexatos** [comment]
@Wuerfel21 The robot assembling station thingie coming to OC 1.3 could also be used to assemble a laptop with all the modules you want it to have.

**Comment by Wuerfel21** [comment]
Good idea! maybe the calc too?

**Comment by fnuecke** [comment]
Hmm, abusing the robot assembler for something like this sounds interesting. It'd need a few adjustments, though, such as a mode switch and whatnot...

**Comment by Wuerfel21** [comment]
Maybe like stevescarts: insert different cases andthe  other slots appear

**Comment by fnuecke** [comment]
Hmm, basically craft a 'laptop case' from a computer case or so and use that? Yeah, that might work.

**Comment by evg-zhabotinsky** [comment]
Well, I think laptops and robots can share almost all their slots. Some upgrades make sense both for robots and laptops. The main difference is that laptop definitely needs to be assembled with a proper display, while assembling robots with some kind of mechanical chassis makes much more sense. Maybe this "extra slot" could define what you are going to assemble?

**Comment by LordFokas** [comment]
following @evg-zhabotinsky's logic, it could be a chassis slot, where the laptop chassis has an integrated screen (maybe make it a part of the crafting process?)

**Comment by Wuerfel21** [comment]
Laptop needs integrated keyboooaaarrd

**Comment by Techokami** [comment]
Wouldn't that be part of the Laptop Case anyway?

**Comment by Wuerfel21** [comment]
Flashing idea: assemble a laptop without a keyboard and you get a tablet pc

**Comment by fnuecke** [comment]
Tablets (without keyboard) were actually what I had in mind originally. Might still make it in, in a directly-craftable fashion (as opposed to laptops, if you can call them). Laptop cases would probably have the screen+keyboard built-in though, yes.

**Comment by evg-zhabotinsky** [comment]
How about that:
Screen and keyboard are upgrades (as with robots, but all tiers of screens).
Got them both? You've got a laptop!
No keyboard? You've got a tablet!
No screen? As of now I see it only as a RFID-like key or a portable beacon but in future it might serve as a portable data logger / controller for terminal glasses (#293) / etc. (one needs to be creative though :)
Also, why robot should be a special case? It is also a portable computer. It just moves on its own.
Mechanical chassis might be a special upgrade that turns just a portable computer into robot. (As special as screen and keyboard are - not hot-swappable)
Inventory-related and maybe some other upgrades should not work without chassis.

**Comment by MatthewSmit** [comment]
Personally I just use the remote terminal as my laptop. I only have one base with computer stuff in it, so range hasn't been an issue yet. I would love for this to be implemented though.

**Comment by asiekierka** [comment]
Sangar seems to have started working on an API to allow custom devices for the Robot Assembler (now the Computer Assembler). I wish to work on Portable Computers once this change and the CPU architecture/I/O controller changes are in.

**Comment by fnuecke** [comment]
Indeed. I started [writing down some ideas](https://gist.github.com/fnuecke/d43359d885c262af4220) for anyone else interested in this.

As for the portable computers themselves, I'm strongly leaning to only add something like 'tablets', which e.g. would not be able to have a keyboard, very low complexity limits, these kinds of limitations. Meaning quite a bit more limited than the testing one in the dev builds. There are still some other things I'll need to fix in the current prototype for those to be 'production ready', though (e.g. battery / internal power, some bugs with components not being properly cleaned up when the item is destroyed).

**Comment by Techokami** [comment]
fffff, no keyboard, that's going to be interesting. A fork of OpenOS that's more touch-friendly with an on-screen touch keyboard? Otherwise, someone is going to need to make a GUI that runs on top of OpenOS.

**Comment by asiekierka** [comment]
There is a testing one in the dev builds?

Also, the tablet idea is neat. Very neat.

**Comment by Techokami** [comment]
@asiekierka Yeah, creative only. The testing tablet acts more like the portable computer from ComputerCraft.

**Comment by XDjackieXD** [comment]
Maybe also make the tablet rotateable (portrait - landscape) with shift right click or something?
Would be neat because working with an on-screen keyboard is better in portrait and some gui programs are better in landscape...

**Comment by fnuecke** [comment]
@XDjackieXD I think that would best be achieved by adjusting the resolution accordingly, so it'd be done via software.

**Comment by XDjackieXD** [comment]
derp... why easy if you can make it complicated? :D

**Comment by Wuerfel21** [comment]
can't find it in the latest dev build

**Comment by Techokami** [comment]
@Wuerfel21 Should be enabled in the latest dev build. You need to use Creative Mode to get it.

**Comment by fnuecke** [comment]
It actually wasn't in the recent dev builds because when merging the patches from the stable branch back into the dev branch that also applied the disabling of it (don't want it in the stable). Re-enabled it, get latest build.

**Comment by Wuerfel21** [comment]
lol, that build faild...
EDIT: Console complains about 403 errors...

**Comment by fnuecke** [comment]
[Yes](https://github.com/MinecraftForge/ForgeGradle/issues/129).

**Comment by Wuerfel21** [comment]
The tablet should have wireless netorking and internet on-board

**Comment by fnuecke** [comment]
Tablets should be pretty much complete in the latest dev builds (testing/bugfixing excluded), so I'm closing this.

They now consume energy and can be charged by placing them in the Charger, and their first hard drive can be accessed when they are placed into a Disk Drive.

As a final remark, I've decided to allow assembling tablets with keyboards for now, since I feel it would lower the usability too much for now (there are hardly any GUI-driven "OSes" at this point). It will consume one of the three upgrade slots, which still leaves some incentive to build purely mouse driven applications, freeing up the last slot for some upgrade.

Also, some upgrades will not work / have no effect when built into a tablet. I couldn't come up with a solution that I liked for marking upgrades as tablet-usable in a generic enough fashion, so that's somewhat left to common sense and / or trial and error for now.
