### ISSUE TITLE
Requested to report Bug (Error running class transformer)

### ISSUE THREAD

**Issue by Marenthyu** [MightyPirates/OpenComputers#2042]
The Chat requested me to report this error as "There were errors running the class transformer."
While i can not find the fml-server-latest.log (as this happened on a local world), here are the logs that i could grab that should be relevant: http://puu.sh/qSoqG/c0acf67fb0.zip

additionally, in case it helps, here's the FTB console's log: http://paste.feed-the-beast.com/view/5b74db06

http://puu.sh/qSouq/6fc4d804ef.png

This occured After i loaded up a newly generated Singleplayer world after having joined a server which stopped responding so i disconnected and it wasn't reachable anymore.

I'm sorry if this a useless report, but i hope it still helps.

**Comment by Marenthyu** [comment]
Additional info:
FTB Unstable 1.10 version 4.2.6 (not the latest, 1 version behind as of posting this)

**Comment by Marenthyu** [comment]
--- This is a duplicate of #2025 #2026 and #2027 ---

**Comment by Ozzymud** [comment]
And here is one from a modified PineFresh pack on 1.10.2 ... just updated all mods in the log to latest. There were block errors I deleted from the log and a lot of other "extra lines" that didn't look important, such as forge griping about case in mod ids.. commented in between 1st/last lines where I made deletions... it was over 512kb pastebin limit.

http://pastebin.com/5kvKFqm8

**Comment by 7OOTnegaTerces** [comment]
I had the same error.  My issue was fixed by updating to this OC build: http://ci.cil.li/job/OpenComputers-dev-MC1.10/lastSuccessfulBuild/artifact/build/libs/OpenComputers-MC1.10.2-1.6.0.31-dev.jar

**Comment by fnuecke** [comment]
And of #1998. Thanks anyway.
