### ISSUE TITLE
[Suggestion] NFC Card/Block for Drones

### ISSUE THREAD

**Issue by Chaz-Targrin** [MightyPirates/OpenComputers#2043]
I am not 100% sure if this function is already available in some other form, but I'd like to see some alternate way of allowing a computer to send commands to a drone without requiring it to have a Wireless Modem.

Here's the trouble I'm having:
I want to have a drone that can travel to a waypoint, and drop an item in its inventory - basically a delivery drone that can use waypoints to determine where it needs to drop stuff. 

The catch is that with a Navigation Upgrade that has a big enough map, this means I run the risk of a drone flying into an unloaded chunk and maybe getting lost. To that end, I'd need to have: a wireless modem, an Inventory upgrade (so it can carry and drop stuff), a Navigation Upgrade (so it can use Waypoints) and a Chunk Loader upgrade (so it can keep the chunk it's in loaded if it travels over a long distance). Unfortunately, even with just one RAM stick this brings the complexity of the drone up to 9, which is just slightly over the Tier 2 drone case's limit.

The solution I can think of would be to have a means of sending commands to a drone without requiring a Wireless modem - For that reason, I was wondering how viable it'd be to include Near Field Communications (NFC) in some format, consisting of either:
- An NFC Block, which acts like a Charger but can allow a drone or robot that's being charged to be sent commands, or my favourite idea,
- Linked NFC Cards. Similar to Linked Cards, but they only allow communication when the objects they're in are adjacent to each other - So a Computer and a Robot, or a Drone and a Microcontroller, or any combination thereof. These could be a lower tier/complexity than Wireless cards, and maybe more energy efficient.

Using this you could turn a Microcontroller into a docking bay, and there'd be a challenge in writing a drone program that tells the drone to go to a particular waypoint and then return to the NFC dock to receive its next command.

**Comment by fnuecke** [comment]
I could've sworn there was something similar in an addon mod, but I can't remember which.

**Comment by magik6k** [comment]
Zetta Industries adds NFC blocks, you can request that kind of thing to be added there. https://github.com/marcin212/Zetta-Industries
