### ISSUE TITLE
3d printer - not more than 3 slabs fit into a single block space

### ISSUE THREAD

**Issue by rahangar** [MightyPirates/OpenComputers#2044]
![2016-08-30_18 01 37](https://cloud.githubusercontent.com/assets/3137077/18110164/d55f7fe6-6edb-11e6-8324-8cd301fbc07c.png)

I'm trying to get at lest 6 slabs (each 1/16th of a block thick) to fit into the same block space.

These must be separate prints.  In other words, I already know I can do this via a single print.  

Sangar, in his tutorial indicated that fitting multiple blocks into the same block space should be possible as long as they don't collide.      At most I can only fit 3.   Since each slab is only 1/16 of a block thick, I don't see why I cannot fit more than 3... I should be able to fit all 16, yes?

Example of two slabs that won't fit, but should since they don't collide.

{
  label = "slab_14",
  shapes = {
    { 0,0,14,16,16,15,texture = "opencomputers:White", tint = 0x404040 },
  }
}

{
  label = "slab_15",
  shapes = {
    { 0,0,15,16,16,16,texture = "opencomputers:White", tint = 0x404040 },
  }

As the picture shows only certain combinations seem to fit into the same block space, but I haven't been able to identify a pattern.  All of these are 1/16th of a block thick, so I don't see why I can't fit more than three.   Is this a bug?  or am I doing something wrong?

**Comment by fnuecke** [comment]
From a bit of debugging, it seems the issue stems from them lying in the same slot (FMP/1.7.10 I assume?)
I'm afraid it's been too long for me to remember if that was actually necessary/what other side effects removing that might have, and I'm sorry to say I don't have the time to dig into the mess that is FMP again. If someone else could have a look at this, that'd be great.

**Comment by rahangar** [comment]
Yes - 1.7.10 - Bevo's tech pack reborn.  

What does it mean "lying in the same slot"?  Are you hinting that there might be a work-around?  

I also noticed that stacking is unpredictable.  In other words, after placing and breaking printed items, sometimes identical prints stack, and sometime they do not.

**Comment by fnuecke** [comment]
FMP has a concept of slots, which are 7 regions in a blockspace - on the faces and the center. Basically the areas you see outlined when placing microblocks. For prints the slots they fall into are computed dynamically based on their bounds. The check for the slot overlap happens somewhere inside FMP, and I don't know how to avoid that.

Edit: ah, and I think I remember what that was for, IIRC it's to make them block cables and such.
