### ISSUE TITLE
Error Running the Class transformer

### ISSUE THREAD

**Issue by z0dkc** [MightyPirates/OpenComputers#2045]
Game told me to report. I haven't tried out any OC things in my world in fear of it screwing up the save.

latest.log :
[latest.txt](https://github.com/MightyPirates/OpenComputers/files/449089/latest.txt)

**Comment by 7OOTnegaTerces** [comment]
I had the same error.  My issue was fixed by updating to this OC build: http://ci.cil.li/job/OpenComputers-dev-MC1.10/lastSuccessfulBuild/artifact/build/libs/OpenComputers-MC1.10.2-1.6.0.31-dev.jar

**Comment by fnuecke** [comment]
#1998.
