### ISSUE TITLE
[Addition/suggestion]

### ISSUE THREAD

**Issue by BenFRC5147** [MightyPirates/OpenComputers#2047]
I propose adding multiblock functionality to tier 3 computer cases, this would allow you to link multiple computer cases into one computer, adding more room for having cards. This would be useful for compact PCs and anywhere else you don't have the time to make some huge contraption for.

**Comment by xarses** [comment]
Hare you explored rack mounted servers?

**Comment by BenFRC5147** [comment]
I have, but they seem to disconnect at random intervals,

**Comment by Vexatos** [comment]
This is exactly what servers are for.
