### ISSUE TITLE
EnderIo

### ISSUE THREAD

**Issue by Eonasdan** [MightyPirates/OpenComputers#205]
Please add support for EnderIo's redstone cable (colors). It would also be really cool if the OC `cable` could be bundled with the EnderIo conduit :)

**Comment by fnuecke** [comment]
From looking at the EnderIO code real quick, it looks like they don't have an API, instead they implement conduits using the APIs of other mods. So if anything I think this request should go to the EnderIO people :-) I'd be happy to assist where necessary, of course.
