### ISSUE TITLE
Computer Shutdown on chunk unload.

### ISSUE THREAD

**Issue by nathandtrone** [MightyPirates/OpenComputers#2051]
This topic is the same as: Computer Turns off When Leaving the Chunk #1405

I've gone through the checks and done exactly what the other thread mentioned but I ended up with the same result. Is this fixed somehow or is there a fix for it I can apply?

I have it managing my nuclear reactors but I've had to restore a backup multiple times now because the computer randomly shuts off when I leave the area, and then my reactor just goes nuclear.

Thanks in advance, I'll provide any information you need, just ask.
Mod Version: [OpenComputers-MC1.10.2-1.6.0.3-rc.1]

**Comment by xarses** [comment]
As noted in #1405 There was no result, the reporter was unable to help figure out what was causing problems other than it appeared to be a problem introduced with one of the 90 mods he was using.

Steps from #1405:
- Use an analyzer (OC) on the computer to see if there was a shutdown code
- If you place a computer somewhere else in the world, leave its chunk and comeback is it off too?
- Does this happen with a creative case?
- Do the logs indicate any reason for the shutdown?
- Does it reproduce with only OC installed and no other mods?
- Lastly (lets save this for later) can you identify which mod's presence is causing this interaction?

**Comment by fnuecke** [comment]
Probably fixed with 2751cec8c1526d489976627b4ffa0d6731616ee5. If not, please reopen.
