### ISSUE TITLE
Crafting Upgrade fails at crafting metal blocks

### ISSUE THREAD

**Issue by MalkContent** [MightyPirates/OpenComputers#2054]
mc 1.8.9
forge x1902
oc 1.6.0.8-rc.1

When you fill the robots crafting area, evenly, with a fitting amount of metal ingots (so amount%9 == 0), it will craft them into blocks, except for the last set. That one it will turn into 8 ingots and 9 nuggets. You can replicate with simply 9 ingots. It's unable to craft a block from this, too.
A workaround is to limit the amount of items crafted, so maybe it in part has something to do with the amount of crafted items being higher if ingots get turned into nuggets.

I say metal blocks specifically, but this might affect other stuff, too, i suppose, though I failed to find something else. Issue affected IE metal blocks, too.

**Comment by MalkContent** [comment]
This appears to only be an issue if the robot.select() selected slot is inside the crafting grid. I'll leave this open, but feel free to close if you'd say this is intended behaviour.

**Comment by payonel** [comment]
yeah, it's intended although annoying
i'll make a note to put a warning in the docs for this

**Comment by payonel** [comment]
ah woops, no - i misread this
I haven't seen this
We have been considering a change to stop the crafting when the recipes changes
I am feeling stronger about this change now because of this ticket, I think I'll repro this and make a fix/change for 1.7.2
