### ISSUE TITLE
[Feature Request] Stationary Robots/Robot Arms

### ISSUE THREAD

**Issue by MalkContent** [MightyPirates/OpenComputers#2055]
Sometimes you only need stationary robots for inventory/tank manipulation/ore breaking (to refine itemdropping ores harvested with silktouch or similar)/animal punching/probably other things.

Right now you'd build full fledged robots for that, which require to be charged, which means a) you definitly need one charger per stationary robot (well i guess you technically could fit 5 robots, but that'd lead to fugly setups) unless you implement some "go and recharge" logic, and b) you got constant green sparkling in your factory :x

So i got these two requests (rooting for the second one to go through, but would be fine with 
1:
Allow for stationary robots that can connect to cables. Either permanently or maybe with an upgrade, so they can "park" one the cable (maybe make them rip out the wire they attached to if you forget to depark and move it). Make the necessary time for (de)parking long enoguh and it wont be a favorable option to do for a mobile robot's recharge. You know, what ever makes the sparkling stop.
2:
A robot arm as an external component, requires cable connection. No computational power on its own and has the capability of a robot component (minus movement). Probably needs inventory/tank controller upgrades inbuilt to work correctly with inventories/tanks on. Maybe with a recipe something like this:
![robotarm](https://cloud.githubusercontent.com/assets/7753414/18349208/56d9c090-75d0-11e6-9a23-63b6356a1e5b.png)

**Comment by Vexatos** [comment]
> inventory/tank manipulation

You mean [transposers](http://ocdoc.cil.li/block:transposer)?

**Comment by MalkContent** [comment]
those can only interact with inventories/tanks
a robot can interact with the world with suck/drop

**Comment by Vexatos** [comment]
> > inventory/tank manipulation
> 
> You mean transposers?
> 
> > those can only interact with inventories/tanks

So pretty much exactly what you requested. You didn't mention in-world interaction before.

**Comment by fnuecke** [comment]
Maybe just add that to the transposer or add a T2 transposer.

**Comment by MalkContent** [comment]
Maybe. I basically had a robot arm thing in mind that feels like the extension or part of a machine(hall) and less like an automaton that happens to work in there.
Simply a component that has the capabilities of a robot in all it's sucking/dropping/swinging/placing/crafting glory, minus the moving and any computational abilities.
Not gonna complain about any less feature/3d modelling heavy solutions though, I'd be glad about a T2 transposer :)
