### ISSUE TITLE
EEPROM from server can't find Components

### ISSUE THREAD

**Issue by Panakotta00** [MightyPirates/OpenComputers#2057]
My Server can't find any comonent in the network or in the server!
I use follow eeprom code:

`gpu = components.gpu`
`screen = gpu.getScreen()`

but my console says the variable gpu is null!!!

**Comment by Vexatos** [comment]
On an EEPROM level, you can only use methods as specified [here](http://ocdoc.cil.li/tutorial:custom_oses). `component.gpu` does not work. The closest alternative would be `component.proxy(component.list("gpu")())`
