### ISSUE TITLE
[Feature Request] Redstone Cards & Redstone I/O support larger numbers (>15)

### ISSUE THREAD

**Issue by CD4017BE** [MightyPirates/OpenComputers#2058]
I have a mod containing bocks that operate with very large Redstone signals (up to 2.147.483.647).
But when testing around with Computers, I found out that Computer Cases with Redstone Cards as well as Redstone I/O Blocks can receive but not emit numbers greater than 15 (although _getOutput()_ says it does).

I would be nice if the output was not limited that way (at least for Tier-2 Cards which are meant to interact with other mods' Redstone systems).

I also found out that EnderIO Redstone Conduits and even vanilla Redstone Comparators actually support any positive integer.

**Comment by xarses** [comment]
I'm guessing you mean that you want to be able to set a level above 15, and not say a channel.

The max output is based on the interoperability between OC and the redstone conductor on the adjacent side. for example, if you place a RedLogic wire on one of the sides, you will be able to set up to 255 (which is RedLogic's max).

You can find the [intergration code](https://github.com/MightyPirates/OpenComputers/tree/master-MC1.7.10/src/main/scala/li/cil/oc/integration).

You will need to consult the branch for the MC version you are using and then look for the corresponding mod to see what compatibilites exist.

**Comment by MyNameIsKodos** [comment]
What mod are you using that adds the blocks with very large redstone signals?

**Comment by CD4017BE** [comment]
It's one of my mods: [Automated Redstone](https://github.com/CD4017BE/AutomatedRedstone)
I changed the signal system to use vanilla redstone instead of my own API that I used before. Because I thought it would make compatibility with other mods easier (no need to implement special APIs).

I looked at the code in OpenComputers: You would only need to remove the
Math.max(Math.min(... , 15), 0) in [RedstoneAware](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.10/src/main/scala/li/cil/oc/common/block/RedstoneAware.scala).getWeakPower()

The only question is whether you want to allow larger signal values at all and if it should be only for Tier 2 redstone cards (bit more complicated to implement) or for all redstone emitting Blocks.
As far as I know (and found out while testing), over ranged signal values shouldn't make other mods do any bad things even if they don't support that. So it should be save.

**Comment by MyNameIsKodos** [comment]
Generally, special support for > 15, as far as I know, is handled through special additions to the T2 Redstone Card. I'm not part of the development team, though, so I cannot speak for them, but that sounds like the best approached for this, since things like RedNet, Bundled Redstone, and Wireless Redstone are already supported through a T2 Redstone card.

**Comment by xarses** [comment]
As I previously mentioned, the expected path to work with this is to create a mod integration and override the appropriate things  You can find that mods like [RedLogic](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/integration/redlogic/ModRedLogic.scala) or [BluePower](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/integration/bluepower/RedstoneProvider.scala) have extended the RedstoneProvider.

**Comment by fnuecke** [comment]
Hmm, not super sold on using the vanilla logic for larger values, but I suppose it's something to look into.
After the next release (no, it's not a running joke yet >_>), don't want to risk it breaking something after all.

**Comment by payonel** [comment]
I think the work for this is simple, just remove the math.max(15, ...) check, but this should be tested which takes time :) so open-for-adoption is for someone to show good faith in testing this

**Comment by CD4017BE** [comment]
Considering that a lot of blocks in my mod AutomatedRedstone (since version 4.2.0) already emit these over-sized vanilla redstone-signals to neighboring blocks during their normal operation, one could theoretically say that this feature has already been tested for ~15 month so far without showing any problems.

If then also TIS-3D implements this, I could finally remove the workaround bridge I currently have in my mod (a redstone cable acting as OC component / TIS-3D serial provider with simple callbacks for reading or setting its redstone signal without limit).
