### ISSUE TITLE
Fire ItemTossEvent on robot.drop()

### ISSUE THREAD

**Issue by Polyana-Fontes** [MightyPirates/OpenComputers#2059]
I'm developing a protection mod for forge and I'm currently working to protect OpenComputer's stuff.

OpenComputers is very well developed and most of the protections worked out of the box, I thought that robots would requires tons of class transformers but I was wrong, it is respecting permissions out of the box :+1: 

But, there's only one issue that I've found so far, the robots drops items to the world and doesn't fire `ItemTossEvent`. The event itself kinda sucks because it does not return the item to the player if we cancel it, so the correct implementation would be to remove from the inventory, fire the event and spawn it into the world only if the event is not cancelled, if the event got cancelled the item should not be returned to the inventory. To deal with that I don't cancel item toss, I let it spawn and then I destroy the entity on the beginning of the next tick and then I return it to the player manually.

So it would be nice if robots fired 2 events when it needs to drop an item, a cancellable RobotDropItemEvent and then an normal ItemTossEvent for compatibility reason.

In normal Java it would be something like:

``` java
@Cancelable
public class RobotDropItemEvent extends RobotEvent
{
    public final ItemStack drop;
    public final World world;
    public final double x;
    public final double y;
    public final double z;
    public RobotDropItemEvent(Agent agent, ItemStack drop, World world, double x, double y, double z)
    {
        super(agent);
        this.drop = drop;
        this.world = world;
        this.x = x;
        this.y = y;
        this.z = z;
    }
}
```

Then when a robot needs to drop the logic would be:

``` java
public abstract class TheRobotClass implements Robot
{
    IInventory inventory;

    /**
     * Executed when an item needs to be dropped into the world
     * @return true If the item was removed from the inventory
     */
    public boolean dropInventorySlot(int slot, int amount)
    {
        if(amount <= 0 || slot < 0 || slot >= inventory.getSizeInventory())
            return false;

        ItemStack originalStack = inventory.getStackInSlot(slot);
        if(amount > originalStack.stackSize)
            return false;

        ItemStack dropStack = originalStack.copy();
        dropStack.stackSize = amount;

        ForgeDirection facing = facing();
        World dropWorld = world();
        double dropX = xPosition() + facing.offsetX;
        double dropY = yPosition();
        double dropZ = zPosition() + facing.offsetZ;
        if(MinecraftForge.EVENT_BUS.post(new RobotDropItemEvent(this, dropStack, dropWorld, dropX, dropY, dropZ)))
            return false;

        originalStack.stackSize -= amount;
        if(originalStack.stackSize == 0)
            inventory.setInventorySlotContents(slot, null);
        else
            inventory.setInventorySlotContents(slot, originalStack);

        EntityItem entityItem = new EntityItem(dropWorld, dropX, dropY, dropZ, dropStack);
        if(MinecraftForge.EVENT_BUS.post(new ItemTossEvent(entityItem, player())))
            return true;

        dropWorld.spawnEntityInWorld(entityItem);
        return true;
    }
}
```

**Comment by fnuecke** [comment]
81c34e0c14596c578f16a41caca2f8dfcf641d3d

Firing the `ItemTossEvent` when agents try to drop something now and not dropping when it's canceled.
If they drop stuff where they shouldn't that's their problem, really :P
