### ISSUE TITLE
There were errors running the class transformer

### ISSUE THREAD

**Issue by jurplel** [MightyPirates/OpenComputers#2062]
[latest.log](http://hastebin.com/aserutulan.log)
OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar

**Comment by topher2010** [comment]
I'm getting this error as well.  here is a dropbox link to my fml-latest log file.

https://www.dropbox.com/s/xm2485e2kc7m2zs/fml-client-latest.log?dl=0

**Comment by Alaberti** [comment]
I think this issue has been address tons of times, try the dev builds here: http://ci.cil.li/job/OpenComputers-dev-MC1.10/ see https://github.com/MightyPirates/OpenComputers/issues/1998

**Comment by Vexatos** [comment]
Duplicate of #1998.
