### ISSUE TITLE
Request - inventory.getAllStacks() for WorldInventoryAnalytics (Inventory controller/transposer/etc)

### ISSUE THREAD

**Issue by thiakil** [MightyPirates/OpenComputers#2065]
I'm looking to make a form of inventory management with OC, but enumerating itemstacks in an inventory takes quite a while with getStackInSlot (around 1min for 300 slots). 

getAllStacks from the inventory driver can get it instantly.

I'm not sure whether this is from the Converters adding their info to the table (getAllStacks seems to not do this), or from the context switch. If it is, perhaps also an option in getStackInSlot to not do this?

**Comment by Vexatos** [comment]
I guess this can be closed now.
