### ISSUE TITLE
There were errors running the class transformer. Please report this

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2072]
Minecraft: 1.10.2
Forge: 12.18.1.2094

Pastebin: https://gist.github.com/BlakeDarwinXE/4fb402a409b738bb501cd6d02ca6e46e

**Comment by Alaberti** [comment]
Looks like your pastebin is for Refined Storage. Try the latest dev builds (http://ci.cil.li/job/OpenComputers-dev-MC1.10/) which should have resolved the transformers issue.

**Comment by Vexatos** [comment]
I am quite certain that this is a duplicate of either #1998 or #2014 (or both). It should not appear anymore in the latest release (1.6.0).
