### ISSUE TITLE
Broken text rendering (1.10.2, v1.6-rc1)

### ISSUE THREAD

**Issue by chris54721** [MightyPirates/OpenComputers#2073]
**OC version:** OpenComputers-MC1.10.2-1.6.0.3-rc.1
**Environment:** Java 1.8.0_102 on macOS Sierra 10.12

Text rendering looks broken (it basically uses what looks like an inventory GUI texture).
I'm using the [All the Mods](https://minecraft.curseforge.com/projects/all-the-mods) modpack, [version 1.32](https://minecraft.curseforge.com/projects/all-the-mods/files/2333376).

**Client log:** http://paste.ee/p/MrCjk

![2016-10-01_15 08 06](https://cloud.githubusercontent.com/assets/3685659/19014285/99930ad8-87e9-11e6-8fd6-db240a508904.png)
![2016-10-01_15 08 19](https://cloud.githubusercontent.com/assets/3685659/19014286/9f8fa478-87e9-11e6-83ec-a9403c2b024e.png)

**Comment by payonel** [comment]
duplicate (likely) of #1458

try reloading textures, `F3+t`
