### ISSUE TITLE
Crash when placing Cable, related to Tesla capabilities

### ISSUE THREAD

**Issue by Aerolivier** [MightyPirates/OpenComputers#2076]
When I place a cable (next to a computer case T3, at least), the game crashes, and the world causes crashes when loaded again.
Using OpenComputers-MC1.10.2-1.6.0.37-dev with Forge 2088.

[latest.log.txt](https://github.com/MightyPirates/OpenComputers/files/505056/latest.log.txt)

N.B. I updated to this developer version because on an older version, I was getting errors about class transformers or so.

If you need any other details, please let me know.

Thanks.

**Comment by fnuecke** [comment]
c81a412046f8c68841a6425f6bfb6ddb3b703af2

**Comment by Aerolivier** [comment]
Thank you very much!
