### ISSUE TITLE
Wrong color drawing on tablets

### ISSUE THREAD

**Issue by limoka** [MightyPirates/OpenComputers#2079]
When i draw 0x606060 on tablets i get blue instead of gray
![2016-10-03_21 14 30](https://cloud.githubusercontent.com/assets/12484618/19048545/723d2abe-89af-11e6-9838-9366cb89e88c.png)
i use OpenComputers-MC1.7.10-1.6.0.3-rc.1-universal

**Comment by magik6k** [comment]
T2 GPU in tablets have a very limited default color palette so this is correct behavior. You may want to use custom palette colors as described on wiki http://ocdoc.cil.li/component:gpu.

**Comment by limoka** [comment]
But i use T3 GPU.

**Comment by magik6k** [comment]
Tablets only have T2 screen and it limits the colors too.
