### ISSUE TITLE
Problem with amount of memory: crashing, OutOfMemoryError

### ISSUE THREAD

**Issue by pjht** [MightyPirates/OpenComputers#208]
Using OpenComputers after about 4 operations (placing, breaking, or using a block) with 
4 3.5 tier memory modules, Minecraft starts to lag, and eventually crashes. I get this error in Console:
4/12/14 1:05:11.589 PM [0x0-0x81081].com.Mojang Specifications.Minecraft.Minecraft: [13:05:11 INFO]: Client> Caused by: java.lang.OutOfMemoryError: PermGen space

I've noticed that if I use less memory, it doesn't have the problem.
I'm using MacOSX.

**Comment by BigRenegade** [comment]
This is because you need to increase the amount of permgen assigned.  the optimal amount to set perm gen to is 512K. This should stop any out of memory error crashes like you just experienced

**Comment by fnuecke** [comment]
See #163.

**Comment by pjht** [comment]
Minecraft can't start when I try that. Any other way?

**Comment by pjht** [comment]
Working!
