### ISSUE TITLE
See if Rembulan (a Lua 5.3 implementation for the JVM) might be helpful

### ISSUE THREAD

**Issue by mjanicek** [MightyPirates/OpenComputers#2082]
(I'm not sure if this is the best place to do this, but I'll try anyway.)

For the past few months I've been working on Rembulan, a new compiler+runtime for Lua 5.3 on the JVM, built from scratch with sandboxing (of the kind you would expect in OpenComputers) in mind. The project lives on GitHub:
- https://github.com/mjanicek/rembulan

I'll just copy the first two paragraphs from the Readme here for your convenience:

> Rembulan is an implementation of Lua 5.3 for the Java Virtual Machine (JVM), written in pure Java with minimal dependencies. The goal of the Rembulan project is to develop a correct, complete and scalable Lua implementation for running sandboxed Lua programs on the JVM.
> 
> Rembulan implements Lua 5.3 as specified by the Lua Reference Manual, explicitly attempting to mimic the behaviour of PUC-Lua whenever possible. This includes language-level features (such as metamethods and coroutines) and the standard library.

I'd like to invite the OpenComputers developers (and of course anyone else interested) to take a look and see if the project might be of help to you!

For the purposes of OpenComputers, there are four significant improvements over LuaJ (that I believe you're using?) that may be of interest:
1. Rembulan implements what I call "CPU accounting": Lua programs may be allocated a number of "ticks" for which they are allowed to run before they are paused (and resumed later). These pauses are transparent to the Lua programs. In other words, Rembulan allows you control over the CPU time spent by the user programs. (I'm not aware of an equivalent functionality in LuaJ.)
2. Coroutines in Rembulan do not use Java threads (as opposed to LuaJ). They are therefore much lightweight and coroutine switches them do not involve a thread context switch. They work with CPU accounting (above). This should allow you to have an order of magnitude more coroutines than with LuaJ.
3. Rembulan implements Lua 5.3, whereas (IIRC) LuaJ implements Lua 5.2.
4. It's possible to have per-state metatables (e.g., for booleans or numbers) in Rembulan, whereas in LuaJ these are accessed via static fields, i.e., by default shared by all programs run on the JVM.

Points 1 and 2 are especially good-to-have (I think). I don't know to what extent you might have addressed similar points in your patched version of LuaJ, though. I've seen an announcement mentioning Lua 5.3, so that's at least part of the 3rd point, and the 4th point is technically doable even in LuaJ.

There are of course downsides and caveats:
- The project is not yet as mature as LuaJ, and a significant part of the standard library is still missing (most notably the module library). However, the runtime is by now mostly stable, and I do not expect it to change much until the release. (A detailed overview of the state of the standard library may be found in the documentation.)
- Given the fundamentally different implementation strategy, libraries written for Lua in LuaJ will not (at this point) work in Rembulan. It should, however, be possible to implement a LuaJ-to-Rembulan adapter that might do at least part of the job.

That said, it might be worth it out to see how it could be used in OpenComputers, and perhaps help shaping it?

**Comment by Techokami** [comment]
LuaJ is a fallback implementation, iirc. The main Lua runtime implementation is JNLua, which @fnuecke has made custom modifications to; memory limits being the biggest one, so you need RAM items inside your computer to have the desired memory capacity. The repo is [here.](https://github.com/MightyPirates/OC-JNLua)

**Comment by mjanicek** [comment]
Ah, I see -- I thought it might be the other way around. Alas, limiting the memory usage is currently not possible in Rembulan (and won't be for quite some time). That's a fantastic feature to have, congratulations @fnuecke!

Thanks for the link to the repo!

**Comment by asiekierka** [comment]
I would say replacing LuaJ with Rembulan might be a great idea, as long as Rembulan gets some proper testing.

@mjanicek One of the biggest features missing from LuaJ but present in the native Lua fork is serialization of the VM state, and deserialization of it - that is, being able to freeze a VM's state, save it to a file then load it from that file again. If you could implement that, I think Rembulan would be a no-brainer.

**Comment by mjanicek** [comment]
Thanks, I've added an issue for this (mjanicek/rembulan#4), will ping back once it's done.

**Comment by fnuecke** [comment]
Hey! Saw this scroll by on the Lua mailing list, and it's definitely something I'd like to give a shot. Being able to give the state a fixed number of ticks to run is great. Persistence would be great to have, but tbh, even if it doesn't, an alternative to LuaJ, or rather, a 5.3 Lua when the natives are disabled/not available would still be nice to have.

Is there some quickstart / documentation on how to register custom callback functions in a state? Basically how to add a callback to a table (what's the interface a callback would have to implement?), and how to put that table into the global state. Those'd be the basics to get working on this.

For userdata, from what I can tell, it'd be a matter of extending [the Userdata class](https://github.com/mjanicek/rembulan/blob/master/rembulan-runtime/src/main/java/net/sandius/rembulan/Userdata.java)? With a customly created metatable to have support for __call, __index etc?

**Comment by mjanicek** [comment]
Hi, sorry for the late reply. I'm glad to see there is interest, even if not all the features you already have are currently ready!

I haven't got any tutorials yet (sorry), but I've added two examples to `rembulan-examples`:
- [rembulan-examples/.../SimpleGlobalFunction.java](https://github.com/mjanicek/rembulan/blob/master/rembulan-examples/src/main/java/net/sandius/rembulan/examples/SimpleGlobalFunction.java) -- add a global function `now` that calls `System.currentTimeMills()`;
- [rembulan-examples/.../CallableUserdata.java](https://github.com/mjanicek/rembulan/blob/master/rembulan-examples/src/main/java/net/sandius/rembulan/examples/CallableUserdata.java) -- create userdata that behaves like a function (using an immutable metatable with an entry for `__call`).

Hope it addresses the question; if there is anything I can help with, do let me know.

**Comment by 20kdc** [comment]
A temporary way to limit the memory usage may be to consider that you can only get as much memory usage as you can generate in a given time, and that a persisted state must contain everything in memory (thus persisted state size == memory usage).
As long as native calls that allow multiplying memory usage in some way are checked (Particularly string operations such as concatenation, but only if the total is above some amount), and another memory check is done every, say, 10000 Lua instructions, it should be relatively easy to prevent dangerous amounts of memory usage. (Assuming the difference between "above the amount allowed" and "dangerous" is larger than a few MB, anyway - some temporary solely table-based above-limit memory usage will slip through, hence the per-10000-Lua-instructions timer.)
So, persistence + cpu accounting should work as a way to keep memory usage in check, at least well enough that it won't be complete server doomsday if that user just can't use JNLua for some reason.
(Re-persisting all the time could well be slow, though.)

**Comment by payonel** [comment]
looks like a cool project, but it's been too long without research and no PR work done. It would be nice to drop luaj, but for now that is what works for us as a backup to native lua libs

**Comment by skyem123** [comment]
It is a shame but sadly the project seems to be dead. Ah well...
