### ISSUE TITLE
Unifont Characters Gone

### ISSUE THREAD

**Issue by J0SLAN** [MightyPirates/OpenComputers#2083]
I've noticed that the new font.hex and wcwidth.bin are missing codepoints 0xA000 ~ 0xDFFF. Is this intentional? Because that means I can use roughly 16000 custom characters without people whining about it. ;D

**Comment by inklit** [comment]
What version of OpenComputers?

**Comment by J0SLAN** [comment]
1.6 Release candidate.

**Comment by magik6k** [comment]
@asiekierka

**Comment by asiekierka** [comment]
Please blame GNU Unifont's GPL license, which, by a set of extensions, would not be compatible with Minecraft being propiertary.

We're now using a public domain font.

If you're doing custom characters, **STICK TO THE PUA**. I cannot emphasize that more.

**Comment by brisingraerowing** [comment]
@asiekierka

Would the Open Font License be usable? I ask as Google now has a font that covers ALL Unicode characters, [Noto](https://www.google.com/get/noto/), and all of those fonts (there are a TON of them) are under that license.

**Comment by asiekierka** [comment]
It's not 8x16 bitmap, though.

2016-10-22 18:38 GMT+02:00 Brisingr Aerowing notifications@github.com:

**Comment by skyem123** [comment]
Wait a moment... aren't bitmap fonts all public domain?

**Comment by asiekierka** [comment]
@skyem123 In your country, yes. In many other countries, yes. In all countries, no.

**Comment by brisingraerowing** [comment]
I see that the bitmap is 256x256, and I guess the cell size is 8x16. What is the range of characters on the font sheet, anyways?
