### ISSUE TITLE
OC doesn't allow any other ICapabilityProviders to exist on TEs

### ISSUE THREAD

**Issue by HenryLoenwind** [MightyPirates/OpenComputers#2086]
If there are other ICapabilityProviders on a TE together with OC's, this:

https://github.com/MightyPirates/OpenComputers/blob/master-MC1.10/src/main/scala/li/cil/oc/integration/tesla/Tesla.scala#L39

will be triggered by Forge code.

**Comment by HenryLoenwind** [comment]
e.g. http://hastebin.com/orinonaday.txt

**Comment by Aerolivier** [comment]
Seems like the same issue as my #2076 , though you seem to know more about it.

**Comment by Vexatos** [comment]
Fixed via https://github.com/MightyPirates/OpenComputers/commit/c81a412046f8c68841a6425f6bfb6ddb3b703af2. see #2076.
