### ISSUE TITLE
OC Robot can't access a world's objects

### ISSUE THREAD

**Issue by AnthonyEvo** [MightyPirates/OpenComputers#2087]
Actually it's all simple. Robot which after been placed, can only to move. Robot.swng() always return "false" and "block". We tried every instrument which was  available on the server. Tried to give with an arguments in a method. But all our action were useless. May be you can help me to figure up with a problem?

**Comment by AnthonyEvo** [comment]
Sorry for my impatience. I forgot to check one little detail. Security system of the server blocking the robot, because he don't have a permission to manipulate with blocks. Security system installed in a server core, it's not a WG. Excuse me for troubling.

**Comment by payonel** [comment]
no problem, glad you got it worked out
