### ISSUE TITLE
GC failure

### ISSUE THREAD

**Issue by MaHuJa** [MightyPirates/OpenComputers#209]
After running for long enough, the following program will fail to do its check. Power cycling the computer at that time will cause it to fail to start due to being out of memory.

The big idea is to use some kind of block placer, redstone triggered, to place a fluid container, wait until it's empty/full (happens in both cases), and use a block breaker  to remove it again.
(I used TE's autonomous activator and terrain smasher, but any of its type will work.)

```
component = require ("component")
sides = require ("sides")
rs = component.redstone

function remove()
  rs.setOutput(sides.east,15)
  os.sleep(0.5)
  rs.setOutput(sides.east,0)
end

function place()
  rs.setOutput(sides.west,15)
  os.sleep(0.5)
  rs.setOutput(sides.west,0)
end

function isEmpty()
  if not component.isAvailable("extrautils_drum") then return true end
  local tank = component.extrautils_drum
  local t = tank.getTankInfo()
  if t[1].amount == 0 then return true end
  return false
end

while true do
  os.sleep(1)
  if isEmpty() then
    remove()
    place()
  end
end
```

I'm noting collectgarbage() is not available, or i would have tried calling that at some point in the cycle; but given that the GC fails with the above, would it even matter? Is something, like the tank proxy, not being considered a candidate for gc even after it's no longer referenced?

**Comment by fnuecke** [comment]
Hmm, well two things: one, garbage is automatically collected before computers are 'resumed' anyway (unless changed in the config), so collectgarbage() really shouldn't be necessary. Two, resetting a computer (i.e. turning it off and on again) creates a completely new Lua state, so if that runs out of memory when booting/directly after something else is going on, it has nothing to do with the old state. Either an autorun script running amok, or possibly Java itself running out of memory?

**Comment by SoniEx2** [comment]
@fnuecke why's there no collectgarbage? (for stuff like collectgarbage("count") etc)

**Comment by fnuecke** [comment]
There's computer.freeMemory() for that.

**Comment by fnuecke** [comment]
Closing due to lack of feedback, probably an error in a script or Java running out of memory.

**Comment by SoniEx2** [comment]
I think this is related to a Lua "bug"... even with collectgarbage("collect") it wouldn't work...
