### ISSUE TITLE
There were errors running the class transformer

### ISSUE THREAD

**Issue by MariuszPL55** [MightyPirates/OpenComputers#2093]
I know the title is repeated multiple time, but I attach the log - hope this will be fix. I'm using OpenComputers with Industrial Craft for MC 1.10.2
[latest.log](https://github.com/MightyPirates/OpenComputers/files/525489/latest.txt)

**Comment by gamax92** [comment]
Like the chat message says we still need `fml-server-latest.log` (or `fml-client-latest.log` if this is singleplayer)

**Comment by MariuszPL55** [comment]
I don't have such a file. Maybe you mean fml-client-latest.log?

[fml-client-latest.txt](https://github.com/MightyPirates/OpenComputers/files/528308/fml-client-latest.txt)

**Comment by gamax92** [comment]
```
[21:33:15] [Client thread/WARN] [OpenComputers/]: Failed patching btb.renderLeash, method not found.
```

Seems to be just this common issue, a thing to note about class transformer 'errors' is that they're actually rather harmless and OC will completely function normally despite the issue.

**Comment by PapyRedstone** [comment]
personally i can run oc alone with tis error but when i put other mods with it i can't use oc

**Comment by Vexatos** [comment]
Duplicate of #1998.
