### ISSUE TITLE
AE2 autocrafting: Bad argument #1 to parameterless function

### ISSUE THREAD

**Issue by Baughn** [MightyPirates/OpenComputers#2096]
That is: `Bad argument #1 to 'isCanceled' (java.lang.Object expected, got none)`

Full stack trace at https://madoka.brage.info/bug-reports/2016-10-14_22.49.14.png, you can find the program code at https://madoka.brage.info/baughn/oc/ae2sat.lua. This is with Rv3 AE2 and the newest OpenComputers for 1.7.

I'm not sure how to debug this one.

**Comment by Baughn** [comment]
It seems to be triggered by the component.me_controller.getItemsInNetwork statement. Unclear how.

**Comment by payonel** [comment]
please retest and report, we've updated our ae2 support in our dev builds

**Comment by Baughn** [comment]
Can't, sorry. We got rid of that world long ago.

**Comment by payonel** [comment]
i'll find time to test eventually

**Comment by payonel** [comment]
sorry, this does not repro for me
though we've made many fixes for ae2 integration -- the isCanceled call has not needed any fixes
closing for no repro
