### ISSUE TITLE
Request: Virtual components

### ISSUE THREAD

**Issue by MaHuJa** [MightyPirates/OpenComputers#210]
I'd like to create a table with the appropriate functions, pass it to a function like computer.addVirtualComponent(t) or similar (component rather than computer?)
and have the system call its members when performing any actions on that component. Naturally we'd want a corresponding remove function.

The table passed would outwardly have to appear like a proxy of the simulated component type; an optional address (or a randomly generated one) and mandatory type fields may be required.

Some example uses:

Network filesystem.
As mentioned in #179 I would like to be use a networked file system. Unless overriding the filesystem table's functions in-place, such network files would have to be accessed through a separate API; I would like for them to transparently appear like any other file.

Multi-disk aggregate
Another idea from #179 is to use multiple disks to store a set of files, like a RAID device, in mirroring or spanning forms. This could be accomplished in a virtual component that addresses each component to do its thing. (Given nesting with network fs, this means files could be transparently mirrored to a server or something.)

If both this and 179 are implemented, the software version would be "cheaper" in resources but more expensive in performance and memory - as it should be.

Network relayed redstone (or any similar component)
Take a piece of software designed to use a redstone component, write a virtual component that instead transmits the calls over a network to activate a redstone component elsewhere.

**Comment by GopherAtl** [comment]
You could probably do this in lua, by overriding component.list with your own function returns an iterator that goes through components from your own virtual component table as well as the normal component.list values. Even component.get just uses component.list to find the component with the provided address. You'd also have to replace proxy and invoke in a similar way. Then just add methods to add and remove compatible tables from this virtual table, making sure to push the "component_added" and "component_removed" signals when you do. 

That's not to say it shouldn't be added as a feature at a lower level, but I would assume things that can be done fairly easily in lua would be lower priorities than other features.

**Comment by SpiritedDusty** [comment]
For the network filesystem, you can create a table with all the filesystem functions that communicate through the network and just run `filesystem.mount(networkFS, '/network')`. So there's not filesystem overwriting complication there as the filesystem API manages all of the mounting for you.

**Comment by fnuecke** [comment]
As mentioned above, this can be done by overriding the right methods in the component API and sending the corresponding signals - or just go right for a custom file system proxy, where appropriate. This cannot really be implemented "host side" anyway, since the virtual component logic would have to implemented in Lua anyway.

**Comment by Alchemichai** [comment]
I know this is an old answered post, but when searching for virtual components or the likes this is the first page that comes up. There is already a library made for virtual components called [vcomponents](https://github.com/OpenPrograms/gamax92-Programs/tree/52ddc2ebd4447a12ff929322ed6b85dec75a3047/vcomponent). Thanks to Hiyacynth from the Minecraft Computer Mods discord channel for bringing this to my attention after my failures to create one for myself. Happy Virtual Componenting.
