### ISSUE TITLE
java.util.Map not supported by Context.signal

### ISSUE THREAD

**Issue by boq** [MightyPirates/OpenComputers#2100]
It seems that in https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/machine/Machine.scala#L327 `Map` means `scala.collection.immutable.Map` (according to [this](https://gist.github.com/boq/dba1b53f5c69e2f9ba91445daa57e6b7#file-opencomputers-mc1-7-10-1-6-0-7-rc-1-universal-jar-L93-L113)), so native Java `java.util.Map` interface is not supported.

Not sure if this is intended, but this causes some problems for me (see https://github.com/OpenMods/OpenPeripheral-Integration/issues/28), as I don't have access to Scala collections.

Also, guard in this case seems to restrictive - Lua allows any type as key and value, including other tables, not only strings.

**Comment by magik6k** [comment]
That's most likely a bug in CC compat module, having full stack trace would be very helpful here.

**Comment by boq** [comment]
Umm, what? I'm calling `Context.signal` directly ([here](https://github.com/OpenMods/OpenPeripheral/blob/master/src/main/java/openperipheral/interfaces/oc/OpenComputersEnv.java#L70)), it's not routed via CC integration layer?

**Comment by magik6k** [comment]
I was mislead by `ModuleAppEng.CC_EVENT_STATE_CHANGED` in your code. So what you want is being able to pass java map instead of scala one?

**Comment by boq** [comment]
Not 'instead', but yeah, I'd like to pass `java.util.Map`.

Restriction in `Machine.signal` seems rather pointless IMO, since it's later [passed](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/machine/Machine.scala#L1075) to `Registry.convert` which already [supports](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/driver/Registry.scala#L206) `java.util.Map`.

**Comment by fnuecke** [comment]
Yeah, there should definitely be a `case` for Java maps in there. Just a reminder that signals in OC are stupidly limited tho, in that maps can only be string -> string maps.

**Comment by fnuecke** [comment]
0148ccff2679bf8c9793aec214905617ef3960e6

**Comment by boq** [comment]
Oh, weird restriction. Is is caused by this [(de-)serialization code](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/machine/Machine.scala#L736)?

**Comment by fnuecke** [comment]
Yep. The main reason they're held by Java IIRC was to keep them asynchronous from the Lua executor thread. I.e. keeping pushing signals super lightweight. And the reason they're not moved into Lua space in the next exec but only one-by-one was, again, IIRC, to avoid being able to force a machine to OutOfMemory by spamming it with network packets e.g.
