### ISSUE TITLE
Friends GUI not working properly gives me this error (hermitcraft 1.10.2 server first release) #3315

### ISSUE THREAD

**Issue by xcnxclutch** [MightyPirates/OpenComputers#2101]
this is the error report it told me to send over (I had to put copy it from my server computer which is why it is in docs... its a text document on the server)

![hermitcraft error](https://cloud.githubusercontent.com/assets/15936686/19459900/b0074460-94a4-11e6-9c42-97a086070e9a.JPG)
[error.report.copied.over.docx](https://github.com/MightyPirates/OpenComputers/files/534937/error.report.copied.over.docx)

**Comment by payonel** [comment]
the ftb packs were using our pre-release version (not our 1.6) - others have reported the class transformer issue is resolved when having updated: #2132
