### ISSUE TITLE
IC2 2.6.27-ex110 power cables do not interact with OC 1.6.0.2

### ISSUE THREAD

**Issue by Gregorsharpe** [MightyPirates/OpenComputers#2102]
Just spun up a world with a friend to try out OC (love the design so far!), but we've run into an issue after choosing IC2 as our source of power. The IC2 wires do not connect to the power converter or computer cases. The included cable in OC will also not interact with IC2 power modules.

**Comment by Gregorsharpe** [comment]
Tested Mekanism-1.10.2-9.2.0.292 as well, same result.

**Comment by magik6k** [comment]
Works here, `OpenComputers-MC1.10.2-1.6.0`, `industrialcraft-2-2.6.84-ex110.jar`. Try getting latest OC from CI, if I'm correct you want this: http://ci.cil.li/job/OpenComputers-dev-MC1.10/.

Setup is as follows:
![setup](https://assets.magik6k.net/screenshoots/8f5890b0-4eae-45e7-a55a-68a7062e5636.png)
Note that you may need some energy buffer(capacitor/power distributor) in network to get it running

**Comment by Gregorsharpe** [comment]
Hi magik6k! Thanks for the heads up, after a little head scratching everything is functional. Thank you so much!

https://gyazo.com/1bf6b60611430eb37a5dc941deb6d571
