### ISSUE TITLE
Robot callbacks pulling a nil value.

### ISSUE THREAD

**Issue by SpEaGs** [MightyPirates/OpenComputers#2103]
I'm just trying to run a super simple code to iterate through my robot's inventory, but it keeps stating that "robot" is a nil value, and points to the line as follows: `size = robot.inventorySize()`

I've tried using the lua interpreter to run the line in question on its own, then printing size, and it works fine, but for some reason it doesn't want to work in my script.

I'm aware that I've also got the same errors as #1998 and a few others, however it seems that this hasn't caused actual functionality issues for anyone, so I'm willing to bet that's not the case here. My log file's attached, along with a couple of screenshot croppings of the issue. 

Here's the code i'm trying to run:

```
i=1
size=robot.inventorySize()
while (i<=size) do
    i=i+1
    robot.select(i)
    torch = robot.compareUp()
    cobble = robot.compare()
    print(torch)
    print(cobble)
end
```

![interpreter working](https://cloud.githubusercontent.com/assets/5341601/19622503/69a702a2-9879-11e6-8cf9-2dcb00e5db7c.png)
![script not working](https://cloud.githubusercontent.com/assets/5341601/19622506/6d6c6e4a-9879-11e6-89a4-be98a4559f5a.png)
[fml-server-latest.txt](https://github.com/MightyPirates/OpenComputers/files/546037/fml-server-latest.txt)

**Comment by Fingercomp** [comment]
The "problem" is that the Lua interpreter automagically loads all libraries it can find, but a script must first call `require(libName)`, and assign its return value to a variable.

In other words, simply put the following line at the top of your script:

``` lua
local robot = require("robot")
```

Then your code should work.

**Comment by payonel** [comment]
Fingercomp is correct, the robot api you are trying to use is provided via the robot library

**Comment by SpEaGs** [comment]
That worked. Thanks bunches! For some reason, I guess I just assumed that since it's being run on a robot, I wouldn't have to reference libraries specific to robots... gotta love how one stupid little mistake can break everything with coding ;)
