### ISSUE TITLE
Not able to get Proxy for external APIs [IC²]

### ISSUE THREAD

**Issue by sayore** [MightyPirates/OpenComputers#2104]
I tried to get a Proxy for an Fluid/ Solid Canning Machine from IC² but everytime i get a nil value back.

http://prntscr.com/cy29tq

Maybe this is intended but i couldn't read anywhere about this being not possible.

**Comment by magik6k** [comment]
You can't use local in Lua shell as it's scope is inside this one single line you type. just do `getc = component.proxy(...`
