### ISSUE TITLE
component.modem.send Not working

### ISSUE THREAD

**Issue by bminnix** [MightyPirates/OpenComputers#2105]
Version: 1.10.2 (beta)

Having an issue using the component.modem.send(address, port, data) command where the message is not being received on the robot.  

Robot config:

=component.modem.address     ## Makes note of the address
component.modem.open(99)
=event.pull("modem")                 ## Place robot into listening state to print inbound

Server config:

component.modem.send("address from above", 99, "test")    ## Robot receives nothing
component.modem.broadcast(99, "test")                                     ## Robot receives modem_message showing same address as above in the "local address" field

**Comment by payonel** [comment]
It is not "modem", but "modem_message"

See http://ocdoc.cil.li/component:signals#network_cards for more information

**Comment by CaitlynMainer** [comment]
This was actually caused by a typo in the send to address, the proper event was being checked, I logged on to their server and helped.
