### ISSUE TITLE
Can't craft CPU Tier 3

### ISSUE THREAD

**Issue by MariuszPL55** [MightyPirates/OpenComputers#2107]
I used this wiki http://ocdoc.cil.li/item:cpu and also used http://imgur.com/a/P4ovH and this recipe on my computer don't work.. ;c Have latest version for Minecraft 1.10.2 (1.6.0.3-rc.1) any ideas?

**Comment by Aleszp** [comment]
Wiki's out of date, try using diamond shards (those OC parts of decrafting of diamond) instead of emeralds.

**Comment by payonel** [comment]
Thanks @MariuszPL55 for reporting, and thanks @Aleszp for commenting that the wiki is out of date. I've updated the wiki to reflect the new crafting recipe.
