### ISSUE TITLE
Lag every 45 seconds

### ISSUE THREAD

**Issue by Aronnax18** [MightyPirates/OpenComputers#2110]
During execution lag emerges every 45 seconds and lasts for 1-2 seconds
My version - OpenComputers-MC1.7.10-1.6.0.7-rc.1-universal

Example - https://youtu.be/1g96VbzRPDU

**Comment by Forecaster** [comment]
Execution of what?

**Comment by Aronnax18** [comment]
Execution of program. [Here's an example](https://www.sendspace.com/file/67jsrc)

**Comment by Forecaster** [comment]
Here's a youtube version of the linked video file for those who'd rather not download it: https://youtu.be/1g96VbzRPDU

It seems quite useless though, nothing is explained, no program is shown, it's just a time counter and a sped up blinking light.

**Comment by Aronnax18** [comment]
Problem is that lamp reduces to blink smoothly and crashes every 45 seconds. Idk how to explain more clearly, sorry for my English.

**Comment by magik6k** [comment]
We have noticed this too on our server and we ran sampler when the lag hit, here's what we got:
![sampler](https://img.bymarcin.com/screenshot-2016-10-25_22-33-22.png)
![sampler](https://img.bymarcin.com/screenshot-2016-10-25_22-34-03.png)

**Comment by Aronnax18** [comment]
magik6k, what does this mean?

**Comment by magik6k** [comment]
I just provided some more in-depth technical info to help investigate the issue. Those graphs show what is or might be consuming server time. It /might/ be due to high disk load.

**Comment by Aronnax18** [comment]
magik6k, so, any ideas how to resolve this?

**Comment by Jomik** [comment]
Lots of IO operations to your harddrive is very slow. I suspect it could be because too little RAM has been allocated to the server instance?

**Comment by MalkContent** [comment]
@Aronnax18 do the mobs lag for you, too? like, stand still and then catch up, while you are moving smoothly and lag free?

**Comment by payonel** [comment]
no strong repo, seems hosting modifications are a work around (more ram to instance, faster io)
