### ISSUE TITLE
Manual: improper use of words.

### ISSUE THREAD

**Issue by Muntafire** [MightyPirates/OpenComputers#2111]
4th line and 5th line in "Server" link page have an incorrect use of words: "**_The can_** also be configured after..." My name is Thomas Knight-Wagener and I require payment of USD$9,999,999 for this help I am providing in a game where it really shouldn't be there. Come on... The can? That is so easy to notice if whoever typed it had of just re-read it once and then another time coz that is how you do a quality check. I actually don't believe it was an accident. I think it was intentional. I am the man for the job. Hello and welcome to my world.

**Comment by LordFokas** [comment]
You have clearly never been developing anything at 6 am, owing your bed 16 hours of sleep and almost drowning in coffee.

**Comment by Muntafire** [comment]
& line 31 in lua... "**_would nothing_**"

**Comment by Muntafire** [comment]
That is not how you dev. You dev 6 hours max a day... go to the gym, cook and eat and have at least 9 hours sleep foo'.

**Comment by Muntafire** [comment]
no coffee coz coffee is for pussies

**Comment by Muntafire** [comment]
any1 who works for more than 6 hours a day is a chump that needs to get a life

**Comment by payonel** [comment]
280bebb4dca9de56e30bbb8071c305a7807bf38d
