### ISSUE TITLE
Server crash on dimension unloading

### ISSUE THREAD

**Issue by cauliflower69** [MightyPirates/OpenComputers#2115]
http://pastebin.com/VM9dmY3p

Player has a setup in a dimension. When he leaves that dimension the server crashes

**Comment by NickNackGus** [comment]
http://pastebin.com/PABW0dx2

I am having the same issue.

**Comment by fnuecke** [comment]
8a7658569485df3406e7da5a3fcd5b1982f8bab0

**Comment by PerchunPak** [comment]
> [8a76585](https://github.com/MightyPirates/OpenComputers/commit/8a7658569485df3406e7da5a3fcd5b1982f8bab0)

and what does this have to do with this bug
