### ISSUE TITLE
Corrupt OC Tile Entity causes real computer to lock up.

### ISSUE THREAD

**Issue by DonBruce64** [MightyPirates/OpenComputers#2117]
I've been having issues with my server crashing.  While the crashing is not the fault of Open Computers, it is responsible for killing my PC whenever I attempt to load the world locally.  Let me explain.

My server currently runs many mods.  One of which is Electrical Age.  That mod has an odd memory leak where if the server is left alone it will happily chew through all it's heap and kill itself with an out of memory error.  Normally I shut the server down when all players are off to keep this from happening, there have been times where I have forgotten about this and came back on the next morning to find the server had run out of memory.

I usually restore the world from a backup before the crash and call it a day, but this last time I needed to test some server settings locally so I downloaded the server off my host and tried to run it on my end.  Upon starting the server Java promptly ate the majority of the 8GB of my RAM on my computer and started constantly writing to swap.  As the computer was un-responsive I had to do hit the reset button to regain control, not my favorite thing to do.  In the log the last entry is a mention that Open Computers couldn't restore some Tile Entities, claiming that they had corrupted.

To see if this was the source of the hang, I removed Open Computers from my list of mods.  Sure enough, the server started just fine and my computer stayed responsive.  I'm no expert on Java, but something tells me Minecraft shouldn't be able to lock up my computer like that.

Log for the startup is included.
[fml-server-latest.txt](https://github.com/MightyPirates/OpenComputers/files/563176/fml-server-latest.txt)

**Comment by payonel** [comment]
we found a case where a bad lua string method could pwn the host cpu. we've resolved that issue, and it was the only known bug that would do this. open a new ticket if you have a specific repro with our latest dev builds
