### ISSUE TITLE
[1.10.2] Server Crash loading OC

### ISSUE THREAD

**Issue by Morpheus1101** [MightyPirates/OpenComputers#2119]
Crash log @ https://puu.sh/s6VOj/77b47dc64d.txt

**Comment by payonel** [comment]
I could not repro this. Tested with your version ( http://ci.cil.li/job/OpenComputers-1.6-MC1.10/3/artifact/build/libs/OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar ) as well as our release version ( http://ci.cil.li/job/OpenComputers-1.6-MC1.10/lastSuccessfulBuild/artifact/build/libs/OpenComputers-MC1.10.2-1.6.0.4.jar ).

What is strange is that this registration should not run from a server, and the client should have no problem with this code. I tested putting in a crash in this method and confirmed that starting a server does not execute this code, but does cause the client to fail.

Closing as non-reproduceable unless you can provide specific repro steps in a scenario we would expect to work.
