### ISSUE TITLE
Unable to pare meta data

### ISSUE THREAD

**Issue by Daenara** [MightyPirates/OpenComputers#2124]
Just letting you know OpenComputers throws an error, no crash or so, not even actively using the mod since we are pretty early game on our server still but I found the error when writing a bug report for another mod.  Logs attached

Daenara

[latest.txt](https://github.com/MightyPirates/OpenComputers/files/581631/latest.txt)
[fml-client-latest.txt](https://github.com/MightyPirates/OpenComputers/files/581632/fml-client-latest.txt)

**Comment by payonel** [comment]
I tested this same version and did not get this failure. Are you using a modpack I can test? Are you usiing a custom resource pack? Is your sha1 of your opencomputers jar `2c91916a955bf54b87256abdcb1e31ffa0927318`
