### ISSUE TITLE
BIOS gone / server crash

### ISSUE THREAD

**Issue by SFort** [MightyPirates/OpenComputers#2126]
I have been having issues with Computers deleting the EEPROM (Lua BIOS) if they ware turned on while the server was restarting. Which was no problem since this is a alpha build of a new pack so it was not a primary concern. 
Today i restart the server, the same thing as usual a few additional errors that i screenshot just in case. So i go to break and place all the computers so that they don't keep deleting the BIOS that is inside them but when i broke the computer the server crashed. I reboot it and the case from the broken computer is gone with the components on the floor, The separate computer nearby it however has lost all its components.

So here are the details:
[Room layout](http://prnt.sc/d5hcg3) the right computer was the one with missing components the left one was broken
Screen shots of console before crash: [1](http://prnt.sc/d5h8hi)/[2](http://prnt.sc/d5h8ki)/[3](http://prnt.sc/d5h8xu)
[Crash report](http://pastebin.com/LxVyQdEh)
[Recent Forge logs](https://dl.dropboxusercontent.com/u/79802995/logs.zip)

Version of OC:    1.6.0.3-rc.1
Version of forge: 12.18.2.2017
OC addon mods:([OpenGlasses](https://minecraft.curseforge.com/projects/openglasses/files/2309233), [OpenFM](https://minecraft.curseforge.com/projects/openfm?gameCategorySlug=mc-mods&projectID=236839), [OpenRadio](https://minecraft.curseforge.com/projects/openradio?gameCategorySlug=mc-mods&projectID=239344), [ActuallyComputers](https://minecraft.curseforge.com/projects/actuallycomputers?gameCategorySlug=mc-mods&projectID=253005), [OpenPrinter](https://minecraft.curseforge.com/projects/openprinter?gameCategorySlug=mc-mods&projectID=225127))
Edit: [Full Modlist](http://pastebin.com/Kyhexrsn)

**Comment by magik6k** [comment]
Likely related to #2092
