### ISSUE TITLE
3D Printed blocks lighting is off on 1.10.2

### ISSUE THREAD

**Issue by inklit** [MightyPirates/OpenComputers#2127]
I recently updated my server from 1.8.9 to 1.10.2 and noticed that 3D prints lighting is darker than normal.

Here is an example:
[http://i.imgur.com/K821Wl2.png](http://i.imgur.com/K821Wl2.png)

The lighting on those 3D printed blocks used to match the blocks around them, but now they do not.

**Comment by inklit** [comment]
I found a new configuration node that may be responsible for this. I'll update this issue after messing with that to see whether or not this is intended behavior.

**Comment by andystevensname** [comment]
@inklit were you able to find the root of this? I'm playing FTB Beyond, also 1.10.2, and have found the same. It seems as if sides other than the top have mismatched light levels.

**Comment by payonel** [comment]
@Vexatos would like this fixed

**Comment by MistakingManx** [comment]
This is still an issue on 1.12.2, but uh, I honestly thought it was a feature so people could tell if it was 3D printed or not

**Comment by asiekierka** [comment]
Fixed, but only for 1.12.2.
