### ISSUE TITLE
Bundled Wire Support

### ISSUE THREAD

**Issue by cookta2012** [MightyPirates/OpenComputers#2128]
This does not support Charset bundled wires on 1.10 it is the only bundled I know of for 1.10

**Comment by mandrewpowers** [comment]
I was looking for this support recently since in 1.10 Charset is one of the only mods available currently with this.

**Comment by BikerEleven** [comment]
Insulated redstone conduit from EnderIO for 1.10 act like the old rednet cables from Minefactory Reloaded. ~~That would be neat if OpenComputers or EnderIO  added the BundledOutput/Input support.~~

**Comment by Vexatos** [comment]
@BikerEleven See #2134.

**Comment by Vexatos** [comment]
Closing this since Charset does not have wires on 1.10.2 anymore.

**Comment by Techokami** [comment]
Wow, where on earth is the bundled wire nowadays? :/

**Comment by magik6k** [comment]
EnderIO?

**Comment by Techokami** [comment]
Is it actual bundled wire or is it something more like MFR's RedNet? Call me old fashioned but I like the concept of having bundles of wire that can be split off by color where needed.
