### ISSUE TITLE
"There were errors running the class transformer" on SpongeForge server.

### ISSUE THREAD

**Issue by HaXrDEV** [MightyPirates/OpenComputers#2129]
forge-1.10.2-12.18.2.2125-universal
spongeforge-1.10.2-2123-6.0.0-BETA-1877
OpenComputers-MC1.10.2-1.6.0.3-rc.1

[fml-server-latest.txt](https://github.com/MightyPirates/OpenComputers/files/587744/fml-server-latest.txt)

**Comment by Vexatos** [comment]
Duplicate of #2014.
