### ISSUE TITLE
robot.compare() failure

### ISSUE THREAD

**Issue by Sharidan** [MightyPirates/OpenComputers#2133]
Minecraft: v1.7.10
OpenComputers: 1.6.0.9

While messing around with robots, I stumbled over a problem with the .compare() method.
I was messing around with having the robot do scans of blocks in world, for later reproduction. My test setup is fairly simple - a 4x4 block square made up of vanilla wooden logs like so:
http://www.sharidan.dk/logs.png
(all vanilla blocks. border: acacia logs; middle; top-left: dark oak, top-right: oak, bottom-left birch, bottom-right: jungle)

The premise is having the robot move across all 16 blocks and for each of the 16 blocks do robot.compare(sides.down) for each block-item in it's inventory to find one that matches. Notice how the 4 sides on the log square, have the logs placed horizontally instead of vertically. All of the vertically placed wooden logs will compare correctly every time, however all of the horizontally placed wooden logs will fail every time. The rotation of the wooden log aparantly causes the compare to be different. I have not tested this, but I suspect the same issue exists for stairs and other blocks that could be placed rotated or differently in-world.
Edit: further testing shows, that robot.compare() also fails comparing a lit up redstone ore with the redstone ore in it's inventory.

I have also noticed that robot.detect() will for the most part detect lava source blocks as "replaceable", though randomly detect them as "liquid". When ever robot.detect() sees a lava source block as "replaceable", the robot.drain() method will fail to pick up the lava source. Doing the same tests with water works perfectly. I don't know if it is on purpose that lava is reported as "replaceable" and not a liquid, but judging from how robot.drain() acts I'm guessing there might be something fishy there too.

My way of accessing the robot is through:
local bot = require("component").robot

**Comment by MajorGeneralRelativity** [comment]
2 side things.
1. "For later reproduction", with 3D printing?
2. Hi Sharidan, long time no see :P

**Comment by Sharidan** [comment]
I've been recreating some of my old computercraft libaries and utilities; currently developing an extended robot library to support all my old turtle tools on robots. One of the utilities is a custom schematic scanner / builder utility that I used to have. With the schematic tool, you'd have the robot traverse an area scanning/comparing the blocks it passes, to create a schematic which can then be saved to disk. Later on when you need it rebuilt, you fire up the schematic tool again and instruct the robot to build the saved schematic and it'll build it.

The problem I'm facing at the moment is that some blocks do not compare correctly. A turned over log does not compare to the exact same log in the robot's inventory, while an up-right log does. The same problem exists with redstone ore that has been "activated" into it's glowing state vs. a silk touched redstone ore in the inventory. I havent tested it further, but I would assume that the compare equally fails with redstone lamps in their on state. ComputerCraft used to have this problem as well, because "someone" forgot to take these situations into account.

I forgot the name of your IRC channel buddy, sorry.

**Comment by MajorGeneralRelativity** [comment]
#yuonsurvival
Your program looks cool, let me know if you can get it working!

**Comment by thiakil** [comment]
> Blocks are considered identical if the type and metadata match

Rotation is stored as metadata in MC. Unfortunately for your use case, the function is working as documented...

(http://ocdoc.cil.li/component:robot)

**Comment by Vexatos** [comment]
This is, indeed, intended behaviour.
Instead, I added metadata-ignoring fuzzy option to `robot.compare`, see #2180.
