### ISSUE TITLE
redstone.setOutput() propagates signal to the opposite side of a block

### ISSUE THREAD

**Issue by repo-alt** [MightyPirates/OpenComputers#2137]
redstone.setOutput sets also input signal to the opposite side. Happens only with RedLogic installed.

Steps to reproduce:
1. set up a computer with T1 redstone card
2. call lua interpreter
3 lua> component.redstone.setOutput(sides.back, 15)
4. add redstone dust to the front and to the back - there will be 15 level at the back and 0 at the front, so far so good.
5. lua> =component.redstone.getInput(sides.front) 
 will print 15

Tested with 
OpenComputers-MC1.7.10-1.5.20.38-universal.jar 
redlogic-59.1.11.jar

This bug makes it impossible in some cases to use microcontroller as a redstone signal processor, which as I understand is one of the main reasons for its existence.

**Comment by Vexatos** [comment]
I guess any computer-like block should not propagate signals through it. For some blocks like Adapters this functionality is actually useful, so it should only apply to actual computers.

**Comment by Vexatos** [comment]
I wonder if that is a bug in RedLogic.

**Comment by repo-alt** [comment]
It is possible of course, but it can hardly be reproduced in redlogic alone.
Note that redstone.setOutput(sides.back, 15) does not set _output_ signal on the front, but only input

**Comment by Vexatos** [comment]
Apparently the input is being read wrongly in the RedLogic redstone handler...

**Comment by Vexatos** [comment]
The case was basically reading its own output from the opposite side whenever redlogic was installed.

**Comment by repo-alt** [comment]
as usual, the bug is obvious when you see the fix..
