### ISSUE TITLE
Feature Request: Add the ability to make read-only filesystems not read-only and vice versa

### ISSUE THREAD

**Issue by Gavle** [MightyPirates/OpenComputers#2138]
Pretty much what it says in the title. A possible use case would be making your own OS install disk and other such things that you want to write protect. And as far as making it non read-only, that's for the ability to deliberately modify your OS install disk, etc., when you find out you made a mistake with your code. :)

**Comment by payonel** [comment]
openos has `mount -r [LABEL|ADDRESS] [PATH]` for read-only mounting
as for changing a ro floppy into a real floppy -- that is out of scope, technical reasons why we prefer to leave a RO floppy as RO.

**Comment by payonel** [comment]
If we leave loot disks out of this discussion, and just have a readonly only mode on the harware itself, that is doable. I'll reopen and let this ticket live a bit longer :)

**Comment by Gavle** [comment]
I apologize for the long delay in response. Would you be willing to explain those technical reasons for why you prefer to leave a read-only floppy as read-only? From your last statement, I assume you mean that you are willing to add a feature to make a specific hard-drive/floppy drive read-only forever, in every location, regardless of OpenOS mount parameters?

**Comment by Gavle** [comment]
You still have not responded to my questions, which would be nice.
@payonel

**Comment by skyem123** [comment]
The main problem with a loot disk is that it night contain more data than a normal floppy normally could, I think.

**Comment by Gavle** [comment]
That could be resolved by making loot disks permanently read only.

**Comment by xarses** [comment]
Which was exactly what @payonel noted in his comment re-opening the ticket.
> If we leave loot disks out of this discussion

To me what it comes down to once a device has been marked RO, the only way to revert it back to RW should be to re-initalize it (empty craft it) so that its then an empty device again. This would allow for the author to protect modification of the device, and allow for the (eventual) re-use of the device. Otherwise flipping the state would likely get quite complicated.

If you want to prevent the accidental writing of the device, then I would go with @payonel initial response, mount the device RO and remount it when you want to write to it. Otherwise you are asking for a lot with what appears to be limited use.

**Comment by Gavle** [comment]
Making a device hardware Read-Only unless it is erased is an acceptable solution to me. I'd like to be able to flip it back and forth, maybe with some sort of key system, but permanent Read-Only is at least usable.

**Comment by xarses** [comment]
What are you looking to solve by having a hardware toggle that shouldn't be addressed by just mounting a rw device as ro?

**Comment by Gavle** [comment]
Devices marked as read only with a specific password necessary to unlock could allow for secure physical delivery of drives in-game. Admittedly, a hardware toggle is an edge case, which is why I said I would settle for permanent Read-Only.

**Comment by payonel** [comment]
You can lock your floppies and disk drives

![image](https://user-images.githubusercontent.com/6590223/48053531-cb139100-e15f-11e8-9f68-feed636b4948.png)

And we keep track of who locked it
![image](https://user-images.githubusercontent.com/6590223/48053602-fa2a0280-e15f-11e8-9e47-aee147b5fc51.png)
