### ISSUE TITLE
Breaking server rack in Spongeforge does not drop Inserted boards

### ISSUE THREAD

**Issue by Modsojoy** [MightyPirates/OpenComputers#2140]
Was on a server (Switchcraft) with OpenComputers for 1.10.2 and i went to move my server, It dropped the rack but the boards were gone, rip all my materials and programs.

**Comment by payonel** [comment]
I've tested this with our release version of OC for 1.10.2 both in single player and multiplayer - and this bug does not repro for me. I also looked for what version "switchcraft" was using and I couldn't find that documented.
