### ISSUE TITLE
OpenComputers 1.6.4 for MC 1.10.2 client crash

### ISSUE THREAD

**Issue by keanucz** [MightyPirates/OpenComputers#2141]
So basically, I go on my server, there's 3 creative tabs.
Two of them are some other mods.
[When I go on the 3rd one, it crashes.](https://i.gyazo.com/ba5e7b915c81668f9d3dcdff433d9f28.gif)
[In the crash report, it mentions about the OC creative tab?](http://pastebin.com/Ndd24LVa)
The server hasn't crashed, but it's only the client.
The mod is on the server, as well.
EDIT: [Do any mods conflict with OC and maybe crash it or?](http://image.prntscr.com/image/270660f926fd4c67aa25ecbb44100c3f.png)

**Comment by Keanu73** [comment]
#1116

**Comment by Keanu73** [comment]
This issue I think references to: #1116
Thing is, I don't have NEI.

**Comment by Vexatos** [comment]
The crash implies that [there is no tier 1 computer case](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.10/src/main/scala/li/cil/oc/CreativeTab.scala#L10). Strange.

**Comment by keanucz** [comment]
Issue closed, the OC jar was corrupt on the server. Not a client issue.
