### ISSUE TITLE
No reboot button on tablet

### ISSUE THREAD

**Issue by jakemroman** [MightyPirates/OpenComputers#2143]
![screen shot 2016-11-20 at 12 51 31 pm](https://cloud.githubusercontent.com/assets/11775545/20464924/15febd26-af20-11e6-8bf4-8082f0151d33.png)
My tablet was running a program, which crashed.  It is now stuck at this prompt and will not let me enter any keys, is there a way to shutdown a tablet forcibly?

**Comment by Vexatos** [comment]
Shift + Right click should work. Did you try that?

Alternatively, it will shut down after a while if you place it in a chest or any other inventory.

**Comment by jakemroman** [comment]
Thanks! I did try shift clicking, but it was really stuck.  I restarted minecraft since I was on singleplayer and it fixed it.

**Comment by payonel** [comment]
does this crash cause the tablet to be frozen every time? I've tested this and I do not repro this. Also, from your crash I can see that you are not running the latest version of OC, we have a release version you should try if you experience more problems.
