### ISSUE TITLE
cannot use component.redstone.setOutput(sides.front, 15) in a program

### ISSUE THREAD

**Issue by mojo123410** [MightyPirates/OpenComputers#2144]
when in the lua interrupter it works fine and I can even set a variable to it but when using it inside of a program it gives me the response

![error](https://cloud.githubusercontent.com/assets/23643534/20501531/18db4cd8-afef-11e6-9e88-f3c652e171a7.png)

**Comment by Vexatos** [comment]
Looks like you forgot to load the component library.
```lua
local component = require("component")
local sides = require("sides")
component.redstone.setOutput(sides.front, 15)
```
This is being done automatically in the `lua` interpreter, so it's not necessary there.

**Comment by mojo123410** [comment]
thank you I am new to lua programing and I was completely stumped because I have not found much documentation on coding in open computers

**Comment by Vexatos** [comment]
This is more or less standard Lua behaviour. Check out the [manual](http://www.lua.org/manual/5.2/manual.html) (or [the Lua 5.3 version](http://www.lua.org/manual/5.3/manual.html)).

**Comment by mojo123410** [comment]
thank you I will
