### ISSUE TITLE
can not find a way to to wait a time before doing something

### ISSUE THREAD

**Issue by mojo123410** [MightyPirates/OpenComputers#2145]
sorry for bothering you with such a small issue but I have tried many things I can find a few examples I have tried are

while os.clock()<time_point do 
--nothing
end
----------------------------------------------------------------------------------------------------------------------
static int lua_sleep(lua_State *L)
{
    int m = static_cast<int> (luaL_checknumber(L,1));
    usleep(m * 1000); 
    // usleep takes microseconds. This converts the parameter to milliseconds. 
    // Change this as necessary. 
    // Alternatively, use 'sleep()' to treat the parameter as whole seconds. 
    return 0;
}

lua_pushcfunction(L, lua_sleep);
lua_setglobal(L, "sleep");

sleep(1000) 
--------------------------------------------------------------------------------------------------------------------
if you need it I'm trying to turn a Redstone signal on for a time and then turn it off

**Comment by Vexatos** [comment]
Don't use this repo for programming help. Use [the forums](https://oc.cil.li) for that.

To answer your question: Try `os.sleep()`.
