### ISSUE TITLE
swing() failing to break stone level or higher

### ISSUE THREAD

**Issue by BrianEdmonds** [MightyPirates/OpenComputers#2147]
I'm having trouble writing a mining robot, as I cannot get it to break anything harder than dirt, wood, leaves, etc. When I call swing() on a harder block (I tried stone, cobble, diorite, and andesite, with no tool, a stone pick, a diamond pick, or a Tinker's pick) it returns (false, "block") and nothing happens. I've tried in both multi and single player.

Minecraft version: 1.10.2 on Linux(server) and Mac(single)
Forge version: 1.10.2-12.18.2.2151
OC version: MC1.10.2-1.6.0.4
Other mods loaded:
  FastLeaveDecay-MC1.10.2-1.2.3.jar
  GraveStone-Mod-1.5.9.jar
  ImmersiveEngineering-0.10-50.jar
  Mantle-1.10.2-1.1.1.jar
  ServerSideChunkLoader-0.3.2.jar
  TConstruct-1.10.2-2.5.6b.jar
  TinkerToolLeveling-1.10.2-1.0.1.jar
  jei_1.10.2-3.13.3.373.jar

**Comment by Vexatos** [comment]
Are you able to reproduce this with only OpenComputers? If not, it would be another mod causing this.
It works just fine for me.
![See here.](https://thumbs.gfycat.com/PerfectSneakyDogfish-size_restricted.gif)

**Comment by BrianEdmonds** [comment]
Ah, fail on my part. I'm new to OC, and totally missed that the equipped tool, and selected inventory slot are not the same thing. Your video of a bot clearly using a tool clued me in that I must be doing something wrong in that regard. Thanks!
