### ISSUE TITLE
Driver add Forge's Capability to Adapter

### ISSUE THREAD

**Issue by Volune** [MightyPirates/OpenComputers#2148]
Warning: I'm not familiar with OpenComputers.

I'm currently working on a PR for Refined Storage, to implement the network nodes using Forge's [Capability System](http://mcforge.readthedocs.io/en/latest/datastorage/capabilities/).
I've also seen a work for a [RefinedStorage Driver](/davidog23/Refined-Storage-OCDrivers)

Connecting the two ideas, I'm wondering if it would be interesting for OpenComputer's Driver to add new Capability to the Adapter, allowing more possibilities of integration with other mods?

----
Note: I've been re-reading the doc, and noticed the `AttachCapabilityEvent`. So this suggestion may be totally useless.

**Comment by thiakil** [comment]
What capability are you referring to with "OpenComputer's Driver" adding to the Adapter?

**Comment by Vexatos** [comment]
The capabilities system specifically allows doing this... But I don't see how it would ever be necessary.
