### ISSUE TITLE
Userdata support?

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#215]
I need it for #206 :/

**Comment by fnuecke** [comment]
It's planned for 1.3. I have a working prototype, but it'll need some more testing.

**Comment by SoniEx2** [comment]
@fnuecke is there a branch for that or something? I wanna help you test it...

**Comment by fnuecke** [comment]
I'll do some more fixing for 1.2, after that and fleshing out one-three some more I'll push that.
