### ISSUE TITLE
Wireless cards do not always provide the correct distance.

### ISSUE THREAD

**Issue by TomatoCo** [MightyPirates/OpenComputers#2154]
When put under heavy load, wireless cards do not seem to always get the correct distance with the correct payload. Sometimes the distance is even outright fabricated.

https://imgur.com/a/KOUN5

This is the output from my triangulation program. It outputs the beacons it manages to reach, their location, and the reported distance. The first bit is all provided by the payload, the second bit is from the wireless card's signal.

The correct result is -24, 66, 394. When sending requests 2 seconds apart or greater, it always works. If I hammer a bunch through, however, then I start to get incorrect values. None of my beacons are 42.485etc away, but the signal seems to claim that they are. You can see that this changes from beacon to beacon, not necessarily always being the same beacon that reports an incorrect distance. This causes my program to either report no possible triangulation, or to report an incorrect one.

What's the deal?

**Comment by payonel** [comment]
may i see your triangulation source?

**Comment by inklit** [comment]
have you made sure that your application is receiving requests in the correct order?

**Comment by MalkContent** [comment]
Wireless card signal distance increases when there is blocks between the participants.
This distance increase is not static, because it only takes samples rather than getting all the blocks in between.
Anyways, that's my best bet on why you are getting incorrect distances.

**Comment by payonel** [comment]
I feel like knowing more about the test would help both of us.
Something I noticed was that `posresult,16,78,353` is always `58.52` when it comes last in the list, and `42.48` when it is not last in the list.
If `-24, 66, 394` is the expected value it gives me the impression your test objects are stationary. But you didn't tell us so I'm not sure. What assumptions does the source makes about the order of the messages?

**Comment by TomatoCo** [comment]
Position beacon code, designed for microcontrollers http://pastebin.com/aRHHc4LF
Position program code, designed for computers. http://pastebin.com/DrKXJKsD

The beacons are stationary. No assumptions are made or required about the order of the beacons, only that four unique locations are received, not all on the same plane, with their correct distances. I have a unit test (somewhere...) with the trilat function that generates 4 random points, calculates their distances from a fifth, and feeds them to the function and compares the computed and expected positions of the fifth. It works every time I don't run into a new and interesting floating point precision error.

MalkContent, the energy required to send a signal increases with blocks between the participants, but the distance reported does not. Please consult def receivePacket in src/main/scala/li/cil/oc/server/component/WirelessNetworkCard.scala

**Comment by payonel** [comment]
this does not reproduce
i tested with 6 broadcasting in a tight loop -- and i verified their distances did not change as detected on a stationary machine as well as a moving robot, confirming single distance changes as it moved.
reading your code carefully, the suspect must have been some machine 42m from your client machine, which had bad or outdated sign data. It would have been preferable to debug this by printing the sender modem address, to compare owners of these messages to show that the distances weren't actually changing.
