### ISSUE TITLE
Native Lua's computer.addUser doesn't error on invalid arguments

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#2156]
Since bccee0c5a0ac03198ecffbc6181a3e92e316fd6a, computer.addUser was added and also wrapped in a try catch, causing any errors to be instead returned as nil, "message" instead of actually erroring

This is okay and has also been this way for more than 3 years, but is inconsistent:
1. This is the only function that seems to catch and process it's own errors itself
No other function in the computer, component, os, system, unicode, etc apis do this.
2. LuaJ's version of this function does error on bad arguments

The try catch can be easily removed and after testing a custom build without it, no problems noticed besides that it now errors on errors.

The function has three possible behaviors:
1. Error because argument isn't a string (but captured and converted to nil, message)
2. Error because argument is a string but the player is not online (but captured)
3. Return true

For backwards compatibility's sake, the argument type check could be moved out of the try catch but leave the second case the same: nil, "player must be online"

Even if this won't be change, it might be a good idea to change LuaJ's version to act like this one.

opinions?

**Comment by payonel** [comment]
I think the "backwards compatibility" solution you provide is the correct solution even in its own right.
1. bad args: error
2. offline: return nil, msg
3. true
