### ISSUE TITLE
Server Hiccup when opening Computer Case/Other machines

### ISSUE THREAD

**Issue by BSherb** [MightyPirates/OpenComputers#2158]
Opening any form of machine/computer case (not the screens) causes timeouts on every other client but not the one who opened the machine

**Comment by payonel** [comment]
We need repro steps
1. Can you reproduce this problem with a new world with no other structures or setup. Give us a step by step repro please.
2. what version of oc are you using, what modpack, what version of minecraft, what version of forge [on clients and server]?
3. does this repro with oc by itself (i.e. no other mods)?

**Comment by BSherb** [comment]
Well, I figured out the issue. The group I was working with had been designing an Operating System that uses a UI, found out that while the OS is running, opening any object connected to that computer, other than the screen, would cause tremendous lag.
For now we are sticking with non-UI based operating systems xD

**Comment by payonel** [comment]
Ok thanks for the update
