### ISSUE TITLE
os.date() returns the wrong time

### ISSUE THREAD

**Issue by Cycomantis** [MightyPirates/OpenComputers#2159]
When I call print(os.date("%H:%M")) in a loop and use the FTB utilities to change the in-game time to Noon or 6000 ticks, os.date returns 4:00. Should this not be 6:00? When I set it to 18000 using the FTB Utils, os.date() returns 16:00 not 18:00.

Also would it be possible to get the 6000 tick offset added in somehow so that we can record times as they make sense. aka noon is 12:00 not 6:00.

![2016-12-06_14 31 01](https://cloud.githubusercontent.com/assets/3446644/20946702/b10c907a-bbc0-11e6-8960-3c6119998c61.png)
![2016-12-06_14 31 07](https://cloud.githubusercontent.com/assets/3446644/20946709/b7f64b06-bbc0-11e6-9d43-6cc585ecc41a.png)

**Comment by gamax92** [comment]
I believe this may be related to the fact that the host timezone appears to change the resulting dates given by os.date
Example, setting my timezone to +2, `os.date("%c", 0)` gives "Thu Jan 01 02:00:00 1970"
Changing it to -7, `os.date("%c", 0)` now gives "Wed Dec 31 17:00:00 1969"
It should instead ignore the host timezone as minecraft does not have timezones

~~Also, I don't believe the 6000 offset is being accounted for.~~
EDIT: OC already does account for the 6000 offset, the timezone is only a problem.

**Comment by Vexatos** [comment]
The offset might be something that could be accounted for in OpenOS. Paging @payonel.

**Comment by gamax92** [comment]
This should be fixed by PR #2183
Putting in a hack to OpenOS is not a good solution.
