### ISSUE TITLE
Changing font kills background

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#216]
With experimenting on different fonts for chars.png and chars_aliased.png, I've noticed that any font that doesn't seem to be the default one, has the background entirely black.

**An example font png that cause this problem:**
http://i.imgur.com/ALxZBVS.png

**Examples of the problem:**
http://i.imgur.com/nUZ76ro.png
In the above, the background and foreground colors are randomly set, yet only the foreground colors apply.

**EDIT:**
So, this happened: http://i.imgur.com/gC2r1qY.png
Although a different bug, it makes me think the background isn't rendering at all, and not just black.

**Comment by gamax92** [comment]
So, the problem with the fonts, is that they didn't have a white dot at the bottom right of the picture.
http://i.imgur.com/XrIg3cy.png
Fixed version of problematic font.

**Comment by fnuecke** [comment]
Ah right, the magic pixel in the bottom right corner, I completely forgot about that. I actually wanted to try and get rid of that at some point... I'll have to look into that again.
As for the image in the edit, no idea what's going on there, is that gone too, or does this still happen (in a reproducible fashion)?

**Comment by gamax92** [comment]
That texture bug, seems to have gone away and I cannot reproduce it with any of the fonts i have, including the bad ones.

**Comment by Techokami** [comment]
Reminds me of an issue I had the other day, the monitor background texture was [totally glitched](http://i.imgur.com/GGhVca3.png), then resolved itself with a restart of Minecraft.

**Comment by fnuecke** [comment]
@Techokami that looks the same, yes. Hm. It pretty much looks like MC is giving me the wrong textures for some reason... I'll have another look through the code to see if I notice anything that might cause that (texture binding in display lists perhaps, although I thought that was supposed to work...)

**Comment by fnuecke** [comment]
Was able to reproduce this quite reliably under the following condition: open a GUI (term/screen) _without_ seeing a screen's text in-world before (i.e. without looking at the front side of a screen before opening the GUI). Made a change and now I can't reproduce it at all, so I'm hoping it's fixed... we'll see. Either way, it only happened in 1.7, so I'm inclined to say it's because of the mess that 1.7.2 is... so this is a workaround at best.
