### ISSUE TITLE
Power Converter is not working with redstone flux

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2161]
Hi,

I have to say, this mod is incredible.

But I'm having some troubles with energy. The Power Converter does'n accept redstone flux from Immersive Engineering, or even from Solar Flux mod. Robots and computers are kind of over power without the challenge to provide energy for them.

Do anyone have a suggestion?

![screenshot from 2016-12-06 14-25-30](https://cloud.githubusercontent.com/assets/21953503/20979500/5a8ac2a6-bc94-11e6-8106-b16f04544749.png)

**Comment by xarses** [comment]
What versions are you running? RF works fine on Mc 1.7.10

**Comment by xarses** [comment]
There is also likely a log in the console when you connect the power source to the adapter

**Comment by ghost** [comment]
Mc 1.10.2

**Comment by ghost** [comment]
The only thing that appears in log is: Not enough energy.

**Comment by Vexatos** [comment]
I am not able to reproduce this. The power converter can accept RF just fine for me. Are you using the latest version of OpenComputers? (1.6.0.4)

**Comment by ghost** [comment]
I was using 1.6.0.2, I will try de new one.

**Comment by ghost** [comment]
It's working very well in the new version, thank you.
