### ISSUE TITLE
Errors on HermitPack Server

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2162]
Hello, i have my own locally hosted HermitPack server, everytime I join it gives me this message

"There were errors running the class transformer. Please report this, together with your (full) latest FML. latest.log/fml-server-latest.log logfile, thank you!"

Where to I submit this file, to the developers?

Thanks, Josh

**Comment by payonel** [comment]
Adding a link in this ticket to a hastebin paste of the logs is generally a good way of sharing log info. We are the devs, so we read these tickets, thus submitting here is submitting to us.

That said, this is likely a duplicate bug. Using the FTB packs may be slightly out of date, see my last comment on #2132
