### ISSUE TITLE
Computer Cases have 0 RF buffer

### ISSUE THREAD

**Issue by payonel** [MightyPirates/OpenComputers#2163]
oc version: OpenComputers-MC1.10.2-1.6.0.4
pack: ftb Direwolf20 mod pack

@DarkMorford said:

> The computer cases do seem to be correctly handling the RF API (i.e., power conduits connect to them), but they don't appear to have any internal buffer. Using an Analyzer on the computer shows "Total stored energy: 0.00/0.00".
> Connecting a Power Converter block to the computer gives it a buffer of 1000, which fills from the power supply and allows the computer to run, but removing that block drops the buffer back to 0/0 and halts the computer.
> Curiously, if I restart the server any computers that had already been placed have a power buffer of 500, as configured. Breaking and replacing them resets their buffer capacity back to 0, so this seems to only affect newly-placed computers.
>

**Comment by Vexatos** [comment]
This appears to happen _only_ with cases. Racks, Robots and Microcontrollers are just fine.

**Comment by fnuecke** [comment]
It's been too long that I did this, I even forgot to tag the issue in the commit message ...

Fixed via 4ffe6220caa9f3912865778d4ee50c3a3c10194b.
