### ISSUE TITLE
Crashes when something tries to get Tesla Capability for facing null

### ISSUE THREAD

**Issue by Thutmose** [MightyPirates/OpenComputers#2164]
It seems your Tesla capabilities will crash things if facing is null.

Here is where it crashes: https://github.com/MightyPirates/OpenComputers/blob/master-MC1.10/src/main/scala/li/cil/oc/integration/tesla/Tesla.scala#L38  if facing is null, this throws a NPE.

https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/common/capabilities/ICapabilityProvider.java indicates that the facing should be allowed to be null.

**Comment by thiakil** [comment]
Out of interest, what is calling Tesla capabilities with null side?

**Comment by Thutmose** [comment]
in this case, a pokemob causing internal interference to tesla devices.

Theoretically it could also be called from an itemstack or some other entity where side does not matter.
