### ISSUE TITLE
[Request] Make component.modem.broadcast accept a table of ports for simultaneous broadcast

### ISSUE THREAD

**Issue by MyNameIsKodos** [MightyPirates/OpenComputers#2165]
This would allow some semblance of syncing a triggered function, or whatever else the user decides he needs it for.

Naturally, this would be limited to the number of allowed open ports set in the config, with too many ports being open would either error or just close the least recent port(s) to open new ones.

**Comment by xarses** [comment]
I'm not sure what you would need this for other than port scanning. Can you please add a use case or three?

**Comment by MyNameIsKodos** [comment]
Let's say you have 10 players, each with their own computer, and a set of ports assigned to each player for various things for them to use

Now, let's say you have a server that you want to use to distribute information to all the players' computers.  Player A's receive port is 10, Player B's is 20, C is 30, etc etc

I want an easier method of distributing the same information to multiple players simultaneously rather than multiple uses of broadcast.

So instead of 
```Lua
component.modem.broadcast(10, mystr)
component.modem.broadcast(20, mystr)
etc
``` 

I would have something like
```Lua
component.broadcast({10,20,30,40,50,60,70,80,90,100}, mystr)
```

EDIT: Yes I'm aware a for loop would be just as easy, but the table as input already exists for some components anyway

**Comment by Vexatos** [comment]
I don't know; this exact change seems to make the function more ambiguous, if anything. A function doing exactly one thing with exactly one possible set of parameters sounds much easier to understand.

**Comment by iamgreaser** [comment]
It sounds like you actually want multicast on a given port, rather than broadcast to multiple ports at once.

**Comment by MyNameIsKodos** [comment]
No, I want multiple ports to receive the same broadcast at the exact same time using one broadcast, instead of multples.

**Comment by xarses** [comment]
I don't understand why you wouldn't broadcast to the same port then (as it is the normal workflow for broadcast on real networks)

**Comment by MyNameIsKodos** [comment]
Because if all the players used the same port, there'd be a huge amount of traffic on the port, which could potentially break programs they are using that use those ports due to unexpected traffic.

**Comment by Vexatos** [comment]
>unexpected traffic

The idea would be that one computer broadcasts to that port and all the others respond with a `send` instead of a `broadcast`. That way, there would be no "unexpected traffic" whatsoever.

**Comment by MyNameIsKodos** [comment]
Oh for fuck's sake.
