### ISSUE TITLE
robot.swing() with tinker's construct hammers only destroys 1 block

### ISSUE THREAD

**Issue by Thource** [MightyPirates/OpenComputers#2167]
Minecraft version: 1.10.2
Mods:
```
  jei_1.10.2-3.13.2.363
  Mantle-1.10.2-1.1.1
  OpenComputers-MC1.10.2-1.6.0.3-rc.1 or OpenComputers-MC1.10.2-1.6.0.4
  TConstruct-1.10.2-2.5.6b
```

I've tried using a few different kinds of hammer, namely stone and cobalt, but the robot will only destroy 1 block at a time.
It happens on both multiplayer and singleplayer.

I've googled and people are saying that hammers are handled, what could be happening here?

**Comment by ShaunDreclin** [comment]
I'm having this issue too. I used an actually additions drill and it worked as expected, but tinkers hammers are only destroying one block
