### ISSUE TITLE
Computers frozen after leaving Area. (Chunk Unload/Load)

### ISSUE THREAD

**Issue by nexitem** [MightyPirates/OpenComputers#2169]
Everytime I leave the area my computers run in and I come back to them they are frozen and I have to boot them up again. There are no errors in the console.

Versions:
OC: 1.6.0.4
Forge: 12.18.2.2171 universal
Minecraft: 1.10.2

modlist SERVER: http://pastebin.com/6dEKiiQc
modlist CLIENT: http://pastebin.com/9XP2tA9a

I'll help as much as possible troubleshooting this issue.

**Comment by nexitem** [comment]
#1966 **Computers left frozen after traveling past render**
Might be related but I wasn't sure.

**Comment by Vexatos** [comment]
Are they still turned on, just inaccessible, or did they shut down?

**Comment by nexitem** [comment]
They are still displaying what had last been seen but you cant type anything and have to reboot.

**Comment by Vexatos** [comment]
Does it still consume energy in that state? Does the power button show that it is turned on?

**Comment by nexitem** [comment]
The power button indicates That it is off and I have to press only once to turn it on. I don't know if they'll consume energy i cant check until tomorrow but i believe they aren't

**Comment by Vexatos** [comment]
See #2051 for some steps that might help identify the issue.

**Comment by nexitem** [comment]
I will go through the whole list including disabling mods, Ill get back to you on this in 24 hours

**Comment by Vexatos** [comment]
Does this still occur using OpenComputers 1.6.2?

**Comment by fnuecke** [comment]
Should have been fixed in 2751cec8c1526d489976627b4ffa0d6731616ee5. If not, please reopen.
