### ISSUE TITLE
Stargate Tech 2 Abstract Bus card is not visible on servers

### ISSUE THREAD

**Issue by LizzyTrickster** [MightyPirates/OpenComputers#217]
Normal cases can see the card fine and initialise it (makes it get an address) but servers cannot do either. Using OpenComputers-MC1.6.4-1.2.7.340-universal and the latest forge for 1.6.4

server component list
![servercomponentlist](https://cloud.githubusercontent.com/assets/3775521/2747960/c18b4ad6-c799-11e3-8692-9881d85ddc6d.png)

Server
![server](https://cloud.githubusercontent.com/assets/3775521/2747961/c18f15b2-c799-11e3-994a-c09537341a0b.png)

Normal Computer
![normalcomputer](https://cloud.githubusercontent.com/assets/3775521/2747962/c18f52c0-c799-11e3-9292-74506021686a.png)
Computers inventory
![normalcomputerinterface](https://cloud.githubusercontent.com/assets/3775521/2747963/c19020e2-c799-11e3-991b-41e871d48859.png)

**Comment by fnuecke** [comment]
Huh, that's... interesting. I'll look into it.

**Comment by fnuecke** [comment]
Fixed in bbe80bc5.
