### ISSUE TITLE
FTB utils chunk claiming and inventory_controller

### ISSUE THREAD

**Issue by liq3** [MightyPirates/OpenComputers#2172]
All the advanced inventory functions with the inventory controller upgrade (component.inventory_controller) don't seem to work in claimed chunks, even when I'm the one that claimed the chunk. They just return nil and "no inventory". Server is running direwolf20 1.10 pack. I think the mod called FTB Utils does the chunk claiming.

**Comment by Vexatos** [comment]
The inventory controller doesn't know about you, it uses its own fake player. Something appears to be blocking fake players.

**Comment by LatvianModder** [comment]
Try "/ftb team config ftbu.allow_fake_players true"

**Comment by Vexatos** [comment]
Looks like it is indeed on FTB Utils' side. Please test, I will re-open this if allowing fake players in FTBU doesn't fix it.

**Comment by RichieSams** [comment]
Confirmed that "/ftb team config ftbu.allow_fake_players true" fixes the behavior
