### ISSUE TITLE
[1.10.2] Robot's break when writeToNBT is called during move

### ISSUE THREAD

**Issue by bloodmc** [MightyPirates/OpenComputers#2173]
So I did some extensive testing to determine what was causing robot's not moving after entering 'robot.forward()' in LUA mode with SpongeForge installed. It seems when we call 'te.writeNBT' on a robot, it freaks out with the following error

https://gist.github.com/bloodmc/05b51174bf06494a41af8dc8261073d2

We make the call during our snapshot creation method here

https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java#L1447

Now you may ask, "why are we calling this method against your TE?" and the answer is simple, sponge tracks everything including NBT so that we may restore if an action is cancelled.

Information about this issue with SpongeForge can be found here

https://github.com/SpongePowered/SpongeForge/issues/799

**Comment by ghost** [comment]
This issue makes robots on my server useless. :-( Please fix this. Thanks a lot.

**Comment by Vexatos** [comment]
This looks like a bug on the SpongeForge side to me...

**Comment by Vexatos** [comment]
This looks like a bug on the SpongeForge side to me... It doesn't just happen with OC, apparently, but creates issues with various things involving moving blocks. Sounds like something that should be fixed on their side since that type of block isn't really uncommon nowadays.

Am I right in thinking that the duplication bug mentioned in that issue has been fixed? Or is that the one we are talking about?

>it freaks out and never returns to the main thread after the call

That is pretty... vague. What exactly happens? Does it error? Crash? Does the robot crash? Does it shut down? Does anything appear in the logs?

**Comment by ghost** [comment]
See this comment:
https://github.com/SpongePowered/SpongeForge/issues/799#issuecomment-256778136

**Comment by Vexatos** [comment]
So... The robot actually fails to move but is still working perfectly fine, just that it spawned an unusable duplicate in the direction it wanted to move to? Or did it spawn the duplicate in the position it used to be in while having successfully moved forward?

Do you know whether the duplicate has any NBT data at all? What does it drop when being broken?

**Comment by ghost** [comment]
Due fail nbt save is robot "moved" without nbt data. See screenshots on the mentioned comment or install spongeforge to mods.
https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2

**Comment by Vexatos** [comment]
I still don't know whether the command actually failed or what exactly happened at all. I cannot test it myself due to various errors with SpongeForge in the OC dev environment.

**Comment by bloodmc** [comment]
I updated my comment with actual error during te.writeToNBT

**Comment by ghost** [comment]
please merge into 1.10.2

**Comment by fnuecke** [comment]
Now!
