### ISSUE TITLE
[1.10] Not reading inventory

### ISSUE THREAD

**Issue by Bellwar** [MightyPirates/OpenComputers#2177]
I need the robot look into inventory and see the size. 
I see no way he can throw back on me "no inventory" for this:

![set up](https://cloud.githubusercontent.com/assets/9407653/21076370/db33755c-bee6-11e6-9e79-38bf87dcdbc4.png)

and this code (Note: I am now speaking only from start to line print, nothing about the loops)

![Program](https://cloud.githubusercontent.com/assets/9407653/21076383/24be7352-bee7-11e6-8c6d-f37c9af69441.png)

What is wrong with it?

**Comment by Vexatos** [comment]
Which version of OpenComputers are you using?
Which other mods do you have installed? Do you have any mod that might block access of other players? (the robot technically counts as a different player.) If you have FTB Utilities installed, maybe this is a duplicate of #2172 and you can try the solution there.

**Comment by Bellwar** [comment]
Oh yeah it was it I will close this and go spam FTB for that crap, why isn't default false, even then I AM on single player it should notice and turn all security crap off... 

Thanks.

**Comment by Vexatos** [comment]
Apparently fake players _are_ allowed by default in more recent versions of FTB Utils, it's just that the config doesn't update automatically if it was generated with an earlier version so packs devs have to do it themselves.
