### ISSUE TITLE
[Suggestion] Add a RF to EU Converter (and EU to RF)

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#2179]
Hello. I ask that to you because you're the last one that still allow EU power, since Immersive Engineering removed support of EU in 1.8. On our server, we need a way to convert RF to EU and EU to RF and there is really no way to do that. As you're the last mod that still support IndustrialCraft, can you add these machines even if your mod is intented to do that at the begening? Thank in advance!

**Comment by ExDomino** [comment]
Or is there a way to extract OpenComputer internal energy to another form of energy? Exactly the contrary the PowerConverter does.

**Comment by Vexatos** [comment]
OC won't convert energy back from its internal system. See #1702.

**Comment by ExDomino** [comment]
Is it a way to manage your digital rights? Often, players want something that mod author refuses.
I'm really wondering what is the reason here. Except that IndustrialCraft is really bugged and I can't explain why it was added on our modpack FTB Infinity Lite.

**Comment by ExDomino** [comment]
Is it a way to manage your digital rights? Often, players want something that mod author refuses.
I'm really wondering what is the reason here. Except IndustrialCraft is really bugged and that I can't explain why it was added on our modpack FTB Infinity Lite.

**Comment by Vexatos** [comment]
To put it simple: OC is a computer mod. Power conversion is not something it should be doing.

**Comment by bookerthegeek** [comment]
@ExDomino you could, you know,  use ic2 to generate your power?  Shocking right? And it is only buggy if your server admins don't know how to work sponge/forge configs about chunk loading garbage collection.

**Comment by ExDomino** [comment]
How to fix the problem then? How to fix my bug about IC2 cables? How to config forge garbage collection to fix that bug? Thank you in advance!

**Comment by bookerthegeek** [comment]
Please reread my post to the answers to you question. As the issue with the cables comes from the chunk garbage collection and not IC2.

You're very welcome.

**Comment by ExDomino** [comment]
I would like to say what to say to my server admin to fix the problem.

**Comment by bookerthegeek** [comment]
Tell them to turn off the chunk garbage collection sponge.

**Comment by ExDomino** [comment]
We're on Forge. We don't have Sponge yet. What line on what file we have to modifiy?

**Comment by bookerthegeek** [comment]
@ExDomino Sorry, if your server admins don't know how to read and configure configs, they need to learn. I'm not going to teach them third hand.

@Vexatos Sorry to clutter your tracker. Love the mod. :) Keep up the good work!

**Comment by ExDomino** [comment]
So you refuses to help me to fix the problem? What do you want in exchange? We did a lot of research and we cannot find any clue about this bug and you have the solution but you want to keep it secret. -_-

**Comment by payonel** [comment]
@ExDomino you have valid concerns, but please consider
1. The initial reason for this bug report/feature request was for OC to provide a power output converter between EU and RF. @Vexatos has stated we are not adding that to OC. I understand your desire to have that but it isn't coming from OC.
2. Your discussion about bugs in another mod, and the potential resolution of those bugs with @bookerthegeek is not relevant to this post nor to this github repo. Also, @bookerthegeek - don't be rude (or passive aggressive) here. Our repo is not your soundboard for attitude. Help if you have helpful comments.
