### ISSUE TITLE
remount "/" with internet card

### ISSUE THREAD

**Issue by jrb0001** [MightyPirates/OpenComputers#218]
After unmounting everything and remountig a harddisk as "/", some directories extended by the internet card are still present.

test.lua:
    local fs = require("filesystem")
    -- umount
    for proxy, path in fs.mounts() do
        fs.umount(fs.get(path))
    end
    -- mount harddisk
    local proxy, reason = fs.proxy("42cff8b6-22da-46d6-b3ba-d25513f20705")
    if not proxy then
      io.stderr:write(reason)
      return
    end
    local result, reason = fs.mount(proxy, "/")
    if not result then
      io.stderr:write(reason)
    end

![unbenannt](https://cloud.githubusercontent.com/assets/2380263/2748887/cb3c387a-c7de-11e3-9d38-02ebd70d4f6f.PNG)

![unbenannt2](https://cloud.githubusercontent.com/assets/2380263/2748886/c08f1f78-c7de-11e3-949a-d04c1bde0c34.PNG)

**Comment by fnuecke** [comment]
Yes, that's because of a) OC symlinks are purely virtual, meaning they don't "need" and underlying real file system, and b) they are created and deleted by the autorun in the internet card's fs. You'll have to kill them off manually.
