### ISSUE TITLE
[3rd party] Entity Render Crash

### ISSUE THREAD

**Issue by Discomanco** [MightyPirates/OpenComputers#2182]
So first off, I need to say that this is not a problem with OpenComputers itself, but it is affected, and we cannot find the root of this problem.

We are on a 1.10.2 server, with a lot of mods, on Forge 12.18.2.2151.
Whenever an entity with an AI (seems to be the only ones affected) such as Railcraft Locomotives, Mekanism Robits and OpenComputers Drones are placed, the client instantly hardcrashes.
We have not tried to try mods one by one, since we have over 150 mods active on the server, and don't have the time for it, due to RL commitments.
The crash occurs for anyone within its render range. Luckily the entities can be killed with some commands, but does require another mod to be on to do so.
This does not happen in SinglePlayer, where everything functions as it should.

Crashlog: http://pastebin.com/Zt2HXkv4

I am writing this for some help, maybe a lead/solution on how to fix this, or where to report this.
I have not been able to find any reports of anyone with the same issue.

**Comment by Vexatos** [comment]
OpenComputers does not appear in that crash log at all. It seems to be related to locomotives. Please provide  a log mentioning OpenComputers instead.

**Comment by Discomanco** [comment]
Yeah, I realise that, however we had the same problem some months ago. Exact same crash log (with the Drone entity instead of the locomotive), with the same trigger (as soon as you put it down, or got in range of it).
However, I can't seem to make a crash happen again, so maybe it already got fixed?
Of course I had been hesitant to use the drone due to the earlier crashes.

I'm trying to fetch an older crashlog from one of our server members, if it is of interest anymore

**Comment by payonel** [comment]
no repro
