### ISSUE TITLE
Geolyzer not working correctly with Beetroot

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2184]
Hello,

I have a farmer robot that uses analyze growth from Geolyzer. It works like a charm with potato, wheat and carrot, but it's getting 0.42 instead of 1 for a fully grown Beetroot.

I'm using Minecraft 1.10.2 and Opencomputers 1.6.0.4.

**Comment by payonel** [comment]
closed with https://github.com/MightyPirates/OpenComputers/pull/2896
