### ISSUE TITLE
[feature request] Robots should be able to re-init hard-disk

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#2187]
I was playing with a headless robot, and realized I forgot to put the needed programs on the hard-disk I installed with it, so I figured, no problem I'll stick it into the charger and it will show up as a device on my computer and I can write it that way(like a tablet), nope. Then I remembered we can recraft the bios, so why not the hdd, nope. So now I have to disassemble my robot to add a program to the disk and possibly break a component in the process.

So I'd request that either 
* We allow the disk to be recrafted into the robot like the bios can be
* We allow the robot's disk to be exposed in the charger like the tablet's disk is.

**Comment by Vexatos** [comment]
If anything I'd prefer the latter option. Re-crafting the HDD seems weird as that would go against the purpose of the assembler. I guess you can think of the HDD being firmly installed in the robot, while the EEPROM of a microcontroller or drone is accessible through some slot from the outside.
Against the latter option would be that I always thought of the charger to be charging without physical contact over a short distance; that would also make it impossible/inappropriate to have any physical peripheral connection.

**Comment by MOXFan** [comment]
I think it would make sense to allow players to insert a robot into the same slot that tablets are charged in, and allow disk access in the same fashion.  That way one could access their disk with manual intervention but the robot still wouldn't be accessing cabled networks.  I was actually surprised this doesn't work for manual charging, also.

Another option would be a floppy drive upgrade.  That would have the added benefit of making user-created floppies more useful.

**Comment by Vexatos** [comment]
@MOXFan You can already install Disk Drives into robots. They count as a container and not an upgrade, as they add an additional slot to the robot's inventory.

Allowing robots to be placed in a charger does sound like a good solution. Right now, the slot only accepts tablets.

**Comment by MOXFan** [comment]
Oh, thanks for the tip!

**Comment by payonel** [comment]
accepting the feature to allow robots to be placed in the charger to give access to its hdd

**Comment by payonel** [comment]
looked into implementing this and honestly, the robot-as-item with access to its component hard drives is a mess to the way our robot entities work, so i'm going to pass on this
