### ISSUE TITLE
Unable to network with ComputerCraft via Relay

### ISSUE THREAD

**Issue by TopOrDrop** [MightyPirates/OpenComputers#2188]
ComputerCraft does not seem to recognise the OC Relay as any form of peripheral, and so is unable to wrap to it or interface in any way. 

Context: I'm using ComputerCraft Turtles to swarm mine, and send information/receive commands from a ComputerCraft computer. I placed the CC computer adjacent to the OC Relay and hoped to be able to send messages between them. I wanted to create a user interface to control the turtles on the OC screens because they have a higher resolution and I just prefer OC interface.  

Any help would be greatly appreciated!

Currently running CC[1.80pr0], CCTweaks[1.2.4], OC[1.6.0.4] & OC(core)[1.6.0.4]

**Comment by inklit** [comment]
Does this work on CC 1.79? CC1.8pr0 is very buggy and SquidDev's patches to it may not work well with other mods trying to interact with it.
If not, I'm not sure that this is an intended feature.

**Comment by TopOrDrop** [comment]
According to the OC Wiki under the Switch block (which was replaced by the Relay): "The Switch block also serves as a ComputerCraft peripheral, providing an interface imitating that of ComputerCraft's (wired) modems. It will forward network messages sent from ComputerCraft to the OpenComputers side, which can be received if a network card is installed. It will also receive OpenComputers' network messages and push a corresponding signal in CC computers attached to the adapter." and I haven't found any documentation of this feature being removed. I will try on CC 1.79, but sadly I won't be able to implement it into a MC1.10.2 world. Thanks.

**Comment by TopOrDrop** [comment]
Tested on Minecraft 1.7.10 with CC[1.7.5] and OC[1.6.0.9] and it works flawlessly.
Also tested in MC 1.10.2, without any additional CC Mods (removed CCTweaks) and it still doesn't work.

**Comment by inklit** [comment]
It may be that it simply isn't using the correct CC libraries for 1.10.2 (considering they dont exist).

**Comment by gamax92** [comment]
That's probably why:
master-MC1.10's build.gradle has CC commented out
while master-MC1.7.10's build.gradle does include CC

Which makes sense, given that there is no official release of CC for 1.9.4 or 1.10.2, only a ~~beta~~ alpha.
It _**could**_ be built against it right now seeing that dan200 did put the ~~beta~~ alpha on curseforge, but probably best to wait for CC 1.8 to get more stable or have an official release.

**Comment by inklit** [comment]
It's stable using hacked together patches by SquidDev, but I dont reckon OC should build against those. Building against the beta would certainly work though.

**Comment by Vexatos** [comment]
@gamax92 It's on curseforge as an alpha, not even a beta. And that's for a reason, it's quite buggy.

**Comment by inklit** [comment]
@Vexatos it is more than just "quite buggy", it is **unusable**. 

I am running a production server stable using patches that fix it though.
Obviously this is unsupported and not official whatsoever, but it is certainly possible to run it stable. 
You can find those here: https://dl.bintray.com/squiddev/maven/org/squiddev/unborked/

As far as it's API goes, it works just fine. I'm running other peripheral mods that are built against the 1.80pr0 build and they seem to work.

**Comment by payonel** [comment]
we have added CC support back in 1.12, should also work with squiddev's cc as it uses the same pkg name
