### ISSUE TITLE
Tablet not see card in card container

### ISSUE THREAD

**Issue by Endag** [MightyPirates/OpenComputers#2192]
**OC version:** OpenComputers-MC1.10.2-1.6.1.6
**Forge:** forge-1.10.2-12.18.3.2185

**Bug summary:**
Title says it - tablets with card container upgrade not see any (internet, wireless, data) cards that are placed in this slot

**Steps to reproduce:**
1) Assemble tablet with _card container_ upgrade
2) Shift-click with assembled tablet and put internet card (for ex.) in slot
3) boot up tabled
4) run _components_ utility to check available components

_Result:_
see no signs of _internet_ component
_Expected result:_
See and able to use cards that placed in external card container

**Comment by GorgWorgington** [comment]
I'm having the same problem with upgrade containers as well.

**Comment by Vexatos** [comment]
I am unable to reproduce this issue... Everything works as expected.

No internet card:
![2016-12-29_12 44 38](https://cloud.githubusercontent.com/assets/4135064/21543163/01d20174-cdc4-11e6-8647-7a136013eafe.png)
Adding the card:
![2016-12-29_12 44 45](https://cloud.githubusercontent.com/assets/4135064/21543166/07fdf83c-cdc4-11e6-8f26-989fe60e2327.png)
Now with card:
![2016-12-29_12 44 59](https://cloud.githubusercontent.com/assets/4135064/21543168/0d9cc7a0-cdc4-11e6-893b-a5aea654f15b.png)
As you can see, the component has been properly added.

**Comment by Endag** [comment]
My bad, didn't test it properly in this-mod-only environment.
But i managed to nail to source of problem - it's Quark interference.

This log shows some problems between OC and Quark https://gist.github.com/Endag/1ebbb0f94f4d0a21f2a618369766b5e8

I did couple tests and get following results:
1. if you place card with **no Quark installed** the card is registering and works fine
2. if you after installing card install Quark and reload tablet the card is still working fine, BUT:
2.1 I couldn't manage to remove that card - it seems to be pulled out of slot, but when i reopened my inventory there was no card not in tablet slot neither in my inventory but it was **still in components list and working**
2.2 if you try to install a fresh new card (with no uuid assigned) into tablet when Quark is installed after booting tabled card will be still without uuid as it was never been in any computer

Based on this results i reached following conclusions:
Quark inventory enhancement module somehow creates the duplicates tablet's original inventory and user always interacts with this mirror but tablet still working with original inventory so it never "see" any changes made.

Although I do not know and cannot speculate which of mods (if not both) does something wrong with inventory handling which is causing this error.

I will cross-report this issue on Quark's tracker as well. (https://github.com/Vazkii/Quark/issues/272)

**Comment by Vexatos** [comment]
Please try reproducing it using the next development build (MCP servers are down currently so it can't compile right now).

**Comment by Vexatos** [comment]
Thanks for testing. Please try reproducing it using the next development build (MCP servers are currently down so it can't compile right now). The error should be fixed but I don't know whether it is relevant to the issue itself. If the issue persists, the rest needs to happen on the Quark side.

**Comment by Vexatos** [comment]
The build worked. Please test using 1.6.1.64-dev or later.

**Comment by Endag** [comment]
It looks fixed. Waiting for official release with this fix (not really urgent).

Thank you.
