### ISSUE TITLE
Motion Sensor line of sight

### ISSUE THREAD

**Issue by feryaz** [MightyPirates/OpenComputers#2193]
The docs say the motion controller only fires the event if it has line of sight to the target. What exactley does that mean? I have one on top of a screen that is on the computer. To try it out I put cobblestone all around the motion sensor, but it still fires the event as if it could see me.  Is that a bug or am I doing something wrong?

**Comment by Vexatos** [comment]
Try adding a layer of cobblestone one block further away from the sensor (so that there is one block space between the wall and the sensor). The motion sensor's own area is slightly wider than the block space, so it might still be able to detect things through blocks directly adjacent to it.

**Comment by payonel** [comment]
we've made fixes and improvements to the motion sensor code, this should be fixed or improved
