### ISSUE TITLE
Update to 1.11

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#2195]
Well, I guess this has to be done eventually. For a mod as big as this, it will require quite a lot of work so I am keeping this here for tracking progress if there ever is any. Updating will cost quite a lot of time so I will probably do it in small batches. [master-MC1.11](https://github.com/MightyPirates/OpenComputers/tree/master-MC1.11) is a thing now and I will start working on it eventually. I'll need to think about how to efficiently handle adapting to the ItemStack changes, issues arising from those are not trivial to find in Scala.

**Comment by Vexatos** [comment]
I guess this is done now.

**Comment by Alaberti** [comment]
🤔
