### ISSUE TITLE
Copying from clipboard is limited to 256 lines

### ISSUE THREAD

**Issue by DTV96Calibre** [MightyPirates/OpenComputers#2197]
OpenComputers version: 1.10.2-1.6.1.6
When using the middle button on the mouse to paste text into the edit program in OpenOS, only the first 256 lines in the clipboard will paste.

**Comment by Vexatos** [comment]
See [this config option](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/application.conf#L1204-L1207).

**Comment by DTV96Calibre** [comment]
I see,
thanks
