### ISSUE TITLE
[Suggestion] Add Printers

### ISSUE THREAD

**Issue by CoolMan119** [MightyPirates/OpenComputers#2199]
I know that OpenComputers has 3D Printers. I really like them but what I always wanted is a printer that can print text onto paper. There would be 3 tier's of ink. Black and white, Grayscale, and full color. It will use a simple printing API also.

 

I would be really happy if OC added this! :)

 It would also be nice if they could print images ;)

**Comment by LizzyTrickster** [comment]
There's a mod made by @CaitlynMainer called OpenPrinter which does printed pages.
It doesn't do images but if it did it'd have to be pretty low-quality

**Comment by CaitlynMainer** [comment]
https://minecraft.curseforge.com/projects/openprinter
