### ISSUE TITLE
Random Computer Shutdowns

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#22]
I can turn on my computer (which due to a ton of capacitors has an ample supply of electricity I believe) and leave it going for 15-20 seconds before it randomly shuts down (freezes/crashes).
![2013-12-23_21 57 13](https://f.cloud.github.com/assets/5545404/1804296/1ea6d536-6c47-11e3-8bc9-4f4ba50d9f30.png)

That is the edit program being used and randomly crashing, usually before the crash the cursor will lag or keyboard input will lag.

**Comment by pingbird** [comment]
did you check the console for any errors?

**Comment by fnuecke** [comment]
Also, does it print the last error message when using the analyzer on the computer case? Aside from a capacitors you'll also need some power source to feed them, or you can still run out of power.

**Comment by ghost** [comment]
Confrim at 1.0.4 with Robot + edit program, I never see the any error in server/client console.
In the 1.1.0 pr1, No sudden shutdown.

**Comment by fnuecke** [comment]
Closing due to lack of feedback from original reporter. Please open a new issue if this should happen again and reference this one in it.
