### ISSUE TITLE
Documentation: event list

### ISSUE THREAD

**Issue by Xfel** [MightyPirates/OpenComputers#220]
A list of possible events/signals and their parameters would be vital. Currently, I can only search through the source, which takes a lot of time, or look which events existing programs used, which is incomplete. A man page would also be helpful.

**Comment by fnuecke** [comment]
That [page exists on the wiki](https://github.com/MightyPirates/OpenComputers/wiki/Signals). A manpage might be a neat addition... if I ever find the time (or someone else writes it?)

**Comment by Xfel** [comment]
Thank you, that's exactly what I was looking for.
