### ISSUE TITLE
Hard drive Corruption

### ISSUE THREAD

**Issue by Natches** [MightyPirates/OpenComputers#2200]
i have an hard drive tier 3 with a lot of program and all is gone, the drive is now blank, i don't know why, it's like the drive format himself and i can't recover my program. Someone know if we can get them somewhere on computer?

**Comment by Vexatos** [comment]
It will be in your world save in the `opencomputers` directory somewhere.

**Comment by magik6k** [comment]
Likely linked to #2092

**Comment by Natches** [comment]
Thank you

**Comment by payonel** [comment]
assuming #2092
