### ISSUE TITLE
Easier relocation of computers

### ISSUE THREAD

**Issue by NickNackGus** [MightyPirates/OpenComputers#2202]
Currently, when moving a desktop, all the components pop out when broken, similar to a vanilla chest. This seems unrealistic and inconvenient. Robots, tablets, and servers can all be moved with their built-in components intact, although robots drop what was in their inventories. Similarly, the real-world computers they are based on can also be moved around without being taken apart.

It would be nice if computer cases could be moved around without taking out their components - I don't particularly care if it's with any tool or by shift-right-clicking with a scrench.

**Comment by Vexatos** [comment]
Unlike robots and tablets, computer cases do not need to be assembled; components are not firmly installed. A server is the "second tier" of cases, allowing moving unassembled computers easily; and they still have to be installed in a rack after all. Making cases easy to move would make them much more superior to robots for anything that does not need motion and especially make microcontrollers a lot less useful, them being easy to move being one of their major advantages.
