### ISSUE TITLE
Possible issue or Feature request: AE2 integration in MC v1.10.2

### ISSUE THREAD

**Issue by wylderhoads1809** [MightyPirates/OpenComputers#2206]
I've seen a lot of places online that OC should have AppliedEnergistics2 integration via an adapter; however, I cannot get any block from AE2 to show up when checking "components". 

I'm using version OpenComputers-MC1.10.2-1.6.1.6.

I can post screenshots if necessary to try and solve this issue.

**Comment by Vexatos** [comment]
Not sure it should be re-added yet, considering the builds for 1.10 are still considered "alpha"...

![From the website](https://cloud.githubusercontent.com/assets/4135064/21541708/d99eade8-cdb8-11e6-9af0-aa45b013dcfe.png)

**Comment by wylderhoads1809** [comment]
Ah I see, I figured that since it was a direct port it would still have this kind of capability. I can understand waiting until it is a full release. In the meantime, perhaps something similar with refined storage? I think that is in full release at this point. or should this be a suggestion for them on their github?

**Comment by TheMrCaveman** [comment]
Mm, I don't think much will be changed since all major 1.10.2 modpacks now contain ae2. It is very much missed here;)

**Comment by arcanefeenix** [comment]
This issue still exists in version 1.6.2.7 of OpenComputers with version rv4-alpha-11 of AE2.

![2017-04-07_09 56 21](https://cloud.githubusercontent.com/assets/804357/24803671/efc91612-1b79-11e7-8162-1bc854b0f9b3.png)
![2017-04-07_09 59 56](https://cloud.githubusercontent.com/assets/804357/24803672/efca780e-1b79-11e7-9991-859b57ccdbe0.png)

**Comment by mvodanovic** [comment]
still no? :(
(1.6.2.7, MC 1.10.2)

**Comment by xarses** [comment]
1.6.2.7 is nearly 6 months old, no its not supported there.
That said, #2465 landed a few hours ago, and is available in the dev build 116 on [jenkins](http://ci.cil.li/view/OpenComputers/job/OpenComputers-dev-MC1.10/)

**Comment by mvodanovic** [comment]
Tnx! Tried both 115 and a newer one, 116, and both of them resulted with a crash. Created a ticket for it:
https://github.com/MightyPirates/OpenComputers/issues/2516

**Comment by stephan48** [comment]
For completeness. 

Theres a problem with the integration in this version with all "Partial" Entities like Export/Import/Storage-bus.
Please see that bugreport/the mentioned pull request https://github.com/MightyPirates/OpenComputers/pull/2519 for a fix. :)

-- stephan

**Comment by payonel** [comment]
support added for 1.10 and verified (not every block and everything function, but spot checking and things mentioned in this ticket)

if a new 1.10 api is failing for ae is found, please open a new ticket with specific repro
thanks
