### ISSUE TITLE
multiple Term API to multiple Screen...

### ISSUE THREAD

**Issue by alwaeles** [MightyPirates/OpenComputers#221]
I was looking for a simple way to redirect the "term" API to a screen other than the default, but unfortunately I have not found ... 

I guess it would be practical to incorporate this functionality, for example:

``` lua
local component = require("component")
gpu = component.gpu
term2 = term.redirect(gpu)
term2.setCursor(2, 2)
term2.write("Hello second screen !")
```

thank you

**Comment by fnuecke** [comment]
Thanks for bringing that up; "instances" of term is something I had been thinking of adding, but would probably have forgotten. I'll see if I can get it into 1.3.

**Comment by Wuerfel21** [comment]
component.setPrimary() should do(untested)

**Comment by Wuerfel21** [comment]
Or binding the gpu?

**Comment by alwaeles** [comment]
Hello I just see just to remind you to integrate support for "instances" in the API, thank you

**Comment by fnuecke** [comment]
No need for reminders. If the issue is still open I haven't forgotten about it.

**Comment by WazWaz** [comment]
The tooltip for Server items says they can support multiple remote terminals. Currently these just seem to be mirrors of the one GPU output and shared keyboard input, so this seems related to this Issue. If not, the documentation doesn't seem to make it clear how to make any other use of multiple remote terminals on a single Server. A Tier 2 server only has 3 card slots, so multiple GPUs can't be the way to get 4 terminals.

**Comment by fnuecke** [comment]
That's a different topic, really. The remote terminals are intended to share display and input. It's merely a way to allow multiple players to interact with the same server. Laptops/tablets/whatever incarnation of portable device it'll be will provide more flexible remote control capabilities.

**Comment by fnuecke** [comment]
The last few times I thought about this I ran into obstacles in OpenOS and stopped. Trying to retroactively add this to OpenOS would, from what I can estimate, break too much. It's more realistic for someone to write an alternative OS that supports this.
