### ISSUE TITLE
Forums Insecure Connection

### ISSUE THREAD

**Issue by brisingraerowing** [MightyPirates/OpenComputers#2211]
When I try to go to the forums, Firefox gives me an Insecure Connection error, stating that the website is configured incorrectly.

@LizzyTrickster

**Comment by Endag** [comment]
Looks like someone forgotten to re-issue SSL certs.

Just passing by

**Comment by LizzyTrickster** [comment]
I am aware of the SSL cert having expired, been ill all day so haven't had a chance to look at it

**Comment by LizzyTrickster** [comment]
It is now fixed, the certs were renewing I had just told it to use the wrong cert ¬_¬

@Vexatos mind closing this ticket?

**Comment by brisingraerowing** [comment]
@LizzyTrickster I hope you feel better soon. Being sick is no fun.
