### ISSUE TITLE
"touch_up" signal

### ISSUE THREAD

**Issue by malucard** [MightyPirates/OpenComputers#2213]
I suggest you add a "touch_up" signal or similar; it's very useful for UIs. Without it I can't know wether the user is holding the mouse button or has already released it, so it might be released before a drag event (for drag 'n drops), plus it looks weird when a button is released but you didn't release the mouse button.

**Comment by payonel** [comment]
hmm, what if we just sent the "drop" event for the release, even if no drag event had occurred -- in real life, UI libraries don't have "drop" events that are distinct from "release" or "mouse up"

so a mouse click would be 2 events: touch, followed by drop

and with drags in between: touch, drag, drag, .., drop

I would prefer this to having an entirely new event "touch_up"
Originally, I think it would have been cleaner to have "touch_up" in stead of "drop", but I'd rather now reuse "drop" than make a new event

**Comment by malucard** [comment]
A "mouse_pos" one would also be useful for highlighting buttons when hovering, but I think removing drag and drop or adding more cases in which they're triggered would break backwards compatibility, not sure if that's a problem though since very few OC programs use them

**Comment by payonel** [comment]
adding an additional drop event would not break reasonable code, imho. sure I could come up with code that would be broken by such a change, but I feel this is a reasonable instance when "drop" could be returned. User code shouldn't expect drags before drops, that would be messy

**Comment by malucard** [comment]
I just hope this would be accepted

**Comment by payonel** [comment]
for review https://github.com/MightyPirates/OpenComputers/pull/2406

**Comment by malucard** [comment]
Great, thanks

**Comment by payonel** [comment]
closed by 1ce5e06df2171e12e4a078f72e7a025132323356
