### ISSUE TITLE
Weird text (cut off)

### ISSUE THREAD

**Issue by malucard** [MightyPirates/OpenComputers#2215]
The text displayed on a 160x90 screen is cut off at the sides, and I can't read it properly. 50x16 is fine, so I figured it's because of my (real life) 1366x768 resolution, which is not low, but is an odd number for a screen resolution.

Is there any way to fix it? Screenshots tomorrow, my computer is off right now.

**Comment by gamax92** [comment]
160x50 requires that you have at least 1280x800 resolution (160\*8 x 50\*16), of which your screen is too small.

**Comment by malucard** [comment]
Then I suggest adding a way to see it on a smaller resolution, maybe a lower resolution font, it's really annoying that I can't see it properly.

**Comment by funniray** [comment]
You can just do resolution  50 16 in shell, or make a startup program that runs component.gpu.setResolution(50,16)

**Comment by malucard** [comment]
I don't want a low resolution. I want to run at 160x50, that's why I posted this.

**Comment by fnuecke** [comment]
So basically "I want a higher resolution than my real life screen can display"?

Anything less than 1920x1080 *is* low. Get a better screen. Or use a lower OC screen resolution.
