### ISSUE TITLE
Integration with Ender IO bundled redstone not working

### ISSUE THREAD

**Issue by Zarkov2** [MightyPirates/OpenComputers#2217]
Minecraft version 1.10.2 
OpenComputers version 1.6.1.6
(Direwolf20 1.10 pack v1.2.2)

When an Insulated Redstone Conduit from Ender IO is connected to an OpenComputers case or Redstone I/O block, the conduit does not support redstone color selection. If the conduit is attached to a computer case that is turned off, it will have color selection. However, after starting the computer and causing a block update, the color selection support is removed. For the Redstone I/O blocks, the non-color conduit is always displayed.

**Comment by Zarkov2** [comment]
Error on my part, closing.

**Comment by nhoad** [comment]
I've got the same issue and I'm having trouble figuring it out - mind telling me what I'm missing? :)

**Comment by xarses** [comment]
Bundled cables require a T2 card or the Redstone block. Otherwise, you should open you're own issue and better detail your situation, versions, setup etc...
