### ISSUE TITLE
Crash with Computercraft floppys

### ISSUE THREAD

**Issue by Hobby-boy** [MightyPirates/OpenComputers#222]
When I put a Computercraft floppy into the floppy drive, and turn the computer on, the server crashes with this crash report, closing minecraft instantly.
http://pastebin.com/2Tzum75c
I'm using Computercraft 1.58 and OpenComputers 1.2.7.

**Comment by Techokami** [comment]
Have you tried updating to ComputerCraft 1.63?

**Comment by fnuecke** [comment]
Hmm, I can't reproduce this, even did a clean MC install with just OC and CC in it, exact same versions you have. You could try a dev version of OC or, as suggested above using a newer CC version.

If you can, please zip and upload your FML log somewhere, I'm guessing the methods are stripped by a class transformer (possibly OC's), and that might help me figure out why it thinks that's a good idea, even though CC is present... thanks.

**Comment by Hobby-boy** [comment]
Here is the FML log (this was when I tested it in single player): https://db.tt/gLCvvVdA That was when I put the disk in the drive, and turned the computer on.
When I restarted the game and logged into the world, I got this crash: http://pastebin.com/Ld7A7URV
This is FML log from when I started the world up after downgrading opencomputers to 1.2.4:  https://db.tt/BrqyDeRx

**Comment by fnuecke** [comment]
Hmm, nothing in there indicates the methods are being stripped... could you try if this also happens if you don't have any other mods in there? If it doesn't, it's _probably_ some other mod shipping another version of the OC API... perhaps. It's hard to say, I'm afraid.

The second thing is unrelated, see #31.

**Comment by Techokami** [comment]
Have you tried this in a new world file? Using new mods in old world files tends to cause issues due to the new ID-less block and item system in Minecraft 1.7.2.

Sent from my Windows Phone

**Comment by Hobby-boy** [comment]
I've found that Calclavia Core 1.2.0.323 also comes with the OpenComputers API, so I'll try deleting it, and see if it fixes the crash.
Update: That fixes the crash, I can now interact with computercraft floppys.

**Comment by Hobby-boy** [comment]
Removing the OpenComputers api from the Calclavia Core jar fixes the crash.

**Comment by fnuecke** [comment]
Hmm, odd, I'd understand CC1.6 support breaking due to that, but 1.58? Anyway, thanks for letting me know! tgame14 mentioned that CalCore no longer ships/hard-depends the OC API in the more recent releases anyway though, so that should resolve itself over time.
