### ISSUE TITLE
OPPM problem

### ISSUE THREAD

**Issue by Slasherss1** [MightyPirates/OpenComputers#2223]
> Error while installing files for package "oppm": no error message. Reverting installation... Done...

**Comment by payonel** [comment]
this isn't the repository for oppm, see https://github.com/OpenPrograms/Vexatos-Programs/issues

also, this is a very incomplete bug report.
what version of oc are you running
what repro steps do you have
repro steps should include what you did, how we can reproduce the bug, and what you'd expect to work

**Comment by Vexatos** [comment]
GitHub was down for half an hour yesterday. That would have caused the connection to fail.

![See here](https://cloud.githubusercontent.com/assets/4135064/21954314/a246b97a-da4d-11e6-8268-b3a7d53dc5d0.png)
