### ISSUE TITLE
Computers Freezing

### ISSUE THREAD

**Issue by GB-Hijacker** [MightyPirates/OpenComputers#2225]
This has been reported a couple times by other people, but nothing has ever come of it.  I decided to take the time and do a slow mod by mod install.

The gist of what is happening is when the chunk is unloaded, and then reloaded, the computer screen will freeze and all computer activity will cease as well.  The activity light on the case will not do anything, and the screen takes no input.

This has been preformed on a FTB Infinity Lite modpack for 1.10.2  Version 1.5.1.  Opencomputers version is 1.6.1.6.

The mod that created the screen freeze was found to be Aroma1997-Dimensional World - 1.9.4-1.1.1.1

Of note, the freeze was not consistent.  Sometimes it would happen with every test, sometimes it would take multiple runs.

The test consisted of this:
-One creative case with tier 3 components
-One adapater hooked to an immersive engineering crusher (I've had UUID resets of hard drives and adapters and was curious to what could be causing this)
-mods were added one at a time
-spawn point was reset to a random chunk
-Upon logging into creative mode, I would teleport to three random chunks to force the chunk the computer was in would unload
-The computer would be checked and UUIDs for the screen, adapter, and hard drive would be noted.

Of note, the times that the computer would freeze, logs would show major time skips.  This log shows one of the times the computer froze and how many ticks the internal server needed to skip:

http://pastebin.com/2ctfu3TA

The following log is from a time later in my testing after I had removed aroma1997 DW.  The catch up was much better:

http://pastebin.com/pM4aFpRs

Lastly, here is the order in which I loaded mods and tested with notes.  I started with core API mods.

http://pastebin.com/zrf1pnyD

**Comment by payonel** [comment]
I just wanted to give you kudos for your time and effort in improving the repro for this bug. Fantastic job and what a great way to contribute to OpenComputers!

**Comment by fnuecke** [comment]
Thanks for the detailed report! This was in itself a relatively simple bug (computer updated before GPU so GPU didn't have time to look for its screen), but while fixing it I found an evil low-level bug hiding in the network merging logic :P
