### ISSUE TITLE
Set color using palette index instead of RGB

### ISSUE THREAD

**Issue by malucard** [MightyPirates/OpenComputers#2229]
I saw that setBackground and setForeground had an isPaletteIndex option. I thought it meant the 6-8-5 palette, the one the 256-256-256 RGB values get truncated to, but it's actually the custom 16-color palette. I'm pre-packing the RGBs so it takes up less space, but having to unpack them myself too is both a pain and unnecessary, since OC unpacks them anyway.

If the set functions accepted that kind of color plus 16 (to separate them from the custom 16 color palette), it'd be good enough.

**Comment by payonel** [comment]
i appreciate the feedback but our color selection logic is baked in for such a long time I don't think it is right to change how we handle color parameters

**Comment by malucard** [comment]
I think it would be, though. It'd really help people who are making graphics, for one.

If not, I'd want pack/unpack functions for colors.
