### ISSUE TITLE
Pastebin looks for the wrong link on get command

### ISSUE THREAD

**Issue by krakaen** [MightyPirates/OpenComputers#2230]
When trying to access code on pastebin, the computer can't access pastebin

Some people have been telling me this in my video.

A person was able to fix it by replacing a line in your pastebin.lua 

 at the line: [local url = "http://pastebin.com/raw.php?i=" .. pasteId], 
he changed it to [local url = "http://pastebin.com/raw/" .. pasteId]﻿

**Comment by payonel** [comment]
thanks, i'll investigate and fix when i can
