### ISSUE TITLE
Crash when using Ore Excavation on screens

### ISSUE THREAD

**Issue by Funwayguy** [MightyPirates/OpenComputers#2231]
**Description:**
Using Ore Excavation on Open Computer's screens causes Minecraft to crash. This appears to be related to screens failing to save their tile NBT correctly when Ore Excavation is attempting to save it into undo history.

**Crashlog:**
http://pastebin.com/Qsyiafyq

**Original Issue:**
Funwayguy/OreExcavation#31

**Comment by fnuecke** [comment]
Looks like it's trying to tell screens to save their data after they've been removed from the world; due to how screens (and computers for that matter) save their data (externally) that's not possible.
