### ISSUE TITLE
Bug: confusing empty table values with nil values

### ISSUE THREAD

**Issue by SinaMegapolis** [MightyPirates/OpenComputers#2235]
I downloaded and installed Mineos from opencomputer forums
But when running it im just seeing an error:
"Attempt to index field 'localization' (a nil value)"

I go to source to see where is this error from but what i saw is that:
'Localization' is an empty table value 
And when os trys to enter data into it , the error appears!

Annnd im seeing another errors like this error in another open computer programs
Such as lperskins python file editor:
"Attempt to index field 'f' (a nil value)"

If it isnt a bug, tell me why these errors appears
And if its a bug, fix it in next versions (sorry for bad english)

**Comment by payonel** [comment]
Sorry but neither of those programs are maintained in this repo. You'll need to report the bugs to their authors/maintainers on theirs repos or relevant forum posts.

**Comment by SinaMegapolis** [comment]
Yes but if it is an program-developing bug
Why im seeing this error in two completely different programs?
I though mabye that is a lua's bug?
So i report that in here

Or mabye it isnt a lua's bug and it can be fixed with some codes?
I asked here if anyone can find how to fix this error
(I got tired from receiving errors like this from mineos(a mac os style operating system for oc))

**Comment by payonel** [comment]
By reading the error messages we cannot determine if these two errors are related at all:
"Attempt to index field 'localization' (a nil value)"
and
"Attempt to index field 'f' (a nil value)"
I don't have their source, nor do I maintain it. You'll need contact them.
You'll want to make sure you're using the right version of opencomputers with the right version of these tools.
