### ISSUE TITLE
suggestion: add sound card + sound api instead of computer.beep()

### ISSUE THREAD

**Issue by SinaMegapolis** [MightyPirates/OpenComputers#2239]
can Opencomputer mod have anything like "Sound Card" with Sound API?
sound api can provide us any sound from minecraft such as noteblock sounds or creeper sound (shhh.... XD)

i know a addon mod for 1.6 named mass sound from the forums but its only for 1.6 and i want a mod that supports 1.10 and above

**Comment by Vexatos** [comment]
Computronics has three types of sound cards as well as a controllable note block; also, you can control the Vanilla note block using an adapter. Other Vanilla Minecraft sounds are not supported, though.
