### ISSUE TITLE
[1.10.2]component.robot.drop() issue

### ISSUE THREAD

**Issue by iesika** [MightyPirates/OpenComputers#2243]
If destination inventory have same itemStack(max stacked), 
`component.robot.drop(side, size)` erase itemStack which is not transfered part of itemStack.
 similar thing happened in `component.inventory_controller.dropIntoSlot()` also.

Movie:https://www.youtube.com/watch?v=MiPXAiYKr40

tested with
OpenComputers-MC1.10.2-1.6.1.6.jar
forge-1.10.2-12.18.3.2221

this does not occur in 1.7.10.

**Comment by Vexatos** [comment]
Thank you for the video, it showed the problem very well.
