### ISSUE TITLE
Remote terminals and terminal server locks up.

### ISSUE THREAD

**Issue by Zero9o1o** [MightyPirates/OpenComputers#2246]
I have encountered what I would call a bug in which both the remote terminals and the terminal server that the remotes are connected to will lock up. I have found this can happen when the chunk the server is in reloads (not all the time), when you join your world, or when you connect to your multiplayer server. You can also induce the bug by removing the terminal server from the rack, but this not how I normally encounter the bug but is a way to reproduce the effect. 

The only way to get the remotes and terminal server to become usable again is to turn off the server that terminal server is connected to and rejoin the world or server you are playing on then you can turn on the server and it works again. 

Also just turning the server in the rack that terminal server is connected off and on again without reloading the world or reconnecting to your multiplayer server does not fix it.

Minecraft version: 1.10.2
Forge version: 12.18.3.2215
Opencomputers version: 1.6.1.6

Encountered on the Skyfactory 3 modpack version 3.0.6

**Comment by Vexatos** [comment]
Sounds related to #2092.
Are you able to reproduce this with [the latest dev build](http://ci.cil.li/job/OpenComputers-dev-MC1.10/)?

**Comment by Zero9o1o** [comment]
Yes it can be reproduced on the latest dev build (Build 69)

**Comment by Nerodon** [comment]
Consistently getting this bug too.
While experimenting with a terminal server on the same rack as a single server, in the space of about 2 hours of fiddling with lua and testing programs in the server console, I had it happen three times. I never unloaded the chunk I was in, but I did move my terminal server around and use multiple remote terminals on the same terminal server but it's still not clear which action created the bug.

Using a different remote terminal and terminal server did not resolve the issue, it seems to be the server itself that exhibits the problem. Did not yet attempt other ways to create the issue or find any workarounds.

Minecraft version: 1.10.2
Forge version: 12.18.3.2221
Opencomputers version: 1.6.1.6

I use it in my own modpack on curse NABB pack 2.0

**Comment by payonel** [comment]
this issue has been around on terminal servers for a LONG time, it is great to get this fixed. thanks for reporting
