### ISSUE TITLE
Screen text missing when running on macOS in 1.10.2

### ISSUE THREAD

**Issue by BenjaminNolan** [MightyPirates/OpenComputers#2247]
Hi, all!

This works perfectly on my Windows PC, but when I connect from my Mac nothing shows up on the screens, even though they are definitely functioning machines.

![image](https://cloud.githubusercontent.com/assets/642271/22405857/0a88aa78-e649-11e6-9a98-8448b925a1d8.png)

Any ideas? I can run commands at the prompt as if it were working (eg, ls), and the cursor moves, but the actual text remains invisible. :( If I then log in from the PC, the on-screen text is clearly visible, which makes me think a required font is missing.

**Comment by gamax92** [comment]
OpenComputers supplies the font for screens inside the jar (font.hex), so it's not that

**Comment by gamax92** [comment]
What's your OC and Forge version? Graphics card info would also be nice.

You can get the Forge and GPU info by pressing F3 and screenshot or copy the text in the top right.
<sup><sup>(also stop using XRay)</sup></sup>

**Comment by ericcourville** [comment]
I had the same issue reported but with the latest release of sky factory it now shows as white blocks which is better than before.  Here is my forge and GPU details.

forge: 12.18.3.2254
GPU: NVIDIA GeForce GTX 680MX OpenGL Engine 2.1 NVIDIA-10.14.20 355.10.05.15f03

I am running OSX Sierra 10.12.3

**Comment by payonel** [comment]
we have seen this before, and continue to see it. from what i've been told mac has issues rendering the font but a refresh your textures resolves this: just press F3+t while in game

**Comment by ericcourville** [comment]
yup that did the trick!  Thanks a ton I was bummed I couldn't do any scripting.
