### ISSUE TITLE
Suggestion: my thinking

### ISSUE THREAD

**Issue by SinaMegapolis** [MightyPirates/OpenComputers#2248]
I'm back :D
I was thinking about that:
Can we add 'monitor' block with tiers that shapes like real-life home computer monitor?(using monitor for home uses and use screen for concerts :musical_note: :D )
Can we insert graphic card in 'screen block' and 'monitor block' instead of inserting them in the computer case? ( im know that doesnt make sense but hey, this is my thinking :D )
Can we improve speaker in computronics? (If computronic mod is installed, oc computer will not make sound until they have one of sound card types and they connected to a speaker )
Can use the documents of ocdoc.cil.li for in-game instead of manual?
Can we add video card tier 3 instead of graphic card tier 3 for faster drawing?
Can we know about progress of oc new version programming and change logs they got from github issues? :l 

And one more thing
Which one of my thinking is correct? :D

**Comment by TinkerWorX** [comment]
This is very disorganized. Try and structure your suggestions better and give some reasons why you think they should be included.

**Comment by payonel** [comment]
* new screen texture
> You are welcome to build a custom texture pack for opencomputers. you can even pull request it if you think it should be included. We don't have plans to change our textures ourselves.
* gpu directly in screen
> We are not planning on changing where the gpu would be inserted. I don't believe this would improve the user experience.
* No sound without computronics sound card
> Are you referring to the system beep that oc can make? That is to emulate the tiny motherboard speaker. I think this is should be left as is.
* Use ocdoc.cil.li for in-game doc instead of manual
> I can see a benefits to this (a: fewer sources of user documentation, b: the wiki can be more verbose at times). But there are many more drawbacks. The in-game manual is easily versioned, locked to the version of the mod you are using. Yes a lot of our documentation in both places are outdated, and we should do better to improve that, but at least the in-game doc is "ahead" of the mod. Also a client would then be required to have internet access to view the documentation in-game.  The wiki is open to edits from the public, it could be inaccurate, misleading, and worst (though perhaps unlikely) malicious. The in-game manual would have to be, essentially, a web browser, to handle rendering the wiki pages and navigation; this isn't a zero work item.
* better gpu
> we have had, and continue to have, discussions about improved gpus. There are tickets for this already and we do care about this issue.
* changelog info
> I'm not sure what you're asking here to be honest. We try to document the api and shell commands on our wiki, and we try to provide a list of changes in the release notes. Can we do better? Of course! Are you asking for a different medium to share this information?

I'll close this ticket. If you want to make a different request ticket, please keep the scope to a single thing. If you have many ideas it might be best to first discuss with our team on irc.esper.net #oc

**Comment by NoX-programer** [comment]
> Use ocdoc.cil.li for in-game doc instead of manual

My opinion is ingame docs is ok, but if online docs is mentioned, well... If you have a few minutes, just look into "Draconic evolution information tablet" (mod Draconic Evolution (1.10.2)) - there already done so. And there also sayed "My goal for this mod is for it to one day have documentation for almost all mods in existence." so integration with that will be cool... only if you think this it's worth it, @payonel . [Actual link for his online docs](https://github.com/brandon3055/Project-Intelligence-Docs), if it is needed.
