### ISSUE TITLE
os.date 's months start from 0

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#225]
if one does os.date("*t"), the months go from 0 to 11, instead of 1-12.

(Also, i don't know if they go from 0 to 11, i just know it can be 0)

**Comment by LordFokas** [comment]
that happens in a lot of languages / environments...
I don't think that's an actual issue... just add 1?

**Comment by fnuecke** [comment]
It's already fixed in build 349, actually (and yes, it does make sense to do this to behave equal to how Lua behaves normally, at least on Linux and Windows).
