### ISSUE TITLE
What language does the .shrc in /home/ use?

### ISSUE THREAD

**Issue by TheOtherMorzie** [MightyPirates/OpenComputers#2250]
I'm trying to get a boot script to run and it seems that the .shrc file is the best way to do it? (correct me if I'm wrong)
So I'm trying to figure out what language it is so I can properly implement an startup script.

**Comment by payonel** [comment]
.shrc is run as shell commands, not lua
https://github.com/MightyPirates/OpenComputers/issues/2171

**Comment by TheOtherMorzie** [comment]
@payonel Thank you, do you have any documentation for the shell commands?
