### ISSUE TITLE
Unsupported platform - can't host games with persistent computers

### ISSUE THREAD

**Issue by Yakov-Chernogor** [MightyPirates/OpenComputers#2252]
Hi there!
I'm trying to setup OC on my orange pi board (armv7l)
I've complied [OC Natives](https://github.com/MightyPirates/OC-Natives) and added them to OC jar files.
When I start server log files says that:

>[OpenComputers/OpenComputers]: Initializing OpenComputers API.
[OpenComputers/OpenComputers]: Found a compatible native library: 'OpenComputersMod-1.6.1.998-dev-lua52-native.32.arm.so'.
[OpenComputers/OpenComputers]: Unsupported platform, you won't be able to host games with persistent computers.
[OpenComputers/OpenComputers]: Done with pre init phase
>
Looks like it found the native library but why it says that I can't host games with persistent computers?
Thanks in advice.

**Comment by TinkerWorX** [comment]
[Persistence](http://ocdoc.cil.li/#persistence) requires the [Eris](https://github.com/fnuecke/eris) library to be available on the system. Eris is a C library.

**Comment by Yakov-Chernogor** [comment]
I've compiled and installed Eris lib. To be sure I recompiled OC Natives again after the Eris installed.
But the warning "Unsupported platform, you won't be able to host games with persistent computers" still present...

**Comment by glasspelican** [comment]
When i was building support for smartos #1962 i needed to build lua52 and lua53 libraries
from your log it looks like you only built 52

**Comment by Yakov-Chernogor** [comment]
Thanks, I've got it to work by compiling Lua 5.3 branch of OC-Natives.
