### ISSUE TITLE
Pastebin didnt download the program

### ISSUE THREAD

**Issue by Doomish** [MightyPirates/OpenComputers#2258]
Hi guys, i am Doomish and i am making Sky block modpack named Equivalent Sky. I need help. I have mod Open Computers from Curse. I have computer tier 3 and everything instaled when i use internet card to download program from pastebin I use: pastebin get -f sjJi0bum start.lua. everything ok, download the code OK. But when i use Edit start.lua its empty. This is problem with every pastebin code i use. Please help

**Comment by brisingraerowing** [comment]
This might be the same issue as #2230 

A fix is described there.

**Comment by Vexatos** [comment]
Sounds like it.
