### ISSUE TITLE
You are not whitelisted to use debug card, when whitelisted

### ISSUE THREAD

**Issue by Sukasa** [MightyPirates/OpenComputers#2262]
Playing FtB Infinity Lite 1.10.2

I set the server to allow debug cards, but whitelisted.  I, as op, ran the command "/oc_debugWhiteList add Sukasa".  I then bound a Debug card to myself, put it in a computer, and tried to use it.  I was told I was not whitelisted.

I've tried restarting the server but that didn't help.

**Comment by Vexatos** [comment]
You need to bind the debug card to yourself: Shift-Right click the debug card in your hand. Then it should start working.

**Comment by Vexatos** [comment]
I just tested it myself and it was working fine. Not sure what is going on. The whitelist seems to have properly registered your name, otherwise you would not have been able to bind the card to yourself.

**Comment by Vexatos** [comment]
I found the issue: It only occurs if your name contains an upper-case character.

**Comment by Sukasa** [comment]
Can I manually edit the debugwhitelist.txt file to get around that problem?

**Comment by Vexatos** [comment]
Manually editing the whitelist might work, you will have to try.

**Comment by Sukasa** [comment]
While the fix is awesome, for anyone who isn't upgraded *yet*, changing the debugwhitelist.txt file is an adequate workaround and does work
