### ISSUE TITLE
Game Crashes when trying to make a loot disk

### ISSUE THREAD

**Issue by PhantomEnderium** [MightyPirates/OpenComputers#2263]
When putting a scrench with a disk to make another, the game crashes. Using a 1.7.10 1.6.0.6 beta 4 version, so i dunno if a new version came out with a fix.

**Comment by payonel** [comment]
does not repro for me in the latest version, but it also doesn't repro for me in 1.6.0.6 beta 4 for me. Though I'm testing in SP.

**Comment by PhantomEnderium** [comment]
Got a new version, it works now luckily
