### ISSUE TITLE
[1.10.2] Lag spike when placing down new screen/loading screen (FPS)

### ISSUE THREAD

**Issue by lurr** [MightyPirates/OpenComputers#2266]
NOTE: This does not apply to new monitors that are **merging** with other screens.

Placing down, or loading a screen causes a lag spike. This does not apply to screens being placed down which automatically merge (screen resizing = no spike).

[F3 Menu showing lag spike](http://i.imgur.com/NLnFUOI.png)

**Comment by payonel** [comment]
no repro, screen place cost seems nominal for many users. nothing unnecessary in the code is occuring
