### ISSUE TITLE
Feature Request - hazardous environment crash

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2267]
Hazardous environments like adjacent water blocks or direct rain should be less friendly to computers and servers (with a config option of course!)

A custom crash message about shutting down to prevent water damage would be pretty neat as would an overheated message when placed next to lava when booting

**Comment by payonel** [comment]
this is perhaps related to this: #1043

**Comment by payonel** [comment]
in short, I don't believe there is interest in adding complexity or damage cost to computers, but thank you for your suggestion. (note that the referenced ticket was actually made sarcastically - as a place to store all related suggestions)

**Comment by ghost** [comment]
oh no, I dont mean as a damage value but rather just a simple check on boot

**Comment by payonel** [comment]
ah a change to the operating system boot messages -- well there would have to be a device connected to the machine that could detect those conditions, and then print a message depending on the detected condition. Given that most computers wouldn't have a device for detecting rain or lava, and that this would increase our boot costs slightly - I'll have to decline to adding this to openos. However, if you make such a start up script that accomplishes this (for startup options see #2171 ) feel free to post to our user forums and share :)
