### ISSUE TITLE
noise.lua missing

### ISSUE THREAD

**Issue by WilcoDW** [MightyPirates/OpenComputers#227]
in your examples for the hologram projector you are using a non-existing library....

so i went on the internet, gathered code and made a bugfree lua version of it. it would be very nice of you to put it in the /lib/ folder. 

here it is:
http://pastebin.com/iUPAMYEe

ps: if possible i would like a little tiny credit in the patch note ;)

source: http://gamedev.stackexchange.com/questions/58664/2d-and-3d-perlin-noise-terrain-generation

**Comment by fnuecke** [comment]
Uhm... you mean [this](https://github.com/OpenPrograms/Sangar-Programs/blob/master/noise.lua)? Where else if not there did you find the example programs? So I can link that repo there, to avoid others having the same issue. Sorry about that :-/

Also, I won't include that in OC directly. It's too special case, IMHO.

**Comment by dashkal16** [comment]
I can understand the confusion.  The Hologram component doc links to the two sample programs, but not the library.
https://github.com/MightyPirates/OpenComputers/wiki/Component-Hologram
Certainly, you can just navigate around the repo you're linked to, but it's not obvious.

**Comment by WilcoDW** [comment]
yeah, ok. if i was you would either link it or include it into the mod.
oh and the examples are found on the bottom of the hologram library component page thingy :?

**Comment by fnuecke** [comment]
Added a note on the wiki page.
