### ISSUE TITLE
MC 1.10.2 FTB Infinity Lite: Power Converter does not Converting RF to EU

### ISSUE THREAD

**Issue by Kratzwurst** [MightyPirates/OpenComputers#2270]
Hey ho, i play actually the Modpack FTB Infinity Lite V1.5.1 on MC 1.10.2.

Mods Version:

EnderIO 3.1.156
IC2 2-2.6.142-ex110
OpenC... 1.6.1.6

so now to the Problem, on the Screenshot can u see what i build up on my singleplayer world. all machine connecting fine together, but the Power Converter doesn't work and converted the RF not into EU

http://fs5.directupload.net/images/170211/albjsr5y.png

Greets

**Comment by Vexatos** [comment]
That is not what the power converter is supposed to do. See #2179.

**Comment by Kratzwurst** [comment]
Okay allright, than says the tooltip a false information, than the tooltip says this block can be converting RF into EU 1.25:1, and nowhere in the manual or in the tooltip stands not the information that this block that not can. Weired Information ^^

**Comment by Vexatos** [comment]
[The manual does state it](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/doc/en_US/block/powerConverter.md).

>The power converter serves as the fastest way to convert energy from other mods' power systems to OpenComputers' internal energy.

**Comment by Kratzwurst** [comment]
Yeah okay, from EnderIO into OpenC that i know it, but why not another way around?
