### ISSUE TITLE
screen turned off

### ISSUE THREAD

**Issue by Nex4rius** [MightyPirates/OpenComputers#2271]
>require("component").screen.turnOff()

A complete restart of the (ingame) computer does not reset this.
I think its only logical to reset this just aswell as the gpu color and resolution are being resetted otherwise the computer is useless if there is no autorun program to reverse this.
(It's really annoying and hard to type in the command to turn it back on without the screen)

**Comment by Techokami** [comment]
Have you tried using a redstone signal to turn it off and back on again?

**Comment by Nex4rius** [comment]
No I haven't tried that.
I put the harddrive into another computer and made the autorun.lua file with the command to turn the screen back on.
I just think it makes sense to have it automatically turn on on every reboot because with gpu color its also resetted when you fail and accidently set the background and foreground to the same color.

**Comment by payonel** [comment]
let me poke with this
i could probably (at least for openos) turn screens on, on boot

**Comment by SeaLife** [comment]
Maybe it is not actually a Bug. I mean - if you disable a Screen in your Driver Control Settings (NVidia Control Panel or something else) it wont come up on next reboot, you have to re-enable it for usage.

Adding a default ``require("component").screen.turnOn()`` on load of OpenOS may help Users with less skills in LUA or in OC-Programming but i dont think its a good solution?

I think if the User is going to "turnOff" the screen, then he needs to enable it on his own. 

This is just my opinion.

Regards
SeaLife

**Comment by Nex4rius** [comment]
If someone turn the screen off in the nvidia settings then it will turn on on start but then turn off when windows and the drivers are being loaded.

Why shouldn't it be a good solution to add <code>require("component").screen.turnOn()</code> into OpenOS? If somebody wants to have a turned off screen he can simply add the <code>turnOff()</code> at the start of his code.

**Comment by feherneoh** [comment]
Simply because the OS shouldn't turn on the screen if it wa turned off by a redstone signal for example. All of my screens have power buttons added to them, and I don't want a reboot to turn them on. You turned it off, then it should be off until you turn it on, it's that simple. That API provided by the screen is something like HDMI CEC, so like a "reactor overheating" message broadcasted on my network can force ALL my PCs to turn screen on and display a warning. But explicitly turning it on at boot? No. Just don't.

**Comment by payonel** [comment]
work around, use a redstone signal (like a button on the side)
