### ISSUE TITLE
Several drones are dropped if screnched quickly

### ISSUE THREAD

**Issue by Fingercomp** [MightyPirates/OpenComputers#2272]
1. Place a drone: ![Step 1](https://i.imgur.com/LK06EsU.png)
2. Shift-click while holding a scrench several times quickly.
3. Several drones will be dropped: ![Step 3](https://i.imgur.com/TdRhExG.png)
4. Try again if the bug didn't reproduce.

**OC version:** MC1.7.10-1.6.1.11

**Comment by Vexatos** [comment]
Should be fixed now.
