### ISSUE TITLE
Computers Hijacking Other Network Computer's Screens

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2277]
How do i fix this, they seem to be trying to get the least capable screen, AKA the lowest tier/smallest.

**Comment by NickNackGus** [comment]
Your computers are probably accessing each other's components because they are connected to one another either through cables or components - you can isolate the components while allowing network access with switches, wireless cards, etc. Try this: http://ocdoc.cil.li/block:switch

**Comment by ghost** [comment]
I have a 3 computer setup which needs to access the same two redstone io blocks

**Comment by NickNackGus** [comment]
Unfortunately, if they directly share redstone io blocks, (a component that also acts as a cable,) then they also share all of their other components, such as keyboards and screens. If change your system so only one computer has direct access to the redstone io blocks, and have all of those computers connected to each other through a switch, then the computer with the redstone io blocks can listen for network messages, set or get redstone signals, and send reply messages to your other computers. How you implement the network messages is up to you.

**Comment by ghost** [comment]
my problem is that for network messages(that's what the blocks are being used for) you have to WAIT for one computer to send a message to another.

**Comment by ghost** [comment]
Is there a way to get around this?

**Comment by Vexatos** [comment]
There are various ways to get around this, one of them has been mentioned. Just experiment. This is intended behaviour, you need to properly isolate your computers.

**Comment by magik6k** [comment]
In theory the OS can choose which screen/keyboard to use, so it can be done by writing simple driver that would blacklist all screens but one that should be used. Event filtering would probably be needed too. It might be easier to do in Plan9k as part of the 'infrastructure' is already there to do that.

**Comment by skyem123** [comment]
@GiantNuker, here's an idea, you could have 6 redstone IO blocks, one per computer, 3 each connected to the same redstone thing. Might not work perfectly (or well at all) but... something that might be possible?
