### ISSUE TITLE
Crash when using Nanomachines

### ISSUE THREAD

**Issue by Versalkul** [MightyPirates/OpenComputers#2278]
I was using this example programm: https://gist.github.com/fnuecke/dc8c79bfb37e66f99649

When i tried option 11 (getName) the game crashed

Crash log : [crashlog.txt](https://github.com/MightyPirates/OpenComputers/files/790105/crashlog.txt)

**Comment by Vexatos** [comment]
Duplicate of #2242 and #2220. I has already been fixed.
