### ISSUE TITLE
package.loaded, package.loaders, etc

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#228]
please? (at least package.loaded...)

**Comment by rmellema** [comment]
All those tables already exist. At least, package.loaders is renamed package.searchers in Lua 5.2, but package.loaded should just work.
See [the package library](https://github.com/MightyPirates/OpenComputers/blob/master/src/main/resources/assets/opencomputers/lua/rom/lib/package.lua)

**Comment by SoniEx2** [comment]
The wiki says there's no package...

**Comment by rmellema** [comment]
Its on the wiki [at NonStandardLuaLibs](https://github.com/MightyPirates/OpenComputers/wiki/NonStandardLuaLibs#modules)

**Comment by SoniEx2** [comment]
https://github.com/MightyPirates/OpenComputers/wiki/APIs says there's no package...

**Comment by rmellema** [comment]
Thanks for noting that. I have updated that page as well.

**Comment by SpiritedDusty** [comment]
It shouldn't be in OC custom API page because `package` is a standard Lua library.

**Comment by fnuecke** [comment]
I think the point was that that page explicitly stated [that there is no package module in OC](https://github.com/MightyPirates/OpenComputers/wiki/_compare/c123483e380c2986fd7c0192816b3c5e59b1e6da...3efc9d9f1c2ec1e89423f08c1a5d4a0dc719afcf), which is what Wobbo corrected.
