### ISSUE TITLE
Hologram issue

### ISSUE THREAD

**Issue by FlufferbatIndustries** [MightyPirates/OpenComputers#2284]
I don't really know whats going on here but about a week ago it was fine until I updated to new version, now no matter what version i use in 1.10.2 every time i go to place a holographic projector of either tier the game crashes with no crash report being made so yea unfortunately I cant supply one for you, just wondering as I've tried the obvious locations of files to delete in a hope to fix it but feel like I'm missing some/the one that's causing the issue, could you list all the locations of files that i can delete to fix this?

**Comment by Vexatos** [comment]
I have never heard of the game crashing without a crash report. Even GL errors are logged. What about `fml-client-latest.log` in the `logs` directory?

**Comment by FlufferbatIndustries** [comment]
well its not giving me one..

**Comment by FlufferbatIndustries** [comment]
ok didn't know about that.. checking..

**Comment by FlufferbatIndustries** [comment]
nope my latest log is from last night from being on a server

**Comment by FlufferbatIndustries** [comment]
well I'm not using this anymore then.. lol..

**Comment by skyem123** [comment]
Note that you shouldn't expect a response instantly. 😛 

Just to get an idea of what is happening, by crash, do you mean the game just suddenly closes, or do you mean it freezes?

**Comment by FlufferbatIndustries** [comment]
lol that's not why i said that man.. you ppl always jump to conclusions ay, and yea i mean closes, and also noticed something else when i have this mod pack on it doubles my recipe count from 10k to 20k.. can one of you please give me the locations of the files so i can try and delete it all.. note in between me being able to use it n not i used the wireless pc in creative mode n also made a few errors happen trying to setup the pc etc so it may be a result of using the wrong parts in stuff or from that wireless thing but i don't know coz i updated before placing the projector again which was fine before i did that coz i placed it like 10 mins before doing so both of them.. also just btw i have tried like more than 10 times and not one crash report and i don't get a server shutting down msg and my loader normally says when i have had a crash on previous load which also isn't happening... I originally thought it was a conflict between this and psionic upgrades but removing made no difference..

**Comment by FlufferbatIndustries** [comment]
[hs_err_pid5000.txt](https://github.com/MightyPirates/OpenComputers/files/797718/hs_err_pid5000.txt)

I just found this..

**Comment by FlufferbatIndustries** [comment]
[hs_err_pid4936.txt](https://github.com/MightyPirates/OpenComputers/files/797744/hs_err_pid4936.txt)

and think this is first time... you will notice their is 2 copies of the opencompers file in there which i deleted from the main directory but it was also in the tagcraft server directory where i found this.. which i just deleted, I will try again and see if it still happens..

EDIT: yea still happened.. I cant be bothered anymore all i wanted was the hologram anyway lol..

**Comment by payonel** [comment]
sorry, no repro
