### ISSUE TITLE
Servers can't beep?

### ISSUE THREAD

**Issue by xorinzor** [MightyPirates/OpenComputers#2287]
I was playing around with programs on one of the servers in the rack, and found the `midi` program which supposedly should be able to play sounds using `computer.beep`.

But it says it couldn't find a "beep card", which means that `if component.isAvailable("beep")` equals `false`.

Seems kinda odd to me, every computer generally has a built-in speaker to produce beep sounds, even servers.

Is this intended or am I missing something? Couldn't find any related components in JEI either when searching for "@OpenComputers"

OpenComputers version 1.6.2

**Comment by Vexatos** [comment]
The beep card is part of Computronics. The `midi` program uses either note blocks or beep cards to produce sounds; if it can't find either, it will fall back to `computer.beep`.

**Comment by xorinzor** [comment]
But it produces no audio at all for me

**Comment by Vexatos** [comment]
This is not the place to ask for help on programs that aren't native to OC. Go to the program's own issue tracker or try the IRC channel in this repo's README.

**Comment by xorinzor** [comment]
I thought it was `computer.beep()` that wasn't working, not the program itself.
But after testing it myself it does seem to be the program.
