### ISSUE TITLE
Switching HDD mode / using RAID not wiping data

### ISSUE THREAD

**Issue by xorinzor** [MightyPirates/OpenComputers#2288]
So, whether I put my hard drives in the RAID block, or switch them between managed / unmanaged, the data remains on them.

Pretty sure that, because of all the warning messages about loss of data, that isn't meant to happen.

(as well as annoying because there is no other way to wipe the disks, haha)

**Comment by Vexatos** [comment]
I am pretty sure that you can wipe disks by shift-right clicking them in your hand.
