### ISSUE TITLE
"Unknown error" when transfering fluid to an IC2 machine

### ISSUE THREAD

**Issue by Fingercomp** [MightyPirates/OpenComputers#2291]
1. Place a transposer next to any IC2 machine that accepts fluids (like Ore Washing Plant).
2. Fill the machine fluid storage (in this case, with water).
3. Then call `transposer.transferFluid` to transfer the same fluid to the machine. It fails, and returns `nil, "unknown error"` instead of `false, 0.0`. The [error stacktrace](https://gist.github.com/Fingercomp/b79e3b8a0434c02a3abcfe5ec3cb5457) is printed to the server log.

* OC version: 1.6.2
* MC version: 1.7.10
* IC2 version: 2.2.827

**Comment by payonel** [comment]
I have a repro, the tank can be full or empty, or partially fully -- the repro only when we try to pull from an empty source

btw, i've updated our docs on this function, it was really unhelpful :) the side parameters need to be cardinal (easy, west, north, south), and not facing directions relative to the machine nor component :)

hope this helps: https://ocdoc.cil.li/component:transposer
