### ISSUE TITLE
Trading upgrade not working

### ISSUE THREAD

**Issue by Derpthemeus** [MightyPirates/OpenComputers#2292]
When using a trading upgrade to trade with a villager (using `component.trading.getTrades()[1].trade()`), it fails with the message "not enough inventory space to trade". The robot has an inventory upgrade and its inventory is empty, except for the 1 item stack used in the trade. I've tried other trades and putting the item to be traded in the robot's selected slot, but it nothing works and I think it may be a bug. [Somebody else posted the same issue on the forums before, but no solution was found.](https://oc.cil.li/index.php?/topic/1198-trading-upgrade-difficulties/)
I'm running Forge version 12.18.3.221 (MC 1.10.2), and OpenComputers version 1.6.2.7 is the only mod installed

**Comment by andreasots** [comment]
I ran into this issue as well and decided to look at the code. I'm not familiar with neither Scala nor Minecraft modding so the analysis might be incorrect. I believe the bug ultimately lies in `li.cil.oc.util.InventoryUtils.insertIntoInventorySlot` which doesn't update the passed item stack if `simulate` is `true`. `InventoryUtils.insertIntoInventorySlot` is used by `InventoryUtils.insertIntoInventory` which is used by `hasRoomForItemStack` in `li.cil.oc.server.component.Trade.trade` which decides if to give this particular error message.

**Comment by lemarcantoine** [comment]
Same issue on Direwolf for 1.10 v1.8.1

**Comment by Vexatos** [comment]
Fixed via #2379.
