### ISSUE TITLE
[Feature Request] Handy Adapters 

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#2293]
Adapters are used as in interface to other mods 'things' (given someone coded an integration) however in some cases said thing may be a multiblock structure where the only valid location to place the adapter also results in obstructing the inventory/tank/GUI because its the only exposed face.

This occurs often when the structure as a whole isn't the TileEntity that the adapter connects to, but instead has a 'controller' block is in the middle of a 3x3x3 (ore lager) structure and has only a single face exposed to the world.

![2017-02-27_17 32 59](https://cloud.githubusercontent.com/assets/2107834/23414119/b1c838dc-fd8f-11e6-82d0-b5b2474f797b.png)

Possible solutions:
* alter the 'range' that the adapter has in detecting an adjacent TE's. This could be accomplished via a wrench click, upgrade to insert or advanced block. (in no way should the extended range be the default). This would allow for a adapter to be placed near a TE, but not blocking it's face. Downside, this changes the TE detection code a lot, and is less intuitive.

* Reduce the model size of the adapter so that it's possible to still access the face of the TE and get its gui open. Downside, we still can't use OC to interact with the inventory, it will probably also be strange to have another not full block.

* Make a block that combines both adapter function and the Transposer, or just allow the Transposer to also be an adapter

* Allow the inventory_controller or tank_controller upgrades to move items when placed in a adapter upgrade slot. This should also mean that the movement functions that are on the transposer should always be attached to a controller upgrade.

 Thoughts?

**Comment by Vexatos** [comment]
Isn't this pretty much what the MFU was made for?

>alter the 'range' that the adapter has in detecting an adjacent TE's

That is what the MFU does. Kind of. It allows interfacing with a block up to three (or more depending on config) blocks away.

**Comment by xarses** [comment]
That would be a start, but how am I supposed to dissect
>  Added: MFU. (Vexatos)

in https://github.com/MightyPirates/OpenComputers/releases/tag/v1.6.2
to mean that?
Here is the docs commit: https://github.com/MightyPirates/OpenComputers/commit/645ca3e448f278ea62eaac50d07e389eea0406dc

P.S. Can you update the wiki?

**Comment by xarses** [comment]
I'll test, given that. do we consider this resolved then?

P.S. Good job anticipating what I need before I do =D
