### ISSUE TITLE
Allow the ability to get the maximum parts of a packet that a modem can send.

### ISSUE THREAD

**Issue by skyem123** [MightyPirates/OpenComputers#2294]
This should be simple...
Modems already have `maxPacketSize()`, and as the number of parts is configurable, why not have a `maxPacketParts()` too?

**Comment by MajorGeneralRelativity** [comment]
That would be nice to have.

**Comment by skyem123** [comment]
This is probably really simple to add, and I'd do it myself if setting up a dev environment for OC wasn't so painful.

**Comment by brisingraerowing** [comment]
I could probably do it. I usually just edit in Notepad++ or Atom, and then build with Gradle. It's slow, but it works (and I really don't want to install Eclipse or Netbeans, as I don't really do any Java development anyways).

**Comment by brisingraerowing** [comment]
I got it written (didn't take long), I just have to test it now. Will report back.

**Comment by brisingraerowing** [comment]
It works perfectly. @fnuecke, would you accept a pull request to add this method?

**Comment by payonel** [comment]
@BrisingrAerowing you don't need to ask permission to make a PR, you just submit it and see where that goes.

**Comment by skyem123** [comment]
@BrisingrAerowing, odd, last time I tried to get a dev environment working, it didn't even build. Though that was some time ago...

**Comment by skyem123** [comment]
Anyway, please do submit a PR for this! It would be good to have this! :D

**Comment by brisingraerowing** [comment]
I get right on it.

**Comment by brisingraerowing** [comment]
@skyem123 I build everything from the command line, and edit with a basic editor. Avoids having to work around bugs and incompatibilities in various IDEs.
