### ISSUE TITLE
[1.7.10] Conflict issue with Computers and Matter Transpoter (Practicalities Mod)

### ISSUE THREAD

**Issue by MJRLegends** [MightyPirates/OpenComputers#2296]
i doubt anything can be done from the Open Computers side since its more a practicalities issue but its worth letting you know about it, just incase you can do a workaround....

See https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/680 (Issue reported to me from  a player of my mod pack)

**Comment by xarses** [comment]
I can't tell easily, which versions of OC , forge,  and practicalities is this? Also, does it repo on the just released 1.6.2 of OC?

**Comment by MJRLegends** [comment]
OpenComputers-MC1.7.10-1.6.2.12-universal
practicalities-1.7.10-0.6.2
Forge: 7.99.40.1614
