### ISSUE TITLE
1.6.4 Server Crash

### ISSUE THREAD

**Issue by Mannai** [MightyPirates/OpenComputers#23]
After you clicked the computer keyboard it instantly crashes the server.

http://pastebin.com/WnxdAKGh <---the crash report 
the mod seems very cool so would be great if there was a fix.

P.S: if you need anything from jenkins to file or server hosting, I dont charge anything for modmakers :)

**Comment by fnuecke** [comment]
Oops, I forgot testing that after making that method sided... my bad. Should be a quick fix!

Jenkins would be cool, thanks for offering! I haven't worked with it before, I assume that'll require some kind of build script? Ant? Gradle?

**Comment by Mannai** [comment]
http://www.minecraftforge.net/wiki/Github_%26_jenkins_buildsystem
that should give you an idea
register on ragetech.ragemc.com:8080
and I'll promote you so, you can do the rest

**Comment by fnuecke** [comment]
Sounds good, I'll look into it over the next couple of days. Thanks again.
