### ISSUE TITLE
piping doesnt work

### ISSUE THREAD

**Issue by shadoxxhd** [MightyPirates/OpenComputers#230]
input: ls | cat > f
output:
/|:

/cat:

/>:

/f:

it seems like it doesnt check for pipes and redirects

**Comment by fnuecke** [comment]
Just to clarify, if anything this works in besh (not in the default, simple shell). That seems to be borked, too, though... I'll have to talk with @Wobbo about that, because the problem seems to be in the parameter expansion.

(I think I/someone/can't remember also broke something by making some of the methods local, but even after fixing that the expand() function seems to derp).

**Comment by rmellema** [comment]
The expand function worked with parameter expansion when I tested it, and it shouldn't even touch | or >, those should just be copied into the resulting string. But I will have to look into that then.

**Comment by fnuecke** [comment]
I might well have broken something, I'll look through the logs. All I can say is that from quick testing, running `asd` through it made it return `nil` :-(

**Comment by rmellema** [comment]
That is really weird :/
What is even weirder though, I cannot even find besh in the repo, where does it hide?

**Comment by fnuecke** [comment]
It's [here](https://github.com/MightyPirates/OpenComputers/blob/master/src/main/resources/assets/opencomputers/loot/BetterShell/besh.lua). As mentioned, there are some scoping issues, and the shell.execute at the end is wrong now, too. I'll push a semi-fixed version later, after looking through the logs.

**Comment by shadoxxhd** [comment]
btw, whats the difference between the simple shell and besh?

**Comment by rmellema** [comment]
Besh has more functionality, like piping and redirecting and more advanced parameter expansion(including $((1+1)) ), but needs more RAM. That is why it isn't the default shell.

**Comment by fnuecke** [comment]
Looks like it's working again in the latest build, if you notice anything else borked in besh, let us know.
