### ISSUE TITLE
Unmanaged tier 3 hard disk has strange default geometry:

### ISSUE THREAD

**Issue by SolraBizna** [MightyPirates/OpenComputers#2305]
Floppy:

    lua> drive.getCapacity() / drive.getSectorSize()
    1024
    lua> drive.getCapacity() / (drive.getSectorSize() * drive.getPlatterCount())
    1024

Tier 1 hard disk:

    lua> drive.getCapacity() / drive.getSectorSize()
    2048
    lua> drive.getCapacity() / (drive.getSectorSize() * drive.getPlatterCount())
    1024

Tier 2 hard disk:

    lua> drive.getCapacity() / drive.getSectorSize()
    4096
    lua> drive.getCapacity() / (drive.getSectorSize() * drive.getPlatterCount())
    1024

Tier 3 hard disk:

    lua> drive.getCapacity() / drive.getSectorSize()
    8192
    lua> drive.getCapacity() / (drive.getSectorSize() * drive.getPlatterCount())
    1365.3333333333

It seems to me that the default for the tier 3 hard disk should be 8 platters rather than 6. The current default doesn't cause problems for most uses, but code that wishes to simulate CHS-style addressing will be... more complicated as a result.

(I'm not currently planning to use CHS-style addressing for anything important, for the record.)

**Comment by payonel** [comment]
i agree. changing the default platter count in the configs

**Comment by Vexatos** [comment]
Should we maybe add a forced config update for this?

**Comment by payonel** [comment]
I considered it, actually. But I also considered that worlds running unmanaged disks, if their platter count changed, it would affect the meaning of the (nbt) saved disk "position", which would cause read failures and potentially cause user scripts to crash or even corrupt their own data. So, honestly, if someone wants this change, they can make the change in their config themselves, or make a new world.
