### ISSUE TITLE
Unable to interface with applied energistics

### ISSUE THREAD

**Issue by rhbvkleef** [MightyPirates/OpenComputers#2306]
## Problem

OpenComputers' computers are unable to interface with Applied Energistics 2 networks.

Any AE2 compoents do not show up when executing ```components``` nor when executing ```=component.list()``` in LUA. They don't show up in ```ls /dev/components/*``` either.

## Troubleshooting steps taken

- Ensured latest versions of OpenComputers and Applied Energistics
- Tried following blocks:
    - Adapter with ME Interface (Both modes)
    - Adapter with ME Export bus
    - Adapter with ME Import bus
    - Adapter with ME Storage bus
    - Adapter with ME Drive
    - Adapter with ME Controller

Testing setup:

![2017-03-12_16 14 26](https://cloud.githubusercontent.com/assets/1645352/23832958/137a561a-073f-11e7-9ac3-3bae7d7886dc.png)

## Game setup/Settings
- World location: Local

## Mods/Versions
- Minecraft: 1.10.2
- OpenComputers: 1.6.2.7
- Applied Energistics: 2 rv4 alpha 11
- Actually Additions: r90
- Actually Computers: 1.0.0
- CodeChickenCore: 2.4.0.101
- CodeChickenLib: 2.5.6.223
- Just Enough Items: 3.14.5.406
- Not Enough Items: 2.1.3.201

## Hardware Information
- OS: XUbuntu 16.04 LTS
- Window manager: i3
- CPU: I5-6200U
- GPU: Intel HD 520 (
- GPU: NVidia GeForce GT 940M (Driver nvidia-375.39)
- RAM: 8 GB DDR3L 1600MHz
- SSD: Samsung 850 EVO (System drive - location of MC install)
- HDD: 1TB WD green (Secondary)

**Comment by thiakil** [comment]
#2206
