### ISSUE TITLE
Getting a Callback from a Value is difficult

### ISSUE THREAD

**Issue by SolraBizna** [MightyPirates/OpenComputers#2308]
I want to be able to tell whether a given `Value` invoke will require a synchronized call from Java code. It's already complicated enough doing that for `Components`, but I don't see a way to do it for a `Value` through the API at all.

**Comment by thiakil** [comment]
`<object>.getClass().getField("blah").getAnnotation(Callback.class).direct()` ?

**Comment by payonel** [comment]
closed thanks to reflection code given by thiakil
