### ISSUE TITLE
1.10.2 Tier 3 Hard Drive keeps erasing itself?

### ISSUE THREAD

**Issue by xaleb** [MightyPirates/OpenComputers#2309]
I keep getting a boot error everytime i leave the chunks and come back. Is it glitched? Im going to try the tier 2 hard drive.

**Comment by xarses** [comment]
Which OC version is this?

**Comment by xaleb** [comment]
OpenComputers-MC1.10.2-1.6.1.6, is it fixed in the new update?

**Comment by Vexatos** [comment]
Should be, please try to reproduce using 1.6.2.
