### ISSUE TITLE
Can't do anything with my computer

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2310]
Hello!

I have OpenComputers on my server.

I have made a computer. I showed it for a friend and he ran some command.

After that it's completely locked (I can't access it in any way).

I restarted the server, but it did not help.

Best Regards
/ Rasmus

**Comment by ghost** [comment]
I talked to my friend, he said he ran "rm -ft /" and "exit".

**Comment by payonel** [comment]
craft a disk drive, place it next to the machine, craft openos floppy, insert floppy into disk drive, restart opencomputers oc, reinstall openos (run `install`), and you're good.

**Comment by ghost** [comment]
Okey, let me explain what I mean with "I can't  do anything".

I can't open the inventory of the computer (so I can't change drives or any other component).

I can't break it with a pick (it don't go away).

So it's definitely a issue.

I wonder if there's a command for locking and unlocking the computer?

Best Regards

**Comment by NickNackGus** [comment]
http://ocdoc.cil.li/computer_users

Your friend has added themselves, or someone else who was online at the time, as a user to your computer. If your friend does not return access to you when you ask them to, you may need a server operator/administrator to add you as a user to the computer. If this is a server you are hosting, giving yourself operator permissions should handle the problem.

If your friend also did the rm command as he said, then he has removed all of the files from that computer.

Sounds like a harsh lesson in computer security to me.

**Comment by ghost** [comment]
Hello!

I suspected that was what's going on.

I know exactly what "rm -rf /" does, we are new to computers and we just had some fun with it.

One though is to automatically add the creator of the computer to the system.

I will have a look at the link.

Best Regards
