### ISSUE TITLE
No way to get character width from the API

### ISSUE THREAD

**Issue by SolraBizna** [MightyPirates/OpenComputers#2311]
Lua code can call `unicode.charWidth`, which in turn calls `FontUtils.wcwidth`, to find out the number of cells wide a character is. I don't see any way for other architectures to provide a similar facility.

I'm starting to think the Lua architectures should be rewritten as a separate mod (still included in the OpenComputers jar). I keep finding things that Lua does by reaching directly into OpenComputers internals...

**Comment by Vexatos** [comment]
You can always just call OC code yourself. Computronics does it in certain places, too.

**Comment by SolraBizna** [comment]
What's the point of having an API if you still have to call internal code to do major tasks?
