### ISSUE TITLE
Incorrect documentation / return value of world.getMetadata() in Debug Card

### ISSUE THREAD

**Issue by Sukasa** [MightyPirates/OpenComputers#2313]
This one is fairly straightforward; getMetadata() says it returns a number matching the metadata of a block, but it actually returns a string with the block's textual ID and metadata value (which itself can be a string, see the second image).

The results in the second image *are* useful, but not when you need the **numeric** metadata

![image](https://cloud.githubusercontent.com/assets/1186656/23934420/8e132540-0902-11e7-9703-83d7d2290122.png)

![image](https://cloud.githubusercontent.com/assets/1186656/23934455/c7e4857a-0902-11e7-9f12-6e0559d990ef.png)

**Comment by brisingraerowing** [comment]
I went ahead and figured out a fix (I think. It compiled at least) for the 1.10 branch, and I am going to test it once I get MC actually running (stupid missing dependencies).
