### ISSUE TITLE
Not detecting certain power/energy mods (1.10)

### ISSUE THREAD

**Issue by paperclover** [MightyPirates/OpenComputers#2314]
After installing some mods with OpenComputers, this message appeared in chat:
![image](https://cloud.githubusercontent.com/assets/24465214/23964190/09f79b5a-098a-11e7-983b-dcf0f2bc439e.png)
The problem is, I *have* mods that generate/use power. The mods are Ender I/O, Extra Utilities 2, and Thermal Expansion.

**Comment by xarses** [comment]
Please provide the versions for forge, opencomputers, ender io, EXU, and TE that you are using

**Comment by Pizzn** [comment]
I can confirm this with OC 1.10.2-1.6.2.7 for

Botania r1.9-341
EnderIO-1.10.2-3.1.171
EnderIO-1.10.2-3.1.179

**Comment by drakray** [comment]
Same message for 
MC 1.11.2
Forge 2262
OC 1.7.0.6
[ExtraUtils2](https://minecraft.curseforge.com/projects/extra-utilities) 1.3.3
[Forestry](https://minecraft.curseforge.com/projects/forestry) 5.3.2.67
[Advanced Generator](https://minecraft.curseforge.com/projects/advanced-generators) 0.9.20.5

(the 5 mod listed in the chat message are not updated to 1.11.2 though)

**Comment by Reggle** [comment]
Same message in MC 1.10.2 - Forge 12.18.3.2185
Advanced Generators & EnderIO installed, both use RF (well, Advanced Generators may do more I believe) and both are not detected as power mods.
Any progress regarding this?

**Comment by ajdepaul** [comment]
Same issue here. Using:
MC 1.10.2
Forge 12.18.3.2185
OC 1.6.2.7
Thermal Expansion 5.0.4.90

**Comment by ShicKla** [comment]
For anyone who is having this issue and would like a simple band-aid/workaround find and install a mod authors core library mod that is using an older RF API that will be recognized by open computers. I am personally using "RebornCore-1.10.2-2.7.1.38-universal.jar" but hypothetically any mod with the older API will do.

**Comment by Vexatos** [comment]
Closed via #2369.
