### ISSUE TITLE
NPE When placing Computer Case

### ISSUE THREAD

**Issue by nrllewellyn** [MightyPirates/OpenComputers#2316]
We experienced a server-side NullPointerException when a player placed a Computer Case (Tier 3) with a capacitor behind it and an ME drive (Applied Energistics 2) to its left. Here's the full stacktrace:
http://pastebin.com/sAsN8ERT

Relevant Versions:
MineCraft: 1.10.2
Forge: 12.18.3.2239
OpenComputers: 1.6.2.7

**Comment by payonel** [comment]
sorry i cannot repro this
perhaps screen shots or gif of the repro would be helpful
also, please retest with our latest 1.10 dev build, all known AE bugs have been fixed
http://ci.cil.li/job/OpenComputers-MC1.10/

**Comment by payonel** [comment]
actually, closing as no repro, please comment with details if you can repro with latest builds
