### ISSUE TITLE
Adapter, Chest and Chemical Synthesis Machine

### ISSUE THREAD

**Issue by duncanwebb** [MightyPirates/OpenComputers#2317]
Hi,

Is it possible to take items from a chest and place them in a Minechem Chemical Synthesis Machine using an Adapter with an Inventory Controller Upgrade?

I can see the items in the chest and the Chemical Synthesis Machine but I'm not sure how to move them between inventories. So it looks like it is possible.

The mod version is 1.6.0.9

Thanks

**Comment by xarses** [comment]
Adapter + Inventory controllers can not move items, what you want is a [transposer](http://ocdoc.cil.li/block:transposer) it will have methods for moving items between the sides for both fluids and items

**Comment by duncanwebb** [comment]
Thank you very much, this works just fine - sort of. I move some hydrogen and oxygen into the inventory but cannot take the water from the slot out.

Any ideas if this is possible, I suspect that I need to remove the item from the bottom side.

Minechem has an API that looks reasonable, https://github.com/iopleke/Minechem/wiki/Using-the-Minechem-API.

Can I copy the commands I've used so that I can paste them here?

**Comment by xarses** [comment]
The fluid tank would have to be operated with the tank commands instead of the inventory ones, and the side you move it to would also need to be a tank (unless the fluid is allowed in the world, ie 1000mB of water).

Some machines do block access to slots/tanks unless you are coming from the correct side. The general rule is, if another mod's fluid/item system can interact with it, then you should be able to code access in a similar fashion.

**Comment by duncanwebb** [comment]
xarses, many thanks. Water in minechem is in a bucket like thing, just I can click it to take the items I can also just used an item conduit from the bottom side the output result into a chest.

I can also move items into the recipe slots so I can program recipes which is really nice.

The only suggestion I would make is to return the number of items moved and nil for an error. I assume that lua treats zero and nil as false.

![minechem-synth](https://cloud.githubusercontent.com/assets/4198031/24071284/c090f438-0bce-11e7-8298-ec0a5df9b593.png)

**Comment by payonel** [comment]
just fyi, lua treats `nil` and `false` as **false**, everything else is **true**, including `0`
