### ISSUE TITLE
"too long without yielding" When starting the machine

### ISSUE THREAD

**Issue by Nikolai521** [MightyPirates/OpenComputers#2321]
Hi lately with the latest version of the mod I was having some problems like the error "too long without yielding" every time I want to start OpenOS the error appears while loading and the load stops in "os.lua" from there that the floppy disk reader Start reading very slowly after a while PUM the error but if I start from plan9k everything is fine and I run out of ideas.

Anyway I hope they try to fix it as the mod is very good.

**Comment by xarses** [comment]
Would need the Minecraft, OpenComputers, and Forge versions at a minimum. There may also some hints in the console/server log that would be helpful too.

**Comment by payonel** [comment]
@Nikolai521 this sounds like a critical bug, something I would have to fix before releasing OpenOS at any version. But I've never seen this happen before. Please help us repro this by providing
1. steps to reproduce this bug. Can you reproduce this bug in a test world with just a single computer?
2. what mc, forge, and oc versions are you using?
3. anything else you can test to show when this repros and when it does not.

**Comment by Nikolai521** [comment]
Minecraft 1.7.10
Forge 10.13.4.1614
Mod version 1.6.2.

Regarding openOS it is impossible for me to install since always the same error when starting on another map me the computer worked correctly but every time I turned it on it appeared the same error tried several times until it worked but now it makes me impossible exept if I use one Older revision of OpenComputer everything works correctly

**Comment by payonel** [comment]
by "1.6.2" do you mean OpenComputers-MC1.7.10-1.6.2.12-universal.jar?
from: http://ci.cil.li/job/OpenComputers-1.6-MC1.7.10/lastSuccessfulBuild/artifact/build/libs/OpenComputers-MC1.7.10-1.6.2.12-universal.jar

**Comment by payonel** [comment]
just testing with the versions you gave, does not repro
created test world, `/oc_sc` a test machine, installed openos and rebooted to shell -- all without time out error.

Please find the minimal set of repro steps necessary to demonstrate this bug.

**Comment by xarses** [comment]
@Nikolai521 It sounds like you updated from a prior version. What happens if you craft a new cpu, bios, and OpenOS disk (try one at a time)

**Comment by Vexatos** [comment]
@xarses Only the floppy disk should be relevant.

**Comment by Fingercomp** [comment]
When running MC on host computers not powerful enough, it's really hard to boot OpenOS because of this problem. I have to start an opencomputer 20-30 times before it manages to actually load instead of crashing with "too long without yielding".

Try to put your host computer under a high load and then start a machine. That should make the issue reproduce.

------------------------------

Btw, I think this line in `machine.lua` causes the problem:

```lua
  if computer.realTime() > deadline then
```

Besides causing this issue, there's another one: if the server freezes (like when loading the world), some computers running in the world would just crash with "too long without yielding".

IMO the if condition has to be rewritten to use in-game ticks, not real time, when deciding if the computer should stop. Right now it makes lots of troubles when running relatively complex programs on rather slow servers.

**Comment by Nikolai521** [comment]
Hello again I went on a trip but I'm back.

Well I was reading the comments and firstly when acutalize the mod I create a new machine but at the beginning it happened the error I thought it was the hard drive and so I changed it and proceeded to start it from floppy to install it but not the error followed as it is I do not play online

The first few times gave the same error until it turned on completely but now it is dead

This is actually just starting with the mod and I do not know very well about the commands

**Comment by Nikolai521** [comment]
At last I discovered that it was not the mod was my own computer to which I had made an overlock and the voltage was very low and the processor was stuck in the heavy processes it raised the voltage and now it works...

**Comment by Armigus** [comment]
I'm seeing this condition from time to time also... Fingercomp has a point.  My machine is rather old and running other programs, notably Firefox and VLC, along with Minecraft.  Any major lag spike, especially when backing up the game via Aroma, risks causing this error.  Using real time to trigger this problem might not be a good idea.
