### ISSUE TITLE
AgriCraft compatibility broken

### ISSUE THREAD

**Issue by Misza13** [MightyPirates/OpenComputers#2322]
Geolyzer is no longer able to inspect AgriCraft crops. I am no Scala expert but it seems to me that:

https://github.com/MightyPirates/OpenComputers/blob/master-MC1.10/src/main/scala/li/cil/oc/integration/agricraft/EventHandlerAgriCraft.scala

expects an "isCrops" method on AgriCraft's API, which does not seem to be present (not in AgriCraft 2.0 which is the version for Minecraft 1.10 anyway):

https://github.com/InfinityRaider/AgriCraft/tree/master/src/main/java/com/infinityraider/agricraft/compat/computer/methods

component.geolyzer.analyze(side) returns the following:

    {color=31744,
     hardness=0,
     harvestLevel=-1,
     name="agricraft:crop"}

Thus, it's not only impossible to get the growth stage % but also the strength/growth/gain stats and even the type of seed, for that matter.

**Comment by Diklabyte** [comment]
I don't know if this can help, but I have found an API change in the AgriCraft code:

The old API (1.7.10 - 1.9) has a "[isCrops(World world, int x, int y, int z)](https://github.com/InfinityRaider/AgriCraft/blob/1.7.10/src/main/java/com/InfinityRaider/AgriCraft/api/v1/APIv1.java#L179)" method.

The new API (1.10.2) has a new method name? > "[getCrop(World world, int x, int y, int z)](https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/infinityraider/agricraft/api/crop/IAgriCrop.java#L21)"

Hopefully it helps a littlebit.

**Edit**
@Misza13 The thing is, OC 1.8 and later, the mod compatibility is smaller than in 1.7.10.
For more information see: [Mods.scala](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.10/src/main/scala/li/cil/oc/integration/Mods.scala#L96).
So the Agricraft Mod won't be initialized!
Additional to this, Agricraft 1.10.2 is currently in Alpha, so OpenComputers won't get any compatibility until Agricraft become to a *Release Candidate*.

**Comment by payonel** [comment]
I would only add new integration to our latest mc version, which is currently 1.12
And so, looking at agricraft for 1.12:
I built some code to use their current latest release and the api just isn't ready yet for us to interact with the mod. There is no proper way to connect to the mod, nor to get crop data through the api. It seems to be very alpha. Not the right time for us to integrate. sorry.
