### ISSUE TITLE
Event.listen not properly notifying handlers

### ISSUE THREAD

**Issue by MajorGeneralRelativity** [MightyPirates/OpenComputers#2323]
I'm trying to test GERTi, but a particularly tricky bug is interfering. I've registered a function with event.listen, but after a certain point, it just stops being notified. Dmesg shows the incoming message though
Code: https://github.com/GlobalEmpire/GERT/blob/Development/GERTi/GERTi%20Gateway.lua
Screenshot: http://imgur.com/a/gxtea

There should be additional messages on the screen about receiving a "DATA" message, but the only sign I get that the packet is coming in is through dmesg. I added a print("I am being called") right before line 201, and that does not fire either, so it seems that receivePacket() is just not being called. 

I'm trying this on the latest OC version in 1.7.10. Please let me know if I should provide any more information.

Edit1: Steps to reproduce:
You will need 3 computers, one with GERTiGateway in a directory and running, and 2 with GERTiClient.lua in /lib . 1 client computer should have a wired card and linked by network cable to the gateway. The gateway and 2nd client computer should have wireless network cards and be linked that way.

Step 1: Run GertiGateway.lua on gateway computer.
Step 2: On wired client, run a program that does "local GERTi = require("GERTiClient")"
Step 3: On wireless client, run the following program: https://gist.github.com/MajorGeneralRelativity/e833c6cbac0728b62a259da94e031454
Step 4: On the gateway, run dmesg.
Step 5: On wired client, run the following program:https://gist.github.com/MajorGeneralRelativity/f94466b8f9816ee7c33fee18441709ca

Result: On the gateway, you will see messages come through in dmesg, but no print statement from receivePacket will fire

**Comment by payonel** [comment]
I also found a couple bugs with event registration recently, I'll have a few fixes soon that I'll have you verify

**Comment by MajorGeneralRelativity** [comment]
Ok, let me know

**Comment by payonel** [comment]
fixed by 400d7eed7eabbff601a1eced86ef8e31b1eadf6b
