### ISSUE TITLE
[1.6.2.7 / OpenOS 1.6.1] Silent errors

### ISSUE THREAD

**Issue by Pizzn** [MightyPirates/OpenComputers#2326]
I have noticed several times that the OS rarely prints errors. Most of the time the causing program just stops working without any output to stdout/stderr. Illustrated with assert:
![mc-assert](https://cloud.githubusercontent.com/assets/19887865/24455546/488e4524-1490-11e7-9805-85bade588e12.jpg)

OC: 1.6.2.7, MC 1.10.2, Forge 2185
Tested in a fresh world with /oc_sc.

Edit: Seems to be happening only when using LuaJ instead of the native libs.

**Comment by gamax92** [comment]
Yeah, this is just an issue with LuaJ being terrible at everything, and giving correct stacktraces (or anything at all) is one of them. If possible you should be use the natives over LuaJ always.

**Comment by Pizzn** [comment]
Ah, so this is more of a shortcoming of LuaJ? 
The only reason why I'm using it is that the native libs render robots unusable for me (#2302), whereas with LuaJ robots are at least booted again.

**Comment by payonel** [comment]
I'll investigate to see if there is anything better openos can do in this situation

**Comment by payonel** [comment]
there is nothing more i am getting from luaj for this
