### ISSUE TITLE
[Feature Request] Tier 2 and Tier 3 Tanks

### ISSUE THREAD

**Issue by RobertBouillon** [MightyPirates/OpenComputers#2327]
The tank holds 16 buckets, which makes sense because it's in-line with the 16 items the inventory provides, with vanilla MC limiting one (filled) bucket per slot. Most mods allow SOME form of stacking buckets now.

The usability with 16 buckets can be pretty limiting. What about making Tier 2 / Tier 3 tanks with 32 / 64 bucket capacity?

**Comment by Vexatos** [comment]
You can just install more tank upgrades.

**Comment by xarses** [comment]
I don't see this as a priority for the mod, as Vextos noted, you can add more upgrades to have more tanks.

Alternatively, you can either place another mod's portable tank in world and drain/fill it and then pick it up and move elsewhere OR using another mods  (not all) mod portable fluid containers directly in the inventory of the robot (this requires the usage of a tank upgrade, and a tank controller)

Which work? usually the ones that work as 'buckets' with other mods for example Drum's from Extra Utilities, cells from IC2 and GregTech 5 work, but barrels from Ye Old Barrels don't (the hint for me is the prior work in most fluid loading/unloading UI (railcraft tank valve), but  the latter will not

**Comment by RobertBouillon** [comment]
Again, thanks for the great reply.

I'm currently using 1.6.2.7 (FTB Direwolf20), but am unable to drain an I2C lava cell into the internal tank using the tank controller. I get "incompatible or no fluid." I can, however, load vanilla buckets of lava. It's worth noting I "can" load the I2C lava cell into the internal generator, though, but the tank controller chokes on it. Is this a bug?

Speaking of loading lava into the generator, is there any way to tell if the generator is actively burning fuel? The generator works fine for consumables, such as coal, because you can tell when it's out or low using count(). Lava is different because you can't put more than one item in there (because the filled and empty cells are different). I work around this by loading and removing a cell. If it comes out empty, the generator "ate" it. What about adding an isActive method? And / or what about adding a method that tells the generator to draw from a specific tank?

Regarding the OP, adding more tanks isn't feasible with a Tier 1 or Tier 2 robot unless ALL it's doing is fluid, and by the time I can spend on tier 3, the robot's utility has diminished. Bigger tanks would be appreciated, but I understand if it's a lower priority since there are workarounds. I have a Tier 2 mining robot: digs tunnels, stores goods, drops crap. With keyboard, mouse, inventory, inventory controller, and generator, I don't have much room to for tanks. Less storage means more trips home, or time wasted reorganizing inventory. Increased storage would represent an incremental speed upgrade to its operation, without sacrificing the ability to hover, navigate independently, etc.

**Comment by xarses** [comment]
If the generator 'ate' the cell, then its a repo of #1779 which should be fixed in any 1.6.x version

**Comment by payonel** [comment]
I'll resolve this by investigating supporting the ic2 tank with our tank controller

**Comment by xarses** [comment]
adding the ic2 tank as a componet? or an in inventory tank that the TC can work?

**Comment by payonel** [comment]
these fixes are for 1.12 only
greatly improved robot item use, makes all tank interactions for large list of mods work correctly. can also properly use stacks of fluid cells with fluid tanks with ic2
