### ISSUE TITLE
[Feature Request] AE2 Interface

### ISSUE THREAD

**Issue by RobertBouillon** [MightyPirates/OpenComputers#2328]
Any chance to get a card / upgrade that functions to remotely access items in an Applied Energistics setup?

**Comment by xarses** [comment]
There is already integration when using an adapter block on some of the AE2 blocks for most MC versions we support (There are some 1.10 versions that don't have it). We almost never integrate with other mods outside of the established adapter method. So adding cards / upgrades will not occur. You will need to use a static computer and adapter to interact with the other them.

Is there a specific set of instructions that is missing off the adapter?

**Comment by RobertBouillon** [comment]
Okay that's great to know. Thanks for the detailed reply.

I wasn't aware that the adapter would work with AE2. I'll give that a shot and let you know if I hit any issues.

Thanks!
