### ISSUE TITLE
[Feature Request] Tier N (network?) card that allows the teleportation of items between computers

### ISSUE THREAD

**Issue by RobertBouillon** [MightyPirates/OpenComputers#2329]
Create a card that lets you get / put items in the inventory accessible by a remote computer. Remotely accessing the inventory should have the normal data transmission energy costs, but the actual movement of items should have a significant energy cost. 

Also - fluid variant.

**Comment by MajorGeneralRelativity** [comment]
This probably wouldn't fit with the spirit of the mod. A possible solution is a chain of transposers.

**Comment by AshIndigo** [comment]
Arent robots or drones meant for item transport instead of a magic card

**Comment by MajorGeneralRelativity** [comment]
That too
