### ISSUE TITLE
[Feature Request] Personal Teleporter

### ISSUE THREAD

**Issue by RobertBouillon** [MightyPirates/OpenComputers#2330]
Would be cool to allow the robot to teleport to and from remote locations, especially for mining programs.

For balance, perhaps require a consumable. One glowstone dust / 10 blocks? Ender pearl for unlimited distance? Allow teleportation to another dimension, but require ender pearl?

**Comment by MajorGeneralRelativity** [comment]
This also probably wouldn't fit with the spirit of the mod, and would defeat the whole point of programming your robot to travel.
