### ISSUE TITLE
[1.10.2] Lag spike due to OpenComputers (Server TPS)

### ISSUE THREAD

**Issue by Brend-Smits** [MightyPirates/OpenComputers#2331]
Heey, first of all I want to thank you for your work on OpenComputers, our players have been enjoying using the mod! 
Running on Sky Factory 3, we've been seeing some lag spikes caused by data saving from Open Computers, I've included a screenshot which will help identify the issue. 
![image](https://cloud.githubusercontent.com/assets/15904543/24550257/82cc419e-161d-11e7-9ca1-f15b9fb4064f.png)
![image](https://cloud.githubusercontent.com/assets/15904543/24550294/a586981a-161d-11e7-980f-308ad300f0e4.png)

Here is the download to the full profile: https://toastynetworks.net/rsampler.php?id=e8f0098fc5aa415ca027bc556233ae67
Running SpongeForge: 
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a3257a01
    SpongeForge: 1.10.2-2254-5.2.0-BETA-0
    Minecraft Forge: 12.18.3.2254
OpenComputers-MC1.10.2-1.6.2.7

I would love to know if I can do something about this ( config wise) or if this is an issue that needs to be fixed within the mod itself.
Thank you for your time

**Comment by fnuecke** [comment]
Hmm, just by looking at the profiler snapshot it looks like it's actually spending most of the time loading classes. Pretty much every path I drill down ends in the class loader. If that happens repeatedly, that'd be quite odd. It also looks... suspicious that *all* of those take 12.6ms. My best guess would be some tweak/code mod gone rogue, the VM running low on memory, or a slow HDD holding the JARs with classes get loaded from.

**Comment by Brend-Smits** [comment]
Hmmm at this point the VM still had more than enough memory. Our SSDs are also not the issue as I just had them replaced for a Raid 10 setup (4 SSDs)
Checked them before turning on all the servers of course. 
Would there be some kind of config option for me to enable / change to lower the lag from these computers?

**Comment by payonel** [comment]
we are improving save performance with improvements to the buffered file save, which will merge for 1.7.3
