### ISSUE TITLE
Unable to craft OpenOS Floppy

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2332]
Hi!

I am playing version 1.7.0.6 on minecraft 1.11.2(on a server).
My problem is, I can't craft an OpenOS floppy disk. I have the manual and the floppy, but I'm unable to craft them together.
Also, the floppy's name isn't actually "floppy", but the variable name that's supposed to contain the name(I think?), so that might be causing it.

The floppy's name
![2017-04-05_18 21 56](https://cloud.githubusercontent.com/assets/22587437/24716130/266becf0-1a2e-11e7-910d-f56ed49c10af.png)

Unable to craft
![2017-04-05_18 22 11](https://cloud.githubusercontent.com/assets/22587437/24716148/434dcdfc-1a2e-11e7-83fb-0f95b55bc36c.png)

**Comment by xarses** [comment]
The OpenOS disk's name contains `openos` not floppy so you should be able to check against that in JEI

**Comment by ghost** [comment]
If I bring up the JEI recipe for the OpenOS disk(or any other floppy), it just brings up a generic recipe that says if I combine an `item.oc.FloppyDisk.name` with a `scrench` I get an `item.oc.FloppyDisk.name`.
Just to be sure, I checked it with only OC installed(no other mods), and it's still not working.

**Comment by payonel** [comment]
oc for 1.11 is alpha -- very much a work in progress. At this point expect everything to not work
