### ISSUE TITLE
All text went red

### ISSUE THREAD

**Issue by bjr29** [MightyPirates/OpenComputers#2333]
![image](https://cloud.githubusercontent.com/assets/26935086/24719192/bbe3e2ea-1a30-11e7-96ea-b885caa29013.png)
I typed in [Filename] and edit and for some reason it came up with a error message with a code error like I wanted it to run and the error went into my input and turned everything red.

**Comment by xarses** [comment]
neat... it looks like the foreground color wasn't set back to white.

What happens if you `exit` or `^D` in the terminal so that it respawns the shell? 
What happens if you restart the computer entirely?

Can you provide the exact commands that caused this state? 
What MC, Forge, and OpenComputers versions are you using?

**Comment by payonel** [comment]
like xarses said, `reboot` will fix the colors just fine. There is a error handler in openos shell that should print red when a program crashes or prints to stderr, and in the past we've had some bugs around capture and handling those errors cleanly. Either your openos version is old (what is your OC version?) or you've found a new bug.

Provide details!
what oc version?
what is the minimal steps to reproduce?

**Comment by Nex4rius** [comment]
Just a quick question but why do you need the oc version? As far as I understand it this is a problem in OpenOS and the version is clearly shown in the picture. Are there different OpenOS 1.6.1 versions?

**Comment by xarses** [comment]
> Are there different OpenOS 1.6.1 versions?

Yes, there are multiple point releases. See https://github.com/MightyPirates/OpenComputers/releases
There are two primary releases, as well as many build version point releases that someone could have downloaded from the build server

It's possible, that it's only present in a specific point release(s). In some error cases (this one is unlikely) the MC and forge versions might be related to the issue as well. As a matter of habit I ask for MC, Forge, OC and if its an interop issue for the other mod's version. It's quite probable that this information is required to reproduce the issue.

In this specific case, it would probably be more necessary for the reproduction steps

**Comment by payonel** [comment]
I still would love some repro steps

**Comment by payonel** [comment]
too long without repro steps. before you reopen you need to test on our latest builds and give repro steps
