### ISSUE TITLE
[Defect] robot.down() and robot.forward() return true even if it failed to move

### ISSUE THREAD

**Issue by RobertBouillon** [MightyPirates/OpenComputers#2334]
There appears to be a race condition in the robot movement.

I have a mining script that keeps failing because it's tracking its movement incorrectly because forward and down are returning true even though they were unsuccessful. Adding an os.sleep(0.2) after every move seems to resolve the issue.

I'm working on a better way to reproduce the issue, using the navigation component to verify each move. I'll try and get a script to you shortly.

**Comment by xarses** [comment]
Please share the version of MC, and OpenComputers. We'd need some code to try to reproduce this.

I've seen something similar to this, but I'm still not 100% that its not my code, but I appear to have mine think they are moving OK when entities are blocking them, but my code is supposed to retry on this already, but they clearly get offset

**Comment by RobertBouillon** [comment]
Sorry - 
MC - 1.10.2
OC - 1.6.2.7
Using the Direwolf20 pack from curse

Here's the code where it's failing (Remove the os.sleep calls to get it to fail again)
https://pastebin.com/vdUzxZT3 - nav.lua
https://pastebin.com/irjLJx6j - mine.lua

You need the following items for the MINE script to work:
Actually Additions Drill (x3 and x5 upgrades) - Equipped
Actually Additions Ring of Magnetizing - In Inventory
Diamond Chest - Placed left of Robot
Open Computers Charger - placed behind Robot
Actually Additions Energizer - Placed right of Robot
Creative RF Power Source (Using EnderIO Creative Capacitor) - Place between charger and energizer

mine 40 8 [height of robot]

I'm trying to create a simpler repo, though. I'll let you know....
