### ISSUE TITLE
[1.11.2] Crash with OC in Dev env

### ISSUE THREAD

**Issue by AshIndigo** [MightyPirates/OpenComputers#2335]
I loaded up my test world with a creative computer (Spawned with the command) and it crashed immediately.

Log: https://pastebin.com/ERiuNS7A

**Comment by payonel** [comment]
oc for 1.11 is alpha, work in progress. thanks for reporting

**Comment by payonel** [comment]
later builds not doing this: http://ci.cil.li/job/OpenComputers-MC1.11/
