### ISSUE TITLE
[1.10.2] Robot cannot use sieves

### ISSUE THREAD

**Issue by md5i** [MightyPirates/OpenComputers#2336]
- OpenComputers 1.6.1.6
- Ex Nihilo Asdcensio 1.10.2-0.1.1.5
- Ex Compressum 2.0.87
- as found in SkyFactory 3 3.0.7

Robots seem to be unable to interact with [Ex Nihilo Adscendio](https://minecraft.curseforge.com/projects/ex-nihilo-adscensio) sieves or [Ex Compressum](https://minecraft.curseforge.com/projects/ex-compressum) heavy sieves.

For the former if (say) sand is equipped, `robot.use()` does not do anything at all.  (Bug [#124](124) seems to imply that this might have worked at some point in time.)

As for the latter, `robot.use()` does insert the compressed block into the sieve, but further invocations of `robot.use()` do not activate the sieve.

**Comment by Vexatos** [comment]
Are you sure that fake players are allowed to use sieves? There should be a setting in the config file.

**Comment by xarses** [comment]
Your MC version appears to be 1.10.2, wha's your forge?

 Also, I don't follow your steps here, can you please detail the requirements in the robot to do this, the steps taken, and the expected results, actual results... 

Something like:
requirements: robot, inventory_controller, (9) sand in 'hand'
steps:
* `robot.use()`
expected result:
* hand contains (8) sand, one was 'used' on the TE
actual result:
* hand still contains (9) sand

Please also identify if there are any server or client console logs at the time of the execution of this process. Lastly, it might be useful to understand what the full response string of use is i.e. `=robot.use()`

**Comment by md5i** [comment]
Vexatos has this partially right.  Ex Compressum has an `Allow Fake Players` option which was `false`.  After setting it to true, `use()` returns `"block_activated"`. I am new to using Minecraft mods, and did not think to look for this.  This is enough for me to be satisfied.  But I am not closing automatically because the Ex Nihilo Adscensio sieve still doesn't behave as expected.  (I have no objection at this point if the issue is closed.)

Although Ex Nihilo Adscensio has a `fakePlayersCanSieve` option, setting it to `true` did not change the behavior using its sieves.

Steps to reproduce:
- requirements: robot, (1) sand in 'hand', sieve with Iron Stiffened Mesh, robot facing sieve, in `configs/ExNihiloAdscencio.cfg`,  `fakePlayersCanSieve` is set to `true`
- robot.use()
  Expected: block activation, sand gone from hand.  Instead returns `false` (no secondary return value), and sand remains in hand.

- MC 1.10.2
- Minecraft Forge 12.18.3.2234

Nothing salient appears in the logs.

**Comment by payonel** [comment]
they're blocking the fakeplayer, not much more we can do

**Comment by payonel** [comment]
also, they've added auto sieve at a higher tier
