### ISSUE TITLE
[1.11.2][Feature Request] Rework Buildcraft Integration

### ISSUE THREAD

**Issue by starg09** [MightyPirates/OpenComputers#2338]
So, at this point in time there's no 1.11.2 mod supported by OpenComputers regarding energy. Mekanism may arrive soon, but besides that the closest one is probably Buildcraft (which is not yet released, but can be compiled and tested). **EDIT:** _Also there's a public alpha on their website, released on April 1st (it's real, not a joke release)._

One of the main changes on BC, however, is the return of MJ no longer as a dependance on RF/FE. So, right now even if both mods are present, no interaction is activated due to BC no longer handling the latter form of energy. It would be nice if we could use MJs as the power source for OC machines :)

No rush on this, of course. At this point in time both mods coexist in a pack with no significant issues whatsoever. Simply wanted to leave the integration suggestion noted somewhere!

**Comment by asiekierka** [comment]
Also, do keep in mind that this MJ works like the old MJ. Pulses!

(In addition, keep in mind that the energy system operates on micro-MJs now)

**Comment by cyberpunkbln** [comment]
Hello,
yes BuildCraft and many other Redstone Flux/Crystal Fkux (i think this is the brand new energysystem supported by the forge-team).

Other 1.12.2 Mod with Energy:

NeoTech (RF) - seems buggy and not well suported after the 1.9 release, i have it loaded but i think i will be it remove in the future and while the hope die last, i hope on the oldies but goldies from teamcofh:).

Actually Additions (i think they use the ne CF/CrystalFlux).

Tech Reborn (the old and good from IC energy:))

MachineCraft (i think the new CF).

Clearly Buildcraft uses the old MJ and the others the new CF, i think this are the thing that OpenComputers make think my mods dont have energy:).

Cu
