### ISSUE TITLE
[1.11.2] Error when trying to create robot

### ISSUE THREAD

**Issue by boof64** [MightyPirates/OpenComputers#2339]
Hello!

When I try to create a robot server shutdown with error "java.lang.NullPointerException: Ticking player" :'(
What could it be? =(((

Mod version 1.7.0.6
[crash-2017-04-11_22.46.21-server.txt](https://github.com/MightyPirates/OpenComputers/files/914369/crash-2017-04-11_22.46.21-server.txt)

P.S. it would be nice to support TechReborn energy=)))))

Thx)

**Comment by boof64** [comment]
I was try to load game in local mode without other mods (exclude OptFine), game was crash with some error when I was try to build robot. However, there were no craft items (proc, mem, sys unit) in my stack when I start game again.

P.S. sorry for my English...

**Comment by noaht8um** [comment]
I'm having the same issue. Using 1.11.2.

**Comment by xarses** [comment]
Please keep in mind, 1.11 is very much *alpha*, lots of problems will be around.

**Comment by Techokami** [comment]
If you're using OptiFine, get rid of it as it messes badly with every other mod in existence.

**Comment by boof64** [comment]
Thx. I tried to launch without OptiFine, fully clean installation... the result is the same.
