### ISSUE TITLE
Screen GUI is totally broken

### ISSUE THREAD

**Issue by char** [MightyPirates/OpenComputers#234]
Whenever I open a screen GUI it just does this:

![screenshot from 2014-04-26 16 38 08](https://cloud.githubusercontent.com/assets/4404985/2809108/769aef2a-cd59-11e3-8916-ff9e3f204663.png)

**Comment by char** [comment]
(On Linux Mint, with OptiFine)

EDIT: Disabled optifine, got same results.

**Comment by fnuecke** [comment]
Which version of OC? Did you try the [latest build](http://ci.cil.li)?

**Comment by char** [comment]
Latest build fixed, thanks.
