### ISSUE TITLE
add git commands

### ISSUE THREAD

**Issue by emanuele6** [MightyPirates/OpenComputers#2341]
It would be cool if git commands were available in game

**Comment by payonel** [comment]
that would be a great oppm project: http://ocdoc.cil.li/tutorial:program:oppm

**Comment by xarses** [comment]
Also there is a basic [git downloader](https://github.com/OpenPrograms/Gopher-Programs/blob/master/gitrepo.lua) linked from  [OpenPrograms](https://openprograms.github.io/)
