### ISSUE TITLE
[1.7.0.6/1.11.2] OpenOS floppy not craftable + disappearing floppy disk

### ISSUE THREAD

**Issue by Exorion1er** [MightyPirates/OpenComputers#2345]
Hi,

First, I can't craft the OpenOS Floppy, here's a gif : 
https://gyazo.com/1f12600e31cc002d9377ec463b97e7f0

Also, when putting a floppy in the Disk drive, it disappears after picking it up again : 
https://gyazo.com/716ac744604467ca7666198b6d3419d2

Thanks for your work

**Comment by Exorion1er** [comment]
Some more infos for debugging : 

Everything is tier 1 in the computer, with a screen and keyboard. I have an EEPROM (Lua bios) and that's it.
I only use 3 mods; TreeChopper, JEI and OpenComputers

**Comment by payonel** [comment]
OC for 1.11 is painfully alpha, but thank you for reporting. At this time we expect most of the mod to not work for 1.11

**Comment by Exorion1er** [comment]
Yeah I guessed so, I'm not complaining btw, I'm just reporting it for you guys

**Comment by Vexatos** [comment]
Oh wait, there's two issues in one.

**Comment by Exorion1er** [comment]
Great, thanks !
