### ISSUE TITLE
weird move error

### ISSUE THREAD

**Issue by Nex4rius** [MightyPirates/OpenComputers#2346]
<img src="http://i.imgur.com/lEarkvR.png" />
OpenOS 1.6.1

**Comment by payonel** [comment]
Thank you, I know about this bug but forgot to address it...and I thought we have a ticket for it. But this is good, I'll resolve this.

**Comment by payonel** [comment]
fixed in f2b5e01730f5bd10303b58ffd1bbb34ad452013f
