### ISSUE TITLE
Unable to receive network messages sent by linked card via Relay

### ISSUE THREAD

**Issue by freznelfennec** [MightyPirates/OpenComputers#2347]
When a relay relays a message sent from a slotted linked card, it does not appear to show up on any port.  Looking at the Relay's code, it seems that the Relay may be sending the message on port -1, which is not valid.  Is this intentional, or an oversight?

**Comment by xarses** [comment]
Please write up some details on what you built, what happened, what you expected to happen, etc ... Please also indicate your versions of MC, OpenComputers and Forge

**Comment by freznelfennec** [comment]
Minecraft 1.10.2, Forge version 1.10.2-forge1.10.2-12.18.3.2254, OC version 1.6.2.7.

What I built is a Relay connected to a computer via network cable, with a linked card slotted into the Relay.  I then used a second computer, not connected to the Relay, to send a message to the Linked Card.  

What I expected: For a modem_message signal to be posted to the computer connected to the relay.

What happened: The relay lit up, and I saw in the GUI that it did indeed relay a packet, however no modem_message signal was posted to the computer.  Yes, the computer contains a network card.

**Comment by freznelfennec** [comment]
My only conclusion as to why this is happening is that the message is not getting posted to a port which can be opened, or it's a high-numbered port (I have tested ports 1 through 20).  As I said, from what I see of the Relay code it will send a packet on the port -1 if no port is provided.  If this is the case, may I request that this be changed to a port which can actually be opened?

**Comment by freznelfennec** [comment]
Another suggestion which may help in the future is to add a config option that, when enabled, will print all sent network messages (sender address, receiver address, port, contents, etc) to the console.  If this had existed it would have made my initial debugging on the issue take much less time.

**Comment by magik6k** [comment]
It's due to a fact that linked cards have no ports. They are just 1 data chanel. what switch sends to it can be written as(IIRC) `component.tunnel.send(senderAddress, receiverAddress, port, data)`. Yes, this allows to spoof src/dst addresses. You can test exact parameter order by running `dmesg` on the computer with the card and sanding a packet from the one connected to relay.

**Comment by freznelfennec** [comment]
No, you fail to understand the situation.  I understand the normal use of linked cards perfectly.  Normally, when installed on a computer, they fire a modem_message event.  I am talking about when a Linked Card is installed in a RELAY (see image below).  I have confirmed that messages are being broadcast by the relay from the linked card, but these messages are not generating signals on any connected computers.  See the other images for proof that messages are actually being sent from the relay.




![image](https://cloud.githubusercontent.com/assets/13923468/25059811/9f511800-215b-11e7-9f84-3d09c49d83b0.png)

![image](https://cloud.githubusercontent.com/assets/13923468/25059823/de957628-215b-11e7-9a20-ca83649586b2.png)

![image](https://cloud.githubusercontent.com/assets/13923468/25059832/0a7cfb44-215c-11e7-960f-25652a5ef0a6.png)

**Comment by freznelfennec** [comment]
Oh, forgive me, I misread your comment.

**Comment by freznelfennec** [comment]
Thank you for the help, I got it working.

**Comment by guillaumearm** [comment]
Hi @elijahlorden, I'm falling into the same issue, how did you fix it ? do you remember ?

**Comment by freznelfennec** [comment]
It's not ideal, but I use a server to forward network traffic through the card.  Here is the solution I came up with: https://github.com/elijahlorden/StattenOS/blob/before_rewrite/miniapps/LinkedRelay

Keep in mind, OC won't see the relay server when performing network pathing, so you will need to come up with your own solution for that.

**Comment by guillaumearm** [comment]
so you don't use any OC relay ? is it ?

**Comment by freznelfennec** [comment]
I use that linked relay program to send messages between OC networks.  Think of each network of relays as an isolated system, and the linked relay program as a bridge between them.
