### ISSUE TITLE
Server Crashes when Making a Robot(OC1.7.0.6)

### ISSUE THREAD

**Issue by Richhobo1216** [MightyPirates/OpenComputers#2348]
I was trying to make a robot on my own server, and as soon as I clicked the 'Assemble' button, the server crashes and I get kicked. This happens regardless of what I put into the Electronics Assembler; even putting the bare minimum(case, cpu, ram) causes a crash. I would use 'Creatix'(I'm building it in creative), but it doesn't have all the upgrades I want(Geolyzer).

Here's the crash report for the server:
https://pastebin.com/i2Fg534J

I can send along the logs for the server or for my client, if you need it. Any help would be greatly appreciated.

**Comment by payonel** [comment]
1.11 builds are alpha, most is not working.

**Comment by Richhobo1216** [comment]
@payonel I know, but it's still worth reporting so the devs actually know the issue exists.  Btw, do you know if the issue just happens with just OC, or is it an incompatibility with some mod?

**Comment by payonel** [comment]
@Richhobo1216 i agree, I'm glad you reported it. just wanted to let you know 1.11 is incomplete at this time.
