### ISSUE TITLE
event timer

### ISSUE THREAD

**Issue by Nex4rius** [MightyPirates/OpenComputers#2351]
This is either a bug or a significant change for the event timer that hasn't been documented. (yay I finally found the problem in my <a href="https://github.com/Nex4rius/Nex4rius-Programme/pull/301/files#diff-38912729fdcc8db924e1c3a5d7af632eR1129">program</a>)
<img src="http://i.imgur.com/qUqmGVw.png" />
<img src="http://i.imgur.com/emJkYuL.png" />
<img src="http://i.imgur.com/k2bRrGh.png" />

**Comment by Nex4rius** [comment]
My best guess is this change here
https://github.com/MightyPirates/OpenComputers/commit/400d7eed7eabbff601a1eced86ef8e31b1eadf6b#diff-3386d27b28d1774e4f4f47af2de8d00cL23

**Comment by xarses** [comment]
Just to be clear, the expected result was that the timer was executed once correct?

**Comment by Nex4rius** [comment]
Yes that is how it was and how I understand
<img src="http://i.imgur.com/LoHo4Ea.png" />

**Comment by payonel** [comment]
thanks for the report

**Comment by payonel** [comment]
https://github.com/MightyPirates/OpenComputers/commit/807dfb7224651ceb2670ccbc882dedffc03c6f4c
