### ISSUE TITLE
sh.lua: command substitution within double-quotes doesn't preserve whitespace

### ISSUE THREAD

**Issue by memotype** [MightyPirates/OpenComputers#2352]
I.e., this works:

```
/home # echo "foo    bar"
foo    bar
```

The 4 spaces between foo and bar are preserved in the output, but

```
/home # cat test.txt
foo   bar
    baz
/home # echo "`cat test.txt`"
foo bar baz
```

The whitespace is lost. I know sh.lua isn't exactly supposed to be a POSIX shell or anything, but it would be nice if there was a way to preserve whitespace on the command line. Especially if you're doing things like this on the command line with Lua files, where whitespace is syntactically significant. (Obviously, the echo/cat example is contrived and redundant, but there are other cases where you want to use command substitution in a command)

**Comment by payonel** [comment]
fix with 57698127fb65b93dd843fa7007ea451bf7affd32
