### ISSUE TITLE
Suggestion for the repository itself: an EditorConfig file

### ISSUE THREAD

**Issue by brisingraerowing** [MightyPirates/OpenComputers#2353]
[EditorConfig](http://editorconfig.org/) is a simple text-based file that defines how an editor should format code. Some editors also have additional configuration keys that can be used to control their behavior. Having an EditorConfig file would help people who don't use the same code formatting as you guys do.

Most editors have built in support for these files, and there are plugins for many that don't.

What do you guys think of this?

**Comment by Vexatos** [comment]
intelliJ is actually pretty smart about formatting, it should do all of that anyway.

**Comment by brisingraerowing** [comment]
I usually use Atom Editor for editing things (I don't use intelliJ or any other Java IDE as I don't usually use Java all that much, I usually use Visual Studio for C#), and it is somewhat smart about formatting, but it has its quirks (as do all editors).

I used to use Notepad++, but that editor has all sorts of formatting quirks.
