### ISSUE TITLE
Inventory controller method for getting name of inventory

### ISSUE THREAD

**Issue by Cruor** [MightyPirates/OpenComputers#2354]
The inventory controller can allready pull information that would break the fourth wall (such as item registration name i.e. oc:component and damage values).

Assuming that you are interacting with a certain inventory (such as an assembler) by saying everything with inventory size of X has to be Y is a pretty silly solution.

The result of the function could be something along the lines of `getStackInSlot()` and return the block registration name and damage value.

**Comment by Vexatos** [comment]
To get the name of a block, you can use the geolyzer. It is also an upgrade.

**Comment by thiakil** [comment]
@Vexatos How would you do that in an adapter or transposer connected to a PC?

**Comment by payonel** [comment]
we have this now, back ported to 1.7.10 even (See our 1.7.2 release)
