### ISSUE TITLE
Presents given when crafting regular items.

### ISSUE THREAD

**Issue by DonBruce64** [MightyPirates/OpenComputers#2355]
I had a player report this one to me on a server I run, so I'd thought I'd relay it to your guys.

Basically, he crafted 9 iron ingots from an iron block on a regular crafting bench and ended up with an OC present in his inventory.  I know he can't of crafted an OC component directly as I have the server set up to prohibit specific items in specific dimensions, and OC items are prohibited in the dimension he was in.

Currently running OpenComputers-MC1.7.10-1.5.22.46-universal on the server, so if this bug has been fixed in a newer version let me know and I'll fight the user protests to bounce the server for an update.

-Don

**Comment by MyNameIsKodos** [comment]
As is usually the case, it's recommended that you update to the latest version, and then see if the bug still exists.

**Comment by payonel** [comment]
no repro, i've been using oc 1.6 and 1.7 for years and never seen this. please update
