### ISSUE TITLE
[1.11.2] Please add TechReborn / IC2 Power Support. 

### ISSUE THREAD

**Issue by StoneLegion** [MightyPirates/OpenComputers#2356]
Minecraft: 1.11.2
Forge: 13.20.0.2282
Mod: 1.7.0.6

Sadly getting the No Power Systems found. I'm right now using both TechReborn and IC2 (Experimental Builds from players Jenkins).

Thanks.

**Comment by magik6k** [comment]
Soooo Minecraft 1.11 or 1.10?

**Comment by StoneLegion** [comment]
my mistake will update this and my last. 1.11.2

**Comment by kreezxil** [comment]
I'm getting the ussupported power message too, and IC2 is now on CurseForge as well as BuildCraft for 1.11.2, I have both in my pack.

If opencomputers uses RF or even FE, shouldn't the mod just sit around quietly and wait to receive said power. But in the case where such power doesn't exist, isn't that onus on the pack maker to set the mod to "nopower"?

**Comment by kreezxil** [comment]
Does OpenComputers-MC1.11.2-1.7.0.13.jar contain anything regards to this issue thread?

**Comment by xarses** [comment]
@Vexatos does #2369 from today resolve this?

**Comment by Vexatos** [comment]
IC2 Energy support is not back in the 1.11 branch.

**Comment by davv1** [comment]
Still can't connect ANY power source to my case/charger/power converter. I'm making issue with detailed logs as now.

**Comment by StoneLegion** [comment]
Thanks for letting me know 4 Years later with the No.
