### ISSUE TITLE
internet.request not working on Content-Type "application/json" ?

### ISSUE THREAD

**Issue by SeaLife** [MightyPirates/OpenComputers#2358]
Hey guys, i was trieng to build a rest client in OC but i cant getting it working due to a bug (maybe), but maybe im just stupid :D

Script to reproduce:

```lua
local internet = require("internet")

local function doRequest(url)
	local h = internet.request(url)

	h.read(100)
	h.read(100)
	local readOnce = h.read(100)

	if(readOnce == nil) then
		print("[" .. url .. "] failed to work ...")
	else
		print("[" .. url .. "] works .. ")
		h.finishConnect()
	end
end


doRequest("https://google.de")
doRequest("https://r3ktm8.de")
doRequest("https://r3ktm8.de/index.php/some-pages")
doRequest("https://r3ktm8.de/index.php/rest/test")
doRequest("http://google.at")
```

the only difference i can see is that https://r3ktm8.de/index.php/rest/test returns 'application/json' insted of 'application/html'
i tried the main page 'r3ktm8.de' to ensure its not a ssl error...

The Script says "url works .." on every page except "https://r3ktm8.de/index.php/rest/test"

Regards
SeaLife

**Comment by magik6k** [comment]
You should use `finishConnect` before read as it's role in to ensure the content is readable, at least that wht the doc says: http://ocdoc.cil.li/component:internet. Let me know if it fixes that for you.

**Comment by SeaLife** [comment]
Hey,

tried this: 

```lua
local internet = require("internet")

local function doRequest(url)
	local h = internet.request(url)
	h.finishConnect()

	h.read(100)
	h.read(100)
	local readOnce = h.read(100)

	if(readOnce == nil) then
		print("[" .. url .. "] failed to work ...")
	else
		print("[" .. url .. "] works .. ")
--		h.finishConnect()
	end
end


doRequest("https://google.de")
doRequest("https://r3ktm8.de")
doRequest("https://r3ktm8.de/index.php/some-pages")
doRequest("https://r3ktm8.de/index.php/rest/test")
doRequest("http://google.at")
```


same result.

**Comment by magik6k** [comment]
You discard first 200 bytes. If the page you request is less than that, you will get nil on third read, so it still seems correct.

**Comment by SeaLife** [comment]
Hey,

its correct that i discard the first 200 bytes, sorry to mention it i always test it without and with discarding these 200 bytes.

I also tried to just read like ~10 bytes, still not working :/

Regards
SeaLife

**Comment by SeaLife** [comment]
Hey,

ok now i wrote a litte Java-Application to test http connection to my website...

Its kinda weird because if i connect to "https://r3ktm8.de" it works just fine but if i connect to the rest service i get an SSL-Exception in Java...

I'll try updating Java and run the same tests again...


Regards
SeaLife

**Comment by SeaLife** [comment]
Another Update,

updated Java and realized that my SSL-Certificate expired yesterday (im dump :D) ...

Updated the SSL-Certificate ...

```
h = internet.request("https://r3ktm8.de")
print(h.finishConnect()) -- returns 'true'


h = internet.request("https://r3ktm8.de/index.php/rest/test")
print(h.finishConnect()) -- returns 'nil     https://r3ktm8.de/index.php/rest/test'
```

Did the same test in Java (pure Java), works just fine (on the same Host)

// Edit: not done with pure java but now, it fails too o.O

```
Something went wrong... [https://r3ktm8.de/index.php/rest/test]
java.io.FileNotFoundException: https://r3ktm8.de/index.php/rest/test
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at java.net.URL.openStream(URL.java:1045)
        at TestOC2358.readFromUrl(TestOC2358.java:14)
        at TestOC2358.main(TestOC2358.java:38)
```

But if i open this up in the Browser i get a valid JSON Response but with 404 HTTP Code... Maybe the Internet-API throws responses with 404 away?

Regards
SeaLife

**Comment by GHXX** [comment]
If this issue is still reproduce able you could try using wireshark in conjunction with a local world. But if you do then use http instead of https so you get to see what opencomputers actually receives.
