### ISSUE TITLE
Shell variable or something to enable/disable string metatable access

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#236]
(I'm not sure if the string metatable is a global thing, (as in it affects all the computers) but...)
Idk it would be nice to have a shell variable or something to enable/disable string metatable access... something for advanced users that would be disabled by default...

**Comment by fnuecke** [comment]
Since this can potentially be used to break the sandbox and/or inject code to be executed in non-time-limited mode - now or in the future - that won't happen.

**Comment by SoniEx2** [comment]
> and/or inject code to be executed in non-time-limited mode

Uhh if it's possible with strings then it must be possible with tables...

> potentially be used to break the sandbox

No? Unless the string metatable is shared across Lua states...?

**Comment by fnuecke** [comment]
No, because those are not global. The string metatable applies to _all_ strings. A table's metatable does not apply to all tables.

**Comment by SoniEx2** [comment]
@fnuecke so (string metatable powered) faster networking?
everything has a good side

**Comment by fnuecke** [comment]
No. It's global _per computer_, each has its own Lua state.
Also, how in a million years would such a game breaking bug be a good thing?

**Comment by SoniEx2** [comment]
@fnuecke it would be a config option, like bytecode loading...

and it's not game-breaking if it's per computer...

**Comment by SpiritedDusty** [comment]
Game breaking as in, you can run code outside of the sandbox and do malicious things.

**Comment by SoniEx2** [comment]
@SpiritedDusty then show me how...

**Comment by fnuecke** [comment]
I was referring to your networking idea, under the condition that it were possible because that's the basis on which you proposed it, therefore... oh screw this. Just stop. Fork OC and remove the sandbox if you want. Make it possible to interface Java directly and manipulate the game world state from Lua. Nobody is stopping you.
