### ISSUE TITLE
[1.11.2] Removing tools from robot deletes them

### ISSUE THREAD

**Issue by davue** [MightyPirates/OpenComputers#2360]
Using: 1.11.2-1.7.0.12

If you try to remove a tool from a robot it will disappear in the robot and in your inventory, deleting it completely.

## How to reproduce
Step 1: Take a robot.
Step 2: Give him a tool.
Step 3: Take the tool from him.
### What you expect
The bot no longer has the tool and you have it now.
### What actually happens
Both, you and and the robot don't have the tool anymore.

**Comment by Vexatos** [comment]
Does any sort of error message appear in the server log while it happens?
