### ISSUE TITLE
[1.11.2] IC2 adapter support

### ISSUE THREAD

**Issue by Aleszp** [MightyPirates/OpenComputers#2361]
Forge: forge-1.11.2-13.20.0.2282
IndustrialCraft: industrialcraft-2-2.7.9-ex111
OpenComputers: OpenComputers-MC1.11.2-1.7.0.6

Any chance for accessing Nuclear Reactor or energy storage units such as Batbox/CESU?

**Comment by ItzKdoge20YT** [comment]
yeah, it happened to me, everytime i run the `component.reactor()` thing on lua it doesn't work
because ic2 is not supported yet so i can't accessing the ic2 reactor eu and heat ones

**Comment by payonel** [comment]
only for 1.12
ic2 components that are currently supported (we've been fixing stuff)
"Nuclear Reacator", "Reactor Access Hatch", "Reactor Chamber", "Reactor Fluid Port", "Reactor Redstone Port", "Reactor Coolant Injector" (rsh and lzh)

Mostly, these items provide the energy interface to oc. If you need to modify their inventories, use an inventory controller upgrade (which you can also place in the adapter)
