### ISSUE TITLE
[1.11.2] Client crash from rendering a robot

### ISSUE THREAD

**Issue by mezz** [MightyPirates/OpenComputers#2362]
I'm crashing on the Modoff server:
https://gist.github.com/mezz/1394809fe19febe162bb27eb4f7699b6

I didn't see a robot but according to the crash log it was pretty much at the top of the world (which is where I was flying, I might have been inside it somehow).
Someone went to the same spot to see what happened and they crashed the same way.

The solution was to remove the robot block using the server console.

**Comment by Vexatos** [comment]
This means the robot's inventory... does not exist? I don't know how that's possible... Do other robots render properly?

**Comment by mezz** [comment]
I think there were two robots next to each other, but I couldn't see them. For now robots are disabled items on the server.

**Comment by Vexatos** [comment]
Not reproduceable at all, but maybe fixed via f947f8da60299c0595b7d5cf3dd18e68abaed699.
