### ISSUE TITLE
maven dep typo ??

### ISSUE THREAD

**Issue by loordgek** [MightyPirates/OpenComputers#2367]
compile "li.cil.oc:OpenComputers:MC1.7.10-1.5.+:api" 
why is there a + ??

http://www.minecraftforge.net/forum/topic/55877-1112-help-with-adding-api-to-buildgradle/

**Comment by loordgek** [comment]
hello anybody ??

**Comment by skyem123** [comment]
That `+` chooses the latest minor version of OpenComputers.
For example if `1.5.0` was released then it'd use it, if `1.5.1` was released, it'd use that instead.
This is so you get the latest bug fixes, while also avoiding large breaking changes.
