### ISSUE TITLE
[1.11.2] Cable is glitchy, voids stack once placed. 

### ISSUE THREAD

**Issue by shortybsd** [MightyPirates/OpenComputers#2368]
MC 1.11.2
Forge 2284
OpenComputers-MC1.11.2-1.7.0.13.jar

When placing down a cable, the whole stack disappears as you only place the one down. When putting into a vanilla chest or Refined Storage, it doesn't put anything in the vanilla chest. It just voids it. When placing into an RF storage, it shows a blank texture with a tiny 0. Same issue, it voids entire stack and you can only get back the one piece. Also the Adapter doesn't seem to work with anything besides vanilla blocks as in furnace, chests e.t.c.

[Example of what it looks like](http://imgur.com/asq5Bt0.png) in Refined Storage, I think the issue is with the /# example Cable #5773/0
[Another Example](http://imgur.com/QsIxO9h.png)

**Comment by Vexatos** [comment]
This should be an issue all the way back to 1.7, but for some reason it isn't.

@fnuecke Should I do this fix on older versions as well? Not having it doesn't seem to cause issues there...

**Comment by shortybsd** [comment]
Changes from 1.10.2 to 1.11

A major change is that itemStacks can't be null anymore, the EMPTY (obfuscated name ItemStack.field_190927_a) is used instead.  i.e.
When the player's hand is empty, the ItemStack is no longer null.  instead, the itemStack.func_190926_b() returns true.
  func_190926_b() has changed to isEmpty() in the latest version of the mappings
An empty ItemStack is ItemStack.field_190927_a - use this instead of Null for ItemStacks.

**Comment by shortybsd** [comment]
That was one of the major changes from 1.10.2 to 1.11x, hence why a lot of mods still aren't updated to 1.11x.
A major change is that itemStacks can't be null anymore, the EMPTY (obfuscated name ItemStack.field_190927_a) is used instead.  i.e.
When the player's hand is empty, the ItemStack is no longer null.  instead, the itemStack.func_190926_b() returns true.
  func_190926_b() has changed to isEmpty() in the latest version of the mappings
An empty ItemStack is ItemStack.field_190927_a - use this instead of Null for ItemStacks.
ItemStack stacksize is now private.  Access through:
   getter: func_190916_E() - getCount() in the latest version of the mappings
   setter: func_190920_e() - setCount() in the latest version of the mappings
   func_190917_f(int i) : increase stacksize by i  --> grow() in the latest version of the mappings
   func_190918_g(int i) : decrease stacksize by i  --> shrink() in the latest version of the mappings
An empty ItemStack is ItemStack.field_190927_a - use this instead of Null for ItemStacks
ItemStack.loadItemStackFromNBT() has been changed to a constructor instead

**Comment by Vexatos** [comment]
That is not related to this issue at all.
