### ISSUE TITLE
3D printer Redstone interection suggestion

### ISSUE THREAD

**Issue by SFort** [MightyPirates/OpenComputers#2372]
Could there be a bool to set if players can interact with 3D printed blocks that have multiple states.
(For example the way iron doors handle)

**Comment by xarses** [comment]
You should be able to do this already. See `setButtonMode()` and the `state` arg of `addShape` http://ocdoc.cil.li/component:3d_printer

**Comment by SFort** [comment]
I used iron doors as a example because either way if ButtonMode is false or true,
A player can still interact with the block it just does not automatically revert.
I think it would be nice if you could make a block state be controlled only by redstone no right-clicking.

**Comment by ReTeYeZ** [comment]
Yes that'd be nice.
It could look like this:

`
setInteractionMode(value:boolean)`
_Sets whether the block can be right clicked by a player_

`isInteractionMode():boolean`
_Gets whether the block can be right clicked by a player_
