### ISSUE TITLE
Not able to interact with gas tank from Mekanism 

### ISSUE THREAD

**Issue by the-papi** [MightyPirates/OpenComputers#2373]
I am not able to interact with gas tank from Mekanism mod via Adapter with Tank Controller Upgrade.

**Comment by xarses** [comment]
Which versions of Forge, MC, OpenComputes, and Mekansim is this for?
Are there any tracebacks in the server log when you attempt to do this?

Generally fluid tanks are all subclasses of the type from forge, if buckets / cells / bottles (depending on your other mods and if the fluid is allowed in buckets) they should be readable by the thank upgrades

**Comment by payonel** [comment]
I'd like to give @xarses a thank upgrade for all the hard work he does here

**Comment by Sognus** [comment]
@xarses  

Hello, I am an admin of server where @PapiCZ is playing. We are using following versions:

**Minecraft version:** 1.10.2
**Forge version:** 12.18.3.2254
**Mekanism version:** 9.2.2.301
**OpeComputer version:** 1.6.2.7

There are not tracebacks in server log, atleast I have not found any. Apparently, tanks from other mods are working well.

**Comment by thiakil** [comment]
I don't believe a Mek gas tank functions as a normal fluid tank.

**Comment by thiakil** [comment]
You may want to build a copy of Mekanism from the 1.10 branch, as that includes an OpenComputers Gas Tank Driver (for adaptor usage, no upgrade needed)

**Comment by xarses** [comment]
Yep @thiakil;

There appears to be an adapter driver for [gas](https://github.com/MightyPirates/OpenComputers/tree/master-MC1.10/src/main/scala/li/cil/oc/integration/mekanism/gas) already, so you should get a component when you drop an adapter adjacent to the gas tank TileEntity which should read its contents, sorry robots aren't supported this way.

**Comment by thiakil** [comment]
@xarses That appears to be only for GasStack (I guess for if you have a Fluid Tank with a Gas fluid in it and that tank is in an inventory), and is also not compiled in 1.10 branch (Mekanism mod integration is commented out in Mods.scala)
