### ISSUE TITLE
[1.11.2] OpenComputers not recognizing IC2 as a viable energy source

### ISSUE THREAD

**Issue by drewbit** [MightyPirates/OpenComputers#2374]
I have both mods installed and I'm getting the "No supported power providing mod available" when I enter the world, not sure what to do here.

OpenComputers Version: OpenComputers-MC1.11.2-1.7.0.13
IC2 Version: industrialcraft-2-2.7.12-ex111
Forge Version: 13.20.0.2294

**Comment by magik6k** [comment]
Duplicate of #2356
