### ISSUE TITLE
[1.11.2] OpenComputers does not recognizing BuildCraft as a viable energy source

### ISSUE THREAD

**Issue by mezz** [MightyPirates/OpenComputers#2376]
![2017-05-10_13 14 35](https://cloud.githubusercontent.com/assets/916092/25919184/be60f2ac-3582-11e7-82cf-fc6f95085e06.png)

The new Buildcraft alpha is loaded but OC does not detect it.

**Comment by NickNackGus** [comment]
Last I checked, OpenComputers is not currently enabling support for mods that are in alpha. Once it's out of alpha, support may be re-added. If I'm wrong, please correct me.

**Comment by xarses** [comment]
Dupe of #2338 and possibly resolved by #2369 (not merged)

**Comment by Vexatos** [comment]
Essentially a duplicate of #2338.
