### ISSUE TITLE
request to extra bee geno pool stand

### ISSUE THREAD

**Issue by nailfor** [MightyPirates/OpenComputers#2377]
Extra bee (binnie mod) 2.0-pre15
OC 1.6.2.12
Minecraft 1.7.10

The adapter does not see the stand with the database gene. The information in the database falls after research the DNA sequence in sequencers.

**Comment by xarses** [comment]
I don't understand, There doesn't appear to be any adapter support for Extra Bee's (at least not from the OC side). Are you a new mod [integration](https://github.com/MightyPirates/OpenComputers/tree/master-MC1.7.10/src/main/scala/li/cil/oc/integration)? Or reporting that some function that exists that isn't returning correctly?

**Comment by nailfor** [comment]
Yes, there is no adapter support for Extra Bee's

This is stand lab:
https://binnie.mods.wiki/wiki/Lab_Stand

This would make it possible to automate the investigation of alleles using already known alleles in the gene database
Of course, I can use os to store such information, but then the genepool and the database will not be synchronized
