### ISSUE TITLE
[1.11.2][1.7.0.21] OC not accepting any power types.

### ISSUE THREAD

**Issue by Rosethorns** [MightyPirates/OpenComputers#2382]
Open Computers does not appear to accepting any power types from 1.11.2
types tested both with a converter and without:
EU
Immersive Engineering IF
and RF

Currently the only way to use OC on this version is to turn power requirements off.

incidentally The One Probe does not show any energy measurement on OC blocks, this is odd because it will normally show energy measurements for everything that can accept power. Which means that TOP isn't recognizing it as a power reciever.

**Comment by xarses** [comment]
Presently this is expected behavior as 1.11.x support is Alpha quality. A build from today *might* work as #2369 was just merged.

Duplicates #2314

**Comment by Rosethorns** [comment]
I understand that. But this version in the title is the version which has forge energy merged. This version contains Vexatos' recent forge energy acceptor code and it isn't accepting any power from forge energy compatible mods.

Clear? @xarses @payonel
