### ISSUE TITLE
Request: Make it possible to differentiate villager with the Trading Upgrade

### ISSUE THREAD

**Issue by MalkContent** [MightyPirates/OpenComputers#2383]
A villagers trades disable after a number of uses and to reenable them, you have to complete other trades with the respective villager, so it would be quite helpful to be able to identify the other trades of the same villager.
Maybe by including a form of villager id in the trade itself or make the trades a sub table of a villager table.

**Comment by payonel** [comment]
I've added a new method on the Trade object (you get a list of these from getTrades)
Each trade has a new sort index (via `getSortIndex`), that let's you group them by merchant
it is also added to our official docs: https://ocdoc.cil.li/component:trading
