### ISSUE TITLE
[1.10.2] Microntroller stay in component list after broken

### ISSUE THREAD

**Issue by ReTeYeZ** [MightyPirates/OpenComputers#2394]
I stumbled over this because my computer crashed, "too many components", even though there weren't too many connected.  Then I checked with component.list() and there where a few microcontroller components I had previosly connected (those didn't existed anymore by that time). Rebooting didn't fixed it, I had to break and replace the computer case to get rid of them.

**Comment by payonel** [comment]
can you repro this? perform the same actions as before and pin point the minimal repro and let us know if the repro is consistent.

Thank you

**Comment by ReTeYeZ** [comment]
Sry for the late answer, a bit busy atm. I hadn't had much time lately so I just did a quick test and I couldn't replicate. But later I realized that I haven't tested the exact same setup as before.
When the bug happened I had a TankController installed in the Microcontroller which might have been the cause. I'll investigate a bit more but it might take a while (exams are coming closer...).

**Comment by payonel** [comment]
sorry i cannot repro. if you see this again, please research the repro (rather than just report that it happened), something we can independently verify and thus fix (and make a new ticket for it when you do)

thanks
