### ISSUE TITLE
[1710] Syntax error in markdown freezes the game 

### ISSUE THREAD

**Issue by loveyanbei** [MightyPirates/OpenComputers#2395]
I'm translating the manual, encountered the problem.

syntax errors should be ignored in parsing md files, and show plain text instead

**Comment by loveyanbei** [comment]
I think the parser fell into an infinite loop, no crash, but cpu usage 100%

**Comment by xarses** [comment]
Can you identify or narrow down which pages and language you suspect are causing issues.

**Comment by xarses** [comment]
Are there specific pages and or languages that you are seeing this more on?

**Comment by loveyanbei** [comment]
On zh_CN localization of manual.
I found the reason
On the condition of long seq of chars，without stopping chars，numChars call returns 0 
which causes infinite loop
I tried to fix the issue.
But build failed on reobf stage ， telling me MALFORMED.

**Comment by loveyanbei** [comment]
my fix:


protected def maxChars(s: String, maxWidth: Int, maxLineWidth: Int, renderer: FontRenderer): Int = {
    var pos = -1
    var lastBreak = -1
    val fullWidth = stringWidth(s, renderer)
    while (pos < s.length) {
      pos += 1
      val width = stringWidth(s.take(pos), renderer)
      if (width >= maxWidth) {
        if (lastBreak > 0 || fullWidth <= maxLineWidth || s.exists(breaks.contains))
          if (maxWidth == maxLineWidth && fullWidth == maxLineWidth && !s.exists(breaks.contains)) return s.length
          else if(lastBreak == -1)
          {
            //lastbreak = -1, then return pos - 1
            //if return lastBreak + 1,we will run into infinite loop
            return pos - 1
          }
          else {
            return lastBreak + 1 //if we got a long sentence without breaks ,lastbreak still -1
          }
        else return pos - 1
      }
      if (pos < s.length && breaks.contains(s.charAt(pos))) lastBreak = pos
    }
    pos
  }

**Comment by payonel** [comment]
if you have a fix please provide as a PR

**Comment by 3TUSK** [comment]
This issue looks a bit similar with MightyPirates/TIS-3D#44 ...

Also, @loveyanbei besides congratulation on accomplishing such a big translation project - you seems to mix up the usages of half-width and full-width punctuations. Would you mind to correct that?

**Comment by fnuecke** [comment]
Yeah, I'm not sure I merged that fix back into OC, I'll have a look.
