### ISSUE TITLE
[1.11.2] OC-1.7.0.24 Tank on adapter with tank controller upgrade not Detecting any fluid

### ISSUE THREAD

**Issue by ItzKdoge20YT** [MightyPirates/OpenComputers#2396]

**Comment by ItzKdoge20YT** [comment]
i use adapter and tank controller upgrades for tanks on 1.11.2 with 2 computers and 1 relays and it didn't show up some programs didn't work, it was work before in 1.7.10

**Comment by ItzKdoge20YT** [comment]
![2017-05-21_17 12 54](https://cloud.githubusercontent.com/assets/13083280/26283363/4feb8526-3e51-11e7-8d4b-80bd318c7c78.png)
this was worked in 1.7.10 but 1.11.2 didn't work and it stay blinking on relay and its attempting to transmit data to another it could be relay or adapter issue

**Comment by xarses** [comment]
Thanks for reporting the issue, please keep in mind that 1.11 is very alpha

**Comment by payonel** [comment]
i'll be testing this feature for 1.12 - if the bug is a common mistake in oc code, I may back port, but MC 1.12 is our target version in general for mod integration issues

**Comment by payonel** [comment]
mod integration fixes will target 1.12
tested tinker tanks, enderstorage tanks, buildcraft tanks, ic2 tanks and even forestry rain tanks 
all working in our latest dev builds
