### ISSUE TITLE
Bug: Diamond Chip doesn't exist.

### ISSUE THREAD

**Issue by tia79** [MightyPirates/OpenComputers#2397]
I have other mods on my server that turns diamonds into Nuggets. However i cant make chips because of this reason. Any way the recepies can we tweaked to allow nuggets instead?

The item collides with Actually Additions i found.

-

**Comment by xarses** [comment]
Dupe of #1852

You can either edit the opencomputers recipes to your liking, or use something like minetweaker to resolve the conflict
