### ISSUE TITLE
Debug card permissions reset

### ISSUE THREAD

**Issue by Forecaster** [MightyPirates/OpenComputers#2399]
It seems the debug card doesn't like the server crashing or something. It's supposed to have my permissions for executing commands (scoreboard) but after restarting the server (perhaps after crashing) it stops being able to execute the commands, however it still has my name in the tooltip.

If I take it out and re-activate it and put it back the commands work again.

**Comment by xarses** [comment]
Which version of mc and oc is this for? 

Is there anything in the server log when attempt a command?

Is this reproducing on so and mp?

**Comment by Forecaster** [comment]
We're currently on 1.10 and OC 1.6.2.97-dev

If I'd seen anything in the log I would have posted it. The OC computer just spams that it can't execute the commands until I reset the debug card.

It's reproducing on the server. Clearly or there wouldn't be a problem. I've been too busy to specifically test anything.

**Comment by payonel** [comment]
there are a few issues here
1. if a server crashes without saving nbt data, there isn't anything more we can do
2. but, if you are just looking for a "just make it work" solution, use the default opencomputer settings, that is debugCardAccess=allow -- and no activation by any user is required

however, if you have a server world, with `debugCardAccess=allow`, and a `runCommand` that is failing saying it can't run the command. Then we have a problem with `debugCardAccess=allow`. That would need repro details (what command, mod versions) and a separate bug
