### ISSUE TITLE
Keyboards Crash Server

### ISSUE THREAD

**Issue by SpiritedDusty** [MightyPirates/OpenComputers#24]
When placing a keyboard on a computer while on a server, the server crashes. Doesn't happen on LAN multiplayer, just on dedicated server.

**Comment by fnuecke** [comment]
As usual, crash logs please. Could this be related to #23? If it's something else I'll try to fix this, too, before pushing the patch.

**Comment by SpiritedDusty** [comment]
Heres the crash log. http://pastebin.com/ehuLkEU0

Ah yes my bad I think its the same issue.

**Comment by fnuecke** [comment]
Yep, that should be the same thing.
