### ISSUE TITLE
[Request] improvement for linked cards

### ISSUE THREAD

**Issue by Tcll** [MightyPirates/OpenComputers#2400]
Instead of having just one link/card, allow the API to select a channel which would link to an address.

I've effectively used a creative chest to securely link multiple (more than 2) computers together across dimensions.

So why not allow the API to use channels to make secure piped ender connections (wormholes) to groups of other machines.

Idea from the TE Tessaract and AE2 p2p buses.

**Comment by GoneNomad** [comment]
_Not sure I am remembering this right and the wiki is no help._

The Adapter (I think) has a slot for an upgrade to remotely read blocks. Could we put multiple Linked Cards in multiple Adapters and talk through them?

**Comment by Tcll** [comment]
If it does work, that's quite the component limit wall there...
I don't think I works though, I think the Adapter upgrade slot is for inventory controller upgrades only, I could be wrong though...

My improvement only suggests 1 component.

I do agree as well, the documentation doesn't give much detail about much of anything...
I had to write down the docs of the Lua functions to figure them out.
(or hack where docs weren't available)
that includes both the wiki and offline docs.

**Comment by thiakil** [comment]
You could do this with a Server (and component bus I suppose) acting as a master, and the slaves having the other end of the linked cards.

Or perhaps Computers acting as network routers

**Comment by thiakil** [comment]
> (or hack where docs weren't available)

Do you have an example of where the documentation was inadequate?

**Comment by Tcll** [comment]
> You could do this with a Server (and component bus I suppose) acting as a master and the slaves having the other end of the linked cards
> Or perhaps Computers acting as network routers

I've been using servers with switches, but I wasn't asking for what I could
do, I was suggesting an improvement to cause less headaches and less lag.
(in some environments, including mine, even 1 OC machine means a buttload
of lag)
^ my FPS drops from 24 to 16 when booting just 1 machine...

of course, my computer is only a dual-core at 1.6 GHz with 4GB of RAM and a
GT430...
it's a common muscle ratio amongst my friends.

**Comment by Tcll** [comment]
> (or hack where docs weren't available)

> Do you have an example of where the documentation was inadequate?

the outdated manual, which I refer to quite alot, since I can see more text
than the wiki...

if you mean scouring the docs to find an occurrence of where I've had
trouble understanding something, I'll need a few weeks to gather and
validate everything.
(I work on alot of stuff, and my autism likes to focus on everything at
once, slowing me down)

**Comment by magik6k** [comment]
You can insert linked cards into relays. There are also software routing stacks.

**Comment by Tcll** [comment]
interesting, alright, I will admit I had no knowledge of the relay method,
hopefully there's no component limit there...

but as for my suggestion, I could just write a software to route on
channels using only 1 card.

**I'm not looking for a workaround**, I'm suggesting something better.

**Comment by thiakil** [comment]
Just had a quick look in the code, and this seems to be already possible, but requires a bit of NBT editing or Craft/MineTweaker trickery...

Each linked card should have an nbt key of `oc:tunnel` - set these to the same on more than the default 2 cards, and they should all talk!

**Comment by Tcll** [comment]
that's exactly why I'm suggesting.

yeah the "channel" is currently stored as an NBT tag, which I was able to
replicate with the dupe mentioned in the OP...

I'm looking to track those addresses and write an Lua script to manage them
automatically, based on an input event of course... :P

**Comment by Tcll** [comment]
oops, splitters, not switches, in my earlier post...
I always confuse the two, sorry.

**Comment by payonel** [comment]
after review and discussion, we feel that we cannot arbitrarily set link card addresses for some reasons
1. link cards (lore) represent a quantum entanglement, across any distance and across dimensions. unlike wireless cards, they only talk to their linked card
2. link cards create their link at the time they are crafted, and a pair of link cards create their channel address together

But we are adding a recraft recipe (2 link cards -> 2 link cards), you can link any two link cards (this will remove them from their previous link). And in case you are keeping track of which cards are linked to which cards (perhaps because you've autocrafted a bunch of them), you can call `getChannel()` on the card,
