### ISSUE TITLE
[1.7.10] Transposer and Tank Controller support for multitank blocks

### ISSUE THREAD

**Issue by BloodyRain2k** [MightyPirates/OpenComputers#2403]
It would be nice if support for multiblock tanks could be added like IC2's nuclear reactor which has a coolant and hotcoolant tank or Railcraft's boilers where the liquid one has even 3 tanks, steam, fuel and water.

Neither of these are currently accessible with OC 1.6.2.12 as they only give access to whatever is the first tank, simply because there's no parameter to request the info for more than one tank from a given side.

Just like they can access a given side's inventory's slots would they need, given that there are blocks with more than one tank, an additional preferably optional parameter that works as a tank index for this purpose.

**Comment by xarses** [comment]
Which MC version is this for? I thought this was working in 1.7.10, in that it returns all fluids

**Comment by BloodyRain2k** [comment]
Sorry, forgot to add that part: 1.7.10
And no it did not yet, it only returned the summary of all tanks.

Edit: ok, it seems that getFluidInTank(side) actually did return a summary of the contents even without Vex's fix : /
His fix though adds an optional index parameter to getTankLevel() and getTankCapacity() to allow also checking the other tanks.

**Comment by BloodyRain2k** [comment]
Just ran into a new issue and while it's now easy to check for the contents in various tanks in multitank blocks does the transferFluid() function lack that support.
It can only access the first tank for transfering.

So in case of tinker's smeltery which seems to dynamically create a new tank per liquid (it can hold a variety of different ones at once) it can only pour our the most bottom one which is the first "tank" of it.
It does report all liquids in it properly though so there's that :D just needs accessing them too.

Though there'd be the question whenever or not other mods can actually deny tank access past this, like RC liquid boilers intentionally not wanting you to get the fuel back out, even though that seems silly but whatever, and that being the reason why the steam tank's the first, water 2nd and accessible through the UI and the fuel the 3rd.

**Comment by Vexatos** [comment]
There isn't really a way to do this properly. While tank blocks do provide a way to get their individual tanks and their contents, the `fill` and `drain` methods do not care about that. External things have no control over which tanks receive which fluid. Well, not in a way that would be compatible with everything. The handling is up to the implementation of the tank.

**Comment by thiakil** [comment]
There is a FluidStack sensitive version of `drain`, but from what I can find that won't help Tinkers in 1.7.10 as it checks the passed FluidStack type is equal to `smeltery.getFluid().getFluid()` (in 1.10+ it should work fine).

EDIT: OC uses these but you need to have that fluid already in a tank if you want to drain a specific fluid.
