### ISSUE TITLE
[1.11.2] "Error"

### ISSUE THREAD

**Issue by trainzkid** [MightyPirates/OpenComputers#2407]
When the world first loads, in the chat, opencomputers says an "error" has occurred and to report my latest log file here, so see attached (since pastebin has a limit). OpenComputers v1.7.0.24
[fml-client-latest.txt](https://github.com/MightyPirates/OpenComputers/files/1033863/fml-client-latest.txt)

**Comment by SDUBZ** [comment]
same here transformer had errors upon world creation
http://puu.sh/w69l3/4e7774f364.log

Forge:1.11.2-2310
OC:OpenComputers-MC1.11.2-1.7.0.24

**Comment by DestinyPlayer** [comment]
https://www.dropbox.com/s/zyc4hkkawum1s7l/fml-client-latest.log?dl=0
Same here.

Forge 13.20.0.2310
OpenComputers 1.7.0.24

**Comment by mainrs** [comment]
Same here:
https://gist.github.com/SirWindfield/07630e67495c2e801d87118dd0f42af5

**Comment by Ozzymud** [comment]
Joining the crowd :P  

Forge: 13.20.0.2315
OpenComputers-MC1.11.2-1.7.0.24.jar


[fml-client-latest - Copy.log.txt](https://github.com/MightyPirates/OpenComputers/files/1066793/fml-client-latest.-.Copy.log.txt)
[latest - Copy.log.txt](https://github.com/MightyPirates/OpenComputers/files/1066794/latest.-.Copy.log.txt)

**Comment by payonel** [comment]
later builds not doing this: http://ci.cil.li/job/OpenComputers-MC1.11/
