### ISSUE TITLE
New Item: Laser Range Finder

### ISSUE THREAD

**Issue by GoneNomad** [MightyPirates/OpenComputers#2409]
Lately I have been wanting to make my creations a little less blind to the world (_and more blinding to others_).

A new item for Drones and Robots: A **Tier 2 Laser Range Finder**. Detects non-air objects/blocks, returns power of returned laser. 

Range is dependant on the power put into the laser. 1-32 allows for a maximum range of 16: 15 to get there, 1 to reflect off solid object/block, 15 to get back with a returned power of 1.

**Options:**
- Get to choose which direction the laser points (other than forward).
    - Drones can only point forward/up/down.
    - Robots can choose any side.
    - Would be a _lot_ more math, but getting to choose a heading and elevation.
- A high-energy Laser mode (1-255) power, range?): cannot get distance but can burn or if stronger, damage. Return true if it worked, false if not enough power.
    - Laser loses power per empty block travelled, increased distance increases loss.
    - If it hits an entity's face, they are blinded for a few seconds.
    - 66 or greater received power will set object/block on fire for (received power / 33) seconds.
    - 100 received power does 2 physical damage. An additional damage for each additional 50 received power.
    - A cool-down period of a tick or two per power used.
    - Laser mode will only use energy from installed Battery Upgrades. Stops some silliness.
    - 'zzt-pew' laser noise before discharge. Allows players some warning.
    - Cannot destroy blocks above a certain hardness (Redstone?) or at all.

A completely silly but cool idea is to allow Robots/Drones to recharge each other using the laser.

_Any and all numbers above are educated guesses._ Thank you for such a great mod!

**Reasons for existing:**
- Want to see if crops have grown without groping each one (Mainly this)
- Check for (intruders / changes in building / anything blocking my way) while patrolling before bumping into it
- Local cave/ground mapping
- Gives a ranged detect ability with less information for more power
- Gives an internal low-damage ranged tool for even more power and equipment
- Portable alternative to the Motion Sensor
- Lasers are cool (Could the laser be visible?)

**Example code:**

    local rf = require("range_finder")

    local maxPower = 255
    local range = rf.range(32, sides.down()) -- or rf.rangeDown(32)
    local batteryPower = rf.powerAvailable() -- returns battery power left
    local coolDown = rf.coolDown() -- number of ticks until ready to use either mode again

    if range and coolDown == 0 and batteryPower > maxPower then -- if something detected, cool down is done and power available
        worked = rf.laser(maxPower, sides.down())
    end

**Comment by Vexatos** [comment]
The Computronics Camera and Camera Upgrade allow you to find the distance between the source and a block at any angle in the direction the device is facing.

The motion sensor can be installed as an upgrade in newer versions of this mod.

**Comment by GoneNomad** [comment]
I'm busy today, but will be trying out the above suggestions on Monday. Thank you!
