### ISSUE TITLE
Confusing comment in config file

### ISSUE THREAD

**Issue by awsmazinggenius** [MightyPirates/OpenComputers#241]
The top of my config file says this (I haven't modified it in any way.)

```
# OpenComputers configuration. This file uses typesafe config's HOCON syntax.
# Try setting your syntax highlighting to YAML, to help readability. At least
# in Sublime Text that works really well.
# Note that this file is only written if it doesn't exist or is empty. This
# means that if new settings are added to mod, they will *not* appear in an
# already existing config file! Sorry about the inconvenience.
# OpenComputers configuration. This file uses typesafe config's HOCON syntax.
# Try setting your syntax highlighting to Ruby, to help readability. At least
# in Sublime Text that works really well. Note that this file is overwritten
# whenever you start the game! Changes to the comments may vanish.
# Note that all mentions of 'KB' or 'kilobyte' mean 1024 bytes.
```

Which is really confusing. It tells me to set my syntax to both YAML and Ruby, and it's telling me that the file only gets written to when it is empty or nonexistent, and that it gets overwritten on every game start.

**Comment by fnuecke** [comment]
That's just different comments having accumulated over time, if you have a look at [the current reference config](https://github.com/MightyPirates/OpenComputers/blob/master/src/main/resources/reference.conf#L1-L5) that comment is less... convoluted. Delete the comment or your whole config to let it regenerate.
