### ISSUE TITLE
[Request] Add Solar Upgrade to components list

### ISSUE THREAD

**Issue by GoneNomad** [MightyPirates/OpenComputers#2410]
I know of no way to see if a Solar Power Upgrade is installed. The regular generator works fine and shows up.

**Comment by Vexatos** [comment]
Doesn't running `lshw` show it?

**Comment by payonel** [comment]
indeed, `lshw` (which uses `computer.getDeviceInfo()`) reports a "Description" of "Solar panel" for the solar panel upgrade
