### ISSUE TITLE
[dev-1.7.10] Hangs on building

### ISSUE THREAD

**Issue by SupremeMortal** [MightyPirates/OpenComputers#2411]
Seems that one of the repositories is broken as building causes this to happen:

`:compileApiJava (Thread[main,5,main]) started.
:compileApiJava
I/O exception (java.net.SocketException) caught when processing request to {}->http://coloredlightscore.us.to:8080: Connection timed out (Read failed)
Retrying request to {}->http://coloredlightscore.us.to:8080`
As this URL is checked for every dependency, the build time is around 5 hours due to waiting for the timeout on every one.

**Comment by payonel** [comment]
we've removed color lights now
