### ISSUE TITLE
Cant Calibrate MultiScreen

### ISSUE THREAD

**Issue by Apexcookie** [MightyPirates/OpenComputers#2413]
I have tried multiple times but when ever i try to calibrate multiscreen it gives me this error
![2017-06-01_12 53 57](https://cloud.githubusercontent.com/assets/29040952/26698327/6c614fe8-46ca-11e7-81eb-376cca6c67ee.png)

**Comment by xarses** [comment]
Which OC and MC versions is this for?

`MultiScreen.lua` appears to be in your `/home` folder, where is this from I wasn't aware that this is something from OpenComputers.

**Comment by Fingercomp** [comment]
This bug tracker isn't a place to report bugs in programs written by other people. Report the bug to the author of this program.

**Comment by payonel** [comment]
@Fingercomp is correct
