### ISSUE TITLE
Getting command line arguments - arg table is nil

### ISSUE THREAD

**Issue by brisingraerowing** [MightyPirates/OpenComputers#2415]
How should I get the raw command line arguments to a lua program? I am using a lua implementation of Argparse, and by default it uses the `arg` table, which doesn't appear to exist in OpenOS. Is there another way to get the arguments as a table, or is this a bug?

MC: 1.10.2
OC: 1.6.2-dev-294a09edd
Forge: 12.18.3.2297

**Comment by payonel** [comment]
`local arguments_as_a_table = {...}`

**Comment by brisingraerowing** [comment]
@payonel  Thanks! That works!
