### ISSUE TITLE
Mod integration suggestion

### ISSUE THREAD

**Issue by LawsOfScience** [MightyPirates/OpenComputers#2417]
Been meaning to post this for a while.
Since the mod Draconic Evolution has successfully updated it's reactor to 1.10.2, I thought it would be good if you guys added some sort of integration like you have with other mods. I suggest this because the integration will allow for the reactor (with a few other things, possibly) to be automated with the computers from this mod. Some examples include shutting the reactor off when the temperature is too high, restarting it when the temperature is low enough, and regulating energy input/output to keep the containment field on the reactor stable.
Of course, this is just a suggestion, so you don't have to add it. Love this mod. :)

**Comment by brisingraerowing** [comment]
Draconic Evolution already has OC support built in, you just need an adapter.

**Comment by LawsOfScience** [comment]
Oh okay, I'll try again. Thanks!

**Comment by SDPhantom** [comment]
While the API is still yet to be documented, Brandon made a post here discussing it.
(Applies to both ComputerCraft and OpenComputers)
https://github.com/brandon3055/Draconic-Evolution/issues/260

**Comment by LawsOfScience** [comment]
Thanks
