### ISSUE TITLE
Server Rack Filler Panel Suggestion

### ISSUE THREAD

**Issue by Dudblockman** [MightyPirates/OpenComputers#2419]
A dummy item that could be inserted into server racks to cover an empty slot for aesthetic purposes.

**Comment by xarses** [comment]
no, you must have ugly racks with poor front to back airflow 😁 

Seeming basic idea, with fantastic aesthetic value... Maybe we just make it so the slots can be closed w/o adding a new item? Maybe srwench the slot?
