### ISSUE TITLE
robot.swing() not working correctly

### ISSUE THREAD

**Issue by gremlin-mod001** [MightyPirates/OpenComputers#242]
Since dev build 129 (for MC 1.7.2) robot.swing () with a pickaxe (or other tool) is not working correcly.
![oc_robot_error](https://cloud.githubusercontent.com/assets/6988796/2838832/22a7529c-d03c-11e3-8508-b9c22a1cb4d8.png)

**Comment by fnuecke** [comment]
Fixed... was a really stupid mistake. Seems I only tested without tools recently. Terribly sorry about that.
