### ISSUE TITLE
Compatability with OpenCubicChunks mod

### ISSUE THREAD

**Issue by SaphireLattice** [MightyPirates/OpenComputers#2420]
It seems that none of the blocks that have GUI are able to open it when the position of *block* (Not user) has Y<0 or Y>255. The interaction trough shift-click seems to work fine, but didn't checked the screen clickability.

Issue on OCC repo: https://github.com/OpenCubicChunks/CubicChunks/issues/216

**Comment by xarses** [comment]
Which OC, MC and Forge versions is this for?

**Comment by SaphireLattice** [comment]
Ah, sorry, should have known I forgot something.
The versions for the MC and mods are below.
- **Minecraft**: 1.11.2
- **OC**: [1.7.0.28](http://ci.cil.li/job/OpenComputers-dev-MC1.11/28/)
- **CubicChunks**: [0.0.612.0](https://cdn.discordapp.com/attachments/317206370359443458/322033016287395840/CubicChunks-1.11.2-0.0.612.0.jar)
- **Forge**: 13.20.0.2315

**Comment by asiekierka** [comment]
Fixed in OC 1.7.6.

**Comment by SaphireLattice** [comment]
...it's kinda funny how this is now basically necessary for any mod that wants to work on the increased heights minecraft version, given how it goes below 0

And whee, thanks ^-^
