### ISSUE TITLE
Converter error 1.11.2

### ISSUE THREAD

**Issue by KamiliaBlow** [MightyPirates/OpenComputers#2423]
industrialcraft-2-2.7.66-ex111
buildcraft-7.99.4
OpenComputers-MC1.11.2-1.7.0.29

OpenComputers has issued a power conversion error from mods

[latest.zip](https://github.com/MightyPirates/OpenComputers/files/1071972/latest.zip)

**Comment by payonel** [comment]
just fyi, i'm actually testing this for 1.12, and not 1.11
mod integration fixes for minor issues such as this won't necessarily be back ported (And in this case, it won't)

**Comment by payonel** [comment]
very much works in 1.12, closing as "won't fix" for 1.11
