### ISSUE TITLE
Feature request: Add the OpenComputers API documents to the ingame manual

### ISSUE THREAD

**Issue by Idrialite** [MightyPirates/OpenComputers#2424]
The title says it all. It'd be great to have another tab in the manual devoted to the API information in the online wiki so that users don't need a browser open (personally my PC is very weak, so running Chrome and MC is a problem).

**Comment by Vexatos** [comment]
For what it's worth, the API documentation can also be seen using Not Enough Items or Just Enough Items, by pressing the usage key.

**Comment by Idrialite** [comment]
Can you see every component and API in this way?

**Comment by ben-mkiv** [comment]
hm, maybe this helps you: you can get all the methods of something on the lua shell, so for example this gives you all methods of the GPU:
`=component.gpu`

**Comment by payonel** [comment]
dup of #2686
