### ISSUE TITLE
Problem by opening creative robot and no edit window when using edit command

### ISSUE THREAD

**Issue by JaccoRu** [MightyPirates/OpenComputers#2425]
I run a minecraft 1.10.2 server on my computer with forge-1.10.2-12.18.3.2254
I run also minecraft 1.10.2 client on my computer with forge-1.10.2-12.18.3.2254
Both use OpenComputers-MC1.10.2-1.6.2.7

When I play minecraft on the server I can't open creative robot interface by right clicking
Only sometimes it flits open for a split second but then immediately close again
And when I want to create a file I use "edit test.lua" the editor window won't show and the next line appear

When I play minecraft singleplayer the this problems won't happen and works everything just fine

Can someone tell me what might be the problem?

**Comment by payonel** [comment]
sorry, this does not repro. if you can repro in an isolated test (make new instance, new server, have only OC mod) please open a new ticket and provide new repro information, and link this old ticket.
