### ISSUE TITLE
Integration compile errors.

### ISSUE THREAD

**Issue by bonnedav** [MightyPirates/OpenComputers#2429]
When I try to compile in IDEA I get [This](https://pastebin.com/sMvEvJXQ) (pastebin). It seems to be a problem with integration APIs.

**Comment by bonnedav** [comment]
Never mind. My fix for IC2's servers being down got reverted in my local copy because I accidentally re-synced with GitHub, so that was causing this.

**Comment by bonnedav** [comment]
scratch that still same errors.

**Comment by bonnedav** [comment]
building from command line with `gradlew build` works. The problem is that building from within IDEA does not.

**Comment by thiakil** [comment]
You need to mark the relevant folders as excluded within IDEA, it does not import this from gradle.

**Comment by bonnedav** [comment]
So it's just better to use the command line to compile then?

**Comment by thiakil** [comment]
Once it's set up you should have no issues (until/unless another integration is re-enabled). Simply look in the build.gradle file and check the exclude from lines, and right click the relevant folders in idea, mark as, excluded.

You can also just use the `runClient` and `runServer` tasks from within IDEA - assuming you've imported it as a gradle project.

**Comment by bonnedav** [comment]
Thank you. Also how do I commit to GitHub? I run git commit and I get "changes not staged for commit."

**Comment by thiakil** [comment]
That is far beyond the scope of an Issue on this repo.

I recommend https://help.github.com/categories/bootcamp/ and https://git-scm.com/book/en/v2

**Comment by bonnedav** [comment]
Ok thank you.
