### ISSUE TITLE
Unintentional duplication of 3d print resulting in an infinite amount

### ISSUE THREAD

**Issue by kayila** [MightyPirates/OpenComputers#2430]
When using the example 3d print for of the well, I printed out one and when I placed it, it seemed to place two in rapid success (possible server lag, not certain) which resulted in me having a negative stack size. I could still place copies of this with the negative stack size which would result in me having an infinite amount. If these are broke, they can be picked up independently

This issue doesn't seem to happen every time that I place a print, but it has happened both for me and other players on my server.

This was done using:
Minecraft 1.10.2
Forge: 12.18.3.2254
OpenComputers: 1.6.2.7

**Comment by oolivero45** [comment]
I can confirm that this is happening to me too. However, when I tried to pick up one of the duplicated items, I received an internal server error and was unable to re-join my world without wiping my inventory by deleting my player file.

**Comment by skyem123** [comment]
O_o
That's odd, I'm not sure how much I can help with this, but I do want to try to understand what's going on here so later people who read this issue have a better idea.
@oolivero45, what versions did you use? MC, Force, OC, any other mods? Singleplayer?

I remember goofing around with 3D prints, I didn't have this issue so maybe it's something recent (or I was in creative mode)...

**Comment by oolivero45** [comment]
Multiplayer on MC 1.10.2 Skyfactory 3.0.8 - I'll check the mod version when I get the opportunity.

**Comment by kayila** [comment]
The problem might be solvable by running a check when a block is placed to
see if item stack size is <1 and, if so, set the stack to null and aborting
as opposed to decrementing the counter

**Comment by skyem123** [comment]
That could work, but since it seems to be reproducible, it might be better to work out why than to hack around it. 😛

**Comment by brisingraerowing** [comment]
AFAIK, this is actually a bug in Vanilla 1.10.2, caused by direct manipulation of stack sizes. 1.11 fixed it through the addition of getCount and setCount methods on ItemStack, which verify the count passed in.

**Comment by payonel** [comment]
The repro steps are not clear on this ticket. Can @kayila or @oolivero45 explain how to repro this bug? What patterns were used? What was the script code used to create the prints? How many prints were made? How were the print outputs used or taken?

Please be specific
