### ISSUE TITLE
[1.11.2] Error running the class transformer

### ISSUE THREAD

**Issue by nigrum-dente** [MightyPirates/OpenComputers#2431]
So here is the message that I get in-world:
![2017-06-19_22 31 13](https://user-images.githubusercontent.com/28484707/27306959-eed49aa8-5547-11e7-83d8-d7b9d1b6064c.png)

My forge version: 13.20.0.2315
OpenComputer version: 1.7.0.24

Mod:
-Fast Leaf Decay
-Guide-API
-Inventory Tweaks
-JEI
-OpenComputers
-Waila
-Wawla

And my latest.log:
https://pastebin.com/ZQmaZFzw

Edit:
So, small update:

To figure if it was due because of a mod, I disabled (I'm using Twitch to manage minecraft) every mod but OpenComputer and I still seem to have that error.
Here is the latest.log of it: https://pastebin.com/Uuaadvch

**Comment by nigrum-dente** [comment]
So, small update:

To figure if it was due because of a mod, I disabled (I'm using Twitch to manage minecraft) every mod but OpenComputer and I still seem to have that error.

**Comment by LordGuppy** [comment]
I have the same issue on 1.11.2 Here's my latest.log file
[latest.txt](https://github.com/MightyPirates/OpenComputers/files/1098478/latest.txt)

**Comment by MrEldritch** [comment]
Same message.

[latest.log](https://paste.ee/p/SVkdq)
[fml-client-latest.log](https://paste.ee/p/jzhfN)

**Comment by quartzsaber** [comment]
Same issue. I'll post the log later (I'm not home right now)

I wonder if it's related to robot's console not working after a reloading the world. (The robot's console displays what was there, but it does not get refreshed anymore. Rebooting the robot fixes it.)

**Comment by davv1** [comment]
Sligthy more info on #2468

**Comment by kencinder** [comment]
I too have this problem with OpenComputers-MC1.12.1-1.7.0.20

[fml-client-latest.log](https://github.com/MightyPirates/OpenComputers/files/1467035/fml-client-latest.log)

**Comment by payonel** [comment]
@kencinder this bug and others like it have been resolved, your log actually refers to a duplicate bug report we recently received, turns out it is sponge's fault. see #2616
