### ISSUE TITLE
Inconsistent side-dependent behavior with robot.use() in Sky Factory 3

### ISSUE THREAD

**Issue by booblebobble** [MightyPirates/OpenComputers#2435]
Shift-right clicking a block with an Actually Additions phantom connector should bind the connector to that block, which can be seen by mousing over the connector.  Using a robot to bind several connectors in sequence works if the block is in front of or below the robot, but not if the block is above the robot.  If the block is above, the first binding will succeed but all subsequent ones will fail.  Though strangely if you remove the connector from slot 1 (either manually or programmatically with robot.drop()) while the robot is cycling through the rest of them, it seems to start working again.

Demonstration: https://youtu.be/d97FByS6n2U

Version 1.6.2.7 in SF3.0.10

**Comment by booblebobble** [comment]
More info: Having a block in slot 1 while trying to use a wand on the block above me will place the block in slot 1 in front of me but do nothing with the wand.

https://youtu.be/SqRJAngxWEs

It almost seems like if there's an item in slot 1 then it somehow overrides the item in the tool slot, though the behavior is still different than if I had stone in the tool slot and ran the same robot.use() command: in that case the block is placed in the space directly above the space in front of the robot (angel upgrade, if it matters).

A workaround for the entire issue seems to be to leave slot 1 empty at all times and never use it for anything.  Everything seems to work as expected when I do that (so far)

**Comment by Vexatos** [comment]
What about using `robot.useUp` and `robot.useDown` instead of `robot.use(sides.up)`?

**Comment by Vexatos** [comment]
What about using `robot.useUp` instead of `robot.use(sides.up)`? [Those behave differently](http://ocdoc.cil.li/api:robot): the former will try to click the block above the robot, while the latter will click the block in front, on the top side. `robot.useUp(sides.up)`, for instance, will try to click the top side of the block above the robot. Not specifying a side makes the robot default to trying all possible sides.

**Comment by booblebobble** [comment]
Yes, robot.useUp seems to behave properly and not get messed up when things are in slot #1, so I'll use that instead.  Thank you.

Also I just caught that robot.use(sides.up, ...) was actually interacting with the empty block above and *in front* of the robot, instead of the one directly above it, so somehow the wands were being bound to an air block (which I'm not sure should be possible lol). robot.useUp binds to the correct one.  That would've bitten me in the long run too if I hadn't noticed.
