### ISSUE TITLE
1.6.0 feature gpu viewport

### ISSUE THREAD

**Issue by Nex4rius** [MightyPirates/OpenComputers#2440]
>Added: Possiblity to define a viewport on GPUs, allowing to copy data from off-screen for performance trickery.

I've checked http://ocdoc.cil.li/component:gpu but it doesn't have anything about the viewport. How exactly does this work or where can I get information about this?

**Comment by payonel** [comment]
By default, your viewport is equal to your resolution
Changing the resolution will change the viewport to match
But changing the viewport leaves the resolution unchanged (again, changing resolution will reset viewport to match)

For example, T2 screen and gpu gives you 80x25 resolution
Thus, your viewport is also 80x25

This will make your viewable area appear half as tall
`component.gpu.setViewport(80,12)`

Now any gpu writes done outside the 80x12 box will not render on the screen (the viewport is fixed to the top left of the resolution area. Thus `component.gpu.set(1,13,'x')` is not rendered)

You can copy sections of gpu data from outside the viewport
`component.gpu.copy(1,13,80,12,0,-12)`

**Comment by skyem123** [comment]
It would probably be a good idea if that was documented officially...
