### ISSUE TITLE
Add a custom, realistic CPU architecture

### ISSUE THREAD

**Issue by malucard** [MightyPirates/OpenComputers#2441]
OpenComputers has totally realistic computers: each part of the computer is properly and realistically limited.
I think being partially restricted to Lua really limits what programmers can do in this mod; even when writing bytecode, it's a bit too high-level (e.g. allows almost zero memory manipulation), and quite slow for complex programs, so the language itself is often the main bottleneck.
What do you think about adding a built-in architecture that emulates a lower-level, more life-like CPU? This idea has been zooming in my head since I met this mod. If you'd rather not, I'll implement it as a separate mod, then.

(btw, I'd implement this myself, if you like.)

**Comment by Pwootage** [comment]
It's been attempted a couple times (including once by myself), but (to the best of my knowledge) was never really fleshed out well. If you want to take a stab at it, there is documentation here: 
http://ocdoc.cil.li/tutorial:modding_architecture

Creating the architecture and integrating it with OC is pretty easy - but fleshing out the entire system, including an OS, is quite a bit of work.

**Comment by NickNackGus** [comment]
Yup, I heard of someone trying to implement an architecture before as well - RISC, if I remember right, though I could be wrong. I'd recommend providing an option to compile Lua to your architecture if possible, as well.

**Comment by magik6k** [comment]
There is whole forum section for this: https://oc.cil.li/index.php?/forum/48-architectures/

**Comment by payonel** [comment]
We invite the community to develop additional CPU archs but OC is not looking to add any natively to the mod

**Comment by Techokami** [comment]
Yeah there's already several addon mod projects doing this: 

- [Thistle](https://github.com/gamax92/Thistle/tree/master) and [OCMOS](https://github.com/SolraBizna/j6502) implement a 6502-based CPU
- [OCMIPS](https://github.com/iamgreaser/ocmips) implements a MIPS-I CPU
- [OC-ARM](https://github.com/SolraBizna/jarm/) implements a ARMv7a CPU
- [OC-DCPU](https://github.com/Gorzoid/oc_dcpu) implements a DCPU-based CPU
- [OpenComputersX86](https://github.com/perkinslr/OpenComputersX86) implements a x86 CPU

There's also [OCJS](https://github.com/mrmakeit/OCJS) but that uses JavaScript instead of Lua, which isn't what you're looking for... but hey, maybe you can help out with one of these projects! The x86 one would be the most interesting IMHO, and that's been dormant since 2015.

**Comment by malucard** [comment]
I was talking about adding a _custom_ architecture that's _built-in_. I know about the addons. The reason I made this issue is because of the _built-in_ part. Geez, I just wanted to know if they'd accept it into the mod!

I already designed most of it, and I'm already implementing it.
I don't know what to call it, tho. The mod is temporarily called Arch. I'm thinking of calling it Katle.

**Comment by Techokami** [comment]
Ahhh, I see now. Yeah, I think stock OpenComputers is just going to be Lua.

I am very excited to see your custom architecture! What CPU arch are you using?

**Comment by malucard** [comment]
By "custom", I mean I'm creating my own. So I'm not emulating an existing one, and you won't be (easily) able to run irl programs with it, and you won't be able to use existing compilers. But that was never the intention, anyway.
My plan is to make _my own everything_ - and my "my own", I mean the OC community. Probably an alternate community within OC.

**Comment by Techokami** [comment]
Woah. So... what's the architecture like? CISC or RISC? Big or little endian? Dedicated or memory-mapped I/O?

**Comment by malucard** [comment]
RISC, little-endian, memory-mapped. It has 32 registers (note: r0 is _not_ 0), plus 32 float registers. It's 64-bit, naturally, and supports double-precision floats. Supports multiplication and division, plus their signed counterparts.

It doesn't do the common fallacy of every instruction being 32 bits wide: it's totally variable-length, so you can make instructions shorter than what they would usually be. For example, arithmetic instructions can have either two or three operands (the third one requires an extra byte). And, mainly, `ret` is a single byte (fu \<insert any RISC>).

You can have 8, 16, 24, 32, 40, 48, 56 or 64-bit immediates (there are 3-bit size fields that count individual bytes), which is great. You don't have to waste three bytes to encode a 40-bit value, for example.

There are four addressing modes (base and index are both registers): base, base+offset, base+index\*scale, base+index\*scale+offset.

So, you can see, it's very memory efficient, and very powerful as well. It was designed with efficiency in mind. You won't go anywhere just packing various instructions in a single one (x86), or making it simple to implement (ARM): it's a trade-off between both. Arch (suggestions?) is simple to implement, feature-packed, and efficient. It doesn't sacrifice things like base+index*scale+offset from x86 to be simple.

There are a few things undefined as of yet, mainly interrupts and multi-threading.

I'm writing an emulator. I'll have it on my GitHub maybe by tomorrow. Docs in the repo come by then as well.

(I've noticed that I probably sounded more serious than I am - that's the effect of ending sentences with periods!)

**Comment by NickNackGus** [comment]
Sounds great to me; if it can't be added as an official architecture, definitely release it as a mod.

**Comment by malucard** [comment]
I will. Just, how do I use C++ code in a mod? (Like, how do I setup JNI with Gradle?) Could someone point me to a tutorial or something?

**Comment by Pwootage** [comment]
After messing around with JNI in Gradle, in my opinion, it's easier to just compile the natives with CMake (or other native build system), and if desired, call into that build system from gradle, or just run it manually. 

My build for JNI, as an example:
https://github.com/Pwootage/oc-js/blob/master/native/CMakeLists.txt

There may be some "gotchas" when building the shared library for multiple OSes - specifically windows - but it should be easily enough handled with some `if (WIN32)` blocks

**Comment by Techokami** [comment]
WOAH. Okay that sounds really interesting. Ever consider the concept of making a FPGA implementation? That'd be super rad. Wow. Wonder how easy/painful it would be to port GNU/Linux? Or DOOM...?

**Comment by malucard** [comment]
Surely, I'll write an HDL version in the future, except I can't buy an FPGA... :'(

**Comment by NickNackGus** [comment]
Yup, FPGA development boards tend to be expensive. The cheapest boards I've seen are on Adafruit's website - one $80 board and one $100 board (US dollars). Other than those boards, the cheapest I've found are in the thousands of dollars range. The good news is you can still develop the HDL code in software.

**Comment by jv110** [comment]
Talking on a dead issue is weird. Join this discord and let's talk there: https://discord.gg/cbCe66h
I'll keep you updated about <insert every interesting OC project im making> , and you can help me as well :)
