### ISSUE TITLE
[1.11.2] Bug with robot block placement

### ISSUE THREAD

**Issue by kovaxis** [MightyPirates/OpenComputers#2444]
When trying to place a block the robot places the block in the selected slot but decreases the item count in the equipped-tool slot instead. The selected slot's item count stays the same, and if the equipped tool slot is empty the operation will fail. I've got power disabled (as in `ignorePower=true`), if that changes anything.

To reproduce:
Place down presumably any robot, place a stack of cobblestone in slot 1 and a stack of dirt in the tool slot. Run `robot.place()` and the robot should place a cobblestone block but decreasing the item count of the dirt stack instead, seemingly 'transforming' dirt into cobblestone.

Minecraft version: 1.11.2
OpenComputers version: 1.7.0.24
MinecraftForge version: 13.20.0.2315

Full mod list:
-OpenComputers
-Mantle (1.2.0.26)
-Tinker's Construct (2.7.0.26)
-IndustrialCraft 2 (2.7.59-ex111)
-CraftTweaker (3.0.26)
-Just Enough Items (4.5.0.288)

**Comment by Vexatos** [comment]
Can you reproduce this using 1.7.0.34?

**Comment by payonel** [comment]
confirmed fixed (in our dev builds)
some time ago, our robot in >=1.11 was using the wrong inventory for the `place` method, due to the new inventory system and offhand vs mainhand actions
