### ISSUE TITLE
Microcontroller Crashes Multiplayer Server

### ISSUE THREAD

**Issue by Dudblockman** [MightyPirates/OpenComputers#2445]
Version 1.10.2, 1.6.2.7
Upon placing a microcontroller the server crashes, crashing each time a player comes within loading distance. Multiple other microcontrollers of the same build have not crashed the server before.

Crash Log: https://pastebin.com/tsdu9gv4

Code loaded onto controller: https://pastebin.com/3jixfzae 
(Does not seem to be the root of the problem as I tried with other programs and blank)

Have not been able to replicate the bug in singleplayer, only when on the server.

**Comment by payonel** [comment]
have you been able to repro the crash at all? or is it only on a specific world?
If you can repro please provide the repro steps
If you cannot produce a repro procedure, can you upload the crashing world?

**Comment by payonel** [comment]
I can protect from the null exception at least, not enough info to resolve root cause
