### ISSUE TITLE
Can't use world sensor card

### ISSUE THREAD

**Issue by dustpuppy** [MightyPirates/OpenComputers#2447]
Hi,
i have Galaticraft installed and can't use the world sensor card.
If i hover over the card, not high lightning and card can't be put in any slot (Tier 1,2,3).

MC Version is 1.10.2
Galacticraft and OC is the newest.

**Comment by payonel** [comment]
I believed you mentioned in irc that the same setup works for you in 1.7.10. correct?

**Comment by dustpuppy** [comment]
Yes, no problems in 1.7.10

**Comment by payonel** [comment]
gc support was removed during our 1.11 and 1.12 upgrade. this work is open for adoption to bring it back
