### ISSUE TITLE
OpenComputers crashes on server startup, but not on client startup

### ISSUE THREAD

**Issue by FChapeau** [MightyPirates/OpenComputers#245]
I am building a modpack and whatever I throw at my server, OpenComputers crashes it. This one happened with Minecraft Forge only.

http://pastebin.com/4TtVXzag

**Comment by FChapeau** [comment]
Found the solution! It's a problem with Scala being badly downloaded by MCPC+. To fix, simply copy-paste everything in "libraries/org/scala-lang" to the corresponding folder in the server directory.

You can mark as resolved.

**Comment by Techokami** [comment]
You can do it. Click the "Close" button next to the post button to close your own ticket ;)

Sent from my Windows Phone
