### ISSUE TITLE
UNIX-like LS_COLORS variable

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2451]
As now OpenOS have ANSI escape codes, LS_COLORS variable should look more UNIX-like.
So it would have following format, just a colon-separated list:
```
di=0;36:fi=0:ln=0;33:*.lua=0;32
```
 - `di` used for *directories*
 - `fi` used for *files*
 - `ln` used for *symbolic links*
 - `*.extension` used as before

Colors are specified as a semicolon-separated list of SGR-codes.

**Comment by payonel** [comment]
closed by e1e2e3c80061d2a5e5abb3ca2cb6adb4e183ed39
