### ISSUE TITLE
How do you remove a file from your computer?

### ISSUE THREAD

**Issue by TimeGumLord1** [MightyPirates/OpenComputers#2452]
As the title says.

**Comment by ghost** [comment]
`rm /path/to/file` if you use OpenOS

**Comment by TimeGumLord1** [comment]
thanks!

**Comment by payonel** [comment]
in openos:
in shell: `rm /path/to/file` or `rm local_relative_file`
in script: `require("filesystem").remove(absolute_path)`

without openos
`component.proxy(fs_address).remove(absolute_path)`
