### ISSUE TITLE
Minecraft Crash 1.10.2

### ISSUE THREAD

**Issue by vlad1vv1** [MightyPirates/OpenComputers#2455]
Minecraft crash when the 'components' program is called. However, components from other mods are not connected. The power is connected from the IC Classic, via the converter. 

/home>components

Then it displays a list of components and crash after a couple of seconds. It also crashes when you turn off the computer.

listing crash https://pastebin.com/20pCBRjQ

**Comment by payonel** [comment]
just retested with our dev build and ic2 classics, no repro
