### ISSUE TITLE
No CC API support

### ISSUE THREAD

**Issue by jetpack-maniac** [MightyPirates/OpenComputers#2456]
ComputerCraft API support has been disabled.  It's minor for most users but inconvenient for those relying on it.  Without them, we cannot use Plethora Peripherals (it's a replacement for OpenPeripherals).

I understand that CC for 1.9+ is unstable, however, allowing users to enable it would allow them to benefit from increased availability of hardware. 

I am currently using:
Minecraft 1.10.2
Forge 1.10.2-12.18.3.2316
OpenComputers 1.6.2.7
ComputerCraft 1.80pr0-build9
Plethora Peripherals 1.10.2-1.1.7pr0

**Comment by payonel** [comment]
cc support is back in
