### ISSUE TITLE
Tablet computers will not load disk drive expansion

### ISSUE THREAD

**Issue by FactualOrc** [MightyPirates/OpenComputers#2458]
When i put a disk drive in the expansion port of a tablet when i am assembling it; the product of the assembly will not acknowledge the presence of the expansion. The components command does not even show the disk drive in its output. The other expansion cards bear similar results. I have attached a screenshot for the sake of clarification.

I am running mc version 1.11.2 and oc version 1.7.0.24

![minecraft 1 11 2 9 jul 2017 5_07_06 am](https://user-images.githubusercontent.com/13560691/27992085-1033f320-6483-11e7-9606-e0a631e5e73c.png)

**Comment by FactualOrc** [comment]
I have conducted further testing, I have attempted:

- using both the latest and recommended forge versions
- using the dev builds
- running opencomputers on its own completely
- making different arrangements of hardware when assembling the tablet

I still could not get the tablet to accept any form of expansion

**Comment by CaitlynMainer** [comment]
Can confirm, this works in 1.10 1.7.0.124, is broken in 1.11-1.7.0.51 and 1.12-1.7.0.20

**Comment by payonel** [comment]
fixed
1.11: build 58 or later http://ci.cil.li/job/OpenComputers-MC1.11/
1.12: build 24 or later http://ci.cil.li/job/OpenComputers-MC1.12/
