### ISSUE TITLE
FEATURE REQUEST: Remote VM hosts

### ISSUE THREAD

**Issue by aaronhance** [MightyPirates/OpenComputers#2459]
If you have a large server with lots of mods there can be performance issues, it would be good if the lua VMs could be hosted on a remote machine.

**Comment by payonel** [comment]
interesting idea, but not something in the scope of what where this mod is going
Two things to consider
1. any lua code accessing components will have to proxy back to the host machine to interact with the world anyways, which will cause processing on the host machine
2. you can already do this with internet cards and connecting to a remote world
