### ISSUE TITLE
1.12 Error (Build from git)

### ISSUE THREAD

**Issue by brisingraerowing** [MightyPirates/OpenComputers#2469]
[Crash Report](https://gist.github.com/BrisingrAerowing/29b37cd18a9869ea12c06e0db834a48c)

For some reason the FMLMissingMappingEvent class is, well, missing. 😕 

Forge: 14.21.1.2420
MC: 1.12
OC: 1.12-1.7.0-git+28f7c57da

**Comment by brisingraerowing** [comment]
I checked the Forge sources, and the event is now FMLModIdMappingEvent.

**Comment by AshtonSnapp** [comment]
Wait, I can get this mod for 1.12 from here? How?

**Comment by brisingraerowing** [comment]
@TPS-Snapp 
I usually do a custom build using Gradle. You can also find builds on [ci.cil.li](http://ci.cil.li/).

Keep in mind that the 1.12 (and 1.11.2) versions are VERY alpha right now, and some things may not work.

**Comment by payonel** [comment]
1.12 is building for me locally

**Comment by brisingraerowing** [comment]
@payonel Yeah, it was fixed a few months ago.
