### ISSUE TITLE
Minecraft freezes on load 1.7.10

### ISSUE THREAD

**Issue by ZionChris1** [MightyPirates/OpenComputers#2471]
Every time i start minecraft 1.7.10 as soon as the title screen loads minecraft freezes.
I am using opencomputers version 1.7.10-1.6.2.12-universal and the forge version is Forge 10.13.4 1558-1.7.10.

I have included the minecraft log below:
[2017-07-23-7.txt](https://github.com/MightyPirates/OpenComputers/files/1168463/2017-07-23-7.txt)

**Comment by LizzyTrickster** [comment]
Have you tred with just OC to see if the error persists?

**Comment by ZionChris1** [comment]
For some reason it seems to be working now.
Thank you for responding.
