### ISSUE TITLE
Network floppy is not working

### ISSUE THREAD

**Issue by Polyana-Fontes** [MightyPirates/OpenComputers#2472]
First, I tried to execute the "installNetwork.lua" to install it on a clean OpenOS installation, it asked me if I wanted to install "OpenOS" instead of "Network", if I type "Y" an error happens.

So I copied everything from the data directory in the floppy to the OpenOS root:
/cp -r /mnt/da2/data /

Then I tried to run arp, it said that it was not installed and that I had to run "install network"

Then I got a new hard disk, installed OpenOS again, then I placed the network floppy, typed "install network", it installed but the programs are unusable:
![2017-07-26_11 38 46](https://user-images.githubusercontent.com/3679022/28627038-0881da58-71f7-11e7-9a2e-2940b32f8363.png)

**Comment by Polyana-Fontes** [comment]
Nevermore, it started working after I rebooted the computer. May be you could make installer ask for reboot after the installation finishes.

**Comment by payonel** [comment]
I would like a repro for the first error you ran into. Also include the oc version you are using
you said "if I type "Y" an error happens"
What error?
Also note that when you see [Y/n], the upper case letter is the default, the response assumed if you simply press [ENTER] without more input
I will test your 2nd error case and see if I get the same problem.

**Comment by payonel** [comment]
note: in this fix i removed installNetwork.lua from the network loot disk. It was a legacy(deprecated) install option, users should only be using `install network` and this will all work just fine (plus the bonus of the `install` command line options and flexibility)
