### ISSUE TITLE
Recipe server error with Galacticraft 1.10.2 v114

### ISSUE THREAD

**Issue by chezpaul** [MightyPirates/OpenComputers#2473]
Issue detailed here: https://github.com/micdoodle8/Galacticraft/issues/2915

**Comment by xarses** [comment]
What is the specific version of OpenComputers?

**Comment by MJRLegends** [comment]
Put this in the "user.recipes" file in "/config/opencomputer/" https://pastebin.com/YwhS5xtY

**Comment by payonel** [comment]
we'll leave 1.10 alone, this is fixed for 1.11 and 1.12 with https://github.com/MightyPirates/OpenComputers/pull/2474
