### ISSUE TITLE
Bug: HDD changes address

### ISSUE THREAD

**Issue by FRA32** [MightyPirates/OpenComputers#2476]
I am playing with a friend on a DW20 multiplayer server and wanted to make a computer that monitors the power level and -generation from DraconicEvolution multiblocks. However the pc was suddendly offline and the tier 3 harddrive empty after I went out to check on other things(unloading the chunk). When the issue happened again, I noticed that the address of the HDD has changed, which seems to redirect it to a new file system, thus rendering previous files inaccessible, including OpenOS. This makes coding of importand programs hard since it means reinstalling OpenOS and recovering the program from the old File system on every reload of the chunk.

You can propably recreate this event on a server by placing a computer case(Tier 3 in my case), inserting the required components all at max tier, installing OpenOS, possibly adding some programs, and then unloading the chunk a few times. When you find the PC Offline and it greets you with No bootable BIOS found, it means that the disk successfully lost the OpenOS data.

**Comment by magik6k** [comment]
This has happened with older version of the mod. Are you sure yours is up to date? Which mod version do you have?

**Comment by FRA32** [comment]
I am using OC 1.6.2.7 for Minecraft 1.10. I last updated it 2 weeks ago with Curse, so it should be quite up to date. Neither have I changed the version or other things before the bug occured for the first time. I am not sure if it's worth noting, but the error did not occur always. We were using the same computer case with all components before and just moved it into the building that has the multiblock structure of the energy core in it. After that the issue started appearing. Perhaps other mods are an influence in this error?

**Comment by magik6k** [comment]
Can you try reproducing it with steps from https://github.com/MightyPirates/OpenComputers/issues/2092#issuecomment-282482615?

**Comment by FRA32** [comment]
Unfortunally I was unable to recreate the error on a creative singleplayer world. I made a PC use a tunnel to make a tablet beep repeadly as long as it was chunkloaded, while adding some network components in a directly neighboring chunk. When the beeping stopped and I returned to the PC, it began again, so the Pc stayed online and the harddrive never changed adress. Either it is a server only problem, or a different cause entirely. I dont think that chunkloading may actually be the issue since the structure is not far from our base, so everytime I leave the PC, I am actually either somewhat nearby, or somewhere completely different, like the nether or the likes.

**Comment by FRA32** [comment]
For now I resolved to having an OpenOS disk in the Computer Case and a floppy disk in a disk drive that contains all programs, which seems to work. The harddrive issue is circumvented this way, however the PC still shuts down everytime the chunk is unloaded. I also took a look at the chunk boundaries, the entire network is placed inside one sole chunk with the exception of some cables that slightly intersect with a neighboring chunk.

EDIT: The floppy disk also lost it's contents after I left the server for a short timespan. However the adapters I use kept their address, so some components seem to be affected, but not all.

**Comment by purplemonday** [comment]
this litterly never happend to me unless changing the modes on the disk mannaged/unmannaged
however a few things crossed my mind

you said you updated, did you also update the config file?
-- remove the old config and start mc, a new fresh config will be generated

the mods that depend on OC did you update 'm aswell?
-- remove tings like computronics opencomponents etc old plugins can couse unexpected results

theres a nother filesystem .. the eeprom
-- editing /dev/eeprom here you can add code without needing a drive or even openos. keep in mind some functions are not accesable in this low level mode. like os.sleep also you cant use the api's but it would allow computers without disk's that is if the eeproms key doesnt chance

finaly try and remove mods till you cant replicate the bug
theres something messing with your keys im not exsactly sure how keys get stored (nbt?) 
but something is messing with it.

my last thought . the server could be out of diskspace? logs do addup over time to huge files
but im not sure how this would effect OC

**Comment by payonel** [comment]
no repro
