### ISSUE TITLE
[1.11.2] Databases Non Functional

### ISSUE THREAD

**Issue by SarahGreyWolf** [MightyPirates/OpenComputers#2477]
MC Version: 1.11.2
Forge Version: 13.20.1.2425
Open Computers Version: 1.7.0.40

The Database is totally non functional in this version, opening it manually and attempting to add an item does not work, placing in 1 item does cause an update and with advanced tooltips on it displays it now has NBT data stored, however the item does not show in the GUI and computers cannot read it and attempting to add any more items results in nothing happening.

Also attempting to store to a database from a computer will always return false.

Good news is, Shift + Right Clicking it in the air does erase the NBT data.

**Comment by MattGalan** [comment]
Can confirm.

**Comment by payonel** [comment]
fixed in our latest dev builds: http://ci.cil.li/
