### ISSUE TITLE
Robot inventory filled with duplicated biker jackets

### ISSUE THREAD

**Issue by purpleposeidon** [MightyPirates/OpenComputers#2478]
Relevant installed mods:
1. Forge 12.18.3.2281
2. OpenComputers 1.6.2.107
3. Cyberware beta-0.2.10
4. WIRED: More Augs 1.7.0

I have a robot that extracts augments from cyberzombies & skeletons. It places the surgery chamber, right-clicks to close the door, waits 6 seconds, breaks the door, and then calls `while robot.suck(front) do end` to grab the loot. After it had processed a cyberzombie, I looked into its inventory and found it had been flooded with identical biker jackets. (The Biker Jacket is an armor that the zombies can wear.) There were no biker jackets on the ground.

**Comment by purpleposeidon** [comment]
Also, the vacuum-loop doesn't dupe biker jackets that are tossed on the ground manually.

**Comment by payonel** [comment]
we have fixed a similar mob drop dup bug, and I have tried to repro this for a good 15 minutes. Though I have no idea what I'm doing with this cyberware and wired mods. My cyberzombies never dropped any jackets, but many other items. Nothing was duplicated. Please retest with our latest dev builds: https://ci.cil.li/job/OpenComputers-MC1.10/

**Comment by payonel** [comment]
I have been unable to reproduce this, and given that we have recently fixed a very related bug about mob drop duplicates, I feel reasonable confident that this will no longer repro. Thank you for reporting.
