### ISSUE TITLE
IC2 Forge Hammer gets consumed in recipe

### ISSUE THREAD

**Issue by FeepingCreature** [MightyPirates/OpenComputers#2479]
Playing FTB Beyond; when using the crafting addon to craft plate recipes involving the forge hammer, the forge hammer gets consumed utterly on the first craft, even when it's at full health.

It should take damage, but stay at its location in the crafting grid unless it's used up.

**Comment by xarses** [comment]
What versions of MC, OpenComputers and IC2 is this for?

**Comment by FeepingCreature** [comment]
The FTB Beyond modpack runs with IC2 2.6.234-ex110, Minecraft 1.10.2 and OpenComputers 1.6.2.7.
~~As a bonus, the Basic Machine Casing recipe (8 ThermalFoundation Iron Plates in a circle) also does not work, resulting instead (somehow!) in 8 iron ingots and 9 iron nuggets.
[edit] The Basic Machine Casing crafts to 8 iron ingots. An iron ingot crafts to 9 iron nuggets. That seems relevant.
[edit] Yep, limiting the number of items crafted fixes that particular issue. Nevermind it!~~
The original problem is unaffected.

**Comment by payonel** [comment]
this might be fixed with our many robot inventory fixes in 1.7.2, but i'll retest and confirm for 1.7.3
