### ISSUE TITLE
[Question] Which mod works with OC's bundled cable outputs in 1.11.2?

### ISSUE THREAD

**Issue by Polyana-Fontes** [MightyPirates/OpenComputers#2481]
I'm setting up an instance to play were the main mod will be OpenComputers, which mod can I use to transport bundled signals emitted from OC in Minecraft 1.11.2?

Project Red and MineFactoryReloaded are not updated... Is there an other?

**Comment by asiekierka** [comment]
I don't think any of them exist for 1.11.2.

**Comment by brisingraerowing** [comment]
I know Immersive Engineering Redstone Cables support bundled signals, but those require a pair of connectors (one input and one output) for each color used (AFAIK, it may have changed from when I last checked).

**Comment by payonel** [comment]
I intend to review bundled cable support for OC for 1.7.3 -- i'll use this ticket as that marker

**Comment by payonel** [comment]
to answer this question, we support project red for 1.11
i do not plan to add more bundled redstone support for 1.11
