### ISSUE TITLE
[Feature request] Web socket support?

### ISSUE THREAD

**Issue by dunstad** [MightyPirates/OpenComputers#2484]
I quite like the TCP socket API that's already available. That said, being able to use web sockets would be more convenient. Any chance this could happen?

**Comment by magik6k** [comment]
This can be quite easily implemented on Lua side (easily - there is nothing that I can see blocking this). There already is http(s) library on top of TCP api - https://github.com/OpenPrograms/Fingercomp-Programs/tree/master/libhttp. Upgrade/websocket logic on top shouldn't be hard to do.

**Comment by skyem123** [comment]
The main "issue" would be that modern services tend to want TLS. Which would mean issue #761, however that's quite hard to do.

**Comment by dunstad** [comment]
For anyone else that finds this issue, there is apparently an existing library that attempts this: [websocket_client](https://github.com/feldim2425/OC-Programs/blob/master/websocket_client/API.md)

Unfortunately it currently only works with Lua 5.3, which is not the default architecture of CPUs. I plan on looking into making it work on 5.2, but I don't know if or when that will happen.

I haven't tried making use of this feature myself yet, but it claims to have TLS support in the readme as well, via [this library](https://github.com/OpenPrograms/Fingercomp-Programs/tree/master/libtls). A quick look shows it has a fair number of caveats, but may be functional for some purposes.

**Comment by xarses** [comment]
`Tend to want` is a bit weak, its required on the internet now days.

wouldn't this just be solved by full method support in `internet.request` since it magically supports https as it is?
