### ISSUE TITLE
Data Card API

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#2485]
Can we get an API to extend the data card?

More specifically, I'd like to add tar support to it. It'd be useful for a tape filesystem for use with computronics tapes.

**Comment by moonheart08** [comment]
TAR is actually simple enough to be implemented in Lua with little trouble. GZIP (orsomeothercompressionformatTM), on the other hand, would be a issue if INFLATE/DEFLATE support didn't exist in the Data Card.
https://en.wikipedia.org/wiki/Tar_(computing)#File_format

**Comment by SaphireLattice** [comment]
Huh. That's actually a pretty nice idea. Would allow for quite some
interesting things... and ability to create small packages of programs/etc.

Perhaps something like
`datacard.compress("method", data_string,
[opt_level_or_args_depending_on_method])`
And a similar companion method to decompress data.

Though, it could be a separate card as well.

**Comment by payonel** [comment]
tar can be a user program, not a component api

**Comment by gjgfuj** [comment]
Yes but what about gzip?
