### ISSUE TITLE
Crafting IC2 solar panels only produces one item, even when more material is provided

### ISSUE THREAD

**Issue by FeepingCreature** [MightyPirates/OpenComputers#2492]
Even when providing input resources sufficient to craft multiple solar panels, and calling `component.crafting.craft(2)`, only one solar panel is produced.

**Comment by FeepingCreature** [comment]
It's possible that the actual issue is that for certain items, it is impossible to craft more than one at once; or rather, you can do so but the result items will not all end up in the selected slot, where that slot collides with an item of the craft pattern.

**Comment by payonel** [comment]
this is probably fixed, will test this specifically before i close

**Comment by payonel** [comment]
fixed in latest dev builds, will be in 1.7.2 release
