### ISSUE TITLE
string.len(russian text here)

### ISSUE THREAD

**Issue by Nex4rius** [MightyPirates/OpenComputers#2494]
I have a <a href="https://github.com/Nex4rius/Nex4rius-Programme/tree/master/nexDHD">program</a> that supports multiple languages and I've noticed that the GUI is misplaced when the russian language is displayed.

I've run a simple test.
<img src="http://imgur.com/Fh1mleY.png" />
<img src="http://imgur.com/7zsRU3p.png" />

I tested it on OpenOS 1.6 and 1.6.7

**Comment by magik6k** [comment]
Use `unicode.len` for that. `string.len` returns raw number of bytes.
