### ISSUE TITLE
[Request] Why isn't there a 1.12 version??

### ISSUE THREAD

**Issue by NovaViper** [MightyPirates/OpenComputers#2495]
I notice that the mod updated to 1.12.1.. but not supporting 1.12 at all. This is a *big* problem because most 1.12 mods haven't updated to 1.12.1. Whenever you get the chance, could you please backpack to 1.12? The changes shouldn't be that drastic, as the names only changed

**Comment by xarses** [comment]
We don't support either, 1.11.x and 1.12.x versions are highly alpha, full of bugs and crashes and other instabilitity. Please don't expect much here as there is a lot of work to be done all over.

**Comment by Vexatos** [comment]
Just move on to 1.12.1. 99% of 1.12 mods should work on that version right away without needing to be ported, similar to 1.8.8 vs. 1.8.9.

**Comment by NovaViper** [comment]
Most of my mods don't work on 1.12.1, I'm trying to create a modpack but I still have some of the core mods (like CustomBackgrounds and Custom Main Menu) that still haven't updated to 1.12.1
