### ISSUE TITLE
Errors running the class transformer (1.12.1)

### ISSUE THREAD

**Issue by Viper5012** [MightyPirates/OpenComputers#2497]
![2017-08-17_17 56 59](https://user-images.githubusercontent.com/31152452/29484058-d188b8ec-850a-11e7-87af-97c7675d4c1a.png)

[latest.txt](https://github.com/MightyPirates/OpenComputers/files/1236104/latest.txt)

**Comment by Viper5012** [comment]
Might be useful to know, I haven't touched the mod yet other than having it.

**Comment by Vexatos** [comment]
Does it still occur [using the latest build](http://ci.cil.li/job/OpenComputers-dev-MC1.12/)?

**Comment by payonel** [comment]
closing - likely fixed and no response
