### ISSUE TITLE
[1.12] Navigation/Waypoints

### ISSUE THREAD

**Issue by vhd** [MightyPirates/OpenComputers#2498]
Minecraft 1.12.1
Forge 14.22.0.2459
OpenComputers 1.7.0.4
navigation.findWaypoints() returns only waypoints that located in south-east direction and above your position.
On screenshot: red wool - can't find, blue wool - OK
![2017-08-19_14 57 55](https://user-images.githubusercontent.com/487056/29486472-dd39be50-84ee-11e7-8824-7c0e89894711.png)

**Comment by williewillus** [comment]
see the botania issue, it's probably because an AABB method got remapped in a silly manner

**Comment by payonel** [comment]
thanks for the help @vhd
