### ISSUE TITLE
Issues With AE2

### ISSUE THREAD

**Issue by Donny208** [MightyPirates/OpenComputers#2500]
I've been trying to connect to my AE2 ME for quite some time with no luck, I've tried attaching an adapter to the controller, interface, etc. but with no luck. 

Pack: FTB Beyond: 1.10.0
OC Version: 1.6.2.7
AE2 Version: rv4-alpha-11

![2017-08-23_15 26 59](https://user-images.githubusercontent.com/9954948/29639481-234959ec-8818-11e7-9518-6f32ee8672dd.png)
![2017-08-23_15 27 21](https://user-images.githubusercontent.com/9954948/29639482-234b8f78-8818-11e7-909f-390779666ec7.png)

**Comment by payonel** [comment]
fyi, just running `components` in the shell is a quick way to list the available components (as opposed to looping on `component.list()` in lua)

**Comment by Donny208** [comment]
Oh neat, that'll save time

**Comment by pot-code** [comment]
AE2 has a stable version of rv4 for 1.10.2, don't know why they are still incompatible

**Comment by ben-mkiv** [comment]
probably the dev who disabled it didnt notice of AE2 final release yet ;)

Looking forward to get the API back, too.

**Comment by xarses** [comment]
AE for mc 1.1.0 isn't expected to work until at least #2465 lands

**Comment by xarses** [comment]
#2465 landed a few hours ago, and is available in the dev build 116 on [jenkins](http://ci.cil.li/view/OpenComputers/job/OpenComputers-dev-MC1.10/)

**Comment by theredghostwolf** [comment]
hey i recently started with OC [1.12.2] version, and im wanted to build something for my AE system, but im assuming that the API for that isnt here yet, or im just doing something wrong since the controller doesnt show when i type "components" into my terminal. does anyone know?

**Comment by ben-mkiv** [comment]
It should work with one of the latest test-builds from the link that xarses posted above. Which one did you try?

**Comment by theredghostwolf** [comment]
took the build that was available on the curse project site, https://minecraft.curseforge.com/projects/opencomputers.  OpenComputers-MC1.12.1-1.7.0.13.jar but since im fairly new to OC it might also be me doing something wrong. my setup is basically, pc case > adapter > controller

EDIT: found it, was using AE2 instead of llamagistics. ae2 still has the OC api disabled. my bad.

**Comment by payonel** [comment]
@theredghostwolf please use our dev builds, here: http://ci.cil.li/job/OpenComputers-dev-MC1.12/
