### ISSUE TITLE
Issue with Adapter/TE Energy Cell

### ISSUE THREAD

**Issue by DevonCash** [MightyPirates/OpenComputers#2501]
Just started using this mod in the FTB Beyond 1.10 pack, and I haven't been able to get my computer system to connect with a Thermal Expansion Energy cell. I did get the adapter to successfully work with the vanilla note block. Is there a known issue about this? Is there something wrong with my installation?

**Comment by xarses** [comment]
Which OpenComputers, MC, Forge, and TE versions is this for?

**Comment by DevonCash** [comment]
OpenComputers: 1.6.2.7
Minecraft: 1.10.2
Forge: 12.18.3.2316
Thermal Expansion: 2.0.7.10

**Comment by Donny208** [comment]
I've been having the exact same issues on the same versions. The only thing I've been able to connect to the computer is a reactor, but only through the computer port that's built in to extreme reactors, the adapter hasn't worked with anything for me so far(Thermal expansion, AE2, etc).

**Comment by payonel** [comment]
note that we've added AE support back

**Comment by payonel** [comment]
we have support for TE cells in 1.10 and above now (tested and confirmed)
