### ISSUE TITLE
Crystal Network failure on dimension unload/load *SSP ONLY*

### ISSUE THREAD

**Issue by DGerry83** [MightyPirates/OpenComputers#2502]
I'm posting this as requested from our conversation yesterday.

This bug occurs when the overworld is unloaded and then re-loaded in SSP by traveling to a different dimension(test case was the nether).  I created an instance containing only the following mods - Chromaticraft, NEI, ChickenChunks, and associated dependencies.  After setting up a simple line of repeaters from a single pylon, I verified that the network was functional(and it was).  Then I traveled to the nether, and came back, and the network had failed and lumens would not flow either through the repeaters or directly from the pylon.  This was without chunkloading(although the option to have pylons self-chunkload after being used was turned on in the cfg).  The debug mode was turned on, and the chat window displayed "Unloading Dimension 0, clearing crystal network" upon swapping to the nether.  Reloading the world restores the network's functionality - following this I put down a chunkloader in the overworld and tried again.  The same debug chat message appeared re: unloading dimension, despite the chunkloader, and the network once again failed in the same way.

**Comment by xarses** [comment]
What are the versions of the mods, MC, and Forge here?

**Comment by DGerry83** [comment]
Apologies!

Minecraft:  1.7.10
Reika's mods:  v18b
Forge: 10.13.4.1614
NEI:  1.0.5.120
NEIaddons: 1.12.14.40
NEIIntegration: 1.1.0
CodeChickenCore: 1.0.7.47
ChickenChunks: 1.3.4.19

It's worth noting that I've been able to reproduce this behavior in various packs using different versions of the mods, but without going over everything I've done I can at least confirm that it does occur with these versions.

**Comment by DGerry83** [comment]
Somehow I posted this in the wrong Github.  Feel free to remove.
