### ISSUE TITLE
Can't drag cable out of crafting bench

### ISSUE THREAD

**Issue by pcking99** [MightyPirates/OpenComputers#2504]
I create the cable with 1 red stone and 4 iron nugget and it shows me the cable. But when i try to put it in my inventory then it jumps back into the result area in the crafting bench. Only in multiplayer.

Minecraft: 1.10.2
OpenComputers Version: 1.6.2.7

Logs: https://www.dropbox.com/sh/swrkwh2hoet6xcg/AACbnRKWCNU-k2ldbuo3Utl7a?dl=0

**Comment by payonel** [comment]
this is probably because your config does not match the server config for the craft recipe.

**Comment by pcking99** [comment]
thats wierd. i left it untouched.

**Comment by payonel** [comment]
i'll test this myself later. but if you are hosting the server, could you (backup first) try removing the entire config folder both in client AND server, and restart and retest? - thanks

**Comment by pcking99** [comment]
Sure. Ill test that and give result back soon.

**Comment by pcking99** [comment]
It didn't fix the problem by deleting config.

**Comment by pcking99** [comment]
Hey, Think i might have found the problem. We have Agricraft on our server and i do see that when i create iron nuggets they come from Agricraft... Im trying to do some config in unidict.

https://github.com/AgriCraft/AgriCraft/issues/939

**Comment by pcking99** [comment]
Found a mod that helps me to keep both mods.
https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict
Edit:
It still made problems for me so i removed it.

**Comment by xarses** [comment]
Uh, unidict? no clue, I thought there was still a oredict in 1.10? if so, we use minetweaker in 1.7.10 to fix such problems by adding items to the oredict

**Comment by payonel** [comment]
@pcking99 is this resolved then?

**Comment by pcking99** [comment]
For you guys, yes. But the person running agricraft have something to do.
