### ISSUE TITLE
Tinkers Construct Mossy Tools don't gain stored XP when used by robots

### ISSUE THREAD

**Issue by InfinitiesLoop** [MightyPirates/OpenComputers#2506]
TiC tools that have Moss will auto repair slowly, but it uses up "stored xp". They gain stored xp when mining ores. But not when a robot uses them. 

I had hoped moss would be a good way for robots to use tools without needing user intervention. Basically I want a robot that can fix its own tool when it needs it. It'd be great if it could use a TiC tool forge but the output slot isn't an inventory slot, so no help there. 

Posted this in the forum too:
https://oc.cil.li/index.php?/topic/1417-tinkers-construct-mossy-tools-dont-gain-stored-xp-when-used-by-robots/

**Comment by brisingraerowing** [comment]
Maybe make them unbreakable? You need 5 reinforcement plates (8 obsidian surrounding a blank cast for one).
