### ISSUE TITLE
OpenOS `less` denies non-OC systems when processing large files

### ISSUE THREAD

**Issue by ouroborus** [MightyPirates/OpenComputers#2507]
I used `wget` to download a "large" json [file](https://api.github.com/gists/25f16ca598bf3cfd26971d017752b40b) (~170KB). Attempted to view it's contents via `less`. OC system is unresponsive even to ctrl-c. After a few seconds, all blocks (including non-OC blocks) become unresponsive to interaction and The One Probe starts displaying "Waiting for server..." in the block info. After several minutes of this, things return to normal and the OC screen shows a BSOD with "to long without yielding".

The concerning portion is how this effects systems outside of OC.

Further testing shows that `more` does the same thing.

Minecraft v1.10.2
All The Mods v3.02
OpenComputers v1.6.2.7

**Comment by Techokami** [comment]
Out of curiousity, what is the configuration of the OC computer you tried to run this on?

**Comment by ouroborus** [comment]
@techokami T3 gpu, cpu, hdd, 2x T3.5 memory, internet card, Lua BIOS, OpenOS, 8x5 grid of T3 screens, keyboard
