### ISSUE TITLE
1) Crash report 2) dont know where to actually post 3) dont know how to read the report

### ISSUE THREAD

**Issue by duh-monkey2** [MightyPirates/OpenComputers#251]
Ok, so I got the crash report after opening the tier 1 computer GUI and well... BAM!!!! Crash, and I don't know where to post it so I came here. Finally What Do I Do?! (I want to try the openComputers Mod but i dont think it likes me

---- Minecraft Crash Report ----
// You're mean.

Time: 5/8/14 10:25 PM
Description: Rendering screen

java.lang.NoSuchMethodError: li.cil.oc.client.gui.Case.drawHoveringText(Ljava/util/List;IILnet/minecraft/client/gui/FontRenderer;)V
    at li.cil.oc.client.gui.Case.func_74189_g(Case.scala:45)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(awy.java:121)
    at li.cil.oc.client.gui.Case.func_73863_a(Case.scala:26)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1036)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:946)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at li.cil.oc.client.gui.Case.func_74189_g(Case.scala:45)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(awy.java:121)
    at li.cil.oc.client.gui.Case.func_73863_a(Case.scala:26)

-- Screen render details --
Details:
    Screen name: li.cil.oc.client.gui.Case
    Mouse location: Scaled: (203, 87). Absolute: (407, 304)
    Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['duh_monkey3'/306, l='MpServer', x=210.68, y=71.62, z=277.90]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (220,64,252), Chunk: (at 12,4,12 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 1307 game time, 1307 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 57 total; [EntitySheep['Sheep'/102, l='MpServer', x=133.50, y=67.00, z=316.50], EntityVillager['Villager'/122, l='MpServer', x=154.78, y=71.00, z=347.47], EntityVillager['Villager'/121, l='MpServer', x=162.22, y=67.28, z=344.50], EntitySheep['Sheep'/137, l='MpServer', x=194.81, y=69.00, z=322.88], EntitySheep['Sheep'/136, l='MpServer', x=186.09, y=69.00, z=316.59], EntityVillager['Villager'/139, l='MpServer', x=169.50, y=68.00, z=352.50], EntitySheep['Sheep'/138, l='MpServer', x=179.03, y=69.00, z=325.06], EntityPig['Pig'/141, l='MpServer', x=218.16, y=66.00, z=315.03], EntityVillager['Villager'/140, l='MpServer', x=170.50, y=68.00, z=352.50], EntityPig['Pig'/143, l='MpServer', x=212.53, y=66.00, z=319.41], EntityPig['Pig'/142, l='MpServer', x=211.31, y=66.00, z=321.22], EntitySheep['Sheep'/129, l='MpServer', x=173.25, y=68.00, z=256.25], EntitySheep['Sheep'/128, l='MpServer', x=168.66, y=67.00, z=249.19], EntitySheep['Sheep'/131, l='MpServer', x=175.72, y=68.00, z=255.81], EntitySheep['Sheep'/130, l='MpServer', x=175.38, y=68.00, z=257.06], EntityItem['item.item.SeedsRaspberry'/132, l='MpServer', x=166.34, y=67.13, z=324.13], EntitySheep['Sheep'/135, l='MpServer', x=190.09, y=68.00, z=309.06], Girlfriend['Girlfriend'/152, l='MpServer', x=186.50, y=70.00, z=220.78], Girlfriend['Girlfriend'/153, l='MpServer', x=201.99, y=70.00, z=216.30], EntitySheep['Sheep'/154, l='MpServer', x=210.88, y=70.00, z=250.16], EntitySheep['Sheep'/155, l='MpServer', x=200.58, y=69.00, z=261.43], EntitySheep['Sheep'/156, l='MpServer', x=214.75, y=70.00, z=262.66], EntitySheep['Sheep'/157, l='MpServer', x=215.17, y=70.00, z=251.80], EntityPig['Pig'/144, l='MpServer', x=208.31, y=67.00, z=320.50], Girlfriend['Girlfriend'/151, l='MpServer', x=198.44, y=70.00, z=215.13], EntitySheep['Sheep'/193, l='MpServer', x=268.56, y=63.00, z=345.03], EntitySheep['Sheep'/192, l='MpServer', x=271.50, y=63.00, z=341.50], EntitySheep['Sheep'/195, l='MpServer', x=270.44, y=63.00, z=343.69], EntitySheep['Sheep'/194, l='MpServer', x=270.28, y=63.00, z=331.16], EntityClientPlayerMP['duh_monkey3'/306, l='MpServer', x=210.68, y=71.62, z=277.90], EntityAnt['Ant'/349, l='MpServer', x=199.53, y=52.00, z=278.65], EntityBat['Bat'/352, l='MpServer', x=220.35, y=54.00, z=285.52], EntityAnt['Ant'/353, l='MpServer', x=207.86, y=52.00, z=274.41], EntityBat['Bat'/395, l='MpServer', x=174.22, y=60.00, z=281.25], EntityBat['Bat'/394, l='MpServer', x=192.63, y=60.98, z=299.38], EntityButterfly['Butterfly'/396, l='MpServer', x=192.06, y=62.32, z=299.49], EntityItem['item.item.seeds'/487, l='MpServer', x=152.75, y=68.13, z=337.19], EntityBat['Bat'/12594, l='MpServer', x=249.75, y=45.00, z=263.16], EntityItem['item.item.SeedsBlueberry'/12745, l='MpServer', x=186.84, y=68.13, z=219.25], EntityFallingSand['Falling Block'/5618, l='MpServer', x=345.50, y=29.57, z=365.50], Rat['Rat'/5316, l='MpServer', x=-24.65, y=-0.62, z=11.76], Ghost['Ghost'/5317, l='MpServer', x=-24.65, y=-0.06, z=11.80], GhostSkelly['Ghost Pumpkin Skelly'/5318, l='MpServer', x=-24.66, y=-0.06, z=12.00], EntityItem['item.item.SeedsGrape'/9315, l='MpServer', x=161.50, y=65.13, z=323.75], EntityItem['item.item.SeedsBlueberry'/6047, l='MpServer', x=165.66, y=67.13, z=320.50], EntityRainbowAnt['Rainbow Ant'/1847, l='MpServer', x=213.16, y=71.00, z=283.89], EntityItem['item.tile.gravel'/2618, l='MpServer', x=252.22, y=52.13, z=211.88], GhostSkelly['Ghost Pumpkin Skelly'/12272, l='MpServer', x=209.78, y=70.83, z=288.00], EntityAnt['Ant'/12251, l='MpServer', x=219.19, y=69.00, z=265.06], Ghost['Ghost'/12143, l='MpServer', x=204.28, y=70.76, z=281.98], Ghost['Ghost'/12141, l='MpServer', x=205.50, y=70.83, z=281.08], GhostSkelly['Ghost Pumpkin Skelly'/12152, l='MpServer', x=207.17, y=70.77, z=282.91], Ghost['Ghost'/12144, l='MpServer', x=200.92, y=70.76, z=282.50], GhostSkelly['Ghost Pumpkin Skelly'/12150, l='MpServer', x=207.84, y=70.69, z=283.59], Chipmunk['Chipmunk'/12108, l='MpServer', x=233.60, y=65.00, z=303.37], Chipmunk['Chipmunk'/12109, l='MpServer', x=232.38, y=65.00, z=294.28], Chipmunk['Chipmunk'/12110, l='MpServer', x=230.72, y=65.00, z=304.44]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2312)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:856)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_55, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 247934352 bytes (236 MB) / 842006528 bytes (803 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 4767 (266952 bytes; 0 MB) allocated, 14 (784 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 2, tallocated: 64
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 48 mods loaded, 48 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.4.49.965} [Forge Mod Loader](minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.11.1.965} [Minecraft Forge](minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{0.9.0.9} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.6.1.9} [Not Enough Items](NotEnoughItems 1.6.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TooManyItems{1.6.4} [TooManyItems](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    VeinMinerCore{0.12.2} [Vein Miner CoreMod](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FLabsBF{4.0} [BetterFurnaces]([1.6.4]BetterFurnacesV4.0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    betterstorage{0.8.0.43} [BetterStorage](BetterStorage-1.6.4-0.8.0.45.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiomesOPlenty{1.2.1} [Biomes O' Plenty](BiomesOPlenty-universal-1.6.4-1.2.1.434.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{4.2.2} [BuildCraft](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{4.2.2} [BC Builders](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{4.2.2} [BC Energy](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{4.2.2} [BC Factory](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{4.2.2} [BC Transport](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{4.2.2} [BC Silicon](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    UniversalElectricity{3.1.0} [Universal Electricity](Universal-Electricity-3.1.0.92-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers|Core{1.0.0} [OpenComputers (Core)](OpenComputers-MC1.6.4-1.2.9.362-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CalclaviaCore{1.2.0} [CalclaviaCore](Calclavia-Core-1.2.0.330-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ComputerCraft{1.63} [ComputerCraft](ComputerCraft1.63.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    craftguide{1.5.2} [CraftGuide](CraftGuide-1.6.7.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThebombzenAPI{2.2.0} [ThebombzenAPI](ThebombzenAPI-v2.2.0-mc1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnchantView{3.12.0} [EnchantView](EnchantView-v3.12.0-mc1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FinderCompass{1.6.4X} [Finder Compass](FinderCompass_1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_GravelToFlint{1.6.4 } [mod_GravelToFlint](Gravel To Flint Mod [By Dynamo] 1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.56} [Inventory Tweaks](InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    magicalcrops{3.2.1} [Magical Crops](magical_crops_1.6.4_3.2.0_BETA_15a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    standardcrops{1.1.0} [Magical Crops - Crops & Food](magical_crops_1.6.4_3.2.0_BETA_15a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MoreTools{1.1} [MoreTools](MoreTools V.1.2 [1.6.4].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Morph{0.7.1} [Morph](Morph-Beta-0.7.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComponents{0.1.0.29} [OpenComponents](OpenComponents-MC1.6.4-0.1.1.37-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.0.0.250} [Forge Multipart](ForgeMultipart-universal-1.6.4-1.0.0.250.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Core{4.3.7.32} [ProjectRed](ProjectRedBase-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transmission{4.3.7.32} [ProjectRed-Transmission](ProjectRedIntegration-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers{1.2.8.361} [OpenComputers](OpenComputers-MC1.6.4-1.2.9.362-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OreSpawn{164.16} [OreSpawn](orespawn164v16b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Integration{4.3.7.32} [ProjectRed-Integration](ProjectRedIntegration-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Illumination{4.3.7.32} [ProjectRed-Illumination](ProjectRedLighting-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transportation{4.3.7.32} [ProjectRed-Transportation](ProjectRedMechanical-BETA-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Expansion{4.3.7.32} [ProjectRed-Expansion](ProjectRedMechanical-BETA-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Exploration{4.3.7.32} [ProjectRed-Exploration](ProjectRedWorld-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    staircraftmod{1.6} [Staircraft](Staircraftmod-16---164-Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TorchLevers{1.3.3} [Torch Levers](TorchLeversV1.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    VeinMiner{0.12.2} [Vein Miner](VeinMiner.0.12.2_MC1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.5.2a} [Waila](Waila_1.5.2a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WorldAndGenerationTweaks{1.6.0} [WorldAndGenerationTweaks](WorldAndGenerationTweaks-v1.6.0-mc1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    McMultipart{1.0.0.250} [Minecraft Multipart Plugin](ForgeMultipart-universal-1.6.4-1.0.0.250.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMicroblock{1.0.0.250} [Forge Microblocks](ForgeMultipart-universal-1.6.4-1.0.0.250.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.6.4-Forge9.11.1.965
    LWJGL: 2.9.0
    OpenGL: GeForce 8400GS/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 2196 (122976 bytes; 0 MB) allocated, 41 (2296 bytes; 0 MB) used

**Comment by fnuecke** [comment]
Huh, so there are two very odd things going on here. One: for some reason Forge decided to not obf-to-SRG that method call... two: for some reason it works for me anyway. Could you please try if this also happens without any other mods present? Thanks.

**Comment by duh-monkey2** [comment]
Okay... well I figured out it was because of TMI (but i use TMI because NEI doesn't let me actually use the modes, like cheat mode recipe mode, utility, it just shows the blocks and the recipes, granted i dont really use cheat mode, i do like it, and i love the util mode but yeah i use the craft book mod for recipes and the tmi for cheat mode, and NEI for waila. if you could possibly help me fix NEI i would love you forever lol, I'll add my CONFIG but i don't know if that will help... if not can you point me to the direction i need to go to get NEI fixed?)

NEI.cfg
#Main configuration of NEI.
#Most of these options can be changed ingame.
#Deleting any element will restore it to it's default value

checkUpdates=true
options.edge-align buttons=false

#Change these options if you have a different mod installed on the server that handles the commands differently, Eg. Bukkit Essentials
command
{
    creative=/gamemode {0} {1}
    heal=
    item=/give {0} {1} {2} {3}
    rain=/toggledownfall
    time=/time set {0}
}

inventory
{
    cheatmode=2
    gamemodes=creative, creative+, adventure
    hidden=true
    itemIDs=1
    layoutstyle=0
    #For those who can't help themselves.
    #Set this to a mode and you will be unable to change it ingame
    lockmode=-1
    profileRecipes=false
    utilities=delete, magnet, item
    widgetsenabled=true
}

keys
{
    gui.back=14
    gui.enchant=45
    gui.hide=24
    gui.next=209
    gui.potion=25
    gui.prev=201
    gui.recipe=19
    gui.search=33
    gui.usage=22
    showenchant=23
    world.chunkoverlay=67
    world.creative=0
    world.dawn=0
    world.dusk=0
    world.heal=0
    world.highlight_tips=0
    world.midnight=0
    world.moboverlay=65
    world.noon=0
    world.rain=0
}

world
{
    highlight_tips=false
    highlight_tips.x=5000
    highlight_tips.y=100
}

NEIServer.cfg

#NEI Server Permissions 

# Names are Comma (,) separated

# ALL, OP and NONE are special names

#List of players who can use these blocks. :Anyone not listed here will not have these blocks appear in their item panel.:format is {itemID}::{itemDamage}:Eg. 12::5=CodeChicken, Friend1
BannedBlocks
{
    7:0=NONE
}

#List of players who can use these features. :Eg. time=CodeChicken, Friend1
permissions
{
    adventure=OP
    creative=OP
    creative+=OP
    delete=OP
    enchant=OP
    heal=OP
    item=OP
    magnet=OP
    notify-item=CONSOLE, OP
    potion=OP
    rain=OP
    save-state=OP
    time=OP
}

NEISubset.cfg

#You can put your own custom SubSet Ranges in here
#Follow the following format (replace {something} with what you want.
#{Parent}.{Name}=[{item1}],[{item2}],[{item3}-{item4}],[{item5}:{damage}],[{item6}:{damage1}-{damage2}]
#Eg. Blocks.Nether = [87-89],[112-115]
#Eg2. Birch = [17:2],[6:2]

**Comment by fnuecke** [comment]
Right, looks like this is somewhat of a [recurring](http://www.minecraftforum.net/topic/140684-176-toomanyitems-in-game-invedit-apr-8/page__st__15480#entry22951120) [issue](http://www.minecraftforum.net/topic/140684-176-toomanyitems-in-game-invedit-apr-8/page__st__15860#entry23348788) [in TMI](http://www.minecraftforum.net/topic/140684-176-toomanyitems-in-game-invedit-apr-8/page__st__16160#entry24303373). While this is quite obviously TMI's fault, it seems it's "too big to fail", so [others have to](https://github.com/CrazyPants/EnderIO/blob/master/common/crazypants/gui/GuiContainerBase.java#L55) [bow to its will](https://github.com/odininon/EnchantingPlus/blob/master/src/main/java/com/aesireanempire/eplus/gui/GuiModTable.java#L282). I'll probably be adding such a workaround, too... under protest ;-)

As for your NEI issue, I'd suggest asking on the NEI thread?
