### ISSUE TITLE
cant access robot gui

### ISSUE THREAD

**Issue by Tcll** [MightyPirates/OpenComputers#2510]
this was initially discovered on version 1.6.0.9, but I've updated and tested on 1.6.2.12 with the same result.
after assembly the robot displays it's name as you would expect, including renaming with an anvil.
but once placed in the world, this happens: https://photos.app.goo.gl/NKCkd8LCRsk8WTFe2

I've tried numerous configurations with no success.

the gui does open, but only for the few frames the name remains the same,  once the name changes, the ui closes,
including opening the ui and looking away from the robot before the ui displays. 

ant ideas what could be causing this behavior??
I'm running minecraft 1.7.10
if you need more info, I'll be happy to provide ;)

**Comment by xarses** [comment]
What is the `Y` (elevation) component of the location of the robot?
Are there any console logs relating to this?
Is this MP? If so what happens if you log out and back in?
What OS is this on?

**Comment by Tcll** [comment]
I don't have minecraft open right now, but I'm on top of a cube in the spectre dimension  if that says enough  ;)
(why does Y elevation matter??) :/
the console doesn't log anything, however I can look through the forge logs and see if there's anything shady going on.
yes, but it's a self-hosted server (I don't have internet), and relogging doesn't change anything.
both computers are currently running Xubuntu: (will be switching to Solus once I get internet)
- client: 14.04 (haven't been able to upgrade)
- server: 16.04

hope that helps ;)

EDIT: the type server I'm running is a setup provided by ATLauncher.

EDIT2: probably should mention I'm working on a modpack, this isn't something off ATL.

**Comment by xarses** [comment]
Information about the mod providing the spectre dimension, might be needed to reproduce.

> (why does Y elevation matter??) :/

There have been similar bugs before with mods that allow for a 0 or negative y coordinate component. Given that the normal game doesn't support it sometimes we as developers code around assuming that those are constants and no one would ever change them

**Comment by Tcll** [comment]
ah ok thanks for explaining, no I don't have any mods that change the Y coordinate it's still the default 0 to 255. ;)
I have considered the idea as it aids in creativity, but ultimately decided against it because the mods involved seem to be slow and buggy.

the issue happens in the overworld as well, I haven't tried the other dimensions, but I assume it would happen there as well...
the mod responsible for the spectre dimension is RandomThings, which I'm currently using version 2.2.4
(I only get 12GB of 4G data with unlimited 3G for 30 service days, so I don't update much often)

what would be some possible causes for the issue??
maybe I can help pinpoint a mod issue ;)

**Comment by payonel** [comment]
With just OC I cannot reproduce this.

**Comment by Tcll** [comment]
here's my modlist from another issue I was having (which is fixed now).
https://mega.nz/#!o0x02DJB!UdanKsT8d6uAfjFch2HKvYiTcgWcLK9FVEw_EnApQZc
the only difference from this list is HxCEnchants, HxCCore, and ConfigurationAPI.

if you know of any issues related to mods I'm using, this will help pinpoint that,
otherwise I need to know a list of possible issues so I can pinpoint from the mods you may not know  ;)
CustomSteve for example, which I doubt is a cause.

**Comment by xarses** [comment]
Unfortunately with out a crash log, we cant tell either. You would have to a do a "bisect search"  style process through your mods until you find which one is being a butt and then we might be able to do something on either side.

 bisecting would require that you take approx 1/2 of the mods + OC and test that it occurs, if it doesn't occur in the test set then the problem is with the other. Then you continue with the set that has the problem dividing it and such until you have reduced the set to the one mod that causes the issue

**Comment by Tcll** [comment]
heh, I was asking for possible causes cause I could probably have diagnosed the 1 mod that's being dumb, or at least sectioned off around 7/8 of the mods... heh
but I guess I can give this a go. ;)

I'll report back once I find the mod.

**Comment by Tcll** [comment]
ok so I haven't found the offending mod yet, but I can confirm I do have it working after removing everything but OC and waila (and associates)...
something I did notice though was that, during game lag on placement, the names cycled through like the video above before the lag cleared and the name was decided...

think that might give you guys a lead to fix the random name generator to make sure a name is only generated once??
or is it something deep down in the registration that may be causing the later decision??

**Comment by Tcll** [comment]
huh... so in my endeavours to find the offending mod, I'd figured something else out:
https://photos.app.goo.gl/ADtnDbafXKU1QcLk1
I ended up scrapping my test robot and building a new one because, when it worked, the name stuck throughout my search for the mod that would break it again.

so the creatix works, along with anything else with a pre-registered name.
(it's not everything like I was initially thinking)

**Comment by Tcll** [comment]
well...
now my modpack is being a butt...
I added all the mods again and it broke again as expected...
but I took out most of the mods except for what I thought would've been offending it.
nope, apparently I removed the offence.
so I slowly added back groups of mods until I found the butt.
I never found the butt and the folder is empty...

so I guess it works now and we'll never know the offense >_<

**Comment by payonel** [comment]
thanks for the updates. if you find this bug again ***and*** you have more information about a repro, please open a new ticket and reference this ticket.
