### ISSUE TITLE
Crash with extreme reactors 

### ISSUE THREAD

**Issue by jkelley2** [MightyPirates/OpenComputers#2511]
I'm using OC to control 2 steam turbines and 1 solid fuel and 1 liquid reactor from Extreme Reactors and when I hook the computer to the second extreme reactor it will randomly while I'm playing give me a Concurrent Modification Exception, Exception Ticking World. Which does not occur with only 1 reactor attached

**Comment by xarses** [comment]
What versions of Open Computers, Minecraft, Extreme Reactors, and Forge version is this for?
Are these attached to the same adapter, or just the same computer?
Also, there should be some console logs of the exception, they would be useful if not the whole server log.

**Comment by jkelley2** [comment]
All attached to the same computer using cables and Extreme Reactors computer ports

Minecraft version 1.10.2
Open Computers mc1.10.2-1.6.2.7
Extreme Reactors 1.10.2-0.4.5.30

I'm playing on the dire wolf 20 pack with a few additional mods and updated versions of mods when this started happening

**Comment by jkelley2** [comment]
And here is a pastebin of the crashlog, doesnt directly state OC or ER but it only occurs when i have more then 1 reactor or turbine hooked up to the computer 

https://pastebin.com/QtFZ587x

**Comment by brisingraerowing** [comment]
This is actually an issue with Extreme Reactors. See ZeroNoRyouki/BigReactors#111 for more info.

Also, Extreme Reactors recently released an update for 1.10.2+ which rewrites the computer support, and may have fixed this bug. You may want to upgrade to it.

**Comment by brisingraerowing** [comment]
This issue has been fixed completely in a recent ER version for 1.10.2+.
