### ISSUE TITLE
Files Not Working? Please Help

### ISSUE THREAD

**Issue by coolerdude57** [MightyPirates/OpenComputers#2513]
I was using OpenComputers And It Was Working Just Fine But Then When I Restarted My Minecraft Some Function Stopped Working Help And Man Don't Work So I Cant Get Program Names Change Directory Stopped working and Home, Lib, Bin, ect... Stopped Working.

**Comment by payonel** [comment]
versions? minecraft and opencomputers versions please

What are the steps to reproduce this?
Does this reproduce? Did this happen only once or can you repro this?

You restarted minecraft and "functions" and "no program names" and "directories" all stopped working? This is unclear. Did your filesystem get wiped? Screenshots might help.

If your in-game hardware got messed up, you can check the world files on the server, and look for your files under the opencomputers/ dir --- if recovery is dire

**Comment by payonel** [comment]
no repro given, closing
