### ISSUE TITLE
1.10 builds #115 & #116 crash with FTB Beyond pack

### ISSUE THREAD

**Issue by mvodanovic** [MightyPirates/OpenComputers#2516]
http://ci.cil.li/view/OpenComputers/job/OpenComputers-dev-MC1.10/116/

I replaced the OpenComputers version shipped with the mod pack with this build and tried to start my world. As I was entering the world
 it crashed with a NullPointerException. I'm attaching the crash report for 116.

[crash-2017-09-10_10.42.01-server.txt](https://github.com/MightyPirates/OpenComputers/files/1290380/crash-2017-09-10_10.42.01-server.txt)

**Comment by payonel** [comment]
let's not use 115, openos had a bad bug in it (unrelated to this bug report)

**Comment by stephan48** [comment]
Hi,

I found the same problem - but for me it did not crash directly but only under certain conditions(removing the export bus) - while not initializing it at all in regards to OC with the similar trace.

I dug throu the code and created a pull request which fixes it for me - the fix happens on exactly these lines in your crash trace.

Pull Request https://github.com/MightyPirates/OpenComputers/pull/2519 

If you do not prefer to compile it yourself, I could hand you a compiled version from that commit.

-- stephan

**Comment by mvodanovic** [comment]
If you can give me your build, I'd be very grateful. I tried building your pull request myself, but I had problems with the MCMultiPart dependency (gradle couldn't resolve it) so I couldn't build it.

**Comment by mvodanovic** [comment]
Any chance this could get prioritized and fixed? As far as I see it, it shouldn't be complicated to fix. Basically I didn't play Minecraft since I reported this and it's been almost a month since then. :(

**Comment by stephan48** [comment]
Hi @mvodanovic,
I really forgot to answer your comment :(
Here is my  compiled version: https://filebase.stejau.de/private/OpenComputers-MC1.10.2-1.6.2-dev%2B1ace76b.jar 

-- stephan

**Comment by mvodanovic** [comment]
It seems to be working... Thanks! 👍

**Comment by stephan48** [comment]
I would hope so :D Using it for quite some time now!

**Comment by payonel** [comment]
it has been merged
