### ISSUE TITLE
OpenPeripherals methods inssue

### ISSUE THREAD

**Issue by marcin212** [MightyPirates/OpenComputers#252]
Whenever I call any method from OpenPeripherals that returns an array, it returns a nil instead. The console output looks like this: http://pastebin.com/raw.php?i=v3M3fmHz

ComputerCraft1.63
OpenComponents-MC1.6.4-0.1.1.37-universal
OpenPeripheralCore-1.6.4-0.4-snapshot-127
OpenModsLib-1.6.4-0.4-snapshot-196
OpenComputers-MC1.6.4-1.2.9.362-universal

**Comment by fnuecke** [comment]
The method in OP tries to 'yield' / pull an event, which is not supported by the CC peripheral wrapper (as the name of the exception indicates). Sorry, but this cannot be 'fixed' due to the way OC works (specifically, its persistence).

**Comment by marcin212** [comment]
You need both fixes to have working events
