### ISSUE TITLE
Launching a lot of terms

### ISSUE THREAD

**Issue by RccHD** [MightyPirates/OpenComputers#2521]
How to launch more than one openos terminal with custom environment?
I would launch second term with my custom global variables and custom io-streams
To be honest I would like to launch two terminals in separate threads
How can I do it using default OpenOS libs and API?

**Comment by payonel** [comment]
sorry, openos doesn't have multiple-terminal support - and I don't plan to make it an official feature for openos either. It might one day be an oppm project I write.
I have designed the code in /lib/term and related libraries with "multiple terminals" in mind, in case other would like to build such tools on top of openos
