### ISSUE TITLE
[Suggestion] Time and date synch with stellar sky

### ISSUE THREAD

**Issue by LiEyWe** [MightyPirates/OpenComputers#2523]
As the title says, a date and time synch between OC and Stellar Sky would be nice.

**Comment by S0ZDATEL** [comment]
I agree, it would be very cool!

**Comment by payonel** [comment]
os.date uses the in-game time, sunrise is at 0:00. maybe weird, but that's how it is :)
if stellar sky breaks that, i would consider that a bug with their mod, we just use game time

**Comment by payonel** [comment]
http://ocdoc.cil.li/api:non-standard-lua-libs#operating_system_facilities
