### ISSUE TITLE
[1.10.2][Possibly 1.8+] ItemStack NBT tag no longer accessible

### ISSUE THREAD

**Issue by brisingraerowing** [MightyPirates/OpenComputers#2526]
In 1.7.10 ItemStacks exposed a tag field, which is used by various libraries for OC (e.g. [Magick6k's LibItem](https://github.com/OpenPrograms/Magik6k-Programs/tree/master/libitem))

In 1.10.2 (and possibly 1.8+) that field is hidden and is no longer accessible. Could it be exposed again somehow? A CC program I am porting uses the NBT Hash, which I planned on doing manually using the actual Tag data.

I may try to figure out how to do this and issue a pull request. I use 1.10.2 and 1.12.1 currently, but I can implement it for any affected versions.

**Comment by thiakil** [comment]
@BrisingrAerowing perhaps you discovered this, but the option to view the tag is still there, it's just a default-off config option.
