### ISSUE TITLE
[Feature] Add NBT Hash to ItemStacks

### ISSUE THREAD

**Issue by brisingraerowing** [MightyPirates/OpenComputers#2527]
Having a hash code for NBT data added to ItemStacks would be helpful for some things I am doing (such as the port of Sidoh's AE2 autocrafting system). AE2 itself has code for this ([here](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/08ee8f7656e37bc0bf206a12b82349317d7c4acc/src/main/java/appeng/util/helpers/ItemComparisonHelper.java#L314)], but AE2 is under the GPL, whereas this mod is CC0.

@AlgorithmX2, would you mind me using that method (converted to Scala) in a pull request to add this feature to OC?

**Comment by AlgorithmX2** [comment]
While I personally don't mind people taking bits and pieces from my code.

I don't know the history of that method, its present state is all yueh, but it seems it was moved from another file, if you can track it back to a point when It was entirely mine, that would cover it, 

Other wise you'll need to request permission from everyone else touched it as well, to guarantee that there are no issues.

While I doubt anyone cares its the only way to be sure.

**Comment by thiakil** [comment]
What exactly is wrong with just using Java's built in `hashCode()`?

**Comment by brisingraerowing** [comment]
@thiakil I believe that may change based on the order of NBT tags.

**Comment by thiakil** [comment]
"unordered" implies the same will happen with the linked code. Neither enforces any order.

**Comment by Vexatos** [comment]
For what it's worth, this is already a thing for items stored in a database upgrade: See `component.database.computeHash`.
