### ISSUE TITLE
[Suggestion] robot component api to destroy item

### ISSUE THREAD

**Issue by wischi-chr** [MightyPirates/OpenComputers#2529]
atm my mining robot drops useless items to free some space in the inventory and items are all over the place. Would be great if we could've some kind of upgrade to destroy/delete items instead of dropping them.

**Comment by Nex4rius** [comment]
+1 for robot inventory item voiding

As a possible workaround the robot could carry a lava bucket (or an item-void block from a mod) and place it and then destroy all items.
(Did anyone test if the /dev/null from OpenBlocks works inside a robot?)

**Comment by ben-mkiv** [comment]
maybe a (Tier3) tractor beam with filter would be more fitting with "no magical power in main oc"
(and/or allow filtering only with a database as reference)

this would also allow some other neat stuff like ae2 crystal automation and such.
