### ISSUE TITLE
Doesn't work on 1.12.2

### ISSUE THREAD

**Issue by TheLimePixel** [MightyPirates/OpenComputers#2530]
OC is one of the mods in my pack that don't work on MC 1.12.2
![image](https://user-images.githubusercontent.com/25333164/30588096-b8f9b612-9d35-11e7-95e8-4f4d43fa0c4d.png)

**Comment by wischi-chr** [comment]
~~iirc there is no official oc release that supports MC1.12 at all (atm)~~
There is an active branch master-MC1.12 (so I think they are woking on it) ~~but according to the releases section (for oc v1.6.2) the lastest mc version supported is 1.10.2~~

**Edit:** Looks like the github release section is outdated. There is a release for 1.12.1 listed here:
https://minecraft.curseforge.com/projects/opencomputers/files (did't know that ^^)

**Comment by TheLimePixel** [comment]
Ik. However, I am talking about updating to 1.12.2.

**Comment by equal-l2** [comment]
Latest alpha release (`OpenComputers-MC1.12.1-1.7.0.4.jar`) seems not to work with 1.12.2

**Comment by Vexatos** [comment]
Please test with [OpenComputers 1.7.0.12](http://ci.cil.li/job/OpenComputers-dev-MC1.12/); it should be working now.

**Comment by TheLimePixel** [comment]
Yup, it works.

**Comment by TheLimePixel** [comment]
So could you just release it on CF. It's the only mod stopping me from updating my pack, so I don't care about new features. :/

**Comment by whatthedrunk** [comment]
Yeah I would love to update ATM3 to 1.12.2 but we need the build on curse if possible.

**Comment by TheLimePixel** [comment]
Oh, nvm then. Do not update for a month, please. :P
