### ISSUE TITLE
[MC 1.10.2] Unsable to register recipe for World Sensor Card

### ISSUE THREAD

**Issue by craft90** [MightyPirates/OpenComputers#2534]
I got an error in chat that some recipes didn't load correctly. After going through the entire log I found that the issue is that the World Sensor Card recipe isn't registering. It appears after testing that the issue is Galactic Craft. Not sure why that would affect the recipe though. I also don't know if this may be on your or their end.

**Comment by brisingraerowing** [comment]
Known issue. OC uses an old item name. See #2474

**Comment by payonel** [comment]
dup of #2474
