### ISSUE TITLE
Redstone I/O Blocks Randomly Changing Address

### ISSUE THREAD

**Issue by FrostyTheTankMan** [MightyPirates/OpenComputers#2536]
I've got a spawner room set up in my base with a computer and program controlling the spawners. I have 10 Redstone I/O blocks set up with 3 rftools redstone transmitters at each. The problem is my program keeps breaking because the redstone i/o blocks keep changing their address, which then no longer matches up with the address in the program.

If it helps, the blocks are coded as such:

local red1 = component.proxy("aa2b2619-5c01-4666-b387-077787cf1889")
local red2 = component.proxy("0dcadb03-57ce-4c76-a6c7-14f9f832ca8d")
local red3 = component.proxy("3ee9f2de-61aa-4194-9f17-afc945434a60")
local red4 = component.proxy("659119e7-008f-413b-b89d-18ffb61bb9e5")
local red5 = component.proxy("a76b2b13-06c4-46dc-bc08-52878b747a6d")
local red6 = component.proxy("6dc4589d-8289-41c3-b5f7-400c12a1c8ca")
local red7 = component.proxy("a76b2b13-06c4-46dc-bc08-52878b747a6d")
local red8 = component.proxy("5c8ff5ad-27c9-4745-aa8e-31780405c7ba")
local red9 = component.proxy("384f2f44-51e9-4800-8971-776ea5d31c51")
local red10 = component.proxy("d7d3322b-a6c8-4984-ac41-28b733a05867")

Any help in stopping the address changing or a better way to go about this without it breaking my program constantly would be appreciated.

**Comment by payonel** [comment]
are the redstone i/o blocks in another chunk? we've had bad chunk issues in the past -- you should update to our latest builds, please try our dev builds: 

http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/
http://ci.cil.li/job/OpenComputers-dev-MC1.10/

when you update this ticket, please let us know which mod version you were using at the time

**Comment by FrostyTheTankMan** [comment]
unfortunately it's on a server and i don't have control over updating, but 6/10 of the i/o blocks are in the same chunk as the computer, and both chunks they're in are chunkloaded

**Comment by FrostyTheTankMan** [comment]
I've moved all the i/o blocks into the same chunk as the computer, so here's to hoping the addresses stay the same
