### ISSUE TITLE
[MC 1.10.2] Unable to run ls command

### ISSUE THREAD

**Issue by craft90** [MightyPirates/OpenComputers#2538]
Hi. So as I'm new to OC and LUA in general I decided to follow the tutorials on the wiki. Unfortunately I'm unable to run the ls command properly. When I input it all it does is jump to the next line rather than showing /bin, /tmp etc. as seen in the tutorial. Sure I managed to complete the tutorial but I was wondering if it's a bug? Or just an outdated tutorial?

**Comment by lifewcody** [comment]
Hello,

What version of OpenOS are you using? A screenshot would be much appreciated!

**Comment by craft90** [comment]
I don't know what version of OpenOS it is... but it's OpenComputers MC1.10.2-1.6.2.7. I think it's the latest version for MC 1.10.2? In essence this what's happens, I am on the main GUI and after home I type ls. Instead of showing /bin, /tmp etc. the cursor blinks away and it stutter as if it tries to think but then the cursor comes back on the next line. To see bin files I had to type - ls /bin.

I'll try to attach a screenshot asap

**Comment by lifewcody** [comment]
That's the intended function. I assume it looks like this when you type ls
`/home#`
If it looks like this then you are in the home directory. This is branched off the root directory (/). If you want to get to the root directory you must type `cd /`. `cd` stands for change directory. With the command `cd /` you are stating you are changing the directory to the root directory (which is `/`). If you type `ls` again, then you will see a bunch of folders including /bin.

Hope that helps you :)

**Comment by craft90** [comment]
That wasn't how it looked in the tutorial tho. But then again it was for CraftOS 1.0 There it looked like if you wrote ls it would list all the directionaries like /bin /tmp etc. So I guess I misunderstood.

**Comment by craft90** [comment]
But thanks anyway!

**Comment by lifewcody** [comment]
In CraftOS, by default, once it it booted you get thrown into the root directory, so for the tutorial in question, that would be correct.
For OpenOS, (entirely different OS and mod), it puts you into /home

**Comment by craft90** [comment]
So the OpenComputer tutorial is for CraftOS?

**Comment by lifewcody** [comment]
> That wasn't how it looked in the tutorial tho. But then again it was for CraftOS 1.0

You made it seem like the tutorial was for CraftOS. CraftOS is from ComputerCraft whereas OpenOS is from OpenComputers. 2 completely different things.

**Comment by craft90** [comment]
No it was the tutorial on the wiki. I mistyped. I meant OpenOS. Sorry. I must be tired.
