### ISSUE TITLE
serialization (lib) bug/error: too long without yielding 

### ISSUE THREAD

**Issue by TactiTac0z** [MightyPirates/OpenComputers#2541]
hi im makeing a lib for opencomputers but there is a error when the serialization function serialize is trying to trun a super huge table into a text(file) then the computer is giveing me a too long without yielding

NOTE: it was Lizzy Trickster her/him self that told me to create this issue post

**Comment by payonel** [comment]
Please provide specific repro, please indicate the OC version you are using

**Comment by payonel** [comment]
I'm adding cannot repro - though I probably could if I created some custom data. But I am waiting on the specific use case this user had.

**Comment by payonel** [comment]
too long without repro :)
