### ISSUE TITLE
[1.12.2] Unable to store items in database

### ISSUE THREAD

**Issue by theredghostwolf** [MightyPirates/OpenComputers#2546]
OC version: OpenComputers-MC1.12.1-1.7.0.18.jar

I am unable to add items to the database either by hand or via a store method from an inventory_controller or me_network.

inserting by hand
![2017-10-08_02 52 30](https://user-images.githubusercontent.com/22449417/31313043-9cbb9d6c-abd6-11e7-875c-85c115eaf8b0.png)
database module inside the adapter
![2017-10-08_02 53 12](https://user-images.githubusercontent.com/22449417/31313044-9cbf1154-abd6-11e7-997d-8ec1fca35e7d.png)
components output
![2017-10-08_02 53 38](https://user-images.githubusercontent.com/22449417/31313045-9cc1e30c-abd6-11e7-9cdd-4b27f94f763b.png)
lua script used
![2017-10-08_03 05 51](https://user-images.githubusercontent.com/22449417/31313046-9cc2d7b2-abd6-11e7-8164-f371cb532519.png)
script output
![2017-10-08_03 06 10](https://user-images.githubusercontent.com/22449417/31313047-9cc366f0-abd6-11e7-98b0-f5b43c59c733.png)
database module is still empty
![2017-10-08_03 06 17](https://user-images.githubusercontent.com/22449417/31313048-9cc37672-abd6-11e7-983e-60367cbb85b7.png)
content of ME system where it reads the items from
![2017-10-08_03 06 44](https://user-images.githubusercontent.com/22449417/31313049-9cd08d76-abd6-11e7-925f-fb93a9c3069f.png)

script used:

```lua
local component = require("component")
local database = component.database

local meController = component.me_network

local itemArray = meController.getItemsInNetwork()
local items = itemArray.getAll()

local itemToStore

for k,v in ipairs(items) do
  if v.name == "minecraft:log" then
    itemToStore = v
    print("found item!")
  end  
end

--attemps 2 filters
meController.store({name = "minecraft:log"}, database.address)
meController.store(itemToStore,database.address)

print("stored item in database: " .. database.address)

--prints all items in database

for x = 1,81 do
  local item = database.get(x)
  if not item == nil then
    print(item.name)
  end
end
```

edit: found an older issue refering to a simelar issue: https://github.com/MightyPirates/OpenComputers/issues/2477

**Comment by payonel** [comment]
please provide lua code you used and maybe a screen shot of your robot. show a screen shot of the output of `components` too

**Comment by theredghostwolf** [comment]
updated.

**Comment by payonel** [comment]
thank you, i'll investigate

**Comment by ben-mkiv** [comment]
same problem for me on 1.7 OC Release on MC1.12.1

can't put items by hand in the DB

**Comment by payonel** [comment]
fixed
1.11: http://ci.cil.li/job/OpenComputers-MC1.11/
1.12: http://ci.cil.li/job/OpenComputers-MC1.12/
