### ISSUE TITLE
[Suggestion] Add a recipe API

### ISSUE THREAD

**Issue by josephcsible** [MightyPirates/OpenComputers#2547]
I propose that a Lua API be added that allows programs to look up recipes, just like JEI lets you do. For example: `recipes.lookupCrafting('minecraft:lit_pumpkin')` would return:
```lua
{{input =
{nil, nil, nil,
nil, {'minecraft:pumpkin'}, nil,
nil, {'minecraft:torch'}, nil},
output = {'minecraft:lit_pumpkin'}}}
```
This would let you, for example, create a program that takes the name of an item, then automatically crafts one with the contents of a storage system, automatically doing any intermediate crafting required.

**Comment by SaphireLattice** [comment]
Wait, you mean, just magically give a recipe to the program by block name, with a table of block names? That sounds rather weird.

Right now you can just make a Lua library or program that would maintan a easily expandable database of recipes and outputs them in conviniet format that you want to use. Perfectly possible without any components, or magical APIs exposed by CPU or whatever.

I guess that would fit the forums' requests forum better, than GitHub issues.

**Comment by lifewcody** [comment]
@dangranos I agree with you on that. This should be a user library rather than a Lua API call.

**Comment by josephcsible** [comment]
That seems wasteful, though. Minecraft already maintains a database of all the recipes. Why should a Lua program need to maintain its own?

**Comment by skyem123** [comment]
it might seem "cheaty" to expose the raw names of things, and from what I can tell, OC doesn't give you that even on robots, as you can only compare to other items?

**Comment by josephcsible** [comment]
You can get item names now. http://ocdoc.cil.li/component:inventory_controller

**Comment by skyem123** [comment]
I see. Then I guess this does make some sense. ^^;;

**Comment by S0ZDATEL** [comment]
It would be better to write your own library, given that OpenComputers is used together with other mods. In your own library, you can add recipes from other mods.

**Comment by josephcsible** [comment]
@S0ZDATEL I don't see how this relates to other mods.

**Comment by S0ZDATEL** [comment]
And if you will need a recipe from other mod?

**Comment by josephcsible** [comment]
I'm not saying to hardcode a list of recipes. I want it to pull the list from Minecraft itself, like JEI does. It would automatically have other mods' recipes.

**Comment by xarses** [comment]
While I agree in it would be nice, its outside the play style of the mod to just 'magically' have a complete recipe db. Even mods that are specifically for auto crafting require that you 'teach' them the recipe before they can store it. I'd propose that we add or extend the existing item db (or have a crafting version) to be able to store a number of recipes for easy recall

**Comment by payonel** [comment]
yeah, i've thought this over and it's a bit magical and outside our scope.

**Comment by josephcsible** [comment]
Fair enough. I'll build an add-on mod that does it instead.

**Comment by 0und** [comment]
> Fair enough. I'll build an add-on mod that does it instead.

Where's the mod?

**Comment by josephcsible** [comment]
Unfortunately, I didn't end up creating it after all.
