### ISSUE TITLE
[1.10.2] Power Converting Not Accepting Energy

### ISSUE THREAD

**Issue by DoctorGlitch** [MightyPirates/OpenComputers#2548]
Using a custom built mod pack on 1.10.2, energy converter not accepting power from any power system [i.e. Applied Energistics, Thermal Expansion, EnderIO]. No crashes or codes, just simply doesn't connect together in-game.

OC ver: 1.10.2 : 1.6.2.7
Ender IO ver: 1.10.2 : 3.1.183
AE ver:  rev4-stable1
Thermal Expansion ver: 1.10.2 : 5.1.10.25

**Comment by lifewcody** [comment]
I've had the same issue. The power mechanisms (in my case IC2 cables) wouldn't connect to the computer or anywhere on the network where it *should* receive power.

**Comment by payonel** [comment]
please use our latest dev builds, we recently added back in ic2 support
http://ci.cil.li/

**Comment by Techokami** [comment]
How are you connecting power from Thermal Expansion to OpenComputers? I've got ThermalDynamics present, and the energy converter is happily accepting power from a leadstone fluxduct. I also have success with Immersive Engineering's wire system. Heck, placing the Dynamo next to an energy converter works. Did you make sure to make the red rod on the Dynamo point at the converter block? (Use a crescent hammer to reorient it!)
