### ISSUE TITLE
Hi! I just installed this mod but i can't find the block named "Power Converter"! Please help!

### ISSUE THREAD

**Issue by Johncrazy1** [MightyPirates/OpenComputers#2549]
Hi! I just installed this mod but i can't find the block named "Power Converter"! Please help!

**Comment by ben-mkiv** [comment]
afaik it only gets displayed when another mod which provides energy is installed

**Comment by xarses** [comment]
Which versions of MC, OpenComputers and Forge are you using?
What power providing mods do you have?

Lastly Power converters are technically decorative, you should be able to connect power cables to most blocks that consume power and they will convert it.

**Comment by Johncrazy1** [comment]
I am using MC 1.8.9, OpenComputer 1.8.9 my forge is 1.8.9 i installed the recommended one
