### ISSUE TITLE
Realistic physical loot disk WR/RO switch

### ISSUE THREAD

**Issue by bhodgins** [MightyPirates/OpenComputers#2551]
it's understandable why loot disks are read only by design- but I thought it would be nice to be able to shift right click a floppy disk and select the read only / writable mode (like on a real floppy disk). For a loot disk, it would copy the loot data onto the disk so that it was no longer some immutable data.. It would allow loot disks to be created by other mods which use the disk itself for storage. (for example, a forth loot disk with built in forth word storage).

It's just a random idea I had.

**Comment by ben-mkiv** [comment]
Mods are able to register their own loot disks

look at how Computronics
https://github.com/asiekierka/Computronics/blob/1.12/src/main/java/pl/asie/computronics/oc/IntegrationOpenComputers.java

or here:
FileSystem Handler
https://github.com/ben-mkiv/OCGlasses/blob/966d19b55421892f832010a022793e0292d01b08/src/main/java/com/bymarcin/openglasses/OpenGlasses.java#L194

Registering the floppy
https://github.com/ben-mkiv/OCGlasses/blob/966d19b55421892f832010a022793e0292d01b08/src/main/java/com/bymarcin/openglasses/OpenGlasses.java#L165-L166

**Comment by payonel** [comment]
we will implement #2138
