### ISSUE TITLE
Bug: robot.swing() doesn't pick up blocks [1.12.2]

### ISSUE THREAD

**Issue by ThreadedSubProcess** [MightyPirates/OpenComputers#2552]
Using OpenComputers-MC1.12.1-1.7.0.18.jar robots fail to pick up blocks with robot.swing(). Instead of ending up in the robot inventory, the block drops to the ground.

To reproduce: Build a robot as usual with inventory upgrade(s). Place it in front of a dirt block, enter lua prompt. =robot.swing(). As seen the robot doesn't pick up the dirt block.

**Comment by ThreadedSubProcess** [comment]
After quite a bit testing, different Forge versions, different robots, removing and adding mods one by one I got some clues. 

Mods: No difference.
Different robots and setups: No difference.
Different Forge: No difference.
Robot placement: Bing!

Moving about 20 blocks from spawn to the east enables robots to pick up stuff with robot.swing(). So, related to world spawn protection!? I have done all testing in single player btw. I then tried to move west to see how far I would have to go for robot.swing() to work correctly. Even after about 1500+ blocks to the west it fails, spawn protection can't be that big right? So I went about 300 blocks to the north. And the robot started to behave once again. 

It's like it doesn't work when Z is between -200 and +200. no matter the X or Y.

So far, the only thing that matters is the placement of the robot. I have tried with Birch wood, grass blocks, dirt and stone (the robot had a pickaxe for that). The material doesn't matter.

To reproduce: Start a single player world, survival, enable cheating. Cheat in an assembler and computer and start building a robot. Check where robot.swing() picks up the block and where it does not.

**Comment by Aberranthian** [comment]
I've had this same issue. Seems to be if I set it to mine a 3x3 hole about 20 blocks long I see half of the blocks dropped on the ground and half in the robot inventory. I can provide addition information after work.

Some further information...

Minecraft version - 1.12.1

Exact OC jar - 'OpenComputers-MC1.12.1-1.7.0.13.jar'

How to repeat bug? - Just have your robot mine any blocks.

**Comment by Vexatos** [comment]
Does it still reproduce using 1.7.0.19?

**Comment by payonel** [comment]
@ThreadedSubProcess please retest, as vex suggested, with our latest dev build.
We have fixed an issue that could be related: http://ci.cil.li/job/OpenComputers-dev-MC1.12/

**Comment by ThreadedSubProcess** [comment]
The update (OpenComputers-MC1.12.1-1.7.0.19.jar) seems to have fixed this issue. Thanks!
