### ISSUE TITLE
[ suggestion ] Allow navigation-upgrades to be installed in adapters

### ISSUE THREAD

**Issue by theredghostwolf** [MightyPirates/OpenComputers#2553]
additionally change navigation.getPosition() to navigation.getPosition([address: string])
to get the position based on a connected component.

So for example i could connect an inventory controller, use the navigation to get its position then send that position to a drone have it move to the adapter that holds inventory controller. or calculate the position of an inventory next tot he inventory controller, then have it take or deliver items there based on some conditions on the server.

requesting something like the address of a cpu would return the position of the device they are installed in.

right now servers or computers cant interact with waypoints either besides changing their label. they cant draw a map of their positions.

**Comment by payonel** [comment]
this is an interesting proposal. I suppose the getPosition would need to return relative positions.

**Comment by theredghostwolf** [comment]
relative to the map that was used to craft just like with drones would work i think. so as long as you use the same map you could pass coordinates between computers. or even to a drone.

**Comment by thiakil** [comment]
Shouldn't the nav upgrade in an adaptor return the position of the *adaptor*? I dont really see how it makes sense to have it return the location of an arbitrary component...

**Comment by theredghostwolf** [comment]
@thiakil i came up with the idea when i was making an warehouse delivery system.

i connected a bunch of inventory controllers to get the items within each connected inventory and displayed a search able list of items to a monitor or have the data send to a tablet and then have the tablet render the list, allowing you to create a shopping list which is send to a drone which will then check each inventory for items on the shopping list (each chest had a inventory controller and a waypoint), but with a large amount of chests this process took forever, so instead i wanted to get the position of the connected inventory controller and combine that with the facing where the chest that has the requested item was connected, then include that location in the shopping list so the drone can fly to the location of the inventory controller that had the items.

so just getting the adaptor where the navigation upgrade is stored wouldnt cut it, as inventory controller and such are seen as components rather then their adaptor it would make sense to get the position based on their address. if you request stuff like a CPU it would return the position of the server / computer that it is installed in.

**Comment by thiakil** [comment]
Don't get me wrong, I understand why you want it. I'm questioning the logic. 

If I connect a GPS receiver via USB, my computer knows where the receiver is, but it can't then tell me where my mouse is.

In OC's case, perhaps directly adjacent components (relative to the adaptor's faces) would make sense, but not arbitrary components connected via a cable that could be chunks away...

**Comment by payonel** [comment]
allowing adapters to use navigation upgrades would allow a non-drone-non-robot find waypoints. And I think the `findWaypoints` results should also include the navigation component address, but it wouldn't make sense to add `getPosition(address: string)` to look up component positions by address - as the logic is based on the map you install with the upgrade, it doesn't imbue all components in its network with position data. Also, an adapter only takes a single upgrade, so I don't see how inventory controllers can be located with a navigation upgrade.

**Comment by payonel** [comment]
so i've gone full circle on this. i apologize for that
let me review the requests
1. getPosition(address: String)
the nav upgrade only knows where it self is. to know where arbitrary objects are in the world, you use waypoints.
2. computers/servers cannot interact with waypoints/cannot know their positions. This is true, and one of the values of robots. A computer has no need of locations, it can't go there. It can, on the other hand, have need of waypoint labels, as it can command a robot/drone to go to one.
