### ISSUE TITLE
[Question][1.7.10] Interactions with private enderchest from Ender Storage

### ISSUE THREAD

**Issue by adriengou** [MightyPirates/OpenComputers#2554]
Hello,
Is there something in the config to allow opencomputers to interacts with Ender Storage's enderchests ?
I use opencomputers on minecraft version 1.7.10.
Thanks for answers.

**Comment by qmnl** [comment]
Robots can interact with normal ender chests, but not with private one's. And there is no config option to change that (at least not on open computers side).

**Comment by payonel** [comment]
yes - an inventory upgrade can read the ender storage chests, even private ones apparently
