### ISSUE TITLE
Robots earn advancements instead of player

### ISSUE THREAD

**Issue by Ruukas97** [MightyPirates/OpenComputers#2556]
I'm still new to OpenComputer, so I don't really know how to use them yet. However, I spawned the Creatix once and later when I slept in a bed, I noticed:
![image](https://user-images.githubusercontent.com/4203804/31593118-f246129c-b22c-11e7-85b5-d8fb3c7d8052.png)
My player name is Ruukas

**Comment by Ruukas97** [comment]
Some more information:
I only booted it up, didn't do anything. I had it in my inventory.

**Comment by skyem123** [comment]
O_o
From my understanding, I know that robots use fake players for certain interactions, but I didn't know they could steal your achievements. I don't think this is intended, regardless of how funny it is...

**Comment by lifewcody** [comment]
Just wanna add my 'lol' here.

@payonel In the code I assume each robot's udid is associated to the real player's udid. All that would be needed is a function that intercepts achievements and if the udid of the player getting the achievement is a bot, then find the owner and direct it to them.

**Comment by Ruukas97** [comment]
I admit that it is a pretty funny bug.

I am not entirely sure if it actually is _instead_ of the player. But at least it hijacked the chat message. It's probably just something that was overlooked, when advancements were added. Might have been on Forge's side.
By my understanding, fake players is a feature of forge.

**Comment by fnuecke** [comment]
Someone threw [this Forge issue](https://github.com/MinecraftForge/MinecraftForge/pull/4438) my way on Twitter, sounds like it might be related?

(My guess is that you already had the achievement and it triggered for the fake player because the requirement is fast-forwarding a night, not actually sleeping in a bed. Just a guess though, someone would have to verify that.)

**Comment by payonel** [comment]
yep, as fnuecke said, this was an issue with the fake player and the forge issue which was resovled, and this no longer repros.
