### ISSUE TITLE
How to get and set value of command blocks

### ISSUE THREAD

**Issue by Kiritow** [MightyPirates/OpenComputers#2557]
I am using OpenComputers on Minecraft 1.10.2. I am the administrator of my server and I want my program to execute some custom commands. I tried debug card (component.debug.runCommand) but it always returns error like 'Permission denied'. Now I am thinking about command blocks and RedstoneIO block...

**Comment by xarses** [comment]
Please see https://github.com/MightyPirates/OpenComputers/blob/master-MC1.10/src/main/resources/application.conf#L1518-L1525 You need to both allow the debug card in config, and add the user to the whitelist. 

IIRC the user whitelist can be worked around by an opper placing the computer and debug card and/or starting the program running the card

**Comment by Kiritow** [comment]
It works! Thank you very much ! (I really love this mod~!)

**Comment by LoganDark** [comment]
![image](https://user-images.githubusercontent.com/4723091/34321356-d163e430-e7c1-11e7-81a7-808e533a348e.png)

I kept getting permission denied on my server, and the only way to fix it was to add the fake OpenComputers player to my ops.json (debug card was already enabled in config).

Posting this here just in case it helps anyone in the future.
