### ISSUE TITLE
how do you power the computer

### ISSUE THREAD

**Issue by assassinwolf** [MightyPirates/OpenComputers#2558]
i don't know how to power a computer

**Comment by Techokami** [comment]
If you have a power providing mod (like Immersive Engineering or Thermal Expansion, for example) loaded alongside OpenComputers, and requiring power is enabled in the OpenComputers config, all you have to do is connect your power source to the computer case block with however else you connect power to other machines/blocks. You could also connect it to a Power Converter block, then connect it to the computer case block with OpenComputers' cables, but just placing some FluxDucts between your computer case and an energy cell with RF charge is a simpler way to get started.

**Comment by payonel** [comment]
http://ocdoc.cil.li has a section that talks about power
