### ISSUE TITLE
Make some lootdisks apear more frequently

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#256]
I am currently working on a big LOOT-UPDATE or something like this(i hate the fact that there are currently only 3 of them)
But i want to have some of the programs require common libs that should appear more frequently
I could imagine entering it multiple times in the list but would look like shit
So add this in! :-) Oh and does 1.3 break mounting stuff in /lib/arandomfoldername ?

**Comment by fnuecke** [comment]
Sounds nice.
And yes, some kind of frequency annotation makes sense I suppose. In particular with the addition of custom loot disks in the save folder (so people don't have to edit the JAR) to allow those disks to 'override' the built-in one. Will be in 1.3, probably something along the lines of a syntax like this: `path=label:count`, e.g. `OpenIRC=openirc:3`.

And no, 1.3 won't directly break that, but it makes it easier to have custom OSes that may not use that folder structure (but that's their problem then :P)

**Comment by Wuerfel21** [comment]
Good, i had just the thought that the buit in disks should be OpenOS comatible, cause otherwise it could force you to download stuff. 
Now a short development sneak-peak:Working on something called noteAL, a utility lib that makes stero and multi-instrument noteblock-stuff easier
