### ISSUE TITLE
[Feature Request] Speed upgrades

### ISSUE THREAD

**Issue by InfinitiesLoop** [MightyPirates/OpenComputers#2560]
I have programmed a robot to do some work for me. This work involves an 81x81x81 area. It needs to visit each block, clear it, and potentially place a new block in its place. (aside: it's pretty neat -- plan on creating a post/video all about it).

If you do the math, the volume of that area is over 530,000 blocks. 

Each action a robot takes is about ~0.5 seconds. Every forward()/back()/turnLeft()/swing(), etc. I think on average my robot has to take 3-4 actions per block, which adds up to something like 12 days worth of work. It's really more like 18 days due to all the resupply and recharge trips it takes, too, and that's if it's running 24/7 fully chunk loaded.

I suggest adding one or two tiers of speed upgrades. Let them be crafted from sugar and emerald or something, I dunno :) A Tier 1 could double the speed, Tier 2 Quadruple it. Then my robot can run around like a rabid rabbit placing blocks and completing the project in much less time. Still a long time, but much more reasonable...

Robots current movement speed is considerably slower than a human player can move, so it seems like within the bounds of the gameplay to allow for upgrades.

I'd settle for a server setting to change the speed so I can at least work on my project in single player mode with faster iteration for finding bugs. 

Your humble user,
-InfinitiesLoop

**Comment by InfinitiesLoop** [comment]
Alternatively, it could be new tiers of battery upgrades. Higher amp output allows robot to move faster.

**Comment by xarses** [comment]
This is already accomplished with the [experience upgrades](http://ocdoc.cil.li/item:experience_upgrade)

![2017-10-19_23 36 45](https://user-images.githubusercontent.com/2107834/31808100-a026ec46-b526-11e7-93be-63305f7181dc.png)

Here is some of my herd in the various stages. To forcably train, it takes about day of it breaking and replacing the same block, while being fed charge, and able to charge, or re-make the tool its using. Other actions like moving, placing, breaking, using gain experience as well as outright consuming enchanted items.

I usually load up a T3 case with 3 in the case and one in the upgrade slot and train a whole set at a time, then disassemble it and re-make the upgrades into other robots

**Comment by InfinitiesLoop** [comment]
I had no idea it increased speed! How much faster can one get with one upgrade? Do they stack?

**Comment by InfinitiesLoop** [comment]
Well maybe I am not crazy. The XP levels do not seem to affect movement speed at all, which is what takes the most time for the work my bot is doing. It won’t make much difference if it breaks blocks faster, if it still takes 4 seconds on average per block just doing movements (forward/back/turnX).

**Comment by brisingraerowing** [comment]
There are configuration variables for robot delays under the robot/delays section in the configuration file. You probably want robot/delays/move and robot/delays/turn. Both of those have a minimum value of 0.05 (I have no idea how that value translates to ticks, and CBA to rummage through the code to find out).

**Comment by InfinitiesLoop** [comment]
Those config values have helped a lot. Combined with a tick rate mod I’ve got something like 10x speed boost. 

But the suggestion stands. I’m cheating to get this speed and would love it if I could earn it and hope to use it in mp.

**Comment by payonel** [comment]
I think this should be a separate upgrade. just changing the xp system to include speed might cause issue with automations some users already have or expect.

**Comment by xarses** [comment]
There is a lot that can be done optimization wise in the code. Turning can take quite a while, and I feel that moving up/down is slower than forward/back. doing anything that extends past the "reach" of the bot will slow you down.

"reach" forward, up and down of the direction the robot is facing

I re-wrote my looping for my dig program from y (height) ,x (forward) ,z(left/right). Initially, I also turned left and right and got those sides first (big waste of time) to y (+/-1) % 3 (that is dig the top, bottom, and forward for every 3 height). then x, z. This gained massive improvements, in not only progress of mining, but reduced energy usage.

It sounds like you aren't digging, but placing, so instead of forward, you should be concerned with going backwards instead and try to turn the robot as few times as necessary to advance what needs doing. don't forget to take advantage of the spaces above and below you.

**Comment by InfinitiesLoop** [comment]
@xarses Yup, already doing all that. The bot has to clear areas and place new blocks at the same time. It manages to minimize turns and movements for the most part. But even in ideal conditions for the simplest job, there's a minimum of 3 movements done per block -- swing, move, place. Each of these is 0.5 seconds per the default config options. For anything but small jobs it means it takes days for it to complete. I don't really mind it taking a long time, but it's a _really_ long time, and it'd feel pretty awesome for users of my program to be able to 'tech up' to reduce the time if they so desired.

**Comment by Inari-Whitebear** [comment]
I always thought the proposed OC solution here was to have more than one bot.
