### ISSUE TITLE
http://ocdoc.cil.li not working

### ISSUE THREAD

**Issue by qmnl** [MightyPirates/OpenComputers#2563]
The website just responds with `Hi.` or with `These are not the bytes you are looking for. ` on any subdirectory.

What is going on?

For anyone looking for the old website, use [this](https://web.archive.org/web/20161122100755/http://ocdoc.cil.li:80/) archive.

**Comment by S0ZDATEL** [comment]
Yes! Not works!

**Comment by LizzyTrickster** [comment]
@fnuecke what did you break?

**Comment by fnuecke** [comment]
Server updates, such fun, much breakage, wow.

Fixed. Ditto maven.cil.li. You may have to Ctrl+F5.

**Comment by qmnl** [comment]
http://ocdoc.cil.li still doesn't work

**Comment by fnuecke** [comment]
Try a hard refresh (Ctrl+F5 usually).

**Comment by qmnl** [comment]
Yes now it works, in Safari the shortcut is alt + command + r

**Comment by qmnl** [comment]
Thanks for the quick support
