### ISSUE TITLE
[Suggestion] Chunk loader for computer.

### ISSUE THREAD

**Issue by S0ZDATEL** [MightyPirates/OpenComputers#2564]
In the mod is a chunk loader for robots and drones, but not for computers or servers. It can be made in the form of a card or block.

**Comment by skyem123** [comment]
Well, not sure how it should be done to be consistent, but it sounds like a good idea.

**Comment by ben-mkiv** [comment]
it could be just allowed in a adapter?!

**Comment by Fingercomp** [comment]
Maybe simply allowing to assemble a microcontroller with the chunkloader upgrade is enough. It's even already written in [the manual](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/doc/en_US/item/chunkloaderUpgrade.md), though the upgrade seems to be blacklisted in the code.

Also, this is a duplicate of #2499.

**Comment by payonel** [comment]
allowed upgrade in uC might be the right solution, but we'll track in the other issue
