### ISSUE TITLE
[Suggestion] Interception card and wireless interception card.

### ISSUE THREAD

**Issue by S0ZDATEL** [MightyPirates/OpenComputers#2565]
Hacking device in the form of interception card can take even those modem-messages that are sent by the send command to another address. This card gets a piece of information. For example, if a card with the address **1234-5678-1234-5678** sent to the card with the address **8765-4321-8765-4321** the message **"Hi! I am a network card!"**, interception card will create a signal (**"intercepted-modem-message"** (name of signal) **"1122-1122-2211-2211"** (address of interception card), **"124-8-23-58"** (part of the address  of sender card), **"875-42-76-"** (part of the address of recipient card), **4** (port), **0** (distance from sender to interceptor), **"Hi Iam enocrd!"** (part of message)). It recipient messages on any port. Thus, after several intercepted messages from the parts of the address you can restore the full address, and if the messages are repeated - maybe even entire messages. This can be used for listening to other people's channels, determining addresses of the network cards and even for hacking. Also nice to add wireless interception card, it is even more useful. The closer the wireless card interception to the sender, the less symbols will be replaced by . Possible interception of wireless card should have a shorter range than the wireless network card (~100 blocks). As compensation for such functionality can increase complexity and power consumption compared to a normal network card. Or you can make them unable to send messages, making them capable only of reception and interception.

**Comment by Kiritow** [comment]
I think this can be implemented by a program instead of a new item...

**Comment by S0ZDATEL** [comment]
No. Now modems not able to intercept messages sent by the command **send(address, port, message)** to other modems. **Broadcast()** messages - yes, but not **send()**. Sent by the command **send()** message is received only by the addressee.

**Comment by skyem123** [comment]
I had this idea too, and yeah it should exist, see issue #1597. It's a bit old though. :P

**Comment by payonel** [comment]
I'm of the opinion that users can use computronic's spoofing card.
