### ISSUE TITLE
[Suggestion] Dish.

### ISSUE THREAD

**Issue by S0ZDATEL** [MightyPirates/OpenComputers#2566]
Parabolic antenna that allows you to send information over long distances. You can configure it with a wrench or function **setRotation(x, y, z)**. Two such antennas, precisely tuned to each other, can exchange messages. They do not use ports and addresses, they just send a message to the direction in which they are configured. Thus, it is impossible to know what address the message came, you can only see the direction.

**Comment by payonel** [comment]
This is a creative idea, but this adds a bit of complexity to the mod that I don't think adds any feature. if you want longer range wireless you can setup repeaters or change the configs.

**Comment by xarses** [comment]
Also, isn't this simply a the same as the existing linked cards?

**Comment by payonel** [comment]
definitely an overlapping use case
