### ISSUE TITLE
[Suggestion] Better keyboards.

### ISSUE THREAD

**Issue by S0ZDATEL** [MightyPirates/OpenComputers#2567]
Now the keyboard works only if it is connected to the monitor. It would be nice to make it self-sufficient. For example, if I want to make a code lock, I have to use monitor, either the touch or non-touch but with the keyboard. It would be interesting to make a code lock only with the keyboard, and the correct combination to denote the sound signals. Or even make a separate type of keyboard - numpud, consisting of digits 0-9, the buttons "Enter" and "Reset". Numpud needs to work as a touchscreen monitor, ie without the interface, the processing simply pressing RMB.

**Comment by payonel** [comment]
interesting idea, i suggest you consider the keypad from opensecurity https://github.com/PC-Logix/OpenSecurity/wiki/Blocks
opensecurity is a nice addon to opencomputers
