### ISSUE TITLE
[Suggestion] Comfortable EEPROM.

### ISSUE THREAD

**Issue by S0ZDATEL** [MightyPirates/OpenComputers#2568]
Now the use of EEPROM is not very convenient. So, we can insert and remove it into a computer or server, but to replace him in the drone we must "remove" the drone with a wrench and put the EEPROM with the drone in the crafting grid. Why not make a separate slot for EEPROM in drone, as is done at the computer?

**Comment by Vexatos** [comment]
You can switch the EEPROMs in placed drones and MCUs by shift-right clicking them with another EEPROM.

**Comment by S0ZDATEL** [comment]
Oh, yeah? I didn't know. Thanks for the advice!
