### ISSUE TITLE
[Suggestion] Printer.

### ISSUE THREAD

**Issue by S0ZDATEL** [MightyPirates/OpenComputers#2569]
The printer allows you to print text on paper and in books, print paintings, which can then be hung on the wall and print maps (here I just have not figured out how to implement it. Perhaps printed on the map will be erased when you update the map?). Printer, as 3D printer uses ink cartridge.

**Comment by skyem123** [comment]
There is already a mod that adds a printer. It's called [OpenPrinter](https://oc.cil.li/index.php?/topic/54-mc-16417101891941102-openprinter/).
