### ISSUE TITLE
Crash when computers are powered up

### ISSUE THREAD

**Issue by Kayinnasaki** [MightyPirates/OpenComputers#257]
Trying to run Opencomputers on Tekkit on mc 1.6.4. I get a crash that occurs within a minute of powering on a computer. Sometimes happened almost immediately. Tried new dev builds and different worlds with the same results.

I realize this might not be terribly useful due to being part of a modpack but it seems it works for other people using tekkit? Anyways here's the crash log.

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 5/16/14 1:24 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: li.cil.oc.api.machine.Owner.x()I
    at li.cil.oc.server.component.machine.NativeLuaArchitecture.save(NativeLuaArchitecture.scala:680)
    at li.cil.oc.server.component.machine.Machine.save(Machine.scala:624)
    at li.cil.oc.common.tileentity.traits.Computer$$anonfun$writeToNBT$1.apply(Computer.scala:165)
    at li.cil.oc.common.tileentity.traits.Computer$$anonfun$writeToNBT$1.apply(Computer.scala:165)
    at li.cil.oc.util.ExtendedNBT$ExtendedNBTTagCompound.setNewCompoundTag(ExtendedNBT.scala:52)
    at li.cil.oc.common.tileentity.traits.Computer$class.writeToNBT(Computer.scala:165)
    at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$Colored$$super$writeToNBT(Case.scala:16)
    at li.cil.oc.common.tileentity.traits.Colored$class.writeToNBT(Colored.scala:32)
    at li.cil.oc.common.tileentity.Case.func_70310_b(Case.scala:75)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:317)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:127)
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:232)
    at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:284)
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:899)
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:360)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:124)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 166979256 bytes (159 MB) / 968359936 bytes (923 MB) up to 968359936 bytes (923 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1024m -XX:MaxPermSize=128m
    AABB Pool Size: 4280 (239680 bytes; 0 MB) allocated, 3296 (184576 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 2, tallocated: 64
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 113 mods loaded, 113 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.4.49.965} [Forge Mod Loader](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.11.1.965} [Minecraft Forge](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics-Core{rv14.finale3} [AppliedEnergistics Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{0.9.0.7} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ImmibisMicroblocks{57.6.3} [Immibis's Microblocks](immibis-microblocks-57.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.6.1.8} [Not Enough Items](notenoughitems 1.6.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsCore{0.3} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PowerCrystalsCore{1.1.8} [PowerCrystals Core](powercrystalscore-1.1.8-9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_ReiMinimap{v3.4_01 [1.6.2]} [mod_ReiMinimap]([1.6.4]ReiMinimap_v3.4_01.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics{rv14.finale3} [Applied Energistics](appeng-rv14-finale3-mc16x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{4.2.2} [BuildCraft](BUILDCRAFT-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    UniversalElectricity{3.1.0} [Universal Electricity](universal-electricity-3.1.0.66-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers|Core{1.0.0} [OpenComputers (Core)](OpenComputers-MC1.6.4-1.2.9.369-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CalclaviaCore{1.2.0} [CalclaviaCore](calclavia core-1.2.0.299-main.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AtomicScience{1.2.0} [Atomic Science](atomic-science-1.2.0.63-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Autoutils{1.0.1} [Autoutils](autoutils-1.6.4-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Backpack{1.26.29} [Backpack](BACKPACK-1.26.29-1.6.X.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ComputerCraft{1.58} [ComputerCraft](ComputerCraft1.58.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{4.2.2} [BC Builders](BUILDCRAFT-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{4.2.2} [BC Energy](BUILDCRAFT-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{4.2.2} [BC Factory](BUILDCRAFT-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{4.2.2} [BC Transport](BUILDCRAFT-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded{1.6.2R2.7.5} [MineFactory Reloaded](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{2.0.0.2} [CoFH Core](cofhcore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NetherOres{1.6.2R2.2.1} [Nether Ores](NetherOres-2.2.1-14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.0.0.250} [Forge Multipart](ForgeMultipart-universal-1.6.4-1.0.0.250.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{3.0.0.2} [Thermal Expansion](thermalexpansion-3.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BigReactors{0.3.0A} [Big Reactors](bigreactors-0.3.0A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bspkrsCore{v5.3(1.6.4)} [bspkrsCore](bspkrscorev5.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{4.2.2} [BC Silicon](BUILDCRAFT-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Additional-Buildcraft-Objects{1.0.7.560} [Additional Buildcraft Objects](buildcraft-Z-additional-buildcraft-objects-1.0.7.560.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CarpentersBlocks{2.0.3} [Carpenter's Blocks](carpenter's blocks v2.0.3 - MC 1.6+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ChickenChunks{1.3.3.3} [ChickenChunks](ChickenChunks 1.3.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHLoot{2.0.0.2} [CoFH Loot](cofhcore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHMasquerade{2.0.0.2} [CoFH Masquerade](cofhcore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHSocial{2.0.0.2} [CoFH Social](cofhcore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHWorld{2.0.0.2} [CoFH World](cofhcore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CCTurtle{1.58} [ComputerCraft Turtles](ComputerCraft1.58.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ImmibisCore{57.1.94} [Immibis Core](immibis-core-57.1.94.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DimensionalAnchors{57.1.95} [Dimensional Anchors](dimensional-anchor-57.1.95.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    dimdoors{1.6.4R2.2.2RC1} [Dimensional Doors](dimensionaldoors-2.2.2RC1-311.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    emashercore{1.2.3.4} [Emasher Resource](EmasherResource-1.2.3.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderStorage{1.4.3.5} [EnderStorage](EnderStorage 1.4.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    eng_toolbox{1.1.8.3} [Engineer's Toolbox](EngineersToolbox-1.1.8.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EE3{0.1} [Equivalent Exchange 3](equivalentexchange3-1.6.4-0.1.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mystcraft{0.10.12.01} [Mystcraft](mystcraft-uni-1.6.4-0.10.12.01.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenMods{0.3} [OpenMods](openmodslib-0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Core{4.3.3.28} [ProjectRed](projectredbase-1.6.4-4.3.3.28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transmission{4.3.3.28} [ProjectRed-Transmission](projectredintegration-1.6.4-4.3.3.28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Railcraft{8.4.0.0} [Railcraft](Railcraft_1.6.4-8.4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenPeripheralCore{0.3.2} [OpenPeripheralCore](openperipheralcore-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraUtilities{1.0.1} [Extra Utilities](extrautils-1.0.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FinderCompass{1.6.4X} [Finder Compass](FinderCompass_1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GalacticraftCore{2.0.11} [Galacticraft Core](galacticraft-1.6.4-2.0.11.978.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GalacticraftMars{2.0.11} [Galacticraft Mars](galacticraft-planets-1.6.4-2.0.11.978.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GregsLighting{1.9.1} [Greg's Lighting](GregsLighting-1.9.1-mc1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.56} [Inventory Tweaks](InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{5.4.1.697} [Iron Chest](ironchest-universal-1.6.4-5.4.1.697.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LogisticsPipes|Main{0.7.4.dev.106} [Logistics Pipes](logisticspipes-mc1.6.4-0.7.4.dev.106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFR Compat Forestry Trees{1.0} [MFR Compat Forestry Trees](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFR Compat Extra Trees{1.0} [MFR Compat Extra Trees](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAppliedEnergistics{1.6.2R2.7.5} [MFR Compat: Applied Energistics](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAtum{1.6.2R2.7.5} [MFR Compat: Atum](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatBackTools{1.6.2R2.7.5} [MFR Compat: BackTools](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatBuildCraft{1.6.2R2.7.5} [MFR Compat: BuildCraft](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatChococraft{1.6.2R2.7.5} [MFR Compat: Chococraft](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatExtraBiomes{1.6.2R2.7.5} [MFR Compat: ExtraBiomes](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForestry{1.6.2R2.7.5} [MFR Compat: Forestry](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForestryPre{1.6.2R2.7.5} [MFR Compat: Forestry (part 2)](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForgeMicroblock{1.6.2R2.7.5} [MFR Compat: ForgeMicroblock](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatIC2{1.6.2R2.7.5} [MFR Compat: IC2](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatMystcraft{1.6.2R2.7.5} [MFR Compat: Mystcraft](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatPams{1.6.2R2.7.5} [MFR Compat: Pam's Mods](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Exploration{4.3.3.28} [ProjectRed-Exploration](projectredworld-1.6.4-4.3.3.28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatProjRed{1.6.2R2.7.5} [MFR Compat ProjectRed](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatRailcraft{1.6.2R2.7.5} [MFR Compat: Railcraft](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatRP2{1.6.2R2.7.5} [MFR Compat: RP2](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatSufficientBiomes{1.6.2R2.7.5} [MFR Compat: Sufficient Biomes](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatThaumcraft{1.6.2R2.7.5} [MFR Compat: Thaumcraft](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatThermalExpansion{1.6.2R2.7.5} [MFR Compat: Thermal Expansion](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatTwilightForest{1.6.2R2.7.5} [MFR Compat: TwilightForest](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatVanilla{1.6.2R2.7.5} [MFR Compat: Vanilla](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatXyCraft{1.6.2R2.7.5} [MFR Compat: XyCraft](minefactoryreloaded-2.7.5-352.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFFS{3.6.2} [Modular Force Field System](modular-force-field-system-3.6.2.56-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    numina{0.1.2-55} [Numina](numina-1.6.2-0.1.2-55.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    powersuits{0.10.0-91} [MachineMuse's Modular Powersuits](modularpowersuits-1.6.4-0.10.0-91.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIPlugins{1.1.0.6} [NEI Plugins](neiplugins-1.1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OCS{1.6.4.1} [OpenCCSensors](OPENCCSENSORS-1.6.4.1B.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers{1.2.9.366} [OpenComputers](OpenComputers-MC1.6.4-1.2.9.369-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenPeripheral{0.1.2} [OpenPeripheralAddons](openperipheraladdons-0.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    powersuitaddons{@VERSION@} [Andrew's Modular Powersuits Addons](powersuitaddons-1.6.4-884.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bau5_ProjectBench{1.8.0} [Project Bench](ProjectBench-1.6.2-v1.8.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transportation{4.3.3.28} [ProjectRed-Transportation](projectredmechanical-beta-1.6.4-4.3.3.28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Compatibility{4.3.3.28} [ProjectRed-Compatibility](projectredcompat-1.6.4-4.3.3.28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Integration{4.3.3.28} [ProjectRed-Integration](projectredintegration-1.6.4-4.3.3.28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Illumination{4.3.3.28} [ProjectRed-Illumination](projectredlighting-1.6.4-4.3.3.28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Expansion{4.3.3.28} [ProjectRed-Expansion](projectredmechanical-beta-1.6.4-4.3.3.28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    QuantumCraft{1.1} [qCraft](qcraft1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Redstone Arsenal{1.0.0.0} [Redstone Arsenal](RedstoneArsenal-1.0.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    JAKJ_RedstoneInMotion{2.3.0.0} [Redstone In Motion](redstoneinmotion_2.3.0.0_mc1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    StevesCarts{2.0.0.b10} [Steve's Carts 2](stevescarts2.0.0.b10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    tradeboothmod{0.6.4.2} [Trade Booth Mod](tradebooth.0.6.4.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TreeCapitator{Forge 1.6.4.r09} [Treecapitator](TREECAPITATOR.FORGE.1.6.4.R09.UNIVERSAL.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Vending{1.1.1} [Vending](vending-1.6.4-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.5.1} [Waila](waila_1.5.1a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    weaponmod{1.6.2 v1.13.5} [Balkon's WeaponMod](WeaponMod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WR-CBE|Core{1.4.0.6} [WR-CBE Core](WR-CBE 1.4.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WR-CBE|Addons{1.4.0.6} [WR-CBE Addons](WR-CBE 1.4.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WR-CBE|Logic{1.4.0.6} [WR-CBE Logic](WR-CBE 1.4.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    McMultipart{1.0.0.250} [Minecraft Multipart Plugin](ForgeMultipart-universal-1.6.4-1.0.0.250.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMicroblock{1.0.0.250} [Forge Microblocks](ForgeMultipart-universal-1.6.4-1.0.0.250.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 1860 (104160 bytes; 0 MB) allocated, 1765 (98840 bytes; 0 MB) used
    Player Count: 1 / 8; [GCCorePlayerMP['Kayin'/243, l='test', x=-293.76, y=72.00, z=-5.28]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by fnuecke** [comment]
The Calclavia Core version is outdated, it contains an older version of the OC API. You'll want build 309 or newer.

**Comment by jeffreykog** [comment]
Why does it even include the api? We have @Optional nowadays

**Comment by Kayinnasaki** [comment]
Well, sorry for not submitting a real bug but thanks for telling me what I needed to get OC working! \o/
