### ISSUE TITLE
[Suggestion] Jammer.

### ISSUE THREAD

**Issue by S0ZDATEL** [MightyPirates/OpenComputers#2571]
Jammer does not allow to operate a wireless network card in its range. The range can be adjusted. It creates noise on all ports, any modem-message will be converted into noise (string of random length consisting of random symbols). Modems will be spammed by random messages all the time. Perhaps you can set a white list to the ports. The ports in a white list, will not be subject to noise.

**Comment by skyem123** [comment]
Well... it's worth noting that a modem will only get messages on ports that it has opened.

**Comment by S0ZDATEL** [comment]
Yes. Jammers will spam messages. Whichever port is opened on modem, if that doesn't port from white list - it will get spam.

**Comment by Fingercomp** [comment]
I can't see how this can be useful. Spamming messages just because someone has installed a magic block called jammer is kind of silly, I think.

**Comment by S0ZDATEL** [comment]
This can be used for protection. For example, the other player will not be able to control the drone via a modem near your home, because of the communication modem will be repress.

**Comment by skyem123** [comment]
It's an interesting concept, that's for sure, though it's uses might be limited...

**Comment by payonel** [comment]
all wireless messages just queue up. you could do some denial of service, but not everything would be lost. keep in mind that you know where a message came from, the sending address is sent in the modem_message. link cards are also a very safe setup. i think mostly this feature would be used to add noise and grief to other peoples networks :)

the thing is, you can already do this with a second computer and just spam the network using modem.broadcast
