### ISSUE TITLE
Robots cannot break bee hives from Forestry

### ISSUE THREAD

**Issue by InfinitiesLoop** [MightyPirates/OpenComputers#2572]
When a robot armed with a high level pick comes across a hive, swing() fails. This makes it difficult to have a program that clears out an area if that area includes trees as there is bound to “bee” a few hives in there. :(

**Comment by brisingraerowing** [comment]
I "bee-lieve" that a scoop is needed to break a hive, as other tools may not work. It would "bee" nice if we could use a database to compare with hives, but I don't think there's a way to actually pick the hive up so that it could be put in the database (other than creative).

**Comment by brisingraerowing** [comment]
I just found you can use an anvil to put silk touch on a scoop, but that doesn't really do anything.

**Comment by InfinitiesLoop** [comment]
You can break a hive with a pick just fine, you just don’t get a queen bee or something like that. So it’s a block that needs a special tool for a special purpose, but can be treated like stone otherwise. It’s frustrating because I don’t even care about the mod, it just comes with FTB, and my landscape is littered with hives that block my bots. 

It’s kind of that mods fault, but it also seems like a bug with oc just bee-cause a player can break a hive with a pick just fine. The tool requirement in this case is different than an ore needing a certain level pick. 

I don’t need a database upgrade for what I am doing and can’t afford the component cost to add one in my bot case. So I’m going to end up having to make a routine that retries failed swings with a scoop, not to mention figure out how to make a scoop, and all to deal with a block I couldn’t care less about. Stuff like this makes me cringe when mods add new tool types. Just seems unnecessary.

**Comment by payonel** [comment]
you can now use a scoop and "swing" at the beehive, it'll break and the robot will collect the items it drops

probably fixed with 8940388cb7981dc0b2ad51456d3fe9e4172b42b0
