### ISSUE TITLE
[Suggestion] Modular armor.

### ISSUE THREAD

**Issue by S0ZDATEL** [MightyPirates/OpenComputers#2574]
Some of these items of clothing cannot be called armor, but that's not important. Present in mod hover boots look too strange. It would be nice if they were customizable and contain various components that change their properties.

- Boots.
  - Hover. Add drone case to the boots will make it like the hover boots, but better (#2274).
  - Insulation. Touch-screen monitors do not react to the player who walks on them in insulated boots.
  - Charging. Adding a charger to the boots will allow you to charge armor by standing close to a charger.
- Pants.
  - Servos. Increase speed. Reduces recoil. Can get commands like go(forward, 1) or setCrouch(true).
  - Dynamo. Produces energy during walking.
- Chestplate.
  - Computer. Yes, real computer on your chestplate. Can control other armor parts.
  - Storage lockers. Add extra slots to inventory.
  - Drone port. Allows you to dock the drone to the back.
- Helmet.
  - Solar panel. Simple solar panel.
  - Motion sensor. Reacts to movement around the player, for example, the skeleton crept back.
  - Monitor glasses. Like augmented reality glasses from OpenGlasses.

Imagine how cool is that? Motion sensor noticed the zombie at the left - warning message appears on glasses. The skeleton shot to you - servos evaded the arrow themself. You started to aim at him - on the glasses appeared sight, calculated taking into account the distance to the skeleton.

**Comment by Fingercomp** [comment]
This seems far out of the scope of OpenComputers. It's probably better to create a new mod.

**Comment by skyem123** [comment]
Maybe it'd be neat to have extra armour for each type, we already have boots, so it'd be neat to have other gimmicks.

**Comment by S0ZDATEL** [comment]
And is available now hover boots do not go beyond mod?

**Comment by Techokami** [comment]
iirc hover boots were developed as a sort of in-joke. But if you want high tech modular powered armor, [there's always Modular Powersuits.](https://github.com/MachineMuse/MachineMusePowersuits)

**Comment by payonel** [comment]
I really like these suggestion, to be quite honest. But I think this should be done is an add-on to opencomputers.

**Comment by payonel** [comment]
I've decided to share the boots ideas to to #2274

As for the pants, chestplate, and heltmet features, I think it would fit more into OC to add more nanomachine features for these. nanomachines work like computerized potion effects. Even the boots idea for soft footed (no touch) could be a nanomachine effect.

**Comment by payonel** [comment]
I do really like this feature request, but I feel with more armor options OC is more an all-in-one mod. And we'd like to keep it focused on the core features we already have. I do think this would make a great add-on
