### ISSUE TITLE
[Suggestion] Improved nanomachines.

### ISSUE THREAD

**Issue by S0ZDATEL** [MightyPirates/OpenComputers#2577]
This topic has been raised in the post #2385, and there was a lot of good ideas. But some was not entirely successful. Here's what I suggest:

- Perhaps effects should not be random? I think it would be better if you make different types of nanomachines (or even custom), and each type will have its own list of available effects, and effects will be available not based on random numbers, but title. For example, instead of setInput(1) issuing a random effect, we use the command setHealing(1), which will give us the first level regeneration .
- Functioning of nanomachines need to improve. Now they receive signals on any port from any source. It is not safe. Better if they have some code before dropping into the body (for example, entered into them with the EEPROM). We also need to be able to check their code (getCode()) or change it (setCode()). They must have different parameters, like amount. The more in you nanomachines of the same type, so they are more efficient, but also increases the power consumption. Over time they can out of order and their number decreases. It may happen that they are over. But they can replicate themselves. If their number are too small - they are ineffective, if too many - they use too much energy. You may be able to contain several different types of nanomachines at the same time, but can happen conflicts. They should be able to get information directly from the body (for example, getPlayerHealth() or getPlayerHungry()).

**Comment by Vexatos** [comment]
Please do not open new issues for suggsetions that already have issues associated with them. Use #2385 for commenting.
