### ISSUE TITLE
[Suggestion] Use of a wrench.

### ISSUE THREAD

**Issue by S0ZDATEL** [MightyPirates/OpenComputers#2578]
I think that some computer components like the monitor or holoprojector too fragile, why we break them with a pickaxe. Perhaps they could be unscrewed with a wrench?

**Comment by Techokami** [comment]
Well, there is a Scrench item. Perhaps a Crouch + Use action of the Scrench on these blocks should auto-harvest them?

**Comment by S0ZDATEL** [comment]
That's what I meant.

**Comment by Pizzn** [comment]
Something I really appreciate in OC is the fact that we don't need fancy tools to setup/break something. I don't need the experience IC2 gives me every time I break a machine with my pick-axe. 😠

Just my 2 cents.

**Comment by payonel** [comment]
@Pizzn i should have added some of my opinions on what would be allowed (i.e. it is open for adoption, but what would I accept)

I think we should allow a scrench "pop" to pick up the oc blocks.
We could slightly increase the "durability" of oc blocks to delay "pop" time
We would not cause oc blocks the destructively "pop"

**Comment by Pizzn** [comment]
@payonel ah, yes, I see. So similar to Ender IO's conduit behavior,  that sounds like a good idea.

**Comment by Inari-Whitebear** [comment]
What do you mean wiht "pop"?

**Comment by Darinth** [comment]
He means similar to how ender io/thermal expansion work. A shift-right-click will instantly break the block and drop it in the world, but it can still be broken with a pickaxe but will take a bit longer.

**Comment by xarses** [comment]
Adding in that the swrench "pop" will result in cases not spewing guts everywhere
