### ISSUE TITLE
[Language correction] Hover boots in the Russian language not quite "hover".

### ISSUE THREAD

**Issue by S0ZDATEL** [MightyPirates/OpenComputers#2579]
Hover boots translated into Russian language as "реактивные ботинки". But "реактивные ботинки" isn't a "hover boots", it's more like "rocket boots" or "jet boots". More correct translate is "парящие ботинки".

**Comment by ghost** [comment]
Feel free to submit a pull request.

**Comment by payonel** [comment]
@S0ZDATEL if you make it a pull request I'd be glad to merge it in. Thanks
https://help.github.com/articles/about-pull-requests/

**Comment by S0ZDATEL** [comment]
I haven't got used to GitHub, but I think I did it right...

**Comment by payonel** [comment]
wow, so, you only needed to make a PR against our default branch, master-MC1.7.10
