### ISSUE TITLE
Add a Sangar mob

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#258]
If OpenComputers included its own Sangar Mob, say via spawn eggs, then we would have an alternative person to complain to when OpenComputers breaks :P

**Comment by LordFokas** [comment]
Make him a villager that sells grog :p

**Comment by fnuecke** [comment]
Heh, the grog selling would be neat. Would have to be consumable and poison you, though :P Maybe some day as an easter egg...

As a workaround, rename a Robot and make it crash multiple times.
