### ISSUE TITLE
ForgeMultipart with Robot make ghost block.

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#26]
ＰＲ－＞
　　　Ｂ

After That happen,

　　ＧＰＲ－＞
　　Ｂ

Ｒ is Robot, with `while true do robot.forward(); robot.back(); end`
Ｐ is Player, trying push the robot!
Ｇ is Ghost Block(Offline Robot), in Server-side (When try to place any block in that space, the block will show) NBT=`{x=-99, y=63, z=200, id='cc:cable', cc:node(TagCompound)`
Ｂ is ForgeBultipart Block, Top-Side are Stone-Panel.

**Comment by fnuecke** [comment]
Can't reproduce it, but I'll add some more aggressive removal strategies for the ghost blocks, hopefully that'll help.

**Comment by fnuecke** [comment]
Did you change anything in the config? Speed up the robot's movement, for example?

**Comment by ghost** [comment]
Nothing with robot config. But i will check later with latest version (Actually that is uncommon)
