### ISSUE TITLE
Revert 89bd057

### ISSUE THREAD

**Issue by makkarpov** [MightyPirates/OpenComputers#2600]
Do you see those Russian paths to assets in 89bd057782a5c9363d63ab45843e2b446cd14d64? :D
Machine translation is so machine.

**Comment by S0ZDATEL** [comment]
What do you dislike? Why do you think that the previous version was better?

**Comment by makkarpov** [comment]
Previous version did not used cyrillic paths

**Comment by S0ZDATEL** [comment]
Oh? What? Why is this so? I just translated the file, but not its path... Strange...

**Comment by S0ZDATEL** [comment]
I didn't notice it. And I did not change the path. Most likely, the built-in browser translator did it for me...

**Comment by payonel** [comment]
ha! I didn't notice that either :)
I'll rename the file, should be src/main/resources/assets/opencomputers/lang/ru_RU.lang

**Comment by payonel** [comment]
https://github.com/MightyPirates/OpenComputers/commit/2f1332f6051731fb594950660093f4711fa18bad
