### ISSUE TITLE
[Suggestion] Advanced guide.

### ISSUE THREAD

**Issue by S0ZDATEL** [MightyPirates/OpenComputers#2603]
Right now the in-game OpenComputers guide is only a short description of the components. I propose to add some improvements to this guide.

- Crafting recipes. It would be great if you could see the crafting recipes right in the manual.
- Functions of the components. If in the manual will describes the functions of the components, it would be much easier to learn the mod.
- Lua guide. People who do not know the syntax of Lua will be much easier to master mode, if in the manual will be described the syntax of Lua, and not just given a link to a guide.

**Comment by skyem123** [comment]
1. Is less useful with mods that shows them but could be useful in situations where said other mods aren't ported.
2. Exists in the [wiki](http://ocdoc.cil.li), but... the separation can be confusing.
3. Is a separate thing that exists, such as the [Lua manual](https://www.lua.org/manual/5.3/), and [programming in Lua](https://www.lua.org/pil/contents.html).

I do understand how the things being split up can be confusing, but it's also impractical to merge them. Though I do think it'll be a good idea in the long run to merge the wiki and in game manual as much as possible.
I'm not sure if one is allowed to include the existing Lua manuals inside OC itself, and making one would be very time consuming... Though maybe a link to it would be better than nothing.

**Comment by payonel** [comment]
I will leave this ticket open because we can ALWAYS improve our documentation and manuals. But the bad part about having this ticket open for that reason is that it can never be closed :)

And so, I offer that this ticket is open until SOME improvements are made. Specifically, I'll review the manual for any inaccuracies.

**Comment by payonel** [comment]
now dup of #2686
