### ISSUE TITLE
[Question] Get position of robots

### ISSUE THREAD

**Issue by qmnl** [MightyPirates/OpenComputers#2604]
I wan't to use the api to get the position of a robot. Thus I need to get a list of all robots and then get the position of one of them. I've searched through the api package but couldn't find out how to do this.

Branch: master-MC1.12

**Comment by payonel** [comment]
http://ocdoc.cil.li/component:navigation
the navigation upgrade can give you a relative position from a configured starting location. you can also use waypoints to determine relative positions
else, you keep track of changes in position

we don't provide a universal xyz

**Comment by qmnl** [comment]
Thank for the quick response!

I wanted to get the position of the robots using a mod, not from Lua on a robot, I've probably not expressed myself correctly. I've now figured it out, basically by looping through all tile entities.
