### ISSUE TITLE
Robots cause water to flow around them even after leaving

### ISSUE THREAD

**Issue by InfinitiesLoop** [MightyPirates/OpenComputers#2605]
When a robot steps into water, water flows around it, as expected. But after leaving, the water remains. This can cause a single source block of water (or lava) to extend flowing blocks in every direction if the robot walks through the water in those directions. There are cases where these interact with other existing source blocks to create new source blocks. I have had a single source block cause flowing water blocks to fill a 25x25x50 area because of this. The main time you run into it is when a robot digs a quarry. It walks through the water or lava that happens to be in the way, spreading it more and more each time it goes through it.

Here's a sequence of screenshots that show it in action. 

I suppose it is because the robot is not causing an 'update' to trigger from the block it came from, so the water doesn't know it needs to update its flowing state? Wild guess.

![2017-10-28_19 21 17](https://user-images.githubusercontent.com/202632/32140235-b0dff39c-bc16-11e7-8f8d-370e82c8bffe.png)
![2017-10-28_19 21 51](https://user-images.githubusercontent.com/202632/32140236-b0f7505a-bc16-11e7-953c-0bea975c56c1.png)
![2017-10-28_19 22 12](https://user-images.githubusercontent.com/202632/32140237-b10e7f78-bc16-11e7-8574-395cdc928e2b.png)

**Comment by 0f-0b** [comment]
Vanilla Minecraft bug

**Comment by qmnl** [comment]
Yes, if you would place and then remove dirt where your robot moves along, it would result in exactly the same result

**Comment by InfinitiesLoop** [comment]
Hmmm. Ok, but that hopefully doesn’t mean oc can’t work around it. Water doesn’t do that when an entity like a player or mob enters it, so why should it for a robot? Perhaps it’s registering as a block and not an entity?

**Comment by InfinitiesLoop** [comment]
More than a minor annoyance. When my bot digs a quarry unattended for a long time, it can cause so much flowing water and lava to appear that the client lags animating it, and cleaning it up is extremely difficult.

**Comment by qmnl** [comment]
Since robots are actually blocks (that's intended), it would be hard to work around it. But you can use drones, which are entities, and those won't disturb the water

**Comment by qmnl** [comment]
Actually drones will shut down if they are in fluids ...

**Comment by payonel** [comment]
tbh, this almost feels like a feature request.

**Comment by qmnl** [comment]
Drones being able to go through water? Maybe with an upgrade.

But water somehow ignoring the robots would probably break many mob farms, which use water.

**Comment by payonel** [comment]
yeah, this is based on some vanilla mechanics of water generation
