### ISSUE TITLE
1.7.10 Thread library load error

### ISSUE THREAD

**Issue by anar4732** [MightyPirates/OpenComputers#2606]
> local thread = require("thread")

not working.

https://i.hizliresim.com/o6VAmQ.png

Please fix this immediate

**Comment by payonel** [comment]
this doesn't repro for me, and i have unit tests that use the thread library extensively that are run before any push I make to update openos

That said, you would need to provide a lot more repro info 

what version of oc are you using?
Does this happen from the openos install floppy?
does this repro if you 1. boot from readonly openos floppy, 2. open lua shell, and 3. run `=thread`

Thanks

**Comment by payonel** [comment]
ADDITIONALLY, are you modifying the kernel libraries or structures, are you trying to set a custom metatable on the event library? Don't do anything like this unless you expect failures.
