### ISSUE TITLE
Unable to run OpenComputers in Dev-Environment

### ISSUE THREAD

**Issue by feldim2425** [MightyPirates/OpenComputers#2608]
I tried to download OpenComputers from maven (http://maven.cil.li/li/cil/oc/OpenComputers/MC1.10.2-1.7.0.124/) and added it to "run/mods"
I did't find the dev jar, so I assume the normal build works in an dev environment.

Crash Log: https://pastebin.com/HuyKp0tE

I removed OpenComputers as a test from the gradle dependencies but still crashes with the same error.

**Comment by skyem123** [comment]
Hmm... I don't know for sure, but I do know that OC does some funky stuff that is based on the obfuscated names. Though that might be meaningless and I know nothing. :P
Quickly checking the log, there does seem to be some reflection going on...

**Comment by feldim2425** [comment]
I tried to add ``deobfCompile "li.cil.oc:OpenComputers:MC1.10.2-1.7.+"`` in build.gradle . Now it starts without crashing but there is another error: https://pastebin.com/6b3y2eGb

This seems to disable the drivers for the Redstone and the Wireless Network Cart. I can't add them to a Computer, Relay, ....
ChickenBonesLib is added to the dependencies (``compile "codechicken:CodeChickenLib:1.10.2-2.5.+:deobf"``) but disabling that line has no effect.

EDIT: But it does crash Minecraft as soon as I place a Screen: https://pastebin.com/DygcNqFk

**Comment by feldim2425** [comment]
OK I think I found the Issue. Seems like Eclipse or the Gradle Script that in combination with Eclipse, messes around with the dependencies. After switching to IntelliJ it woks fine. 
Still I don't know exactly why it won't work in eclipse. But at least it works

**Comment by skyem123** [comment]
Interesting, it's not good that it doesn't work in Eclipse, but at least it's not completely broken.

**Comment by payonel** [comment]
We develop OC using IDEA and gradle - so we can help give build steps for those. Eclipse support is slightly out of scope - but I'm glad you got it working on IDEA
