### ISSUE TITLE
Wiki Issue: Terminoligy

### ISSUE THREAD

**Issue by awsmazinggenius** [MightyPirates/OpenComputers#261]
Often on the wiki, the word "callback" is used to describe regular functions. A function is either something you define and call, or something that the system defines and you call. A callback is something that you define and the system calls. For example, on the Component Sign page (I'm looking at commit 20d3f9a033cbc9db3ee572aee87976611b2a24a2 ), you use "callback" when the proper term is "function". Is there a reason for this?

**Comment by fnuecke** [comment]
I agree with that definition, I just never really thought about it, frankly. Go ahead and correct those occurrences on the wiki when you spot them. Thanks!
