### ISSUE TITLE
Uses Power even without Power supplying mods present

### ISSUE THREAD

**Issue by Pizzn** [MightyPirates/OpenComputers#2613]
OC does not detect the absence of power anymore. Fired up MC with only OC, robots and the electronics assembler still use power.
Tested with MC 1.10.2, Forge 2511, OC 1.7.0.128.

**Comment by brisingraerowing** [comment]
This was caused by the addition of Forge Energy as a valid power source. Since Forge itself provides that, there is technically always a power 'mod' present. You need to disable power usage in the config now.

**Comment by payonel** [comment]
yep - we are limited by supporting forge energy as an energy source. if you plan to play without a power mod you'll need to disable power in the configs unfortunately. maybe someone will PR a simple, but yet another, coal generator :)

**Comment by skyem123** [comment]
Theoretically, could you detect the presence of energy supplying mods using the API? Or is it written in a way that doesn't allow it?

**Comment by payonel** [comment]
@skyem123 it was explained to me that forge api doesn't tell us if there is a producer of the energy. we would have to check for an explicit list of mods. which is sort of what we used to do, but we wanted to support forge energy in general and not limit the supported list

**Comment by skyem123** [comment]
That's actually kinda annoying. Maybe display a warning that there may or may not be a way to power computers and to change the config if needed, similar to how it used to work when there was no forge energy. :P

**Comment by payonel** [comment]
we'll leave this ticket closed, and track a solution via #2655
