### ISSUE TITLE
runClient gradle Task doesn't want to work.

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#2614]
So it seems that for some reason it loads the AE2 jar twice?

https://gist.github.com/Inari-Whitebear/e6bd334deb41b74b7bc37377dfe547f3

**Comment by payonel** [comment]
the ae2 jar was zipped magically wrong
it has every file in it doubled up, if you unzip that jar you'll get warning about duplicate files for each file in it

the solution to resolve this ticket will be for sangar to update his ae2 jar with a fixed zip

**Comment by Inari-Whitebear** [comment]
Right, I fixed it for myself at least. Now it complained about not having micdoodlecore, so I downloaded that and chucked it into run/mods/1.7.10 (is that the right folder?). Then the same with immibiscore. Now It wanted Thaumcraft (and a certain minimum version of it)? Am I doing something wrong? xD

**Comment by payonel** [comment]
I'm not sure what it would take to support `./gradlew runClient`. I've personally never run OC in a dev env in that way. @fnuecke, I, and vex use IntelliJ IDEA to run OC, but the setup is a bit tedious so I worked out all the steps needed to get it running:

After running `./gradlew setupDecompWorkspace` and `./gradlew idea`

* 1.7.10
    * From IDEA, open the OpenComputers.ipr created from `./gradlew idea`
    * Open File->Project Structure (or press Shift+Control+Alt+S)
    * In the left pane select Modules
    * Depending on how you imported the project there may be mulitple top level modules. There should only be one. Keep only the one named OpenComputers which has three sub modules named `OpenComputers_api`, `OpenComputers_main`, and `OpenComputers_test`. Right click on the others and choose to delete them.
    * Set separate output paths for `OpenComputers_api` and `OpenComputers_main`. In the middle pane select `OpenComputers_api`, in the right pane select "Paths" and change the "Output path:" from ending in /main to end in /api
    * Set the scope of other minecraft mods in Dependencies "provided". This needs to be done for `OpenComputers_api` as well as `OpenComputers_main`. Select "Dependencies" in the right pane. A large list of dependencies are listed. All, by default due to importing the gradle properties, will default to "Compile". Set all of the following to "Provided"
        - factorization-api.zip
        - ic2classic-api.zip
        - AgriCraft-1.7.10-1.4.0-beta-2.1.7.10-api.jar
        - Gradle: appeng:RotaryCraft:api:V5c
        - Gradle: appeng:appliedenergistics2:dev:rv2-beta-26
        - Gradle: codechicken:EnderStorage:dev:1.7.10-1.4.5.24
        - Gradle: codechicken:WR-CBE:dev:1.7.10-1.4.1.2
        - Gradle: com.bluepowermod:BluePower:deobf:0.2.928
        - Gradle: com.gregoriust.gregtech:gregtech_1.7.10:dev:5.04.06
        - Gradle: igwmod:IGW-Mod-1.7.10:userdev:1.1.3-18
        - Gradle: li.cil.tis3d:TIS-3D:dev:MC1.7.10-1.2.4.70
        - Gradle: mcp.mobius.waila:Waila:dev:1.5.10_1.7.10
        - Gradle: net.industrial-craft:industrialcraft-2:dev:2.2.654-experimental
        - Gradle: net.sengir.forestry:forestry_1.7.10:dev:4.1.0.44
        - Gradle: dev.modwarriors.notenoughkeys:NotEnoughKeys:deobf-dev:1.7.10-2.0.0b4
        - Gradle: qmunity:QmunityLib:deobf:0.1.105
        - Gradle: tmech:TMechworks:deobf:1.7.10-75.0afb56c
        - Gradle: mrtjp:ProjectRed:dev:1.7.10-4.6.2.82
        - Gradle: :buildcraft:dev:7.0.9
        - Gradle: :GalacticraftCoreAll:3.0.7
        - Gradle: :MekanismAll:7.1.2
        - Gradle: :redlogic:59.0.3
        - Gradle: :CoFHLib:[1.7.10]1.0.0RC7-127
        - Gradle: :CoFHCore:[1.7.10]3.0.3B4-302-dev
        - Gradle: :MineFactoryReloaded:[1.7.10]2.8.0RC8-86
        - Gradle: :ComputerCraft:1.73
        - Gradle: :EnderIO:1.7.10-2.2.1.276
        - Gradle: :Railcraft:1.7.10-9.4.0.0
        - Gradle: :BloodMagic:1.3.0a-1
        - Gradle: :ExtraCells:deobf-1.7.10-2.2.73b129
        - Gradle: :ThaumicEnergistics:1.0.0.1-RV2
        - Gradle: api:rf:2
        - Gradle: codechicken:CodeChickenCore:dev:1.7.10-1.0.4.35
        - Gradle: api:mfr:1
        - Gradle: api:railcraft:1
        - Gradle: appeng:mekanism:api:1.7.10-8.0.1.198
        - Gradle: api:ic2:1
        - Gradle: api:betterstorage:1
        - Gradle: api:immibis:1
        - Gradle: api:coloredlightscore:1
        - Gradle: api:craftguide:1
        - Gradle: api:rblocks:1
        - Gradle: api:invtweaks:1
        - Gradle: appeng:Waila:api:1.5.10_1.7.10
        - Gradle: tconstruct:TConstruct:deobf:1.7.10-1.6.0.jenkins528
        - Gradle: codechicken:NotEnoughItems:dev:1.7.10-1.0.4.107
        - Gradle: codechicken:CodeChickenLib:dev:1.7.10-1.1.3.127
        - Gradle: codechicken:ForgeMultipart:dev:1.7.10-1.1.1.324
        - Gradle: mantle:Mantle:deobf:1.7.10-161.45beb09
        * Again, make sure you repeat this process for both `OpenComputers_api` as well as `OpenComputers_main`.
    * Close Project Structure window (press OK), and Select "Minecraft Client" as the run target
    * Build Project (Shift F9)

**Comment by payonel** [comment]
We've decided that we aren't going to build in support to run the mod via `runClient`, but only by using the OC jar in `build/libs/` as a result of `./gradlew build`, or by running the client from IDEA. I will update the readme.md to reflect this and close this ticket at that time.

**Comment by payonel** [comment]
http://ocdoc.cil.li/tutorial:debug_1.7.10

**Comment by payonel** [comment]
front page readme updated with a link to these IDEA instructions
