### ISSUE TITLE
Motion sensors have a blindspot

### ISSUE THREAD

**Issue by TomatoCo** [MightyPirates/OpenComputers#2615]
I upgraded from 1.6.2.7 to 1.7.0.124 on Minecraft 1.10.2. I am using a motion sensor positioned above and inline with two iron doors. On 1.6.2.7 the doors would open when I approached them from either side. On 1.7.0.124, however, the motion sensor does not detect fully half of the area it previously did.

Below is a video demonstrating the blindspot. Notice that, when the doors and filler are removed, the outside-left quadrant of the sensor has a blindspot. When the doors and filler and in place, the entire outside is a blindspot.

https://www.youtube.com/watch?v=1QpJUOlGUDo

**Comment by ebragas** [comment]
I'm having a similar issue in mc 1.11.2 / oc 1.7.0.51 using the motion sensor component in a microcontroller. The blind spots appear to be the front, left, and bottom.

**Comment by payonel** [comment]
@SirWindfield try http://ci.cil.li/job/OpenComputers-MC1.12/48/ for the motion sensor fix for 1.12

**Comment by mainrs** [comment]
Yep, event gets fired :smile: thank you very much!
