### ISSUE TITLE
[1.12.2] Error running the class transformer

### ISSUE THREAD

**Issue by JoeSGT** [MightyPirates/OpenComputers#2616]
Hello when i login to my server it said this
` There were errors running the class transformer. Please report this, together with your (full!) FML latest.log/fml-server-latest.log logfile, thank you!`

so here is my Forge version - 14.23.0.2529
and i am using OpenComputer - MC1.12.1-1.7.0.23 i had tried 1.7.0.20 but still an erorr when i login
to the server
here is the error i found that causing the problem
https://pastebin.com/wAXDrwha

**Comment by thiakil** [comment]
That looks like a Sponge issue

**Comment by JoeSGT** [comment]
so what can i do to fix this?

**Comment by thiakil** [comment]
Try to reproduce it without Sponge, and if you can't, report it to them.

Slightly technical explanation: Sponge is a very invasive coremod and does things that are not normally present in a standard Forge environment.

**Comment by JoeSGT** [comment]
okay thanks it seem to be there issue i will report it thanks
EDIT: i can't reproduce without sponge
so it seem to be there issue

**Comment by SirDavidLudwig** [comment]
@payonel What kinds of problems should I expect to occur with this issue on the class transformer? Everything seems to work fine from what I can tell immediately playing with it, but I don't know if there is something I could be missing.

**Comment by payonel** [comment]
@SirDavidLudwig 
i suppose that depends what class fails to transform :) but if you are seeing this error and you are using our latest dev build, please open a new ticket

**Comment by SirDavidLudwig** [comment]
@payonel It really may just be something on Sponge's end since they're still in beta for 1.12, so I'm not going to worry about it. Thanks
