### ISSUE TITLE
An adapter next to an ME Controller will cause the server to crash on loading the world

### ISSUE THREAD

**Issue by TomatoCo** [MightyPirates/OpenComputers#2618]
This doesn't happen immediately but eventually an adapter next to an ME Controller will cause the world to crash on loading the chunks. The world was recovered by removing OpenComputers, removing all AE2 components adjacent to where the adapter was, then restarting the server with OpenComputers reinstalled. At this point the adapter and cables reappeared (but not the computers themselves...) and they were removed. The world seems healthy from this point on.

Disabling OC compatibility in Applied Energistics did not have any effect.

This was done with OC v 1.7.0.124 and ae2 v rv4-stable-1. Minecraft 1.10.2

Below is the pastebin of the crash.

https://pastebin.com/EfVt6aA4

**Comment by brisingraerowing** [comment]
#2519 has a fix for this. It just needs to be pulled into the repo.

**Comment by payonel** [comment]
fixed in our dev builds, thanks
