### ISSUE TITLE
Update of require

### ISSUE THREAD

**Issue by ToXeye** [MightyPirates/OpenComputers#262]
![the copying fixes the update error](https://cloud.githubusercontent.com/assets/7665417/3050716/f1481ca0-e17e-11e3-8e86-6f88e35397ce.png)

**Comment by ToXeye** [comment]
This is after adding the function hello to the program after having required it once before. So it should be more on the picture such as me doing "require 'f1'" in lua, then exiting and editing the file f1.lua before what happens on picture.

**Comment by Wuerfel21** [comment]
What does hello() contain?
BTW, what the heck is a thread value?

**Comment by ToXeye** [comment]
(note that this entry has been changed a lot of times)

In short, lua 5.2 lets you use thread values like value:resume

I deleted my old post because it contained a lot of information about how bad I am at programming.

I mean, it's POSSIBLE to do it that way, but it's so redundant. I had a coroutine that yields from a for loop, making it possible to express what I wanted to do in a way that didn't involve much thinking. It's one of the latest concepts that I learnt in LUA 5.2 so I took a short route through that and built a very gnomish contraption that abuses concurrency for non-concurrency purposes. It's putting a for loop somewhere, removing the for-properties in it, and then putting a for-loop outside of it. Also, as a generator it is pretty unreliable in comparison to the right way of using standard lua generators. I can also point out to myself that using a generator inside a generator, removing the for-characteristics of a for loop in order to use a next-value inside a for loop... I used a generator to make a generator that does the same thing. The real reason for this is that I forgot that pairs is a generator... If I remembered that hello would look like this:

function hello(table1)
  for k, v in pairs(table1) do
    print(k.." -> "..typeof(v))
  end
end

which is a very standard function.

I really did want to use coroutines for some reason, even though there's nothing concurrent about how they were used.

If we can put that to the side, with your "what the heck is" statement about my code... please consider the actual bug which is about where in the OC code that the require statement fetches information from.

**Comment by ToXeye** [comment]
The reason I posted this was not because I made a programming typo, but that I could not load the file twice because the old file would be kept somewhere in memory the second time you import.

So the real answer to this "problem" would be something along the lines of a bug fix where you can import files, then edit them, then import them again. If it's the same file, the data of the previous version remains somewhere in the loading chain.

Sorry for causing confusion by being less explicit.

**Comment by rmellema** [comment]
The loaded version of the library is cached somewhere to increase loading speed and decrease memory usage. The only downside it has is that if you want to debug a library, you need to keep reloading it. This can be done by writing `package.loaded['module name'] = nil`. So in your case, this would be

```
package.loaded['f1'] = nil
require 'f1'
```

**Comment by ToXeye** [comment]
Nice! Thanks.

**Comment by fnuecke** [comment]
Soo this is solved, yes?
