### ISSUE TITLE
Robot can't place water from bucket

### ISSUE THREAD

**Issue by xenoxsis** [MightyPirates/OpenComputers#2622]
I am trying to create a simple farm robot, that should first dig a center hole, fill the hole with water using a bucking and hoe the ground. So I dig the hole and the robot hovers over the hole. Then I equip the bucket and useDown() - Though it says "Item placed" nothing happens. I have tried all combinations of use, place and such. Robot in the hole, above the hole, and one extra above the hole. It just doesn't work.

![1](https://user-images.githubusercontent.com/4257863/32689602-1678b3de-c6e8-11e7-9892-ebd5c4c06d39.png)
![2](https://user-images.githubusercontent.com/4257863/32689600-1642a672-c6e8-11e7-8acd-211a6707afdf.png)
![3](https://user-images.githubusercontent.com/4257863/32689601-165f6cf8-c6e8-11e7-9460-d3fb375238d3.png)

**Comment by payonel** [comment]
what oc version?

**Comment by xenoxsis** [comment]
OpenOS 1.6.1 (You can see it in the prompt on the last two pics as well)

**Comment by xenoxsis** [comment]
OpenComputers-MC1.10.2-1.6.2.7

**Comment by payonel** [comment]
confirmed broken in 1.6.2.7
fixed in latest dev builds, 1.7.2 will be the next official build you should use
