### ISSUE TITLE
WebRTC support

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#2623]
Would it be possible to have WebRTC?

**Comment by LizzyTrickster** [comment]
I fail to see how this can not already be achieved through pre-existing 
tools?

**Comment by SoniEx2** [comment]
You can do HTTP(S) and raw TCP, but not WebRTC.

Until I can use WebTorrents, we don't have WebRTC.

(Gosh I'd love to be able to download scripts over webtorrent!)

**Comment by payonel** [comment]
webrtc is typically supported in browsers. the OC networking/modem support does not plan to add application level protocols. the http(s) support that was added was for convenience, but that's all we plan to do. if you find a simple command line tool that speaks webrtc and would like to port that to OC using lua, that would be a good oppm project.

**Comment by SoniEx2** [comment]
Well then can we get TCP server support?

**Comment by payonel** [comment]
1. don't ask for new features on a closed ticket
2. are you asking for bind() access? we're not giving that. if you want bind access, write a program that runs on the host, outside of minecraft, accepts connections from your in-game "server", and proxies the binding (if you have question about this, use irc, not this feature please)
