### ISSUE TITLE
Drone duplicates Wither skulls

### ISSUE THREAD

**Issue by TomatoCo** [MightyPirates/OpenComputers#2624]
I have a wither farm that uses a drone to place the soul sand and heads. To get the blocks to the drone I place them with an Actually Additions (v r105) auto-placer. Every time I see the drone break a skull, I see its inventory increase by two.

I am using OC v 1.7.0.124 on MC v 1.10.2.

**Comment by payonel** [comment]
why is the drone breaking the skull in the first place? just curious

**Comment by TomatoCo** [comment]
It's a tier 1 drone so it has a solar panel and an inventory. I didn't want to set up charging or anything that'd insert the items into it.

**Comment by payonel** [comment]
but why do you need to break any skulls? aren't you just placing them and letting the boss spawn?

**Comment by TomatoCo** [comment]
Couldn't figure out a way to put the placers where I needed them and not have them destroyed when the big man spawned, so it places them for the drone to pick up and safely fly into the wither containment vessel.

I recognize there's better ways to do it but, god damn it, this is how I figured it out.

**Comment by payonel** [comment]
ah i understand, ok cool
so the repro doesn't need a boss at all (finding minimum repro is important!)
it's just when the drone breaks a skull?
does anything else dup with drone break?
does it duplicate if YOU placed the skull?
thanks

**Comment by TomatoCo** [comment]
Nope. Players can break the skull without duplicating and the drone doesn't duplicate the soul sand when it breaks that. Let me test what happens if the skull is placed by a player... Sorry, I responded before totally parsing all your questions.

Update: I can confirm it duplicates with hand-placed wither skulls as well. It's also not just wither skulls. creeper heads and zombie heads do it as well.

**Comment by xarses** [comment]
@TomatoCo you can reproduce the dupe w/o using OC? Can you please provide very specific steps here?

**Comment by payonel** [comment]
confirmed:
no repro in 1.7.10
repro in 1.10
repro with robots too (not just drones)
repro with wither skulls, skeleton skulls, zombies heads, creeper heads, and dragon heads
