### ISSUE TITLE
Something - anything, even a proprietary protocol - that can receive connections

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#2625]
Can we get a thing to receive connections? Proprietary, TCP, UDP, I don't care, just give me *something*.

Make it so I need to connect to OC as if OC is a VPN, and then I can access the computers in the world, that'd be ok with me. Just give me SOMETHING. Even if "OCTorrent" doesn't have access to normal torrent or webtorrent, it's still alright for sharing scripts.

**Comment by payonel** [comment]
Sorry, no -- we don't plan to add the ability to accept connections. If you want this you'll need to run a proxy-relay on the host machine

This proxy-relay running on the host can bind() outside conenctions, but the connection from your service in-game is given "in charge" status, and you communicate all other connections to your "in charge" service, somewhat like a reverse proxy

**Comment by magik6k** [comment]
There is `ip` package on mpt which implements ipv4/icmp/udp/can support tcp - http://mpt.magik6k.net/api/file/ip/lib/ip.lua, and also a more mature version for plan9k at https://github.com/OpenPrograms/Plan9k/tree/master/plan9k-ip. You can implement stateful protocols such as TCP on top of that relatively easily.

**Comment by payonel** [comment]
I forgot about that project. That is cool, but - a key thing soni is asking for is the option to accept out of game connections.

**Comment by SoniEx2** [comment]
I'm asking for OC, the mod, to accept out of game connections.

Not computers themselves.

OC would then provide some sort of VPN/tunnel that bridges the internet and the server's OC network.

It's called "fakebind" (as opposed to "bind") for a reason. It can also require tier 3 internet cards or something.

**Comment by payonel** [comment]
I understand that, but we don't plan to provide that.

**Comment by purplemonday** [comment]
Forgive my spelling im on the most crappy acient laptop that makes typing a real pain.

Outgoing http is all you need.
incoming gets quite complicated with the server needing to keep connections alive and dropping packages when you start loading it.

Ill not name the other game ive seen this happen.  but X server can only deal with X connections and will start lagging/dropping packets/players when you start hammering it

Your going to need somesort of timing/loadspreadig annyways.
youll need to have some sort of wrapper to a other (http) server that acts like a central database
say a webserver running php/mysql, or something similar on your own desktop.

and just call it piriodicaly retriving messages that where left behind by other computers

advantages are that the central server isnt limited and do some/alot of the processing without loading MC
disadvantage is that this is quite delayed. 

If you dont have a php/mysql toss me a PM and we will look if we can host you a similiar script somewhere.

**Comment by skyem123** [comment]
Hmm... Theoretically, wouldn't it be possible to just use TCP based NAT traversal methods if they exist?

**Comment by SoniEx2** [comment]
That doesn't work. The 3-way handshake would fail.

**Comment by skyem123** [comment]
https://en.wikipedia.org/wiki/TCP_hole_punching

**Comment by skyem123** [comment]
I actually think NAT traversal methods would be a good compromise here.

**Comment by SoniEx2** [comment]
That implies I can predict the next port.

**Comment by skyem123** [comment]
I wonder if it'd be reasonable to add NAT traversal to OC itself as a compromise
