### ISSUE TITLE
Continuation of #2623

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#2626]
Continuation of #2623

1. that's BS. you throw ideas out too fast.
2. well give me something else then.

(also please start treating me the same way you treat everyone else, it's not fair >.>)

**Comment by payonel** [comment]
is this different than #2625 ?

**Comment by payonel** [comment]
anyways, like i've said. Implement a real program on the host that accepts connections, and communicates the intent to connect to your in-game process. we won't be providing oc->internet->oc access

**Comment by skyem123** [comment]
I will quickly note that WebRTC isn't about hosting, though it kinda needs support to listen to sockets on the client (though that can be hidden and abstracted).
However there probably isn't much use for it, because no audio or video support is possible.
What might be possible is the data channel, but still it's not useful. WebRTC also has a lot of potential security issues...
So while possible for a limited implementation for a limited use... It's impractical and time better spent elsewhere.

**Comment by SoniEx2** [comment]
Ever heard of webtorrent? That uses data channel. Can be used to torrent scripts.

**Comment by skyem123** [comment]
I have a feeling that there are server owners that would freak out at the mere mention of the word "torrent".

**Comment by purplemonday** [comment]
oc > internet > webserver with database
store and retrieve messages from that database

its hell slow, 2k limmit but it would work over dim etc

if you dont have such a webserver toss me a pm and ill look into hosting a lil php script somewhere

**Comment by SoniEx2** [comment]
Isn't that just called centralization?

**Comment by Darinth** [comment]
While I will agree that there is use for this, the use is very limited and probably a little more dangerous than what I think the vast majority of server owners are comfortable with. I'm a little surprised that the internet card is enabled at all by default. Allowing incoming connections just sets up red flags. So... even if this did get implemented I'd have to recommend it being disabled by default. Given that if you really want this functionality, nothing is stopping you from doing it via a proxy anyways... I'd rather see development time go pretty much anywhere else. Really, the only thing that I support using the existing internet card for is downloading programs I've written in an external editor. To that note... I need to remember to modify the config to limit the websites OC has access to...

**Comment by SoniEx2** [comment]
Why not support peer-to-peer script sharing?

**Comment by payonel** [comment]
because we will not add to OC the ability to accept connections

**Comment by SoniEx2** [comment]
Why not?

**Comment by SoniEx2** [comment]
Trivial TCP Tunneling Protocol (TTTP):

Open a TCP connection to `<server address>:<OC port>`. `server addresses` is a config option which lists DNS and IP values for accessing the server (not to be confused with `bind address`, a separate config for which specific IP address OC will use).  `OC port` is a config option which defines the public TCP port for OC.

Then send the 4-byte sequence representing the IPv4 address of the computer in the `10.159.12.0/22` (bit pattern: `00001010 1001111 1000011 0000000000`) address range (this gives roughly 1020 OC computers that can accept internet connections), and a 2-byte port number.

You now have a TCP connection to the given OC computer - assuming OC doesn't deliberately reset the connection (because the computer is down, there's nothing on the given port, or something like that).

API-wise, there should be `getServerAddresses()`, `getPort()` and some sort of `fakebind()`, preferably neatly wrapped in a luvit-like API.

**Comment by xarses** [comment]
This seems quite far beyond the scope of the mod. You get lua to automate minecraft, no a generic code-execution platform to make bit-torrent bot-nets from. For this capability to be a core, and/or enabled component in the mod, your asking for sever operators to allow for arbitrary code execution with full network access. This would be non-starter for not only most server operators, and could even result in the mod being banned from some MC hosting networks. So no, it won't be up for it being added to OpenComputers either. The current internet access level is a compromise that trades off being able to access software distribution methods to ease getting code into the system and while your more than welcome to be creative getting it out, it really isn't intended for you to be able to. You are more than welcome to make a companion mod that has this functionality.

**Comment by SoniEx2** [comment]
It's not full network access. It's barely full TCP access. It still requires everything to go through a single external IP and port, as if it's just the OC mod running a TCP service.

**Comment by payonel** [comment]
soni: honestly, whether you agree with my reasoning or not, i'm not adding any way for remote connections to be accepted
