### ISSUE TITLE
Distributed, peer-to-peer OPPM

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#2627]
Make OPPM peer-to-peer for once.

Why do you make everything so centralized.

**Comment by payonel** [comment]
I actually definitely agree with this :)
oppm should allow custom repos, even in-game hosts over the modem component :) ala command line args perhaps

**Comment by SoniEx2** [comment]
Also globally distributed. Similar to torrents and dat and stuff.

**Comment by payonel** [comment]
globally distributed? no - that'd be an entirely different system/service you are asking for. let's keep this ticket to your original ask

**Comment by SoniEx2** [comment]
Yes, my original ask was distributed-over-the-internet. Let's keep this ticket to my original ask.

**Comment by payonel** [comment]
actually, I think we might be saying something different. peer-to-peer to us in in-game only. There is not a method to provide over the internet peer-to-peer as we do not provide bind() to run a service

**Comment by Vexatos** [comment]
oppm uses github, that's just what it is - a specialized github interface. If I changed it to use anything other than github it wouldn't be oppm anymore.

**Comment by SoniEx2** [comment]
You don't need full bind, you just need a way to address OC computers over the internet. This could be a service provided by OC itself, which then dynamically selects which OC computer to address based on the contents sent to it. But I've always been talking about a globally peer-to-peer OC package manager.

**Comment by Vexatos** [comment]
If you want to access computers via something like websockets, feel free to write something. That's outside the scope of OPPM.

**Comment by SoniEx2** [comment]
Is it too hard to make every MC server also an "OC server"?

Hmm... How hard would it be to use the MC server protocol to remote-connect to arbitrary OC computers... Would need a "tracker" mechanism and a bunch of disposable MC accounts, but is the only way to do it...

Well I have a job now, so I can buy some disposable accounts...

**Comment by Vexatos** [comment]
It is not hard at all - as I said, you are free to implement it. OPPM is specifically using github, though.
