### ISSUE TITLE
Questions? Updating 1.6.8 OpenOS to 1.7 

### ISSUE THREAD

**Issue by saintpool** [MightyPirates/OpenComputers#2628]
I currently play on the technic, The 1.7.10 Pack single player mode, So I try to update my Open Computers mod loading the correct version everything is working but when I ; install OpenOS ingame it only give's me the 1.6.8 version. What am I doing wrong? thanks for the help, love the mod!

**Comment by xarses** [comment]
That is correct that is the OpenOS [version string](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/openos/lib/core/boot.lua#L4)

**Comment by saintpool** [comment]
Thank you for the help! I will go back and look at my programs on OpenOS coding must be wrong then. thanks again 
V/r
St. P

**Comment by payonel** [comment]
When we released 1.7 the 1.6.8 version string in openos was one of the first things I thought of. Woops :)
I should just update openos version string 1.7 now even though it'd be a dev build and not our latest release build.

**Comment by payonel** [comment]
a9c4529372c3ea9654b985521a59a39cdc656ba7
