### ISSUE TITLE
Blocks not analyzable

### ISSUE THREAD

**Issue by ToXeye** [MightyPirates/OpenComputers#263]
I can't use the analyzer on blocks like the adapter or noteblocks.

**Comment by Wuerfel21** [comment]
Have you placed an adapter next to an noteblock and used it on the adapter?

**Comment by Wuerfel21** [comment]
And have you installed OpenComponents?
You need it to use the adapter. You will find it when you go to the mightypirate page: https://github.com/MightyPirates 
Sorry for double posting, my smartphone dont likes editing stuff.

**Comment by ToXeye** [comment]
OpenComponents does not fix the problem. Computers and similar blocks work. Not the adapter or noteblock. (edit - opencomponents was necessary to fix the problem altogether)

**Comment by ToXeye** [comment]
Now it works. I didn't follow all the instructions at once but rather : I kept pressing for small changes. So what I did was to put a noteblock next to the adapter as you said, after installing opencomponents. The first thing is : don't just use an adapter on its own. Right... Eventually the problem was fixed...

(Edit) sorry for not reading up on the forum page
I have a habit of not making sure I read everything. For example, opencomponents was hidden and didn't seem that important. A warning in the middle of the first bits of text might clear that up. Other than saying "this is necessary" you can say "some functions require this!"

**Comment by fnuecke** [comment]
Where exactly do you mean? At least the wiki (where the methods are documented) is very explicit about OpenComponents being required.

**Comment by Wuerfel21** [comment]
He did only read a small piece of the forum post.
So this is a lesson to all the people out there in this interweb i crafted 10 mins ago: ALWAYS READ THE ENTIRE FORUM POST! Sorry for the capital letters.

**Comment by fnuecke** [comment]
Right. Was just wondering if it was maybe mentioned incorrectly somewhere, since note blocks were originally supported directly, after all. Might well be possible I forgot to update that somewhere. If that's the case let me know, otherwise I don't really know how to better format the MCF post, or I would have.
