### ISSUE TITLE
Pathing/Tier 2 navigation

### ISSUE THREAD

**Issue by Darinth** [MightyPirates/OpenComputers#2630]
Any chance of a tier 2 navigation card that could allow drones to path to a designated location? Would more or less just invoke minecraft's existing AI pathing. Unsure of how well minecraft's pathing is for flying entities, but if necessary I'd be perfectly happy with walking drones that possess more advanced pathing capabilities.

**Comment by Vexatos** [comment]
You can write pathing algorithms in Lua yourself, using things like the geolyzer or camera.

**Comment by Darinth** [comment]
Unless I've missed something, unfortunately, neither drones nor robots can have onboard geolyzers. Nor can they communicate with them directly. This places extensive limits on where such drones can physically go and still be able to path.

While I appreciate the camera option in computronics, I'm playing on a server and do not have access to such. Having some method of pathing around in an open environment would be appreciated. Out of curiosity, is the robot camera upgrade in computronics able to be applied to drones?

**Comment by payonel** [comment]
drones and robots CAN use the geolyzer, just add the geolyzer when assembling them

**Comment by Darinth** [comment]
Well I'll be damned. My apologies @payonel.
