### ISSUE TITLE
can't place drone (crashes both server or client)

### ISSUE THREAD

**Issue by Tcll** [MightyPirates/OpenComputers#2637]
[crash-2017-11-18_20.58.56-server.txt](https://github.com/MightyPirates/OpenComputers/files/1485593/crash-2017-11-18_20.58.56-server.txt)

That's the latest crash log from my server, is this OC, or is another mod making an incompatible patch somewhere??

**Comment by payonel** [comment]
This does not reproduce for me. If you can provide more detailed steps to reproduce and if you can find necessary conditions for it to reproduce that would help.

**Comment by Tcll** [comment]
hmm, that tells me it might be my configs, or perhaps something with
minetweaker??

will you work with me to narrow it down, you know more about the src than I
do, and might help me come to a better conclusion.

so far I assume you've basically built my pack with no mt3 scripts and
default configs, and everything worked as expected...

another thing could be my forge version could be outdated...
but that's all I can come to...
I'll send you my configs if the defaults work.
but if it's forge, well...

either way I'll report back ;)

**Comment by payonel** [comment]
No I test with OC by it self, else this is a compatibility bug. You might have to duplicate your minecraft instance and make a test world and test your mods and configs in a binary-search approach to find the offending setting
