### ISSUE TITLE
Cannot load OS: no bootable medium found: /init.lua

### ISSUE THREAD

**Issue by leomil72** [MightyPirates/OpenComputers#2638]
I just downloaded OC 1.7.0.20 and installed through MC Mod Installer on MC 1.12.1.
I assembled a tier 1 computer with Lua BIOS EEPROM , placed a floppy drive near it, inserted the OpenOS disk, nut every time I power it on, I get 2 beeps then the message: "Unrecoverable Error no bootable medium found: /init.lua". But the floppy disk drive is just close to the computer case and the floppy is in the tray.
It just seems that the floppy doesn't contain the correct files to boot the OS but I'm pretty sure that it is the right floppy (it's the green one, named "OpenOS"). I've also used the EEPROM with the Lua BIOS and set everything correctly. Can someone tell me what's wrong? I've tried both on a Mac machine and a Linux box and I got the same error.
Thank you
Leo

**Comment by payonel** [comment]
Note that the "No bootable medium found" error is actually thrown by the "lua eeprom", so you should feel confident you have the right eeprom.

For some reason the disk drive and the openos floppy in its slot is not being detected by the computer. A face of the disk drive and a face of the computer case should be touch. Can you take a screen shot of your configuration?

**Comment by leomil72** [comment]
![2017-11-20_22 28 30](https://user-images.githubusercontent.com/1081865/33042477-449364d8-ce42-11e7-8248-c4ad69488841.png)
I have the EEPROM Lua BIOS. As you can see, the floppy drive is face to face with the computer case, the OpenOS disk is into the tray and the computer is looking for the /init.ua file that seems not to exist on that floppy. Thanks for the attention.

**Comment by purplemonday** [comment]
Note 
some guy playing direwolf20 had this same thing happening
#2476

might this be the same bug?

**Comment by payonel** [comment]
@purplemonday probably not related, loading disk drive floppies is quite different than how hdd's save+load from nbt data

**Comment by payonel** [comment]
this does not repro for me, try isolating the problem please
these are just some ideas of things to try:

Try the following tests
- only OC and no other mod
- creative mode
- a newly crafted machine and disk drive
- single player
- multiple player

**Comment by leomil72** [comment]
Before to open this issue I made several tests with this mod.
First of all, I must tell that I'm playing Minecraft started by Shiginima 3.1. I've tried OC mod on my Mac and both on my Linux box: both use Shiginima. The first time I launched the mod I used OC with Industrial Craft but I wasn't able to connect any of the Industrial Crafts power sources nor any of the power pipes of the mod. Simply,  the pipes didn't create the connection. The only power source that worked was che coal generator from Actually Additions. WIthout this mod, I was only able to try to power up a computer by modifying the configuration file of OC to set the mod  to ignore the check for a power source.
I tried using the components taken in Creative mode and they didn't work. I tried components like the EEPROM or the floppy disk crafted by myself but nothing changed.

I could think that there is a connecting problem: it seems that the item blocks aren't able to connect with other items placed close to them. In fact, the power pipes from Industrial Craft didn't connect to the computer, and the power generators from Industrial Craft placed face to face didn't power the computer. And now the computer that seems unable to find the disk drive that is placed face to face to it.

**Comment by payonel** [comment]
We won't support cracked versions of mc, Expect various differences in the way mods interact with forge and how that interacts with the real vanilla mc runtime

**Comment by tolis5162** [comment]
I have the same problem with all kind of computers in this mod and i am in version 1.12.2 .Please fix that bug or whatever it is.

**Comment by skyem123** [comment]
It might be better to open a new issue with a full description of what's happening with details such as minecraft version, mod version, and other mods installed.

**Comment by 4etvGaming** [comment]
Hi so I had the same problem so I did some testing and the floppy disk you need to use is the Plan9k

**Comment by 4etvGaming** [comment]
and it shoud work
