### ISSUE TITLE
OpenOS motd unicode.char using utf-16be codes

### ISSUE THREAD

**Issue by grandmaster8** [MightyPirates/OpenComputers#2640]
in docks it is written that unicode.char works with utf 8

**Comment by payonel** [comment]
unicode.char takes a unicode value and returns a utf8 string
motd is using [0x2552](http://www.unicodemap.org/details/0x2552/index.html), [0x2550](http://www.unicodemap.org/details/0x2550/index.html), [0x2555](http://www.unicodemap.org/details/0x2555/index.html), [0x2502](http://www.unicodemap.org/details/0x2502/index.html), [0x2514](http://www.unicodemap.org/details/0x2514/index.html), [0x2500](http://www.unicodemap.org/details/0x2500/index.html), [0x2518](http://www.unicodemap.org/details/0x2518/index.html)

I don't see a mistake here. Could you explain what I'm missing?

**Comment by Avaja** [comment]
"UTF-8 aware version of string.char. The values may be in the full UTF-8 range, not just ASCII."

The question is what is written in the range utf 8, but these codes refer to utf 16.

https://unicode-table.com/en/2552/

**Comment by Avaja** [comment]
You want to say that unicode.char gets any unicode format code and converts it to utf 8?

**Comment by grandmaster8** [comment]
You want to say that unicode.char gets any unicode format code and converts it to utf 8?

**Comment by skyem123** [comment]
It takes a codepoint number and converts it to a UTF-8 string that represents that codepoint.
That codepoint number is sort of UTF-32, but it isn't really that, because it's a number, not a string.

**Comment by payonel** [comment]
this doesn't appear to be a bug. if you have further questions about unicode codepoints, feel free to ask for clarification on our irc channel, #oc on esper.net

**Comment by skyem123** [comment]
it's #oc :P

**Comment by payonel** [comment]
#oc ...
