### ISSUE TITLE
[BUG] [1.7.10] Microcontroller dupe

### ISSUE THREAD

**Issue by anar4732** [MightyPirates/OpenComputers#2641]
1. Assamble a microcontroller
2. Place microcontroller and connect ender IO item conduit
3. Set item conduit to always active
4. endless amounts component

https://i.hizliresim.com/LOXjXG.png
https://i.hizliresim.com/rJaGaN.png

**Comment by payonel** [comment]
ha!
interesting. but apparently just the sign i/o upgrade

**Comment by payonel** [comment]
confirmed repro
the item conduit needs to be extracting from the uC, and inserting into the other inventory
and the extract doesn't need to be always active, but rather just active (it can be always active, or active with redstone signal and activate thusly, etc)

**Comment by payonel** [comment]
ah nope, the item conduit pushes just the first component sees. the sign io upgrade is the first component with the creative uC, but if i craft my own, the tier 1 cpu is the first.

**Comment by payonel** [comment]
hoppers don't do it, neither do translocators. enderio item conduits are special

**Comment by payonel** [comment]
robots and drones don't do this. and pulling from computer cases remove the components. it seems the uC is reluctant to remove the item from its inventory, but is okay with enderio duplicating them
