### ISSUE TITLE
[Suggestion] New argument for "resolution" program

### ISSUE THREAD

**Issue by UV-Husky** [MightyPirates/OpenComputers#2642]
Hi, would it be feasible to add a "default" argument to the "Resolution" program? then you could write "resolution default" and it would reset the screen resolution to the maximum supported.
I have actually done it manually for one of my computers but it would be handy to have it "out of the box"

```lua
if args[1] == "default" then 
  local w_max, h_max = gpu.maxResolution()
  gpu.setResolution(w_max, h_max)
  return 1
end
```
A

dding this between the `if(#args==1) ` and `if(#args~=2)` works.
And then edit the usage helper accordingly.

example [resolution.txt](https://github.com/MightyPirates/OpenComputers/files/1501799/resolution.txt)
change it from .txt to .lua and replase the original.

**Comment by payonel** [comment]
or what about a `reset` command?

**Comment by UV-Husky** [comment]
That's actually even better.

**Comment by Nex4rius** [comment]
What about just calling it without any arguments and it resets the resolution?

**Comment by UV-Husky** [comment]
Because writing it without arguments prints the current resolution then that would have to be changed.

**Comment by skyem123** [comment]
Would it be possible to somehow get/encode different tiers of resolution so one could do `resolution t2`?
Or maybe a way to name custom resolutions and save them... Not sure if implementing that would be a waste of time or not?
