### ISSUE TITLE
Drones with a Chunkloader Upgrade don't load chunks beyond activation

### ISSUE THREAD

**Issue by TheCodex6824** [MightyPirates/OpenComputers#2643]
MC Version: 1.12.2
OC Version: 1.7.0.30
Forge Version: 14.23.0.2552

Using just OpenComputers on a singleplayer world, drones seem to get unloaded when moving between chunks, even though they got a chunkloader ticket (setActive returns true). They remain loaded and working when they are still or moving around in the same chunk, however.

Steps to reproduce:
1. Make a drone with a chunkloader upgrade, give it a program to make it travel outside its starting chunk
2. Start it and teleport away so it would be unloaded without a chunkloader
3. The drone will be unloaded upon leaving the chunk, I used the "/forge entity list" command to verify this
3.5 Go back to where you teleported from, see that the drone barely moved, but is otherwise fine

I couldn't see anything noteworthy in the logs (but can upload them if requested). I also have a minimal test world if that would help.

**Comment by TheCodex6824** [comment]
So I was able to figure this one out:

- Other than when the chunkloader firsts loads or is activated, the only time the chunkloader is updated [is when a RobotMoveEvent occurs](https://github.com/MightyPirates/OpenComputers/blob/43a4db05ecc12356070aaf5e0260d8a120783ba4/src/main/scala/li/cil/oc/common/event/ChunkloaderUpgradeHandler.scala#L64)
- But unlike robots, drones do not fire those events, meaning the chunkloader never gets to load new chunks beyond the first time it activates. If its moving, it then can fly into an unloaded chunk.

On both my test world and the server where I noticed it first, it works perfectly after allowing drones to update their chunkloaders in [the chunkloader's update method](https://github.com/MightyPirates/OpenComputers/blob/43a4db05ecc12356070aaf5e0260d8a120783ba4/src/main/scala/li/cil/oc/server/component/UpgradeChunkloader.scala#L43-L53).

~~I can submit a PR if you're interested.~~

I submitted it, let me know if there's any issues / you don't want it.

**Comment by payonel** [comment]
wow, thank you so much! you saved me a ton of time working this out for us :) I'll merge the PR soon

**Comment by Kiritow** [comment]
I'm sorry but this bug seems happened again. I am playing OC 1.7.1.150 on Minecraft 1.10.2.

**Comment by TheCodex6824** [comment]
I just tried it out on the latest dev build and it seems to work for me. Some questions for you:
- What is returned by the chunkloader's isActive component method?
- Do you have a lot of other chunks loaded at the same time?
- Is this singleplayer or on a server?

**Comment by Kiritow** [comment]
1. `component.proxy(component.list("chunkloader")()).isActive()` returns `true`.
2. I have no idea about that. But I think no.
3. Server.

**Comment by TheCodex6824** [comment]
When exactly does the drone seem to stop working? Also, if you happen to have access to admin commands, run `/testfor @e[type=OpenComputers.Drone]` and see if it finds anything (which would mean its loaded)

Singleplayer worked for me, currently sending a drone on an expedition on a test server

**Comment by Kiritow** [comment]
I tried again on my server and find out that: 
The drone can **keep** the chunk loaded with upgrade, but it can't **change** the chunk to loaded by itself. When I type `drone.move(0,0,300)` , the drone start moving and get frozen after a moment. If a player reach the chunk it is, then the drone will keep moving. After that even if players get out of that chunk, the drone will never freeze.

The testfor command returns `Found Drone`. But drone does not respond to any request.

The interesting thing is that commands seemed to be queued. When the drone is "activated" again, all commands return successfully.

**Comment by TheCodex6824** [comment]
If testfor says `Found Drone`, then that means that it is in a loaded chunk. So it seems like the chunk is loaded, but the entity isn't being processed? Before I go investigate that (probably not so fun to debug) route, can you post the program you're using?

**Comment by Kiritow** [comment]
This is the program in eeprom of drone. Edit from a example code from gist.
```
local m=component.proxy(component.list("tunnel")())
local function respond(...)
  local args=table.pack(...)
  pcall(function() m.send(table.unpack(args)) end)
end
local function receive()
  while true do
    local evt,_,_,_,_,cmd=computer.pullSignal()
    if evt=="modem_message" then return load(cmd) end
  end
end
while true do
  local result,reason=pcall(function()
    local result,reason=receive()
    if not result then return respond(reason) end
    respond(result())
  end)
  if not result then respond(reason) end
end
```
And I use Lua on a computer to control it.

**Comment by TheCodex6824** [comment]
I just tried that on both singleplayer and a server again, and both times it worked perfectly, both sending and receiving data. Other than checking in the logs for anything weird, maybe try the same program in singleplayer with the exact versions I used:
OC: 17.1.157 (your version was not on the build server anymore)
Forge: 1.10.2-12.18.3.2511

**Comment by Kiritow** [comment]
I had a test with OpenComputers 1.7.1.157 in Minecraft 1.10.2 with forge 1.10.2-12.18.3.2185 in SinglePlayer mode. And everything is ok.
And test pass with 1.7.1.150 in MC 1.10.2 with forge 1.10.2-12.18.3.2185 in Single Player mode.

**Comment by TheCodex6824** [comment]
You never mentioned the forge version you were using on the server, but if you can try updating the server's version of forge.

**Comment by Kiritow** [comment]
Sorry, the OC on Server is 1.7.1.150 and Forge is 12.18.3.2215.
I will try updating it tomorrow. 
But I think it is the other plugins on server cause this.

**Comment by TheCodex6824** [comment]
What are the other plugins you have? I probably should have asked that first, oops.

**Comment by Kiritow** [comment]
Sponge, Railcraft, IC2, OpenComputers, InfernalMobs, TConstruct
CodeChickenLib, StatusProtocol, ServerListPlus, ProjectPortals, WorldEdit, twentyticks, Nucleus, ProjectWorlds, TitleMOTD, PermissionManager, Inspector, Stackban, Keys

**Comment by TheCodex6824** [comment]
Yeah I feel really bad now for not asking at first, Sponge changes everything. I'll look into it but to be honest I'm not terribly familiar with Sponge stuff.

**Comment by TheCodex6824** [comment]
So I poked around at this a little bit more, and found some stuff that could be the cause of it (in the mod, don't think sponge is an issue at this point). So follow up question time:
- Does it happen with robots?
- Does it happen only after the server is restarted?

Either way, I fixed some issues with reclaiming chunkloader tickets in drones, so maybe [try this build I made](https://www.dropbox.com/s/46gdzhfk0rh788z/OpenComputers-MC1.10.2-1.7.1%2Bedb49584b.jar?dl=1), or compile my 1.10-drone-chunkloaders branch if you would prefer doing it yourself. If the above questions fit the issues you are having, this will fix it.

**Comment by Kiritow** [comment]
1. Seems no. I write a program in robot which will send its address using debug card once move forward. And it works well. The robot reaches there, too.
2. No. It always happens.

**Comment by TheCodex6824** [comment]
If you can and are ok running a dev build, try [this build](https://www.dropbox.com/s/46gdzhfk0rh788z/OpenComputers-MC1.10.2-1.7.1%2Bedb49584b.jar?dl=1), or compile from my fork if you prefer. If it fixes it great, if not please upload your latest.log file. You may need to manually restart the drone one more time.

**Comment by TheCodex6824** [comment]
I'm going to assume that I fixed it as I tested everything again, even in sponge, and everything works as it should. If the bug I fixed isn't what's giving you issues then I'll take a look again.

**Comment by Kiritow** [comment]
Sorry for the delay but I have no access to server now. I can't test the build on the server but I have tested it in single player mode (pass). I will test it as soon as I have access later. (maybe a few days...)

**Comment by TheCodex6824** [comment]
That's ok. I just wanted to PR what I have because even if it isn't *your* bug, its *a* bug that can probably mess people up.
