### ISSUE TITLE
error message is lying / crash too early

### ISSUE THREAD

**Issue by Nex4rius** [MightyPirates/OpenComputers#2644]
<img src="https://imgur.com/kuAxfdf.png" />
<img src="https://imgur.com/BnruRs9.png" />
OpenOS 1.7.0

**Comment by payonel** [comment]
Honestly I'm surprised you got to 8191 :) The size includes any packing metadata or serialization info that is needed to pack the signal. We are correctly using `>` as a check. This size limit is not a guarantee of chars you can send.
