### ISSUE TITLE
Multi-CPU servers

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#2646]
Let's put 4 CPUs in a server and get 4x the processing power.

**Comment by payonel** [comment]
The solution to this is to change the thresholds in the `config/opencomputers/settings.conf`. We're not going to increase the current memory nor cpu allowances

**Comment by SoniEx2** [comment]
I thought servers already had more than 2 memory slots?

**Comment by payonel** [comment]
I didn't say they didn't, I said we're not going to increase them

**Comment by SoniEx2** [comment]
Give us more than one server CPU slot.

**Comment by payonel** [comment]
thanks for the suggestion, but things are good how they are.
