### ISSUE TITLE
injectEnvironmentImplementation should remove @Optional annotations

### ISSUE THREAD

**Issue by josephcsible** [MightyPirates/OpenComputers#2649]
When [injectEnvironmentImplementation](https://github.com/MightyPirates/OpenComputers/blob/06e7149573cc310254b691b3944eeb5d99619ff8/src/main/scala/li/cil/oc/common/asm/ClassTransformer.scala#L268) makes its changes to a class implementing SimpleComponent, it should remove any @Optional annotations for the interface itself as well as for its methods, to ensure that Forge doesn't strip them but leave our injections. See McJty/RFTools#1466 for details as to why.

**Comment by payonel** [comment]
I dont know what it takes to implement this, to be honest. So I'll leave it open for adoption if someone can help me out with this.

**Comment by josephcsible** [comment]
Okay, my first approach failed. Forge looks at the @Optional annotations before our transformer runs, so just removing them then doesn't work.

**Comment by payonel** [comment]
thank you @josephcsible

**Comment by josephcsible** [comment]
Can we do a new release of OC so that players can easily have this fix? We've had 4 bug reports and a Reddit crash report about this, and there's nothing that can be done about it from our (RFTools') end.

**Comment by Vexatos** [comment]
There was a release about ten minutes ago. I am uploading it right now.
