### ISSUE TITLE
OC isnt on the first google result page

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#265]
Tried googleing ¨minecraft computer mod¨ and no OC on the first page!(A math.huge drama)
Some ideas how to fix this issue?

**Comment by LordFokas** [comment]
White-hat SEO.

**Comment by Wuerfel21** [comment]
Maybe we should have more keywords in the forum post(not shure if google searches spoilers, if not things could get ugly with this)

Also suggesting OC to modpack-maker-guys, this would be a win-win-thing, cause !. people play it in modpacks + 2. People write about it(even stupid issues like ¨wht am i doin wrng dnt wrks ur mod suks¨ can help)

**Comment by LordFokas** [comment]
You can't really fool google. There is way-better-than-average artificial intelligence involved in determining how relevant certain keywords are in certain pages.

The best way to actually make it achieve a better place without later being blacklisted by Google would be letting it grow naturally by creating actual relevant content.

**Comment by Wuerfel21** [comment]
Some pretty good content is in the work!

**Comment by fnuecke** [comment]
Heh, I think discussions like this should go onto the forums ;-)
But yeah, I'm happy for people spreading the word, so please do. I'm just not a PR person myself.
