### ISSUE TITLE
Timers do not work in threads

### ISSUE THREAD

**Issue by TobleMiner** [MightyPirates/OpenComputers#2653]
Hi,

I'm experiencing issues with timers when using threads.

Timers created in the main process but cancelled in another thread do still elaps.

I've tested this code on both MC 1.7.10 and MC 1.12.1 with OpenComputers 1.7.0.20 and it is giving me the exact same result:

```lua
local event = require('event')
local thread = require('thread')
local computer = require('computer')

-- Works as expected
local id = event.timer(2, function() print('Timer 1 cb called') end)
print('Added timer 1 callback @' .. tostring(computer.uptime()))
event.cancel(id)
print('Cancelled timer 1 callback @' .. tostring(computer.uptime()))

os.sleep(3)

-- Fails
local id = event.timer(2, function() print('Timer 2 cb called') end)
print('Added timer 2 callback @' .. tostring(computer.uptime()))
thread.create(function() print(event.cancel(id)); print('Cancelled timer 2 callback @' .. tostring(computer.uptime())) end)

os.sleep(math.huge)
```

Output:
![unbenannt](https://user-images.githubusercontent.com/2042858/33512284-8067073c-d72d-11e7-81cd-b51a03644982.PNG)
 
From my understanding the second, threaded example should behave exactly the same as the first one if the thread executes before the timeout elapses. But that is not the case. ```event.cancel(id)``` returns false and the timeout does elapse.

I'm not sure if this may be an issue with my understanding of lua coroutines/OpenComputer threads but I do feel like this is a real issue.

**Comment by TobleMiner** [comment]
Also adding timers in threads does not seem to work:

```lua
local event = require('event')
local thread = require('thread')
local computer = require('computer')

-- Works as expected
print('Create in main')
local id = event.timer(2, function() print('Timer 1 cb called') end)
print('Added timer 1 callback @' .. tostring(computer.uptime()))

os.sleep(3)
print()

-- Fails
print('Create in thread')
thread.create(
	function()
		id = event.timer(2, function() print('Timer 2 cb called') end) 
		print('Added timer 2 callback @' .. tostring(computer.uptime()))
	end)

os.sleep(math.huge)
```

Output:
![timer create test](https://user-images.githubusercontent.com/2042858/33512852-2dc00e84-d737-11e7-8434-0f27138d5064.PNG)

The callback of the second timer is never called.

**Comment by payonel** [comment]
Both of your examples work as expected. The first example was a design choice that had important benefits but can cause some unexpected results. An api that is not predictable is not a great api -- but I do believe it can be justified. The second example is actually quite expected, and I think you'll agree. Let me explain ... 

**cannot cancel parent timer inside a thread**

Event timers are unique per thread. And in fact all event registrations are unique per thread. You could see a timer id `3` in 2 distinct threads, and cancel them independently. This was done for two reasons
1. A thread's suspension and death is facilitated by giving the thread management of its own event registrations.
1. A thread does not rob an event from another thread. As an example, two separate threads may be pulling on `key_down` and each of them we observe the `key_down`.

I felt that the user could find a similar theme between these two aspects of the api
1. When a thread dies all event registrations made by it die with it
1. Event registrations are not shared, inherited, nor accessible to other threads.

To my surprise I did not explain this in our docs. It is incompletely referred to in the section talking about suspended threads. I've added a section to outline this further: http://ocdoc.cil.li/api:thread#event_registration_independence

**thread timer never fired**

Your thread died/completed in the same execution that it started. In other words, it began and finished in the same breath, before `thread.create` ever returned. Keep in mind that OpenOS threads are based on coroutines still, and are not preemptive. Threads begin in the same call to `thread.create`, and your thread function in the example has no `pullSignal` of any form (such as `event.pull` or `os.sleep`, etc). Thus, the your thread also completes and returns before `thread.create` returns. Once a thread function exits that thread is `dead`. And, as explained in response to your first example/question, all event registrations died with it, which includes the timer you created. Thus, when the `os.sleep(math.huge)` is not going fire the now-expired event timer.

**Comment by TobleMiner** [comment]
Ah, thanks for the clarification
