### ISSUE TITLE
Tablets don't turn the screen off properly

### ISSUE THREAD

**Issue by AmandaCameron** [MightyPirates/OpenComputers#2654]
Calling `component.screen.turnOff()` from a tablet returns the right values, but doesn't actually blank the screen. Unsure if it's lowering the power usage. 

MC: 1.12.2
OC: 1.7.0.36
Forge: 1.12.2-14.23.1.2555

**Comment by payonel** [comment]
i believe this was intentional. if we add this, we also need to force screen on on boot

**Comment by skyem123** [comment]
Maybe the UI used for the tablet FDD could have buttons for the screen and power?
