### ISSUE TITLE
make opencomputers work standalone, no forge energy producer

### ISSUE THREAD

**Issue by payonel** [MightyPirates/OpenComputers#2655]
OC used to run without needing power when no power mods were detected, but now supporting forge power api has complicated that, for example: #2613

OC should have SOME recourse to work when there are no energy producers without having to modify the configs. Perhaps make a list of known energy providers?

Open to feedback from the community for smart ways to detect energy production is available

Perhaps OC should have a BASIC power producer, an OC coal generator maybe

**Comment by Vexatos** [comment]
See asiekierka/Computronics#131.

I don't see why people can't just edit the config.

**Comment by skyem123** [comment]
Maybe have a notification similar to the current one if it's using forge energy. Telling them that to use it without power they need to change the config. Though then how does the user state that they want to use power and don't need the message...

**Comment by payonel** [comment]
@Vexatos because in my opinion, oc should work out of the box, without needing to edit the config

**Comment by Darinth** [comment]
I feel like forge power should expose a method of checking to see if there are forge power generators present which mods providing them should be registering for or which should be automatically flipped once another mod begins providing power. OC isn't the only mod that wants to have conditional power requirements.

**Comment by Vexatos** [comment]
@skyem123 Should one do more than a log message, though? Getting the message everytime you join a new world might be pretty annoying.

**Comment by skyem123** [comment]
Well have three options in the config:
1. Default, nag me 
2. Don't nag me I want to use energy 
3. Don't nag me I don't have any energy mods

**Comment by Vexatos** [comment]
Well it would only nag once anyway.

**Comment by LightningSh0ck** [comment]
I think we should tell the guys from Forge that we need a way to detect energy producing mods.

**Comment by SaphireLattice** [comment]
I'm with the opinion that Forge *should* (or maybe must?) be the one to
signal lack of or presence of power generation. And if they don't - disable
Forge power API unless toggled in config, or use some kind of
(configurable, if possible?) master list of power providing mods. Do *not*
however make OC not work if there's no energy mods.

вт, 5 дек. 2017 г. в 1:57, LightningSh0ck <notifications@github.com>:

**Comment by payonel** [comment]
i actually have an idea for this i'm pretty excited about. but i'll share it publicly with a video demo when i have it done.

**Comment by payonel** [comment]
oh oops, this is done in dev builds. a la SHEEP POWER :)
when we release 1.7.2, there will be a nice video detailing it
