### ISSUE TITLE
Reduce tight coupling with IC2

### ISSUE THREAD

**Issue by josephcsible** [MightyPirates/OpenComputers#2656]
So IC2's Maven is down (I'm reminded of the Leftpad fiasco). I don't have the 1.10.x version of IC2 or Forestry in my Gradle cache, so I can't build OC for 1.10.x right now. In trying to temporarily disable IC2 and Forestry compats so that I can build it, I noticed that IC2 is more tightly coupled than it should be. In addition to its entries in integration/Mods.scala and its directory in integration/, there's:
* A method in common/EventHandler.scala
* An if statement in common/block/PowerConverter.scala
* An interface and its method in common/item/Wrench.scala
* An interface and its methods in common/item/traits/Chargeable.scala
* An entry in common/tileentity/traits/PowerAcceptor.scala
* The file common/tileentity/traits/power/IndustrialCraft2Experimental.scala (not in the directory with the rest of the IC2 stuff)

Would it be possible to clean this up, so that there's fewer places you need to comment out/remove to build without IC2?

**Comment by skyem123** [comment]
Ah... The problem with Gradle. It's wonderful until it breaks.
To be honest, this is not like the leftpad thing because there isn't really a different way to integrate with mods, though maybe finding a way to isolate it if possible would be a good idea.
Actually, maybe a Maven mirror of every dependency needed to compile would be a good idea, though I remember talking about that before...

**Comment by CaitlynMainer** [comment]
I've added the required version of IC2 for OC 1.10 to my maven (I'm adding the rest of the deps too) you can add 
```  
maven {
        name = "Michiyos-Everything-Maven"
        url = "https://maven.caitlynmainer.com/"
    }
```

to your build.gradle with the other repos and it should let you build successfully.

**Comment by josephcsible** [comment]
I did get it to build successfully (by taking care of everything I listed). This ticket is about making it easier to disable cross-mod integrations, not just making my build work.
