### ISSUE TITLE
Some AE2 export bus functions aren't working

### ISSUE THREAD

**Issue by Xanderr** [MightyPirates/OpenComputers#2658]
Hello,

I'm currently playing the All The Mods 3 modpack. In my world I wanted to automate draconic fusion crafting, which I wanted to do using OpenComputers. Using AE2 in combination with OC would make this a whole lot easier, but I couldn't get some of the export bus functions to work.

The functions that aren't working are called setExportConfiguration and exportIntoSlot. The functions do output errors when using wrong sides or giving invalid slot indices, for example. But when it doesn't output any errors, nothing happens (while it should be exporting or setting the configuration).

All other functions seem to work correctly, for the export bus at least. The directly related mods I'm using are:

- AE2 rv5.stable build 3
- OC 1.12.1 1.7.0.36 (latest from the build server)

I did notice that the latest OC version was "made" for AE2 rv5 stable 2, not 3. So maybe they changed something with AE2. If you need any further details, let me know!

**Comment by payonel** [comment]
can you provide an example of the actual code you are running and a screen shot of the AE2 device and point out what didn't change in the image that you expected would change? thank you

**Comment by Xanderr** [comment]
Ofcourse! I tried to simply the setup as much as possible. This is what it looks like:

![2017-12-05_16 11 43](https://user-images.githubusercontent.com/7647454/33615066-61962672-d9d9-11e7-8906-dabf8215cc32.png)

A computer with an adapter attached. The adapter contains a database upgrade tier 3. It should also allow me to interact with the export bus below it (which works fine).

![2017-12-05_16 11 02](https://user-images.githubusercontent.com/7647454/33615048-530c65ee-d9d9-11e7-9633-141a316e84d6.png)

This is the content of the database. In the first slot is cobblestone, for the sake of testing.

![2017-12-05_16 25 24](https://user-images.githubusercontent.com/7647454/33615295-0f4a92d0-d9da-11e7-8b5c-156ec02b276e.png)

This is what the filter of the export bus currently looks like. Its empty, with max capacity cards installed & a redstone card - to prevent it from constantly exporting the items when the filter is set.

![2017-12-05_16 24 31](https://user-images.githubusercontent.com/7647454/33615169-b0b1fc86-d9d9-11e7-9cb3-a1bdc53392db.png)

This is a simplified code of what I'm trying to do. The variable part should be obvious & works fine. Then I try to set the configuration of the export bus by calling setExportConfiguration(). This should place cobblestone in the export bus filter, right? The next line with exportIntoSlot() should then place 1 cobblestone in the chest.

However, after executing the code, the filter of the export bus is still empty (as in the image shown earlier), while the following was expected:

![2017-12-05_16 25 45](https://user-images.githubusercontent.com/7647454/33615410-5d12df36-d9da-11e7-87eb-25453c09dba5.png)

Since nothing was set in the filter in the first place, exportIntoSlot() does nothing. So I tried to manually put cobblestone in the filter and execute the code again. exportIntoSlot() still didn't do anything though, as the chest was still empty.

I hope this makes my issue a little more clear :)

**Comment by pkartner** [comment]
Do you already have an ETA on when this will be fixed? Thanks in advance :)

**Comment by payonel** [comment]
@Xanderr this is the code I see in your screen shot
```
local comp = require("component")
local sides = require("sides")
local db = comp.database
local ex = comp.me_exportbus

ex.setExportConfiguration(sides.back, 1, db.address, 1)

ex.exportIntoSlot(sides.back, i)
```
So, is that an `i` ?

I'm working on testing and fixing this now

**Comment by Xanderr** [comment]
Yeah it is, but that is a mistake from my end. Like I stated, I simplified the code as much as possible and must have missed correcing that. That "i" came from a for loop. I don't recall what it looped through, but most likely it was either slot indices for the target chest or indices for the export bus filter.

**Comment by payonel** [comment]
ok, setExportConfiguration fixed for interfaces and export buses
also fixed exportIntoSlot for export buses

this was also partially broken in 1.10, that's fixed too

**Comment by Xanderr** [comment]
Awesome, thanks! :)
