### ISSUE TITLE
Shader Bug

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#266]
I recently noticed when playing with shaders screen text and robots start to wave like leaves(this of course only happens with shaders involving waveing leaves)
So should we remove any organic material from screens?

**Comment by fnuecke** [comment]
Uh, they have Material.iron set, so that's not it... I don't know what's going on there. I'd have to know what that shader uses to check whether it should be applied to a block or not.

**Comment by Wuerfel21** [comment]
Maybe shader sourcecode can help (hint: its inside the .zip(duh)).
As for screens its just the text waveing( tested on tier 1 while leaving the background black)
Robots just glith between thier normal geometry and the altered geometry.
Cant test more now, but is simple to set up(really(i cant understand why anyone is using modinstallers, they just mess around with your profiles :-( ))

**Comment by fnuecke** [comment]
I haven't messed with shaders for MC in forever. Sounds like it only affects tile entity renderers. I'm afraid I don't really have the time to look into that right now, if someone else could provide some insight into what properties have to be set where to avoid this that'd be great.

**Comment by Wuerfel21** [comment]
Only able to reproduce when using minecrift. But could be something different, cause the minecrift jar is completley empty expect for a file which says something about classes are in libs.

**Comment by LizzyTrickster** [comment]
I've used 1.6.4 shaders with Sonic Ethers' shader packs and some others and they don't cause TileEntities to wave

**Comment by fnuecke** [comment]
Well, [minecrift is open source](https://github.com/mabrowning/minecrift) but I don't have the time to wade through that code to find some shader implementation detail (that doesn't even affect ~99% of the population), but if you point me to the line where they do the 'should it wave' check, I'll reopen this and have another look into it.

**Comment by Wuerfel21** [comment]
Uhh, it hapens only if you have minecrift and glsl shaders installed, currently you can only have one turned on at a time. I installed minecrift to see if it is compatible to oc and some other mods.
