### ISSUE TITLE
Updating to OC 1.7 from 1.6.1 now causes Segmentation fault

### ISSUE THREAD

**Issue by Noire86** [MightyPirates/OpenComputers#2662]
Hello, fellow developers!

I`ve faced with a server fault after updating OC version from 1.6.1.11 build to build 1.7
That was a bit strange, because there were neither JVM fault logs (hs_err), nor server crash log.

After several experiments, i`ve found that server is being killed by a SIGSEGV exception, also known as Segmentation fault.

This crash was reproduced many times by just loading problematic chunk with computers and stuff. After a couple of seconds, autosaving or using a command, server faulted.

You may say: "But where is the evidences"? The only thing that I found, is this message provided from debugging core crashdump through gdb utility:

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000661257bef71b in ?? ()

(full text: https://pastebin.com/5NR7A1TS)

So, I tried to switch ForceLuaJ option to true, and, voila! Everything was okay and fine. Switching it back meant those cringy segfaults. I also tried to launch my server on a plain Forge 1614 (Im using Thermos 58 on OVH Debian 8 with GrSecurity-hardened kernel by default) but result is still the same.

Then, I tried to update my system and java to the latest versions. That didn`t help too.

Finally, I even wiped all the OC hard disk and "state" data, but this didn`t make any sense.

As I think, some changes in 1.7 version broke the persistence mechanics of mod (sorry, if i am wrong, not a specialist in this things :P).

So, thats it.
Thanks in advance!

**Comment by payonel** [comment]
should I close as no-repro? :) (mostly) kidding
I'll need a zip of your world if you can upload that somewhere. Or, a clean-install-to-repro set of steps I can take to repro

**Comment by Noire86** [comment]
This is a modpack, do you need a modlist for this?

**Comment by payonel** [comment]
I don't know. Does it repro without the modpack?

**Comment by xarses** [comment]
Which MC and forge versions? I didn't have any problems on mc 1.7.10 running on a windows server

**Comment by Noire86** [comment]
Forge 1614, mc 1.7.10

OS: Debian 8 x64 with GrSecurity (Standard OVH hosting option)

**Comment by skyem123** [comment]
Yeah... I sorta remember this I think, I blame GrSecurity, but we weren't able to test any more than that? ah well...

**Comment by Noire86** [comment]
Problem is solved on version 1.7.2. Server works fine, no segfaults.

**Comment by skyem123** [comment]
That's good to hear, interesting that it apparently only affected a small range of versions, but glad that it is fixed somehow. ^^
