### ISSUE TITLE
[Feature Request] All items with uuid can be 'reset'

### ISSUE THREAD

**Issue by xarses** [MightyPirates/OpenComputers#2663]
Hard disks and floppies can be reset by empty crafting them, I'd like to ask that any thing that gets a uuid as part of the component bus inherits this ability (and we should probably hide the recipes from nei to not confuse people). This would allow us to be able to reset components for storage or purge them from weird states (terminal servers get funky and have to be disassembled)

**Comment by Darinth** [comment]
Please don't hide the reset recipes from NEI/JEI. I really appreciate seeing the self-crafting recipes, it's how I know that items can be reset.

**Comment by Vexatos** [comment]
We would have to hardcode in an exception for linked cards, since those cannot have their UUID removed.

**Comment by skyem123** [comment]
Hmm... Should there be a way to "relink" linked cards?

**Comment by Vexatos** [comment]
You cannot "re-link" linked cards. They are crafted in pairs. You cannot separate them. That's why you must not change their UUIDs.

**Comment by skyem123** [comment]
But what about a way to re-link two cards instead of being able to unlink them? 😛

**Comment by Vexatos** [comment]
That would require a fundamental rewrite and lots of hardcoding in the component system itself to prevent it from automatically generating new UUIDs.

**Comment by skyem123** [comment]
O_o

**Comment by skyem123** [comment]
For new linked cards, wouldn't having new UUIDs be okay?

**Comment by Darinth** [comment]
Craft a pair of linked cards together to get a new pair of linked cards? They'd change UUID, but remain linked.

**Comment by skyem123** [comment]
Yeah, that's what I meant. ^^;;
