### ISSUE TITLE
Minechem Compatibility

### ISSUE THREAD

**Issue by jrddunbr** [MightyPirates/OpenComputers#2665]
Hello,

Trying to use Minechem with OpenComputers - specifically the fusion and fission chamber multiblocks.

For some reason, when I try to do anything with the adapter, it returns ```nil```.

In the Minechem config, I made the following change (from false to true), with no effect:

```
    # Allow automation of Minechem machines
    B:allowAutomation=true
```

I'm not sure if this is caused by OpenComputers or Minechem.

If I try to use the transposer, I can see the items in a chest, but I can not see the  multi-block, even with items in the slots.

## To replicate:

- Install Minechem and OpenComputers (and a RF mod for Minechem to have power)
- Make the above config change (or don't)
- Run the same commands below:

![2017-12-06-190852_1920x1080_scrot](https://user-images.githubusercontent.com/14130505/33692043-6562b9a6-dab9-11e7-9cf8-87817f8868c9.png)

**Comment by payonel** [comment]
please give full mc, oc, forge, and minechem version info

**Comment by jrddunbr** [comment]
Minecraft Version: ```1.7.10```

Open Computers: ```OpenComputers-MC1.7.10-1.6.2.12-universal``` (from startup log)

Forge: ```Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10``` (from startup log)

Minechem: ```Minechem-1.7.10-5.0.5.406``` (from startup log)

[Startup Log](https://pastebin.com/XRPkT2V8) (may be helpful, perhaps not. I can also try with a cleaner environment, but it's pretty light)

EDIT: Nothing shows up in the log when I get the error.

**Comment by payonel** [comment]
can you retest with an updated OC? Your version is roughly 10 months old
our latest dev builds: http://ci.cil.li/job/OpenComputers-MC1.7.10/
our release versions go to curseforge: https://minecraft.curseforge.com/projects/opencomputers/files

**Comment by jrddunbr** [comment]
Sure, I'll get back to you once I've done that. I'll try to fetch a fresh Minechem as well.

**Comment by jrddunbr** [comment]
So I still have the same issue. The output for the adapter is now different (see below), but besides that, the transposer still doesn't think it exists, despite finding a chest fine.

Running any functions related to the adapter causes an error to come from Lua. I can nab that next.

New versions:

```
  buildcraft-7.1.23
  Minechem-1.7.10-5.0.5.406
  OpenComputers-MC1.7.10-1.7.0.1124-universal
```

I also fetched the latest Buildcraft, because otherwise Minechem would get upset that there was no energy mod in place.

![2017-12-06-231545_1920x1080_scrot](https://user-images.githubusercontent.com/14130505/33698618-bb6800be-dadb-11e7-89bb-bef8cf7a8212.png)

**Comment by jrddunbr** [comment]
The error I got was related to the fact that I can't spell receiver for some reason. For every side I try as an argument for each of the functions, it outputs information that is irrelevant/incorrect about the device.

**Comment by jrddunbr** [comment]
I have tried the transposer on the top block, and the bottom center edge of the South and West sides. Nothing shows up at all. Will try the bottom center as well as the North and East sides.

**Comment by jrddunbr** [comment]
Every side says ```nil    no inventory``` when I query it with the transposer for every side of the transposer (0-5 is what I'm feeding into it for side numbers) with ```getInventorySize()```

**Comment by payonel** [comment]
btw
1. in the lua proxy, libraries load automagically for you. you dont' need to `require` anything in there
2. openos provide convenience "primary" component access, you don't need to proxy or get address if you have just one component you want to access by type, `component.transposer`

**Comment by jrddunbr** [comment]
Hmm, thanks. I had noticed that the lua shell behavior was different from executing files, but I wasn't sure how.

Would be cool if issue was fixed, but no particular rush (nor disappointed if it never happens). Still using 1.7.10 believe it or not.

**Comment by payonel** [comment]
@jrddunbr are you able to join us in irc? I'm getting very different results in my minechem testing
if you dont have an irc client, you can visit us with a web browser: https://webchat.esper.net/?nick=&channels=OC

**Comment by jrddunbr** [comment]
It's super late at night (2:39am), but sure in a few. Esper? What's the IRC server IP?

**Comment by payonel** [comment]
well in case you see this much later ( i was hopeful you were here right now, given how quickly you responded to my previous comment )

the transposer finds no inventory (nil, 'no inventory')
the adapter loads the multi block, but it is acting as a generic energy receiver, and isn't correctly reporting its stored energy (returns 0)
the inventory controller in the adapter is acting like the transposer, showing no inventory

**Comment by payonel** [comment]
yeah, no worries about irc chat, but it's #oc on esper.net (208.94.117.115)
the changes i see could be due to OC version, it could be the MineChem version (i'm on latest of each on 1.7.10)

**Comment by jrddunbr** [comment]
It appears that the usage of `component.transposer.getInventorySize()` has changed from taking no arguments previously, to taking a side as argument. @payonel mentions in IRC that the problem is probably not OC related, and Minechem for 1.7.10 is *old*.

One of the sides in the screenshot below has a chest (thus the 27 inventory slots for `t1.getInventorySize(2)`). `t1` in this scenario is a proxied transposer (but I did try the transposer with `component.transposer.getInventorySize(0)` (through `5`) as well - just did this to check and make sure it wasn't an odd thing with proxies)

![getinventorysize](https://user-images.githubusercontent.com/14130505/45925263-e728df00-bedf-11e8-8900-085e054d41cb.png)

```
Mods:
  CoFHCore-[1.7.10]3.1.4-329
  Minechem-1.7.10-5.0.5.406
  OpenComputers-MC1.7.10-1.7.2.1215-universal
  ThermalDynamics-[1.7.10]1.2.1-172
  ThermalExpansion-[1.7.10]4.1.5-248
  ThermalFoundation-[1.7.10]1.2.6-118
```

**Comment by payonel** [comment]
I found that we are able to interact with the minechem machines if i remove the isUseableByPlayer check. At this point I'll have to point to this a bug in their code (as it is correct for us to check isUseableByPlayer), though sadly the project appears dormant now days.

**Comment by xarses** [comment]
This isn't another case of fake player acl biting again?
