### ISSUE TITLE
Utility Fog for OC

### ISSUE THREAD

**Issue by abculatter2** [MightyPirates/OpenComputers#2666]
Copy-pasted from the IRC;
What about a Utility Fog Projector block, which lets a computer create (and destroy) 'Utility Fog' blocks in a specific radius. These blocks would have a lot of properties that can be assigned by the computer, such as whether or not they're solid, their texture (maybe this would require printer ink?), their hardness and blast resistance, whether or not they glow (maybe this would require glowstone?) and possibly also their model. Creating these blocks would consume Chamelium, which is returned if the beacon destroys the block, as well as quite a bit of energy and an amount of CPU cycles proportional to the block's complexity (special textures, custom models, etc.)
There could also be a RAM cost for storing the block's location, otherwise the block will eventually decay

**Comment by payonel** [comment]
I feel this is outside the plans for OC, but this is a fun idea. Reminds me of calclavia's modular force fields. This would make a good add-on
