### ISSUE TITLE
add basic rc api and document

### ISSUE THREAD

**Issue by payonel** [MightyPirates/OpenComputers#2667]
openos rc lib needs an api that is simple and meaningful, ~~with documentation to back it up~~ (doc issue handled by The Big Wiki issue)

**Comment by purplemonday** [comment]
sorry tobe daft.. but rc? 
remote controle? retroactive computing, i meen i can keep going for days?
what does RC stand for?

**Comment by payonel** [comment]
rc comes from "run command"
the rc system for openos is inspired by openrc
https://wiki.gentoo.org/wiki/OpenRC

**Comment by payonel** [comment]
I've changed my mind. I've reviewed the rc api and I find it adequate. It does, however, need plenty of documentation. If anyone reading this has great ideas for a more advanced rc system, hit me up on #oc or feel free to comment here. At the very least, this has been removed from the 1.7.3 milestone.
