### ISSUE TITLE
wrong char in font.hex

### ISSUE THREAD

**Issue by snafets** [MightyPirates/OpenComputers#2676]
The big char for | is missing and { is on this place (0xFF5B) instead.

output: z ? { }
expected: z { | }

FF5A:0000000000000000000000003FFC003C00F003C00F003C003FFC000000000000
FF5C:0000007E01E001E001E001E003C07F8003C001E001E001E001E0007E00000000
FF5D:00007E00078007800780078003C001FE03C007800780078007807E0000000000

Edit: 
found another missing char that would be nice to have.
0x2193 = ↓ (arrow down)

**Comment by asiekierka** [comment]
That's probably a bug in http://github.com/asiekierka/funscii

**Comment by asiekierka** [comment]
https://github.com/asiekierka/funscii/commit/af77b49161043d5113561f5f57a8606dcc4b41ed

Aaaand fixed.

**Comment by snafets** [comment]
Thanks for the quick fix, I tried the new font.hex, but I guess I need a new wcwidth.bin too.

I have "z ? | }" now

**Comment by payonel** [comment]
@snafets aye, we're reviewing the updates we want for this
