### ISSUE TITLE
Add *Environment Capabilities to the API

### ISSUE THREAD

**Issue by davenonymous** [MightyPirates/OpenComputers#2677]
I'd like to "fake" an Environment on a block in my Compact Machines mod so cables visually connect to said block. I'd need to do that via Capabilities.

The thing about Compact Machines is that they are not an Environment themselves, but pass *all* capabilities along to another tileentity. This works fine on the server, but since the "other tiles" are in another dimension I need to fake these capabilities on the client side.

[Related issue](https://github.com/thraaawn/CompactMachines/issues/279).

**Comment by Vexatos** [comment]
The capabilities are already part of the API, they are the same interfaces you used to implement on a tile: `li.cil.oc.api.network.Environment` and `li.cil.oc.api.network.SidedEnvironment`. They also still work that way, OC would automatically attach their capabilities if you implement them, but it's better to attach the capabilities yourself.

**Comment by davenonymous** [comment]
Oops, derp. Thanks for clearing that up.
