### ISSUE TITLE
How do you interact with a relay wirelessly to send component commands?

### ISSUE THREAD

**Issue by uehlbran** [MightyPirates/OpenComputers#2680]
I have a relay that is x blocks from my computer, both have a wireless card, but the computer can only see the relay when a cable is running between the two. How do I wirelessly send some data to the relay without hardwiring anything to the relay or computer?

for example, component.modem.send(port number, br_reactor.setActive(true)) - How do I do something like this?

or component.modem.broadcast(123, component.redstone.setOutput(sides.left, 15)) - This command reaches the relay, but does nothing to the redstone connected to the relay.. how do i do something like this? It does affect redstone connected to the computer where the command was sent from.

**Comment by xarses** [comment]
You don't, the component network is only accessible via computers on the wired connection. You would need to send messages to another computer with access to those functions. You would also need to set it up the receiver to respond to messages as they don't just take lua commands directly

**Comment by payonel** [comment]
@xarses is correct, relays are controlled as components, and a component must be part of a wired network, or adjacent to computer
