### ISSUE TITLE
How can robot get the details of the front block?

### ISSUE THREAD

**Issue by thestronger8** [MightyPirates/OpenComputers#2684]
Using detect, I can only get information like soild, air, and so on.
I want to know whether the wheat is mature , how to distinguish it?
Just like  component.inventory_controller.getStackInInternalSlot(slot)

**Comment by xarses** [comment]
using a geolyzer in an upgrade container slot, or as permanent upgrade allows you to call `analyze` (http://ocdoc.cil.li/component:geolyzer)

**Comment by payonel** [comment]
ah thanks @xarses - i forgot to update this ticket (had clicked it, so it was "read" and not showing as a notification anymore for me)
