### ISSUE TITLE
Crafting the drone and EEPROM doesn't work

### ISSUE THREAD

**Issue by Litvinosss** [MightyPirates/OpenComputers#2685]
Crafting a drone and EEPROM doesn't return anything
MC Version: 1.12.2
OC Version: 1.7.1.44.
Forge version: 14.23.1.2566
![change eeprom](https://user-images.githubusercontent.com/32991055/34121817-05d4ca00-e433-11e7-8862-3a73e49149e4.png)

**Comment by payonel** [comment]
confirmed in 1.12, does not repro < 1.12

**Comment by LiddulBOFH** [comment]
There is a temporary workaround, if this hasn't already been fixed (Playing FTB Revelations 1.2.0), go to an Anvil and toss the drone in, and clear the name. I discovered this when looking at the "JEI to Crafting Grid" recipe, and noticed it didn't match, thought it might have been the name which for some reason gets placed on drones automatically. Clearing that restored the original "Drone" name, and then lets me install a new EEPROM.... which then puts a new name on the drone, but whatever.

Minecraft 1.12.2
OC 1.7.1.43
Forge: 14.23.1.2573
