### ISSUE TITLE
Hover Boots can't be charged with Thermal Expansion's Energetic Infuser

### ISSUE THREAD

**Issue by Thungo** [MightyPirates/OpenComputers#2687]
As the title states, I've tried to charge the Hover Boots in the Energetic Infuser, but I can't place it into the machine to be charged at all. For reference, I'm using OpenComputers version 1.7.1.43 and Thermal Expansion version 5.3.7.31 (Minecraft 1.12.2). I also tried to use the Flux Capacitor to charge it (both with having the boots in my hand and as armor), but that didn't work either. (Not sure if that is a feature anyway)

**Comment by payonel** [comment]
have you tried OpenComputer's [Charger](http://ocdoc.cil.li/block:charger)?

**Comment by Thungo** [comment]
Yeah, that's not the problem. I have charged it before with the Charger, I was just wanting to also charge it with the Energetic Infuser (since it says in the documentation it should be able to)

**Comment by payonel** [comment]
this is probably an incompatibility with >= 1.11, things changed with the forge energy api
I'll leave this ticket open as an incompatibility issue, but to be fair, this will be pretty low priority compared to other tickets we're working on.

I'll add notes to our documentation needed ticket, #2686 , that we should update that we require just our charger in >= 1.11

**Comment by payonel** [comment]
hover boots, tablets, and batteries are forge energy compatible, and can be charged by forge energy devices, such as the TE energetic infuser
