### ISSUE TITLE
New font.hex instead old

### ISSUE THREAD

**Issue by Stevexmh** [MightyPirates/OpenComputers#2689]
I sent an issue about some wrong characters two days ago.
Now I finally made a full characters hex file!
The hax file:
[https://mega.nz/#!UgkgHTgB!9ZbfEahchKNtEYKzg73XDiyz8mSkbySnL0valxRyJLQ](url)
Here is the fonts map:
![fullfonts](https://user-images.githubusercontent.com/20882300/34166695-8a20ed74-e51a-11e7-8cb6-2f52d4643df2.png)

**Comment by payonel** [comment]
what is the license of this? who designed this font? who owns it?

**Comment by asiekierka** [comment]
Where did you source the font from?

**Comment by asiekierka** [comment]
Oh, GNU Unifont! How adorable. Unfortunately, that's a "no" - the Unifont is GPLv3 and thus requires all works including it to also be distributed under the GPLv3, whereas OpenComputers wants to remain MIT-licensed as far as I know.

**Comment by payonel** [comment]
yeah, sorry @Stevexmh - the licensing of the font is very important

**Comment by skyem123** [comment]
@asiekierka, doesn't Unifont have a bitmap exemption? and IIRC you can't copyright bitmap fonts at all...

**Comment by asiekierka** [comment]
@skyem123 It has an exemption for the font being used embedded in a document, not in a computer program.

Bitmap font copyright differs from country to country.

**Comment by skyem123** [comment]
Theoretically the bitmap rendering counts as a document? :P

**Comment by xarses** [comment]
We aren't going to mess with maybes on GPLv3 contamination

**Comment by asiekierka** [comment]
@skyem123 Is OpenComputers a document? No? Then shush.

It's a computer program.

**Comment by Stevexmh** [comment]
@asiekierka @payonel 
Sorry for that, I don't know about this I can't use. :(
So what font can I use?
I just want to fix the chinese font problem.

**Comment by asiekierka** [comment]
You can use GNU Unifont locally. It's legal, as long as you're okay with OpenComputers + Unifont being GPLv3-licensed as a whole.

You can even make a resource pack which replaces the font.hex with GNU Unifont, although some issues with wcwidth.bin need to be fixed first...

It's just that the project is not interested in bundling it officially.

**Comment by Stevexmh** [comment]
@asiekierka 
OK got it. But what is the wcwidth.bin?
And how do I edit it to support chinese characters?

**Comment by payonel** [comment]
@Stevexmh the wcwidth.bin is an issue I'm fixing on the OC side, to allow you to replace your own font.hex

On the client side, font.hex can replace our mod font.hex just like you can replace a texture in a texture pack

**Comment by Stevexmh** [comment]
So I know a bit about what wcwidth.bin do. I tried to make a new one but failed.
Use GNU Unifont. Any problems?
![1212121](https://user-images.githubusercontent.com/20882300/34215257-cc42d31e-e5df-11e7-89d7-928090171735.png)

**Comment by payonel** [comment]
I'm removing wcwidth.bin. The new logic will only use the font.hex file

We cannot use gnu unifont, but you can locally if you choose. You can make your own resource pack and include a custom font.hex that has your gnu unifonts

We don't plan to update our font.hex at this time.

**Comment by Stevexmh** [comment]
@payonel I know. So hope can update full font.hex :D
So the last qustion: How to add font.hex to resource pack?

**Comment by 3TUSK** [comment]
Apologize for jumping in first.

@Stevexmh 
I assume you are native Chinese speaker because of the topic of this issue.
Thanks to https://github.com/MightyPirates/OpenComputers/commit/d67156ed52d2417142685f188914c06f5ff04dd2, there has been a resourcepack ready-for-use, released here: [http://www.mcbbs.net/thread-773005-1-1.html](http://www.mcbbs.net/thread-773005-1-1.html). You may consider about this one if you struggle on making one on your own.

I am not the one who released that resourcepack, so I don't really know the copyright status.

> On my first glance of this issue, I was thinking of [Source Han Serif](https://github.com/adobe-fonts/source-han-serif/blob/master/LICENSE.txt) but that's a font specifically designed for CJK characters... and thus it may not works well (to the extent of visual effect) even if the license is not a n issue.

**Comment by Stevexmh** [comment]
@3TUSK I saw it. It use Song Font (宋体). And this font is no copyright.
But I'm still using GNU unifont so I don't need it. :)

**Comment by xiaoye1024** [comment]
@payonel 
My English is not very good, so I use Google Translate to express what I want to say.
Before reading your conversation, I was very interested in complementing "font.hex". I first implemented using "中易宋体," but was deprecated for copyright reasons. Now I have re-created this file using "Source Han Serif", which uses a SIL license. Its effect is a little worse than "中易宋体," but it's enough.
Note: I only replaced 0x4E00-0x9FBF and 0xFF01-0xFF65, only Chinese and Chinese symbols.
If necessary, I can provide the original hex replace the Chinese file or only Chinese hex file.
preview:
![ocpack8](https://user-images.githubusercontent.com/34893504/34421542-e21a54de-ec4a-11e7-86a5-383e9c56cf26.png)

the original hex replace the Chinese map
http://xiaoyebucket.oss-cn-beijing.aliyuncs.com/Picture/map.bmp

only Chinese map
http://xiaoyebucket.oss-cn-beijing.aliyuncs.com/Picture/onlyChenese.bmp

**Comment by payonel** [comment]
@xiaoye1024 I think we agree that your work would help OC fonts
I think the SIL license is okay. I need to read it a 2nd time to be sure.
However, this discussion here is a closed bug report. If you want to provide an update to our font system, please make a Pull Request to master-MC1.7.10 to update src/main/resources/assets/opencomputers/font.hex
