### ISSUE TITLE
OpenComputers creates files that cannot be accessed on Linux (likely macOS as well)

### ISSUE THREAD

**Issue by sparky8251** [MightyPirates/OpenComputers#2690]
Problem:

OpenComputer states are store in folders that use the chunk coordinates. Linux utilities cannot access directories or files starting with '-'.

Steps to reproduce:

Run a Minecraft server on Linux and create an OpenComputer in a chunk whose coordinates are '-#,-#' or '-#,#' and try to access 'world/opencomputers/state/#/-#,*'. You will not be able to as the leading '-' is interpreted as a switch.

Implications:

Unsure how important states are but... If backing up/restoring/migrating a Minecraft server it will likely cause inconsistencies in states folder contents (can't overwrite/backup files in certain dirs).

Suggested solution (if problem really exists):

Adopt Minecraft's world save naming scheme and use 'r.#.#' so all files/folders that would have a leading '-' now have a leading 'r.'

If you need any more information please let me know.

**Comment by payonel** [comment]
linux shells can DEFINITELY access files/dirs that start with `-`. Name me one tool or shell that cannot
`mkdir -- -1,1`
`touch -- '-1 foo . bar'`
`tar czf back.tgz -- -1,1 `
etc

**Comment by payonel** [comment]
btw, for what it's worth, openos supports this too

**Comment by sparky8251** [comment]
Why isn't the `--` switch documented more readily? Tried searching online for general docs and didn't see a mention of it...

I was able to access them using absolute paths or relative paths from above their parent directory so i figured this was a very minor issue if one at all.

Thanks for teaching me something new! Really handy to know.

**Comment by xarses** [comment]
`--` is commonly used to reference the end of switches (anything after is a positional arg and not a switch or flag) in *NIX commands many commands don't reference they support it.
