### ISSUE TITLE
Tablet's Screen Freezes after Death

### ISSUE THREAD

**Issue by Shazuli** [MightyPirates/OpenComputers#2696]
***Hi!***

I noticed when I was playing around with the nanomachines that when I died with the tablet on me while it was active, the screen freezes.
I tried a bunch of things such as shutting it off (sneak-right click), running other programs. But to no success. It wasn't until I restarted my game that the screen worked correcly. This is not intended behavior.

*Minecraft:* `1.12.2`
*Opencomputers:* `MC1.12.1-1.7.1.43`

**Comment by payonel** [comment]
i'm improved the reliability of the tablet considerably, but only for 1.12 (for those looking to get bug fixes on early mc versions)
