### ISSUE TITLE
Turn on button does not work

### ISSUE THREAD

**Issue by DevNebulae** [MightyPirates/OpenComputers#2698]
When pressing the "Turn on" button on any tier computer, it does nothing. I have to shift + right click on a computer case for it to start up.

Minecraft version: 1.12.2
OpenComputer version: MC1.12.1-1.7.0.20 and MC1.12.1-1.7.1.43

EDIT: This bug only seems to occur in the FTB Revelation mod pack

**Comment by payonel** [comment]
thank you for reporting
this was an issue with our netty code and forge as reported here: #2695
And fixed in our dev builds, available >= build OpenComputers-MC1.12.1-1.7.1.46.jar
here: http://ci.cil.li/job/OpenComputers-MC1.12/
