### ISSUE TITLE
Bootable medium not installing

### ISSUE THREAD

**Issue by DevNebulae** [MightyPirates/OpenComputers#2699]
When placing a computer and a disk drive next to each other, the computer does not seem to install any OS onto the computer's hard drive. The disk drive needs to make the iconic old hard drive sound, but it doesn't.

Minecraft version: 1.12.2
OpenComputers version: MC1.12.1-1.7.0.20 and MC1.12.1-1.7.1.43

EDIT: This bug only seems to occur in the FTB Revelation mod pack

**Comment by payonel** [comment]
closing as side affect of #2695 please update to our dev builds here: http://ci.cil.li/job/OpenComputers-MC1.12/
