### ISSUE TITLE
Advanced Holographic Projector

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#270]
Greetings,
I'm trying to make advanced CCC on bridge of my spaceship, using Holographic Projectors, though there's issue that makes it impossible for time being - Holographic projectors are monochromatic;
I'd like to ask IF it would be possible to create multichromatic (a.k.a. with multiple colors) projectors, or make them component block as computers are to allow for exchangable projector units, to change resolution, distance from projector and/or color amounts.

Of course costs should increase accordingly (3 fold for 16 colors of bits as example, due to light being composed of 3 primary colors).

p.s. in hindsight even ability to modifiy of default color and addition of ability to move 'center' position of hologram would be more than enough to do that, question if it is feasible.

**Comment by Wuerfel21** [comment]
Will be in 1.3

**Comment by fnuecke** [comment]
Indeed, there'll be  tricolor hologram projector in 1.3 (see [this post](http://oc.cil.li/index.php?/topic/82-heads-up-on-opencomputers-13/)) and that's already pushing it so it's unlikely there'll be one one with more colors than that ;-)

Providing an offset... might be something interesting to add. I'll think about it.
