### ISSUE TITLE
Console error spam + disconnecting users

### ISSUE THREAD

**Issue by xorinzor** [MightyPirates/OpenComputers#2700]
Using OpenComputers 1.12.1-1.7.1.43 on MC 1.12.2 with modpack "All The Mods 3".

Getting this error spammed in the console, stops when all nearby opencomputer blocks are removed, starts again as soon as a computer case is placed down and the power button is pressed.

[Server thread/WARN] [opencomputers]: Received a badly formatted packet.
java.io.EOFException: Unexpected end of ZLIB input stream

Tried removing all data from /world/opencomputers/ but despite that directory being empty this issue still persists.

The console / log isn't showing anything else aside of the error as pasted here. This same error is also causing the client to disconnect when they get near (although not consistent, it seems to get worse with time).

Client error:
[Netty Client IO #4/ERROR]: NetworkDispatcher exception
io.netty.handler.codec.DecoderException: io.netty.handler.codec.EncoderException: java.io.EOFException: fieldSize is too long! Length is 25189, but maximum is 185.

This also  happens for other users on different computers with a freshly downloaded client.

**Comment by payonel** [comment]
definitely sounds like a repro of #2695 
we have a fix in our latest dev builds, please retest and let us know if the problem persists: 
http://ci.cil.li/job/OpenComputers-MC1.12/

**Comment by xorinzor** [comment]
Can confirm, I upgraded forge to 2582 and the issue is gone.
Thanks!
