### ISSUE TITLE
Suggestion: Screen+keyboard in one block

### ISSUE THREAD

**Issue by DcNdrew** [MightyPirates/OpenComputers#2702]
I use Bibliocraft and other furniture mods and it's a bit weird to see my screen behind the whole table.

**Comment by Techokami** [comment]
Do what I do and make the table deeper.
![scaledfurniture](https://user-images.githubusercontent.com/1530728/34385918-0baea5fa-eaf4-11e7-9a57-f0e256a916d5.png)

**Comment by DcNdrew** [comment]
I made this, but my suggestion is still on.
https://www.dropbox.com/s/8fmq9ov34ed5187/2017-12-28_00.05.04.png?dl=0
