### ISSUE TITLE
Hologram component doesn't exist

### ISSUE THREAD

**Issue by aackerson** [MightyPirates/OpenComputers#2703]
I'm trying to write the basic hologram snippet in the tutorial but the hologram component is not there. And when I run components.lua to get the list, hologram is missing. I'm using version 1.6.2.7

**Comment by skyem123** [comment]
Well... Not sure about how you have things setup, but you need to connect a hologram projector to the computer, note that the wire needs to be at the bottom of the hologram projector. If you already have it setup like that then that's a worry.
Either way, please take screenshots and attach/link them, as it will help figure out what's wrong.

**Comment by aackerson** [comment]
Ah, no, that was the problem! I had just put the block adjacent to the computer case. I didn't realize it needed to be connected through the bottom of the projector. Once I did that, it worked just fine. Thank you!
