### ISSUE TITLE
The rackmount disk drive cant be opened...?

### ISSUE THREAD

**Issue by Vectrobe** [MightyPirates/OpenComputers#2704]
If you put a rack disk drive (for floppies) into a rack for servers to access, and attempt to open the disk drive, it instead opens the rack's GUI. Other rack components will open their GUI's as normal however...

**Comment by skyem123** [comment]
you can shift+right-click, but the GUI doesn't work for some reason... dunno if this is intentional or not, but I agree that it *should* open the GUI

**Comment by Vectrobe** [comment]
now that's interesting, I had tried literally everything before, shift-clicking with and without the floppy in hand etc yesterday. However I just tested now with shift-clicking the floppy in and it worked, however the server now already has the OS installed, so shift-clicking only works if the server's already running an OS...?

I think this affects the terminal server as well, as apparently there's supposed to be a GUI to change the range, however there's no accessible GUI to do so, but pairing terminals works?

I'd suggest we add buttons in the rack GUI as well to open the GUI of each component, as aiming onto such a small area of the rack is rather problematic...

**Comment by payonel** [comment]
adding inventory gui for just the disk drive for this ticket
