### ISSUE TITLE
Adapters function incorrectly on claimed chunks

### ISSUE THREAD

**Issue by VirtuesL** [MightyPirates/OpenComputers#2706]
There seems to be an issue where the Adapter block fails to check inventories if it is In a claimed chunk.

![2017-12-28_13 33 06](https://user-images.githubusercontent.com/34153474/34409637-b1c08b0e-ebd3-11e7-991f-7686bd64ffb5.png)
![2017-12-28_13 33 18](https://user-images.githubusercontent.com/34153474/34409640-b7899d6e-ebd3-11e7-8d45-0c8d2f6fd83f.png)

**Furthermore, it seems to only be an issue if the claimed chunk belongs to a team you didn't make.**

![2017-12-28_13 26 09](https://user-images.githubusercontent.com/34153474/34409672-de08e576-ebd3-11e7-94bb-39ac425877da.png)
![2017-12-28_13 26 16](https://user-images.githubusercontent.com/34153474/34409674-dfca7708-ebd3-11e7-8900-ce8e54943ecf.png)

I believe this should not work like it does.

**Comment by payonel** [comment]
What mod are you using for these claimed areas?
Are you able to open the inventory manually of these chests in these areas?

And, "Furthermore, it seems to only be an issue if the claimed chunk belongs to a team you didn't make." sounds like a nice feature -- if someone else claimed the area they probably don't want me inspecting their inventories

also, what version of oc are you using here?

**Comment by VirtuesL** [comment]
The mod used to claim chunks here is FTBUtilities, version 1.1x-3.6.5, 
And I'm running version 1.6.2.7 of OpenComputers.

I am able to open chests and such, since I am a part of the "team", to which the claimed chunks belong to.
Upon further investigation it seems that the Adapter(along with all the other nececcities) works fine if placed by the **Owner** of the Team.

This isn't necessarily a big issue, it would be nice if one could read the inventories of containers of the Team one is apart of.

**Comment by thiakil** [comment]
@VirtuesL is the setting to allow FakePlayers turned on? You might want to try it with that enabled if not.

**Comment by payonel** [comment]
currently no plans to add support for this (I'm not opposed, this just isn't planned)
open for adoption
