### ISSUE TITLE
Suggestion: Gaming Platform

### ISSUE THREAD

**Issue by TekuSP** [MightyPirates/OpenComputers#2709]
Add "Game Controller card"

- _Basic_ = 2 game ports
- _Advanced_ = 4 game ports

Add "Game Controller"

- 6 buttons A/B/C/D/E/F/G
- 4 buttons UP/DOWN/LEFT/RIGHT

Allow mapping buttons to real keyboard. 

**USAGE:**
On ground entities as "game controller". Players can select, will display screen, like keyboard does.
Will allow mapping keys and pushing them by pressing keys on keyboard.

Now API. Card will have function "ReadKey()" which will return "Key Pressed" and "Controller number".

I think its great idea, because multiple players will be able to play on one OpenComputer. And what more, it will push players to develop games on OpenComputers, as playing them will be a lot easier.

**Comment by payonel** [comment]
`ReadKey()` is an interesting suggestion, but the rest of it is already supported. The "key_down" and "key_up" events also tell you who pressed it. I would filter based on the player. And if I had a multiplayer game I would have each player select a box on the screen so they can choose to be player 1 and the other player 2. I would store who select which player number, and then parse key events with that info.
openos already keeps track of the key pressed states. You can review its implementation to keep state per player.

Thanks for the suggestion but I think we'll pass on this.
