### ISSUE TITLE
Big Reactor support broken in 1.2.11

### ISSUE THREAD

**Issue by jorritTyb** [MightyPirates/OpenComputers#271]
Seems a computer no longer recognizes big reactor component since 1.2.11 (the big reactor is not listed in 'components'). This is the case both with the computer cable connected directly to the computer port or indirectly with an adaptor. Neither work.

**Comment by Wuerfel21** [comment]
Computronics is broken too. Seems like 1.2.9 works

**Comment by Techokami** [comment]
Computronics in 1.6.4 or 1.7.2? If it's the latter, I will look into fixing it later today.

Sent from my Windows Phone

**Comment by jorritTyb** [comment]
In my case I'm talking about 1.6.4

**Comment by Wuerfel21** [comment]
1.6.4 ,it would be like a nuke-explosion if this not getting fixed in 1.3! Btw in 1.3 will addons robot upgrades get broken?

**Comment by fnuecke** [comment]
Well, I derped in the fix in 1.2.11... go me. Fixed version is [building right now](http://ci.cil.li/job/OpenComputers/), will push it as a release as soon as I've double-checked it works in non-dev mode.

And yes, robot addons will have to adjust to the new API in 1.3 - it's a relatively minor change, though.
