### ISSUE TITLE
There is no switch

### ISSUE THREAD

**Issue by Gaborboy95** [MightyPirates/OpenComputers#2712]
I can't find the switch block.

**Comment by payonel** [comment]
your bug report is nearly as lacking in details as our documentation is on the switch and relay. the switch was removed in 1.11. use a relay

in the future, when posting bugs here or to any project. please provide as much info as you can that could be helpful. At a minimum, you should always indicate what version of this project you are using. And it is often relevant to include mod pack information as wel
