### ISSUE TITLE
Expose computer.beep(pattern)

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#2716]
https://github.com/MightyPirates/OpenComputers/blob/d5f1280fc9c9f463c45eff76119cfc513d8c3fd5/src/main/java/li/cil/oc/api/machine/Machine.java#L180-L181

This doesn't seem to be exposed to the LUA Api, would be cool.

As seen here:
![Pic](https://cdn.discordapp.com/attachments/125649403162656768/397818963159154688/unknown.png)

**Comment by payonel** [comment]
good catch, @Inari-Whitebear 
the change will be here: https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/machine/Machine.scala#L423
right now that code is assuming nil or int, needs to allow for the string pattern too
