### ISSUE TITLE
Multiple Adapters with same block type

### ISSUE THREAD

**Issue by caine717** [MightyPirates/OpenComputers#2717]
Is there a way to use all adapters with the same type/label with a single call?

**Comment by payonel** [comment]
I'm not certain what you are asking. Can you be more specific? But I'll predict the answer is no, we don't have a way to use multiple proxies in a single call

**Comment by caine717** [comment]
To be more specific: I have a row of railcrafts locomotive tracks, where I want to change the mode of, but I can just call the setMode method of the primary one. I would like to call the setMode method of all connected adapters with a locomotive track on it.
I tried to use a for each loop to call the method but it doesn't find the setMode method.

**Comment by payonel** [comment]
1. no you can't call a method at the same time on a collection of proxies, you would need to loop on them like you are trying to do
2. i would need to see your code to see why it is failing, please share

**Comment by payonel** [comment]
i'll close with this comment, the code will be similar to this

```
for track_addr in ipairs(component.list("locomotive_track")) do
  local proxy = component.proxy(track_addr)
  if proxy then
    proxy.setMode(mode)
  end
end
```
