### ISSUE TITLE
[AE2 Integration] Certain filters for getItemsInNetwork(filter) do not work

### ISSUE THREAD

**Issue by foltik** [MightyPirates/OpenComputers#2718]
![Setup to reproduce](https://i.shimapan.rocks/jitjmg.png)
Setup to reproduce. Any computer with an adapter on an ME interface will do.
![ME Contents](https://i.shimapan.rocks/dasepb.png)
The ME system has a few blocks in it, including Stone.
![Test Program](https://i.shimapan.rocks/vkheey.png)
The test program, filtering by label and name should both properly return the contained stone. [Pastebin](https://pastebin.com/iD7aw60b)
![Program Output](https://i.shimapan.rocks/vgbonb.png)
As you can see, the label filter properly returns the stone, but the name filter does not work at all, even though it is clearly shown above as matching. Manually walking the table and checking every item will work for checking by name, but the filter does not.

OpenComputers Version: MC1.12.1-1.7.1.43
AE2 Version: rv5-stable-3

**Comment by LordTerbium** [comment]
I have a similar problem:
Filtering getCraftables(filter) with label or name does not work. Trying to find the sticks pattern in my network. Going manually through the table finds it.
![2018-01-05_01 46 48](https://user-images.githubusercontent.com/6330838/34591132-9a9340be-f1bb-11e7-9d0c-fcfc7fb4d72e.png)
The result of the test program
![2018-01-05_01 47 08](https://user-images.githubusercontent.com/6330838/34591133-9ab00b9a-f1bb-11e7-9b67-45ef4cce5023.png)
The program
![2018-01-05_01 47 43](https://user-images.githubusercontent.com/6330838/34591134-9ac9b7e8-f1bb-11e7-9c11-4f6199d0011e.png)
Proof of a sticks crafting pattern in the network.

Can confirm that getItemsInNetwork(filter) does only work with labels. But that is fine for me. getCraftables(filter) is not working at all.

OpenComputers Version: MC1.12.1-1.7.1.43
AE2 Version: rv5-stable-3

**Comment by jackrh** [comment]
I had this same issue and it sounded very similar to https://github.com/MightyPirates/OpenComputers/issues/2674
So I grabbed the latest build off their Jenkins server (OpenComputers-MC1.12.1-1.7.1.52) and it fixed my issue with getCraftables.

**Comment by hohserg1** [comment]
I have similar problem
Build:
![image](https://user-images.githubusercontent.com/35610168/72204963-a36c3700-348e-11ea-8544-48b88356b439.png)
Storage contains one cell and cell contains some items
Test and result:
![image](https://user-images.githubusercontent.com/35610168/72204976-ca2a6d80-348e-11ea-9543-4b05dcf63308.png)

**Comment by payonel** [comment]
make sure youre using our latest release that included the fix from this issue. make a new ticket with the oc version and ae version if you feel you are doing it correctly and it isn't working

**Comment by hohserg1** [comment]
yeah! this bug are fixed in last version
