### ISSUE TITLE
3d models from minecraft json files

### ISSUE THREAD

**Issue by mainrs** [MightyPirates/OpenComputers#2719]
I am not sure where to ask for this so just close the issue if it doesn't fit.
Is there any way to print minecraft json models? I made some custom ones using Cubik but I can't find any way to actually print them using the 3d printer.

**Comment by skyem123** [comment]
You'd need to write code that converts the file from whatever format Minecraft uses to whatever format this one uses. It's probably not impossible but also likely to be quite tricky. For one thing, OC doesn't use textures directly, it uses block names to get the texture from, I think.

**Comment by payonel** [comment]
our custom 3dm format is explained a bit by this example provided by sangar: https://github.com/OpenPrograms/Sangar-Programs/blob/master/models/example.3dm
