### ISSUE TITLE
OPPM not properly updating package

### ISSUE THREAD

**Issue by mainrs** [MightyPirates/OpenComputers#2720]
I have added my repo to the `/etc/oppm.cfg` file installing the package worked without any problems. The program can be started. But it had some syntax errors. So I pushed an updated version to github and tried to run `oppm update <package>`. But that didn't do anything. The same syntax error still happened.
Uninstalling the package, rebooting and installing again only works for me :(
Here is the repo I set up: https://github.com/SirWindfield/opencomputers-programs
And my config file:
```lua
{
    path = "/usr",
    repos = {
        ["SirWindfield/opencomputers-programs"] = {
            ["elevator"] = {
                ["files"] = {
                    ["master/elevator/elevator.lua"] = "/bin"
                },
                ["repo"] = "tree/master/elevator",
                ["name"] = "SirWindfield's Elevator Code",
                ["description"] = "Controls various elevators across my underwater base",
                ["authors"] = "SirWindfield"
            }
        }
    }
}
```
  
**Edit:** I posted this on the IRC channel but nobody answered over there.

**Comment by Vexatos** [comment]
Can you reproduce this if you wait, I don't know, five or ten minutes after the push to your github repository before running `oppm update`? The Github API is sometimes _extremely_ slow, which would cause `oppm update` to just pull the old version until github realizes that it changed.

**Comment by mainrs** [comment]
That actually fixed the issue. Pretty strange, because the url that oppm uses (`raw.githubcontent.com`) updates immedietly after pushing the code changes.
Well, sorry for bothering you guys then!
