### ISSUE TITLE
Computer not turning on and causing me to be kicked from the server in FTB Revelations v1.2.0

### ISSUE THREAD

**Issue by 1matto** [MightyPirates/OpenComputers#2723]
Having issues with open computers in the latest ftb pack update

**Comment by payonel** [comment]
please ask the server admin for logs

**Comment by payonel** [comment]
also, please retest with your same pack whether you can turn on a computer in single player
also, what version of oc is this (give the full filename)

**Comment by 1matto** [comment]
admin says the logs weren't coming up but we will try again

**Comment by 1matto** [comment]
[2018-01-10-1.log](https://github.com/MightyPirates/OpenComputers/files/1617464/2018-01-10-1.log)

**Comment by payonel** [comment]
@1matto sorry, but that log doesn't have opencomputer crash info
also, you didn't give me the oc version you are using
we recently have a fix for 1.12, if you can retest with our latest 1.12 build and let us know if that resolves the problem, that would be great
http://ci.cil.li/job/OpenComputers-MC1.12/

**Comment by payonel** [comment]
closing no repro, no more info from user
might be fixed in latest
