### ISSUE TITLE
getStackInSlot() doesn't return documented item table

### ISSUE THREAD

**Issue by gurland** [MightyPirates/OpenComputers#2724]
Sample code:
```lua
local component = require("component")
local inv = component.inventory_controller

local chest_slots = inv.getInventorySize(sides.top)
if not chest_slots then return nil end -- Check if there is chest

for slot = 1, chest_slots do
  local item = inv.getStackInSlot(sides.top, slot)
  if item then
    io.write(""..item.id) -- Returns error, because this field is nil
  end
end
```

So then I wanted to get all keys from `item` table.
Code:
```lua
if item then
  for k,v in pairs(item) do
    io.write(k.."\n")
  end
end
```
And the result was obviously as on this picture
![image](https://user-images.githubusercontent.com/30530987/34900935-08edbc7c-f80d-11e7-9f8b-9b0090bfd339.png)
There is no id field! But look here:
![image](https://user-images.githubusercontent.com/30530987/34900951-2b162b68-f80d-11e7-8db6-ff3be34c2ad1.png)

Minecraft: 1.7.10
Forge: 10.13.4.1558
OpenComputers: 1.7.0.1085

**Comment by thiakil** [comment]
Check your config. I believe the option to expose the internal id is disabled by default, as it tends to be a bit controversial

**Comment by gurland** [comment]
The chest above in addition contains only one stack of stone. No items from other mods.

**Comment by brisingraerowing** [comment]
As noted in the docs, the existence of the id field depends on configuration. It is likely disabled in your config file.

**Comment by gurland** [comment]
@BrisingrAerowing, it would be great if you help me find right setting.
All I found is `allowItemStackInspection=true`.

**Comment by brisingraerowing** [comment]
Is there any particular reason you need the numeric ID?

Also, I'm not at my computer right now, so I can't help you there.

**Comment by gurland** [comment]
@BrisingrAerowing Yeah. I want to make item sorting robot.

**Comment by brisingraerowing** [comment]
Using the `name` attribute might be a better bet, as that usually doesn't change across servers. It will return, e.g. `minecraft:furnace` for a furnace. For using the numeric ids you want the insertIDsInConverters setting. You may also want to look at the database component.

**Comment by payonel** [comment]
the config option you are looking for is
`insertIdsInConverters=false`
change that to
`insertIdsInConverters=true`

But, as @BrisingrAerowing said, I recommend you use the `name` field instead

**Comment by payonel** [comment]
also, i've updated the docs:

![image](https://user-images.githubusercontent.com/6590223/36078586-8f098dc2-0f2d-11e8-987a-9edd4bb027b4.png)
