### ISSUE TITLE
component.crafting.craft() works once but breaks recipe until server restart

### ISSUE THREAD

**Issue by Kaeteker** [MightyPirates/OpenComputers#2728]
I'm using a mining script that automatically compresses redstone, diamonds, etc, and I noticed that the mining robot was only ever making one block of each type. I did some tests to figure out why, and discovered that the robot will only craft one item (no matter how many you requested it to craft) and then the recipe breaks completely and it will just return "true  0". To make matters weirder, it doesn't just break the recipe for the robot, it breaks it for ME! After the robot has crafted a recipe, that recipe stops showing any output if I put it into a crafting grid normally with my character, and I can't craft it. Restarting the server fixes the recipe, but having the robot craft it again breaks it. Disconnecting and reconnecting my client does not fix it. I have not tested whether it breaks the recipe for everyone on the server or just me.

Can anyone else reproduce this?

I'm playing on minecraft 1.12.2 with the direwolf20 1.7.1 modpack (this issue happened with direwolf20 1.5.0 too, haven't tested versions previous to that)

**Comment by payonel** [comment]
can you test with our dev build: http://ci.cil.li/job/OpenComputers-MC1.12/
The effect this bug has on crafting with elsewhere is pretty weird, but nonetheless, I've changed how the robot crafting works in 1.12, and I hope it is better now.
Thanks

**Comment by Kaeteker** [comment]
I tested the latest dev build and the issue is resolved.
Thanks!
