### ISSUE TITLE
[1.12.2] Transposer doesn't work correct with RfTools Workbench

### ISSUE THREAD

**Issue by darkman1984** [MightyPirates/OpenComputers#2729]
Hi!

Problem:
Tried to input an item through a transposer into the workbench from RfTools on top inside the  pattern grid (3x3) for crafting. 

Slot 1 is working, but Slot 2-9 response with Invalid Slot.

Command Usage:
transposer.transferItem(sides.north, sides.down, 1, 1, 2)
sides.north = Chest
sides.down = Workbench

Version: 1.7.1.43

Thx
DaRkMaN

**Comment by payonel** [comment]
this is now working. I likely fixed this with: 58d3c6b45cc768d39d147bfcb6e0ba9b29594ef9
