### ISSUE TITLE
Server Rack "missing component"

### ISSUE THREAD

**Issue by ToXeye** [MightyPirates/OpenComputers#273]
For a server rack with a server installed in it, when trying to turn on the power, it says that there is no RAM or no CPU installed in it. So it doesn't turn on.

**Comment by ToXeye** [comment]
"No RAM is installed in the computer." is the message to the player.

**Comment by Wuerfel21** [comment]
Have you actualy put them into the server?

**Comment by ToXeye** [comment]
If you mean the RAM or the CPU then no. The server is in the slot, the server displays as a 3d server in the rack-block. If I put multiple servers in, then different servers alternate between saying there's no RAM or CPU when I press the power button for each of the servers.

**Comment by ToXeye** [comment]
Forge, OC and OpenComponents are updated.

**Comment by Wuerfel21** [comment]
Right click with the server in hand

**Comment by ToXeye** [comment]
Not solved.

**Comment by fnuecke** [comment]
As he said, open the actual server by rightclicking while holding it in your hand, then put in the components (RAM, CPU, ...). After that put it back into the rack.
