### ISSUE TITLE
No Inventory returned when on a GPP claim using getInventorySize()

### ISSUE THREAD

**Issue by Idlehumor** [MightyPirates/OpenComputers#2730]
When I run the method getInventorySize() from a robot where there is no claim, I get the inventory size like normal.

When I try to getInventorySize() with a robot inside a claim, it returns "no inventory". 

I've already trusted the fake player #[opencomputers] and tried /autotrust on the GPP claim and it can break blocks, but still cannot access inventories. OC version 1.7.1.1127 for MC 1.7.10

GPP is Grief Prevention Plus
I've sent a bug report to the Grief Prevention Plus github as well: KaiKikuchi/GriefPreventionPlus#156

Edit: I can use tank controllers just fine inside and outside of a claim, so I'm thinking this is related to OC rather than the grief prevention plus

**Comment by Idlehumor** [comment]
I've sent a bug report to the Grief Prevention Plus github as well: https://github.com/KaiKikuchi/GriefPreventionPlus/issues/156

**Comment by payonel** [comment]
related to #2706
currently no plans to fix this (I'm not saying we won't, it's just not coming soon)
I'll leave as open for adoption, it's somewhat a feature request

**Comment by Idlehumor** [comment]
Well it looks like the fake player name is case sensitive. I found somewhere that it was all lowercase [opencomputers], where infact it's [OpenComputers].

So for anyone having this problem with GPP, the command is /trust #[OpenComputers]

**Comment by skyem123** [comment]
Hmm... maybe there should be a document with a list of known things that are annoying but aren't bugs.
@payonel, something for the big documentation issue? :P

**Comment by payonel** [comment]
this page could add notes about GPP: http://ocdoc.cil.li/crossmod_interoperation
