### ISSUE TITLE
[1.12.2] Computer don't use the whole screen?

### ISSUE THREAD

**Issue by darkman1984** [MightyPirates/OpenComputers#2731]
Hi!

I really don't know how i can fix that but no Screen (Tier 1,2 or 3) is using the whole screen. I have everytime a black border on top and bottom.

Sample Pic
https://imgur.com/a/2NJRj

What can i do?

Version: 1.7.1.43

Greetings
DaRkMaN

**Comment by payonel** [comment]
The rendered font aspect ratio doesn't change, regardless of the aspect ratio of the multiblock screen
You have two options:
1. change the resolution (see gpu.setResoltuion() or use the command line tool to change the resolution, `resolution` to match the multiblock aspect
or
2. use an equivalent number of screens in  your multiblock to match the aspect ratio of the rendered font

The font is not 1x1

Here is the tier 2 screen with native resolution 80x25
![image](https://user-images.githubusercontent.com/6590223/35252024-3aacdca6-ff93-11e7-85da-e3152599b96f.png)

Using 6 screens, 3 wide and 2 tall, will fill the screen with a native resolution
![image](https://user-images.githubusercontent.com/6590223/35252067-74a3157e-ff93-11e7-96ad-8648b67d2717.png)
