### ISSUE TITLE
Open Computer error

### ISSUE THREAD

**Issue by SoCalAbsol** [MightyPirates/OpenComputers#2738]
I think I built my computer correctly but I keep getting the error "Unrecoverable Error no bootable medium found: /init.lua"

What could the issue be?

![opencomputer error](https://user-images.githubusercontent.com/36123108/35774819-ee4ce0da-092f-11e8-8085-8d44ebe284ff.png)

its powered wirelessly from behind

**Comment by S0ZDATEL** [comment]
You inserted in the disk drive blank floppy disk? You need to insert the floppy with the system, such as OpenOS.

**Comment by payonel** [comment]
you're using a blank floppy (just like @S0ZDATEL said) you need to craft the operating system install disk using that blank floppy and the open computer manual

http://ocdoc.cil.li/item:openos_floppy
