### ISSUE TITLE
He will not accept the items of felled trees

### ISSUE THREAD

**Issue by tuckypetr** [MightyPirates/OpenComputers#2739]
The robot does not accept any degraded tree blocks in tree harvesting. He throws them into the world and does not save the inventory. With the same program, but the extracted blocks of stone receive, it will be stored in the inventory. Uses tools from Industrial Craft 2. Tested without the tool, but with the same result. forge-1.12.2-14.23.1.2555, MC 1.12.2, OpenComputers-MC1.12.1-1.7.1.43

**Comment by payonel** [comment]
if you are breaking multiple blocks the robot isn't going to recover all of them. try sucking the blocks after you cut the tree down.

**Comment by tuckypetr** [comment]
I tried to win the downhill, unfortunately with the same result. interesting that the leaves take, but never wood and does not matter what it is. I will try to create a video.

**Comment by tuckypetr** [comment]
https://youtu.be/sxLpNhfZ7R0
https://youtu.be/ANEep8jU434
https://youtu.be/F_EGR3mHYaI
As you can see from the video, it's a stone, but never wood

**Comment by tuckypetr** [comment]
Error found. It was Techreborn
