### ISSUE TITLE
Gregtech Adapter

### ISSUE THREAD

**Issue by tomasbrod** [MightyPirates/OpenComputers#2740]
I'd like to ask for support of reading information from gregtech machines via the Adapter. API for this is in form of interface `gregtech.api.interfaces.tileentity.IGregTechDeviceInformation` method `getInfoData()`.

Nuclear Control mod is using that api via a sensor card.

Currently only power and steam(?) information can be read using the adapter, implemented in [driver here](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/integration/gregtech/DriverEnergyContainer.java).

I can try to implement it but I am lost in what should be done to make it do. Can I modify that file to use `IGregTechDeviceInformation` api and submit a pull request? Or need to make an addon mod?

**Comment by Vexatos** [comment]
On Minecraft 1.7.10, GregTech support for that interface is provided in Computronics, along with a couple of other GregTech-related drivers.

**Comment by tomasbrod** [comment]
Oh, thank you. I somehow missed the whole "Computronics" mod.
