### ISSUE TITLE
Issues when trying to write "[", "]" and "}"

### ISSUE THREAD

**Issue by Krafter166** [MightyPirates/OpenComputers#2741]
I'm using a Croatian keyboard and for writing the characters "[", "]" and "}", in the text editor in computers, I need to use the key combination AltGr (that's basically Ctrl+Alt) and F, G or N. While doing so, the find tool get's activated. I could understand that this would apply to AltGr+F (Ctrl+Alt+F) since the key combination for the find tool is Ctrl+F. Because that I'm forced to paste those characters all the time and that gets annoying after a while. If you could, change the key combination to something else.

Until that gets fixed in a new update, is there a way to fix this manually? Like, is it possible to change the key combinations for the find tool?

Thanks in advance.

**Comment by payonel** [comment]
@Krafter166 I could probably make the hot key selection a bit smarter, but in the meantime you can edit your `/etc/edit.cfg` and customize the hotkeys yourself

**Comment by payonel** [comment]
@Krafter166 https://github.com/MightyPirates/OpenComputers/commit/6fd7fc07e1a272c772db8ba9946e19e263ac54fc probably helps your situation. It makes ALT+CONTROL+F not match CONTROL+F
It's all or nothing match for key combos

but like I said, review your /etc/edit.cfg if you want to make more changes to hotkeys
