### ISSUE TITLE
[Suggestion] Track who placed robots and use it with the FakePlayer

### ISSUE THREAD

**Issue by Lemmmy** [MightyPirates/OpenComputers#2742]
This is similar to [SquidDev-CC/CC-Tweaked#8](https://github.com/SquidDev-CC/CC-Tweaked/issues/8). Robots appear to be using a generic FakePlayer. The result of this is that mods listening to events for robots are receiving data inconsistent with that of real players. The suggestion is to make them track the UUIDs of the players who placed them, build a GameProfile based on it, and use that to construct FakePlayers per robot.

A consequence of the current behaviour is that robots placed on SpongeForge servers running any version of SpongeAPI greater than 7.0 do not inherit the permissions of the player who placed them at all. This means that players can use robots to grief in GriefPrevention claims, or are unable to give their own robots specific permissions in their claims. This is because SpongeAPI 7.0 introduced a rehaul to the event tracker system, and they no longer track who placed blocks for permission inheritance. Due to the use of the generic FakePlayer, there is no way for Sponge or GriefPrevention to track which player placed the robot.

My apologies if this is a false claim - however this is the only conclusion I am able to draw from the debugging data I have access to.

**Comment by Eufranio** [comment]
Sponge is and has always been able to track the owner of FakePlayers correctly (on most cases), but there's a bug in the current tracker. While that's a good suggestion, I'd not have only GriefPrevention/Sponge as a reason for this change: ANY other mod listening to build events are going to break by using generic events, like Minecolonies (which protects colonies land), FTBUtils (allowing generic fake players or none at all on claims), etc.
