### ISSUE TITLE
New PRs should be in Java

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#2745]
I think it would help to request new PRs to be written in Java whenever possible.

**Comment by SaphireLattice** [comment]
Uh, why? OC is Scala, and only API is Java and certain parts, AFAIK.

**Comment by SoniEx2** [comment]
And it was still stuck on 1.7.10 last time I checked.

And there are complaints about it being in scala.

And there are other issues.

Easiest way to move away from scala? Request new PRs to be Java.

**Comment by Techokami** [comment]
Uh, OC is not stuck on 1.7.10. It is on 1.12.2 while still being mostly in Scala. Have you tried changing the branch on the repo? The default branch is 1.7.10 but there are branches for fully functional ports to later versions of Minecraft.

**Comment by payonel** [comment]
This is a policy request of our PR approvals, not a bug nor an issue against the existing code base.
I'm fine with scala PRs, in fact, if a submitter is unsure, I would prefer they use the language that most closely interacts with the change/additions they are making.
