### ISSUE TITLE
The geolazer doesn't return a metadata

### ISSUE THREAD

**Issue by Litvinosss** [MightyPirates/OpenComputers#2746]
`component.geolyzer.analyze(side)` doesn't return a block metadata.
I use:
MC 1.12.2
OC 1.12.1-1.7.1.54
Forge 14.23.2.2615
![2018-02-11_17 15 37](https://user-images.githubusercontent.com/32991055/36075615-15ad9af4-0f5a-11e8-9722-f5d324c9fb23.png)
![2018-02-11_17 16 13](https://user-images.githubusercontent.com/32991055/36075632-52e086fc-0f5a-11e8-9fe9-0827ac3faf84.png)

**Comment by xarses** [comment]
What are you expecting it to return?

**Comment by Litvinosss** [comment]
@xarses Previously using geolyzer it was possible to obtain data by which it was possible to recognize the presence of latex on Hevea from the mode IC2. In version MC 1.7.10, OC 1.7.10-1.7.1.1127, Forge 10.13.4.1614 `component.geolyzer.analyze(side)` returns a table that has the item "metadata". Below are screenshots that demonstrate this
![2018-02-12_17 38 11](https://user-images.githubusercontent.com/32991055/36104814-b73f8fc8-101b-11e8-9dac-40f60a4c9ddf.png)
![2018-02-12_17 38 44](https://user-images.githubusercontent.com/32991055/36105536-897c0b46-101d-11e8-99a2-5073d162f916.png)
![2018-02-12_17 39 05](https://user-images.githubusercontent.com/32991055/36106130-26c98490-101f-11e8-9870-f4f939b43470.png)
I don't know, maybe something has changed in the mechanics of the work of Minecraft and now one can't get metadata blocks

**Comment by brisingraerowing** [comment]
The addition of metadata seems to have been removed in [this commit](https://github.com/MightyPirates/OpenComputers/commit/d0e0baac98d2f9b53a70afbaec20f1e141cb63d9#diff-21000ccbba641efa7b00226d0f450b03) by @fnuecke. I would think that's a mistake and it needs to be added back.

**Comment by fnuecke** [comment]
99% sure that was because there's the block property system now. If this comes back, IMHO it should be in that format, i.e. a table of key-value pairs of the properties and their string serialized value (e.g. `{wood_type="oak"}` or whatever it is for logs/stairs/etc). Or in other words, a Lua table representation of what you see in F3 bottom right when looking at the block in question.

**Comment by brisingraerowing** [comment]
That would probably be the best route to go, considering that 1.13 is removing the numeric metadata / id stuff.

**Comment by payonel** [comment]
closed with https://github.com/MightyPirates/OpenComputers/pull/2896
