### ISSUE TITLE
About "&" background tasks

### ISSUE THREAD

**Issue by CitrusSin** [MightyPirates/OpenComputers#2747]
I tried to run "lua &" to test the "&" but it failed. i think some tasks needs to run in the background such as the "oppm", especially when your network speed is slow.

**Comment by payonel** [comment]
openos doesn't have background support neither through specifying & nor by using control+z

also, putting oppm in the background would have no benefit based on your network speed

openos does have the ability to run processes in the background such as by using detached threads (see http://ocdoc.cil.li/api:thread ), event listeners (see http://ocdoc.cil.li/api:event ), or by using the rc system (see http://ocdoc.cil.li/api:rc ) [ the rc wiki page has been incomplete for a long time, one day we'll update it ]

**Comment by CitrusSin** [comment]
I means i can do other things during the oppm is running....

**Comment by payonel** [comment]
correct, we don't have support for that unless you write a program that runs oppm in a thread, see the thread api

but this isn't something that is necessarily gonig to work with just any program, and there is no command line support for it

**Comment by CitrusSin** [comment]
Oh, now I know. Thanks for your reply!

**Comment by DCNick3** [comment]
Hmm, but isn't OC design is purely one-task with no async operations? Like, when you invoke component function it just blocks all code for some time, right?

**Comment by payonel** [comment]
openos supports concurrency, just not parallel execution
Every time you pullSignal (or sleep, or even.pull, etc) the os is switching processes and executing things in the background, and eventually returning execution to your process
If you use the openos thread api or event listeners, you can hook into this scheduler
