### ISSUE TITLE
Using converters recursively

### ISSUE THREAD

**Issue by marcin212** [MightyPirates/OpenComputers#275]
It is not possible to access 

``` scala
def convert(value: Array[AnyRef])
```

 so converting fields recursively would be a really nice feature.

It is a simple change.
At [Registry.scala](https://github.com/MightyPirates/OpenComputers/blob/master/src/main/scala/li/cil/oc/server/driver/Registry.scala#L106)
change 

``` scala
else result
```

  to  

``` scala
else convertRecursively(result)
```

**Comment by Wuerfel21** [comment]
Why do you not do it and pull-request it?

**Comment by marcin212** [comment]
I am not sure this is correct way to do it. I don't want to mess things up. :)

**Comment by SpiritedDusty** [comment]
If it's not the correct way to do it, then Sangar won't accept the pull request. No harm.

**Comment by fnuecke** [comment]
That would be the right spot to add it, yes. However in that case I'd also like to add a proper check for cycles to avoid infinite loops. Ideally that would then also make identical objects on the Java side pop up as identical on the Lua side, but that kinda stands and falls with how JNLua's map->table conversion works.

If I find the time I'll have a look into adding it for 1.3. Might not make it into the first prerelease, but possibly the first release. Feel invited to PR that; even if I won't merge it as-is, it'd speed things up for sure :-)

**Comment by Kubuxu** [comment]
What you mean by the second part?
The protection shall be a cyclic reference detection or just a flat recurrence depth limit, like 100?

**Comment by fnuecke** [comment]
I imagine tracking the processed objects to avoid the cycles using a lookup from a map instead of actually doing a recursive call again - leaving one with the identical converted object for the identical source object.
