### ISSUE TITLE
Error booting OpenOS from hard drives in OC devices

### ISSUE THREAD

**Issue by ArsiTheFox** [MightyPirates/OpenComputers#2754]
Currently I am in my modded Minecraft server and have been having a few issues with OC and it's boot os.... This doesn't happen in single player but when I try to boot up an OC device this error shows: https://oc.cil.li/uploads/monthly_2018_02/javaw_2018-02-19_16-37-03.png.6e22512094f18909e8c323beadad0308.png

I have trying to resolve this issue but can't seem to fix it..... I need your guys help please.......

Mod version: OpenComputers-MC1.7.10-1.7.1.1127-universal

**Comment by payonel** [comment]
@GamesArsenal96 I'm going to need more information to help you.
You say, "an oc device"
Does this happen on all oc machines?
Can you reinstall openos on that machine?
Does this happen if you boot from the openos floppy?

If this does not repro with the openos floppy disk, then it sounds like someone has modified and broken the openos boot sequence on that device.

**Comment by ArsiTheFox** [comment]
Testing it right now I found a config

**Comment by ArsiTheFox** [comment]
Basically I am inserting a hard drive into a computer installing OpenOS onto it... then placing the hard drive into a robot then it errors out:
![javaw_2018-02-19_22-03-40](https://user-images.githubusercontent.com/24835664/36407072-32ab1132-15c1-11e8-99d4-f60a3bbcbcfb.png)

**Comment by ArsiTheFox** [comment]
It also just failed on a normal computer: 
![image](https://user-images.githubusercontent.com/24835664/36407109-78cde234-15c1-11e8-8c39-5bf2f7bd8594.png)

**Comment by payonel** [comment]
this does not repro for me
i even tested the same exact build you are using, I tested on a server, I even tested installing openos with machines that are low on memory - it does not fail, let alone fail in the way you are presenting

It definitely appears that your openos installations are corrupted, or were not completed, as if the hard disks were taken out of the machines before the install completed. I have never seen this type of failure before with one of our official builds

If you would like me to investigate further, I'll probably have to join your world and poke around. Please send the mod info and server address to me in a private(direct) message in our irc channel: https://webchat.esper.net/?channels=oc

**Comment by ArsiTheFox** [comment]
I didn't edit the OpenOS floppy in anyway

**Comment by payonel** [comment]
I will not be able to fix this without a copy of (or visit to) your world (and modpack details), sorry.

**Comment by ArsiTheFox** [comment]
Sorry for the late replies...
Ok I am sending you my details

**Comment by ArsiTheFox** [comment]
Check the IRC

**Comment by ArsiTheFox** [comment]
I messaged you

**Comment by payonel** [comment]
Thank you, I have the server info now so I'll add this bug to our 1.7.2 release milestone

**Comment by payonel** [comment]
Thanks to @GamesArsenal96 and his friend, a-one, and some testing on their server, we found that this was actually due to some server security software that blocked writings to files anywhere in the real host filesystem under directories named `boot`, and it so happens that openos creates a dir named `boot`, and writes some rather important boot files to.

No OC code change will be made to fix this, they were able to resolve this by adjusting their security software settings.

Thanks guy!
