### ISSUE TITLE
Suggestion- More Features!

### ISSUE THREAD

**Issue by CTH999** [MightyPirates/OpenComputers#2756]
Suggestions!

1. Light is faster than Electrons. So, there should be Fiber Optics that are faster, but can't transmit power. (The difference should be nglible, but still there! Great for massive cables, if you make it take time to move)

2. Infrared Laser- A Wireless data transfer that's as fast as fiber optics. However, it has 0 loss instead of very low, and it also needs line of sight! Also, walking through it stops the beam, allowing a sensor system to be mad!

3. This goes with the above one. It would add in mirrs to reflect Infrared Light, allowing corners. For a lot of loss! (Great for Sensor Networks)

4. Radio Transmitter- A Multi-Frequency Radio Transmitter. For all your hacking/ long range/ sort range communication needs! (Would need to have the frequency programed in! For extra security, make it rotate around!)

5. Solid State Drive- A Faster drive, but with less storage. Tier 3 only!

6. Mag-Cards- A security card that you program in, then you can "swipe" (Click) On the mag-card reader, you to check it! Great for: Security, personal cards, and more!

7. RF-Id Chips- A Wirless version of the Mag-Card. All you have to do is program something in it, walk near the scanner, and It scans it any where in your inventory (Or a slot for the drones /robots)

8. Cameras- A Camera that's completely controllable/ automatable, and can save data in a disk, or transmit it/ transfer it to a screen/ screens for you to see! Allowing remote surveillance!

9. Speaker- Allowing you to select a voice to use, and "Speak" (using text) into it. Then, in a small area, (Configurable and programmable. Larger areas are louder nearby and need power. Also, some blocks block sound (Stone) Absorb (Wool) Distort (Water) And more!) Can also be used in a phone for actual sound!

10. Microphone- Translates sound from the speaker code, which is used to make text/ power another speaker, to reproduce about what the microphone heard. Put speaker on on voice: none to make this work! (Works in phones for talking!) Also picks up chat in a sort radius, and uses Voice: Normal.

These are all just suggestions. It's your mod after all, so you decide which/ any to use!

**Comment by payonel** [comment]
extending the base set of features is the ideal place for add-ons. For example, Computronics provides more drive options, OpenRadio provides speaks and audio drives, look into OpenLights, OpenPrinters, OpenSecurity, etc

I appreciate your suggestions, and they are quite interesting. But they are best suited for add-ons.

**Comment by CTH999** [comment]
Ok, fair enough! They are just suggestion! Thanks for looking at this!

**Comment by Techokami** [comment]
OpenFM provides radio stuff; OpenRadio provides optical communications stuff; Computronics adds Speakers, Sound Cards, a TTS engine, and lots of other stuff; OpenPrinters adds a printer; OpenSecurity adds RFID and MagStripe stuff.

Basically, what you're looking for are the addon mods! Though I don't think they've jumped past 1.10.2 yet, aside from Computronics.

**Comment by CTH999** [comment]
@Techokami Exactly!

That's why I said it's just a _suggestion_

It would be nice if it was in the mod, but I don't think that will happen :)
