### ISSUE TITLE
[Severe Bug]Disabling Crafting Recipes with the Robot

### ISSUE THREAD

**Issue by Ninsa** [MightyPirates/OpenComputers#2757]
Hello, I am part of the StaffTeam from a Network.
I'Ve encountered a severe Bug with the Robot:

When a Robot, given that it has the crafting recipe, tries to craft something, it only can craft this recipe once.
There is no way to craft a recipe more than that. But not only that:
This crafting recipe, lets say, Stone Button, cannot be crafted **anywhere** on the Server. It does not matter where you try it, vanilla Workbench or ME System, nor who does it or in what Dimension you craft it. It is completely disabled

![grafik](https://user-images.githubusercontent.com/36482870/36502960-d2e2cb14-174b-11e8-862a-c9fd9d906738.png)

It can only be resolved with a server Restart.

Sadly I cannot provide the exact code used since we nuked the robot.
![grafik](https://user-images.githubusercontent.com/36482870/36502945-c5685116-174b-11e8-8918-15629f61c839.png)

the Modpack used is Revelation 1.3.0

Tag me if you need to know more

**Comment by payonel** [comment]
which oc build are you using?

**Comment by Ninsa** [comment]
OpenComputers-MC1.12.1-1.7.1.43

**Comment by payonel** [comment]
**that's an old build**
please retest with
http://ci.cil.li/job/OpenComputers-MC1.12/60/artifact/build/libs/OpenComputers-MC1.12.2-1.7.1.60.jar

can you test with JUST oc in a single player world?
let me know if it repros
This area of code is actually currently under review for another purpose and I would be glad to add another fix if we can confirm
Thanks

**Comment by payonel** [comment]
pretty sure this is a dup of #2728
I'll close unless you report otherwise (latest dev build should resolve it for you)
we are expecting an official release on curse again soon
