### ISSUE TITLE
Error starting with spongeforge MC version 1.12.2

### ISSUE THREAD

**Issue by pfigueiredo** [MightyPirates/OpenComputers#2758]
OS: centOS 7, 
java version:

openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

mods and sponge plugins installed:

`CoFHCore-1.12.2-4.3.10.5-universal.jar
CoFHWorld-1.12.2-1.1.1.12-universal.jar
CodeChickenLib-1.12.2-3.1.5.331-universal.jar
LuckPerms-Sponge-4.0.60.jar
Nations-2.8-S6.1-MC1.11.2.jar
Nucleus-1.3.1-S7.0-MC1.12.2-plugin.jar
OpenComputers-MC1.12.1-1.7.1.43.jar
RedstoneArsenal-1.12.2-2.3.10.4-universal.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
ThermalCultivation-1.12.2-0.1.5.3-universal.jar
ThermalDynamics-1.12.2-2.3.10.4-universal.jar
ThermalExpansion-1.12.2-5.3.10.15-universal.jar
ThermalFoundation-1.12.2-2.3.10.6-universal.jar
TotalEconomy-1.7.1.jar
appliedenergistics2-rv5-stable-8.jar
griefprevention-1.12.2-4.3.0.554.jar
projectcore-7.0.0-0.2.1.jar
projectportals-7.1.0-0.14.3.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2931.jar
worldedit-sponge-6.1.9-SNAPSHOT-dist.jar`

[fml-server-latest.log](https://github.com/MightyPirates/OpenComputers/files/1756060/fml-server-latest.log)

**Comment by payonel** [comment]
right now this seems to be an incompatability with spongeforge
a solution suggested to me was to look into adding oc to an TransformerExclusions list

**Comment by pfigueiredo** [comment]
Ok nice. w8ting for a next build to solve this as I wanted to start a server with spongeforce and a few mods including OC that I absolutely adore.

**Comment by clecle253** [comment]
i have the same issue someone get a solution ?

**Comment by Wolfgang071** [comment]
same problem for me

**Comment by payonel** [comment]
we don't support spongeforge compatibility
but, feel free to upload/attach a modpack where this is easily reproducible with repro steps and there is a better chance i'll take a look
note, i've tested oc 1.12 1.7.5 with spongeforge and "it worked for me"(tm)

**Comment by tie** [comment]
Can confirm that [ForgeMixinFix](https://curseforge.com/minecraft/mc-mods/forge-mixin-fix) mod fixes the issue (at least in case of #3183) by excluding Scala classes. Should work with an outdated SpongeForge too.

**Comment by payonel** [comment]
work around provided
