### ISSUE TITLE
[Issue?] File - re-execute causes to fail

### ISSUE THREAD

**Issue by accessdenied0** [MightyPirates/OpenComputers#2759]
MC-version: 1.12.2
OC-version: 1.7.1.43
Forge-version: 14.23.1.2594
Addons:
-ocxnetdriver-1.0.1-b8
-ocsensors-1.0.3-b18
-actuallycomputers-2.1.0

Options changed: 
-bufferChanges=false
-ignorePower=true

Issue: After executing a program and killing it (Ctrl+Alt+C), the computer goes back to its home console and it is [not possible to execute the program a second time.](http://puu.sh/zvryP/229734565f.png) I need to restart the compute with the on/off button, because even build in commands, doesn't work.

I'm not sure if this is really an issue from OC, that why I put a "?" on my Issue tag.

I want to apologise for any inconvenience.

**Comment by payonel** [comment]
looks like something is altering global functions or system libraries. that will break any os if you do that
if you link your program source i'll find some time to review
thanks

**Comment by accessdenied0** [comment]
[I use this frame program now](https://pastebin.com/TThgJ0UB) in multiply versions of OC, never had any problems. I highly doubt this is a fault of my program, because the one time termination of ANY program (for example even the lua console) causes every following commands and programs to fail with the same message. And my program is at best "simple" and not clumsy written.

(process.lua line 29: "environemnts" typo)

But I thank you for your time, investigating it.

**Comment by payonel** [comment]
I have not forgotten about this bug, just busy with other things
i took a moment to try to repro and noticed you are doing a couple nonstandard things
1. `c` is a global variable assigned to require("component") at the top, it should be local
2. you use a local event for the event name, which will confuse your code if you try to use event again in that scope

But in my first test, it did not repro for me. I was able to run the program multiple times no problem. I'll continue to investigate later

**Comment by accessdenied0** [comment]
Yeah, my code is at best sloppy. I corrected the code mistakes you pointed out.

Still the issue persists with any kind of program I run. Even if a program fails, the next one is unable to load. (I looked through process.lua to understand what is going on)

I would like to help more to find this error, but I have no clue where to start my research... 
I like I said use plugins to OC and turned some options off (all mentioned in my OP).

The console itself doesn't show anything and all the Plugins to OC are up-to-date. Other mod-packs like for example Modern Skyblock 3, uses the same plugins and versions. Can it be that an other mod, for instance CC causes issues like that? I can post my mod-list if that helps. Maybe I overlooked something.

**Comment by payonel** [comment]
ok i see the error. i'll investigate. marked for 1.7.2

**Comment by accessdenied0** [comment]
Ohhh thats great! Thank you alot for your effort!

Just out of interest, because I wanna learn: What caused it? Can you explain/show it?

If it doesn't make to much additional work.

I thank you.

**Comment by payonel** [comment]
i had not found the bug when i last commented, only repro'd it and was happy to fix it

but now i know, in your code you are created a function `load`, and did NOT declare it local, thus it is global

This is the epitome of reasons to keep your variables and functions local.

If you recall, my first comment was, "looks like something is altering global functions or system libraries" and this is exactly what is happening

`load` is a crucial lua function. once you overwrite this, NOTHING else is going to run until you kill the machine and reboot.

so, the fix? use `local` on your functions, especially ones named "load" Only omit `local` when you intend to modify the runtime of the system

**Comment by accessdenied0** [comment]
ohhh my... I usually declare all my functions to local, to exactly avoid that... I forgot/miss that totally!

I'm so sorry for causing that trouble! It works now, soon I "localized" load and save...

I just wonder why it worked in the past, without noticing me...

**Comment by payonel** [comment]
this has influenced me to consider sandboxing a bit about the shell, specifically so user programs can't accidentally corrupt the kernel functions, such as load

intentional modification is still possible with the change i want to make, for example

```
_G.load = function() end
```

That is, I'm not going to hide _G, just make the default ENV separate from the kernel

**Comment by payonel** [comment]
I've decided to guard from this type of error
