### ISSUE TITLE
/lib/filesystem.lua error in unbuffered mode

### ISSUE THREAD

**Issue by KFAFSP** [MightyPirates/OpenComputers#276]
I get this error message whenever listing directory contents (i.e via "dir") of an external filesystem object (Floppy, HDD):

/lib/filesystem.lua:307: attempt to call field 'list' (a nil value)

Im running OpenComputers-MC1.6.4-1.2.12.376-universal (newest build) on MC 1.64 with Forge 9.11.1.965. The filesystem mode is set to "bufferChanges=false", because I want to edit my programs outside the game.

My guess is that a previous commit broke unbuffered again (already had a related problem with a method that according to the java interface declaration should be present was not properly implemented for unbuffered). I would really appreciate somebody looking into this, as I really don't want to have to log in and out everytime a made a change ;) .

**Comment by fnuecke** [comment]
I'll look into it. As a workaround, you don't have to restart, just remove the disk/floppy from the computer/drive and reinsert it.

Edit: hmm, I can't reproduce this. Could you describe the exact setup you're encountering this with? Have you tried turning the computer off and on again?

**Comment by KFAFSP** [comment]
Well, I have conducted some more testing. It seems to be fixed in the last non-experimental version. The only situation in which I can "reproduce" this is when passing an invalid driver table to the filesystem.mount(...) function (that will produce the same error). 

In conclusion: I can't tell for sure what was the reason in the first place, but now it's gone. I'd consider this fixed.
