### ISSUE TITLE
add config option for lua 5.3 default cpu

### ISSUE THREAD

**Issue by payonel** [MightyPirates/OpenComputers#2761]
maybe migrate to false for existing server
maybe set to true for new configs?

**Comment by payonel** [comment]
i can make the default cpu Lua 5.3
But ... it turns out that all crafted CPUs are in an "unassigned" state until the user manually changes their architecture

When a world is loading, all machine architectures load. All machine architectures in an "unassigned" state will take the "Default" architecture. This is outside my control, this is how it works. I don't have the ability to "migrate" nbt data in existing worlds without perhaps adding a step on load to assign any unassigned nbt data to a specific cpu arch.

Anyways, without intercepting load -- that means basically all machines would start running 5.3 on the next world start with this change. Any *assigned* cpus would retain their arch

But the worst part is that machines whose arch changes also stall. The machines will all need to be started (turned on).

**Comment by skyem123** [comment]
Couldn't you change it so that "unassigned" means Lua 5.2, and new CPUs when crafted default to Lua 5.3? Or do it on some per-world state to say what "unassigned" is for that world, and new worlds have 5.3, while old worlds have 5.2?

**Comment by payonel** [comment]
I was GREATLY simplifying the problem. Currently the design and much of the code does not provide me that option. Sometimes my efforts to put the issue into simple to explain boxes can mislead to make it appear simple to resolve
