### ISSUE TITLE
Robot dupe by placing it on tiled farmland

### ISSUE THREAD

**Issue by Thial** [MightyPirates/OpenComputers#2763]
Not exactly sure if it's the issue with OpenComputers as I'm playing on a direwolf20 1.12 server but when I'm placing a robot on a tiled farmland the robot gets placed but it still remains in my inventory resulting in a dupe. The server is running on SpongeForge and it's using GriefPrevention.

**Comment by ktole1999** [comment]
is the area claimed or unclaimed. if claimed does it happen on unclaimed area?

**Comment by Thial** [comment]
I've tested it on my private spongeforge server without grief prevention and also on sp and it's working as intended. Looks like it's an issue with grief prevention. With grief prevention on the other hand it works properly on normal blocks but for some reason placing it on a tiled farmland results in a dupe. I also confirmed that it happens only in claimed area.

**Comment by ktole1999** [comment]
You will have to test with latest version before reporting it to GP. Trust me lol



Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by payonel** [comment]
i would report this to GP. they are welcome to open a feature request if there is something our robots need to do differently
