### ISSUE TITLE
Visual Studio

### ISSUE THREAD

**Issue by lena-kze** [MightyPirates/OpenComputers#2764]
Your Mod is great, but is there a way to implement the apis and stuff into Visual Studio or another editor? For big scripts that would be nice.

**Comment by payonel** [comment]
you mean a plugin for an IDE that helps autocomplete our api? Sure, but not in this repo -- should be an addon or a separate project. thanks

**Comment by skyem123** [comment]
It's also possible to edit files externality from Minecraft in a normal text editor. No autocomplete possible except from vanilla Lua, but it helps.

You need to disable the file system caching, I forgot exactly where files are stored but it's in your Minecraft safe file.
