### ISSUE TITLE
event mechanics inventory_changed

### ISSUE THREAD

**Issue by grandmaster8** [MightyPirates/OpenComputers#2767]
Why is inventory_changed not called for all inventory changes? In this case, you can fully cache the inventory in memory, which will not involve long searches. If this is your game function, then why?

**Comment by payonel** [comment]
review the details in our official wiki: http://ocdoc.cil.li/component:signals#robots
if you find behavior that is incongruent with that description, please open a bug report

**Comment by Avaja** [comment]
do you suggest that I offer a feature? Or did I not understand something? It's not a bug or a error, just not enough options.


For example, when a hopper pulls items from a robot.

**Comment by myrddraall** [comment]
This doesn't really answer the question that was asked. the question was why it doesn't trigger on changes to stack size. It would be nice if it did so that we didn't have to use polling when writing programs that execute once a stack of a certain size has been reached... think of the servers ;)
