### ISSUE TITLE
All mechanisms from the mod IC2 dismantled by the robot - disappear

### ISSUE THREAD

**Issue by Litvinosss** [MightyPirates/OpenComputers#2769]
Mechanisms from the mod IndustrialCraft-2 Experimental, dismantled by a robot with an electric wrench - disappear. They don't drop and don't move into the robot's inventory. The problem is in the latest version of OC 1.7.1.63. In the OC version 1.7.1.62, the dismantling works correctly. By the way, if the player dismounts the mechanism, then they drop out.
I use:
MC 1.12.2
Forge 14.23.2.2624
IndustrialCraft-2 2.8.62
![2018-03-07_20 55 50](https://user-images.githubusercontent.com/32991055/37115451-d98f14d2-2253-11e8-80b6-e07a62624cb1.png)
![2018-03-07_20 56 03](https://user-images.githubusercontent.com/32991055/37115602-3a0bc0e4-2254-11e8-8733-8a1fc6137ac3.png)
![2018-03-07_20 56 23](https://user-images.githubusercontent.com/32991055/37115616-456757b4-2254-11e8-9641-ae5da02190a9.png)
![2018-03-07_20 56 28](https://user-images.githubusercontent.com/32991055/37115623-4bc2bac2-2254-11e8-9238-98a544638c1a.png)

**Comment by payonel** [comment]
Yes, in a way this is the same issue as #2766 - it is a regression, and one that I'm currently building a more robust and general solution for. Thank for testing our jenkins builds to make sure these types of things are caught before we push to curseforge
