### ISSUE TITLE
i cant craft a drone with my eeprom

### ISSUE THREAD

**Issue by JulianWogersien** [MightyPirates/OpenComputers#2770]
i have written a wireless control script and flashed it on an eeprom then i wantet installing it in the drone that should be done with crafting the drone with your eeprom but if i try that it dont work ist like the recipe dont exist but jei tell me that the recipe exists

**Comment by payonel** [comment]
please always include OC versions (the full jar name is best, such as OpenComputers-MC1.12.2-1.7.1.63.jar) in your bug reports

**Comment by JulianWogersien** [comment]
OpenComputers-MC1.12.1-1.7.1.43

**Comment by payonel** [comment]
confirmed duplicate of #2685
