### ISSUE TITLE
[Request] Toggleable runCommand feedback

### ISSUE THREAD

**Issue by Cre8or** [MightyPirates/OpenComputers#2774]
In my current survival world, I rely on command blocks to teleport my pet wolf out of chunks before they unload. The reason I'm not using the debug API's `runCommand(command:string):number` is because it outputs the command feedback to the chat - despite the `commandBlockOutput` gamerule being set to `false`.

However, because I am now using command blocks, I notice about 1 or 2 game ticks of delay between the command block detecting my wolf, outputting a signal (via a comparator) and the signal being picked up by my program. This is bad because my program runs once every tick, and relies on up-to-date information in order to do its job properly.

I see two possible solutions for this issue:
- make the command feedback from `runCommand(command:string):number` respect the `commandBlockOutput` gamerule (not my ideal choice because this would make OC depend on gamerules)
- add a function to toggle OpenComputers command feedback *specifically*

Personally the second option sounds more appealing to me, as we'd have more control over which environment generates command feedback (MC command blocks / OpenComputers). Additionally, if we take this idea further we could perhaps toggle command feedback on *specific* computers only (useful for those that run commands every tick, like mine).

**Comment by Cre8or** [comment]
Any word/thoughts on this?

**Comment by payonel** [comment]
yeah, i saw this the first day you made the ticket :) no need to bump please.

by "feedback" you are only talking about the chat text the debug card prints?

**Comment by Cre8or** [comment]
Sorry about that.

Yes, I was only talking about the chat text that appears when executing commands (using the debug card). Since it's similar to the command feedback you receive from Minecraft command blocks, I figured it was essentially the same, except specific to OpenComputers.
