### ISSUE TITLE
[Suggestion] Allow frequency change of EnderStorage private ender chest / tank

### ISSUE THREAD

**Issue by adriengou** [MightyPirates/OpenComputers#2775]
In public servers, i think we're nearly forced to used private ender chests, but computers doesn't allow to change their frequencies. So it would be good to add an options in the config to allow computers to change private ender chests frequencies.

**Comment by payonel** [comment]
what are you talking about? what is ender storage frequency?

**Comment by payonel** [comment]
are you talking about changing the color code on the ender storage chest?

**Comment by Techokami** [comment]
I believe he is. The "frequency" (I call them channels myself) is a 12-bit number expressed as three dye colors on the lid, read left to right.

EDIT: Whoops, I was thinking of Ender Tanks, which go right to left

**Comment by Ristellise** [comment]
that would be kinda cheaty since you usually require dyes to change the frequency.

**Comment by LordFokas** [comment]
@Joshwoo70 unless you had a component / machine that stored dyes and changed frequencies/channels if enough dyes were available.

**Comment by adriengou** [comment]
the fact is that opencomputers can already change ender storage chest channel. My suggestion was to allow it with this chests when they are private( with a diamond put on it).
