### ISSUE TITLE
Robots consider air as inpassable objects on treetops

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2777]
I noticed this while writing my script for chopping down spruce mega trees. At about 15-20 blocks in the air the robot ends not going forward or backward, claiming there's an impassable object (the sparks indicating a crash of the robot with the block appear). To repeat this issue you just have to create a new world, put down 4 spruce saplings and grow a mega tree. Then if you want you can use my script for the robot to chop it down (creatix). Once it reaches a certain altitude it will fail to move.

Code used:

https://github.com/ferdal1/OpencomputersPrograms/blob/master/chop.lua

I thought at first that it was due to some leftover by the mod fast leaf decay. However even after removing the mod and reproducing the situation the issue still happens.

**Comment by payonel** [comment]
sounds more like youre dealing with altitude
The robots have a height limit, review this detailed documentation on the issue:
http://ocdoc.cil.li/api:robot#movement

**Comment by ghost** [comment]
Doesn't the hover upgrade remove the height limit? And doesn't creatix have all the upgrades installed?

**Comment by ghost** [comment]
Edit: Tried to place a block on the invisible barrier block and remove it afterwards. The result was that the new "air block" was passable, so the robot was able to go through.

**Comment by ghost** [comment]
![2018-03-13_23 31 19](https://user-images.githubusercontent.com/15970512/37380321-e437b3fe-2716-11e8-961b-52bed4f4812d.png)

**Comment by payonel** [comment]
it doesn't REMOVE the height limit, it increases it
the limits are set by the configuration, defaults are
no upgrade: 8
tier 1: 64
tier 2: 256

**Comment by payonel** [comment]
and no, it doesn't look like we ever gave creatix the hover upgrade 
edit: i'd be happy to change that

**Comment by ghost** [comment]
Indeed, the problem was with the height limitation. Thank you very much for your time @payonel.
