### ISSUE TITLE
[Enh,TC6] Thaumcraft 6 support?

### ISSUE THREAD

**Issue by AnrDaemon** [MightyPirates/OpenComputers#2778]
May be I'm a bit preliminary, but I searched before posting this.

With TC6 comes new mechanics of Vis in environment. Would be veery interesting to be able to access and project it with OC holographic emitter.

**Comment by payonel** [comment]
tc6 support is not even on my long list :)
I'm definitely not saying I won't add/update TC support, just saying this is a long way off unless someone wants to provide the work for us.

I'll set this ticket "open for adoption"
as with all tickets "open for adoption", if you are concerned about wasting time implementing a feature in the chance I don't accept the PR, feel free to discuss the details with me here publicly or privately in irc

**Comment by ben-mkiv** [comment]
my personal opinion is that this rather belongs to some addon mod. as thaumcraft barely supports 1.10.2 at this time. (first public 1.12 beta was released 2 days ago)

Its something that an addon should be able to cover by adding a Component or Adapter Driver

**Comment by AnrDaemon** [comment]
Thaumcraft does not support 1.10 at all. Your comment makes little sense.

**Comment by ben-mkiv** [comment]
so these files dont exist!? https://minecraft.curseforge.com/projects/thaumcraft/files

**Comment by AnrDaemon** [comment]
Early betas, with near zero content and progression-blocking bugs? No, they do not count.

**Comment by jco2641** [comment]
As  a novice to java and minecraft mods I had difficulty developing this for a pull request to this project.
So I have implemented this as an addon mod. 
https://github.com/jco2641/Thaumic_Computers
