### ISSUE TITLE
[Suggestion] exportItem() and other me_interface methods

### ISSUE THREAD

**Issue by BlacklightShining** [MightyPirates/OpenComputers#2779]
I haven't been able to find a way to export a specific amount of a specific item from an ME network to an inventory on-demand. Searching the Web turned up a few references to an [`me_interface:exportItem()`](https://oc.cil.li/index.php?/topic/1009-how-to-export-items-from-me-network/), but that doesn't seem to exist anymore. It'd be nice to have it back.

[ComputerCraft seems to have this method as well](https://pastebin.com/RkpFLE1R); you may wish to have a look at its API for compatibility reasons. It has a few other useful inventory-manipulation methods (e.g. `pushItem()`, `pullItem()`, `swapStacks()`) that you might like to add as well.

**Comment by Keridos** [comment]
In earlier versions (1.7.10) the export bus could do that. Not sure if that has been ported yet.

**Comment by payonel** [comment]
after further review, the ae api for oc needs some rework and cleanup, and honestly a lot of breaking changes. For 1.7.3 I have fixed existing ae methods.
you can export specific items from an ae network (with the incoming change) using a database upgrade to set configuration on an interface or an export bus, and then pull from the slot (in the interface) or call exportToSlow (with the export bus)
we've written up some api documentation on our wiki: https://ocdoc.cil.li/component:applied_energistics
