### ISSUE TITLE
oc_spawncomputer not working

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2782]
I'm on a singleplayer world on FTB Revelation 1.12.2 with cheats enabled and oc_spawncomputer doesn't work, it says unknown command and putting it in chat without / doesnt work either

**Comment by payonel** [comment]
I just saw the same error testing this myself, and then realized no mods had loaded
Perhaps we made the same mistake
When you've opened the minecraft launcher, after using the twitch app, did you change the version drop down to use revelation? or were you playing its default profile which loads no mods.

without oc loaded, /oc_sc isn't going to do anything :)
