### ISSUE TITLE
Robot sometimes fails to place blocks above.

### ISSUE THREAD

**Issue by SpeedCuber1** [MightyPirates/OpenComputers#2783]
I created a program to automatically place pillars with torches on them so that my mine is well lit.  The code allows the computer to resupply itself from ender chests.  Sometimes,  the program crashes because it was unable to place the chest on top of itself.  Manually placing the chest on top fixes the problem, but it comes back the next time it has to resupply.  The same program works flawlessly on older versions of minecraft.  When the problem occurs,  it is unable to place any blocks on top of itself.  Minecraft 1.12.2 OC 1.7.2

Link to code:
https://pastebin.com/GNw6Eup4

**Comment by payonel** [comment]
i'll put this on the backlog, but for now you can retry placing the chest until you detectup that it is there

**Comment by payonel** [comment]
no repro
