### ISSUE TITLE
[BUG] Power Converters stop working after server crash

### ISSUE THREAD

**Issue by pdglobal** [MightyPirates/OpenComputers#2785]
When the server crashes power converts "break", their exact behavior is that they completley stop accepting power and have to be broken and replaced in order to return power to the system.

**Comment by payonel** [comment]
great title :)

**Comment by payonel** [comment]
I'll need repro
1. always, ALWAYS, include the full version filename of the OC jar you are using
2. please try to save me loads of setup time and provide a minimal repro
-> does this repro with just OC
-> what is causing the crash? have you examined the crash logs
3. can you repro this (or any bug you report) with ONLY our mod being used?
4. can this repro in sp?

These are basic things you can do to help mod devs narrow in on the problem and fix the issue more quickly

**Comment by pdglobal** [comment]
Sorry, I didn't make myself clear, OC isn't making the server to crash, this happens when the server doesn't shut down gracefully.

The OC file/version I am using is OpenComputers-MC1.12.2-1.7.2.67.jar

It's impossible to reproduce in single player because the server has to be killed without graceful exit, have confirmed this issue persists with JUST OC on the server & client. (forge-1.12.2-14.23.2.2625-universal.jar)

**Comment by pdglobal** [comment]
I forgot to mention the mod I'm using to power the network is mekanism.

**Comment by payonel** [comment]
thanks for the added details
This isn't the first I've heard of some oc machines losing state or going into a bad state when a server is killed/aborted/crashed.

I can't put this issue high on my priority list currently, but I appreciate the info you have given.

Does this happen everytime? If there is anything else you learn about this problem, or other issues you have with oc when the server crashes, feel free to add it to this ticket.

Thanks

**Comment by pdglobal** [comment]
Please disregard this, aparently this is a bug in mekanism. Once using power cables from another mod I am having no problems!

**Comment by payonel** [comment]
cool, thanks
