### ISSUE TITLE
Trading written books for emeralds - "not enough items" (NBT tag)

### ISSUE THREAD

**Issue by 7eggert** [MightyPirates/OpenComputers#2788]
My robot won't trade books for emeralds even though I have written books (copies of a signed book); manually trading them does work.

I googled and found the request to compare the NBT tags on trades, I guess written books need to NOT compare NBT tags.

Version: OC OpenComputers-MC1.10.2-1.7.1.150.jar

(No full version report since I think I identified the cause; will do on "request".)

**Comment by payonel** [comment]
thanks for the details

**Comment by 7eggert** [comment]
Do you have all the details you need or did you just request them?

**Comment by payonel** [comment]
haha, no - i wasn't being passive aggressive :) I actually think this is enough to go off of.

if you wanted to test 1.7.10 that would be helpful. I fix everything in the lower version first (1.7.10, 1.10, 1.11, 1.12)

**Comment by 7eggert** [comment]
I don't have that version installed and I'm quite busy. Sorry.

**Comment by 7eggert** [comment]
Comparing NBT on  was introduced due to github.com/MightyPirates/OpenComputers/issues/829
As far as I know, it's only wrong for books which are expected to differ.

**Comment by payonel** [comment]
I understand, but I checked the vanilla code which does NOT check nbt. If it is okay for vanilla, it is okay for us

**Comment by 7eggert** [comment]
Vanilla will require the user to chose the item, thus it's OK to trade whatever fits. The hack of checking NBT was a fix for not choosing the item, and there is still concern in me as the other thread/issue mentioned custom trades from other mods (unless they too are handled without NBT).
¢¢: This fix will require the other issue to be fixed properly.

**Comment by payonel** [comment]
tell you what, I'll make the code try the exact match first. If that fails, it'll fall back and use item type matching. I'm not going to make a "if book" exception though

**Comment by 7eggert** [comment]
¢¢: The best solution would be to supply a list of slots to use, as suggested on the other issue, because if I want to deal with your solution, I'd need to know the slots anyway. (Or I'd use the old function to just automatically have a slot being selected.)

**Comment by payonel** [comment]
it searches in slot index order, so put the items you prefer to use in the trade in lower slot indexes
