### ISSUE TITLE
wrong error message while trading

### ISSUE THREAD

**Issue by 7eggert** [MightyPirates/OpenComputers#2789]
If the inventory is completely filled with tradeable items and no emerald is in the inventory and a trade that would result in having one is invoked, the trade fails with "not enough items to trade" instead of "not enough inventory space to trade". Having a full stack of emeralds in slot 1 (selected), I got the correct error message.

Version: OC OpenComputers-MC1.10.2-1.7.1.150.jar

**Comment by payonel** [comment]
fixed along with the same fix for #2788
commit sha: c57dc9ae48f96bb0b0ffc6db267e96844694d6d7
