### ISSUE TITLE
[1.12.2 1.7.2.67] Errors running the class transformer

### ISSUE THREAD

**Issue by rndmorris** [MightyPirates/OpenComputers#2793]
I've been receiving the below error when a world is loaded: 

> [00:13:06] [main/INFO]: [CHAT] §aOpenComputers§f: There were §cerrors§f running the class transformer. Please report this, together with your (full!) FML §alatest.log§f/§afml-server-latest.log§f logfile, thank you!

Skimming through the log file, it appears to be an issue with Malisis Core and/or Malisis Doors. The error message is not displayed after removing them from the mods folder.

I've put the requested log file (as well as two other log files) in a [gist here](https://gist.github.com/rndmorris/fb3d7d93a9cf8200958a0ab2ef42688e).

- Minecraft 1.12.2
- OpenComputers 1.7.2.67 

Let me know if there's any more information I can provide that might help.

**Comment by thiakil** [comment]
Are you able to reproduce without MalisisCore (and dependants)?

If it still happens, hammercore would be the next candiate

**Comment by libfrozen** [comment]
I have the same error.
Here is a list of mods I'm using.

mod_voxelMap_1.7.1_for_1.12.2
ChickenASM-1.12-1.0.2.7
NotEnoughItems-1.12.2-2.4.2.244-universal
ChickenChunks-1.12.2-2.4.1.73-universal
OpenComputers-MC1.12.2-1.7.3.146
CodeChickenLib-1.12.2-3.2.2.354-universal
OpenEye-1.12.2-0.8
EnderStorage-1.12.2-2.4.5.136-universal
SmoothFont-mc1.12.2-1.16.2
ForgeMultipart-1.12.2-2.6.1.81-universal
Translocators-1.12.2-2.5.1.79-universal
Hwyla-1.8.26-B41_1.12.2
i18nupdatemod-1.12.2-1.0.8
Wawla-1.12.2-2.5.270
jei_1.12.2-4.14.4.264
WR-CBE-1.12.2-2.3.1.31-universal
millenaire-7.1.1
Xaeros_Minimap_1.16_Forge_1.12

And the latest.log is in the attachment.

[latest.log](https://github.com/MightyPirates/OpenComputers/files/2835247/latest.log)

**Comment by payonel** [comment]
some have reported this was a conflict with liteloader

**Comment by ArtyIF** [comment]
I have the same issue. Disabled every mod except OC and MalisisCore. [latest.log gist](https://gist.github.com/ArtyIF/86cd4f2d3c5bdbd8ba0c84fdc7117e87)
