### ISSUE TITLE
Script suddenly no longer works

### ISSUE THREAD

**Issue by Faabvk** [MightyPirates/OpenComputers#2794]
I wrote a small mining script that digs 1x2 tunnels, nothing special. The script stopped working though, and I have no clue why. Code:

```Lua
local component = require("component")
local robot = require("robot")
local shell = require("shell")

if not component.isAvailable("robot") then
    print("This program must be run on a robot!")
end

local args, options = shell.parse(...)

function forward()
robot.forward()
end

function dig()
while robot.detect() do
robot.swing()
end
end

function digUp()
while robot.detectUp() do
robot.swingUp()
end
end

function help()
print("Syntax: tunnel <length>")
print("Digs a 1x2 tunnel for a specified length.")
print("   -h, -help:     Shows this screen.")
end

if options.h or options.help then
help()
end

if #args < 1 and not options.h and not options.help then
help()
end

local length = args[1]

if length then
for i=1,length,1 do
dig()
forward()
digUp()
end
end
```

This program worked for me for weeks but today it returned:

`/lib/package.lua:64: module 'robot' not found: no file '/lib/robot.lua'`

**Comment by Saklad5** [comment]
You realize this isn’t actually an issue with the mod itself, right?

**Comment by xarses** [comment]
I would recommend live debugging on IRC or Discord

The message implies that openos was not properly installed, their may be something wrong with the bios, or something modified the the robot's drive on the actual server (the disks are stored as real files in the server's world data directory separated by the objects uuid).

The best first step would be to re-load openos from a floppy (who's data is stored in the mod files ) and work from there, you might need to also reset the bios and in some absurdly rare cases (usually updating) you might need to also reset the CPU

**Comment by Faabvk** [comment]
@Saklad5 My bad, thanks for feedback!

**Comment by Faabvk** [comment]
@xarses I tried reinstalling OpenOS to the robot and that didn't work, I'll try creating a brand new robot and run it on that.

**Comment by payonel** [comment]
`/lib/robot.lua` is actually a symlink, created when the robot's internal read-only filesystem is mounted and autorun creates the symlink for you
Did you turn off autorun? you can turn it back on:
`filesystem.setAutorunEnabled(true)`

**Comment by payonel** [comment]
there is not evidence that this is due to a bug in OC, but probably due to the in-game configurability of the robot and its filesystem
