### ISSUE TITLE
[Suggestion] Command to reload OC data from disk

### ISSUE THREAD

**Issue by XFactHD** [MightyPirates/OpenComputers#2795]
Because of how the ingame editor on an OC computer works I prefer to use an external editor like Notepad++ to edit the .lua file found in the save folder. Forcing the game to save the files to disk after editing the .lua file ingame can easily be done by opening the pause menu but there is no way to force the game to reload the .lua file from disk after editing it in an external editor other than exiting and reentering the world which gets annoying very fast. I would suggest adding an /oc_reload command to force the game to reload the saves/<save name>/opencomputers directory.

**Comment by payonel** [comment]
our solution to this problem is for you to disable our buffered file io, so that files in-game are "real" files
open the config and change and look for the filesystem section, and change `bufferChanges` from the default `true` to `false`

**Comment by XFactHD** [comment]
Thanks for that hint, didn't know that config option existed.

**Comment by lena-kze** [comment]
Nice
