### ISSUE TITLE
[Suggestion] Flat Screen

### ISSUE THREAD

**Issue by Moobien** [MightyPirates/OpenComputers#2796]
Cool would be if you could have a RFTools style screen. Nice and flat, compact and they look cool when you wrench them to remove their borders so they look holographic. Also EnderIO compatible cables would be sweet (am beta testing EIO currently on their server)

**Comment by payonel** [comment]
enderio already has opencomputers integration with their oc conduits
as for flat screens, yeah, that would be neat. i'm not against this at all, i just personally have other priorities for oc for the foreseeable future. I'll leave this open for adoption.

**Comment by Moobien** [comment]
The EIO OC conduits are scheduled for post release currently. But thanks for listening to my suggestion :)
