### ISSUE TITLE
[1.7.10][dupe] EEPROM on crafting

### ISSUE THREAD

**Issue by Artmoneyse** [MightyPirates/OpenComputers#2797]
Sorry for bad english.
Tested on OpenComputers-1.6.2.12

1) put the craft in the workbench
[https://imgur.com/Wa8Ldz8](url)
2) result crafting:
https://imgur.com/8pcLVtn

In the drones should already be EEPROM.
Works also with robots.

**Comment by payonel** [comment]
1.6.2 is old. this has been fixed in 1.7.2
