### ISSUE TITLE
Unexpected error in Lua callback Exception are fired.

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#28]
2013-12-27 00:07:39 [WARNING] [OpenComputers] Unexpected error in Lua callback.
java.lang.ClassCastException

with 1.0.3 version.

**Comment by fnuecke** [comment]
Which method, what setup/context, ... details please.

**Comment by ghost** [comment]
in robot command. Like swing() or forward(). i will check with latest version (i use the .3 version)

**Comment by fnuecke** [comment]
Please post a full error log, too. There should be a stacktrace for that exception. I can't do anything about it if I don't know where it's coming from.

**Comment by ghost** [comment]
In the 1.0.4, No problem with robot. close.
