### ISSUE TITLE
Tiered batteries for robots and laptops

### ISSUE THREAD

**Issue by evg-zhabotinsky** [MightyPirates/OpenComputers#280]
Exactly what title states.
I see it as an extra slot in assembler.
I am not quite sure what capacities they should have, need to test energy usage.
Anyway it should make sense since different tiers of components draw different amounts of power.
The same batteries can serve as a base for battery upgrades (not capacitor - why should portable capacitor upgrade have capacity of more than 15x capacity of stationary capacitor block?)
**EDIT:** I also forgot about creative battery (like creative computer case)

**Comment by fnuecke** [comment]
Well, there is a capacitor upgrade in 1.3 (which is basically a battery). I have thought about tiering it, haven't had the time to look into it further, yet, though.

**Comment by evg-zhabotinsky** [comment]
I know about this upgrade. And I have written above that it's capacity is ridiculously large for a "capacitor". (Even capacitor block stores a bit too much compared to real-world capacitors)
Also, I proposed these batteries as required component for robot assembly and not just upgrades, much like CPU or RAM. (That is, no built-in capacity like no built-in RAM)
Excuse me for being unable to clearly explain what I mean :)

**Comment by fnuecke** [comment]
Oh, seems I skipped that part, sorry. Th higher capacity can kind of be explained away by the fact that placing capacitors next to each other in the world also improves their capacity, and the upgrades are just very densely packed capacitors ;-) Come to think of it, I'll probably rename that to 'battery upgrade', to make the distinction more clear. But yeah, adding tiers and starting lower does make sense I guess.

As for the capacitor-as-component thing, what would be the reasoning for that? Avoid robots' energy storage getting too big? I'm not convinced that's... necessary. If anything, I might re-evaluate the idea of making the robot's complexity affect the cost of certain actions such as movement.

**Comment by evg-zhabotinsky** [comment]
Capacitor-as-component thing only means that robots don't come with a huge power storage preinstalled for free. It does not even have to be component as such. It's much like how CPU works in this mod.

**Comment by fnuecke** [comment]
Hmm, I'd like to keep "specialization" to a bare minimum, tbh (consider screens and keyboard, even those don't get an extra slot type). I think keeping the capacities of the batteries relatively low should work well enough for balance. I'm thinking something like 10k, 15k, 20k for the three tiers? Considering the complexity limits I think that's enough to force a trade-off when packing a bunch of batteries.
