### ISSUE TITLE
OpenComputers Manual Typo

### ISSUE THREAD

**Issue by r3volut1on** [MightyPirates/OpenComputers#2805]
Mod version: OpenComputers{1.7.1.150}

Under the section Microcontroller, the last sentence of the first paragraph says "In particular, **the *can* *not*** interact with external components."  I believe this is supposed to say "In particular, **they *cannot*** interact with external components."

**Comment by Tahakk** [comment]
It is not a type, as dictionaries say you can use both, "_cannot_" is just used frequently

**Comment by r3volut1on** [comment]
"Can not" is fine, I'm saying "the" should be changed to "they"

**Comment by LordFokas** [comment]
I'd like to input here that as a non-native english speaker (although quite proficient with the language) **cannot** and **can't** are a lot easier to read and understand than **can not**.

**Comment by Theyoungster** [comment]
I found a more obvious typo, on the page for the Linked Card, as the hover text for the image.
It currently says "I feel we some kind of connection."
It SHOULD say "I feel we **have** some kind of connection."

**Comment by Techokami** [comment]
So, little question then... why not make a pull request with these fixes? 👀

**Comment by Theyoungster** [comment]
You mean open a new issue, or fix it myself? I just saw the issue and
wanted to point it out for someone who can reasonably fix it.
