### ISSUE TITLE
Transposer transferItem argument checkSlot should check for the opposite side

### ISSUE THREAD

**Issue by cyb0124** [MightyPirates/OpenComputers#2806]
Here:
https://github.com/MightyPirates/OpenComputers/blob/ac67d8ba37c2b2c65f6eafb9c2bd371dd6f13fea/src/main/scala/li/cil/oc/server/component/traits/InventoryTransfer.scala#L28-L29

The sourceSide and sinkSide in these 2 lines should be followed by `.getOpposite`, just like the line 31 below.
This causes issues when accessing inventories that have different number of slots on opposite sides.

**Comment by payonel** [comment]
how is this different than #2863 ? do you have any specific block that is exactly this issue that is not the same as #2863 ?

**Comment by cyb0124** [comment]
This affects all thermal expansion blocks that let you set different inventory access for different sides.
For example in this setup I want to transfer the content from the chest to the furnace using `component.transposer.transferItem(sides.up, sides.west, 1, 1, 1)`

![](https://i.imgur.com/VdY7VWp.png)

It doesn't work when I only open the right side of the furnace: (raises "no inventory" error)
![](https://i.imgur.com/kGo4eAJ.png)

But it works when I also open the opposite side:
![](https://i.imgur.com/BABuzsz.png)

This issue only appears when the slot is specified. If I change the code to `component.transposer.transferItem(sides.up, sides.west, 1)`, the issue disappears.

**Comment by payonel** [comment]
ok perfect! thank you

**Comment by payonel** [comment]
closed with #2946
