### ISSUE TITLE
Transposer.transferItem() return value bool; documented as number

### ISSUE THREAD

**Issue by 7eggert** [MightyPirates/OpenComputers#2807]
The return value of transferItem() is documented to be a number, presumably the successfully transfered amount, but it just returns a success value

Also and due to race conditions, it should return (transferedSomething, amountItTransfered (the same applies to similar functions) - I assume it's not possible?

**Comment by xarses** [comment]
Which oc version is this for?

**Comment by 7eggert** [comment]
OpenComputers-MC1.10.2-1.7.2.170.jar
Sorry.

**Comment by payonel** [comment]
So, technically, the ocdocs were wrong in this case
you'll also get some method documentation if you run in lua repl: `component.transposer.transferItem` which would show you that the method returns a boolean
`suck` also returns a boolean
HOWEVER ---
I think this idea is really handy, to return the item count. I've built a solution in 1.12 for this, but i'm going to port it to 1.7.10 and merge up
