### ISSUE TITLE
[1.12.2][1.7.2.67] Cannot craft diamond nuggets 

### ISSUE THREAD

**Issue by lhooge** [MightyPirates/OpenComputers#2808]
Hi, 

we are trying to craft a tier 3 roboter but we encounter problems crafting the diamond nuggets. 

We are placing the diamond in the corner left but we can't craft the nuggets. (see screenshot)

![2018-04-09-200731_1670x902_scrot](https://user-images.githubusercontent.com/1236642/38515470-a83188c0-3c34-11e8-81a7-14a239fe421b.png)

MC version: 1.12.2
OC version: 1.7.2.67

We do not have any further mods installed.

Do we miss something?

Thanks!
Lars

**Comment by payonel** [comment]
the recipe has changed (technically, we already had the new recipe in the hard mode recipe file, now default is just using it)

it now requires a cutting wire
