### ISSUE TITLE
Robot`s leveling

### ISSUE THREAD

**Issue by Shtak** [MightyPirates/OpenComputers#281]
Sorry for my bad english, but I have a some question. I have some robots and i don`t understand how they get expirience. I have easy programm - place stone, dig stone, repeat. Some robots getting expirience, some - not.

**Comment by evg-zhabotinsky** [comment]
It gains experience the same way real players do, but only if it has experience upgrade installed.
Also, I guess forums are better place for questions. ([OpenComputers forum](http://oc.cil.li/index.php?/index) or [OpenComputers thread on minecraftforum.net](http://www.minecraftforum.net/topic/2201440-opencomputers-v1212/) are what I know, both links from README)
GitHub Issues are meant for bugtracking and project improvement suggestions if I am not mistaken.

**Comment by Shtak** [comment]
Thanks. I think it may be a bug, becouse all robots have installed angel upgrade. I not found information about exp. upgrade. What is that?
And yes - when a lot of robots do some deals (moving, breaking e.t.c) they deal massive lags. I think it is not bug, but it is problem.

**Comment by fnuecke** [comment]
I'm assuming you're on 1.2, in that case there is no separate experience upgrade there, all robots should be able to gain experience. It depends on what they do, however. For example, they will only gain XP for digging blocks if they're using a tool. How do you measure XP? If by 'picking' the robots, the client XP value is only updated every-so-often. Use the Lua API to make sure they really don't get XP.

As for the lag, I don't really see any difference to when blocks are broken by other block breakers / by hand. Meaning no real impact at all. Maybe it's some interaction with another mod?

**Comment by Shtak** [comment]
I use robot.level command. All robots, who place and broke stone don`t get exp (except 5-7). I am not undestand why? If all robots would not get - it will be normal, but some get exp... About lags - I am that player, who burn server (if you understand). Robots deals lugs when moving, breaking e.t.c. I have 52 robots active, and when they moving - server has extremely high lags.

**Comment by fnuecke** [comment]
Hmm, they _should_ get experience from 'exhausting' themselves. No idea what's going on there. I'm afraid I'm a little too busy getting 1.3 stable to look into it further right now, but I'll keep an eye on it in 1.3.

I'm curious, if you have 52 pistons that get (individually) triggered by a redstone timer every 0.4 seconds, will that lag, too? Because if the answer is yes then it's simply the chunk-update taking relatively long, which is something I can't really do anything about.

**Comment by Kilobyte22** [comment]
52 pistons triggered at same is horrible lag wise, especially with 0.4 second delay. So i guess that is the cause of it

**Comment by fnuecke** [comment]
After breaking it while refactoring and then fixing it again XP seems to work as it should, if you still see issues with this in 1.3 let me know.
