### ISSUE TITLE
Custom Loot Discs - full how to

### ISSUE THREAD

**Issue by gdarai** [MightyPirates/OpenComputers#2812]
I found in this issue: #1409 that it is somehow possible to add some program as a custom loot disc.
But unfortunately there is no clear description how to do it, so here is my question:

Where am I supposed to change the loot folder and can it be done in a way so I can make it an integrated part of my modpack, downloadable from the Twitch?

I found loot folder only in the mods/OpenComputer.jar file... in such a case I would have to tweak your compiled mod file and I don't know if that is legal operation.

From what was in the previous issue it looks like there is supposed to be a folder in the save, but I found none and it would not fulfil my need to integrate it into the modpack.

So in the light of those facts:
Can I do that somehow just by modifying/adding it in the config folder?
If not, can I tweak the jar and then submit it as part of the modpack?

**SOLUTION:**
[https://minecraft.curseforge.com/projects/opendisks](https://minecraft.curseforge.com/projects/opendisks)
This mod is now available also for Curse and Twitch (Tested for 1.10.2)
After first start of the game with this mod it adds ```mods/opendiscs``` folder, where you can add whatever discs you want. Example included. Discs then can be installed using OC install program.

**Comment by LordFokas** [comment]
You can probably create a resource pack, with the programs in the same path you see in the jar `/assets/opencomputers/loot/...` and put what you want there...

Don't quote me on that though, as I'm not sure how OC handles custom packs...

**Comment by brisingraerowing** [comment]
There is [OpenDisks](https://github.com/PC-Logix/OpenDisks) which does just this. It's not allowed in Curse modpacks though. 

@CaitlynMainer is there going to be a Curse publish of that mod?

**Comment by CaitlynMainer** [comment]
"Vexatos: yourworldsave/opencomputers/loot should be it put a loot.properties there just like it would be in the jar"   This is why I dropped OpenDisks, and haven't bothered restoring any of the jars for download.  OpenDisks can be useful for ModPack creators though, if they're not including a world, this is the one place that OpenDisks can shine...  But there has been little demand for it.

**Comment by gdarai** [comment]
@CaitlynMainer And that is exactly my case.. I don't need to tweak my save... I can code. But I want to make life easier for players of my modpack... so OpenDiscs would be a solution for me.

I am going to try to buid it as a resourcepack today and we will see. Othrwise I will tell my players to pull it from wget and give them the address. But some people are even afraid of that one line. That is why I am looking into having it on a disc.

**Comment by CaitlynMainer** [comment]
What version of Minecraft is this for?

**Comment by gdarai** [comment]
@LordFokas Ok, I tried. I created a custom ResourcePack using the tutorial here: [minecraft.gamepedia](https://minecraft.gamepedia.com/Tutorials/Creating_a_resource_pack)
And the ResourcePack is there, visible in the game.

I added "assets/opencomputers/loot" folder (actually copied it from the jar so name is hopefully ok)
There I added my folder "get" copying the content from the "dig" disc.
(I expect I am not supposed to copy all asset content so this "get" is now thy only subfolder of "loot")
And added a "get" line into the loot.properties:
```get=Space Race Get (Package Manager):0:dyeYellow```
But now new disc appeared in the game. Is that all or did I forgot something? What do you think?

**Comment by gdarai** [comment]
@CaitlynMainer For 1.10.2

**Comment by gdarai** [comment]
@LordFokas ok, I didn't find the new disc anywhere, in JEI in creative tab anywhere, so I tried minetweaker:
```recipes.addShaped(<opencomputers:storage:1>.withTag({"oc:data": {"oc:fs.label": "get"}, "oc:color": 5, display: {Name: "SpaceRace Getter"}, "oc:lootFactory": "OpenComputers:get"}), [[<minecraft:stick>, <opencomputers:storage:1>, <minecraft:stick>], [null, null, null], [null, null, null]]);```
And still no luck. The new disc has the proper name, but on inserting into the computer it does not load the data from the resourcepack.

This is it, I am out of ideas. If you will have any other hints, let me know. :o)

**Comment by CaitlynMainer** [comment]
The Default branch for OpenDisks is 1.10.2 so I'll see about getting a project up on CF, adding a disk with OpenDisks is very simple.  The mod creates a directory in the Mods directory with an example file and some example directories and you just follow that example.  the disks show up in the OC creative tab, and can be cycled through with the OC floppy and a scrench in a crafting table.

**Comment by gdarai** [comment]
@CaitlynMainer That OpenDisks of yours? Can you put it on Curse/Twitch so I can add it officially into the pack? If yes than that is the GOLDEN solution for me... thank you...
If not, is there a way how to add it as a 3rd party mod? Well I will explore any way I will think of of you suggest.
let me know please once I'll be allowed to get it (+ from where I can get it) and I will try it out. Thanks again.

A pro po, why are you adding those resource things into the mods folder? Isn't it more logical to have it in the config? I saw the same approach you are using in the 'ruins' mod so I am interrested if there is reason or if it is just a matter of choice.

**Comment by CaitlynMainer** [comment]
https://minecraft.curseforge.com/projects/opendisks

**Comment by gdarai** [comment]
You are Great... thank you. I will try it and let you know how did it go.

**Comment by gdarai** [comment]
@CaitlynMainer IT WORKS... PERFECT, and it even works with the install. Thank you, I will write a short summary to the headder of this thread, so everybody can know from now on.

I will do few more tests. Include it in my modpack and in the near future fill in a lot new programs.
Next questions I will submit directly into your repo.

**Comment by PublicVoidUpdate** [comment]
Is there something like OpenDisks but for eeproms?

**Comment by payonel** [comment]
closing old feature request, there is a work around here
