### ISSUE TITLE
[Request] make sides for Transposers in Microcontrollers relative to the front of the Microcontroller

### ISSUE THREAD

**Issue by MalkContent** [MightyPirates/OpenComputers#2814]
Right now they appear to be based on cardinal directions, which is a hassle to program for and also imbues the machine with magic compass powers.
The block has an obvious front, like computers, which can even be manipulated with a scrench.
If the cardinal directions thing stays, it'd at least be neat if one could determine the front side programmatically.

**Edit:**
After further investigation, the problem with sides is not a general one. i used a transposer in the upgrade slot of the microcontroller and that one required cardinal directions. A redstone card was fine with relative directions. I'll see if i can work out how it works for other components, but consistency would be nice either way. For now I'm gonna get some sleep <3 sorry for the hassle.
Edit2:
Far as i can tell only the transposer is affected

**Comment by payonel** [comment]
yes, this is by design. our transposer are blocks without a face, and a microcontroller with a transposer upgrade is more like a transposer with a microcontroller running it :)
