### ISSUE TITLE
[Request] allow Inventory/Tank Controller upgrades in Microcontrollers

### ISSUE THREAD

**Issue by MalkContent** [MightyPirates/OpenComputers#2817]
The idea is for the upgrades to have the same capacity as if they were placed in an adapter. Meaning they can only read the inventory/tank, not manipulate it.
Since microcontrollers can already accept transposers as upgrades, it is something they already can be capable of, so no new powers. Only difference would be that a microcontroller that is purely there for monitoring would be a good bit cheaper. And also it would stop people like me wondering why you can't put these upgrades in there :x

**Comment by Vexatos** [comment]
Tank and inventory controller upgrades are an interface between the robot's or drone's internal inventory and the outside. The MCU does not have an internal inventory. The transposer is an interface between two different external inventories, so that is what you will need.

**Comment by MalkContent** [comment]
The adapter has no inventory either. Which is why I argumented for a similar functionality.

**Comment by Vexatos** [comment]
The inventory controller in the adapter was there before the transposer existed. It should be removed eventually.

**Comment by MalkContent** [comment]
aw. fair enough. I'd say it fills a niche without much effort though.

**Comment by gatoborrachon** [comment]
Well, after looking how to check internal inventories of other mod's machines with a Microcontroller, i guess it is impossible (no problem, at least i won't waste more time and just set up a computer)
