### ISSUE TITLE
[1.12.2] Crash when starting server on linux

### ISSUE THREAD

**Issue by RawrUniversal** [MightyPirates/OpenComputers#2818]
Hello. I am getting this crash with the latest OC on my server. https://pastebin.com/nmnLE0bP

**Comment by payonel** [comment]
very strange, it appears to be crashing here: https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/server/machine/luac/LuaStateFactory.scala#L198

which is meant to remove old copies of the OC lua library when you have it local to your server folder
are you upgrading from an old version of OC?

This code has been here for about 3 years, with no report of error

do you have any OpenComputersMod- files in your server dir?
what is your host os?

**Comment by RawrUniversal** [comment]
I am not upgrading from an old version and there is no OpenComputerMod- files. I am using ubuntu 16.04

**Comment by payonel** [comment]
are you running any security software that blocks reading or writings files? is your folder (`./`) give your user write/read permissions?

**Comment by RawrUniversal** [comment]
No security, but the read/write was the problem. Thanks for the help.
