### ISSUE TITLE
Sandboxed Lua `debug` api access

### ISSUE THREAD

**Issue by dimitriye98** [MightyPirates/OpenComputers#2819]
Would there be any way to sandbox the Lua `debug` API enough to allow it to run in OC? It'd be really nice to be able to do debugging in OC itself, rather than resorting to OCEmu.

**Comment by payonel** [comment]
there would be value in having a strongly sandboxed and complete debug api, we agree there. but the cost in supporting such a debug api is project of its own. Honestly, if you feel you have a hard project to debug and you feel you would greatly benefit from the debug library, just modify our machine.lua and expose the debug library full (set `sandbox.debug = debug`)
