### ISSUE TITLE
[Question] How to detect if a filesystem is a floppy?

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#2822]
Hello,

My question is simple: I want to know if a filesystem is a floppy, an internal disk or a tablet, or anything like this. In fact, I would like to find the first floppy's filesystem.

Thank in advance!

**Comment by payonel** [comment]
perhaps this is a bit...unexpected - but what you want is currently possible
`computer.getDeviceInfo()[filesystem_address].clock`
`clock` reports: `read / seek / write` speeds
hard drive: "200/200/80"
tmpfs: "260/260/100"
floppy: "20/20/20"

**Comment by payonel** [comment]
also, with our dev builds, you can get the floppy in external disk drivers using the new disk_drive component method `media`, it returns the floppy's hardware address
