### ISSUE TITLE
[Suggestion denied] Lua BIOS eeprom readonly and method eeprom.isReadonly()

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#2823]
Hello,

I suggest to make that the Lua BIOS eeprom is readonly by default.
Also, adding a new method isReadOnly() to see if an eeprom is readonly or not.
And a return value for set() that returns the same value of isReadOnly().

Thank you in advance.

**Comment by payonel** [comment]
http://ocdoc.cil.li/component:eeprom
see `makeReadonly`
if readonly, `set` and `setLabel` cannot be modified, though `setData` can
there is currently no way, short of trying to use `set` or  `setLabel`, to determine if the eeprom is ro

**Comment by ExDomino** [comment]
And to make Lua Eeeprom (made from crafted eeprom and manual) readonly by default?

**Comment by skyem123** [comment]
Eh, that might cause confusion though...

**Comment by ExDomino** [comment]
OpenOS floppy disks are already readonly.

**Comment by payonel** [comment]
we're not going to change the default, and there is a workaround to detect isReadonly (That is: eeprom.set(eeeprom.get()) succeeded if it is rw)

**Comment by ExDomino** [comment]
Ok, so keep base floppy disks readonly and base eeeprom not readonly. It's confusing but don't worry, you are the author.
