### ISSUE TITLE
[Bug] "copy" always prompt to overwrite

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#2824]
Hello,

Doc says that "copy" program is only supposed to prompt to overwrite if "-i" is added as option. In my case, it always prompt if I want to overwrite an existing file, with "-i" or without.

Minecraft: 1.12.2
OpenComputers: 1.7.2.67

**Comment by payonel** [comment]
yep, that's because openos aliases cp to `cp -i`. This isn't a broken `cp`, but instead the default alias for openos. been that way for a long time. feel free to edit your /etc/profile if you would like a different alias, or you can add `unalias cp` to your /home/.shrc
