### ISSUE TITLE
[Suggestion] SATA like numeration for HDD slots

### ISSUE THREAD

**Issue by i-am-dies** [MightyPirates/OpenComputers#2825]
I trying to make my own BIOS with blackjack and sluts. This thing is very important for making boot priority and showing correct numbered list. Can I use some API to implement it myself, or it's impossible from my side? The size of EEPROM is 16kb for now, going to extend in future if needed, because 4kb is absurdly small.

**Comment by payonel** [comment]
each component has a `slot` you can use, which is -1 if it is an external component
eeprom code would be -> `component.proxy(component.list("filesystem")()).slot`
beyond that, no, we're not add more slot, order, or component info about "where" it is
