### ISSUE TITLE
Big performance issue

### ISSUE THREAD

**Issue by JoeSGT** [MightyPirates/OpenComputers#2826]
Well i have found reason to believe that OpenComputers mod is causing a lot of lag
Forge version i am at is 14.23.3.2655 and OpenComputers version i am at is MC1.12.2-1.7.2.67
timings: https://timings.aikar.co/?id=3e0f020722ac48f8af2d18fb4a66349f
i have also went into more detail and here is it

![8634ad83f0631247d45570589fd0f145](https://user-images.githubusercontent.com/30296350/39571304-0b528ad2-4e99-11e8-8012-41a3d55b2473.png)

If you want to look at the WarmRoast here a copy of it in a zip you can view it yourself
[WarmRoastReport.zip](https://github.com/MightyPirates/OpenComputers/files/1970439/WarmRoastReport.zip)

**Comment by Vexatos** [comment]
This method loads the filesystem from (the real-life) disk. If it takes a long time, that means your hard drive must be really, really slow. It is particularly curious that reading takes a long time, while writing does not.

**Comment by JoeSGT** [comment]
If it is the harddrive issue how would i go about fixing that?

**Comment by Techokami** [comment]
Get a faster hard drive. It's an actual physical, real-world hardware issue.
On that note, you miiight want to consider running some hard disk diagnostics. Slow hard drives are a sign of impending death, from personal experiences.

**Comment by JoeSGT** [comment]
Here is my results of testing for a few hours, it turns out it's NOT my harddrive issue on OVH dedicated servers, i took a copy of my laggy server and ran it on my computer, my computer spec's are
GTX 980, amd 8350, 16GB RAM 250GB SSD with h100i watercooling and i left my server on my computer online and since it was on my computer no one was on it the server was lagging very hard TPS was hitting around 1-2 TPS i left this for 10 Mins with no one on that server that was on my computer 
after the 10 minute mark had paste i took down the server and remove OpenComputer mod 
boot back the server on my computer and TPS went up straight up to 20TPS within seconds.
I have also when to do this same steps on my OVH dedicated servers and got the same results.
Sorry this took so long i wanted to go into more detail about this lag problem. Also my internet wasn't that great so i had to download a copy of the server. I hope this help to figure out the issue that it's indeed OpenComputer mod lagging the server earlier i had provided WarmRoast but if this still not proof the server lagging because of OpenComputer then please tell me a better System then Timings and WarmRoast i would be gladly to try to do an another tool to determine the issue  thanks.

**Comment by thiakil** [comment]
@JoeSGT what is/are the computer(s) in your world actually doing?

**Comment by Vexatos** [comment]
It reading takes a long time and writing doesn't, that suggests that loading is simply called a lot of times, but that doesn't make much sense, it should mostly be called when chunks are loaded. Do you happen to have chunks with lots of computers that unload and reload all the time? (unloading should also write to disk, and that should still be more noticable than loading)

**Comment by JoeSGT** [comment]
Here is what the computer is doing, it's one of my players base, @Vexatos  seem to be right about chunk loading and unloading, i have tested it in his base that has the OpenComputer mod items in there
when i unload the chunk the TPS hit to 1-8 when i teleport to his base and load the chunk the TPS goes up to 20! here is an image of his computer
![2018-05-04_17 40 44](https://user-images.githubusercontent.com/30296350/39654375-88c07ab8-4fc2-11e8-8506-4fb6bd46b4f2.png)


![e22e3d326e383fb02ca2d94fe073964e](https://user-images.githubusercontent.com/30296350/39654390-99f39ec8-4fc2-11e8-8797-b0519433afe2.png)
I am not sure what this player actually doing in the computer but it seem normal. The player is offline and unable to contact him to get more detail of what his doing

**Comment by Vexatos** [comment]
Something seems to be constantly unloading and reloading the chunks the computer is in, that's likely not related to the computer itself, and there would be nothing I can do about it; a single or a few badly coded blocks in the chunk might cause that, or something else. A solution would be making sure the chunks always stay loaded.

**Comment by JoeSGT** [comment]
But very confuse if it's not the computer it's self then how come when i remove the mod the TPS was stable and also if it really wasn't then how come nearly everything was pointing to that OpenComputer mod, even warmroast was pretty much saying it was from that mod.

**Comment by Vexatos** [comment]
OC is likely not the cause but just a symptom of the repeated chunk unloading and reloading. Loading and saving takes more time than it does for many other mods, but not enough that it should impact TPS, so if the chunk loads and saves a lot of times, OC will appear as the one taking the most time, but its blocks are saving just as often as any other block in that chunk, it is just that the other blocks do not have as much data to load or save.

**Comment by JoeSGT** [comment]
in OC is there a way to prevent computers from saving until a server restart/stop ? because i check the chunk there are no chunk loaders or any of the sort

**Comment by JoeSGT** [comment]
It turns out it's a sponge issue, causing it to unload and load chunks
not too sure how it work but once i removed SpongeForge the issue went away

**Comment by JoeSGT** [comment]
@thiakil  I spoke to the player about his computers and he said he was trying to learn how to use the mod and did very little in turns out all he did was just putting an operating system.
