### ISSUE TITLE
[Bug] Tablet icon still blinks even if setCursorBlink(false)

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#2827]
Hello,

The icon of the tablet, in the inventory, is still has its square symbol after > blinking even if is is disabled by setCursorBlink(false).

OpenComputers version: 1.7.2 for mc 1.12.2

**Comment by payonel** [comment]
you mean while you are holding the tablet? that's not actually the openos cursor, that's just how the tablet renders when you're holding it, but not viewing/interacting with the screen

**Comment by ExDomino** [comment]
ComputerCraft hides it when the cursor stops blinking. You could imitate them.

**Comment by skyem123** [comment]
The problem is that there's no API to tell the mod that the cursor is rendering. All cursor rendering is done manually in the Lua code by setting and resetting a character at a position. Maybe there should be a "hardware cursor", but that's a different feature request...
