### ISSUE TITLE
[1.12.2] Client Crash - Out of bounds - at li.cil.oc.client.renderer.block.CableModel.

### ISSUE THREAD

**Issue by ProsperCraft** [MightyPirates/OpenComputers#2828]
I got this on logging in to the server and opening a beehive.

https://gist.github.com/ProsperCraft/be852a4bf67b3de0197d0fc32a0d3c67

Here are screenshots of the simple setup we have, the adapter is touching a Zetta Industries battery terminal to read its level.

![2018-05-04_15 04 21](https://user-images.githubusercontent.com/4427684/39653031-a563861c-4fac-11e8-91c1-e977983c14b4.png)
![2018-05-04_15 04 32](https://user-images.githubusercontent.com/4427684/39653033-a58bc0c8-4fac-11e8-8aa0-4400dba7214c.png)

**Comment by thiakil** [comment]
@ProsperCraft are you able to test with this? http://maven.thiakil.com/OpenComputers-MC1.12.2-1.7.2+495f4a451.jar

Code is at https://github.com/thiakil/OpenComputers/commit/495f4a4513afad830a25d50e15434e11eded7c94

Technical explanation: It looks like `getQuads` is accessing the `world` from the Render Thread, which is rather unsafe.

**Comment by ProsperCraft** [comment]
Its a big multiplayer server, and it hasn't happened since, not sure how I could reproduce it.  Will update when you push to curse.

**Comment by thiakil** [comment]
I'm not an OC dev :P

It is likely to be a very rare condition, possibly to do with rendering a newly loaded chunk

**Comment by payonel** [comment]
@thiakil very nice, thank you for looking into this. I'll mark this ticket for 1.7.3 and when I get to it, test and merge your work (or request you make a PR for us)

**Comment by thiakil** [comment]
I saw a few more usages of the Tile prop that shoves the TE ref into ExtendedBlockState, so I'll look at changing them and then make a PR

**Comment by payonel** [comment]
thanks @thiakil 
i reviewed your code and test it
