### ISSUE TITLE
1.3 dev build is SHIT

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#283]
Sorry but it is:
Crashed randomly somewhere in the native lib(cant give you the report now, but its the 64bit version if that matters)
Is incompatible with existing addons(CRASH)
Disassembler is op, it gave me a huge load of stuff off a t1 case
Assembler cant be automated(no robot trading with forestry :-(    )

**Comment by fnuecke** [comment]
While I do appreciate feedback, I really don't appreciate your tone.

Anyway:
- The crash is something I'm aware of and looking into. It's not even beta yet, so what made you believe the build is stable?
- Incompatible? Well no shit, the API changed! Which I mentioned very, very clearly on Jenkins.
- The disassembler at best returns the items that were used to craft the items. It's the, IMHO preferable, alternative to highly complex, upgrading recipes. If something else comes out, file a proper report, not a "zomfg op y it no work leik i want!!!"
- I might look into making the assembler start when it gets a redstone pulse. It can already be filled appropriately by robots with an inventory controller upgrade. I have no clue what you're talking about wrt Forestry.

**Comment by Wuerfel21** [comment]
Sorry for that tone, but i didnt ever think it was stable( its a crappy alpha?!)
Well, an legacy thing would be very cool, thats what i meant.
And increasing the disassembler "nope!" Chance to 25% would be alot more balanced.
Oh, and forestry is a mod which has automated tradeing, with mfr, buildcraft, ic2 and forestry you can make a 100% automated trade station where others can buy stuff

**Comment by Techokami** [comment]
> Is incompatible with existing addons(CRASH)

See the OC forums for 1.3-compatible downloads of Computronics. There are also builds of OpenPrinter that are 1.3-compatible. And OpenComponents/ImmibisPeripherals on 1.7.2 are somehow compatible, from my testings.
