### ISSUE TITLE
Remote Terminal Fail To Work After Re-linkage

### ISSUE THREAD

**Issue by tongkl1** [MightyPirates/OpenComputers#2830]
After I join the terminal server and another server together I open the remote terminal and nothing happened. The only way to solve is to re-enter the world and everything goes back to normal.Ver 1.7.2.

**Comment by payonel** [comment]
we have fixed issues with the terminal server connections in our dev builds, which will be in our next 1.7.3 patch release
retest with our dev builds, if it repros, please give precise steps that cause the failure
https://ci.cil.li
