### ISSUE TITLE
Shift clicking components into a computer case crashes.

### ISSUE THREAD

**Issue by brisingraerowing** [MightyPirates/OpenComputers#2832]
[Crash Log](https://gist.github.com/BrisingrAerowing/cf2d572df17dd1a4ce02a52b4f245de3)

I originally noticed this in a development environment, but chalked it up to a devenv specific issue at the time.

**Comment by feldim2425** [comment]
I have the same issue. 
Minecraft 1.12.2 
Forge 14.23.3.2670 (also tested with 14.23.3.2701)
OpenComputers 1.7.2.71

https://pastebin.com/AJqZCAdU

**Comment by brisingraerowing** [comment]
[These two lines](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/common/container/Player.scala#L69-L70) are the root of the issue. The `null` should probably be `ItemStack.EMPTY`, or there should be a null check on line 70.

EDIT: [This](https://github.com/MightyPirates/OpenComputers/commit/37c3ddaf91403033b533bd8b93647d421d6504e0) is the commit that caused the issue. @payonel

**Comment by payonel** [comment]
fixed in https://github.com/MightyPirates/OpenComputers/pull/2882
