### ISSUE TITLE
config version check fails, reverting custom values in 1.12

### ISSUE THREAD

**Issue by payonel** [MightyPirates/OpenComputers#2833]
as reported by cat2002 in irc, our config version check fails and we revert some values to their default values
Updating config from version `@VERSION@` to `@VERSION@`

**Comment by Vexatos** [comment]
Blame @fnuecke, it was removed in [this commit](https://github.com/MightyPirates/OpenComputers/commit/aaf1b234408ebc2ba8cd8f3da4db63cee0a5d6cd#diff-c197962302397baf3a4cc36463dce5ea).
