### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by neumannfe** [MightyPirates/OpenComputers#2834]
If i program a drone and test the program in a Computer,it works,if i run it in a drohe,i'll get the error:attempt to Fall a nil value(global  'require') for my first line,which is :component = require("component")

**Comment by payonel** [comment]
openos provides the `require` global method, and it loads libraries in openos' /lib folder
in your drone you have neither of those things
programming a drone is essentially programming a custom os, read this wiki page: https://ocdoc.cil.li/tutorial:custom_oses
