### ISSUE TITLE
ls -al /dev/ causes a 'C-call boundary' exception on first call

### ISSUE THREAD

**Issue by notpeelz** [MightyPirates/OpenComputers#2835]
Calling `ls -al /dev` triggers a C-call boundary exception, and crashes subsequent `ls` executions.

Tested on OC 1.7.2.1166, MC 1.7.10, OpenOS 1.7.2

Steps to reproduce
----------------------

1) Boot machine
2) `ls -al /dev`
3) `ls /dev`

![image](https://user-images.githubusercontent.com/920910/40210153-5d76df06-5a11-11e8-9661-7ccd4b650335.png)

Workaround
--------------

If `ls /dev` is executed first, it prevents `ls -al /dev` from crashing.

![image](https://user-images.githubusercontent.com/920910/40210255-e870fe20-5a11-11e8-845a-512fe9a5979a.png)

**Comment by payonel** [comment]
this was fixed with a small refactor to `ls`, putting all the filesystem calls before functional calls to lua std lib like pairs
fixed in 1a6756248c010fdceff6f50ea4f3023c9362931a
