### ISSUE TITLE
cp doesn't expose a `-f` (force) option to disable prompts

### ISSUE THREAD

**Issue by notpeelz** [MightyPirates/OpenComputers#2837]
The `cp` CLI program doesn't expose the `f` (force) option from `transfer.batch()` to disable prompts, but it exposes `i` to enforce overwrite prompts.

Tested on OC 1.7.2.1166, MC 1.7.10, OpenOS 1.7.2

**Comment by payonel** [comment]
irl `cp -fi` still prompts, that's why i left it
but given that `cp -i` is the default alias for `cp`, I've considered allowing `-f` to disable overwrite prompt

also, `transfer` isn't a public api, i use it for internal purposes. if it isn't on ocdoc, you can assume it is internal

**Comment by payonel** [comment]
this has been fixed, `cp` now supports `-f` to ignore the `-i` option
