### ISSUE TITLE
uuid lib doesn't import bit32 (crash when calling uuid.next())

### ISSUE THREAD

**Issue by notpeelz** [MightyPirates/OpenComputers#2838]
Tested on OC 1.7.2.1166, MC 1.7.10, OpenOS 1.7.2

**Comment by skyem123** [comment]
Out of curiosity, what Lua version is this? (see it by running the `lua` program, which should give the version, which should be either 5.2 or 5.3)

**Comment by notpeelz** [comment]
Lua 5.3

**Comment by payonel** [comment]
yeah, it's fixed in dev builds: https://ci.cil.li/
it'll be generally available in 1.7.3
