### ISSUE TITLE
Incompatibilities with Cubic chunks

### ISSUE THREAD

**Issue by Alessandro404** [MightyPirates/OpenComputers#2840]
OpenComputers-MC1.12.2-1.7.2.67
when used with: malisiscore-1.12.2-6.4.0 and CubicChunks-1.12.2-0.0.835.0-SNAPSHOT-all

Every time I join a world in singleplayer it gives me this error: 
§aOpenComputers§f: There were §cerrors§f running the class transformer. Please report this, together with your (full!) FML §alatest.log§f/§afml-server-latest.log§f logfile, thank you!

I'm testing in a custom cubic world

Everything but GUIs under Y=0 works fine.
I've tested drones, robots, modems and so on on y 2048+ and everything works.

The only problem i've found is that I cannot interact with blocks under Y=0. Robots still works and so everything else, and I can access the gui of tablets and drones, but i cannot open cases or robots with right click.

[latest.log](https://github.com/MightyPirates/OpenComputers/files/2019777/latest.log)

**Comment by Niko-sk2x** [comment]
The class transformers errors appears to be a mixin issue https://github.com/SpongePowered/Mixin/issues/252
