### ISSUE TITLE
[Suggestion] All components should have an address() method

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#2841]
Hello,

My suggestion is simple: all components should have an address() method, not only the computer. At this moment, it is impossible to get the address of the primary component. For example, if I have a computer with two redstone I/O block and a redstone card inside the computer, there is no way for the program to tell if the redstone signal come from an external redstone block or from the internal card. The doc says that the address would be the address of the computer, but it is the address of the internal redstone card and there is no way to get it.

I would like to ask you if you can add an address() method to all components please.
Thank you in advance!

It is also possible to get the type of the component and its position inside the computer as well? In real life, computers can get this information. Position would be zero if this is an external component.

**Comment by Vexatos** [comment]
Wasn't there already `component.redstone.addr` or something similar?

And you can get a list of all addresses of a type using `component.list("redstone")`

**Comment by ExDomino** [comment]
But you can't get the address of the specific component that you have already linked.

**Comment by payonel** [comment]
you can access the string this way: `component.redstone.address`
That'll give you the address of the primary (an openos term) redstone care

With any given proxy, you can use that proxy `proxy.address` of any and all components
Also, the component slot (`proxy.slot`) can give you info about "where" it is

**Comment by ExDomino** [comment]
Where can I found these methods in the documentation?

**Comment by payonel** [comment]
https://ocdoc.cil.li/component:component_access
it could be improved :)

**Comment by ExDomino** [comment]
And for proxy.slot? Are there any other attributes than address, type and slot that I should know?
