### ISSUE TITLE
[Bug] redstone_change from computer gives the redstone card's address instead of the computer's address

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#2842]
Hello,

The doc says:
> The address is either that of the Redstone I/O block or that of the computer with the redstone card that generated the signal.

But the address is the redstone card's address, not the computer's address.
This is no way to know if the signal is from the computer or from an external redstone block.

**Comment by payonel** [comment]
the documents are wrong, it is the intent that signals are process by the cards that provide that capability
for example, modems handle modem messages, redstone devices handle redstone messages
I did review the code to see how we could provide the computer case address for these signals specifically, and it was a considerable change for just this type of signal, it is clearly not the intent of the code to do this.
I'll update the docs, thank you for finding this
if you want to know where the signal originated from, you can proxy the redstone devices, and internal cards will have a positive integer slot, referring to the slot index where the device is installed in the computer inventory
