### ISSUE TITLE
Make robot better suited for farming operations

### ISSUE THREAD

**Issue by Rami-Sabbagh** [MightyPirates/OpenComputers#2844]
I was going to create a robot in my survival world to do the farming work for me, but I faced the following issues:

1- The robot converts any hoed dirt block to  normal dirt block, very bad for farms and villagers grass paths.
2- For some reason it fails to automatically suck the wheat and seed after swinging (using `swingDown()`), A walkthrow is to equip a tool.
~~3- It's not possible to know if the wheat has fully grown or not.~~ _Turns out that the geolyzer can do this._
~~4- Calling `robot.suckDown()` rarely works.~~ _Using the item magnet upgrade solves this_

**Comment by sshilovsky** [comment]
1- The hoed dirt block is converted to normal whenever any other block is placed atop of it. I doubt this is going to get fixed (there is probably no easy and all-compatible way to do it). If you want your robot to build your farmland, you can do it from the side, removing and replacing dirt row-by-row.

2- Real issue. This happens for me with any block, not just wheat. Opencomputers 1.7.2.67, MC 1.12.2, forge 2655. `robot.swing()` and `components.robot.swing(3)` both return `nil, "unknown error" ` immediately, the block starts to get destroyed though regardless, even tho the robot could've moved away already. (e.g. `robot.swing(); robot.up()`)

UPD: this happens only when no instrument is equipped: you can probably workaround this by equipping nearly anything into tool slot, be it a wooden stick or a hoe.

3- It's not possible right now so far as I know. You can just farm the whole plot on timer. I would like to see database upgrade be able go get data from the world some day, not just the inventory.

4- This should work, but it gathers items just from below of the robot. Some items could have been dropped on neighboring blocks.

**Comment by thiakil** [comment]
1- likely because you're telling the robot to go to the block directly above it. A robot is a block itself, so this triggers vanilla logic. You should be able to have the robot in the block above the crop (2 up from the farmland).

3- Geolyzer can do this; `geolyzer.analyze` when used as an upgrade

**Comment by sshilovsky** [comment]
Oh my, I didn't even realize that geolyzer can be used as an upgrade

**Comment by Rami-Sabbagh** [comment]
4- I discovered that there's the magnet upgrade (whatever is it's name) which will extend the range so it can suck them, but as @sshilovsky said, It's easier to equip a tool in the robot (for farming purposes, a hoe)

**Comment by sshilovsky** [comment]
2- This is actually already solved in recent builds, at least for 1.12.2: https://ci.cil.li/view/OpenComputers/

**Comment by payonel** [comment]
for concern 1. "The robot converts any hoed dirt block to normal dirt block, very bad for farms and villagers grass paths."
yes, it is a whole block. you need to fly +1 block above the soil. and you can hoe the dirt below from above like that using `component.robot.use(sides.down)`
Using the "helpful" robot library (from require("robot")) has its own `use` method which does have the same param options, and forces you to pass sides.FRONT to the first argument of component api version of the method. This first param is what lets you specify in what direction from the robot you want to use the tool.

**Comment by payonel** [comment]
I cannot reproduce issue 2. on 1.7.10 dev builds. I'll retest on 1.12 later

**Comment by Rami-Sabbagh** [comment]
It's been a year, I no longer remember anything about this issue 😛

**Comment by payonel** [comment]
confirmed working in 1.12 (see dev builds)
