### ISSUE TITLE
Pulling from AE Inteface using OC Transposer doesn't update item

### ISSUE THREAD

**Issue by Faeranne** [MightyPirates/OpenComputers#2845]
#### Description
Attempting to transfer an item present in an Applied Energistics ME Interface using the OpenComputers Transposer causes the item to not be restocked inside the interface until the interface's UI is clicked on by a player.

Steps to reproduce:
 - Setup AE2 with interface containing 1 item in the top slot. Ensure there are sufficiant items inside the network
 - Place a OC Transposer next to the interface
 - Place an inventory block next to the Transposer
 - Call `.transferItem()` with appropriate side parameters
 - Check AE interface

Clicking inside the UI of the interface causes the item stack to properly update.

Tested in Single Player including only AE2 and OpenComputers version 1.7.2.67

Log Paste: https://paste.ee/p/yn77J
Last line regarding possible item duplication was created when running the transfer.

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- OpenComputers Version: 1.7.2.67
- Forge Version: 14.23.3.2702

Related issue AppliedEnergistics/Applied-Energistics-2#3508

**Comment by Faeranne** [comment]
Cross post issue from AE2 per @yueh's request

**Comment by GuntherDW** [comment]
I'm currently looking into this (as an AE2 dev), and have noticed a couple oddities.
When you extract less than the entire stack, it has time to "refill" the stack. When you extract the entire stack, it doesn't.

The main issue seems to be in InventoryUtils.scala, where the stack gets set to Items.AIRx0 (probably an isEmpty() check too much somewhere?) when it travels through "consumer(extracted)".
https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/util/InventoryUtils.scala#L140

It then logs as you've show an error message about how items might have been duplicated.
I'll update this message when I find out more.

EDIT: Hmm, I might be wrong, after testing with regular chests the root might lie elsewhere.

Looks like in the second pass (simulate=false) the ItemStack stacksize gets set to 0 it might just be setting the value somewhere too quickly?
Looks like the stack.split(amount) call in InsertIntoInventory() might be to blame, either we don't implement it just right, in comparison to Forge's wrapper classes at least, or it might be something else?

**Comment by fscan** [comment]
Just for some insight to the implementation in AE2: The passed IItemHandler is subclass of forges ItemStackHandler,  extraction and insertion logic is untouched.

Looking at the code and comment (with no clue about scala) it seem to assume that extractItem always returns a copy. This is not true for the simulate case, just take a look at net.minecraftforge.items.ItemStackHandler.

**Comment by GuntherDW** [comment]
I kind of suspected something like that indeed.
But due to my limited Scala knowledge I kind of made it worse when I tried that so I kind of left it at that when I was debugging the difference between the IItemHandler classes I was checking ("vanilla" chest with Forge wrapper vs Interface).

**Comment by payonel** [comment]
thank you everyone in this ticket, you all provided fantastic investigation and helpful notes. We have this fix pushed in our 1.10, 1.11, and 1.12 minecraft versions (this bug did not exist in 1.7.10)
