### ISSUE TITLE
1.12.2 Project:Red Mod compatability readding

### ISSUE THREAD

**Issue by Keridos** [MightyPirates/OpenComputers#2847]
Seems like in 1.10.2 PR was supported by OC; PR development seems to be pretty active on MC 1.12.2 branch on their github. Would be very nice if support f.ex. for bundled cables was readded to OC on 1.12.2

**Comment by desvandev** [comment]
Adding to this so it gets more attention. Not even EnderIO Redstone Conduits have bundled support (they had in previous versions). I belive there's not a single mod in 1.12 that OC can i/o bundled settings.

**Comment by Cre8or** [comment]
Also subbing to this issue, A lot of my builds depend on bundled wires, as it is simply the most practical way of handling lots of redstone signals in a compact space. Not to mention that without them, you're limited to a max of 6 wires ( = amount of sides of a computer block), which is often not enough.

**Comment by payonel** [comment]
redstone support, and bundled redstone support, in OC is very important to me. this will come back!

**Comment by payonel** [comment]
now official back, see dev builds: https://ci.cil.li/job/OpenComputers-MC1.12/
will be part of 1.7.3
