### ISSUE TITLE
[MC1.12.2-1.7.2.67] Robot crafting deleting non-consumable crafting items.

### ISSUE THREAD

**Issue by JBarcelos** [MightyPirates/OpenComputers#2848]
The crafting recipe I tried to perform was the flower petal + pestle and mortar -> floral powder recipe in Botania. The pestle and mortar is usually left behind when crafting regularly with workbench. Though when crafting with a robot, it deletes the pestle and mortar and only leaves behind the floral powder. I've tried this with several other mods that have non-consumeable crafting and it seems to also delete those items. E.g. Pam's Harvest: salt recipe, Immersive Engineering: any recipe with the engineer's hammer.

**Comment by payonel** [comment]
to be honest, some mods do some pretty weird things with their crafting, and the core minecraft objects involved break encapsulation. I'll have to this specifically, but it may not be reasonable fixable. However, do make sure you are using our latest version for which ever version of minecraft you are using: http://ci.cil.li/

Thanks

**Comment by thiakil** [comment]
What kind of weird things do you mean?

Any items present in the return of `net.minecraft.item.crafting.IRecipe#getRemainingItems` should remain in the grid / be copied to the output.

**Comment by JBarcelos** [comment]
@thiakil The non-consumable items just don't get copied to the output. It only results in the output of the recipe. In the Botania example, the pestle and mortar are consumed though they shouldn't be; in Pam's harvest, the pot is consumed though it shouldn't be; etc.

**Comment by thiakil** [comment]
oh I understand the issue; my comment was directed towards 

>to be honest, some mods do some pretty weird things with their crafting

**Comment by JBarcelos** [comment]
@thiakil Oh, I see.

**Comment by payonel** [comment]
@JBarcelos you should still test with our latest builds
@thiakil i have dealt with a few. It would be nice if they obeyed the intended use of the IRecipe interface and methods. Mods tend to toss their side affects and outputs all over the place, inconsistently. Some make direct changes to the underlying inventory arrays, while others don't. Some make changes directly to the inventory controller. some expect you are passing your crafting materials by reference, and they make changes to the count of those itemstacks. And yes, some actually use the IRecipe interface.

**Comment by GReaperEx** [comment]
I'm using 1.7.2.97 for minecraft 1.11.2 and the same issue is still here... Any updates?
