### ISSUE TITLE
Hex font file problem

### ISSUE THREAD

**Issue by mingl0280** [MightyPirates/OpenComputers#2851]
Is there any way to add new chars into the font.hex? There are a lot of unicode characters missing.
Thanks.

**Comment by payonel** [comment]
The delay in adding glyphs are our 2 requirements
1. must have 8x16 blocks, and monospaced
2. must be public domain
Otherwise, you are free to modify your own or make a fonts.hex in your resource pack

**Comment by skyem123** [comment]
I thought the question was about the format and how to edit it?

**Comment by payonel** [comment]
we use https://github.com/asiekierka/funscii for generating the font.hex file. 
the format is
codepoint hex:serialized hex-based bitmap
