### ISSUE TITLE
Add config option for passing NBT data uncompressed

### ISSUE THREAD

**Issue by Someguynamedpie** [MightyPirates/OpenComputers#2853]
I'm ok with my players being able to read and utilize the NBT data from items. It'd be nice if there was a way to allow this in a way that allowed the NBT data to be converted to a Lua table.

**Comment by payonel** [comment]
we provide more meta data if you set allowItemStackNBTTags in your config. That's the extent of this feature we plan on supporting. thanks

**Comment by Someguynamedpie** [comment]
Care to elaborate on why?
