### ISSUE TITLE
Allow linking of multiple Linked Cards together

### ISSUE THREAD

**Issue by Someguynamedpie** [MightyPirates/OpenComputers#2854]
If you're an avid user of RFTools dimensions, you know how much of a pain it can be to use with OpenComputers. It'd be nice if there was an official way to link Linked Cards together to avoid the overhead of opening a ton of TCP sockets to a relay, to form a sort of mesh/P2P network that works across dimensions.

**Comment by LizzyTrickster** [comment]
When you craft linked cards you get 2 per craft (they are bound to each
other).

>
Having more than 2 cards on a "channel" would be a headache as the cards do
not transmit any identity info like the modem cards do

**Comment by Someguynamedpie** [comment]
It's a headache I'm willing to deal with in software. There's no real viable way other than creating a lagfest of a ton of computers to deal with routing multiple of them together.

**Comment by payonel** [comment]
you can have one machine with multiple link cards to act as the hub
yes it is a complex set up, but, you have a complex scenario
it is best if we keep our cards simple

**Comment by Someguynamedpie** [comment]
OpenComputer's entire niche is that it's not very simple. Your solution involves adding unnecessary overhead to the server by running several OC instances together to simply get cross dimension communication, or to (wrongly) encourage users to create (at the minimum) hundreds of TCP sockets to an echo server.

I also don't see how interlinking multiple linked cards isn't very simple, either, given that it already works how you'd think so you'd only have to add the crafting recipe.

**Comment by skyem123** [comment]
I guess the question is, can it be done in a way that doesn't violate the principle of least surprise?

**Comment by Someguynamedpie** [comment]
Naming it something like it is in code, e.g. a Quantum Network card might make more sense if this is done. Or even adding some way to bridge linked cards with a device to avoid having to create an excessive number of tile entities to communicate across dimensions.
