### ISSUE TITLE
Single Player crash when Adapter is set next to EnderIO Capacitor

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2856]
I am using MC 1.12.2 with ATM3 modpack v5.9.6b (latest at this point) and I have been able to reproduce this quite a few times in a creative single player game, even creating a new save.

I have been doing some testing to get a script working that I downloaded into the Opencomputers system.  The program, is to control Reactors and Turbines from Extreme reactors, and it is working well.  The second I put an Adapter down to try to read the usage from an EnderIO capacitor the local game server locks up hard.  I have tried letting it sit and chew through everything and I have tried breaking the adapter to get it to come back.  The only way I can recover the game is to hard crash the game.  I am not sure it will output a good log for you, but if needed, I will update the log files.

This pack does include the Computronics pack that is required to interface with EnderIO.  If I am doing something wrong, someone please correct me!

Thanks for any help!

**Comment by MasterEnderman** [comment]
This also happens with Ender IO Capacitor Banks in 1.10.2.

**Comment by thiakil** [comment]
Try to reproduce with the minimum set of mods, starting with just OC & EIO

**Comment by payonel** [comment]
what oc version?

**Comment by MasterEnderman** [comment]
I'm using OpenComputers version 1.7.2.170 for 1.10.2 with EnderIO version 3.1.193.

This is the Server Crash Report when the user places an adapter next to a EnderIO Capacitor Bank.
https://pastebin.com/NAkWY52z

**Comment by payonel** [comment]
sorry. I cannot get this to reproduce. I tested enderio with ic2 in 1.10 as well as 1.12. I tested atm3, the exact version you were using. It never crashes for me. I even built a reactor in atm3, placed plenty of ender capacitor and adapters. Downloaded the brgc program, ran it from a computers...the whole works. No crashes, no lock ups. nada :(

For what it is worth....we have indeed made plenty of fixes for enderio as well as for ic2.
I need to close this as no repro. If you can repro this - ESPECIALLY using our latest dev builds please)
