### ISSUE TITLE
crash in tryMoveAllSlotToSlot

### ISSUE THREAD

**Issue by sshilovsky** [MightyPirates/OpenComputers#2858]
I get crash when trying to shift-click items away from (or into) OC inventories

Happened to me with electronics assembler and with tablet upgrade slot.

https://gist.github.com/sshilovsky/1b4d892ec591bb2539902f338cdb6569

Just upgraded from .67 to .71

**Comment by sshilovsky** [comment]
It only happens when the target slot is empty, i.e. you don't merge stacks of the same type of item.

My guess was that it was introduced by 648cdf78aa64fe44c70f4714fcd8391d6946ba7a, but .69 also has this issue

**Comment by Vexatos** [comment]
Fixed via https://github.com/MightyPirates/OpenComputers/commit/088964b168024f848eb5e7be86cce06982b70db2.
