### ISSUE TITLE
tier 3 hologram

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#286]
As of there is a t3 of everything why not for holograms?

A tier 3 hologram may have 15 pallete entries.
Also using basic textures might be cool, like wood, log, dirt, stone, ironore,glass,leaves and so on

**Comment by Techokami** [comment]
Apparently, Tier 2 is already pushing things. We'll see what Sangar says, but my Magic 8 Ball is saying "No"...

**Comment by Wuerfel21** [comment]
Well, just say "if you have a crappy computer, dont use holograms or your head will explode¿¡

**Comment by Wuerfel21** [comment]
Oh just some flashing ideas: higher max scale(me wants frikn huge voxeeeeeelllls)(block sized voxels), maybe also increase resolution across tiers.
Now the most wierd idea, t3 holograms can turn collusion on, so voxels can be walked on, come on we already seen some airship mod which lets you move your stuff, rotate it and still have collusion

**Comment by Techokami** [comment]
Archimedes' Ships pulls it off by making the block region a compiled entity, then erasing the blocks from the world. You can't stand on a compiled ship, it has to be decompiled first back into blocks that overwrite the air blocks it occupies.

That's not to say a means of rendering block-sized voxels isn't doable. You could instead use a command block and the set block commands. I think adapters will let you drive command blocks? Might need OpenComponents. If not, well here's a compelling argument to make it possible! :)

Sent from my Windows Phone

**Comment by Wuerfel21** [comment]
Ahh block sized voxels needs just a scale of 16

**Comment by Wuerfel21** [comment]
http://www.minecraftforum.net/topic/488434-125-zeppelin-031-wip/ seems to have collusion, but isnt further develoπed

**Comment by Wuerfel21** [comment]
If performance is such a issue a config option "disableHolograms" would help(or a button in the grapic options menu)

**Comment by Wuerfel21** [comment]
Sorry for quad posting, but command blocks arent a option either, cause we want to use it in survival

**Comment by evg-zhabotinsky** [comment]
By the way, item name colors (yellow for monochrome hologram and blue for color one) say that these holograms are in fact tier 2 and tier 3 respectively :)

**Comment by Techokami** [comment]
Why not edit your posts instead of make 4 in a row?

Sent from my Windows Phone

**Comment by Wuerfel21** [comment]
Awww, i dont see the edit button on the mobile version

**Comment by fnuecke** [comment]
Sorry, not going to happen. I wouldn't have a problem with anyone creating a t3 hologram as an addon, though, if they want to do that, just to make that clear. As evg-zhabotinsky pointed out, holograms t1 and t2 should be considered 'general quality' tier 2 and 3 already (i.e. I consider a t1 holo as the same global tier as a t2 screen, and a t2 holo the same as a t3 screen). And also there's the performance issues that they already have, so...
As for solid holograms... that doesn't make sense, really, IMHO. I think you're looking for MFFS ;-)
