### ISSUE TITLE
tablet_use suggestion

### ISSUE THREAD

**Issue by sshilovsky** [MightyPirates/OpenComputers#2860]
first of all, it's bugged right now: the event structure is inconsistent with other events

Suggestions:

1. tablet_use should be fired even if there is no geolyzer or any other upgrade. Consider it just pressing a button on the tablet.

2. When geolyzer is installed, the event should contain block analysis data (hardness, harvest_tool, color,...)

3. When navigation upgrade is installed, the event should contain block coordinates (granted both the block and the player are inside navigation upgrade map area). It would be perfect if distance limitation is increased in case of navigation upgrade presence.

**Comment by payonel** [comment]
also, it shouldn't pass a table, but a serialized table. definitely bugged

**Comment by sshilovsky** [comment]
I would also really be happy to see a custom key binding for tablet_use. Or a binding to touch tablet at a random point on screen. I.e. anything that can be used fast and often, and doesn't require holding mouse button for longer time or opening tablet UI.

**Comment by payonel** [comment]
people have been using the table result for some time, leaving that as is
also, removing features from 1.7.5 patch
changing this to open-for-adoption
