### ISSUE TITLE
suggestion: navigation upgrade getFacing() and tablet.getYaw() limitations

### ISSUE THREAD

**Issue by sshilovsky** [MightyPirates/OpenComputers#2861]
Some realism(tm) improvement suggestions:

* Navigation upgrade getFacing() and tablet.getYaw() should not work in nether

Motivation: vanilla compasses and maps do not report player facing in nether

* tablet.getYaw() should only work if navigation upgrade is present, even in the overworld

Motivation: pitch might be deducted based on gravity vector (assume accelerometer is available in every tablet), so getPitch() is reasonable to be always available, but getYaw() is not.

**Comment by payonel** [comment]
interesting, but i'm not inclined to make it LESS useful than it is :)
this is a tablet, it has it's own gyroscope :) it doesn't use a magnetic field which obviously the nether lacks
