### ISSUE TITLE
add filesystem table

### ISSUE THREAD

**Issue by jkhsjdhjs** [MightyPirates/OpenComputers#2862]
Add a file like `/etc/fstab` on linux systems to allow mounting drives to mountpoints different from /mnt/<addr> at boot-time.

For example:
```
# /etc/fstab
# <label> <mountpoint>
home /home
```
would mount the drive with the label `home` to `/home` instead of `/mnt`.

Currently I have to edit `/boot/90_filesystem.lua` to do this:
```
# Line 18 | /boot/90_filesystem.lua
+ if name == "<addr>" then
+   fs.mount(proxy, "/home")
+ else
+   name = fs.concat("/mnt", name)
- name = fs.concat("/mnt", name)
+   fs.mount(proxy, name)
- fs.mount(proxy, name)
+ end
```

It's not necessarily needed, but a neat enhancement in my opinion.

**Comment by skyem123** [comment]
Maybe there could be something similar to save symlinks?

**Comment by jkhsjdhjs** [comment]
Would be possible too, but why aren't symlinks persistent in the first place?
If they were I could just link `/home` to `/mnt/<addr>`, although I still find mounting prettier.

**Comment by skyem123** [comment]
Why not both

**Comment by payonel** [comment]
this request isn't without merit -- but let's discuss some of the finer points

i think it is fine to leave the default mounting to /mnt behavior unchanged, a filesystem can be mounted multiple times

also, you can create a bind point (folder to folder)
imagine /home is a natural dir on /, and / is /mnt/123
imagine in that /home/.shrc you have:
`mount --bind /mnt/xyz /home`

now /home/.shrc is /mnt/xyz/.shrc and /mnt/123/home/.shrc is no longer there

**Comment by jkhsjdhjs** [comment]
>a filesystem can be mounted multiple times

Ah ok, didn't know that, even though it is pretty obvious as `/` is mounted twice per default too.

>also, you can create a bind point (folder to folder)

Ok, nice feature. But you'd have to create a script that executes `mount --bind` every boot too which is possible via `/boot/rc.lua`.
On the one hand a filesystem table is not really a neccessary feature because it is possible via a script but on the other hand it would still be nice to have.

**Comment by skyem123** [comment]
It's definitely a nice to have feature which will make OpenOS more like a *nix! :P
