### ISSUE TITLE
Auto code indenting

### ISSUE THREAD

**Issue by bjr29** [MightyPirates/OpenComputers#2864]
It's kinda annoying having to press tab every line when trying to do something. I think when you've pressed tab on one line, it should carry it on until the coder breaks it. It would be very useful in my opinion to make looking back on the code easier as well.

**Comment by payonel** [comment]
you're talking about an upgrade to `/bin/edit.lua` yes? We all definitely want /bin/edit.lua to be a better editor, but we cannot. the main reason being memory cost. Edit needs to be simpler and lower in cost, not more. We need better editors, and they need to be external to openos unfortunately
