### ISSUE TITLE
Drone behaves incorrectly if powered on by a wake message

### ISSUE THREAD

**Issue by Fingercomp** [MightyPirates/OpenComputers#2866]
The program used:

![The program used](https://my.mixtape.moe/dbivzm.png)

I placed the drone on top of the stone block, and turned it on by pressing the button in the drone's GUI. As expected, the drone went 5 blocks up.

![Manual start](https://my.mixtape.moe/vzhnes.png)

~~I screnched the drone, and placed it on top of the stone block.~~ I turned the drone off by pressing the button, which made it return to the bottom. This time I sent the wake message to the drone.

![The wake message](https://my.mixtape.moe/ersjeg.png)

And the `drone.move(0, 5, 0)` call made the drone go up by 10 blocks, twice as far as it was supposed to.

![Started by the wake message](https://my.mixtape.moe/rajeef.png)

**OC version:** MC1.7.10-1.7.2.1166

**Comment by payonel** [comment]
seems like it is running the bios twice
could you send a modem message BACK from the drone on boot? see if that message is sent twice?

**Comment by payonel** [comment]
LeshaInc found that:
> it seems that preparePowerUp function is not calling in the wake-up message handler
> https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/common/entity/Drone.scala#L477
things work correctly if the drone is started by hand
