### ISSUE TITLE
Crashing Server when placing OC conduits (in loop?)

### ISSUE THREAD

**Issue by NikkyAI** [MightyPirates/OpenComputers#2867]
#### What happens:

when placing oc conduits or causing them to connect, sometimes (i think when creating a loop) the server crashes

#### What you expected to happen:

connected opencomputers ?

#### Steps to reproduce:

1. connect computer to oc wire
2. connect oc conduit
3. see if it crashes
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.26
- EnderCore: 0.5.31
- OpenComputers: 1.7.2.67
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
https://gist.github.com/NikkyAI/495f320873ef2fa7ed567217e778d99a

see also SleepyTrousers/EnderIO/issues/4720

**Comment by magus1972** [comment]
Same here.

**Comment by payonel** [comment]
sorry, with latest enderio and oc, i cannot reproduce this (And i made a LOT of loops in various configurations with computers)

**Comment by NikkyAI** [comment]
good news then, or possibly not enough info
thx

**Comment by payonel** [comment]
if you continue to experience problems, make sure you've updated both mods, and use our latest dev builds: https://ci.cil.li/job/OpenComputers-MC1.12/
