### ISSUE TITLE
Add in support for GregTech Community Edition

### ISSUE THREAD

**Issue by ScienceDrummer** [MightyPirates/OpenComputers#2869]
When starting the game with GregTech recipes selected in the config, OpenComputers says that some recipes were not loaded. Would there be any way of adding support for the new GregTech that came out? https://github.com/GregTechCE/GregTech

**Comment by payonel** [comment]
to be honest, our greg tech recipe support has been broken for a very long time. From the time we first added gregtech recipes as an option, greg tech items have changed considerably. I never play with gregtech myself and I haven't taken the time to familiarize myself with the items to make the best choices  for what a good experience in OC would be to use gregtech for crafting. Some avid gregtech user should review our recipes and make these changes in a PR for us!
