### ISSUE TITLE
tiered remote terminals

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#287]
Well, the title states it

**Comment by Wuerfel21** [comment]
Make terminals less expanive as laptops(terminals dont need cpu or ram) and we got a purpose for terminals

**Comment by evg-zhabotinsky** [comment]
(this comment was above the previous one)
As for me, I think it would be better to wait for laptops (if they are coming) and add something like ssh or telnet. This would also resolve #288 (remote terminal adapter for normal computers)
Then remote terminals are no longer needed at all. (Although I guess just adding tiered terminals might be easier)

**Comment by Wuerfel21** [comment]
Oh, and maybe higher tier terminals have a range multiiplier(t3 has 1.5 times the range of t2 aka 600 blocks when range is set to 400)(the normal one seems to be t2)
If the multiplier is for terminals, wlan cards could get the same threatment

**Comment by Wuerfel21** [comment]
Wtf, comments got out of order

**Comment by evg-zhabotinsky** [comment]
Sorry, I screwed the order of comments

**Comment by fnuecke** [comment]
Laptops or something similar are relatively likely to be a thing, depending on their cost I might adjust the terminal recipe to make it less... superfluous. I don't think I'll do tiered terminals, though.
