### ISSUE TITLE
suck can't work well with wirelesscraftingterminal

### ISSUE THREAD

**Issue by thestronger8** [MightyPirates/OpenComputers#2870]
If the client contains WirelessCrafting Terminal Mod(AE2 extension), the mothed "suck" of robot & Tractor Beam can't work well.

MC version: 1.7.10
OC version:MC1.7.10-1.7.2.1166-universal & 1137

**Comment by payonel** [comment]
can you explain the problem?
repro steps
what is expected
what actually happens
Please read this: https://github.com/iopleke/Minechem/wiki/Bug-Reporting-Guidelines

**Comment by thestronger8** [comment]
My robot installed "digger" from the floppy.When i run ""dig 5"", robot is working, but it can't pick up anything.
I enter "robot.suck()" in lua GUI, it return error " nil, unknown error"
![wa](https://user-images.githubusercontent.com/33371366/41889955-d3e77324-793f-11e8-8c08-c26fc3ad2f37.png)
![wa1](https://user-images.githubusercontent.com/33371366/41889959-dc0622e4-793f-11e8-9a02-d0e5953d9927.png)
![mod](https://user-images.githubusercontent.com/33371366/41890065-6969f96c-7940-11e8-9862-8166246bd3db.png)
I found that if I removed the wireless  crafting terminal MOD, then can work well

**Comment by payonel** [comment]
ah, interesting
ok, i will investigate

**Comment by ben-mkiv** [comment]
idk if it helps, but tested it on 1.12.2 with OC 1.7.2.67 and WCT 1.12.2-3.9.64 and it works fine as long as you provide a side as argument to both methods.
