### ISSUE TITLE
getStackInSlot(side:number, slot:number) not working as intended with robots

### ISSUE THREAD

**Issue by Alessandro404** [MightyPirates/OpenComputers#2871]
The sides.api doesn't work with robots when trying to use the inventory_controller upgrade.

It only works if the robot is facing the inventory and sides.forward is passed as an argument. Trying to use any other side return an "incorrect side" error.

**Comment by Alessandro404** [comment]
Nevermind, someone told me that sides is NOT for the robot but for the inventory. Still, i have found this information not really clear when reading the wiki.

**Comment by payonel** [comment]
i'll add a note to our "big wiki" bug to improve this info
