### ISSUE TITLE
Unable to access input slots for any machine

### ISSUE THREAD

**Issue by bendauphinee** [MightyPirates/OpenComputers#2873]
I have a robot with an inventory controller upgrade, and I've parked it in front of an industrialcraft2 machine, as well as a vanilla furnace. I attempted to load both with dropIntoSlot(), but slots 1-4 don't seem to be available.

getInventorySize() does return a number for the ic2 machine, and I can read the output slot.

**Comment by payonel** [comment]
mc and oc version, please
demo code you are using, screenshot of orientation

**Comment by bendauphinee** [comment]
Minecraft 1.12.2
OpenComputers OpenComputers-MC1.12.2-1.7.2.67

No specific code, just manually using the Lua console (trying out robot things before I actually write a script).

ic = component.inventory_controller

ic.getStackInSlot(sides.front, 1)
Returns info about the Coal. I did up to slot 9, the rest threw exceptions (aside, how do I paginate or otherwise capture the full exception text so I can read it?).

![2018-06-28_09 25 16](https://user-images.githubusercontent.com/521381/42034310-053af71c-7ab6-11e8-820a-34a2c463c3df.png)
![2018-06-28_09 30 03](https://user-images.githubusercontent.com/521381/42034311-054c1b1e-7ab6-11e8-928f-7157cfca2941.png)
![2018-06-28_09 30 45](https://user-images.githubusercontent.com/521381/42034312-055ac7d6-7ab6-11e8-81a4-d15a8362908b.png)

**Comment by ben-mkiv** [comment]
furnaces have sided inventories. so you can only access the middle slot from sides, top slot from top and bottom slot from bottom

**Comment by payonel** [comment]
I've confirmed on all versions of MC, with various containers, that yes, just as @ben-mkiv has stated, this was only a sided inventory issue

when interfacing with an inventory, you may not be able to get nor store an item into a slot, if that inventory refuses access from that side.

For example, the ic2 generator has 2 slots, and from the back you can place coal into slot 2.

**Comment by LMWafer** [comment]
This problem exists/can be solved in a similar way for Thermal Expansion machines : you need to configure as output and/or input a side before making the robot suck or drop. 

Tested version : 
- Minecraft 1.12.2
- Forge 14.23.5.2855
- TE 5.5.7.1
- OC 1.7.5.192
