### ISSUE TITLE
Can't change to unmanaged mode for raid.

### ISSUE THREAD

**Issue by Steve-xmh** [MightyPirates/OpenComputers#2874]
Like the title, i can't change it to unmanaged mode even i change hard disk's disk mode.
![ocraid](https://user-images.githubusercontent.com/39523898/42122500-77bd9342-7c75-11e8-9809-a86e3096a6c8.png)
![ocdf](https://user-images.githubusercontent.com/39523898/42122509-95994316-7c75-11e8-9714-2d14ffdc4a7b.png)

**Comment by payonel** [comment]
confirmed
putting unmanaged disks in the raid still adds a filesystem, not a `drive`

**Comment by DaComputerNerd717** [comment]
Can confirm this is still the case. Even if all drives in the raid are unmanaged, the raid still gives a `filesystem` component, rather than a `drive` component

**Comment by payonel** [comment]
so after some review, and discussing this with others for feedback - the raid wasn't intended for unmanaged mode and the hard disks should be reset to managed (and unlocked if locked readonly)
I've cleaned up the code to this end and now drives are wiped and reset to unlocked managed mode

**Comment by DaComputerNerd717** [comment]
What option do we have for using drives in unmanaged mode beyond just ones that fit in the computer/rack?
