### ISSUE TITLE
failed opening file for writing: etc/oppm.cfg

### ISSUE THREAD

**Issue by jckyeung** [MightyPirates/OpenComputers#2875]
![image](https://user-images.githubusercontent.com/40608508/42127890-c2063b86-7cd2-11e8-9bea-0b5815d81d12.png)

**Comment by payonel** [comment]
yes, oppm is hard coded to run from a rw rootfs. it is designed to store what you've installed on your system in /etc/oppm.cfg

**Comment by jckyeung** [comment]
which mean i cant install oppm in my opencomputer?

**Comment by payonel** [comment]
meaing, install openos on the system first, then reboot wit openos rw and install oppm

**Comment by kitgor14** [comment]
i installed openos before,but i still fail to open this file

**Comment by payonel** [comment]
(note to self: the solution might be to have the oppm install use the correct /etc/ )
