### ISSUE TITLE
Domain whitelist does not work.

### ISSUE THREAD

**Issue by GalacticArc** [MightyPirates/OpenComputers#2883]
MC: 1.12.2
Forge: 14.23.4.2705
Opencomputers: 1.7.2.67

**Problem:**
When setting up a whitelist for the internet card, it works with a single domain, but adding more domains seems to break it for some reason.

**Example that worked:**
``   
whitelist=[
      "skynet.ai"
]
``

**Example that failed (The whitelist stopped working with this setting)**
``
    whitelist=[
      "skynet.ai",
      "gist.github.com",
      "pastebin.com",
      "github.com",
      "raw.githubusercontent.com",
      "githubusercontent.com",
      "api.github.com"
    ]
``

Blacklist was empty in both cases

**Comment by asiekierka** [comment]
```
[20:38:55] [Client thread/WARN] [OpenComputers]: Invalid entry in internet blacklist / whitelist: githubusercontent.com
java.net.UnknownHostException: githubusercontent.com: No address associated with hostname
```

**Comment by asiekierka** [comment]
Either way, the whitelist should not just pass every domain through if one of them fails to resolve.
