### ISSUE TITLE
Request: Allow pack makers to change the required fuel

### ISSUE THREAD

**Issue by TheDeviantCrafter** [MightyPirates/OpenComputers#2887]
I'm working on a pack that gates things behind complexity rather than raw cost. To achieve this, I'd like to make Open Computers run on electrotine instead of fuel. There doesn't seem to be a config setting for this, so I'd like to request one.

Ideally it would contain a boolean setting to toggle whether normal furnace fuels worked. The pack maker could define a list of items along with their fuel values. Is something like this possible?

**Comment by payonel** [comment]
We discussed how to power OC without a "power mod", and we decided on the carpeted capacitor.  you can adjust how much energy sheep and ocelots produce in the configs. This was the video discussing that feature: https://www.youtube.com/watch?v=zbkZ-1dIR1o

We specifically decided that we didn't want the furnace to generate power for OC.

We accept any forge energy compatible mod to provide power to our power converter block ( https://ocdoc.cil.li/block:power_converter )

Review the options under the power section in the configs to see if any of those suit your needs.

**Comment by asiekierka** [comment]
If this doesn't happenstance with your theming, I'd recommend developing a single Forge Energy-compatible "generator" mod which simply only outputs to OpenComputers tile entities.
