### ISSUE TITLE
Update StargateTech 2 API

### ISSUE THREAD

**Issue by LordFokas** [MightyPirates/OpenComputers#289]
This: https://github.com/LordFokas/StargateTech2/tree/master/SOURCE/stargatetech2/api

... has changed last night, on v0.7.0-Alpha
Basically now IBusDrivers should implement a couple more getters, and there's some Generic (a.k.a. Templates) stuff going on with BusPackets (that shouldn't affect you), but still, if you want to give PC the ability to read feedback from the network packets they sent you should add a way to read each packet's Responses.

As a reference, I only do that for LIP packets, which use String responses.

Please update at your earliest convenience :)
Thanks

**Comment by LordFokas** [comment]
Oh, also there's a new protocol (see BusPacketNetScan) that allows any device to scan the network for other devices. \o/

That should be all for OC. Feel free to bug me if you need any references or ideas on how to use or implement anyof the new things :)

**Comment by fnuecke** [comment]
Nice! Updated, returning responses from `send()` instead of a boolean and added a `scan()` method to the abstract bus card. Also fixed abstract bus card recipe.

**Comment by LordFokas** [comment]
\o/
Thanks :)
