### ISSUE TITLE
oppm command does not work after installing oppm

### ISSUE THREAD

**Issue by DaveKnifeman** [MightyPirates/OpenComputers#2892]
I've installed oppm through the craftable floppy multiple times and it asks to install to ``/``. and after entering ``y`` it says: ``Installing package to /usr``. Then when I try to type ``oppm list`` I get ``The program is not currently installed.``
Contents of my Tier 3 Computer case:
* Graphics Card Tier 3
* Internet Card
* Data Card Tier 2
* CPU Tier 3
* 2 * RAM Tier 3
* HDD Tier 3
* HDD Tier 2
* EEPROM (Lua Bios)
My version of this mod is ``MC1.7.10-1.7.2.1166``
See screenshot below for more details.
![oppm error](https://user-images.githubusercontent.com/13962901/42728502-ee116dba-87bb-11e8-8338-ea4963ef148e.png)

**Comment by DaveKnifeman** [comment]
Error was supposedly caused by a floppy in a connected diskdrive component. I removed the floppy and reinstalled OpenOS and OPPM and it works fine now.

**Comment by skyem123** [comment]
This still seems like unexpected behaviour from OpenOS, so I'm gonna poke @payonel

**Comment by asiekierka** [comment]
In general, I think a way should be added to ask for the address of the filesystem inserted to a specific disk_drive.
