### ISSUE TITLE
ProjectRed Bundled Cables no longer connect to Cases/Redstone I/O blocks

### ISSUE THREAD

**Issue by DeeJayhX** [MightyPirates/OpenComputers#2899]
Bundled cables clearly not attaching to opencomputers blocks. All listed mods are the latest versions at the time of this writing... Forge, OC, and PR.

![](https://media.discordapp.net/attachments/125649403162656768/471248381860118529/unknown.png)

MineCraft 1.12.2
forge-1.12.2-14.23.4.2739-universal.jar
OpenComputers-MC1.12.2-1.7.2.67.jar
ProjectRed-1.12.2-4.9.1.92-Base.jar
ProjectRed-1.12.2-4.9.1.92-compat.jar
ProjectRed-1.12.2-4.9.1.92-fabrication.jar
ProjectRed-1.12.2-4.9.1.92-integration.jar

**Comment by DeeJayhX** [comment]
Going to try #71 to see if it's resolved
https://ci.cil.li/job/OpenComputers-MC1.12/

**Comment by DeeJayhX** [comment]
Nope... 
![image](https://user-images.githubusercontent.com/1514573/43162112-0669d3cc-8f58-11e8-9620-dd20946ee918.png)

**Comment by asiekierka** [comment]
Nobody added support for them back in 1.12 - simple as that.

https://github.com/MightyPirates/OpenComputers/pull/2852

**Comment by DeeJayhX** [comment]
Ok, so, are we planning to add support for them again? PR is one of the biggest mods there is in terms of redstone use, so it would seem a prime candidate for integration.

**Comment by asiekierka** [comment]
Linked you to the relevant pull request already, so, yes!

**Comment by DeeJayhX** [comment]
Ah, I apologize. I figured it was a "duplicate issue" not a pull request. Hopefully we'll see some progress on that since it's been 21 days. Thanks again!

**Comment by asiekierka** [comment]
OpenComputers is, in general, going through issues with insufficient maintainership. You'll have to be patient.
