### ISSUE TITLE
besh and wget do not like each other

### ISSUE THREAD

**Issue by Techokami** [MightyPirates/OpenComputers#290]
So I set up besh as my default shell on a computer with two Tier 3.5 RAM. I went to use wget to download a file, and instead I got this: 
/bin/besh.lua:519: /bin/besh.lua:384: bad argument #1 (string expected, got nil)

**Comment by rmellema** [comment]
Does this only happen with wget or also with other programs like edit? And does the link you are trying to download contain a $ sign? Because then you might have to escape it with a \ or by enclosing the entire url in single quotes.

**Comment by Techokami** [comment]
Other programs seem to work fine. And the link was https://raw.githubusercontent.com/OpenPrograms/Vexatos-Programs/master/op-manager/autorun.lua which doesn't need escaping. It also does this when given NO arguments, too.

**Comment by Techokami** [comment]
OKAY, after some debugging and replacing files with fresher ones, half the problem is solved (I can use wget again!)
But there still lies an issue: besh needs to be friendlier about files not existing, like sh does now.

**Comment by fnuecke** [comment]
Had a go at this in the latest versions, and it worked - this may well have been related to #467 but I'm not sure. Either way, confirmation would be nice.

**Comment by fnuecke** [comment]
Closing since it works for me in the latest builds.
