### ISSUE TITLE
It crashes on startup the game,why???

### ISSUE THREAD

**Issue by qgss** [MightyPirates/OpenComputers#2900]
I just install only one mod,that is OpenComputers.Unfortunately，it crashed after i startup.
I throw it into the mods folder,looks no problem ,like others.
1.7.10 works well
but i prefer to play on 1.12.2,it does not work,i even install the visual studio to deploy the environment for lua5.3 for win10,you know,if the problem is solved i will not present to here.......
if it need some mod like LIB,sorry  i donot realise,please  remind me ,thanks a lot..

**Comment by asiekierka** [comment]
I, what?

1. You haven't posted a crashlog.
2. OpenComputers' APIs differ vastly beyond simple printing statements from the Lua 5.3 APIs you'd get in Visual Studio. You're better off at least testing in-game, and for writing code perhaps something lighter like Notepad++?

**Comment by qgss** [comment]
Sorry i don't have crashlog..
Because it crash at the beginning,after i double click the icon..i cant even see the loading interface ,i cant launch the game.
What's wrong with my Minecraft??

**Comment by LizzyTrickster** [comment]
Without the crashlog, we don't know. (We lost our crystal balls).

What Minecraft Launcher are you using? Most launchers have a way you can enable the console to see what happened.

Alternatively, look in the `crash_reports` folder in the Minecraft directory.

**Comment by qgss** [comment]
only install the forge,1.22.2-14 23.4.2738

**Comment by qgss** [comment]
i will have a look,thanks for your help

**Comment by qgss** [comment]
i just need to put it into mods folder ,right?
what else should i do to ensure it can works?

**Comment by qgss** [comment]
it works?? well, it finally works ,i just reinstall the minecraft....

**Comment by LizzyTrickster** [comment]
If your issue is resolved, please close this issue :)
