### ISSUE TITLE
Can't use adapter block with draconic evolution

### ISSUE THREAD

**Issue by Grimmy347** [MightyPirates/OpenComputers#2901]
I placed an adapter block next to a draconic reactor stabilizer and right clicked it with the analyzer only to find that nothing would happen.  After a lot of looking around the internet I found that a slot was added that needs a controller.  The adapter itself is not enough.  I have tried a inventory controller and a tank controller but I can't seem to do anything with the reactor when I use the address of the controller rather than the address of the adapter.  I am trying to use the guild at https://tenyx.de/draconic_control/ to control the reactor but I am not sure this is possible anymore with the new controller setup.  Is this just broken for draconic evolution now?

**Comment by OfficialStamper** [comment]
@Grimmy347 I have just recently developed a new program for controlling the draconic reactor and I am not experiencing any issues with the adaptor block.  MC 1.12.2.
What versions of MC, Forge, Java etc. are you using?
I am not an OC Dev, but might be able to help.

**Comment by payonel** [comment]
perhaps discuss this on https://ci.cil.li/ for further programming help
if there is a bug, please feel free to open a new ticket and reference this ticket
