### ISSUE TITLE
computer.pullSignal should not sidestep coroutine hierarchy

### ISSUE THREAD

**Issue by Inari-Whitebear** [MightyPirates/OpenComputers#2903]
So I recall running into this once in the past already and now again...

In coroutines I'd expect the hierarchy to be respected. If I create a coroutine co1 and resume it, I expect it to yield back to me.
However in the current implementation computer.pullSignal (in machine.lua) uses the native coroutine.yield, while the normal non-machine.lua code only has access to the coroutine.yield that machine.lua provides to the environment.
Thus if a coroutine I resume calls computer.pullSignal it'll not yield to me .resume call, but to Scala/Java/whatever.

**Comment by payonel** [comment]
`computer.pullSignal` should not be viewed as a coroutine method. It should be viewed as a special "suspend the current system until the next signal"
This is by design, and if users expect pullSignal to act like `coroutine.yield` that would be confusing
