### ISSUE TITLE
Allow user scripts to catch hard interrupts

### ISSUE THREAD

**Issue by Fingercomp** [MightyPirates/OpenComputers#2904]
I understand that Control-Alt-C isn't supposed to be caught by user scripts. But there are cases when they need to do this. If a computer is running a public terminal (for accessing users' bank accounts, for instance), it's highly undesirable to allow users to terminate whatever programs they want, isn't it?

Is there a way to disable hard-interrupts for a specific program — or a part of it? For example,

```lua
local event = require("event")

event.noHardInterrupts(function()
  print("Inside this block, pressing Ctrl-Alt-C pushes an event we can catch and examine")

  local time, evt, isHardInterrupt

  repeat
    evt, time, isHardInterrupt = event.pull("interrupted")
  until isHardInterrupt

  print("The program was hard-interrupted at" .. time)
end)

print("But here, Ctrl-Alt-C terminates the program")
```

Using `pcall` to handle the hard interrupt is not a nice way to do it: after all, the error still unwinds the stack.

**Comment by payonel** [comment]
@Fingercomp you're not alone, others want this. I'll give it some more thought how I want to support this.

**Comment by payonel** [comment]
@Fingercomp consider https://github.com/payonel/OpenComputers/commit/6a693e99f9ad0d498e4af64cf1835f27dfa34b5e

user code would look like this

```
local process = require("process")

process.info().data.signal = function(...)
  print("caught hard interrupt")
end
```

I'm still thinking this over. I may provide an API to set this function handler
There are a few things I've been thinking about

1. It needs to be process specific, not system specific. Thus using process data
2. Threads, unfortunately, will never receive hard interrupts. So code run in a thread will not behave the same if you are expecting hard interrupts.
3. I don't yet have the right solution, but, I would like to provide more process specific interrupts/error/signals (signals in the linux sense). Eventually, I would like to provide a type of `kill` command that uses a process signal handler, or terminate it

**Comment by Fingercomp** [comment]
Oh, I like this solution. It nicely decouples signal handling from actual event processing, which removes the need to handle potential interrupts at every point in the program where an `event.pull` or another similar call is made.

I agree that the signal handler should be process-specific. Signals are a way of inter-process communication, so it doesn't make much sense to handle them globally, or per a single thread.

To make it more future-proof, the `process.info().data.signal` can be made a table that maps signals to handlers, e. g.

```lua
local process = require("process")

process.info().data.signal.terminate = function(...)
  print("caught hard interrupt")
end

process.info().data.signal.interrupt = function(...)
  print("caught soft interrupt")
end
```

The example shows it's also possible to integrate soft interrupt handling into this design, which may be convenient in multithreaded programs.

**Comment by payonel** [comment]
There deserves to be a process instance api, but not at this time for our next patch. I gave your suggestion about multiple signal.* methods but decided against it
1. soft interrupts, specifically, will remain event signals
2. in the future if i provide sigpip or sigint, it'll be through this same single handler. the parameter will tell the user what signal is being raised (in this case, "interrupted")
