### ISSUE TITLE
Minecraft Crash! Help

### ISSUE THREAD

**Issue by FraWar00** [MightyPirates/OpenComputers#2906]
This is the log output:

13:32:02 | launcher | main | info | Preparing to launch minecraft client for 1.13
-- | -- | -- | -- | --
13:32:06 | launcher | main | info | Checking installations.
13:32:06 | launcher | main | info | Minecraft client 1.13 is ready to start.
13:32:06 | launcher | main | info | Starting!
13:32:06 | launcher | main | info | Using default game log configuration client-1.12.xml (outputs XML)
13:32:09 | cfi | Client thread | info | Setting user: Fra0War0
13:32:14 | cfl | Client thread | warn | Skipping bad option: lastServer:
13:32:14 | cfi | Client thread | info | LWJGL Version: 3.1.6 build 14
13:32:16 | vg | Client thread | info | Reloading ResourceManager: Default
13:32:19 | dgh | Sound Library Loader | info | Starting up SoundSystem...
13:32:19 | dgh | Thread-2 | info | Initializing No Sound
13:32:19 | dgh | Thread-2 | info | (Silent Mode)
13:32:21 | dgh | Thread-2 | info | OpenAL initialized.
13:32:21 | dgh | Sound Library Loader | info | Preloading sound minecraft:sounds/ambient/underwater/underwater_ambience.ogg
13:32:21 | dgh | Sound Library Loader | info | Sound engine started
13:32:30 | ddb | Client thread | info | Created: 1024x512 textures-atlas
13:32:34 | com.mojang.text2speech.NarratorWindows | Client thread | info | Narrator library for x64 successfully loaded
13:34:38 | launcher | main | info | AL lib: (EE) ALCmmdevPlayback_mixerProc: Failed to get padding: 0x88890004

15:34:38 | monitor | Process Monitor | fatal | Process crashed with exit code -805306369
-- | -- | -- | -- | --

Someone can help me to fix this crash?

**Comment by asiekierka** [comment]
That's vanilla 1.13 without mods. Not related to OpenComputers. Ask Mojang.
