### ISSUE TITLE
holoeditor not working

### ISSUE THREAD

**Issue by xaleb** [MightyPirates/OpenComputers#2908]
![bug](https://user-images.githubusercontent.com/10950572/43481340-ba5f02dc-94d3-11e8-82d4-036d334684b1.png)
 what do?

**Comment by asiekierka** [comment]
holoeditor requires Lua 5.2. Shift-click the CPU in hand to change the architecture.

**Comment by skyem123** [comment]
Shouldn't OpenOS have a bit32 thing for Lua 5.3 though? Though that's more of a feature request, I suppose...

**Comment by payonel** [comment]
this is a bug with https://oc.cil.li/index.php?/topic/335-hologram-editor/
not with OC
bit32 should be required, in lua 5.2 and 5.3
`local bit32 = require("bit32")`
