### ISSUE TITLE
Screen not readable, unrecognizable symbols.

### ISSUE THREAD

**Issue by frenzy167** [MightyPirates/OpenComputers#2909]
I set up a tier 3 computer with a Lua eeprom, a gpu, an openOS floppy, 2x tier3 memory, a tier 3 hdd, and attached a 9x9 tier 3 screen with an attached keyboard, I started it up and the screen only shows weird symbols, I can type "install" and when it pauses I type y and hit enter and it installs the OS to the hdd, but I can't read it. I am running off of my own server on a Debian OS, my client is running on a Mac computer.

![2018-08-01_14 00 19](https://user-images.githubusercontent.com/42008045/43539631-6ceb0d8c-9593-11e8-99b7-f13e32bc2364.png)

**Comment by asiekierka** [comment]
>Mac

Praise Apple's OpenGL drivers!

What's your graphics card (and/or device model), your Java version and your OS version?

**Comment by frenzy167** [comment]
My graphics card is a NVIDIA GeForce GT 750M 1024 MB
Java version 8 update 171 (build 1.8.0_171-b11)
OS macOS High Sierra Version 10.13.6

**Comment by payonel** [comment]
This is been around for ages sadly :)
When you see this happen, just reload textures by pressing F3 on your keyboard
