### ISSUE TITLE
Allow access to "non-printable" char set

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#291]
The font has all the ASCII characters for CP437, yet OC limits us to the "printable" set, I.E 32-126

Being able to use the extra characters could allow for some neat programming in OC:
Many elements are great for making interfaces
Creating Games, the faces, hearts, diamond, club, etc, could all help that instead of being colored letters.

This allow would allow localization of programs to other languages:
Spanish
German

**Comment by Wuerfel21** [comment]
For me i can paste stuff in from the windows-thing which is (in german) called("zeichentabelle")

**Comment by Vexatos** [comment]
@Wuerfel21 "Zeichentabelle" == Character Map

**Comment by Wuerfel21** [comment]
Thanks @Vexatos

**Comment by fnuecke** [comment]
You can either paste them or 'create' them using `unicode.char`, using the [respective code points](http://en.wikipedia.org/wiki/Code_page_437#Standard_code_page) - for example, ▓ is `unicode.char(0x2593)`.
