### ISSUE TITLE
This is not a issue is just a suggestion

### ISSUE THREAD

**Issue by Zimux** [MightyPirates/OpenComputers#2910]
In the wiki tells you the mods that can interoperate with the mod, but now I discover that this mod is interoperable with railcraft, in the wiki didnt say nothing about that mod, I´m only suggesting to put the railcraft mod in the interoperation section

**Comment by skyem123** [comment]
I think this is part of #2686 (The Big Wiki Issue)

**Comment by payonel** [comment]
yep, the big wiki work. it'll happen :)
