### ISSUE TITLE
The player object (from the debug component)'s setGameType() doesnt function properly

### ISSUE THREAD

**Issue by RedstoneParkour** [MightyPirates/OpenComputers#2911]
So i was writing an MineOS application that let players manage other players. So, when i got into the code that sets the players gamemode i noticed that it always setted me to survival. So i tried the following (but in one line) in the lua prompt:
```lua
local comp = require("component")
local me = comp.debug.getPlayer("RedstoneParkour")
me.setGameType(me.getGameType())
```
This code should do nothing to my gamemode (i was in creative) BUT it set me to survival. So i looked into it and this is my guess what happens at the last line of code:

My gamemode gets set to the gamemode that im in. But the function cant properly recognize gamemodes. So it sets me to the default gamemode (survival).
Note: I am not English. So there may be words that you cant understand.

**Comment by asiekierka** [comment]
https://github.com/MightyPirates/OpenComputers/blob/5209f5723972a88b865fe92db3796ba7ec401ee2/src/main/scala/li/cil/oc/server/component/DebugCard.scala#L329-L339

One of these uses getName, the other uses name. Maybe their values differ?

**Comment by RedstoneParkour** [comment]
I also tried directly using "creative". But that didnt work. Maybe try adding the checks inside the function?

**Comment by RedstoneParkour** [comment]
Actually, why do you even check the name against the gametype?

**Comment by brisingraerowing** [comment]
From a quick look at the GameType enum, 'creative' is the name, and getName simply return the name field. The enum does have a parse method to get a GameType with a default, so maybe that can be used instead?
