### ISSUE TITLE
Cannot swap robot's equipped tool

### ISSUE THREAD

**Issue by BaconRemovalUnit** [MightyPirates/OpenComputers#2913]
Checking the [robot API](https://ocdoc.cil.li/api:robot) page, there seems to be no way for a robot to change its equipped tool with something from its inventory. Is this intentional or is there a function that can be used to equip the robot?

**Comment by Vexatos** [comment]
See `component.inventory_controller.equip()` [here](http://ocdoc.cil.li/component:inventory_controller).
