### ISSUE TITLE
Piston upgrade event don't posts any event

### ISSUE THREAD

**Issue by Sirse** [MightyPirates/OpenComputers#2914]
Piston upgrade don't posts any event and can be used for griefing on public multiplayer servers.

https://github.com/MightyPirates/OpenComputers/blob/06e7149573cc310254b691b3944eeb5d99619ff8/src/main/scala/li/cil/oc/server/component/UpgradePiston.scala#L50

**Comment by payonel** [comment]
what event should it post?

**Comment by Sirse** [comment]
Piston block moving - just block breaking at X,Z and block placing at new X,Z.
Maybe throw 2 events? BlockBreakEvent and BlockPlaceEvent

**Comment by payonel** [comment]
when i work on this, i can step through vanilla pistons to see what events fire
