### ISSUE TITLE
[1.7.10] [OC-1.7.2.1166] Bug: Robot's name constantly cycles in WAILA- Can't access robot GUI. 

### ISSUE THREAD

**Issue by cheesealmighty** [MightyPirates/OpenComputers#2915]
Previously placed, working robot. It continues carrying out its function.

But WAILA is doing this: https://puu.sh/B9PrZ/a67d7f1ba0.mp4
Cannot access the GUI, exactly. 
A GUI of sort flashes sometimes, captured here, from the video: https://puu.sh/B9Puu/d09c19b3ee.png

Other robots were accessible at this time. And seemed normal.

It stabilized after a while, and returned to normal.
https://puu.sh/B9PFb/5d33321f93.png
https://puu.sh/B9PFn/728277bd20.png

Nothing out of order in server logs. These chunks were chunk loaded using FTBUtil.

Modpack: https://minecraft.curseforge.com/projects/bad-times-and-big-machines

Couldn't find any bug report related. Sorry if this is duplicate.

**Comment by payonel** [comment]
this has happened in the past, but i had to close for no-repro. I'll leave this open for a time, if you are able to create a small and consistent repro, that'd be helpful

**Comment by cheesealmighty** [comment]
I never encountered this error again, (un)fortunately. This accounts for the last 26 days.

**Comment by payonel** [comment]
i said no-dupe, sorry, no idea why i wrote that, i meant no-repro
ok i'll close this, but if you are able to produce a repro, even if that requires sharing a world dir, that would be helpful. thanks

**Comment by cheesealmighty** [comment]
No probs. Will do. Much appreciated.
