### ISSUE TITLE
Suggesting better naming of native libraries

### ISSUE THREAD

**Issue by Low-power** [MightyPirates/OpenComputers#2917]
During port of this mod to Solaris (#2916), I found the current naming cannot truly reflect the corresponding operating system and processor architecture. For example the name `native.32.so` meaning a '32-bit shared object' is too generic, for the actual platform 'GNU/Linux i386'; `native.32.bsd.so` is actually for FreeBSD, shouldn't be named just `BSD`.

I suggest rename them with:
* native.32.arm.so -> native.gnu-linux-arm.so
* native.32.bsd.so -> native.freebsd-i386.so
* native.32.dll -> native.windows-i386.dll
* native.32.dylib -> native.osx-i386.dylib
* native.32.so -> native.gnu-linux-i386.so
* native.64.bsd.so -> native.freebsd-amd64.so
* native.64.dll -> native.windows-amd64.dll
* native.64.dylib -> native.osx-amd64.dylib
* native.64.so -> native.gnu-linux-amd64.so

**Comment by asiekierka** [comment]
https://github.com/MightyPirates/OpenComputers/pull/2898
