### ISSUE TITLE
Loot disk change proposals

### ISSUE THREAD

**Issue by asiekierka** [MightyPirates/OpenComputers#2918]
Post your loot disk-related proposals here.

I'd recommend removing plan9k - the version in OC has always been outdated and I don't think it even works well anymore.

I also think distribution of programs which require an Internet Card (such as "irc") is mildly redundant given OPPM, but I don't have a concrete thought on that yet.

**Comment by XeonSquared** [comment]
If we're getting rid of plan9k, it might also be worth looking into getting rid of the 'network' disk, I don't think I've heard of anyone using it successfully, and it hasn't been updated in a *long* time.
