### ISSUE TITLE
Crashes with adapter

### ISSUE THREAD

**Issue by bjr29** [MightyPirates/OpenComputers#2919]
I've been having some trouble with the adapter such as:
- Removes an item when I click on it in creative mode
- Crashes when 2 of the blocks are put together
- This also happens after removing 1 of the blocks and putting a new one next to the position where the old one was.
- After the crash, the world can't be opened again

File Name: OpenComputers-MC1.12.2-1.7.2.67

P.S Could you show me an API or create one for how to use IC2 with OpenComputers?

**Comment by payonel** [comment]
can you provide specific repro for this? I'm a bit confused

>     * Removes an item when I click on it in creative mode

What item are you clicking on? In what inventory? What does this have to do with an adapter? Does the adapter need to be touching a chest?



>     * Crashes when 2 of the blocks are put together

Which 2 blocks? What does this have to do with the adapter? Does the adapter need to be touch both blocks?



>     * This also happens after removing 1 of the blocks and putting a new one next to the position where the old one was.

If the game crashed when you placed 2 blocks, how are you then able to remove one of them...the game has crashed? Are you able to reload the world and the 2 blocks are there but not crashing?



>     * After the crash, the world can't be opened again

But then this point invalidates the previous. I'm confused. Also, this is likely a incompatiblity issue with another mod, please list what mod this breaks with. And please try to reduce your modpack (if you are using one) to JUST oc and that one mod, and give that mod's version number.

**Comment by bjr29** [comment]
> 
> 
> can you provide specific repro for this? I'm a bit confused
> 
> > ```
> > * Removes an item when I click on it in creative mode
> > ```
> 
> What item are you clicking on? In what inventory? What does this have to do with an adapter? Does the adapter need to be touching a chest?
> 
> > ```
> > * Crashes when 2 of the blocks are put together
> > ```
> 
> Which 2 blocks? What does this have to do with the adapter? Does the adapter need to be touch both blocks?
> 
> > ```
> > * This also happens after removing 1 of the blocks and putting a new one next to the position where the old one was.
> > ```
> 
> If the game crashed when you placed 2 blocks, how are you then able to remove one of them...the game has crashed? Are you able to reload the world and the 2 blocks are there but not crashing?
> 
> > ```
> > * After the crash, the world can't be opened again
> > ```
> 
> But then this point invalidates the previous. I'm confused. Also, this is likely a incompatiblity issue with another mod, please list what mod this breaks with. And please try to reduce your modpack (if you are using one) to JUST oc and that one mod, and give that mod's version number.

**Comment by bjr29** [comment]
Sorry, pressed the wrong button.

**Comment by bjr29** [comment]
If I click on the adapter with the item/block selected, it would remove it from my own inventory.

It crashes when 2 adapter blocks are placed next to each other.

Once again, I meant the adapter blocks. I placed one and removed it, then placed a new one next to where it was before.

Does this make sense now? I'll try just running OC on its own. It'll have to be the next day, I've gtg.
I sent you the file name for you to know the version. Minecraft - 1.12.2 & OC - 1.7.2.

**Comment by payonel** [comment]
Can you grab the crash report please, and add it to this bug report?
I do appreciate it. Note that this does not repro for me

**Comment by payonel** [comment]
also, "click on the adapter with the item/block select"
I dont know what that means
You have another item, like cobblestone, in your hand when you right click the adapter, and the cobblestone and it is removed from your inventory? Where does it go? inside the adapter? Are you crouching? Is the item destroyed/disappears?

**Comment by payonel** [comment]
no repro
if the original poster can repro with our latest release, and can answer some more questions for a repro (like, crash reports, mods required, etc) we can reopen
