### ISSUE TITLE
World sensor card in Galacticraft 4

### ISSUE THREAD

**Issue by PhysicalNova** [MightyPirates/OpenComputers#2924]
I've heard that there is a world sensor card in the mod, which is added by Galacticraft (if both mods are installed). But with the newest version of Galacticraft (The 4.0, which adds Venus), this card/upgrade is nowhere to be found. Is that a bug ?

**Comment by payonel** [comment]
might be dupe of #2447

**Comment by payonel** [comment]
galacticraft support was removed as we reduced our cross mod support when upgrading to 1.11
also, the support broke in 1.10, as I have confirmed :|
It would be nice to have more mod support for OC going forward, but for our 1.7.3 release, I am focusing on fixes, rather than expanding support
