### ISSUE TITLE
Request: AE2 Integration - Get list of Cells from ME Controller

### ISSUE THREAD

**Issue by AntiBlueQuirk** [MightyPirates/OpenComputers#2929]
It would be convenient for ME monitoring to be able to get a list of all the Cells connected to an ME Network. I believe this can be accomplished by adding something like the following to `src/main/scala/li/cil/oc/integration/appeng/NetworkControl.scala`:

```
  import appeng.api.implementations.tiles.IChestOrDrive;
  import appeng.api.storage.ICellInventory;
  
  @Callback(doc = "function():table -- Get a list of all cells in the network.")
  def getCellsInNetwork(context: Context, args: Arguments): Array[AnyRef] = {
    val chests = tile.getProxy.getGrid.getMachines(classOf[IChestOrDrive])
    val cells = chests.map(_.getCellArray).flatten.collect{ case cell: ICellInventory => cell }
    result(cells.toArray)
  }
```

(I didn't create a pull request because this is *very* untested.)

**Comment by thiakil** [comment]
`getMachines` requires the exact class, not an interface, but otherwise looks doable.
