### ISSUE TITLE
[Suggestion] "Connection" Cables

### ISSUE THREAD

**Issue by Shazuli** [MightyPirates/OpenComputers#2930]
***Hi!***

Right now cables connect to any component they are besides, which can give a few problems when working in a small space. Sure you can install [MultiPart](https://minecraft.curseforge.com/projects/mcmultipart) or use `Net Splitters` but they are pretty bulky in both size and can break if they receive a redstone signal (and are quite expensive if you use a lot of them) and MultiPart is not always a definite it's going to be installed on a server.

My idea is to either add a new cable that will only connect to others of its kind or ordinary cables (with its color variants) similar to [Buildcraft](https://minecraft.curseforge.com/projects/buildcraft)'s [Sandstone Pipe](http://minecraftbuildcraft.wikia.com/wiki/Sandstone_Pipe) or can click on the connection between a cable and a component to toggle the connection.

**Comment by asiekierka** [comment]
>and MultiPart is not always a definite it's going to be installed on a server.

Why not ask the modpack developer?

In general, I'm not a huge fan, as even placing two components next to each other causes a connection...

**Comment by payonel** [comment]
we're going to leave our cables as simple (basic). multipart covers and enderio conduits provide the fine-tuned cable management we recommend
