### ISSUE TITLE
event.timer always returns the same event ID

### ISSUE THREAD

**Issue by OfficialStamper** [MightyPirates/OpenComputers#2931]
the following code always returns the same 'timerId/Event ID'

```
local event = require("event")
local waitTime = 0.5
local timerId = 0
local count = 0

os.sleep(1) -- flush the queue from any left over key presses etc.

local function timerHandler()
	count = count + 1
	print("Count:"..count.." TimerId:"..timerId.." TimerCancel:"..tostring(event.cancel(timerId)))
	event.push('timer', timerId)
end

for i = 1, 10 do
	timerId = event.timer(waitTime, timerHandler)
	print("Loop:"..i..' Timer set, id:'..tostring(timerId))
	local event, id, op1 = event.pull()
	print("TimerId: "..timerId.." - Event: "..event.." - "..id.." - "..tostring(op1))
end
print("END")
```

![image](https://user-images.githubusercontent.com/21112096/44529891-1849a000-a6e5-11e8-9129-39a6d8685c81.png)

Expect event.timer to return a unique Event ID each time it is called.

Minecraft Version: 1.12.2
forge-1.12.2-14.23.4.2715
OpenComputers-MC1.12.2-1.7.2.67.jar

**Comment by payonel** [comment]
yes, the default timer fires once, its third optional parameter lets you specify how many times it should fire
once a timer has expired, its ID may be used again
```
times - how many times the function will be called. If omitted the function will be called once. Pass math.huge for infinite repeat.
```
more here https://ocdoc.cil.li/api:event
