### ISSUE TITLE
Calling term.setCursor with nil causes (in-game) bluescreen later

### ISSUE THREAD

**Issue by AntiBlueQuirk** [MightyPirates/OpenComputers#2932]
Calling term.setCursor with nil succeeds without error, but corrupts the tty state, causing it to crash later when term.write is called with the error:

    /lib/tty.lua:461: attempt to compare nil with number

I guess because this error occurs in a system library, it causes the computer to bluescreen. (Unrecoverable Error)

(Note: I wasn't intentionally calling setCursor with nil, I had a misspelled variable.)

- MC: 1.12.2
- Forge: 14.23.4.2745
- OC: 1.7.2.67

**Comment by payonel** [comment]
haha, i made the same mistake once, and i fixed it :) added a check arg, but - this code was only recently merged up. if you get our latest builds it'll be fixed. thanks for reporting
