### ISSUE TITLE
drone.suck() from above robot duplicates items

### ISSUE THREAD

**Issue by nzhook** [MightyPirates/OpenComputers#2935]
OC Version: 1.10.2-1.7.2.170 (latest on Twitch)
MC Version: 1.10.2

When a Drone interacts with a Robot (which does not expose its inventory - separate bug) using drone.suck(sides.bottom, 1) above the robot if nothing is in the robot's slot (tool slot) an item from the robot's assembled state is returned. eg. Monitor, keyboard... this item remains inside the robot so it creates multiple of those items for every suck operation the drone does.

I suspect it's the last item added in the Assembler as it is always the same item returned after the robot is assembled. 

If the robot is holding something then it will return the held item correctly, it's only when the robot is not holding anything that the duplication occurs.

**Comment by payonel** [comment]
does not repro in 1.7.10
confirmed repro from 1.10 - > 1.12

**Comment by payonel** [comment]
robots too, not just drone
inventory_controller.suckFromSlot also repros this, for slots >= the inventory size (e.g. slot 69 on creatix)
