### ISSUE TITLE
::Suggestion:: Tablet Screen Upgrade

### ISSUE THREAD

**Issue by eawilhelm** [MightyPirates/OpenComputers#2937]
Not familiar with GitHub so sorry in advance if this was already suggested. 

I was running a OS GUI on my OpenComputer, and figured it would be cool to have it on my Table Too.. unfortunately, the OS requires a T-3 Screen, now I figured the Creative Tablet would suffice, but read it's only fitted with T-2 Screen, is it possible to implement this?

**Comment by payonel** [comment]
similar to our robots, tablets are limited. you need a computer to do bigger stuff like fancy graphics
i could put a t3 on a creative tablet, but then it wouldn't behave like a normal tablet in this regard. i dont think we should
