### ISSUE TITLE
Oredict support

### ISSUE THREAD

**Issue by Pival81** [MightyPirates/OpenComputers#2939]
I'm writing a program that outputs to a file the contents of a chest, or a refined storage system, and it works well, but I can't figure out how to distinguish two items with the same id.
For example, stone and diorite have the same id, `minecraft:stone`, and I need to distinguish the two, because i have to feed the contents of the storage system to another external program
Maybe using oredict? I searched this repo's issues, and found #1303, but that ended up adding a feature which doesn't solve my problem.
I think a solution could be to add an option in the configs, in the same fashion of the `allowItemStackNBTTags` option, but to add the oredict(s) of the itemstack in the table generated, for example, by `component.inventory_controller.getStackInSlot()`, or `component.refinedstorage_grid.getItems()`

**Comment by asiekierka** [comment]
I think revealing oredicts is not harmful at all.
