### ISSUE TITLE
Colors lib in tier 3 graphic cards. Bug ?

### ISSUE THREAD

**Issue by PhysicalNova** [MightyPirates/OpenComputers#2941]
Recently, I toyed arround with the colors library. But using a tier 3 graphic card in creative (for making a texture making program), I noticed that, for exemple, "colors.blue" wasn't blue. On tier 2 graphic cards however, it works fine. Is there a way to counter that ? Or is it a bug ? (Btw, this mod is just awesome !)
Thanks in advance for any feedback !

**Comment by payonel** [comment]
i assume your using `gpu.setForeground(colors.blue, true)`, thus using the palette mode
with your t2 gpu and screen, the bit depth is 4, while on 3 it is 8
Why does bit depth matter? we prepared different default color palettes for the 2 different bit depths

you can set your own color pallete, see https://ocdoc.cil.li/component:gpu

**Comment by PhysicalNova** [comment]
Thanks !
