### ISSUE TITLE
On play.direwolf20.ca (DW20 2.3.0), opencomputers:robotafterimage remains and collides with the player.

### ISSUE THREAD

**Issue by FeepingCreature** [MightyPirates/OpenComputers#2948]
Invisible blocks with a black outline remain in the wake of the robot. It's pretty annoying.

**Comment by FeepingCreature** [comment]
May have randomly fixed itself.

**Comment by payonel** [comment]
bug reports need:
1. version of OpenComputers
2. version of minecraft
3. does it repro in single player games?
4. does it repro without other mods?
5. if not (4), what other mod needs to be installed along side it to cause the problem?
6. what are the repro steps? are there steps similar to the repro where the bug does NOT occur?
7. etc

Anyways, sounds like it went away, we've never heard this report before and we don't have a repro

I also installed the 2.3.0 client of direwolf20 and tested this. I do not see it, sorry
for reference, that d20 pack is includes OpenComputers-MC1.12.2-1.7.2.67.jar

**Comment by FeepingCreature** [comment]
Right, it's apparently definitely something specific to that server.

There were some other issues too involving oc move functions returning before they were finished.
