### ISSUE TITLE
Screen render flickering

### ISSUE THREAD

**Issue by kilanth** [MightyPirates/OpenComputers#2949]
Minecraft 1.12.2
Forge 2732
OpenComputers OpenComputers-MC1.12.2-1.7.2.67
Hey,
The problem might have occurred multiple times, I don't know, I couldn't find anything that matches my issue. I have **[this](https://www.pastiebin.com/5ba3c56cedede)** little prog, which hooks to the induction matrix with adapter and renders on-screen all the values that it can get: input/output/total battery.
Link to flickering part (speed set to 25% of the original)
![webp net-gifmaker](https://user-images.githubusercontent.com/15314260/46079233-37819480-c19f-11e8-9922-0e1e09b2a372.gif)

You can see the flickering of a big bar representing total storage.
It could be just the piece of code which does that, if so, please tell me where did I go wrong, you are literally the only one, who can help. 
Set up is simple - everything is max tier (not creative), as well as case and screens. Adapter hooked to induction matrix, energy from that same induction matrix port.
Thank you, good sirs!

Some notes. Problem first occured back in 1.10 FTB Infinity Lite, only recently was transfered onto 1.12, so not equals (~=) initially broke on 1.12, fix lines 75, 123, 126 the not equals in attached code and the prog should launch, ah, and the random "lol" at the very beginning, no idea why it is in there.

**Comment by payonel** [comment]
the game may choose to update and render the actual in-game screen at any point between line 132
```lua
gpu.fill(1, 1, w, h, ' ')
```
and by the time you finish drawing your final bar on line 137
Perhaps you were hoping the game would update the screen only when you yield, on line 157
```lua
os.sleep(refresh_rate)
```
That is not the case.
To remove any flickering, you will need to only draw to the screen the sections that change.

**Comment by kilanth** [comment]
Hey-o, thanks for the reply, but I'm not exactly clear as to what you mean by draw only things that change, I don't know what is going to change, so how can it be changed? Can you give some example?
I've also noticed, that it runs smoothly and perfectly fine until the top left and top right graphs fill out, only then it starts flickering.
![image](https://user-images.githubusercontent.com/15314260/46108867-c2867d00-c1e7-11e8-9160-805004b45247.png)
So before the space fills up, it's all smooth and nice.
Thank you very much again!

**Comment by payonel** [comment]
I see two options
1. store all data you previously drew and compare to new data you would like to draw, and only send the changes
or
2. buffer all the writes you would like to make, then upload them line by line (and color section by color section)

**Comment by kilanth** [comment]
1. You are on about double buffering? Creating a copy of the changed contents and comparing it every time until the change has been registered, then it will attempt to draw it on screen. Do you think that will be easier to include that library by default because I don't want to spend like 5 hours figuring out how it all can be put together for 2-3 progs?

**Comment by kovaxis** [comment]
I know this is already closed, but the solution is not necessarily double buffering and this is the first result for googling "opencomputers flickering".

The flickering probably happens because you are querying the induction matrix in between your draw calls, which makes a small pause. Try to get all the needed info before you start rendering and then draw in one go. This at least solved it for me.

**Comment by kilanth** [comment]
Been a while,
I solved it by using double buffering by Igor Timofeev. This tryharding gentleman created beyond-real library for OC.
GitHub.com/IgorTimofeev/DoubleBuffering
But thanks for the help.

-----
Your knowledge - our heritage
