### ISSUE TITLE
AE2 rv6-alpha-4 breaks OpenComputers integration in export bus

### ISSUE THREAD

**Issue by arketec** [MightyPirates/OpenComputers#2950]
I'm playing on a Foolcraft 3 server that was just updated and AE was updated to rv6-alpha-4.

Now, when trying to use the OC integration:
component.me_exportbus.exportIntoSlot(side,slot)

it fails to export and I get this message:

appeng.api.storage.channels.IItemStorageChannel.poweredExtraction(Lappeng/api/networking/energy/IEnergySource;Lappeng/api/storage/IMEInventory;Lappeng/api/storage/data/IAEStack;Lappeng/api/networking/security/IActionSource;)Lappeng/api/storage/data/IAEStack;

Environment
Modpack: Foolcraft 3 v1.5.4
SMP server

Minecraft Version: 1.12.2
AE2 Version: rv6-alpha-4
OC Version: 1.12.2-1.7.2.67
Forge Version: 14.23.4.2760

I know AE is in an alpha build, but it seems like whatever they changed in IItemStorageChannel is breaking the integration and this change will likely also be in the beta version

**Comment by payonel** [comment]
please retest with our latest 1.12 build: https://ci.cil.li/job/OpenComputers-MC1.12/ and just ae2

**Comment by arketec** [comment]
I have confirmed the issue still exists with the latest OC jar:

 OpenComputers-MC1.12.2-1.7.2.106.jar

**Comment by arketec** [comment]
also narrowed the change to the AE rv6 update breaking the comparability as rv5 is the last working version.

this is the commit that seems to have changed poweredExtraction():

https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/d2250b115f230dba7702a242cb7ad55ab124193b#diff-29b3afdc275eadc2628b3ad05970c74a

**Comment by payonel** [comment]
breaking between rv versions? ugh....ok thanks
