### ISSUE TITLE
computer.beep() causes thread to die.

### ISSUE THREAD

**Issue by ahallrq** [MightyPirates/OpenComputers#2953]
When using computer.beep inside a thread I've noticed that the thread immediately stops running.

For example when running the below code:

```
local thread = require("thread")

t = thread.create(function()
    print("Should display before the beep loop.")
    for i=1,3 do
        print("beep")
        computer.beep(500, 0.05)
    end
    print("Should display after the beep loop.")
end)

thread.waitForAll({t})
```

The output is:

> Should display before the beep loop.
> beep

rather than:

> Should display before the beep loop.
> beep
> beep
> beep
> Should display after the beep loop.

No error is displayed and even the first beep isn't played.

**Comment by payonel** [comment]
`computer` isn't available unless you `require` it
the thread is throwing an exception because `computer` in that context is `nil`
hopefully there is a thread crash message in your `/tmp/event.log`

**Comment by ahallrq** [comment]
>`computer` isn't available unless you `require` it

Well, damn. I don't know how I missed that. Nonetheless thanks for pointing out where the thread crash logs are held.
