### ISSUE TITLE
Adapter Crashes when  applied-llamagistics is installed

### ISSUE THREAD

**Issue by Grimmy347** [MightyPirates/OpenComputers#2954]
Why when I hold shift and right click on an adapter, does it not give me a network address?  What am I doing wrong?  Thank you!

**Comment by Grimmy347** [comment]
I am right clicking on the adapter with the analyzer in my hand btw.

**Comment by Grimmy347** [comment]
I am using OC 1.7.2.67 and DE 1.12.2-2.3.13.306

**Comment by payonel** [comment]
the address is copied to your clipboard (like a control+c)
you can then paste it in chat, or press [insert] in the computer to paste it

**Comment by Grimmy347** [comment]
no, it does nothing when I do this for an adapter block, it will do it for anything else with an address but not adapter blocks

**Comment by Grimmy347** [comment]
it does not show it with the list of devices. if I put a controller in the adapter then it will show the address of the controller but not the adapter. I remember seeing something in one of the update messages about it not having an address of its own anymore but I don't know how to use it with DE if it doesn't have its own address.

**Comment by payonel** [comment]
ah - you mean specifically the adapter. I see, sorry i read over that detail
The adapter itself is not a component. It provider a component for cross-mod behavior. if there are any DE blocks the adapter understands, those DE blocks will load as components on your computer with the adapter next to it.

**Comment by Grimmy347** [comment]
so far when I type components it does not show any de components though  =/

**Comment by payonel** [comment]
there was a time the draconic pylons could register with the adapter making a `draconic_rf_storage` available. That was a feature provided by DE

**Comment by Grimmy347** [comment]
is that no longer the case?  I am having an issue with the pylons crashing my server  =/

**Comment by Grimmy347** [comment]
not only that but any block placed next to an adapter, if I break the block it disappears rather then dropping so I can pick it up

**Comment by payonel** [comment]
we didn't make the oc integration with the pylon, DE did. you'll have to bring it up with them

**Comment by Grimmy347** [comment]
it actually crashes the server with just about anything I put next to the adapter.  not just DE  =/

**Comment by payonel** [comment]
This has evolved into an unnatural way to use the github issue tracker. Typically, you should create a ticket with all of the relevant info at the top, some suggestions:
1. oc version
2. steps to reproduce
3. description things that dont work or crash
4. logs
These things should have been your first comment. We are 12 comments in and you are just now mentioning that the adapter causes a crash? And that it happens with other blocks? Please open a new ticket, with this information, showing a repro with not just DE - but specifics of the "just about anything" you place next to the adapter that causes a crash.

**Comment by payonel** [comment]
I read your comment in #oc and we have discovered the incompatibility is with Applied Llamagistics
this mod has caused us grief before, and apparently it has reared its cruel head again
It uses the same mod-id MOST of the same class names as Applied Energistics. But because of the confusion in the code, this breaks OC code trying to talk to AL thinking it is AE
And this causes our adapter block to fail
Please remove AL
Also, I'll review this issue again tonight, and add some safeguards to OC to not crash due to AL
