### ISSUE TITLE
AE2 Power Source not connecting

### ISSUE THREAD

**Issue by BamButz** [MightyPirates/OpenComputers#2955]
Hello,

im trying to power my OpenComputer with an ae2 vibration chamber.
But the glass cables of AE2 are not connecting with oc.
I've tried also to put the power converter between the case and cable.

### Versions

MC: 1.12.2
Forge: 14.23.4.2765
OC: 1.7.2.67
AE2: rv6-stable-1

### Setup

The block under my feet is a power converter.

![2018-10-05_01 34 51](https://user-images.githubusercontent.com/7022144/46508715-1a079700-c83f-11e8-93f3-664d56b81f05.png)

Thanks in advance

**Comment by payonel** [comment]
thank you for reporting. When we brought back ae2, the power work was not done
you should be able to use a power converter or even a computer case to directly get power from the ae2  power grid
also, you will visually see the glass fluix cables connecting
you'll need our latest dev builds: https://ci.cil.li/job/OpenComputers-MC1.12/
these fixes will be official in our 1.7.3 patch release
