### ISSUE TITLE
Screen block in left hand looks weird

### ISSUE THREAD

**Issue by thetakodev** [MightyPirates/OpenComputers#2957]
![image](https://img.kukiteam.xyz/TaNIMRMCft.png)

Version: 1.12.2-1.7.2.67

**Comment by payonel** [comment]
I need to review https://github.com/MightyPirates/OpenComputers/blob/master-MC1.10/src/main/resources/assets/opencomputers/models/item/screen1.json

and review for other items as well

**Comment by payonel** [comment]
lacking repro
