### ISSUE TITLE
setBundledOutput not working with EnderIO Redstone Conduit

### ISSUE THREAD

**Issue by kman3107** [MightyPirates/OpenComputers#2958]
Forge: 14.23.4.2760
Mods:
EnderIO-1.12.2-5.0.36 (Current Relase)
EnderCore-1.12.2-0.5.41 (Current Release)
OpenComputersMC1.12.2-1.7.2.113 (Current Dev Build, also checked with current release 1.7.2.67)

I've been trying to use setBundledOutput  with EnderIO conduits with no success.
I am using the same OC setup, and the exact same script as I used in MC1.10.
Which back then worked just fine.
![2018-10-10_21 08 53](https://user-images.githubusercontent.com/10728652/46760046-3426f680-ccd1-11e8-9840-0c0ea39034d8.png)
![2018-10-10_21 09 04](https://user-images.githubusercontent.com/10728652/46760048-3426f680-ccd1-11e8-87b3-8a6538164c8d.png)
![2018-10-10_21 09 17](https://user-images.githubusercontent.com/10728652/46760049-3426f680-ccd1-11e8-87c5-024499193eb1.png)

This is it working just fine in MC 1.10
Forge: 12.18.3.2316
Mods:
EnderIO-.1.10.2-3.1.183
EnderCore-1.10.2-0.4.1.66
OpenComputersMC1.10.2-1.6.2.7

![2018-10-10_21 31 20](https://user-images.githubusercontent.com/10728652/46761301-66862300-ccd4-11e8-904a-15933bea9368.png)

**Comment by payonel** [comment]
thank you very much for testing with our dev builds!!! seriously, thank you

**Comment by payonel** [comment]
this comes down to enderio integration
you'll notice that when you open the enderio redstone conduit on the face against the OC machine, the 1.12 GUI shows you a color selector but in 1.10 there is no color selector

The EnderIO code is checking to see if our block implements their `crazypants.enderio.conduit.redstone.IRedstoneConduit` interface. And if it does, that means we can speak their bundled redstone language.

I'll review what it takes to bring this back in for 1.12, but it might fall out of the 1.7.3 milestone if it isn't trivial

**Comment by kman3107** [comment]
I thought the new EnderIO Conduit setup might have something to do with it.
Thanks for looking into to it. I hope it's fairly easy to work around, if not then it's not ment to be :)

**Comment by kman3107** [comment]
I just checked Thermal Dynamics Redstone Relay and it has the same problem as EnderIO Redstone Conduits.

**Comment by payonel** [comment]
btw, enderio 1.12 doesn't yet have a redstone api that we can hook into

**Comment by selli69** [comment]
Any news on this?
