### ISSUE TITLE
java.lang.IncompatibleClassChangeError mods.immibis.core.api.multipart.IMultipartSystem

### ISSUE THREAD

**Issue by samuelh2005** [MightyPirates/OpenComputers#2959]
The game crashed whilst rendering item
Error: java.lang.IncompatibleClassChangeError: Found class mods.immibis.core.api.multipart.IMultipartSystem, but interface was expected

In 1.7.10 the latest one 0.6.1 version

**Comment by payonel** [comment]
this is our latest version of curseforge: https://minecraft.curseforge.com/projects/opencomputers/files/2540142
and this is our latest dev version: https://ci.cil.li/job/OpenComputers-MC1.7.10/
please try both

also, what version of immibis multipart are you using?

also, please provide sufficient and minimal repro steps

**Comment by payonel** [comment]
also, we need a crash report
