### ISSUE TITLE
OpenComputers causing server lag.

### ISSUE THREAD

**Issue by GameBurrow** [MightyPirates/OpenComputers#2960]
For a while now OpenComputers has been causing considerable lag on our server (see the bottom section on the right side)
![javaw_2018-10-14_12-54-45](https://user-images.githubusercontent.com/4341091/46915166-85c0d100-cfb0-11e8-9aa9-e591f6937672.jpg)

It's happening in the following modpack:
https://minecraft.curseforge.com/projects/the-society-transportcraft
**Forge version** 14.23.4.2766 (happened also with earlier version)
**OC version:** 1.12.2-1.7.2.67

**Comment by SaphireLattice** [comment]
Why was this closed?

**Comment by GameBurrow** [comment]
@saphire-lattice It may have not been OC, or it may have been the fact that one of the OC computers was trying to interact with reactors mod, which was removed from the pack, either way the lag is gone after I broke some cables going to emptiness.
