### ISSUE TITLE
There were errors running the class transformer

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#2963]
Opened my world, got this error:

> OpenComputers: There were errors running the class transformer. Please report this, together with your (full!) FML latest.log/fml-server-latest.log logfile, thank you!

So here is my full log up to the moment where I saw this error.

I hope it helps...

[latest.log](https://github.com/MightyPirates/OpenComputers/files/2496231/latest.log)

**Comment by payonel** [comment]
it appears to be a conflict with malisiscore, which is using spongepowered mixin, which we do not support. If malisiscore wants to update their spongepowered mixin to a version that doesn't cause conflicts, that's up to them.

I wouldn't worry too much about this failure, I suspect drones won't be able to use leashes correctly, or the leash may not rendered centered on the drone
