### ISSUE TITLE
Angel Upgrade doesn't work

### ISSUE THREAD

**Issue by sezze** [MightyPirates/OpenComputers#2965]
- Using OpenComputers 1.7.2.67 (MC 1.12.2)
- Only ThermalExpansion + requirements + Optifine is installed

robot.place() (as well as robot.placeDown() and robot.placeUp()) do not work in mid air even when an angel upgrade is installed. False is returned as if the angel upgrade wasn't installed. Tried placing multiple different blocks in multiple different robots, all with angel upgrades, no luck. The commands work if there is a block adjacent, like normal.

**Comment by payonel** [comment]
fixed in dev builds
