### ISSUE TITLE
Thut's Elevators black monitor issue and floor number issue

### ISSUE THREAD

**Issue by TwilightWolfi** [MightyPirates/OpenComputers#2966]
Having negative floor numbers sets the floor -1 to "65" and -2 to "66" respectively and, I assume, increasing for lower floors. Not too much of an issue.

When I call the elevator to the floor that the computer is on (component.lift.callFloor(65)), connected to the controller block and able to access the component, the monitor screen goes black and requires replacing to work again. This is repeatable, and happens wherever the controller block is placed (on the correct y value for a working lift, at least).

**Comment by payonel** [comment]
wow, forgive me, but I really don't understand what this bug is talking about
can you give screenshots, a simple repro, ... walk me through this

+edit

So when you call `component.lift.callFloor(65)` the screen goes black.
Is a connection to the screen lost?
are cables being cut or moved?
is this a bug with thut's elevator mod and their integration with oc?
How is -1 set to "65"? Is that normal? is that supported?

Seriously, I have no clue

**Comment by TwilightWolfi** [comment]
I apologise, I'm not good at explaining this bug.

When I want to call the elevator to a negative floor, the `component.lift.callFloor()` function doesn't accept negative numbers. When trying to retrieve the floor number for a negative floor controller block , floors -1 and -2 return as 65 and 66 respectively. This is not a huge issue (to get a negative floor number able to be interpreted by the Lua component `callFloor()` function, simply run `math.abs(floorNumber) + 64`), but is not as convenient as expected.

With the elevator Tier 3 screen bug:

If I call the elevator to the floor that the computer is on, the elevator moves to the floor, and when it stops moving, the display cuts to black. There are no connection issues between the PC and the monitor, and the screen still makes the expected sound effects when it is working. There are no cables, as the elevator controller block, which is the required component to execute the elevator functions, is connected as part of the multiblock system. This is a bug with the integration of OC and Thut's Elevators. I'll try and capture a video of the issue and link it in this or another comment.

I'll send pictures of the setup and the computer internals also.

**Comment by TwilightWolfi** [comment]
CLOSING ISSUE

Edit: I'm an absolute basket-case. Controller blocks emit a redstone signal when the elevator arrives at the floor, and screens turn off on a signal. The screen turned off when the elevator arrived, and turned on when it arrived again.

However, the numbering system is a minor inconvenience still, though I assume it overflows to 65 as 64 is the maximum cap on the number of floors a Thut's Elevator can have. This means it is likely integrated in Thut's rather than OC, but could still be adapted in OC.
