### ISSUE TITLE
Add syntax color/highlighting to openos editor

### ISSUE THREAD

**Issue by NateKDavis** [MightyPirates/OpenComputers#2968]
I apologies if this isn't the correct place to do this. 

It would be awesome if you could use colored texted link ComputerCraft did. So like the operators would be one color, comments could be another, etc. I don't know if you can add that because of copying or whatever. But it would be super useful.

**Comment by payonel** [comment]
At this point, and for the foreseeable future, I'll be leaving the features of /bin/edit.lua as they are. I've gone down that rabbit hole before, and I may find Alice's adventurous spirit again one day, but not at this time

**Comment by NateKDavis** [comment]
Alright. Thanks for the awesome mod btw!

**Comment by BloodyRain2k** [comment]
Technically anyone could add this, someone would just need to put the effort into upgrading the Lua and donate it to the mod : /

And as much as I'd love to have this too, I can't do that and I'm too used at this point to just use NP++ and just plop the floppy back in again to reload my changes.
Works only in SP and on your own server ofc, but that's fine for me.
