### ISSUE TITLE
make Screeenplacing easy

### ISSUE THREAD

**Issue by aligator** [MightyPirates/OpenComputers#297]
check in the RightClick method of the screen-block, if the item, the player is holding is also a screen.
If it is so, don't open the Gui.

With this, sneaking is not needed, if the player wants to build a big screen.

**Comment by Wuerfel21** [comment]
Whats so bad about sneaking?

**Comment by Techokami** [comment]
Sneaking makes sense, since that's used in vanilla Minecraft for placing objects on blocks which can be interacted with (try placing a torch on a chest with sneak + right click!)

**Comment by evg-zhabotinsky** [comment]
If you are in creative or otherwise flying, sneaking in mid-air is really problematic. However, I don't know if placing a block of dirt under your legs is difficult enough to require such measures :)

**Comment by Wuerfel21** [comment]
Or just simply put down the keyboard after building the screen

**Comment by aligator** [comment]
ah ok I didn't noticed that it behaves different if there is no keyboard.
