### ISSUE TITLE
robot.swing() returns nil

### ISSUE THREAD

**Issue by Ethaot** [MightyPirates/OpenComputers#2974]
robot.swing() is documented to return true or false. For me it is returning nil instead of true - it will return false when asked to mine air, but will return nil when asked to mine a solid, whether it is carrying a tool of the correct type or not (ie it returns nil when asked to mine cobble, whether it's empty-handed or has a pickaxe equipped). As a matter of thoroughness, I also tested with the default Dig program. While the effects play for digging, the robot does not break any blocks regardless of its capability to do so.

EDIT: I should have noted this is on 1.7.2.129
EDIT 2: Sorry for thinking of things after the fact, I just reverted to 1.7.2.67 within the same modpack, and the robot.swing() function works properly with that version still.

**Comment by payonel** [comment]
thanks for testing our dev builds, i'll be sure to very this code before we push the release

**Comment by payonel** [comment]
it was due to an obfuscated field name in forge. i added code to do things the right way now
