### ISSUE TITLE
add a lua 5.1 cpu

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [MightyPirates/OpenComputers#2976]
the addition of a craftos install floppy and lua 5.1 cpu as a part that when installed in a computer makes it fully compatible with scripts for craftos (mutually exclusive with openos / lua 5.2) would make the mod more accessible to computercraft users.

**Comment by payonel** [comment]
Interesting suggestion (but sorry, no). I'm happy to help CC users learn how to transition to OC. Feel free to reach out to the community https://oc.cil.li/ and our irc channel on esper.net, #oc

**Comment by kristibektashi** [comment]
I honestly think there should be an addon (as a separate mod) that implements this. If possible, it could also add interoperability between ComputerCraft and OpenComputer peripherals (peripherals from one should work with the other and vice-versa)

**Comment by asiekierka** [comment]
The only reason Lua 5.2 and 5.3 CPUs still exist (now that 5.4 is supported) is backwards compatibility. Were that not a concern, they would have been removed as well.

This is probably not a good place to suggest addon mods - consider using the Discord or forum!

**Comment by asiekierka** [comment]
Also, there already is ComputerCraft peripheral interoperability! We've had it for years!
