### ISSUE TITLE
Way to obtain component topology

### ISSUE THREAD

**Issue by Garagoth** [MightyPirates/OpenComputers#2977]
Hi.

I am currently testing setup with several adapters, each with database upgrade, to do some item movements using Refined Storage network.
All works fine, except that I have to manually identify components and databases, match them into pairs in a config file and then run a program. This requires use of analyzer to see the address of component created by adapter (RS cable that is) and manually inputting all DB addresses to form pairs of: {label = {database, machine}}

So I was thinking, it would be really nice to be able to:
1. Label the adapter (it already has GUI...)
2. Be able to discover that external component (RS cable) and a database are connected to a same adapter.

This will allow me to stop messing with addresses and just do something like:
1. for each adapter (possibly filtered by label regexp):
2. get connected components - would result in database upgrade address and addresses of all components created by this adapter (so I would get RS cable here as well)
3. depending on what is in database, do some stuff with connected RS component

Component topology could also help with #2822 as you will be able to discover that filesystem is from disk drive (or raid etc). Not sure about floppy drive built into computer case though...

Regards,
Garagoth.

**Comment by payonel** [comment]
crouch+right click your adapter, it'll print to your chat window the adjacent components it has loaded, and their hardware addresses. this doesn't give you the topology programatically, but it is not our intention to provide direct access to an adapter, but rather only the thing(s) it loads. And using the analyzer you get the 2nd thing you were asking for (what is connected to a given adapter)

**Comment by Garagoth** [comment]
I am well aware of analyzer functionality, this is how I am obtaining addresses right now.
I wanted to be able to get this programatically. Maybe via computer component, just adding parent address would be sufficient - and adapter has one.

Regards,
Garagoth.

**Comment by payonel** [comment]
it is a meaningful request, i'm not trying to say it "can already be done" exactly. getting the addresses to your clipboard (by clicking on the text printed to your chat window) with the analyzer is our intended workflow for these needs

however, I do think it would be helpful to include the address of components in the adapter slot, I think that should be printed as well to the analyzer. i'll reopen this ticket and close it when i've added that to the analyzer report

**Comment by Garagoth** [comment]
Thanks, one less address to type manually.

I still think that adding to computer.getDeviceInfo() extra field with adapter address for components that are added by adapters (like database and blocks around) would be super cool :)

Regards,
Garagoth.

**Comment by payonel** [comment]
even if the device info listed the adapter-provided components, how are you getting the adapter address?

**Comment by Garagoth** [comment]
Hwyla/Waila is showing address of any OC component/block, including adapter. (~~Isn't analyzer showing this as well?~~ - Update: No it isn't. I have this info from Hwyla only.)
However, with adapter address being listed in device info, I wouldn't need to worry much about adapter address - mostly when debugging program and testing things, to find it in real world and see what is around and in it.
