### ISSUE TITLE
When fast graphics are enabled, floppy disks are not rendered from below

### ISSUE THREAD

**Issue by ZefTheFox** [MightyPirates/OpenComputers#2979]
![image](https://user-images.githubusercontent.com/44857466/48225807-e521bf00-e36b-11e8-8754-fde623c90e76.png)
![image](https://user-images.githubusercontent.com/44857466/48225827-f1a61780-e36b-11e8-83cb-0808ca49c053.png)
The floppy disk is in the drive in both images, it just doesn't appear from below. This only happens with fast graphics enabled

**Comment by Wuerfel21** [comment]
on fast graphics, items are drawn as 2D sprites. But apparently, the culling mode isn't changed to NONE, thus the back side dissapears.
