### ISSUE TITLE
Terrible FPS drop with shaders mod

### ISSUE THREAD

**Issue by Mourdraug** [MightyPirates/OpenComputers#298]
I tried to use open computers with shaders installed, and after i placed screen and turned it on my fps dropped down to ~4 from stable 30. Thought it might be because shaderpack places heavy load on gpu, but switching to none shaderpack didn't help after turning pc on fps went down from ~120 to ~4. Removing shaders mod completely did help and there is no fps drop without it.

**Comment by Wuerfel21** [comment]
Then dont use shaders

**Comment by Mourdraug** [comment]
I don't right now, but I was already using plenty of mods including CC and none of them had such incompability, that probably means OC breaks something in renderer.

**Comment by Wuerfel21** [comment]
Uhh, that might have to do something with #31

**Comment by evg-zhabotinsky** [comment]
Could you please give links to the mod and shader pack you use? (and other required stuff, if any)

**Comment by Mourdraug** [comment]
http://www.minecraftforum.net/topic/1544257-172174175shaders-mod-v2312-updated-by-karyonix/
http://www.minecraftforum.net/topic/940974-175sonic-ethers-unbelievable-shaders-v101/page__hl__%20seus
http://optifine.net/downloads
Drop occured using:
GLSL Shaders Mod v2.2.2 for Minecraft 1.6.4
SEUS v10.1 Standard
OptiFine 1.6.4 HD U D1
And I also have a AMD card (7950), so yup it might be somehow related with #31 .

**Comment by fnuecke** [comment]
Tested with MC1.7.10, OC 1.3.3, GLSL Shaders Mod v2.3.18 and SEUS 10.1 Ultra, cannot observe any noticeable change in FPS with or without screen being rendered. No OptiFine though. But OptiFine breaks more than it helps from my experience, anyway, so yeah. If someone else can reproduce this and wants to look into it, please do.
