### ISSUE TITLE
[Suggestion] Dyable servers

### ISSUE THREAD

**Issue by ZefTheFox** [MightyPirates/OpenComputers#2980]
The ability to color code servers in a rack would be a nice and pleasing addition.

**Comment by BloodyRain2k** [comment]
While we're at it: dyeable disc drives

**Comment by Nex4rius** [comment]
Dyable cables?

**Comment by ben-mkiv** [comment]
https://www.curseforge.com/minecraft/mc-mods/ocdevices got a rack which allows to color the rack + the rack mounts independent ;)

**Comment by payonel** [comment]
@ben-mkiv i love it! yep, please should use your mod with oc :)
