### ISSUE TITLE
HDDs sound weird?

### ISSUE THREAD

**Issue by evg-zhabotinsky** [MightyPirates/OpenComputers#2981]
Maybe it's just me, but I think that HDD activity sound is way off.
The rare clicks that computers produce infrequently when idling are spot on, but heavy disk activity sounds to me like... I don't know, really. Filing or sawing a piece of iron, maybe?

For reference, that's how I remember my 486 sounding: https://youtu.be/uIHWDnSeM-E?t=34
Now that I think about it, it sounded more like a geiger counter than current OC HDDs.

**Comment by payonel** [comment]
Good feedback, and nice video you've linked. I've heard machines that sound just like that, as well as like the machines we have.

The community is welcome to provide a PR with a better sound (though do be certain the sound bits are not bound by license for us to use). We're okay with how it sounds currently.
