### ISSUE TITLE
Destroying or wiping HDDs does not remove their contents from world save

### ISSUE THREAD

**Issue by evg-zhabotinsky** [MightyPirates/OpenComputers#2982]
When a disk is destroyed or wiped by crafting, its backing directory / file in the world save seems to remain untouched. Therefore, unreachable disk contents can pile up as players wipe / destroy ( / disassemble? ) their HDDs.

This leak can easily be used maliciously for a DOS attack by repeatedly filling up and craft-wiping the same disk. It can even be automated by making a robot do the crafting. The host, or at the very least that MC world, will run out of disk space and crash. Really discarding disk contents at least upon craft-wiping is required to prevent such attacks.

**Comment by payonel** [comment]
yeah, this is currently by design. we've long allowed users to recover lost data which can be valuable. we've discussed this before and there are some cases where we won't know the disk is safe for deletion, so we are unable to fully "close" this issue.

**Comment by evg-zhabotinsky** [comment]
My MC modding experience is near-zero, but I think this might help: https://www.programcreek.com/java-api-examples/index.php?api=net.minecraftforge.fml.common.gameevent.PlayerEvent.ItemCraftedEvent

As I understand, that handler is called whenever an item is crafted, and the 3rd example iterates over the crafting grid. So the idea is to check if a disk was crafted, check if it was crafted from an initialized disk, if so then add its uuid to that player's "wiped disks" list, and finally discard some oldest disks so that the total size of remaining does not exceed a configurable threshold.

This way, a malicious player will have to craft each disk from scratch before filling it up. (And then either destroy it or throw it into a chest.) Even with floppies this would cost a full single chest of iron and almost 2 double chests of sugar cane per GB. It's probably doable, even automatically, but very involved and time-consuming.

**Comment by payonel** [comment]
yes, we have crafting handlers, i said we cannot resolve this for all cases. i'm also not strongly interested in adding this feature, as it provides a recovery mechanism, which has been used many times in the past

**Comment by evg-zhabotinsky** [comment]
> it provides a recovery mechanism

Hence I suggested a list of recently wiped disks, only discarding the oldest when total amount of wiped but not discarded data reaches a per-player limit. I don't think someone can generate more than, say, 100MB of valuable data, and accidentally wipe all of the disks at once by crafting. (Although some asshole can potentially steal a whole chest of someone else's HDDs and deliberately wipe them all.) And it can be disabled by default in single player, because it's your own problem if you fill up your own disk.

Yes, I found the event handlers now, but none of them take notice of craft-wiping a disk. I argue that handling just that will be enough, because there's no other way to change a disk's uuid, and mining several full chests of iron would likely be way too much trouble for a potential attacker. Setting up a robot of doom that does "Fill up disk; Craft-wipe; Repeat" and running it off a solar panel is way too easy, on the other hand.

If robots and auto-crafting tables trigger crafting callbacks just like real players do, the only problem I see is to figure out which player is responsible, which should be easy for OC robots. (And I doubt that someone will manage to accidentally send a whole chest of valuable HDDs at once into another mod's autocrafting table and wipe them all, so all other fake players can be pooled into one.)

**Comment by payonel** [comment]
you're trying to solve a problem we've already discussed internally. we've already considered this issue, and we haven't ruled out that there could be value in doing this. we're already aware of the options and handlers and code you've dug into. this isn't necessarily a feature that we want

**Comment by ghost** [comment]
@payonel consider adding it as optional feature in mod config

**Comment by xarses** [comment]
Maybe adding a some bread-crumb on the host filesystem that the in-game object was dis-associated with the UUID on disk is a compromise here, this way a determined admin can formulate whatever policy they want regarding orphaned oc volumes (aka, cron-job) is a reasonable middle ground.

I very much otherwise agree with @payonel, retaining the volumes on the host has saved people many times from much frustration and grief when something goes wrong, and I would prefer that behavior stays as the default.
