### ISSUE TITLE
Unexpected error saving/loading the state of a computer

### ISSUE THREAD

**Issue by DylanJones** [MightyPirates/OpenComputers#2985]
Was playing around with robots and pathfinding, and I managed to get the server to start freezing up and throwing a bunch of OC-related errors.  Error says to report it, so here I am.  While my code _did_ use a few hundred KB to a few MB of ram, it shouldn't be too far over the limit.  
Upon restarting the server, OC threw another error saying something about the state being corrupt and then shut the robot off, which stopped the errors.

Server log: https://pastebin.com/Sk1JunDQ
Code: https://pastebin.com/ggYfp2ms

Also this seemed to upgrade my robot to have 1 GB of ram.
https://i.imgur.com/COmtaIh.jpg

**Comment by payonel** [comment]
I'll need a repro
please provide a world save file in a state where this is not happening
with a script that causes it to happen (you've provided the script)

**Comment by payonel** [comment]
This ticket will close without sufficient repro information. As far as I can tell, the world save corrupted the data and is not reproducible
