### ISSUE TITLE
[1.7.3] LuaJ not being registered in all expected configurations

### ISSUE THREAD

**Issue by Pizzn** [MightyPirates/OpenComputers#2986]
Registration of LuaJ does not happen if any other architecture is enabled. If not otherwise mentioned, I used standard values for the config. Tested architectures with Tier 2 APU and Tier 3 CPU. Forge version 1.12.2-2768 and OC 1.7.3.146.

- registerLuaJArchitecture=true
-> available architectures: 5.2, 5.3

- registerLuaJArchitecture=true
- forceLuaJ=true
-> available architectures: 5.3

- defaultLua53=false
- registerLuaJArchitecture=true
- forceLuaJ=true
-> available architectures: 5.3

- enableLua53=false
- defaultLu53=false
- registerLuaJArchitecture=true
- forceLuaJ=true
-> available architectures: LuaJ

- enableLua53=false
- defaultLu53=false
- registerLuaJArchitecture=true
- forceLuaJ=false
-> available architectures: 5.2

**Comment by payonel** [comment]
Some of these permutations of configurations do not seem correct, however LuaJ is crap - and only an option for hosts that won't have native support or for admins that are overly cautious.

If you really need LuaJ `forceLuaJ` is a solution for you.There is no reason to have LuaJ as well as native 5.2 and/or 5.3

**Comment by Pizzn** [comment]
Yes, that's the reason I issued the ticket in the first place. However, the native persistent Lua 5.3/5.2 is not always persistent in my setup at all (lacking the definite repro though, still investigating), i DO want the native lua and LuaJ side by side, to compensate for either shortcomings, e.g. Lua 5.2/5.3 not being available to resume, then to switch to LuaJ; that's the way the config is suggesting to me. And that's the way it worked in former versions.

**Comment by payonel** [comment]
LuaJ doesn't provide persistence

**Comment by payonel** [comment]
If you're trying to pinpoint a repro of a failed persistence, that would be helpful. But there is no short coming of native, it is better in every way. LuaJ has no persistence support.

**Comment by Pizzn** [comment]
I totally agree with you on LuaJ being crap  in comparison to the native ones. However, there is one thing LuaJ is nice to have IMO. If for whatever reason, persistence fails, I like to fall back to LuaJ, because if LuaJ is running/not erroring out, it keeps restarting the computer upon the chunk loading, rather than the computer being dead until manual restart ;).

Regarding the repro: I did a lot of testing this morning and it seems the culprit is the spot loader from the Chicken Chunks mod, whereas the chunk loaders from the same mod seem to be ok. Haven't checked OC's own ones and I haven't tested across server restarts yet. Something I noted is that persistence failed more often with computers than with robots (10:1 I'd say). So I think, nothing for you to fix regarding persistence failing. I will open another issue, if I find out anything useful for you.
