### ISSUE TITLE
transposer.transferItem ignores specific slots request

### ISSUE THREAD

**Issue by grompe** [MightyPirates/OpenComputers#2988]
Using OpenComputers-MC1.7.10-1.7.3.1258,

I found that the transposer's method `transferItem` ignores optional slot parameters,
and transfers from the first available slot to first available slot instead.

In the mod's code `getTransferBetweenInventoriesSlotsAt` appears to be copy-pasted from `getTransferBetweenInventoriesAt`
and does nothing with the `sourceSlot` argument. In fact, `transferBetweenInventoriesSlots` doesn't appear to be used!

https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/util/InventoryUtils.scala#L334

**Comment by payonel** [comment]
Just from reading your explanation, I suspect you're analysis is correct. However, please also provide actual lua code, expected and actual results

**Comment by grompe** [comment]
Ok. Source chest:
![2018-11-22_23 24 00](https://user-images.githubusercontent.com/1010017/48914870-463eac00-eeaf-11e8-8f78-82a67758b199.png)
Executed commands in attempts to move clay from slot 5 into slot 2 in another chest:
![2018-11-22_23 26 11](https://user-images.githubusercontent.com/1010017/48914896-5191d780-eeaf-11e8-80e7-517a0df814e1.png)
Destination chest:
![2018-11-22_23 26 16](https://user-images.githubusercontent.com/1010017/48914909-59ea1280-eeaf-11e8-970d-20cfd242f4e4.png)
Source chest:
![2018-11-22_23 26 19](https://user-images.githubusercontent.com/1010017/48914917-63737a80-eeaf-11e8-9bee-515767398eb2.png)

**Comment by BloodyRain2k** [comment]
I can confirm the issue. I've written a bee breeder for use with Forestry and before I updated OC from dev-1.6.something to 1.7.3.1258 it was still working, but as said with 1258 not anymore.
I dug around with Lua testing and came to the same result, the source slot is completely ignored.
