### ISSUE TITLE
T1 wireless modems receive wired messages

### ISSUE THREAD

**Issue by evg-zhabotinsky** [MightyPirates/OpenComputers#2989]
MC 1.10.2 (Forge 12.18.3.2185)
OC 1.7.3.224

T1 wireless modems receive wired messages, even though they can't send them and isWired() returns false.

Related questions:
1. With T2 wireless, both wired and wireless copies of the same message are received. Is it intended? Can it be avoided?
2. Is it possible to send/broadcast just a wireless message with a T2, without the wired copy?
3. Is it intended that wired messages reach robots that are adjacent to the computer? It does not quite make sense to me. Why would a robot automatically connect to the wired network whenever it gets close to, say, a monitor?

**Comment by payonel** [comment]
hmm, thanks. I thought I fixed this in 1.7.3 -- apparently not :/

**Comment by payonel** [comment]
check for distance == 0 to determine wired messages, that might help mitigate the issue for now
