### ISSUE TITLE
[SUGGESTION] Native UDP/TCP modem/tunnel sockets.

### ISSUE THREAD

**Issue by DannehSC** [MightyPirates/OpenComputers#2991]
Me and my friend were thinking about creating an encrypted protocol for OC, and it'd be very beneficial to have native sockets to connect them.

I know, it'd probably be a fair bit of work, but I can think of many cases where it'd be nice to have.

**Comment by payonel** [comment]
these types of feature we leave open to the community to develop on top of the modem_message events. others have been able to mimic traditional sockets and network stacks. See the forums, ask on irc, give it a try yourself to implement. This isn't something we plan to add natively

**Comment by DannehSC** [comment]
While I respect the answer, I still must ask, out of all possible features requested, why leave out sockets? It feels like one many systems could use. And most systems, including the one I am trying to develop, it's most likely flawed compared to a native implementation of the protocols.

**Comment by payonel** [comment]
because we like our "modem_message", you can mimic protocols on top of it, that's what it's for :) hardware signals in oc keep a common style and theme, native sockets would create hardware events that is unlike all other component events

**Comment by DannehSC** [comment]
Hm. Fair enough. Well, thanks for the quick replies and info.
