### ISSUE TITLE
Item duplication by server

### ISSUE THREAD

**Issue by Kiritow** [MightyPirates/OpenComputers#2995]
**Steps to reproduce**

Holding a server, right click and install some components. Then left click the server and move it to another slot in player's inventory. Cards in T3 slots, rams, cpu and bus extensions are still there.
After picking up all these items, press ESC and right click with the server in hand again, all items are back again.

Duplicated items have the same uuid. But if the previous installed one has no uuid (just after crafting it, before inserting into the server rack), the duplicated one will have no uuid. (kind of fresh new cards)

Duplicated items are still usable after a reloading.

Tested in Single Player with OpenComputers-MC1.12.2-1.7.3.146 and Forge 1.12.2-14.23.5.2784.

**Comment by payonel** [comment]
closed in dev builds
