### ISSUE TITLE
Unsupported method on plethora peripheral

### ISSUE THREAD

**Issue by JomerDev** [MightyPirates/OpenComputers#2996]
When trying to call methods on a Plethora manipulator oc returns 
![javaw_2018-12-03_19-08-56](https://user-images.githubusercontent.com/5282863/49392507-ebb71280-f72e-11e8-8d57-92b3b167b8af.png)
The same method works with CC computers

**Comment by SquidDev** [comment]
OpenComputers provides an [incomplete implementation of `ILuaContext`](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/integration/computercraft/DriverPeripheral.java#L234-L269), which prevents some peripheral calls from working (which includes most of Plethora's).

I'm not sure there's much which can be done here - CC and OC have very different approaches to both events and running things on the main thread, and I don't really think those two models can be united. 

I put together a PR a few months back (dan200/ComputerCraft#574) which means CC is no longer tied to it's current coroutine/event model, but I'm not sure what work can be done on the OC side. Sorry, might be getting off-topic here - just saw the issue in my notifications, and thought it might be worth chipping in.

**Comment by payonel** [comment]
we don't plan to extend our support of "just anything cc connects to", you will have to manage this device from cc it sounds like, or have Plethora add OC support
