### ISSUE TITLE
feature request: ForgeMultipart

### ISSUE THREAD

**Issue by Leftorius** [MightyPirates/OpenComputers#3]
Don't know if this is planned but it would be cool if you can cover the cables with ForgeMultipart :)

**Comment by fnuecke** [comment]
Just realized I hadn't actually commented on this: covers are something I very much want, too :)

I haven't decided on a system for this, yet (FMP, immibis' microblocks, BuildCraft Facades [AE did it apparently]... they all look bloody complicated). The decision may come down to which one is the least intrusive, i.e. the easiest to support _optionally_.

While I'm more than happy to add _support_ for as many mods as possible, I'd like to stay away from _dependencies_.

**Comment by ShadowDrakken** [comment]
Once CrazyPants finishes his cable API (assuming he ever gets caught up enough to make it, lol), EnderIO support could be an option :)

**Comment by Belgabor** [comment]
AE2 will switch to FMP afaik, generally I think that's the way to go for maximum compatibility. While it's somewhat sad, BC seems to get more and more replaced by other mods.
Personally I can't play without Ender IO anymore so supporting those facades would be amazing =)

**Comment by fnuecke** [comment]
We'll most likely go for FMP, too, but the lack (or difficulty to find, at least) of documentation made it very easy to prioritize other things ;-)

**Comment by rmellema** [comment]
Forge Multipart looks really nice, I hope you will support it. 
On another note, isn't the documentation just in the code? So only need to javadoc it?(Or something similar, I don't know what scala uses)

**Comment by lordjoda** [comment]
The problem with FMP is that you don't know where to begin with... and as there is a lack of tutorials it doesn't help if each class has a java doc if you don't know where to start from... And yes of course with enough time or motivation you could find your way around, but as Sangar said, we prioritized other things ;)
