### ISSUE TITLE
1.7.2 JVM Crash

### ISSUE THREAD

**Issue by natedogith1** [MightyPirates/OpenComputers#300]
Leaving the game running (perhaps paused, perhaps with a screen open, perhaps in inventory(can't remember)) in the background and the JVM suddenly crashed. http://pastebin.com/mBMDJ9AB no other mods were installed

**Comment by Wuerfel21** [comment]
Well, that looks like youre useing 1.3¿

**Comment by natedogith1** [comment]
I'm not sure I understand what you mean, I'm using the latest release of the 1.7.2 version (and have now have a bunch more JVM crash logs is anyone's interested)

**Comment by Wuerfel21** [comment]
i mean which opencomputers version you use(hint: click mods in main menu)

**Comment by natedogith1** [comment]
Ah, ok, yeah I am

**Comment by Wuerfel21** [comment]
Then use a 1.2 one, 1.3 buids are not stable yet

**Comment by Techokami** [comment]
From what Sangar said in the Jenkins:

> Due to what's probably some bug in the native library, I recommend adjusting the following settings for the time being:
> 
> computer.debug.disableMemoryLimit = true
> computer.debug.disablePersistence = true

**Comment by fnuecke** [comment]
Please try again with the latest builds, haven't had any crashes in a while now, so I'm hoping the bugs I fixed were all the ones there were. You might want to make sure the new native libraries are used by manually deleting the old ones from your temp folder (e.g. `C:/users/[username]/AppData/Local/Temp/OpenComputer-native.*.dll` on Windows).
