### ISSUE TITLE
Command Card to Run Command as Server

### ISSUE THREAD

**Issue by TChapman500** [MightyPirates/OpenComputers#3007]
In ComputerCraft, we have a command computer that can run commands as the server, just like the command block, but it locks-out anyone who is not OP in creative mode.  The debug card is good, but it itself needs permissions to execute commands or needs to be linked to someone with said permissions.  That said, I think it would be good to introduce a command card which can only be placed inside creative-tier computers and causes the monitor that the computer is attached to to not be interactable to anyone who is not an OP in creative mode.  Interaction by normal users or OPs outside creative mode would be through a non-primary touchscreen monitor.

**Comment by payonel** [comment]
requiring op+creative on the command card, reasonable
but having different types of access based on the screen, no

There could definitely be unexpected consequences for servers not expecting this type of access. we could make it opt-in (via configs, or via api, etc) but there is a reasonable work arounds using user access list. The creative case already requires creative. I'll decline on this request, but I can see you have an edge case with a different set of expectations
