### ISSUE TITLE
Animated texture

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#301]
I recently noticed that a computer cases side texture changes when i turn it on(the one with the fan)
It would be cool eyecandy if it actually was animated(rotating fan)

**Comment by Techokami** [comment]
Computer fans spin at such high speeds, you don't see them spin, and instead see a blur. So IMHO it's fine as-is. :wink:

**Comment by Wuerfel21** [comment]
you normally also cant see a creeper(altrough i can see my fan just fine)

**Comment by fnuecke** [comment]
Nah, the 'on' texture already fakes a spinning blurred fan (and if you see your fan's blades while it's spinning it isn't running fast enough :P). Further consideration: animated textures only update once per tick, which I imagine would make this look really weird.
