### ISSUE TITLE
IC2 reactor redstone port driver does not expose the fluid methods

### ISSUE THREAD

**Issue by MatthiasMann** [MightyPirates/OpenComputers#3010]
The following methods should be exported:
isFluidCooled()
getCoolantAmount()
getMaxCoolantAmount()
getHotCoolantAmount()
getMaxHotCoolantAmount()

The coolant amount can be checked with either getinputtank() and getoutputtank() or gaugeLiquidScaled()

I'm using OpenComputers-MC1.12.2-1.7.3.146 and industrialcraft-2-2.8.105-ex112

**Comment by Nex4rius** [comment]
Why should there be any fluid methods in the redstone port driver?

Make a fluid port and an adpater + tank controller and just check it that way.
