### ISSUE TITLE
OpenComputers NanoMachines CRASH on DisintegrationBehavior  (ATM3 ModPack)

### ISSUE THREAD

**Issue by ro5490** [MightyPirates/OpenComputers#3011]
Referred to post this here - https://github.com/AllTheMods/ATM-3/issues/823 - (Original issue opened)

Pretty much you crash and then get locked out of a SP/MP server if you activate the "DisintegrationBehavior" effect via OpenComputers Nanomachines.

Expected Behavior
Not too sure, but if you activate DisintegrationBehavior it should do something normal not crash?

Current Behavior
You immediately crash on DisintegrationBehavior activation and then cannot reconnect to the server, either SP or MP til your playerdata OCNM file is deleted.

Possible Solution
Remove DisintegrationBehavior?

Steps to Reproduce
https://streamable.com/4s8d9

Make an OpenComputer setup that has a wireless card in (also install OpenOS and OPPM onto the computer, and use OPPM to install NN using " oppm install nn "
Make some OpenComputer Nanomachines and use them on yourself
Check if the DisintegrationBehavior effect is listed for your current nanomachines with /oc_nanomachines if not then drink some Grog and try again from 2.
If it is, use the OpenComputer to "turn on" the correct numbers to activate DisintegrationBehavior by using nn commands (example: nn on 11)
5.???
6.Crash
Open playerdata and delete .OCNM to get back into the server (this removes your nanomachines data)
Log
https://gist.github.com/ro5490/9b8216121dcd87873b1cc0929570343e

**Comment by payonel** [comment]
sonar isn't checking that the EnumFacing isn't null, but then again, we don't need to pass null for the facing, then again, even handlers (such as sonar's) should be very careful to not throw exceptions

**Comment by payonel** [comment]
https://github.com/MightyPirates/OpenComputers/blob/master-MC1.11/src/main/scala/li/cil/oc/common/nanomachines/provider/DisintegrationProvider.scala#L61

**Comment by payonel** [comment]
https://github.com/SonarSonic/Practical-Logistics-2/blob/1.12.X/src/main/java/sonar/logistics/base/events/PL2Events.java#L79

getFace() returns the null we passed, and they crash here: https://github.com/SonarSonic/Practical-Logistics-2/blob/1.12.X/src/main/java/sonar/logistics/base/utils/slots/EnumDisplayFaceSlot.java#L63

**Comment by Ninetailed** [comment]
I've run into what appears to be the same issue. Server log excerpt and nanomachines NBT attached.

[nanomachines-crash.zip](https://github.com/MightyPirates/OpenComputers/files/2719522/nanomachines-crash.zip)

**Comment by payonel** [comment]
see dev builds for 1.12, >= 1.7.3 build 148
https://ci.cil.li/job/OpenComputers-MC1.12/
