### ISSUE TITLE
[1.7.2.67] Odd robot.swing() behavior with wooden axe with WorldEdit (AllTheMods)

### ISSUE THREAD

**Issue by Babbie** [MightyPirates/OpenComputers#3012]
When WorldEdit is installed, it seems to cause some weird behavior when using a wooden axe with `robot.swing()`. When trying to break a log, I'm getting `false` and `"block"` and the robot refuses to break the block, even though I can mine it manually just fine.

Note that I am using All The Mods 3, so there might be another conflict at play, but due to specifically wooden axes not working (everything else works fine) it seems very likely that it is a conflict with WorldEdit.

I have also made an issue at All The Mods 3's github: [https://github.com/AllTheMods/ATM-3/issues/824](https://github.com/AllTheMods/ATM-3/issues/824)

**Comment by payonel** [comment]
you are probably right. would you mind testing ONLY oc and worldedit?

**Comment by payonel** [comment]
oh wait, you're on  1.7.2?!?!! that's old, we've made significant fixes to our swing code. Please, test with 1.7.2 and worldedit only, then retest with 1.7.3

**Comment by Babbie** [comment]
Strangely, testing with just OC and WorldEdit resulted in normal behavior. This probably means the conflict is somewhere else, or it might be multiplayer only (since the original problem was on a server).

**Comment by payonel** [comment]
as I said, though, our swing code in 1.7.3 got a lot of fixes

**Comment by Babbie** [comment]
I should have mentioned that I tested it with 1.7.2 as well, and it worked fine there as well.

**Comment by payonel** [comment]
I'm confused
In your mod pack, you said you are using 1.7.2 and it fails
In a test world, just worldedit + oc 1.7.2, it fails?
Or was that test world worldedit + oc 1.7.3?

But now you said you tested 1.7.2 and it worked? Worked as well as what? What mods did you have in your test?

Please retest your modpack with OC 1.7.3

**Comment by Babbie** [comment]
In All The Mods 3, which uses 1.7.2, chopping with a wooden axe fails.
In a test world with just 1.7.2 and WorldEdit, it works just fine, as well as a test world with 1.7.3 and WorldEdit.
I'll test All The Mods 3 with OC 1.7.3 tomorrow, when I have time (since booting it takes 15 minutes... Big packs, am I right)

**Comment by Babbie** [comment]
I have not found a way to reproduce the bug in singleplayer. I've tested ATM3 as is and ATM3 with OC 1.7.3, but it seems to be working normally on both of them. This leads me to believe it's either a multiplayer-only bug or there is an interaction going on somewhere that I'm not seeing. Tomorrow, I'll try loading the world from the multiplayer server in singleplayer and see if I can reproduce the bug that way.

**Comment by payonel** [comment]
Interesting. I really appreciate your efforts to test this.

**Comment by payonel** [comment]
couldn't repro :( but added some null checks on that crash line

**Comment by payonel** [comment]
no repro sorry - and i see the modpack github also closed. i do recommend not using wooden axes fwiw :)
