### ISSUE TITLE
Add External Component Upgrade for Micro-controllers with Limits

### ISSUE THREAD

**Issue by ComputerErika** [MightyPirates/OpenComputers#3019]
I have been building a Turret System with OpenComputers and OpenSecurity and I REALLY don't want to have a computer for every turret I want to set up! A tier 3 Upgrade for the Microcontroller that allows it to connect to 3 external components would help a lot! I know this might not fit OpenComputers but I still wanted to ask.

**Comment by ComputerErika** [comment]
This would be so useful for so many other projects too such as for the door controllers in open security!

**Comment by payonel** [comment]
you should run oc cable to each turret, and control them all from a central machine, or use ender io oc conduit. but yeah, microcontrollers and "full" computers need to satisfy different needs, and not overlap so much

**Comment by ComputerErika** [comment]
Ok cool, that is a good idea! Thanks for the help! :)
