### ISSUE TITLE
Robot reading the script incorrectly

### ISSUE THREAD

**Issue by Xelbayria** [MightyPirates/OpenComputers#3020]
I believe this is a bug. Here's the detail: 

I have created a script where I want to make the robot facing in what direction from the direction it was facing. 
UPDATED SCRIPT:
______________________________________________

https://pastebin.com/qg93FYDk
____________________________________
so here's a few results: 
Robot facing North: 
input (south) - > turn around <- correct
input (east) - > turn Right <- correct 

Robot facing East: 
input (west) - > turn right <- incorrect: It should be "turn around"
input (north) -> turn right <- incorrect: It should be "turn left"

as you can see that the robot is reading the script incorrectly. I have run this script within my computer using the Lua console. it was working just fine. if you are familiar with IF-statement, then you know how it works.
if it's not the robot reading the script incorrectly as you know what caused this bug, then please tell me. I'm not sure why I got the wrong result, not the desired result. Thanks

**Comment by TheCodex6824** [comment]
Your `bearing` variable is being assigned to outside the scope of the `turn` function, so it is only being assigned to when the script is loaded and not when the function is called. So, if the bearing changes, the script will still have the old bearing. You just need to set bearing to the current facing inside the function.

Since it looks like you are trying to make an API, if you are using `require` to load this in another script it will load it once and then cache it, even if you end up using `require` on it multiple times.

**Comment by Xelbayria** [comment]
Oh yeah. I don't think of that. Let me take a look at my coding
______________________________________________________________________
edit:
@TheCodex6824 you are right. it's the bearing variable. when i made the robot turned to "east", the bearing doesn't change.. I am not sure how to solve this. this will take a whille for me to figure it out.

**Comment by TheCodex6824** [comment]
I'd probably move the bearing assignment as the first line in the function, and maybe instead of converting the bearing to words have some constants to compare it to, like:
```
local BEARING_NORTH = 2
-- do the rest for each direction

function facing.turn(direct)
  local bearing = component.navigation.getFacing()
  if bearing == BEARING_NORTH then
    -- do everything else...

**Comment by Xelbayria** [comment]
I see. I've moved bearing inside the function. it doesn't work. But I've added a few things to the script. I'll update the script so you can take a look. It works without any problems. 

what I added is create another function for the bearing. function facing.check()
then i can add the function inside facing.turn(direct) where it can update the value of bearing to the latest direction that the robot is currently facing. 

EDIT: I'll need to do some research to learn more about how to update the value of variables everytime an action happened, so they won't be outdated and give undesired results
