### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by KRGAMING2005** [MightyPirates/OpenComputers#3021]
TransformerLoader (OpenComputers-MC1.12.2-1.7.3.146.jar)
I cant find anything calles TransformerLoader
![error](https://user-images.githubusercontent.com/44669137/51017751-759b9c00-1575-11e9-8e74-5878abf00f0e.PNG)

**Comment by payonel** [comment]
we need to know the offending mod (if you have many other mods, please reduce the mod pack size until you can determine which mod doesn't play nice with OC)

**Comment by payonel** [comment]
not enough info given. next time we see TransformerLoader errors we need to know the mod in your modpack that is not playing nicely with OC
