### ISSUE TITLE
Redstone I/O dosen't work with Bundled Cables from Charset.

### ISSUE THREAD

**Issue by Acerixx** [MightyPirates/OpenComputers#3023]
https://puu.sh/Cw7lO/ea0cd5e392.png

**Comment by payonel** [comment]
if you are requesting charset support, you should also specify which version of oc, mc, and charset you are refering to. Note that it is not planned to add new mod integration in mc 1.12 nor for oc 1.7.x

**Comment by Acerixx** [comment]
MC: 1.12.2
Charset: 0.5.5.6
SimpleLogic-Wires: 0.5.5.0
OC: 1.7.3.146

**Comment by brisingraerowing** [comment]
Computronics adds compat for Charset.
