### ISSUE TITLE
Can't Select Specific Monitor in BIOS

### ISSUE THREAD

**Issue by TChapman500** [MightyPirates/OpenComputers#3025]
On a setup with multiple monitors that can display output, it is impossible to reprogram the bios to select a specific monitor as the default monitor for output.  Code example:
```lua
local screens = component.list("screen")
local screen
for i = 1, #screens do
    if screens[i].address == [target_address] then
        screen = screens[i].address  -- screen = screens[i] doesn't work.
        break
    end
end
```
This code, if placed in the bios in the place of `local screen = component.list("screen")()` will not work the way it's supposed to.  The monitor selected to be the default will still be random.  I have tried other variations on the code as well, which also don't work.

**Comment by payonel** [comment]
please provide all of your eeprom code

**Comment by TChapman500** [comment]
```lua
local init
do
  local component_invoke = component.invoke
  local function boot_invoke(address, method, ...)
    local result = table.pack(pcall(component_invoke, address, method, ...))
    if not result[1] then
      return nil, result[2]
    else
      return table.unpack(result, 2, result.n)
    end
  end

  -- backwards compatibility, may remove later
  local eeprom = component.list("eeprom")()
  computer.getBootAddress = function()
    return boot_invoke(eeprom, "getData")
  end
  computer.setBootAddress = function(address)
    return boot_invoke(eeprom, "setData", address)
  end

  do
    local screen = component.proxy("451")  -- Changed line (appears to work at first, but doesn't)
    local gpu = component.list("gpu")()
    if gpu and screen then
      boot_invoke(gpu, "bind", screen)
    end
  end
  local function tryLoadFrom(address)
    local handle, reason = boot_invoke(address, "open", "/init.lua")
    if not handle then
      return nil, reason
    end
    local buffer = ""
    repeat
      local data, reason = boot_invoke(address, "read", handle, math.huge)
      if not data and reason then
        return nil, reason
      end
      buffer = buffer .. (data or "")
    until not data
    boot_invoke(address, "close", handle)
    return load(buffer, "=init")
  end
  local reason
  if computer.getBootAddress() then
    init, reason = tryLoadFrom(computer.getBootAddress())
  end
  if not init then
    computer.setBootAddress()
    for address in component.list("filesystem") do
      init, reason = tryLoadFrom(address)
      if init then
        computer.setBootAddress(address)
        break
      end
    end
  end
  if not init then
    error("no bootable medium found" .. (reason and (": " .. tostring(reason)) or ""), 0)
  end
  computer.beep(1000, 0.2)
end
init()
```
NOTE:  Secondary monitors must also have a keyboard as well as the one intended to be primary.

**Comment by payonel** [comment]
your eeprom code doesn't have the same code that you first posted. So I'm not sure which issue you're having.
However, I can say that `component.proxy("451")` definitely isn't going to work. you'll need the full address/guid

**Comment by TChapman500** [comment]
You can just replace the line that I marked with the code that I first posted.  I tried both and they all failed.  I'll try with the full address and see what happens.

**Comment by TChapman500** [comment]
Full address still doesn't work.

**Comment by payonel** [comment]
Sorry -- I didn't read the whole eeprom until just now (I was busy with other things, and distracted) you're invoking init.lua (standard eeprom boot behavior) and then I'm assuming you're booting openos at that point. We don't support keeping the same screen in this manner, openos doesn't have multimonitor support. you'll need to also edit https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/openos/lib/core/boot.lua#L24 to select the same screen

**Comment by payonel** [comment]
you could edit that line to check if a screen was already bound, by checking `gpu.getScreen()`
