### ISSUE TITLE
Major Lag Spikes During World Save.

### ISSUE THREAD

**Issue by StoneLegion** [MightyPirates/OpenComputers#3026]
So I'm using 1.12.2 of OC and I find during World Save on a modpack I'm making I get over 3500ms+ can't keep up messages steady. Just even with OpenOS sitting at the command prompt. If I shutdown the PC itself and then check it still sits at 3500ms.

But if I reboot the entire server and not turn it on it's quite lower around 2000ms.. Once I turn the PC back it's about 3500ms.

So I wanted to test this on my own pc to see and it still happen. About 2600ms with it on and then off and reboot about 1400ms. Including when I just delete the OC folder from the world.

Is there some known issue when saving during world state?

First machine: 2600k/18gigs ram/250 gig ssd.
Second Machine 9900k/32gigs ram/1tb m.2 drive that clocks about 2500MB/s write speed.

**Comment by payonel** [comment]
short answer: no, we do not have reports of this nature

how many oc machines? do it repro with oc only? deleting oc folder from the world would effectively clear every oc filesystem in the world.

**Comment by payonel** [comment]
new world, made 4 machines, each with drives, all 4 running. world saved in less than a 250ms. I can see that you've tried to repro this. try testing with oc only. report how many machines it takes to repro.
