### ISSUE TITLE
Burning sound files to music disc

### ISSUE THREAD

**Issue by NeonWizard** [MightyPirates/OpenComputers#3027]
I understand there's a lot that goes into encoding audio data and such, and that the devs want to avoid large file systems. However, it would be a pretty nice feature to be able to burn sound files to a music disc to allow custom songs on a jukebox. The sound files could be downloaded from the internet with the internet card, and then a DVD burner block could allow burning it to a special blank music disc.

**Comment by payonel** [comment]
there is a companion mod, computronics, that has interesting audio features. look there
https://github.com/Vexatos/Computronics/
