### ISSUE TITLE
Starting drones on non full blocks

### ISSUE THREAD

**Issue by Matrix89** [MightyPirates/OpenComputers#3029]
When a drone is started on a half block it stays on the same block but it looks like it's on the block above. IMO if the drone is started on a non full block it should move one block up.
Steps to reproduce:
1. Place two chests with a drone on top, like [this](https://i.imgur.com/l07NNM4.png)
2. Start the drone(it looks like it's hovering very low on the block above the chest, but in fact it's still on the block below)
3. When you try to access the chest(using the inventory controller) below(side 0) the drone reports contents of the bottom most chest

**Comment by QuicksilverBou** [comment]
This bug annoying me, too. I just place drone on full solid block (charging block for exemple) to fix this.

**Comment by payonel** [comment]
after some play testing this particular issue, I can agree. The drones should start in such a way to read the block below.
