### ISSUE TITLE
Error raised when start up - MC1.12.2-1.7.3.146 - "执行类转换器时发生错误"

### ISSUE THREAD

**Issue by Somiona** [MightyPirates/OpenComputers#3030]
I'm running under Chinese so I can guess what the English error message would be: "Error when performing class transformer".
The game was not crashed, except a message popped up and told me that this error should be reported. An error log is attached.

[latest.log](https://github.com/MightyPirates/OpenComputers/files/2777790/latest.log)

**Comment by skyem123** [comment]
Can you give a list of all the mods that you have installed?

**Comment by Somiona** [comment]
I've tried to make that error message raise again, but it seems like only occurred once. I'll comment again if that error is raising any more.

**Comment by payonel** [comment]
no repro, class transformer errors also need to tell us which is the offending mod (We need to know what mod in your mod pack causes oc to complain)
