### ISSUE TITLE
Error booting after exiting minecraft

### ISSUE THREAD

**Issue by Iron-Fist-SA** [MightyPirates/OpenComputers#3032]
I'm Playing on Minecraft 1.12.2 but tried this with other versions of minecraft as well and the result stays the same. OC version - OpenComputers-MC1.12.2-1.7.3.146. Forge version - 14.23.5.2808 (also tried other versions). Ok Here is what happens on single player mode. I build my PC And install OpenOS on disk from floppy. I can use the computer and write programs and all but when I exit the world or minecraft and return at a later stage to play again the PC displays the #Home where I can type the program to run but it does not respond but it makes the disk sound when I press enter. No command is responsive. the only way to get anything from the PC is to press the power button and the is gives a blue screen with message unrecoverable error computer halted. the only way to get the pc working again is to remove the disk and reinstall a clean disk with OpenOS. On the server side I can exit and enter as I like as long as the server is not restarted . In my case I am running a server for me and my 2 sons and switch off the server every night after we played.
[latest.log](https://github.com/MightyPirates/OpenComputers/files/2797313/latest.log)

**Comment by skyem123** [comment]
This seems to be that it's corrupting the actual files stored somehow...
Could you disable filesystem buffering in the opencomputers configuration and see if you no longer need to reinstall after restarting the game?

**Comment by Iron-Fist-SA** [comment]
Thanks this seems to be the problem, Systems up and running with no issues, is this a general problem or just a MultiMC issue because I created a instance with minecraft's GUI and worked.

**Comment by payonel** [comment]
I exclusively use multimc. I would like to figure out what you're doing with multimc that causes this. I'll close this ticket, but please, if you are able to find any more info about how this is happening, it would be quite helpful

**Comment by payonel** [comment]
@Cobus777 i saw your note in curseforge (btw, that's the first time i've ever noticed i got a message in curseforge in a very long time....github is best, or pm me in irc if you have private info)
anyways, my best guess would be where you're running multimc from, perhaps there are permissions on the filesystem for modifying files. sometimes programs are allowed to create files, but not modify existing ones. you could try moving mmc to a nonprotected path, you could try elevating privs of mmc. but regardless...this seems like a host issue and not a mod issue. good luck!
