### ISSUE TITLE
robot.swing() has different behavior in 1.12 and 1.7.10

### ISSUE THREAD

**Issue by svitoos** [MightyPirates/OpenComputers#3035]
diffs:
- mining block at the wrong tool:
  - 1.7.10 - the block does not break - robot.swing() returns false
  - 1.12 - the block breaks without a drop - robot.swing() returns true
- mining a bedrock:
  - 1.7.10 - robot.swing() returns false
  - 1.12 - robot.swing() returns true

Is it a feature or bug?
Is it possible to return the old behavior?
Maybe add a "component.robot.canMineBlock()" method?

Versions:
- MC1.12.2-1.7.3.146
- MC1.7.10-1.7.3.1258

**Comment by payonel** [comment]
hmm, strange. the swing work was actually a significant improvement, but just looks like we have a bug in the 1.12 branch. 1.7.10 isn't the "old behavior", we try to keep the features and bug fixes the same across all mc versions (when reasonable/possible to do so). You'll notice in your versions they are both "1.7.3", thus you are using OC 1.7.3

**Comment by payonel** [comment]
closed in dev builds (>= oc for 1.12 version 1.7.3.147)
