### ISSUE TITLE
What about component.getTier() method?

### ISSUE THREAD

**Issue by MoonlightOwl** [MightyPirates/OpenComputers#3037]
It would make tier-dependent Lua code easier to write, and more consistent too.

Methods like `gpu.maxDepth()` are not always obvious.
And in this case it also does not allow to distinguish between a screen tier and GPU tier.

**Comment by Vexatos** [comment]
How would you want to get the tier of things that aren't components? Would need to be part of deviceinfo then.

**Comment by payonel** [comment]
this would be for device info, indeed

**Comment by 4PXKHF9IK8ZL7XKN** [comment]
I have had the problem just now.
As a workaround I have to offer this function:

https://gist.github.com/4PXKHF9IK8ZL7XKN/61298527e1c098ae496536f5bb8d7495

Of course, this also has the problem that is indistinguishable, who limits the color depth or resolution.
