### ISSUE TITLE
Computer keeps trowing halted error

### ISSUE THREAD

**Issue by lukeh990** [MightyPirates/OpenComputers#3038]
my computers keep bring up a computer halted error after reboot I am trying to reboot my system and when I turn the computer on and a blue screen says computer halted I have installed the OS correctly it might be one of my addons but this has never happed before
![screen shot 2019-02-01 at 8 45 23 pm](https://user-images.githubusercontent.com/20286772/52158047-5074e780-2662-11e9-95c8-a9ee2ceaff0b.png)

**Comment by payonel** [comment]
I assume this is the same discussion from https://oc.cil.li/index.php?/topic/1808-computer-halted-error

We do not have a repro of this. please verify you can repro on a single player game
also verify you can play the same modpack via multimc, and not just twitch launcher, or others, and verify it repro's in mmc

also try removing all other mods, and produce a repro

once you are not sure what else to remove from the equation, please zip up your minecraft folder and send it to me. pm me in irc (oc on esper net) and i can share a cloud folder for you to upload it to

**Comment by payonel** [comment]
I saw this issue while testing #3031
I actually think these two bugs are the same.
The computer will go to a halted state once the machine lua state completes
if your init.lua is empty, you'll get this halted state
