### ISSUE TITLE
Convert from OC power to RF (or atleast allow carpeted capacitors to output to RF)

### ISSUE THREAD

**Issue by CorneliusCornbread** [MightyPirates/OpenComputers#3042]
I know this has been requested in the past, but now with the introduction of an actual power gen with carpeted capacitors, I'd like to see if there's a way to convert OC power to RF so I can transport and store it using RF based blocks.

At the very least I'd like to be able to connect RF cables to carpeted capacitors to directly store it as energy

**Comment by payonel** [comment]
we prefer to not power RF.
The carpeted capacitors are really intended to provide some power for worlds with NO power, but we needed something for OC. OC is not meant to be a power source, once you have another RF producing source, use that to power your oc machines. If you really want to convert OC to RF, you can discharge oc batteries in rf machines
other mods or addons are welcome to convert our power to theirs
