### ISSUE TITLE
OpenComputers makes server crash

### ISSUE THREAD

**Issue by chnigel** [MightyPirates/OpenComputers#3044]
Hello developer, I use opencomputer 1.7.2.67 in my server, and it works very well before.
But recently, it makes the server low tps even make the server crash.
I don't kown what happened to it, but the sponge's timing report says "OpenComputers::SimpleComponentTickHandler_onTick" event takes too much ticks.
Here is the crash-report file:
[crash-2019-02-08_21.41.19-server.txt](https://github.com/MightyPirates/OpenComputers/files/2847812/crash-2019-02-08_21.41.19-server.txt)
And the timing link: 
https://timings.aikar.co/?id=3374cf96acc340d0831bf7c559d030b6

Thank you!

**Comment by payonel** [comment]
there is likely far too little information here to provide any type of fix. first of all, we don't support sponge, but only forge. secondly there is no info in your bug report for us to perform any type of repro. you must always provide mc version, forge version (though you're not using forge), and steps to reproduce. If you are unable to provide repro steps, you may attach a zip of the full server folder (mods, configs, and worlds), or a link to it.

**Comment by chnigel** [comment]
We are using forge now without doubt.
Minecraft version is 1.12.2 and forge version is 14.23.5.2768.
The link of server(zipFile, contains mods,configs and worlds) is below:
https://1drv.ms/u/s!ApHBqrLMYY3Pg8YgGcP1fppw9Vva9w

**Comment by payonel** [comment]
I downloaded your server, ran it, and tested it.
This bug does not repro for me
there is no crash. i see no tps issue. 
The code in the crash report, the on_Tick handler that ran for 60s, hasn't been an issue for us before.

I appreciate you taking the time to zip your world and upload. Normally that would be enough for a repro. But ideally you are able to isolate the problem and define it in terms of minimal steps to reproduce (a.k.a. a repro)

**Comment by skyem123** [comment]
Out of curiosity what is your server? What OS/Java version, etc...

**Comment by payonel** [comment]
from the lua natives (.dll) the OP is running windows, and likely oracle java. i'm running gentoo with openjdk

**Comment by chnigel** [comment]
OK, I think I have found the where the issue is.
It seems that Thuttech(elevator) does not work very well with Open Computers.
Teleport to x=379, y=72, z=204 and do nothing for a moment, then you will see "Can't keep up!" warning showing in the console, if waiting longer, the server will crash; but there is no performance problem when oc is removed.
After entering "/sponge timings report" command, it will take seconds to show a link related to timings Viewer which contains current timing infomations and entering "/sponge tps" to show tps.

The link of test server is below:
https://1drv.ms/u/s!ApHBqrLMYY3Pg8YhCArWIWREdy6Kzw
(Opencomputer is disabled,you can enable it later)
Minecraft version is 1.12.2 and forge version is 14.23.4.2705.

**Comment by payonel** [comment]
sorry, cannot repro
