### ISSUE TITLE
Beep

### ISSUE THREAD

**Issue by T0biasCZe** [MightyPirates/OpenComputers#3045]
Hello. When i write computer.beep(), etc... it says file not found =/
![obrazek](https://user-images.githubusercontent.com/44525446/52536497-9f560780-2d5b-11e9-83af-ef73bdcad821.png)

**Comment by LizzyTrickster** [comment]
That's because `computer.beep()` is a function provided by the computer component, not a program that you can run in the shell.

try writing `computer.beep()` to a file then running that or execute it from the `lua` prompt

**Comment by payonel** [comment]
as lizzy said, youre in the shell prompt where you issue bash-like commands (openos is linux inspired)
`computer.beep` is an api, you use that in lua script or the lua repl
