### ISSUE TITLE
OC 1.7.2 (MC1.7.10) File System/File System Buffer Error.

### ISSUE THREAD

**Issue by Maxstripe** [MightyPirates/OpenComputers#3046]
Server Side Issue. Cannot Reproduce In SP.
i cant save new files to any file system (hard drives, floppys)
file names save but the files themselves come up empty after a reboot

**Comment by payonel** [comment]
duplicate of #3031, #3040, etc
use our latest release please: https://minecraft.curseforge.com/projects/opencomputers/files
