### ISSUE TITLE
[MC1.12.2] [OC 1.7.4.153] problem with enchanted instruments

### ISSUE THREAD

**Issue by DOOBW** [MightyPirates/OpenComputers#3050]
When some blocks are destroyed with an enchanted tool, the robot returns false.
https://youtu.be/lUXPgaQlE5c

**Comment by svitoos** [comment]
only when the block breaks immediately in the "PlayerInteractionManager.onBlockClicked" method
(high efficiency tools + low hardness blocks)

**Comment by payonel** [comment]
interesting problem. I have a fix, I check for a change from block to air in this case where the block breaks too fast

**Comment by svitoos** [comment]
breaking an ice block produces water
