### ISSUE TITLE
[1.12-1.7.4.153] Fluid dupe

### ISSUE THREAD

**Issue by LeoBeliik** [MightyPirates/OpenComputers#3051]
I tested this with oc and vanilla only.
I made a robot in my test world (I made it in survival, giving me the parts and waiting until it was created, so I didn't insta make it in creative. I don't know if this is important but I want to clarify)
When I give it a bucket and use the command 'robot.use()' with a cauldron in front of the robot, the cauldron was filled with water and the bucket of water stayed in the robot (it also works with bottles), allowing me to repeat the process and get infinite fluid.
This also happens with barrels and the tank of immersive engineering.

P.s.: sorry for my English "x)

**Comment by Asioron** [comment]
This error is present in many versions, for example, I tested it in 1.7.2 and in 1.7.4 there it definitely is. As soon as I discovered this error, I tried to report it via the IRC quietly, but unfortunately there were no developers out there.
https://youtu.be/HQtI38PJjaM

**Comment by payonel** [comment]
Thank you for reporting, I've been working on a fix for this and another robot.use bucket issue discussed on the forums: https://oc.cil.li/index.php?/topic/1838-robotuse-not-working-with-water-bucket/#comment-8584

**Comment by payonel** [comment]
fixed in the next dev build: https://ci.cil.li/job/OpenComputers-MC1.12/154/
