### ISSUE TITLE
Possibility of "Too Many Components" after reloading Compact Machines

### ISSUE THREAD

**Issue by TorakWolf** [MightyPirates/OpenComputers#3052]
Version: 1.7.10-1.7.4.1265

Now I believe this could be fixed by either OC or CM, but CM does not support 1.7.10 anymore. It's probably something to do with the fact that the Compact Machines (if configured to behave like that) only gets loaded after the chunk they are in (the same as the computer). For whatever reasons, this triggers the computer thinking that there are too many components connected.

I suggest adding some sort of delay to only check for components inside Compact Machines after their chunk is properly loaded, or even if this proves to be hard, just add a 5-8 second delay before the computer tries to connect to it, still way better than having the whole thing shutting down.

**Comment by Nex4rius** [comment]
Sounds a bit like a <a href="https://github.com/MightyPirates/OpenComputers/issues/1908#issuecomment-231563047">problem</a> I had before.

There is this option in the OpenComputers config.

> The time in seconds to wait after a computer has been restored before it continues to run. This is meant to allow the world around the computer to settle, avoiding issues such as components in neighboring chunks being removed and then re-connected and other odd things that might happen.
> startupDelay=0.25

**Comment by payonel** [comment]
@TorakWolf do you have this problem still? if so, can you zip up the world and mods so i can import to mmc and retest?

**Comment by payonel** [comment]
closing for no repro/no response
