### ISSUE TITLE
OC crashes AE network tool

### ISSUE THREAD

**Issue by purpleposeidon** [MightyPirates/OpenComputers#3054]
![](https://user-images.githubusercontent.com/150333/53141712-fcb13c00-3545-11e9-846e-9f07ca1bdf33.png)

https://gist.githubusercontent.com/purpleposeidon/c42f16d22c8c5146c215ba73fdf5dce8/raw/74bce155aef1aa539150a6911e1498d29e0b65e3/gistfile1.txt

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3925

OpenComputers-MC1.12.2-1.7.4.153.jar
appliedenergistics2-rv6-stable-6.jar
Forge: 14.23.2781

**Comment by payonel** [comment]
fixed with dev build: https://ci.cil.li/job/OpenComputers-MC1.12/155/ or later
