### ISSUE TITLE
[AE2] Interface(part) connected to Adapter, can't access ME network via Common Network API

### ISSUE THREAD

**Issue by FrozoWolf** [MightyPirates/OpenComputers#3055]
Hi,

I found a problem with the following setup. Maybe it's intentional or maybe it's not.
When connection an (AE2) Interface to the (OC) Adapter block, it shows up like it should!
But the Common Network API is not available. 

I can't use the ME Coantroller because channels are disabled.

Mods used:
appliedenergistics2-rv5-stable-11
OpenComputers-MC1.12.2-1.7.4.153

Setup:

Computer internal:
![](https://i.imgur.com/8ClWIX1.png)

Adapter connected:
![](https://i.imgur.com/f0BRMBS.png)

Components command result:
![](https://i.imgur.com/oAyceDW.png)

Lua command on me_interface:
![](https://i.imgur.com/tbDiyrd.png)

Missing API command:
![](https://i.imgur.com/pE5SL8T.png)

Am I doing it wrong? Hopefully there is a solution.

**Comment by payonel** [comment]
You found that our AE Interface PART support was lacking `NetworkControl` access, the Interface BLOCK had it, but not the part. I've fixed that now, see https://ci.cil.li/job/OpenComputers-MC1.12/156/ or later

**Comment by Alexejhero** [comment]
@payonel The link you posted (https://ci.cil.li/job/OpenComputers-MC1.12/156/) is broken. Is there any place I could download version 156 of this mod? (Very important)

**Comment by payonel** [comment]
it doesn't have to be build 156, just the latest builds

**Comment by Alexejhero** [comment]
In the latest builds, the ME intefaces don't even appear in the component list.

**Comment by Alexejhero** [comment]
Should I create another issue for this? @payonel

**Comment by payonel** [comment]
you need an OC adapter next to the me interface. just tested this and it works

**Comment by Alexejhero** [comment]
Which version did you use, and did you use a block interface or a cable interface?

**Comment by Alexejhero** [comment]
Just tested on 173 and the computer did not even list the interface under the components list.

**Comment by Alexejhero** [comment]
The interfaces are detected if channels are enabled, but if channels are disabled, no interfaces show up in the components list (which makes the fix pretty much useless)

**Comment by payonel** [comment]
i always work with dev builds, btw. thanks for the update. i'll retest with channels disabled

**Comment by Alexejhero** [comment]
If you need more details, mc version is 1.12.2, modpack is Omnifactory (latest version), with OpenComputers manually added.

**Comment by payonel** [comment]
fixed in latest 1.12 dev build, thanks for your patience (build >= 1.12 178)
