### ISSUE TITLE
[1.7.4.153] client crash, one off

### ISSUE THREAD

**Issue by kreezxil** [MightyPirates/OpenComputers#3056]
one of my players reported that my World of Dragons pack is crasshing for them. However, I and my staff are unable to reproduce it.

https://pastebin.com/BpjwRg5d

**Comment by payonel** [comment]
we have a dependency on com.typesafe:config which should be available as a library by your clients launcher. They probably moved files, switched launchers...broke an installation of something. But this is not our code directly. I believe they are missing the akka-actor jar (clients should not have to download this themselves). It might resolve for them if they recreate the instance of mc and launch. These libraries should be installed on the first launch

**Comment by kreezxil** [comment]
yeah that's what I told them to do, that Twitch likely screwed up the install, for them to wipe to install and try again.
