### ISSUE TITLE
Make Security A Concern

### ISSUE THREAD

**Issue by ThanasisVlioras-zz** [MightyPirates/OpenComputers#3057]
So .. i am a bit of a nerd so i want to make security a cool thing to worry about in multiplayer

I was thinking that you could make it so network cards have monitor modes ?
(this means that if a messge is sent NOT TO YOUR CARD but its in the range of your card, the card ignores the message, but if it is in monitor mode, then it can read messages not directed at it, yes this can happen irl)

Maybe make it so tier 1 cards dont have a monitor mode for balancing

Or.. maybe i just want to give my friend a copy of my networking software that does not include encryption
so that i can read all his passwords for whatever he is doing with open computers

Also sorry if this sounds really vague, but uh im not creative im sorry

**Comment by payonel** [comment]
we've discussed similar ideas before. there is Computronics, an addon for opencomputers, which providers some different play options with OC

closing as (nearly) duplicate of #1597
