### ISSUE TITLE
screens loses all colors -> really weird screen behaviour

### ISSUE THREAD

**Issue by Nex4rius** [MightyPirates/OpenComputers#3060]
If you break the bottom left screen then weird stuff happens.

The screen is suddenly in black and white and cannot be changed with gpu.setBackground() gpu.setForeground().
Additionally the resolution is going down (I think to tier 1 level).

Futhermore the other screens have suddenly this lower resolution "window" thats affected by term.clear().

The other screen reset after a reboot but the screen where you broke and placed the bottom left screen resets only sometimes.

I've found a workaround by calling gpu.bind(ID) but it doesn't work with gpu.bind(ID, false)
```lua
local c = require("component")
for screenid in c.list("screen") do
    c.gpu.bind(screenid)
end
```
I showed it in a video:
https://youtu.be/ECHCsf2WeKs

OpenComputers-MC1.12.2-1.7.2.67

**Comment by payonel** [comment]
update to 1.7.4 and retest
also, I very much do not appreciate profanity in bug reports (I edited it out of your comment)

**Comment by Nex4rius** [comment]
I've tested it now in 1.7.4 and it's exactly the same.
OpenComputers-MC1.12.2-1.7.4.153

>also, I very much do not appreciate profanity in bug reports (I edited it out of your comment)

Sorry about that.

**Comment by payonel** [comment]
Would you share your test code that you are running in the video? Thanks
Also, does the top screen have a keyboard? Or only the screen that is sitting directly on the case?

**Comment by Nex4rius** [comment]
The keyboards aren't affected by this issue that might have just been me showing it badly.
The top screen didn't have a keyboard.

Sure here it is:
```lua
local component       = require("component")
local term            = require("term")
local gpu             = component.getPrimary("gpu")

--[[
for screenid in component.list("screen") do
    gpu.bind(screenid)
end
]]

for R = 0, 255, 50 do
    for G = 0, 255, 50 do
        for B = 0, 255, 50 do
            for screenid in component.list("screen") do
                gpu.bind(screenid, false)
                local farbe = tonumber(string.format("0x%x%x%x", R, G, B))
                gpu.setForeground(0x000000)
                gpu.setBackground(farbe)
                term.clear()
                print("test here", string.format("0x%x%x%x", R, G, B))
            end
        end
    end
end
```
And here to reset the screens:
```lua
local component       = require("component")
local term            = require("term")
local gpu             = component.getPrimary("gpu")

for screenid in component.list("screen") do
    gpu.bind(screenid)
    gpu.setForeground(0xFFFFFF)
    gpu.setBackground(0x000000)
    term.clear()
end
```

**Comment by payonel** [comment]
after some careful review, I've determined that this is somewhere between "by design" and "will not fix" :). the gpu holds the depth and resolution, and sending bind(screenid, false) tells it to NOT reset based on the screen you're connecting to. Note that bind(id, false) is also now faster in our latest dev builds for 1.12

BTW, this isn't "bottom left" problem, per se -- as you break screens there is some networking that happens as the machine determines the attached screens and the gpu is losing screen connections and metadata

also - a cache of screenids might help you detect when screen configurations change
