### ISSUE TITLE
MineOS Installation crashes on OpenComputers Error

### ISSUE THREAD

**Issue by gvsem** [MightyPirates/OpenComputers#3061]
Running multiplayer Minecraft server (1.12.2, 3 GB of RAM) with OpenComputers 1.12.2-1.7.4.153.
I have a computer built (Graphics Card Tier 3, Internet card, Processor Tier 3, 2 x Memory Tier 3.5, HDD Tier 2, Open OS Diskette, Tier 3 Computer Case, 2 x Screen Tier 3, Keyboard).

**What did I do:**

1. Set up a computer 
2. Install OpenOS on /mnt/.../ + reboot
3. Run an installation of [MineOS](https://github.com/IgorTimofeev/MineOS): pastebin run 0nm5b1ju

**What happens next:** installation crashes after the full completion of the MineOS progress bar with a blue screen error with the following statement:

Unrecoverable Error

machine:1494: [string "..."]:183: load =GUI: java.lang.NullPointerException
stack traceback:
[Java]: in ?

THIS ERROR CAN'T BE CAUSED IN A SINGLEPLAYER GAME. It is produced ONLY in a server. Everything works fine in singleplayer. Note that.
The Minecraft Server build is modded. Note that too.

> I had a conversation with the [MineOS leading developer](https://github.com/IgorTimofeev) on that crash. He told me that it is caused by inability of Java to read and run Lua file (supposed to be GUI one), however, it is not somehow related to MineOS, he said.

Some screenshots on that issue.
![image 2019-03-07 19 09 35](https://user-images.githubusercontent.com/7927563/54024431-d5df4080-41a8-11e9-9318-69880d268bdb.jpg)
![lqw4awt6slq](https://user-images.githubusercontent.com/7927563/54024440-db3c8b00-41a8-11e9-856d-ac27ddc145fc.jpg)

**Comment by IgorTimofeev** [comment]
Note: this error occurs when trying to load("string file contents"). I.e. load() returns nil and "java.lang.NullPointerException"

**Comment by gvsem** [comment]
A solution has been found. Config file has been changed this way:
**lua: allowBytecode=true** (false originally).
It is not safe, however, I strongly recommend to explain this config param more carefully in documentation to avoid such server errors.

Error is no longer produced. You can have this thread closed.

**Comment by theohuguet01** [comment]
hello me I can not install mineos on opencomputer on a moderated server and a solo world how to solve this problem

**Comment by pivinx1** [comment]
Do you have enough space? Do you have enough RAM? I mean here in your OC
computer, not the server.

pt., 1 sty 2021 o 01:13 theohuguet <notifications@github.com> napisał(a):

**Comment by theohuguet01** [comment]
I put everything in opencomputer

**Comment by pivinx1** [comment]
I mean what parts, everything doesn't really tell me much

pt., 1 sty 2021, 16:44 użytkownik theohuguet <notifications@github.com>
napisał:

**Comment by theohuguet01** [comment]
I put in processor, hard drive, tier 3 graphics card and two tier 3.5 ram modules and a network card

**Comment by pivinx1** [comment]
You should put in an network card instead.

niedz., 3 sty 2021, 09:03: theohuguet <notifications@github.com> napisał(a):

**Comment by theohuguet** [comment]
I put in processor, hard drive, tier 3 graphics card and two tier 3.5 ram modules and a network card

**Comment by theohuguet01** [comment]
I tried and it still doesn't work
