### ISSUE TITLE
Geolyzer Distance doc/impl Discrepancy

### ISSUE THREAD

**Issue by Nopey** [MightyPirates/OpenComputers#3064]
The geolyzer's config is incorrect about the meaning of 'geolyzerNoise', as the actual code uses euclidean distance in all 3 dimensions, whereas the config says distance is only along the vertical axis. As well, the config option is only three fifths of the maximum noise, as the noise normalization assumes distance peaks at 33, not 55 or 57 (the diagonal)
The distance is calculated as such:
https://github.com/MightyPirates/OpenComputers/blob/cca7f202d5040156bf93a0ef687fd6447fbfd07d/src/main/scala/li/cil/oc/integration/vanilla/EventHandlerVanilla.scala#L43
The noise is normalized by dividing by 33, however distance can go up to 55 or 57
https://github.com/MightyPirates/OpenComputers/blob/cca7f202d5040156bf93a0ef687fd6447fbfd07d/src/main/scala/li/cil/oc/integration/vanilla/EventHandlerVanilla.scala#L28
From the mod config file:
```
Noise increases linearly with the vertical distance
to the Geolyzer. So yes, on the same height, the returned value are of
equal 'quality', regardless of the real distance. This is a performance
trade-off.
```
Should the distance be changed to match the documentation, or the documentation to match the documentation?

**Comment by payonel** [comment]
docs are wrong, I like the code. I didn't know the docs said that, thanks for letting me know

**Comment by Nopey** [comment]
Found another, `ignoreReplaceable` is in the docs, but the code actually checks for `includeReplacable`
https://github.com/MightyPirates/OpenComputers/blob/cca7f202d5040156bf93a0ef687fd6447fbfd07d/src/main/scala/li/cil/oc/server/component/Geolyzer.scala#L97
https://github.com/MightyPirates/OpenComputers/blob/cca7f202d5040156bf93a0ef687fd6447fbfd07d/src/main/scala/li/cil/oc/server/component/Geolyzer.scala#L102

**Comment by Nopey** [comment]
I think the not halfway down the line is to handle this, but I'm not sure, as I'm having trouble reading Java/Scala after a good few years away from it.

**Comment by payonel** [comment]
i've cleaned up the conf language to more closely match what the code is doing (with regards to the geolyzer noise)

the `includeReplacable` and `ignoreReplaceable` thing is not a problem.
The docs name the field `includeReplacable` to help the user understand what it is used for
The code then reads that field via index, not name. The `ignoreReplaceable` is not a lookup key, but a key created in the code only to help code later use it by name. It is working as intended. The user need not know of this, and only use `ignoreReplaceable` as it is shown in the doc
