### ISSUE TITLE
[Script] local keywork not working

### ISSUE THREAD

**Issue by 0ddlyoko** [MightyPirates/OpenComputers#3065]
It seams that the "local" keywork doesn't work on computercraft.
I'm using OpenComputers-MC1.12.2-1.7.4.153 version.
![image](https://user-images.githubusercontent.com/11074473/54234819-2e4b7080-4510-11e9-8759-a4f7023e6efd.png)
It only works without the "local" keywork

**Comment by LizzyTrickster** [comment]
The local keyword inside the Lua prompt makes it local to that line. 
each line you run through the lua prompt gets run through `pcall()` so 
that it can show you the output and/or any errors without crashing itself.

**Comment by payonel** [comment]
test the use of `local` irl in a lua repl prompt, you'll see it behaves the same
