### ISSUE TITLE
opencomputers crash on start up

### ISSUE THREAD

**Issue by FluffyMac3** [MightyPirates/OpenComputers#3067]
https://pastebin.com/bZR96CmJ
opencomputers crash on the pre instalition

**Comment by payonel** [comment]
looks like you have an incomplete library installation from minecraft and/or forge. Perhaps you messed up your launcher? Perhaps you tried to move some files? Missing this library will cause many mods to fail to load, not just ours

Try doing a clean install of your launcher.

For reference, this is the library you seem to be missing:
 http://tool.oschina.net/uploads/apidocs/akka2.0.2/api/com/typesafe/config/ConfigMergeable.html 

you shouldn't have install this yourself, it should be installed for you by the launcher/minecraft/forge...something like that. This is not something with OC
