### ISSUE TITLE
Can't boot from floppy

### ISSUE THREAD

**Issue by LordOfSpace** [MightyPirates/OpenComputers#3070]
Hi, after my game crashed now i could no longer boot my computer from a floppy disk.
I have tried taking out all other media.

![Part 1](https://user-images.githubusercontent.com/7018779/54872407-b09e2500-4d99-11e9-9bf9-e11b30f87584.png)
![Part 2](https://user-images.githubusercontent.com/7018779/54872406-b0058e80-4d99-11e9-9ace-a2fe3f235c5c.png)

**Comment by payonel** [comment]
the error states the eeprom is missing data, or is corrupt. perhaps things are in bad state when the game crashed. consider crafting a new eeprom

**Comment by LordOfSpace** [comment]
I have I even maybe a different world same effect. But I could boot from a floppy before the crash, and now I can't. And I am getting the no bios error even with out a boot media, unlike before I crashed were I was getting a no boot media error. 
I'm going to try reinstalling the mod maybe that will fix it.

**Comment by payonel** [comment]
it is the eeprom, not the floppy
