### ISSUE TITLE
[suggestion] return empty selection box for screens when player is not sneaking

### ISSUE THREAD

**Issue by ben-mkiv** [MightyPirates/OpenComputers#3072]
actually theres a bounding box drawn when you focus on a screenblock, which doesnt look nice on multiblock screens.

at least for 1.12 theres a method in the block class which could return an empty bounding box without affecting the hitbox of the block, so it could be hidden like this

```java
static final AxisAlignedBB emptyBB = new AxisAlignedBB(0, 0, 0, 0, 0, 0);

@SideOnly(Side.CLIENT)
@Override
public @Nonnull AxisAlignedBB getSelectedBoundingBox(IBlockState state, @Nonnull World worldIn, @Nonnull BlockPos pos){
    return !Minecraft.getMinecraft().player.isSneaking() ? emptyBB : super.getSelectedBoundingBox(state, worldIn, pos);
}
```

![](https://i.imgur.com/S7dni9a.png)

**Comment by payonel** [comment]
fantastic suggestion, thank you! I've added the code
