### ISSUE TITLE
[1.12.2] [1.7.4.153] signal data loss

### ISSUE THREAD

**Issue by freznelfennec** [MightyPirates/OpenComputers#3074]
I am having issue with the latest release of OpenComputers.  I spent around 2 hours trying to figure out what I was doing wrong, until I examined the logs.  It appears that sometimes when a table is passed as an argument to computer.pushSignal(), that table is lost.  This happens seemingly at random, even with the same arguments.  Whenever a table is dropped the following message appears in the log: "[OpenComputers-Computer-1/WARN] [opencomputers]: Trying to push signal with an unsupported argument of type li.cil.repack.com.naef.jnlua.DefaultConverter$18"

**Comment by payonel** [comment]
do your tables compose anything but basic scalar types? they cannot compose threads, functions.

**Comment by freznelfennec** [comment]
No, they do not.  They are deserialized from network modem_message signals.  I have checked, and no functions are present inside the tables. It is very inconsistent, the same deserialized packet will either make it through or cause an error. Sometimes the issue will not occur at all until the computer in is restarted.  As in, some computer sessions will not experience the error at all, and other sessions experience it for every packet.  Here is output from one of the sessions with the issue present: 
![image](https://user-images.githubusercontent.com/13923468/55099911-fd824400-5096-11e9-8d30-f3ff875a6069.png)
The table printout is the serialized packet, (printed before being deserialized and passed to computer.pushSignal()) and the error is from one of the network listeners.  The packet IS checked before being passed to computer.pushSignal().

**Comment by freznelfennec** [comment]
I should add that this is not OpenOS, this is a custom OS that I am developing.

**Comment by payonel** [comment]
you're going to need to pinpoint the payload that causes, and show a repro where that specific payload fails to send

**Comment by freznelfennec** [comment]
Load this
```lua
local screen, gpu

for a,t in component.list() do
	if (t == "screen") then screen = a end
	if (t == "gpu") then gpu = component.proxy(a) end
end

if (screen and gpu) then
	gpu.bind(screen, true)
end

t = computer.uptime()
i = 0
tsttbl = {["1"] = " "}
tsttbl2 = {[1] = " "}

while true do
	gpu.set(1,1,tostring(i))
	if (computer.uptime() - t > 0.2) then
		t = computer.uptime()
		i = i + 1
		if (i % 3 == 0) then computer.pushSignal("tablesignal", tsttbl) end
		if (i % 5 == 0) then computer.pushSignal("tablesignal", tsttbl2) end
		if (i % 2 == 0) then
			local s,tbl = computer.pullSignal(0.1)
			if (s == "tablesignal") then
				gpu.set(1,2,type(tbl).."       ")
			end
		end
	end
end
```

into an init.lua file.
You will see that the array does not pass through, while the dictionary does.  A mixed table will also not pass through.
I captured the result here: https://gyazo.com/ff7e1e71ea98c44bc6610f86a81f9dab

**Comment by payonel** [comment]
and you try switching your cpu to lua 5.2?

**Comment by freznelfennec** [comment]
The cpu was already on 5.2

**Comment by payonel** [comment]
ok very good, i'll toy with this and report (it'll take a day or two at least) but thank you

**Comment by freznelfennec** [comment]
Alright, thanks!

**Comment by freznelfennec** [comment]
Any update on this?

**Comment by payonel** [comment]
our table code only allowed from strings - i made it slightly more lenient (but still not allowing nested tables)
