### ISSUE TITLE
[1.12.2, 1.7.4] Can't power my OC

### ISSUE THREAD

**Issue by LordOfSpace** [MightyPirates/OpenComputers#3075]
Is anyone else have a problem powering you OC with the EnderIO's conduits or is it just me?

If i use EnderIO's conduits i need a power converter, but it should work without a power converter

OpenComputers-MC1.12.2-1.7.4.153, EnderCore-1.12.2-0.5.52 ,EnderIO-1.12.2-5.0.43, EnderIO-endergy-1.12.2-5.0.43

**Comment by LordOfSpace** [comment]
Oh and it crating a power draw the wipes my power in 4s-10s if i don't use a power converter

**Comment by LizzyTrickster** [comment]
Got a picture of your setup?

Also, the cases/server rack can only convert a low amount of RF energy into OC's energy per tick.
The power converter can do at least 10x what a case can do so if you have a lot of things on the OC power net you will exceed the maximum for a single case

**Comment by LordOfSpace** [comment]
This is my set up with the power converter
![My OC](https://user-images.githubusercontent.com/7018779/55262790-4d067280-5245-11e9-957a-7eefd3372397.png)
![My setup part 1](https://user-images.githubusercontent.com/7018779/55262802-5b548e80-5245-11e9-9b53-666458eee940.png)
![My setup part 2](https://user-images.githubusercontent.com/7018779/55262804-60194280-5245-11e9-8bc8-dee996806823.png)
![My setup part 3](https://user-images.githubusercontent.com/7018779/55262810-64456000-5245-11e9-94c0-3090be2552ec.png)
![My setup as a hole ](https://user-images.githubusercontent.com/7018779/55262822-70c9b880-5245-11e9-8ecd-aab6fe44240a.png)
![My setup power graph](https://user-images.githubusercontent.com/7018779/55262824-74f5d600-5245-11e9-957c-daa7747ffbc1.png)
![My setup power moniter](https://user-images.githubusercontent.com/7018779/55262828-77f0c680-5245-11e9-977f-a0c82a7af558.png)
This is my hole setup

**Comment by LordOfSpace** [comment]
Am i still getting help?

**Comment by payonel** [comment]
i matched your setup and even used the same versions of the mods you listed. powers the computer just fine without power converter. should work. closing for now as no repro - if you are still having this problem and you've updated your mod versions, please recreate a minimal repro (with minimal set of mods) and upload a link to your save of the repro (you shouldn't have to include the mods, just list them and their versions)

**Comment by LordOfSpace** [comment]
Thank you for helping, re-downloaded the mods and now it works. You can keep is closed
