### ISSUE TITLE
Incompatibility with Forge Multipart and MCMultiPart (1.12.2)

### ISSUE THREAD

**Issue by Driftini** [MightyPirates/OpenComputers#3078]
Today I've tried putting more 3D Prints in one blockspace to cover some cables and it didn't work. I've installed Forge MultiPart and MCMultiPart, though the result is the same: I can only put one 3D Print per blockspace and I can't put a cable in the same blockspace a 3D Print is located in. By the way, the cable doesn't collide with any of the prints. Any ideas on how to fix this?

Minecraft version - 1.12.2
OpenComputers version - 1.7.4.153
FMP version - 2.6.1.81
MCMP version - 2.5.3

**Comment by payonel** [comment]
this isn't broken, but rather is no longer supported - the fix would be if someone from the community had the opportunity to implement it for us. sorry about that
