### ISSUE TITLE
issues with twitch

### ISSUE THREAD

**Issue by Nbgreen** [MightyPirates/OpenComputers#3079]
I'm currently working on an update for my pack tested it works great on technic. I port all the mods and configs over to twitch to get ready to update my pack on there. I go to run the game and I get this error caused by open computers.
error: https://paste.dimdev.org/temuhagoba.mccrash
forge: 1.12.2-14.23.5.2824
OC version: MC1.12.2-1.7.4.153

**Comment by payonel** [comment]
make sure you have config.jar (for example config-1.2.1.jar) this is a launcher issue, same as https://github.com/MightyPirates/OpenComputers/issues/1516
