### ISSUE TITLE
AE integration in 1.7.4

### ISSUE THREAD

**Issue by repo-alt** [MightyPirates/OpenComputers#3080]
Looks like in OpenComputers-MC1.7.10-1.7.4.1265 AE integration is broke at least with appliedenergistics2-rv3-beta-17.jar 
What I did to reproduce:
![image](https://user-images.githubusercontent.com/23512002/55649657-3c796d80-57ec-11e9-8999-0722bffe05bc.png)
![image](https://user-images.githubusercontent.com/23512002/55649677-4c914d00-57ec-11e9-8726-f2870c0f228a.png)
![image](https://user-images.githubusercontent.com/23512002/55649729-6e8acf80-57ec-11e9-9fdc-391637f1ce43.png)
Mod list:
appliedenergistics2-rv3-beta-17.jar              
AsieLib-1.7.10-0.4.8.jar                         
CodeChickenCore-1.7.10-1.0.7.47-universal.jar    
CoFHCore-[1.7.10]3.1.4-329.jar                   
CoFHLib-[1.7.10]1.2.1-185.jar                    
Computronics-1.7.10-1.6.5.jar                    
NotEnoughItems-1.7.10-1.0.5.120-universal.jar    
OpenComputers-MC1.7.10-1.7.4.1265-universal.jar

**Comment by repo-alt** [comment]
In 1.7.3 it is already broken, 1.7.2 works.
Ae2-rv3-beta-17 is essentially the same as rv3-beta-6 (and the bug reproduces with rv3-beta-6 as well)

**Comment by repo-alt** [comment]
I debugged a bit and looks like it was broken in a75992e164623ff8ab81b80559b86ba125b1ec94
when in function li.cil.oc.integration.appengNetworkControl.convert type filter
` .collect { case hash: java.util.HashMap[String, AnyRef] => hash }`
was replaced with 
` .collect { case StringAnyRefHash(hash) => hash }`

Looks like Scala did some dark magic under the hood when matching HashMap explicitly, and does not do it when matching with case class.
( Registry.convert returns an array of HashMap[AnyRef,AnyRef] )

**Comment by payonel** [comment]
yep, i broke that in 1.7.10 -- but didn't merge this mistake into 1.12
i see your PR and i'll test it, but it looks good
