### ISSUE TITLE
IC2 analyzer

### ISSUE THREAD

**Issue by salimAbdulIt** [MightyPirates/OpenComputers#3081]
Robot can use analyzer of croops from IC2 but message shows to player (robot owner).
Pls make that message shows to robot.
And add abilitty to robot that it uses analyzer inventory.

**Comment by lfreew1ndl** [comment]
Pls do it :).
It will really save a lot of my time because IC2 selection takes a lot of time.

**Comment by payonel** [comment]
use the geolyzer.analyze method to get crop data. working on ic2 analyzer would be better in a plugin to oc

**Comment by lfreew1ndl** [comment]
Could you explain more better how to get these stats 
(Growth, Gain, Resis)
![image](https://user-images.githubusercontent.com/19494059/68611659-4cb0a400-04c3-11ea-8dd0-3ab09d0c177e.png)

**Comment by payonel** [comment]
and how is your robot using that device currently?

**Comment by lfreew1ndl** [comment]
He can't use it. He can only analizy item by right click but message about crop shows to owner of robot
![image](https://user-images.githubusercontent.com/19494059/68620538-57286900-04d6-11ea-884d-109521e25919.png).
And I am asking to do some way to get this information to create robot (farmer).
I am expecting that robot can use internal storage of this item but he can't.

**Comment by payonel** [comment]
yeah this is an integration feature request between oc robots and ic2. i'll give it some more consideration, but this is best done as an addon to oc
