### ISSUE TITLE
Screen background has issues with shaders, foreground does not.

### ISSUE THREAD

**Issue by KryptonicDragon** [MightyPirates/OpenComputers#3086]
This isn't game-breaking or anything, but it is pretty disappointing for anyone who uses shaders and wants to have something on display with a screen.

When using shaders with Optifine, the background part of a screen will render in very glitchy manners, while the foreground part of a screen renders just fine.
I have a video showing this effect [here.](https://drive.google.com/file/d/1LprYkFfxud5J8HTEW615TIJN_Cusonmy/view?usp=drivesdk)

In the testing program I used, the screen is first filled with spaces, using a background color. You can see the glitchy rendering there.
After 7 seconds, the screen is filled with the letter F, using a foreground color and a black background color. You can see this renders just fine, as expected.
And finally, after 7 more seconds, the screen is filled with F again, but with the same foreground and background color. The background part continues to render incorrectly, while the foreground renders normally.

The issue is present with every shader I tried, SEUS (in the video), Chocapic, KUDA, and MrMeepz.
Minecraft version 1.12.2, and the only mods loaded are OpenComputers (version 1.7.4.153), and Optifine (version 1.12.2 HD U E3). Using Forge version 14.23.5.2821, though I have tested the issue to be present on Forge version 14.23.5.2836 as well. Optifine reports OpenGL version 4.6.0, and Nvidia driver version 425.31.

Hope I gave enough information to help!

**Comment by payonel** [comment]
it would be nice if this was improved/fixed -- you've provided great testing info about the issue, but I should also point out that we dont have plans to fix this ourselves. I do appreciate you pointing this out, perhaps someone will PR this work later. Note that the last round we had looking at improving our rendering code had serious performance penalties for users without graphics cards.

**Comment by Alivebyte** [comment]
It's kinda weird the issue is still in place
