### ISSUE TITLE
Suggestion: Increase RAM size

### ISSUE THREAD

**Issue by valerierx** [MightyPirates/OpenComputers#3087]
#1698 
I tweaked the config and  tested computers with 16 mb RAM and it worked perfectly, on a GUI system, which is laggy when runned with default config. 

My system: 8 GB DDR3, NVIDIA GT 710 2GB DDR5, Linux Mint 19.1.
Java memory allocation: 1024 MB

**Comment by skyem123** [comment]
Out of curiosity, which GUI software are you using?

**Comment by valerierx** [comment]
MineOS

**Comment by payonel** [comment]
our default ram settings are by design (they provide a low cost to server admins). if you want to run software that requires significantly more ram, adjust your configs as you see fit, otherwise, reduce/optimize the software you are running
