### ISSUE TITLE
unscii font contains three glyph errors

### ISSUE THREAD

**Issue by Alaisx** [MightyPirates/OpenComputers#3089]
The unscii font used for unicode rendering in OC contains three incorrect glyphs within the box drawing set. The characters are U+2559, U+255C, and U+2568 (bottom row of the below 3x3 glyph example). The bottom middle glyph is obviously out of place, and the bottom left and right  glyphs have horizontal bars one pixel too high when connecting to other characters. I believe the hex for them should be as follows:
```
2559:6C6C6C6C6C6C6C7F7F00000000000000
255C:6C6C6C6C6C6C6CFCFC00000000000000
2568:6C6C6C6C6C6C6CFFFF00000000000000
```
Regular font example of how the glyphs should look:
╓╥╖
╟╫╢
╙╨╜
Image showing the errors rendered using the TTF font in excel:
![unscii errors](https://user-images.githubusercontent.com/13923969/56874155-42cac600-69f5-11e9-8d55-2d279698cf31.PNG)

I made a modified font.hex file which fixes the issue, with the extension to .txt in order to upload it here:
[font.txt](https://github.com/MightyPirates/OpenComputers/files/3125813/font.txt)

The errors exist in the font itself, not just the OC implementation, so I have also reported it to the unscii creator.

**Comment by payonel** [comment]
1. we use font hex built from https://git.asie.pl/asie/funscii - if there is an error/mistake in the font hex, please report it there
2. if you would like to suggest a correction to the mod, make a PR, not attach a fix to a github issue

**Comment by Alaisx** [comment]
Thanks for letting me know the correct procedure. I've never actually made a pull request before but I will look into how to do it. I will also report the issue over at funscii.

**Comment by payonel** [comment]
we'll review funscii updates when/if they occur
