### ISSUE TITLE
Crash when the server rack is turned on

### ISSUE THREAD

**Issue by Heedroot** [MightyPirates/OpenComputers#3091]
I play on my server with friends, and we decided to create a server rack. But when turned on, its server crashes. Correct this bug in the new version. Since I want to sit on it. I started playing the last version, but there is a bug that was corrected in this version ...

**Comment by Heedroot** [comment]
If I play for version 1.7.10

**Comment by payonel** [comment]
i cannot repro, server racks do not crash for me. please give the full version name you are using that crashes, and consider using our latest dev builds: https://ci.cil.li

**Comment by payonel** [comment]
ok i've been playing around with different configurations, there is more to this story than it seems. i'll continue to investigate
