### ISSUE TITLE
Bug with rack network

### ISSUE THREAD

**Issue by GalacticArc** [MightyPirates/OpenComputers#3095]
The bug is that racks are only able to receive 4 network events a second, where as a normal computer is able to receive a lot more. 

Scripts used in bug: https://pastebin.com/i4wEhb4k

OC version: OpenComputers-MC1.12.2-1.7.4.153

How to repro:
 - Create 3 separate computers connected via relays, 2 rack computers in their own rack, and a regular computer, Example: https://i.imgur.com/b7fqzlq.png
 - Setup the receive part of the script on 1 rack, and the regular computer, and run it.
 - Setup the send part of the script on the other rack, and run it.
 - Should send a close number on the regular computer being recieved as the sender
 - The receiving rack will only have 4/s

Demo video: https://www.youtube.com/watch?v=TBNMuuNCrvk

**Comment by payonel** [comment]
very nice details, which made it easy for me to resolve the issue

I recommend you rewatch your video carefully between 2:01 and 2:07

first relay
![image](https://user-images.githubusercontent.com/6590223/59075502-cb0a7980-8885-11e9-8560-42dad10e3b7b.png)

second relay
![image](https://user-images.githubusercontent.com/6590223/59076150-736e0d00-8889-11e9-8c83-ee5a2499c0a6.png)

third relay
![image](https://user-images.githubusercontent.com/6590223/59076169-8385ec80-8889-11e9-8042-60ad1ea5a094.png)

If you notice, your first and third relay don't have drives in them, and that'll limit their ability to transfer packets. That is why you see 4p/s. I suspect you had a drive in the third relay at some point that allowed the regular case to get a burst of packets raising its count to 18 or so

Put a drive, cpu, and memory in your relays, they'll transfer more packets

**Comment by payonel** [comment]
![image](https://user-images.githubusercontent.com/6590223/59077368-33118d80-888f-11e9-80fa-af26e3d857d2.png)

**Comment by payonel** [comment]
there is more to this issue than it seems. I'm testing configurations and finding unexpected behaviors. I'll continue to investigate

**Comment by payonel** [comment]
@GalacticArc please try out our dev build, you should see a network improvement when using servers now

https://ci.cil.li/

**Comment by GalacticArc** [comment]
I have tested build 1.12.2-1.7.4.164 and it appears to have the issue fixed, thank you!

**Comment by GalacticArc** [comment]
Going to reopen this issue, racks and modem messages appear to be broken again

Version OpenComputers-MC1.12.2-1.7.5.217
(Also tried version 192)

Reproduction steps:

1. Setup 3 computers, 1 as a rack.
2. Put the sending script posted below on one of the normal computers
3. Put the receiving script posted below on both the rack and the other normal computer
4. Check the modem_messages being received and see that the rack computer does not receive modem_message events despite being connected

Image of setup:
![image](https://user-images.githubusercontent.com/5256221/142946256-4ffbbed7-3f71-44e0-adc5-4f9e9c076653.png)

Image of scripts running
![image](https://user-images.githubusercontent.com/5256221/142946889-8db6167f-5497-41af-9a43-ad6b642a2639.png)

Addon mods:
- OpenGlasses-MC1.12.2-2.2-53
- openscreens-1.12.2-1.0.1
- OpenSecurity-1.12.2-1.0-83
- ocbookconv-0.1
- OpenPrinter-1.12.2-0.1.0.15

Receiving script:
```lua
local component = require("component")
local computer = require("computer")
local event = require("event")
local args = {...}
local m = component.modem
local num = 0
local term = require("term")
local gpu = component.gpu
local xs,ys = term.getViewport()
m.open(1)
gpu.fill(1, 1, xs, ys, " ")
local lastupdate = computer.uptime()
local frametime = 5
while true do
  local ev, _, from, port, _, message = event.pull(0.1)
  if ev == "modem_message" then
    num=num+1
  end
  if computer.uptime() - lastupdate >= frametime then
    lastupdate = computer.uptime()
    gpu.fill(1, 1, xs, 1, " ")
    gpu.set(1,1, "Receiver")
    gpu.set(1,2,"Packets/s: ".. (num/frametime) .. string.rep(" ",5))
    gpu.set(1,3,"Uptime: ".. computer.uptime() .. string.rep(" ",5))
    num = 0
  end
end
```

Sending script:
```lua
local component = require("component")
local computer = require("computer")
local args = {...}
local m = component.modem
local num = 0
local term = require("term")
local gpu = component.gpu
local xs,ys = term.getViewport()
m.open(1)
gpu.fill(1, 1, xs, ys, " ")
local lastupdate = computer.uptime()
local frametime = 2

while true do
	for i=1,50 do
	  m.broadcast(1, "PING!")
	  num=num+1
	end
  if computer.uptime() - lastupdate >= frametime then
    lastupdate = computer.uptime()
    gpu.fill(1, 1, xs, 1, " ")
    gpu.set(1,1, "Sender")
    gpu.set(1,2,"Packets/s: ".. (num/frametime) .. string.rep(" ",5))
    gpu.set(1,3,"Uptime: ".. computer.uptime() .. string.rep(" ",5))
    num = 0
  end
	os.sleep()
end
```
