### ISSUE TITLE
[Bug] WakeUp message on microcontrollers

### ISSUE THREAD

**Issue by DOOBW** [MightyPirates/OpenComputers#3096]
The microcontroller does not wake up if it receives a message from another microcontroller. All other devices work fine.

`local modem = component.proxy(component.list('modem')())
modem.broadcast(1, 'PING')
computer.pullSignal(0.5)
modem.setWakeMessage('PING')`

**Comment by payonel** [comment]
works for me :/

code on uC A
```
local c = component or require("component")
local m = assert(c.proxy(c.list("modem")()))
local x = computer or require("computer")

m.setWakeMessage("PING")

while true do
  x.pullSignal(1)
end
```

code on uC B
```
local c = component or require("component")
local m = assert(c.proxy(c.list("modem")()))

m.broadcast(1,"PING")
```
