### ISSUE TITLE
Vertical black lines render error

### ISSUE THREAD

**Issue by Alaisx** [MightyPirates/OpenComputers#3097]
When filling the screen with solid block characters, black vertical lines appear where the whole screen should be solid colour. The lines are spaced at even intervals, and the number of lines changes if the Minecraft window is resized. I have attached a couple of examples with different window sizes. 

The lines do not appear on the face of the screen blocks rendered in the world, just on the pop-up screen that appears when interacting with the computer via keyboard.

![lines1](https://user-images.githubusercontent.com/13923969/57564773-01300880-736f-11e9-9687-2eed5b1817f5.PNG)

![lines2](https://user-images.githubusercontent.com/13923969/57564774-02613580-736f-11e9-9ae5-d62f5736bfcf.PNG)

**Comment by UV-Husky** [comment]
Try setting Minecraft UI scaling to something other than "Auto". This is most likely a scaling issue, but just a guess.

**Comment by Alaisx** [comment]
You're right, the problem does go away when setting UI scale to something that forces the OC screen UI to be smaller than the minecraft window. Thanks for the workaround. It would be nice though if I could use large or auto UI scale with OC because my setup is to play minecraft on a TV, so the screen is further away than a normal monitor and normal UI scale is hard to read. 

 Maybe if the automatic scaling of the OC screen window was locked to increments that don't cause this issue? There are definitely large scale increments that work fine.

**Comment by skyem123** [comment]
I've always noticed that scaling has been a bit weird.

**Comment by payonel** [comment]
yeah, leaving this as won't fix
