### ISSUE TITLE
Lua lambda syntactic sugar

### ISSUE THREAD

**Issue by Fictitious-Rotor** [MightyPirates/OpenComputers#3105]
Stock lua comes with rather wordy anonymous functions.
`someFunction(function(a, b) return a + b end)`
All of the above keywords could safely be made implicit.

Lua seems to have a variety of solutions involving dodgy code generation, C patches and lua libraries, [all of which can be found here:](http://lua-users.org/wiki/ShortAnonymousFunctions)

One that stands out for me is the [MetaLua](http://lua-users.org/lists/lua-l/2009-10/msg00496.html) patch, which 
> provides a syntax `|x,y| x*y` for `function(x,y) return x*y end`.

In the end, none of this matters that much. Lua is already a nice language to use and tampering with it may lead to undesired side effects, but, if it isn't desirable, would it be possible to expose an interface for end users to make their own patches?

Thanks

**Comment by payonel** [comment]
yep, as an addon mod you can define your own machine Architecture, which you can base on our native lua arch. you could also add an interpreter layer in `load()` and replace syntax in a custom os (or personal modification of openos)
