### ISSUE TITLE
screen not refreshing

### ISSUE THREAD

**Issue by venomzz** [MightyPirates/OpenComputers#3107]
im running OpenComputers-MC1.12.2-1.7.4.153,im connecting a program to a draconic reactor,the screen ui doesnt update,i have to click on the screen to see it update or refresh the info to be shown,if i dont spam click on it,it stays frozen

im using https://forum.craftersland.net/topic/22059-open-computers-program-for-draconic-reactor-direwolf20-mc1102/ for my reactor,it did work along time ago on 1.12.2 but now with the latest draconic and opencomputers mod the screen freezes on the computer ingame

im using:
OpenComputers-MC1.12.2-1.7.4.153
Draconic-Evolution-1.12.2-2.3.20.333-universal

**Comment by payonel** [comment]
this is fixed in (the not released) 1.7.5, but you can patch openos manually, read this comment i left in the forums: https://oc.cil.li/topic/918-big-reactors-grid-control/page/33/?tab=comments#comment-8907
