### ISSUE TITLE
About version 1.14.2 update

### ISSUE THREAD

**Issue by UmutAlihan** [MightyPirates/OpenComputers#3109]
Hi,

First of all thank you very much for such huge and great contribution to the community!

I am admin of a forge server on MC 1.14.2 and would like to install this great mod. Any plans for 1.14.2 update?

**Comment by payonel** [comment]
not in the near term, feel free to join our conversations on irc chat room #oc on esper.net (or via discord https://discord.gg/bYqKv7h )
