### ISSUE TITLE
Internet card HTTP improvements

### ISSUE THREAD

**Issue by kchanakira** [MightyPirates/OpenComputers#3110]
Hey, it's me again. I've been working on a project that does a lot of communication over HTTP and noticed a few things that would make it easier.

1. I noticed that when a request returns a redirect from an HTTP address to an HTTPS one, the request fails silently. It turns out that this is [intended behavior in HTTPUrlConnection](https://stackoverflow.com/questions/1884230/urlconnection-doesnt-follow-redirect) thanks to some [security concerns](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4620571). I understand what they were going for, but this makes it pointlessly annoying in regular use cases. Lots of sites have automatic HTTPS redirection, but they expect devs to deal with this themselves instead of adding a toggle option for it... Rant aside, it would be awesome if the internet card allowed us to either bypass, or control this behavior from lua.
2. ~~Access to the status code of HTTP responses.~~
3. ~~Access to the response message from unsuccessful requests. Right now the default behavior is to throw a lua error, but the response message can sometimes have some important information.~~
4. ~~Support for downloading binary data. #21 requested the same feature, but it's been a while since that has been closed so I thought it would be good to bring it up again.~~

I think request numbers 2, 3, and maybe 4 could be resolved by the internet card offering another request method (for backwards compatibility) that returns a table instead of a simple string. That would give lua coders easy access to all the information about the request/response they need, and allow for better error handling than just using pcall or xcall.

There's a lot going on in this issue so I'll try coming up with an implementation to take the load off of you guys.

**Comment by kchanakira** [comment]
Forgot to finish writing the title.

**Comment by Fingercomp** [comment]
One can get the status code by calling the `response` method on the response object, I believe:

```lua
local inet = require("component").internet

local response = inet.request(...)
local statusCode, message, headers = response.response()
print(statusCode, message)
-- for example:
--> 200     "OK"
```

Also, the internet card already returns binary chunks. I don't think I've ever had any problems receiving binary data in my programs.

**Comment by kchanakira** [comment]
Oh? That saves a lot of time then. Thanks!

I'm not sure why I was having trouble downloading an image, but that's probably because I'm bad. I'll look into that some more.

I guess the only things missing is following cross protocol redirects then right?

**Comment by payonel** [comment]
I'll look at adding the redirect info to the error response

**Comment by payonel** [comment]
i verified that the `r.response()` gives the 301 and `Location` specifics for http -> https data you need
