### ISSUE TITLE
[SUGGESTION] Block Rotator Upgrade

### ISSUE THREAD

**Issue by Shazuli** [MightyPirates/OpenComputers#3112]
An Upgrade for Robots and Drones to allow them to rotate a block they are facing/are next to. Most likely a Tier 2 Upgrade.

```
getRotation(direction: int):string
```
Gets the orientation of the block as if a player placed it: `north`, `east`, `south`, `west`, `up`, `down`.
If the block doesn't have a general direction it will return `None`.

```
rotate(direction: int, blockDirection: string):boolean
```
Rotates the block by the value of the side of `direction` to the orientation of `blockDirection`. Returns `true` on success and `false` if there is no block or the block doesn't have a orientation with a error saying it can't rotate it.

```lua
local block_rotator = require("component").block_rotator

block_rotator.rotate(3,"down")
```

**Comment by payonel** [comment]
i recommend building an OC addon :)
