### ISSUE TITLE
[1.7.4.153] Placing Screen causes server to crash and hang indefinitely

### ISSUE THREAD

**Issue by shortybsd** [MightyPirates/OpenComputers#3114]
MC v1.12.2
Forge 2837
OpenComputers vMC1.12.2-1.7.4.153
Environment: Multiplayer with Dedicated Server

Error Log: [https://pastebin.com/7Cx3YPei](https://pastebin.com/7Cx3YPei)
Full Error Log: [ https://www.dropbox.com/s/ig4gqdc1agekckf/crash-2019-06-25_19.31.02-server.txt?dl=0]( https://www.dropbox.com/s/ig4gqdc1agekckf/crash-2019-06-25_19.31.02-server.txt?dl=0)
Placing a screen immediately crashes server and causes the server to hang indefinitely.
Single player I cannot replicate this problem.

After restarting server it just crashes from then on with the following error:
Error Log after restarting server: [https://pastebin.com/yhTKXgee](https://pastebin.com/yhTKXgee)

**Comment by payonel** [comment]
i think it is because you have channels on AE disables, i think this same issue is fixed in our dev build: 
https://ci.cil.li/job/OpenComputers-MC1.12
just take latest, if I'm correct, we've had this fixed in dev builds for some time

**Comment by shortybsd** [comment]
Thank you! Nothing in AE2 is disabled far as channels and all the OC compatibility is all set to either true or auto. I'll try the dev version. This is a MP issue and doesn't exist in single player. 

**Update**: Works like a charm! Thank you again. Please push this to release. This is probably the reason most popular packs disable or ban OC completely on other servers.
