### ISSUE TITLE
Fluid Dupe and not pass event

### ISSUE THREAD

**Issue by Artmoneyse** [MightyPirates/OpenComputers#3116]
Tested on OpenComputers-MC1.7.10-1.7.4.1277
Not fixed:
https://github.com/MightyPirates/OpenComputers/issues/3051

`--1 slot: liquid storage tank, empty Fluid cell (ic2) or empty bucket. Best suited drum (Extra utilites)
--2 slot: item sample fluid for dupe. Fluid cell or bucket of liquid

local r = require('robot')
local c = require('component')
local tc = c.tank_controller
local lv = 255000 -- Extra utilites drum storage in mB

if not tc.getTankLevelInSlot(1) and tc.getTankLevelInSlot(2)>1 then
  r.select(2)
  tc.drain(1000)
  r.select(1)
  tc.fill()
  repeat
    tc.drain(1)
    r.fill()
    r.drain()
    tc.fill()
    os.sleep(0)
  until tc.getTankLevelInSlot(1) >= lv
end`

**Comment by Artmoneyse** [comment]
FluidUtils not pass event on fill\drain.
Robots can spread liquid everywhere.

**Comment by lfreew1ndl** [comment]
I think this bug about : if you spread 0.001 bucket of fluid you will place block of that fluid then you can get it and you will have 1 bucket
And also this bug works with transposers

**Comment by payonel** [comment]
i have found some oddities with getting tank info that i would like to fix, but meanwhile I cannot repro this issue

can you repro with buckets only?
can you make a gif/video demonstrating the dup?

thanks

**Comment by Artmoneyse** [comment]
[https://youtu.be/HQtI38PJjaM](https://youtu.be/HQtI38PJjaM)


Not Fixed on 1.7.10 
https://github.com/MightyPirates/OpenComputers/issues/3051

**Comment by payonel** [comment]
i have this fixed now
now, `fill()` will return `false, "incompatible or no fluid"` if you try this
