### ISSUE TITLE
Cables dont work on long distances

### ISSUE THREAD

**Issue by jasiekk913** [MightyPirates/OpenComputers#3117]
Hi,

Today i have built on my server 2 computers connected with one relay and cable (over 250m long). When I started my program at first computer and went to second computer it didn't work, but when my friend was near 1st computer (without touching) it worked again...

Quick picture: 
![opencomputers problem](https://user-images.githubusercontent.com/52331939/60365939-71135480-99ea-11e9-9e73-c5b2eba45375.png)

Thanks,
jasiekk913

**Comment by LordFokas** [comment]
Computers don't run if they're in an unloaded chunk. Use a chunkloader.
Only the computer needs to be loaded, even if the cable runs through unloaded chunks as long as the computers are in loaded ones everything should work just fine.

**Comment by jasiekk913** [comment]
First - thanks for quick answer :). Do i need to "render" relay's too?

Cheers,
jasiekk913

**Comment by payonel** [comment]
rendering has no effect, this should be a chunk load issue only

**Comment by jasiekk913** [comment]
> rendering has no effect, this should be a chunk load issue only

But does relay need to be on loaded chunk to work?

Cheers,
jasiekk913

**Comment by payonel** [comment]
yes, every block that is necessary for your system needs to be in loaded chunks. including relays

**Comment by jasiekk913** [comment]
> yes, every block that is necessary for your system needs to be in loaded chunks. including relays

REALLY Last question to you because you are developer, cables don't need to be in loaded chunks?

Cheers,
jasiekk913

**Comment by payonel** [comment]
cables DO need to be loaded

**Comment by LordFokas** [comment]
Wait cables need to be loaded? Is this a recent thing? Have I been lied to my entire life? :o
