### ISSUE TITLE
Wireless Network Card manual entry does not exist

### ISSUE THREAD

**Issue by AutumnalModding** [MightyPirates/OpenComputers#3119]

**Comment by payonel** [comment]
~can you explain:~
~1. what are you trying to do~
~2. what is the expected outcome~
~3. what is the actual outcome~

also always include OC version and MC version

**Comment by payonel** [comment]
With help from some community members, I believe that I now understand what you were asking, sorry. I completely misread what you meant by the title. I believe you are saying the is no document in our in-game manual about the wireless card

note, that is also good in a bug report to include the version, please add that

**Comment by DoubleHypercube** [comment]
Yes, that is correct. In future bug reports I will include those fields (have never written many bug reports)

**Comment by asiekierka** [comment]
There *is* a wireless network in-game manual, though... what's this ticket about?

**Comment by payonel** [comment]
there is an entry for the legacy wlan card, but now there are 2 tiers. i think (it's been a long time). maybe the request was about having info about the 2 tiers

**Comment by asiekierka** [comment]
Looking at the commit history, I think it was related to https://github.com/MightyPirates/OpenComputers/commit/8e69c06f52036fdb2d135425d23e8ecd67399d4c

Tier two documentation already exists, the above was fixed, so - closing.
