### ISSUE TITLE
Problematic Frame Crash with Remote Terminals

### ISSUE THREAD

**Issue by TorakWolf** [MightyPirates/OpenComputers#312]
When I try to bind one Remote Terminal to one server, I got that error:

http://pastebin.com/Djz845VK

**Comment by fnuecke** [comment]
Which build of OC did this happen with?

**Comment by TorakWolf** [comment]
1.6.4-1.3.0.415 dev. I will test the 416 anyways.

**Comment by TorakWolf** [comment]
The dev tag is just for state, I use universal, not deobfuscation ( what should probably crash on game loading anyways )

**Comment by TorakWolf** [comment]
Tested 418... Same issue: http://pastebin.com/jZkmh3Mi

**Comment by fnuecke** [comment]
All right, thanks! Let's continue this in #321, since that seems to be the same thing, but you posted more info there already.
