### ISSUE TITLE
Wireless networking does not work between Servers in the same Rack

### ISSUE THREAD

**Issue by krs013** [MightyPirates/OpenComputers#3124]
OC v. 1.7.4.153
MC v. 1.12.2

Setup: Two Tier 3 servers in a rack with wireless network cards in each. The rack's I/O matrix was configured so that the network interfaces shared a common side of the rack, and the servers output to different sides each. The networking tools were installed from the Network floppy. Hostnames were given to each server.

Test: We tested communication between the servers by using `ping` with their respective hostnames and also by broadcasting messages on port 1 from one server and printing all events on the other. Both tests failed, and no packets seemed to be transmitted between the servers. 

Possible causes: The fact that both the sender and receiver have the same physical location likely derails the wireless network logic. It may be that the current network tree is not equipped to handle colocated endpoints, but I haven't seen that part of the code. I did notice that in `WirelessNetwork:isUnobstructed()` there is a variable `gap` that is the distance between the endpoints minus one. If the distance is zero then `gap` will be negative, though it doesn't look like that will do anything unexpected in that function at least, so maybe that's not it.

Workaround: For now we've instead put normal network cards in each server and let their wireless communication go through an attached relay block with a single wireless card, and everything works as expected.

This is our first day seriously using OC so sorry if we're just using things wrong. It's been really fun so far, even with the head scratching, so thanks!

**Comment by payonel** [comment]
tested, works just fine (no repro)
make sure you open the port, e.g. `modem.open(1)`, on the receiving end
try our latest dev builds, there have been various fixes for networking with the cases: https://ci.cil.li/
