### ISSUE TITLE
Add a simple way to share files between saves

### ISSUE THREAD

**Issue by AR2000AR** [MightyPirates/OpenComputers#3126]
I often find myself having to make a copie of my programes between minecraft save.
OPPM is a good solution but it can be long to setup and you need a internet connexion.
Something like the **Typesetting Table** from bibliocraft could be nice. It could be attached like a component and be seen in the filesystem or be used to copie floppy disk.

**Comment by ben-mkiv** [comment]
you can use pastebin put/get to upload/download from pastebin

**Comment by payonel** [comment]
the floppy disk is sufficient as a core feature for sharing programs between machines
