### ISSUE TITLE
Rebound "paste clipboard" shortcut types "v" when used

### ISSUE THREAD

**Issue by drewcassidy** [MightyPirates/OpenComputers#3128]
I rebound the "paste clipboard" shortcut from insert to command-V since I don't have an insert key, and when used types the letter V before the clipboard is inserted. Ended up binding it to right-ctrl instead. Not sure if this bug is mac-specific.

example: copy "foo", and when pasting in the computer it ends up as "vfoo"

**Comment by payonel** [comment]
rebinding is to a single key, not a key combination. our emulation sends all key strokes, except the single bound one for pasting. sorry that caused some confusion
