### ISSUE TITLE
Can't type on tablet

### ISSUE THREAD

**Issue by shadoxxhd** [MightyPirates/OpenComputers#3133]
When right-clicking with the tablet item, openOS boots normally, but the command prompt doesn't react to any keystrokes (esc still closes the interface). This happens with or without dimension changes.

I'm playing Enigmatica 2 Expert in single player.

**Comment by payonel** [comment]
sometimes you have to open the tablet a couple of times for it to respond. btw, did you craft it with a keyboard?

**Comment by shadoxxhd** [comment]
A _tablet_ needs a _keyboard_?!

**Comment by shadoxxhd** [comment]
Do I need to somehow insert the keyboard while assembling? I can't craft tablet and keyboard together.

**Comment by payonel** [comment]
yep, needs a keyboard
