### ISSUE TITLE
Any computer can be shutdowned via packet hack

### ISSUE THREAD

**Issue by Sirse** [MightyPirates/OpenComputers#3135]
Any computer can be shutdowned via packet hack. Usage example: https://github.com/N1nt4nd0/Xenobyte/blob/master/src/main/java/forgefuck/team/xenobyte/module/MODS/OCShutDown.java

**Comment by payonel** [comment]
yeah, we're not going to block from attacks like this. we're not trying to be griefer proof. if people join your world that are causing disruption to other players, sounds like a server issue, regardless of which mods they are trying to interfere with
