### ISSUE TITLE
[Hack] ShutDown Computer

### ISSUE THREAD

**Issue by Artmoneyse** [MightyPirates/OpenComputers#3136]
https://github.com/N1nt4nd0/Xenobyte/blob/master/src/main/java/forgefuck/team/xenobyte/module/MODS/OCShutDown.java

`    private boolean shutDownPacket(TileEntity comp) {
        try {
            if (Class.forName("li.cil.oc.common.tileentity.Case").isInstance(comp)) {
                Class.forName("li.cil.oc.client.PacketSender$").getMethod("sendComputerPower", Class.forName("li.cil.oc.common.tileentity.traits.Computer"), boolean.class).invoke(Class.forName("li.cil.oc.client.PacketSender$").getField("MODULE$").get(null), comp, state);
                return true;
            } else if (Class.forName("li.cil.oc.common.tileentity.Rack").isInstance(comp)) {
                for (int rack = 0; rack <= 3; rack ++) {
                    Class.forName("li.cil.oc.client.PacketSender$").getMethod("sendServerPower", Class.forName("li.cil.oc.common.tileentity.Rack"), int.class, boolean.class).invoke(Class.forName("li.cil.oc.client.PacketSender$").getField("MODULE$").get(null), comp, rack, state);
                }
                return true;
            }
        } catch(Exception e) {}
        return false;
    }`

**Comment by LizzyTrickster** [comment]
This looks to be somewhat a duplicate of #3135
