### ISSUE TITLE
Server crash on start since I placed the adaptater

### ISSUE THREAD

**Issue by Mugiwaxar** [MightyPirates/OpenComputers#3137]
Hello
My server crash since I placed the adaptarer, unable to start
Other things, the adapter doesn't work, I don't see the adress of the me_controler when I place the adapter next to it
Here the crash:
[PasteBin](https://pastebin.com/vUVSxiRu)

Edit:
I use OpenComputers-MC1.12.2-1.7.4.172.jar
And Ftb Revelation 3.1.0

**Comment by payonel** [comment]
is something in your pack pretending to be ic2?

**Comment by Mugiwaxar** [comment]
I have IC2 Classic

**Comment by payonel** [comment]
yeah, that's why. i'll add a check to protect from this issue

**Comment by Mugiwaxar** [comment]
OpenComputes and IC2 classic are not compatible?

Ok..., didn't know :'(
I love both mods, any way to fix that?

**Comment by payonel** [comment]
we are compatible when we fix these one-offs
the issue is that ic2 classic is not ic2. we are ic2 compat, and ic2-classic is compat when they pretend to be ic2 sufficiently

**Comment by Mugiwaxar** [comment]
> we are compatible when we fix these one-offs
> the issue is that ic2 classic is not ic2. we are ic2 compat, and ic2-classic is compat when they pretend to be ic2 sufficiently

Wow, ... What??

Then, I can do nothing exept wait


Edit:
Or, I have to switch to IC2

**Comment by payonel** [comment]
i added an exception check for this case, though I wasn't able to repro with the ic2 classic version in your report
