### ISSUE TITLE
Filesystem writing prevents pub/priv keys from working

### ISSUE THREAD

**Issue by Cyakat** [MightyPirates/OpenComputers#3139]
When ever I generate a public/private key and write it using the filesystem and I try to retrieve it, It doesn't work.

**Comment by payonel** [comment]
this bug report is lacking in almost every single way
1. what mc version
2. what oc version
3. what is a minimal repro code sample
4. what line in the code sample "fails". Then you must clarify and detail the meaning of fail. Some examples of how to detail a failure
* what exception is thrown
* does the computer shut down
* does the script hang
* does the return value not match what you expect, and what return value do you expect
* does the output not match what you expect, and what output do you expect

if you are trying to use a key for encryption/decryption, explaining the details of step 4 (above) would include in your sample repro script lines of code that include the encryption/decryption attempts, and an explanation of the expected results vs the actual results

Also, in a bug report, focus on a minimal repro. Minimal means, only include the absolute required steps in your code to reproduce the problem. If you don't know the minimal steps required to repro, then do work to determine that

**Comment by Cyakat** [comment]
Sorry I forgot to include just about everything.
The mc version is 1.12.2
The oc version is 1.7.4.153

I wrote a small program to generate key pairs and then write them to a file
The private.key file has this in it: 0A 0*†HÎ=*†HÎ='0% ³ixþg+Ì–3Ã;B¦É‹åà+ñp~^ÿïáæ•u

To reproduce use the file included and execute code in the lua console.

The key generation and writing file is this:
```lua
local fs = require("filesystem")
local comp = require("component")

d = comp.data

public,private = d.generateKeyPair(256)

pub = public.serialize()
priv = private.serialize()

file = io.open("./private.key","w")
file: write(priv)
file: close()

file = io.open("./public.key","w")
file: write(pub)
file: close()
```
To reproduce use the file above and execute the following code in the lua console.
```lua
>d = component.data
>fs = filesystem
>file = io.open("./private.key")
>size = fs.size("./private.key")
>privateKey = file: read(size)
>d.deserializeKey(privateKey, "ec-private")
```
Here is a picture of the results that it gave me. It is supposed to end up with a table. I checked that it was a private key before it was generated.
![debug stuff](https://user-images.githubusercontent.com/36944093/62678740-8aa3a680-b96f-11e9-8ed4-826d0981c239.PNG)


When I try to deserialize the key after it has been store in a file it fails.

**Comment by payonel** [comment]
thanks for the great repro info!
can you switch the cpu to lua 5.2 and try again?

**Comment by Cyakat** [comment]
The cpu was already on the 5.2 architecture. Should i try moving it to 5.3?

**Comment by payonel** [comment]
hmm. sure. i would have expected 5.2 to be more likely to work. but sure :)

**Comment by Cyakat** [comment]
Same thing happens when I ran it on the 5.3 architecture.
![debug stuff 2](https://user-images.githubusercontent.com/36944093/62815217-fb63d380-bad3-11e9-997c-bc85e0a207b3.PNG)

**Comment by payonel** [comment]
I could only partially repro your issue. a couple of things to note

1. All filesystem library methods, e.g. `filesystem.size(path)`, use absolute paths, never relative. The`io` library uses relative paths. thus, `filesystem.size("./private") is the same as fileystem.size("/private'). in your repro code you provided, i ran the code from the default dir, `"/home" and thus my `size` value was 0. Note, however, that it is fine to use `file:read("*a")` to read the entire file

2. I do not get "Invalid DER encoding, not ended". it works just fine. I can use "*a" or `67` from `filesystem.size("/home/private")`

**Comment by Cyakat** [comment]
Ok. Thank you for trying. I will try again with what you did to try and get it to work and if it does work than I will have found the issue and I can fix it.

**Comment by payonel** [comment]
closing, no update and no repro
