### ISSUE TITLE
(hardened) SHA1 on data card

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#3140]
SHA1 is used in all sorts of places:

- git
- bittorrent
- SVN (optional)
- among others

for these use-cases, it would be nice if the data card could do SHA1

**Comment by payonel** [comment]
looks like you can easily do this in lua, here is a nice MIT licensed project: https://github.com/mpeterv/sha1
maybe make an oppm project for it

**Comment by SoniEx2** [comment]
oof http://lua-users.org/lists/lua-l/2018-11/msg00114.html :(
