### ISSUE TITLE
Simple Multitouch (and real touchscreen support)

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#3142]
Would it be possible to support real touchscreen input?

Additionally, for a multitouch API, add is_multi or has_next param to event, and combine a sequence of them until false.

E.g.

```
local touch = {}
repeat
    local name, x, y, has_next = pullEvent("touch")
    table.insert(touch, {x, y})
until not has_next
```

Equivalently, an "has_next" for drag events would allow multidrag (pinch zoom?).

**Comment by payonel** [comment]
we get our mouse events from the forge's GuiScreen, which is a single mouse click event, not related  to multitouch in any way. Interesting request, but no thanks
