### ISSUE TITLE
[1.12.2] Major client lag spikes with computers

### ISSUE THREAD

**Issue by Mattmn** [MightyPirates/OpenComputers#3148]
I'm getting large lag spikes when performing any kind of work with OC computers while they're turned on.

Typing "ls ../bin" on a lua-installed computer with all tier-1 components drops the fps to 1 for about 14 seconds. Doing the same with all tier-3 components results in 0-1fps for around 12 seconds, and the computer ends with a BSOD. I get this warning in the Minecraft log:

> [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 5711ms behind, skipping 114 tick(s)

Throughout this, my memory usage ranges from 10% to 30% with no large climb in-between, and the amount allocated stays at around 77%. In Task Manager, the Java(TM) Platform SE binary app reports around 8% CPU, 2,836.3MB Memory when the OC computer's off. When running "ls ../bin", memory jumps to as high as 53%. Just holding down backspace keeps it at around 50%. There's also half-second lag spikes every 5 seconds when the computer is idle, and no lag at all when the computer is off.

I'm using MultiMC and OpenComputers-MC1.12.2-1.7.4.153 as the only mod, with Minecraft version 1.12.2 and Forge 14.23.5.2838. This was tested in a superflat world (3 layers of stone, 1 bedrock). My memory allocation is 2048MB minimum, 4096MB maximum.

I've also tested this using OpenComputers version 1.7.4.1265 on Minecraft version 1.7.10 and Forge 10.13.4.1558, under similar conditions. In this version, the tier-3 computer doesn't end with a BSOD, but still experiences significant lag spikes. I've upgraded Windows and Java to the latest version, and my graphics card driver is the latest from the manufacturer.

I suspect it's an issue just between my computer and OC. I'm able to run other mods without issue, and I believe my computer's in healthy condition.

Java: version 1.8.0_221
Java(TM) SE Runtime Environment: build 1.8.0_221-b11
Windows: Windows 10 Home
Processor: Intel Core i7-8550U CPU
RAM: 16.0 GB (15.8 GB usable)
System Type: 64-bit Operating System, x64-based processor
Display Adapter: Intel(R) UHD Graphics 620

**Comment by payonel** [comment]
you can try removing your configs, which will cause the default settings for OC to be recreated.  I can tell you right now, without more specifics of what is causing the lag spikes we're never going to be able to close this type of ticket. It is simple a matter of no repro as we dont have this reporting elsewhere.

Also, experiment with more RAM than just 4GB max.

If you exit and return to the game world, are the computers still running? If yes, good, this shows that you are running native lua libraries (which are efficient)

Closing as "no repro" (I know this may sound harsh, but honestly ,I don't have enough info to fix this. Feel free to update this ticket if you have info that might show a repro elsewhere that could be reviewed)

**Comment by payonel** [comment]
also, the BSOD occurs due to the delay in the world ticks. you probably assumed this, but thought I'd mention that

**Comment by Maximus266** [comment]
I had the same problem. I downloaded Tlauncher and all problems with open computer are gone.
Try to do same thing. :-)
