### ISSUE TITLE
type() will "table" for component functions

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#315]
Example:
type(component.gpu.getResolution) -> "table"

Despite these actually being tables, its confusing when they get used as functions.

**Comment by fnuecke** [comment]
Well, it's to allow writing `=component.gpu.getResolution` to get the docstring. And since there's no `__type` metamethod/field...

Is there a scenario where this is an actual, technical problem, and additionally checking for `getmetatable(component.gpu.getResolution).__call` won't work?
