### ISSUE TITLE
the start of the game

### ISSUE THREAD

**Issue by fallengod445** [MightyPirates/OpenComputers#3151]
im on 1,12v of minecraft and when i start my game it loads me on normal map than on the skyblock i suggest checking it out or helping me out

**Comment by payonel** [comment]
I'm not sure how this has anything to do with opencomputers
Also, your description of repro is quite insufficient. Some things to consider in the future when reporting bugs

1. what version of the mod?
2. does it repro with only OC installed and no other mod?
3. what are the minimum repro steps?
4. what launcher are you using?
5. was it working with a previous version of mc and/or oc?
6. does it repro consistently?
7. what version of OC did this problem start?
