### ISSUE TITLE
I'm not able to craft "World sensor card"

### ISSUE THREAD

**Issue by KamaroTheN7** [MightyPirates/OpenComputers#3153]
1.12.2, I have a Galacticraft mod.

**Comment by payonel** [comment]
dup of #2924

**Comment by KamaroTheN7** [comment]
Ok, I'll readed it, it's any way to get this card? Or to create custom recipe who use analyzer for egzample instead of sensor lens.

**Comment by payonel** [comment]
the support wasn't added back for 1.12
