### ISSUE TITLE
[1.12.2] Computers Broken

### ISSUE THREAD

**Issue by Multi-Coder-24** [MightyPirates/OpenComputers#3154]
I cannot open computer cases GUI to put components in or boot the computer. For ease of testing i will run only OpenComputers and the addons I have.

Data: 
Forge Version: 1.12.2-14.23.5.2838
OpenComputers version: 1.7.4.153
OpenSecurity Version: 1.0-35
OpenPrinters version: 0.1.0.7
OpenDisk Version: 0.1.0.3
Computronics Version: 1.6.6

**Comment by DDX5** [comment]
Updating to new latest version.
OpenPrinter: 0.1.0.7
OpenDisk: 0.1.0.4

**Comment by Multi-Coder-24** [comment]
Tested By Isolating Mod and addons to a separate directory and profile, there seems to be an incompatibility somewhere

**Comment by DDX5** [comment]
Looks Like A glitch on server side or client side. Sorry

**Comment by Multi-Coder-24** [comment]
Looks like AE2 is causing a collections empty error to trigger

**Comment by payonel** [comment]
update, use our dev builds: https://ci.cil.li/
this fix goes out in our next release
