### ISSUE TITLE
Make debug.getWorld().getBlockId() return string ids instead of numeric

### ISSUE THREAD

**Issue by DaComputerNerd717** [MightyPirates/OpenComputers#3157]
Wasn't sure where to put a suggestion, so I put it here

The getBlockId() function in the debug component's world object [(wiki link)](https://ocdoc.cil.li/component:debug#world_object) should return string ids (like minecraft:stone), rather than numeric ids, since vanilla commands no longer support numeric ids, and also string ids won't change but numeric ids can. 

Alternatively, a method to convert between the two could be provided, or a second function which gets the string id could be added, to avoid breaking older programs.

**Comment by payonel** [comment]
use the world's `getBlockState(x,y,z)` for this
