### ISSUE TITLE
Issue with robot.count() and robot.space()

### ISSUE THREAD

**Issue by niclukman** [MightyPirates/OpenComputers#3158]
I have a robot with 80 slots and when I'm doing robot.count() or robot.space() on empty slots from 65-80 it would always return 64 and 0 respectively

**Comment by brisingraerowing** [comment]
What MC version? And what OC version?

**Comment by payonel** [comment]
1. use inventorySize() to know the limit
2. count and space should throw an exception for out of range requests
3. make sure you are using our latest version, even from our dev builds

I've tested this on our latest version and it works as expected. this was probably fixed
