### ISSUE TITLE
debug.sendToDebugCard()

### ISSUE THREAD

**Issue by ewwhash** [MightyPirates/OpenComputers#3159]
![image](https://user-images.githubusercontent.com/28766913/65718709-c83dc980-e0ac-11e9-9024-3a7cefe4fd77.png)
forge:1.12.2-14.23.5.2838

**Comment by brisingraerowing** [comment]
Issue is on [this line](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/server/component/DebugCard.scala#L273).

EDIT: This appears to affect all supported versions.
