### ISSUE TITLE
Wireless Network coverage area not updating on block break

### ISSUE THREAD

**Issue by MyNameIsKodos** [MightyPirates/OpenComputers#316]
It's nearly 7 am, so I'll try to be as clear as I can.  I enabled the rendering of the wireless network area via the command, and noticed that as I added more computers with wireless cards, the area got bigger, however when I removed the cards and/or the computers, the area wasn't going back down.  I'm not sure how this would affect performance if at all, but I felt the need to report the behavior nonetheless.  If this is intended, feel free to close this issue.

Edit: I am using build 174 of the 1.7.2 dev versions of OC.

**Comment by fnuecke** [comment]
Thanks for reporting that bug, was quite the evil one.
