### ISSUE TITLE
Issue reading Mekanism Gas Tanks

### ISSUE THREAD

**Issue by Polarized12** [MightyPirates/OpenComputers#3160]
Hey, I've been trying to read the gas stored in an ultimate gas tank, but it keeps returning a nil value error. It shows up on the components list, along with the functions, and in the code I have the require component line at the beginning. Anything else i missed?

**Comment by payonel** [comment]
please share your mc, oc, and mekanism version
share the lua code you've tried
show the setup you're using (like a screen shot), and what components you've installed in the robot/computer

**Comment by Polarized12** [comment]
I fixed using component.ultimate_gas_tank yadda yadda but now it's outputting a table instead of a number, any way to fix that?
https://pastebin.com/3WFHnaDF - code
versions:
mekanism 9.8.1.383
OpenComputers-MC1.12.2-1.7.4.153

**Comment by payonel** [comment]
look for the value you want from the table. that component is provided as an addon to OC from mekanism (in other words, not our code)
