### ISSUE TITLE
[suggestion] Implement the mod's own ribbon redstone cables

### ISSUE THREAD

**Issue by NarigudoBR** [MightyPirates/OpenComputers#3166]
A very annoying problem is that enderIO conduits have changed their API, though making redstone conduits incompatible with OC,  there's only a few mods that are compatible(project:red for instance), but adding extra mods may be not that good(because of lag issues and even incompatibilities between mods). So, why not create your own redstone cables with your own redstone API(thus eliminating the need of a thir party mod)?

**Comment by payonel** [comment]
we're going to leave redstone ribbons, cables, to other mods. we should update our mod to interact with ender io better, once they actually have an API for this purpose. last i checked there was no endier io api for this (in 1.12)
