### ISSUE TITLE
Adapter not working (not found in component list)

### ISSUE THREAD

**Issue by torbenvanassche** [MightyPirates/OpenComputers#3167]
OC Version: 1.7.4.184 and 1.7.4.153
MC Version: 1.12.2 (ATM3-Remix pack)

Computer + adapter does not seem to be working on either version whilst connected to a chest.
https://imgur.com/a/GuVp7FJ

**Comment by payonel** [comment]
adapter are not components. the things they connect to can become components
for example, the adapter adds the AE's me interface to the network

**Comment by payonel** [comment]
also, chests are not components, try putting an inventory_controller card in the adapter, then the inventory_controller component will be available, and with it you can interact with the chest you have palced adjacent to the adapter

**Comment by torbenvanassche** [comment]
Oh. Damn... Well pebkac all the way it seems.
