### ISSUE TITLE
Crash with AE2

### ISSUE THREAD

**Issue by Multi-Coder-24** [MightyPirates/OpenComputers#3168]
Crash that I get is: java.lang.IllegalArgumentException: Collection is empty

Gist Link: https://gist.github.com/DDX5/d93bfd18cb7f608c5a5cdd6cf3d8856d

I can only guess it's AE2 as it states AE2 in the crash report

**Comment by Multi-Coder-24** [comment]
Just looking Back it seems this issue I had stumbled across A while back. I have no idea why this happened all I know is that I have tried reloading the world and even restored an old backup of when I opened this world up first time. still to no avail

**Comment by payonel** [comment]
this is fixed (i believe) in our devs builds: https://ci.cil.li/job/OpenComputers-MC1.12/
