### ISSUE TITLE
Lua /tmp should be as fast as messing about with tables, and files in it should count towards memory limit

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#3170]
this would basically allow programs to freely abuse tmpfs files as mutable strings, and is more akin to real-life tmpfs.

**Comment by payonel** [comment]
it is better to let the kernel decide how much file io to put on ram, rather than requiring ram usage, especially for a untrusted user sandbox
the speed constraints are quite reasonable for tmpfs

**Comment by SoniEx2** [comment]
what?

tmpfs should be as fast as messing about with byte buffers.

**Comment by SoniEx2** [comment]
okay I'm convinced you completely misunderstood me as usual. please reopen and ask someone else to explain it for you.
