### ISSUE TITLE
Power converter passing component and other messages

### ISSUE THREAD

**Issue by Jobox42** [MightyPirates/OpenComputers#3171]
The power converter in 1.7.10 seems to be a little bit broken
Its allowing component messages to pass through it as if it were a cable

I've tried everything thinking that it was a bug in some other mod but alas it is not
this includes testing two different versions of forge and OpenComputers in various combinations
1.7.10-Forge10.13.4.1566 and 1.7.10-Forge10.13.4.1614
OpenComputers-MC1.7.10-1.7.4.1265-universal and OpenComputers-MC1.7.10-1.7.2.1166-universal
I even tried resetting the config files

Here's the test environment:

1.7.10-Forge10.13.4.1614-1.7.10

IC2Classic+Version+1.2.1.6
OpenComputers-MC1.7.10-1.7.2.1166-universal
OptiFine_1.7.10_HD_U_D3
NotEnoughItems-1.7.10-1.0.4.107-universal
CodeChickenCore-1.7.10-1.0.6.43-universal
CodeChickenLib-1.7.10-1.1.3.136-universal

Simply hook up your power source to the power converter and connect a computer case and monitor with keyboard and start the computer
The specs of the computer don't really matter
This was tested with OpenOS and a custom OS

![2019-11-06_14 53 58](https://user-images.githubusercontent.com/32477262/68348906-47cea780-00f3-11ea-98c6-434db97f505c.png)

I also ran the network debugger on the power converter block, here's the output
[OC_network_debugger.txt](https://github.com/MightyPirates/OpenComputers/files/3817298/OC_network_debugger.txt)

I'm sorry for submitting a report for such an old version of Minecraft, ram leaking and a few other issues from other mods forced us to downgrade

**Comment by payonel** [comment]
after some thoughtful review i've decdied to not change this behavior
i do agree it shouldn't have been this way, but now it has been for a long time
you CAN use the power distributor to tx power through a network without connecting the components, considering using that as part of your setup where you want to share power and not components

(and if you are also converting power, you would just need to use both blocks [the converter and the distributor])
