### ISSUE TITLE
robot.swing ignores enchantments of the item in hand and drops nothing

### ISSUE THREAD

**Issue by DaveDevil** [MightyPirates/OpenComputers#3172]
Forge 1.12.2-14.23.5.2825
Mod version MC1.12.2-1.7.4.153

I made a tier 1 robot, it works perfectly. I made a simple program:

`while (rob.detect()) do
  rob.swing(3)
  os.sleep(1)
end`

With this the robot is able to break a block placed exactly in front of it.

I put in the robot's "hand" a Dark Steel pickaxe (enderIO) with many enchantments, in particular I have fortune 3 (vanilla) and xp boost 3 (don't know what mod exactly adds it)

Using a quartz ore, it drops 4 exp points instead of 11, and it drops none quartz items.

Obviously the pickaxe in my hands works normally.

I made this setup with refined storage's constructor, so all ores that drops XP can be mined automatically giving me exp and items that are processed by "item vacuum" and "exp vacuum" (enderIO) but the robots ignoring my pickaxe's enchantmens and dropping nothing made it completely useless...

**Comment by payonel** [comment]
i did some tests, and it appears that only the xp boost (which is from enderio) doesn't play nice

**Comment by DaveDevil** [comment]
I tried with many ores, but it drops nothing at all. Tried with xray and the drop is not visible around, I don't thing it goes to the robot's inventory because I made it without inventory upgrade

**Comment by payonel** [comment]
xp orbs? those aren't put in inventory. if the robot as the xp upgrade then the robot itself gains the xp, else the orbs are dropped in-world
anyways, i've confirmed that the xp boost is not used by the robot. right now this looks like a limitation imposed by enderio, requiring a real player use the upgrade. if my prediction is correct, then this is "by design" or basically our of our control. I'll update this ticket later

**Comment by payonel** [comment]
yep - enderio requires real players use those upgrades. our robot is not a real player

**Comment by DaveDevil** [comment]
I wasn't talking about xp orbs but items that are dropped when I broke a ore like quartz, redstone, diamonds, silicon, coal. Nothing is being dropped by the robot

**Comment by payonel** [comment]
Ok this sounds like two separate problems. Can you confirm please?
1. the upgrades are not producing extra xp orbs (4 instead of 11). This is by design, enderio blocks our robot from using the xp boost. This is why I closed the ticket

and 

2. The item drops are disappearing. I've tested this with diamon ore and redstone ore, with the dark steel pick axe, and the robot successfully stores the drops in its internal inventory. Are you saying a robot without the inventory upgrade is causing the items to be deleted? Please test in creative with the "creatix" robot (which has the inventory upgrades) and your quartz block type. This could be a problem with the quartz block you are testing with

**Comment by DaveDevil** [comment]
Yes to both. I thought it could be the same problem.

I am trying with all vanilla blocks, later I'll try in creative. And yes, the robot I'm testing with has no inventory so it's supposed to drop items on the ground, and I'm expecting to drop many of them (fortune 3 is a vanilla enchantment)

**Comment by payonel** [comment]
ok, i'll retest (when i'm home) with a robot sans inventory upgrade

**Comment by DaveDevil** [comment]
Can't test with creatix, I'm getting a strange error regarding tile entities:

`/***************************************************************************************************************************************************************************************************************/
/*                                                                                   Exception occurred during a PhaseState                                                                                    */
/***************************************************************************************************************************************************************************************************************/
/* Sponge's tracking system makes a best effort to not throw exceptions randomly                                                                                                                               */
/* but sometimes it is inevitable. In most cases, something else triggered this                                                                                                                                */
/* exception and Sponge prevented a crash by catching it. The following stacktrace                                                                                                                             */
/* can be used to help pinpoint the cause.                                                                                                                                                                     */
/***************************************************************************************************************************************************************************************************************/
/* The PhaseState having an exception: TileEntityTickPhase                                                                                                                                                     */
/* The PhaseContext:                                                                                                                                                                                           */
/*     - Owner: GCEntityPlayerMP['Playername'/33334, l='world', x=7412.37, y=77.00, z=6811.73]                                                                                                                 */
/*     - Source: RobotProxy{tileType=oc:robot, world=WorldServer{Name=world, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=7414, y=77, z=6812}, blockMetadata=0}        */
/* org.spongepowered.asm.util.PrettyPrinter@282d23ae                                                                                                                                                           */
/***************************************************************************************************************************************************************************************************************/
/* StackTrace:                                                                                                                                                                                                 */
/* java.lang.ArrayIndexOutOfBoundsException: null                                                                                                                                                              */
/*  Phases Remaining:                                                                                                                                                                                          */
/*                                                                                                                                                                                                             */
/* Minecraft : 1.12.2                                                                                                                                                                                          */
/* SpongeAPI : 7.1.0-fb496dbf0                                                                                                                                                                                 */
/* Sponge : 1.12.2-7.1.7-SNAPSHOT                                                                                                                                                                              */
/* SpongeForge : 1.12.2-2825-7.1.7-RC3774                                                                                                                                                                      */
/* Minecraft Forge : 14.23.5.2825                                                                                                                                                                              */
/***************************************************************************************************************************************************************************************************************/
`

**Comment by payonel** [comment]
@DaveDevil can you chat with me in our #oc channel, either via discord or irc

Discord: https://discord.gg/bYqKv7h
or on esper.net

**Comment by payonel** [comment]
i've confirmed that robots without inventories still suck up items, which is bad :)
