### ISSUE TITLE
Remote Terminal Hopping With More Than 1 Server

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#3174]
Basicly With Version 1.7.4.153 1.12.2 Servers Would Hop On To A Random Remote Terminal I Tested 3 in 8 Servers Would Terminal Hop Please Can You Fix This Because Im Working On A Big Server Room Also 50% Of The Time Remote Terminals/Terminal Servers Would Not Work.

**Comment by payonel** [comment]
Why Is Every Word Capitalized In This Bug Report?
also, please provide minimal repro steps, perhaps with screenshots if that helps.

**Comment by payonel** [comment]
this happens if you use a tool like world edit and copy blocks, as you are also copying hardware addresses - the remote terminal links to addresses
