### ISSUE TITLE
Tile data for stacks in inventories needs to be exposed.

### ISSUE THREAD

**Issue by DaveB63** [MightyPirates/OpenComputers#3176]
Many blocks in vanilla and many mods have common ids and are distinguished by their tile data. 
Examples: 
Overloaded Compressed Stone - on the server I play on it has id #11967. 1x compressed stone to 16x compressed stone are distinguished by the tile data, #11967/0 .. #11967/15
The tiers of slate in blood magic are similarly distinguished only by their tile data.
Botania runes, petals, dyes and many others in this pack are distinguished only by tile data, each type having a single id.

In these cases a call to getStackInSlot cannot distinguish between the different blocks. In vanilla the tile data is mostly only a visual difference - the various patterns chiselled on a block, for example - and makes no difference to crafting etc. However, in almost all mods that use it the tile data is critical for whether a block is usable in a particular recipe or multiblock structure. Being unable to see it is a huge hole in using opencomputers for automation. 

This tile data needs to be exposed to the APIs for transposers or inventory controllers to be able to tell these blocks apart

**Comment by payonel** [comment]
you can enable this in the config - `insertIdsInConverters` default is false

**Comment by DaveB63** [comment]
With respect, given that the insertIdsInConverters  option ALSO exposes other data and that resolution of a blockid to a label breaks in these many situations when it is false this is a problem. I can see many situations where a server admin or a pack developer may wish to keep this config parameter as false and not show all the data it reveals to a player.

The parameter defaults to false which "breaks stuff" - this is not an ideal default, particularly when it is in a section of the config file where the comment at its head says that changing these parameters is "not recommended" for regular use but only for debugging. Most server admins wont touch it, and stuff will be broke.

Exposing this data to the code that resolves an id into a label should be independent of this config parameter, at the very least. You should get the correct block label even when this config tag is set to false, even if the data isn't reported to the user in the table returned by getStackInSlot.

**Comment by Vexatos** [comment]
This is what OpenComputers has the [Database Upgrade](https://ocdoc.cil.li/item:database_upgrade) for. You populate the database with reference items you want to compare against, then use the [Inventory Controller](https://ocdoc.cil.li/component:inventory_controller)'s `compareToDatabase` function to match items with higher precision, respecting item data. The [database component](https://ocdoc.cil.li/component:database) makes it trivial to generate copies and more; you can even compare items across the network using the hash function! If you want to, you can automate the whole population process by, for example, having a robot with a removable upgrade slot facing a chest, you fill the chest with items you want in the database, turn on the robot, and it will store everything in the chest on the database, you remove the database and put it wherever it is needed. Once again, the [Inventory Controller](https://ocdoc.cil.li/component:inventory_controller) is useful for this, using `store` and `storeInternal`, as well as the [Geolyzer](https://ocdoc.cil.li/component:geolyzer).
