### ISSUE TITLE
Computers wouldn't start on MP Server, will in sp

### ISSUE THREAD

**Issue by ROMVoid95** [MightyPirates/OpenComputers#3179]
I have the mod running on a MP server i run, on the server, no matter what, when going to press the on button in the computer, you get nothing, no beep, no noise, analyzer card shows no error either.

signed off and tried in singleplayer, worked like a charm.

there are no logs either, console is clear of any errors or info logs.

**Comment by payonel** [comment]
version info please

**Comment by ROMVoid95** [comment]
wow i am sorry i dont know why i didnt add any of that


OpenComputers-MC1.12.2-1.7.5.192.jar
forge-14.23.5.2847
_additional:_
spongeforge-1.12.2-2838-7.1.7-RC3928 (not sure if relevant, but has worked before on this vers. with the forge vers.)

**Comment by payonel** [comment]
we've definitely had problems with spongeforge :(. Can you try without it? I'll test this further later today

**Comment by ROMVoid95** [comment]
in a server environment? can give it a shot, i should prob also mention the server is also running in a Docker instance. yet another thing that im not sure of if its effecting anything

**Comment by payonel** [comment]
tested without spongeforge, works fine

**Comment by payonel** [comment]
tested WITH spongforge as well (using your exact version), still works

**Comment by ROMVoid95** [comment]
yep same, gunna have to just mark this one as instance specific due to very specific prior issues with system or world/data. Works fine every other way.

**Comment by payonel** [comment]
ok, sorry for lack of resolution, if you find repro specifics, please share
