### ISSUE TITLE
Broken redstone card?

### ISSUE THREAD

**Issue by whoisnotthere** [MightyPirates/OpenComputers#3184]
Hello, I installed the latest version of OC (1.7.5) on Minecraft 1.7.10
And it seems that the redstone card is broken. Previously (OC 1.7.2), it was tied to the computer itself, that is, on the left it was left, right it is right, now it works like a redstone block, is it tied to the sides of the world? Is this a bug?

https://youtu.be/m977GJfzo8w

**Comment by UV-Husky** [comment]
So, you are saying that the Redstone is oriented North/South/East/West, instead of relative to computer facing. That seems like a bug as there is no mention of there being such a change in changelogs.

**Comment by whoisnotthere** [comment]
Can we get some answers from the developers? So it’s conceived, and I need to rewrite the code, or is it a bug and I have to wait for the update?

In the old version redstone interrupts does not provide information about cable color which the interrupt was initiated (according to the documentation it should be). Therefore, I would not want to return the old version to my client

By the way, again it seems that this is a bug. Because `setBundledOutput` works as expected, relative to the sides of the computer. But at the same time, the event returned by the card does not work relative to sides of the computer, event return world sides.

**Comment by payonel** [comment]
apparently this broke way back between 1.7.2 -> 1.7.3
we should be respecting the old behavior
i'll get a fix for this, sorry for the confusion

**Comment by whoisnotthere** [comment]
Thanks :)

**Comment by whoisnotthere** [comment]
Thanks for fix, but i tested latest `OpenComputers-MC1.12.2-1.7.5.197` and sides return works as expected, but now `redstone_changed` event doesn't return cable color (colors return works until fix, and in OC wiki mentioned that it should return the cable color)
![Annotation 2020-01-27 103059](https://user-images.githubusercontent.com/25249029/73160063-adc63c00-40f0-11ea-92f1-fa82cd4d0e61.png)
![redstibe](https://user-images.githubusercontent.com/25249029/73160197-04cc1100-40f1-11ea-828e-370815c6452f.png)

**Comment by payonel** [comment]
what mod and version are you using for bundled cables? I didn't remove any information from the event ,only rotated the side. in 1.12 we lost some bundled cable support due to changes in other mod apis, you'll notice the api doc uses `[]` square brackets to indicate those fields are optional

**Comment by whoisnotthere** [comment]
I use ProjectRED, i tested minecraft 1.12.2 (mod version ProjectRed-1.12.2-4.9.4.120, OC version OpenComputers-MC1.12.2-1.7.5.197) and don't have color info in event.

And tested minecraft 1.7.10 (mod version ProjectRed-1.7.10-4.7.0pre12.95, OC version OpenComputers-MC1.7.10-1.7.5.1300-universal) and same have no color output.

I thought square brackets indicate color, not mod, sorry. 
But in stable OC 1.7.5 i have color output, but sides output broken, or with OC 1.7.2 (and latest developer OC 1.7.5 version) i have correct sides output, but don't have color output in `redstone_changed` event.
On stable OC 1.7.5 with Minecraft 1.7.10 / 1.12.2 i have color output in event, but sides output is broken

**Comment by payonel** [comment]
i'll investigate further. thanks for the version info

also: square brackets in documentation indicate optional fields, not mods

**Comment by payonel** [comment]
https://github.com/MightyPirates/OpenComputers/commit/67c375391b91e16224e94077388022ee383531fd
