### ISSUE TITLE
Too long without Yielding when starting OpenOS

### ISSUE THREAD

**Issue by lukadev-0** [MightyPirates/OpenComputers#3188]
When i started my **Computer** with **OpenOS** on a floppy disk it started loading until the second line and gave me an error `Too long without Yielding`.

This happened after i installed **Immersive Engineering** _(Which is one of the mods that add power for computers)_. I think its has something to do with that.

```
OpenComputers-MC1.8.9-1.7.0.175
forge-1.8.9-11.15.1.2318-1.8.9
```

**Comment by lukadev-0** [comment]
I set `IgnorePower` to `true` and it works again.
So it does have something to do with the Power

**Comment by payonel** [comment]
this doesn't have anything to do with power, our code tries super hard to be nice to the host machine and use minimal resources. On a host that is overburdened, we often see this failure. It is expected, but not ideal. Currently we don't have plans to fix/improve this. If you server is having trouble keeping up with ticks (5s delays, for example) I recommend increasing our timeouts in the configs. The default is 5s. Perhaps increase that to 10s or 20s. Look in the config for an option called `timeout`

**Comment by lukadev-0** [comment]
> this doesn't have anything to do with power, our code tries super hard to be nice to the host machine and use minimal resources. On a host that is overburdened, we often see this failure. It is expected, but not ideal. Currently we don't have plans to fix/improve this. If you server is having trouble keeping up with ticks (5s delays, for example) I recommend increasing our timeouts in the configs. The default is 5s. Perhaps increase that to 10s or 20s. Look in the config for an option called `timeout`

I set the setting to 20, it works now.
