### ISSUE TITLE
Add Support for UDP

### ISSUE THREAD

**Issue by natedogith1** [MightyPirates/OpenComputers#3189]
The InternetCard already has support for TCP.  UDP should be added for completeness.

Some actual services that use UDP:
* WebRTC
* BitTorrent
* OpenVPN
* HTTP/3

**Comment by payonel** [comment]
to allow reading udp in untrusted code would allow client code to collect udp packets from the host network. tcp sockets are nice in this regard because we can allow a connection without having to allow listening. we're not trying to provide every imaginable network service

**Comment by natedogith1** [comment]
TCP is still listening (it's just harder to guess the info needed to talk to it than it is for UDP).  And it doesn't seem like it'd be a security issue (at least not much more than WebRTC)

**Comment by payonel** [comment]
ah no, you cannot create a listening socket in with OC's wireless card. There is nothing to guess. you could create a reverse tunnel by hosting a proxy, but there is no access to accepting a incoming socket request.
