### ISSUE TITLE
 [Bug] Just doing what the console told me to do.

### ISSUE THREAD

**Issue by LemonNick** [MightyPirates/OpenComputers#3193]
> [18:58:00] [Server thread/ERROR] [OpenComputers]: Unexpected error loading a state of computer at (393.5, 77.5, 303.5). State: Paused. Unless you're upgrading/downgrading across a major version, please report this! Thank you.
> java.lang.Exception: li.cil.repack.com.naef.jnlua.LuaRuntimeException: could not read data
>         at li.cil.oc.server.machine.luac.NativeLuaArchitecture.load(NativeLuaArchitecture.scala:351) ~[NativeLuaArchitecture.class:?]
>         at li.cil.oc.server.machine.Machine.liftedTree1$1(Machine.scala:721) [Machine.class:?]
>         at li.cil.oc.server.machine.Machine.load(Machine.scala:720) [Machine.class:?]
>         at li.cil.oc.common.tileentity.traits.Computer$class.readFromNBTForServer(Computer.scala:156) [Computer$class.class:?]
>         at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$Colored$$super$readFromNBTForServer(Case.scala:27) [Case.class:?]
>         at li.cil.oc.common.tileentity.traits.Colored$class.readFromNBTForServer(Colored.scala:33) [Colored$class.class:?]
>         at li.cil.oc.common.tileentity.Case.readFromNBTForServer(Case.scala:80) [Case.class:?]
>         at li.cil.oc.common.tileentity.traits.TileEntity$class.readFromNBT(TileEntity.scala:80) [TileEntity$class.class:?]
>         at li.cil.oc.common.tileentity.Case.func_145839_a(Case.scala:27) [Case.class:?]
>         at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:116) [aor.class:?]
>         at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:496) [aqk.class:?]
>         at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41) [ChunkIOProvider.class:?]
>         at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
>         at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:?]
>         at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:?]
>         at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:?]
>         at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) [ms.class:?]
>         at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
>         at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
>         at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
>         at net.minecraft.world.ChunkCache.<init>(ChunkCache.java:39) [ahr.class:?]
>         at net.minecraft.world.World.func_72844_a(World.java:3353) [ahb.class:?]
>         at net.minecraft.pathfinding.PathNavigate.func_75488_a(SourceFile:81) [vv.class:?]
>         at net.minecraft.pathfinding.PathNavigate.func_75492_a(SourceFile:85) [vv.class:?]
>         at net.minecraft.entity.ai.EntityAIWander.func_75249_e(SourceFile:41) [vc.class:?]
>         at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94) [uj.class:?]
>         at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540) [sw.class:?]
>         at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774) [sv.class:?]
>         at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367) [sw.class:?]
>         at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25) [yg.class:?]
>         at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:217) [yq.class:?]
>         at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611) [sv.class:?]
>         at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206) [sw.class:?]
>         at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30) [yg.class:?]
>         at net.minecraft.entity.monster.EntityZombie.func_70071_h_(EntityZombie.java:303) [yq.class:?]
>         at net.minecraft.world.World.func_72866_a(World.java:2070) [ahb.class:?]
>         at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) [mt.class:?]
>         at net.minecraft.world.World.func_72870_g(World.java:2034) [ahb.class:?]
>         at net.minecraft.world.World.func_72939_s(World.java:1887) [ahb.class:?]
>         at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
>         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
> Caused by: li.cil.repack.com.naef.jnlua.LuaRuntimeException: could not read data
>         at li.cil.repack.com.naef.jnlua.LuaState.lua_pcall(Native Method) ~[LuaState.class:?]
>         at li.cil.repack.com.naef.jnlua.LuaState.call(LuaState.java:677) ~[LuaState.class:?]
>         at li.cil.oc.server.machine.luac.PersistenceAPI.unpersist(PersistenceAPI.scala:164) ~[PersistenceAPI.class:?]
>         at li.cil.oc.server.machine.luac.NativeLuaArchitecture.load(NativeLuaArchitecture.scala:356) ~[NativeLuaArchitecture.class:?]
>         ... 44 more

**Other Useful Info:**
OC Version (OpenComputers-1.7.5.1290)
Forge Version (forge-1.7.10 v10.13.4.1614)

**Possibly Unrelated:**
This error occured after a user logged into the server.

**Comment by payonel** [comment]
if this happens with just one oc machine, and does not repro, then we're not going to be able to fix this. This was likely a chunk save failure and the machine state didn't save correctly. If this continues to happen (after the machine at (393.5, 77.5, 303.5) ) is shutdown and started again, and the chunk is saved and reloaded -- then please comment on this ticket again and give us some repro info (which may include a backup of your server directory)

**Comment by payonel** [comment]
(closed be cause we've seen these one-offs before and it is due to bad chunk saves)
