### ISSUE TITLE
Tier 1 Wireless Cards Can Not Receive Messages

### ISSUE THREAD

**Issue by Cruor** [MightyPirates/OpenComputers#3195]
Tier 1 Wireless cards doesn't seem to be able to receive messages, however it is able to send them.
Reproduction steps:
- Open port in Lua prompt on tier 1 device
- Start `dmesg` on tier 1 device
- Broadcast message from any other  device in range
- Message does not show up in `dmesg` on tier 1 device

If you do the same steps as above, but use a tier 2 device for listening and tier 1 for sending it works as expected.

OpenComputers-MC1.12.2-1.7.5.192

**Comment by Alechuu** [comment]
Came here to second this, by further testing I realized that sending the wake message to a device using in both devices a wireless tier 1 card does work, but then it just comes down to what you describe, apparently can send messages but are never received by other tier 1 cards.
