### ISSUE TITLE
Feature Request: Allow fast typing by echo in client-side

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#32]
http://www.minecraftforum.net/topic/2011400-early-wip16x-modular-computing-cpus-tape-terminals/
- Hardware Echo puts an end to typing lag by typing the characters on the client side as soon as you type them!

Well that feature will be nice when editing the program or typing the something.
- Cursor echo enable/disable by `term.setCursorEcho(true or false)` (or other API)
- Cursor echo filter? `term.setCursorEchoFilter(x)` (like NUMBER KEY, or Control KEY+3 -> `#`, `(`, `)`, Backspace key, etc.)
- Another event are fire for handle that (only cancel are possible for erase char and rollback cursor position(how?)), and if that event are cancel, must key_up, key_down fire for fallback?
- Enter Key must not handle by Cursor echo (it will break window frame)

**Comment by LordFokas** [comment]
and when you press a key and that packet is lost before it gets to the server, you have a sync problem.

it may be a bit more complicated than that, even though it uses TCP as far as I know, it may not be 100% safe.

**Comment by fnuecke** [comment]
The biggest issue I see with this is that it gives control over server-client synchronization to user programs. Packets don't even have to get lost, the Lua code just has to discard a typed key, and you're async.
