### ISSUE TITLE
Feature Suggest: Get possible ingredient of a recipe

### ISSUE THREAD

**Issue by Water-Moon** [MightyPirates/OpenComputers#3202]
Right now the robot is able to craft using a crafting upgrade. However, it's a problem that robots can't look up JEI or things like that like a human player, thus making it necessary to hard-code recipes. 
If a function/method/etc. could be added that returns a `table` based on the passed parameter of an `item` information, it will be way much easier for certain programs to work.

**Comment by payonel** [comment]
this has come up before, and i see the value, but this feature is potentially a very large scope and should be a mod of its own, like NEI :) not a small thing to just add to the crafting table of a robot. we try to reduce scope creap

**Comment by Water-Moon** [comment]
Im thinking if it is possible to write an addon that pulls recipe from NEI with a method provided by a certain upgrade/card...
