### ISSUE TITLE
Internet card requests fail on sites with LetsEncrypt/IdenTrust signed certificates

### ISSUE THREAD

**Issue by computer2467** [MightyPirates/OpenComputers#3203]
When running this example code:
```lua
local internet = require("internet")

function GET(uri, data, headers)
    local handle = internet.request(uri, data and data or {}, headers and headers or {})
    local result = ""
    for chunk in handle do result = result..chunk end
    local mt = getmetatable(handle)
    local code, message, headers = mt.__index.response()
    return result, code, message, headers
end

print(GET("https://irclogs.pc-logix.com/")) -- any site with LetsEncrypt/IndenTrust as CA
```
it throws with the error:
`get.lua:6: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`
This happens with any site with "DST Root CA X3" as the root certificate.

**Comment by payonel** [comment]
this works just fine "on my box"
this very much looks like a problem with the trusted cert authority stored on the host machines, not something OC is doing wrong

**Comment by Namelessys** [comment]
It't not optimal, especially playing on a server. But here is a workaround.

https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ
