### ISSUE TITLE
Do not block entire computer on component calls, only yield currently running coroutine.

### ISSUE THREAD

**Issue by Archengius** [MightyPirates/OpenComputers#3205]
Currently, when any of the computer's coroutines calls component methods which are executed in main server thread, entire computer blocks until it is executed.
However, it is not necessary at all to block entire computer if only one coroutine is waiting for a component call's response. So, my suggestion is using coroutine.yield() when component call occurs in components library, and then calling coroutine.resume() with call result when server thread data becomes available, thus stopping execution only of the calling coroutine, and not the entire computer. That would prevent background services (like the ones running with rc) from affecting foreground work performance, and generally promote multitasking rather than spaming different computers for each task.

**Comment by payonel** [comment]
if you leverage event listeners or threads, you get this feature. read more about events here: https://ocdoc.cil.li/api:event and read about threads here: https://ocdoc.cil.li/api:thread

if you have more questions, feel free to visit our irc channel (oc) on esper net (also via discord) https://discord.gg/bYqKv7h
