### ISSUE TITLE
OpenComputers for 1.14.4?

### ISSUE THREAD

**Issue by Edivad99** [MightyPirates/OpenComputers#3209]
Hi, since the Forge team said 1.12.2 is no longer supported, when will the OC be released for 1.14.4?

**Comment by payonel** [comment]
this isn't a github issue, ask these types of questions in our forums or irc channel. we haven't made any annoucements about this

**Comment by Techokami** [comment]
I expect this to meet the same fate as #3181 and be redirected to the forums... [with a dead topic that hasn't been touched since November.](https://oc.cil.li/topic/1843-plans-for-114/)

And just as I was typing this, payonel went and did it.
