### ISSUE TITLE
[MC 1.12.2, OC 1.7.5.192] There were errors running the class transformer.

### ISSUE THREAD

**Issue by T-Dark0** [MightyPirates/OpenComputers#3214]
When I entered a world, a chat message told me there had been errors

Attached are the mod list and the latest.log

I took a quick look at the log, and tried downgrading vanillaFix from 1.0.9-99 to 1.0.9-97, but the error still appeared.

[modlist.txt](https://github.com/MightyPirates/OpenComputers/files/4076609/modlist.txt)

[latest.log](https://github.com/MightyPirates/OpenComputers/files/4076598/latest.log)

**Comment by svitoos** [comment]
Install [Forge Mixin Fix](https://www.curseforge.com/minecraft/mc-mods/forge-mixin-fix)
