### ISSUE TITLE
event.pull("modem") works in lua interpreter but not in a saved lua file

### ISSUE THREAD

**Issue by RetroScythe** [MightyPirates/OpenComputers#3217]
I am making a simple instant messenger but I cant get my head around why this isn't working.

`function send()
io.write("Message >> ")
  local message = io.read()
  component.modem.broadcast(5975, message)
  event.pull("modem") -- This line only works in the interpreter but not from a file.
  send()
end

send()`

it get the error "attempt to index global 'event' (a nil value)" like it just doesn't exist when it clearly does because it runs in the interpreter just fine when I write it line by line. I'm not sure if this is a bug or something. How can I make this work?

**Comment by payonel** [comment]
correct - that is expected
our lua repl [read-eval-print-loop] (a.k.a the lua interpreter) loads all the libraries (i.e. `require`) for you, in the background (and dynamically as you use them)
in actual scripts, you have to `require` the libs you want to use

your code run outside the repl would need to look like this:

```
local event = require("event")
local component = require("component")

function send()
  io.write("Message >> ")
  local message = io.read()
  component.modem.broadcast(5975, message)
  event.pull("modem") -- This line only works in the interpreter but not from a file.
  send()
end

send()
```

however ---- i am concerned your code failed on the event line, and not the preceding line when you use component (which also has to be imported)

Are you trying to run this code with openos? Or from the eeprom directly (such as with a drone, or microcontroller?)

If that is the case, then in that environment you have no `require` defined (openos does that for you). read our docs about building a custom OS ( https://ocdoc.cil.li/ ) or talk with us on irc on the oc channel for some more information

**Comment by payonel** [comment]
but you did use `io` as well, which is also defined by openos. i suspect you did require component in your original code, but not event
