### ISSUE TITLE
print3d-examples not working [MC 1.7.10 OC 1.7.5.1290-universal]

### ISSUE THREAD

**Issue by HassaFelipe** [MightyPirates/OpenComputers#3219]
I'm having trouble running the 3d printer code samples, I have no idea what's going on, I've tried re-installing the OS and OPPM and nothing, I also tried to create another instance of minecraft and nothing the error continues.

Error screenshot.
https://imgur.com/BKIaV1L

I am not familiar with the English language so I apologize for any mistakes.

Thanks.

**Comment by payonel** [comment]
read about the 3d print here: https://ocdoc.cil.li/block:3d_printer
the 3dm files are not programs, you don't run them, instead you can feed them to the print3d program provided by sangar's print3d oppm package
e.g. `print3d /usr/share/models/pot.3dm`
this will set the print job in the printer, and you need to provide chamelium and an ink cartridge

again, this is explained in the ocdoc i provided above
