### ISSUE TITLE
Virus detection in OpenComputers-MC1.7.10-1.7.5.1290-universal.jar

### ISSUE THREAD

**Issue by zetti68** [MightyPirates/OpenComputers#3221]
I store my mods at a NAS with weekly virus check. Last OpenComputers-jar is infected. May be it is a false positive detection. The last version was clean: OpenComputers-MC1.7.10-1.7.4.1265-universal.jar.

I loaded it here: https://www.curseforge.com/minecraft/mc-mods/opencomputers/files/2828353

Here is the log:

JobName = Weekly
LogLastScanTime = 2020/01/20 01:00:07
AntivirusEngine = ClamAV

-------------------------------------------------------------------------------

/<path/to/file>/OpenComputers-MC1.7.10-1.7.5.1290-universal.jar: Win.Dropper.Kovter-7489194-0 FOUND

----------- SCAN SUMMARY -----------
Known viruses: 6701764
Engine version: 0.101.2
Scanned directories: 7692
Scanned files: 122290
Infected files: 1
Data scanned: 118875.62 MB
Data read: 1804149.39 MB (ratio 0.07:1)
Time: 54836.597 sec (913 m 56 s)

Please check it and register a false positive detection at clamav.net. My NAS is a UNIX system.

Thanks

**Comment by payonel** [comment]
the file on curseforge is a binary match to our file we build via jenkins, which takes directly from our git source repo
```
$ sha256sum *OpenComputers-MC1.7.10-1.7.5.1290-universal.jar 
10257a83bbb15e0a79d635ce218ce9f5a2229cd4d7809067dbe5aed776f7f79c  curseforge-OpenComputers-MC1.7.10-1.7.5.1290-universal.jar
10257a83bbb15e0a79d635ce218ce9f5a2229cd4d7809067dbe5aed776f7f79c  OpenComputers-MC1.7.10-1.7.5.1290-universal.jar
```
see https://ci.cil.li/job/OpenComputers-MC1.7.10/1290/
and you can review our code, it is open source
sounds like a problem with your virus scanner, not us

**Comment by zetti68** [comment]
Thanks, I found the problem. I unpacked the files and scanned again:
**/lib/lua52/native.32.dll**: Win.Dropper.Kovter-7489194-0 FOUND

The virus is not in your source code but in your archive. Sorry.

Last checks: without .../lua52/native.32.dll in jar
-> check is ok -> I know, it was clear before start of check ;-)
Copy .../lua52/native.32.dll from last version OpenComputers-...1.7.4.1265.jar into current 1.7.5.1290
-> check is also ok
-> strange, because old and new native.32.dll have same size.
May be the last version of **.../lua/native.32.dll** is infected!

Quickfix for me: I deleted all Win32 natives, I use 64Bit forge.

**Comment by Techokami** [comment]
The native DLLs don't have their source code in this repository. Rather, they are in [their own repository](https://github.com/MightyPirates/OC-Natives), so you can check the source code for these here as well.

Anyway, this sounds like a false positive. I have filed a false positive report on ClamAV's site and they will probably be reading this bug tracker entry as I have linked them to it.
