### ISSUE TITLE
OpenComputers not using Power in Singleplayer 

### ISSUE THREAD

**Issue by CoolMan119** [MightyPirates/OpenComputers#3222]
Hi, I have setup my power system with Redstone Flux and none of my computers are using the power, i dont have any creative cases and they are not using any power. I dont know if its in the config

Thanks!

**Comment by payonel** [comment]
please attach your opencomputers config, and tell us the full oc version string, including redstone flux version

thanks

**Comment by payonel** [comment]
just tested our realed oc with the latest cofh stuff, works fine
check your config and make sure `ignorePower` is set to false, and true :)
