### ISSUE TITLE
[1.12.2] In server,Debug card cannot run command.

### ISSUE THREAD

**Issue by mckuhei** [MightyPirates/OpenComputers#3224]
I already given op. :(

**Comment by mckuhei** [comment]
Lua> component.debug.runCommand("say aaa")
0.0           "You do not have permission to use this command"

**Comment by mckuhei** [comment]
I think is forge fake player's problem.

**Comment by mckuhei** [comment]
My op list:
[
  {
    "uuid": "3c9df0da-8f0b-3c15-a388-c6b967271b83",
    "name": "[opencomputers]",
    "level": 4,
    "bypassesPlayerLimit": false
  },
  {
    "uuid": "960fdc33-e2d3-4b1e-9957-9519659f9784",
    "name": "computer",
    "level": 4,
    "bypassesPlayerLimit": false
  },
  {
    "uuid": "eb776106-2be0-3908-8967-b90975c5e5bd",
    "name": "xiaoyu",
    "level": 4,
    "bypassesPlayerLimit": false
  },
  {
    "uuid": "834a7dc9-4214-332b-bc16-c3b455fd082a",
    "name": "opencomputersuser",
    "level": 4,
    "bypassesPlayerLimit": false
  },
  {
    "uuid": "f63a340b-6732-47b0-bb1b-57ac91b6c76e",
    "name": "Forge",
    "level": 4,
    "bypassesPlayerLimit": false
  },
  {
    "uuid": "ef0e0b1e-4d9b-3b59-b87e-91cbeb6550a7",
    "name": "窝窝头169块钱1个",
    "level": 4,
    "bypassesPlayerLimit": false
  },
  {
    "uuid": "37c56b7a-9bf8-4b47-b453-1bb2340eafba",
    "name": "Computers",
    "level": 4,
    "bypassesPlayerLimit": false
  },
  {
    "uuid": "bc71f709-8e5c-38f6-98ea-0ef64f62f3c7",
    "name": "[opencomputers",
    "level": 4,
    "bypassesPlayerLimit": false
  },
  {
    "uuid": "a96eea13-de45-4ba5-b763-a4f7e65adac8",
    "name": "FakePlayer",
    "level": 4,
    "bypassesPlayerLimit": false
  },
  {
    "uuid": "250b30bd-93fe-352e-a397-8937fb163e72",
    "name": "[[opencomputers]",
    "level": 4,
    "bypassesPlayerLimit": false
  },
  {
    "uuid": "da2c7609-7734-32fa-9e32-5ec5d3234c14",
    "name": "Minecraftku_hei",
    "level": 4,
    "bypassesPlayerLimit": false
  },
  {
    "uuid": "7457f40e-5e5b-41e9-8a29-2cac3838f0c2",
    "name": "OpenComputers",
    "level": 4,
    "bypassesPlayerLimit": false
  },
  {
    "uuid": "17e0cf50-1fee-4b01-9d87-565cc05fc928",
    "name": "Minecraftku_hei",
    "level": 4,
    "bypassesPlayerLimit": false
  },
  {
    "uuid": "e5359186-03e8-4e03-82e1-0b712ffd1b0f",
    "name": "Debug",
    "level": 4,
    "bypassesPlayerLimit": false
  },
  {
    "uuid": "8e22931b-a3c4-4588-8e32-4ba3e45fd423",
    "name": "CommandBlock",
    "level": 4,
    "bypassesPlayerLimit": false
  },
  {
    "uuid": "1edd1883-39fd-408a-b896-48083b266f67",
    "name": "buildcraft",
    "level": 4,
    "bypassesPlayerLimit": false
  },
  {
    "uuid": "39598781-34f1-4230-8212-a6fa59f7e54a",
    "name": "zhou2008",
    "level": 4,
    "bypassesPlayerLimit": false
  },
  {
    "uuid": "4c0ecb0c-f3e0-37ce-be51-1252ce2ecab6",
    "name": "zhou2008",
    "level": 4,
    "bypassesPlayerLimit": false
  }
]

**Comment by payonel** [comment]
in multiplayer, you have to bind the debug card to a real player
have the player that should "own" the debug card, hold the debug card in hand, then crouch and right click. This binds and unbinds the card. If the card is bound, you'll see the player name in the mouse-hover tooltip for the card. If you crouch+rightclick with the card in hand a second time, it unbinds it
