### ISSUE TITLE
Hard drive's maxSize value in stack info should be 1 if the drive has UUID assigned

### ISSUE THREAD

**Issue by Kristopher38** [MightyPirates/OpenComputers#3226]
**Versions:**
Minecraft: **1.12.2**
Forge: **14.23.5.2768**
OpenComputers: **1.7.5.192**
Pure forge install without any third-party launchers, with only OpenComputers installed

**Description:**
When checking for stack info of a UUID-assigned hard drive (this also applies to floppies and EEPROMs as they too can get assigned a UUID) with e.g. inventory_controller.getStackInInternalSlot the reported maxSize value is 64 (which is true for hard drives which don't have UUID assigned since they can stack), where in reality UUID-assigned hard drives don't stack so the reported value should be 1.

**Steps to reproduce:**
1. Place a robot with screen, keyboard, inventory and inventory controller (creatix will suffice) and a computer case
2. Insert the hard drive into the computer case to get UUID assigned to it
3. Place the hard drive in the first slot of the robot's inventory
4. Turn on the robot, open lua interpreter and type `component.inventory_controller.getStackInInternalSlot(1)`
5. The reported maxSize value will be 64

**Notes:**
As per discussion on discord/irc, I don't know how feasible it is to fix this without a lot of hassle, especially without creating a new item to differentiate between UUID-assigned and UUID-less storage devices. Maybe a simple check if the item has UUID assigned [in ConverterItemStack.scala where maxSize is set](https://github.com/MightyPirates/OpenComputers/blob/cca7f202d5040156bf93a0ef687fd6447fbfd07d/src/main/scala/li/cil/oc/integration/vanilla/ConverterItemStack.scala#L31) and setting maxSize to 1 in that case would do the job?

**Comment by xarses** [comment]
for my edification, other than it looks weird in the interface, what is the need for a UUID assigned device to report their maxSize as 1?

Doesn't this have the side effect of all UUID cloned devices stacking? As do p2p cards and in the rare cases you purposely or accidentally do clone them.

**Comment by payonel** [comment]
woah, xarses!?! where have you been, mate?! :) we've missed you o/

this is just a requests for hard drives to report stack info different, to inventory controllers, we already don't stack uuid-assigned drives
