### ISSUE TITLE
[Feature-Request] Generic more customizable overlays

### ISSUE THREAD

**Issue by AnotherDevlop** [MightyPirates/OpenComputers#3227]
Add for all (overlayed) blocks, an independent overlay texture for each side, for each block state/condition. And allow the overlay texture be specified in a json file, like the models/block/*.json approach. It will bring a lot of flexibility, and power to texture pack creators.

Also will be nice to add overlay to the switch for when queue is full, or packet is dropped; and for when wireless card is present. It will allow players to become aware of problems with it easily.

**Comment by payonel** [comment]
pretty neat idea, but honestly, it's not going to get done - this is not a trivial change
