### ISSUE TITLE
TCPNotifier thread crashes if socket address is blacklisted

### ISSUE THREAD

**Issue by Fingercomp** [MightyPirates/OpenComputers#3228]
I get the following exception when I attempt to connect to a blacklisted address:

```
Exception in thread "Thread-28"
scala.MatchError: (null,<function0>) (of class scala.Tuple2)
	at li.cil.oc.server.component.InternetCard$TCPNotifier$$anonfun$run$4.apply(InternetCard.scala:195)
	at li.cil.oc.server.component.InternetCard$TCPNotifier$$anonfun$run$4.apply(InternetCard.scala:195)
	at scala.collection.immutable.Stream.foreach(Stream.scala:555)
	at li.cil.oc.server.component.InternetCard$TCPNotifier$.run(InternetCard.scala:195)
```

The code I used to reproduce the bug:

```lua
local socket = require("component").internet.connect("localhost:80")
os.sleep(1)
print(socket.finishConnect())
print(socket.finishConnect())
socket.close()
```

I'm running OpenComputers 1.7.5. The game version is 1.7.10, but I'm quite sure this issue does not depend on it.

---

I don't know Scala, so I can be wrong, but I think [this line](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/server/component/InternetCard.scala#L266) is the culprit:

1. During `os.sleep(1)`, `AddressResolver` resolves the address to `127.0.0.1`, which is blacklisted by default.
2. `socket.finishConnect()` runs `checkConnected()`.
3. The error is [thrown there](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/server/component/InternetCard.scala#L332-L334).
4. It's [caught](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/server/component/InternetCard.scala#L342), and the handler calls `close()`, which [sets](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/server/component/InternetCard.scala#L317) the `channel` to `null`.
5. `setupSelector()` is then run, which [calls](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/server/component/InternetCard.scala#L253) `TCPNotifier.add`, passing `(null, () => Unit)` as the argument.
6. Eventually [this code](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/server/component/InternetCard.scala#L199-L202) takes that tuple, and the exception is thrown.

**Comment by Kristopher38** [comment]
I have tested the PRed fix and can confirm that it fixes not only this specific issue, but another one I ran into - when the server process that the OC socket is connected to gets forcibly killed for example, it can also crash that thread and disable `internet_ready` signals on all computers until the MC server is restarted, so I'm hoping this will be merged soon.
