### ISSUE TITLE
Wrong Dimensions for Hologram Rotation

### ISSUE THREAD

**Issue by jajajafeti** [MightyPirates/OpenComputers#3231]
As far as I understood it, the function setRotationSpeed(speed, x, y, z) out puts a Rotation in a Plane around the normal vector (vector orthogonal to the Plane), made up out of the components x, y, z.

For example holo.setRotationSpeed(anySpeed,1 ,0, 0)
  should give me a Rotation around the x-Axis.

But instead I get a Rotation around the z-Axis. It works correctly for the Rotation around the y-Axis.

Same with setRotation(angle, x, y, z).
Dont know if I am just dumb or there is something wrong.

**Comment by payonel** [comment]
it is a rotation around that axis, not in that direction. i've confirmed the results match expected
