### ISSUE TITLE
Fabric Support

### ISSUE THREAD

**Issue by 9p4** [MightyPirates/OpenComputers#3233]
How difficult would it be to port this to Fabric?

**Comment by payonel** [comment]
not really the item for a github ticket. open discussions on our forums or irc channel

**Comment by 9p4** [comment]
Added to forums, awaiting admin authorization 


https://oc.cil.li/topic/2164-fabric-support/

**Comment by Merith-TK** [comment]
Any updates on this? the forum post has not been approved at all,

**Comment by rdrpenguin04** [comment]
To be fair, the forum post was a bit aggressively worded.

**Comment by 9p4** [comment]
Looking back at it, yeah it's pretty bad... sorry to the devs for being rude :)
