### ISSUE TITLE
[Suggestuon] User privilege levels.

### ISSUE THREAD

**Issue by bonnedav** [MightyPirates/OpenComputers#3235]
I think that the user system on computers should be expanded to have 2 user levels, User and Admin. An admin should have full access same as a user currently, while a User shuld only be able to input commands except interrupts but not access the inventory or break the block. A computer with both lists blank shuld allow anyone to do anything. A computer with Users but no Admins shuld act just like users do now. A computer with Admins but no users should give anyone input access but only Admins inventory access. Maby also expand what is pritected by the system as well. Please consider this as it would be very useful to me and possibly others, thank you.

**Comment by payonel** [comment]
make your own OS for that, openos is single user. we're not adding more locking features on the hardward=e

**Comment by bonnedav** [comment]
but is not the os its the signal form the keyboard and screen, I can't prevent someone form accessing the computer inventory without also preventing them form interacting because the signals wont fire. This has nothing to do with openOS and is a request to have inventory checking be different then the checks on keyboard and screen input.

**Comment by bonnedav** [comment]
please reconsider @payonel
