### ISSUE TITLE
Computer's state not saving

### ISSUE THREAD

**Issue by LaG1924** [MightyPirates/OpenComputers#3238]
MC version: 1.12.2
OC version: OpenComputers-MC1.12.2-1.7.5.192
Server OS: Windows10-1909

When I joined to my Minecraft server again I see that computer is shutdown but screen is working (I mean it has words on it but not interactive).

That's spammed in log when I started computer again:
```
[17:49:49] [Server thread/WARN] [opencomputers]: Could not persist computer @ (-685.5, 74.5, -1280.5).
li.cil.repack.com.naef.jnlua.LuaRuntimeException: attempt to literally persist userdata
```

**Comment by payonel** [comment]
i need minimal repro steps, not just version info

**Comment by LaG1924** [comment]
I had supposed that this issue because of mod conflicts (there are 100+ mods). But after generating new world I can't reproduce it. Surprisingly, I destroyed malfunctioned computer and placed it again and now it works. So, that issue is no more relevant.

Actually, there was a power outage few days ago and world could became corrupted (atleast that was wrote in logs). But that happened before I ever created any item from OpenComputers. And any other mod didn't corrupted (or I didn't noticed that). Because of that I don't think that extremal server shutdown caused computer's state loosing.

Anyway, I backuped world with corrupted pc and if you would to investigate that issue I'll help you. Looks like there was exception in Lua Runtime, so somewhere should be callstack which will give more info, right?

**Comment by payonel** [comment]
usually not much info in the crash, it can be quite opaque. are you saying you have a world save that prints that error each time you start the world? or at least the next time you start the world?

**Comment by LaG1924** [comment]
Unfortunately, I can't reproduce it.

Few days ago it was like:
1. Start MC server
2. Start up computer
3. There is periodical (about few times in minute) "Could not persist computer" in MC server's log
4. Reboot MC server (or go far away to unload chunk)
5. OC's computer is powered off

But, now even after loading save when computer is powered off due to that bug (earlier it was every reboot) there is no messages in log after booting up pc and it still does work after server restart.

I loose it. You can mark this issue as "no-repro" and close it.

**Comment by payonel** [comment]
sorry for the loss of data you had, though
