### ISSUE TITLE
[1.7.10 only] Potential improvements to agent Block clicking

### ISSUE THREAD

**Issue by svitoos** [MightyPirates/OpenComputers#3239]
vesrions:
mc 1.7.10
latest oc
forestry 4.2.16.64

Removing block.canEntityDestroy(world, x, y, z, this) fixes it
https://github.com/MightyPirates/OpenComputers/blob/b9cc1663b262816c8c1f271ef6b8eb9850523462/src/main/scala/li/cil/oc/server/agent/Player.scala#L348

See also: 
https://github.com/ForestryMC/ForestryMC/blob/e83dcbc61d22535c5717c97fb7e8161719c37713/src/main/java/forestry/apiculture/blocks/BlockBeehives.java#L64

ps

"canEntityDestroy" allows to protect block of destruction by such mobs as ender dragon, wither and some another moded mobs

**Comment by asiekierka** [comment]
Forestry blocks all entities here, but this method is *not* used by real players, and it is *not* used in 1.12.2. I think the canEntityDestroy check should be _removed_ in 1.7.10 to match, as such.

**Comment by asiekierka** [comment]
I'm removing canEntityDestroy for 1.7.6. In 1.8.0, I'd like to consider replacing the explicit fluid registry check with a collision box check - this should correlate with "blocks the player can't break", but more testing is required.
