### ISSUE TITLE
Computers dont turn on

### ISSUE THREAD

**Issue by Xanadu16** [MightyPirates/OpenComputers#324]
I don't exactly have a log, but in the Technic console, when I go to turn a computer on, I get this.

[B#439]  [18:34:33] [OpenComputers-Computer-1/WARN]: Kernel returned unexpected results.

OpenComputers-MC1.7.2-1.3.0.176-universal.jar
industrialcraft-2-2.1.478-experimental.jar
gregtech-1.7.jar

This is also a problem even without those two extra mods; I was testing the computers with a power source.

Forge is build 1124. Also tested in 1122 with no success.

Java version is 1.7.0_55.

UPDATE: Still occurs as of build 177.

**Comment by TorakWolf** [comment]
Do you have one openos disk on one disk drive connected to the computer?

**Comment by Xanadu16** [comment]
After punching ON over and over, I got this to pop up.

[B#439]  Error in class 'SourceLWJGL OpenAL'
[B#439]      Channel null in method 'stop'
[B#439]  Error in class 'LibraryLWJGLOpenAL'
[B#439]      Source '6cdf3b18-9f74-475f-b2b5-5dae44677efa' not found in method 'play'

And yes, I do.

**Comment by fnuecke** [comment]
Looks like LuaJ borked again, I'm looking into it. The OpenAL errors are unrelated and non-critical, but something I'm aware of, and look into when I have the time.
