### ISSUE TITLE
Native libraries not working on 64bit ARM processor running 32bit Raspbian OS (Raspberry Pi 4B)

### ISSUE THREAD

**Issue by RSA-4096** [MightyPirates/OpenComputers#3240]
I'm trying to run a small forge server on my newly received Pi 4B, however, OpenComputers is having some issues that I cannot resolve. Upon joining the server, I get the **"Native Lua libraries are not available, computers will not be able to persist their state. They will reboot on chunk reloads."** message, and in the server logs, this happens:
```
[17:49:20] [Server thread/INFO] [opencomputers]: Initializing OpenComputers API.
[17:49:21] [Server thread/WARN] [opencomputers]: Unsupported platform, you won't be able to host games with persistent computers.
[17:49:21] [Server thread/WARN] [opencomputers]: Native library with name 'lua53/native.32.arm.so' not found.
[17:49:21] [Server thread/WARN] [opencomputers]: Unsupported platform, you won't be able to host games with persistent computers.
[17:49:21] [Server thread/INFO] [opencomputers]: Done with pre init phase.
```
Apparently OpenComputers cannot find (and obviously load) the library for ARM. An ARM library for Lua 5.2 already exists within OpenComputers repositories and should be extracted automatically, but this just doesn't detect any of that. What I've tried:
Manually downloading the Lua 5.2 library, placing it inside of the main server folder, using the config's "load specific library" setting to try and load it in using its full name (extension as well), disabling both of the Lua 5.3 settings in the config, trying the 'extract to temp directory.

**Comment by mrmelon54** [comment]
Is there any updates on a fix for this?

**Comment by RSA-4096** [comment]
None that I'm aware of.

**Comment by hazzal** [comment]
I'm having the same issue on my arm hardfloat raspberry pi 4. It tries to load the OpenComputersMod-1.7.5.1290-lua52-native.32.arm.so library but gets an java.lang.UnsatisfiedLinkError error.

**Comment by Ijdtm7** [comment]
you can compile the Lua5.3 for the pi 4 here: https://github.com/MightyPirates/OC-Natives/tree/master-Lua5.3
i tweaked a few stuff and it compiled. Still says its unsupported though

**Comment by payonel** [comment]
we dont plan to add native support
