### ISSUE TITLE
Add support for non-BMP Unicode characters

### ISSUE THREAD

**Issue by asiekierka** [MightyPirates/OpenComputers#3242]
Currently, TextBuffer and co. operate on the Java primitive "char" type, supporting codepoints from 0 to 0xFFFF. Support for beyond-BMP Unicode characters would be particularly beneficial due to Unicode 13.0 introducing new glyph types inspired by legacy computer/terminal fonts in said area.

**Comment by skyem123** [comment]
What would the best way of storing it be?
Strings? UTF-32 codepoints?

This would probably need a library too for the modern features.

(I like this so I want to figure out how it could be done)

**Comment by payonel** [comment]
this is a great suggestion :) but not planning to add features around this
