### ISSUE TITLE
[QUESTION] Robots restricted to Tier 1 Screen

### ISSUE THREAD

**Issue by Shazuli** [MightyPirates/OpenComputers#3245]
***Hi***

I've always wondered why Robots are restricted to just Tier 1 screens. After a little searching, I found [this](451) issue where fnuecke answered the same question I do that he liked robots being limited in their construction. But his last commit was back in May 2018, so maybe the question can be brought up again with the new lead developer.
In that issue the reason to allow better screens was to make working in it more pleasant, I think I can do better: My biggest issue with being locked in on a tier 1 screen is that there are no touch events on them. If you want to have your program be interactable by players you have to either install a keyboard and loose one upgrade slot or make one more PC and send signals from it to the robot. A tier 2 screen would make the screen larger, multicoloured and touch events while only taking up one upgrade slot but same complexity point. Touch events can be interpreted as inputs and by the use of software add a touch keyboard. A good compromise in my opinion. The tier 3 screen would add an even bigger screen and full colour-depth, maybe screens should be limited to the casing?

That's my argument, I think it would be nice with allowing better screens in Robots.

**Comment by JujuLynx** [comment]
While I agree with this idea in principle, I feel like if I needed that much control over a robot then I'd probably want a more convenient input method anyway.

Personally I'd make a tablet which handles the input and the instructions transmitted via wireless network to the robot. This would allow you to position yourself in a location to better observe the robot. It also means you don't have to follow the robot around when it inevitably moves too far away from you.

What kind of robot controls did you have in mind?

**Comment by Shazuli** [comment]
> While I agree with this idea in principle, I feel like if I needed that much control over a robot then I'd probably want a more convenient input method anyway.
> 
> Personally I'd make a tablet which handles the input and the instructions transmitted via wireless network to the robot. This would allow you to position yourself in a location to better observe the robot. It also means you don't have to follow the robot around when it inevitably moves too far away from you.
> 
> What kind of robot controls did you have in mind?

Sorry for the late reply @Rayder44. The controls I had in mind could be pairing the Robot to a device, program start in different modes, program settings (mining program for digging out area), manual control of a robot for shorter distances (guide a full Robot to charging station), prevent malicious use of other players (Robot warfare (prevent Ctrl + Alt + C)), extra component slot, etc. I could ramble all day for different uses of touch events on a Robot without a keyboard.

**Comment by payonel** [comment]
i can see how it would be nice to have touch events on robots, and that is a new dynamic. but robots were also intended to be limited, your advanced UIs should be on cases instead. I would recommend setting up the UI on the fixed-location case, and send modem messages to robots to respond
