### ISSUE TITLE
component.robot.drop DOES drop into world

### ISSUE THREAD

**Issue by 7eggert** [MightyPirates/OpenComputers#3248]
OpenComputers-MC1.12.2-1.7.5.192.jar

component.robot.drop is documented to NOT drop into the world. It does.
(robot.drop is documented to drop the item.)

The function should have a parameter to chose weather to drop things or to put them into an inventory. ¢¢

(BTW: Is "if inv.getInventoryName() then c...robot.drop(...);end" atomic?)

**Comment by payonel** [comment]
it is atomic only if getInventoryName() did not cause an machine yield, which can happen when the machine call budget is spent. every component call can have a budget cost. i wouldn't rely on any proxy call being "free". it also depends on the proxy object involved (e.g. vanilla minecraft chest vs 3rd party mod with integration)

**Comment by 7eggert** [comment]
Is it possible to (intentionally yield and) refresh the budget?

**Comment by payonel** [comment]
drop has a fallback to drop in world, this is intended, but not well documented. if you need to make sure there is an inventory to put an item into, use the inventory component
`component.inventory_controller.dropIntoSlot(sides.bottom, slot_index, number_of_items_to_drop)`

**Comment by 7eggert** [comment]
Suggestion: A slot_index value to put things into any slot (just like robot.drop does).
