### ISSUE TITLE
remote terminal crash

### ISSUE THREAD

**Issue by haq3rgaming** [MightyPirates/OpenComputers#3249]
after trying to open remote terminal that is binded to terminal card and card isnt in server rack it crashes the game please help

**Comment by payonel** [comment]
version and repro steps. minimal repro is always helpful. that means, find variations similar to your repro steps where this does not causes  crash and add that detail

i've closed a bug similar to this so you'll need to be specific and careful to explain how it is happening, and just as important, when it doesn't happen in similar steps
