### ISSUE TITLE
RC check for service script changes

### ISSUE THREAD

**Issue by JustMax10001001** [MightyPirates/OpenComputers#3250]
While creating a service script for monitoring my reactors I stumbled across the problem of having to either run lua interprenter and rc.unload or rebooting the whole computer. Therefore, I made a small change to rc.lua which allowed a user to be notified about a change in loaded script and to easily reload the script. Attached are the modified /bin/rc.lua and /etc/rc.cfg
[bundle.zip](https://github.com/MightyPirates/OpenComputers/files/4350256/bundle.zip)

**Comment by JustMax10001001** [comment]
The way this works is as follows: while loading script, rc tries to generate hash of it if datacard is present. Otherwise filesize will be considered, which should be more than enough. Then, on every command issued to rc, it checks whether loaded script still has the same hash and then reports to user if they turn out to be not equal

**Comment by payonel** [comment]
this is not how real-life openrc behaves at all, i would expect a user to restart a service if changes are made.
if rc restart isn't working for you because you've used require to cache libraries, don't use require, or, add a `package.loaded[lib] = nil` to your service stop handler

**Comment by JustMax10001001** [comment]
Well, I was inspired because while working on Ubuntu I ran into similar issue with service command suggesting me to run `systemctl daemon-reload` to get changes applied. But yeah, I see your point.

**Comment by skyem123** [comment]
Maybe this could be on a loot disk or something? Like a "better RC"?
