### ISSUE TITLE
Screens don't render at certain positions

### ISSUE THREAD

**Issue by big-lip-bob** [MightyPirates/OpenComputers#3252]
![image](https://user-images.githubusercontent.com/41026257/77233744-cd865780-6ba9-11ea-9d16-74351752d3d8.png)
![image](https://user-images.githubusercontent.com/41026257/77233755-d5de9280-6ba9-11ea-8a58-a44a41f28cf0.png)
it only starts rendering if im a slab off the ground.

**Comment by big-lip-bob** [comment]
OpenComputers-MC1.12.2-1.7.5.198
1.12.2-forge1.12.2-14.23.5.2847
Didn't test without Optifine

**Comment by payonel** [comment]
we dont try to support optifine nor custom shaders - those mod devs are welcome to make PRs to our mod if they would like to trouble shoot

**Comment by payonel** [comment]
confirmed without optifine. i misunderstood that you are standing below the y level of the screen by only a half block and the screen goes black. likely we are checking the view from the foot not the eye

**Comment by payonel** [comment]
this started in 1.10
