### ISSUE TITLE
__ipairs metamethod is ignored on Lua5.3 architecture

### ISSUE THREAD

**Issue by Kristopher38** [MightyPirates/OpenComputers#3256]
**Versions:**
Minecraft: 1.12.2
Forge: 14.23.5.2768
Opencomputers: 1.12.2-1.7.5.192
(This might be relevant) Operating system: Windows 7 64-bit (using native.64.dll)

**Description:**
Consider the following code:
```
local t = {}
t.somefield = {}
t[1] = "This shouldn't be printed"

local meta = {}
meta.__ipairs = function(self)
    print("Called ipairs")
    return ipairs(self.somefield)
end

setmetatable(t, meta)

table.insert(t.somefield, 53)
table.insert(t.somefield, 63)
table.insert(t.somefield, 28)
table.insert(t.somefield, 74)

for i, v in ipairs(t) do
    print(i, v)
end
```

It creates a table with `somefield` subtable and element at index 1, sets the metatable to a table with `__ipairs` key, which just prints that it was called and returns standard ipairs iterator on `t.somefield`, then `t.somefield` gets populated with data and `ipairs` on `t` is called which should call the `__ipairs` function defined earlier, so the expected output should be:
```
Called ipairs
1       53
2       63
3       28
4       74
```
And this is exactly what happens in standalone lua 5.3.5, lua 5.2.3 (I just happened to have those versions installed on my PC), latest Eris that I compiled from branch `master-lua5.3` and in OC's lua 5.2 architecture. But in OC's lua 5.3 architecture this is printed instead:
```
1       This shouldn't be printed
```
It looks like the `__ipairs` metamethod is ignored and instead it does iteration over `t`. Note that the `__pairs` metamethod works as expected as I've been using those for some time now and never encountered any bug when using them, both in OC's Lua 5.2 and 5.3 architectures.

**Notes:**
I wondered where to report this, on this repo or Eris' repo, but since this happens only in OC I figured here is the correct place. I'm not sure how to properly compile Eris to be able to just drop it inside the OC .jar file, since the function names in the dll bundled with OC and those in the one compiled by myself are different, so it prints an error in-game "native libraries not available" when I try to use them (which is to be expected). Maybe the dll bundled with the game needs to be updated, or maybe it's an issue with the interaction between java and lua?

**Comment by Fingercomp** [comment]
The `__ipairs` metamethod was deprecated in [Lua 5.3](http://www.lua.org/manual/5.3/manual.html#8.2):

> The ipairs iterator now respects metamethods and its __ipairs metamethod has been deprecated.

So you should not use it anyway. Further, the native Lua 5.3 library used by OpenComputers is compiled without Lua 5.2 compatibility, so everything deprecated since that version is in effect removed. As a side note, the same happened to the `bit32` library, also deprecated since Lua 5.3.

**Comment by Kristopher38** [comment]
Oh, so it's dependent on lua 5.2 compatibility compilation flag, now it makes perfect sense why it could've worked in lua 5.3/latest 5.3 Eris, but not in OC, I did not know about this. It's a shame they removed it since now it uses __index metamethod which adds a lot of overhead because it first has to check if the provided index doesn't already exist in a table and only then it calls __index, so the iteration is in the order of tens times slower compared to using ipairs directly on the iterated object. I can still roll my own function returning an iterator so that's okay but I'll have to drop usage of `ipairs(t)` syntax in favour of `t:myOwnIterator()`.

**Comment by skyem123** [comment]
This does raise a question though... Should OC Lua 5.3 be compiled with Lua 5.2 compatibility?

**Comment by 20kdc** [comment]
The missing bit32 definitely causes interesting unexpected compatibility issues.
