### ISSUE TITLE
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes

### ISSUE THREAD

**Issue by Azim** [MightyPirates/OpenComputers#3261]
Made an app to scan for ores using Geolyzer, and then displaying the results on OpenGlasses:
https://pastebin.com/dSR9ASLg

However it just crashes my save with "java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes" after some long wait.
[latest.txt](https://github.com/MightyPirates/OpenComputers/files/4399320/latest.txt)

The geolyzer is located inside the Tablet

**Comment by Azim** [comment]
Appears to be an issue with OpenGlasses and the amount of 3d elements it can draw

**Comment by payonel** [comment]
sounds like an issue with OpenGlasses, perhaps you need to break up the render calls

**Comment by DaeTheFlame** [comment]
Has anyone made any other cool apps with the Open glasses mod?
