### ISSUE TITLE
drone.suck() not working

### ISSUE THREAD

**Issue by joshop** [MightyPirates/OpenComputers#3263]
I'm trying to make an automated delivery system using drones and it's going great except for the "pickup" part. My drones are unable to retrieve items from chests using drone.suck() or inventory_controller.suckFromSlot(). With suckFromSlot() it does error if the drone is not above a chest but it doesn't actually retrieve it. They can still retrieve dropped items using drone.suck(). Is this intended behavior? I'm running MC 1.12.2 and OC 1.7.3.146.

**Comment by payonel** [comment]
try lifting the drone a half block or a bit more higher - sometimes suck gets a block too low if it is flying in the same block as the object you're sucking from
