### ISSUE TITLE
Issue with schematic and vanilla clone command when applied energistics is installed with open computers

### ISSUE THREAD

**Issue by brom10** [MightyPirates/OpenComputers#3264]
Minecraft version 1.12.2

So I'm not sure if I should have posted this issue at the applied energistics github instead, but since my problem is with an open computers block I decided to start here.

When opencomputers is installed WITHOUT applied energistics, the vanilla /clone command, as well as schematics is able to copy computers along with the components inside. However when applied energistics is installed alongside opencomputers, both schematics and the vanilla /clone command say that an unknown error occurred, and place a computer case without any components inside. Other tile entities such as chests appear to work fine, and retain their contents. 

Steps to reproduce:
1. Install opencomputers and start a world.
2. Place a computer case and place a component such as a hard drive inside
3. Use the /clone command to clone the computer case to another area, and note that the contents remain the same.
4. Install applied energistics along with opencomputers and open a world
5. Repeat steps 2 and 3, except now the command will say "An unknown error occurred while attempting to perform this command" however the case will still be placed, and the contents of the case will be empty

Again sorry if this is actually an applied energistics issue not an opencomputers issue.

**Comment by payonel** [comment]
It's not an expected feature that OC machines can be cloned this way. components need a generation step, such as during crafting, so allow us to uniquely identify the objects
