### ISSUE TITLE
Problem with Lua Code

### ISSUE THREAD

**Issue by tigerboy985** [MightyPirates/OpenComputers#3268]
I have wanted to install this program into my base: https://pastebin.com/wA3Nz2YC. I tested in gmc and it worked, I then went on my survival world and created all the same components, did the same stuff I did in gmc but I get an error whereas in gmc it works fine. 

![image](https://user-images.githubusercontent.com/43861729/78504397-d6a82480-7764-11ea-891b-1850eb55f926.png)

**Comment by tigerboy985** [comment]
![image](https://user-images.githubusercontent.com/43861729/78504640-5f739000-7766-11ea-9d0b-10ea9730e465.png)

**Comment by payonel** [comment]
we accidentally left bit32 in the global env in previous versions of openos and some projects errornously used it, when they should have require'd it
you can fix their code by adding: `local bit32 = require("bit32")` at the top of their source file `/etc/rc.d/clock.lua`
