### ISSUE TITLE
No "func" entry in debug.getinfo(1)

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#3269]
I am trying to get F-Strings working with the OpenComputers however I face the issue that the script for F-Strings tryies to access ```debug.getinfo(2, "f").func``` however that entry is missing. Whenever I go to an Online Interpreter for either Lua 5.1.2 or 5.3 (can't find 5.2 online) there is the ```"func"```. Am I just missing something or would the implementation be to difficult / a security vulnerability or something else?
![func not working](https://user-images.githubusercontent.com/52219957/78887657-87ae0800-7a60-11ea-89e2-65e1fc3f4f0a.png)
![func working](https://user-images.githubusercontent.com/52219957/78887660-8a106200-7a60-11ea-8baa-e87cf629cf0b.png)

**Comment by Fingercomp** [comment]
https://github.com/MightyPirates/OpenComputers/blob/b9cc1663b262816c8c1f271ef6b8eb9850523462/src/main/resources/assets/opencomputers/lua/machine.lua#L972-L991

If the `func` field was not omitted, one could circumvent the sandbox and access native functions directly.

**Comment by ghost** [comment]
Would there be any way for me to get the ```func``` field in Singleplayer or perhaps multiplayer? And what security Issues would that pose?

**Comment by Fingercomp** [comment]
Open `assets/opencomputers/lua/machine.lua` in the mod jar and add `func` to that table analogously to the other fields.

As for the security issues...

```lua
local nativeLoad

load(function()
  for i = 0, math.huge do
    local frame = debug.getinfo(i)

    if not frame then
      break
    end

    if frame.name == "load" and frame.source == "=[C]" then
      nativeLoad = frame.func
    end
  end
end)
```

Now you can run arbitrary bytecode using `nativeLoad`. Since Lua does not validate the bytecode, this is a really dangerous security vulnerability if you're doing it on the server.

**Comment by SquidDev** [comment]
It's worth noting that F-strings also depends on `debug.getlocal`, which isn't (fully) supported by OC for similar security reasons. While you can also expose the original definitions of those, it's probably easier just to use `string.format`, even if it is less convenient.

**Comment by ghost** [comment]
Thank you for the great feedback. I will definatly stick to ```string.format``` because of obvious reasons. Thank you two!
