### ISSUE TITLE
Switch/Access Point Message Spamming/Too Long Delay

### ISSUE THREAD

**Issue by TorakWolf** [MightyPirates/OpenComputers#327]
I was using them as Computercraft peripherals, and every time I sent one message, It got spammed 5 times when I set to one computer to print it. Also, can I serialize one table via CC, the send the string, and unserialize via OC?

**Comment by TorakWolf** [comment]
*then send the string ( edit option do not work on Android ).

**Comment by TorakWolf** [comment]
Also, what I mean with spamming is something like using:

while 1==1 do 
_,_,_,_,_,_,msg = event.pull()
print( msg )
end

...then getting 5x msg instead of 1 time then wait for the next one.

**Comment by fnuecke** [comment]
Sounds like you have a loop in your network, in which case that's expected and intended behavior. Network packets have a TTL of 5 hops, so this sounds like the switch is forwarding it those 5 times.

**Comment by TorakWolf** [comment]
...That makes my radar screen ( openperipherals sensor + cc computer + switch + oc computer and screen ) impossible, 3 seconds for every message is too much...

**Comment by fnuecke** [comment]
You're probably doing something wrong then, packets are relayed every five ticks, so a single switch at most adds a delay of 250ms. Bounced through 5 switches that's barely over a second. If it's from CC -> OC the package is even be sent immediately from the switch connected to CC (i.e. if the switch relays an existing packet it delays, if it 'creates' one - via CC - it's immediate).

Post a screenshot of your setup.

**Comment by marcin212** [comment]
![example](http://starchasers.pl/oc/network.png)

Programs:
1- while true do print(event.pull()) end
2- http://pastebin.com/6vFyyqa4 spamming to computer 1
3- http://pastebin.com/vfcGS8RC
4- http://pastebin.com/wPjLPJt8 pinging to computer 3

spam sleep                                      |   ping time
 without                                                |       1,2s
    0,5                                         |       3,09s
    0,3                                         |       4,59s
    0,2>                                                                            |  not responding
    0,5 + additional message(random string)                     |        5s

**Comment by TorakWolf** [comment]
My setup is: 

![2014-06-16_16 38 59](https://cloud.githubusercontent.com/assets/6556973/3292319/e84aa636-f58d-11e3-94f7-34501abefb22.png)

Actually I sent one message from cc to oc system with transmit method wrapping the switch as one peripheral, then set to receive message, print and wait 0.3 seconds to receive another. Still printing 3 messages instead of 1. So, are you sure EVERY message uses 0.050 seconds instead of 0.250?

**Comment by fnuecke** [comment]
@marcin212 Interesting. On the timings (in particular the 0.5 one), did you make sure to give the network time to recover after the 0.2 test? Either way, this is kind of a mix of two things, one a pseudo-racing condition that delayed packet resending if a new packet arrived at a bad time, two, well, congestion. That there's no response at 0.2 is to be expected, since anything faster than 0.25s will fill up the buffer in switches faster than they can empty it, so the chance to get in is pretty small. The other timings were probably higher than they should (except the 1.2, that's exactly what's to be expected) due to aforementioned issue.

@TorakWolf, could be the initial enqueing takes 0.25s, yeah. That's nowhere near 3 seconds, though? Where's the keyboard? Above the server rack? Then that's where your cycle causing the multiple messages is (racks act as switches and power distributors).

**Comment by TorakWolf** [comment]
Hum, I still get 2-3 messages even sleeping 0.5 seconds between receiving every message... Sleeping 1.15 seconds works. but that's too much if compared with 0.250...

**Comment by fnuecke** [comment]
Can you post a shot from the other side?

**Comment by TorakWolf** [comment]
Hum, I'ts just one networking cable, with some wired modems... the switch is only connected to one modem and one OC cable. But anyways, I changed to something simpler like that:

![2014-06-16_18 33 28](https://cloud.githubusercontent.com/assets/6556973/3293680/e3b7e0e2-f59d-11e3-8673-2d7439199970.png)

and set to receive message, print and wait 0.3 seconds then waiting again for messages, and still get 2-4 messages...

Note: I Finished My Radar Code, but It will be good to update the screen every 0.25 seconds instead of 1.15 - 1.25...

**Comment by fnuecke** [comment]
I meant the other side. I.e. the inverse angle of that shot.

**Comment by TorakWolf** [comment]
I know, but since I changed the design, I just said "there's nothing special on it", as I was too lazy to rebuild the whole thing :P.

**Comment by fnuecke** [comment]
Well, apparently there is, or you wouldn't be getting the message multiple times ;-)

Here is what I'm suspecting the other side looks like, which would be causing the loop:
![](http://i.imgur.com/rAHRfYL.png)
And here's how it should be:
![](http://i.imgur.com/UyULP65.png)
that is, no keyboard over the server rack.

**Comment by TorakWolf** [comment]
Oh... Sorry and thanks!
