### ISSUE TITLE
CC: Tweaked not receiving messages.

### ISSUE THREAD

**Issue by Lennart247** [MightyPirates/OpenComputers#3270]
I'm trying to send a message from a OC computer to a computer from CC:Tweaked in MC 1.12.2. For that I connected a relay to a CC computer. When sending a message the relay flashes (receives the message?) but the computer doesn't seem to receive the message, as is doesn't react in any way.
![2020-04-09_17 37 42](https://user-images.githubusercontent.com/20297308/78914134-4a5e7000-7a8a-11ea-8e40-9f265f039fcc.png)
![2020-04-09_17 37 44](https://user-images.githubusercontent.com/20297308/78914144-4cc0ca00-7a8a-11ea-8054-f69ff3b31856.png)
![2020-04-09_17 37 50](https://user-images.githubusercontent.com/20297308/78914152-4f232400-7a8a-11ea-9e23-7091a630feee.png)
![2020-04-09_17 37 54](https://user-images.githubusercontent.com/20297308/78914156-50ece780-7a8a-11ea-96e4-5b8527d480f4.png)
![2020-04-09_17 38 01](https://user-images.githubusercontent.com/20297308/78914161-51857e00-7a8a-11ea-87b6-7e1bc0322932.png)
![2020-04-09_17 38 07](https://user-images.githubusercontent.com/20297308/78914162-52b6ab00-7a8a-11ea-8acd-fe81e61a707c.png)
![2020-04-09_17 38 17](https://user-images.githubusercontent.com/20297308/78914171-53e7d800-7a8a-11ea-846e-a63ca90d3892.png)

 I don't know whether this is your fault, or SquidDevs, or whether I connected something wrong, or intended behaviour.

**Comment by payonel** [comment]
i dont know how to receive/send messages between cc and oc, but - on the oc side you only need to open ports you plan to read, no need to open ports when writing to them
however, I dont plan on adding more inter-mod support to 1.12 at this time. i'm happy to help trouble shoot, ask us on our irc: #oc on esper net
