### ISSUE TITLE
More realistic Component Comunication

### ISSUE THREAD

**Issue by Digifox03** [MightyPirates/OpenComputers#3272]
# Better Component Comunication Proposal

## Rationale
Currently comunication between Computer and Component is extremly painfull in real archs. To alleviate the comunication problem for real archs i propose a better and more realistic component communication.

## Difference between OC and Real Computers
In OC, to connect a component to a computer, you must have the component in the same network as the computer, either by being placed next to the computer or by being connected thought cables. Once the component is in the same network it can be accessed by the computer by addressing it by its UUID.

In a real computer the components are connected to the computer in many different ways, mostly for legacy reasons. For simplicity i will consider only one of those which is generic enought to be adapted for OC, PCI.

From the point of view of the processor there can be up to 256 busses, each bus can address up to 32 components and each component can have up to 8 functions. For comunication the processor is connected to the PCI host bridge, each component connected to the PCI host bridge is accessed from the bus 0. To allow the connection of more than 32 components to the computer another PCI bridge can be connected to the PCI host bridge (or to another PCI bridge) and the components connected to it can be accessed on other busses depending on how the processor configures them.

## OCCI -- Open Computer Component Interconnect
The new way that computers will use to communicate with components is OCCI. there are 256 Busses and each bus can have up to 32 components. OCCI addresses use the following format: `XX:YY.Z` where `XX` is the bus id, `YY` the component id and `Z` is the component function, all numbers use hex. Each computer always has a special component called "OCCI Root" which is always mapped at `00:00.0`. This component allows to configure the other OCCI bridges. bus `00` addresses from `01` to `0F` and all other busses addresses from `00` to `03` are reserved for internal use by the architecture. Bus `00` maps the components directly connected to the computer while the other busses maps the components connected to bridges.

## Possible implementation
Components connected to the network will keep their UUIDs. The case GUI will have a new page, the wirings page, which, when the computer is off, allows assigning UUID addresses to the computer's OCCI addresses. Currently the installed processor limits how many components can be connected to th computer otherwise it won't be able to boot, instead the number of components that can be accessed by a computer can be limited in the wirings page by limiting the number of usable OCCI addresses.

## Interfacing with LUA
To interface the new protocol with the LUA arch without breaking most of the existing code the Component Address can be modified to use OCCI addresses instead of UUIDs

## Some problems and their solutions
With the OCCI protocols the connected components cannot be changed while the computer is running, but some components might require so to be usable (e.g. The floppy). The solution is to update the Disk Drive functionality: Instead of having the floppy as a component and accessing it directly, it has to be accessed thought the Disk Drive.

**Comment by skyem123** [comment]
I am gonna nitpick some things... Hopefully that's okay! ^^;

-----

* Having to manually map components to UUIDs sounds like a pain

-----

> To interface the new protocol with the LUA arch without breaking most of the existing code the Component Address can be modified to use OCCI addresses instead of UUIDs

Doesn't that contradict mapping UUIDs to addresses?

-----
> Instead of having the floppy as a component and accessing it directly, it has to be accessed thought the Disk Drive.

This would definitely break compatibility with existing software.

-----

Overall it is an interesting idea but would definitely need some refinement to work properly.  
My suggestion: Maybe have UUIDs in addition to OCCI addresses? Different arches will have different "optimal" ways to access them.

**Comment by Digifox03** [comment]
Ops, i should have been more clear.

---

> Having to manually map components to UUIDs sounds like a pain

UUID have to somehow be mapped to OCCI addresses, but not necessarely manually.

For example there could be an item that when used on a component will write all the info about the component comprised of the UUID which can be marked with `copy_on_clipboard`.

Or an item which you can use to select a computer and a component and will open an UI to select to which address to connect it to.

Or just a list of visible components in the wiring page which can be drag and dropped to the OCCI address slot

---

> To interface the new protocol with the LUA arch without breaking most of the existing code the Component Address can be modified to use OCCI addresses instead of UUIDs
>> Doesn't that contradict mapping UUIDs to addresses?

when i said Component address i meant the address you give to `component.invoke(address, method, ...)` and get from `component.whatever.address`

---

>Instead of having the floppy as a component and accessing it directly, it has to be accessed thought the Disk Drive.
>>This would definitely break compatibility with existing software.

Again, i wasn't clear.
it will make use of multifunction devices (i.e. the Z part of the address):
let's say that the Disk Drive is at `00:0A.0` then when a floppy is inserted it appears at `00:0A.11`.
From LUA point of view (hopefully) nothing has changed

---

>My suggestion: Maybe have UUIDs in addition to OCCI addresses? Different arches will have different "optimal" ways to access them.

That seems a good idea, although OCCI have some advantages over UUIDs, the primary component can be determined more easily (the first component of each category, since they have an explicit order) and in the case of having more components than the computer can handle in a network is simply solved by selecting which components to connect.

**Comment by gjgfuj** [comment]
An inability to change components while the computer is running is a major
flaw, so it would be wise to change it in some way where you can modify
components at runtime.

**Comment by skyem123** [comment]
I think moving away from UUIDs for the existing Lua arch would break things... So for Lua addresses should still be UUIDs, but there should be a function that translates OCCI addresses into UUID addresses?

**Comment by Digifox03** [comment]
> An inability to change components while the computer is running is a major
flaw, so it would be wise to change it in some way where you can modify
components at runtime.

You cannot connect, or worse disconnect, a component directly connected to a computer while it is on, but what you can do is having another component that allows connecting and disconnecting (like usb ports).

---

>I think moving away from UUIDs for the existing Lua arch would break things... So for Lua addresses should still be UUIDs, but there should be a function that translates OCCI addresses into UUID addresses?

i don't think that replacing UUID address with OCCI address would break the code. The only thing that changes is that all functions that would have returned or that would accept an UUID address now will return/accept OCCI addresses, so all code that treats the component address as an opaque value won't see any difference. The only code that would be broken is code that manipulates UUID or stores the UUID in persistent storage, which i see no reason to do so.

**Comment by payonel** [comment]
I understand this proposal would make OC more real-life like, but I don't see what problems it solves. 

Keep in mind that making something easier for real archs is not our primary goal, but rather an important secondary goal.

A work around is that you could map components to bus addresses when the machine is starting (before eeprom). You can query the components via component list, you could sort the uuids, and map them to bus addresses. you could also list and sort their available methods and map those. Sounds like this could be a fixed component bus configuration until you reboot. You could even add to your arch a machine api that allows the kernel to remap bus addresses to give the system the option to reorder things as the kernel sees fit (so no new UI is needed)

Anyways, we won't be making this type of change to our addressing system
