### ISSUE TITLE
Pastebin changed something their end

### ISSUE THREAD

**Issue by baconjuggling** [MightyPirates/OpenComputers#3273]
I have been failing to download a pastebin script for days with the latest update for 1.12.2

After noticing i had the same issue with computercraft I posted around on reddit.

A CC dev alerted me pastebin has made some changes their end and he is having to revert some of their code. 

I think that's why I'm having issues.

**Comment by payonel** [comment]
just tested with our release build on 1.12: https://www.curseforge.com/minecraft/mc-mods/opencomputers/files/2828357
it works fine for me
`pastebin get 9hbHuYWv test.txt`
(note, i can reopen if you can provide some repro data that shows the failure details)
