### ISSUE TITLE
Improve Applied Energistics integration

### ISSUE THREAD

**Issue by TomatoCo** [MightyPirates/OpenComputers#3274]
There is currently no way to cancel a crafting job in Applied Energistics 2. I would like the following improvements:

Methods on the Crafting Status object: Items remaining, estimated time remaining, and a function to cancel the job.
Methods on the result of getCpus: Items remaining, estimated time remaining, ItemStack information for the item being crafted, and a function to cancel the job.

**Comment by payonel** [comment]
in adding more support for AE i found all kinds of problems, it was a complete mess
i've fixed up our AE integration quite nice, i feel our crafting support should be quite strong now

before any type of chunk saving/reloading would throw our crafting objects out of sync, that is all solid now

added (and i'll add docs for this eventually):

* me_controller.isNetworkPowered
  - function():boolean -- True if the AE network is considered online
* me_controller.getEnergyDemand
  - function():number -- Returns the energy demand on the AE network
* craftable.requesting
  - function():number -- Returns the number of requests in progress.
  > Please note, this is on the craftable object returned by getAllCraftables() and NOT the crafting status object you get back from `craftable.request()`. The reason here is because of AE, the api gives us data about the crafting type and its current outstanding craft requests, but not on a specific job.
* crafting_status.cancel
  - function():boolean -- Cancels the request. Returns false if the craft cannot be canceled or nil if the link is computing
  > This new api is on the crafting status response object you get from `crafting.request()`, that is the job status, and you can cancel the job

I did not add a method for measuing time, that can be done in lua code
I did not add more api on the cpu, as AE does not provide it. isBusy is all we have
