### ISSUE TITLE
OpenComputers can't get to show something on the screen

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#3277]
I try to use print in autorun.lua, don't work. Try to use gpu.set, don't work. Tier 3 pc and screen and all parts are installed. Why can't i show something on the screen?

**Comment by payonel** [comment]
please ask in the irc channel for mod support, unless you have a specific reproducible bug to report here

**Comment by payonel** [comment]
also https://ocdoc.cil.li/tutorial:autorun_options
