### ISSUE TITLE
Question about the invoke method in the modding API

### ISSUE THREAD

**Issue by IamTheCarl** [MightyPirates/OpenComputers#3278]
The method in question: https://github.com/MightyPirates/OpenComputers/blob/b9cc1663b262816c8c1f271ef6b8eb9850523462/src/main/java/li/cil/oc/api/machine/Machine.java#L245

I am writing a custom arch. I'm working on figuring out how to handle the values returned from this function. It looks like your official LuaJ arch uses LuaValue.varargsOf to convert the result into something Lua can make use of.

So would it be safe to assume that if my arch supports all of the LuaValue types, my arch should be complete and able to interface with all peripherals?

Note, these are the types that implement LuaValue:
IoLib.File       // Maybe?
LuaBoolean
LuaFunction  // Will not support
LuaNil
LuaNumber
LuaString
LuaTable       // Maybe?
LuaThread    // Will not support
LuaUserdata // Will not support

**Comment by payonel** [comment]
tables are often returned, and userdata is important for some result, such as filesystem handles. you're probably going to ask for more info about userdata :) you could hold the userdata in your machine arch and pass an object you use as a key to reference the userdata when the user code tries to use it. keep in mind that userdata is just raw pointers, no methods. but they are passed as args (such as filesystem.write(userdata_handle, ...))
if you'd like more info, chat with us in our irc channel
