### ISSUE TITLE
attempt to concetanate nil value

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#3280]
Here is there screen shot of my code: 
![2020-04-25_16 32 54](https://user-images.githubusercontent.com/27305378/80281293-bf7ca700-8712-11ea-98e0-a60649db7b44.png)

**Comment by payonel** [comment]
on line 35(?) of your for loop range is 0,2. lua arrays start at 1, not 0. so i would expect t[0] is nil
also, this is a good question for our irc channel, not github issue
