### ISSUE TITLE
Lua 5.3 Invalid key to 'next'

### ISSUE THREAD

**Issue by MrJake222** [MightyPirates/OpenComputers#3282]
Hi, I'm trying to add a OC support for my mod but I get `nil "Invalid key to 'next'"` error when calling this function:
```
@Optional.Method(modid = "opencomputers")
@Callback
public Object[] getEnergyRequiredToDial(Context context, Arguments args) {
	if (args.isTable(0)) {
		Aunis.info(args.checkTable(0).toString());
	}

	return new Object[] {};
}
```

In Lua 5.2 mode everything is ok. Any help on this one?

**Comment by payonel** [comment]
the root problem is the same we face here: https://github.com/MightyPirates/OpenComputers/issues/2448 - 
and now it is almost 3 years later and we still haven't updated our jnlua - we really need to do that

the problem has been that updating jnlua caused many other issues for us

I'm surprised this code of your fails though, we can generally get aroudn the problem by making sure to not call next() on the table, but access keys specifically

closing this as dup of #2448 

please message me on our discord if you would like some help mitgating this problem, it is possible as long as you dont need to call alls pairs on the table on the java side

**Comment by MrJake222** [comment]
Using `table.unpack` on Lua side and iterating manually through all (now separate) parameters seems to work.
