### ISSUE TITLE
api sugestion

### ISSUE THREAD

**Issue by emilyvans** [MightyPirates/OpenComputers#3283]
sugestion for api so that you can make custom cpus

**Comment by payonel** [comment]
you can, see https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/java/li/cil/oc/api/machine/Architecture.java

and compare with our lua implementation: https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/machine/luac/NativeLuaArchitecture.scala
