### ISSUE TITLE
Expose the complexity limit on robots/drones/uC for assembly

### ISSUE THREAD

**Issue by InfinityGosha** [MightyPirates/OpenComputers#3292]
It would be excellent if complexity limit in assembly would be configurable. For servers, in settings.conf perhaps. Thank you!

**Comment by Kristopher38** [comment]
I second this, it would be quite useful to be able to modify complexity limits to allow assembling devices with more parts (for example for debugging purposes), but without infinite power that comes with using creative cases.

**Comment by xarses** [comment]
So my $0.02 (and please take it for that as a drive by) Maybe the cases / drones / micro all have this configuration, bonus, all of the tiers for this are a config array and color mask so we can add additional tiers if we so desire

**Comment by EnLoz** [comment]
Well, it will be great, because it's unable to build a healer drone without cfg for tool using.

**Comment by payonel** [comment]
PR if interested
