### ISSUE TITLE
VLANs

### ISSUE THREAD

**Issue by Bjonnfesk** [MightyPirates/OpenComputers#3293]
Hello,

I have played around a bit with servers and server rooms, and while the mod as a whole is great, I find that the networking part is a little bit disappointing. It could be made almost infinitely better and easier to work with if VLANs were supported. Imagine:

- A server rack could, instead of the slightly strange system of connecting servers to sides of the rack, simply connect to a single network cable with 4 VLANs, and network separation between the servers would be maintained. 
- Furthermore, that does away with server racks that have cables coming out from all - 1 sides (4 for the different networks, 1 for power), allowing you to stack the racks on top of and next to each other, like a real server room.
- The VLANs could be colour-coded with Mindcraft's good old 4-bit colour system, running on top of OpenComputers' pre-existing coloured network cables, allowing for 16² = 256 different networks (White-White, White-Orange, ... Orange-White, Orange-Orange, ... Lightblue-White, Lightblue-Orange ...).
- Wireless clients could of course support it too.
- Defining which VLAN a machine connects to could be done through right-clicking the "connector" between the network cable and the machine.

Pardon me if this has been suggested before, I am on the mobile client OpenHub, which has very limited search capabilities (by which I mean it can't search at all).

Your humble servant,
Bjonnfesk

**Comment by payonel** [comment]
Let's talk specifically about the modem message network, and not the component network -- the solution is to plan to use a range of unique ports for each blade. then they can share the same modem network. This is not as advanced as  you are asking, but it has worked well for many users

**Comment by Bjonnfesk** [comment]
The **idea** was to use it to separate component networks. Your suggested solution doesn't accomplish that. You still have to make sure the computer connects to the right screen, etc. **That** is what I find disappointing, it feels so clunky.

**Comment by payonel** [comment]
component networks is an entirely different problem than modem networks. i agree this is clunky
