### ISSUE TITLE
pastebin program ignore some lines.

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#33]
http://pastebin.com/raw.php?i=qCdLgfhE

in line 710, `_0[10] = function(_55, _56)` are ignored.
when execute `pastebin qCdLgfhE py` and run `py`

test with v1.1.0pr1 and memory 1024 KB environ.

**Comment by fnuecke** [comment]
Seems to be a derp in the way HTTP responses are enqueued. Will be fixed when #21 is closed (which is what I'm working on right now).

Also: python interpreter? Sweet!

**Comment by ghost** [comment]
OK. close.
