### ISSUE TITLE
Computer Screens outlines become redish 

### ISSUE THREAD

**Issue by big-lip-bob** [MightyPirates/OpenComputers#3302]
![](https://cdn.discordapp.com/attachments/125649403162656768/710928945146626098/unknown.png)

Was just leaving and then rentering the chunk and the screens outlines became red.
Relogging makes the outlines white (normal) again.
Can be reproduced by leaving and rentering the chunk constnatly.
OC 1.12.2 Build 201. Forge 14.23.5.2847. Optifine in. (and many other mods)

**Comment by big-lip-bob** [comment]
May rebecome white after a while too, it wasn't as consistent now that i redo more tests

**Comment by payonel** [comment]
could not repro  this, and word is this is due to mods that modify opengl behavior (see OpenGlasses and optifine)
