### ISSUE TITLE
[QUESTION] ETA for mc 1.15.2?

### ISSUE THREAD

**Issue by sigmasoldi3r** [MightyPirates/OpenComputers#3304]
Hello there, thanks for this big mod!

The question is simple, is there an ETA for Minecraft 1.15.2 version?
If not, how can I contribute?

I've read this gist https://gist.github.com/williewillus/30d7e3f775fe93c503bddf054ef3f93e so if it's a matter of refactoring I could give a hand, but probably there's more than just refactoring...

Cheers!

**Comment by sigmasoldi3r** [comment]
I've been trying to update since I've posted this issue with no luck; I can't get past the gradle sync step, everything breaks, so I don't know where to start 😓

**Comment by payonel** [comment]
I appreciate the interest! :) Our plans are still internal, thanks
