### ISSUE TITLE
Clean Server setup ?

### ISSUE THREAD

**Issue by capsload2** [MightyPirates/OpenComputers#3307]
Hey guys,

is there any server with everything setup (forge.jar, opencomputers.jar) and all that stuff, so i just need to upload it on my Linux Server, so i can host it?

**Comment by payonel** [comment]
this is a good question for our irc channel or forums, but a "bug" to report on github
you download forge here: http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.12.2.html

you can download opencomputers here: https://www.curseforge.com/minecraft/mc-mods/opencomputers/files

you can also try out dev builds: https://ci.cil.li/
