### ISSUE TITLE
Upgradeable Switches

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#331]
Well, put some Cpus in to make it relay stuff faster, put ram in to make the buffer bigger.
(Idea came when playing around with network, switches are slower than my old Win95 machine)

**Comment by fnuecke** [comment]
Hmm, while higher tier switches would be a little more consistent, I actually kind of like this idea, would give CPUs another raison d'être.

**Comment by TorakWolf** [comment]
Yeah, switches are pretty slow...

**Comment by Wuerfel21** [comment]
Would really like to make a benchmark battle: Win95 Machine with 128M Ram vs. OC Switch, who is faster in redirecting messages. Sadly im missing my VGA Cable

**Comment by Kubuxu** [comment]
Win95 for sure. You won't have 1k ping after two hops.

**Comment by fnuecke** [comment]
Definitely Win95, no need to benchmark ;-) Switches are intentionally slow, to avoid lagging the server by spamming messages, and to make designing networks more interesting.

**Comment by Wuerfel21** [comment]
Well but OC is approx. 1000 times more stable

**Comment by TorakWolf** [comment]
Got the idea... So since switches also relay messages to/from cc computers, they use not only the oc thread, but a little of JVM as well. Stoping to think, cc must be one memory eater then...

**Comment by Kilobyte22** [comment]
Ok, i am going to work on this tomorrow, given i find time. I got a pretty busy day tomorrow. otherwise on sunday

**Comment by fnuecke** [comment]
Continued in #373.
