### ISSUE TITLE
CPU's not recognizing each other

### ISSUE THREAD

**Issue by keebster** [MightyPirates/OpenComputers#3310]
The CPU's Item number 5933/0 /1 and /2 Do not see the tier below it within the system.

We are using a Refined Storage computer system. I can create the 5933/0 Item as it doesnt require another cpu. But the 5933/1 does not recognize the pattern or the item of 5933/0 in the computer. and the 5933/2 does not recognize the pattern or the item 5933/2

I have tried to make different items that require those CPU's and none of them seem to work.

I have also sent this issue to Refined Storage just encase its an issue with their system.

**Comment by payonel** [comment]
i dont really follow
are you trying to define a getAllItemsInStorage filter?
please provide repro steps, and all the lua code youre writing
what blocks are you using with refined storage

**Comment by keebster** [comment]
I figured out to get it working. Manually create the pattern and not use the Plus sign. And turn off Ordict
