### ISSUE TITLE
`tablet_use` broken when analyzer is installed

### ISSUE THREAD

**Issue by Faeranne** [MightyPirates/OpenComputers#3313]
Title more or less spells it out, but basically when you install a analyzer into a tablet, the tablet_use event won't fire on anything except blocks with an OC address.  Data from the geolyzer will show up, but the event won't fire for normal blocks.

Tested on 1.7.5.192

**Comment by Fingercomp** [comment]
I think this is the bug that #3286 fixes. You can try running [a dev build](https://ci.cil.li/job/OpenComputers-MC1.12/) or wait for the next release.

**Comment by Faeranne** [comment]
Looks like it.  I'll download and test it tonight, and close the issue if that is the case.
