### ISSUE TITLE
Persistent RAM

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#332]
did you ever play hours and hours playing a game, to get to a new Highscore and you were so close to it and then your nuclear reactor gone BOOM and the computer ran out of energy? Basically a type of ram(with less capacity as normal ram) which can survive powerdown(expect shutdown/reboot) would be sufficient

**Comment by Xfel** [comment]
that would be difficult to implement; what if you use that persistent type ram together with normal ram? The way memory management is coded, you have no way to determine what goes to which part of the RAM.

I'd rather suggest building a power backup store (IE with the capacitor blocks) or building a better reactor system that doesn't go BOOM.

**Comment by TorakWolf** [comment]
"did you ever play hours and hours playing a game, to get to a new Highscore and you were so close to it and then your nuclear reactor gone BOOM and the computer ran out of energy?"

Did you ever played one game using OC or CC for anything but fun? I don't! So don't bother about that...

**Comment by Wuerfel21** [comment]
@Xfel Just use persistant memory and display an warning message.
@TorakWolf that was just an example, you could use it for so many useful stuff

**Comment by LordFokas** [comment]
Actually, no, the only use it has is so that people can be lazy when power goes down.
Instead, in current implementation, if your RAM's contents are important to you you should engineer a robust power distribution network. (Spoiler: that's where the fun is).

**Comment by Wuerfel21** [comment]
The main use i thought of were robots, but maybe i can implement this in software

**Comment by TorakWolf** [comment]
Well, so maybe one linked memory, just like linked cards, everything that happens with X computer, happens with the other. But actually you can recover your computers by saving the world and copying the state file in the saves/savegamename/opencomputers/state them changing the id of the old one to a new one.

But nothing can be done if you don't save the state beforehand...

**Comment by fnuecke** [comment]
Short answer: no.

Long answer: nooooooooooooooo ;-)

Serious answer: it's your job to ensure there are no power outages. For robots, you can indeed check the energy level regularly and perform an emergency shutdown when necessary, saving your current state to disk. Or find some other, clever workaround ;-)
As for the 'linked memory', aside from being kind of weird, that's just not very doable. Yes, you can transfer states by copying stuff around in the state folder, but as you kind of implied, that only works while the related computers are unloaded. This isn't even comparable to trying to synchronize running computers. And even then, addresses of components would be different, so the whole state is meaningless anyway.

**Comment by rmellema** [comment]
Shameless plug: If you want to know when your robot is almost out of energy, a few months ago(time goes fast :/) I wrote a small program/library to do just that. You can find it [here](http://oc.cil.li/index.php?/topic/8-energyd/). If you have any questions about it, you can ask them in that thread.
