### ISSUE TITLE
GIVE ME A COOKIES

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [MightyPirates/OpenComputers#3323]
GIVE ME A COOKIES

**Comment by payonel** [comment]
passthrough from host? that's not the intent of this mod. there are config options to increase limits on cpu, ram, and gpu calls. play with those if you need more

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
GIVE ME A COOKIES
