### ISSUE TITLE
Robot not using correct floppy disk file

### ISSUE THREAD

**Issue by luznaturalny** [MightyPirates/OpenComputers#3325]
Video explanation: https://www.youtube.com/watch?v=jN_xJVLNGKI&feature=youtu.be
I am constantly moving my floppy disk from a disk drive to the robot, doing changes while it's in the disk drive. Sometimes the file I edit with the disk drive is not the one being loaded in the robot and I have to make a new floppy disk and copy the file to the new floppy disk for it to work again.

**Comment by luznaturalny** [comment]
Discovered something else
Maybe this helps you troubleshoot it
https://youtu.be/ampWafGEDEU

Seems like I can still access the file even though it's not in the disk drive

**Comment by payonel** [comment]
try disabling the buffer file writes in our config.
