### ISSUE TITLE
lua crash

### ISSUE THREAD

**Issue by Gunni** [MightyPirates/OpenComputers#3330]
<removed by developer>

**Comment by skyem123** [comment]
Hm... This means the Lua 5.3 arch needs to be updated to 5.3.4 or later, and the Lua 5.2 arch needs to be patched somehow...

**Comment by payonel** [comment]
I've removed the detail of the crash as this can cause unnecessary crashes for the community. I've noted the details privately. In the future, please provide this concerns in a private message directly to our maintainers

**Comment by asiekierka** [comment]
Fixed in OC 1.8.0-pre1, across all three Lua versions.
