### ISSUE TITLE
Establish a contact path for crash/security/dupe? type issues.

### ISSUE THREAD

**Issue by Gunni** [MightyPirates/OpenComputers#3331]
> I've removed the detail of the crash as this can cause unnecessary crashes for the community. I've noted the details privately. In the future, please provide this concerns in a private message directly to our maintainers

_Originally posted by @payonel in https://github.com/MightyPirates/OpenComputers/issues/3330#issuecomment-655623014_

I would have done so had I found any way to do so, but i just found this github.

So this issue is for: Establish a contact path for crash/security/dupe? type issues.

**Comment by payonel** [comment]
Just to let you know, I really appreciate the bug report!
On our README.md for this project, there is a link to us on irc and discord:
> If you have any questions, please do not hesitate to ask, either in the forums or in the IRC!
http://webchat.esper.net/?channels=#oc
