### ISSUE TITLE
Invalid char number in key_down & key_up events on MacOS

### ISSUE THREAD

**Issue by LemADEC** [MightyPirates/OpenComputers#3332]
As of OpenComputers 1.7.5.192 + Forge 1.12.2-14.23.5.2838, the key_down & key_up events are passing invalid character numbers when using a MacBook Air and pressing certain keys. As those numbers are above 255, a call to string.char() leads to a crash of the related LUA code.
The minecraft wiki fails to report such values, so is LWJGL from what I could find.

Here is the related documentation in OC: https://ocdoc.cil.li/component:signals?s[]=key&s[]=down
and Minecraft (up to 1.12.2): https://minecraft.gamepedia.com/Key_codes

Here's a non-exhaustive list of keys I've found so far to cause this issue:
Up arrow returns 63232 200
Down arrow returns 63233 208
Left arrow returns 63234 203
Right arrow returns 63235 205
Euro symbol returns 8364 27
Fn-Up arrow returns 63276 201
Fn-Down arrow returns 63277 209
Fn-Left arrow returns 63273 199
Fn-Right arrow returns 63275 207
Fn-Backspace returns 63272 211
Alt-Inferior (inferior or equal symbol) returns 8804 41
Alt-Superior (superior or equal symbol) returns 8805 41
Alt-O (oe symbol) returns 339 24
Alt-P (PI symbol) returns 960 25

In comparison, ComputerCraft doesn't return a character for arrow or symbol keys (i.e. the char event isn't sent for those).

From a quick check in the Unicode char numbers, the arrows are private while Alt-keys are the proper Unicode number.
I would suggest to either
A- update string.char() to actually support Unicode (converting back to the default codepage when it's above 255)
B- or update the events to returns 0 when the code is above 255 (using similar behavior as ComputerCraft).

**Comment by payonel** [comment]
string.char is not for unicode, it is for single bytes. see lua: https://www.lua.org/pil/20.html
use unicode.char for the OC char value given by key_*
the last num is the keycode, which appears to be working
