### ISSUE TITLE
Support for Thermal Dynamics conduit grids

### ISSUE THREAD

**Issue by exuvo** [MightyPirates/OpenComputers#3333]
Essentially i want to access the information the thermal foundations multimeter shows when used on a thermal dynamics conduit, it shows grid power stats like average power that went in or out the grid in the last 100 ticks.

The [meter](https://github.com/CoFH/ThermalFoundation/blob/2adfc5faf0483e918d6f471c2841120623fc9fb7/src/main/java/cofh/thermalfoundation/item/ItemMeter.java) in doMultimeterUseFirst() calls getTileInfo() which in this case goes to [TileGrid in thermal dynamics](https://github.com/CoFH/ThermalDynamics/blob/2bd74346a927a50bf053cb511adceeb8c883d2bb/src/main/java/cofh/thermaldynamics/duct/tiles/TileGrid.java)
Relevant parts in there are:
```java
for (DuctUnit ductUnit : getDuctUnits()) { // i don't think the loop is needed, they should all be part of the same grid?
  MultiBlockGrid grid = ductUnit.getGrid();
  if (grid != null) {
    info.add(new TextComponentTranslation("info.thermaldynamics.info.duct"));
    grid.addInfo(info, player, debug || TDProps.showDebugInfo);
  }
}
```
Relevant parts from [grid.addInfo in MultiBlockGridTracking](https://github.com/CoFH/ThermalDynamics/blob/3068b2f6d716950d3269a1c598194a49332fb7b3/src/main/java/cofh/thermaldynamics/multiblock/MultiBlockGridTracking.java)
```java
getTracker();

// they do some delayed shit so that the counter never shows 0 and is quickly removed again but not needed in open computers

addInfo(info, "tracker.avg", format(tracker.avgStuff()) + getUnit());
addInfo(info, "tracker.avgInOut", String.format("+%s%s/-%s%s", format(tracker.avgStuffIn()), getUnit(), format(tracker.avgStuffOut()), getUnit()));
```

In the code there it seems like getTracker() has to be called at least once per 3 minutes for the [tracker](https://github.com/CoFH/ThermalDynamics/blob/3068b2f6d716950d3269a1c598194a49332fb7b3/src/main/java/cofh/thermaldynamics/multiblock/Tracker.java) to remain running. We can leave that part up to the users lua program. On the returned tracker object the useful methods avgStuff(), avgStuffIn(), avgStuffOut() can then be called. The first time getTracker() is called it will be created and return 0 for the first tick but subsequent calls will show correct values as long as you call at least once per 3 minutes. Probably need to mention that in the Callback.doc and that the multimeter will reset the tracker when used.

I think the DriverSidedTileEntity does not need to much more complex than ex DriverLamp is. Just a Reflection.tryInvoke for getTracker() and then call the relevant method on the tracker.

I think this would work on all types of conduits (energy, fluid, item) but i am specifically only interested in the energy ones if that is simpler. All the duct types are created in [TDDucts](https://github.com/CoFH/ThermalDynamics/blob/cd8bd2efa292fa9d136891f96b0db4fcdb36c444/src/main/java/cofh/thermaldynamics/duct/TDDucts.java) with public static references and energy and fluid ducts share the same class.

Would the lovely developers of OpenComputers be able to do this?

**Comment by payonel** [comment]
closing as won't do, however, interesting idea. PRs welcome
