### ISSUE TITLE
无法解决的问题 

### ISSUE THREAD

**Issue by PTALTS-LK** [MightyPirates/OpenComputers#3335]
![Screenshot_20200719131003](https://user-images.githubusercontent.com/62936489/87896848-0fea7300-ca7c-11ea-9f42-c08fa21576e2.jpg)

**Comment by payonel** [comment]
we need github issues described in english please

**Comment by PTALTS-LK** [comment]
> 我们需要用英语描述的github问题

When I start the game, "Native Lua libraries are not available, computers will not be able to persist their state. They will reboot on chunk reloads."

**Comment by payonel** [comment]
what is the host operating system of the server? or if single player, of the client?

**Comment by PTALTS-LK** [comment]
> 服务器的主机操作系统是什么？或如果是单人游戏，则是客户？

Android

**Comment by PTALTS-LK** [comment]
> 服务器的主机操作系统是什么？或如果是单人游戏，则是客户？

It sounds impossible, but it does run on Android

**Comment by payonel** [comment]
sounds pretty cool :) but we don't have support for android - the mod will still work, but without native lua (only luaj)

**Comment by skyem123** [comment]
I mean... why not build the libraries for android? what could go wrong? :P

**Comment by 20kdc** [comment]
You'd have to build the libraries not really specifically for Android but for whatever environment you're running Minecraft in *on* Android.
