### ISSUE TITLE
[Request] Support for the latest versions of Minecraft

### ISSUE THREAD

**Issue by Occhioverde** [MightyPirates/OpenComputers#3337]
Good morning, everybody.
I know this topic has probably been discussed several times, but I could not find any comprehensive news anywhere.
So I would like to ask the OpenComputers team if there is currently an intention to make the mod compatible with the latest version of Minecraft (1.16 at the time of writing).
Obviously I don't hide that I've heard about heavy changes within the Forge API (correct me if I'm wrong) and, for this reason, I'm even more curious to know the intentions of the developers.
Thank you in advance for your answers and good work.

**Comment by SquidDev** [comment]
Related: #3304, #3209, #3181, #3109.

**Comment by payonel** [comment]
thanks for the request - nothing official at this time

**Comment by Occhioverde** [comment]
Too bad, it would have been really nice to be able to use OpenComputers in the latest versions of Minecraft, also because 1.12 is no longer supported by many mod developers (and Forge, if I'm not mistaken).

In any case, I thank you for the very quick response while waiting for future news.

**Comment by Oct0bass** [comment]
Yeah. Probably would involve rewriting much of the mod, from what i've heard OC makes much use of block metadata (or something like that), which was removed in 1.13.  However, I would like to hear a little more announcements/plans from the devs.  I don't care if they don't "UPDATE ASAP OR ELSE!!!!", but i feel like it would be nice to get some more info such as "probably won't happen for a year", or "we're working on it" or "we're planning on starting porting once we finish <xxx issue/feature here>" and stuff like that.
