### ISSUE TITLE
[Suggestion] SQLite3 on Tier 3 Data Cards

### ISSUE THREAD

**Issue by andrewlalis** [MightyPirates/OpenComputers#3339]
As of right now, at least from personal experience, I seldom use data cards because I don't have any need for encryption or inflate/deflate, but I do end up writing lots of similar code all over the place to write data to and from files as serialized tables, and I wish that we could more easily use a hardware-accelerated relational database. Because this is difficult to do as-is, I usually end up turning my OC computers into 'thin clients' which just interact with an HTTP API on localhost via the internet card and a simple JSON serialization library.

So that is why I propose adding support for the SQLite3 embedded database as one of the benefits of the top-tier data card. If I had this, it would be much more feasible to use the ingame computers as data storage components, and it would give me a legitimate use for a raid setup, and I know there are many others who would enjoy having a relational db available out of the box.

This is the most popular Lua-based SQLite3 wrapper library: http://lua.sqlite.org/index.cgi/home

**Comment by payonel** [comment]
interesting :) sounds like a good add-on feature, not in-mod

**Comment by andrewlalis** [comment]
Would it be something you would be interested in adding as a loot floppy disk?

_I can also do the actual work for the pull request, but I'd just like to know before I invest a bunch of time in this._

**Comment by payonel** [comment]
no because then we'd have sqlite in our repo - which is why i would suggest an addon
