### ISSUE TITLE
Terminal visual corruption

### ISSUE THREAD

**Issue by cyberc001** [MightyPirates/OpenComputers#3340]
Minecraft version: 1.12.2
OC version: 1.7.5.192

I've came across an issue with OpenOS terminal: moving it's cursor replaces the symbols that cursor is at with zeroes and dots. It's only a visual effect, but, of course, it renders working with a computer an impossible task. 
Here is a youtube video link that briefly shows the effect: [link](https://youtu.be/GkE9I39jnQ0)
Before getting this issue, I was:
- typing in, deleting and inserting UTF-8 strings from clipboard;
- writing and executing a lua program that uses utf8 functions.
This issue also persisted through rebooting a computer.

**Comment by payonel** [comment]
we'll need a repro if you'd like this fixed. that means, share the exact script to run, what to type, and when you see it happen

if it is persisting through reboots, you should test on single player world creative mode, spawn in a clean machine: /oc_sp

**Comment by cyberc001** [comment]
Looks like I was totally wrong about the cause of this issue. Here is the reproduction:
On a computer with OpenOS installed on a hard drive, write and execute the following Lua script:
`event = require("event")
event.listen("key_down", function (key_ad, ch, code, plr)
print(code)
end)`
Looks like event listeners persist even if the script is terminated.

**Comment by payonel** [comment]
yep, they do. look at threads: https://ocdoc.cil.li/api:thread
