### ISSUE TITLE
1.12.2 Game crash while launching

### ISSUE THREAD

**Issue by Logic530** [MightyPirates/OpenComputers#3342]
Minecraft version:1.12.2
Forge version:2875
Open Computers version:1.7.5.192
No other mods
[Log](https://paste.ee/p/bxpZu)

**Comment by ghost** [comment]
Try deleting the OpenComputers config folder.

In your case, this can be done with one command:
`rm -rf "/home/logic/.local/share/multimc/instances/Open Computers/.minecraft/config/opencomputers"`
