### ISSUE TITLE
Creative computer do not have energy

### ISSUE THREAD

**Issue by hohserg1** [MightyPirates/OpenComputers#3345]
How to reproduce:
+ create standard computer(/oc_spawnComputer)
+ insert linked card
+ open lua repl
+ evaluate for i=0,1000 do print(component.tunnel.send("test")) end

Not all calls are successful
![image](https://user-images.githubusercontent.com/35610168/90080958-b4c33d80-dd14-11ea-8152-ae5282a6083e.png)

**Comment by payonel** [comment]
not a bug, but perhaps a poor choice in our how our creative computers manager power. they simply refill their power buffer every chance they can. but if  you run something too hot, they can still use up all power.

if you need to run a heavy job, just place an empty creative computer case next to it (touching). maybe place a bunch of them. they'll share power buffer and each refill their storage

**Comment by hohserg1** [comment]
I fix it in game by placing capacitor beside
