### ISSUE TITLE
term.setCursorBlink(true) is not working

### ISSUE THREAD

**Issue by ExDomino** [MightyPirates/OpenComputers#3346]
Hello,

Event if term.setCursorBlink(true) is called, and term.getCursorBlink() returns true, the cursor is not blinking when a custum program is running, when is still blinking in the shell.

I'm not sure if this is a bug on the 1.7.10 version, OpenComputers 1.7.5.
This version is probably no longer supported, but I just wanted to know if this is a bug or what I'm doing wrong.

Thank you in advance.

**Comment by payonel** [comment]
it's not well supported, but works only in some tiny cases. it's not a feature of terminal i wish to continue to support.

on the other hand, if you run io.read() in a program, you'll notice that your cursor is blinking waiting for input
