### ISSUE TITLE
Computer not start

### ISSUE THREAD

**Issue by Hellyclaster** [MightyPirates/OpenComputers#3347]
I putted all component, but nothing
video - https://youtu.be/tCTg_grcupA

Minecraft Version - 1.12.2
Forge - 14.23.5.2854
Mod v. - 1.7.5.192

**Comment by payonel** [comment]
your bios is probably invalid. try a EEPROM Lua bios
also, use an analyzer on a computer to read error strings from a crashed machines
also, check out tutorial videos on starting a machine for the first, and/or read our wiki

**Comment by Hellyclaster** [comment]
> your bios is probably invalid. try a EEPROM Lua bios
> also, use an analyzer on a computer to read error strings from a crashed machines
> also, check out tutorial videos on starting a machine for the first, and/or read our wiki

thx!
