### ISSUE TITLE
OpenOS ls program returns wrong last modified time.

### ISSUE THREAD

**Issue by credomane** [MightyPirates/OpenComputers#3348]
I've noticed this for years but never got deep enough into OpenComputers until very recently to figure out why. OpenComputers and I have a love/hate relationship you see. Anywho...

The filesystem component's function lastModified returns a unix timestamp in milliseconds. However the `ls` program well I really mean `/lib/core/full_ls.lua` calls `os.date()` which is expecting the passed timestamp to be in seconds. This results in dates in the distant future of year 52k.

Currently for my install I've just changed the call located [here](https://github.com/MightyPirates/OpenComputers/blob/8b8ddb231989702bf027f102b64ea569e4467bd6/src/main/resources/assets/opencomputers/loot/openos/lib/core/full_ls.lua#L137) to `os.date("*t", math.floor(epochms/1000))`

Highly doubt that is a proper fix to the problem but it works well enough for the time being.

**Comment by payonel** [comment]
no repro. probably host timestamps are not playing nice with our date code
