### ISSUE TITLE
Persistance on  RPI4 (arm32)

### ISSUE THREAD

**Issue by Ijdtm7** [MightyPirates/OpenComputers#3349]
Hey there and great mod! I am currently trying to run OpenComputers on my RPI4, i already have forge 1.12.2 and all the stuff loaded. I am using a program on opencomputers that doesnt support LuaJ, so i have to use Lua 5.2 or 5.3 for it. I found the 5.2 so file in the jar already but i used the LUA5.3 branch of OC-Natives and compiled for arm. I put the so in the 5.3 folder and put the correct name, then in the config i put the same name under the force native thing. It registers they exist but it says unsupported platform so i wont get persistance. Is there anyway to use the so files i compiled?

**Comment by payonel** [comment]
sounds like your solving this correctly, not sure why it didn't load. we dont plan to support arm ourselves.
