### ISSUE TITLE
Weird GUI glirch

### ISSUE THREAD

**Issue by Nagispace** [MightyPirates/OpenComputers#3350]
Open computers version 1.7.5.192
MC eternal modpack
I have this weird interface when using OC
(Having optifine ornot does not solve the problem)
![unknown (4)](https://user-images.githubusercontent.com/65559593/90888236-299e1380-e3b6-11ea-82bb-87edcafee669.png)

**Comment by OneEyeMaker** [comment]
@Nagispace 
This is **_NOT_** a bug of OpenComputers. This is bug in the texture.
I guess that you're using Faithful32 texture pack.
If so, go and delete ```assets/opencomputers/textures/gui/borders.png``` in your F32.zip resourcepack (*or modify this texture: one should have small black square in the middle; these middle pixels define color of screen*).
