### ISSUE TITLE
Wireless card tier 1 do not recieve messages

### ISSUE THREAD

**Issue by hohserg1** [MightyPirates/OpenComputers#3351]
How to reproduce:
1. Insert card to first computer
2. Open port 1
3. Run `while true do print(event.pull()) end`
4. Insert card to second computer
5. Open port 1
6. Send message(broadcast or send method)

Video:
https://vimeo.com/451519263

**Comment by payonel** [comment]
this was fixed in our latest release build, you can also test our dev builds
https://ci.cil.li/
