### ISSUE TITLE
[Suggestion] Toggleable side-specific modem_messages

### ISSUE THREAD

**Issue by KTaylorIII** [MightyPirates/OpenComputers#3352]
As of August 29th, 2020, when a modem-equipped microcontroller or similar device receives a `modem_message` signal, there is no means of determining which side of the block a `modem_message` came from. This makes broadcasting microcontrollers worse than Relays in that Relays rebroadcast inbound messages out through all sides but the inbound side; naively pulling a modem_message and rebroadcasting it from a microcontroller will send the message out through the original side in addition to the desired sides. This causes the source host and others on the same LAN segment to receive the bounced message.

What is proposed is a modem-specific toggle function that determines whether `modem_message` signals include an additional `side` return value. To maintain backward compatibility with preexisting code, the toggle should be set to false by default, making this functionality opt-in. This would allow developers to completely implement broadcast domain segmentation, for example, as well as ARP tables, routing tables, and other ideas requiring side-specific information.

**Comment by payonel** [comment]
we need better side controlled solutions - but if we build the solution it won't be modem_message specific - i appreciate your interest in this area, this is something we also care about
