### ISSUE TITLE
interpreted wasm CPU

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#3353]
currently OC supports lua 5.2 and lua 5.3 (and in the future, lua 5.4, maybe). it'd be nice to have interpreted wasm tho, because it supports languages like C, C++, Rust, Lua 5.1, Lua 5.0, and so on. (however, running Lua using interpreted wasm uses more RAM, because you pay the runtime cost per computer instead of once for all computers.)

**Comment by payonel** [comment]
that would be an external addon feature, not internal to the mod

**Comment by SoniEx2** [comment]
why should it be an external addon? is OC strictly-lua? what about moving lua into a wasm eeprom/bios and getting rid of the persistence-related patches and LuaJ? (with a boost to RAMs so as to fit the added overhead) bonus points for exposing all of debug, bytecode loading, etc.

**Comment by payonel** [comment]
oc native support will only ever be lua
