### ISSUE TITLE
Update peaceful recipes to not require endstone

### ISSUE THREAD

**Issue by Kristopher38** [MightyPirates/OpenComputers#3354]
Currently, there is no way to acquire endstone if you're playing on peaceful difficulty. Custom endstone provided by OC uses ender pearls, and to get vanilla endstone you need to travel to The End which isn't possible on peaceful since you can't get eyes of ender to activate the portal to The End. This seems to be the only item that isn't obtainable with peaceful recipe set, denying players from crafting hover upgrade tier 2 and drone cases. Current recipe is:
```
endstone {
  input: [[materialEnderPearl, "oc:chameliumBlock", materialEnderPearl]
          ["oc:chameliumBlock", materialEnderPearl, "oc:chameliumBlock"]
          [materialEnderPearl, "oc:chameliumBlock", materialEnderPearl]]
  output: 4
}
```
As far as I know the policy was to replace ender pearls and eyes of ender with diamonds in peaceful recipe set, but I feel like it might make some items too expensive (keep in mind that 4 endstone blocks are used in recipes for hover upgrade (tier 2) and drone cases (both tiers), so that would make the recipe require **20 diamonds** for a single hover upgrade/drone case). Instead of modifying the recipe for endstone, maybe we could modify recipes which use them by replacing endstone with diamonds? 4 diamonds for a hover upgrade/drone case (those are the only ones that use endstone) seem more like a fair cost. I can make a PR, but I'd like to get some feedback first.

**Comment by Techokami** [comment]
If this mod were to make it past 1.12, getting Ender Pearls in Peaceful is no longer an issue; as of 1.14 you can buy them from Cleric villagers.
Also, it is theoretically possible to get to The End in Peaceful, but you have to make sure the seed you are using will generate a completely filled End Portal frame, then you have to find it without the aid of Eyes of Ender.

**Comment by Desynq** [comment]
> Villager clerics now sell ender pearls for 4–7 emeralds, as one of their tier III trades.
[You can get enderpearls in 1.9+](https://minecraft.gamepedia.com/Java_Edition_15w41a)

**Comment by Kristopher38** [comment]
@Desynq Oh, you're right, I missed that way of acquiring endstone. This is indeed possible, even on pre 1.9 versions, but let's narrow it down to 1.7.10 only since that's enough for our purposes - on 1.7.10 villagers sell eyes of ender instead - so it's possible to get to the end and still get endstone. So it's possible on all currently maintained versions.
