### ISSUE TITLE
Program Stuck when chunk unloaded

### ISSUE THREAD

**Issue by DinShub** [MightyPirates/OpenComputers#3358]
Hello,
I have an issue in my program (a simple while true with event.pull) that opens a door with doorcontroller when a card is swiped in the cardreader. The issue is that when the chunk is unloaded the program doesnt work and require either a restart or I can interrupt (alt+ctrl+C) and relaunch the script and it works again. There is no error message and the computer is on and looks like it is running the program.
What can I do to fix it? I read that the program should return to where is was when the chunk unloaded but it seems the the event.pull messes it up?

**Comment by payonel** [comment]
if a alt+ctrl+c and script restart fixes it, the computer is still running and things should be working. your computer might be losing access to the external components and you aren't handling that possible failure in your script.

I'll close this ticket, but, reopen if you can
1. provide version information
2. provide minimal repro steps
3. provide error details (print some logs about where the script is failing and how)
