### ISSUE TITLE
Computer in Unloaded chunk stops scripts

### ISSUE THREAD

**Issue by DinShub** [MightyPirates/OpenComputers#3359]
OpenComputers version 1.7.5.192
Minecraft 1.12.2
When I run a simple script that listens to an event (card reader event) and the computer is in an unloaded chunk the script is technically runs but the event does not pop, There is no error message and the only way to make it work again is to relaunch the script or restart the pc.

Steps to procedure:
1.Make a pc with a card reader.
2.Make a simple script:
```
local event = require("event")
local component = require("component")
local ms = component.os_cardreader

ms.setEventName("swipe")

while true do
    event.pull("swipe")
    print("Swipe"
end
```
3.If it's singleplayer, either leave the chunk far enough so it will unload or leave the world and play again
   if it's multiplayer leave the chunk and let it unload
4.You will see it will not work after the unload of the chunk.

**Comment by payonel** [comment]
i assume your print irl has a closing `)`

**Comment by DinShub** [comment]
> i assume your print irl has a closing `)`

Well yes and no, my script doesnt print anything.
The script is working properly normally. The problem is when the chunk is unloaded.

**Comment by payonel** [comment]
then you haven't tested this minimal repro? i would test this code
also, check /tmp/event.log for any error messages

**Comment by DinShub** [comment]
> then you haven't tested this minimal repro? i would test this code
> also, check /tmp/event.log for any error messages

Tested it and it works until I leave the chunk.
The log in the pc in game or irl?

**Comment by payonel** [comment]
/tmp/event.log in game
with this test program, when you re-enter the chunk - is it back to the shell?
put the whole program in a xpcall and print the error that is thrown

**Comment by DinShub** [comment]
There is nothing in the tmp folder.
It is not back to the shell, it is as the program is running.
What does that mean to put the program in a xpcall?

**Comment by payonel** [comment]
https://www.tutorialspoint.com/lua/lua_error_handling.htm

**Comment by DinShub** [comment]
Nothing in the tmp folder, i did the xpcall and the only error is when I interrupt the program when it stops working, not other message.

**Comment by DinShub** [comment]
https://www.youtube.com/watch?v=Db9FrzkUH6E
Here I even made a video to show you.

**Comment by xarses** [comment]
It looks reminiscent of some of the bugs we've seen previously with devices shifting on the network (they can re-UUID, or even re-init, and these are third-party to OpenComputers as it depends on the implementation from the other mod). 

You can test for this behavior, using the `dmesg` command. This will emit all of the events that the computer sees. You can then click on the reader and see what data it responds with. Then go do your thing to unload the chunk and wack the card reader again.

Lastly, it would probably be more effective to come onto IRC/Discord to live discuss this problem further rather than debugging over issues

**Comment by DinShub** [comment]
> It looks reminiscent of some of the bugs we've seen previously with devices shifting on the network (they can re-UUID, or even re-init, and these are third-party to OpenComputers as it depends on the implementation from the other mod).
> 
> You can test for this behavior, using the `dmesg` command. This will emit all of the events that the computer sees. You can then click on the reader and see what data it responds with. Then go do your thing to unload the chunk and wack the card reader again.
> 
> Lastly, it would probably be more effective to come onto IRC/Discord to live discuss this problem further rather than debugging over issues

It's UUID issue I tested it out already, the ID's are static. where can I find the discord?

**Comment by payonel** [comment]
this isn't a uuid issue, nor a crashed machine because the user said halt interrupt returns to shell. so it is a bug in their code, or a bug in a library call their code is using.

**Comment by DinShub** [comment]
> this isn't a uuid issue, nor a crashed machine because the user said halt interrupt returns to shell. so it is a bug in their code, or a bug in a library call their code is using.

Can you find the bug? The code is posted twice here, the first post (ignore the missing ) thats not it ) and later as a video that includes the xpcall to see if there's an error.

**Comment by payonel** [comment]
no repro
