### ISSUE TITLE
shell.execute appears to be broken

### ISSUE THREAD

**Issue by magik6k** [MightyPirates/OpenComputers#336]
when trying to run 'shell.execute' after upgrade it produces following error:

"/bin/sh.lua:91: bad argument #1 (string expected, got nil)"

**Comment by magik6k** [comment]
Crafting new floppy helped... but afaik floppy is linked to rom, so it might be still strange

**Comment by fnuecke** [comment]
Couldn't reproduce in a few quick tests. Probably some lingering code somewhere after updating? If you can reproduce this, let me know and I'll re-open this issue.

PS: also, careful with those cross-references on Github ;-) (you referenced issue number one)
