### ISSUE TITLE
Robots Vanish/Glitch Out Near Lazy Chunks

### ISSUE THREAD

**Issue by Shadow8472** [MightyPirates/OpenComputers#3365]
I have now observed a total of three mining robots vanish -- one without a trace, but on my second incident involving two bots, I checked their dump Ender-Storage Ender chests and found them glitched out.
--Robots became invisible by trying to interact with them (Possible just a ghost block bug: same fix)
--They appear to be carrying the tools they should be carrying.
--Name is not displayed in world. WAILA shows several names cycling too fast to read -- about one per tick.
--Bots made with Tier 3 case, but names are white
--Robot's inventories can only be interacted with for about one tick by spamming interaction.
----Upgrade containers and upgrades are missing. Missing Diamond level XP upgrade is reflected with a black exterior.

Situation
--I'm running the loot disk dig -s 16 on robots' bootup, and mining exclusively on a chunk per chunk basis.
--Material drop off point is an Ender Storage ender chest being unloaded in AFK chunk.
--Glitched bots finished their chunks, but didn't turn away from e-chests.
--Glitched bots' e-chests were in "lazy chunks" while bots were mining 10 chunks away from player.

Outcome
--I mined up one bot and got everything back.
--Reloading the area of the other bot fixed it without picking it up, though my tier I and tier II batteries somehow swapped slots when their respective upgrade containers match their tiers.

OpenComputers Version: 1.7.5.192

I personally suspect this is just a client-side bug.

**Comment by payonel** [comment]
robots play weird tricks to move as TileEntities, and in some cases with the chunk unloaded we lose the robot state. we don't plan to make this much more stable, i recommend chunk loaders, it helps
