### ISSUE TITLE
TLS sockets and HTTPS support.

### ISSUE THREAD

**Issue by Kroppeb** [MightyPirates/OpenComputers#3366]
I was wondering if it were possible to implement TLS and HTTPS support? I noticed that I couldn't make any HTTPS request, and was planning on making my own TLS sockets but I'm asking here to check first.

If you were to add this feature I would suggest requiring a data card of at least tier 2 (as it provides aes) or even tier 3 providing rsa to verify certificates

**Comment by payonel** [comment]
there are not plans to extend the https card features

**Comment by Kroppeb** [comment]
Could I ask why not?
