### ISSUE TITLE
Draw.lua doesn't want to install

### ISSUE THREAD

**Issue by vitershpan** [MightyPirates/OpenComputers#3369]
Hello. I want to upload my picture to my computer.  it does not come out directly through the hard disk - it does not see the picture (it is in pic format (used a converter)).  decided to install draw.lua using the pastebin run ng73uZqT command, but the installation hangs at 84% and an error pops up

![16030092706552240782470347801022](https://user-images.githubusercontent.com/73055800/96362204-80716080-114d-11eb-9ab6-b4c89eca2d85.jpg)

**Comment by payonel** [comment]
looks like the download completed (See the output that says it saved in tmp?) but then failed to execute. it's an issue with the program your downloading, not opencomputers
