### ISSUE TITLE
MultiBlockScreens getting wiered sometimes

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#337]
i have no idea what caused this but well, see it:

On default textures, t3 seems to be unaffected:
![2014-06-17_16 02 18](https://cloud.githubusercontent.com/assets/6944842/3301189/bf49ab6a-f628-11e3-872e-205ae5caa96c.png)

On WoodyComputers only t3 is affected:
![2014-06-17_16 04 12](https://cloud.githubusercontent.com/assets/6944842/3301198/d1fec16e-f628-11e3-92b5-66faccb200c5.png)

It even makes my math.huge screen derpy:
![2014-06-17_16 04 34](https://cloud.githubusercontent.com/assets/6944842/3301206/e39b1d0a-f628-11e3-9cfd-1fd0ebb97f0e.png)

dyeing has no impact

**Comment by Techokami** [comment]
Can't reproduce in current git state of 1.7.2...
What version of Minecraft?

**Comment by Wuerfel21** [comment]
MC 1.6.4, OC 1.2 screenfix (find it at the bottom of issue #31)
And maaaaaany mods(it worked! just now it started to be wierd)

**Comment by fnuecke** [comment]
Hmm, in 1.7 I'd just have said it's 1.7's crappy rendering, but in 1.6... that's new.
- Does forcing the textures to reload (F3+t) change anything?
- Does this happen 100% percent of the time or only sometimes?
- Does this also happen if OC is the only mod in use?

**Comment by Wuerfel21** [comment]
going to test soon

**Comment by Wuerfel21** [comment]
Veeeery wierd!
started minecraft, and gone to my underwater base.
WoodyComputers - fine
Default - all tiers wierd
Even keeps this when restarting now
F3+t has no effect.
Should be noted that optifine and shaders(which are disabled!) are installed.
Oh, and it seems to not remember me turning shaders off, i turn them off, restart, and they are on.

**Comment by fnuecke** [comment]
Could you try without OptiFine, please?

**Comment by Wuerfel21** [comment]
Will soon try, but i have noticed it preffers oc textures

**Comment by TorakWolf** [comment]
Woho, Optifine sucks, if you like clear water and so, use gammabright and mcpatcher.

**Comment by Wuerfel21** [comment]
I hate MCPatcher since it messed up my minecraft back in 1.1 so i had to install 50 mods manually again, as well as optifine has better grass, natural textures and it gives like +20 fps...

**Comment by Wuerfel21** [comment]
Just tested, seems like its optifines fault, but it seems to work with woodycomputers and OF.
And without OF i get 10 fps(i get like 60 normally!)

**Comment by fnuecke** [comment]
Try disabling connected textures or some of the other, texture related features in OptiFine.

**Comment by TorakWolf** [comment]
10 fps? I get 70+ without it... And with it, I get only 30...

At least on 1.6.4

**Comment by fnuecke** [comment]
Actually, either way, since it seems to stem from some optimization OptiFine does, I don't really feel like digging into it to find out what might need changing, sorry. If someone else wants to have a look, go for it.
