### ISSUE TITLE
Run shell command and redirect io to function

### ISSUE THREAD

**Issue by busti** [MightyPirates/OpenComputers#3370]
Is it possible to run a shell command so that the stdout is redirected into a function of some sort?  
I.e.
```
shell.execute("cat somefile", function (data)
  process(data)
end )
```
Where the anonymous function is called for every "print" (or access to `io`) in the executed command   

Also sorry for submitting a general question here, but I cannot make a forum account since the confirmation mail won't send

**Comment by payonel** [comment]
look at io.popen
