### ISSUE TITLE
Feature request crafting component

### ISSUE THREAD

**Issue by salimAbdulIt** [MightyPirates/OpenComputers#3377]
It would be nice if the crafting component has the following method.
getAllReceipts() returns a table with all receipts.
getReceipts(id string) returns a table with all receipts for a specific id.

nice to havr
isCraftable(count: number) return true of false if the craft(count: number) method would craft items.

**Comment by Water-Moon** [comment]
#3202 I tried to request this feature before but... It looks like they're not going to add a method to get recipes...
