### ISSUE TITLE
switch to JVM-based eris, using wasm2kotlin

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#3379]
you can use wasm2kotlin to make eris for the JVM. https://github.com/SoniEx2/wabt/tree/wasm2kotlin

then you can remove JNI, LuaJ and enable bytecode loading.

currently missing is porting the emscripten runtime to kotlin.

**Comment by SoniEx2** [comment]
this doesn't export any of the lua symbols because emscripten doesn't support doing that, but, this is eris for lua 5.3, as a kotlin source file.

[lua.txt](https://github.com/MightyPirates/OpenComputers/files/5611548/lua.txt)

**Comment by SoniEx2** [comment]
you can drop eris entirely too and dump/load the wasm memory instead. slightly less space-efficient tho.

**Comment by lucsoft** [comment]
Hey im making a port to 1.16 do you have some knowledge about wasm2kotlin

https://github.com/lucsoft/OpenComputers/issues/2

**Comment by SoniEx2** [comment]
this lua is just the interpreter, without the necessary API symbols. because we fucked up. .-.

uh we'd recommend not implementing the native io.* APIs provided by C (just make them throw instead), nor any other blocking stuff. instead force lua to yield, so that you can save/load the whole wasm memory and not bother with eris at all. also wasm2kotlin has some issues - the generated files are sometimes too big for kotlinc. (kotlinc just completely refuses to compile files bigger than 20MB. it just ignores them entirely.)

anyway wasm2kotlin needs more work tbh, sorry. .-.

**Comment by lucsoft** [comment]
so we can keep JNI, LuaJ in the new version of OpenComputers?

**Comment by SoniEx2** [comment]
JNI is a pain, and LuaJ is broken. wasm2kotlin is blocked on https://youtrack.jetbrains.com/issue/KT-43829 tbh.

**Comment by lucsoft** [comment]
why cant wasm2kotlin split files that are larger then 20MB?

**Comment by SoniEx2** [comment]
kotlinc can't accept files larger than 20MB. wasm2kotlin outputs them just fine.

**Comment by SoniEx2** [comment]
update: managed to get lua.kt down in size a bit.

![1607718734](https://user-images.githubusercontent.com/1779619/101952270-2766fb80-3bd7-11eb-8a8d-07f29d492263.png)

it works!

**Comment by payonel** [comment]
@SoniEx2 make a PR for this and I can test it
