### ISSUE TITLE
Preserve file name sensitivity on insensitive host OSes

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#338]
If buffered mode is enabled (which it is by default) and two files with names that only differ in capitalization, one will override the other when the filesystem is flushed to disk, if the hosting Operating System treats file names case insensitive (e.g. Windows).

OC should ensure that the case sensitivity is preserved.
- Possibility A) is some extra bookkeeping, postfixing file names with a random string that is managed in a 'database'. The downside is that this is error-prone and can easily go out-of-sync.
- Possiblity B) is to define an escape character that is used to mark uppercase in 'duplicate' file names. This could get pretty... messy, too, though. The main problem with this is there's no nice way to differentiate file saved in this 'escaped' format, versus newly imported ones.

So right now I'm leaning towards A. The 'database' could either be a physical file, making it easier to copy disk contents between worlds, or part of the NBT data, making it easier to manage.

**Comment by Wuerfel21** [comment]
Rather A, but with the list being runtime-only(initalize it when loading the world, and add an entry when a file gets opened, use this until it is closed, then delete it from the list).
Or just send a letter to microsoft: "Make your os case-sensitive or we do baaaad things"

**Comment by LordFokas** [comment]
B.

**Comment by Wuerfel21** [comment]
Which normal OC user does have 2 files in 1 folder which have the same name expect they are in different case?

**Comment by fnuecke** [comment]
Which normal user tries to break out of the sandbox? ;-)

**Comment by LordFokas** [comment]
what about this:
- Possibility C) Make OC's file paths case insensitive.

Like @Wuerfel21 said, normal users probably aren't expecting to have 2 files in different case on the same dir, and it'd make it simpler to deal with files paths without worrying about case sensitivity.
Plus, it seems to be the easier solution presented so far.

**Comment by rmellema** [comment]
I like option C). It is easy and clean and will only effect users on Linux and BSD. It also keeps OC's behavior similar across all systems, which is also a plus. 

You could make the filesystem work like that of OS X(I only know how OS X's fs works): case insensitive but case preserving.

**Comment by LordFokas** [comment]
@rmellema that's the same behavior as Window's FS.

**Comment by Wuerfel21** [comment]
or just store stuff in something like a .iso?

**Comment by fnuecke** [comment]
Closed via #370.
