### ISSUE TITLE
Crash when loading: Cannot use Buffers when Array Buffer Object is enabled

### ISSUE THREAD

**Issue by lampyr** [MightyPirates/OpenComputers#3380]
hi i use a lot of mod and after updating a lot of mod (i don't remember which mod)
i have this crash: https://gist.github.com/lampyr/86750e84d12fb656d4c5641b30e66906

and the debug log: https://gist.github.com/lampyr/c8be176218d9e0e4a653dca5e341db79

**Comment by payonel** [comment]
looks like some other mod is doing something with opengl settings that is incompatible with our renderer. would need more specific repro
