### ISSUE TITLE
Problem with opencomputers

### ISSUE THREAD

**Issue by KelyanDev** [MightyPirates/OpenComputers#3381]
Hi so basically im trying to control the draconic evolution reactor with opencomputers and when i try to install the program i have this issue
![2020-12-05_15 35 39](https://user-images.githubusercontent.com/69301352/101245785-993ed100-370f-11eb-9e2c-3535f1e74741.png)

I really need to control the reactor but i t just doesn't want to 
Pls be fast

**Comment by lucsoft** [comment]
Are you in a read only filesystem?
is OpenOS installed?
is youre filesystem full?
what have you stored on it?

**Comment by KelyanDev** [comment]
I do not now if im in read only filesystem
Yup i install it before
Not at all
Pratically nothing because this is a test world

**Comment by payonel** [comment]
looks like your rootfs is ro, probably booted off the openos floppy. wget to a hdd, you can also install openos and boot from hdd for rw
