### ISSUE TITLE
Inventory controller does not work with backpacks

### ISSUE THREAD

**Issue by hohserg1** [MightyPirates/OpenComputers#3383]
This backpack have inventory through `ITEM_HANDLER_CAPABILITY` capability, but it inventory are not visible from inventory controller
![image](https://user-images.githubusercontent.com/35610168/101348320-8574a580-389c-11eb-86f3-b5b365f5ce7c.png)

![image](https://user-images.githubusercontent.com/35610168/101348346-902f3a80-389c-11eb-9ef0-c28114a5d1b8.png)

OpenComputers-MC1.12.2-1.7.5.192

**Comment by payonel** [comment]
this feature of the inventory_controller allows the robot to move items in and out of 2 specific types of inventories
1. opencomputer database
2. opencomputer server blades
