### ISSUE TITLE
Navigation upgrade not detected on robot

### ISSUE THREAD

**Issue by prushton2** [MightyPirates/OpenComputers#3386]
I have a robot that has a navigation upgrade installed in an upgrade container. When I try to type `nav = require("navigation")` into lua, I get an error saying that navigation component could not be found, and there is no navigation.lua script in /lib/. When I type `=component.navigation` into lua, I will get information on the upgrade. Am I getting the component incorrectly, or is this an actual issue?

**Comment by payonel** [comment]
`require` is for libs, not components
use `local nav = require("component").navigation` instead
