### ISSUE TITLE
how to use ssh client in openOS to connect openssh server?

### ISSUE THREAD

**Issue by qqqZXzz123** [MightyPirates/OpenComputers#3387]

**Comment by Ocawesome101** [comment]
There is no built-in, or even any at all, SSH client for OpenOS.  You'd have to write your own, which would involve implementing a large part of the SSH stack in Lua.  The simplest way to use SSH in OpenComputers is to not use it at all.

There is PSH, which is a remote shell program for OpenOS that you can use to connect two OpenComputers computers together.  Other than that there is nothing.
