### ISSUE TITLE
[Nanomachines][config] Allow for potion blacklist

### ISSUE THREAD

**Issue by codecnotsupported** [MightyPirates/OpenComputers#3388]
Currently the config allows only for a potion whitelist.
As it stand now I find all available effects with the default config is really not worth the effort.
If you have a mod which adds potions effects you have to look them ALL up and add them to the whitelist.

Purpose that the blacklist is added back in. With it being disabled by default. (Since some effects are broken/too OP)
I can report on broken effects so it can be added to the blacklist, and for the too OP ones, make them appear less often.

I'm not sure what happened to have it whitelist only but it would seem fnuecke wasn't in a good mood when it happend.
https://github.com/MightyPirates/OpenComputers/commit/155bf0702c3e81da71fe10b7c7bcf107da03d5d0

Also a idea add a config entry for permission of /oc_nanomachines so that non-opped players may use it

**Comment by payonel** [comment]
consider PR. not working on new feature requests at this time
