### ISSUE TITLE
Rendering going crazy when in some menus of oc manual

### ISSUE THREAD

**Issue by RealParSec** [MightyPirates/OpenComputers#3390]
So when opening some of the menus in open computers manual book ingame the top and bottom bars of the screen seems to not render there, two huge blueish bars.

Mods that are perticurarly installed for open computers include: OpenPrinter, Computronics (with TTS, for fun).

Here is the modpack link (my google drive, curseforge launcher needed or anything that supports their profiles): https://drive.google.com/file/d/18wz2UeHSCV_e7_fRGvkPtIn8ntxYM9Fk/view?usp=sharing

And also VirusTotal Scan for the modpack: https://www.virustotal.com/gui/file/1761743e738fe9870c328088a3c6db6ef41ac28ad7ca6f9789f817a909287add/detection

And last is the screenshot:
![Screenshot (8)-1](https://user-images.githubusercontent.com/18197204/102744086-3bd69100-4359-11eb-8389-7404e18a4951.png)

**Comment by lucsoft** [comment]
Do you have Optifine installed?

**Comment by RealParSec** [comment]
Who doesn't these days?

**Comment by lucsoft** [comment]
Well optifine is known to break stuff and especially when you change the settings

**Comment by RealParSec** [comment]
It's not making it unusable in any way, it's really more of a just me reporting and unexpected behaviour, so instead of telling optfine is causing problem, I would look into why...

**Comment by TheExistingOne** [comment]
I don't contribute to OC, but I do know that OptiFine does some weird stuff with rendering and overwrites a massive number of rendering classes, making troubleshooting difficult. I'd recommend living with it or messing with OptiFine's settings to see if that fixes anything..

**Comment by payonel** [comment]
blaming optifine
