### ISSUE TITLE
Robot - inventory controller - Inventory not found

### ISSUE THREAD

**Issue by Glastis** [MightyPirates/OpenComputers#3392]
Opencomputers: OpenComputers-MC1.12.2-1.7.5.192
MC version: 1.12.2
```lua
-- test.lua
local component = require("component")
local sides = require("sides")
 
print(component.inventory_controller.getInventorySize(sides.up))
print(component.inventory_controller.getInventorySize(sides.down))
```

![image](https://user-images.githubusercontent.com/15161394/103038994-1c658100-4570-11eb-8772-c7755b259f17.png)
![image](https://user-images.githubusercontent.com/15161394/103039028-30a97e00-4570-11eb-91f2-7e6cbeaf36e0.png)

No inventory found even with a vanilla chest and droppers. Can do a `robot.dropDown()` without trouble.
Tested on multiple robots with a fresh install of OpenOs.

Nothing found in logs

**Comment by payonel** [comment]
does not repro for me. maybe retry with our dev build

**Comment by Glastis** [comment]
Late reply, in case of someone having the same problem.

Found out it was due to Minecolonies villages.

Still don't know why computercraft/other mods does not have this behaviors, probably due to the fake player.
Well, this is definitely not a OC bug, I don't know if it is even possible to add a error message.
