### ISSUE TITLE
Feature Request: Detect what side an incoming network signal came from

### ISSUE THREAD

**Issue by prairiedog56** [MightyPirates/OpenComputers#3393]
If we could have the ability to do that on something like a microcontroller, they could basically pretend like they're level 2 networking devices. It would allow for more complex lvl2 devices, too. Could be neat

**Comment by oc-t35** [comment]
You don't really need that, a server rack can be configured to not relay packets, and individual network cards can be assigned to sides of the rack block.

But using microcontrollers as routers would be nice, the server rack solution is quite expensive.

**Comment by prairiedog56** [comment]
well I mean that's kinda the issue, it seems like it's really expensive to do something so simple as close off sides

**Comment by oc-t35** [comment]
I think the big problem with this is that you would have to modify how many parameters are in a modem_message.
That would mess up all programs created before.

One solution would be to have the ability to assign network cards to sides, but then servers would have nothing special, just that you can pack more into one computer.

**Comment by payonel** [comment]
work around is to pass network packets from machine to machine to cross different networks, consider a link card to be the connection between the two.
