### ISSUE TITLE
Unable to run programs using the modem component

### ISSUE THREAD

**Issue by pivinx1** [MightyPirates/OpenComputers#3394]
Normally the modem component is not installed and you have to use the Network Stack floppy to install the modem component. (Correct me if I'm wrong) 

After running even an simple program using the modem component, the program will throw an error that the modem component was not installed, because when installing the network "drivers" instead of copying the .lua files into the lib folder, the installer copies the "drivers" into an newly created "network" directory where the subprogram searching for an requested module _does not_ search for the requested modem component.

**Comment by oc-t35** [comment]
The modem component is not provided by the Network-floppy, components are the physical things the computer can interact with, like the GPU, the screen, the keyboard...
The modem-component is provided by any network card. You have to put it in your computer case, and then you can use the modem-component.

**Comment by pivinx1** [comment]
One problem. It IS there.

pon., 11 sty 2021, 18:33 użytkownik oc-t35 <notifications@github.com>
napisał:

**Comment by payonel** [comment]
the modem component is the "network card" or wireless network card
