### ISSUE TITLE
Limitation of (external) component calls

### ISSUE THREAD

**Issue by jrddunbr** [MightyPirates/OpenComputers#3395]
Hello. I'm the project leader for Electrical Age. I am looking for some insights.

During a recent building project, I came to the realization that there appears to be a limitation to the number of calls you can make from OpenComputers to our Eln Computer Probe components.

From the research I've done and after analyzing our code, I have come to the conclusion that it is likely that there is a limitation of one external component call per 'tick' in OpenComputers. I am unsure if this is a server tick or a redstone tick, as I have not tested, but I was wondering the following:

* Is there a way to configure OpenComputers to allow more external component calls per tick (setting the call limits in the config to [100,100,100] does not solve the problem).
* Is there a way to allow Electrical Age to make unlimited calls to our components via some whitelist

My current mitigations are to either set up multiple computers (not particularly favorable) or to batch the calls to our probes by using a single function call (also not particularly favorable).

To provide some insight, Electrical Age Computer probes allow users to address arbitrary signal names with arbitrary signal power (in the form of a floating point number) as well as read/write "6" (5) sides of the probe to create signal voltages. In the recent build, we were building a clock with 54 individual pixels, and we were writing all of those pixels from one computer. Ideally, we would be able to update the two seconds digits in the same tick, but this was not possible with the 1 operation per tick limit (the digit required 13 pixels and took over half a second to update as a result).

Yes, I am aware this can have a negative TPS effect on many components, but our code does not push those changes until later in the tick (and we run at the server tick rate for cables, not redstone ticks).

Thanks in advance!

**Comment by fnuecke** [comment]
Sounds like the callbacks are probably not flagged as safe to call from the executor thread, in which case each call will take one tick, as you've observed. If you haven't, take a look at [`Callback.direct`](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/java/li/cil/oc/api/machine/Callback.java#L43-L59). As mentioned, though, for this to be safe, the annotated methods must themselves be safe to call from a thread that's not the MC main thread.

**Comment by jrddunbr** [comment]
That looks to be exactly what I needed. Thanks for pointing this out. I'll close the issue and re-open it if I encounter problems or have further questions.
