### ISSUE TITLE
How can I make my custom card component interact with the host's filesystem?

### ISSUE THREAD

**Issue by andrewlalis** [MightyPirates/OpenComputers#3396]
I'm making a simple mod that will add an SQLite3 binding, which will allow users to create SQLite files on their filesystem and read/write to them with functions exposed by my component, which wrap around the SQLite JDBC driver.

So basically, I need to be able to obtain the filesystem of the host (given a certain `Context` and `Arguments`), the current working directory of the calling script, and I need to be able to get the real system path to that location on the IRL drive. It would also be nice if there is some way to respect the host filesystem's storage limits when attempting to update the database.

Additionally, I was wondering about how one would define a callback that returns an object with its own set of methods (because I want to define `open(filename)` to return a `connection` object with methods like `prepareStatement`, and `execute`.

Thanks for your help.

**Comment by payonel** [comment]
i would start with how our FileSystem manages opening files
src/main/scala/li/cil/oc/server/component/FileSystem.scala

And this is how we create the FileSystem:
        var fs = oc.api.FileSystem.fromSaveDirectory(address, capacity max 0, Settings.get.bufferChanges)
in src/main/scala/li/cil/oc/integration/opencomputers/DriverFileSystem.scala

I hope that helps
