### ISSUE TITLE
Internet API Throws Exception for HTTP Error Response

### ISSUE THREAD

**Issue by andrewlalis** [MightyPirates/OpenComputers#3398]
I'm trying to use an API running on localhost, but when I attempt to send a malformed payload to one of its endpoints, there is no clean way for me to handle that scenario programmatically in the ingame script, because attempting to iterate over the request handle throws the following error: `Server returned HTTP response code: 400 for URL: ...`, and `getmetatable(handle).__index.response()` simply returns `nil` so I am unable to check for certain response codes there either.

Now, I'm not familiar with Scala, but I believe that it is caused by the `call()` method here https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/server/component/InternetCard.scala which simply takes any exception thrown by the HTTP request and throws it further, despite the fact that 400's are probably thrown as an exception by whatever proxy library you're using.

**Comment by asiekierka** [comment]
Fixed by https://github.com/MightyPirates/OpenComputers/commit/9f1d521e4a6f4d75ce7460a7ef4ccd6bd29fbf45
