### ISSUE TITLE
Using rc.unload from a stop handler breaks “restart” command

### ISSUE THREAD

**Issue by Hawk777** [MightyPirates/OpenComputers#3406]
It seemed reasonable in my head: make my script’s `stop` handler call `rc.unload("myscript")`, so that I could just stop and start the service in order to reload the code file, rather than needing a separate command. Sadly, the `restart` command doesn’t work properly in this case: `/bin/rc` looks up the code chunk only once and then calls its `stop` function followed by its `start` function, which means the `unload` call removes the chunk from the cache table but then the same chunk (now removed from the table) has its `start` function called. A subsequent `rc myscript stop` then loads a new instance of the chunk with its own environment and calls `stop` on it, which obviously doesn’t stop the original now-orphaned instance of the service.

IMO it would make sense if the `restart` command were to invoke the service’s `stop` function, then call `load` again before calling the `start` function on the returned value; services that don’t call `unload` in their `stop` functions would not change behaviour at all (since `load` would just short-circuit and return the existing chunk from `rc.loaded`) but services that do would now work right (`stop` would call `rc.unload` removing the service from `rc.loaded`, then the `load` call would load the file into a fresh chunk, put it in `rc.loaded`, and return it, and the new chunk would be used for the `start` call).

**Comment by Hawk777** [comment]
I’m happy to submit a PR, but would first like to know whether maintainers even want this changed or whether they don’t like the idea.

**Comment by payonel** [comment]
you can make a PR, but fwiw, you could get around this problem by not using the cached "chunk" to store your data you wish to unload. You could manage your cache data as a child object on the chunk, and unload would nil that, start would recreate it when nil
