### ISSUE TITLE
Pushing an event with a table-valued parameter does not work

### ISSUE THREAD

**Issue by Hawk777** [MightyPirates/OpenComputers#3407]
[The manual](https://ocdoc.cil.li/api:computer) says of `computer.pushSignal`:
>  Pushes a new signal into the queue. Signals are processed in a FIFO order. The signal has to at least have a name. Arguments to pass along with it are optional. Note that the types supported as signal parameters are limited to the basic types nil, boolean, number, string, and tables. Yes tables are supported (keep reading). Threads and functions are not supported.
Note that only tables of the supported types are supported. That is, tables must compose types supported, such as other strings and numbers, or even sub tables. But not of functions or threads.

This does not seem to be the case, on a totally fresh OpenOS 1.7.5 boot:
```
/home # lua
Lua 5.3 Copyright (C) 1994-2017 Lua.org, PUC-Rio
Enter a statement and hit enter to evaluate it.
Prefix an expression with '=' to show its value.
Press Ctrl+D to exit the interpreter.
lua> computer = require("computer")
lua> computer.pushSignal("foo", {1, 2, 3})
invalid key to 'next'
stack traceback:
  machine:805: in function <machine:798>
  [C]: in function 'error'
  machine:679: in function <machine:676>
  (...tail calls...)
  [C]: in function 'xpcall'
  machine:798: in global 'xpcall'
  /lib/core/lua_shell.lua:110: in main chunk
  [C]: in function 'pcall'
  machine:750: in global 'pcall'
  /bin/lua.lua:23: in main chunk
  (...tail calls...)
  [C]: in function 'xpcall'
  machine:798: in global 'xpcall'
  /lib/process.lua:63: in function </lib/process.lua:59>
lua>
```

It appears to work in Lua 5.2, only 5.3 is broken.

**Comment by payonel** [comment]
yep, we dont support lua 5.3 fully due to issues with our version JNLua, and we can't update JNLua because it seems to make our eris serializer worse
