### ISSUE TITLE
Game crashed and the log told me to report this :D

### ISSUE THREAD

**Issue by RandomExplosion** [MightyPirates/OpenComputers#3409]
Expected behaviour: Server starts without crashing
Actual Behaviour: https://pastebin.com/R7m47X2n

I'm not too worried if the only way to fix it is to delete some OC data, my main priority is getting the server to start 😅 

Any help would be much appreciated :D

**Comment by payonel** [comment]
not sure how the data got corrupted, but yeah, the nbt data is failing in a few places. closing as no repro
