### ISSUE TITLE
Crash When Moving (Switch?) With Redstone in Motion While Sending Messages

### ISSUE THREAD

**Issue by TorakWolf** [MightyPirates/OpenComputers#341]
I posted this on OpenPeripheral issue tracker: https://github.com/OpenMods/OpenPeripheral/issues/181

But as the error says this have something with OC, here's the log:
http://pastebin.com/LVVZ0bHK

At least, it crashes when used as one cc peripheral, sending messages, and moving, meeting all 3 conditions at the same time.

I believe this is the same problem that OpenPeripheral's sensor had in 0.1.4 ( considering the switch is being used as one cc peripheral ), so @boq can provide some information.

**Comment by fnuecke** [comment]
Good timing. You had a switch with a packet generated from CC in the queue when it was saved, and there was a derp in packet generation that made those error when save. Sorry about that!

**Comment by TorakWolf** [comment]
Sorry, but I had another crash with the same thing...

http://pastebin.com/dx3ssvH5

**Comment by fnuecke** [comment]
Had the time to actually check in MC now, should be fixed for good. Thanks for testing!
