### ISSUE TITLE
Bug in Battery display

### ISSUE THREAD

**Issue by Anti27** [MightyPirates/OpenComputers#3410]
I found this bug in the display of the power:
it goes from 107 to 000 and then to 073.

OpenComputers-MC1.12.2-1.7.5.192.jar

https://user-images.githubusercontent.com/20539129/109402925-27ff6a80-795a-11eb-98a4-d3cc3bdc9b22.mp4

**Comment by payonel** [comment]
could be youre charging the battery and using it. charge updates could be occurring quickly.
no repro provided
