### ISSUE TITLE
Questien not issue

### ISSUE THREAD

**Issue by zaze06** [MightyPirates/OpenComputers#3415]
HI in the config it says `enabelTcp=true` does this means that I can make a program that can use the TCP protocol to talk whit my computer if I have a computer in Minecraft?

**Comment by zaze06** [comment]
Answer to my own questions probably it means i can have one program in Minecraft and one on my pc

But where ar the file saved on my pc that ar in eh tmp folder in the oc computer

**Comment by AR2000AR** [comment]
`enabelTcp=true` mean you can use tcp socket in your programs. See https://ocdoc.cil.li/component:internet for more info
Your minecraft computer will be able to talk with **any** computer except your real computer or your local network (by default).

The tmp folder isn't written anywere from what I know.

All your programs can be found in the mape save data in the openomputers folder

**Comment by zaze06** [comment]
ok thx but how can I do to make the in game computer can talk to my computer?

**Comment by AR2000AR** [comment]
Change the blacklist in the mod configuration file (internet { blacklist{}}
You need to remove 127.0.0.0/8 and/or 192.168.0.0/16
