### ISSUE TITLE
Is it possible to break the bound between a Remote Terminal and its Terminal Server ? 

### ISSUE THREAD

**Issue by LMWafer** [MightyPirates/OpenComputers#3416]
I have a server, a terminal server and a disk drive connected to the same line in a rack. I made a bound by shift-right-clicking on the terminal server with a remote terminal but I cannot "break" that bound... 

Re-shift-right-click, restart, break and replace... I tried a lot of things and I did not find any solution about that in the doc and the issues topics....

**Comment by payonel** [comment]
you can rebind it to a new terminal. you might be able to unbind it if you "recraft" it, just place it in a craft bench and take it back out. i believe this resets its nbt

**Comment by olavbs** [comment]
As far as i can tell, there is no recipe for either the remote terminal or the terminal server that allows "recrafting" either of them. Simply moving either item in and out of a crafting grid does nothing.
