### ISSUE TITLE
inventory controller suckFromSlot() incorrect/undocumented behavior

### ISSUE THREAD

**Issue by Hunter3216** [MightyPirates/OpenComputers#3417]
I am using OpenComputers-MC1.12.2-1.7.5.213.

According to ocdoc, when suckFromSlot() is used it "takes up to count items from the specified slot of the inventory at the specified side and puts them into the **currently selected slot**." However, if the currently selected slot is full it will then attempt to put items into the next available slot.

**Comment by payonel** [comment]
this is intended behavior. feel free to update the wiki for us
