### ISSUE TITLE
Computer turns off by itself

### ISSUE THREAD

**Issue by Senliast** [MightyPirates/OpenComputers#3419]
A computer in my world turns off by itself. I cannot tell whatever it happens on chunk load or on world load, i think it happens just randomly. I already manually powered on the PC countless times, also replaced block and all component in the PC (i took new from inventory) and reinstalled OS on it - all the same. Another computers in my world are running just fine. AI am using the latest mod version. I attached the error and the full log files from the latest session. Please say if you need anything else.

Minecraft: 1.12.2
Mod version: latest, 1.7.5.192

Installed mods:
- Aether
- BadMobs
- Cavern
- CodeChickenLib
- coroutil
- D3Commands
- DynamicTransport
- funky-locomotion
- MrFish Furniture
- IC2
- Galacticraft
- OpenComputers
- ProjectRed
- Railcraft
- Tropicraft
- Twillight Forest
- WorldEdit
- WorldUtils

Logs: https://mega.nz/file/8BMGCZzZ#0I1_u4iiBOKp-CjuhTkXO2OgIg2Gay5Rdu-h8NsHb7w

Edit: nvm, other computers in the world a are turning off by itself too.

**Comment by AR2000AR** [comment]
I have a similar issue #3399 (not duplicate)

**Comment by Senliast** [comment]
> I have a similar issue #3399 (not duplicate)

Do you have Twilight Forest?

**Comment by AR2000AR** [comment]
> > I have a similar issue #3399 (not duplicate)
> 
> Do you have Twilight Forest?

No I don't. The modpack is not the same at all

**Comment by AR2000AR** [comment]
I found this error in the server log : https://pastebin.com/8M7vh0s9

I also found this in a other log :
> [18:30:36] [Server thread/WARN] [opencomputers]: Could not persist computer @ (-4077.5, 86.5, 58.5).
li.cil.repack.com.naef.jnlua.LuaRuntimeException: attempt to literally persist userdata

The error could be cause by the data card returned userdata objects

**Comment by Senliast** [comment]
Could a dev please take a look on it? I need the mod very much, would be great if you could help me with it.

**Comment by AR2000AR** [comment]
The non persistent computers are supposed to be the backbone of the economy
in my server.

**Comment by Senliast** [comment]
@AR2000AR could you give your mod list?

**Comment by Senliast** [comment]
@AR2000AR use experimental mod version OpenComputers-MC1.12.2-1.7.5.213.jar from here https://ci.cil.li/job/OpenComputers-MC1.12/

**Comment by AR2000AR** [comment]
> @AR2000AR could you give your mod list?

https://pastebin.com/GuDZSpaJ

**Comment by Senliast** [comment]
Nvm, on the latest experimental mod version the issue still exists. Devs, please do something about that.

**Comment by payonel** [comment]
i recommend using chunk loaders to keep the machine loaded. not a great solution, but some edge cases where our serializer fails for some users can been a nasty problem that seems to never fully die

**Comment by Senliast** [comment]
But its a terrible solution, it requires more PC resources and increases the world loading and unloading time! Could you may be review your decision? I could help with testing new builds or send other logs if you need. I mean, it shouldnt be so and in OC for MC 1.7.10 this bug didnt exist, it worked just fine.

**Comment by AR2000AR** [comment]
> i recommend using chunk loaders to keep the machine loaded. not a great solution, but some edge cases where our serializer fails for some users can been a nasty problem that seems to never fully die

Chunk loader were not allowed for player (admin only). We had persistence problem with relay on a chunkloaded chunk too (using a turtle chunk loader).
