### ISSUE TITLE
How to programmatically update robot's file system externally

### ISSUE THREAD

**Issue by CraigKnoblauch** [MightyPirates/OpenComputers#3421]
Hey everyone. Thanks for the mod you've put together. It's a freaking blast to use.

I have a robot with a custom library in a server. I'd like to update those libraries without bringing the server down or going through oppm. My first thought was to replace the lib files in the saves folder directly. The robot doesn't seem to recognize this change, even after a reboot. Before I go digging through source and the file system, does anyone have any insights that might point me in the right direction?

Thanks everyone.

**Comment by AR2000AR** [comment]
Check the mod config. There is a buffer option you want to set to false to
enable real time read and write to the save file.

Libs (imported with require) are stored in memory by openOS when first
loaded. You will need to reboot the robot each time you update it's files.

**Comment by CraigKnoblauch** [comment]
Changing that option to false made this possible straight away. In fact, you don't even have to reboot the robot!
