### ISSUE TITLE
event pull for modem_message doesn't work on tablet

### ISSUE THREAD

**Issue by zhiyan114** [MightyPirates/OpenComputers#3424]
I'm currently using 1.7.5 OC version with minecraft version of 1.7.10

So while I was experimenting with the network around, I notice that the tablet was not able to pick up the `event.pull("modem_message")` and while the computer case was able to pick up the signal.

Keep in mind that the computer case is directly connected to the relay while the tablet ofc is wireless. The tablet is however able to send the message but not able to receive any.

Here is the sample code that I've used while testing:
Computer case: `require("component").modem.broadcast(1000,"Test")`
Table:
```
local modem = require("component").modem
modem.open(1000)
print(require("event").pull("modem_message"))
```

edit: Yup can confirm that this is an issue on relay since when I tested this on the access point, everything works.

**Comment by payonel** [comment]
put a wireless card in the relay
and to receive, you need to open the port

**Comment by zhiyan114** [comment]
@payonel I did both actually. I even used the demo script on the wiki site to test it and indeed the tablet is incapable of receiving the message.

Using the deprecated wireless access point does however fix such an issue. I can test it again if you would like but that is what's going on last time.
