### ISSUE TITLE
[1.12.2] Robot (propably) has no permissions

### ISSUE THREAD

**Issue by HonzaVinCZ** [MightyPirates/OpenComputers#3426]
Hello, I'm running Magma server ( Forge with classic Bukkit plugin support ) and I noticed, robots can't break/place blocks.
After searching all day on google, I couldn't find a solution. I think it is caused by some permission.

- Adding [OpenComputers] with its UUID to ops.json didn't help
- Adding [OpenComputers] to fake player list in Towny config didn't help
- Turning off world protection completely in Towny didn't help
- Giving permission with player's name for ex. HonzaVinCZ.robot didn't help

The same robot with the same program works well in singleplayer.

Server log:
[latest.log](https://github.com/MightyPirates/OpenComputers/files/6313969/latest.log)

OpenComputers-MC1.12.2-1.7.5.192

Screenshots from the server:
![2021-04-14_23 58 08](https://user-images.githubusercontent.com/29098779/114786008-c23a3700-9d7d-11eb-955b-48e7867f5b00.png)

![2021-04-14_23 58 10](https://user-images.githubusercontent.com/29098779/114786020-c49c9100-9d7d-11eb-8364-8a1732a08f03.png)

**Comment by ghost** [comment]
Can a robot break blocks if no plugins are installed?

**Comment by mckuhei** [comment]
same problem.

**Comment by mckuhei** [comment]
Okay,To fix this problem you should add `<playername>.robot` in config.

**Comment by HonzaVinCZ** [comment]
> Okay,To fix this problem you should add `<playername>.robot` in config.

Which config please?

Sorry for late reply, I had problems with my hw in my laptop.

**Comment by xemnes** [comment]
did you figure this out? i have the same problem, using mohist rather than magma though.

**Comment by HonzaVinCZ** [comment]
> did you figure this out? i have the same problem, using mohist rather than magma though.

Not yet. I'm still not sure what config is mckuhei referring to. I think he is referring to permission but except permission plugin I have no idea where else I could put it. 

Even though if it worked, I need to allow it to each player who connects. That can't work if I had to write it manually and I'm not that experienced to make program that sets that automatically. I don't even have idea how to make it other way.

**Comment by xemnes** [comment]
i think i figured it out. im not entirely sure how. i added opencomputers with its uuid to ops, then i went into config/opencomputers/settings.conf

found "nameFormat=" and changed it to "OpenComputers.robot"
(note: this makes the name generation static, im not sure if this is a problem or not, but works around permissions)

at first, it didnt work. but then i waited a bit and went back to try something and it was suddenly working.

i have to use ops.txt because luckperms wont let me add a user that doesnt exist.
