### ISSUE TITLE
Question: How to run a refreshed autorun without removing the floppy and putting it back in again

### ISSUE THREAD

**Issue by CraigKnoblauch** [MightyPirates/OpenComputers#3427]
Hey everyone. I'd like to utilize the autorun feature to have a robot run a program every time the autorun file is updated. I have an MC server that, when it boots, has a robot sitting idle. When the server boots, I'd like the robot to begin an autorun program. In my own testing, I'm able to edit the file external of Minecraft, the changes take effect immediately, but it's only when I take the floppy out of the robot and put it back in again that the autorun runs. Is there a way to get around that behavior, so that the autorun runs when the autorun file is updated?

Thanks!

**Comment by payonel** [comment]
run a timer-driven event or background thread in openos to check for updates on the file
