### ISSUE TITLE
Lua API creation for robot error [1.12.2]

### ISSUE THREAD

**Issue by NilByt3** [MightyPirates/OpenComputers#3429]
Hi everyone, first of all, im learnig lua cause im in love with this mod.
The thing is that i want to create some files to automate some tasks with a robot (mining, tree farm, ...). I create a file like an API where the functions are defined: [https://pastebin.com/e3B1Ts1R](https://pastebin.com/e3B1Ts1R)
The dig(d) function works perfectly by itself but the problem is when i try to use the lineDig(d, l) function in this file: [https://pastebin.com/3qDmTF7R](https://pastebin.com/3qDmTF7R). It supossed to mine a l blocks line of deep d.

When i try to execute the file i get this error:
![image](https://user-images.githubusercontent.com/83133217/115997381-2e6d3400-a5e3-11eb-8d10-3d7c05c7f258.png)

I don't understand so much this error. Anyone know what happend?

Thanks <3

**Comment by payonel** [comment]
nothing wrong stands out from the code you linked. i could have missed something
keep in mind that require() will cache libraries. so your digAPI might be outdated. you'll need to reboot to get require to recache
another option is to use dofile instead of require. dofile does not cache
