### ISSUE TITLE
Robot assembly should be gameplay-oriented, not time-based.

### ISSUE THREAD

**Issue by Skrylar** [MightyPirates/OpenComputers#343]
Arbitrary wait times are definitely unpopular in the modding scene, very
few parts of very few major mods make use of it:
- Railcraft's large boilers
- Buildcraft's laser assembly table
- Everything to do with Steve's Carts
- Big Reactor's turbines
- Thaumcraft 1

Even with discussions for balancing out CC turtles, it usually involves
expending tool durability or making them less cheap. Bolting on up to an
hour waiting period is, at least in my opinion, complete overkill and
Not Fun.

To make a better case, Azanor (of Thaumcraft fame) used this exact same
solution in attempt to balance out the original Thaumcraft. Back then
you needed to use a Quaesitum block and pipe in resources, then simply
wait a large period of time to be allowed access to mod content. Enough
people thought this was boring that Let's Plays tended to jump cut a lot
of Thaumcraft-related development out of their screen time, people
tended not to engage in the mod more than once simply because of the
time investment, and Azanor finally concluded that introducing gameplay
elements (what became the newer research systems) was superior to simply
waiting on the "Q-block" (to quote Direwolf) to allow you access.

Having a time-delay system removes from the Fun Factor, and mods which
rely on this are continually sidelined by the Minecraft community at
large in favor of blocks and mods which do not.

We should keep to more gameplay-oriented means of moderating access to
content, such as augmenting the general speed of a Robot by spending
more resources on servo chips. Robots already use tools which can break
(unless the player finds tools which do not, such as electricity-based
drills), and it seems now require extra cost to add in screens and ways
to control it on-site.

**Comment by Kubuxu** [comment]
The only that are using time based balance are Steve's Carts and Thaumcraft 1 as in case of rest it is energy based or just slow physical process. Those mods are not ones of most popular.

**Comment by Wuerfel21** [comment]
Yeah, good!

**Comment by Skrylar** [comment]
@Kubuxu Yeah, sorry. There was an extra paragraph about how a full scale boiler takes up 30 minutes to reach full temperature ("time based balance" but no explicit "will not generate steam until xx minutes" counter, as no steam is generated for the first ~10 an then slowly it generates as it comes to full tempo) which was cut to keep things succinct.

**Comment by Kubuxu** [comment]
@Skrylar you have nothing to sorry for.
The greatest difference between Boiler and Robot is that you need the Robot to continue working on it and in case of Boiler you just set it up and do a system that will consume the power.

**Comment by Wuerfel21** [comment]
The assembler concept is 100% stolen from stevescarts...

**Comment by fnuecke** [comment]
@Skrylar Interesting point. First off, I'd like to point out that a maximum complexity robot takes merely ~6 minutes, which I would not consider a long very time ;-)

Can you give a few more examples for what you mean by 'gameplay-oriented'? That's little abstract for me. Something like more complex recipes / more materials for example doesn't sound like a very good idea, seeing how people already occasionally complain about the complexity of the recipes (not the hardmode ones, mind you, the normal ones). If you mean something like... 'mini-games', that's something I can see as a replacement for the complexity system (I actually had something in mind there, but it seemed too unrealistic due to arbitrary addon-upgrades). The power requirement is still logically required, I find.

The 'time' is merely a side-product of the amount of energy being required, paired with a limited energy input per tick. Which does sound like a reasonable system to me, and is what pretty much every kind of machine does, be it generators converting fuel to power, or furnace replacements of every mod ever made. If anything, energy costs could be reduced a little, I guess, effectively speeding things up. But I'm actually quite happy with where they are right now.

If you have anything concrete in mind, I'd be interested to hear it, though!

**Comment by Wuerfel21** [comment]
let it cost a specific amount of energy, with it getting faster when you give it more power

**Comment by Kubuxu** [comment]
I'd love it, especially with my 2*20k RF turbines.

**Comment by Vexatos** [comment]
I like the current way. Time is the very most important resource in a sandbox game like Minecraft. Robots aren't supposed to be cheap, so it's good to make them cost a little of this resource. And no, adding more power shouldn't make it faster. It's really good as it currently is.

**Comment by Kilobyte22** [comment]
If you really want to make it faster with more power, just change the setting for that in the config. You can change how much power the assembler consumes per tick at maximum speed. So, if you set this to 9001 (like i did in my test instance) you can make robots almost instantly (given you have the energy or you disabled energy requirement)

**Comment by Skrylar** [comment]
@Kilobyte22 That doesn't work on servers, though. Steve's Carts eventually added in modules to exchange more resources for faster construction, because you don't have the option of editing a server config (unless you're the admin) and waiting 3-9 hours for a build isn't fun.

I prefer the general crafting recipe, personally. Or maybe having an augmentation block to assign upgrades and then clicking to receive the finished object. Since these are Lua interpreters, you still have to do actual work to plan out solutions an work within memory constraints to get them to do what you want. Having to wait X period of time at all, seems like its an attempt to "balance" against people who copy/paste scripts. I think this penalizes people who write their own, though, because now they have to just sit and wait for things to finish before they can put their own code in.

My ultimate preference would be a special block to edit modules, then instantly complete.

My second preference would be to have a machine that had no maximum limit on voltage, and just slurped that amount of power to complete. I don't see why it should take power to _build_ the robot when it already requires power to use, and Steve does a massive amount of things by hand anyway. I might accept a power draw from a Tier 2 set of equipment, which performed automatic crafting of the lower components instead of requiring Steve to manually do each and every recipe by hand to make the modules.

If I had to design a time-based system, I would probably vote for having "armature" items which are equipped in to the assembly table. Each thing would have a complexity score which is accumulated across all of the upgrades/modules, and an armature would convert ??? in to decreased complexity. So if you want to go overboard, you just make a lot of high-power armatures. There'd be no need for tiered assembly machines, since you're already using the 'armature' items to replicate a robot having to use some kind of limb to put the machine together--upgrades to that machine are just upgrades in the armature put in place.

**Comment by fnuecke** [comment]
> [...] waiting 3-9 hours for a build isn't fun [...]

Again, even the most complex robot will only take **6 minutes** to complete, when the assembler is powered maximally. I stress this to put the time it'd take to add whatever features you imagine into perspective. 6 minutes i barely enough to make a good cup of tea :-) Heck, writing this reply took longer.

And quite frankly, the assembly times in SC never bothered me, it's just something you plan with, and that's that. If you have nothing else to do in the meantime, well, then I'm a little confused, to be honest ;-) Although I might just be being nostalgic here, haven't had the chance to play with it in what feels like... forever.

> Since these are Lua interpreters, you still have to do actual work to plan out solutions an work within memory constraints to get them to do what you want. 

Well, yes, but once you have, you can copy-paste that code. Or, much more likely, you just download the code someone else wrote. This is, IMHO, a faux argument, one frequently used to try and convince people that CC is well balanced.

> My ultimate preference would be a special block to edit modules, then instantly complete.

This is, quite literally, creative mode. I don't see myself agreeing with this approach, ever.

> My second preference would be to have a machine that had no maximum limit on voltage, and just slurped that amount of power to complete. I don't see why it should take power to build the robot when it already requires power to use [...]

The assembler already draws power plenty fast. I don't believe there is _any_ power-using mod out there that will allow you to instantly charge electric appliances. And why does it take power? Well, unlike in vanilla MC and some other mods, machines in OC don't run on fairy dust (aka redstone). And in case you hadn't noticed, the assembled robot you get is fully charged. So if nothing else, consider it the time it takes to get in that energy.

> I would probably vote for having "armature" items which are equipped in to the assembly table.

So if I understand correctly, something like the lasers for BC's assembly table? It's an interesting concept, and if someone were to PR something along those lines I may consider merging it (if anyone sees this as an invitation, do talk to me, first, to avoid wasting your time). But again, 6 minutes. I don't agree this is game-breaking (and certainly not game-breaking enough) to validate the effort. There are other, far more interesting things to keep busy with.
