### ISSUE TITLE
[Bug] Paste clipboard does not work without keyboard

### ISSUE THREAD

**Issue by hohserg1** [MightyPirates/OpenComputers#3430]
Build of tablet without keyboard do not support paste clipboard
How to reproduce:
1) Assemble tablet without keyboard
2) Try to paste something to OpenOS terminal

**Comment by payonel** [comment]
yep, intentional. also tablets are way to complex in the code and have been buggy. i recommend using the server remote terminal

**Comment by hohserg1** [comment]
yep, so behavior look logical, but it makes useless some things like screen keyboard
