### ISSUE TITLE
[1.12.2]Game crash

### ISSUE THREAD

**Issue by Aaur1s** [MightyPirates/OpenComputers#3435]
My game crashes after I enter the world.
Minecraft version: 1.12.2
Forge version: 14.23.5.2854
OpenComputers version: 1.7.5.192
Crash log:
[crash-2021-05-08_16.15.42-client.txt](https://github.com/MightyPirates/OpenComputers/files/6445922/crash-2021-05-08_16.15.42-client.txt)

**Comment by payonel** [comment]
no oc in stack, no repro provided. closing as not enough data
