### ISSUE TITLE
Robot cannot access inventory of chest.

### ISSUE THREAD

**Issue by WazWaz** [MightyPirates/OpenComputers#344]
While `robot.drop()` with a chest in front of the robot works fine, when trying to use the _inventory_ component to do more specific things (eg. pull a replacement pickaxe out of the chest), the robot cannot see the inventory.

``` lua
local c = require("component")
local robot = require("robot")
local ic = c.inventory -- (same problem if use c.inventory_controller)
local side = require("sides")

-- This works: drops current item into chest:
robot.drop(side.front)

-- This fails with "no inventory"
print(ic.getInventorySize(side.front))

-- This prints "inventory_controller", confirming upgraded inventory
print(ic.type)
```

Other functions like `suckFromSlot` also fail with "no inventory".

**Comment by fnuecke** [comment]
As an unintended side-effect of fix for another issue, `c.inventory` is actually the same thing as `c.inventory_controller`. I'll fix this, to avoid further confusion.

As for the rest, getInventorySize and suckFromSlot work perfectly fine for me. Is this some mod chest or a standard vanilla chest?

**Comment by WazWaz** [comment]
Standard chest. Also tested with all other mods removed. Tested with single and double chests.

**Comment by fnuecke** [comment]
~~On which exact Forge and OC version?~~
Nevermind, was able to reproduce, looking into it. Thanks!

**Comment by WazWaz** [comment]
Forge 10.12.2.1121.
OC Core 1.0.0
OC 1.3.0.190-beta.1

**Comment by WazWaz** [comment]
Is there a nightly build or something? I'm happy to test.

**Comment by fnuecke** [comment]
Yep, automatic builds can be [found here](http://ci.cil.li). Thanks for testing!
