### ISSUE TITLE
No component.disk_drive.media() method on server disk drive

### ISSUE THREAD

**Issue by ewwhash** [MightyPirates/OpenComputers#3440]
![image](https://user-images.githubusercontent.com/28766913/119237981-7a5eba80-bb48-11eb-99b9-c4ade0e36779.png)

**Comment by payonel** [comment]
version
screen shots of server blade, world blocks relating to issue

**Comment by ewwhash** [comment]
Forge 14.23.5.2855, 1.12.2, OpenComputers 1.7.5.192

![image](https://user-images.githubusercontent.com/28766913/119240234-ffe96700-bb56-11eb-919e-1b5ffe83743d.png)
![image](https://user-images.githubusercontent.com/28766913/119240254-1e4f6280-bb57-11eb-965d-262fb66b49e3.png)

![2021-05-22_23 40 19](https://user-images.githubusercontent.com/28766913/119240246-1394cd80-bb57-11eb-8f26-eddb97ce900f.png)

**Comment by tt-thoma** [comment]
I remarked that there is no component `disk_drive`, there is only `filesystems`.
