### ISSUE TITLE
Global variables don't change in if statement

### ISSUE THREAD

**Issue by TheInfinityUser** [MightyPirates/OpenComputers#3442]
When I declare a variable without any global/local prefix in a file, try to change that variable in an if statement and output that variable, it doesn't seem to change the value that I gave in the if statement. The value remains exactly the same as when I first created the variable. 
This is the code I used (it's quite simple) -
My if statement goes something like this
> a = 65
b = 78
result = 0
operation = "2"
if operation == "0" then
  result = a + b
elseif operation == "1" then
  result = a - b
elseif operation == "2" then
  result = a * b
elseif operation == "3" then
  result = a / b
end
print(result)

This outputs 65 * 78 in an online compiler -
![unknown](https://user-images.githubusercontent.com/67455129/120004980-07948a00-bff5-11eb-93a9-3cf3c9d12eeb.png)

...but outputs 0 when I type the program in the file and execute the file. And yes, I changed the var type to string in the code that I executed in the mod, but that shouldn't have any effect right?

**Comment by payonel** [comment]
"I changed the var type to string .."
Well "2" ~= 2
So it depends what else you changed or didn't change. I dont believe there is a bug in OC, but rather in your lua code. feel free to discuss in our discord
