### ISSUE TITLE
[1.12.2] Wireless messages not working - event.pull("modem_message")

### ISSUE THREAD

**Issue by Jlectric** [MightyPirates/OpenComputers#3444]
Hello.
OpenComputers Version: 1.7.5.192 (on 1.12.2)
**Here's my issue in a** [**video**](https://www.youtube.com/watch?v=HSr7rmhwRCM) 

- I was able to recreate this in a new world 
- I am using [the example code from the wiki](https://ocdoc.cil.li/component:modem) on 2 computers spawned with /oc_spawnComputer 
- Both have tier 1 wireless network cards and OpenOS installed (I have run `install` on both)
- The other computer doesn't receive anything
- A relay (with wireless card) lights up
- The relay is also able to forward a wirelessly received broadcast and forward it to the other computer
- Does not work after the cable is removed

This issue seems to have appeared before in OC version 1.6.8: #2681 
(It seems the issue was closed as others weren't able to reproduce it)
The cause suggested by MakotoMiyamoto doesn't seem to be correct as I was able to recreate the issue playing in survival too

Here is my world file if that is at all useful...
[New World.zip](https://github.com/MightyPirates/OpenComputers/files/6602914/New.World.zip)

**Comment by RobertCochran** [comment]
Wireless modems do not automatically send their messages over the air - you need to use the `setStrength()` method and give it a non-zero range with which to send messages over (see https://ocdoc.cil.li/component:modem ). That seems to imply to me that a relay will automatically set its strength to the maximum provided by the card (which is why it worked when you did it that way), but to be honest, it's been a while since I've played a lot with OpenComputers.

**Comment by Jlectric** [comment]
@RobertCochran Thanks for your response - I have just tried this (in the lua shell) but it doesn't seem to fix the issue. `getStrength()` returns 16 and `setStrength()` also always returns 16 for any value over 16. 
It would seem that the default range is the maximum of the card. (Running the example modem code has the same result as previously)

**Comment by RobertCochran** [comment]
A tier 1 wireless card by default has a maximum range of 16, which is consistent with what you're seeing.

However, now that I'm actually testing this out... I am 100% consistently getting the same behavior, also with 1.7.5.192 on Minecraft 1.12.2. T1 wireless cards are refusing to communicate directly with each other. Wireless communication only works when one end is wired into a relay with a wireless card, but only the side that's wired into the relay will get any messages.

Further testing with T2 wireless cards was perfectly fine. Under the same circumstances, even with the range reduced to the T1's 16 block limit, it's been perfectly fine and direct communication is happening as expected.

**Comment by Kristopher38** [comment]
Please try upgrading to one of the latest working dev build ([https://ci.cil.li](url)) and retest, as similar issue regarding T1 wireless cards has been already resolved in the past.

**Comment by Jlectric** [comment]
@Kristopher38 Tried this with version 1.12.2-1.7.5.217 and it works fine - Thanks

To others experiencing this issue either use a newer build of the mod as it has been fixed (may not be stable?)
**Or just use the tier 2 card - @RobertCochran has tested that the tier 2 card doesn't have the same issue**
(I have also found it to work)
