### ISSUE TITLE
OpenComputers build issues, future mod direction for OpenComputers

### ISSUE THREAD

**Issue by jrddunbr** [MightyPirates/OpenComputers#3446]
Hi, apologies if this is somewhat off topic.

@caeleron and I are from the Electrical Age development team and we were trying to compile the 1.7.10 branch of OpenComputers, but it seems like the Forge Gradle packages for that version have just vaporized.

I don't have a log in front of me, but I was trying to figure out if it was just that the two of us are being idiots with regards to Forge development or if it actually doesn't build anymore, since Electrical Age has a hard time building these days and it would be nice to still be able to compile bugfixes and such. Has anyone on your side done a clean build of the mod recently (w/o a gradle cache?)

Also, somewhat related, [we've been working (slowly) on Electrical Age 2 (aka ELN2)](https://github.com/eln2/eln2) for 1.16.5 (probably will come out for 1.17 at our current development rate), and we were wondering if OpenComputers will be moving to newer versions as well. We saw a package called Open Computers 2 floating around your build server, but it doesn't look to be very official so we were curious. 

We would love to have some integration -

On top of the normal "ELN Probe" that we had in the past that basically acted as a ADC/DAC for our wires to OpenComputers lua calls...

We want to do some things such as "optical fiber" on our telephone poles that allows for OpenComputers (network) wiring to be transmitted over long distances along with our electrical wires and such. I've briefly looked over the API for this and it doesn't look too difficult for old versions, but I was unsure if the API would be different in a newer version, and we're still in the planning stages of our graph topology calculations for ELN2, so it would be easier to integrate at this stage.

We also have a cool idea (which would probably be more for small servers like our development server and likely far too advanced for normal play) where we have a custom computer orchestration system which actually translates OpenComputers devices to [x86 or ARM Firecracker microvm's](https://github.com/firecracker-microvm/firecracker) running some small Busybox or some custom OS, and connect the serial terminals into OpenComputers somehow (or even emulate a framebuffer). The local networks could utilize bridge networks on the local machine or in a sandboxed machine and use nested virtualization for Firecracker. I guess a bunch of lxd system containers or QEMu could also work, but the nice thing about Firecracker is the very low footprint, allowing for hundreds of microvm's.

Alternatively, one could use various cloud platforms (such as AWS EC2). For example, placing some computers down could translate to some t3a.nano's and then some gp2 disks for all the hard drives made in the game. There's a recent feature to EC2 that allows you to get serial console on the system which makes this particularly workable without the instances having a network/internet connection, and OpenComputer wired networks could become automatically generated subnets in an AWS VPC. The various floppies could translate to AMI's that can be cloned to a gp2 disk.

My guess is that this sort of feature is a bit over the top for standard OpenComputers (and expensive if you use the cloud option), so we're probably going to make it a pluggable feature of ELN2, but I would be interested to hear your take.

If you'd rather chat about this kind of thing in Discord, I can join yours or you can join ours, either works for me. The link to ours is on the old Electrical Age website under support I think.

Full disclosure, I work for AWS so I am obviously a bit biased on why it might be cool. But there's no reason you couldn't support GCP/Azure/etc as well I don't think.
My opinions are my own and not that of my employer.

**Comment by SquidDev** [comment]
>  we were wondering if OpenComputers will be moving to newer versions as well

There's some more discussion in #3375, but I think the answer right now is "no".

> We saw a package called Open Computers 2 floating around your build server, but it doesn't look to be very official so we were curious.

[OC2 is a separate mod](https://github.com/fnuecke/oc2/) - I believe the name is just temporary right now. It is created by the same person, but there's not much overlap in content or API surface. It might still be possible to do what you want with this mod though, though be warned the API isn't stable yet!

<sub><sup>It's definitely possible to do with ComputerCraft's API, but you may not want that</sup></sub>

**Comment by jrddunbr** [comment]
> It's definitely possible to do with ComputerCraft's API, but you may not want that

I see your little itty bitty comment :)

I would much prefer to work with open source software in this situation. I am not a fan of having no visibility or say into what happens in one of my dependencies. So I would much rather use OpenComputers in some fashion.

I'll keep my eyes peeled on OC2, but I was not impressed with the fact that it doesn't use a more sane JVM based language like Scala, Groovy, or Kotlin.

**Comment by SquidDev** [comment]
> I would much prefer to work with open source software in this situation

CC has been open source for ~3 years now, but understand the reluctance for sure!

> I was not impressed with the fact that it doesn't use a more sane JVM based language like Scala, Groovy, or Kotlin.

Doing anything non-Java is a little awkward for modded, as it involves dragging in additional dependencies. Would also hardly describe Groovy as "more sane" :p. Sorry, this is probably a little off-topic now.

**Comment by jrddunbr** [comment]
> CC has been open source for ~3 years now, but understand the reluctance for sure!

Wait, what? Where was I when this happened?! But, OC is still my favorite.

> Doing anything non-Java is a little awkward for modded, as it involves dragging in additional dependencies. Would also hardly describe Groovy as "more sane" :p. Sorry, this is probably a little off-topic now.

Considering that ELN2 is going to be 99% Kotlin, and is so far a single `.java` file (just for integration with Forge hooks and the instance of the `Mod` class or whatever), I think it's totally possible to do without pulling in much more than Kotlin's stdlibs. Some of those languages offer a lot of nice features that make development on the JVM much more safe. But, perhaps that's just my opinion. Raw Java feels like I'm writing C these days compared to Kotlin and Rust and Typescript.

**Comment by jrddunbr** [comment]
Oh bleh: https://github.com/dan200/ComputerCraft/blob/master/LICENSE

Why can't people just use real software licenses...

**Comment by jrddunbr** [comment]
I guess that there's not much more to discuss here, looks like OC2 has a ways to go and OC1 isn't porting. :'(

That said, if people are interested, shameless plug that [ELN2](https://eln2.org/) is looking for Java/Kotlin developers (among other things like texture artists, modelers, etc), and I'd be happy to have an OpenComputers-esque module/whatever in ELN2. Plus we're MIT licensed! Shoot me a message in our Discord if you're interested.
