### ISSUE TITLE
\n with term.read

### ISSUE THREAD

**Issue by tt-thoma** [MightyPirates/OpenComputers#3451]
I tried to make a program with commands (Y/n) and with term.read so I did and I got surprised when my program didn't work.
There was no error, but it says to retry to input (y/n)
I tried to see what return this function and I got this format: `textiinput\n`
I think this \n is not normal but due to an pull event before a confirm event.
Can you fix this problem in the future ?

**Comment by AR2000AR** [comment]
term.read() will return the new line character.  io.read() won't.

**Comment by tt-thoma** [comment]
But why ?
Is it intended ?

**Comment by ShadowEO** [comment]
If term.read didn't provide the \n, programs wouldn't know if a new line was entered. This is actually how all operating systems handle their command line APIs, for instance, Windows uses \r\n and hides it from the user/developer focused API similarly to how IO.read does.

Think of term.read as the lower level version of IO.read

**Comment by tt-thoma** [comment]
Okay, thank you!
