### ISSUE TITLE
Where is `maxPacketSize()` and `maxPacketParts()`

### ISSUE THREAD

**Issue by asvdvl** [MightyPirates/OpenComputers#3455]
OC 1.7.5.192, minecraft 1.12.2.
I am trying to execute `maxPacketSize()` with a modem and I am getting an error. If I try to look at all the functions of the modem, then I cannot find this function, but the tunnel has it.
![image](https://user-images.githubusercontent.com/57688070/124512468-1be05980-dde1-11eb-924c-ee2f25334809.png)
Also, trying to find a similar issues, I found [this](https://github.com/MightyPirates/OpenComputers/issues/2294), and I see that this functionality has been added to the mod. However, I don't see this function either.

**Comment by BennyTurtle** [comment]
what is the error your getting? sorry for being a bit late, thinking of taking this mod up and plan on starting by fixing bugs

**Comment by AR2000AR** [comment]
> what is the error your getting? sorry for being a bit late, thinking of taking this mod up and plan on starting by fixing bugs

It's not a bug but a regression. 2 methods disappeared from the modem component.
I remember having made a program with them and having it crash after a mod update.

**Comment by BennyTurtle** [comment]
Maybe they left a note in the code as to why it was removed, ill check now

**Comment by BennyTurtle** [comment]
All the code for it is there, but this is kinda a mess (the structure of the source files) so maybe im not seeing something

**Comment by asvdvl** [comment]
> It's not a bug but a regression. 2 methods disappeared from the modem component.
> 
well, I probably have to use a binary search algorithm to get these values
Or catch error and parse it

**Comment by Rayder44** [comment]
I know it's not ideal, but is it that much of an issue to hardcode these values in your program?

maxNetworkPacketParts and maxNetworkPacketSize are defined as 8 and 8192 respectively in the config, and will never change unless you change them.

**Comment by brisingraerowing** [comment]
All that data is part of the Device Info now. Use `computer.getDeviceInfo` to get a table of various bits of information.

**Comment by Ocawesome101** [comment]
These functions were removed, as Brisingr noted, in favor of `computer.getDeviceInfo`.  I believe it says on the wiki that they were removed.
