### ISSUE TITLE
Robot not moving

### ISSUE THREAD

**Issue by GameTec-live** [MightyPirates/OpenComputers#3456]
I have a robot, wich is porgrammed in lua to move to a location with robot.forawrd() robot.up() etc. the way to the location works flawless, but on the way back the robot just stopps in the air and makes the crashing particles. there are no blocks ore invisible blocks.

the lua code is here:
while( true )
do
    if computer.energy() < 20300 
    then 
        robot.up()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.down()
        robot.down()
        robot.down()
        robot.down()
        robot.down()
        robot.down()
        robot.down()
        robot.turnLeft()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.turnLeft()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.forward()
        os.sleep(5.0) 
        robot.turnLeft()
        robot.turnLeft()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.up()
        robot.up()
        robot.up()
        robot.up()
        robot.up()
        robot.up()
        robot.up()
        robot.turnRight()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.turnRight()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.forward()
        robot.down()
        robot.turnLeft()
        robot.turnLeft()

    end
    os.sleep(0.1)
end

**Comment by asvdvl** [comment]
Try to build a robot with Hover Upgrade.
You can read about the robot's movement here https://ocdoc.cil.li/api:robot#movement

**Comment by GameTec-live** [comment]
I will try...

**Comment by GameTec-live** [comment]
Did it! thanks!
