### ISSUE TITLE
Network Info

### ISSUE THREAD

**Issue by eyeofgafeeney** [MightyPirates/OpenComputers#3458]
The relay saying "packets" made me think can you send a program to a computer making a in game internet?

**Comment by JujuLynx** [comment]
You can, it just needs a little work from the user.

OpenComputers has huge potential for what you can do. The mod just gives you the basics and it's up to you to implement it.

**Comment by asvdvl** [comment]
> 
> 
> The relay saying "packets" made me think can you send a program to a computer making a in game internet?

YES! For example, I made a simple server/client program that works similarly to "pxe" on real computers, it allows me to download programs larger than the eeprom size. it helps a lot when working with drones.

**Comment by unforseenconsequ3nces** [comment]
I made a game once, in OC. It was on an old multiplayer server. Basically, I had a few server racks with different servers in them (T2s). People could connect using a command and then play the game with other people. It took me a while to do it, but it worked.
