### ISSUE TITLE
assembly table recipes

### ISSUE THREAD

**Issue by feldim2425** [MightyPirates/OpenComputers#346]
Can you add BC assembly table recipes ?

**Comment by Wuerfel21** [comment]
For what?

**Comment by rhjobe** [comment]
?

**Comment by fnuecke** [comment]
Uhm, as in make it build stuff otherwise built in the BC Assembly Table? No. Just because it's called "Assembler" doesn't mean it has _any_ relation to that block. If that's not what you meant, you'll have to put a little more effort into describing what you suggest.
