### ISSUE TITLE
Error when i try to open a pastebin program

### ISSUE THREAD

**Issue by Freshplex** [MightyPirates/OpenComputers#3460]
Everytime when i try to start an written or an pastebin program this happens:

/lib/process.lua:61: attempt to index a nil value:
stack traceback:
             /lib/process.lua:61: in function </lib/process.lua:47>
             (. . . tail calls. . .)
             [C]: in function ´xpcall´
             machine:751: in function `xpcall´
             /lib/process.lua:84: in function </lib/process.lua:80>
             
 Can someone please help me with this im very new into OpenComputers and this is is the most frustrating thing.

**Comment by asiekierka** [comment]
Not enough information, sorry. We'd need a reproduction case.
