### ISSUE TITLE
Lua/Java bridge issues

### ISSUE THREAD

**Issue by v1993** [MightyPirates/OpenComputers#3461]
1. There is support for 64-bit integers in Lua 5.3, but OC passes Java-side integers as doubles into Lua. While not critical (there are hardly any values crossing Java/Lua border that are big enough to run into issues), it still would be nice to have it working properly.
2. Arrays pushed to Lua have index `n` set to their length. This is an old convention that was removed staring with Lua 5.1, so it should be removed in OC as well.

**Comment by repo-alt** [comment]
First issue is actually very inconvenient but I believe the answer will be the same as to https://github.com/MightyPirates/OpenComputers/issues/2448 (Outdated JNLua built from unkown sources, impossible to update w/o breaking Eris)

**Comment by asiekierka** [comment]
1. Fixed in https://github.com/MightyPirates/OpenComputers/commit/ac4d93589ab9c666979bbfda818cad701b617a47

**Comment by asiekierka** [comment]
2. Fixed in https://github.com/MightyPirates/OpenComputers/commit/fa30722e6bdbabf58f836b3946fa0968c6d79da8 - most production Lua code seems to be unaffected.
