### ISSUE TITLE
How do you postiton text in an eeprom program?

### ISSUE THREAD

**Issue by unforseenconsequ3nces** [MightyPirates/OpenComputers#3462]
I want to position a text at the center of the screen, the coordinates are done but how do I do it in an eeprom? Should I just use gpu.set?

**Comment by payonel** [comment]
there is no keyword gpu available in eeprom. but you do have the component class
you want to do something like `component.invoke((component.list("gpu")()), "set", pos_x, pos_y, str)`
see https://ocdoc.cil.li/tutorial:custom_oses for more information
