### ISSUE TITLE
Computers shut down on server randomly. Havent tracked down cause yet.

### ISSUE THREAD

**Issue by cadergator10** [MightyPirates/OpenComputers#3463]
I run a small scp community on minecraft, and the way we use opencomputers are for the security system. Everyone has a card and they swipe it on a magreader, and it lets them in and such. But randomly, all the computers just shut down in the site. We are currently building, so it isnt much of an issue yet, but with maybe over 50 different computers in the site soon, THIS HAS TO BE FIXED! Any suggestions on how it can be fixed?
Mod list: https://www.dropbox.com/s/fc06tcmfeyxhy0x/Site91.zip?dl=0 (its the dropbox link for the modpack)

I use magma on the server, and have daily restarts

**Comment by cadergator10** [comment]
Could it be something with how the computer might be constantly waiting for an event? (It can maybe go for a whole day waiting for an event)

**Comment by AR2000AR** [comment]
Look for any OC related lines in the server log. On our server OC couldn't save the state of some computer. Because of that those computers were off when the chunk reloaded.
Our solution was to use a redstone clock to reboot the computer.

**Comment by cadergator10** [comment]
In a crash log, I did receive an error that a computer block was corrupted, but it only happened once. What causes a computer to be unable to retain its state? I don't want to have all the computers on chunk loaders

**Comment by cadergator10** [comment]
I discovered the error
12.08 00:53:29 [Server] Server thread/ERROR [opencomputers]: Unexpected error loading a state of computer at (2760.5, 167.5, 1458.5). State: Paused. Unless you're upgrading/downgrading across a major version, please report this! Thank you.
12.08 00:53:29 [Server] INFO java.lang.Exception: li.cil.repack.com.naef.jnlua.LuaRuntimeException: could not read data
12.08 00:53:29 [Server] INFO at li.cil.oc.server.machine.luac.NativeLuaArchitecture.load(NativeLuaArchitecture.scala:351) ~[NativeLuaArchitecture.class:?]
12.08 00:53:29 [Server] INFO at li.cil.oc.server.machine.Machine.liftedTree1$1(Machine.scala:766) [Machine.class:?]
12.08 00:53:29 [Server] INFO at li.cil.oc.server.machine.Machine.load(Machine.scala:765) [Machine.class:?]
12.08 00:53:29 [Server] INFO at li.cil.oc.common.tileentity.traits.Computer$class.readFromNBTForServer(Computer.scala:152) [Computer$class.class:?]
12.08 00:53:29 [Server] INFO at li.cil.oc.common.tileentity.Case.li$cil$oc$common$tileentity$traits$Colored$$super$readFromNBTForServer(Case.scala:28) [Case.class:?]
12.08 00:53:29 [Server] INFO at li.cil.oc.common.tileentity.traits.Colored$class.readFromNBTForServer(Colored.scala:38) [Colored$class.class:?]
12.08 00:53:29 [Server] INFO at li.cil.oc.common.tileentity.Case.readFromNBTForServer(Case.scala:100) [Case.class:?]
12.08 00:53:29 [Server] INFO at li.cil.oc.common.tileentity.traits.TileEntity$class.readFromNBT(TileEntity.scala:90) [TileEntity$class.class:?]
12.08 00:53:29 [Server] INFO at li.cil.oc.common.tileentity.Case.func_145839_a(Case.scala:28) [Case.class:?]
12.08 00:53:29 [Server] INFO at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:128) [avj.class:?]
12.08 00:53:29 [Server] INFO at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:493) [aye.class:?]
12.08 00:53:29 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:102) [ChunkIOProvider.class:48ec0a1]
12.08 00:53:29 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:162) [ChunkIOExecutor.class:48ec0a1]
12.08 00:53:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:955) [MinecraftServer.class:?]
12.08 00:53:29 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
12.08 00:53:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
12.08 00:53:29 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
12.08 00:53:29 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
12.08 00:53:29 [Server] INFO Caused by: li.cil.repack.com.naef.jnlua.LuaRuntimeException: could not read data
12.08 00:53:29 [Server] INFO at li.cil.repack.com.naef.jnlua.LuaState.lua_pcall(Native Method) ~[LuaState.class:?]
12.08 00:53:29 [Server] INFO at li.cil.repack.com.naef.jnlua.LuaState.call(LuaState.java:681) ~[LuaState.class:?]
12.08 00:53:29 [Server] INFO at li.cil.oc.server.machine.luac.PersistenceAPI.unpersist(PersistenceAPI.scala:164) ~[PersistenceAPI.class:?]
12.08 00:53:29 [Server] INFO at li.cil.oc.server.machine.luac.NativeLuaArchitecture.load(NativeLuaArchitecture.scala:356) ~[NativeLuaArchitecture.class:?]
12.08 00:53:29 [Server] INFO ... 17 more

**Comment by cadergator10** [comment]
I really, really need a fix for this :/ It makes the card system unusable if it constantly powers off the computer

**Comment by brisingraerowing** [comment]
I think this might be fixed in newer dev builds. You can get them from the [CI server](https://ci.cil.li/)
