### ISSUE TITLE
Can't access ME Controller api from sky factory 4 in order to work with craftables.

### ISSUE THREAD

**Issue by IRFinky** [MightyPirates/OpenComputers#3464]
Since skyfactory 4 removed the ME Controller due to removing channels for AE2
Without the ME Controller, getCraftables returns an empty object.
The resulting empty userdata object cant be used to send a request(amount:int), like:  craftable.request(64).

Heres a Snippet:
craftables = AE2Adapter.getCraftables({
    name = curName,
    damage = curDamage })
if craftables.n >= 1 then
    -- Request some of these items
     cItem = craftables[1]
     retval = cItem.request(craftAmount)

**Comment by asiekierka** [comment]
This seems to be what the AE2 API returns, we can't really do much beyond that. Sorry!
