### ISSUE TITLE
robot.dropDown() doesn't drop straight down

### ISSUE THREAD

**Issue by black3agl3** [MightyPirates/OpenComputers#347]
I tried having a robot drop items straight down and out of 200 or so items around 20 of them will not land on the block vertically below the robot.

They will land on random blocks around the block vertically below the robot.

The same problem happens with robot.drop(). Sometimes the item will land 2 blocks away from the robot instead of 1 block away.

Isn't it possible to make the robot just create the item in the centre of the block space where the item is supposed to be with zero velocity? I think that would be better than having the items fly out with random velocities from the robot.

**Comment by fnuecke** [comment]
Hmm, what's the use case for this to actually matter? Instead of just directly dropping into an inventory, that is.

**Comment by Vexatos** [comment]
Some blocks (like the Thaumcraft 4 Infernal furnace) require items to be dropped(!) into the top of the block. This would be really helpful in such a case.

**Comment by Wuerfel21** [comment]
Vanilla dropper?

**Comment by Vexatos** [comment]
The Vanilla Dropper doesn't drop straight down. And that's intentional.

**Comment by Wuerfel21** [comment]
BC pipes

**Comment by black3agl3** [comment]
In my case I was trying to automate the purification of Certus Quartz Seeds from Applied Energistics to Pure Certus Quartz Crystal. 

This process requires you to drop the seeds into a pool of water and pick them up from time to time so that the items don't despawn

**Comment by black3agl3** [comment]
BC pipes also spew items all over the place if I'm not mistaken

**Comment by Vexatos** [comment]
Yep, BC pipes are dropping randomly as well. Not to mention that it is pretty irrelevant if there is a mod that does that (The OpenBlocks Item Dropper actually works and has been made just for that). This feature would just be nice to have for robots, since you should expect them being rather precise.

**Comment by Wuerfel21** [comment]
This is a bad way to do stuff, the AE guy should be bugged with adding a macine to do this

**Comment by Wuerfel21** [comment]
Oh, vexatos was faster....

**Comment by black3agl3** [comment]
Sadly OpenBlocks is not updated for 1.7.2

**Comment by fnuecke** [comment]
I'm keeping the slight randomization, because always dropping in the exact same direction looks really... lazy, I find. Did make it more consistent though, dropped two stacks worth of items down over ~20 blocks and all items were collected by the (mid-air) hopper.
