### ISSUE TITLE
Cannot set output value on Redstone I/O

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#3470]
Minecraft 1.12.2, OpenComputers 1.7.5.217

When I call `component.redstone.setOutput(1, 15)` the block doesn't emit a signal and the function returns 0. When I call function again, it returns 0, and there is no signal either.

After rolling back to OpenComputers 1.7.5.216, the function started working as written on ocdoc.

**Comment by asiekierka** [comment]
Closing in favor of https://github.com/MightyPirates/OpenComputers/issues/3478
