### ISSUE TITLE
What does the digger,mazer,builder,generator and data card software do?

### ISSUE THREAD

**Issue by SlainMaster** [MightyPirates/OpenComputers#3471]
Also how do i connect a remote terminal to a server?(oc 1.7.5,mc 1.12.2)

**Comment by MixedVictor** [comment]
digger mazer builder and generator are the tools for the robots, i have no idea yet what the data card software does

**Comment by SlainMaster** [comment]
> digger mazer builder and generator are the tools for the robots, i have no idea yet what the data card software does

thanks,also what does the network stack do?im not really into coding but i know a few things (not lua tho)

**Comment by MixedVictor** [comment]
> > digger mazer builder and generator are the tools for the robots, i have no idea yet what the data card software does
> 
> thanks,also what does the network stack do?im not really into coding but i know a few things (not lua tho)

probably for communication with other computers

**Comment by SlainMaster** [comment]
uhh also how do i connect a remote terminal with a server since i cant
connect a screen to it (im on the newest version and downloaded from
curseforge)

**Comment by MixedVictor** [comment]
> connect a screen to it (im on the newest version and downloaded from

i dont know but i will try to see how to do it

**Comment by SlainMaster** [comment]
Ok, thanks.

**Comment by MixedVictor** [comment]
so i made an video instead because explaining in text would be horrible because i am not english native
https://youtu.be/RwH-ngc3b24 (and sorry for the bad video quality)

**Comment by SlainMaster** [comment]
thanks i didnt know i can click on those to connect them also do you know
how to send messages without cables since the video tutorials are very old

**Comment by MixedVictor** [comment]
im also going to see how to send messages without cables

**Comment by SlainMaster** [comment]
Thanks

**Comment by MixedVictor** [comment]
i think you need to learn lua for that https://ocdoc.cil.li/api:component you need to use lua and modify the components so you can do stuff

**Comment by SlainMaster** [comment]
there is probably a tutorial for that,i just cant find it

**Comment by MixedVictor** [comment]
this video could also help too https://youtu.be/55Xjv221kic (made by the guy who made the mod itself :D and yes its old)

**Comment by SlainMaster** [comment]
i already tried it but its old and doesnt help that much for someone that
doesnt know lua well

**Comment by SlainMaster** [comment]
i dont really understand it

**Comment by asiekierka** [comment]
This is not a bug report or feature request. For OpenComputers mod discussion, please use the forums: https://oc.cil.li/
