### ISSUE TITLE
Error when trying to compile

### ISSUE THREAD

**Issue by z3roco01** [MightyPirates/OpenComputers#3473]
im trying to compile with `./gradlew build` on arch linux on the `master-MC1.7.10` branch but i get the error 
`A problem occurred configuring root project 'OpenComputers'.
\> Could not resolve all artifacts for configuration ':classpath'.
  \> Could not find org.eclipse.jdt.core.jar (org.eclipse.jdt:org.eclipse.jdt.core:3.10.0.v20131029-1755).
     Searched in the following locations:
         https://files.minecraftforge.net/maven/org/eclipse/jdt/org.eclipse.jdt.core/3.10.0.v20131029-1755/org.eclipse.jdt.core-3.10.0.v20131029-1755.jar`

**Comment by asiekierka** [comment]
Fixed.
