### ISSUE TITLE
I can't delete an empty directory.

### ISSUE THREAD

**Issue by Vararg97** [MightyPirates/OpenComputers#3477]
I tried using del and rmin relative and absolute path but it wont work.

**Comment by Ocawesome101** [comment]
did you use `rm -r`?

**Comment by PublicVoidUpdate** [comment]
rm -rf / --no_presserve_root

(DONT DO THIS ON ANY MACHINE AT ALL REAL OR OC.)

**Comment by payonel** [comment]
rm is for files, and rmdir for directories
rm -r can be used for directory deletion as well
we try to be linux like
