### ISSUE TITLE
Redstone card doesn't work

### ISSUE THREAD

**Issue by thedimas3007** [MightyPirates/OpenComputers#3478]
It only works as an input and can't control redstone around computer/redstone controller

Forge version: 1.12.2:2855
Minecraft version: 1.12.2
OpenComputers version: 1.7.5.217

**Comment by thedimas3007** [comment]
when i run setOutput(1,15) in lua console, redstone on redstone controller doesn't change

**Comment by Ocawesome101** [comment]
I've just experienced this issue also.  Also on build 217.

**Comment by mihis** [comment]
Looks like a duplicate of #3470 

Try to reproduce on build 216

**Comment by asiekierka** [comment]
IMO this is a regression from https://github.com/MightyPirates/OpenComputers/commit/59d63fe57ecee6d11971bf02fd0633325889acd1

**Comment by Ocawesome101** [comment]
I thought this was fixed in 218?

**Comment by CaitlynMainer** [comment]
Same, I thought https://github.com/MightyPirates/OpenComputers/pull/3449 took care of this?

**Comment by asiekierka** [comment]
Oh, it was only merged in December. I see. I got the dates wrong!
