### ISSUE TITLE
error when starting the server (Tier 3)

### ISSUE THREAD

**Issue by TheHomecraft** [MightyPirates/OpenComputers#3479]
when I start the Tier 3 server I get the error: "OC: NO bootable medium found: /init.lua"
Here are a few more screenshots:
https://cdn.discordapp.com/attachments/822945228578619423/897238634674139166/unknown.png 

(if the link do not work with you please contact me)

**Comment by Unknown-User2** [comment]
Thats because theres no os installed and no os disk inserted

**Comment by TheHomecraft** [comment]
I could fix it
