### ISSUE TITLE
Is this still uvailable for MC 1.7.10

### ISSUE THREAD

**Issue by veso266** [MightyPirates/OpenComputers#3480]
Hi there, was wondering is the latest version still for Minecraft 1.7.10?
I see quite an old release, also on courseForge, so I am a bit confused if the version that I am looking at Patch 1.7.5 is still the latest version as I love Minecraft 1.7.10 (when they bring RedPower or some clone back call me to update :smile:

and was wondering is I can use the latest OC mod there

Thanks for Anwsering

**Comment by rashdanml** [comment]
Patch 1.7.5 does work on 1.7.10 (did a quick test, loads up just fine). There may be a new release in the works beyond 1.7.5, but not sure what the status of that is.

**Comment by asiekierka** [comment]
Soon.
