### ISSUE TITLE
Wireless Network Card (Tier 1) not returning "modem_message" signals.

### ISSUE THREAD

**Issue by aswerf** [MightyPirates/OpenComputers#3482]
The t1 wireless network card will not return any "modem_message" signals despite otherwise appearing to work. The card can send signals, and even respond to wake messages but refuses to generate any "modem_message" signal. If the t1 card is replaced with a t2 card in the receiving computer, the signal is generated as expected.

Simple signal logging script I used:
`local component = require("component")
local event = require("event")
local m = component.modem
m.open(1)
m.setWakeMessage("string")
while true do
--get args, print signal to shell
local t = {event.pull()}
print(t[1])
end`

Simple broadcast script I used:
`local component = require("component")
local m = component.modem
m.open(1)
m.broadcast(1,"string")`

modlist:
<img width="476" alt="modlist" src="https://user-images.githubusercontent.com/93063948/138578650-c5515c8a-7559-4b6b-918c-4df2240e09c6.png">
video:
https://youtu.be/IMTr2RqvyD0

**Comment by aswerf** [comment]
I also used computer.pullSignal() instead of event.pull() and got the same result.

**Comment by RobertCochran** [comment]
This is a known issue: https://github.com/MightyPirates/OpenComputers/issues/3444 

It has been fixed in Git but has not made its way to an official release. Build from source or use the CI build ( https://ci.cil.li/job/OpenComputers-MC1.12/ ).

**Comment by aswerf** [comment]
Okay thank you.
