### ISSUE TITLE
Crash after lshw command

### ISSUE THREAD

**Issue by riprsa** [MightyPirates/OpenComputers#3483]
i write lshw command in computer, then server crashes
server has 20gb of RAM
i have no problem with it in single

log: https://dpaste.com//24CZ6KMHX
forge-1.12.2-14.23.5.2855
OpenComputers_MC1.12.2_1.7.5.192

**Comment by riprsa** [comment]
in some cases, the operating system itself crashed, in some - only the server
server has ARM processor

**Comment by riprsa** [comment]
![image](https://user-images.githubusercontent.com/44776391/139082319-bc69cbba-9bea-4164-9756-f3d92f8194ec.png)
this command too

**Comment by asiekierka** [comment]
The pastebin has expired :( Please reopen if you manage to restore it.

**Comment by riprsa** [comment]
> The pastebin has expired :( Please reopen if you manage to restore it.

Hi, I remember the issue was with wrong arch of the Lua binary, but i might be wrong here. I will not be able to provide log, because I lost the hardware where the issue was found.
