### ISSUE TITLE
Attempt to call a nil value (global 'require'); Drone Error

### ISSUE THREAD

**Issue by asian-mario** [MightyPirates/OpenComputers#3484]
Hello! I'm programming my first drone and flashed my `bios.lua` to my EEPROM, the program worked perfectly fine on my computer while testing it but as soon as I assembled the drone and turned it on it gave me the error: `bios:1: Attempt to call a nil value (global 'require')`

I have no idea what's wrong since it worked on the computer, here is the 1st line of bios.lua:

`local component = require("component")`

**Comment by z3roco01** [comment]
this happens because `require()` is apart of an os like openos and not apart of lua if you want to use a component without an os you do `local i = component.proxy(component.list("<componentName>")())`

**Comment by asian-mario** [comment]
Makes sense, but what about other libraries such as 'event' etc.

Couldn't seem to find an answer on the wiki (also I found out the solution to my original issue on the wiki, sorry about that).

**Comment by z3roco01** [comment]
you can only use the libraries listed [here](https://ocdoc.cil.li/tutorial:custom_oses)
