### ISSUE TITLE
shell.parse() treats negative numbers as options

### ISSUE THREAD

**Issue by WazWaz** [MightyPirates/OpenComputers#349]
Since options.123 is not very useful, I'd suggest that shell.parse treat arguments like "-[0-9].*" as arguments, not options. Took me ages for my brain to even realize I was technically passing an option (doh!).

**Comment by Wuerfel21** [comment]
Hard issue ...
we could change options from -a to /a

**Comment by Kilobyte22** [comment]
We wont. Any unix like system uses dash and double dash for options. Thats how one would expect it. if you want negative numbers try something like this (untested):  

``` bash
./my_awesome_program -- -1 -2 -3  
```

The `--` should make the parser stop parsing any further arguments. If this does not work i might do a pull request to add that

**Comment by fnuecke** [comment]
Well, on the other hand numeric options _are_ quite... unlikely, I agree. And a simple `tonumber(arg[n]) ~= nil` check would do the trick. Hmhmhm.

**Comment by rmellema** [comment]
Numeric options are required by the POSIX standard and they are used. 
For example, `ls -1`(one) forces the output to be one entry per line, where `ls -l`(ell) writes the output in long format.

So although they might not be as frequent as letter options, I have to agree with @Kilobyte22 on this one.

**Comment by fnuecke** [comment]
Ah, good to know. Well in that case `--` ftw. Just tested it and it works as expected.
