### ISSUE TITLE
[IRC.lua] Unable to connect to servers protected with password. 

### ISSUE THREAD

**Issue by gaussandhisgun** [MightyPirates/OpenComputers#3491]
Any server with SASL authentication gives me instant "Connection lost". I guess, server passwords are not implemented?

**Comment by asiekierka** [comment]
That is correct, and unlikely to be fixed.

**Comment by payonel** [comment]
yeah, irc.lua was a very basic tool added in the early days. look for community apps such as wocchat for better irc support. not something built-in
