### ISSUE TITLE
game crashes when i open world that wasnt generated with open computers

### ISSUE THREAD

**Issue by f4563** [MightyPirates/OpenComputers#3492]
i didnt have opencomputers before and i got it after making my worlds and it crashes when i try to open already generated worlds

The game crashed whilst ticking memory connection
Error: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
Exit Code: -1

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.9.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  FMLPlugin (albedo-1.12.2-1.1.0.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  HCASM (HammerLib-1.12.2-2.0.6.25.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_21.16.0_Forge_1.12.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 12/31/21 10:50 PM
Description: Ticking memory connection

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:899)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)
	at com.wynprice.secretroomsmod.handler.HandlerUpdateChecker.onPlayerJoin(HandlerUpdateChecker.java:72)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_279_HandlerUpdateChecker_onPlayerJoin_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72838_d(World.java:1209)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:377)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:166)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.google.gson.Gson.fromJson(Gson.java:899)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)
	at com.wynprice.secretroomsmod.handler.HandlerUpdateChecker.onPlayerJoin(HandlerUpdateChecker.java:72)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_279_HandlerUpdateChecker_onPlayerJoin_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72838_d(World.java:1209)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:377)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:166)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@4499df6a
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4469483896 bytes (4262 MB) / 6878658560 bytes (6560 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 106
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 88 mods loaded, 88 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version               | Source                                         | Signature                                |
	|:------ |:----------------------- |:--------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft               | 1.12.2                | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                     | 9.42                  | minecraft.jar                                  | None                                     |
	| LCHIJA | FML                     | 8.0.99.99             | forge-1.12.2-14.23.5.2855.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                   | 14.23.5.2855          | forge-1.12.2-14.23.5.2855.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | xaerominimap_core       | 1.12.2-1.0            | minecraft.jar                                  | None                                     |
	| LCHIJA | opencomputers|core      | 1.7.5.192             | minecraft.jar                                  | None                                     |
	| LCHIJA | srm-hooks               | 1.12.2-1.0.0          | minecraft.jar                                  | None                                     |
	| LCHIJA | albedocore              | 0.1                   | minecraft.jar                                  | None                                     |
	| LCHIJA | securitycraft           | v1.8.12               | [1.12.2]+SecurityCraft+v1.8.12.jar             | None                                     |
	| LCHIJA | albedo                  | 1.0.0                 | albedo-1.12.2-1.1.0.jar                        | None                                     |
	| LCHIJA | jei                     | 4.15.0.291            | jei_1.12.2-4.15.0.291.jar                      | None                                     |
	| LCHIJA | appleskin               | 1.0.9                 | AppleSkin-mc1.12-1.0.9.jar                     | None                                     |
	| LCHIJA | ctm                     | MC1.12.2-1.0.2.31     | CTM-MC1.12.2-1.0.2.31.jar                      | None                                     |
	| LCHIJA | appliedenergistics2     | rv6-stable-7          | appliedenergistics2-rv6-stable-7.jar           | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | quark                   | r1.6-179              | Quark-r1.6-179.jar                             | None                                     |
	| LCHIJA | autoreglib              | 1.3-32                | AutoRegLib-1.3-32.jar                          | None                                     |
	| LCHIJA | baubles                 | 1.5.2                 | Baubles-1.12-1.5.2.jar                         | None                                     |
	| LCHIJA | bibliocraft             | 2.4.5                 | BiblioCraft[v2.4.5][MC1.12.2].jar              | None                                     |
	| LCHIJA | biomesoplenty           | 7.0.1.2441            | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar  | None                                     |
	| LCHIJA | botania                 | r1.10-363             | Botania+r1.10-363.jar                          | None                                     |
	| LCHIJA | buildcraftlib           | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftcore          | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftbuilders      | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcrafttransport     | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftsilicon       | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftcompat        | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftenergy        | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftfactory       | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftrobotics      | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | chiselsandbits          | 14.33                 | chiselsandbits-14.33.jar                       | None                                     |
	| LCHIJA | clumps                  | 3.1.2                 | Clumps-3.1.2.jar                               | None                                     |
	| LCHIJA | codechickenlib          | 3.2.3.358             | CodeChickenLib-1.12.2-3.2.3.358-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux            | 2.1.1                 | RedstoneFlux-1.12-2.1.1.1-universal.jar        | None                                     |
	| LCHIJA | cofhcore                | 4.6.6                 | CoFHCore-1.12.2-4.6.6.1-universal.jar          | None                                     |
	| LCHIJA | cofhworld               | 1.4.0                 | CoFHWorld-1.12.2-1.4.0.1-universal.jar         | None                                     |
	| LCHIJA | coloredlights           | 1.2.1                 | ColoredLights-1.12.2-v-1.2.1.jar               | None                                     |
	| LCHIJA | comforts                | 1.4.1.2               | comforts-1.12.2-1.4.1.2.jar                    | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | extendedrenderer        | v1.0                  | coroutil-1.12.1-1.2.37.jar                     | None                                     |
	| LCHIJA | coroutil                | 1.12.1-1.2.37         | coroutil-1.12.1-1.2.37.jar                     | None                                     |
	| LCHIJA | configmod               | v1.0                  | coroutil-1.12.1-1.2.37.jar                     | None                                     |
	| LCHIJA | craftingtweaks          | 8.1.9                 | CraftingTweaks_1.12.2-8.1.9.jar                | None                                     |
	| LCHIJA | enderstorage            | 2.4.6.137             | EnderStorage-1.12.2-2.4.6.137-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | energyconverters        | 1.3.6.24              | energyconverters_1.12.2-1.3.6.24.jar           | None                                     |
	| LCHIJA | mantle                  | 1.12-1.3.3.55         | Mantle-1.12-1.3.3.55.jar                       | None                                     |
	| LCHIJA | twilightforest          | 3.11.1021             | twilightforest-1.12.2-3.11.1021-universal.jar  | None                                     |
	| LCHIJA | tconstruct              | 1.12.2-2.13.0.183     | TConstruct-1.12.2-2.13.0.183.jar               | None                                     |
	| LCHIJA | extrautils2             | 1.0                   | extrautils2-1.12-1.9.9.jar                     | None                                     |
	| LCHIJA | fastleafdecay           | v14                   | FastLeafDecay-v14.jar                          | None                                     |
	| LCHIJA | forgelin                | 1.8.4                 | Forgelin-1.8.4.jar                             | None                                     |
	| LCHIJA | forgemultipartcbe       | 2.6.2.83              | ForgeMultipart-1.12.2-2.6.2.83-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe           | 2.6.2.83              | ForgeMultipart-1.12.2-2.6.2.83-universal.jar   | None                                     |
	| LCHIJA | minecraftmultipartcbe   | 2.6.2.83              | ForgeMultipart-1.12.2-2.6.2.83-universal.jar   | None                                     |
	| LCHIJA | hammercore              | 2.0.6.25              | HammerLib-1.12.2-2.0.6.25.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | waila                   | 1.8.26                | Hwyla-1.8.26-B41_1.12.2.jar                    | None                                     |
	| LCHIJA | ichunutil               | 7.2.2                 | iChunUtil-1.12.2-7.2.2.jar                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | mekanism                | 1.12.2-9.8.3.390      | Mekanism-1.12.2-9.8.3.390.jar                  | None                                     |
	| LCHIJA | teslacorelib            | 1.0.15                | tesla-core-lib-1.12.2-1.0.15.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | industrialforegoing     | 1.12.2-1.12.2         | industrialforegoing-1.12.2-1.12.13-237.jar     | None                                     |
	| LCHIJA | ironchest               | 1.12.2-7.0.67.844     | ironchest-1.12.2-7.0.72.847.jar                | None                                     |
	| LCHIJA | itemfilters             | 1.0.3.12              | ItemFilters-1.0.3.12.jar                       | None                                     |
	| LCHIJA | journeymap              | 1.12.2-5.7.1          | journeymap-1.12.2-5.7.1.jar                    | None                                     |
	| LCHIJA | jeresources             | 0.9.2.60              | JustEnoughResources-1.12.2-0.9.2.60.jar        | None                                     |
	| LCHIJA | malisiscore             | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                   | None                                     |
	| LCHIJA | malisisblocks           | 1.12.2-6.1.0          | malisisblocks-1.12.2-6.1.0.jar                 | None                                     |
	| LCHIJA | malisisdoors            | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                  | None                                     |
	| LCHIJA | mekanismgenerators      | 1.12.2-9.8.3.390      | MekanismGenerators-1.12.2-9.8.3.390.jar        | None                                     |
	| LCHIJA | mjrlegendslib           | 1.12.2-1.2.0          | MJRLegendsLib-1.12.2-1.2.0.jar                 | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | morph                   | 7.2.0                 | Morph-1.12.2-7.2.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | mousetweaks             | 2.10                  | MouseTweaks-2.10-mc1.12.2.jar                  | None                                     |
	| LCHIJA | naturescompass          | 1.5.1                 | NaturesCompass-1.12.2-1.5.1.jar                | None                                     |
	| LCHIJA | opencomputers           | 1.7.5.192             | OpenComputers-MC1.12.2-1.7.5.192.jar           | None                                     |
	| LCHIJA | patchouli               | 1.0-20                | Patchouli-1.0-20.jar                           | None                                     |
	| LCHIJA | rsgauges                | 1.2.5                 | rsgauges-1.12.2-1.2.5.jar                      | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | secretroomsmod          | 5.6.4                 | secretroomsmod-1.12.2-5.6.4.jar                | None                                     |
	| LCHIJA | simpleplanes            | 3.0.1.7               | simpleplanes-1.12.2-3.0.1.7.jar                | None                                     |
	| LCHIJA | stevekung's_lib         | 1.1.9                 | SteveKunG's-Lib-1.12.2-1.1.9.jar               | None                                     |
	| LCHIJA | subcommonlib            | 1.2.0.1               | subcommonlib-sublib-1.12.2-1.2.0.4.jar         | None                                     |
	| LCHIJA | telepads                | $version              | telepads-1.12.2-1.1.0.7.jar                    | None                                     |
	| LCHIJA | thermalfoundation       | 2.6.7                 | ThermalFoundation-1.12.2-2.6.7.1-universal.jar | None                                     |
	| LCHIJA | thermalexpansion        | 5.5.7                 | ThermalExpansion-1.12.2-5.5.7.1-universal.jar  | None                                     |
	| LCHIJA | uppers                  | 0.0.6                 | Uppers-0.0.6.jar                               | None                                     |
	| LCHIJA | waystones               | 4.1.0                 | Waystones_1.12.2-4.1.0.jar                     | None                                     |
	| LCHIJA | weather2                | 1.12.1-2.6.12         | weather2-1.12.1-2.6.12.jar                     | None                                     |
	| LCHIJA | worldedit               | 6.1.10                | worldedit-forge-mc1.12.2-6.1.10-dist.jar       | None                                     |
	| LCHIJA | wrcbe                   | 2.3.2                 | WR-CBE-1.12.2-2.3.2.33-universal.jar           | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | xaerominimap            | 21.16.0               | Xaeros_Minimap_21.16.0_Forge_1.12.jar          | None                                     |
	| LCHIJA | xercapaint              | 1.12.2-1.3            | xercapaint-1.12.2-1.3.jar                      | None                                     |
	| LCHIJA | teslacorelib_registries | 1.0.15                | tesla-core-lib-1.12.2-1.0.15.jar               | None                                     |

	Loaded coremods (and transformers): 
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.9.jar)
  
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
FMLPlugin (albedo-1.12.2-1.1.0.jar)
  elucent.albedo.asm.ASMTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
HCASM (HammerLib-1.12.2-2.0.6.25.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
XaeroMinimapPlugin (Xaeros_Minimap_21.16.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)

	HammerCore Debug Information: 
		Dependent Mods: None.

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:ON, OpenComputers:ON, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['BlackholeNebula'/181, l='m land', x=-2201.39, y=92.13, z=-2797.33]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 460.79
	OpenGlRenderer: GeForce GT 1030/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by f4563** [comment]
nvm it just crashes in general without a specific mod

**Comment by f4563** [comment]
nvm i got a older version and it works fine except it takes a long time to load worlds but thats prob a seperate issue

**Comment by asiekierka** [comment]
>at com.wynprice.secretroomsmod.handler.HandlerUpdateChecker.onPlayerJoin(HandlerUpdateChecker.java:72)

The crash comes from SecretRoomsMod.
