### ISSUE TITLE
1.12.2 crash

### ISSUE THREAD

**Issue by Karfagenych** [MightyPirates/OpenComputers#3497]
[crash-2022-01-22_09.30.20-client.txt](https://github.com/MightyPirates/OpenComputers/files/7917268/crash-2022-01-22_09.30.20-client.txt)

**Comment by G0x209C** [comment]
It has not been updated for 1.12.2
Latest supported minecraft version is 1.7.10

**Comment by asiekierka** [comment]
```
    at pro.gravit.launcher.DalCrAFT9nQNVD.daLcrafTb7NnnF(Unknown Source)
    at pro.gravit.launcher.DalCrAFT9nQNVD.main(Unknown Source)
```

The crash log doesn't show OpenComputers, but shows this obfuscated nightmare of a launcher. WON'TFIX unless it is proven it is specifically OC's fault.
