### ISSUE TITLE
Editor Crashing Once clicking on somewhere

### ISSUE THREAD

**Issue by nostopgmaming17** [MightyPirates/OpenComputers#3499]
computer.pullSignal() returns float x and y on the click events

/bin/edit.lua:252: bad argument #2 to 'format' (number has no integer representation)
stack traceback:
[C]: in function 'string.format'
/bin/edit.lua:252: in upvalue setCursor
/bin/edit.lua:655: in local 'onClick'
/bin/edit.lua:708: in main chunk
(...tail calls...)
[C]: in functipn 'xpcall'
machine:799: n global 'xpcall'
/lib/process.lua:63: in function </lib/process.lua:59>
![h](https://user-images.githubusercontent.com/65682727/152245598-87d9946b-eb95-4815-bcc8-59a0b9671989.png)

**Comment by vberezinbadger** [comment]
Try copying the editor from a standard OpenOS floppy. Otherwise, you will have to reinstall the system.

**Comment by nostopgmaming17** [comment]
> Try copying the editor from a standard OpenOS floppy. Otherwise, you will have to reinstall the system.

I knew it wouldn't work since I used openos editor
tried it
and obviously
didn't work

**Comment by Ocawesome101** [comment]
`component.screen.setPrecise(false)` might fix it.

**Comment by payonel** [comment]
i decided to floor the values passed to setCursor in edit. This could have been fixed in the tty layer but that code is so heavily reused that it is hard to measure the impact at this point.
