### ISSUE TITLE
Graphical glitch (See image)

### ISSUE THREAD

**Issue by MFernflower** [MightyPirates/OpenComputers#35]
https://www.dropbox.com/s/oujq2ch2x634787/glitched.png

**Comment by fnuecke** [comment]
What exactly do you mean? The font? That's to be expected due to the scaling. Try the `client.textLinearFiltering` config option or set the screen to use a lower resolution (using the `resolution` program, for example).

If that's not what you mean, please elaborate.

**Comment by MFernflower** [comment]
the font. How do I fix it?

**Comment by fnuecke** [comment]
As I wrote, try the config option or lower the screen's resolution.
