### ISSUE TITLE
Crashed a server

### ISSUE THREAD

**Issue by Kerbal-Man** [MightyPirates/OpenComputers#3507]
![image](https://user-images.githubusercontent.com/100152985/162627454-b8ba1cd4-80a1-4a84-b54e-a9cf4b2e080f.png)
forge 14.23.5.2860 
Minecraft forge 1.12.2

**Comment by Ocawesome101** [comment]
What happened to cause the crash?  Can you reproduce it with only OpenComputers / whatever other mods have any blocks that may be involved?

**Comment by payonel** [comment]
oc is calling getWorld.notifyNeighborsOfStateChange in that stack, but the crash happens in World.java
could be chunk load related, could be another mod trying to do something special with chunk loading.
we'd need a minimal repro please
