### ISSUE TITLE
Robot cannot have Tier 2 screen in Tier 2 slot.

### ISSUE THREAD

**Issue by WazWaz** [MightyPirates/OpenComputers#351]
Tier 1 screen works fine. I understand that the robot is small, but an iPhone has a high resolution color screen while still being horrible and small like would go on a robot (and besides, the floppy drive has a whole piston in it, so the scale is not fixed).

**Comment by Techokami** [comment]
You need to remember that the robot's GUI is the screen, plus your inventory, plus the robot's inventory, plus the robot's upgrade slots. A Tier 2 screen is too big for this.

**Comment by fnuecke** [comment]
It's not really a matter of 'size', per se, but a matter of... purpose. Robots aren't intended to be used as walking full HD screens, the screen is only there to help setting them up / starting them / debugging them ;-)

And while I wouldn't have thought of it, @Techokami argument is valid, too. In fact, they have a lower resolution than a tier 1 screen.

**Comment by WazWaz** [comment]
General purpose computing didn't get to where it is today by designers having an "intended purpose" for them :-).

Who would have thought that tiny colour touch screen would have any purpose before the iPhone? My use case is a robot that wanders around town which players can interact with to request jobs. Is there a better way? For now players put up signs.

Resolution and Size are two different things.
