### ISSUE TITLE
WGET 403 Error

### ISSUE THREAD

**Issue by MistakingManx** [MightyPirates/OpenComputers#3511]
**Version:** 1.12.2

The mod gets a 403 error when trying to download files from my database, but CC-Tweaked can do this just fine.

**Comment by Ocawesome101** [comment]
Try [updating Java](https://youtu.be/fZ2QIarg_c8).  That's the most probable cause of this issue.

**Comment by payonel** [comment]
needs minimal repro steps (e.g. provide devs a sample URL that fails in this way)
also, try updating java as suggested and report the version of java you are using
