### ISSUE TITLE
I Broke my Lua Interpreter

### ISSUE THREAD

**Issue by TheMagikPeanut** [MightyPirates/OpenComputers#3516]
While trying to debug an error preventing me from accessing io.stderr:write() (which turned out to be a simple typo -- OOPS), I made a mistake playing with access control of my io variable, obviously used for referencing said api. Now, it appeaars that I have overwritten the global io var, used in /lib/term.lua:129, now I can't run my lua interpreter, which I would previously have used to solve such an issue in my programs when I failed to use proper access control.

Lua Interpreter apparently can't access stdin (a nil value, it says). How do I fix this? Just reinstall OpenOS?

OC 1.7.5.192
MC 1.12.2

**Comment by RedstoneParkour** [comment]
Just reboot the computer manually (open the case, press the power button to turn off, press the button again to turn on)

**Comment by TheMagikPeanut** [comment]
I had actually attempted that twice and it was still broken. This is not the first time this has happened, but the others were from a failed run of HPM to istall something that errored out, and broke many other things. I tried booting it without the hard disk, then reinserting and booting again, thinking it would flush the buffers, but the broken interpreter remained.

**Comment by payonel** [comment]
remove the drive with openos installed
boot from openos disk
insert openos drive (just run `install openos`, it will ask you where you want to install)
install to openos drive (this will overwrite openos install files)
