### ISSUE TITLE
[1.12.2] OC ClassCircularityError when SecurityCraft (or another Mixin mod) is also loaded.

### ISSUE THREAD

**Issue by maxer4192** [MightyPirates/OpenComputers#3528]
The title of this issue pretty much describes the entire nature of the problem. I'd had an issue with loading OC on a Magma 1.12.2 server and eventually narrowed down the issue to SecurityCraft. Any time both plugins are present it throws a ClassCircularityError. I've attached my `latest.log` with more information:

[Server log file](https://github.com/MightyPirates/OpenComputers/files/8934175/latest.log)

This issue occurs on the latest version of each plugin.

**Comment by asiekierka** [comment]
This is an issue (seemingly? feel free to correct me) introduced by Mixin. Use an additional patch mod to fix it:

https://www.curseforge.com/minecraft/mc-mods/forge-mixin-fix
