### ISSUE TITLE
Error when calling certain functions of CC:Tweaked printer

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#3535]
I am trying to use a ComputerCraft (actually, CC: Tweaked) printer with an OpenComputer using an Adapter block. The printer is recognized when calling component.list(), and some printer functions can be called successfully, but others result in nasty errors. Namely:

- printer.newPage() always throws an error (because it should always be able to be called, unlike endPage)
- printer.endPage() only returns one of these nasty errors when there is no page in progress to end, i.e. when it is not time to run it. In this case, the function returns `nil     "Page not started"` as it's supposed to. When there is a page to end, the function call throws an error instead.
- printer.write() succeeds
- printer.getPaperLevel() succeeds
- printer.setPageTitle() succeeds
- printer.getInkLevel() succeeds
- printer.setCursorPos() succeeds

I verified that the successful commands actually do something by using a ComputerCraft computer to call printer.endPage() and see the result. Unfortunately, without the first two functions, using a CC printer using only an OC is impossible. Both newPage() and endPage() (when it does throw one) return this error:
```
unsupported operation
stack traceback:
        machine:805 in function <machine:798>
        [C]: in function 'error'
        machine:1044: in function <machine:1041>
        (...tail calls...)
        [C]: in function 'xpcall'
        machine:798: in global 'xpcall'
        /lib/core/lua_shell.lua:110: in main chunk
        [C]: in function 'pcall'
        machine:750: in global 'pcall'
        /bin/lua.lua:23: in main chunk
        (...tail calls...)
        [C]: in function 'xpcall'
        machine:798: in global 'xpcall'
        /lib/process.lua:63: in function </lib/process.lua:59>
```

Minecraft 1.12.2
OpenComputers 1.7.5.192
CC: Tweaked 1.89.2

**Comment by asiekierka** [comment]
```
         * Since we abstract away anything language specific, we cannot support the
         * Lua context specific operations ComputerCraft provides.
```

`printer.newPage()` calls `executeMainThreadTask()`, which we do not implement.

**Comment by asiekierka** [comment]
I've contacted SquidDev of CC:Tweaked; the necessary API changes to make this possible to implement are only present in 1.13 onwards.
