### ISSUE TITLE
harddrive corrupted as soon as its taken out of casing

### ISSUE THREAD

**Issue by JanzenJohn** [MightyPirates/OpenComputers#3536]
After installing OpenOS onto a harddrive, everything works until i take the harddrive out of the computer casing

Game Version : 1.10.2
Mod Version : 1.6.2.7

This is in multiplayer on a FTB Beyond server

Taking the drive out, and putting it in again the computer only shows "unrecoverable error, computer halted"

i inspected the disk by booting from a floppy, resulting in following observations
the drive now has two file systems, with both containing the same file structure both filesystems are called "OpenOS", on those filesystems all files appear to be empty but still exist and the tooltip of the harddrive still displays a disk usage of 92160 bytes

the mountpoints /mnt/d27 and /mnt/d27a belong to the disk in screenshot below
![s](https://user-images.githubusercontent.com/51709412/177144810-be99cce1-62c1-4aa1-aee4-874352516f85.png)

the server does still have free space on its harddrive

**Comment by payonel** [comment]
first of all, 1.10 is not get anymore updates
secondly, this isn't a bug but a confusing user experience

openos will auto create dirs for filesystems that "show up"
your drive isn't corrupted, you've confused the system by removing a drive while it was running and  you get extra junk dirs in /mnt/. shutdown if you want to change hardware.

also, if there is some type of actual data loss/corruption -> retest in 1.7.10 or 1.12 and open a new bug report

**Comment by asiekierka** [comment]
This isn't even the latest OC version for 1.10.2; the latest one is 1.7.5. It is exactly this lack of bugfixing from modpack developers which leads us to abandon versions, unfortunately - no point in releasing an update when a good 95% of users come from modpacks with outdated releases.
