### ISSUE TITLE
filesystem / io open function

### ISSUE THREAD

**Issue by istasi** [MightyPirates/OpenComputers#354]
Relative path not working?, by design?, 
Its in 1.7.2-1.2.13.148

lua> =io.open ('fu','w')
nil    "file not found"

lua> =io.open ('./fu','w')
nil     "file not found"

lua> =io.open ('/mnt/955/fu','w' )
{bufferMode="full",  // well, working

same result with filesystem.open ('fu','w') and so forth.

**Comment by Wuerfel21** [comment]
Use ...
io.open(os.getenv("PWD").."fu")
...

**Comment by istasi** [comment]
io.open( shell.resolve ( 'fu' ), 'w' ) also works ^^, but the issue still stands, relative pathing isn't working :-)

**Comment by fnuecke** [comment]
Huh, I never realized `io.open` actually resolved paths in standard Lua, I thought it treated everything as absolute. I guess now's as good a time as any to change it.
