### ISSUE TITLE
version="@VERSION@" in config

### ISSUE THREAD

**Issue by Krutoy242** [MightyPirates/OpenComputers#3546]
After update to `1.7.6+fe5ba4e` version in `config/opencomputers/settings.conf` file changed:
```diff
  # The version of OC this config was generated by. This is used to allow the
  # mod to reset parts of the config when their meaning changed across
  # versions, so that the user does not have to delete it.
- version="1.7.5.192"
+ version="@VERSION@"
```

This looks like a mistake👀

**Comment by PublicVoidUpdate** [comment]
while(true){ignore safeguards}

**Comment by asiekierka** [comment]
oops

**Comment by PublicVoidUpdate** [comment]
> while(true){ignore safeguards}

btw I meant this as a joke to poke fun, I love the work you guys do on this mod, and it is really cool and inspiring. And tbf who hasn't done that before in a program.

**Comment by asiekierka** [comment]
Affects 1.12 only...
