### ISSUE TITLE
Inconsistent Braille character glyphs in the new font

### ISSUE THREAD

**Issue by Fingercomp** [MightyPirates/OpenComputers#3547]
The new font introduced in https://github.com/MightyPirates/OpenComputers/commit/23d218d598a31799a24cd155333675a4fb126414 seems to use Unifont glyphs for a few (but not all) Braille characters. They look quite horrible when used together, to be honest. I doubt that was intended.

![demo](https://i.imgur.com/LU9cenM.png)

**Comment by asiekierka** [comment]
... oops
