### ISSUE TITLE
OpenComputers world Shutdow

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#3549]
OpenComputers
the world continues to collapse in Shutdow

**Comment by asiekierka** [comment]
Insufficient detail - could you please clarify?

**Comment by ghost** [comment]
When exiting the game, it says it stopped responding and the game closes, the world does not open when you enter it again.

**Comment by asiekierka** [comment]
Do you have any crash logs?

**Comment by ghost** [comment]
please wait a while

**Comment by ghost** [comment]
there was a file called pid now the world has opened

**Comment by ghost** [comment]
If there is a problem, I will write
