### ISSUE TITLE
gregtech recipes

### ISSUE THREAD

**Issue by Leftorius** [MightyPirates/OpenComputers#355]
Hey, there are some gregtech recipes which doesn't work

-PrintedCircuitBoard
-Mikrochips
-Cardbase
-Cable
-Robot
-Memory(Tier1)
-Keyboard
-WirelessNetworkCard
-Switch
-PowerDistributor
-Raw Circuitboard
-Controll Unit
-ALU
-Computer Base
- maybe a few more but those all I found at the moment (latest stable version MC1.7.2-1.2.13.148)

**Comment by fnuecke** [comment]
Yeah, it seems pretty much everything changed, item-name-wise in 1.7 GT. We'll wait for it to reach stable to update the recipes. If you want, you can start fixing them yourself, though, they're in a plaintext format after all :-)

**Comment by Leftorius** [comment]
He's done a lot of his stuff so his beta is really stable and you can use a lot of materials :) I would do it by myself but I have really no idea how to search some OreDict items without NEI Plugins :DDD
