### ISSUE TITLE
.shrc doesn't work

### ISSUE THREAD

**Issue by ProgramCrafter** [MightyPirates/OpenComputers#3550]
Putting any programs in .shrc file leads to following error:
![](https://computercraft.ru/uploads/monthly_2022_09/image.png.4682c7438a29ad3c4e12661b49785025.png)

This bug is related to c9530ae:

- .shrc file is executed by source.lua,
- which starts a shell process and tells it to continue with environment and the shell command
  https://github.com/MightyPirates/OpenComputers/blob/ae644f3c74002a4d22ac4efeef5d9914deb09cad/src/main/resources/assets/opencomputers/loot/openos/bin/source.lua#L33
- but shell after c9530ae does not expect environment as its argument and passes it to /lib/sh.lua itself,
  https://github.com/MightyPirates/OpenComputers/blob/ae644f3c74002a4d22ac4efeef5d9914deb09cad/src/main/resources/assets/opencomputers/loot/openos/bin/sh.lua#L44
- and that creates an error.

Possible way to fix: replace https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/openos/bin/source.lua#L33 with `  process.internal.continue(source_proc, line)`.

**Comment by asiekierka** [comment]
Related to https://github.com/MightyPirates/OpenComputers/issues/3548

**Comment by payonel** [comment]
we've decided to revert a fix for sh command actions that caused some regression. this issue is fixed by that revert. thank you
