### ISSUE TITLE
tier 2 and 3 screen textures are swapped

### ISSUE THREAD

**Issue by Pietropil15418** [MightyPirates/OpenComputers#3551]
in the 1.7.6 update, the tier 2 and 3 screen textures got swapped.
screenshots:
![2022-09-03_17 48 52](https://user-images.githubusercontent.com/107318636/188278391-11f7baed-5eb8-4358-98ae-01f00cbd2c72.png)
![2022-09-03_17 48 55](https://user-images.githubusercontent.com/107318636/188278397-45c8480a-c75c-4920-bb9a-1dbbd199d592.png)

**Comment by asiekierka** [comment]
Fixed in 1.7.7.
