### ISSUE TITLE
Creative Tablet does not boot

### ISSUE THREAD

**Issue by payonel** [MightyPirates/OpenComputers#3552]
> By the way, the creative (from inventory) tablet does not work at all (hand made tablet works)
![2022-09-02_18 10 04](https://user-images.githubusercontent.com/79054301/188180243-55de9122-a88a-4c57-bd26-486ed2c2965f.png)

_Originally posted by @Bumer-32 in https://github.com/MightyPirates/OpenComputers/issues/3548#issuecomment-1235619842_

**Comment by payonel** [comment]
this issue persists even with the sh env changes reverted

**Comment by asiekierka** [comment]
It did work for me on 1.7.10, last I checked... Is this 1.12-specific?

**Comment by Bumer-32** [comment]
i tested on 1.12.2

**Comment by TheCodex6824** [comment]
I just tested on 1.7.10 and 1.12.2, and it only happens on 1.12.2. I think I figured out the cause of it, and opened a PR to fix it: #3565

**Comment by asiekierka** [comment]
Fixed, thank you!
