### ISSUE TITLE
 OpenComputers-MC1.10.2-1.7.4.228

### ISSUE THREAD

**Issue by daviesharry** [MightyPirates/OpenComputers#3554]
I receive blank screens on my server with no errors 
minecraft version: 1.10.2
forge version: 12.18.3.2511
modpack: space astronomy 2 v1.5.7
screenshot of issue: https://imgur.com/vNvbL3x
Tried repairing settings config file to no avail
Already patched the file but still receving issues

**Comment by asiekierka** [comment]
Please update to the latest stable version of OpenComputers (That's v1.7.5 on 1.10.2) first.

**Comment by daviesharry** [comment]
> Please update to the latest stable version of OpenComputers (That's v1.7.5 on 1.10.2) first.

I have done this however the modpack now gives an error: net.minecraftforge.fml.common.MissingModsException: Mod actuallycomputers (ActuallyComputers) requires [OpenComputers@[1.6,)]

ActualllyComputers seems to be on the latest version there is for 1.10.2

**Comment by asiekierka** [comment]
That would imply that OpenComputers is no longer present... Which specific JAR do you have, and is it for the correct Minecraft version?

**Comment by daviesharry** [comment]
The jar is [OpenComputers-MC1.10.2-1.7.5.245.jar](https://mediafiles.forgecdn.net/files/2828/355/OpenComputers-MC1.10.2-1.7.5.245.jar)

**Comment by daviesharry** [comment]
I have got past that error but found that there is an error that shows: native libraries not available
I only receive this error when playing on my server not on singleplayer
It is a ubuntu oracle cloud server @asiekierka

**Comment by asiekierka** [comment]
It's an AArch64 server. OpenComputers prior to 1.8.0 won't officially support AArch64 servers, only x86/x86_64/ARM ones - and 1.8.0 is unlikely to come out for 1.10.2.

You can try following the workarounds in https://github.com/MightyPirates/OpenComputers/issues/3466 - but we do not support this.
