### ISSUE TITLE
Improve forceNativeLibWithName config option

### ISSUE THREAD

**Issue by TheCodex6824** [MightyPirates/OpenComputers#3561]
Currently, using the `forceNativeLibWithName` option isn't a perfect solution on platforms missing native library support.

There are 3 native libraries to load, one for lua 5.2, 5.3, and 5.4. However, that config option only allows specifying a single string, meaning only one custom library can be loaded. This means that platforms without native support in the code cannot have every version of lua working at the same time as normal. Also, due to how `LuaStateFactory` handles native library loading, if the last library to be loaded is not found (or in other words, the lua 5.4 native isn't used as the single version specified in the config), it thinks that there is no native library support and disables that system entirely.

Possible solutions for this are:

1. Changing the `forceNativeLibWithName` to take a string pattern instead of just a normal string. For example, there could be a "$version" pattern that gets expanded to the lua version being loaded, so users can set the option to something like "libjnlua$version-linux-ppc64.so" to handle the different versions.
2. Changing the `forceNativeLibWithName` option to be a map of lua version to library name instead of a single string, with an entry for each lua version.

Edit: It occurred to me that the issue below is probably happening because of the `forceNativeLibWithName` issue described above

<del>Lastly, using this config option still requires users to pack natives into the OC mod jar itself to be able to load them. Ideally, the native loader should check if an appropriately named native is in the place it would have extracted a native to, and if so, use that native instead of loading from the jar. The final native name as used by the mod does include the OC version though, so users would have to rename their natives after every update - a bit annoying but maybe fine? It might also be a good opportunity to combine this with the `forceNativeLibWithName` changes above, and make that option try loading libraries from the filesystem first instead of looking in the jar. </del>

**Comment by asiekierka** [comment]
The way I see this would be:

1. Adding a `forceNativeLibPlatform` option, which takes strings of the type `windows-aarch64`, or `darwin-x86_64` - this allows you to pick a specific type of the library, without forcing the Lua version prefix.
2. Adding a `forceNativeLibPathFirst` option, which takes a directory; if present, OpenComputers tries to load natives from that directory first, without unpacking anything from the JAR.

`forceNativeLibWithName` would thus disappear.

What do you think?

**Comment by TheCodex6824** [comment]
I think your idea is much better than mine. `forceNativeLibPathFirst` sounds perfect. For `forceNativeLibPlatform`, my only concern would be with the file extension part of the library name. I know Linux, BSDs, and Solaris all use `.so`, and windows and mac have `.dll` and `.dylib` - is there anything I left out that uses something different? If that covers it all, we can probably do a platform check for `.dll` and `.dylib`, and just make the fallback `.so`.

**Comment by TheCodex6824** [comment]
So I started working on this and noticed that 64-bit detection seems to only check for x86_64 and not others like aarch64 - should I make a separate PR for that or roll it into this one? Edit: I'm just going to include it, it's relevant to native library architecture support anyway
