### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by ArtyomKor** [MightyPirates/OpenComputers#3563]
Hello! When I try to build the mod, I get an error:
[error.txt](https://github.com/MightyPirates/OpenComputers/files/9630959/error.txt)

**Comment by asiekierka** [comment]
```                                                             
java.lang.IllegalStateException: Could not find tools.jar. Please check that C:\Program Files\Java\jre1.8.0_341 contains a valid JDK installation.
```

You installed the Java Runtime Environment; to develop Java-based software, you need the Java Development Kit.
