### ISSUE TITLE
[Feature] Computers need to explode

### ISSUE THREAD

**Issue by rhjobe** [MightyPirates/OpenComputers#357]
Open Computers needs a little more oomf. You should add that by making computers explode if they get over-worked. Everyone loves explosions!

Though this should be added if you ever add a hard mode! (Along with fire)

**Comment by Kilobyte22** [comment]
I don't see how exactly you would measure 'over-worked'. plus, does your real computer blow up just because it is 5 h on 100% CPU usage? I don't think so ;)

**Comment by rmellema** [comment]
Exploding Robots = Programable Creepers
Nuff said.

**Comment by Techokami** [comment]
EXPENSIVE programmable creepers.
Perhaps this would be better as a mod? e.g. a Detonation Card for computers and robots deemed to be too sensitive to have tampered? I probably won't make it but someone else can.

**Comment by Vexatos** [comment]
I really don't like this idea. Especially if you don't play on easy recipe mode, computers are extremely expensive. They shouldn't ever explode.

**Comment by Wuerfel21** [comment]
TNT card?
tier1: creeper
Tier2:charged creeper
Tier3: nuke

Just random idea...

**Comment by Kilobyte22** [comment]
Small side note, yesterday in IRC we had (more jokingly) the idea to make computers explode if someone tried to mount something as /c: which @PotatoTrumpet did on a server yesterday :P

**Comment by fnuecke** [comment]
Very jokingly ;-) If anything this might be an easter egg one day. But it'd probably make for a better addon than something built-in.
