### ISSUE TITLE
opencomputers doesn't work correctly with keyboard shortcuts

### ISSUE THREAD

**Issue by Bumer-32** [MightyPirates/OpenComputers#3570]
if you press combinations of keys and then press other keys, the system may be rebooted or the desired character may not be written
https://photos.app.goo.gl/LjD86iD1TuJGPumW7
and this works not only in open OS but also in other systems, for example Mine OS:
https://photos.google.com/search/_tra_/photo/AF1QipN7bO5ws7CCPzoYUKFE-kUkijeGI3gfdZYXGQJ1
and the system crashed when i pressed ctrl or alt

**Comment by payonel** [comment]
what you are seeing is the effect of ^d (ctrl+d)
it is the same as the exit command

**Comment by Bumer-32** [comment]
That's not what I meant! after I press CTRL+D (or something else) then almost every button becomes work as CTRL+D
