### ISSUE TITLE
[MC1.12.2] OC1.12.2-1.7.7 not unavailable on the maven repository

### ISSUE THREAD

**Issue by OptimusZeGaming** [MightyPirates/OpenComputers#3573]
Hello, 

I tried to download the latest release of OC1.12.2 version 1.7.7 with gradle, but it is not available on the maven repository, will it be available?

**Comment by asiekierka** [comment]
`maven.cil.li` is gone. Use something like https://github.com/MightyPirates/OpenComputers/packages/1624843
