### ISSUE TITLE
unicode.sub("test", 0) throws java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by IgorTimofeev** [MightyPirates/OpenComputers#3579]
Mod version: OpenComputers-MC1.12.2-1.8.0-snapshot-20220917+efb20a2.jar
Minecraft Version: 1.12.2
Java Version: 1.8.0_51

![image](https://user-images.githubusercontent.com/11760002/203051606-3a321b26-7db1-44d6-82c9-645fcf87573a.png)

**Comment by asiekierka** [comment]
Confirmed. Exclusive to 1.8.0 snapshots.
