### ISSUE TITLE
Bug with a pre-release snapshot 

### ISSUE THREAD

**Issue by Veritaris** [MightyPirates/OpenComputers#3589]
Minecraft version used: 1.7.0 on Cauldron
Mod version: **OpenComputers-MC1.7.10-1.8.0-snapshot-20220918+00c5a9b-universal.jar**
Hi! 
IDK if SNAPSHOT reports are accepted but the following bugs were found 
As for me this is a bug with numbers interpretation 
The following code snipped is failed at last row:
```lua
print(os.time())
print(type(os.time()))
math.randomseed(1)
print("after int randomseed")
math.randomseed(os.time() + 1)
```

![Raised error](https://demo.web.veritaris.me/static/media/lua_snippet_error.png)

Also one of players on server reported that for [this](https://pastebin.com/HMyh7xHt) code he got the following error:
![](https://demo.web.veritaris.me/static/media/mo_teleporter_error.bmp)

At 1.7.7 mod version everything is okay, so error is somewhere between 1.7.7 and 1.8.0

**Comment by asiekierka** [comment]
Valid bug report. Not sure when I'll have the time to look into it; snapshot versions are alphas for a reason, though!

**Comment by asiekierka** [comment]
Appears to be fixed in the later commits.

**Comment by asiekierka** [comment]
https://github.com/MightyPirates/OpenComputers/commit/c71c1479ddec8f3288e7bc2f75204d220bb6742c
