### ISSUE TITLE
OC Suspected Memory Leak

### ISSUE THREAD

**Issue by CSX8600** [MightyPirates/OpenComputers#3591]
I noticed my server, who's allocated 16GB, was maxing out RAM usage. After performing a heap dump and popping it into Eclipse Memory Analyzer, the number 1 suspect for the memory leak was Open Computers. I've attached the report which can be drilled into using the "Details" link. If you need any other details from the heap, please let me know and I can do my best to get you that data.

[heap-2022-12-22_15.45.33_Leak_Suspects.zip](https://github.com/MightyPirates/OpenComputers/files/10292174/heap-2022-12-22_15.45.33_Leak_Suspects.zip)

Edit: I suppose it would help if I mentioned mod version :) - 1.7.6 (game version 1.12.2)

**Comment by asiekierka** [comment]
Bad interaction with Minecraft Transport Simulator. I'll *try* to fix it, but no promises...
