### ISSUE TITLE
Game freeze when connecting to ComputerCraft Disk Drive via the Adapter

### ISSUE THREAD

**Issue by kristibektashi** [MightyPirates/OpenComputers#3596]
When I try to connect an OC computer to the CC Disk Drive via the Adapter the game freezes and I have to kill the process. 
I haven't tested if other CC peripherals are affected by this.

Latest.log: https://gist.github.com/kristibektashi/b8034dc553d0dfde0087a6358e869998

Minecraft version: 1.12.2
Forge: 14.23.5.2860
CC:Tweaked version: 1.89.2 (latest for 1.12.2)
OpenComputers version: 1.8.0-snapshot-20220917 (also tested 1.7.5 and 1.7.7)

Steps to reproduce: 
Step 1: Build an OC computer and power it on
Step 2: Place an Adapter next to the computer
Step 3: Place a CC Disk Drive next to the Adapter
Step 4: Insert a CC Floppy Disk in the Disk Drive
Expected behavior: The game doesn't freeze and the floppy disk in mounted in /mnt directory 
Observed behavior: The game freezes and I have to kill the process

**Comment by KosmosPrime** [comment]
I've encountered this issue while checking 1.16 compatibility, and can confirm it also happens in 1.12.2. In my testing it never crashed though, only slowing down very rapidly. The port managed to produce a crash report (that's how I found it) but the UI merely became unresponsive.
I believe that OC creates a wrapper component for CC stuff and attaches it, which causes that to create an OC wrapper peripheral and attach that, which then creates a new CC wrapper and so on.
I've patched this with KosmosPrime/OpenComputers@b2d32e2802289aea9926b233bc6f051b941731ac but taking an in-depth look at CC compatibility again is on my to-do list.
