### ISSUE TITLE
Event types?

### ISSUE THREAD

**Issue by applejag** [MightyPirates/OpenComputers#36]
I was looking at https://github.com/MightyPirates/OpenComputers/wiki/API-Event and it got a way to add listeners
event.listen(name: string, callback: function): boolean
but what is the names?

**Comment by fnuecke** [comment]
Please use the forums (MCF or opencomputers.net) for support.

Events are the same thing as signals, except that they are automatically distributed to multiple callbacks (not just the one doing the `event.pull`), so [the list of signals](https://github.com/MightyPirates/OpenComputers/wiki/Signals) is probably what you're looking for.
