### ISSUE TITLE
[Pre-release] Unsupported data type (java.lang.Long)

### ISSUE THREAD

**Issue by Matrix0150** [MightyPirates/OpenComputers#3602]
Mod version: OpenComputers-MC1.12.2-1.8.0-snapshot-20220917+efb20a2

There's an issue when calling Modem.Broadcast/Send with varargs
Using a float is fine, but not an integer.

require("component").modem.broadcast(25565, 1.) --This works fine
require("component").modem.broadcast(25565, 1) -- Unsupported data type: 1 (java.lang.Long)

**Comment by asiekierka** [comment]
Duplicate of https://github.com/MightyPirates/OpenComputers/issues/3568
