### ISSUE TITLE
computer.getDeviceInfo doesn't pause the computer immediately

### ISSUE THREAD

**Issue by Fingercomp** [MightyPirates/OpenComputers#3603]
The method is supposed to pause the computer for a second, but this only happens at the next yield point (`os.sleep` or an indirect method call, for example).

![](https://i.imgur.com/wq15x2n.png)

I would expect both lines to print something around 1 second, yet the first one doesn't actually pause the machine until later.

**Comment by AR2000AR** [comment]
This are the problematics lines : https://github.com/MightyPirates/OpenComputers/blob/1c0dc67182292895495cb0d421ec0f529d243d74/src/main/scala/li/cil/oc/server/machine/Machine.scala#L461-L463
Potential fixes are removing `context.pause(1)` or making the methods a indirect call
