### ISSUE TITLE
Using wget program on GitHub will download older files, even when verifying that Github did in fact update.

### ISSUE THREAD

**Issue by Corbinhol** [MightyPirates/OpenComputers#3604]
Mod Version: OpenComputers-MC1.12.2-1.7.7+5413028.jar

Using wget program on GitHub will download older files, even when verifying that Github did in fact update.
Restarting the computer sometimes will fix it, but sometimes even that doesn't fix it.

Steps to reproduce:
-Upload code to github
-Download raw using wget
-Commit/push new code to github
-Verify that the code did in fact change
-redownload using the same github raw url
-check the new file, chances are will not be updated

I find this frustrating because I personally like the option of pushing to github then downloading from there, instead of using pastebin.

**Comment by PublicVoidUpdate** [comment]
Is this an issue with GitHub? Or is it an issue with wget?

**Comment by Corbinhol** [comment]
> Is this an issue with GitHub? Or is it an issue with wget?

This is not an issue with GitHub, because when loading up the raw version of the code in my browser, that updates immediately. But when downloading the same URL through wget, it's the version that I downloaded previously and not the updated version.

**Comment by PublicVoidUpdate** [comment]
Huh, thats really interesting, i wonder if its a caching issue. There must be some pre checking that is stopping it from drawing from the new file

**Comment by AR2000AR** [comment]
It is weird that you can see the raw up to date version in your browser.
Github cache the raw file for 5 minutes.

**Comment by asiekierka** [comment]
I can reproduce the issue on GitHub's side. It's their CDN - nothing we can do about it.
