### ISSUE TITLE
Bug With Forge Mod Server (1.12.2)

### ISSUE THREAD

**Issue by Klsnjns** [MightyPirates/OpenComputers#3606]
I Get  the error  java: symbol lookup error: /home/container/./OpenComputersMod-1.7.7+5413028-lua53-native.64.so: undefined symbol: floor When  Starting a Computer

**Comment by asiekierka** [comment]
What Linux distribution and version are you on?

**Comment by asiekierka** [comment]
No required information provided; closing.
