### ISSUE TITLE
Consider using Luna to execute Lua

### ISSUE THREAD

**Issue by JasonS05** [MightyPirates/OpenComputers#3607]
I found a neat project called [Luna](https://github.com/kroepke/luna) which is a Lua to JVM bytecode compiler. It might be possible to use as a drop-in replacement for your current Lua implementation. Because the resulting Lua code runs on the JVM directly instead of an interpreter that's run on the JVM, it should enjoy enhanced speed. It also supports what they call "CPU accounting" which is basically what you do already where the Lua execution is suspended after a certain number of instructions are executed. If you do use this, it seems like the biggest change would be a different API on the Java side, but besides that from what little I know of the project it seems like it should be a perfect fit for OpenComputers.

**Comment by FatalMerlin** [comment]
It's worth noting that this implementation is unfortunately incomplete https://github.com/kroepke/luna/blob/master/doc/CompletenessTable.md

**Comment by asiekierka** [comment]
It is an interesting project, but not up to date with Lua 5.4 and no longer maintained as of 2017 - as such, relying on it with the current active developer count (zero) would be unwise. Closing for now.
