### ISSUE TITLE
Breeks Support for 1.12.2

### ISSUE THREAD

**Issue by sreekrishna5** [MightyPirates/OpenComputers#3608]
Is it possible to run 1.7.10 ic2 crop breeding program from gtnh on 1.12.2 cause the geolyzer is not getting data from ic2 crops

**Comment by asiekierka** [comment]
If https://github.com/MightyPirates/OpenComputers/pull/3317 gets merged (there's an outstanding design issue), probably!

Remember that GTNH uses a custom version of OpenComputers, which provides many features the official version does not.
