### ISSUE TITLE
Broken compatibility with WarpDrive

### ISSUE THREAD

**Issue by Alex-1248** [MightyPirates/OpenComputers#3611]
With OC 1.8.0, most attempts to turn on a computer with the WarpDrive control program installed end in an error. It takes several attempts to successfully turn on. OC 1.7.7 does not have this problem.

Mc 1.7.10:
![Mc 1 7 10](https://github.com/MightyPirates/OpenComputers/assets/114651872/ecef5206-d0b2-4a1e-a0e2-da1f3617ab7d)

Mc 1.12.2:
![Mc 1 12 2](https://github.com/MightyPirates/OpenComputers/assets/114651872/a407ed92-3bfc-475b-9dce-08312b39281d)

**Comment by asiekierka** [comment]
Which exact version are you using? There were 1.8.0 snapshots which had this issue, but I cannot reproduce it on the final 1.8.0 release.

**Comment by Alex-1248** [comment]
OpenComputers-MC1.7.10-1.8.0+8fb006a-universal and OpenComputers-MC1.12.2-1.8.0+9833087 downloaded from curseforge. If I understand correctly, these are not snapshots, although for some reason the freshly installed OpenOS is designated as 1.8.0-snapshot (this can be seen in the screenshots). I previously installed an alpha, presumably OpenComputers-MC1.7.10-1.8.0-snapshot-20220918+00c5a9b-universal, but I uninstalled it a long time ago.

**Comment by Alex-1248** [comment]
After disabling all options that mention Lua 5.3 in the OC config file, the problem disappears. Tested on Mc 1.7.10 and Mc 1.12.2.

**Comment by PublicVoidUpdate** [comment]
Juat hold the cpu, sneak and (left?) Click till it says 5.2

**Comment by Alex-1248** [comment]
Thanks, I didn't know about that. Yes, sneak and right click with the cpu also work. But is it normal that WarpDrive almost does not work with default settings? On OC 1.7.7 this problem does not appear when using Lua 5.3.

**Comment by PublicVoidUpdate** [comment]
I believe 1.7 is the main version, so it's possible new changes including Lua libraries and the like will hit it first.

**Comment by Veritaris** [comment]
@Alex-1248, I think your issue same as mine https://github.com/MightyPirates/OpenComputers/issues/3589
The problem is that WarpDrive is not being updated for a while for 1.7.10 (last commit from Lem was at 2018) 
Currently I work on some updates for this version's fork but not sure when it will be finished and I can publish it

**Comment by Alex-1248** [comment]
@Veritaris I also think that our problems are similar. But I think the problem is with OpenComputers, not WarpDrive.

I was able to pinpoint the error more precisely. The test was made on OpenComputers-MC1.7.10-1.8.0+8fb006a-universal with CPU in Lua 5.3 mode.

Apparently when I turn on the OC computer the error occurs on this line:

math.randomseed(os.time())

os.time() often returns a number with a non-zero decimal part. If math.randomseed() receives a number with a non-zero decimal part (eg 5.5), an error occurs. This error does not occur if the CPU is running in Lua 5.2 mode.

**Comment by Veritaris** [comment]
Thus you mean that when you just turned your PC on (without extra components attached) with CPU in Lua 5.3 mode then you got this error?

**Comment by Alex-1248** [comment]
I mean, I get an error if I start an OC computer with the WarpDrive control program installed and the CPU is running in Lua 5.3 mode. It seems that in the latest release of the OC, the math.randomseed() function forgot how to accept numbers with a non-zero decimal part in Lua 5.3 mode and the os.time() function started returning numbers with a non-zero decimal part.

**Comment by Veritaris** [comment]
Oh, got your point

**Comment by asiekierka** [comment]
https://github.com/MightyPirates/OpenComputers/commit/c71c1479ddec8f3288e7bc2f75204d220bb6742c
