### ISSUE TITLE
Add support for Windows on Arm

### ISSUE THREAD

**Issue by kristibektashi** [MightyPirates/OpenComputers#3612]
Since it wasn’t added with #3466 I’m opening a separate issue for this

**Comment by asiekierka** [comment]
Does a version of Java 8 exist such that it runs *natively* on ARM64 Windows?

**Comment by kristibektashi** [comment]
> Does a version of Java 8 exist such that it runs *natively* on ARM64 Windows?

No, there doesn't seem to be any. Only Java 16 and above exists for Windows on ARM

**Comment by asiekierka** [comment]
In that case, I don't see a need for OpenComputers to handle this issue at this time; it can be reopened once OpenComputers officially moves past Minecraft 1.12.x.
