### ISSUE TITLE
Unable to connect to the internet

### ISSUE THREAD

**Issue by CorneliusCornbread** [MightyPirates/OpenComputers#3615]
Behaviour I'm experiencing is the exact behaviour described in this post https://www.reddit.com/r/OpenComputers/comments/13k28wo/how_to_access_internet/

- Unable to download things via wget
- oppm can't connect to the internet
- works just fine in single player

Unraid (Docker, via Crafty Controller)

![image](https://github.com/MightyPirates/OpenComputers/assets/8294697/47610a02-60c9-4443-a177-c06206a24ed3)

**Comment by linuxchr** [comment]
Same for me on arm64 server with pterodactyl, this means that minecraft is in docker containers.

**Comment by Kry-a** [comment]
I'm having the exact same issue as well, same setup, arm64 server on Pterodactyl, I cannot access the internet at all with the same error.

OpenComputers 1.7.7 does not have this issue, it only started occurring after updating to 1.8.0.

**Comment by asiekierka** [comment]
Fixed by reverting the HttpClient patch.
