### ISSUE TITLE
java.io.FileNotFoundException: /tmp/OpenComputersMod-native.64.so (Permission denied)

### ISSUE THREAD

**Issue by eonicdesign** [MightyPirates/OpenComputers#362]
I host on a shared server environment where multiple instances of Yogscast Complete are running on a node, all these instances use COMPUTERCRAFT1.63.jar.

When one server with the user mc1234 boots up it creates the OpenComputersMod-native.64.so file successfully in the /tmp/ folder

-rw-rw----  1 mc1234   mc1234   266952 Jun 26 15:48 OpenComputersMod-native.64.so

When the second server with the user mc4321 boots up it tries to access the file in the /tmp/ folder and fails since it does not have permission to overwrite or use files created by user mc1234, 

The error is as follows
java.io.FileNotFoundException: /tmp/OpenComputersMod-native.64.so (Permission denied)

For the mod to run on a multiserver system like Multicraft the OpenComputersMod-native.64.so would either need to put in a tmp folder in the server folder or the prefixed with the username in the tmp folder mc1234.OpenComputersMod-native.64.so

Have you come across this issue and is there a suitable fix for this error

**Comment by fnuecke** [comment]
Oh, very good point. I'll make it set the permissions more liberally when creating the file.

**Comment by eonicdesign** [comment]
Thanks so much for resolving so quickly

**Comment by fnuecke** [comment]
No problem. If you want to wait with OC 1.3 until it's properly released, I just backported the change to the 1.2 branches (http://ci.cil.li/job/OpenComputers-1.2-MC1.6/ and http://ci.cil.li/job/OpenComputers-1.2-MC1.7/). Let me know if it doesn't work like it should!

**Comment by eonicdesign** [comment]
My initial test of the http://ci.cil.li/job/OpenComputers-1.2-MC1.6/ branch was a success, I've booted two identical servers with no problem at all. I will do some more tests, thanks again for sorting this out.
