### ISSUE TITLE
Control rod API for Extreme Reactors 1.12.2 is broken

### ISSUE THREAD

**Issue by CorneliusCornbread** [MightyPirates/OpenComputers#3620]
Attempting to call component.br_reactor.getControlRodLevel(1) returns an error saying `Invalid argument 0, expected number"
![image](https://github.com/MightyPirates/OpenComputers/assets/8294697/f2b1b40b-c4d2-4c93-95f1-7b015dc42c15)

**Comment by asiekierka** [comment]
`ArgumentsImpl` needs a rewrite of `checkX` and `isX` for numbers to be more permissive/proper in light of JNLua now passing Longs and such around.

**Comment by asiekierka** [comment]
(This is another OC 1.8.0+ regression, so downgrading to OC 1.7.7 should be fine for now.)
