### ISSUE TITLE
OpenComputers 1.12 Crashes after it's removal from Mods folder

### ISSUE THREAD

**Issue by juleklO** [MightyPirates/OpenComputers#3624]
I wanted to modify my 'The 1.12.2 Pack' modpack by removing the OpenComputers mod. After doing so, the game crashes on loading. 

Report here:
https://mclo.gs/2lAkT2u

Hope it's not too old of an version to get help for, cheers!

**Comment by asiekierka** [comment]
One of the mods in your modpack has a hard dependency on OpenComputers. It's probably this one: https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing-oc-compat
