### ISSUE TITLE
[SECURITY] Releases are built/executed/released in the context of insecure/untrusted code

### ISSUE THREAD

**Issue by JLLeitschuh** [MightyPirates/OpenComputers#3625]
Duplicate of #3048, but the vulnerability is back:

https://github.com/MightyPirates/OpenComputers/blob/affac839cb313e5bfb2118e190fbf0ba7d22cfd4/build.gradle#L8-L11

https://github.com/MightyPirates/OpenComputers/blob/affac839cb313e5bfb2118e190fbf0ba7d22cfd4/build.gradle#L108-L113

See my writeup:

[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
[Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)

**Comment by asiekierka** [comment]
New maintainer, same old problems, it seems ^^

**Comment by JLLeitschuh** [comment]
If you upgrade to the latest version of Gradle, Gradle would have caught this for you by the way. Just a heads up

**Comment by asiekierka** [comment]
Minecraft modding plugins for Gradle tend to meddle with internals a lot, so they're often tied to specific Gradle releases, at least in terms of the major version.
