### ISSUE TITLE
T2 Redstone made my Wireless Frequency permanently on

### ISSUE THREAD

**Issue by MyNameIsKodos** [MightyPirates/OpenComputers#363]
Okay, so I know this is technically user error since I should've disabled the signal before removing my card, but here's what I did.

Use T2 card in a computer, set frequency 100 of Wireless Redstone to true
Removed said card, and later it got deleted because I wasn't thinking and cleared my inventory.  Now, even from the same computer, I can't disable that signal because it's not the same address on the new T2 Redstone card, so my frequency 100 Wireless redstone is always on.

**Comment by fnuecke** [comment]
I cannot reproduce this, not in SSP, SMP, devenv or normal MC (using WR-CBE, which, as discussed on IRC is the same you're using).

Can you reliably reproduce this? If so, can you give me the exact steps? Thanks!

**Comment by MyNameIsKodos** [comment]
Just woke up, will try now and edit in results.

EDIT: Can't reproduce either.  Might have been a fluke, or I might not be doing proper reconstruction of the thing.  I'll close  this for now, and if I can lock down a duplicatable and reliable method of doing this again, I'll reopen.

**Comment by fnuecke** [comment]
All right, thanks :-)

**Comment by TorakWolf** [comment]
Is not you using the receiver to move one carriage from Redstone in Motion? If yes, then you cannot solve the problem... It is one problem with Forge Multipart and RIM.

**Comment by TorakWolf** [comment]
Anyways, I posted in the OpenPrinter forum thread about the fact the callback .writeIn is not working, but do it have been renamed? Also, how I can print one list of callbacks in order to not ask?
