### ISSUE TITLE
powering my computer with immersive engineering?

### ISSUE THREAD

**Issue by mrnick942** [MightyPirates/OpenComputers#3631]
how do i power my computer with immersive engineering mod?

**Comment by PublicVoidUpdate** [comment]
put the lv connecter on a OC converter, then wire that to your computer if the normal method doesnt work

**Comment by mrnick942** [comment]
what is an oc converter?

> put the lv connecter on a OC converter, then wire that to your computer if the normal method doesnt work

**Comment by PublicVoidUpdate** [comment]
Open computers power converter

**Comment by mrnick942** [comment]
oh ok

**Comment by mrnick942** [comment]
how am i supposed to power the lv wire though

**Comment by PublicVoidUpdate** [comment]
Same way you would a normal Immersive Engineering wire, if you need help id suggest youtube as it is a bit too graphical for me to easily type.

**Comment by mrnick942** [comment]
so just power it with redstone?

**Comment by PublicVoidUpdate** [comment]
No... check for a immersive engineering tutorial on youtube, IE has power gen, its own wire system and its own battery system.

**Comment by mrnick942** [comment]
please type it out as best as you can because i haven't found a helpful tutorial yet

**Comment by mrnick942** [comment]
please

**Comment by PublicVoidUpdate** [comment]
https://www.youtube.com/playlist?list=PLQzDSnrhrcyyK2n3-obCpHJbhQ7HR4Ie9

**Comment by mrnick942** [comment]
i need to get sleep so email me tomorrow 3:30 pm gmt-4 at mrnick9469449@gmail.com

**Comment by asiekierka** [comment]
This is an issue tracker for bugs and feature requests with the mod, not a personal support contract. Asking unpaid volunteers to e-mail you personally with tailored advice is kind of rude.

**Comment by asiekierka** [comment]
Please take discourse like this to a more player-oriented community - there are many Discord servers, online forums, and such which can help you better.

**Comment by mrnick942** [comment]
I am so sorry I was just in a hurry to get a mod working i will not do anything like this ever again

**Comment by asiekierka** [comment]
It's fine! I'm here to give you advice; not punish you.

The OpenComputers tracker is mostly read by developers of the mod, who are not always the best people to help with issues which involve another mod (say, Immersive Engineering). There are communities which are mostly read by *players*, and those often have a better awareness of how all the mods in a large modpack interact with each other.

Also, taking discussion private doesn't help others - if it's public (as this discussion was initially), other people who look for the answer to the same question in the future can find it.

Good luck and enjoy your game!

**Comment by mrnick942** [comment]
I had been trying to do something for like 4 hours so I was desperate so ill just give up now

**Comment by asiekierka** [comment]
Your choice; but I encourage you to keep tinkering with it, if that's something you enjoy.

**Comment by mrnick942** [comment]
I need to go to bed so bye
