### ISSUE TITLE
Is it possible to create a shell script for OpenOS?

### ISSUE THREAD

**Issue by wqferr** [MightyPirates/OpenComputers#3639]
I would like to create a script such as

```
regex='.*\s\s*$'
cat file1 file2 | grep "$regex"
```

and the like. I understand it's very much not trivial so this isn't a feature request, only a check that it actually isn't possible.

I'm playing in MC version 1.12.2

On a related note, is it possible to control process I/O with Lua? Like running a program and reading its output?

**Comment by brisingraerowing** [comment]
For the second question there's `shell.execute`.

See [the shell library docs](https://ocdoc.cil.li/api:shell) for more info.

**Comment by wqferr** [comment]
Thank you. For documentation's sake, I also discovered the `source` command which sources a shell script file. I was just confused because, unlike in a Linux shell, the default interpreter for a source file is `lua`, not `sh`.
