### ISSUE TITLE
GPU colors aren't working properly

### ISSUE THREAD

**Issue by MyNameIsKodos** [MightyPirates/OpenComputers#364]
I'll try to keep this as concise as I can.  Upon running this program;

local component = require("component")
local gpu = component.gpu

local function setColor(bg, fg)
gpu.setBackground(bg)
gpu.setForeground(fg)
return
end

for i = 1,15 do
setColor(i, i + 1)
print("Test")
end

---

The resulting output on my screen was black text on a black background, and after the program executed, my text at the prompt was changed to black as well.  Luckily a quick 'dir' fixes this, but it makes for rather limited choices in programming.  For reference, I am on 1.6.4, using build 456 RC1 of OC.

**Comment by MyNameIsKodos** [comment]
_Sighs_

Closing this one for now as well. Ran a different test program and it seems to have worked, so I have no idea what's going on.

**Comment by fnuecke** [comment]
For clarification, GPUs expect a hex triplet (`0xRRGGBB`, see [wikipedia](http://en.wikipedia.org/wiki/Web_colors#Hex_triplet) for example). So the above code is telling the GPU to set the color to 0x000001 through 0x00000F / 0x000010, which is pretty much just black.

In OC 1.3 T2 GPU/Screen combos use a 16 color _palette_, defaulting to the 16 MC colors. They can be set using `gpu.setBackground(idx, true)`, e.g. `gpu.setBackground(colors.red, true)`. T3 also has a 16 color palette (in addition to a fixed 240 color space) which defaults to greyscale values, however.
