### ISSUE TITLE
unable to put tablet case in assembler to build tablet.

### ISSUE THREAD

**Issue by masterblaster221** [MightyPirates/OpenComputers#3641]
mods
![5ddiyitytyftyifyft](https://github.com/MightyPirates/OpenComputers/assets/35042730/b2c7b62f-2f34-4566-8eac-d6a397708eb8)
![Capture](https://github.com/MightyPirates/OpenComputers/assets/35042730/0a593d31-dfee-4685-8777-5ecc82264fb4)
![cftcvyuvyitgi](https://github.com/MightyPirates/OpenComputers/assets/35042730/38aeef2c-bb52-490c-9f9d-3d068e156854)
![Ctfytfe](https://github.com/MightyPirates/OpenComputers/assets/35042730/8e2bca4d-d20d-4187-9f02-af197f4eebe9)
![Cyctiyftiue](https://github.com/MightyPirates/OpenComputers/assets/35042730/d104f258-e725-4718-bddf-d56b3217e6c8)
![tcchjfgj](https://github.com/MightyPirates/OpenComputers/assets/35042730/586f16ff-ec37-4d1d-8b28-7a17565856de)
![ytfdtufiytyitfy8ftiyfu](https://github.com/MightyPirates/OpenComputers/assets/35042730/507767f8-0850-4047-803a-cb8ceba3e981)

**Comment by masterblaster221** [comment]
the images are out of order but thats all my mods

**Comment by masterblaster221** [comment]
also robots/drones and microcontroller are broken too.

**Comment by Kylstreak** [comment]
What was the solution??
