### ISSUE TITLE
Feature request: add a GPU that acts like a real one 

### ISSUE THREAD

**Issue by AlphaTechNinja** [MightyPirates/OpenComputers#3648]
I think it would be a good addition to add GPUs that act like real ones and if you ask for details what I’m asking for is for a GPU that draws pixels instead of characters and my purpose for asking is because I want to build a GUI-based operating system also it would allow users to make more complex programs

**Comment by PublicVoidUpdate** [comment]
I'd say check out MineOS if no one on Dev gets back to you

**Comment by AlphaTechNinja** [comment]
I’ve used mineOS but I want it to have a higher resolution that’s also why I’m asking

**Comment by AlphaTechNinja** [comment]
At issue #3638 i found kind of what I was looking for under graphics mode 1 but this suggest sounds better but it should have 256 set of custom characters and all standard ascii characters

**Comment by asiekierka** [comment]
There are currently no plans, as the mod is in maintenance-only mode for the most part. However, OC2 does feature a pixel-based graphics card, so at least there's a solution worth evaluating - one which doesn't destroy server bandwidth, which is a crucial consideration.

**Comment by AlphaTechNinja** [comment]
but will there be plans in the future?

**Comment by asiekierka** [comment]
To a mod who has zero active developers left? Unlikely.

**Comment by AlphaTechNinja** [comment]
oh that's not good this is a great mod I wonder why they are not active anymore

**Comment by asiekierka** [comment]
For the most part? They, myself included, got industry jobs and therefore can't devote as much time to something as complex as maintaining a Minecraft mod anymore.
