### ISSUE TITLE
Rendering error in the manual in the openos part, going down a little (I don't know if it is from optifine or opencomputers)

### ISSUE THREAD

**Issue by ELJOKER900** [MightyPirates/OpenComputers#3667]
What happens is that when in the openos tutorial part of the manual when you lower down a little the top and bottom of the Minecraft game turns blue, as if it were a chunk downloading and when I close the manual everything goes back to normal, In the optifine I have the quick graphics set as additional data

**Comment by ELJOKER900** [comment]
Issue image : 
![Minecraft 1 12 2 29_09_2023 13_15_44](https://github.com/MightyPirates/OpenComputers/assets/121907632/9d4a15ac-4e1b-457e-9949-975126ac9003)

**Comment by brisingraerowing** [comment]
I'd suspect Optifine shenanigans here. Test without it.

**Comment by ff66theone** [comment]
happened to me
I think it might be ALSO your graphics card because I don't have any problem with my GTX 1650 super but I have that issue with my geforce 210

**Comment by ELJOKER900** [comment]
okay thanks
