### ISSUE TITLE
don't kill the mod 😭

### ISSUE THREAD

**Issue by igorkll** [MightyPirates/OpenComputers#3670]
I noticed that the development of the mod is fading, nothing new has been added for a long time.
I am really looking forward to new updates, but they are not coming out ...
I really want the mod to continue to develop, new content is added so that the mod is ported to new versions of minecraft as well as to fabric ...
I don't know if official updates of this mod can still come out?

**Comment by asiekierka** [comment]
There are zero developers left, and handing over the mod to new developers is blocked for a variety of technical reasons. Just have someone fork it.
