### ISSUE TITLE
AgriCraft

### ISSUE THREAD

**Issue by Scherbakov-eugene** [MightyPirates/OpenComputers#3676]
OpenComputers do not work with "computer controlled seed analyzer" from AgriCraft mod. Please, fix it.

**Comment by asiekierka** [comment]
OpenComputers with the latest version of AgriCraft for 1.12.2 correctly detects the seed analyzer as `agricraft_peripheral`.

**Comment by dzkm** [comment]
Good that it has been fixed, but what version of OpenComputers are we talking about? The latest version of AgriCraft for 1.12.2 is 2.12.0, are you talking about that one?
