### ISSUE TITLE
Some methods calls don't return data

### ISSUE THREAD

**Issue by Morebits05** [MightyPirates/OpenComputers#368]
Not All Methods on Peripherals work but do in Computercraft.
For example, using chesty = component.chest
chesty.getStackInSlot(1) should return a table of data relating to the chest.
However when I use this I get 'nil' See image.
![computers](https://cloud.githubusercontent.com/assets/2943557/3458456/a4220442-0201-11e4-8387-52549be5684e.jpg)

**Comment by fnuecke** [comment]
Yes, this is expected behavior, since those methods return 'userdata' (i.e. actual Java objects), which is not supported in OC 1.2. It is in 1.3 and I'm looking into making use of this for transparently wrapping CC's userdata interface.
