### ISSUE TITLE
Error when trying to boot the Mine os system

### ISSUE THREAD

**Issue by Xray1716** [MightyPirates/OpenComputers#3689]
I tried different options, jumped between versions 1.8.3-1.7.7 (everything happened on the Minecraft version 1.12.2) but I did not achieve the desired result. (I logged into Minecraft from my phone, namely from the pojav launcher)
I attach screenshots of errors and the text itself at the bo
![Screenshot_2024-02-03-11-26-21-977_net kdt pojavlaunch](https://github.com/MightyPirates/OpenComputers/assets/121585142/2a6047e4-5b38-4677-8d71-1fbd25e55b83)
![Screenshot_2024-02-03-11-36-23-808_net kdt pojavlaunch](https://github.com/MightyPirates/OpenComputers/assets/121585142/872075df-65d3-4132-b204-bfa7576a79fe)
![Screenshot_2024-02-03-12-19-35-845_com estrongs android pop](https://github.com/MightyPirates/OpenComputers/assets/121585142/00e882cf-6a30-437e-b923-b367f839e45a)
![Screenshot_2024-02-03-12-19-38-952_com estrongs android pop](https://github.com/MightyPirates/OpenComputers/assets/121585142/c2e290f5-006a-4e74-87cd-e972798d1b42)
![Screenshot_2024-02-03-12-22-42-559_net kdt pojavlaunch](https://github.com/MightyPirates/OpenComputers/assets/121585142/1b7a45c7-6c23-49fb-9e35-cacd738dac05)
![Screenshot_2024-02-03-12-23-28-973_net kdt pojavlaunch](https://github.com/MightyPirates/OpenComputers/assets/121585142/c4c0ab24-3481-4613-9cfd-90f0b8570a47)
![Screenshot_2024-02-03-13-25-21-597_net kdt pojavlaunch](https://github.com/MightyPirates/OpenComputers/assets/121585142/9e0926d2-4a52-4c7a-9ac3-1c48a063ef7e)
ttom.
![Screenshot_2024-02-03-13-25-25-050_net kdt pojavlaunch](https://github.com/MightyPirates/OpenComputers/assets/121585142/c73e043f-bea6-44ca-ac1c-0421b1661ac7)
-
Unrecoverable error:
Machine: 1359vm error: java.lang.Nullpointer.Exception
stack traceback: 
machine:1359: in function <machine:1334>
[Java]: in ?
Here is what I inserted after installing the lua Bios:
pastebin run 
1. HvLEX6cx
2. 0nM5b1jU
3. PDE3eVsL
4. wget -f https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/Installer/BIOS.lua /tmp/bios.lua && flash -q /tmp/bios.lua && rebootAs you can see, nothing helped. Maybe it's because I'm playing from my phone (then I'll try from my computer) There may be an omission on the part of the developers. I'm waiting for a correction if it's not my fault. Good day to all and good health to your loved ones

**Comment by asiekierka** [comment]
PojavLauncher is not a supported platform. Can you reproduce this issue on Windows, Linux or macOS?

**Comment by Xray1716** [comment]
> PojavLauncher не является поддерживаемой платформой. Можете ли вы воспроизвести эту проблему в Windows, Linux или macOS?

I'll try later, I don't have access to a computer right now, I'm not at home and I won't be coming soon...

**Comment by Xray1716** [comment]
Yes, it's all the fault of the launcher.
