### ISSUE TITLE
OPPM fails to install [HTTPS certificate not supported by old Java versions]

### ISSUE THREAD

**Issue by HauberDevs** [MightyPirates/OpenComputers#3696]
So yesterday while playing around with a modpack, I discovered OpenComputers. Today I installed the mod on a seperate modpack I made for testing OpenComputers, the OS install went well, however when I tried to install OPPM, it told me that it couldnt connect to the internet. After reconnecting my WiFi, using a VPN and using my mobile hotspot, the issue persisted. I have also checked and the computer is configured correctly. It has an internet card and any other components it may need.

I am on Minecraft 1.7.10 with OpenComputers version 1.8.3+089dd28 and Forge 10.13.4.1614 installed.

The log file can be viewed here: https://pastebin.com/DFq4FJWm

**Comment by FINK89i** [comment]
ye bro also i have this problem try if irc works to me irc worked but then afther a reboot it stoped whitch is weird before the worked fine

**Comment by HauberDevs** [comment]
@FINK89i Please write your message again, but this time in more understandable english thank you very much

**Comment by asiekierka** [comment]
I suspect it has something to do with the Java version being outdated:

> javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by HauberDevs** [comment]
@asiekierka I am running Java 1.8.0_261. I don't think that's the issue.

Here's what it shows me when I run java -version:
`java version "1.8.0_261"`
`Java(TM) SE Runtime Environment (build 1.8.0_261-b12)`
`Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)`

**Comment by asiekierka** [comment]
The Minecraft launcher provides its own version of Java:

`[14:21:49] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\Maximilian\curseforge\minecraft\Install\runtime\jre-legacy\windows-x64\jre-legacy`

**Comment by FINK89i** [comment]
> @FINK89i Please write your message again, but this time in more understandable english thank you very much

ok bro sorry im not that good at English to IRC chat worked only one time but after i did reboot the computer on minecraft it didn't work anymore end oppm never work but some moths ago all worked fine so i dont know maby a windows update or a java update caused a error in the code also i dont know if other people have this problem

**Comment by HauberDevs** [comment]
> The Minecraft launcher provides its own version of Java:
> 
> `[14:21:49] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\Maximilian\curseforge\minecraft\Install\runtime\jre-legacy\windows-x64\jre-legacy`

So what do I do?

**Comment by xJon** [comment]
Enabling [ArchaicFix](https://github.com/embeddedt/ArchaicFix)'s `enableLetsEncryptRoot` feature might have a positive effect?

**Comment by HauberDevs** [comment]
> Enabling [ArchaicFix](https://github.com/embeddedt/ArchaicFix)'s `enableLetsEncryptRoot` feature might have a positive effect?

ArchaicFix crashes the game if I try to run Minecraft with it

**Comment by zeng-github01** [comment]
> > The Minecraft launcher provides its own version of Java:
> > `[14:21:49] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\Maximilian\curseforge\minecraft\Install\runtime\jre-legacy\windows-x64\jre-legacy`
> 
> So what do I do?

Replace the Java 8 version with the latest version. For example, turn off "Use Java provided by Minecraft" in ATLauncher
After testing, there are no problems

**Comment by zeng-github01** [comment]
> > > The Minecraft launcher provides its own version of Java:
> > > `[14:21:49] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\Maximilian\curseforge\minecraft\Install\runtime\jre-legacy\windows-x64\jre-legacy`
> > 
> > 
> > So what do I do?
> 
> Replace the Java 8 version with the latest version. For example, turn off "Use Java provided by Minecraft" in ATLauncher

After testing, there are no problems

**Comment by HauberDevs** [comment]
> > > The Minecraft launcher provides its own version of Java:
> > > `[14:21:49] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\Maximilian\curseforge\minecraft\Install\runtime\jre-legacy\windows-x64\jre-legacy`
> > 
> > 
> > So what do I do?
> 
> Replace the Java 8 version with the latest version. For example, turn off "Use Java provided by Minecraft" in ATLauncher After testing, there are no problems

I'm using the CurseForge Launcher. Is there any way to do that on there?

**Comment by zeng-github01** [comment]
> > > > The Minecraft launcher provides its own version of Java:
> > > > `[14:21:49] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\Maximilian\curseforge\minecraft\Install\runtime\jre-legacy\windows-x64\jre-legacy`
> > > 
> > > 
> > > So what do I do?
> > 
> > 
> > Replace the Java 8 version with the latest version. For example, turn off "Use Java provided by Minecraft" in ATLauncher After testing, there are no problems
> 
> I'm using the CurseForge Launcher. Is there any way to do that on there?

Sorry, I haven't used this before. Why don't you search it on Google?

**Comment by xJon** [comment]
@HauberRBLX You'd need to manually change the Java version after CurseForge launches the vanilla launcher -> `Installation` Tab -> `Edit` the modded profile -> `MORE OPTIONS` -> edit `JAVA EXECUTABLE`.

**Comment by HauberDevs** [comment]
> @HauberRBLX You'd need to manually change the Java version after CurseForge launches the vanilla launcher -> `Installation` Tab -> `Edit` the modded profile -> `MORE OPTIONS` -> edit `JAVA EXECUTABLE`.

What would I change it to?

**Comment by xJon** [comment]
@HauberRBLX An updated Java 8 executable.

**Comment by FINK89i** [comment]
guys i have just solved so this is how i did it im using legacy launcher because i dont have money for minecraft sorry but in the java options there is a custom end so i have download java 8 x64 from the site end in the launcher i have set the custom to C:\Program Files\Java\jre-1.8\bin\javaw.exe end it works now just fine i can install oppm end use irc now

**Comment by patapon888** [comment]
if you are watching this in the future, it is C:\Program Files\Java\latest\jre-1.8\bin\javaw.exe

there is now latest in the url

**Comment by xJon** [comment]
On 1.12.2 this is also resolved by installing [CensoredASM](https://www.curseforge.com/minecraft/mc-mods/lolasm).

**Comment by HauberDevs** [comment]
> On 1.12.2 this is also resolved by installing [CensoredASM](https://www.curseforge.com/minecraft/mc-mods/lolasm).

Yea only issue is I'm not on 1.12.2 but on 1.7.10...

**Comment by xJon** [comment]
@HauberRBLX In this case just change the Java 8 version CurseForge uses to an updated one over the default one:
![image](https://github.com/user-attachments/assets/85b0c239-5066-4474-a1d9-31fde5b14b77)

**Comment by HauberDevs** [comment]
> @HauberRBLX In this case just change the Java 8 version CurseForge uses to an updated one over the default one: ![image](https://private-user-images.githubusercontent.com/8945347/380511430-85b0c239-5066-4474-a1d9-31fde5b14b77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNDUwMjIsIm5iZiI6MTczMDA0NDcyMiwicGF0aCI6Ii84OTQ1MzQ3LzM4MDUxMTQzMC04NWIwYzIzOS01MDY2LTQ0NzQtYTFkOS0zMWZkZTViMTRiNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjdUMTU1ODQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTllNDBiMjRhYzkxNjdhMzdmMjUxYzE5YWI0ZTYzZmJiMDg2ODQyMDI3NDAzZjRiZDQ0MDI4M2NlMDBlYWFhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-SWZeLOm7wUTikXe2lPkTuR7idTqjmjW44lJXAS4xQw)

So do I just replace it with the java in program files?

**Comment by HauberDevs** [comment]
So after replacing the Java 8 with the javaw from the one I installed, I get this error. Any idea?
![grafik](https://github.com/user-attachments/assets/70278f40-0c43-4724-a513-ff16ef9bb6d7)

**Comment by xJon** [comment]
@HauberRBLX Did you manually install Java 8?

**Comment by HauberDevs** [comment]
@xJon yes, i used the installer

**Comment by ff66theone** [comment]
I already encountered that error when running 32 bit Java on a 64 bit PC. Try using the 64 bit version, or use a very small -xmx argument (not recommended)

**Comment by HauberDevs** [comment]
> I already encountered that error when running 32 bit Java on a 64 bit PC. Try using the 64 bit version, or use a very small -xmx argument (not recommended)

That finally did the trick and I was able to install OPPM. 

With that I can finally close this issue, thanks to everyone who helped (and tried to)!
