### ISSUE TITLE
server crash when putting second GPU in active computer

### ISSUE THREAD

**Issue by karelmikie3** [MightyPirates/OpenComputers#37]
crash report:
http://pastebin.com/UDnbTb1W

**Comment by fnuecke** [comment]
Thanks. Does this happen at random or is it reproducible? If so how, because I can't reproduce it. If necessary I'll just a null check, but I'd prefer to understand why it actually gets to that point (because I can't see why it can).

**Comment by MFernflower** [comment]
I believe you can do this by running a gpu test program of any description (for example a color changing line drawer) on a superior card and then inserting another superior into the machine while that program is running.

**Comment by fnuecke** [comment]
Can you reproduce this reliably, or is it more of a random thing? Here's the test script I just ran, couldn't reproduce it with that:

``` lua
local w, h = component.gpu.getResolution()
for y = 1, h do
  for x = 1, w do
    local color = math.random(1, 0xFFFFFF)
    component.gpu.setBackground(color)
    component.gpu.set(x, y, " ")
  end
end
component.gpu.setBackground(0x000000)
```

**Comment by MFernflower** [comment]
Seems to be more random it seems

**Comment by fnuecke** [comment]
Then it's probably only happening when the computer is in one very specific state... well, it's a start.

**Comment by fnuecke** [comment]
I just noticed this and #59 seem to be running in MCPC+. Could you please verify this also happens in a "normal" Forge setup?

**Comment by fnuecke** [comment]
Just pushed [prerelease 3](https://github.com/MightyPirates/OpenComputers/releases/download/v1.1.0pre3/OpenComputers-1.1.0pre3.zip), which includes the above null check. I still cannot reproduce the issue (even when running MCPC+), so I can't be sure this helps. Please give it a try and let me know.
