### ISSUE TITLE
the internet card gives issues whit oppm end irc chat but not whit wget

### ISSUE THREAD

**Issue by FINK89i** [MightyPirates/OpenComputers#3700]
hello some days ago i decied to make a computer but afther i build a level 2 pc whit an apu end internet card 512k of ram end 1 mb of storage afther ive installed open os end network i was installing oppm but it say no internet but i have so i instaled irc for ask some help they could not help me but wget works idk if pastebin does but also afther a reboot irc also died idk before on another world all worked fine but also they stped working i tried to download a vm of opencomputers end on there they work fine so idk please help also i lost the logs but i can make new ones if you need

**Comment by brisingraerowing** [comment]
I suspect you're on an older Java version with outdated SSL certs. If you're using the CurseForge launcher you'll need to switch to something else like Prism, as CF doesn't allow changing the used Java version, AND its bundled Java is super old.
