### ISSUE TITLE
downloading files from github is not working for you

### ISSUE THREAD

**Issue by igorkll** [MightyPirates/OpenComputers#3711]
![image](https://github.com/MightyPirates/OpenComputers/assets/69525332/69be4d16-399a-46a7-8b75-238e243429d2)
as far as I understand, there is a problem with the certificate, but I do not know how to disable certificate verification in the mod config.
I do not want my traffic to be encrypted as I am categorically against encrypting data on the network.

**Comment by zeng-github01** [comment]
> ![image](https://github.com/MightyPirates/OpenComputers/assets/69525332/69be4d16-399a-46a7-8b75-238e243429d2)
> as far as I understand, there is a problem with the certificate, but I do not know how to disable certificate verification in the mod config.
> I do not want my traffic to be encrypted as I am categorically against encrypting data on the network.

See #3696

**Comment by ff66theone** [comment]
try http:// instead of https://

**Comment by asiekierka** [comment]
Duplicate of https://github.com/MightyPirates/OpenComputers/issues/3696
