### ISSUE TITLE
FIX GITHUB!!!!!!!!!!! 

### ISSUE THREAD

**Issue by igorkll** [MightyPirates/OpenComputers#3717]
![image](https://github.com/MightyPirates/OpenComputers/assets/69525332/45bccf53-cf38-4366-96d2-a47d1a36e696)

**Comment by zeng-github01** [comment]
> ![image](https://github.com/MightyPirates/OpenComputers/assets/69525332/45bccf53-cf38-4366-96d2-a47d1a36e696)
> 

This is a Java issue. Minecraft 1.12 uses an outdated Java by default. Please find a solution on your own

#3696

**Comment by igorkll** [comment]
oh... it turned out that it was enough for me to download this version of java and specify it in the launcher to fix it: https://www.mfnd.ru/downloads/java/java%208/jdk-8u321-windows-x64.exe

**Comment by CACKE** [comment]
Not fixed
![image](https://github.com/MightyPirates/OpenComputers/assets/89192120/5d3239ae-29e0-4174-ba6f-464fd857f17e)

**Comment by igorkll** [comment]
Are you sure you have chosen the new java? try using legacy launcher

**Comment by patapon888** [comment]
![image](https://github.com/MightyPirates/OpenComputers/assets/99602498/86381d65-feb8-4846-a74e-95bddc55ea6b)

no github = no mineos = very sad
same with the other java and with legacy launcher
pls fix

**Comment by xJon** [comment]
For 1.12.2, this is fixed by https://github.com/LoliKingdom/LoliASM/commit/d44e45fd386b84c76e29caa78ea6aac7413abbd2 + https://github.com/LoliKingdom/LoliASM/commit/8f76f3016b1945e6dbd5747e0c74bf01652139e5

**Comment by misha99fr** [comment]
and what next

**Comment by xJon** [comment]
@misha99fr Just install the mod and it will patch this.

**Comment by asiekierka** [comment]
Duplicate of https://github.com/MightyPirates/OpenComputers/issues/3696

**Comment by misha99fr** [comment]
> @misha99fr Just install the mod and it will patch this.

What mod

**Comment by xJon** [comment]
@misha99fr [CensoredASM](https://www.curseforge.com/minecraft/mc-mods/lolasm)
