### ISSUE TITLE
(Not An Issue) Permission to rewrite for Minetest?

### ISSUE THREAD

**Issue by PublicVoidUpdate** [MightyPirates/OpenComputers#3721]
May i remake this mod for Minetest? And may i use the assets or do i need to make my own? Thank you for making this mod to begin with!
-Void

**Comment by asiekierka** [comment]
Please follow the terms of the licenses as provided in the repository.

No single person owns OpenComputers, so no single person can grant you explicit permission - you'd need to ask a majority of the 150 contributors. The licenses exist as a way to give everyone clear and understandable terms.
