### ISSUE TITLE
Open Computers 1.8.6 crashing with BuildCraft Lib 7.99.24.8

### ISSUE THREAD

**Issue by Shibidibop** [MightyPirates/OpenComputers#3743]
[crash-2024-10-26_17.17.07-client.txt](https://github.com/user-attachments/files/17533881/crash-2024-10-26_17.17.07-client.txt)

Before Open Computer doesn't crash at the 1.8.6 version and i dont know how may crashing with Buildcraft lib now (Idont change versions all of them)
Open Computer: OpenComputers-MC1.12.2-1.8.6+cd8851e
BuildCraft Lib: buildcraft-core-7.99.24.8
It might be a bug but i have not sure...

**Comment by asiekierka** [comment]
The true cause appears to be a bug in the mod `BetterFontsCore (TTFR-1.12.1-1.9.1.jar)`
