### ISSUE TITLE
term.read() returning wrongly

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#375]
I made this simple program to get a password protected door, just for testing:

``` lua
local component = require("component")
local term = require("term")
local sides = require("sides")
local rs = component.redstone

local password = "pastryfork\n"

while true do
  term.clear()
  term.write("Password: ")
  local p = term.read()
  if p == password then
    print("Password correct!")
    rs.setOutput(sides.top,2)
    os.sleep(3)
    rs.setOutput(sides.top,0)
  else
    io.stderr:write("Wrong Password! Try again.\n")
  end
end
```

As you can see, the password is "pastryfork\n", because term.read() returns the entered string plus the new line added when hitting the Enter key. Since I assume that this is a bug, I'm posting this here.

**Comment by fnuecke** [comment]
Not a bug. Use `io.read()` if you want it without the newline.

**Comment by Vexatos** [comment]
I should probably write this to the wiki then.

**Comment by fnuecke** [comment]
Good idea. If there'll ever be an FAQ, this should probably go into it, too, since there was at least one ticket on this before.
