### ISSUE TITLE
[1.7.10] Scala Issue on Settings Load

### ISSUE THREAD

**Issue by Dyonovan** [MightyPirates/OpenComputers#378]
Version: 1.7.10-1.3.0.9-rc.1
Crashlog: http://pastebin.com/GNQEP8cd

Issue seems to be with the config load. I know scala just got an update for forge.

**Comment by Techokami** [comment]
Update your Forge to 1170.

**Comment by fnuecke** [comment]
Wait for build 10 to finish and get that, that _should_ fix it.

**Comment by fnuecke** [comment]
Was reported to happen in latest build, too... strange.

**Comment by Dyonovan** [comment]
Actually getting a different error now using the newest build. And I updated forge.

http://pastebin.com/RX7LqUDS

**Comment by fnuecke** [comment]
All right, build 11 should fix it for good! Sorry about that. You _may_ have to delete your config. Try without deleting, first, though, and tell me if something breaks.

**Comment by Dyonovan** [comment]
Looks good. I also used a config from my 1.7.2 version and no issues.

Thanks for the quick fixes.

**Comment by fnuecke** [comment]
Thanks for confirming :-)
