### ISSUE TITLE
Possibility to read item/block/entity id from around the robot or from slot

### ISSUE THREAD

**Issue by fipil** [MightyPirates/OpenComputers#385]
Hi, it would be nice to have a possibility to read MC Id of block/item/entity in the front of robot, or above/below robot. And a possibility to read the same from selected/specified slot.
So we can in program distinquish items around robot even if the items aren't in robot's inventory.
For example there is no way how to distinquish if the entity in front of robot is a sheep, or cow or player.

**Comment by fnuecke** [comment]
For identifying entities, check out Computronics' radar. For items in the inventory, I've considered adding something like this to the inventory controller upgrade. It might be disabled in the config by default, though, same as it is in OpenComponents.

**Comment by Techokami** [comment]
Consider installing the mod Computronics. It adds new peripherals that allow you to do a lot of the actions described here.

Sent from my Windows Phone

**Comment by fipil** [comment]
@fnuecke thanks, great to read that you're going to implement!
@Techokami thanks for advice, I tried it. Unfortunatelly the Computronics is crashing on our MCPC1.6.4 server. Hope that it'll be fixed soon.
