### ISSUE TITLE
Entity scanner with some upgradeable range

### ISSUE THREAD

**Issue by fipil** [MightyPirates/OpenComputers#386]
Hi, it would be nice to have some component, the same kind such is Internet card for example, which can be placed to the robot and will allow robot to scan area around robot up to some distance, for example 5 meters in tier 1, and more in higher tiers. The operation will spend some EU depending on distance, butthe operation should be quick enough, so we can implement the following examples:
1. A guard robot which is following it's owner - a specified player, and if there is some hostile mob, the robot will attack to him
2. A hunter robot, which will seek for a specified mob, for example cow and will hunt them.
3. A breeding robot which will search for a specified animals and breed them.
4. A herdsman robot, which will search for a specified animals, then it will tie it to a rope and will bring the animal to the pen.

**Comment by fnuecke** [comment]
Get [Computronics](http://mc.shinonome.ch/doku.php?id=wiki:computronics:radar) ;-)

**Comment by Techokami** [comment]
Consider installing the addon mod Computronics. Radar blocks and Radar Upgrades allow you to do all of this.

Sent from my Windows Phone
