### ISSUE TITLE
OC 1.3 hardmode recipes missing

### ISSUE THREAD

**Issue by Leftorius** [MightyPirates/OpenComputers#387]
there are a lot of missing hardmore & gregtech recipes for Opencomputers 1.3 (Robot Assembler + Upgrades) and almost every gregtech recipe...

**Comment by fnuecke** [comment]
Seems like recursive includes aren't working, will fix. For now, just keep the default recipes enabled in addition to the hardmode ones in your user.recipes. I.e. have it read like so:

```
include file("default.recipes")
include file("hardmode.recipes")
```
