### ISSUE TITLE
Robots actions on smp

### ISSUE THREAD

**Issue by Huls** [MightyPirates/OpenComputers#389]
More than half of robots actions not working properly or doesn't work at all on smp. 
Swing(), place() nor robot.level().

Fault of engine or mine permissions or new version?

@edit
Robots nor visible at all in ssp or smp.
v. OpenComputers-MC1.7.2-1.3.0.249-universal.jar

**Comment by fnuecke** [comment]
Make sure you're not in a protected area (spawn protection e.g.). Make sure they have a tool good enough to break the block you're telling them to break. Try using `=robot.swing()` to see if it returns an error message.

`robot.level()` has been removed, this functionality is now provided via the Experience Upgrade and can be queried using `component.experience.level()` if it is present.

Which parts did you use to build the robot(s)? I.e. exactly which items (ideally: in which slots) did you put into the assembler? A screenshot of the assembler GUI with the items in it would do.

Edit: also, which version of Forge are you using?

**Comment by Huls** [comment]
![image](https://cloud.githubusercontent.com/assets/3637068/3549990/9c49b904-08d2-11e4-9ab1-17f20be6bfbf.png)
![image](https://cloud.githubusercontent.com/assets/3637068/3550008/dbf81690-08d2-11e4-9727-9d0a085da0f1.png)

We (me and Rosie) are standing in neutral world ground, no spawn, protected area etc.

Thank you for response with robot.level()

I didn't build robot, just took it out from NEI items list.

My Forge version: 10.12.21147 (newest for my engine for now, my enginge: cauldron-1.7.2-1.1147.04.90-server.jar)

Btw. is it possible that is fault of permissions, same as it was/is with f.e. Buildcraft where you need to declare "machines with full permissions" ?

**Comment by fnuecke** [comment]
You're not running the OC version you stated. 
- In 1.3 the robots are not in the items list any more.
- In 1.3 the minimum RAM is higher and robots wouldn't even start with 96k.
- In 1.3 the OpenOS version 1.2.

I'm guessing you're using an old OC 1.2 version from before some issues caused by the presence of Battlegear 2 were fixed.
