### ISSUE TITLE
OpenComputer 1.3.0.507 crash, cannot start MCPC+ 1.6.4 server

### ISSUE THREAD

**Issue by fipil** [MightyPirates/OpenComputers#390]
We want to upgrade OC from the working version 1.2.12.376 (MC1.6.4) to the new OpenComputers-MC1.6.4-1.3.0.507-universal. 
MCPC+ 1.6.4 server crashes during startup.
Here is the crash report: http://pastebin.com/e84WNbh2

**Comment by fnuecke** [comment]
I'm afraid I can't reproduce it, so I fail to see the original cause for this, but I'll catch the error for now and just log it. [Build 511](http://ci.cil.li/job/OpenComputers-1.3-MC1.6.4/) should not crash on this anymore. Alternatively you could load up the world using OC1.2 again and stop all computers first, that should also prevent the crash from happening when upgrading.

Sorry for the inconvenience!
