### ISSUE TITLE
Request: Startup scripts

### ISSUE THREAD

**Issue by pocketpc** [MightyPirates/OpenComputers#40]
I would like it if we could create a file that would run when the computer boots, or have autorun.lua run a startup, not just when the drive is mounted. At my laptop's max resolution, I can barely read the text on a Superior Monitor, and I would really like to be able to automate a resolution change.

**Comment by fnuecke** [comment]
The autorun scripts on drives should actually run on startup. A quick test confirmed that they do. Maybe it's some other issue you're running into?

**Comment by ghost** [comment]
Can I write something in terminal after the start? I think that issue are loading autorun.lua before loading GPU.

**Comment by fnuecke** [comment]
You can start a timer and print in its callback to make sure the terminal is available, e.g.

``` lua
event.timer(1, function()
  term.write("Printed from startup script.")
end)
```

I just added a check to `term.read`, that will make the read "soft fail" if the term was meddled with from the outside, making it a little less quirky to write to the term from event callbacks. With that change, any current input in the shell will just be discarded, and the shell will behave as if the user simply pressed enter on a blank line (i.e. do nothing and start a new line read). Until the next release doing the above can still screw up the read, and you may have to reposition the cursor manually, for example.

Waiting for @pocketpc to confirm that was indeed the issue he was having.

**Comment by fnuecke** [comment]
Closing this due to lack of feedback, assuming the timing indeed _was_ the issue.
