### ISSUE TITLE
[20:49:14 WARN]: Unexpected error in Lua callback.

### ISSUE THREAD

**Issue by Huls** [MightyPirates/OpenComputers#401]
http://pastebin.com/uAmPpmri

OC v: OpenComputers-MC1.7.10-1.3.0.25-universal.jar 
IC2 v: industrialcraft-2-2.2.508-experimental.jar

only these 2 mods are installed on my local server right now.

![image](https://cloud.githubusercontent.com/assets/3637068/3565544/f53b535e-0abe-11e4-86f6-6e1a8f78ab1e.png)

**Comment by fnuecke** [comment]
Thanks, fixed in build 27.
