### ISSUE TITLE
Anisotropic Filtering

### ISSUE THREAD

**Issue by istasi** [MightyPirates/OpenComputers#409]
http://istasi.dk/screen.png

Set it, right click on screen, bam this...
Nvidia card if that makes a difference.

**Comment by istasi** [comment]
OpenComputers-MC1.7.10-1.3.1.29-universal btw

**Comment by Techokami** [comment]
What other mods are installed?

**Comment by istasi** [comment]
with only optifine and opencomputers i get it like this, though its not transparent.

http://www.istasi.dk/screen2.png

anyway, it seems its not transparent always, with all mods in, i still get issues as seen in screen2, though the texture may differ in to various green ones currently.

**Comment by LordFokas** [comment]
what happens WITHOUT optifine?

**Comment by istasi** [comment]
http://istasi.dk/screen3.png that is ONLY opencomputers

**Comment by fnuecke** [comment]
Does this also happen without the texture pack?

**Comment by istasi** [comment]
http://istasi.dk/screen4.png i'd say so

**Comment by fnuecke** [comment]
See if the next Jenkins build (37) solves this for you, please. I could only reproduce this a few times (i.e. it didn't happen all the time) so I'm not sure this actually fixes it.

**Comment by istasi** [comment]
oh god no

http://istasi.dk/screen5.png
http://istasi.dk/screen6.png

**Comment by istasi** [comment]
or well, it did fix the texture changing thingy

**Comment by istasi** [comment]
the screen in screen5 didn't multiblock though, no texture issues though

**Comment by fnuecke** [comment]
So the original issue is fixed, yes? It just for some reason didn't connect into multi-block screen? Is this reproducible for you?

**Comment by istasi** [comment]
no, it is not ... only happened first time i opened the game with the new build

but yes, original issue does seem gone.

**Comment by fnuecke** [comment]
OK. If you get the non-connecting thing again, open a new issue. I'll just pretend that never happened until then :-P

**Comment by istasi** [comment]
why does the font look so uhh, well pixeled?

**Comment by fnuecke** [comment]
See #41.
