### ISSUE TITLE
You should be able to drink Grog (Acid).

### ISSUE THREAD

**Issue by Techokami** [MightyPirates/OpenComputers#410]
Make it cause a minute of the Nausea potion effect. That's a good substitute for a drunken hangover. (And refill 1 unit of food meter/saturation as well)
Maybe compound it with another random negative effect. Like, randomly get Blindness, or Hunger, or (in rare cases) Poison.

I want to build a pub and serve booze. There is a booze item in OpenComputers. Let's put it to use!

**Comment by Kilobyte22** [comment]
I approve. I mean, you can drink factorization acid as well. If Sangar doesnt mind I can squeeze this between my other projects and PR later

**Comment by fnuecke** [comment]
@Kilobyte22 if you want, please go ahead! The idea isn't that new, I just never got around to it because I kept prioritizing other things ;-)

**Comment by Kilobyte22** [comment]
Mind assigning the issue to me so I dont lose track of it

**Comment by Kilobyte22** [comment]
Small status update: the effects are implemented, as is the applying to player. Right now I am working on getting drinking animation/sound to work

**Comment by Techokami** [comment]
*pokes @Kilobyte22 *
How's it comming along? :O

**Comment by LordFokas** [comment]
\o/ Let's get wasted!

**Comment by Kilobyte22** [comment]
I had barely time in past, but i have definitely not forgotten about it
