### ISSUE TITLE
Access Point send infinite messages

### ISSUE THREAD

**Issue by feldim2425** [MightyPirates/OpenComputers#422]
If I send a message from one access point to an other the computer recives the message multible times.

**Comment by fnuecke** [comment]
You have a loop somewhere in your network, or a robot connected to it (robots duplicating network messages will be fixed in 1.3.2).

**Comment by feldim2425** [comment]
I have no loop in the network

![2014-07-20_21 25 50](https://cloud.githubusercontent.com/assets/6705744/3638341/123db12e-1044-11e4-9b51-378ca4cc0900.png)
![2014-07-20_21 25 56](https://cloud.githubusercontent.com/assets/6705744/3638342/124bad88-1044-11e4-83c2-d6090d5633a8.png)
![2014-07-20_21 26 01](https://cloud.githubusercontent.com/assets/6705744/3638343/1254e60a-1044-11e4-9648-9fb88cde8b80.png)

**Comment by fnuecke** [comment]
Yes you do. The keyboards also connect to the switches.
