### ISSUE TITLE
[Tablets] NPE!

### ISSUE THREAD

**Issue by Techokami** [MightyPirates/OpenComputers#427]
http://pastebin.com/eBjSMV8C
Also, it might be related to this, but the HDD of tablets doesn't get written to the world save.

**Comment by Wuerfel21** [comment]
Whut? Tablets? Why did i miss this?

**Comment by Techokami** [comment]
@Wuerfel21 You need to use the dev builds, and you need to get the item from the creative mode inventory (it's currently uncraftable)
