### ISSUE TITLE
Robots spawning randomly

### ISSUE THREAD

**Issue by returnzork** [MightyPirates/OpenComputers#431]
I have 4 robots on my server, 2 of which are not being used, 1 of which is carrying wood from my tree farm, and 1 that harvests the trees.

Every so often, new robots spawn next to one of the 2 working ones. These new ones have names, but they change when you relog (I am connected to a local server)
When breaking, they break like normal, and I get them in my inventory.  Where the name is supposed to be displayed (item tooltip), its blank. The id of these robots is 0512/0. 
If you try to turn these robots on, it says there are too many components connected to the computer.

Server is running forge 7.2.217.1147, OpenComputers is version 1.7.2-1.3.1.260

**Comment by fnuecke** [comment]
Haven't heard of this before, strange.
- Do these 'clones' happen along their path of movement? (i.e. could it be the block they were previously in wasn't cleared properly?)
- Could you check to see if this happens at chunk borders?
- If at a chunk border, were any players nearby / chunkloaders active, or could this have happened while chunks were loaded/unloaded?

Thanks.

**Comment by returnzork** [comment]
1. It is in their movement path

2+3. I have a railcraft admin anchor directly under the tree farm robot, but it still happens there as well, will check and see though

Since the tree farm goes into 2 chunks, i placed a world anchor in both chunks. Will let you know if it happens again

**Comment by fnuecke** [comment]
OK, followup question: can you tell if the 'new' robots are in front of or behind the original ones? I.e. was the clone created by the old position not being cleaned up properly, or by it being created in the target block?

**Comment by returnzork** [comment]
It appears above, below, and usually infront of. The robot has a task to go forward 80 blocks, and about 60 blocks through, one is spawned below, so it isn't always constant (unless one gets spawned infront of the robot, blocking the program until the loop ends and its told to go down, where it tries and spawns another fake one; in this case it would be the target block that is spawning one)

**Comment by fnuecke** [comment]
Weird. I'm wondering, you mentioned RC, do you have the residual heat blocks disabled or not? If not, i.e. if they're around, that's something I could look into.

**Comment by returnzork** [comment]
The only thing thats around are some dead bush's (checked with creative) and some cactus. Everything with railcraft is about 15 chunks away.

After adding more chunk loaders, the problem appears gone, but it was like that yesterday (without chunk loaders) for a long time, and it happened. I will post again later in the day, if they reappear or not.

**Comment by returnzork** [comment]
Still happens even with the chunk loaders,

Im looking through the railcraft config files, and i'm not finding anything that related to the residual heat blocks in any of the railcraft config files...

**Comment by returnzork** [comment]
Okay, I gave myself a pair of the trackmans goggles, and when i put it on tracking mode, there is a purple aura that is around the spot where 1 of the robots is

I did find the hidden block in the config, I put it to false, will report the results again.

**Comment by fnuecke** [comment]
Hmm, I haven't been able to reproduce this after having multiple robots running back and forth for a couple of hours, with and without RC... I did a small change which may or may not fix the issue in the dev builds, though. As soon as you have the chance to update to 1.7.10, please see if the issue is still present there. Thanks.

**Comment by returnzork** [comment]
I haven't had a chance to test in on 1.7.10, but after disabling the hidden block in railcraft's config, the problem appears to have gone away. I am going to be updating the server and everything to 1.7.10 within the next couple of days, so I will also be able to check that soon.

**Comment by fnuecke** [comment]
All right, thanks for letting me know!
