### ISSUE TITLE
Missing folder?

### ISSUE THREAD

**Issue by istasi** [MightyPirates/OpenComputers#434]
http://istasi.dk/save.png

needless to say, it havn't created the folder in the saves/world/opencomputer/address

not sure how i made this happen

**Comment by istasi** [comment]
component.invoke ( dat address, 'remove', slash or '' )  on a init file

Removes the address folder

**Comment by fnuecke** [comment]
Unbuffered mode? Will have a look tomorrow.

**Comment by istasi** [comment]
no buffering, havn't tested whenever it does the same with buffered though
