### ISSUE TITLE
Extra Utilities Interaction

### ISSUE THREAD

**Issue by ph1x3r** [MightyPirates/OpenComputers#435]
It seems that the 'Adapter' block does not understand anything about the Extra Utilities 'Trading Post', it won't show up as a component.

When CC was installed, the trading post was the way to automate villager trading. I have removed BC/CC from my pack and now cannot re-implement my villager trading program with OpenComputers.

Is there any way to add this type of functionality into OpenComputers? I really don't want to add BC/CC back into my pack.

Thank you,

**Comment by Techokami** [comment]
Have you installed OpenComponents?

**Comment by ph1x3r** [comment]
Yes. The versions I have are:

OpenComponents-MC1.6.4-0.2.0.47-universal.jar
OpenComputers-MC1.6.4-1.3.1.516-universal.jar

Yes, still on 1.6.4 - some of my mods are still not on 1.7.x yet :(

**Comment by fnuecke** [comment]
Please open a ticket on the OpenComponents repo for this, since that's where that'd have to be implemented. Me or someone else will hopefully have the time to look into this, can't make any promises though.

**Comment by Kubuxu** [comment]
The CC's interface in trading post is probably marked as optional. But it is only blind shot.
