### ISSUE TITLE
Chunkloader component doesn't exist?

### ISSUE THREAD

**Issue by fipil** [MightyPirates/OpenComputers#437]
Hi, we use Open Computers 1.3.1.516 with MCPC 1.6.4.
I'd like to use the Chunkloader. I put into the robot's upgrade slot tier 3 the Chunkloader component. Then I'd like to activate it from my code:

local chunkloader = require("chunkloader")
chunkloader.setActive(true)

But it returns error that the chunkloader doesn't exist. Please what's wrong?
Thanks!
Filip

**Comment by fnuecke** [comment]
It's not a library ;-) Use `local chunkloader = require("component").chunkloader`.

**Comment by fipil** [comment]
Ahh, perfect. Thanks!
