### ISSUE TITLE
event.ignore() crashes

### ISSUE THREAD

**Issue by applejag** [MightyPirates/OpenComputers#44]
Trying out some events, and noticed that event.ignore crashed me with

```
lib/events.lua:79: attempt to index global 'list' (a nil value)
```

And when I looked at the event.lua file at line 79 there is

```
list.listeners[name] = nil
```

and previously in the function it only relates to listeners[name], not list.listeners[name].
So the only change necessary I think is to remove "list.".

**Comment by fnuecke** [comment]
Thanks for reporting this! Yep, sounds about right... seems to have slipped in after a bit of cleanup and me forgetting to test that function again. Oops.
