### ISSUE TITLE
Dupe Bug with Robot

### ISSUE THREAD

**Issue by ph1x3r** [MightyPirates/OpenComputers#441]
When you have a robot with a generator upgrade installed, breaking the robot to pick it up gives you the robot plus the fuel from the generator.

However, it seems the code does not zero out the fuel in the generator, since placing it down and breaking it again gives you another quantity of fuel.

The amount of fuel returned is equal to the quantity reported from the refuel.lua program.

Mod Version: OpenComputers-MC1.6.4-1.3.2.525-universal.jar

**Comment by fnuecke** [comment]
Thanks! This was actually a much more general issue, fixed now :-)
