### ISSUE TITLE
some chars dont render propertly

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#444]
For example the double frame bottom right coner displays a smily instead.
It worked before

**Comment by fnuecke** [comment]
I can't do anything with this report. What OC and MC version? Example code? Proper description of expected vs. observed behavior, ideally with screenshots, please.

**Comment by Wuerfel21** [comment]
Mc 1.7.10 and latest oc dev build
The probkem is that when i want to display a double frame bootom right corner i get a smiley. In older versions it worked perfectly
