### ISSUE TITLE
Slot One on Robot Sometimes Unavailable

### ISSUE THREAD

**Issue by ph1x3r** [MightyPirates/OpenComputers#448]
I am still working on how to reproduce this particular issue, but I have seen it multiple times since I have been playing with the robots.

The best example is a robot with the dig loot disk. You set it running and for some reason, it ignores slot one when sucking up the dropped blocks. The end result is the robot never knows it has a full inventory and blocks just drop onto the ground as it continues digging.

I have also seen the same effect when using the inventory controller to pull items from an adjacent chest. suckFromSlot(sides.front,1,1) pulls an item into the robot inventory, but even though the green line is running round slot one, the item ends up in slot two. Even doing a robot.select(1) and then trying the suck again does not work.

You can still put an item into the slot manually, but the suck functions have a problem.

**Comment by fnuecke** [comment]
Hmm, strange, I'll have a look over the related methods when I have the time, hopefully later today. A robot build with which to reproduce that would help a lot, though. Thanks for testing the robots so thoroughly :-)

**Comment by ph1x3r** [comment]
@fnuecke - I have seen the same behaviour on all of the robots I have built so far. I am just building a fairly minimal Tier 1 robot and will see what happens.

**Comment by ph1x3r** [comment]
After some testing, this issue seems to be related to the generator upgrade.

The sequence was:
1) place robot
2) install generator
3) install pick
4) put fuel in slot 1
5) run command "refuel 1"
6) run "dig 16"

The blocks that were then mined ended up in slot 2 even though slot 1 was now empty. Placing a block into slot 1 caused the robot to start sucking items into that first slot.

I would suspect that the refuel function is not correctly marking the first slot as empty when it pulls all of the fuel out. But this only affects the robot.suck() function, since the robot.count() does recognize the slot is empty.

**Comment by fnuecke** [comment]
Confirmed, thanks a lot for tracking this one down!
