### ISSUE TITLE
suckFromSlot() Ignores NBT data

### ISSUE THREAD

**Issue by ph1x3r** [MightyPirates/OpenComputers#449]
I have an Extra Utilities filing cabinet in front of my robot. The cabinet contains Mystcraft pages.

When I use the suckFromSlot(sides.front,1) function call, a stack of pages is pulled from the cabinet, however when it is placed into the robot inventory, it is added to an existing stack of pages even if they are a 'different' page.

The pages all have the same item ID.

I have re-produced this with a regular minecraft chest by placing 4 different pages into the first 4 slots and then sucking them in. I end up with a stack of 4 in the robot. This problem does not happen with 'damage' values (I tried with colored wool).

**Comment by fnuecke** [comment]
Confirmed, thanks.
