### ISSUE TITLE
Holographic projector for Robots would be cool

### ISSUE THREAD

**Issue by danielsilverstone-ct** [MightyPirates/OpenComputers#450]
Hi,

I appreciate this is an "out there" idea and as such it's a very low priority feature request (unless you also think it'd be awesomely cool like I do) but I think it'd be nice if there were a way to upgrade a robot with a holoprojector which would allow it to project similarly to the holoprojector block.  Mostly I'm imagining a robot pretending to be a holo-cow, but in general it'd be in keeping with the fact that robots look a lot like Red Dwarf light bees to me :-)

**Comment by fnuecke** [comment]
It's definitely an interesting idea. Would need some refactoring, and reworking things in general, but should be doable. I'll keep this as a reminder, to have a closer look into for when there are no more pressing issues at hand.

**Comment by ingie** [comment]
"help me obi-wan kenobi, you're my only hope..."
