### ISSUE TITLE
[Feature Request] Allow Larger Robot Screens

### ISSUE THREAD

**Issue by ph1x3r** [MightyPirates/OpenComputers#451]
It is really annoying to try and write programs for robots on a Tier 1 screen.

Please can we have an ability to get a bigger screen. A high tier graphics card can be installed, but only a tier one screen is accepted by the builder.

Perhaps allow a robot to 'plug in' to an external screen and keyboard if it is at a recharging station or some such mechanism. Then we can write/modify/debug  code and send it on its way again.

**Comment by fnuecke** [comment]
Keeping robots limited in some fashion is something I'm pretty adamant about, so higher resolutions isn't something I'm willing to support, I'm afraid. Do your coding on a computer with a proper screen, or maybe write an SSH-like program to remote control your robots? Do note that at least in the recent versions, wired network messages can also be sent to robots if they're "connected" to a network, so you wouldn't have to use wireless networking for this, making it somewhat more realistic to plan with.

The idea of robots gaining access to external components via the charger has been brought up before. It's interesting, but brings a similar problem, gameplay-wise: it makes computers almost redundant. Another issue would be that robots could then also be "uncharged" and basically serve as capacitors.
