### ISSUE TITLE
Native Library for CentOS

### ISSUE THREAD

**Issue by Randolph-J** [MightyPirates/OpenComputers#452]
I am requesting the Native Library be compiled for 'CentOS' it is a linux based CLI OS. The presistance module does not currently work with current libraries.

Thanks. :)

**Comment by fnuecke** [comment]
I'm a little surprised about that, in fact I seem to remember people that _did_ run it on CentOS. Are you sure the problem isn't the _architecture_? Could you post the output of `uname -a`?

**Comment by Randolph-J** [comment]
Linux 7.03C1.securedservers.com 2.6.32-431.20.3.el6.x86_64 #1 SMP Thu Jun 19 21:14:45 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I asked about the presistance module in the irc and 'v' told me that the CentOS library was not added.

**Comment by Techokami** [comment]
...2.6.32? Wow that's an old Linux. I remember when that was new _YEARS_ ago! But Linux has moved on to a new major version long ago... so I suggest upgrading your OS, if possible?

**Comment by Randolph-J** [comment]
It is a dedicated server hosting company. So I don't know. I don't know about changing OSs just for the persistance mod.. use to autorebooting scripts so can just stick with them.

**Comment by ph1x3r** [comment]
I suggest you ask your hosting company about upgrading your VPS. There are significant security reasons to keep any OS up to date.

A provider that keeps those old versions running is not doing their customers a good service.

Can you imagine trying to find a Windows Vista or XP hosting provider on the net?

**Comment by Techokami** [comment]
> dedicated server

That means the box you're using is just for you. So if they don't provide OS migration services, well... guess what you're doing over the weekend! (Hint: backups and OS installing)

**Comment by fnuecke** [comment]
Still odd, since the kernel of the Linux I built the libs on is even older (specifically to avoid it only working on newer installations). I might have to set up a CentOS VM when I have the time to have a closer look. No ETA on that, though.

**Comment by Randolph-J** [comment]
We have installed Eris to the common lib path. The persistnace still does not load in game, is there anything we can do on our side besides a full OS upgrade?

**Comment by fnuecke** [comment]
It only tries to load the ones inside the JAR, so adding it to the lib path won't change a thing.

I forgot to ask this in the first reply, but does the user the MC server runs as have access to the tmp directory? Because that's where it extracts them to be able to load them.

**Comment by Randolph-J** [comment]
In the root dir? Yes.

**Comment by Randolph-J** [comment]
What dir does it extract them to? tmp/?

**Comment by fnuecke** [comment]
On Linuxes, per default to `/tmp`, yes. More specifically, to whatever `java.io.tmpdir` is set to.

**Comment by RobertCochran** [comment]
I feel like it would be helpful to inform that since the user is using CentOS 6, the 2.x Linux kernel
is purposefully old, for stability reasons. (CentOS is meant to be used in server-class applications
and other places where stability is important)
Of course, the CentOS kernels have all sorts of backpatches and the like, and are heavily tested.

Source : My fully updated personal CentOS 6 server : 

```
[Sora@SirWendell ~]$ uname -a
Linux SirWendell 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

EDIT : Persistence seems to be fine on said server using OpenComputers-MC1.6.4-1.3.2.525-universal.jar, and my user does have write access to /tmp

**Comment by fnuecke** [comment]
Thanks for the input! So... it does work on CentOS? I'll assume this was a rights issue then.

**Comment by Randolph-J** [comment]
So what can I do to resolve this on my end? Have you tried the the 1.7.10 version?

**Comment by fnuecke** [comment]
Double-check the user running MC has write access to `/tmp`, check the log if there's anything in it telling you what's causing the native libs failing to load.

**Comment by Randolph-J** [comment]
I'm looking through the log, Is there anything I should be looking for?

The only log i have about open computers is

[04:00:43] [Server thread/INFO]: Initializing OpenComputers API.
[04:00:43] [Server thread/WARN]: Unsupported platform, you won't be able to host games with persistent computers.

**Comment by fnuecke** [comment]
Uhm, there should be a couple of 'fine' log entries inbetween those, are you looking in the actual log file or in the console? (because the console won't print fine messages)
Also, which version of OC are you using?

**Comment by RobertCochran** [comment]
Run this on the command-line, it will pull out any lines of the log with 'fine' in them
`grep -i fine /path/to/server/ForgeModLoader-server-0.log`
I'm not entirely sure, but I'm guessing this is the log we want,
right @fnuecke ?

PS : Sorry for any crap formatting, on phone

**Comment by fnuecke** [comment]
For MC1.6, that is the correct file, but since he mentioned 1.7.10 I'm assuming he's on that, and then the log file is found at `serverdir/logs/fml-server-latest.log`. Having had a look at that, though, it seems anything below info isn't logged in there anymore... sooo yeah, I don't know :-/
@Randolph-J You could try setting up a minimal 1.6 server just to get a more informative log file...

**Comment by Randolph-J** [comment]
Sure. I'll set up a clean 1.6.4 and a clean 1.7 and post the logs when I get off work later.

**Comment by Randolph-J** [comment]
Here is the FINE between the lines of what you wanted. Below will be a pastebin for 1.6.4 and 1.7.10 FML logs.

1.6.4 log:
2014-08-13 17:55:02 [INFO] [OpenComputers] Initializing OpenComputers API.
2014-08-13 17:55:02 [FINE] [OpenComputers] Trying native library 'native.64.dll'...
2014-08-13 17:55:02 [FINE] [OpenComputers] Could not load native library 'OpenComputersMod-1.3.2.525-native.64.dll'.
2014-08-13 17:55:02 [FINE] [OpenComputers] Trying native library 'native.64.dylib'...
2014-08-13 17:55:02 [FINE] [OpenComputers] Could not load native library 'OpenComputersMod-1.3.2.525-native.64.dylib'.
2014-08-13 17:55:02 [FINE] [OpenComputers] Trying native library 'native.64.so'...
2014-08-13 17:55:02 [FINE] [OpenComputers] Could not load native library 'OpenComputersMod-1.3.2.525-native.64.so'.
2014-08-13 17:55:02 [FINE] [OpenComputers] Trying native library 'native.64.bsd.so'...
2014-08-13 17:55:02 [FINE] [OpenComputers] Could not load native library 'OpenComputersMod-1.3.2.525-native.64.bsd.so'.
2014-08-13 17:55:02 [FINE] [OpenComputers] Trying native library 'native.32.dll'...
2014-08-13 17:55:02 [FINE] [OpenComputers] Could not load native library 'OpenComputersMod-1.3.2.525-native.32.dll'.
2014-08-13 17:55:02 [FINE] [OpenComputers] Trying native library 'native.32.dylib'...
2014-08-13 17:55:02 [FINE] [OpenComputers] Could not load native library 'OpenComputersMod-1.3.2.525-native.32.dylib'.
2014-08-13 17:55:02 [FINE] [OpenComputers] Trying native library 'native.32.so'...
2014-08-13 17:55:02 [FINE] [OpenComputers] Could not load native library 'OpenComputersMod-1.3.2.525-native.32.so'.
2014-08-13 17:55:02 [FINE] [OpenComputers] Trying native library 'native.32.bsd.so'...
2014-08-13 17:55:02 [FINE] [OpenComputers] Could not load native library 'OpenComputersMod-1.3.2.525-native.32.bsd.so'.
2014-08-13 17:55:02 [FINE] [OpenComputers] Trying native library 'native.32.arm.so'...
2014-08-13 17:55:02 [FINE] [OpenComputers] Could not load native library 'OpenComputersMod-1.3.2.525-native.32.arm.so'.
2014-08-13 17:55:02 [WARNING] [OpenComputers] Unsupported platform, you won't be able to host games with persistent computers.

This as well is in the console on 1.7.10. I did not notice this on my modded server. Which was running while i ran this one. if that matters.
1.7.10 log:
[18:13:07] [Server thread/INFO] [OpenComputers]: Initializing OpenComputers API.
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/OpenComputersMod-1.3.2.34-native.64.dll which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
[18:13:07] [Server thread/WARN] [OpenComputers]: Unsupported platform, you won't be able to host games with persistent computers.

Pastebins:
1.6.4: http://pastebin.com/CLjqs1kj

1.7.10: http://pastebin.com/index.php?e=1

**Comment by fnuecke** [comment]
Hmm, so it seems it can unpack it fine, but can't load it. One more thing to try maybe: extract the lib (or [wget it from Github](https://github.com/MightyPirates/OpenComputers/blob/master/src/main/resources/assets/opencomputers/lib/native.64.so)), then `ldd -v native.64.so` it, see if that complains about missing dependencies.

**Comment by Randolph-J** [comment]
Here is what i got from that.

ldd -v native.64.so
ldd: warning: you do not have execution permission for `./native.64.so'
        not a dynamic executable

It gave same message as logging in as me, and logging in a root.

**Comment by Kubuxu** [comment]
Do chmod +x native.64.so

**Comment by Randolph-J** [comment]
i did the chmod and it still gives me 

~]$ ldd -v native.64.so
        not a dynamic executable

**Comment by fnuecke** [comment]
Uhh... what does `ldd --version` say?

(And in case you wgetted it, make sure it downloaded correctly.)

**Comment by Randolph-J** [comment]
~]$ ldd --version
ldd (GNU libc) 2.12
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by fnuecke** [comment]
Hmm, while that is quite old (2010? wow) I'm suspecting it downloaded incorrectly. Did you perchance use `wget thatlinkabove`? Because that won't work, you need the "raw" URL (sorry for possibly being misleading there, didn't think about it when I posted the link). Try:
`wget --no-check-certificate https://github.com/MightyPirates/OpenComputers/raw/master/src/main/resources/assets/opencomputers/lib/native.64.so`
instead.

**Comment by Randolph-J** [comment]
]# ldd -v native.64.so
        linux-vdso.so.1 =>  (0x00007fff208c7000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fecf7a88000)
        /lib64/ld-linux-x86-64.so.2 (0x000000357e400000)

```
    Version information:
    ./native.64.so:
            ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
            libc.so.6 (GLIBC_2.3) => /lib64/libc.so.6
            libc.so.6 (GLIBC_2.7) => /lib64/libc.so.6
            libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
    /lib64/libc.so.6:
            ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
            ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
```

**Comment by fnuecke** [comment]
Hmm, looks like it should be fine on that front... I'll add a debug flag to allow logging more information if a lib fails to load, maybe that'll shed some light on this.

**Comment by Randolph-J** [comment]
Ok just let me know if there is anything I can help with to fix this.

**Comment by fnuecke** [comment]
In [the latest **dev** build](http://ci.cil.li/), try setting the `computer.debug.logFullNativeLibLoadErrors` setting to `true`, see what it prints, optionally also set `computer.debug.forceNativeLibWithName` to `native.64.so`.

**Comment by Randolph-J** [comment]
Heres the log for the 1.7.10 dev version; OpenComputers-MC1.7.10-1.3.4.103-dev-universal.jar:

http://pastebin.com/nc4hy0LZ

This is with logFull and ForceNative options changed to your request.

**Comment by fnuecke** [comment]
> failed to map segment from shared object: Operation not permitted

Looking this up, the most likely reason seems to be that your `/tmp` is mounted with the `noexec` flag. From what I read, `mount -o remount,exec /tmp` should fix this. Alternatively, try starting the server with the `-Djava.io.tmpdir=...` parameter, where `...` is some writeable directory outside of tmp (e.g. the MC server's directory).

**Comment by Randolph-J** [comment]
mount -o remount,exec /tmp 

Fixed the issue

Thank you so much for all the help with this!

:)

**Comment by fnuecke** [comment]
Happy to hear that solved it, thanks for confirming :-)

I'll be looking into generating a more helpful message in the log by detecting if the tmp dir is mounted as noexec.

**Comment by Randolph-J** [comment]
glad it was a simple fix :)
