### ISSUE TITLE
Crash on Opening a Terminal

### ISSUE THREAD

**Issue by xploitedd** [MightyPirates/OpenComputers#453]
A friend of mine is going to open a terminal when the game crash. I'm trying to help him the best I can but find no solution to this problem. The crash report : http://pastebin.com/CtYWJcH2

Sorry for my bad english :(

**Comment by fnuecke** [comment]
Hmm, my first thought was this would be related to #31, but it crashes somewhere else. Will look into it.

**Comment by fnuecke** [comment]
So, since I don't see anything obvious that might cause this, I'm afraid this is another one of those "someone with an ATI card who can reproduce this will have to look into this"-issues.

@iamkryforpt Are your drivers up-to-date? If not, could you see if this still happens after updating them?

@gamax92 Since you had trouble with OC crashing the ATI drivers before, have you seen this in the recent builds?

**Comment by xploitedd** [comment]
i'll ask to my friend if he was AMD Catalyst installed on his computer

**Comment by gamax92** [comment]
Unable to replicate crash. Used same OC and Java version as mentioned in crash.

**Comment by jotac0** [comment]
hello, i got the same crash as mentioned here, with a bit different address:
http://pastebin.com/xjhGXUZK

Their exact graphics card model.
ATI Radeon X1200 series

Their version of their graphics drivers.
driver version:8.593.100.0
acording to this site: http://support.amd.com/en-us/download/desktop/legacy?product=Legacy1&os=Windows%20Vista%20-%2032
i have the latest version

The tier of screen this happened with (there is speculation it only happens with tier 3, but I'd like to know for sure).
it was tier one

The amount of memory allocated to Minecraft (-Xmx etc).
-Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M

Their Minecraft version (1.6 or 1.7).
1.6.4

Their used launcher (vanilla, MultiMC, ...).
vanilla

Their LWJGL version (e.g. see libraries/org/lwjgl/lwjgl/lwjgl/).
2.9.0 and 2.9.1

Confirmation whether org.lwjgl.opengl.GL11.glCallList is in the stacktrace of the crash.
yes

crash log: http://pastebin.com/ezAR95p3

edit: curious, on 1.7.10 does not crash, at first test atleast :O!

**Comment by xploitedd** [comment]
ok finally i got a response from him, he said AMD Catalyst is not installed.

**Comment by fnuecke** [comment]
Since this or similar crashes were resolved for others by installing the latest drivers I'll assume that's what the issue was here, too. If this still happens from him with the latest drivers, let me know and I'll re-open this.
