### ISSUE TITLE
1.3.2 doesnt have a 1.7.2 download?

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#454]
Hey mate, my server keeps bugging me to update on 1.7.2 but I cant - you don't have a download link! :(

**Comment by Techokami** [comment]
1.7.2 support was discontinued. Consider upgrading to 1.7.10!

Sent from my Windows Phone

**Comment by fnuecke** [comment]
That. Sorry, managing two versions of MC is taxing enough.

**Comment by ghost** [comment]
@fnuecke Cant upgrade to 1.7.10 - im on a SMP server with 63 mods... need all to be ready first.... You're supporting 1.6 instead of 1.7? weird. :(

**Comment by Wuerfel21** [comment]
Most 1.72 mods work on 1.7.10, too.

**Comment by fnuecke** [comment]
> You're supporting 1.6 instead of 1.7?

I am supporting 1.7. Just not every minor patch of it, only the most recent one... seriously, go complain to other mods that haven't updated instead of complaining to mods that are up-to-date.
