### ISSUE TITLE
Add energy support for a few mods

### ISSUE THREAD

**Issue by asiekierka** [MightyPirates/OpenComputers#458]
I know I'm bothering you with things too much, but I really need Factorization energy support for my pack to work correctly. (Also, the ability to block energy reception by mod ID, if possible. Or anything. Whatever works with you.)

As a bonus feature, consider adding support for IC2 Classic. Shouldn't be too different from IC2-exp.

**Comment by fnuecke** [comment]
Yep, will look into this over the weekend.

Do you have a link to the IC2 classic API? The only ... concern I have with that are possible conflicts with the new one?

**Comment by fnuecke** [comment]
For the record, Factorization and IC2 Classic support are in the latest dev builds, still need to add the blacklist thinger.

**Comment by Robby-** [comment]
Would it be possible to also add support for the Energy Cells in Applied Energistics 2?

**Comment by asiekierka** [comment]
What about OC gets its own engines?

Hmm... new Computronics idea? :3

**Comment by Vexatos** [comment]
@asiekierka The totally wondrous Drama Generator. Insert random drama case, it generates OC power from it.

**Comment by Robby-** [comment]
I don't know. Whatever works I guess, but I'd like to be able to put an energy cell there, and use that instead of BuildCraft's engines.
