### ISSUE TITLE
Change T1 screen Text Color to red

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#459]
Old monochrome Monitors were Green or amber, behause white phosphor was more expansive or something like that. As the T1 screen is made from redstone, the text should be red.

**Comment by fnuecke** [comment]
Nah, that'd make everything look like an error message.

**Comment by Kilobyte22** [comment]
Why not make the color configurable

**Comment by fnuecke** [comment]
Mmm, I suppose that would work, though I must say I feel that'd be kind of ... inconsistent? The other tiers would look the same on all clients, tier one wouldn't. And syncing it via the server seems like overkill. The special code for it should be ... relatively local (that being the 1-bit color used in PackedColor), though that also means it'd apply to all screens / GPUs in 1-bit mode.

**Comment by Wuerfel21** [comment]
why not via setPaletteColor?

**Comment by Kubuxu** [comment]
I'd love ability to configure T1 as green P1 screen.

**Comment by Wuerfel21** [comment]
green would be nice too.

**Comment by SaphireLattice** [comment]
Maybe make it dyeable?

**Comment by Techokami** [comment]
Uh, dyes are already used to color the block.

Sent from my Windows Phone

**Comment by fnuecke** [comment]
While I kind of like the idea of the screen color determining the text color, this would mean quite a lot of restructuring/cross-referencing, as opposed to a simple, global config option. And seeing as I'm not that convinced by the idea anyway, a global setting is pretty much the most I'd be willing to put into this, effort and bug-risk-wise ;-)

The setPaletteColor approach would be a little less invasive, but make the T1 screens more powerful than I want them to be.
