### ISSUE TITLE
Suggestion: Add VersionChecker Integration for ease of updating

### ISSUE THREAD

**Issue by TehSomeLuigi** [MightyPirates/OpenComputers#460]
dynious' VersionChecker mod allows mod updates to be shown in a central location and it also adds the power to update the mod from the VersionChecker screen.

Therefore, I suggest that OpenComputers adds VersionChecker integration so that players using VersionChecker no longer receive a notification once they have entered their world, but instead at the main screen, along with other mod updates that may require tending to.

**Comment by fnuecke** [comment]
Hmm, looks like it can be talked to using IMC, so a soft-dependency / simple check should be easy enough. I'll look into it.

**Comment by fnuecke** [comment]
Done.

**Comment by TehSomeLuigi** [comment]
Thanks!
