### ISSUE TITLE
Mini floppys

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#462]
Add small floppys that have less space for tablets.
Similar to how real tablets only eat microSDs.

**Comment by Vexatos** [comment]
They should literally eat them, with a nice "nom nom" sound.

**Comment by Kilobyte22** [comment]
That also involves destroying the floppy

**Comment by Wuerfel21** [comment]
@Vexatos well: http://bit.ly/1qHjWmA

**Comment by fnuecke** [comment]
I think floppies are limiting enough as it is? Keep in mind that tablets will in all likelihood not have a keyboard, so you have to take into account a lot more code for GUIs and the like. Introducing a new storage medium just for tablets seems a little... excessive to me.

**Comment by Wuerfel21** [comment]
you should be able to upgrade them with a (bluetooth?) keyboard.

**Comment by fnuecke** [comment]
Nah, leave that to people who want to implement laptops.

**Comment by Wuerfel21** [comment]
that answer was_fast_

**Comment by fnuecke** [comment]
I still think there are enough tiers of storage already, if someone wants to implement this as an addon, go for it.
