### ISSUE TITLE
setmetatable(table, nil) crashes

### ISSUE THREAD

**Issue by ComputationalAlchemist** [MightyPirates/OpenComputers#464]
When I use the following code:

```
setmetatable(self, nil)
```

I get the error: `kernel:81: bad argument #1 to 'rawget' (table expected, got nil)`
This happens because, in kernel.lua, the parameter to setmetatable is assumed to be a table:

```
setmetatable = function(t, mt)
    local gc = rawget(mt, "__gc")
    if type(gc) == "function" then
        -- ...
```

However, it can also be nil in order to remove the existing metatable.
Quote from the Lua 5.2 documentation:

```
setmetatable (table, metatable)

Sets the metatable for the given table.
(You cannot change the metatable of other types from Lua, only from C.)
If metatable is nil, removes the metatable of the given table.
If the original metatable has a "__metatable" field, raises an error.

This function returns table.
```

Suggested solution - add these three lines to the top of the implementation:

```
if mt == nil then
  return setmetatable(t, nil)
end
```

My current workaround is to set the metatable to {} instead of nil, but it would be nice to have this fixed.

**Comment by fnuecke** [comment]
Whoops, fixed, thanks! Using a slight variation, `if type(mt) ~= "table" then` instead, to re-use standard setmetatable's error handling for bad metatable arguments.

**Comment by ComputationalAlchemist** [comment]
Sounds good, thanks!
