### ISSUE TITLE
io.lua uses shell.running(), which doesn't exist anymore

### ISSUE THREAD

**Issue by ComputationalAlchemist** [MightyPirates/OpenComputers#467]
io.lua has the following code in the code that allows for redirecting IO of processes:

```
pcall(function()
  for level = 1, math.huge do
    local path, env = require("shell").running(level)
    if not path or override then
      return
    end
    if programs[env] then
      override = filter(programs[env])
    end
  end
end)
```

Note that it says `require("shell").running(level)` - for a long time `running()` has been in `process`, instead of `shell`. Since it's wrapped in a pcall() with the results ignored, _no error is actually reported despite this block of code always failing_.

The same issue applies twice more a bit later, where similar `pcall()`/`shell.running()` code is used.

**Comment by fnuecke** [comment]
Thanks! The code audit is very much appreciated :-)
