### ISSUE TITLE
shell.lua getShell() crashes if shell.resolve() fails

### ISSUE THREAD

**Issue by ComputationalAlchemist** [MightyPirates/OpenComputers#470]
If /bin/sh is removed, the system will crash upon startup with a vague error about the first parameter being nil instead of a string. The expected behavior is an error message saying that the shell doesn't exist.
The reason for this error is that shell.lua's getShell() doesn't check the result from shell.resolve:

```
local function getShell()
  local shellName = shell.resolve(os.getenv("SHELL"), "lua")
  if shells[shellName] then
    return shells[shellName]
  end
  local sh, reason = loadfile(shellName, "t", env)
  if sh then
    shells[shellName] = sh
  end
  return sh, reason
end
```

If shellName is nil (because the shell couldn't be found), it will pass nil to loadfile, which will subsequently cause an unspecific error and the computer will crash.

Recommendation: add these lines to getShell() after the first line:

```
if not shellName then
  return nil, "cannot resolve shell " .. os.getenv("SHELL") .. ": " .. reason
end
```

This causes the error to be reported properly.

**Comment by ComputationalAlchemist** [comment]
Correction:

```
local shellName, reason = shell.resolve(os.getenv("SHELL"), "lua")
if not shellName then
  return nil, "cannot resolve shell " .. os.getenv("SHELL") .. ": " .. reason
end
```

(I forgot the modification to the first line.)

**Comment by fnuecke** [comment]
Done.
