### ISSUE TITLE
tmpfs usage desynchronizes with contents

### ISSUE THREAD

**Issue by ComputationalAlchemist** [MightyPirates/OpenComputers#471]
As far as I can tell, the counting of the usage in tmpfs is independent of the actual contents of the filesystem.

If I reboot a computer, but don't close and reopen the world, the same usage is kept, but the files aren't. Which means that I can run out of room in the tmpfs filesystem without having a single file in it.

If I close and reopen the world, without rebooting a computer, the usage is reset to the default, but the files remain. If I then delete one of these files, the usage drops into negative numbers...

Neither of these are good.

The following is a printout from my testing:
![tmpfs_failure](https://cloud.githubusercontent.com/assets/8279806/3821890/f10b7268-1d16-11e4-8b99-d63a4d1aa8b0.png)

**Comment by fnuecke** [comment]
Thanks!
