### ISSUE TITLE
gpu.getSize() does not exist

### ISSUE THREAD

**Issue by WazWaz** [MightyPirates/OpenComputers#472]
http://ocdoc.cil.li/component:gpu lists "getSize()", but it does not exist.

We can use screen.getAspectRatio(), but there appears no way to find which screen a gpu is bound to (not a problem in my application, but the only reason I can see that getSize() might be needed).

**Comment by fnuecke** [comment]
Thanks, updated. Since 1.3.2 there's `gpu.getScreen()` which returns the address of the bound-to screen (which I also just added to that page).
