### ISSUE TITLE
Crash with cables and mfr decoration blocks

### ISSUE THREAD

**Issue by SonoSooS** [MightyPirates/OpenComputers#478]
I get a crash when placing a cable on a Minefactory Reloaded "decorative brick"

I'm using
- OpenComputers 1.3.2.34
- Minefactory Reloaded 2.8.0RC1-540
- CodeChickenCore 1.0.2.13-universal
- Minecraft 1.7.10 with Forge 10.13.0.1194

http://pastebin.com/kXFrCFEW

**Comment by fnuecke** [comment]
Thanks, should be fixed in latest builds.
