### ISSUE TITLE
Ability to externally trigger the assembler

### ISSUE THREAD

**Issue by LizzyTrickster** [MightyPirates/OpenComputers#480]
The current assembler can accept item inputs. Maybe have it start the 'construction' when it receives a redstone signal? as that would be useful for automating production of robots

**Comment by Vexatos** [comment]
That would allow robots to produce more robots... Creepy.

**Comment by LizzyTrickster** [comment]
\o/ Skynet

**Comment by fnuecke** [comment]
Aye, planned, but good to have an issue for :-)

**Comment by LizzyTrickster** [comment]
\o/

**Comment by fnuecke** [comment]
Done in 16b52c8e90dd07f9fef55a1db3dedf899cd01a30.
