### ISSUE TITLE
Robot assembler should work instantly in creative mode

### ISSUE THREAD

**Issue by flarn2006** [MightyPirates/OpenComputers#481]
If you're playing in creative mode, you may want to still have certain balancing mechanics that sometimes get in the way. For instance, you may want to experiment with efficient use of limited power. Having devices not require any power in creative mode would make this hard. However, the time it takes to build a robot is simply there for realism, and (I assume) to make it difficult to create tons of robots at a time. In creative mode there is no need for this. Therefore, wouldn't it make sense to not need to wait several minutes for a robot to finish assembling if you're in creative mode?

**Comment by fnuecke** [comment]
Hmm, true. So basically if the player that clicked the start button is in creative mode, finish instantly. Can switch to non-creative for testing power consumption of the assembler after all. Yeah, will do.
