### ISSUE TITLE
coroutine.yield() vs coroutine.yield("")

### ISSUE THREAD

**Issue by Akuukis** [MightyPirates/OpenComputers#483]
I wanted to collect all signals without event API, but `coroutine.yield()` doesn't return any signal at all. Instead `coroutine.yield("")` returns all signals correctly just like `event.pull()` do. See the following script to reproduce:

``` lua
term = require("term")
computer = require("computer")
local count = 0
while not switch do -- try clicking keys or insert component to generate signals
  count = count + 1
  local r = {coroutine.yield()} -- change to coroutine.yield("")
  term.clear()
  print(count, computer.freeMemory())
  print(table.unpack(r))
  if r and type(r[1]) == "string" then switch = true end
end
```

In ComputerCraft I had to use coroutine.yield(), and I haven't used Lua outside of minecraft, so I cannot judge if its normal or not. Should this behavior be documented in wiki or considered as a bug like is said in wiki?

**Comment by fnuecke** [comment]
While that is indeed CC specific behavior, there's some code in the OC shell that emulates it, which is why yielding with some string as filter works. For a reason I cannot remember it simply doesn't do that if _no_ arguments are given... if I can't remember why that is by tomorrow I guess I'll just change it to pull always.

**Comment by Akuukis** [comment]
By the way, what happens if you give `coroutine.yield()` a number as first argument? All signals have first argument as string.

``` lua
computer.pullSignal = function(timeout)
  local deadline = computer.uptime() +
  (type(timeout) == "number" and timeout or math.huge)
  repeat
    local signal = table.pack(coroutine.yield(deadline - computer.uptime()))
    if signal.n > 0 then
      return table.unpack(signal, 1, signal.n)
    end
  until computer.uptime() >= deadline
end,
```

**Comment by fnuecke** [comment]
That yield is different from the yields done in programs, but to answer your question: it tells the host side that that Lua state may be paused for the specified amount of time, unless a new signal arrives in the meantime.

**Comment by fnuecke** [comment]
Should work now, remember to re-install OpenOS if necessary.
