### ISSUE TITLE
error "index out of bonds" by term.setCursor

### ISSUE THREAD

**Issue by Akuukis** [MightyPirates/OpenComputers#484]
To reproduce execute with tier 1 screen (50x16) any of the following lines to get the error `index out of bonds`:

``` lua
term = require("term"); term.write("12345678901234567890123456789012345678901234567890"); term.setCursor(47,16)
term = require("term"); term.setCursor(47,16); term.write("blah"); term.setCursor(1,2)
term = require("term"); term.setCursor(51,16); term.setCursor(51,16)
```

It seems that functions `term.isWide()` and `term.setCursor()` do not work well together at the last x position of the screen.

Using OC version 1.3.2.34 in Minecraft 1.7.10

**Comment by fnuecke** [comment]
Thanks!
