### ISSUE TITLE
Robots made with a T3 case cannot use the case's floppy drive

### ISSUE THREAD

**Issue by RobertCochran** [MightyPirates/OpenComputers#485]
Basically what it says on the tin. The T3's drive is usable, but only in a very restricted sense.
All you can do is permanently insert a floppy into the T3's drive. What's the point of a permanent
floppy? Isn't that what a HDD is for? Kinda frustrating because you use up extra complexity adding a
redundant FDD.

**Comment by fnuecke** [comment]
There is no real correlation to the actual slots in a robot to those in a computer case. They just dictate the basic tier. In particular, the floppy slot in the robot doesn't come from the T3 case, T1 and T2 robots also have that, and it's only reason to be there is to allow people to be lazy and throw in an OS disk.
