### ISSUE TITLE
error in downloading oppm programs

### ISSUE THREAD

**Issue by darkluck4you** [MightyPirates/OpenComputers#488]
i tried to download holo2geo but it didn't work. after i found out that it didn't work i tried to download derp, but it didn't work either. when i download it this is what it says: 
Installing package to /usr...
Installing Files...failes opening file for writing: file not foundError while in Done.
Please contact the package auther about this problem.

i hope someone can tell me how to fix this.

edit: somehow it works now.

**Comment by fnuecke** [comment]
Um, there's no `holo2geo`, but I'm assuming that's a typo. And `derp` is designed to be broken (it's a test program for seeing how OPPM behaves for broken packages).

May have been an internet issue.
