### ISSUE TITLE
Analyser doesn't work on drives

### ISSUE THREAD

**Issue by applejag** [MightyPirates/OpenComputers#49]
The analyzer doesn't work on disk drives.

**Comment by fnuecke** [comment]
Well, yes. The analyzer message for the disk drive is suppressed, since the address of the actual disk drive itself would not be very interesting. I could change it to display information on the inserted disk, though, is that what you would have expected?

**Comment by applejag** [comment]
Yes, I was a bit unclear. The analyzer doesn't show the address of the disk inside a disk drive.

**Comment by applejag** [comment]
Useful when you got a CC disk inside the drive since it doesn't say its address

**Comment by fnuecke** [comment]
Ah, very good point. I'll change it.
