### ISSUE TITLE
How to force boot from floppy disk, not hdd?

### ISSUE THREAD

**Issue by Akuukis** [MightyPirates/OpenComputers#492]
I installed OpenOS to a robot and then messed up lib files (term.write function) so it doesn't load but shows error, and the only thing I can do is restart into hdd. In other words, robot is useless now.
Is there a way how to force to boot from floppy disk?

**Comment by fnuecke** [comment]
If both are hard-wired in the robot, no, you're pretty much screwed then. The primary device from which to boot can only be changed via the API (`computer.setBootAddress`) or by removing the boot device.

Also, for questions please use the forums.
