### ISSUE TITLE
OpenComputers doesn't accept non-vanilla colorants

### ISSUE THREAD

**Issue by FredMSloniker** [MightyPirates/OpenComputers#493]
It appears that OpenComputers looks specifically for cactus green, rose red, and lapis lazuli, rather than accepting any similar colorants other mods may add (I'm told this is an oredict thing?) Botania, for instance, adds a wide variety of floral powders that can be used in most recipes where vanilla dyes are accepted... but not OpenComputers. This makes assembling computers more difficult than it needs to be.

**Comment by fnuecke** [comment]
Which recipes are you referring to, specifically?

**Comment by FredMSloniker** [comment]
Well, just as an example, I can't make raw circuit boards with floral green powder; I have to use cactus green. Same deal with screens and their requirements for rose red and lapis lazuli; I can't satisfy them with floral powders. But I can use those powders to dye wool or stain glass or do other things that the vanilla colorants can do.
