### ISSUE TITLE
Adapter should listen to onNeighborChange() as well

### ISSUE THREAD

**Issue by asiekierka** [MightyPirates/OpenComputers#496]
onNeighborChange() is called for TE changes, which is what RailCraft does, for instance (it sets a TE separate from the block setting). onNeighborBlockChange() is only called for block placements/changes. To ensure compatibility with mods which setTileEntity() manually, OC's Adapters should listen to onNeighborChange() as well.

Not sure what the function is called in 1.6.4, though.

**Comment by fnuecke** [comment]
I suppose that would be `onNeighborTileChange`. Didn't see that when I implemented the adapter. Adding it now.
