### ISSUE TITLE
Programs can't be edited outside the game

### ISSUE THREAD

**Issue by Kilobyte22** [MightyPirates/OpenComputers#50]
I tried to edit programs outside the game by editing files in .minecraft/saves/worldname/opencomputers/hdd-id/something

However - it did not work out. in particular, it did not adopt to any file changes. if i changed files on the ingame computer they appeared after rebooting ingame it worked however.

**Comment by fnuecke** [comment]
By default, changes to disk drives and floppies are only flushed to the save folder when the world is saved. This is to avoid game crashes causing disk content and computer state to get asynchronous - as long as the disk remains in the computer / disk drive. This also means that changes to the save folder are also only detected when the world is saved. You can force synchronization by removing and re-inserting a disk.

See the config option `filesystem.bufferChanges`. Set it to false to disable this behavior.

**Comment by Kilobyte22** [comment]
oh, wow, thanks :D
