### ISSUE TITLE
Have components return their capabilities

### ISSUE THREAD

**Issue by FredMSloniker** [MightyPirates/OpenComputers#502]
I'm making a server with a tier 3 GPU and a tier 2 GPU; the former is intended to control a large attached screen, while the latter is for the remote terminal. However, I've run into an issue. I can get the addresses of the two GPUs and the two screens _manually,_ but I don't see how to do it in code. Or, rather, I don't see how to tell them _apart_ in code, because there doesn't appear to be a, say, gpu.tier() function. So if I replace any of those components for some reason (like someone breaks the server case and accidentally walks away with the actual server in their pocket--back up your files, kids!), I have to rewrite the code.

Would it be possible to add a tier() function, or something similar, to components it'd make sense for? It'd be especially useful for GPUs and screens, but I'm sure someone would find a use for it for any part with tiers.

And on a related note: there doesn't appear to be a function to unbind a GPU from a screen. If I boot up and the tier 2 GPU gets bound to the tier 3 screen, and vice versa, can I just bind the tier 3 GPU to the tier 3 screen, then bind the tier 2 GPU to the tier 2 screen? Or will this fail because the screens are already bound?

**Comment by Wuerfel21** [comment]
you can find out with maxColorDepth() (or somerhing like that)

**Comment by fnuecke** [comment]
For now, you'll have to look up the address in the tooltip I'm afraid, but for GPUs you may somewhat differentiate using the max color depth as @Wuerfel21 suggested (if they're different tiers anyway).

I added a required API change to the todo list to allow adding something like `computer.componentSlot(address:string):number` in the future.

As for binding, indeed, I guess I'll add an unbind() method. Note that you can in fact bind two GPUs to the same screen. They'll just both write to it, which is e.g. what you'll see if you have two computers with one GPU each directly connected to the same single screen.

**Comment by FredMSloniker** [comment]
Doesn't checking the max color depth not work right if the Tier 3 card is bound to a Tier 2 screen? I.e., it would report 4-bit color depth because of the limits of the screen?

**Comment by Wuerfel21** [comment]
yep, but you could try until you found the combination returning 8

**Comment by FredMSloniker** [comment]
So try binding every graphics card to every screen until I match the Tier 3s up?  Bleah.

**Comment by fnuecke** [comment]
Yeah, it's a nasty workaround, but I'm unwilling to patch in a slightly less hacky workaround that will get redundant in 1.4 anyway but might then in turn break stuff when being removed again :-/

**Comment by FredMSloniker** [comment]
I'll live with it until then, then!
