### ISSUE TITLE
Add sprites

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#503]
There would be a limited amount of sprites(determined by gpu tier).
these can show any item/block texture or player head.
these can be a any given screen position with any size.

(if someone dont knows what a sprite is: http://en.wikipedia.org/wiki/Sprite_(computer_graphics)

**Comment by fnuecke** [comment]
The GPUs in OC are purely text base, so this would be a major break from that concept. This is more appropriate for a more "image" oriented GPU as in [OCLights](https://github.com/gamax92/CCLights2/tree/opencomputers) (port of CCLights to OC @gamax92 is working on).

**Comment by Wuerfel21** [comment]
it dont seems to work...

```
c:\CCLights2-0.4.1-72>gradlew
Creating properties on demand (a.k.a. dynamic properties) has been deprecated and is scheduled to be removed in Gradle 2.0. Please read http://gradle.org/docs/current/dsl/org.gradle.api.plugins.ExtraProper
tiesExtension.html for information on the replacement for dynamic properties.
Deprecated dynamic property: "ENV" on "root project 'CCLights2-0.4.1-72'", value: "{USERPROFILE=C:\Users\...".

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\CCLights2-0.4.1-72\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating root project 'CCLights2-0.4.1-72'.
> Could not find property 'config' on root project 'CCLights2-0.4.1-72'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.07 secs

```

**Comment by fnuecke** [comment]
Never said it does :P Either way, this is not the place to report that.

**Comment by Wuerfel21** [comment]
yep, getting another error after setting the value in line 25 to 9001.
lol it has no issue tracker...

**Comment by gamax92** [comment]
Umm, that looks like CCLights2 and not OCLights2?

Remember to pull from https://github.com/gamax92/CCLights2/tree/opencomputers
The opencomputers branch

Also i just enabled the issue tracker on my fork.
