### ISSUE TITLE
some unicode things dont render as they should

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#505]
➐➁❡✐╝✂☯☤☢➠

paste these into OC and you will see (just picked a few of them)

**Comment by fnuecke** [comment]
Well, `╝` renders correctly for me, the others as `?`s, meaning they're not supported.

**Comment by Wuerfel21** [comment]
for me they render as pixel mess...
![image](https://cloud.githubusercontent.com/assets/6944842/3972314/21f4cf9e-27dc-11e4-8e2f-eda0bd4e744a.png)

(they are in the last line)

**Comment by fnuecke** [comment]
Latest OC version?

**Comment by Wuerfel21** [comment]
still 1.2.2

**Comment by fnuecke** [comment]
Time to update then!

**Comment by Wuerfel21** [comment]
oh i meant 1.3.2

**Comment by Wuerfel21** [comment]
awww, on 1.3.3 they render as ?, that seems like the font your using is missing that
