### ISSUE TITLE
Yet another power source support request (AE2)

### ISSUE THREAD

**Issue by Robby-** [MightyPirates/OpenComputers#508]
Would it be possible to also add support for Applied Energistics 2's Energy Cells as a power source? Its API is located [here](https://github.com/AlgorithmX2/Applied-Energistics-2-API).

**Comment by fnuecke** [comment]
From what I can tell the AE2 API doesn't lend itself very well for this particular use-case, code-overhead-wise. I.e. for just pulling/receiving some energy it's pretty complex to implement. I'm not really convinced this makes a lot of sense anyway; AE2 is not a power producing mod, and OC isn't an addon to AE2.

If there's more demand for this I might look into it.

**Comment by Wuerfel21** [comment]
i heard AE2 has a coal generator...
