### ISSUE TITLE
Texture mistake

### ISSUE THREAD

**Issue by applejag** [MightyPirates/OpenComputers#51]
The keyboard, looks good all and all.
![alt text](http://i.imgur.com/HZ8gKm7.png?1)

It looks like a real keyboard.
But on the recipe...
![alt text](http://i.imgur.com/Ct7XMhu.png?1)
There's clearly a numpad as an item, but why isn't there a numpad on the block itself?

:)

**Comment by pingbird** [comment]
then it would be a keyboard with only a couple keys

**Comment by applejag** [comment]
I am just saying. As you craft that keyboard the numpad disappears into a alternative numpad dimension and the keyboard is left numpad-less.

**Comment by fnuecke** [comment]
Well, it's pretty hard to fit a recognizable numpad into 16x16 pixels ;) (less, actually)

If anyone wants to make a higher resolution texture set, that could most certainly show a numpad.

**Comment by Vexatos** [comment]
32x computer textures? I would love to see those.
