### ISSUE TITLE
Bug with energy input

### ISSUE THREAD

**Issue by jammer312** [MightyPirates/OpenComputers#514]
I playing on one server and discovered issue with energy input.
When you go away far enough from chunk with OC blocks , so it will unload, next times it loads every block is unable to get energy from IC2 experimental cables and Thermal Expansion energy pipes. That's not only happens to blocks already connected to cables(I had server rack connected directly to cable and computer conected to server rack via OC cables, then I tried to connect computer to cable, it was unable to connect). I found only 2 solutions to keep this from happening, first one is always keep chunk loaded using chunckloaders, second is break energy input block and place it again each time cable disconnect from it.(I hadn't said, but it happens for both computer cases and server racks and power converters).
Sorry for my bad english.
Server core is Cauldron Build 1.6.4-1.965.21.164
If you need more info(like installed mods or screenshots of problem, etc) just ask here.

**Comment by fnuecke** [comment]
While I couldn't reproduce this in my dev-env I did notice some warnings that slipped my attention before, and was able to fix those; could you please try [the latest **dev** build](http://ci.cil.li/) (build 624) and see if it still happens there? (Note this is a dev build, it should stable, but you might want to make a backup of your world first, just to be on the safe side, nonetheless).

**Comment by jammer312** [comment]
I can't check this for now because admin don't want to install dev build (server instabile already(OC and CC conflist with some other mods and no way found yet to prevent it)).
I'll try to check it in singleplayer in some time.

**Comment by fnuecke** [comment]
No feedback in over a week, if this is still an issue in the latest version let me know and I'll re-open this.
