### ISSUE TITLE
Ic2 Crash 1.7.10

### ISSUE THREAD

**Issue by kyomintcraft** [MightyPirates/OpenComputers#518]
http://pastebin.com/UQfB6P93
IC2 is also not installed

**Comment by fnuecke** [comment]
Hmm, could you please check if this still happens to you in the [latest stable and/or dev builds](http://ci.cil.li/)? Thanks.

**Comment by kyomintcraft** [comment]
@fnuecke It does, same log

**Comment by fnuecke** [comment]
Hmm, I can't reproduce this. Could you check if this also happens if you only have OC in your mods folder?

Maybe one of the other mods is shipping a partial/other version of the IC2 API?

**Comment by kyomintcraft** [comment]
@fnuecke It only happens when I place an OC server rack.

**Comment by fnuecke** [comment]
Yes, I saw that in the log, that is what I tried, and I refer you to my previous post ;-)

**Comment by Jyzarc** [comment]
I am having the same problem.

**Comment by fnuecke** [comment]
> Could you check if this also happens if you only have OC in your mods folder?

Any word on this?

**Comment by kyomintcraft** [comment]
@fnuecke it doesn't. It happens when OC and Thermal Expansion are installed together.

**Comment by fnuecke** [comment]
Hmm, still can't reproduce this. Versions I used:
- CoFHCore: 3.0.0B5-30
- CoFHLib: 1.0.0B6-26
- ThermalExpansion: 4.0.0B5-13
- ThermalFoundation: 1.0.0B3-8
- OpenComputers: 1.3.3.54 (as well as latest builds, all work fine)

Tested in singleplayer and multiplayer (Cauldron 1.1207.01.187).

**Comment by kyomintcraft** [comment]
It seems to work with
CoFHCore-[1.7.10]3.0.0B6-32
OpenComputers-MC1.7.10-1.3.4.117-dev-universal
ThermalExpansion-[1.7.10]4.0.0B5-13
ThermalFoundation-[1.7.10]1.0.0B3-8
