### ISSUE TITLE
Project Red API error. (with OC 1.1.0pr2)

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#52]
Version with 1.1.0pr2
Environ: Client, x64 Windows, Minecraft 1.6.4
Mod Installed: CodeChickenCore, Project: Red (2013/12/30, 4.2.2), Many other mods.

java.lang.NoClassDefFoundError: mrtjp/projectred/api/ITransmissionAPI

Crash Report: http://pastebin.com/d1F5SLw0
And: https://www.dropbox.com/s/6h8lk0kphtcpvxy/ForgeModLoader-client-1.log

(*I don't have problem with RedLogic or MinefactoryReloaded.)

Also Post in: https://github.com/MrTJP/ProjectRed/issues/275 (I think it must Project RED problem, but i don't determine that.)

**Comment by fnuecke** [comment]
I'm fairly certain that _this_ particular error has nothing to do with OpenComputers. I just released a hotfix for another issue (Project:Red cables crashing if Redlogic isn't present, stupid mistake on my side), but this looks like the sub-mods of Project: Red are loaded in the wrong order.

**Comment by ghost** [comment]
I will check hotfix later. It will not close until ok. (Written in android phone)

**Comment by ghost** [comment]
It still problem, check here, new comment. https://github.com/MrTJP/ProjectRed/issues/275#issuecomment-31579968

**Comment by ghost** [comment]
Private server admin make mistake, i will hit him.

By `ProjectRedBase-1.6.4-4.2.2.19.jar.zip`, it must `ProjectRedBase-1.6.4-4.2.2.19.jar` but has wrong filename.
