### ISSUE TITLE
term.write to last character on screen causes errors

### ISSUE THREAD

**Issue by FredMSloniker** [MightyPirates/OpenComputers#520]
I've discovered an odd bug in the Term library. Here's some sample code:

``` lua
term = require("term")
component = require("component")
gpu = component.gpu
screenWidth, screenHeight = gpu.getResolution()
term.setCursor(screenWidth, screenHeight)
term.write("#")
term.setCursor(1, 1) -- crashes here with 'index out of bounds'
term.write("#")
```

The thing I don't get is _where_ the program crashes. If I comment out the second setCursor() call, it runs just fine; it just doesn't print the second "#". Nevertheless, printing to the last screen character in this way shouldn't cause a crash.

**Comment by fnuecke** [comment]
Can't reproduce in latest build, try updating please (and don't forget to update/reinstall OpenOS, too).

**Comment by FredMSloniker** [comment]
Is there an automated way to update OpenOS without reformatting my hard drive? Nonetheless, bug seems to be fixed. Thanks!

**Comment by fnuecke** [comment]
Boot from the OpenOS floppy (e.g. remove HDD until booted) and run `install` again. It's the cost for the freedom it brings :-P Maybe one day I'll see if I can put it into OPPM... or someone else does.

**Comment by FredMSloniker** [comment]
I can insert a hard drive _while the computer is running?_ Eeek. Duly noted.

**Comment by Techokami** [comment]
Yep, all components (aside from the CPU and I think RAM) are hot-swappable. Have fun!
