### ISSUE TITLE
Request: robot.count, .compare, .compareTo, etc equivalents in the inventory controller component

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#521]
I was attempting to write a program to move items between inventories if a certain slot was filled, however I found that it was going to require another mod to detect items in the inventory, which is suboptimal. This functionality in the robot inventory controller upgrade would be extremely useful for systems such as the one I was building.

**Comment by fnuecke** [comment]
Already exists: `component.inventory_controller.getStackInSlot`. You can do all of those with that. And yes, it was missing from the wiki.
