### ISSUE TITLE
[Feature change] Remove Component restriction for Robots, just rely on Complexity

### ISSUE THREAD

**Issue by WazWaz** [MightyPirates/OpenComputers#522]
Since there is already a "complexity" number associated with the items added in the robot assembler, and it is opaque for players to work out what is and is not a component, perhaps it would be best to remove the component count limit entirely for robots (since they can't connect to external stuff anyway), and rely solely on the Complexity to keep robots fair.

**Comment by fnuecke** [comment]
Hmm, while I kind of agree to the logic, this invites building robots only using T1 CPUs. So CPUs would have to somehow factor into the complexity cap, then.

**Comment by LordFokas** [comment]
How about higher tier CPUs increasing the complexity cap? That way, the better the CPU the more stuff you can put into the robot. It's almost the same logic as computers.

**Comment by fnuecke** [comment]
Yes. I'm just undecided on how to weigh it (i.e. complexity cap gain from case tier vs. from CPU tier).
Maybe something along these lines?

| Case | CPU | Complexity |
| --- | --- | --- |
| 1 | 1 | 12 (no change) |
| 2 | 1 | 16 |
| 2 | 2 | 24 (no change) |
| 3 | 1 | 26 |
| 3 | 2 | 28 |
| 3 | 3 | 32 (no change) |

**Comment by LordFokas** [comment]
I'd say the cap would be the regular cap ("no change") minus 25% x how many levels below the case the CPU is.

So the caps would be:
12
18, 24
16, 24, 32

Here's my math in case I wasn't clear enough:

```
level_gap = case_level - cpu_level
loss = 0.25 * level_gap
max_complexity = case_complexity * (1 - loss)
```

**Comment by LordFokas** [comment]
Alternatively:

Move the complexity cap from the case to the CPU. Since to use a higher tier CPU you need a higher tier case, it brings that table back to the old 12, 24, 32, eases implementation and still forces players to have both higher tier Cases and CPUs when they need more complexity.

**Comment by fnuecke** [comment]
Hmhm... the fact that the lowest value for T3 would be lower than for T2 irks me, so I'd favor the move to complexity based on CPU thing... though that will invalidate the tutorials again, that tell people it's all based on the cases :-/ Ahhh well. I'll sleep over it.

**Comment by WazWaz** [comment]
It's quite extreme for a robot to ever reach the Component cap for a Tier3 CPU without first exceeding the Complexity cap, so I'd suggest a Tier3 case with a Tier3 CPU should allow a higher complexity than 32. eg. here is a rather maxed-out robot:

![oc-maxed-robot](https://cloud.githubusercontent.com/assets/7268071/4085447/605fd44e-2f1c-11e4-8d72-3743bf55af80.png)

That's 32 complexity, but only 12 components, so only a Tier2 CPU. (the pluggable component slots are basically never worth using since they cost double complexity, eating even deeper into the complexity cap that is easily hit just using the normal slots)

**Comment by fnuecke** [comment]
Funny thing, I was actually thinking one of the nice things of having the CPU influence the max complexity is that you'd now actually _need_ a T3 CPU for max capacity. Because, as you say, more than a T2 CPU in a robot is pretty rare / unnecessary right now. Which I'm not very happy with, for the "extreme" builds.

Edit: CPUs themselves probably wouldn't contribute to the overall complexity then, though, I guess, since that would just be confusing.

**Comment by WazWaz** [comment]
I was thinking more along the lines of a T3 CPU making all the slots in a T3 case usable - mostly for future expansions.

**Comment by fnuecke** [comment]
Ahh, no. There are deliberately more slots than can be fully used, to allow a good amount of flexibility without the robot becoming an overpowered monster that can do anything and everything ;-) [which, given the right upgrades, it can still be, of course]

**Comment by WazWaz** [comment]
Ah - as in 3 Tier1 upgrades vs. 1 Tier3 upgrade. Makes sense.
