### ISSUE TITLE
Merge OpenComponents back into OC

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#523]
The split was originally motivated by trying to have OC itself relatively... light on external APIs. That ship has sailed with all the power APIs anyway, so we might as well merge OCC back in. Potentially as a submodule, if that doesn't turn out to be too complicated / time consuming to set up.

I'll do this with 1.4, i.e. the next bigger version change, to avoid causing duplicate-mod errors after people doing what they think is a minor update.

**Comment by Vexatos** [comment]
You could still have it as a seperate `@Mod`, just in the same .jar file (and in the same github repo), this way it wouldn't need any re-doing.

**Comment by fnuecke** [comment]
Yes, naturally, if only to keep existing configs valid :-)

**Comment by Wuerfel21** [comment]
or merge some power apis to open components

**Comment by fnuecke** [comment]
Wat.

**Comment by fnuecke** [comment]
Done in (for now) local branch.
