### ISSUE TITLE
OC 1.7.10-1.3.3.61

### ISSUE THREAD

**Issue by FoxZOolm** [MightyPirates/OpenComputers#524]
crash when I click on "search item" in creative mod.

works fine if I delete OC.

syl

**Comment by fnuecke** [comment]
Please see if this also happens in the latest dev build ([119 at this time](http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/119/artifact/build/libs/OpenComputers-MC1.7.10-1.3.4.119-dev-universal.jar)). If yes, please upload the crashlog to pastebin and link it, thanks.

**Comment by fnuecke** [comment]
No feedback in over a week, if this is still an issue in the latest version let me know and I'll re-open this.

Also, as mentioned, crash log if it happens again.
