### ISSUE TITLE
Robot Assembler retaining hard disk data

### ISSUE THREAD

**Issue by isavegas** [MightyPirates/OpenComputers#526]
I would very much like for the robot assembler to retain data stored on any hard disks used to build a robot. Much to my dismay, when I used a hard disk that I had installed OpenOS upon to assemble a robot, the robot was unable to boot, due to a lack of a bootable medium.

**Comment by fnuecke** [comment]
Hmm, this should definitely work (and does, for me). Make sure the disk actually works (can you boot from it when it's in a computer without any other filesystems present?). See if it still happens in the latest dev build.

**Comment by isavegas** [comment]
Hmm... Works now that I'm running the Jenkins build. I noticed only because I made a robot with an OpenOS disc pre-installed while playing around with the mod in a creative test world, and decided to try installing the disc onto the HDD before popping it into the robot.

**Comment by fnuecke** [comment]
Strange, since it _should_ have worked since the beginning, but oh well, as long as it works now.
If this happens again (and the disk definitely was bootable before assembly) let me know, and I'll reopen this issue.
