### ISSUE TITLE
Screens displaying as T1 even though they're not

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#527]
So this has been reported as a side-note in other issues before, and I've seen this before, and come across it again in one of the recent builds, so it's still around: occasionally, screens (and tablets) display as 'tier one' in the GUI (i.e. lowest resolution and monochrome), even though they're not - querying the resolution and depth via Lua will print the correct settings, meaning it's a purely visual thing. Logging out and back in / breaking and replacing the screen will usually fix it.

I do not know yet whether this is caused by the state not being properly applied on the client in the first place, or if the client decides to reset the resolution and depth. If anyone can figure out a reliable way to reproduce this, that would help tremendously.

**Comment by Kilobyte22** [comment]
Maybe add a networking debug setting that dumps all OC packets into a file? would help debugging those issues in general (if possible as compile time option, or using ASM, to reduce overhead)

**Comment by fnuecke** [comment]
Should be fixed in the latest dev builds.
