### ISSUE TITLE
Out of memory during file write destroy the file

### ISSUE THREAD

**Issue by twothe** [MightyPirates/OpenComputers#534]
I just had this nasty encounter: hit ctrl-S in the editor and got an out of memory crash while it was writing. It managed to write the first half of the file, the rest was lost forever (about ~1h of work -.-).

As a rule the computers should never crash during IO operations, because there is always something major going to be destroyed.

**Comment by fnuecke** [comment]
Well no. On the one hand, there's no way to cleanly implement that special case, on the other hand, IMHO that's just something you have to account for in an environment with limited memory.

What _would_ be reasonable is to teach `edit` to make a copy of the file before writing to it, and delete the copy only if it succeeds. Can't promise when I have the time to do that, so feel free to PR that in, if you like.

**Comment by twothe** [comment]
The problem is that LUA uses garbage collection, so the amount of free memory at a given point is difficult to impossible to determine.

In addition the error was imo caused by the edit.lua program, there just has to be some memory leak going on there, as otherwise it could hardly run out of memory during the edit of a <1kb file.
