### ISSUE TITLE
Add switch upgrades

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#536]
These would be similar to robot upgrades. Some ideas:

Intelligence upgrade - make the switch reject dupe messages
Port filter upgrade - filters ports
One way upgrade - what it says on the tin
Advanced filter upgrade - filters addresses, ports and message sizes

**Comment by Techokami** [comment]
What's wrong with using a computer to do these functions?

**Comment by Wuerfel21** [comment]
The Source address is wrong then.
Also computers don't differentiate networks

**Comment by fnuecke** [comment]
Hmm, well, some of this could be quite interesting, I guess. Though I'm not a fan of the extra upgrade types idea. It'd be better to have these unlock via the already existing "upgrade system" I think (e.g. needs T1 CPU for simple filtering, T2 for advanced etc).
This will need a lot of GUI work, which I hate very much :-P Also will need some drafting for nice GUI layouts to properly visualize all this... so yeah, relatively time consuming. Will have to see.

**Comment by Wuerfel21** [comment]
why not expose some api and configure stuff from a computer?(of couse only affter entering a password)

**Comment by fnuecke** [comment]
Expose them as components (as access points already are) maybe. Password? No.

**Comment by Kilobyte22** [comment]
Switches are not intended as security devices, but only to seperate networks. If you want anything with security, you gotta make your own switch using a computer and two network cards. (Actually, i am not sure if that is possible currently)

**Comment by fnuecke** [comment]
It's possible to do manual "routing" using servers (that's the reason the internal mode was added). But that seems somewhat... excessive, if all you want to do are really simple things, like one-directional thinger, so I didn't reject it immediately.

**Comment by Kilobyte22** [comment]
indeed. But, if you want more, grab a server.

**Comment by Kilobyte22** [comment]
> The Source address is wrong then.

Then write your own networking protocol or wait for OpenIP (or whatever i'll call it)

**Comment by LizzyTrickster** [comment]
(This was originally intended to be posted after @Kilobyte22 second comment but was helping little brother with the wii) SKS managed to do something similar to manual routing using computers on my server. I think he had computers/switches in a configuration of: Computer <=> cable <=> switch <=> cable <=> computer (with the sequence repeated a few times). I think it worked by broadcasts or somehing

**Comment by magik6k** [comment]
I'm making an advanced zeroconf 'routing software' for few days now and I have fully working network layer. When I finish transport layer and drivers I'll put it to OpenPrograms, and/or if Sangar agrees I'll try to build it in OpenOS or put on a floppy

**Comment by fnuecke** [comment]
@magik6k this stuff in "software"? That sounds really cool! (and would be the ideal way for me to close this issue :P)

I'd be happy to have it as a loot disk for raising awareness of it (possibly with a tiny `init.lua` "firmware"? That'd be awesome). Depending on how complex it is, maybe in OpenOS. Then again, keeping OpenOS somewhat limited by default is better for encouraging custom OSes, so yeah, probably loot disk.

**Comment by magik6k** [comment]
For init I'd use rc/boot script(for now I'm using script in boot). I was also thinking of making minimal network library that could be built into OpenOS, and make a floppy with my operating system with full implementation(For client the library'd have to detect server with full implementation for routing). It'd introduce split between client and server software(My os is bulit on top of OpenOS so it'd keep compatibility with existing software)

**Comment by Kubuxu** [comment]
@magik6k @fnuecke I think that is more than possible. Loot disk with API and drivers and init.lua that makes it act like router/switch.
