### ISSUE TITLE
Restrict Internet card based on location

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#537]
So basically it should be slower when the computer is, eg. In a cave

**Comment by fnuecke** [comment]
Hmm, nah. It's kinda magic anyway, and connects to some omnipresent network from a parallel dimension, so that wouldn't really make any sense at all, IMO.

**Comment by Wuerfel21** [comment]
some question about the internet cards implementation: does it account the 6 cookie dimensions?

**Comment by Vexatos** [comment]
Remember that the Internet card uses the magic power of the Interweb, the Interweb is omnipresent and you cannot _not_ have access to it :P
