### ISSUE TITLE
MFR RedNet Compatability seems to be defunct on MC1.7.10

### ISSUE THREAD

**Issue by TehSomeLuigi** [MightyPirates/OpenComputers#540]
I'm using OpenComputers 1.3.3.61 on Minecraft 1.7.10 along with Minefactory Reloaded 2.8.0RC3-591.

The peripheral in question is the Redstone I/O peripheral. As you can see from the screenshot, normal redstone calls work fine, but using the redstone.setBundledOutput functions has no effect on the RedNet cable.

![2014-09-04_21 32 46](https://cloud.githubusercontent.com/assets/3112308/4156313/f156847e-3472-11e4-9692-a808a7f18bc6.png)

(from left to right:
Redstone Dust = North side of Redstone I/O, a normal redstone connection

Redstone Dust next to White RedNet cable, RedNet historian on the white subnet, Redstone Dust on Orange RedNet Cable, RedNet historian on the orange subnet = all showing no redstone strength output from the Redstone I/O peripheral).

The tooltip of the Redstone I/O peripheral, however, says that RedNet is supported.

**Comment by fnuecke** [comment]
Aye, the API changed, see #525, it's fixed in the latest dev builds (http://ci.cil.li).
