### ISSUE TITLE
Using 'Dual Hotbars' mod rendering 1 hotbar of 18 items causes Itemslots to be misplaced in all OC Inventory GUIs

### ISSUE THREAD

**Issue by TehSomeLuigi** [MightyPirates/OpenComputers#541]
I'm using OpenComputers 1.3.3.61 on Minecraft 1.7.10 along with Dual Hotbars 1.6.

I have the 'Dual Hotbars' mod configured to render my hotbar on the HUD as one row of 18 items as demonstrated by the mod author's display screenshot:
http://i.imgur.com/uJz1Qhz.png

Normally this doesn't affect any Inventory GUIs in the slightest -- except OpenComputers, it would seem.

As you can see from the below screenshot, the items are actually rendered in two rows of 18 item slots in the Computer Case GUI. I have also noticed this with the Robot GUI and the Server Rack GUI, but it probably affects all the GUIs in OpenComputers.

![2014-09-04_21 28 36](https://cloud.githubusercontent.com/assets/3112308/4156446/85667c2c-3474-11e4-9dfe-6d9c3de73553.png)

Sorry for making so many bug reports in such a small space of time. This is my last one, for now, thankfully.

**Comment by fnuecke** [comment]
Well, I suppose that's what you get for using "constants" like `InventoryPlayer.getHotbarSize` without actually having the GUI dynamically adjust to potentially different values than the default :-P I'll look into it. Thanks!

**Comment by TehSomeLuigi** [comment]
I thought it would be something like that indeed. Thanks again for your fast response time!
