### ISSUE TITLE
Cant use $_GET or $_POST with wget.lua

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#545]
as above, I've tried diligantly and failed.... I dont think wget on OC supports get or post variables (PHP Receiving them).

**Comment by fnuecke** [comment]
Please describe the steps you took, what exactly you expected to happen and what happened instead, e.g. which commands exactly did you run and so on.

**Comment by ghost** [comment]
Called this from OpenOS: 

wget http://stargatemc.com/gl.php?username=USERNAME?password=PASSWORD

The PHP script is attempting to receieve this information via the $_GET['username'] and $_GET['password'] fields but it fails.

Both values are alphanumeric strings, nothing special for the get statement.

Both values come up NULL in the receiving PHP script. If I use a regular browser to call these, it works (or wget in linux)

**Comment by fnuecke** [comment]
> wget http://stargatemc.com/gl.php?username=USERNAME?password=PASSWORD

Your query string is wrong. the second `?` should be a `&`. Unless that's a typo in the issue?

**Comment by ghost** [comment]
Thats a typo in the issue, but I'll triple check it is not something I did before too..

**Comment by ghost** [comment]
Nope - Its still a problem - Sorry I should have included this before:

Using http://staragatemc.com/testing.php?username=TEST causes this:

/bin/sh.lua:42: no matches ofund: testing.php?username=TEST

Im not sure how to fix it ?

Ill leave the url up for testing. it just echoes $_GET['username'] back to the requestor.

**Comment by fnuecke** [comment]
Ah, right, globbing kicking in there. Try `wget 'http://staragatemc.com/testing.php?username=TEST'` (note the single quotes).

**Comment by ghost** [comment]
You rock. Thank  you =D

**Comment by fnuecke** [comment]
Glad to hear it works (and wasn't a bug ;)). If you're asking whether there's a "urlencode" method, I'm afraid the answer is no, there isn't. I _think_ that's done automatically by the underlying implementation of the HTTP requests, anyway, though.

**Comment by ghost** [comment]
Thanks mate :dancer: 
OC is amazing.

**Comment by ghost** [comment]
@fnuecke  Hey mate, Not a bug - but is there any way to hide the input of the password on the OC Screen that you're aware of? That way it prevents a player's password being seen by players that might be looking at the computer.

Feel free to ignore this - but a response would be appreciated =D

**Comment by ghost** [comment]
EDIT: Dont worry, Your a developer... If you answer my query then others will expect it. Keep up the good work on OC =)

**Comment by fnuecke** [comment]
"Password chars" for term.read are sort of a pending feature request; for now you'll have to implement that yourself. For help with that (or stuff in general) please use [the forums](http://oc.cil.li).

**Comment by Techokami** [comment]
One way you could hide password chars is to use a Tier 2 or 3 display, and set both the foreground and background colors of the character being printed to the same black color... you can't drag to highlight in the terminal window, so nobody will be able to uncover it.

**Comment by ghost** [comment]
@Techokami You rock!!!!!!! Now to figure out how to do that =D
