### ISSUE TITLE
Remote Terminal Screen Not Updating

### ISSUE THREAD

**Issue by expert7000** [MightyPirates/OpenComputers#547]
https://www.youtube.com/watch?v=rs8b5T_S7So&list=UUGZ7JQhPh-Ea_dUk1jh_Ldg

Basically the only things that will appear on the screen are errors, typing letters / hitting enter yields no results. It has a boot disk so should be booting up just fine.

**Comment by fnuecke** [comment]
Which OC version? If not latest, please try with that, first.
Is there something more than the disk drive connected to the server (another screen and/or keyboard e.g.)?

**Comment by expert7000** [comment]
13.3.54, I'm using Bevo's Tech Pack 1.7.10-10 Full. With just the disk drive for the floppy with openOS attached, the terminal doesn't work, attaching a screen via the cable works, but still no luck with the terminal.

**Comment by fnuecke** [comment]
Try 1.3.4, see if that fixes it.

**Comment by expert7000** [comment]
Sorry, I forgot to mention the issue only occurs on multiplayer. Unfortunately I have to wait for the modpack and server to update to get 1.3.4 on the server.

**Comment by fnuecke** [comment]
If this is still an issue in the latest version, let me know and I'll re-open this issue.
