### ISSUE TITLE
Feature request: Robot SMASH!!1 - well, robot piston arms... 

### ISSUE THREAD

**Issue by ingie** [MightyPirates/OpenComputers#549]
Hello again,

it's a trivial task for a robot to place a piston in front of it, and then actuate it with redstone.

wouldn't it be nice if a robot holding a piston in its "use" slot [where the robot also has a redstone card] could just "be" a piston on robot.use()

it's not like it would be OP since, as i say, it is trivial to just place it down and set the redstone, but it would be nice [i think - perfectly sensible] for a robot to be able to do that itself... 

i doubt this is a trivial change however... as pistons have a lot of weird code in their process [cf. block 36 etc]  ... but it'd be nice :)

[ i shan't try and do this one myself, i'd end up having less hair than i have already ]

**Comment by fnuecke** [comment]
This is actually something I already tried some time ago, but as you say there's a bunch of really... "special" code in there, and worse, a lot of the methods that'd be really useful (like "canThisBlockBePushed" [name differs]) are private, so yeah. Will need access transformer stuff (_at.cfg). Either someone else picks this up, or I might have a look at it again in a few weeks.

**Comment by fnuecke** [comment]
Piston upgrade done. Won't push entities because... well, it's instant, and that would be really derpy for entities. Also, I'm lazy. But it works for blocks! (Even in tablets, which is kinda... weird, but whatever)

**Comment by ingie** [comment]
wow, nice work... didn't need entity pushing anyway, so no biggie...
