### ISSUE TITLE
Crashed, not sure how

### ISSUE THREAD

**Issue by applejag** [MightyPirates/OpenComputers#55]
I wrote a simple program to print a colored box where I touched (very simple).
Here's the code:

```
local gpu = component.gpu
local w,h = gpu.getResolution()

gpu.fill(1,1,w,h, " ")
term.setCursor(1,1)

print("Press CTRL ALT C to interrupt")
repeat
    local ev,_,x,y,user = event.pull()
    if ev == "touch" then
        local color = math.random(0x000000,0xFFFFFF)
        gpu.setBackground(color)
        gpu.fill(x,y,1,1," ")
    end
until false
```

When I touched minecraft just crashed.
I didn't get a crash report...

EDIT: This might not be OC related, but I'll keep the issue up in case it turns out to be OC

**Comment by applejag** [comment]
I do not know if OC caused it but this has happened before, I get a

```
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000001684e660, pid=7540, tid=4224
```

error each time I open a world or log on to a server.
Apperently I have to upgrade my JVM

**Comment by fnuecke** [comment]
Can't reproduce, can you post the full crash report/log, please?
Also, you're missing a `gpu.` in front of the `fill` in the third to last line.

**Comment by applejag** [comment]
Let's just say it all went downhill from there...
![alt text](http://i.imgur.com/9P8erz8.jpg)

I researched some, I followed some suggestions...
...aaaaaaaaaand fuck.

Right now I am sitting on my dads computer, but I'll tell ya, this is not cause of OC so you can close this issue

**Comment by fnuecke** [comment]
Ouch, well good luck with getting your computer (laptop?) back up and running again.

**Comment by applejag** [comment]
Idk man. I just somehow reproduced it and so confused.

I was on the server and tested stuff.
On my dads old computer (the enterprice one) it did **not** crash while it did on my one (I fixed my one, the one with the black screen that couldnt boot from the comment above).
I could crash on my one, and then logon with my dads old computer and it worked just fine. No clue why, but my dads computer did not crash.
I tested a bunch and noticed it was kinda in a certain chunk it was, only when I was in that specific chunk it crashed. But like half of the chunk next to it.
So I messed around, only happens near my cluster of computer containing TE creative power source, TE 1 autonomous activator, 1 CC disk drive, 2 CC computers, 1 OC superior case, 1 OC power converter, 1 OC router, and a bunch of CC and OC cables connecting them all. At the end of the cables leading off the cluster I had 1 OC drive, another CC computer, and 2 superior OC screen blocks (the 2x1 setup I have showed before).

I have it like for security reasons so no-one can get virus into my systems or steal my disks, cause the cluster is underground and hidden. And cause I got networking between OC and CC.

So I with my dads computer removed the cluster of computer, not removing one at a time cause... idk I was lazy, had to reboot minecraft each time because of "Bad Login". But I removed the entire setup including cables and drives and everything, then tried to logon and bam! No crashing!

So I recreate the setup (with my previously crashing computer) and start it up, everything works fine. Until I try out the touch program on it. When I touched the screen I saw it create the pixle on the screen and then I crashed, same crash as before (that EXCEPTION thing, will post the full error in a separate comment).

In the error it says its something wrong with the _ig7icd64.dll_ file, wich is a driver for intel graphics. I have recently updated all my drivers so I am not outdated.

Now I logged on with my dads computer and ONLY removed the screens since this was a graphical crash. And what do you know, I could then logon with my own computer. Not crashing.

I dont know much but I do know its something with the drawing thats strange and crashing me.

**Comment by applejag** [comment]
Heres the full crash report (if you want it on something like pastebin instead I can do that so this comment isnt that big)

**EDIT:** On second thoughs, its waay too big, heres the paste: http://pastebin.com/eFuYh4vE

**Comment by applejag** [comment]
Very similar to #31 but I got intel not ATI

**Comment by applejag** [comment]
Ok just tested, I crash when I set the background color.

**Comment by applejag** [comment]
Does not only happen on the superior screen.
Happens on all screens, any background color on any screen crashes the game with that error report.

**Comment by fnuecke** [comment]
Thanks! Can you definitely narrow it down to the background color being set? (not sure after your last post)

Let's continue this in #31, it seems its something in the display lists, and even if this isn't ATI I think it's safe to say it's related - same stacktrace and all - so it'd be better to keep everything related in one place. I'll change the name of the other thread.

**Comment by applejag** [comment]
Yea by the looks of the crash reports its most definetly related, in my opinion
