### ISSUE TITLE
Wiki: "screen_resized" event is written as "screen_resize"

### ISSUE THREAD

**Issue by twothe** [MightyPirates/OpenComputers#550]
As in the title.

Another good time to mention that allowing access to the Wiki should be a top priority. New players who can't use OC because the documentation is incomplete will abandon it.

**Comment by fnuecke** [comment]
Thanks, corrected it. By the way, registrations on the wiki should be open again, so feel free to fix any more typos you find!

**Comment by twothe** [comment]
Ooooh great! I am on my way to the Wiki then. =)
