### ISSUE TITLE
Feature Request: Secured Input

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#552]
I heard it mentioned this was on the cards and I'd have to do it myself for now.
I'm just creating this as I didnt see another feature request for it so I hopefully know when it's done :)

Basically it'd be really good if we can use term.secureread() or something similar, that allows the user to input a starred value as a credentials (i.e a password).

This would need to;
- Accept input from the player without displaying it on the screen (ideally it would display stars though)
- Clear the history of the terminal for the input so it no longer exists when pressing the up arrow but store the correct input in a variable.

If either of these items above are easy to do without OC supporting it natively, tell me I'm an idiot and point me in the right direction but I've spent a long time looking at the forums and wiki! :)

**Comment by Wuerfel21** [comment]
both are, really easy.
no display: set foreground color to backgound color
no history: domt pass a history table

**Comment by ghost** [comment]
1: How do you do that with a tier 1 computer screen? It doesn't seem to support colors?

2: How do you not pass a history table within a program? I have tried and failed miserably for hours.

**Comment by Wuerfel21** [comment]
1: you can set foreground color to black, or background color to white
2: dont pass one to term.read

**Comment by ghost** [comment]
Is think the problem is I'm using io.read? And I'm not passing any arguments.

Do you have an example of that? 

(I'm closing after your response buddy and not opening stupid questions again.. Sorry devs)

**Comment by fnuecke** [comment]
Well, password chars for `term.read` are sort of a planned feature anyway, so I'll take this as a reminder.

**Comment by ghost** [comment]
Thanks @fnuecke Thats all I was hoping for =)

**Comment by ingie** [comment]
@DraksterAU 

it's a bit "hacky" but this may help you in the meantime:

stick it in your lib or home/lib folder as "pwread.lua" - or whatever you prefer - and "require" it in your main code like a normal lib, then call the validate function with a prompt, a mask char and a password... and it'll return whether it was valid or not

usage: pwread.validate( prompt: string, maskChar : string, password : string ) : boolean 

it isn't designed to cope with any special chars or funky stuff, but should work for most use cases
it doesn't cater for deleting a mis-typed char - but then, i don't think password entry systems should :)

http://pastebin.com/mCPGTY8j

**Comment by rmellema** [comment]
@ingie: Since the library only has one function and it is a hack, you don't have to stuff it into a table. Only returning the function is enough ;)

**Comment by ingie** [comment]
well, i know that... but i started off thinking to do something more complex, then i didn't :)

plus, i like to start my "boilerplate" as if i'm going to do the biggest and best code in the world - never is of course, but hey :)

**Comment by ghost** [comment]
Thanks @ingie!!!! :D Works and will do the trick for now!
