### ISSUE TITLE
robot.swing() will not return an error message if the equipped tool is insufficient to mine the block.

### ISSUE THREAD

**Issue by twothe** [MightyPirates/OpenComputers#555]
If for example the robot has a wooden pick-axe equipped and it tires to mine an obsidian block then robot.swing() will simply return false, but not why it has failed.

Expected: if the quipped item is a tool, but not sufficient to mine the block in front of the robot, then robot.swing() should return `false` and the description of what was in front of the robot (like `false, block`).

This would allow programs to handle pick-axes of a quality lower than diamond without having to have each possible block type in the robot's inventory.

**Comment by fnuecke** [comment]
This is a little tricky, usability-wise, actually. A plain "swing" without a side specified will check multiple sides after all, so the failure message for which side should be returned in that case? Probably the first, but I'll have to sleep over this one.

**Comment by twothe** [comment]
Wohoo! Big thanks! That will make my mining program so much easier. =)
