### ISSUE TITLE
With an Angel upgrade robot.use() on air blocks will always return true even if the action failed.

### ISSUE THREAD

**Issue by twothe** [MightyPirates/OpenComputers#557]
As the title says. For example "Flint and Steel" will report 'true' and 'item placed' even though nothing happened.

**Comment by fnuecke** [comment]
Well, that's because it technically succeeds. At least according to the flint and steel item. It lights the air block on fire, then it gets extinguished again in the fire block's "on added" callback. I don't really feel this warrants special handling, sorry.

**Comment by twothe** [comment]
Well it definitely is a minor issue, just wanted to report it. ;)

**Comment by fnuecke** [comment]
Of course, please do continue reporting these things! :-)
It's just that sometimes the cost-benefit estimate is too unfavorable, as it is here :-/

**Comment by Kilobyte22** [comment]
In fact, this one would probably require a lot of special handling and exceptions, because every item handles it differently. The result: lots of inconsistancy
