### ISSUE TITLE
Bug: Two Multiblock Screen Errors

### ISSUE THREAD

**Issue by Eunomiac** [MightyPirates/OpenComputers#560]
(Sorry for the length; I decided to err on the side of being too thorough ;) )

I've been consistently experiencing two errors with multiblock screens.  While both errors are different, they have one thing in common:  Both screens behave perfectly well when the computers initially boot up, but whenever I relog, both errors appear---consistently and without exception.

**Error 1:  Multiblock Screens Don't Connect; Breaking & Replacing Blocks Eventually Causes It to "Snap" Together**

I mentioned this in a forum post, but thought it best to log it here.  Of the four multiblock screens I have in this one room, only one of them is affected in this way.  Originally, it was very large (I modified the config file to allow for larger screens), and these pictures describe what happens _every single time_ I log in:

![Big Broken Multiblock](http://i.imgur.com/3FauWae.jpg)

Even after reducing the size of the screen, the problem persists:

![Smaller Broken Multiblock](http://i.imgur.com/KLxyjkh.png)

**Error 2: Display Resolution Is Changed and/or Cropped At Login**

Here is an image of my floor display behaving properly---this is how it appears whenever I restart the computer.  Ignore the brown line going down the middle (just for testing), but take note of the brown border lines: they were drawn along the perimeter of the display (i.e. from "1,1" to maxResolution()), so _should_ consistently frame the outer bounds of the screen (and they do, in the "working" version of the floor screen):

![Startup Floor Screen](http://i.imgur.com/zFvEomk.png) 

However, whenever I relog, the entire image is contracted several units vertically, with the top being shifted down and the bottom being cropped.  Note the bottom line, from (1, maxZ) to (maxX, maxZ) has been cut out entirely, and the hologram no longer lines up with the display (oh, and I meant to say "Z", not "Y" in the image caption).  As with the first error, this one never fails to occur at login---and the error only affects this one screen, none of the other three in the same room:

![Broken Floor Screen](http://i.imgur.com/KjfUU9w.png) 

Here is a link to my [autorun.lua](http://pastebin.com/CTsJaMHg) file, as well as to the [jaunt.lua](http://pastebin.com/MeRTYztb) program itself.

**Comment by fnuecke** [comment]
Ah, right, I completely forgot about your forum post, my apologies.

For the issue with the screens not connecting... I'll have to dig some, haven't seen this myself, and from what I remember it shouldn't really be possible (since screens should connect vertically first, and if one screen in a column is loaded, so should all others, since they'd be in the same chunk after all). If need be I'll add some delay before they try to connect, maybe that'll help some.

Regarding the incorrect vertical offset... no idea what's going on there... if you log in with a second client, does it also display incorrectly? Would be helpful to know if it's a synchronization-on-load issue or actually messes up on the server.

Edit: and just to make sure, this happens in 1.3.4, still, yes?

**Comment by Eunomiac** [comment]
> Ah, right, I completely forgot about your forum post, my apologies.

Perhaps, in the fullness of time, I'll find it in my heart to forgive you.  It's not like you're especially busy or anything, jeez. 

;)

> For the issue with the screens not connecting... I'll have to dig some, haven't seen this myself, and from what I remember it shouldn't really be possible (since screens should connect vertically first, and if one screen in a column is loaded, so should all others, since they'd be in the same chunk after all). If need be I'll add some delay before they try to connect, maybe that'll help some.

The screen-breaking issue has been a problem since that first forum post, all the way through to my current version (OC 1.3.4 dev 124)

I think a delay might help---just from logging in, my world kind of goes nuts for a few seconds as everything loads (e.g. my carpenter's blocks appear unpatterned for a split-second).  If the screen is trying to form during that split-second of crazy, this might be causing the problem.

I do find it very odd that only one screen is affected by this---and it's _always_ affected this way, even after I resized it---while the issue hasn't impacted any of the other three screens in the room.

> Regarding the incorrect vertical offset... no idea what's going on there... if you log in with a second client, does it also display incorrectly? Would be helpful to know if it's a synchronization-on-load issue or actually messes up on the server.

Could you expand on what you mean by logging in with a second client?  (I'm running this on my computer in SSP, if you meant having someone jump in with another account.)  Please let me know any other tests you'd like me to try; I'm definitely happy to troubleshoot!

And again, it's very odd (to me, at least) that none of the other three screens in the room are affected---even the screen that breaks apart never shifts/crops its display, just as this screen that shifts/crops its display never breaks apart.  My other two screens (both of which steadily cycle through various "pages" of information) have been running consistently for what feels like months without a single problem.

Could it be a problem with the resolution I've chosen?  (If you look closely at the right and left side, you can see a bit of a shift there as well---the display expands _very_ slightly horizontally when it crops.  I've only ever seen that behavior when I'm fiddling around with different resolutions.)

**Comment by Eunomiac** [comment]
Oh---I just had an idea, which I'll test as soon as I can (might be a couple days; I've got company coming over after work):  With regard to the breaking multiblock screen, would repeatedly logging the results of `getAspectRatio()` to a file eliminate some possible issues?  If `getAspectRatio()` consistently responds with the full size of the screen, even when it appears broken, that would indicate a client-side desync, yes?

**Comment by fnuecke** [comment]
Ah, I somehow assumed this'd be on a server. Well, you could still open a LAN game, but... yeah, the `getAspectRatio()` thing should work! Would be good to know what that reports. Could you also check if that screen's on a chunk border? If it is, that might at least be a less random starting point for investigating this.

**Comment by marduv** [comment]
I have the same issue on my server where the monitor do not snap properly together all the time.
This happen just on the client side and do not affect all players looking at the screen, if you disconnect and connect some times then the screen connect as it should.
So this is way getAspectRatio() says you have a complete big screen.

@fnuecke Yes this is the latest version and the screen is in the same chunk :-)

**Comment by fnuecke** [comment]
All right, that's good to know, thanks. Hmm, I wonder... if the tile entity data is sent to clients separate from the main chunk data that might explain it (meaning some of the screens are missing their data at the time the multi-block screen is created).

**Comment by marduv** [comment]
@fnuecke If you like me to test some builds for you just PM me ;-)

**Comment by Eunomiac** [comment]
### RE: 2nd Issue (Cropped Floor Screen)

**I figured out the problem:**  I was setting the vertical resolution to 55, which is, of course, 5 higher than the maximum vertical resolution of 50.  (Derp.)

**This does reveal a new bug** (though one that should be a lot easier to pin down):  With a Creative Computer and a T3 Screen/GPU, setting the resolution to a value that's higher than the maximum resolution IS permitted, and displays without issue... until a relog (or, I assume, a reload of the chunk), at which point the maximum limit of 50 asserts itself by cropping the image as shown in the screen captures.  I presume the expected/intended behavior is to throw an error if resolution is set too high?

_(Should I separate this into a separate issue from the multiblock screen problem?)_

### RE: 1st Issue (Multiblock Screens Not Snapping Together)

I'll be testing this tonight, but I'm definitely inclined to believe this is a problem with delays or desyncs related to how/when data is sent to the client as the chunk loads, as you suggest:

> Hmm, I wonder... if the tile entity data is sent to clients separate from the main chunk data that might explain it (meaning some of the screens are missing their data at the time the multi-block screen is created).

**Evidence:** When I log in, there's definitely a long delay while everything loads, during which time it's a madhouse:  I see individual, uncolored screen blocks facing the wrong way (plus un-skinned, "naked" carpenter's blocks) for a half-second or so, before everything comes together.  If absolutely _anything_ relating to the multiblock screen forming is occurring in that half-second, I can't imagine how it _would_ form properly---it's chaos, at least client-side, during that brief moment!

**Testing Tonight:**  I'm going to monitor `getAspectRatio()` as promised, just to confirm **marduvGitHub**'s observations.   I'm also going to adjust the config delay defining how long to wait after a chunk loads before persistent computers continue running (I realize this is a different animal from multiblocks forming, but I figure it's worth a shot).

Please let me know if there's anything else you'd like me to try, or any other data you'd like me to log to my debug file.

**Comment by fnuecke** [comment]
Ahhhh, I see what's going on there. 55 is indeed a valid vertical resolution so long as the _total area_ remains lower or equal to 160x50 (that's to allow "pivot mode" with 50x160). But when loading the text buffer just clamps the values to the standard limits when validating. Should be an easy fix!

I'll be adding a delay to the screen multi-block-connect logic later today.

**Comment by fnuecke** [comment]
All right, added the client-side delay to wait for other tile entities in the chunk(s) to load... 2 seconds for now, might make it configurable, but as it's only on load I think that should be fine. Placing them by hand still triggers the check immediately.

@Eunomiac please give it a try when you have the time.

**Comment by Eunomiac** [comment]
Works perfectly!  I've relogged several times, and moved out of range to reload the chunks without disconnecting---no matter what I tried, the screen snapped together without issue every time.  Thanks!

**Comment by fnuecke** [comment]
Great! Thanks for confirming :-)
