### ISSUE TITLE
Crafting should return the amount of items crafted

### ISSUE THREAD

**Issue by twothe** [MightyPirates/OpenComputers#561]
Technically not a bug, but it makes crafting of some items difficult.

The problem is that crafting returns true but does not craft anything if the requested amount of items is lower than the minimum of what can be crafted. Example: craft 1 stick will return true but nothing is crafted, because the minimum amount of sticks that can be crafted is 4.

A solution would be to return the amount of items crafted as a secondary result, so in the above case `true 0` would be returned. 

This would as well help when crafting something without providing the `count` parameter, because it is not clear how many items will be returned in that case.

**Comment by fnuecke** [comment]
Can't you just check the number of items in the selected slot before and after the craft request?

**Comment by twothe** [comment]
Not if that slot was occupied, in which case the items get distributed over the inventory, in worst case over several slots.

**Comment by fnuecke** [comment]
s/selected slot/inventory slots/ :P But agreed, that can be error prone. I'll look into it.
