### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by goldensecret** [MightyPirates/OpenComputers#562]
http://pastebin.com/PQitx2pf

hi, i install the mod on the recommended version of forge yet it crashes. i cannot read crash reports very well so i am sorry if i am giving this to the wrong person. but without this mod, my game is fine, with, it crashes.

**Comment by fnuecke** [comment]
Try upping your permgen memory, it's one of the most common reasons for  `ClassNotFoundException`s.

If that doesn't help, `tconstruct.plugins.imc.TinkerBuildCraft` is Tinker's Construct, see if they can help you.
