### ISSUE TITLE
More Intuitive GPU Control

### ISSUE THREAD

**Issue by Eunomiac** [MightyPirates/OpenComputers#563]
Figuring out how to consistently get the right GPU assigned as Primary, then binding it and the other GPUs to the right screens, is really quite a pain (at least, unless I'm missing out on some easy methods to do this).  The decision to make the selection of primary components random has always struck me as a little odd, at least regarding those components that are slotted into the computer.

A very simple potential solution just occurred to me:  Why not make the GPU in the top-most slot the primary GPU, every time?  _(I totally searched to see if this had already been suggested, and couldn't find it.)_  You could even indicate this in the GUI with a thicker border around that slot.  The same could be done with hard drives, such that the topmost drive is assumed to be the boot drive.

Following up on this, perhaps a change to how `component.list()` works, so that the primary component (if there is one) is always sorted into index 1?  This would make it a lot easier to configure secondary and tertiary GPU's without risking interference with the primary.

(My current method of doing this is to iterate through a `component.list()`, checking each address against the primary component's address to get a list of all my non-primary components, which feels a bit "there's gotta be a better way" to me!)

Okay, I promise this is my last issue submission today :)

**Comment by Kilobyte22** [comment]
Might look into it too see if doable later in case I find time.

**Comment by fnuecke** [comment]
Making the slot a component is in (if any) queryable is planned for 1.4 - needs an API change for a clean implementation.

One thing I wanted to add to OpenOS is designating 'priorities' for components, which will basically determine their sort order, and thus the primary component, now that it can be installed onto writable disks, and those priorities can be written to disk somewhere, therefore persisting. This and/or any other changes to OpenOS, please go ahead @Kilobyte22 if you have the time!

**Comment by fnuecke** [comment]
Slot querying is done in my (for now) local branch, and OpenOS will pick the first one as the primary component when booting.

If anyone wants to contribute further improvements after the 1.4 branch is up on Github, please go ahead.
