### ISSUE TITLE
Bug: Multiblock screen turns off and or computer power down with screen size change or redstone signal

### ISSUE THREAD

**Issue by ingie** [MightyPirates/OpenComputers#564]
Situation: 

Creative Case [ i'm in a mod-free except for OC, world, for testing, so have no power source ]
Case has: 2*T3.5 memory, 1 T3 HDA, T3 CPU, Internet Card, T2 RS Card, T3 GPU

I stick an array of T3 screens on top, turn on... all good.

If i then apply redstone to the case, the screen turns blank, and occasionally the case will power down.
Often this will also happen just by destroying one block of the screen "array"

If the computer hasn't powered off, I usually can't get to the terminal anymore [screen opens, just no response as if it's not powered up or connected to a computer] 

Seems to be rarely triggered by other block updates too, as the first time i noticed this, all i'd done was place some wool alongside the screen. 

Doesn't seem to happen if only 1 screen is connected.

if anyone can test this scenario to reproduce it, it'd make me feel slightly less insane... as for a long time i just couldn't see what the pattern was.... i wasn't even next to the computer and i'd turn round to find the computer had powered off or was not responsive via the screen.. when all i'd been doing was placing wool in the room.

**Comment by fnuecke** [comment]
It's not a bug, it's a feature!

No, really, it is. Applying a redstone pulse to a screen will toggle its power state - and redstone travels through one block in MC. Either apply a constant high redstone signal (lever, rs torch), or avoid sending redstone pulses to screens (connect it via cable, for example). Also see [`screen.turnOn()` and `screen.turnOff()`](http://ocdoc.cil.li/component:screen).

As for the computer turning off when breaking the screen, that's probably something trying to write to the screen, erroring and thus crashing the computer (you can check the crashing error using the Analyzer).

**Comment by ingie** [comment]
hmm.... not sure if that's exactly the case i'm seeing, but i'll check.

as mentioned, this has happened when it was just a block update and there... oh,
hold on, i have a daylight sensor on my roof....  hmmmmmm :)

as for the crash. there was nothing writing to the screen - it was idle at a shell prompt, but i'll check that.

**Comment by ingie** [comment]
yeah, i think my initial "um, my screen has gone" was my rooftop daylight sensor passing its rs through the ceiling into the top block of the screen... damnit :) 

the crash after screen size change is giving me: _boot/02_io.lua:39: attempt to compare number with nil_
which looking at the code could be a race condition...

**Comment by fnuecke** [comment]
Ah, `getDepth()` returns `nil, "no screen"` there. I will add an extra check, thanks!
