### ISSUE TITLE
[Bug/Feature Request] - Big Reactors Crash

### ISSUE THREAD

**Issue by Tkdmaster** [MightyPirates/OpenComputers#566]
So, I placed the adapter against a big reactor's computer port, seemed fine, placed a cable form the adapter and instant crash.

Is there any proper support for big reactors yet with this? Or does it just not work at all?

**Comment by fnuecke** [comment]
It should work, but sometimes things break due to unexpected interactions. Could you please post your crash log? Also which exact versions of OC, BR and MC/Forge did this happen with?

**Comment by Kilobyte22** [comment]
Also, you do not need an adapter. BigReactors has native OC support. Just plug in a cable directly.

**Comment by Tkdmaster** [comment]
Ah alright. In regards to my initial post, I couldn't get this bug to constantly reproduce either, so there's a good chance it was just something to do with the modpack I had on or just a freak one time thing.

On Friday, September 19, 2014 5:04 AM, Kilobyte notifications@github.com wrote:

Also, you do not need an adapter. BigReactors has native OC support. Just plug in a cable directly.

**Comment by fnuecke** [comment]
So can this be closed then?
