### ISSUE TITLE
Monitor touch not accurate

### ISSUE THREAD

**Issue by applejag** [MightyPirates/OpenComputers#57]
On a big superior monitor (with superior graphics card) on default resolution if you try edit a file you cant use the mouse to jump to a position in the text.

And I noticed when using the touch functionality on the monitor itself (outside the gui, without a keyboard) that it didn't count in some of the spots where I clicked, and like skipped some steps. I should note I used a 2 wide 1 high screen on a small resolution (dont got the resolution in my head atm).

I will add more information and screenshots explaining further later.

**Comment by fnuecke** [comment]
There was a bug with click coordinates in scaled GUIs I fixed earlier. I'll look into the "touch" events being off.

**Comment by applejag** [comment]
Now in the GUI it works fine (we are now using 1.1.0 pre2 btw)
but when touching the actual screen its not as accurate, dont know if theres a limitation to your api or something

Here I am using the touch program from #55 and the resolution 63x15 on a 2 wide 1 high superior monitor.

```
local gpu = component.gpu
local w,h = gpu.getResolution()

gpu.fill(1,1,w,h, " ")
term.setCursor(1,1)

print("Press CTRL ALT C to interrupt")
repeat
    local ev,_,x,y,user = event.pull()
    if ev == "touch" then
        local color = math.random(0x000000,0xFFFFFF)
        gpu.setBackground(color)
        gpu.fill(x,y,1,1," ")
    end
until false
```

![alt text](http://i.imgur.com/BOkShgl.png?1)

As you can see it like skips every second one here.
And some spots I cant even click, like the animation doesnt happen where you swing the item you are holding and theres no event...

**Comment by applejag** [comment]
This seems to still be an issue in pr3, when I touch the screen it seems to skip every second one. If I press between one of these gaps it sets the one to the right, and if I press on one of the "listening" pixles it changes as it should. Hard to explain..
Also, bottom half of the pixle sets the pixle below it

![alt text](http://i.imgur.com/1AARMFE.png?1)

**Comment by fnuecke** [comment]
What resolution do you run Minecraft at, what resolution does the screen have, and how big is the screen in blocks?

**Comment by applejag** [comment]
Same size as before. Don't know the size of the minecraft window but I run it at maximized and total screen size of my monitor (IRL computer monitor) is 1366 x 768.

But I tested the program (shows in the second comment) on a singleplayer world (had to add your library to the ignore list, hint hint #65) and it works fine! 
![alt text](http://i.imgur.com/rsCiCwH.png?1)

The server I am playing on got OC pr3 and I got OC pr3... But something gets messed up when I am on a server, you should test if you get the same results on a dedicated server

**Comment by fnuecke** [comment]
Oh. Well. Yay for network optimization... -.-

Minecraft sends click sub-coordinates on blocks in a _very_ low resolution to the server when it's an actual server (16x16 segments apparently). Guess I'll need a custom packet instead of just using the activate event. Learning something new every day!

**Comment by applejag** [comment]
Planned fix for 1.2.0 or 1.1.0pr4?

**Comment by fnuecke** [comment]
It's in [prerelease 4](https://github.com/MightyPirates/OpenComputers/releases/download/v1.1.0pre4/OpenComputers-1.1.0pre4.zip). Hopefully the last one...

**Comment by applejag** [comment]
Just wondering; what will happen if you use pr2 on client and pr4 on server, what will happen with the new packets?
Will it crash something?

Just curious cause all these prereleases still got 1.1.0 so you can connect to a server with 1.1.0 but another prerelease

**Comment by fnuecke** [comment]
Since the packet existed before (for the GUI) there won't be errors, but if the server and client versions differ you'll probably get duplicate `touch` events. And yeah, I kind of forgot updating the version info... oh well. Next time.

**Comment by applejag** [comment]
Just wanted to say that I tested pr4 client and server side and it works beautifully! Now I can start making GUIs :D

**Comment by fnuecke** [comment]
Thanks for confirming :)
