### ISSUE TITLE
IC2 energy crash, without IC2

### ISSUE THREAD

**Issue by KaseiFR** [MightyPirates/OpenComputers#570]
Hi,

I encountered the following crash:
http://pastebin.com/QM3r5y2Q

Basically, it seems OC is trying to interface with IC2 power grid, without IC2 installed (java.lang.NoClassDefFoundError: ic2/api/energy/event/EnergyTileLoadEvent)

**Comment by fnuecke** [comment]
See #567.

**Comment by KaseiFR** [comment]
Thanks for the fast reply!

I tried the last dev build, and it worked.

Yay! No MCEdit!
