### ISSUE TITLE
[ Feature Request ] Geolyzer Improvement

### ISSUE THREAD

**Issue by sirdabalot** [MightyPirates/OpenComputers#571]
This is a really simple and basic request, but could you make the scan( ) method for the geolyzer accept negative numbers? Otherwise it's a major pain in the rear tryin' to get global scanning on the go instead of local. =D

**Comment by sirdabalot** [comment]
Closing the issue - it was extreme numbers it had problems with, this can be deleted, sorry for wasting time.

**Comment by fnuecke** [comment]
Aye, there's a (configurable) range limit.
