### ISSUE TITLE
OpenComputers becomes extremely unstable

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#575]
So, I've had it installed for a while but never used it. So I decided my house needed a computer, so I built one and as soon as I hit the Power button, _bam!_ Minecraft hung. Tried again, so far so good, tried to restart after installing to hard disk, _bam!_ Minecraft hung. I tried a third time, only it hung _before the world even loaded._ [I posted game output log here](http://pastebin.com/EqVn5eQ7). Also, I should mention, I have a LOT of mods running.

tl;dr :computer: :hotsprings:

**Comment by fnuecke** [comment]
Hmm, first things first, please try updating OC. If that doesn't help, could you see if this also happens without LiteLoader?

**Comment by ghost** [comment]
Updating it seemed to work. Thank you.
