### ISSUE TITLE
Crash when installing Pam's Harvestcraft in modpack

### ISSUE THREAD

**Issue by Devilin-Pixy** [MightyPirates/OpenComputers#576]
Although this appears to be an issue with another mod, searching for solutions showed similarities with OpenComputers. I have posted my issue on the Minecraft forum for Pam's Harvestcraft, but wanted to let you know as well in case the problem might be related or on your end. See post here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294413-pams-mods-sept-17th-harvestcraft-1-7-10b?comment=858

I am using OpenComputers MC1.7.10-1.3.4.63 and crashes when adding Pam's Harvestcraft 1.7.10b. MFR is not installed, but last version for Harvestcraft did add compatibility for that mod and to be honest, I believe the issue might be caused by that update. Previous version of Harvestcraft seems to cause no issues.

Crash log: http://pastebin.com/6tbJmwBg

Just figured it would be best to post my findings here as well, although i doubt the issue is on your end.

Keep up the good work,

Daimy

**Comment by lordjoda** [comment]
See #574
