### ISSUE TITLE
Allow Tablets to use floppy disks

### ISSUE THREAD

**Issue by SeniorFight** [MightyPirates/OpenComputers#578]
Allow tablets to use floppy disks, so we can insert an OS via the floppy disk.

OR:

Make an tablet adapter, 1 slot for a finished tablet, and in the computer we could see what's inside tablet's memory, edit, write, copy ect...

It would be awesome! And make the same version for 1.6.4 and 1.7.1+ please, as many modpacks/mods are only for 1.6.4 :(

Thanks for reading.

**Comment by fnuecke** [comment]
Tablets can be placed into disk drives to allow accessing their first HDD (in the dev builds).
OC is and has been feature identical for 1.6.4 and 1.7.10 for ever. Not sure what makes you think otherwise?

However: I'll drop 1.6.4 starting with OC 1.4. Amongst other things, because I can't expect other mods using the OC API to be updated for 1.6.4 anymore, meaning that would only lead to incompatibilities all over the place.

**Comment by SeniorFight** [comment]
Em just 1 question.
Why I can't craft Tablet Case then?
Are tablets not ready?
And I can't put my tablet (made in creative mode, cuz no recipe in NEI) into a drive, just like trying to put a paper instead of floppy disk.

Gonna try again to check this out.

**Comment by fnuecke** [comment]
Unless you're using the latest dev builds they won't have a recipe, yes. Also another change, they now only go into the charger, no longer into the floppy drive (first disk can then also be accessed, to keep things in one place).

**Comment by SeniorFight** [comment]
So i can download a dev build? or is it dev-only?
Because I just can't resist using my HydraOS (GUI based operating system with own apis) on a tablet, making it an android-styled system!
Don't forget to make a variable to detect if it's a computer, robot or tablet, without the need of openOS.

**Comment by fnuecke** [comment]
https://github.com/MightyPirates/OpenComputers#experimental-builds

**Comment by SeniorFight** [comment]
Can I at least manually add an recipe for any block of the mod? (i saw many .recipe in the configs so, but i think it's only a value that mod will search and make it as the current recipe, just can't say THIS ID has THIS RECIPE, the mod will just search for a specific value).

If yes, I would piss on my pants so much i luv eet ! :D

**Comment by fnuecke** [comment]
You're looking for Minetweaker.

**Comment by SeniorFight** [comment]
Just downloaded latest dev build, charger seems to _not_ charge (stays a 0%). I connected thermal expansion's cables successfully to it, with no change. IndustrialCraft2 too, no change. Can't test now for universal electricity, anyway thanks for advice.

Just last question, when my tablet is in the charger, what api/program/component should I seek/use to add files to the hdd of my tablet?

(Thanks for minetweaker!)

**Comment by fnuecke** [comment]
Have you tried turning it off and on again? (no, seriously, the charger's probably not on, wrench it / apply a redstone signal)

When the charger is connected to a computer the HDD of a tablet in it shows up like any other file system.

**Comment by SeniorFight** [comment]
Oh so I just needed a redstone signal...
Thanks for advice. That's all i want to know ;)
Thank you! :D

**Comment by SeniorFight** [comment]
Of course, some bugs in the code.
df "attempt to call field 'getLabel' (a nil value) at line 39" after removing the tablet from the charger, also that a filesystem fatal error that crached my computer (in MC, not the real one of course), saying it's at line 440 ~ something.

Can't boot my tablet, even after adding code.
Says that it can't find the bootable init.lua file... Even after installing openos 1.2! on the tablet's hard disk drive tier 2.
Sneak + right click _does NOT_ restart the tablet.
Of course you know all this stuff I think...

**Comment by Techokami** [comment]
You can add a recipe, but it requires editing one line in the Scala source code first, so the Tablet Case will be registered with a recipe. Once that is done, you can add an entry to the recipe files in the resources folder.

Sent from my Windows Phone

**Comment by fnuecke** [comment]
I'm afraid I can't reproduce the Lua side issues you're seeing, so I can't really do anything about those. The files not showing up / tablet not being bootable after copying OpenOS over should be fixed in the latest dev build; tablets are forced to power off when placed into chargers now, flushing the buffered file system data. Sneak-rightclicking tablets won't reboot them, it'll stop them, and that works as it should for me.
