### ISSUE TITLE
Lighting issue with Chunk-Loader Upgrade

### ISSUE THREAD

**Issue by Nibato** [MightyPirates/OpenComputers#579]
Minecraft refuses to (re)light a chunk if all eight of the immediately surrounding chunks are not loaded. (See World.updateLightByType() and World.doChunksNearChunkExist())

Since the Chunk-Loader Upgrade only loads a single chunk, any sort of block interaction the robot does, such as placing torches, will not trigger light updates. I propose that the Chunk-Loader Upgrade load a 3x3 area of chunks centered on the robot. This will probably help with any other unforeseen issues caused by unloaded chunk borders, as well.

This is relatively easy to test for. Simply load up a single person server, put a robot on a very low Y-level, and have him continuously move forward while digging forward/down, and placing a torch every 8 or so blocks with a Chunk-Loader Upgrade enabled. Log out for about 5-10 minutes, keep the server running, and log back in. If nothing else was keeping the chunks loaded, you should have lighting issues.

**Comment by fnuecke** [comment]
Ugh. Now I do wonder if spot loaders have / had that same issue, and if not, how those work around it. Either way, extending it to 3x3 seems to be the most reasonable solution (although I'd have preferred to keep it as minimal as possible, but oh well).

**Comment by fnuecke** [comment]
Closed via 7b43512d9de28e5c74ed1c8a1d4508cf4caa0b18.
