### ISSUE TITLE
Recipe conflict with Flaxbeard's Steam Power

### ISSUE THREAD

**Issue by Guardian9978** [MightyPirates/OpenComputers#581]
The mod Flaxbeard's Steam Power is overwriting the recipe for the Disk Platter. Is there a way to have an alternate recipe for when both the mods are installed at the same time?

**Comment by fnuecke** [comment]
Hmm, which recipe is that? Would it make sense to oredict it? Otherwise: change it in the `user.recipes` file for now. Automatically changing it won't really be a thing exactly because of the user-defined recipes, but changing the default recipe could be possible I guess... I'm open for suggestions.

**Comment by Guardian9978** [comment]
The Disk Platter recipe needed for the Hard Drive and Disc is being overwritten by the Capsule from Professor Flaxbeard's Wondrous Steam Power Mod. So when trying to craft the Disk Platter instead of receiving a Disk Platter the recipe results in the Capsule from Professor Flaxbeard's Wondrous Steam Power Mod. I'll just change the recipe like you suggested.

**Comment by fnuecke** [comment]
OK, thanks. So not really oredictable. I'll leave this open as a notice to others and as a reminder for now.

**Comment by Guardian9978** [comment]
I also left a message on the Issue Tracker for Professor Flaxbeard's Wondrous Steam Power Mod informing them of the incompatibility.

EDIT: looks like the mod maker for Professor Flaxbeard's Wondrous Steam Power Mod has come up with a solution in there next mod update.

**Comment by Kilobyte22** [comment]
Can this be closed yet?

**Comment by fnuecke** [comment]
@Guardian9978 can you confirm the incompatibility is gone?

**Comment by Guardian9978** [comment]
I can confirm the incompatibility has been resolved.

**Comment by fnuecke** [comment]
Awesome, thanks :-)
