### ISSUE TITLE
robot.use() with a sign (and upgrade) throws "unknown error" but returns "true", works as expected

### ISSUE THREAD

**Issue by Aeysol** [MightyPirates/OpenComputers#582]
Hello,

as the title suggests a robot with a sign upgrade will place a sign when using robot.sign() but returns "true" in conjunction with "unknown error" from the lua backend.

Crashlog is here: http://pastebin.com/yPBAhcZf

Regards.

**Comment by fnuecke** [comment]
I can't reproduce this, neither in single nor in multi-player, neither MC1.6 nor 1.7. Could you try this with the latest (dev) version (see http://ci.cil.li). If it does, let me know if it's single or multi-player, and which MC version, thanks!

(Also: I assume you meant robot.use() in your post [as you mentioned in the subject], not robot.sign()?)

**Comment by Aeysol** [comment]
Latest build solves this bug. Message changes from "unknown error" to "item_placed".

Thanks for this "proactive" fixing.

Regards.

P.S.: It was indeed a typo. :-)
