### ISSUE TITLE
robot.use() destroys bucket

### ISSUE THREAD

**Issue by Aeysol** [MightyPirates/OpenComputers#583]
Hello,

when I use robot.use() with one single bucket in front of a cow the bucket just vanishes with the message "item_interacted" despite there is no filled bucket at all. But when I execute robot.use() with two buckets, the bucket with milk is put in the inventory, so it works as expected as long as the robot has more than one bucket in it's ... claw.

Bug is still present in OpenComputers-MC1.7.10-1.3.5.155-dev-universal.

Regards.

**Comment by fnuecke** [comment]
Thanks!

This seems to generally happen when the interact method replaces the actual "equipped" item, which messed up the following check for whether the item has been consumed. This may also fix more, similar issues.

**Comment by OhiraKyou** [comment]
This is happening in OpenComputers-MC1.9.4-1.6.0.1-beta.2. Might be due to the bucket I'm using being the universal bucket from Base Metals.

**Comment by fnuecke** [comment]
Tried with a regular vanilla bucket, no issues. The only way this still consuming the container item I can see is the container item actually being burnable. Your best bet is to just immediately extract the container again after inserting the filled item (i.e. just follow up your insert() with a remove()).
