### ISSUE TITLE
Tank upgrade for robots

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#584]
Allow storing fluids in robots, one per upgrade. Allow piping fluids into and out of the robot. Allow "sucking" and "dropping" fluids from and into tanks and the world.

Tank controller upgrade to allow the same for items that are fluid containers that are in the robots inventory, as well as inspecting fluid stacks.

This is already implemented, this issue is just for reference and for the milestone.

**Comment by Vexatos** [comment]
@fnuecke Have fun adding that to http://ocdoc.cil.li/component.

**Comment by fnuecke** [comment]
Or someone else could! But since probably nobody will... yeah. Soon (TM).
