### ISSUE TITLE
Rename the JNLua package

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#586]
When other mods try to make use of JNLua (such as LuaCraft), this leads to conflicts with the patched version of JNLua in OC. Will have to rename the package - and recompile all the libs :-/

**Comment by Kilobyte22** [comment]
At least you aren't doing it like cc where they use a patched luaj and yet tell others to rename their version, even if it's unpatched

**Comment by Vexatos** [comment]
At least you aren't doing it like CC and properly recognize other mods using Lua and don't tell them to fix stuff you break.
