### ISSUE TITLE
"Could not load native library" error on OS X with 64 bit JVM

### ISSUE THREAD

**Issue by mheyse** [MightyPirates/OpenComputers#588]
I get the following error when starting minecraft 1.7.10 with OC 1.3.5.67 on Mac OS X running in a 64 bit JVM because it tries to load the 32 bit lib:

```
[OpenComputers/OpenComputers]: Could not load native library 'OpenComputersMod-1.3.5.67-native.32.dylib'.
java.lang.UnsatisfiedLinkError: /Users/mheyse/Library/Application Support/minecraft/OpenComputersMod-1.3.5.67-native.32.dylib: dlopen(/Users/mheyse/Library/Application Support/minecraft/OpenComputersMod-1.3.5.67-native.32.dylib, 1): no suitable image found.  Did find:
    /Users/mheyse/Library/Application Support/minecraft/OpenComputersMod-1.3.5.67-native.32.dylib: mach-o, but wrong architecture
```

It does work when I set `forceNativeLibWithName="native.64.dylib"` in the config:

```
[OpenComputers/OpenComputers]: Found a compatible native library: 'OpenComputersMod-1.3.5.67-native.64.dylib'.
```

So I assume architecture detection is broken. Short JVM info:

```
$ /usr/bin/java -version
java version "1.7.0_25"
Java(TM) SE Runtime Environment (build 1.7.0_25-b15)
Java HotSpot(TM) 64-Bit Server VM (build 23.25-b01, mixed mode)
```

**Comment by fnuecke** [comment]
Ah, thanks for reporting... this is kind of a funny bug in light of the recent "it's Windows 10 because of `if (osVersion.startsWith("Windows 9")`" jokes ... it checks for startswith "x86" before it checks for startswith "x86_64" -.- Will fix.
