### ISSUE TITLE
Tablet/Robot upgrade tooltips should display what they work in

### ISSUE THREAD

**Issue by LizzyTrickster** [MightyPirates/OpenComputers#592]
Raised by Forecaster on IRC, it would be helpful to have a bit of the tooltip that tells you what it works in.

**Comment by fnuecke** [comment]
In 1.4 components that won't work in tablets / robots / whatever simply won't be insertable. This requires some of the API changes in 1.4 tho, so it's a can't do in 1.3, but I cba to adjust the tooltips just to adjust them right back :P (note: I'm already working on 1.4)

**Comment by LizzyTrickster** [comment]
Ok, cool

## 

Josh Green

Sent from my Surface Tablet

From: fnuecke
Sent: ‎Monday‎, ‎6‎ ‎October‎ ‎2014 ‎16‎:‎24
To: MightyPirates/OpenComputers
Cc: Josh G

In 1.4 components that won't work in tablets / robots / whatever simply won't be insertable. This requires some of the API changes in 1.4 tho, so it's a can't do in 1.3, but I cba to adjust the tooltips just to adjust them right back :P (note: I'm already working on 1.4)
