### ISSUE TITLE
Reika's mods

### ISSUE THREAD

**Issue by JoshuaBowerman** [MightyPirates/OpenComputers#595]
With Reika's mods they're split into the api and the 2 actual mods(rotarycraft and reactorcraft). Rotarycraft for instance has functions for computers in opencomputer and computercraft. The functions that are defined in the dragonapi work with some, but not all and none of the functions from the other mods are showing up. these are meant to be used without the adapter and are not being assigned an address but do have a component name, they do not work with adapters either. I'm not sure if this is on your end or not but I figured I would bring it up anyways.

**Comment by LordFokas** [comment]
Given how horribly Reika mods and how many times Sangar has proven his skill, I'd instantly default to dump all blame on Reika.

**Comment by JoshuaBowerman** [comment]
I assumed so but figured I'd bring it up anyways

**Comment by Vexatos** [comment]
Sounds like something Reika has to fix.

**Comment by fnuecke** [comment]
Let's not blame anyone so quickly, I make mistakes, too.

Having a quick look at Reika's sources, his implementation looks fine, except that I can't see a call to `joinOrCreateNetwork` anywhere. If that's the case, and the Github search isn't just messing with me, that means his tile entities never join the OC network. But that would mean _nothing_ should work, which is odd.

@WitnessedHades do you connect to the RC blocks directly (using cable, e.g.) or via the adapter block (and have OpenComponents installed)? In the latter case that might explain some of it, because then you'd probably be seeing the methods provided by OCC, _not_ RC itself.

**Comment by JoshuaBowerman** [comment]
@fnuecke When connected to an adapter the ones that are outlined in dragonapi work but not the others, he says they should work without the adapter but they dont work either way. the ones in the dragon api only work on the adapter and only on some blocks

EDIT: just realized that that meant that its the opencomponents ones because dragonapi creates the same ones.

**Comment by fnuecke** [comment]
All right, I also had a look in dev-env to make sure, but it seems it really is the case that `Network.joinOrCreateNetwork` never gets called for RotaryCraft/ReactorCraft nodes, i.e. it is indeed an issue on Reika's side.

I'd recommend either adding something like

``` java
if (node.network() == null) Network.joinOrCreateNetwork(this)
```

to `updateEntity` or schedule that operation for a tick handler in `validate()`.

Feel free to quote this or point him to this issue directly.

**Comment by ReikaKalseki** [comment]
I will do this.

Also, @LordFokas, who ***\* in your cereal?

EDIT:
`joinOrCreateNetwork` is expecting an argument of type TileEntity, not of type Node. Do I supply `this` into the function, or is there a structural difference?

**Comment by JoshuaBowerman** [comment]
@ReikaKalseki Sangar closed the issue you might have to contact him directly through the forum

**Comment by fnuecke** [comment]
@ReikaKalseki ah, yeah, my bad. Ninjaedited it. `this` is correct.

@WitnessedHades I just closed it because it's nothing I can fix in OC :-)

**Comment by JoshuaBowerman** [comment]
@fneucke I wasn't sure how github worked, I thought you might not see that

**Comment by fnuecke** [comment]
Aye, better safe than sorry. I still get notifications when people reply, even to closed issues, so no worries.

**Comment by ReikaKalseki** [comment]
And fixed.
https://github.com/ReikaKalseki/DragonAPI/blob/master/Base/TileEntityBase.java#L435

**Comment by fnuecke** [comment]
Great, looks good, thanks!

**Comment by JoshuaBowerman** [comment]
@ReikaKalseki just wanted to point out that when i said "I assumed so but figured I'd bring it up anyways" i was only saying that it seemed like something on your end, not that i agreed with what @LordFokas  said.

**Comment by LordFokas** [comment]
oh sorry, I forgot I'm among programmers, the kind of people whose egos don't allow them to take things lightly. But yeah Reika, last time I checked (about a year ago, to be honest, which is not reliable nowadays) you coded your mods in a very... lousy way. That's not to be discussed here though. Sorry if I offended you in any way, it was not intended, but hey, chill.

**Comment by fnuecke** [comment]
To be fair, that was worded very negatively, and in a very general way.
But this is indeed not the place, so I'll be locking this.
