### ISSUE TITLE
Error in scheduled tick action

### ISSUE THREAD

**Issue by Suterusu1337** [MightyPirates/OpenComputers#596]
I thought this was an AE2 issue, they pointed me here.

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/283

OpenComputers (Core) 1.0.0
OpenComputers 1.3.5.67
OpenComponents 0.2.0.22

**Comment by Suterusu1337** [comment]
Power convert blocked being placed in the world causes this error.

Having the chunk the power converter is in unloaded (or being too far away at least) causes the server log to SPAM this message.

**Comment by fnuecke** [comment]
Yeah, see [my comment here](https://github.com/MightyPirates/OpenComputers/issues/573#issuecomment-57949889). Get the latest dev build to avoid the log spam. I'll make it compatible with rv1, too, later today, and throw out 1.3.6 pretty soon I think.
