### ISSUE TITLE
Add Robot move events

### ISSUE THREAD

**Issue by elacy** [MightyPirates/OpenComputers#603]
When a robot moves (of it's own volition or due to external force) there should be a signal to say the direction of the movement, this could be added to the navigation upgrade

**Comment by fnuecke** [comment]
Hmm, the main use would be for external influences I think; for self-movement you could just override the basic move function and push the signal from there. And external influences are kind of rare, and I'm not sure I agree the robot would be able to "tell" (I'm thinking of frames and MFFS).

**Comment by elacy** [comment]
I'm still getting used to how flexible lua is, you're right I could just override the method, thanks :)
