### ISSUE TITLE
Tier 3 Computers disappearing

### ISSUE THREAD

**Issue by SeppDE** [MightyPirates/OpenComputers#604]
After u place an T3 Computer with all components (T3) the computer with all components dissapear. Anything we found is an Crash inside the serverlog, but the server is running without problems.

Crashreport: http://pastebin.com/2L3nL9Z6
Reference: https://github.com/BakermanLP/ModpackProjectRETv7/issues/124

**Comment by fnuecke** [comment]
See #600.
