### ISSUE TITLE
Screen graphic bug

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#605]
Well, i was just programming and debugging with tablets, and then THIS:
![2014-10-19_15 19 20](https://cloud.githubusercontent.com/assets/6944842/4693289/ca0370e2-5792-11e4-84e2-6cedb307799a.png)
![2014-10-19_15 18 43](https://cloud.githubusercontent.com/assets/6944842/4693288/c9edd926-5792-11e4-8f6a-787264042416.png)

It apeears when i open the tablet and disappears after a few seconds when i close it.

To the poor slow internet people: Its the screen contents displayed all over the place!

![2014-10-19_15 23 26](https://cloud.githubusercontent.com/assets/6944842/4693294/27c2d70e-5793-11e4-9362-1602159a25a2.png)

**Comment by Wuerfel21** [comment]
JUst noticed it happens wit other screens, too:
![2014-10-19_15 27 32](https://cloud.githubusercontent.com/assets/6944842/4693310/ee0f3de4-5793-11e4-956d-dfd2be9b8777.png)

**Comment by LizzyTrickster** [comment]
What OC version does this happen on?

**Comment by Wuerfel21** [comment]
1.3.6
oh and i recently installed "Simple Xray", might be that...
will uninstall it until the situation is clearer.

Hmm, also my laptop suddenly rebooted a few minutes later

**Comment by fnuecke** [comment]
Well that, or OptiFine, which is (in)famous for screwing up rendering for mods.
If you can reproduce this without those two mods, I'll re-open this.

**Comment by Wuerfel21** [comment]
Interstimg, now i cant reproduce at all...
