### ISSUE TITLE
OC 1.4: Bugs found so far

### ISSUE THREAD

**Issue by LizzyTrickster** [MightyPirates/OpenComputers#606]
Tablets don't seem to work, well. they dont display a GUI (when built both with and without a GPU)

I also have a server rack occasionally have its servers crash due to 'not enough energy' even though the rack is linked to a MFSU from IC2 that is always full because it's powered by RTGs

**Comment by fnuecke** [comment]
Aaaand I should learn to read. Will look into the IC2 thinger.

**Comment by fnuecke** [comment]
Hmm, IC2 energy works fine for me. What was the exact setup like? Was there maybe some machine with high energy draw (assember/charger) on the side the server was configured to use? In that case the power distribution may have been too slow, which would be kind of expected behavior.

**Comment by LizzyTrickster** [comment]
The only thing i can think of that _would_ potentially drain enough to starve the server would be RC's Electric feeder unit for it's electric tracks but a full mfsu usually provides enough energy to charge the tracks whilst still powering the server rack fine. Will get pictures in a bit (gonna try latest build to see if tablets are fixed)

**Comment by LizzyTrickster** [comment]
IC2 power issue was due to the server rack not being capable of converting the power fast enough. placing a power converter fixed this ( server converts at 50/t whereas power converter does 500/t )
