### ISSUE TITLE
Multipart Packet Crash

### ISSUE THREAD

**Issue by metoray** [MightyPirates/OpenComputers#607]
http://pastebin.com/WqsKrvyz

This crash occurs whenever I log into the server where I placed a multipart cover next to a peripheral cable.

OpenComputers version 1.3.6.69

**Comment by LizzyTrickster** [comment]
What version of forge are you using? This looks to be an error in FMP itself (because i get it with other FMP stuff)

**Comment by metoray** [comment]
I'm using forge version 10.13.2.1230

**Comment by LizzyTrickster** [comment]
Ah, try with 10.13.1.1208, that's what i'm using and FMP doesnt crash (any newer and it does)

**Comment by metoray** [comment]
I tried it with forge 10.13.0.1208 (which I assume you meant) and this indeed fixes it.

**Comment by LizzyTrickster** [comment]
Now that i look at it, yes that is the version i was talking about. Unless @fnuecke can see anything to fix OC side this looks to be a problem with FMP and later builds of forge

**Comment by fnuecke** [comment]
I doubt there's anything I could do about this, since the actual error is indeed in FMP - it's just that the initialization is in this case triggered by OC, but that could have just as well been triggered any other mod using FMP.
