### ISSUE TITLE
1.4.0.1/2-beta1 - Component Bus issue

### ISSUE THREAD

**Issue by MindlessPuppetz** [MightyPirates/OpenComputers#608]
In these latest versions, it seems that the component buses cannot be placed inside of the server boards anymore.

http://puu.sh/cjeTu/63ff243849.png
http://puu.sh/cjeU6/d3ac984a5c.png

I have tried all three tiers of the server board as well as all three tiers of the component buses.

**Comment by fnuecke** [comment]
Thanks! Yep, was a silly oversight, already fixed in [the latest build](http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/191/) :-)
