### ISSUE TITLE
Crash during world generation with chromaticraft

### ISSUE THREAD

**Issue by AnonymousPuppy** [MightyPirates/OpenComputers#609]
Using Forge .1231, a custom modpack, and OpenComputers 1.4.0.2-beta.1 along with chromaticraft v2.
I keep crashing when attempting to generate a world, it consistently occurs every time.

Here is the crash report: http://pastebin.com/mLxGYM4z

This issue was brought to Reika's attention and his response was: "It is crashing on something related to OpenComputers." I reverted OpenComputers to the previous version, and the issue went away.

Until this is fixed, I will be reverting back to version 1.3.6.69. Please take a look at this whenever you can, thank you.

**Comment by Techokami** [comment]
OpenComputers doesn't add any world generation... Report it to the chromaticraft dev(s)?

Sent from my Windows Phone

**Comment by LizzyTrickster** [comment]
OpenComputers is no-where in that stacktrace, can you list all the mods you have loaded when the error occurs?

**Comment by fnuecke** [comment]
While it isn't explicitly in the trace, createNode is where the OC stuff is init'ed. I'm 99% sure this is an API incompatibility (see the OC 1.4 changelog, it states very clearly that mods using the OC API won't work right away). Once it's out of beta I'll more actively try to get people to update; right now I still want to wait a few days to make absolutely sure the API won't need any last minute changes.

So yeah, for now please stay on 1.3.6, update to 1.4 when DragonAPI gets the new OC API. The 1.4 version has intentionally few new actual features, to make this transition (so people staying on 1.3.6 for now don't feel like they miss out).
