### ISSUE TITLE
Robot with crescent hammer cant break strongbox above it

### ISSUE THREAD

**Issue by dunkfordyce** [MightyPirates/OpenComputers#610]
A robot with a crescent hammer and a strongbox above it, if you issue robot.use(sides.up, true), the strongbox isnt broken, the function returns 'true   "item_placed"'. If the strongbox is in front of the robot, and I use sides.front, it can break the strongbox.

**Comment by Kilobyte22** [comment]
I think it shouldn't be able to break the strongbox at all. The Fake player of the robot has a different name than the person who placed it by default. No matter how, thats a bug.

**Comment by dunkfordyce** [comment]
Even if the robot placed it himself?

**Comment by fnuecke** [comment]
You're kuya from IRC, right? Guess you didn't get my message then ;-)

You need to use `robot.useUp(sides.up, true)`.

**Comment by dunkfordyce** [comment]
Thankyou.. thats not intuative!

**Comment by Vexatos** [comment]
@dunkfordyce http://ocdoc.cil.li/api:robot

**Comment by fnuecke** [comment]
To add to that link, as is documented there, the side parameter to these methods is not the "main" direction, it allows specifying which direction the robot "aims" with more precision. This is primarily useful when placing blocks (e.g. buttons or torches, so they go onto the face you want) or activating blocks (e.g. multiple buttons in one block space when using ForgeMultipart). It also allows more control over direction when using certain items, such as bows or splash potions.
