### ISSUE TITLE
Detailed robot.detect() to yield block ID and block name

### ISSUE THREAD

**Issue by Qanthelas** [MightyPirates/OpenComputers#611]
I talked a bit on IRC about the possibility of a new function - perhaps through use of a Geolyzer upgrade for a Robot - that yields the block ID and block name of a block around the robot rather than just the basic results of robot.detect() like 'entity' or 'solid'.  Any other information that this function could yield, such as the name of the mod that item comes from or its density/required pick level, would be icing on the cake but not necessary (at least for my purposes.)  That said, my hope would be that this call could return a table of all the information that OpenComputers can feasibly access about a block in the world, if for no other reason than that it might allow for more customization options in various programs in the future.

To give an idea of why I'd like to use this, consider this sample case.  A robot pulls coal from one chest and logs from another chest to put into a furnace.  It then takes the charcoal out of the furnace and puts it into a 3rd chest.  I would like to run a check before attempting to robot.suck() from a chest to make sure that it actually is in front of a block with item name 'chest' and another check that it is in front of a block with item name 'furnace' before trying to robot.drop() into it.

In theory an extended use could be used to find a block of a certain type around the robot, perhaps integrating the 'nav' program to help it plot out a map of where different blocks are and help it navigate to a block of a specific type, but that is something to look into further down the road.

**Comment by fnuecke** [comment]
The geolyzer now has an additional method, `analyze`, that can be used to get more information about blocks directly adjacent to the analyzer / robot / thing containing the geolyzer upgrade. It'll return the block name, metadata and some additional info for now.

**Comment by Qanthelas** [comment]
Yay! Thanks! I will try to experiment with this new upgrade once I can get a stable testing environment set up. (Currently the official Minecraft server is not letting me download the 1.7.10 files.)
