### ISSUE TITLE
All-In-One Computer [Suggestion]

### ISSUE THREAD

**Issue by rhjobe** [MightyPirates/OpenComputers#612]
I would like to suggest an all in one computer - like the ones in Computer Craft, but much more in the style of Open Computers.

I have imagined two versions of this. One that acts much like that of Computer Crafts, and one that is much like that of a Keyboard.

Version 1: Computer Craft Version
-Fits in one block
-Made in Assembler
-Very limited, low powered compared to multi-block computer
-Tier 1 Screen integrated 
-No drive bay
-Limited cards (internet, redstone, etc)
-Optional Battery
-Limited to 1 block

Version 2: Keyboard Version
-Goes on a wall, much like keyboards
-Made in Assembler
-Much like Version 1
-Redstone card powers the attached block (block it is placed on)
-Thin, sleek, about the thickness of one pixel.
-Can be rotated using what ever tool OC has
-Touch Screen
-Battery, accepts power from cables behind, and can connect to networks

I'm sure you get the point.

**Comment by Vexatos** [comment]
I really don't like this idea. The whole point of OC is to have a large computer sitting somewhere in your house, it not being a single "magic block".

**Comment by fnuecke** [comment]
I'd lean to agree with Vexatos here.

My main argument, however, would be that the "all-in-one" devices that do exist (robot, tablet) are very specialized and therefore have very clear limitations / different use-cases than normal computers, and this isn't different enough from normal computers / adds too little value for the involved effort, both implementation-wise and using it in-game.

**Comment by Techokami** [comment]
Thirding that this isn't a good idea. "Magic Blocks" are not fun. Consider building around the concept of a larger computer setup; why not build a desk and chair for it? Make it look like a proper computer station!

**Comment by fnuecke** [comment]
Well, fun is fairly subjective ;-) But yeah, it doesn't really fit the theme/style of OC, Which, I guess, is also kind of subjective. Anyway. Closing this for now. If someone can make a compelling argument for it I'll re-open this.
