### ISSUE TITLE
in Lua prompt =component.list() throws an error 1.4.0.4-beta.1

### ISSUE THREAD

**Issue by Moltenkore** [MightyPirates/OpenComputers#614]
In the Lua prompt when I type 
=component.list()
I get this:
![component list error](https://cloud.githubusercontent.com/assets/3200633/4745875/97810f3e-5a40-11e4-996d-2b7bad3fc446.JPG)

(Not sure if this has been reported before)

**Comment by fnuecke** [comment]
Thanks! No idea how I missed this... probably forgot to reboot.
