### ISSUE TITLE
Creative Mode: Navigation Upgrade + Vanilla Map (with location set by use) Crashes the Game

### ISSUE THREAD

**Issue by Qanthelas** [MightyPirates/OpenComputers#615]
This is running the latest dev build, OpenComputers-MC1.7.10-1.4.0.194-dev-universal, with the FTB Lite 3 Alpha pack as the barebones mod pack I'm using to test with.

Use NEI to give me a stack of Navigation Upgrades, a stack of Compases, and a stack of Paper.  Crafter the Paper and Compases into Maps.  Right click each map to set its point on the same area.  Craft a Navigation Upgrade with a Map in a Crafting Table and it crashes.

First crash log: http://pastebin.com/37W8PZVX
Reproduced again yielding a 2nd crash log: http://pastebin.com/G7HNVKmf

**Comment by Qanthelas** [comment]
Tried recreating this error on Minecraft 1.6.4 but no, the Map and Navigation Upgrade crafting together in a crafting table without issue.

**Comment by fnuecke** [comment]
Thanks! Yeah, that one wouldn't happen in OC 1.3 because it's in the code used for converting blocks from the old format to the new.
