### ISSUE TITLE
computer.explode

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#616]
I think there should be a computer.explode function.
It would work like this:

If potatotrumpet is near the computer in a 16 block radius, kill him immediately

alternatively, halt and catch fire could be a function.

it would find potatotrumpet and light him on fire.

**Comment by rhjobe** [comment]
Why are we not funding this?

**Comment by gamax92** [comment]
Because we is broke

**Comment by gamax92** [comment]
r iq is negative

**Comment by fnuecke** [comment]
Addon card. Go. :P
