### ISSUE TITLE
Add a "modem.effectiveLength()" function

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#618]
to get the network length of a list
Edit: And please backport to 1.3

**Comment by fnuecke** [comment]
Hm. Maybe. For now, just compute it yourself (strings are `#str`, numbers are 8 (double), booleans and `nil` are 4).

Probably won't backport though, too utility for that, and easy enough to compute on the Lua side.

**Comment by Kilobyte22** [comment]
Doesn't the length depend on the platform of the host? (As in x86_64 having longer size for numbers)

**Comment by fnuecke** [comment]
[Not when it comes to network messages](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/network/Network.scala#L647-L657). Since those are "sent via JVM" anyway.

**Comment by Kilobyte22** [comment]
Ah, good to know

**Comment by Wuerfel21** [comment]
ahh currently writing it in software anyway
Edit: for numbers i hack the header of a dumped function
