### ISSUE TITLE
Computer's drain far much more power than they should (Mekanism)

### ISSUE THREAD

**Issue by Moltenkore** [MightyPirates/OpenComputers#619]
Hello, when I connect my computer up to Mekanism's ultimate universal cable it will drain an ultimate energy cube extremely quickly. Not to sure why because the computer is at full power and it seems to be over consuming.

Surely this is enough power:
![2014-10-23_15 35 05](https://cloud.githubusercontent.com/assets/3200633/4754952/e02d91fe-5ac1-11e4-85dc-3ff314960072.png)

**Comment by fnuecke** [comment]
Which OC version is this? (And Mekanism)

**Comment by Moltenkore** [comment]
Oh sorry, it's 1.7.10-1.4.0.194

**Comment by fnuecke** [comment]
OK, thanks. Might have accidentally flipped the logic when implementing the limited throughput for blocks in 1.4... (it feels like half of the power systems expect you to return the _consumed_ energy, and the other the _surplus_ energy, so I tend to get confused :P)

**Comment by Moltenkore** [comment]
You've created a monster! It eats all the power!
