### ISSUE TITLE
Unexpected "Not enough memory" errors...

### ISSUE THREAD

**Issue by KFAFSP** [MightyPirates/OpenComputers#620]
I'm getting a seemingly incorrect "not enough memory" error when trying to include a library using "require". It is also thrown when it is loaded using "dofile". The screenshot:

![2014-10-23_16 49 03](https://cloud.githubusercontent.com/assets/4153280/4755272/38389afe-5ac4-11e4-9915-62928cab333e.png)

shows you the exact error text. Note that managed.lua itself calls require("stdlib") and require("unmanaged"). That is why I tried to load them independently. To put it in proportion: The computer contains two Tier 3.5 memory modules, in a creative case. And the three files have the following filesizes (after obfuscating them, admittedly):
stdlib.lua = 18kb
unmanaged = 3kb
managed = 12kb

So, shouldn't this work?

**Comment by fnuecke** [comment]
File size stands in no correlation to the amount of memory actually used by a lib/script (not necessarily anyway). For example, you can use up 2MB of memory easy, just do `string.rep('a', 2000000)`. Without seeing what 'managed' actually contains it's impossible to say, but I'm pretty sure this is _not_ an issue with the memory allocator... all sorts of things would be breaking left and right if it were ;-)

Have another look at your managed script and/or have someone else give you feedback (e.g. ask on IRC). If you're absolutely sure the script would not consume that much memory when loaded, post it here, and I'll also have a look at it.

**Comment by Techokami** [comment]
Does it work with the non-obfuscated versions?

Sent from my Windows Phone

**Comment by fnuecke** [comment]
Why would that make a difference? Minecraft's obfuscation has nothing to do with Lua's memory allocation.
