### ISSUE TITLE
The IRC Client doesnt support colors!!!

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#621]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Kilobyte22** [comment]
Indeed. Why do you tell us about that though?

**Comment by LizzyTrickster** [comment]
Yes, it is known it doesn't support colours. Why don't you fix it instead of whining about it? Surely that'd make everyone happier?

**Comment by Kilobyte22** [comment]
He never stated he wanted a change, so i have to assume that he is just trying to inform us about this thing.

**Comment by LizzyTrickster** [comment]
So it seems. Thank you for the _information_, Wurfel21.

**Comment by fnuecke** [comment]
If there were rules for feature requests, assuming this is a feature request, one of them would be "no zero-effort-posts". I mean, come on...

Anyway, if you think this should be a thing, feel  free to implement it and make a pull-request. Depending on how quick the chat goes and how colorful it gets, this could be quite slow, though, so I'm not sure it's worth the effort at this point ;-)

**Comment by Techokami** [comment]
Isn't color not actually a thing that's part of the proper IRC protocol, but was just added in by mIRC and then a bunch of clients adopted it as well? Because the RFC for IRC makes no mention of colors.

**Comment by Kilobyte22** [comment]
Its a de-facto standard. Nothing more and nothing less.
