### ISSUE TITLE
Connecting to Big Reactor Crashes the Open Computer

### ISSUE THREAD

**Issue by Qanthelas** [MightyPirates/OpenComputers#622]
Here is an imgur gallery to help explain the issue: http://imgur.com/a/ws3b5

This is using BigReactors-0.4.0rc10 and OpenComputers-MC1.7.10-1.4.0.196-dev-universal in the FTB Lite 3 Alpha pack (which I'm using as the bare bones pack for testing in by adding additional mods.)

I have an Open Computer set up and I've been doing a bit of testing with it, no problems.  I made a small Big Reactor (5x5x3, internal dimension 3x3x1) with a Computer Port and ran Open Computer Cable from my Open Computer to this Computer Port.  That causes an error to show on the Open Computer.  Running 'components' shows the Big Reactor, but going into lua and trying =component.br_reactor crashes the Open Computer.  Trying to turn the Open Computer off and back on keeps crashing the Open Computer.  Break a cable so the Big Reactor is no longer connected and the Open Computer starts up just fine.  Replace the cable to restore the connection and the same cycle repeats (first the error, then I can see the Big Reactor in the components, then trying to go into lua to get details about that component crashes, then the Open Computer won't turn back on.)

For what it's worth, this test is run on my older laptop.  It's possible the real computer (as in the one running Minecraft) is part of the issue here - if need be I can try to test again on a different computer.

**Comment by fnuecke** [comment]
This is an (expected) API incompatibility (which is something I clearly mentioned in the post on MCF and the OC forums ;-)).

BR [will be updating shortly](https://github.com/erogenousbeef/BigReactors/issues/363).

**Comment by Qanthelas** [comment]
Step ahead of me :)  Thanks for the news!  And good point on the API incompatibility - I just didn't expect it to crash the Open Computer, but I suppose I should have.

**Comment by LizzyTrickster** [comment]
I did say about the API incompatibility / conflicts in IRC
