### ISSUE TITLE
Opencomputers crash game when start up

### ISSUE THREAD

**Issue by Usernm0** [MightyPirates/OpenComputers#626]
I rename mods files in my mods folder like this:
lib_Resonant-Engine-1.2.0.349-universal.jar
lib_Universal-Electricity-3.1.0.115-core.jar

When start open computers find this mods, and try to do something with ue. And crash on pre initialization.
http://pastebin.com/21u26iGY - here last lines from forge mod loader log. 
If i remove Resonant-Engine-1.2.0.349-universal.jar or rename it back to default name, everything work just fine. 

I have few more mods depends from resonant engine, like mffs or icbm and they works fine with renamed lib.

**Comment by LizzyTrickster** [comment]
It seems that you've managed to grab a build of Resonant Engine that was for OC 1.2 yet you have OC 1.3. try updating your RE build to a later one if possible.

**Comment by fnuecke** [comment]
Yeah, this seems to be an API incompatibility. I'm not sure there is a version of RE for MC1.6 with the newer OC API.

As for MC1.7, I've also [opened an issue](http://tracker.calclavia.com/issue/RE-30) to let them know about the upcoming 1.4 version of OC.
