### ISSUE TITLE
Crash when placing a cable at layer 0

### ISSUE THREAD

**Issue by Snakybo** [MightyPirates/OpenComputers#63]
OpenComputers Version: v1.1.0pre2
Forge Version: 965

Crash log: http://pastebin.com/c4s07mGn

**Comment by LordFokas** [comment]
That makes sense, cables check the blocks around them, at layer 0 the block below is at y-1, and since blocks are stored in arrays, it's out of the array's bounds... it's only an issue in creative, but it's as simple to fix as adding a check for negative Y values.

**Comment by LordFokas** [comment]
I strongly suggest doing the same check for when the y Level is the world's height... that one might be a problem in creative. Let's not forget arrays have 2 bounds :P

**Comment by fnuecke** [comment]
Yeah, that's what I thought, too. See the second commit, uses getBlockId which in turn properly checks the y coordinate (and also checks this in another code location that uses neighboring blocks, meaning coordinates that may be out of bounds). I have no idea why Minecraft doesn't check the y coordinate in getBlockTileEntity anyway... it checks the x and z coordinate, but not y -.-

**Comment by LordFokas** [comment]
Because fuck logic

![notch](https://f.cloud.github.com/assets/3021352/1849790/b1662eaa-76bd-11e3-8cdd-fe660d5b386a.jpg)
