### ISSUE TITLE
IC2 Batpack support for tablets

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#632]
Basically, Tablets should be able to drain power from a batback i have on.

**Comment by Vexatos** [comment]
I don't think that would be good, would remove the need for manual charging anyhow.

**Comment by Wuerfel21** [comment]
But thats exactly the purpose of a batpack, charging mobile devices.
Also the biggest batpack that isnt endgame anyway has 600k EU

**Comment by fnuecke** [comment]
I don't think this is a good idea. It makes battery upgrades superfluous, and kind of messes with the "balance" that is given by the number of upgrade slots in a tablet. For comparison, while it's super-useful, I always disliked that Modular Powersuits could be powered by energy items in the inventory. Completely makes battery modules superfluous, making the weight restraint kind of... a non-issue. What I do consider is allowing certain energy items as upgrades, we'll see.
