### ISSUE TITLE
Tablets rebooting all the time

### ISSUE THREAD

**Issue by Wuerfel21** [MightyPirates/OpenComputers#633]
In 1.3.6, my tablets reboot when:
- I didnt used them a while
- When i restart the game
- When i need them

Is this fixed in 1.4?

**Comment by fnuecke** [comment]
Tablets should only stop/reboot when
- They're not in a player's inventory.
- The player with the tablet in the inventory leaves the game (including SSP).
- The player with the tablet in the inventory changes dimension.
- They run out of power (duh).
- They're also immediately stopped when placed into a charger to avoid issues with how the first HDD is accessed.

The fact that they're not saved across joins is a technical limitation (it's a combination of the tablet state being referenced via the player entity, which ceases to exist when the player leaves, and the fact that computer states are saved externally and pruned on chunk save to avoid accumulating "dead" states).

If they stop while they're in your inventory and none of the above applies let me know and I'll look into it.

**Comment by Wuerfel21** [comment]
Sometimes, i just pull it out, see the normal screen for a second and then its rebooting

**Comment by fnuecke** [comment]
The screen keeps it state when they stop, that's normal and the same as it is for screens.
What I'd like to know is if you are 100% certain this happened without any of the cases I described above applying (i.e. them stopping in "normal" use).

**Comment by Wuerfel21** [comment]
i am, pretty sure

**Comment by fnuecke** [comment]
I'm afraid I have not been able to reproduce this in all this time. If someone can, and is capable of programming, I'd appreciate if they could have a look into this. Either way, until it's confirmed to still happen by a third party, I'm considering this closed.
