### ISSUE TITLE
Shell environments

### ISSUE THREAD

**Issue by rmellema** [MightyPirates/OpenComputers#634]
This has also been sad on the irc, but having shell environments would be really nice. This would allow people to write simple shell scripts or have a different `$USER` for each process for example.

All I know about implementation is that @fnuecke wanted to use the process API for this, but I don't know that much about OpenOS to be able to implement this myself.

**Comment by fnuecke** [comment]
> This has also been sad on the irc

Much sad. Thanks for the reminder ;-)
