### ISSUE TITLE
Feature Request: Camera Upgrade

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#64]
https://github.com/fnuecke/cccamera :D

**Comment by rmellema** [comment]
I second this. This peripheral is a great way to give people insight into what block they are dealing with, without breaking the fourth wall.

**Comment by MFernflower** [comment]
What about one for stationary computers too?

**Comment by fnuecke** [comment]
I might port it as an addon component, to serve as an example project or so. If anyone else wants to have a go at that, I'd be more than happy about that, since I can't say when I'd get to do it.

**Comment by asiekierka** [comment]
Computronics has Cameras, but they are not a Robot Upgrade (yet!)

**Comment by fnuecke** [comment]
Well they are now, and getting better all the time. Definitively use them. You can [find them here](http://mc.shinonome.ch/doku.php?id=wiki:computronics).
I or someone might still port my camera peripheral, but if anything that'll be to serve as an example. For functionality I'd recommend Computronics.
