### ISSUE TITLE
Confusing error on architecture removal

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#643]
When a CPU in the computer is set to an architecture that no longer exists, the error is reported:

```
Last error: No CPU is installed in the computer.
```

However, while this does make sense, it also doesn't because a CPU is present in the slot.
Perhaps a different error could be reported:

```
Last error: %s architecture is no longer available.
```

Which, is unlikely to affect new people because to have that happen, they would already know about the architecture system, had to have a mod giving one, and had to had switch the cpu to it.

**Comment by fnuecke** [comment]
Hmm, good point. The machine can't really tell the difference, though (`cpuArchitecture` returns `null` in either case), so I guess I'll just adjust the error string to be more generic. The name of the arch should still be in the CPU's tooltip, so something like "No CPU is installed in the computer, or the architecture it provides is no longer available" should be OK, I guess?

**Comment by gamax92** [comment]
Making more ambiguity is worse. If its not possible then stick with the original message which is more common.

**Comment by Techokami** [comment]
Wait, has someone actually made an architecture addon for OC 1.4 already??
