### ISSUE TITLE
Copy and Paste

### ISSUE THREAD

**Issue by RedefiningReality** [MightyPirates/OpenComputers#644]
This is just a suggestion, but I would really like to be able to copy and paste the code I write on my computer or robot, so that I can paste it into another lua file, or edit it outside of minecraft. I'm not sure how hard this would be to do, but I find it annoying when I am trying to move a piece of code from one file to another and I have to retype it. Thanks!

**Comment by Vexatos** [comment]
The thing is, IRL you do not have a virtual clipboard in your hand to copy Lua files. Floppy Disks are there for a reason.

**Comment by fnuecke** [comment]
IRL you also cannot paste code from magically nowhere ;-)

So - for finite-sized snippets - I agree this could be a very time-saving thing. However, there are some things to keep in mind with this. For one, there's no "selection" concept right now, so what would get copied? Next, even if there were, the _server_ would have to copy that text to a _client_'s clipboard for pasting to work homogeneously. If this isn't done _very_ carefully it could pose a major security risk.

Therefore I'm thinking the most sensible solution would be something like the Windows console's "mark" mode (yes, I know I'm a horrible person, even though they weren't testing for it). That is, clients could enter a mode where they can - in the their _local_ GUI, i.e. no other clients would see it - select an area of the screen, and then copy that text to their local clipboard.

**Comment by Vexatos** [comment]
It should have a limit, however, for example 32 characters maximum. Again, Floppy Disks are there for a reason.

**Comment by RedefiningReality** [comment]
Thanks for the input. The mark mode idea sounds great, but I guess I'll just have to stick with using floppy disks for now.

**Comment by Vexatos** [comment]
Another idea, @fnuecke: New item called "Clipboard", well, shift-click onto a screen or keyboard to copy the currently entered text; rightclick onto screen/keyboard to paste. Limited character amount, again, of course.

**Comment by Jeb1945** [comment]
Does this feature is avalid?

**Comment by SzuperTNTAkos** [comment]
> It should have a limit, however, for example 32 characters maximum. Again, Floppy Disks are there for a reason.

The issue is, that if i want to use the code I wrote on an opencomputer in a different world or even outside of minecraft, it's pretty much impossible. If there was a "cliboard" block that could only accept floppies to copy some text from them, to your computer's clipboard. This would make it nescessary to use a floppy very time you want to copy stuff anyway, so it wouldn't make it too overpowered.
