### ISSUE TITLE
Priority in NamedBlock being ignored

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#645]
It appears that the component will always have the name of the NamedBlock you registered first, no matter what the priority is. Tested with 3 different NamedBlock environments on the same TileEntity.
Order of registration: A, B, C
Order when sorted by priority (from high to low): C, B, A
Name chosen in the end: A.

**Comment by fnuecke** [comment]
Hmm, could you try if maybe the sort order is just the wrong way around? I.e. invert your priorities, see if C is chosen?

**Comment by Vexatos** [comment]
Can confirm the order is inverted. Set C to -1 and it got chosen.
