### ISSUE TITLE
Antivirus dislikes your libraries

### ISSUE THREAD

**Issue by applejag** [MightyPirates/OpenComputers#65]
I made a world in survival for testing and setup a OC computer, but when I tried to boot the machine it said in the chat "native libraries not available". At the same time my anti virus alerted me that a file might damage the system, and it aimed at this file
`C:\Users\name\AppData\Local\Temp\OpenComputersMod-native.64.dll`

The antivirus says
**Category:** Trojan
**Description:** This program is dangerous and runs commands from an attacker.
**Recommended act:** Remove immediately.
**More info about this object online:** http://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fRepplock&threatid=2147680292

**Comment by applejag** [comment]
Idk man, I trust you so I'll add it to the list of files to ignore...

**Comment by fnuecke** [comment]
This has been mentioned on the forums before, and [as I posted there](http://www.minecraftforum.net/topic/2201440-opencomputers/page__st__180#entry27597784) each and every virus scanner didn't have an issue with the library when submitting it. I invite you to upload the DLLs yourself, but I promise I just uploaded them as they are in the ZIP files. I also invite you to try this on other online services, that was just the first google result.

Thanks for reporting this, though. I'll file a false positive report.

**Comment by fnuecke** [comment]
Or I would... can you tell me [which of these](http://www.microsoft.com/security/portal/vendor/falsepositive.aspx) triggered the warning? (Windows Defender, MSE, ...?)

**Comment by applejag** [comment]
I am using MSE (aint windows defender and MSE the same thing for different OS versions?)

**Comment by fnuecke** [comment]
OK. And yeah, that's what I thought, but they list them separately... can you also tell me the version of your definitions (see above link) for the report?

**Comment by applejag** [comment]
Dont really know what to do, I fill in the forms and press submit but it gives me this
`Unexpected failure to submit form. Please retry operation.`

**Comment by fnuecke** [comment]
I was referring to

> 1. On the Help button Defender Help Button, click the arrow, and then click About
> 2. Locate the Definition Version number and type the number into the form.

But skip the "type the number into the form" part and tell me that number instead ;) Sorry for being unclear.

**Comment by applejag** [comment]
Ah ok I see :P 
109.61.0.0

**Comment by fnuecke** [comment]
Thanks!

**Comment by applejag** [comment]
Sigh and now I am having trouble downloading the file cause my browser (Chrome) says "A virus was detected"

**Comment by applejag** [comment]
I think it is cause the file I set to ignore was in the temp folder, so when I closed minecraft MSE had nothing to relate to so it called it a threat again

**Comment by fnuecke** [comment]
It's weird, because my MSE doesn't say a thing. And it'd be quite helpful if I could reproduce it so I know when it's gone... just manually updated the definitions and still nothing. What version of Windows are you running?

**Comment by applejag** [comment]
Windows 7 Enterprice with MSE version 4.4.304.0

**Comment by fnuecke** [comment]
Well that's just brilliant. Guess what I'm running? All right, Professional instead of Enterprise, but other than that it's the same, including the version number. Let's see what Microsoft says... if anything.

**Comment by applejag** [comment]
On the enterprice computer I had that message from MSE, now tested on my Windows Professional computer and guess what; no message. Seems to me theres something special about enterprice (obviously)
