### ISSUE TITLE
More POSIX features in default shell

### ISSUE THREAD

**Issue by PowerOfTech** [MightyPirates/OpenComputers#650]
Please add Pipelines ('|', '&&')  and Streams ('>' ,'>>', etc.).

**Comment by LizzyTrickster** [comment]
Have you looked at Besh?

## 

Josh Green

Sent from my Surface Tablet

From: PowerOfTech
Sent: ‎Tuesday‎, ‎4‎ ‎November‎ ‎2014 ‎15‎:‎05
To: MightyPirates/OpenComputers

Please add Pipelines ('|', '&&') and Streams ('>' ,'>>', etc.).

**Comment by fnuecke** [comment]
Indeed, besh has most of these, and was working last I tested it IIRC. I may or may not look into adding this the default shell at some point, now that OpenOS requires way more RAM than the minimal RAM bar anyway. We'll see.
