### ISSUE TITLE
False? False False False OC GT Issue

### ISSUE THREAD

**Issue by Suterusu1337** [MightyPirates/OpenComputers#651]
In prior version of OpenComputers/Components, I used OpenComponents with an adapter on a GT battery buffer.  With this I pulled stats from the batteries in the buffer, calculated the EU current and EU max and had a nice display for it all:

http://imgur.com/a/glx1v

My modpack recently updated and we are on: OpenComputers-MC1.7.10-1.4.0.6-rc.1-universal

Now, a lot of the methods I used are gone, but there are new ones....  The way I manually had to get the battery information has been replaced with methods for getting the information directly.

(Sorry, I don't know the markdown code for making this appear LUA scripted)
OLD:

``` lua
local function getStoredCharge(c)
    local inv = c.getAllStacks()
    local storedCharge = 0
        local maxCharge = 0
        local differenceCharge = 0
    for i = 1, c.getInventorySize(), 1 do
                if inv[i] == nil then
                else
            storedCharge = storedCharge + inv[i].charge
                        maxCharge = maxCharge + inv[i].maxCharge
                        end
        end
        maxCharge = maxCharge + c.getEUCapacity()
    storedCharge = storedCharge + c.getStoredEU()
        if previousCharge > storedCharge then
                differenceCharge = 0
                previousCharge = storedCharge
        else
                differenceCharge = 1
                previousCharge = storedCharge
        end
    return maxCharge, storedCharge, differenceCharge
end
```

NEW:

``` lua
local function getStoredCharge(c)
 --   local inv = c.getAllStacks()
 --     Damnit where is my ability to check the battery buffer inventory size???
        local bat = c
        local invSize = 4
    local storedCharge = 0
        local maxCharge = 0
        local differenceCharge = 0
    for i = 1, invSize, 1 do
                if bat.getBatteryCharge(i) == nil then
                else
            storedCharge = storedCharge + bat.getBatteryCharge(i)
                        maxCharge = maxCharge + bat.getMaxBatteryCharge(i)
                        end
        end
        maxCharge = maxCharge + bat.getEUCapacity()
    storedCharge = storedCharge + bat.getStoredEU()
        if previousCharge > storedCharge then
                differenceCharge = 0
                previousCharge = storedCharge
        else
                differenceCharge = 1
                previousCharge = storedCharge
        end
    return maxCharge, storedCharge, differenceCharge
end
```

Now, the issue is, the screen _flickers_ every time it refreshes (never did this prior to the update) and EVERY time it flickers, the server log is spammed with "false", it appears to be equal to the number of batteries in the battery buffer.  So when I run the EU update to refresh the screen, something is evaluating false and appearing in the server log....  The worst part is, the program is _working_ per say, the screen updates the EU values, but I cannot have the log filling up with OC errors.  Maybe this always had an issue and never reported it to the log in the old version of OC, unsure...

```
6:29:15 PM  CONSOLE: [INFO] false
6:29:15 PM  CONSOLE: [INFO] false
6:29:15 PM  CONSOLE: [INFO] false
```

Full code, old version: http://pastebin.com/eqTdt3Fd

Full code, new version: http://pastebin.com/bQEAQpKf

**Comment by fnuecke** [comment]
I'm 99.9% sure this isn't logged by OC itself, but some other mod (I just did a quick search for any info / plain logs and even printlns, nothing that could produce this). So I'm also guessing this might be some weird interaction with another mod.

But just to cover the bases: the screen isn't getting a redstone pulse, perchance (or two, rather, the first turning it off, the second on again)? You're also sure it's not a temporary power outage? (Blocks in 1.4 accept different amounts of energy/tick, so unless you have a creative case in there for testing, try feeding the computer system using a power converter).

PS: FTFY. For future reference, the markdown is

<pre>
```lua
code
```
</pre>

**Comment by Suterusu1337** [comment]
Nothing on my side has changed, I will test with different power input methods, however I run the computer off of a capacitor (OC) which I would think should work to buffer the power.

GT Power rail -> power converter -> capacitor -> PC case

The log still says "false" for every battery in the buffer, which can range from 1-16.  Having 16 lines of "false" every time it iterates through and pull the battery power is a bit blah.

**Comment by fnuecke** [comment]
Well it shouldn't be the power then, sure. As for the log spam, of course that shouldn't happen; but as I said, I'm quite certain it's not OC doing that.

**Comment by Suterusu1337** [comment]
I understand it shouldn't be OC doing it, but it happens when OC iterates through the battery buffer and it happens for the exact amount of batteries checked.

Would there be any other indication of mod interaction that would be throwing this log event?

Other than GT and Forge, I don't see how another mod would play into a method I used from OC itself.

**Comment by fnuecke** [comment]
I'm pretty sure this is [Computronics' driver](https://github.com/asiekierka/Computronics/blob/master/src/main/java/pl/asie/computronics/integration/gregtech/DriverBatteryBuffer.java#L51) printing that message.

@Vexatos mind removing your debug prints? ;-)

**Comment by Suterusu1337** [comment]
Ah yes, already closed but my code checks for if the slot is null or not, I don't need extra console output for it :)

**Comment by Vexatos** [comment]
@fnuecke Already did that, derp. [It's gone for weeks now](https://github.com/asiekierka/Computronics/blob/OC14/src/main/java/pl/asie/computronics/integration/gregtech/DriverBatteryBuffer.java#L56), just need to release the next Computronics version.
