### ISSUE TITLE
Sign Driver should be disabled by default

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#653]
The [Sign Driver](https://github.com/MightyPirates/OpenComputers/blob/OC1.4-MC1.7.10/src/main/scala/li/cil/oc/integration/vanilla/DriverSign.java) should be disabled by default (and thus get a config option) because it removes the need for a robot [Sign Upgrade](https://github.com/MightyPirates/OpenComputers/blob/OC1.4-MC1.7.10/src/main/scala/li/cil/oc/server/component/UpgradeSign.scala) which does the exact same thing.

**Comment by fnuecke** [comment]
Hmm, shouldn't it be more like the inventory/tank controller, i.e. enabled in adapter only if sign upgrade is placed into it? Otherwise I don't quite agree :-P

**Comment by Vexatos** [comment]
@fnuecke That's probably how it should work. :+1:
