### ISSUE TITLE
Robot upgrade that will allow the robot to "learn" and then "recognize" objects in it's environment

### ISSUE THREAD

**Issue by jpastuszek** [MightyPirates/OpenComputers#654]
The upgrade would add API that would allow robot to "learn" objects in front (up and down) of it and store it's characteristics (name, meta data etc.) in selected "memory bank".
There would be say 16 such banks.
Robot API then could be used to compare objects in front (up and down) with selected bank and return if they are the same as learned or not (true/false).

This way we wound not need to know any implementation details about objects in the world (like in case of geoanalyzer.analyze?) or "real" objects would not to be stored in the inventory but still will be able to say for instance if the object under the robot is wheat in last growth stage.
Also this adds new game play element where you "teach" your robot how to recognize different things.

Additionally there could be different levels of object similarity that could be detected. For instance only check for names to match or name + metadata, etc. so that you can say for instance if this is wheat or not no matter the growth stage.

Implementation wise robot would only need to keep hashes of data (name, name + meta, ...) since data would never need to be displayed to the user so it should be relatively fast and of small footprint.

**Comment by fnuecke** [comment]
There's been discussion about something similar in #649, although that will be purely for item stacks. There is no 100% guaranteed way of knowing how a block relates to an item stack because many mods have very custom code when it comes to dropping an item stack representation of a block when it is harvested, so I'm not sure how well this applies to what you imagine, but unless this is something else or something more, I guess it'll be covered assuming this approach is taken for the above linked issue?

**Comment by jpastuszek** [comment]
Since items can be picked up and stored in inventory for further comparison this upgrade would only be for blocks or other entities (as placed in the world - not picked up or stored and not floating around items).
The idea here is that robot would not pick up or store anything apart from information about the block that is in front of it. This information could be than compared with same information about another block that is in front of it at later stage (and not stored block in the inventor although that could also be useful).

This way for example if it "learned" that in front of it there was a gravel block, than after it moved somewhere else and compared this information with another block in the wold that is in front of it it could tell if that is also gravel (true) or something else (false).
Here note that it would not need to store gravel block in it's inventory - just information about what it "seen" when it was "learning".

**Comment by jpastuszek** [comment]
API usage could look like this:

You place our robot in front of unmined iron ore block (somewhere in your mine).
In lua console you do:

``` lua
component.holomemory.learn(1) -- learn iron ore block in bank 1
```

Than you pick up your robot and place it somewhere else and run it's mining program that could include:

``` lua
if component.holomemory.recognize(1) then
  -- it is iron ore block; mine it!
end
```

**Comment by fnuecke** [comment]
Hmm, so you suggest `geolyzer.analyze` should be removed in favor of some "database" component (like the one in the above referenced issue but for blocks, not item stacks)?

**Comment by jpastuszek** [comment]
`geolyzer.analyze` is more powerful version of the "database" component since it gives you access to the metadata values themselves witch may be useful. Perhaps this should be on different tiers.

**Comment by fnuecke** [comment]
Hmm, I dunno. On the one hand it'd fit with the database component concept, on the other there's still the converter based item descriptor that's available for item stacks via the inventory controller (and database component for stored stacks), which is pretty much the equivalent of `geolyzer.analyze`.

**Comment by jpastuszek** [comment]
The database component would be much simpler to use then `geolyzer.analyze` since it will pretty much cosist of two functions when one returns true/false while it still would be a very powerful tool. So it would be much in pair with `robot.detect` interface wise rather than `geolyzer.analyze`.
The down side is that you cannot actually see the values of metadata, name etc. so in 10-20% of the cases you still need `geolyzer.analyze` for advanced scenarios.
So I think that  `geolyzer.analyze` should definitely stay since it gives you the ultimate power of analyzing your environment but it should come with hight energy/tier cost. Also it is, as you say, an equivalent component to inventory controller so there is nice symmetry here.
While the database component having very simple to use interface would be useful on lower tier (2?) since it is pretty much more powerful version of `robot.detect` yet still as simple to use.
I think the concept is interesting but I would not like it to replace `geolyzer.analyze` since it is still more powerful. Also the concept of database and (AI?) learning are very cool terms in computer world. On the other hand having too many components that basically overlap with their usage may not be good in the long term.
Perhaps you should point more eyes on this one so people can have their opinion.

**Comment by fnuecke** [comment]
The overlap is exactly the problem I'm seeing here. Given .analyze remains, I don't expect anyone to use a more limited approach, really (the difference with the database component being that it internally also stores NBT data which is why it was added in the first place), so I don't feel it'd be worth the effort implementing it in the first place, to be honest.
And sure, I'll mention this issue on IRC to get some more feedback.

**Comment by jpastuszek** [comment]
Implementation wise with databases component you would need only store few bytes of hash of block data since you don't need to know the exact details - just if they differ/are the same; still they need to be saved somewhere probably in similar fashion of floppy or hard drive so the information persists.
Perhaps if you make `geolyzer.analyze` a tire 3 component and database tier 2 component it may still be used (while `robot.detect` is available since tier 1 by default)... let's see what people think about this.

**Comment by jpastuszek** [comment]
I guess item stack representation will have to do for now.
I will give it a try when you make a full release.
Thank you very much for this super cool and high quality mod!

**Comment by ebragas** [comment]
I stumbled across this issue when doing some research for a automated farm project. What I am looking to accomplish is as simply as possible detect the metadata (crop growth state) of a block.

So far, the only option is to use a geolyzer, which is quite expensive compared to the rest of the components required to accomplish this task. This method, combined with a database, would be allow a robot to read in the block data and metadata for later comparison.

If this is interesting enough, I'd be happen to open another issue.

Thank you!

**Comment by gjgfuj** [comment]
I do agree that the robot should be able to compare world blocks (even if
not exposed, just the ability to say... Read a few blocks and see if block
there is the same as block here).

**Comment by Vexatos** [comment]
> the only option is to use a geolyzer, which is quite expensive

That is not really a good argument. Comparing blocks is pretty powerful, so it makes sense to cost a little. And it's not that expensive.
