### ISSUE TITLE
[Suggestion] Allow TileEntites to wrap ManagedEnvironments

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#659]
Basically, have an Interface like [Block](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/java/li/cil/oc/api/driver/Block.java), but to put onto a TileEntity. That should make the TE be recognized as if it was an instance of Environment, just that it has to implement the same methods the Block Interface has. This would allow TileEntites to create ManagedEnvironments and thus expose certain callback functions depending on various clauses.

**Comment by fnuecke** [comment]
As mentioned on IRC, you can either use `ManagedPeripheral` or a custom environment class for this. For the latter, the code could look something like this:

``` java
class CustomTE extends TileEntity implements Environment {
  private Environment customEnv = new CustomEnv1();

  public Node node() { return customEnv.node(); }

  private void switchEnv() {
    node().disconnect();
    customEnv = new CustomEnv2();
    api.Network.joinOrCreateNetwork(this);
  }

  private static class CustomEnv1 implements Environment {
    // what env related logic you'd usually have in your TE
  }
  private static class CustomEnv2 implements Environment {
    // alternative callbacks etc
  }

  // Note these will never be called, because this isn't the direct host of the returned node.
  // If you have common behavior in these, just call them from CustomEnv1/2's corresponding methods.
  void onConnect(Node node);
  void onDisconnect(Node node);
  void onMessage(Message message);
}
```
