### ISSUE TITLE
Abstract Bus card will not compute

### ISSUE THREAD

**Issue by LizzyTrickster** [MightyPirates/OpenComputers#661]
The Abstract Bus Card cannot be placed in any slots of computer cases / servers / robots which kinda makes it redundant

OC Version: OpenComputers-MC1.7.10-1.4.0.209-dev-universal
StargateTech2 version: stargatetech2-Alpha-0.7.5-MC1710-Forge1232-B4-UnOfficial

**Comment by LizzyTrickster** [comment]
Tried on latest versions of both (oc dev 223, stargatetech 0.7.5 official ) and still not able to put de card in teh pc

**Comment by fnuecke** [comment]
Thanks. Forgot adding init call while refactoring... much derp. Should be fixed in next build!
