### ISSUE TITLE
Can't push 8-bit clean byte arrays onto the Lua stack

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#662]
Lua strings are 8-bit clean but what's the point if we can't use them that way?

**Comment by fnuecke** [comment]
[`Arguments.checkByteArray`](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/java/li/cil/oc/api/machine/Arguments.java#L108) gives you the raw binary data when reading, returning `byte[]` from callbacks pushes them as is back to Lua.

**Comment by SoniEx2** [comment]
Well @Vexatos said he couldn't get it to work...

**Comment by Vexatos** [comment]
I could. I just had to Base64 encode it, it wasn't liking Java's UTF-8.

**Comment by SoniEx2** [comment]
> it wasn't liking Java's UTF-8.

Whut?! I said it already and I'm gonna say it again, that makes no sense.

**Comment by fnuecke** [comment]
I don't know what the context is, but I'm guessing Computronics' cipher block / RSA stuff? In that case I'm also not quite sure where you'd need actual strings (i.e. something with an encoding) as opposed to plain byte arrays?

**Comment by SoniEx2** [comment]
@fnuecke I thought Lua strings were immutable plain byte arrays?

**Comment by Vexatos** [comment]
Why don't you just leave it be? As I said, I got it working.

**Comment by SoniEx2** [comment]
@Vexatos what if I want to manipulate it from Lua? having to convert it from b64 then back is a pain.

**Comment by Vexatos** [comment]
You are not supposed to do that anyways.

**Comment by SoniEx2** [comment]
@Vexatos like I ever do things the way I'm supposed to...

**Comment by fnuecke** [comment]
Well, if it's working I don't see a point in discussing this further.
