### ISSUE TITLE
RF power input eating infinite amount of energy

### ISSUE THREAD

**Issue by magik6k** [MightyPirates/OpenComputers#663]
Any input of RF power isn't limited in any way. i.e. all machines eat whole RF that is offered to them:

![1.9MRF/t](http://i.imgur.com/ttREu9G.png)
Yep this is power converter eating 1,9MRF/t(my max energy output), all other OC 'powerable' blocks behave in the same way.

Same happens for energy input like EIO conduits, the only 'narmally' working configuration is TE cell placed by OC energy input

I'm using OC build from jenkins: OpenComputers-MC1.7.10-1.4.0.223-dev-universal.jar

**Comment by fnuecke** [comment]
Thanks, should be fixed in next build!
