### ISSUE TITLE
Server Rack Rendering Bug

### ISSUE THREAD

**Issue by Keridos** [MightyPirates/OpenComputers#665]
The HDD LED for the server rack renders wrong if you put a server in the bottom slot and then turn it on. The HDD LED renders as if the server was in the top slot. Power LED is fine.

**Comment by LizzyTrickster** [comment]
I had this before with a few of my servers, did you clone (middle click / control + click with NEI) them when putting them in the rack? Cause that's what happened to me when I cloned them

**Comment by Keridos** [comment]
No, this is a survival mode, If I correctly understood what you mean with cloning.

**Comment by LizzyTrickster** [comment]
Ah, then this is a different issue entirely, have you tried breaking and replacing the rack to see if it still has the problem and/or move it to a few blocks away and see if it still has the same error

**Comment by Keridos** [comment]
Still persists, did not think that would fix it though. It's probably just a minor derp in the rendering code.
