### ISSUE TITLE
Better GregTech tools integration

### ISSUE THREAD

**Issue by Namarius** [MightyPirates/OpenComputers#666]
The durability and charge of GregTech tools should be readable like any other tools. I know that the GregTech API provide some functionality for this.

I had tried to implement this by myself for OC1.3 branch, but I had some problems with creating the eclipse project.

**Comment by fnuecke** [comment]
Don't GT tools provide rough durability information like the IC2 ones do? And to get the actual charge you can use the inventory controller (which at least works for IC2 items, so I had assumed it would also work for GT items).

If I'm wrong on both accounts, please let me know which GT tool in particular I can reproduce this with so I can have a go at it, thanks!

**Comment by Namarius** [comment]
Well not completely wrong the IC2 part is correct.
Here is a list for GregTech tools:

Non electric tools in inventory contoller: durability not readable
Electric tools in inventory controller: durability not readable; charge readable
Non electric tools in robot: [ nil , "tool cannot be damaged" ]
Electric tools in robot: [ nil , "tool cannot be damaged" ]

As a note: GregTech tools have durability even if they electric.

**Comment by fnuecke** [comment]
Huh, interesting. I'll look into it!
