### ISSUE TITLE
No Control Unit crafting recipe with NEI and/or Craftguide

### ISSUE THREAD

**Issue by Pyrolusite** [MightyPirates/OpenComputers#67]
The crafting recipe for the Control Unit (needed for the Central Processing Unit) is not displayed with NEI (1.6.1.8) and Craftguide (1.6.7.4).

I first though they were only found in dungeon chests, but since I can't find anything about this on the wiki and on the MCF thread so far...

EDIT : I was not using both at the same time, by the way.

**Comment by ghost** [comment]
I use NEI 1.6.1.8 and no problem. (And not use Craftguide)

Only Crafting issue has. (Grog and PCB are uncraftable in ME Crafting Table, when i craft it -> server kick me)

**Comment by fnuecke** [comment]
Can't reproduce. I could reproduce what @EcmaXp mentioned though, and fixed it.
@Pyrolusite what version of OC is this with? 1.0.5(a) or one of the 1.1 prereleases?

**Comment by Pyrolusite** [comment]
@fnuecke OC 1.1.0 pre 4, and it seems it's the only recipe missing.
I remember having it with older versions of OC, though.

**Comment by fnuecke** [comment]
Is it still craftable and just doesn't show up in the list? Does it show up in the list of the vanilla creative GUI? Is there anything in the log? If a recipe fails to load it should be logged.

**Comment by Pyrolusite** [comment]
I don't know its crafting recipe to begin with, so I have no idea how to craft it, but I can use it to craft the CPU, It does show up in the creative GUI, in NEI and Craftguide, and nothing about recipes in the log. In NEI, the crafting recipe for the CPU shows up from the CU (U/Right click), but the recipe for the CU in itself doesn't show up (R/Left Click).

**Comment by fnuecke** [comment]
Default Control Unit recipe:
![Control Unit](http://i.imgur.com/z4moz6X.png)

**Comment by Pyrolusite** [comment]
Some progress : I can't craft it, and the recipe for the transistors doesn't show up too, even if they exists in the creative GUI, NEI and Craftguide and I can craft things with it.

**Comment by fnuecke** [comment]
Could you please compare the recipe file `<yourconfigfolder>/opencomputers/default.recipes` with the one [in the repository](https://github.com/MightyPirates/OpenComputers/blob/master/assets/opencomputers/recipes/default.recipes#L156)? If they match and there's nothing in the logs I'm somewhat out of ideas.

**Comment by Pyrolusite** [comment]
I just replaced everything in the default.recipes by the repository version, nothing changed.
I also deleted all my config files for every mod I have, and still nothing.

Okay, I just had a bunch of recipe errors from the log : 
http://pastebin.com/1ffSu2Fw
Hope this helps

**Comment by fnuecke** [comment]
It does help, seems like some entries aren't in the ore dictionary per default we assumed that were. Thanks for reporting this!

**Comment by Pyrolusite** [comment]
You're welcome, glad it helped!
