### ISSUE TITLE
Install should be able to install 'packages' from floppies/hdds

### ISSUE THREAD

**Issue by magik6k** [MightyPirates/OpenComputers#672]
The install program should be able to install adnitional software from floppies/whatever, i.e. We have a floppy with tools that require installing in OpenOS(boot sctipts/libs, etc.), the syntax would be like `install somepackage` for installing package, and `install` for clonning boot disk.

I have few concepts on how it would package detection work:
1. When user attempts to install package, install looks for disk with label that is name of package
2. Install looks for some file in root directory of filesystems i.e. `package` that contains name of package, if name matches, files from disk are installed
3. Better version of 2 - Install looks for package index i.e. user wants to install `somepackage`, the program should look for `somepackage.pack` file on disks, when it finds it, it should read the file to get list of files to install OR execute it with some parameters like installation point

I wanted to implement the feature and PR it(and I still may do it), but I think some discussion on it is needed

**Comment by fnuecke** [comment]
One possible way of going this, as discussed on IRC, would be to allow passing parameters to `install.lua` that determine the install source and program name (for display reasons only), and then a loot disk can have a minimal install script itself that just delegates. This script may look something like this:

``` lua
os.execute("install --name='Fancy Thing' --from=" .. filesystem.get(process.running()).address)
```

Considerations:
- A `to` parameter (`--to=/usr/bin`)? Or just default to `/usr` for custom (i.e. non OS) installs?
- An exclude filter (`--exclude='install.lua,other.thing,examples/'`)? (only thing that immediately comes to mind is the mini install script itself, but may include example code, readme in non-manpage format, ...)?
