### ISSUE TITLE
Both hologram projectors crash the game

### ISSUE THREAD

**Issue by tojohawk** [MightyPirates/OpenComputers#673]
Both tiered hologram projector crash the game in both SSP and SMP

**Comment by magik6k** [comment]
Crashlog, steps to reproduce, build/version, whatever?

**Comment by fnuecke** [comment]
Cannot reproduce. As magik6k said, at the very least I need a crash log to investigate this.

**Comment by tojohawk** [comment]
Issue seems fixed, apparently. Sorry to waste your time.
