### ISSUE TITLE
OpenComputers tends to crash Intel Graphics drivers

### ISSUE THREAD

**Issue by MFernflower** [MightyPirates/OpenComputers#68]
I do not have a Intel chipset. I have an AMD. But my friend Kalle (jilleJr) does and he crashes when he is changing the color of a monitor's text (advanced and superior) 
for example this causes him a crash:

component.gpu.setBackround(0x140000)
print("Hello World!")

Crash Report: http://pastebin.com/eFuYh4vE

**Comment by applejag** [comment]
Does not crash from screen text, only background text. And this happens on all screen types

**Comment by fnuecke** [comment]
Thanks for the report :-)
But please let's keep this in one place, #31, since I'm fairly certain it's the same thing. I changed that issue's name to make it more generic.
