### ISSUE TITLE
install.lua causes a OutOfMemory Error

### ISSUE THREAD

**Issue by PowerOfTech** [MightyPirates/OpenComputers#682]
install.lua causes a OutOfMemory Error when launched with 1xTier 1 memory.

**Comment by Vexatos** [comment]
That's known and not fixable. Go get a Tier 2 memory stick (or multiple tier 1.5 ones), or make/use a smaller OS.

**Comment by fnuecke** [comment]
Indeed. I'm surprised it boots at all with one T1 :-P
Alternatively consider OSes others have built that supposedly require less RAM.
