### ISSUE TITLE
CC mode

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#684]
I want a mode that changes all features to match CC, more specifically: no power usage, EGA colors, no RAM limit, etc

**Comment by Vexatos** [comment]
The mode is already in, here's how to do it:
1. Open your /mods folder
2. Delete OpenComputers-something.jar
3. Go to http://computercraft.info/download
4. Download ComputerCraft
5. Place the jar file you downloaded into your /mods folder
6. Launch Minecraft

You're welcome.

**Comment by SoniEx2** [comment]
But that would have CC's bugs and shitty tech support, and wouldn't be open source

**Comment by Vexatos** [comment]
You said you wanted a full CC mode.

Seriously, this shouldn't be in OC and probably would be too hard to do to be worth it.

**Comment by SoniEx2** [comment]
No I said "features", bugs and open source aren't features, just details

**Comment by fnuecke** [comment]
All possible via the config file (ignorePower, disableMemoryLimit) and color palettes (t2+ graphics card).

**Comment by SoniEx2** [comment]
What about the cheap recipes?

**Comment by fnuecke** [comment]
Sure. See `config/opencomputers/user.recipes`.
