### ISSUE TITLE
Hologram Projector Crash (With logs and additional info)

### ISSUE THREAD

**Issue by tojohawk** [MightyPirates/OpenComputers#685]
http://pastebin.com/13w8nEUp

Hologram Projectors crash upon placement into my world. I am using Multimc, ssp creative mode, in version 1.7.10 with the following mods:
Applied energistics 2
Bibliocraft
Blood Magic
Botania
Carpenter's Blocks
Chisel
CodeChickenCore
EnderIO
Extra Utils
Fastcraft
Hardcore Ender Expansion
InventoryTweaks
Mekanism + Generators + Tools
Minetweaker 3
NEI
Openblocks (With openmodslib)
Opencomputers (Obviously)
Railcraft
Ruins
Thaumcraft
Thaumic Tinkerer
Tinker's Construct (With Mantle)
Zombie Awareness

Any additional info may be requested.

**Comment by fnuecke** [comment]
I'm afraid that log snippet doesn't contain any useful information; there should be a crash log (displayed in your launcher after the crash and saved in the `crash-reports` directory). That would be more helpful.
That will also contain the versions of the mods, which would also be good to know.

Aside from that, please try if this also happens in the [latest build](http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/) (get the `universal` one). If you weren't on OC 1.4 already, beware that you won't be able to downgrade to OC 1.3 without losing OC blocks, so make a backup of your world (better to make one either way, anyway).

**Comment by tojohawk** [comment]
I'm only getting a hs_err_pid.log. Would it help to post that?

**Comment by fnuecke** [comment]
Maybe. Throw it up on pastebin or gist.

**Comment by fnuecke** [comment]
No response in over a week. Closing until further feedback is provided.
