### ISSUE TITLE
Ability to spoof source addresses

### ISSUE THREAD

**Issue by skyem123** [MightyPirates/OpenComputers#686]
I was thinking of the ability to make custom switches / routers using two servers in a server rack, but the problem was that you can not relay a message by spoofing the source address.
While you could work around this by using code on all computers on the network that implements more advanced networking (and this appears to be already done), it requires more set-up.

Spoofing source addresses can also be interesting as people would have to think more about security, making an idea about a "hacking game" possible.

**Comment by fnuecke** [comment]
While I'm not against adding this, and it should be fairly easy to add from what I can see, I'm wondering if maybe @Vexatos might want to add a spoofing card to Computronics? I think it'd fit well with the crypto block and such.

If so, all the component would have to do to send the message is pretty much this:

``` java
node.sendToReachable("network.message", api.Network.newPacket(spoofedSourceAddress, targetAddressOrNull, port, otherDataAsArray))
```

**Comment by Vexatos** [comment]
I'm on it.

**Comment by fnuecke** [comment]
Awesome :-)
