### ISSUE TITLE
Add HTTP request and response headers

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#689]
CC has request headers but OC could get both and be better than CC again. And then I wouldn't need shitty hacks or raw TCP sockets to get GitHub's API limit info. ♥

For response headers you could add an http_header signal (will be ignored by stuff that listens to http_response)

**Comment by fnuecke** [comment]
I've been planning to rewrite the HTTP request part of the internet card to use userdata for a while now. Checking response headers will make it in when I actually do.

**Comment by SoniEx2** [comment]
If you're working on it why close the issue?
