### ISSUE TITLE
Access to config values from API

### ISSUE THREAD

**Issue by Korynkai** [MightyPirates/OpenComputers#690]
Hello,
As a fellow mod programmer, I am looking for a way to access the OC instance's configuration values from within a different mod, specifically the value of terminalsPerTier as I am attempting to implement a Remote Terminal into another mod, as a modular tool. However, I see that (in Scala) you have an (instance) object Settings and a class Settings, but I see no way to access any values within either object from within the API. This is necessary if any other mods make use of config values that're globally specific to OpenComputers but should not/have no reason to be redefined.
I'm not sure if there's another way to retrieve these values outside the mod, but I can't seem to find it...

(Also, as such, I've noticed it may be a good idea to add accessor methods for the private members "terminals" under li.cil.oc.common.tileentity.ServerRack, "keys" under li.cil.oc.common.component.Terminal and "machine" under li.cil.oc.server.component.Server but I've found these are accessible through the "hackish" route of getDeclaredField and setAccessible)

**Comment by fnuecke** [comment]
Hmm, typesafe config is a standard lib loaded by Forge, so I guess I could just make the `Config` instance available via the API...

For now, if you don't mind linking against the full JAR instead of just the API (`:dev` instead of `:api` in the maven dep) the `Settings` class is public, so something like `Settings.get().terminalsPerTier()` should work I think.

All the fields you mentioned are already public. Just keep in mind they appear as methods to Java (i.e. you'd write `server.machine()`, e.g.).

**Comment by fnuecke** [comment]
Added a new IMC message that can be used to request OC's config object, use like so:

``` java
FMLInterModComms.sendMessage("OpenComputers", "requestSettings", "com.example.mod.integration.OpenComputers.setConfig")
```

Where the provided method (`setConfig` in the above) must be static and take a single parameter of type `com.typesafe.config.Config`. For a few settings you may want to apply the same sanity checks OC's `Settings` class does (e.g. that buffer sizes aren't negative, i.e. `Math.max(0, ...)` them).

**Comment by Vexatos** [comment]
I have actually just been getting the values from the Settings object directly, as Computronics has a compile dependency on OC anyways, so I assume I won't need this new method. Thank you for adding it, though.

**Comment by Korynkai** [comment]
Heh, yeah, after Sangar mentioned that Scala's values act like methods in Java I figured out my issues pretty quickly. I do know I'll make use of this method, either on this mod (to narrow if not eliminate compile-time deps if possible) or another I plan on working on in the future (and I thank you very much for implementing it)... 
However, now it seems I can't find any way of properly accessing the OC global instance to open the terminal GUI(?) Or is it just Scala's syntax confusing me again? Or perhaps is it somehow evading me some other way? ^_^'

**Comment by fnuecke** [comment]
Using the settings class directly is obviously the easier alternative (tho I can't promise I won't rename some of the settings fields when I have a sudden urge to refactor the living hell out of the mod again :P). Just added the IMC callback to be able to close this without having to tell people to use the non-API version ;-)

As for the OC instance, I'm assuming you mean the mod instance? You may have to use something like `OpenComputers$.MODULE$`. Not sure about which dollars go where, but that should be close. Alternatively you could use

``` java
cpw.mods.fml.common.Loader.instance().getIndexedModList().get("OpenComputers").getMod()
```

(I think that's correct, anyway).

**Comment by Vexatos** [comment]
> tho I can't promise I won't rename some of the settings fields when I have a sudden urge to refactor the living hell out of the mod again

Addon will crash, someone will report, hotfix will be released -> done.

**Comment by fnuecke** [comment]
Of course. I feel it's nicer to have an agreed upon API where such changes are clearly communicated, but linking against the mod itself is obviously always an option if you want to use it :-)
