### ISSUE TITLE
NEI not working after update

### ISSUE THREAD

**Issue by drago87** [MightyPirates/OpenComputers#691]
When i updated from OpenComputers-MC1.7.10-1.3.6.69-universal to OpenComputers-MC1.7.10-1.4.0.11-universal NEI stopped working alltogether. As in no NEI to the right no Creative+ no utility mode or eny way to change it. The game starts normal and i'm not getting eny error that i can see. If you want i can post a pastebin off my Game output and Launcher log befor/after update.

**Comment by LizzyTrickster** [comment]
Have you tried pressing "o" whilst in your inventory? It might have been
that you accidentally disabled it

On 26 November 2014 at 13:29, drago87 notifications@github.com wrote:

> When i updated from OpenComputers-MC1.7.10-1.3.6.69-universal to
> OpenComputers-MC1.7.10-1.4.0.11-universal NEI stopped working alltogether.
> As in no NEI to the right no Creative+ no utility mode or eny way to change
> it. The game starts normal and i'm not getting eny error that i can see. If
> you want i can post a pastebin off my Game output and Launcher log
> befor/after update.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MightyPirates/OpenComputers/issues/691.

## 

Regards,
Josh Green

**Comment by drago87** [comment]
tried that and the ony thing that fixed it was to downgrade the mod. (had to disable all my 200+ mods and anable them one by one untill i found what mod did it)

**Comment by fnuecke** [comment]
Which version of NEI are you on? I tested with 1.0.3.60 and 68 (currently latest) and had no issues of the sort.

**Comment by drago87** [comment]
NotEnoughItems-1.7.10-1.0.3.68-universal
also using forge-1.7.10-10.13.2.1236
i can zip/rar my mods and configs if that would help

**Comment by fnuecke** [comment]
Sure. Before that, to potentially save yourself the bandwidth, try starting a new creative world though, because if it works there it's probably because you're in a non-cheat world (if you're on a server, are you sure you're op?)

**Comment by drago87** [comment]
I have tried both creative and survival no difference.
Also babandwidth is not problem for me have 100/100 line with unlimited bandwidth/month

I've done some updating off mods so going to try it once more before upploading

--EDIT--
Nope no difference here is the rar
The 1.3.6.69 is enabled and the 1.4.0.11 is disabled (added .disable after the .jar)
https://www.dropbox.com/s/7k5tblag27zdw5s/Opencomputers%20w%20outher%20mods%20and%20configs.rar?dl=0

**Comment by fnuecke** [comment]
Caused by outdated OC API in DragonAPI, remove the `li` directory from that JAR for now.
