### ISSUE TITLE
geolyzer.analyze scanning wrong sides on robot

### ISSUE THREAD

**Issue by Nibato** [MightyPirates/OpenComputers#693]
When the robot is facing east or west (direction reported in F3 hud), geolyzer.analyze() scans the opposite direction passed to the first argument. sides.right will scan the left block, sides.front will scan the block behind the robot, etc.

However, when the robot is facing north or south, geolyzer.analyze() scans the sides properly. sides.left will scan the left block, etc.

up/down seem to always work properly though.

![2014-11-26_18 38 41](https://cloud.githubusercontent.com/assets/102328/5210783/3017774e-75a1-11e4-8c64-7ee93cbd443f.png)
![2014-11-26_18 38 39](https://cloud.githubusercontent.com/assets/102328/5210785/33a00232-75a1-11e4-9960-ec03ba51b369.png)

**Comment by fnuecke** [comment]
Thanks! Mixed up the coordinate system translation direction. Derp.
