### ISSUE TITLE
Additional ways to manipulate database components

### ISSUE THREAD

**Issue by iambob314** [MightyPirates/OpenComputers#695]
Given the issues presented in, e.g., #649, the new database component makes sense. However, as noted in its mouseover text, currently its contents can only be manipulated manually with the exception of a full database clone(), which makes teaching computers to "learn" database items impossible.

A two-part proposal: expand the Inventory Controller component to interact with the Database component, and expand the Database component to allow fine-grained manipulation:

Inventory Controller:
- Add invcontroller.copySlotToDatabase(side: number, slot: number, db: addr, otherslot: number): copies the information about an item the inventory controller can see into a slot in a database

Database component:
- Add database.copySlot(slot: number, otherdb: addr, otherslot: number): copies a slot in the current database to a slot in another database
- Add database.delete(slot: number): deletes a slot
- Maybe add database.swap(slot: number, otherslot: number): swaps two slots
  - (Note: probably not useful, as database order is irrelevant, unless someone writes code to make use of the order somehow, like a priority list?)

These new methods would allow a computer/robot with both an Inventory Controller and Database to dynamically manage its Database as it sees new items. It could also lay the groundwork for future Database-Component interactions (e.g., geoanalyzer.analyze -> database to address #654?).

**Comment by fnuecke** [comment]
Sound good. Will implement when I can.

**Comment by rmellema** [comment]
If you want to identify blocks in the wild, you could have a counter that counts how many blocks of each type you encountered and order them with the most frequent first, as a speedup for you program, so the swap is most certainly useful.

**Comment by fnuecke** [comment]
Will implement `database.copy` as `function(fromSlot, toSlot[, database])`, if the target database is omitted it'll copy to a local slot, so swap can be implemented on the Lua side (requiring one free slot, but I'm OK with that).
