### ISSUE TITLE
The game freezes and crashes with other mods for numerus reasons

### ISSUE THREAD

**Issue by EzerArch** [MightyPirates/OpenComputers#696]
First off, I'm about to fall in love with OpenComputers, but our hang-out is not being so friendly.

I'm getting constant crashes and frozen screens when I place a Server Rack or a Robot (`java.lang.OutOfMemoryError: PermGen space`), or if I try to connect a Mekanism cable to the Assembler, or simply out of nothing when I'm using the Assembles the game starts hanging and then freezes.

[12:50:52] [Server thread/INFO]: [EzerArch: Given [Computer Case (Tier 2)] \* 64 to EzerArch]
[12:50:52] [Client thread/INFO]: [CHAT] Given [Computer Case (Tier 2)] \* 64 to EzerArch
[12:51:12] [Client thread/INFO]: Stopping!

It also seems the game needs to crash when I place the 1st Rack on the world, so I can place the next ones: https://gist.github.com/EzerArch/4e51f772a668f2b3754d

Or when  I try to right-click a Mekanism Solar panel: https://gist.github.com/EzerArch/d834d6c8da5a8b150213

As I'm playing with other techmods, probably one of them is not getting along with OC, I tried to remove one by one but I have no idea which one is the culprit. These are the mods I'm using:

bspkrs' Mods
DynamicLights
JourneyMap
NotEnoughItems
CustomNPCs
BiblioCraft
Galacticraft
Mekanism
ModularPowersuits
powersuitaddons
MrCrayfishFurnitureMod
Carpenter's Blocks
ZoomMod
fastcraft

If need more info, feel free to ask.

Thanks in advance.

**Comment by magik6k** [comment]
PermGen is part of JVM memory, that is 'separated' from regular heap (-Xmx, -Xms), and it seems that your modpack simply requires more of it. To set permgen space use `-XX:MaxPermSize=[size]`, for example `-XX:MaxPermSize=384M` should be enough for most modpacks. Alternatively you may try to update to java 8, but then if you are using old forge it may derp. And this issue is probably not related to this mod directly

**Comment by fnuecke** [comment]
Yup, what magik6k said, nothing OC specific. Just increase your PermGen memory a bit :-)

**Comment by EzerArch** [comment]
Thanks for the answers.

Looks like I discovered where the problem is, Mekanism. I removed this mod and finally I was able to play more than 5 minutes with no crashes, hangings or something (20 minutes until now). Probably this mod was eating up all memory. The problem now is I don't have any other energy sources besides Galacticraft energy, which is not supported.

I'll use the -XX:MaxPermSize=384M thing.

EDIT:
Increasing the MaxPermSize allowed me to re-add Mekanism back. Thank you!

**Comment by fnuecke** [comment]
To clarify, this is not any single mods' fault. Each mod has a number of classes, and if the overall number of classes loaded in Java becomes too large, the default PermGen size just isn't enough. This could just as well have happened with any other mod in existence.
