### ISSUE TITLE
Bounding boxes on Keyboards and Cables are weird

### ISSUE THREAD

**Issue by iambob314** [MightyPirates/OpenComputers#699]
At least in SMP, whenever a player attempts to walk over/past a Keyboard or Cable such that they partially pass through the block it resides in, the player will be consistently teleported backward. This makes it difficult to maneuver around a keyboard in tight spaces, and literally impossible to walk over a cable embedded in the floor without a microblock cover.

My guess is the bounding box on Keyboards and Cables are not in sync between the client and server: the server thinks them to be full blocks, whereas the client believes they have smaller bounding boxes. Could be related to FMP somehow, however I'm not familiar with that mod/API.

I've only witnessed this problem on Keyboards and Cables, but it could affect any other sub-block-bounding-box blocks. I can't think of any other examples at the moment, though...

**Comment by Techokami** [comment]
I have the same issues with vanilla anvils...

Sent from my Windows Phone

**Comment by Kubuxu** [comment]
@Techokami Issue with anvil is when there is arrow stuck in it or you are looking on other anvil. It is not the same issue.

**Comment by fnuecke** [comment]
I'm aware of the keyboard related bounding box issues, but haven't been able to fully track them down, yet. I'll have another look when I can. For now, try not to walk into them >_>
