### ISSUE TITLE
Feature Request: Allow for all music discs to be played via a adapter connected to a jukebox

### ISSUE THREAD

**Issue by MFernflower** [MightyPirates/OpenComputers#70]
Because why not ? :D

**Comment by fnuecke** [comment]
Not sure what you mean. You want to play the music of any music disc without actually having to find the disc? Then that's why not ;-)

**Comment by MFernflower** [comment]
Yes :D

**Comment by MFernflower** [comment]
Or a sound device that does noteblocks and music discs all in one?!
