### ISSUE TITLE
Lative libraries not loading on 133 (and previous versions)

### ISSUE THREAD

**Issue by morlanius** [MightyPirates/OpenComputers#701]
This is happening on a forge cauldron server. I have been on the irc channel and changed all kinds of options in the config to the puzzlement of all. I have even installed lua and eris on the server which is a CentOS 5 server. one of the changes was something to do with an earlier post about a similar thing but changing the temp dir did not work. I changed the config to extract the libraries but i see nothing being extracted to any of the temp dirs.

Currently running build 133
a log with the debug option to display full library errors can be found here http://91.121.75.102/log/latest.log

**Comment by fnuecke** [comment]
I'll set up a CentOS5 VM when I can; for now, please set `logFullNativeLibLoadErrors` to true in your config and post that log. I'm suspecting its libc is too old or something like that... if that's the case I'll have to recompile the libs in the VM and test if they still work on other Linuxes...

If you feel up to it, you can try to grad the OC-Natives repo yourself (clone _with --recursive_), build the libs (`./gradlew x64RNSh`) and replace the lib in the OC JAR (`assets/.../lib/native.64.so`) and see if that helps. If you do try, you'll probably have to add the include path to the Java native headers in the `build.gradle`... they seem to hide in a different place for every single Linux distro in existence -.- (oh, and you'll most likely need the JDK installed, not just the JRE)
