### ISSUE TITLE
ClassCastException caused without IC2

### ISSUE THREAD

**Issue by mzx987** [MightyPirates/OpenComputers#702]
The title is self-explanatory, but every time a case, power converter, or server is placed on the ground, this warning is displayed:
http://pastebin.com/5rUuQT5X

I am currently using the latest development build of OpenComputers (v1.4.1-253)

**Comment by fnuecke** [comment]
Hmm, I have to guess, but probably some other mod is shipping a potentially partial IC2 API. Could you please check your startup log for the part where OC reports which power interfaces it uses and which it doesn't (look for "Injecting interface" or "Skipping interface") and paste that part? I want to confirm something before I start changing things.

**Comment by mzx987** [comment]
This is a list of instances I found with the two phrases "Injecting interfaces" & "Skipping interfaces":
http://pastebin.com/S5Y2ecR2

If this is not exactly what you need, then I could send the entire log file.

**Comment by fnuecke** [comment]
Hmm, yes, please post the full log. Non-classic IC2 is missing there, so I'm guessing there was some error injecting the interface.

**Comment by mzx987** [comment]
I'm pretty sure this is the current log file:
https://dl.dropboxusercontent.com/u/27284881/fml-server-latest.log

**Comment by fnuecke** [comment]
Thanks. ResonantEngine is shipping an outdated IC2 API. I've informed them.
For now, just remove the `ic2` directory from the RE JAR, or ignore the warning.

**Comment by mzx987** [comment]
Not to comment on something already closed, but I believe I should update my Resonant Engine then. It seems to be heavily outdated. XD

**Comment by fnuecke** [comment]
I checked the Github repo, and it still contains the old API. Dark said he'll probably remove it / avoid shipping it in the future. But yeah, updating rarely hurts! ;-)
