### ISSUE TITLE
Blacklisting CC peripherals not working as intended

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#703]
As you can see at https://github.com/MightyPirates/OpenComputers/commit/2abfdeaa3ca6bbfce911116ab14f27b9c8408b88, you are now able to blacklist Peripherals, but the Driver is never checking if a peripheral is blacklisted, it is still just checking if the TileEntity is.

**Comment by fnuecke** [comment]
Right, there was that, too. Thanks!
