### ISSUE TITLE
OpenIRC does not show all users

### ISSUE THREAD

**Issue by gamax92** [MightyPirates/OpenComputers#705]
![Example](http://i.imgur.com/cD6Ok0t.png)

Except there are 115 people, not 18.

**Comment by LizzyTrickster** [comment]
Does it print it across multiple lines? IRC messages are (in the RFC) limited to 512 bits/bytes so it usually splits it up.

**Comment by fnuecke** [comment]
In principle multi-part name replies should work, see [related code](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/OpenIRC/irc.lua#L312-L318). Not sure why it'd fail. Can't say I'm bothered enough to find out, so if someone else wants to investigate and PR a fix, please go ahead!

**Comment by payonel** [comment]
this has been fixed, some time ago probably, perhaps with the many tty fixes we've had in openos
