### ISSUE TITLE
Sticking LPeg in OC?

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#706]
Is there any way to stick LPeg in OC before the sandboxing takes place?

**Comment by Kubuxu** [comment]
There's LulPEG. But last time I was trying to run it on CC it required few tweaks.

**Comment by fnuecke** [comment]
@Kilobyte22 was working on a fork that allowed loading external libraries, but I think that project is on hiatus / dead. Maybe you can get that running again, then you can load libs. Otherwise, yes, there's LulPEG. It's not hard to get working in OC, really.

**Comment by SoniEx2** [comment]
No loadlib() on kernel.lua? :/

**Comment by Kilobyte22** [comment]
That project is currently unmaintained due to lack of time. I will however update it eventually, maybe i get some time over christmas
