### ISSUE TITLE
Floppy drive in Tablets

### ISSUE THREAD

**Issue by Brycey92** [MightyPirates/OpenComputers#709]
I propose a shift-right click GUI in the Tablet with a power button and floppy drive. This would make the Tablet exactly 17.5x cooler. (That's right, I did the math.)

Edit: A recheck of my calculations by mrmakeit reveals that the Tablet would actually be 17.75x cooler, not 17.5x, as I had previously thought. My apologies to all who have been inconvenienced by this error. If this miscalculation has caused you physical or mental distress, or loss of property or revenue, please send a formal complaint to /dev/null.

**Comment by Vexatos** [comment]
Make sure it only is available if you assemble the thing with a Disk Drive.

**Comment by fnuecke** [comment]
Of course.

**Comment by Faeranne** [comment]
I want to see your figures on that.

**Comment by Brycey92** [comment]
Sorry, the coolness calculations use uh... classified mathematical formulas that I can't show to you.

**Comment by Faeranne** [comment]
ಠ_ಠ

Right.

Internet, here I come.

**Comment by Faeranne** [comment]
after toiling over the necessary calculations, I have come to the conclusion that the number 17.5 is - in fact - incorrect.  (it appears you forgot to carry the pony.)  A further check confirms that, not only would it be a full 17.75x cooler, but would increase it's effective usefulness by over 9000.  (that last number may or may not be accurate, but apparently effectiveness is not a much of a science as coolness.)

**Comment by Brycey92** [comment]
Ah, my mistake. I'll change the original post to reflect the corrected calculations.

**Comment by fnuecke** [comment]
With the risk of messing up your numbers, here's a question that needs answering: should tablets allow (T1) containers of _any_ kind (including card and upgrade), or only disk drives? I'm a little undecided. Given it'd consume two complexity I'm inclined to allow any container type.

**Comment by Brycey92** [comment]
Oh, T1 containers of any kind seems like a much cooler idea. We will have to rework the numbers, but I think it will be worth it.

On a side note, are things like keyboards and disk drives checked against a computer's cpu the way they are against a tablet's? It could just be me, but I could swear I can add more components to a T2 computer than to a tablet.

**Comment by fnuecke** [comment]
Added in b0a4e8f857e7865fc2f720f5ed37fd8a1ac3d89a.
