### ISSUE TITLE
Feature Request: CD/DVD Drive

### ISSUE THREAD

**Issue by MyNameIsKodos** [MightyPirates/OpenComputers#714]
Essentially it would be a disk drive, but instead of floppies it would have a new storage type, a Blank DVD, with a bigger amount of storage.  It would also be able to play vanilla music discs via something like cdDrivePlay(), cdDriveStop(), etc.

Just something that popped into my head that I wanted to suggest.  Doesn't have to be a huge priority (assuming it's even possible).

Thanks for your time reading =)

**Comment by Vexatos** [comment]
@Kodos-Atoz You might want to try Computronics' tapes and the tape drive, the largest-size tape is able to store 32 MiB of data.

**Comment by MyNameIsKodos** [comment]
I'm aware of the tape drives.  I'm talking CDs and discs though.  It would be a way for us to code jukebox/playlist programs, among other things.

**Comment by MyNameIsKodos** [comment]
Also the tapes aren't fs' by default, that has to be done software side, which not everyone is capable of doing.  CDs would essentially just be a reskinned floppy with a bigger capacity.

**Comment by fnuecke** [comment]
I'm pretty sure I said "no" to CDs some time ago, with the same reason I'm not convinced now: I don't really see the benefit over using a floppy / hard drive given that I do not think a CD should have more capacity than an HDD. Leaving relatively little wiggle room - floppies are 512k, T1 HDD is 1MB. A new block and item for 250kb more storage that would have to be read-only? I don't think _I_ would use this. If the demand is there though (i.e. by more than one person ;-)) I may reconsider.

Actually, there's [that mod with lasers](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2093100-awesome-sauce-mods-openautomation-now-with-lasers) that has OC integration already, anyway, maybe CDs would fit in there (seeing as it already has lasers. Oh, and I think it also has lasers!)

**Comment by MyNameIsKodos** [comment]
The 'lasers' are practically magic.  Buildcraft has lasers.  OA has wireless magic.

**Comment by Vexatos** [comment]
I'll just say I agree with @fnuecke. I don't see a point in CDs.

**Comment by MyNameIsKodos** [comment]
I'll go ahead and leave this issue open in the event anyone else wants to chime in with their desire to have this implemented.  If you feel that closing it is necessary at any time, feel free to do so.

**Comment by fnuecke** [comment]
Definitely, leave it open for now so others that might be interested can say so.

**Comment by scj643** [comment]
I would like to see CD but see them as one time write objects. As a sort of backup medium. So if you are working on say an os, that won't fit on a floppy you can write it to the disk.

**Comment by MyNameIsKodos** [comment]
What about, since it's a 'higher quality' type of storage medium, would it be possible to make it work with T2+ or even T3 only computers?

Or even instead of T3 computers using built in floppy support, have it support CDs.  If nothing else there's still the floppy drive block they can use for accessing OS installations and such.  If you have a T3 case, you probably have the materials for an extra component.

**Comment by gjgfuj** [comment]
Coming to OA Soon (TM). CD drives. Possibly. When I finish the rest of the lasers I have planned.

**Comment by MyNameIsKodos** [comment]
I'll leave this open until either OA has them, or OC has them :3

**Comment by Techokami** [comment]
Forgive my ignorance, but what mod is "OA"? O.o

**Comment by scj643** [comment]
It's open automation

**Comment by MyNameIsKodos** [comment]
As an alternative to CD drives on OC's side, we could change the way RAIDs work, and have T1-T3 RAID Blocks, with 3, 6, and 9 HDD slots accordingly, following the same general crafting schemata as cases, screens, and the like.

**Comment by Techokami** [comment]
@scj643 I cannot seem to find anything on the internet about a mod named "open automation", care to provide a link?

**Comment by gjgfuj** [comment]
http://www.minecraftforum.net/topic/2695349-172-forge-awesome-sauce-mods-openautomation/
Is the link to it. No problems.

**Comment by Techokami** [comment]
Thanks for that.

**Comment by XeonSquared** [comment]
When CD-ROMs were first introduced, they were SCSI devices that had a write-once limitation, but were 600MB when hard drives at the time were 50MB.
Just thought that was worth noting.

**Comment by Vexatos** [comment]
@shadowkat10 So you are thinking about a mass-storage write-once system? FS or no FS?

**Comment by XeonSquared** [comment]
FS would be ideal- think an archive drive or even a development drive- can't break old versions of the repo.

**Comment by Kubuxu** [comment]
@shadowkat10 incremental write or one time and forever?

**Comment by XeonSquared** [comment]
One time and forever, but with symlinks, you could have a git-like system, or something similar.
Think something like once the buffer is closed, that file can no longer be written.

**Comment by Kubuxu** [comment]
I meant "should we be able to add informations to the CD after first write?".

**Comment by XeonSquared** [comment]
Oh, yes, you just wouldn't be able to modify existing files- like a real CD-ROM with a filesystem.

**Comment by gjgfuj** [comment]
No, I would assume.

**Comment by MyNameIsKodos** [comment]
But it would/should still have a fixed capacity.  So it'd be a CD-R basically.  I really like this idea now.

**Comment by MFernflower** [comment]
Sorry that I brought up an older post but - What about a CF card type thing but instead of having flash its a large OTP-ROM? We can call them CompactROM™ cards or perhaps just CR cards. ;-) (No idea what to do about FS - If someone thinks they can come up with a solution we can all agree on please show!)

Don't know what to do about music discs tho - Some sort of OC soundsystem thing? Like the elaborate cards of the 1990's?

**Comment by fnuecke** [comment]
I think there's too much overlap with the other storage devices, tbh. I'd also like to avoid huge file systems in OC itself.
