### ISSUE TITLE
oc.cil.li down?

### ISSUE THREAD

**Issue by tbbw** [MightyPirates/OpenComputers#716]
Seems the main webpage is down.
Any status on it?

**Comment by LizzyTrickster** [comment]
Yes, it's down. No, there is no ETA because @Ir7_O has been absent

**Comment by fnuecke** [comment]
Up again!

**Comment by ghost** [comment]
On an unrelated note, does anyone read the url as "awk.silly"?

**Comment by LizzyTrickster** [comment]
No. Your just weird :/

**Comment by LizzyTrickster** [comment]
Fuck you too outlook
