### ISSUE TITLE
An Intra-Net card.

### ISSUE THREAD

**Issue by scj643** [MightyPirates/OpenComputers#719]
So this is basicly an internet card except it only has connections within the server. It would have it's own addressing scheme too. It would also have a DNS loot disk to setup a DNS server. Fell free to add on to this idea.

**Comment by magik6k** [comment]
umm, so global linked card? You can already setup a network made from cable modems, linked cards and in some cases wireless cards using network loot disk.

**Comment by scj643** [comment]
A global linked card yes. This would be for servers and allow an ingame intranet (Local internet) It would be cross dimensional. Basicly a linked card without the need for pairing. Could be useful for people who play on servers and want to develop an ingame website.

**Comment by LizzyTrickster** [comment]
I don't see the point in this. It's basically a wireless network card that can transmit server wide and potentially not have addresses which would be hard when responding to messages

**Comment by Techokami** [comment]
Global Linked Card sounds too powerful. Do what magik6k suggested and build a network using the provided components. That's what makes OpenComputers so fun: you have to engineer your solutions instead of just plopping down a magic block.

**Comment by fnuecke** [comment]
Honestly? For servers that want this, I'd recommend setting up an HTTP server on a custom port and blacklist all external connections in the config (if desired). Then you can just use the internet card for it (using `localhost:1337` or whatever, or even alias the host if you have to).

Leaving this open a few days to allow some more feedback.

**Comment by scj643** [comment]
isn't localhost blocked on the default? also this wouldn't just be for internet but cross dimension communication with "Client" Computers, an http server would be too limited.

**Comment by LizzyTrickster** [comment]
The blocks are configurable

**Comment by scj643** [comment]
Never mind this would never work.
