### ISSUE TITLE
Tiered slots in computer cases

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#72]
This is inspired by an idea mentioned in #69. Generalizing it I think it would be interesting to explicitly categorize items into tiers, and the different tiers of computer cases would only support a certain tier of items.

For example basic graphics card and redstone card are tier one, advanced graphics card and network card are tier two, superior graphics card and wireless network card are tier three. Memory and hard drives would be tiered according to capacity.

Computer cases may have mixed tiered slots, for example the basic case would only support basic items, the advanced case would support one tier two item each*, the rest of the slots would still be basic. The superior case would support one tier three item each and the rest of the slots would be tier two.

*) Except memory, that I'd like to keep "symmetric", meaning two tier two in the advanced case, two tier three in superior.

Feedback welcome.

**Comment by MFernflower** [comment]
Like diffrent buses? A ISA for redstone? A AGP for graphics? A pci for networking?

**Comment by fnuecke** [comment]
Sort of, but with backwards compatibility, i.e.
- Tier 1 slot only takes tier 1 items.
- Tier 2 slot takes tier 2 _and_ tier 1 items.
- Tier 3 slot takes tier 3 _and_ tier 2 _and_ tier 1 items.

I think I'd leave it a three tiers. If there were more memory modules as suggested in #69 I'd group them somehow (e.g. 64k = tier 1, 128k and 256k = tier 2, 512k and 1m = tier3 or so).

**Comment by MFernflower** [comment]
Perhaps we can have a work station with tons of memory and card slots. I
could texture it. Perhaps a orange color would be nice.

**Comment by fnuecke** [comment]
Well, I imagine the servers #17 would maybe have up to four RAM sots, but fewer/no card slots (if no cards they'd have built-in networking, though).

**Comment by MFernflower** [comment]
What about a performance machine with 4 ram and card slots for those big
builds?

**Comment by fnuecke** [comment]
I'd prefer to keep what you can achieve in one block limited. If you need several high tier cards, build multiple computers/servers and have them communicate. I'd say this is more consistent with the design philosophy so far (OC is relatively multi-blocky: screen is an extra block, power converter is an extra block, ...)
If you want a compact build you'll have to work with less powerful hardware, just like in real life where you have embedded systems, not tiny power machines with triple SLI in your router, USB-hub, telephone, etc.

**Comment by LordFokas** [comment]
I support this. The servers should have _nothing_ built in though, instead, you should add all network, graphics, and other hardware yourself.

**Comment by MFernflower** [comment]
Orange workstation computers could have 2 or 3 card slots, can take up to 2x 512 kb sticks and should not have a inbuilt disk drive (For balance) but are capable of having 2 HDD's 
Lime server computers should have 4 card slots, and can take up to 2x 1mb sticks and should have 4 hdd spaces.

**Comment by LordFokas** [comment]
they should actually be just drive slots. If you want to sacrifice an HDD for an optic drive on the most basic of computers you should be able to... after all, they run on the same bus.

it should boil down to:
- ram slots
- cpu slots
- expansion slots
- drive slots

what you put in each doesn't really matter.

**Comment by fnuecke** [comment]
I don't know, I think servers will be fine as tier 3.5 (more ram and hard drive slots), without an extra tier of computer cases. Simply put, after adding more computer case tiers, I don't think the differences between the tiers would still be big enough. It'd be like taking away the level-up effect in an RPG, and instead just having an ever-progressing XP bar. Wouldn't that be boring? Plus I like the idea of grouping the ram into a total of three tiers, since it allows some upgrading inside the individual tiers.

Generalized drive slots: the issue I have with that is: how do you insert a disk into a disk drive that is installed inside a computer? I'm not very keen on making the GUI dynamic. If anything I might just make the floppy slot in tier 3 cases another HDD slot. I just thought a little more... variety would be nice.

**Comment by LordFokas** [comment]
you hit the computer with the disk in hand, and it goes in the drive, maybe?

**Comment by fnuecke** [comment]
But then you can't control into which one it goes if there's more than one disk drive. Which may be negligible. What's more problematic is that the only way to eject a disk without ripping out the drive would be via Lua, and that there'd be no visual indicator as to whether there's a disk in there or not, and if where.
Don't get me wrong, the idea is neat, and I'd be happy to have it in, but I'm not sure the gains justify the potentially big chunk of time it'd take to implement. Because the only way that I currently see that isn't a usability nightmare would be to dynamically expand the GUI with floppy disk slots if disk drives are in the drive slots.

**Comment by LordFokas** [comment]
You gave me an idea. What about a side tab in the GUI in TE / BC / Forestry style ?
Wouldn't hurt the GUI as much...

**Comment by fnuecke** [comment]
Hmm, like the tray of the disk drive? That'd be a nice thing, but I always disliked BC and Co's side tab stuff because it collides with NEI (which can be toggled, I know, I know). Plus it'd be very restricted vertically anyway, since I'd like to keep the floppy slots on the same height as the drive slots to keep the association clear. Another thing I've run into while trying to make a mockup: any idea for an icon that represents both HDD and floppy disk drive?

**Comment by LordFokas** [comment]
you can put it on the left side, so it doesn't collide.

They're both disks and both run on the same bus, but apart from that I don't think they have anything in common...
You could make an icon with both a floppy and an HDD...

**Comment by fnuecke** [comment]
I dunno, placing it to the left leaves too much space between the drive and its contents, no?
Quick mock-up with the main inventory moved to the left a bit, so there's space to the right for the floppy disk slots:
![Drive Slots](http://i.imgur.com/sSivET7.png)
Not really happy with that, it just looks weird if there are no drives in the computer and the right part is empty. I think that works better if there's no fancy graphics at all:
![Plain Slots](http://i.imgur.com/B0DsXFZ.png)

**Comment by LordFokas** [comment]
I like the top one ;)

**Comment by fnuecke** [comment]
I'm closing this since the main topic (tiered slots) is done (locally, no one shall see my precious!).

Feel free to bring the drive thing up again in a new issue. Though I admit I won't prioritize that for now.
