### ISSUE TITLE
Forestry Analyzer (And possibly other blocks) not acting as actual components...

### ISSUE THREAD

**Issue by MyNameIsKodos** [MightyPirates/OpenComputers#723]
beyond calling the getEnergyStored() and getMaxEnergyStored() methods.

Would love to be able to write a bee program akin to the one I saw in a video ages ago, granted that was a CC program.

Maybe a few other blocks from Forestry could be interacted with as well, since the mod itself is open source now.  No idea what would be good and viable choices, so if anyone else wants to chime in, they're welcome to.

**Comment by fnuecke** [comment]
What methods would you expect to be available on this block?

Looking at the tile entity itself, sensible candidates would be:
- `isWorking():boolean`
- `getProgress():number`
- `getIndividualOnDisplay():table`

Anything else? (That can't be done using inventory / tank controller)

**Comment by Vexatos** [comment]
@fnuecke Be careful with the individual's data, exposing that would remove a huge part of Forestry Bee breeding (If you are not playing with GenDustry or Binnie's Mods)

**Comment by Kubuxu** [comment]
@Vexatos but this data is available after analyzing and there is even itemstack convener for that.

**Comment by fnuecke** [comment]
Q: Which brings up the question whether that converter has to be reworked.
A: It's fine as it is IMHO. There's an `isAnalyzed` field and it properly respects that from what I see.

**Comment by fnuecke** [comment]
I guess that's it for now. If anyone has suggestions for further drivers, feel free to open a new issue.
