### ISSUE TITLE
Tablet typing not working in dimensions

### ISSUE THREAD

**Issue by mzx987** [MightyPirates/OpenComputers#727]
So I have an assembled tablet in my small Minecraft server (with a keyboard in it, of course) and I noticed that when I traveled to another dimension, the tablet would not respond to any of my typing. I thought this was a fluke of some kind, so I rebooted the tablet and tried again. It still wouldn't let me type. It only seems to let me type in the Overworld and not anywhere else.
I've tested this in single player and it seems to work fine in any dimension without any problems.

Is there something I am doing wrong/missing, or is this really a bug?

**Comment by fnuecke** [comment]
Thanks! Looks like tablets weren't properly un/reloaded on world changes. Should be fixed in the next build!
