### ISSUE TITLE
getStackInSlot for Robots own inventory.

### ISSUE THREAD

**Issue by therealeldaria** [MightyPirates/OpenComputers#730]
I might be missing something.
In the API for the Inventory Controller I can find information about what is in an external inventory by using the getStackInSlot function.
But I can not find the same information for what is in the Robot's own inventory?
Feels a bit silly if I have to put it into a chest to see what it is?
Is this a bug or a missing feature?

**Comment by fnuecke** [comment]
Quoting from the inventory controller's wiki page:

> To interact with the robot's own inventory you need to use the side `back`.
