### ISSUE TITLE
Tier 2 Micro Controller

### ISSUE THREAD

**Issue by scj643** [MightyPirates/OpenComputers#731]
A tier 2 micro controller that only difference is that it supports bundled I/O. Would have a more expensive recipe. It doesn't have any other differences besides it can only hand one tier 2 redstone card.

**Comment by fnuecke** [comment]
Only a T2 redstone card? That feels a little _too_ special-case for me. I agree that bundled redstone would be neat, but it should force a choice. I am considering making one of the two card slots in the MCU a T2 slot, while keeping the current limit. That'd allow T2 redstone cards. Opinions?

**Comment by Techokami** [comment]
That would probably be the smartest choice

Sent from my Windows Phone

**Comment by LordFokas** [comment]
I would make the T2 redstone card built into the controller. It's a controller, it's role is to interact with wires on specialized systems, so redstone cards shouldn't be optional. You could then make the card part of the recipe... And then, keep all the slots T1. That's what makes the most sense to me.

**Comment by Vexatos** [comment]
I agree with @LordFokas here.

**Comment by fnuecke** [comment]
Hmm, I think having a special case like a pre-built-in card is a bit unintuitive, given how almost everything else built in the assembler lets you explicitly pick all components (the exception to the rule being the screen in tablets, but I personally feel that's a bit different to a card, there are many addon cards after all, but not (m?)any addon screens).

**Comment by Vexatos** [comment]
I don't think it should support bundled redstone anyway, so you decide ;)

**Comment by LordFokas** [comment]
Without bundled redstone you're limited to 6 (?) wires per controller. We're on extreme opposites here @Vexatos , as I think of the controller like, well, a controller. You program it, put it down, plug a ton of wires in and it's done. Eventually it may have an addon or two, but those are very special cases... you mostly want controllers to handle large amounts of redstone cabling without needing a full computer. It's pretty much just RAM and a CPU.

I think special cases, recipe- or implementation-wise, are OK. At the right abstraction level, a robot is just a computer that moves, terminals are just screens, and so on. You need special tools for special tasks, and I can't imagine all of them being built in the same generic way.

**Comment by fnuecke** [comment]
While I agree that it'd be desirable to have them support bundled redstone, I retract my T2 card slot concept. That'd then need a special case to prohibit wireless network cards again. Gah.

As for special cases... I think that depends on the circumstances. Relatively optional stuff like re-crafting the nav upgrade with maps? Sure. Getting a redstone T2 card into a MCU only by crafting it into the case before assembling it, which is a different concept than anything _component related_ you'll have encountered in OC thus far? Inconsistent and unexpected, IMHO. Where possible (given I notice it [in time]) I try to follow the principle of least surprise, not only in software. I think this is one such case.

Now, seeing as T2 card slot is ded, and I don't think a single item in difference validates the overhead of an extra MCU tier... what about making the redstone card for modded redstone T1 (slot-wise)? At this point I really would like to have a tier between one and two, but alas...
Anyway, I'm not _quite_ sure how I feel about this. On the one hand it feels like giving T1 cases quite a bit more power, on the other they feel kind of underpowered at the moment, anyway, and redstone really isn't something _that_ high-tech, so... I'd lean towards going through with that. You can start yelling at me now.

**Comment by LordFokas** [comment]
That's fine by me. Here, have a piece of lie. :cake:

**Comment by Vexatos** [comment]
:traffic_light: I don't really like the T2 Redstone card going T1, but I wouldn't hate you if you did it; I would vote against it, but if there is no better way of doing it... :traffic_light:

**Comment by fnuecke** [comment]
I'm so torn about this :-/ Gah. Will need to sleep over this another day.

**Comment by scj643** [comment]
How about this we just make a config option. It toggles it on or off, Having it on allows you to make a tier 2 MCU while if it's off all of you that don['t want it can be happy.

**Comment by jotac0** [comment]
A solution i thought : use the power consumption so we can ban the wireless card..
So the Micro controller can only convert a certain amount, so with this, you could install a wireless card, but using it would make the micro controller go down (not enoth power).. making the energy storage of the controller lower for this ... i don't know, just a random suggestion!

**Comment by Vexatos** [comment]
@fnuecke Another idea would be, put the completed MCU into the Assembler AGAIN, that opens a slot for a T2 Redstone card (and only a redstone card).

**Comment by Faeranne** [comment]
I've been looking at the api a bit, and according to http://ocdoc.cil.li/tutorial:modding_imc there should be an easy way to validat that it is not a wireless card in the tier 2 slot.  Now, I'm not sure how the recipe is handled internally, but if it follows the same pattern as for external mods, shouldn't this be easy?

Know what?  I'm just going to see how your handling the GPU blacklist and see how hard it is.

**Comment by Faeranne** [comment]
Yep,  that's what I thought.  I can't find the code that handles blacklisting GPUs from the microcontroller.  Seems I still have much to learn about this mod.  Especially if I'm going to tackle adding a JS architecture.

Anyways, not sure how deep a rabbit hole the slot validate function is,so I'll leave that to your judgment.
