### ISSUE TITLE
Remote terminals and robots!

### ISSUE THREAD

**Issue by seebs** [MightyPirates/OpenComputers#733]
It should be possible to set up a robot with a remote terminal so you can mess with it from a longer range.

**Comment by Techokami** [comment]
Fleshing this out a bit more, how about a Card that can do this with regular computers as well? Remote Terminal Card! Craft parts of a Wireless Card with a Tier 2 GPU Card. Should probably be Tier 3. Plop it in a case, then bind a Remote Terminal to it like with a Server. Of course, Servers don't need the card to utilize Remote Terminals. But with the Card, you can use Remote Terminals on regular computers and Robots.

**Comment by Vexatos** [comment]
I agree with it being tier 3, should also require some tier 3 components.

**Comment by fnuecke** [comment]
Let's me say this: remote terminals were a stopgap solution until I had the time to fully implement tablets. Therefore I strongly would prefer people using tablets to remote control robots. In light of #709 I'm considering adding an upgraded remote tablet that allows T3 graphics, to avoid rendering them completely sub-par in every respect. But I'd still like to keep them easier to setup yet more limited in use than tablets.

If there's an overwhelming demand for remote terminals to work with computers / robots, I may reconsider, but that's my current stance anyway.

**Comment by seebs** [comment]
I don't know about tablets yet. Mostly, I want to be able to get a shell on a robot while not physically next to it.

**Comment by fnuecke** [comment]
After some more thinking I won't look into this, please use a tablet plus some software for this.
(Background: I am in fact considering removing remote terminals when porting to 1.8 in favor of multiple tablet tiers, so that would be a lot of wasted implementation effort)

**Comment by hohserg1** [comment]
Have someone a program the remote terminal based on the tablet?
