### ISSUE TITLE
Encrypted FS / Virtual FS / FS Driver support

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#736]
It would be cool to be able to register a function to handle filesystem, that way we could get encrypted FS and stuff.

**Comment by LizzyTrickster** [comment]
You can already sort of encrypt data already

**Comment by LizzyTrickster** [comment]
If you want encrypted stuff, why not look into the cipher block in computronics. OC doesn’t need encrypt able FS’ IMO

**Comment by SoniEx2** [comment]
The idea is not for OC to provide them. The idea is to let the user hook into the filesystem and let those hooks encrypt/decrypt stuff on the fly.

**Comment by LizzyTrickster** [comment]
What do you mean “hook into the filesystem”? You can edit OpenOS however the hell you want

**Comment by SoniEx2** [comment]
>.> can we get OpenKernel then?

**Comment by LizzyTrickster** [comment]
What would a “Kernel” do that isn’t already available in OpenOS or other OSs??

**Comment by SoniEx2** [comment]
Split the OS from the kernel?

**Comment by fnuecke** [comment]
The FS has nothing to do with the kernel. It's a component like any other, and there already are vcomponent implementations AFAIK (even remote-capable ones, i.e. via network). In fact, in 1.4.2 even the bootstrap code for filesystems is on the EEPROM, so you could boot off an energy cell that has the OS encoded in its energy level for all I care. So yeah, do it in Lua, no need for "native" support here.

**Comment by SoniEx2** [comment]
What if you want to run multiple things that hook the FS? Overriding things sounds like asking for trouble IMO.

**Comment by LizzyTrickster** [comment]
Have multiple FS hooks maybe?

**Comment by natedogith1** [comment]
fs.mount accepts a table instead of a component label, wouldn't that work for hooking the fs?

**Comment by SoniEx2** [comment]
I'm not sure... are there any docs on that table?

**Comment by natedogith1** [comment]
the table should have the same functions as those of a proxy object/table made from a filesystem component

**Comment by SoniEx2** [comment]
Is that API stable?
