### ISSUE TITLE
Virtual components / component drivers

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#737]
The #736 equivalent for components (hmm now that I think of it, this would remove the need/usefulness of #736)

Uses: /dev/random and /dev/urandom, dummy components, etc. Just like linux.

**Comment by fnuecke** [comment]
Well... for one, it's been done AFAIK, for two, maybe just write it yourself? Because writing programs / libs / OSes yourself is kind of a big part of what this mod is about ;-)
