### ISSUE TITLE
Linux/Unix philosophy

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#738]
Can we follow the [Linux/Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy)?

(Also can you please be a bit less... aggressive, when talking to me?)

**Comment by LizzyTrickster** [comment]
Maybe if you stopped suggesting stupid ideas then sure

**Comment by SoniEx2** [comment]
How are they stupid?

**Comment by fnuecke** [comment]
Please stop throwing around sentences like they mean anything on their own. It makes you at the very least seem uninformed, ignorant, or worse, lazy. Possibly a combination of those. If you want to contribute something, please at least take the time formulate a proper, understandable, elaborate post. Why do you expect others to invest more time in your one-liners than it appears you took coming up with them?

**Comment by SoniEx2** [comment]
Split the kernel from the OS, make the FS easily hookable (with compatibility between hooks!), make the components easily hookable (also with compatibility), all those things would make it easier for the user to do things, as they wouldn't have to hack things to make them work together. (and thus users would be more end-users than devs - just like IRL)

**Comment by fnuecke** [comment]
What you're describing can be achieved with a custom OS, no problem. "The OS" (I'm assuming you mean OpenOS?) is already completely separate from the "kernel" (which is really just part of the machine layer, and has been renamed to machine.lua a couple of commits back, even, to make that more clear). There's nothing special about OpenOS. Just roll your own! What's more open-source than that? :P

**Comment by SaphireLattice** [comment]
Try latest dev build. There is 4KiB EEPROM that replaces kernel.lua (mostly, very small part of it is still read-only) and can be edited.

**Comment by SoniEx2** [comment]
So it's a kernelless OS? (because that thing you call a kernel sounds more like a BIOS)

**Comment by fnuecke** [comment]
Kind of. Hence the file rename.

**Comment by SoniEx2** [comment]
Ok... then can we please follow the Unix philosophy and make a proper kernel for the OS?

**Comment by LizzyTrickster** [comment]
If you want to make one then go right ahead. No one is stopping you.

**Comment by fnuecke** [comment]
I'll be locking this before someone gets hurt...
