### ISSUE TITLE
Project Red: Bundled Wires

### ISSUE THREAD

**Issue by Wallum** [MightyPirates/OpenComputers#74]
Hey, I was very glad that you implemented Project Red functionality, however upon testing my private modpack, I stumbled across a few problems, all of which had this error report.
1) I placed a 'golden' case next to a basic case. This caused the game to crash.
2) Connecting Project Red bundle wires up to any of the cases appears to cause the game to crash due to the same reason apparently.

Crash report: http://pastebin.com/3NmVGdWx

I am running OpenComputers-1.1.0pre2 and ProjectRed(Base, Compatability, Integration, Lighting, Mechanical, World)-1.6.4-4.2.2.19 on Forge9.11.1.953

If I have posted this in the wrong section I do apologise; github was not loading for me and I feel like this is a major issue.

Thanks

**Comment by fnuecke** [comment]
Yeah, there was a bug in prerelease 2, please try [the latest one](https://github.com/MightyPirates/OpenComputers/releases/download/v1.1.0pre4a/OpenComputers-1.1.0pre4a.zip) (prerelease 4a at this time).
