### ISSUE TITLE
Official OC server

### ISSUE THREAD

**Issue by scj643** [MightyPirates/OpenComputers#741]
A server just for the OC github community. It would have some mods and not be overly intense. The list I would suggest. I have no way of making this happen.
- OC
- Project red core (For bundled cables)
- Computronics
- Railcraft
- FMB
- AE2
- Ender IO
- Thermal Expansion
- Big Reactors
- Flux solar
- MFR
- NEI
- Buildcraft
- Extra Utils (1.1.0k)

Feel free to suggest more.
(I posted this in the github and not the forums since i feel the github is more active.)

**Comment by fnuecke** [comment]
There's an extra section on the forums for servers, and this is really not the place for such topics.

Side note: how do you expect the forums to get more lively when everyone only posts on Github? ;-)

**Comment by scj643** [comment]
Ok going to move it
