### ISSUE TITLE
Crash on Boot up

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#746]
Problem: Minecraft Crashes after booting up computer. It won't crash if graphic card is not inserted into computer, so i assume crash is related to displaying stuf on screen.

Crashlog: http://pastebin.com/pHNts3xU

**Comment by fnuecke** [comment]
Please give [this build](https://www.dropbox.com/s/suict6mi9c2wyqs/OpenComputers-MC1.7.10-1.4.3-c6d5584-dev-universal.jar?dl=0) a shot, it contains DLLs built on Windows 7.

**Comment by ghost** [comment]
It works now, no crash this time. Thanks!

**Comment by fnuecke** [comment]
Awesome, thanks for confirming!

(Fixed in c6d5584f93cd46f2a1592cfc222d272a739ee5f9)
