### ISSUE TITLE
Error in scheduled tick action

### ISSUE THREAD

**Issue by Roadcrosser** [MightyPirates/OpenComputers#747]
The server is spitting out this error on the latest version of OC, computronics is installed, IC2 is not.

![image](https://cloud.githubusercontent.com/assets/7963090/5515541/ec78918c-88a9-11e4-8e67-41a486edf3f3.png)

**Comment by Techokami** [comment]
Full log?

**Comment by gdude2002** [comment]
Server owner here (Was too busy to submit this myself earlier - thanks road!) - this happens every time a chunk containing computer cases is loaded or unloaded. It doesn't crash the server, though.

EDIT: I'm not sure what fuller logs to give, there's pretty much nothing else from OC there when this happens.

**Comment by fnuecke** [comment]
The log is fine. Which version of OC is this? Also mind posting a list of mods / checking yourself if any of those contain (parts of) the IC2 API? Thanks.

**Comment by gdude2002** [comment]
We're using [this version](http://minecraft.curseforge.com/mc-mods/223008-opencomputers/files/2221890) of OC (MC1.7.10-1.4.2.16).

We don't actually have IC2 installed, but here's the mods we've got.
- Antique Atlas 4.0.1a
- **Applied Energistics 2 rv1 (beta 37)**
- AsieLib 0.3.5
- Baubles 1.0.1.9
- BiblioCraft 1.9.1
- BiblioWoods (Natura) v1.5
- BigReactors 0.4.0rc9
- Botania 1.3-139
- bspkrsCore 6.15
- Carpenter's Blocks 3.2.6
- ChickenChunks 1.3.4.14
- Chisel 1.5.6a
- CodeChickenCore 1.0.4.29
- CodeChicken Lib 1.1.1.106
- CoFHCore 3.0.0B9-47
- **Compact Machines 1.12**
- Computronics 1.3.3
- CustomNPCs 1.7.10b
- Dragon's Radio Mod 1.6.2
- EiraIRC 1.7.52
- **EnderIO 2.2.2.285**
- ExtraCells 2.1.18b
- Extra Utilities 1.2.0
- Forbidden Magic 0.55
- Forge Multipart 1.1.0.314
- Hats 4.0.1
- iChunUtil 4.1.2
- Iron Chest 6.0.62.742
- Jabba 1.7.10
- Mantle 0.3.2
- Deconstruction 2.2.5
- **Mekanism 7.1.1.127**
- **Mekanism Generators 7.1.1.127**
- **MineFactory Reloaded 2.8.0RC5-694**
- MineTweaker 3.0.9C
- Mod Control 1.2
- **Mod Tweaker 0.6-0**
- MrTJPCore 1.0.3.5
- MultiMine (No version info)
- Natura 2.2.0.1
- NotEnoughItems 1.0.3.72
- OpenBlocks 1.3-snapshot-511
- OpenComputers 1.4.2.16
- OpenModsLib 0.6-snapshot-268
- Pam's HarvestCraft 1.7.10d
- PlanetguyLib 1.3
- ProjectBlue 1.1.2
- ProjectRed Base 4.5.7.58
- ProjectRed Compat 4.5.7.58
- ProjectRed Integration 4.5.7.58
- ProjectRed Lighting 4.5.7.58
- ProjectRed Mechanical 4.5.7.58b
- ProjectRed World 4.5.7.58
- Remain In Motion 2.2.0
- Resonant Engine Core 2.0.0.63
- **Simply Jetpacks 1.2.0**
- Tinkers Construct 1.7.1c
- Thaumcraft 4.2.1.4
- Thaumic Tinkerer 2.5 161.jar
- Thermal Expansion 4.0.0B6-16
- Thermal Foundation 1.0.0B3-8
- TMechworks 0.2.10
- **Universal Electricity Core 4.0.0.45**
- Waila 1.5.6a_1.7.10

I've highlighted the ones I think might use the IC2 API in bold.

**Comment by fnuecke** [comment]
Thanks. Interestingly, RE does ship the API, in full, so I have no clue how that interface is supposed to be missing (it's there, I checked)... anyway, I _did_ fix this a while back (by requiring IC2 proper to be present instead of just the API), but apparently that got lost in a merge. Should be gone in the next build. Again.
