### ISSUE TITLE
Creative Inventory Controller Upgrade

### ISSUE THREAD

**Issue by TinkerWorX** [MightyPirates/OpenComputers#752]
This is an extra step to the Inventory Controller Upgrade, which would allow me to spawn items in an inventory. Would be perfect if it supports id and metadata. If NBT tags are possible, that would be great as well, but for my needs, it's not important right now.

**Comment by fnuecke** [comment]
Hmm, isn't there a command to spawn items? Then you could use the debug card's `runCommand` method for this. Otherwise a new method on that would be doable. Won't add an extra item for that, though.

**Comment by TinkerWorX** [comment]
I found a way to spawn items in the world, but not into containers.

For others that might find this, here's how:
`/summon Item " .. x .. " " .. y .. " " .. z .. " {Item:{id:" .. id .. ", Damage:" .. dmg .. ", Count:" .. n .. "}}`

**Comment by fnuecke** [comment]
Ah, I see. I'll look into it then.
