### ISSUE TITLE
Assembler template blacklist

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#753]
Brought up by @asiekierka on IRC a little earlier today.

I see two ways for this, basically:
- IMC message providing a callback that's asked whether something is blacklisted.
  - Pro: as flexible as you could ever need it to be.
  - Con: needs an extra mod.
- Config entry with blacklisted items (that serve as template bases, such as computer cases, tablet cases, ...)
  - Pro: can be changed easily.
  - Con: less flexible, more effort to implement.

Well, I say "effort", I'm pretty sure I could reuse some code from the Recipes parser to parse the blacklisted items. Anyway, what would your preference, @asiekierka? I'm guessing the latter?

**Comment by LordFokas** [comment]
or you can have a config file and allow an IMC interaction for cases that are not in the config.
That way a modder can blacklist stuff from his mod and pack makers can override the whole thing.

Of course, that's like, triple the effort to implement. But doesn't get any more flexible or powerful than that.

**Comment by fnuecke** [comment]
Yeah, adding both. Cleaner anyway.
