### ISSUE TITLE
"debug.runCommand()" Can't Run Commands (Fake Player Lacks Permissions?)

### ISSUE THREAD

**Issue by Eunomiac** [MightyPirates/OpenComputers#754]
Any time I attempt to execute a console command via the debug card's "runCommand" method, I get a "You do not have permission to use this command" error.  

This includes commands like "help" and "tell":

![luacommanderror](https://cloud.githubusercontent.com/assets/5692071/5535123/1385ab94-8a43-11e4-8695-74206124a5b8.jpg)

**Game Details:**
- SSP, Cheats enabled
- I'm in Creative mode
- Debug Card is enabled in config
- Debug Card is in a Creative Computer Case

(**Also,** the above error is returned when I try to use those WorldEdit commands I was so excited about in #700; I'm not sure if the issue is the same, or if runCommand is unable to use WorldEdit console commands at all---hopefully the former!)

**Comment by fnuecke** [comment]
Hmm, I thought I had tested single player, too. Will look into it.
