### ISSUE TITLE
Any filename ending in a backslash in filesystem save directory (under Linux) causes random file nonexistence

### ISSUE THREAD

**Issue by celskeggs** [MightyPirates/OpenComputers#758]
Okay, this is a weird bug: If I add any filename that ends in a backslash to the data directory, arbitrary files don't show up from the computer's perspective.

Create a hard disk and, in a shell, go into `saves/<save name>/opencomputers/<drive id>/` and create a file named `test\` (with a trailing backslash.)
Remove and reinsert the disk (to refresh the files) and then list the directory from the in-game computer.
You will notice that a number of the files and directories do not show up.

The expected behavior is for all files to show up, possibly including the file ending with a backslash. (Though, since such files cannot be created in-game, this isn't absolutely necessary.)

Different malformed filenames (such as `init\` or `zzz\`) cause different files to not show up, though I haven't figured out the pattern.

I suspect that this is a problem with handling filename paths across multiple kinds of systems. As such, it is likely only reproducible on Linux systems and maybe Mac OS X systems.

**Comment by fnuecke** [comment]
This is probably the buffered file system getting confused by the backslash; for all other ways of creating files / directories these are considered invalid chars IIRC. For now, if you absolutely need files named like that, try disabling the buffering (`bufferChanges=false` in the config).

I'll look into supporting or (more likely) filtering out such files when I can.
