### ISSUE TITLE
Put a wrapper around Lua's io.open instead of rolling your own FDs

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#759]
The wrapper simply makes sure you can't escape the FS sandbox. This lets the + modes work and removes a ton of overhead.

**Comment by fnuecke** [comment]
No. All of OC's virtual file systems would stop working (RAM based FSes, buffered FSes, wrapped CC FSes, ...).

**Comment by SoniEx2** [comment]
Yet no random access FSes :/

**Comment by fnuecke** [comment]
All filesystems support seek in both read and write mode, so I'm not sure what you mean?

**Comment by SoniEx2** [comment]
dual mode FDs >.>

**Comment by fnuecke** [comment]
Eplain.

**Comment by SoniEx2** [comment]
Example of dual mode FDs: https://gist.github.com/SoniEx2/655d4ba7d7cc4eee6ef4 (I call them "readwrite" FDs but they don't seem to have a name? it's really hard to google and duck (I tried both) them)

**Comment by fnuecke** [comment]
Ah, you mean the [update modes](http://www.lua.org/manual/5.2/manual.html#pdf-io.open)? Yeah, you'll have to live without those in OC for the time being, sorry.

**Comment by SoniEx2** [comment]
I'll still call them readwrite modes. (also are they unsupported by the buffer API or by the FS API?)

**Comment by fnuecke** [comment]
Both. The underlying API has no concept of such modes, Lua side might be able to emulate them but I don't think that's a good idea (messy / largely unnecessary bloat).

**Comment by SoniEx2** [comment]
Well it's actually kinda simple... on all modes you have a read and a write(*) stream, on w+ you clear the file, (so w+ is like w but with a read stream) on a+ you have an append stream instead of a write stream, you have to flush to update the read stream. (so basically, when you clear the write buffer you also clear the read buffer) Maybe there are a few other things I missed but this seems mostly easy to implement...

**Comment by natedogith1** [comment]
maybe I'm under-thinking things, but could you just open a read stream and a write stream and keep their locations in the files in synch?

**Comment by SoniEx2** [comment]
for r+ you'd probably have to write the whole file again...
