### ISSUE TITLE
Case Crash

### ISSUE THREAD

**Issue by Wallum** [MightyPirates/OpenComputers#76]
I updated to the prerelease4, and I had a crash upon placing any of the cases. I had the following crash report: http://pastebin.com/0aEuv9g4

Thanks

**Comment by fnuecke** [comment]
Are you also using the latest version of Project: Red?

**Comment by Wallum** [comment]
The version I was using was indeed OpenComputers-1.1.0pre4a following your earlier advice. I am also using Project:Red-4.0.5.12, if that is causing an issue.

**Comment by fnuecke** [comment]
Yeah, they updated their API quite recently, I think you'll need at least 4.2.2 build 18 (which shows up as build 19 ingame).
