### ISSUE TITLE
Better GregTech integration

### ISSUE THREAD

**Issue by HiTECNOLOGYs** [MightyPirates/OpenComputers#760]
It would be great to have support for all the machines for recipes, not only assembler. Having a way to make use of liquid input in those that support it would also be nice.

This is probably not really important feature to implement, though.

**Comment by fnuecke** [comment]
Hmm, could be interesting I guess, but I don't think I'll look into adding this myself.

If someone's interested in implementing this, a PR would be welcome.

**Comment by Timeslice42** [comment]
In the mean time you can use this addon for minetweaker to change the recipes for all the new GT5 machines (including fluids): http://forum.industrial-craft.net/index.php?page=Thread&threadID=11353

For example I changed the cutting wire to use fine tin wire, and added a recipe to the plate cutter to get 4 raw boards from a block of green stained clay using lubricant, distilled water, or water: http://pastebin.com/fuX4LJHv

**Comment by HiTECNOLOGYs** [comment]
@Timeslice42 woah, that looks interesting. Thanks.

**Comment by lordjoda** [comment]
Ok so I added the possibility to use more gregtech machines. Please (after Sangar has aproved the stuff ;) ) take a look and feel free to suggest recipe changes as I did not change them for now. If there is the demand for additional machines please let me know as it should now be relativly easy to add them!

**Comment by HiTECNOLOGYs** [comment]
@lordjoda neat, thanks. I surely will check that out.

**Comment by fnuecke** [comment]
All right, it's in. The basics definitely still work (i.e. the recipes in the built-in GT set), but we haven't had the time to actually make a test case for each individual machine. If something doesn't work, let us know. There's some documentation [in the GT recipes file](http://git.io/vfnaJ) on how to make recipes for the different machines, and which ones are supported.

If you do create a better set of recipes, consider making a PR to get them into the current set. I can't quite remember how up-to-date that one is, and if it's any good at all :P Thanks.

**Comment by Timeslice42** [comment]
The current recipe set is pretty amazing, it just needs to be reworked a bit to use the forming press, laser engraver, and the assembly machine that can now use fluids. For example to craft an advanced circuit in gregtech you now run electrum through a plate bender twice to get 4xelectrum foil, put the foil in the laser engraver with a red lens to get 4xetched high voltage wiring, put that in the forming press with a silicon plate to get an advanced circuit board, put a lapis plate and glowstone dust in the forming press to get the advanced circuit parts, and then the board and parts in an assembly machine with molten lead, tin, or soldering alloy to make the advanced circuit. Used to be you crafted that all in the assembly machine and there were no fluids involved.
