### ISSUE TITLE
Drones unable to use Navigation upgrades?

### ISSUE THREAD

**Issue by Aedda** [MightyPirates/OpenComputers#762]
First forgive me if this is posted in ignorance, I've not found anyone who can answer this.

I took the [drone bios.lua](https://gist.github.com/fnuecke/6bcbd66910b946b54ec7#file-bios-lua) example and added the following under the first line:
local n=component.proxy(component.list("navigation")())

Drone just beeps at me, tried changing n to nav and navigation.
I tried omitting that line and sending a broadcast message from [client.lua](https://gist.github.com/fnuecke/6bcbd66910b946b54ec7#file-client-lua):
modem.broadcast(2412, "nav=component.proxy(component.list('navigation')())")
then tried accessing it via client with:
nav.getFacing()
and the error was attempt to index global 'nav' (a nil value)
So then I omitted both broadcasts and pasted them into client to send, the drone= worked however nav= threw this error:
bad argument #1 (string expected, got nil)

Not sure what else I can possibly try. Please let me know if you need any other information, etc.

ETA:
eeprom=component.proxy(component.list('eeprom')()) pasted into the client program works fine.
As does drone.setStatusText(eeprom.getLabel())
Just navigation failing, and yes I verified it is listed as a component in the tooltip. :)

**Comment by fnuecke** [comment]
Ah right, I think I forgot to add the rotatable interface to the drones which is required for this and a few other upgrades (piston, sign, ...), so the component won't be instantiated.
