### ISSUE TITLE
"debug.runCommand()" always returns "Unknown command." on Cauldron

### ISSUE THREAD

**Issue by Hotrian** [MightyPirates/OpenComputers#763]
Any time I use the runCommand method, it always returns the same values

![debugcard](https://cloud.githubusercontent.com/assets/580880/5565472/438eea3e-8eb3-11e4-9136-f847a7ea8f3e.png)

Other debug card features work properly, but I cannot get runCommand to return anything else. I have tried a few other methods to proxy the debug card to ensure that wasn't the issue (such as component.proxy( component.list( "debug")())). The debug card seems to work fine aside from runCommand.

**Game Details:**
- Using OC Version 1.4.3.21-beta.1
- Cauldron Version 1.1236.05.212
- SMP Server, new world after upgrade to new OC
- I've tried in Creative and Survival mode
- Debug Card is enabled. When it is disabled I do get a different error.
- I have tried in Tier 3 Cases and Creative Cases
- Deleted Config files to reset defaults

Am I doing something wrong?

Edit: I think I was having the same issue with OC v1.4.1.14 as well, but I have since upgraded and am not certain

**Comment by Hotrian** [comment]
Actually, runCommand does work SSP. Is there something that must be configured or changed for SMP or perhaps Cauldron does not work properly with OC?

**Comment by Hotrian** [comment]
Looks like this was a compatibility issue with Cauldron. A clean install of Cauldron with just OC gives the same "Unknown command." issue. A new install of FML gives "You do not have permission to use this command" on SMP similar to #754, which is fixed by Opping the fake player UUID. I'm leaving this issue open in the hope someone may track down the issue with Cauldron in the future, feel free to close though

**Comment by fnuecke** [comment]
Hmm, will look into why this might fail in Cauldron when I can (which will be in about a week).

**Comment by fnuecke** [comment]
Did some testing, the only explanation I can come up with is that Cauldron/Bukkit is prohibiting command use by fake players. I don't think there's anything I can do about that, I'm afraid.
The only workaround I can suggest is enabling command blocks and using those. Or not use Cauldron but plain Forge.
