### ISSUE TITLE
Fleshing out user permissions

### ISSUE THREAD

**Issue by Aedda** [MightyPirates/OpenComputers#767]
It could use useful if the user permission system were just a little more fleshed out than the current. Specifically I'd like to see two additions, and one tweak to the system...

1) A way to list users in the user list.

2) A way to allow two specific new types of access; e.g. Console access, and Console access + Power On/Off

3) An option to lock a computer in Single Player and in LAN, for Adventure style play or other uses. As it is now it requires a genuine server to be running.

Additional notes: It would also be nice to see a way to limit adding and removing users to specific trusted users. I realize this however may be handled at the user coding level but any successful breach could mean the end of ownership. Perhaps a separate entry for the Owner of the machine which can only be removed or changed by the Owner or an OP.

ETA: An option to make computer cases explosion proof might be nice too, as exploding them allows their hardware to be harvested. Also if these are too many things for one issue please let me know and I'll separate them! :D

**Comment by Techokami** [comment]
A semi-usable solution to the third point is to use a Creative Case. If you're not in Creative Mode, you can't use the GUI of a Creative Case-based computer. Also has the added benefit of not needing a power source, which would be useful for important machines handling an Adventure map.

**Comment by natedogith1** [comment]
Ownership could probably just be changed so that it didn't effect access to the gui, and then that part can just be implemented in lua-side code.

**Comment by Aedda** [comment]
Some of this may be redundant when compared to my original post but I felt it helped to keep all the topics together when replying.

I think the best and most realistic approach would be to move hardware-locking to a physical system like actual computers. Have a key that unlocks a machine to allow full hardware access, and have a key that allows for power control/rebooting only access. Optionally a third key for built-in floppy access? I've seen such a case back from the 90s, little bar came down in the slot when the case was locked. In any case maybe still require the original owner to dismount the machine and move it?

Screen access control should be done on the software level as suggested by natedohith1, it would open up the possibility of multi-user systems with access levels, and all sorts of fun stuff.

The functions for adding and removing users could then be dropped entirely (replaced by the physical keys) eliminating that as a potential security issue.

And finally the explosion thing could be handled with a config option makeMachinesInvincable=true and then tnt, creepers, other mods could not break (provided they follow block hardness) the machine and steal the components, software, etc.

**Comment by fnuecke** [comment]
I like the idea of physical locking being physical. It's more intuitive and logical. I think I'll still leave the old system in place, for things like #823 and #827 at least. With the possibility of removing the "physical" part from that in 1.5 or so (but not in 1.4 because breaking changes and such).

**Comment by S0ZDATEL** [comment]
I think that the physical lock can be a like a upgrade. If you need it, you can add a physical lock. But "hardware" level lock must be removed. I mean the commands like addUser(). What is the magic command that simply forbids people to interact with a computer? It needs to be removed, and instead let each player composes his own security system. Perhaps he can make a password lock or make it necessary to have a special floppy disc in the diskdrive. But anyway the password can be bruteforced, and the floppy disk can be stealed or forged. But the fact that the player can just write addUser(Username) to protect any computer is not realistic.

**Comment by payonel** [comment]
hmm.....maybe the addUser feature should be moved to an upgrade card, that locks the computer :)

**Comment by payonel** [comment]
We'd have to change the machine interface to extend the user security system api. nope
i like to see this sort of thing in addons. OpenSecurity for example could add a lockable machine case.
