### ISSUE TITLE
WR-CBE integration

### ISSUE THREAD

**Issue by KaseiFR** [MightyPirates/OpenComputers#768]
Hi,

I'm reporting here that I can't get the WR-CBE integration to work: the Tier 2 redstone card remains absent from NEI.
I don't have any stack trace to show, but I'm using WR-CBE 1.4.1.9 and OpenComputers 1.4.3.21-beta.1 . I've also tried with Computronics, without success.

Thank you.

**Comment by Techokami** [comment]
Have you tried adding a mod that implements bundled redstone? This includes MineFactory Reloaded, Project:Red, and RedLogic. The Tier 2 Redstone card might only be available if one of these mods is present.

**Comment by KaseiFR** [comment]
It worked, thank you. Should it be possible to enable it with only a wireless mod present? I'm using computers to avoid redstone logic ^^

**Comment by Techokami** [comment]
Well, that does sound like a bug. Paging @fnuecke to the thread...

**Comment by fnuecke** [comment]
Ah, crap, the check for wireless mod presence happens in the item initialization, which happens before mod integration. I'll switch things around a bit to fix this!

PS: no need for @ mentioning me, I get emails for all issues on this repo ;-)
