### ISSUE TITLE
suggestion: Nano tablet

### ISSUE THREAD

**Issue by morlanius** [MightyPirates/OpenComputers#771]
Nothing fancy, just a tablet like normal but much smaller and its GUI would sit in the bottom left/right/configurable area of the screen. This would allow us to fly drones interactively by sensing key presses from the nano tablet and still be able to see what you are doing.

It would also be useful for other things where people might want a UI that doesn't take up the screen. This could be sorted with OpenGlasses or something if they could see keypresses but im very doubtful that the author would want to add that functionality to it or they would have done it already as its such an obvious thing to think about.

**Comment by Kubuxu** [comment]
@morlanius As one of co-authors of OpenGlasses I must say we never thought about feature like that. OpenGlasses were always in game GUI and nano tablets would be cool addition to the feature set.

**Comment by morlanius** [comment]
That would be an awesome if you could add that. Would it be possible to have a version of the glasses that has a noteblock function too, a recipe could be normal glasses with a noteblock either side. implements 3 methods note() (plays both noteblocks as one) and noteLeft() and noteRight().
it shouldn't be difficult to get the stereo effect just by setting the location field of the play event to be 4 or so blocks to the right/left. obviously this should be a client side thing so other people cant hear your "ear buds".

**Comment by fnuecke** [comment]
Aye, I think this'd make a lot more sense as a feature in OpenGlasses, as that's all about extending the GUI / augmented (virtual) reality. @Kubuxu if there's anything I can do to make this easier for you to implement, let me know.

**Comment by Kubuxu** [comment]
Thanks fnuecke, I won't hesitate to ask unfortunately currently OG system is parts as we were rewriting rendering to VBOs so you could generate whole structures in a AR.
