### ISSUE TITLE
Inspect library

### ISSUE THREAD

**Issue by scj643** [MightyPirates/OpenComputers#772]
I am suggesting that the inspect lua library be added to oc
https://github.com/kikito/inspect.lua

It would be a loot disk.

**Comment by Kubuxu** [comment]
I second this. It would be great debugging tool.

**Comment by scj643** [comment]
I'm still trying to figure out what implements the  `describe()` and `it()` functions.

**Comment by fnuecke** [comment]
Having a quick glance over the code, I see nothing that'd make it not work in OC, and I see no reason not to add it as a loot disk (as long as the license text is kept in there), so feel free to make a PR.

**Comment by fnuecke** [comment]
As I said, PR as a loot disk if you like. No need to keep the issue open.
