### ISSUE TITLE
suggestion: speaker

### ISSUE THREAD

**Issue by morlanius** [MightyPirates/OpenComputers#776]
a networked device that uses the same sounds scale as the OC local to the speaker so it can be placed about. each speaker should have a setting to set its channel. from the api it should have the beep() method as well as setChannel() getChannel(), setVolume() and getVolume().

And perhaps the computronics people would think this idea is so neat they make the tape recorders have an option added for speaker internal/external and channel number.

**Comment by fnuecke** [comment]
What would the 'channel' do?

**Comment by morlanius** [comment]
it would be the audio channel that the speaker "listens" on. so you could do something like (ill simply infer variables for simplicity)
speakers[1].beep(note_value) or speakers.beepChannel(channel, note_value)

**Comment by fnuecke** [comment]
Hmm, not sure how that'd fit in with each speaker probably being its own component.

@Vexatos would you be interested in adding this functionality to Computronics' iron note block?

**Comment by Vexatos** [comment]
I'd make a new block for it, but yes, I think it would fit well into Computronics.
As each speaker will be its own component there is no need for channels.
Question: Which functions would you like to have on the block?

I would add a speaker.listen(address) so you can listen to either a computer or a tape drive by inserting the computer's/drive's component address. This, of course, being seperate from the functions the component itself has.
@fnuecke Any way to make a speaker actually listen to computer.beep()? If not, I'd just implement .beep() on the speaker itself.

**Comment by fnuecke** [comment]
Not as things currently stand, no. And I don't really want to make `computer.beep` trigger external stuff, it's explicitly for the built-in speaker. You already have the beep card, though, you could make that broadcast messages (`node.sendTo...`) and trigger the block like that if you want to avoid them being separate components?

**Comment by morlanius** [comment]
@Vexatos to be able to configure what it is listening to would be nice, perhaps an internal "oscillator" type arrangement so we could output different tones to different speakers on the network and have them able to output audio from tape drives.

**Comment by Vexatos** [comment]
I have been told by @asiekierka that he wants to work on something similar to this, so I'm not allowed to make speakers just yet, you'll have to wait.

**Comment by fnuecke** [comment]
Closing this for now. Reopen over at Computronics if necessary.
