### ISSUE TITLE
Keep drones moving after teleport

### ISSUE THREAD

**Issue by natedogith1** [MightyPirates/OpenComputers#784]
I feel that it might be more appropriate if instead of the drones stopping after they teleport, they continue moving, with their new target location based on where they were the relative location of the target before the teleport. So if I told the drone to go five blocks north, and it teleported after traveling two, it would travel 3 blocks north after the teleport.

**Comment by MyNameIsKodos** [comment]
I second this, though I'm not sure how difficult it would be, code-wise, to implement.
