### ISSUE TITLE
Disasember eats robots

### ISSUE THREAD

**Issue by morlanius** [MightyPirates/OpenComputers#786]
The disasember seems to be eating robots. There is no animation the thing just vanishes. It disassembles other things fine.

**Comment by gamax92** [comment]
Can confirm, On Creative mode, Disassembler eats robots regardless of chest or nothing connected to it.
No items dropped on the ground.

**Comment by fnuecke** [comment]
The Copy-Pasta strikes again! Thanks for the report.
