### ISSUE TITLE
Allow binding network cards to sides of microcontroller

### ISSUE THREAD

**Issue by magik6k** [MightyPirates/OpenComputers#788]
As microcontroller can fit multiple network cards, binding them to sides would allow creation of compact networking devices like routers.
The only thing I see, that requires a little discussion, is how the sides would be bound.
- Through some kind of component API
- Using GUI, like in server rack
- Using some tool like wrench on sides to decide how is specific side connected, probably slightly changing textures

**Comment by Vexatos** [comment]
This should be specific to the Tier 2 Microcontroller.

**Comment by fnuecke** [comment]
Hmm, making this T2 specific might make T1 MCUs a little _too_ special-case?

Maybe have both be sided, but the side for sending network messages be hardwired to the back in T1? (or all sides, actually... would still provide different enough functionality from both computers and T2).

**Comment by magik6k** [comment]
Ohwait, from what you've wrote, you might have misunderstood what I intended. It was more like having 2 network cards in one uC and allow connecting of specific sides ot them(so one card could be conected to something like WAN port, and second one would provide LAN port(s)), not just binding send/recv functions to sides.

**Comment by fnuecke** [comment]
Ah, so you mean something like the side-assignment in server racks, but instead for servers for slots? Sortakinda? Or just have slot one be connected to up/back/down, slot two to left/right or something like that? (hardcoded)

**Comment by magik6k** [comment]
Yep, Having it done in way server racks are done would be nice, but would require messing with additional guis, having it hardcoded would be still nice(like second slot connected to back and first slot to rest of sides. Also I dunno if It'd be possible but it'd be really nice if in this(hard-coded) case all sides but back were acting as one network node))
