### ISSUE TITLE
Make Cases, Microcontrollers and Drones have their Tier exposed in the API

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#789]
the classes `internal.Case`, `internal.Drone` and `internal.Microcontroller` should have a method getTier() that returns the drone's/MCU's currently tier (same as the `internal.Server`) so 0 would be tier 1 and 1 would be tier 2. This would allow behaviour specific to certiain tiers of environment hosts

**Comment by Hotrian** [comment]
Does this cover robots? Because they should get the same method which reports back which case they were constructed with as well; if they do not have one already.

**Comment by fnuecke** [comment]
Probably a new interface (`Tiered` or something like that) implemented by all of those.
