### ISSUE TITLE
AE2 integration

### ISSUE THREAD

**Issue by invliD** [MightyPirates/OpenComputers#791]
Currently, the only way to interface with AE is using an ME Controller. When channels are disabled, there are, however, no Controllers. If that AE2 setting is used, there is no way to use OC to interface with the ME network. Could you either detect that setting and add interaction using a different block in that case or maybe add another ME block as a possible interface (maybe the ME Interface) either way?

**Comment by Techokami** [comment]
Uh, out of personal curiousity, _why_ would you disable channels in AE2?

**Comment by invliD** [comment]
It kinda defeats the purpose of saving space. Sure, you can work around that limitation for a while using P2P. But at some point, there's an actual limit on building more complex things. It also makes certain features useless. We wanted to use one single network of (ME) cables in our base and distribute power using P2P, but with the addition of channels, they are too valuable to lose that many for power alone. So we disabled them.
Now, on the other hand, we can't use OC to manage the network anymore.

**Comment by ghost** [comment]
having a different issue with ae2 and opencomputers (i plan to make a proper report in a bit after i gather a bit more info) but was looking through the issues to see if anyone else had the same bug and saw this and your question about why anyone would disable channels and wanted to weigh in
we also disable channels (infact in my ftb modpack they are disabled by default) they are the worst addition to any mod in a long time, for small to medium bases they are easy to work around but once you start getting bigger bases you start having massive p2p connections, extra cables etc and it becomes an absolute nightmare fast, thankfully the option to disable them exists (even if you then also need to use minetweaker to fix a missing recipie for quantum connections) so its not an issue, but i can promise you that me and invLiD are most likely not alone in the disabling of ae channels...hmm and while writing this out i just finished getting the info i needed for bug report

**Comment by Keridos** [comment]
I have one more bug regarding AE2 Compatability: It seems that when requesting a crafting job while no crafting CPU is available creates a phantom job that never gets finished (regarding .isDone of the object given back). What also might be the cause of this is that isDone() may be calculated by the amount of the item in the system, but when the value is changed fast, it may never be recognized as done by the Computer?
