### ISSUE TITLE
More realistic eeprom interface. 

### ISSUE THREAD

**Issue by morlanius** [MightyPirates/OpenComputers#792]
eeproms need to have a couple more functions to make it more realistic and add more functionality. By 'interface' I am referring only to the software interface only.

int eeprom.getSize() // returns number of lines of the eeprom array.

int eeprom.setLine(string data, int line_number) // returns true(1) on success, false(0) on fail, returns 2 if line replaced an existing, non-nil line

string data getLine(int line) // returns the string at [line], return false if [line]<eeprom.getSize()

char data getChar(int line, int chr) // returns the character on line [line] in potition[chr], returns false if line |or| character is nil

eeprom.chksum // data value self populated after a write operation
a simple 16 character hash based on the data being written similar to MD5. Read only value.

string data eeprom.getChksum() // return the eeproms' chksum value as a string.

eeprom.protected // Boolean data value. Prevents changes to the eeprom, think blowing protection fuses.

Boolean eeprom.protect(string chkSum) // returns true on success, requires the chksum of the eeprom in order to prevent idiots from fusing everything.

Changes to LuaBios
set the protected data value to true and set the chkSum to a known string that does not use the standard chkSum routine to generate eg: "Official LuaBios" to assist in preventing a bios virus in a spoofed bios.

**Comment by morlanius** [comment]
I forgot to add one important thing.

string data eeprom.genChksum() // returns the checksum of the eeprom, not from the value but from calculating the checksum from a live state. Using this to validate eeproms.

**Comment by Kubuxu** [comment]
EEPROM is not lined. It is just string of limited number of chars.
About protection you could just run script in init checking content of EEPROM.

**Comment by morlanius** [comment]
Aah ok, then what I said above should be easily translatable to the knowledge of it being a string. But I still maintain this would be a valid thing to add.
I would like to be able to write to the eeprom on the fly so i can reserve an area to contain some data without having to load, alter, save the entire thing. This would allow for more persistent (yet very limited) storage on a device with no hard drive.

**Comment by fnuecke** [comment]
Since there's even still `computer.setBootAddress` (and `get`), which is kind of redundant now, and which can be used for arbitrary data, I admit I don't think that random access to the EEPROMs has a high priority.

Getting the size makes sense though, in particular now that there's a setting for it.

As for the `protect` call, that's interesting, and I agree fuses are indeed a good, realistic explanation for it. I'll see if that's as simple to add as I think it is.
