### ISSUE TITLE
Temporary directory does not cleans when computer reboots by typing computer.shutdown(true).

### ISSUE THREAD

**Issue by PowerOfTech** [MightyPirates/OpenComputers#794]
When computer reboots by double pressing power button, all is ok. When computer shutdowns by typing computer.shutdown() and turns on, all is ok again. But when I reboot computer by typing computer.shutdown(true) or reboot program, /tmp directory does not cleans.

**Comment by Kubuxu** [comment]
IIRC it is on purpose.

**Comment by NPException** [comment]
I'd assume that this is not a bug.
As long as memory is supplied with power (which is the case when telling your PC to reboot IRL) it does not lose it's content. Power is usually only cut from memory when a computer is shutdown completely.

**Comment by LizzyTrickster** [comment]
There's a setting in the config for that, by default it's set to _not clear the /tmp on a soft-reboot_ so it should be easy to change it if you want the contrary

**Comment by fnuecke** [comment]
[What Josh said](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/application.conf#L214-L218). (Actually, what everybody above said.)
