### ISSUE TITLE
suggestion: Linked cards in drones

### ISSUE THREAD

**Issue by morlanius** [MightyPirates/OpenComputers#795]
It would be nice if linked cards would fit into drones in a tier 2 slot, as this would make drones more able to compensate the complexity should be 1 higher than that of a wireless network card.

**Comment by Techokami** [comment]
Linked Cards are the Tier 3 network card, though.

**Comment by morlanius** [comment]
Ahh ok, my bad.

**Comment by fnuecke** [comment]
Drones won't get linked cards, sorry. They are kind of to robots as microcontrollers are to computers. They're intentionally a little more limited.
