### ISSUE TITLE
Drones not turning on

### ISSUE THREAD

**Issue by SeniorFight** [MightyPirates/OpenComputers#796]
I followed the "primitive" remote control tutorial.
Did exactly what You did.

Drones just ... won't turn on (charged fully, BIOS flashed, all components with wireless card too, tier1/tier2 tested).

Please fix ASAP.

**Comment by Kubuxu** [comment]
Try using Analyzer.

**Comment by SeniorFight** [comment]
PS: It beeps everytime i press "Turn on" button...

**Comment by SeniorFight** [comment]
failed loading bios (I used as done in the video)
flash.lua broken? (using latest dev)
i flashed an LUA bios because the EEPROM didn't work... "errored" in flash.lua line 61 function 'writeRom'

**Comment by SeniorFight** [comment]
How can I "see" the BIOS code through an computer?
Is it even possible?
Maybe in save/opencomputers folder... but It's like 99% probality that flash program just flashes with errors...

**Comment by SeniorFight** [comment]
NVM just got it to work correctly.
Fixed manually an issue i my BIOS

STILL ONE FACT:

When I have a lua bios in my computer,
I launch flash <file>
It says give the EEPROM ...
So i remove LUA bios, and put in EEPROM,
flash.lua errors at line 61.

So i have to start flash <file> while I have ALLREADY an EEPROM bios inside.
This is a real bug. Not an error of mine.
I consider this issue as fixed, please delete. Still don't forget to fix flash.lua.

**Comment by Hotrian** [comment]
I had originally misread your issue, but I was able to reproduce the error on line 61. This will be fixed in the next release, thanks for reporting it! You can close this issue yourself, but only a few others (not me) will be able to close it.
