### ISSUE TITLE
Argument objects do not support Integer objects.

### ISSUE THREAD

**Issue by ds84182** [MightyPirates/OpenComputers#797]
So I was making an Arch for OC, and this specific arch has no way to modify floating point values in a fast way, So everything is integer based. But then I found out that if I pass an Integer object into a function like Machine.invoke, it yells and screams at me because it can't convert the Integer object into an integer... T_T. A change I would propose is to use the Java Number type for handling numbers, since it is a subclass of all number objects, and it exposes methods to convert numbers into native formats.

**Comment by fnuecke** [comment]
Can you tell me where exactly it failed? (Class and line/stacktrace)
