### ISSUE TITLE
Redesign Adapter Block

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#8]
I'm planning to change how the adapter block works. As it is now, it's basically an all-in-one magic block that supports whatever there are drivers for. The idea is to give it an inventory for one or more expansion cards instead.

This obviously raises the issue of the Redstone I/O block becoming redundant. It'll probably be changed to be a lot cheaper than it is now, but to only support simple redstone signals, no bundled signals.

**Comment by fnuecke** [comment]
So, I've been thinking, and just allowing cards to be put in the adapter brings a whole host of new issues with it, for example network cards in adapters would be really weird. Instead I'm now leaning towards adding a GUI with a "phantom" slot that can be used to set a block type for which the adapter should be used. This way you could still control multiple blocks of the same type with one adapter, but you'd have to at least have one adapter per type of block, making it a little less... magic.

**Comment by LordFokas** [comment]
Sounds good.
Magic blocks are just plain stupid... _cough cough_ BC Quarry _cough cough_

**Comment by fnuecke** [comment]
Done, waiting with merge to fix some of the reported bugs and release a final 1.0 patch.
