### ISSUE TITLE
Robots with tools

### ISSUE THREAD

**Issue by applejag** [MightyPirates/OpenComputers#80]
Noticed that when a robot does
`robot.use()`
it like tries 6-9 times, I don't know if it tries all sides of the block or like 9 segments of the block side .. ?

But anyways it apparently tries multiple times before returning false, and so if you stick like a IC2 mining laser in it and do robot.use it shoots similar to the mining lasers scatter mode. I don't know if its possible but make robot.use return true if it successfully used the item, not only if it successfully clicked a block.

**Comment by fnuecke** [comment]
Yeah, that's the "autodetect" if no side is explicitly specified. I'll add a more sophisticated "has the item changed" check in there to catch mining lasers and co. For now you can avoid this by explicitly providing a side like so: `robot.use(sides.front)`.

**Comment by fnuecke** [comment]
Closed with 8643fb4.
