### ISSUE TITLE
Total Fail in dev...

### ISSUE THREAD

**Issue by SeniorFight** [MightyPirates/OpenComputers#801]
"computer.getBootAddress() is a nil value, init.lua error"

my dreams became false...
To make a gui based operating system....

**Comment by fnuecke** [comment]
Uhm, what?

**Comment by SeniorFight** [comment]
computer = component.proxy(component.list("computer")())

list of methods:

beep isRunning start stop

should be much more.

i need to use primitive 'computer = computer' to make it work ... properly.

like:

computer = computer

invoke(computer.getBootAddress etc...

**Comment by fnuecke** [comment]
There's a computer component and then there's a computer API. Just use whichever you need.
In your case just call `computer.getBootAddress()` and you're good.
