### ISSUE TITLE
Customizable Variables for components

### ISSUE THREAD

**Issue by SeniorFight** [MightyPirates/OpenComputers#807]
Can You add, in the OpenComputers.cfg (in configs folder), options to change:

Memory[tiernumber] = ... (kb) > set the memory added by the component
HardDrive[tiernumber] = ... (kb) > set the max memory for hard drive of [tiernumber]

and so on...

and force to use the server .cfg for these options (it should overwrite client's options anyway).

it would be sort of more "customizable"
of course, it's just something optional, don't rage if it's something you don't mind to do ..

**Comment by fnuecke** [comment]
Next time, please take the time to check before suggesting something something that's [already](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/application.conf#L137-L148) [there](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/application.conf#L754-L763).

**Comment by SeniorFight** [comment]
Sorry, didn't notice :/
