### ISSUE TITLE
Liquid Dupe Bug

### ISSUE THREAD

**Issue by ghost** [MightyPirates/OpenComputers#810]
"Today I found a tekkify dupe bug. Here is how the bug works:
1. Make an open computers robot with the "tank upgrade".
2. Place the robot over flowing liquid. For example, dig a 2x1 hole. Place one bucket of lava in the hole, and place the robot over the other square.
3. Tell the robot to drain the liquid beneath it. Easiest way to do this is to do:
   /# lua
   lua> robot.drainDown()

The robot will pick up one bucket of liquid into its internal tank, but the source block will continue to exist, and the liquid flow will be replaced. You can then use a fluid conduit to pull the liquid out of the robot into a normal portable tank, or whatever.

I wrote a program that repeatedly does drainDown(), and ended up getting 128 buckets of lava very quickly. I then tried the same thing with molten ardite and that works too, so the bug can be used to duplicate anything that can be a liquid.

I think the open computers dev should be able to fix this pretty easy. He just needs to check if the liquid is a source block before allowing the drain operation to work."

User-reported bug, re-created in Forge SSP: http://i.nentify.me/mR4ZggDs.png

OpenComputers 1.4.3.22

**Comment by fnuecke** [comment]
Ah, didn't consider the fluid registry would also return the entry for non-source blocks. Thanks for the report!

**Comment by paulbatum** [comment]
(I'm the user that found this dupe issue) 

This is like the fastest bugfix ever. Thanks for being so awesome (and making such a great mod!).

**Comment by fnuecke** [comment]
Thanks! My pleasure :-)
