### ISSUE TITLE
Feature Request: Support for Super Massive Tech

### ISSUE THREAD

**Issue by Keridos** [MightyPirates/OpenComputers#813]
Could you please add support for the Super Massive Tech Blocks like the Black Hole Storage, can store up to 2^40 Items and millibuckets of fluids at the same time. Also maybe support for the Black Hole Hopper and the Star Harvester would be nice. Star Harvester is just a energy generator based on stars. Black hole hopper is a gravity based hopper that can suck in nearby items and filter them, if I am correct.

**Comment by Kilobyte22** [comment]
What do you mean by support?

**Comment by Keridos** [comment]
Currently the Black Hole Storage Fluid amount cannot be read by the component it currently has. Only the inventory seems to be detected.

**Comment by fnuecke** [comment]
Did you insert a tank controller upgrade into the adapter? (and used that)

**Comment by Keridos** [comment]
Oh is that needed for even getting any information about the tank?
update: I have a tank controller now, checking that one atm.

The Tank Controller cannot find any tanks apparently...

**Comment by fnuecke** [comment]
It works fine for me when I test it with BC tanks - make sure you're using the `tank_controller` component, not the one of the block.
(And yes, having the upgrades in the adapter is somewhat unintuitive, but robots would feel discriminated against otherwise :P This implementation may change again at some point, but for now that's how it is)

**Comment by Keridos** [comment]
No, it does not work for me. Try using the Black Hole Storage... That one does not work at all for me, the tank controller does not even recognize any tank.

**Comment by fnuecke** [comment]
[Works perfectly fine for me](http://imgur.com/46uoxNJ,Rm6ubUK,WjAa7Ya). So you're either doing it wrong, or there's something else in your modpack breaking things? Tested with SMT 0.3.0-alpha-106.

**Comment by Keridos** [comment]
Oh I think i see the issue, I did not try to specify a side for the getFluidInTank method.
