### ISSUE TITLE
Screen as microblock.

### ISSUE THREAD

**Issue by PowerOfTech** [MightyPirates/OpenComputers#814]
I think this should be a tier 2 screen, which can't generate "touch" and "walk" event and can't have attached keyboard. It should be connected to the cable, as terminals in AppliedEnergistics 2 connects to fluix cables, and used as information screen.

**Comment by Kilobyte22** [comment]
Can you name a place where this would actually be more useful than a regular screen?

**Comment by MyNameIsKodos** [comment]
General displays would be a valid use.  Full sized screens seem kind of clunky for something as simple as a meter showing how much power you have stored, or the time, or what have you.

**Comment by Kilobyte22** [comment]
Well, you still have the cable attached, so it still requires a full block. Only reason i see would be where you only want to see front panel. I am not sure how the use/work ratio on that one would be either.

**Comment by fnuecke** [comment]
I don't really want to add more multipart blocks, to be honest, at least none that only work if FMP is present. And that would definitely fall into that category. And I won't roll my own multipart system ;-)

**Comment by Vexatos** [comment]
@fnuecke OpenMicroblocks :sunglasses:

**Comment by fnuecke** [comment]
I see what you did there...
