### ISSUE TITLE
Make Touch events return floating point values instead of integers

### ISSUE THREAD

**Issue by cinder1992** [MightyPirates/OpenComputers#816]
after discovering how to render square pixels on an OC monitor using halfchar blocks, I was pretty shocked to discover that the touch event returns integer-only values instead of floating point X/Y coordinates.

This should either be made standard or an enable-able mode for the touch event or GPU.

**Comment by fnuecke** [comment]
Hmm, I guess that could be something exclusive to T3 screens. Not sure if that'd break existing programs, though... how common is it to check for exact coordinates vs. areas? I'd assume the latter is the more common case, but still.

**Comment by cinder1992** [comment]
I was thinking it could be some kind of expansion card that generates it's own touch event to avoid breaking people's code.
