### ISSUE TITLE
Changing primary keyboard behaving weirdly when mixed with a keyboard signal.

### ISSUE THREAD

**Issue by mpmxyz** [MightyPirates/OpenComputers#818]
Hello, what a nice mod you have here...

For this bug you need:
-a working computer setup with a screen and 2 keyboards

What I did:
1. execute "primary keyboard 'address'" to change the primary keyboard
2. goto 1 if the bug did not appear

What I expected:
The command above should do its job and output the address of the new primary.

The Bug:
The bug is appearing randomly and it depends on the keyboard being set as a primary.
When it happens, I get this: https://www.youtube.com/watch?v=Z86V_ICUCD4
or in the shell:

> primary keyboard
> 86add8c2-2fbd-4eae-ad01-99ebe002bacf
> primary keyboard 425c57e0-dbb6-4168-be80-4c6f4fb5e4b5
> 86add8c2-2fbd-4eae-ad01-99ebe002bacf

I already traced down the bug for you. :)
So here is what happens:
1. You hit enter; the command is run.
2. primary.lua calls component.setPrimary.
-> It clears an entry in the primaries table
-> and starts a timer to refill it later.
3. primary.lua calls os.sleep.
4. You now release the key.
5. os.sleep pulls the corresponding event and calls the listeners.
6. onKeyDown from boot/92_keyboard.lua is called.
-> It calls component.isPrimary.
-> component.isPrimary calls component.isAvailable.
7. component.isAvailable is called.
-> It checks the primaries table.
-> It doesn't have a primary listed there. (The timer hasn't finished yet.)
-> Because of that it executes the following line:
8. 'component.setPrimary(componentType, component.list(componentType, true)())'
That means that component.setPrimary is called again.
But this time with the first component in component.list and not with the argument given by the user!

There is also another side effect: This second call restarts the timer and therefore the os.sleep from primary.lua isn't necessarily long enough to wait for the primary change to happen.
This means that the primary table isn't setup when primary.lua calls component.isAvailable.
(which also calls the line from point 8; but it is smart enough not to repeat itself.)
The program primary.lua therefore sometimes reports "no primary component for this type".

I hope this helps.
I had my fun hunting that one. :-P

**Comment by fnuecke** [comment]
Thanks for digging into this! I was afraid that timer workaround would come back to haunt me. Now if only I remembered why I needed it in the first place...
Welp. Adding a check in `isAvailable` seems to fix it, so let's go with that :P
