### ISSUE TITLE
"Gadget" equipment slot

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#819]
This has been brought up and I think it's worth discussing: the prospect of having OC add some kind of "gadget" equipment slot. The context was talking about [OpenGlasses](http://starchasers.pl/OpenGlasses/doku.php) eating up the helmet slot.

The main points to clarify are IMHO:
- General interest in such a slot.
- Would this even be desirable, or is such gadgets taking up a normal equipment slot preferred? (For potentially eccentric notions of balance :P)
- What else could this be used for? If it's just for one item it wouldn't be justified.

The alternative solution - given a solution is needed, of course - would be for mods adding such gadgets to allow combining them with some kind of armor maybe?

Either way, ideas and feedback very much welcome.

**Comment by Vexatos** [comment]
I think things like OpenGlasses glasses should properly take up the helmet slot (and gadgets like this should generally take up normal slots). There really is no reason in adding a new slot, there is more than enough space in your inventory by default. I don't think it would be useful at all.

**Comment by lordjoda** [comment]
I think gadgets like glasses should not be equipped in the helmet slot, as I can wear glasses while wearing a hat or something. Or to put this more in the Minecraft world, as I see it, the standard equipment slot should be used for everything "armor" related (ore also radiation, poison etc., but utility things like glasses don't "fit" in this description)
It might be interesting to make gadgets slots available to more then just OC addons and more something like "FMP" in the terms that it is a api that can be used by multiple mods, without OC beeing required. (This then could have slots like glasses, watches and what else comes to mind)

**Comment by Voidi** [comment]
I agree with lordjoda. Equipment other then arrmor weapons/tools in your hand could have a seperate slot.
But: we didn't need just another inventar slot, at some point the inventar gui is not width enough.
My recommendation: use extra slots from other mods if installed, else use the normal Slots.
Possibilities: Tinkers Construct, Baubles

**Comment by Kilobyte22** [comment]
i actually think @Voidi is right, we have to ensure however that one does not have more than one of those slots at a time (aka use first mod that is detected, with override setting in config file).

**Comment by Vexatos** [comment]
If Baubles or TCon is installed, use these, if not, use helmet slot -> Problem solved
I agree with that, there really is no reason for YET another mod to add additional slots...
@fnuecke If you were to add a new slot, it should be in a seperate mod (OpenGadgets or something) which people can then make compatible with their mod.

**Comment by Kubuxu** [comment]
As I am helping @marcin212 I must say: We rather won't play with Baubles and/or TCon compatibility. It would require replicating putting on/out code which causes increased complexity. I also don't think Baubles is correct place for gadget like OpenGlasses.

**Comment by fnuecke** [comment]
The mods providing gadgets re-using slots from other mods would be great, I agree. Mostly because it means no work for me :P OpenGadgets also sounds fine to me, but I won't be the one making it.
If Baubles/TCon doesn't suit the theme, maybe Galacticraft? Are there other "tech" mods with additional slots?

**Comment by Kubuxu** [comment]
Problem is that nothing will suit well as everyone created slots for themselves.
TCon for its augments, Baubles for magical jewellery and Galacticraft for spacesuit.

**Comment by Voidi** [comment]
right @Kubuxu but when everybody create there own Slots and Inventory Tabs, this would produce a new Minecraft Hell(in terms GUI-Interface and interference with shortcuts), if you play with many of these mods.
The best way would to have an API, like with other things from Forge. Maybe it is possible to work with the Baubles Author together to create some Kind of Framework (One Inventory GUI-Tab, configurable Slots)

**Comment by fnuecke** [comment]
Welp, since the general consensus appears to be leaning towards "maybe, but not in OC" I'll be happily closing this (because it means less work for me :P).
