### ISSUE TITLE
Potential Issue

### ISSUE THREAD

**Issue by natedogith1** [MightyPirates/OpenComputers#820]
From what I understand of how the new boot on modem message thing works (and this is from reading the code, not actual testing) it will boot whenever the message contains a subset of the required string. So, if I were to do modem.setWakeMessage("test") and turn off, and then have another computer do modem.broadcast("t") my computer would boot when it shouldn't. (I think this is the relative code spot thingy) https://github.com/MightyPirates/OpenComputers/blob/4e33221e9809bfb1d206ca5f080fb9294bad523f/src/main/scala/li/cil/oc/server/component/NetworkCard.scala#L134

I should probably just PR this, but I'm being lazy right now.  Also on the topic of things I should PR, check the comments for drones in the config, 'cause the drone assembly config options mention microcontrollers.

**Comment by Kilobyte22** [comment]
I actually went ahead and tested it. With the wake message set to `wake` it _only_ reacts if i send the message `wake`. It does not for any other, neither `w` nor `wake_`. So there is likely some logic somewhere else to prevent that from happening.

Test Setup: 2 computers, each with regular networking card, each on a seperate network which then are connected with a power distributor and a switch. Messages are sent using `.broadcast()` on port 123, version [MC1.7.10-1.4.5.344](http://ci.cil.li/view/All/job/OpenComputers-dev-MC1.7.10/344/) in production environment

**Comment by fnuecke** [comment]
Thanks for having a look! As Kilobyte's test showed, this is fine though - i.e. it will only match the exact wake message, because `wakeMessage` is a Scala `Option`, and its contains method is defined such that it returns true if it has a value and that value equals the specified one.

Edit: oh, and I will have a look at the config. Thanks for the pointer.

**Comment by Kilobyte22** [comment]
okay that one is a bit trippy xD I totally forgot scalas Optional is a collection.

**Comment by natedogith1** [comment]
Ah ok, that's a tad confusing (though it's not like most people will be reading the code to figure out how things work (I think))
