### ISSUE TITLE
Increased Resolution & Color Depth for Remote Terminals

### ISSUE THREAD

**Issue by Eunomiac** [MightyPirates/OpenComputers#822]
Could the Remote Terminal get a buff in resolution and color depth at the highest tiers?  I raised this issue in my eighty-three trillion-word magnum opus (issue #700), and fnuecke somehow managed to wade through that wall of text to bring the discussion to this point:

> Adding higher/creative tiers of the remote terminals/tablets is something I might consider, but I'm not sure they'd make very much sense - there are comparatively few people who have screens with a resolution that can display T3 screen GUIs without downsampling the text, making it pretty much unreadable.
#### Resolution

I certainly defer to the technical limitations you raised, but I still find the 25-line maximum on the Remote Terminal to be very limiting.  The jump from T2 resolution (80x25) to T3 resolution (160x50) is very big (four times the space!), so I wonder if this is a Goldilocks issue---i.e. T2 is too small, while T3 is too large?

Might there be a way to implement a "just right" maximum resolution for top-tier Remote Terminals, lying somewhere in between T2 and T3?  I'd suggest 128x40, which I'm using on my T3 screens (and which looks pretty good in GUI-mode when running Minecraft at lower resolutions); 112x35 is another possible sweet spot that retains the 3.2 width-to-height ratio.
#### Color Depth

I believe Remote Terminals currently have 4-bit color depth, the same as a T2 Screen.  Any objections to raising this to the 8-bit color depth of a T3 Screen, when connected to a server of a sufficiently-high tier?

PS:  I made it through a whole issue post without saying "adventure map"!
PPS:  Er, _almost_.  (Dammit.)

**Comment by fnuecke** [comment]
Ah, I thought there was still an issue for that explicitly, but it was actually in #733 where this was talked about. Yeah, when I ever get around to implementing floppy drives in tablets, remote terminals would most likely receive a buff to their "screen" tier, to avoid making them completely irrelevant.
