### ISSUE TITLE
Advertisements! No wait. Achievements!

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#823]
They look so similar.

Anyway. The achievements branch has been catching dust for a while now, mostly because of lack of (realistically realizable) ideas. Right now it's pretty much only rather boring "craft X" things.

So here's a call for ideas. Feel free to go crazy, just expect things to get shot down if they're technically infeasible too complicated to implement or require too much bookkeeping overhead ;-)

One of the problems we ran into when trying to brainstorm ideas so far, was that it's pretty much impossible to reliably tell who caused a computer to do something. E.g. an achievement like "Light a lamp using a redstone card" cannot really be attributed to a single player. A potential solution might be to give it to all players in a vicinity of the computer that triggered this, but I'm not _quite_ happy with that solution. Maybe someone has a better idea?

Either way, input very much welcome.

PS: also, one idea that came up was to add some high tier achievements with actual "rewards", e.g. the pet robots (which would be server-local of course).

Suggestions so far:
- [ ] Make a maxed out T3 server run out of memory.

**Comment by Voidi** [comment]
Problem 'Who get's the Achievment': maybe the player who access the computer at last? This would player encourage to explicit set accounts to prevent stealing achievments.
Or some achievments require to use a function while you are in the screen gui.

PS: I thougt about suggest you this idea (with pet robots), by myself, since on nearly every Minecraft video on your youtubechannel someone is asking how to get these robots.

**Comment by LordFokas** [comment]
I agree with that. Set up user accounts on computers, and bind them to the player. when a computer lights a lamp, if it's on a bound account (e.g. anything not root), trigger the achievement.

**Comment by NPException** [comment]
Once you sorted out how to assign the achievements, I would suggest one that imediately came to my mind when I saw this posted issue:

"Maxi Modded Minecraft Server" - Getting a Tier 3 Server with maxed out RAM to run into an Out-Of-Memory error :D

**Comment by Voidi** [comment]
@NPException42 shame on me that I didn't play OC long enough yet. But are there other nice errormessages? If not yet implemented we need a nice Bluescreen and associated achievement.

**Comment by LordFokas** [comment]
Linux doesn't BSOD, the kernel panics and core dumps.

**Comment by rmellema** [comment]
OpenOS does BSOD. At least it did last time I played :/
But that should be fixed into a kernel panic imho :P

**Comment by Pwootage** [comment]
Another option: Whoever placed the computer. At the very least this should allow for achievs in single-player.

**Comment by fnuecke** [comment]
Hrm, using the user list would be nice, true. That would require people to actually use it, though. Not sure whether that's a good or a bad thing :P I guess it's time for me to take on #767 and maybe add some way to change the permissions via the GUI, too.

**Comment by LordFokas** [comment]
@fnuecke you're going to take on an issue that's also a Boing aircraft? Careful with altitude!
Also, this is totally not productive. I'll shut up now.

**Comment by Vexatos** [comment]
@fnuecke It's not about using. If achievements force you to use a feature of a mod, it's good! Also keep in mind that achievements are purely gimmicks and noone will do them for anything other than fun. Having to use the userlist isn't a problem there.

**Comment by LordFokas** [comment]
I have to agree with @Vexatos here. Also, some of them should be very hard to do, because the whole point is to have something to show off and brag about, so while having some easier ones is cool to ease players into it, they can't all be easy.

**Comment by fnuecke** [comment]
Good point you have there. Still feel I should put some work into the permission system and add at least some config options to the GUI anyway, so I think that'll come first. Even though I loathe GUI coding... maybe it's time to build a proper framework for that... (and no, no third-party dependencies :P)

**Comment by LordFokas** [comment]
I was about to tell you how awesome CoFH GUIs are... damn :(
Still they come in CoFH Lib, and you can build against it, so it's not like depending on a mod :p 
I've actually been using those and made a few custom components, they are great.

**Comment by fnuecke** [comment]
Yes, that remark was exactly in anticipation of that ;-)

**Comment by PowerOfTech** [comment]
New achievement: Kill wither(or endergragon?) using drone and leash upgrade!

**Comment by Sbotkin** [comment]
1. «Indian Code» — get first error.
2. «Gipsy Quadro» — steal a horse with a drone :dancer: 
3. «TMNT»... Oops, this isn't CC :)
4. «Connected» — first sent message. —> «Radiowaves» — first wireless sent message —> «To Cyberspace... and beyond!» — first connection via Internet.
5. Mod-themed achievment —> «Even more digital!» — call any AE2 method.
6. «No more acoustics!» — call any adapter-noteblock method.

**Comment by Shuudoushi** [comment]
As far as a way to figure out who to give the achievement to, why not write the player data of the last player to click on a computer to the computers NBT?

**Comment by eslachance** [comment]
How does AE does it when it triggers achievements such as using more than 8 channels? Is it the player that places the 8th item that uses a channel?

**Comment by fnuecke** [comment]
I'd assume so.

**Comment by S0ZDATEL** [comment]
New achievements:

- Tin Woodman. - Force the robot to cut the tree down.
- Capacious. - Accumulate a HUGE charge in the capacitors.
- Hacker. - Use a wireless terminal.
- Large screen. - Create a maximum large multiblock screen.
- Surprise! - Get a gift.
- Motherboardf***er. - Blow up the computer.
- What is this? - Find a floppy disk in the dungeon.
- Better than  stylus. - Shoot touchscreen monitor with an arrow from a distance of 30 blocks.
- Not on my watch! - Hit another player who uses your computer.
- It's me. - Add yourself to the list of users of the computer.
