### ISSUE TITLE
sh.lua ignores io settings

### ISSUE THREAD

**Issue by natedogith1** [MightyPirates/OpenComputers#825]
if I use io.input or io.output to set a new input/output handle, the interactive shell doesn't use it and instead uses term's functions.

**Comment by fnuecke** [comment]
It kinda has to, to allow using a custom command history and tab completion.

One solution I could provide is to add a command line option that forces it to use the plain `io.*` methods.

**Comment by rmellema** [comment]
What about a readline like library for OpenOS? It could decide if the current io.input() is interactive(aka uses term.read) and only then support history and tab completion and otherwise just read from io.input()

This does should implementable, and it would solve this issue.

**Comment by gjgfuj** [comment]
Couldn't term.read use the io.\* methods?

**Comment by Kubuxu** [comment]
@gjgfuj No it can't as io.\* can't handle UI.

**Comment by gjgfuj** [comment]
@rmellema said: "It could decide if the current io.input() is interactive(aka uses term.read) and only then support history and tab completion and otherwise just read from io.input()", couldn't you just implement that in term.read() instead of another library?

**Comment by rmellema** [comment]
The only way to read from a screen is to use `term.read`. And the only thing that `term.read` should do is read from the screen. So it can't use io.\* because that isn't its purpose. A third library could be written to do that, but that isn't the goal of `term.read` or `io.read` for that matter.

**Comment by Kubuxu** [comment]
In Unix program (fe. bash) decides if file descriptor of opened file is interactive (tty) or not (file or fifo) and works in corect mode.

**Comment by gjgfuj** [comment]
But, term.read is what does the history and tab completion. It is not what reads from the screen, it is the readline library.

That is it's purpose @rmellema

**Comment by magik6k** [comment]
Done in #912
