### ISSUE TITLE
Beyong minecraft's graphics

### ISSUE THREAD

**Issue by SeniorFight** [MightyPirates/OpenComputers#826]
We need to go faster than light.
We need graphics card that instantly draws anything.
We need graphics card that can switch between 1 x 1 pixel size and 1 x 1.5 character pixel size
We need graphics card that instantly clears screen, then draws without any "slow down".

We need tier 3 graphics card that can handle all this.

WE NEED THIS:

gpu.setMode("draw") -- Instant drawing, no characters, allowing GUI BASED OPERATING SYSTEMS

-- and symmetrical 1 x 1 pixels, not those bugged 1 x 1.5 character sized pixels...

-- Like GalactiCraft does with the ESC > Team Menu > Flag Drawing

gpu.setMode("char") -- Slow drawing, but with characters, allowing TEXT BASED OPERATING SYSTEMS

gpu.set -- We need FIX, because it has always 0.2 second of delay between draws.

Please, break the barriers, make something that will draw instantly and SYMMETRICALLY.

Thanks from advance.

EDIT : JUST BY THE WAY, I am already working on an operating system, but it's hard to display an image from file INSTANTLY, so I do it only one time at begin of system. I try to make a "driver" that uses FPS style drawing (clears, draw, clears, draw, everytime an event is pulled).

I'll MAYBE upload it if you do the effort to fix the "delay" while drawing.

**Comment by LordFokas** [comment]
You've said too much of "we need" and not enough of "I'll do".
I'm pretty much sure if you were to implement that yourself and sent a PR Sangar would merge it, given the code was decent.

Now, while it's OK to propose stuff like that, or even absurdly hard to implement stuff, it is not OK to demand, and you sound a lot like demanding. I'd just advise in the future you keep a more ... friendly tone.

**Comment by Kubuxu** [comment]
@LordFokas do you also feel that people who SHOUT are thinking that it helps?

**Comment by LordFokas** [comment]
I'm pretty sure they believe there's a benefit in that. Doesn't mean there actually is one.
I don't think people would go through the effort of shouting if they didn't think it'd help. And I mean both vocally (although that's more of emotional) and holding down Shift.

**Comment by fnuecke** [comment]
I did bump the GPU draw call speeds quite a bit recently. So make sure you're running an up-to-date version of OC. Note that this was after finally getting around to doing some proper bandwidth usage testing. So no, I won't have them go any faster than this. Unless someone can provide an implementation that is faster while at the same time not exceeding the current bandwidth and processing costs (CPU load).

I believe @gamax92 was working on a "creative tier" kind of GPU that circumvents most limits. You may want to give that a shot. Given it has a release, which I don't know.

Alternatively you can always try to come up with clever drawing logic that optimizes the number of draw calls you use to speed things up. Encouraging that is the other reason these limits are in place.

**Comment by gamax92** [comment]
Well my Graphics Card was mainly to abuse TextBuffer stuff like setMaximumResolution, not to be fast.
If you want to do graphical stuff as in pixels, I'd recommend OCLights2: https://github.com/gamax92/OCLights2

The current gpu speeds are imho fast enough to do image drawing btw. I've had entire 160x100 images drawn in 1-3 seconds (ignoring palette changing), it used to take about 20. (iirc)
