### ISSUE TITLE
Feature Request: Drone Serial Number or Owner Name

### ISSUE THREAD

**Issue by LordFokas** [MightyPirates/OpenComputers#827]
Very well, as you probably know, my mod, StargateTech 2 features shields that filter the entities that can go though. I'd like to add support for OC's drones, but for that I need to be able to identify the drones as unique entities.

Allow me to explain:
I could categorize drones as vessels and allow either all of them or none through, but since they are controlled by players it's unsafe, so I need players to have a way to identify their drones and list them in the exceptions, allowing their drones to go through. If "enemy" players hijack a drone and use it to do evil stuff on the inside of shields I'm totally fine with that.

Implementation:
There are 2 ways we could do this:
- The Drone exposes a method in its Java interface that returns the name of his owner. This is preferred because it would automatically reflect a player's permissions on his/her drones.
- The Drone exposes a method in its interface and in the OS that returns its Serial Number, which can be used to list it in the shield's exceptions. This is a more manual process and doesn't fit as well with the shield's implementation, but I'll accept it if you tell me the first one isn't practical.

Thanks in advance :)
OC Master Race! \o/

**Comment by fnuecke** [comment]
Hmm, I can see either of those working like this:
- For player names, use the drone's user list: `((api.internal.Drone) entity).machine().users()`. Requires the user to `useradd` herself, but would work via player names.
- For the UUID you can also use what's the `computer.address()` on the Lua side via `((api.internal.Drone) entity).machine().node().address()`.

**Comment by fnuecke** [comment]
In case I was unclear, the two approaches mentioned above are already possible - will those do, or do you need something more specific? (And if so what and why ;-))

**Comment by LordFokas** [comment]
Nah, that's good enough.
I only required one of the two, and you got me both. Thanks a lot.

I have one question though, since we got a user list and not an "owner" is there a way to know under which user account is this drone running?

**Comment by fnuecke** [comment]
Which player actually placed the drone is currently not stored, no.
All entries in the user list can basically be seen as "owners".
