### ISSUE TITLE
EEPROM "breaks" if placed into computer before Lua-fying

### ISSUE THREAD

**Issue by WazWaz** [MightyPirates/OpenComputers#828]
If an EEPROM is mistakenly placed into a computer (tested on computer without power, if that matters), it can then not be turned into a Lua EEPROM. This seems wrong, especially since it's such an obvious mistake for a player to make.

**Comment by fnuecke** [comment]
Ah, damn, that's the re-crafting / clone-crafting logic interfering. Thanks for letting me know!
