### ISSUE TITLE
Soundcard

### ISSUE THREAD

**Issue by Aedda** [MightyPirates/OpenComputers#831]
It might be fun to have a Soundcard. Installing one would allow playing multiple beep tones at the same time, in triangle, square, and sine wave patterns, and would allow continious tones as well as being able to stop tones. For instance...

soundcard.playTone(frequency, channel)...

soundcard.mode(modes.triangle)

soundcard.playTone(220, 1)
os.sleep(2.5)
soundcard.playTone(380, 2)
os.sleep(0.75)
soundcard.stopTone(1) or soundcard.playTone(0, 1)

Perhaps also be able to modulate the volume of the tone...
soundcard.playTone(220, 1, 0.75)
soundcard.setVolume(2, 0.50)

Increasing the maximum frequency might also be useful here.

Also worth considering would be a higher tier of soundcard allowing playing pre-compiled patterns of sound data.

sound_data = []
channel=1
for tone=60,2000 do
  sound_data[i] = [tone, channel, volume/2000]
end
sound_data[2001] = [0, channel, 0] -- to stop the sound once played
playspeed = 20 -- sound commands per second, 20 = one per tick obviously
sound1 = soundcard.compile(sound_data)
soundcard.play(sound1, playspeed)
This would play a tone over 97 seconds that ramps from 60Hz to 2kHz and a volume of 0.03 to 1.0 on channel 1 and then stops.

The soundcard could have a soundbank to store a few precompiled sounds for later retrieval/playback.

Ideally the precompiled sound would be binary data that could be generated manually or altered after creation and would represent the data that would be sent to the DAC on the soundcard.

**Comment by Vexatos** [comment]
Computronics already adds a Beep Card, allowing up to 8 computer.beep() equivalents at once. The Song API I updated to support that card allows playing pre-compiled music.

**Comment by Aedda** [comment]
Ah apparently it is, I overlooked this due to not being listed outside the Computronics change log at the time I opened this. Thank you Vexatos, I will try playing with this.

**Comment by fnuecke** [comment]
Yep, I think it'd make more sense to include this in one of the existing "sound cards".
