### ISSUE TITLE
robot.swing hangs sometimes

### ISSUE THREAD

**Issue by WazWaz** [MightyPirates/OpenComputers#834]
Under some circumstances, robot.swing() does not return.

Possible causes:
- GregTech bronze pickaxe
- moderately-full inventory

I've only noticed the problem with 1.4.5 and with GregTech, but normally my robots don't fill their inventory (I only give them one tool and have them return when it has low durability). Definitely it is hanging in robot.swing() as I print on either side. It only seems to happen after a while (when the inventory also partially fills). Switching to stone pickaxes avoids the problem.

Let me know if there is something I could check more precisely. I can easily reproduce it.

**Comment by fnuecke** [comment]
Hmm, assuming the robot doesn't crash and Minecraft doesn't freeze, this sounds like the tool is returning a very (very) large number for the time it takes to break the block it's trying to break.

Could you see if there's some pattern to the blocks it stops in front of? Could you see how damaged the pickaxe is? Could you try how long it takes to break these blocks when you do it yourself (with that very pickaxe)?

I'm not sure if this is actually a bug, suboptimal implementation or possibly intended behavior from GTs side, but a sane workaround might be to define a "maximum break time" that, when exceeded will just make the block appear as unbreakable and return false? (configurable, and assuming that _is_ the issue, ofc)

**Comment by Vexatos** [comment]
@fnuecke I know that GregTech tools calculate the damage they take by the block hardness of the mined block, you might need to add a special handler for GregTech tools, fortunately the GT API supports that.

**Comment by WazWaz** [comment]
When it stops, if I reboot and restart the dig it usually digs forward a few more (sometimes many more), so it's not a specific block. Usually it is stone in the cases I have found.

Today I got a case where the inventory was nearly empty, so that part of the report is a red herring. I've also comfirmed that regular iron pick axes (which can be crafted by not going via axe heads) work fine, so it's most certainly the GT tool.

**Comment by fnuecke** [comment]
Could you please get [build 358](http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/358/) and reproduce it with that? It should print a message to the console whenever a robot breaking a block takes longer than 10 seconds. The message will contain a bit of information about the involved block, hardness and tool strength vs block. When it appears, please post it here. Just to give me a better idea of where to start looking, code-wise. Thanks!

**Comment by WazWaz** [comment]
No message when it hangs. By console, I'm assuming you mean in the robot's terminal (computers within computers...).

**Comment by WazWaz** [comment]
Ah, in fml-client-latest.log ...

[10:24:57] [Server thread/INFO] [OpenComputers/]: Slow block break: block=tile.dirt, meta=0, hardness=0.5, strength=0.0, time=Infinity

**Comment by fnuecke** [comment]
Thanks! That's what I hoped it'd be, because that means I can just add a check for zero/very tiny strength and return failure.

**Comment by WazWaz** [comment]
Under what circumstances would the robot be "too weak"? It seemed random to me, but I'd like to confirm the fix.

**Comment by fnuecke** [comment]
It appears something in the tool-vs-block-strength computation goes wrong (maybe deliberately, I don't know). My usual first guess for apparently random bugs is threading, but I'm not sure how that could be related here.
