### ISSUE TITLE
Echo command doesn't do what is specified in man in OpenOS

### ISSUE THREAD

**Issue by Glomzubuk** [MightyPirates/OpenComputers#835]
The manual for "echo" says the following:

> echo "a b" > test
> Writes the string `a b` to the standard output, which is redirected into file `test`.

Instead that's what happends:
$ echo "a b" > test
a b > test

It doesn't create nor modify "test".

**Comment by fnuecke** [comment]
It does? Ugh, will need to change that. The default shell doesn't support piping, only `besh` does.

**Comment by MyNameIsKodos** [comment]
Last I checked, besh was pretty broken.  Has it been cleaned up and fixed in recent versions?

**Comment by fnuecke** [comment]
Last I checked it worked, so if that was after that and nobody fixed anything who knows :P
