### ISSUE TITLE
Add some kind of tesseract

### ISSUE THREAD

**Issue by kevinkk525** [MightyPirates/OpenComputers#837]
I had the idea of a computer part like a tesseract as a block with an id. So that you can send items to someone else using his tesseract-address. this block could have an inventory and the ability to send energy/fluids would be nice but not neccessary. 
I would like to hear what you think about this idea and whether it is difficult to implement.

**Comment by MyNameIsKodos** [comment]
I'm pretty sure you can interact with a tesseract using one of the available addons for OC already.  Having one with an inventory and having it be a component would be entirely too overpowered.

**Comment by kevinkk525** [comment]
yes maybe that is too overpowered but that depends on who you ask :D
you can interact with the TE tesseract but not as I would like to. You can not change frequency if it is set to private and you can not activate/deactivate it which makes the interaction almost useless.
And you can't send items with a pulic tesseract which is quite obvious therefore a tesseract component. would be great. It does not need to have a inventory. It could also just push into a nearby chest.

**Comment by Vexatos** [comment]
@kevinkk525 You can connect to the Dimensional Transceiver from EnderIO if you have Computronics installed, you can pretty much get/set anything that block provides.

**Comment by kevinkk525** [comment]
Thanks a lot. I did not have a closer look at the Dimensional Transceiver.
You can not add private Channels but at least you can activate/deactivate it.
So probably the decision about having a tesseract OC block will be no as it is not that important or maybe too overpowered. But I could understand that and at least I could tell my suggestion.
@Vexatos thanks for that hint!

**Comment by gjgfuj** [comment]
@kevinkk525 also it wouldn't really fit particularly well in OC.

**Comment by Vexatos** [comment]
I agree with @gjgfuj.

**Comment by fnuecke** [comment]
There's an addon that adds upgrades based on Tesseracts IIRC (see the forums).
It's something I (for the time being) feel doesn't have a place in "vanilla" OC.
