### ISSUE TITLE
Guest User permissions

### ISSUE THREAD

**Issue by kevinkk525** [MightyPirates/OpenComputers#838]
Is there a way to implement a function on a computer to allow access to the screen and keyboard for guest users but preventing them from cancelling the running program with ctrl+alt+c and maybe automatically cancel their permissions after that program quit running?

**Comment by gjgfuj** [comment]
+1 to that.

**Comment by Kubuxu** [comment]
As far as I know you can handle ctrl+alt+c by `while true do pcall(mainfunc) end`

**Comment by kevinkk525** [comment]
How is that supposed to help me disabling the effect of pressing ctrl+alt+c resulting in a stop of the running program?

**Comment by Kubuxu** [comment]
Oh, I was probably wrong. I though that error is thrown form program call. It is in event handler.

**Comment by kevinkk525** [comment]
Yes. Maybe it can be changed if you change something in openos but I did not have a look at openos...

**Comment by fnuecke** [comment]
You can override [`event.shouldInterrupt`](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/OpenOS/lib/event.lua#L163) for this, then make it inaccessible to the running program by only exposing a wrapper of the event lib, e.g.

**Comment by kevinkk525** [comment]
Thanks a lot! With that changed it is possible to have a guest access/freely availabe PC that nobody can terminate and manipulate (except your program is bad and can be crashed..)
