### ISSUE TITLE
Feature request: instant disassembling in creative mode

### ISSUE THREAD

**Issue by DirtYiCE** [MightyPirates/OpenComputers#839]
The Electronics Assembler will instantly assemble robots/drones in creative mode, but the Disassembler does not. I think it should (and also probably set break chance to 0). Alternatively, there should be a way to modify robots/drones after being assembled in creative mode (for example placing it in the assembler), because currently if you want to change something in a robot/drone you either wait ages till the disassembler disassembles it, or start to pick all items from creative tabs (since the assembler eats your item, even in creative), which is tedious and problematic if you have disks/eeproms with custom content...

As a workaround I can set `disassemblerPerItem=1` in the config, but it will ruin survival gameplay then...

Also: https://github.com/MightyPirates/OpenComputers/blob/5679150b8067924a8dd941b77df0b1caca302943/src/main/scala/li/cil/oc/common/tileentity/Disassembler.scala#L82: that should be a `>=`, since Random.nextDouble can return zero, and in this means that there's a very little chance to break items even when `disassemblerBreakChance=0`

**Comment by fnuecke** [comment]
I agree this would make sense, but there's no (good) way of checking for the player that inserted the item AFAIK. I could add something along the lines of shift-right-clicking the disassembler when in creative mode makes it finish immediately?

**Comment by DirtYiCE** [comment]
I think it's ok, if there's no better way.

**Comment by fnuecke** [comment]
I think I've found a non-terrible way to make this work. Testing now.
