### ISSUE TITLE
When i press the "Start Button" on the computer the game crashes.

### ISSUE THREAD

**Issue by emeraldhunter111** [MightyPirates/OpenComputers#84]

**Comment by fnuecke** [comment]
Welcome to Github. Let me introduce you to Golden Rule No. 1 when it comes to reporting crashes: logs or it didn't happen.
Also, please confirm this is when using the latest version of the mod (1.1.3 at this time).

**Comment by emeraldhunter111** [comment]
It did not give me a crash report, it just crashed.

On Wed, Jan 22, 2014 at 11:57 AM, Florian Nücke notifications@github.comwrote:

> Closed #84 https://github.com/MightyPirates/OpenComputers/issues/84.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/MightyPirates/OpenComputers/issues/84
> .

## 

-Adam Badura

**Comment by fnuecke** [comment]
There'd have to at least be the FML log.

**Comment by emeraldhunter111** [comment]
Nothing, it just took me back to the Minecraft Launcher.

On Wed, Jan 29, 2014 at 1:53 PM, Florian Nücke notifications@github.comwrote:

> There'd have to at least be the FML log.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/MightyPirates/OpenComputers/issues/84#issuecomment-33623184
> .

## 

-Adam Badura

**Comment by rmellema** [comment]
The FML log doesn't show when it crashes, but can be found in your minecraft folder(the folder where the saves and mods also go). It is called ForgeModLoader-client-0.log.
