### ISSUE TITLE
AE2 Bug

### ISSUE THREAD

**Issue by Keridos** [MightyPirates/OpenComputers#841]
When the ME system gets changed (placing a cable etc.), apparently the Interface for the controller still lists the old crafting jobs, but returns 0 for every single item stack size. So if you use that for autocrafting, changing the system while the computer is running leads to a lot of wrong crafting requests. 
Imo the getCraftables command should return nil when the system is currently updating or not reachable otherwise. Not sure though if this can be fixed on OCs side.

**Comment by fnuecke** [comment]
Hmm, that's odd. I'll look into it.
