### ISSUE TITLE
AE2 getItemsInNetwork

### ISSUE THREAD

**Issue by zeoril** [MightyPirates/OpenComputers#842]
``` LUA
local c = require("component")
me = c.me_controller
for _,v in ipairs(me.getItemsInNetwork()) do
   q1,q2,q3,q4,q5,q6,q7 = table.unpack(v)
   print(q1,q2,q3,q4,q5,q6,q7)
end
```

table.unpack(v) - returns 'null' for all values

**Comment by fnuecke** [comment]
Yes, because each item representation (here: `v`) is a map, not an array, i.e. you have key->value entries where the keys are strings, not integers, and table.unpack only works for sequences (numeric indices).
