### ISSUE TITLE
Allow robots to use debug card's runCommand with their own name.

### ISSUE THREAD

**Issue by Kubuxu** [MightyPirates/OpenComputers#843]
It would allow to use commands by robots on creative servers with per player permissions if robot name is set to username.

**Comment by fnuecke** [comment]
Hmm, how about allowing to bind the card to a player by shift-right-clicking it while holding it? That way they could be used in cases bound to individual players (robots can still be broken by all players to avoid griefing) which should make it a little more reliable?

Hmm, or maybe even bind on pickup? That actually sounds like the most secure way. Then allow clearing the binding by shift-right-clicking to allow OPs to spawn/insert unbound cards. Sounds reasonable?

**Comment by Kubuxu** [comment]
Of course.
