### ISSUE TITLE
Not recognizing installed lua eeprom on computer and robot

### ISSUE THREAD

**Issue by GoneNomad** [MightyPirates/OpenComputers#845]
Running on Kubuntu 14.04, Minecraft 1.7.10 x64, OpenComputers1.4.5.28, SSP game

I built a Tier 2 Computer, as in the 1.3 tutorial on youtube. Also a Tier 2 Robot.
I try to turn on both and they double-beep at me. The Analyzer says 'no bios found' on both.
I have the Lua BIOS installed in both machines (Shift-click into Case) plus the openos floppy in a disk drive next to the computer.

Only problem I see is that the lua eeprom and regular eeprom have the same id and crafting recipe. I tried to change the id number in the Opencomputers.cfg but could not find an entry pertaining to any item IDs.

Help me get this running, and I would be glad to write up a newer tutorial and tips guide on the OC forums.

**Comment by MyNameIsKodos** [comment]
Just for shiggles, try crafting the Lua BIOS EEPROM with a book to get a proper Bios EEPROM, and stick that in a computer to see if it still beeps at you.

**Comment by fnuecke** [comment]
IDs don't matter, the info is stored in the item's NBT tag (and welcome to MC1.7, where there are no ID configs anymore because Forge handles that automatically now ;-))

While it shouldn't really make a difference, please try crafting one, as Kodos suggested.
Alternatively, try cheating in the preconfigured testing robot (Creatix) and see if that boots.

**Comment by GoneNomad** [comment]
Crafting with a book gives back the same item, which still does not boot.
Creatix, howvever, did startup just fine (yeah!) Would the next step of action be removing mods one by one to find a possible conflict?

**Comment by GoneNomad** [comment]
Well, I got it working, but I do not know how. I scrapped that world and wiped the minecraft directory (it was a test world to check out mods, so stuff had been coming and going). In two new worlds with different mod sets, the bios (both spawned in and crafted) worked correctly.

During this, I have also learned about how there is a nice manual hidden in NEI, the correlation between an item's Label Color and its Tier Level, the subtle highlighting of useable parts in NEI and the proper crafting of a lua bios eeprom (thank you Kotos-Atoz!). All this and more will be going into a tutorial. I don't want anyone else to have this much trouble getting started on such an excellent mod.

**Comment by fnuecke** [comment]
Odd. If you're able to reproduce it at some point, let me know. If it's world-related and you can reproduce it with OC-only, a copy of that world would be great!

Thanks in advance for writing an up-to-date tutorial! I really appreciate it. The one on the wiki is indeed painfully outdated.
