### ISSUE TITLE
Crash when looking up the usage of items in NEI

### ISSUE THREAD

**Issue by xJon** [MightyPirates/OpenComputers#847]
Is it NEI's, or OC's fault?
Crash report: http://pastebin.com/hpFwtLws

**Comment by fnuecke** [comment]
It's OC. Caused by AE2's API changing and me using the wrong API class (namely the Api one instead of the AEApi one). Fix incoming.

**Comment by xJon** [comment]
Gotcha, thanks for quick reply. Waiting for an update.

**Comment by fnuecke** [comment]
All right, [build 367](http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/) should fix it, please give that a try.

**Comment by xJon** [comment]
Give me a minute :+1:

**Comment by xJon** [comment]
Good job @fnuecke :wink:
It fixed it.

**Comment by fnuecke** [comment]
Glad to hear it! Just in time to hotfix the release I was just in the process of making :-P

**Comment by xJon** [comment]
Yes I saw it!
I was just in the process of updating my modpack, checking that everything works. Glad I was able to help more people on the way! :)
