### ISSUE TITLE
filesystem.remove needs 2 calls for directories with symlinks + real files

### ISSUE THREAD

**Issue by mpmxyz** [MightyPirates/OpenComputers#849]
I found a bug in filesystem.remove:
It happens when removing a directory which has got:
1. a normal file / directory and
2. a symbolic link or a 'virtual directory' containing one
It then just removes all virtual directories and links but no real files and directories.

Example:

> mkdir bug/a #creates a real directory
> ln bug/a bug/b #creates a link
> ls bug
> a b
> rm bug
> ls bug
> a

This happens because filesystem.remove checks if it has to remove a virtual object and then doesn't care about the real filesystem anymore.
A solution would be to move the part for the real file system out of the 'else'
(Error handling and returning would have to be adjusted.)

**Comment by fnuecke** [comment]
Thanks! Next dev build should fix this.
