### ISSUE TITLE
Drones - No Bootable Medium Found: file not found

### ISSUE THREAD

**Issue by spideynn** [MightyPirates/OpenComputers#850]
Whenever I try to use the drones after using the EEPROM Lua Bios and the T2 Drone in the crafting table it doesn't start, and I looked at it with the analyzer and it told me `No Bootable Medium Found: file not found.` What am I doing wrong?

Latest version of OC, Windows 8.1 64-bit

**Comment by gjgfuj** [comment]
Yes, you need to code your stuff in a custom bios for the drones, you can't just use the default bios as that requires a bootable filesystem.

So use component.eeprom.set("script_to_run") on the eeprom.

**Comment by spideynn** [comment]
@gjgfuj Could I use OpenOS or I have to do my own? The documentation doesn't say much about them.

**Comment by gjgfuj** [comment]
@spideynn You cannot run OpenOS on a drone, OpenOS is too large and requires a size limit. Drones can run the same code Microcontrollers can. They have a specific limit so you cannot put too complicated programs on them.

**Comment by spideynn** [comment]
OK, thanks!
