### ISSUE TITLE
unnamed

### ISSUE THREAD

**Issue by lieven121** [MightyPirates/OpenComputers#851]
a lot off the blocks are called unnamed here is a pic 
![oc](https://cloud.githubusercontent.com/assets/7773244/5891125/ddcd6bcc-a482-11e4-8d92-b7f864c9e608.png)
i am using the newest build + have tested it whit OpenComputers-MC1.7.10-1.4.6.30-universal

**Comment by fnuecke** [comment]
I can't reproduce this. Does this also happen when OC is the only mod present? If it doesn't, could you please add mods back until it happens again, to figure out which mod causes this? Also, have a look at your MC logs, maybe there's a clue in there.

**Comment by lieven121** [comment]
will try this soon but I know if I have none installed the the crash of key things happens (my report called crash (closed))

**Comment by fnuecke** [comment]
Closing due to lack of feedback.
