### ISSUE TITLE
Suggestion: AE2 getItemByLabel(label)

### ISSUE THREAD

**Issue by Keridos** [MightyPirates/OpenComputers#856]
Currently We can only get a List of items in the network. So when we try to maintain a specific amount of items for some items, we need to iterate over the items we want to keep stocked, then iterate over the getCraftables table and after that iterate over the getItemsInNetwork table. With 150 craftables and 2200 items in network, the worst case scenario is about 330k iterations for EACH item we want to have maintained at a specific level. This results in extremely long computation times and currently there seems to be no way to alter this in any way. So I propose to add the function getItemByLabel(label) function that returns the itemStack of the item in the network. Label would be the one that craftables[entry].getItemStack().label would be. Alternatively use the internal name of the item, f.ex: minecraft:planks. Or add in both ways.

**Comment by fnuecke** [comment]
Hmm, maybe an optional parameter to the existing methods that defines a filter (like `id=minecraft:dirt` or `label=Bucket`)?

**Comment by theron61** [comment]
I would like the call to reference the database component as the match should take NBT into account. Further, how can we handle multiple references to the same item?

**Comment by fnuecke** [comment]
Using the db for this is a great idea. Not sure what you mean with 'multiple references to the same item'?

**Comment by Keridos** [comment]
Another way would be like the old bug was, but maybe return the itemStack that is in the Network as a separate table for the Craftables. That would be optional though.

**Comment by theron61** [comment]
I retract the multiple references question. I thought you could set multiple priorities on like patterns to have more than one way to craft the same item.  Even still, it should still be a single reference.
