### ISSUE TITLE
[Tablet Case] Interaction Upgrade/Feature

### ISSUE THREAD

**Issue by TinkerWorX** [MightyPirates/OpenComputers#858]
Allow the Tablet to detect left-clicks with the item.
Should fire a "use" event and optionally the x,y,z,id of a block it was used on.
Usages include setting a target for a program, executing a program at a specific user controlled moment, and similar usage situation.

**Comment by Vexatos** [comment]
what would x, y, z and ID be if you left-click air?

**Comment by TinkerWorX** [comment]
That's the optional part. If id is nil/0 or whatever invalid value is suitable, it was a left-click in the air.

**Comment by fnuecke** [comment]
I don't really like making absolute world coordinates queryable - hence the relative coordinates for the nav upgrade and geolyzer. So if anything those'd be coordinates relative to the device/tablet/player holding it.

I did consider adding an event along those lines, though that was more inspired by the analyzer. The actual data provided might depend on the installed upgrades. For example, the geolyzer upgrade would add some block information to the event data, the sign upgrade might add the text of a clicked sign, something along those lines?

**Comment by Vexatos** [comment]
I wouldn't want absolute coordinates either. Maybe add it as a feature to the nav upgrade?

**Comment by TinkerWorX** [comment]
I like those ideas. And I understand the reluctance to give absolute coordinates, but how would I use those relative coordinates to say, direct a robot to the selected location?

**Comment by fnuecke** [comment]
> Maybe add it as a feature to the nav upgrade?

Yeah, the nav upgrade injecting the (for it relative) coordinates sounds good.

> but how would I use those relative coordinates 

By having a nav upgrade with a copy of the same map in the robot - or another map with known frame of reference. Or maybe by using a Computronics radar upgrade to get the player's position (if that's possible? Otherwise let me know and I'll think about some kind of T2 motion sensor thingy) and go from there?

**Comment by TinkerWorX** [comment]
I'm fine as long as it's possible to compute the absolute coordinates. I've yet to play around with the position components in OC. So many features, so little time.

**Comment by Vexatos** [comment]
@fnuecke it is possible to get the distance between a player and the radar block. If a certain config option is disabled (it is by default IIRC), you can even get the x, y and z distance vector. You could disable this config option, hardcode the radar's position and there you are.

**Comment by MyNameIsKodos** [comment]
What about a T3 Nav card that would work with absolute coordinates, so you'd be able to use it as proper GPS?

**Comment by Vexatos** [comment]
No. No absolute coordinates whatsoever, it really ruins the game. There is a reason you only see those in Vanilla if you are using the debug screen.

**Comment by MyNameIsKodos** [comment]
How does knowing where you are ruin the game?  We have coordinates in real life and if the need arises can easily access that information, why shouldn't we be able to in a game?

**Comment by natedogith1** [comment]
The coordinates we have in real life are player (human) made.  Besides, you can just hard code the coordinates into whatever program your using, and it can use the hard absolute + the relative to find out the actual coordinates. (I mean, that's how computercraft's gps works). Speaking of, you could get your location, instead of with the nav upgrade, by setting up a gps system.

**Comment by Vexatos** [comment]
@natedogith1 I second this.
@Kodos-Atoz You might also try the Computronics radar block, it gives you  a relative distance vector measured from the radar block itself.

**Comment by MyNameIsKodos** [comment]
What is the range on the radar block though? I'm talking T3, super expensive Nav upgrade that would allow absolute coordinate tracking for things like telling the robot, drone, or whatever where to go, without a relative direction, but rather an absolute vector of coordinates.

**Comment by Vexatos** [comment]
@Kodos-Atoz You can set the range in the config.
