### ISSUE TITLE
[Severe] Server crash when removing experience upgrade

### ISSUE THREAD

**Issue by drheat** [MightyPirates/OpenComputers#859]
Built a small experience farm for robots with associated software. Nothing fancy, basically robot just sits next to a charger, has an enderchest to dump dusts in front of it and another one to pull ores to it's left. 

I wanted to know if the experience is stored in the robot itself (and thus lost on disassembling) or on the xp upgrade card. So I've built a robot with an upgrade card slot, inserted an experience card in it and started the thing.

When the robot reached level 1, I stopped my program then when I removed the experience card from the slot the server crashed. Here's the associated log:

https://gist.github.com/heatseeker0/e4c337058ada356e7e1b

Further information: The robot was powered on and charging at the time the card was removed from the robot GUI.

There is no crash if the card contains no XP. There is no crash if the robot is broken say with a pickaxe without opening it's GUI. Also there is no crash if a card containing XP is inserted or removed from the robot GUI while the robot is powered off and away from a charger.

**Comment by fnuecke** [comment]
Thanks a lot! Tracked it down to an issue in the logic for changing a connector's local buffer size.
