### ISSUE TITLE
InventoryController.getInventorySize returns nil for Sides.back

### ISSUE THREAD

**Issue by drheat** [MightyPirates/OpenComputers#860]
On a robot with an inventory controller upgrade, InventoryController.getInventorySize() incorrectly returns NIL for Sides.back (it's internal inventory). Without this function working properly there isn't a way to determine if more than one inventory upgrade is installed in the robot and thus making full use of robot's internal storage.

Other InventoryController or Robot functions work properly with Sides.back in the same robot.

**Comment by fnuecke** [comment]
I guess I can add that back for backwards compatibility if someone actually used that. Consider that deprecated, though. The preferred way is to use `robot.inventorySize()`.
