### ISSUE TITLE
Add InventoryController.compareToDatabase(slot: number, db:address, dbSlot:number)

### ISSUE THREAD

**Issue by drheat** [MightyPirates/OpenComputers#861]
So I was playing around with the Database component. Didn't find a way to compute hashes for items in robot own inventory or in containers around the robot.

Without this function I feel the database component is a bit useless and serve no practical purpose on robots.

**Comment by fnuecke** [comment]
I was about to add this, but on second thought I don't like that allowing to compute the hash of any item makes not only a large part of the DB upgrade useless, but also the compare methods. A compromise might be adding a `compareToDB`-like method? I'm not fully convinced even that is necessary, considering you could dedicate one slot in the DB upgrade as a 'comparator' slot into which you store the item to compare on demand.

**Comment by drheat** [comment]
The way I figured the DB upgrade works is by adding several items to it by hand, then installing it in a robot. It would then be used as some sort of filter for which items to push and / or pull.

If it's possible to add items dynamically to it through code I guess this enhancement could be dropped. Even though a simple comparison would be much more costly since it would involve potentially moving many items to the DB just for the purpose of seeing if they match?

For outside containers it would be even more costly as you'd have to move the item inside the robot own inventory, then into the DB, then back to robot inventory and back to chest all that just to make a comparison. Not to mention if the chest is auto-stocked by AE or other means, it would be full and not accept the item back.

A compareToDB for InventoryController would be a great way to add this functionality, as you suggested.

**Comment by DirtYiCE** [comment]
I second that the database upgrade in it's current state is pretty much useless. (Anyway, how can you store items in the database from inventory? I've only found `copy`, but it's pretty much only work with items already in the database somehow). Maybe inventory_controller should have a `computeHash`, but only when a database upgrade is also installed.

**Comment by fnuecke** [comment]
The inventory controller provides `store` (stack from adjacent inventory -> database), `storeInternal` (stack from internal inventory -> database). The geolyzer provides `store` (block's item representation -> database).

But yes, absolutely, the database component is currently very... focused. This is of course because it was added for a very specific use-case (that of providing stack info with NBT data to other components). I'd be happy to give it more applications, but not by making other features completely superfluous (like the existing compare methods).
