### ISSUE TITLE
Gradle subprojects

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#863]
http://gradle.org/docs/current/userguide/multi_project_builds.html

Things that could be done with subprojects:
1. Lua architecture. It shouldn't be part of the "core" so to speak.
2. [todo come up with more things to list here... cross-mod compat? API implementations? (CPU item, RAM item, etc, could all be in its own subproject, altho we're nothing alike so I don't know if you like splitting projects like this.)]

**Comment by fnuecke** [comment]
?

**Comment by SoniEx2** [comment]
Use gradle subprojects (for example, for the Lua architecture)

**Comment by LizzyTrickster** [comment]
no description, vague title, no structure

-INF/10 would run away from at all costs

**Comment by SoniEx2** [comment]
Ok, fixing that now.

**Comment by fnuecke** [comment]
The main reason this isn't the case already is that I couldn't figure out how to get this working with ForgeGradle right away, and don't have enough personal benefit from this to spend a lot of time on it. Si non confectus, non reficiat, after all.
If you can get it to work, instructions on how to would be appreciated. If splitting things up, I suppose things like integration, API and translations would make sense. As might the different architectures, though that might need quite a bit of refactoring.

**Comment by SoniEx2** [comment]
You should make a "core" subproject which implements ForgeGradle and stuff, and then the other projects should use "core" as a dependency. Works for LibGDX, _should_ work here too. The main project just compiles all subprojects, then you use a jar utility to pack all the subjars into one jar. There are quite a few available.

**Comment by fnuecke** [comment]
Sorry, considering this not worth the effort. If someone were to make a (non-breaking) PR that does this, I'd be willing to merge it, but I'm not going to spend time on this.
