### ISSUE TITLE
Add an interface for better ComputerCraft peripheral blacklisting

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#865]
I'd like to have an interface in OC you can put onto any ComputerCraft `IPeripheral` that has a method `isBlacklisted()` so you can blacklist a peripheral under certain conditions rather than having to blacklist an entire peripheral via IMC.
I need this because the Computronics MultiPeripheral system now supports wrapping every single ComputerCraft peripheral into its own, but because the MultiPeripheral is blacklisted via IMC, it renders the ComputerCraft integration in OC useless. The easiest way probably would be something like this in [here](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/integration/computercraft/DriverPeripheral.java#L52):

``` java
if (!(isBlacklisted(p) || (p instanceof BlacklistablePeripheral && ((BlacklistablePeripheral) p).isBlacklisted()))) {
    return p;
}
```

or, the other way around,

``` java
if (!isBlacklisted(p) && !(p instanceof BlacklistablePeripheral && ((BlacklistablePeripheral) p).isBlacklisted())) {
    return p;
}
```

**Comment by fnuecke** [comment]
I don't quite follow - how does Computronics' CC peripherals being blacklisted break OC's support for _other_ CC peripherals?

**Comment by Vexatos** [comment]
@fnuecke Computronics' CC peripheral wraps _every_ other CC peripheral if a certain config option is enabled, that's the problem. This means every CC peripheral will be an instance of Computronics' peripheral.

**Comment by fnuecke** [comment]
Wrap as in replace? That's quite... aggressive :P All right then, I'll look into it. Maybe with a slightly more explicit name, because `isBlacklisted` is quite generic. So it's not _that_ unlikely to lead to naming conflicts. `isPeripheralBlacklisted` maybe?

**Comment by Vexatos** [comment]
@fnuecke `isPeripheralBlacklisted` is very unlikely to be used, so it should be fine.
And yes, it's aggressive indeed, but it works :)
