### ISSUE TITLE
[Debug Card] World.removeItem

### ISSUE THREAD

**Issue by TinkerWorX** [MightyPirates/OpenComputers#866]
The world api comes with an `insertItem` function. Can we get a `removeItem` function as well?

**Comment by fnuecke** [comment]
Would that work like a robot's suck method (i.e. pull something from a specific slot), or also work via a item descriptor (like insertItem) and remove that if it's found? Would the removed item vanish or be dumped into the world?

**Comment by TinkerWorX** [comment]
I was simply thinking something along the lines of `removeItem(slot:number, count:number, x:number, y:number, z:number, side:number):boolean`, basically deleting the item from the inventory.

Alternatively you could name it `destroyItem`, to underline the functionality better.

**Comment by fnuecke** [comment]
Sounds good.
