### ISSUE TITLE
Inventory_controller and (JABBA) Barrels

### ISSUE THREAD

**Issue by L00Cyph3r** [MightyPirates/OpenComputers#871]
Currently, it is possible to track all the items in a certain amount of chest. But for bigger storage needs of a single item (cobblestone?) we like to use [JABBA](http://minecraft.curseforge.com/mc-mods/73510-jabba).
With the help op the inventory_controller, we can see only a single stack of 64 inside a barrel.
What I would like to be possible, is to see the actual content of the barrel, even is the stack-size is displayed in a huge number.

If there already is a way of interacting with the barrels, then please enlighten me.

**Comment by Vexatos** [comment]
@fnuecke Computronics has had an IDeepStorageUnit driver for ages...
I guess I have to get rid of it now.

**Comment by fnuecke** [comment]
Ah, well. Sorry for not knowing all the drivers in Computronics I guess :P
Also looks like it was only loaded if MFR was present; so it wouldn't have worked for JABBA unless MFR was present, too, no?

**Comment by Vexatos** [comment]
It was loaded if MFR or JABBA was present.

**Comment by fnuecke** [comment]
Ah, well then. I guess OP didn't have Computronics then. Meh.
The Gradle dep on MFR was already in OC anyway, so whatever.
