### ISSUE TITLE
Texture bug

### ISSUE THREAD

**Issue by nister6000** [MightyPirates/OpenComputers#873]
![2015-01-30_17 33 38](https://cloud.githubusercontent.com/assets/5342590/5979719/6ff5e0ee-a8aa-11e4-9b9c-c6c546d390c2.png)
This happen on all cases.

I tried:
Removing config
Reinstalling minecraft
Removing all mods but Opencomputers, Thermal Expansion and Waila.

OC version: OpenComputers-MC1.7.10-1.4.6.376-dev-universal
I also tried stable, nothing changed.

My server users also have this bug.

**Comment by fnuecke** [comment]
What's the bug, exactly?

**Comment by nister6000** [comment]
I remember other looking texture hmm.

**Comment by nister6000** [comment]
Ahh this texture is normal but my players say its weird.
It would be nice to see new texture, when i will find it i will add it here to show.

![casebackon](https://cloud.githubusercontent.com/assets/5342590/5982249/8c92d4fc-a8c1-11e4-84f6-e5c8a0d867ad.png)

This is bdcraft textures it have  vent on back (it spins when on) thats look nice.

**Comment by fnuecke** [comment]
That's the right texture. Rotation is based on which way you're looking when placing it, and cases can be rotated using wrenches (hit them on the top or the bottom). If that doesn't work it's most likely some other mod interfering.
