### ISSUE TITLE
Robot crafting component is unable to repair armor

### ISSUE THREAD

**Issue by GunArm** [MightyPirates/OpenComputers#874]
If two pieces of damaged armor are placed in the crafting space of a robot, as you would on a vanilla crafting table to combine/repair them, when you attempt to call component.crafting.craft() it fails and returns false.
I have actually only tested this with damaged chain-mail chestplates.  When I get home I will try a few other types of armor/weapons, to make sure the issue is not limited to this particular item type, and report back.

**Comment by fnuecke** [comment]
Welp, looks like MC is being MC and has a special case in the crafting handler for handling repairs, instead of going the logical route of that being a recipe... Meaning I'll need to add special code to handle that use-case, too. I'll look into it.
