### ISSUE TITLE
[Command] Prevent item from diassembling

### ISSUE THREAD

**Issue by TinkerWorX** [MightyPirates/OpenComputers#875]
I'm working on a challenge map where OC machines play a big role. I've made some robots that make use of the debug card and are locked for specific tasks. I would rather not have players disassemble them. However, I want to allow them to take full use of OC, so I don't want to simply disable the Disassembler either.

My suggestion is to add a "/oc_lock" or "/oc_nodis" command, that locks the currently held device, and blocks it from getting disassembled. It should not block interaction or breaking, only prevent it from getting disassembled.

**Comment by Vexatos** [comment]
A command adding some "undisassemblable" (that word :dancer:) NBT tag shouldn't be that hard to do, actually.

**Comment by TinkerWorX** [comment]
That's the solution I had in mind as well. Add the tag, check before disassembling.
