### ISSUE TITLE
Need a limit to number of values in a modem message

### ISSUE THREAD

**Issue by SolraBizna** [MightyPirates/OpenComputers#876]
A program like the following:

```
    local bomb_port = 7
    local bomb_size = 16000
    local bomb = {}
    while #bomb < bomb_size do table.insert(bomb, "") end
    local modem = require "component".modem
    modem.open(bomb_port)
    while true do modem.broadcast(bomb_port, table.unpack(bomb))
```

can, with varying values of bomb_size:
- Annoy people using packet sniffers.
- Crash any computer listening on `bomb_port`.
- Run its own computer out of memory (or bluescreen it with an "internal error").

Particularly because of the second possibility, I recommend instating a limit on the number of values a modem message can contain. The upper limit of sanity for this limit is the maximum packet size in bytes... but with default settings even this is enough to crash a computer with 1MiB of memory. I'd recommend a configurable limit with a fairly low default&mdash;32? (Even that might be too high.)

This change can hinder real applications; the current iteration of my remote filesystem sends each filename in a directory as a separate element. On the other hand, that protocol could trivially be changed to take another approach.

**Comment by fnuecke** [comment]
There's already a system for limiting packet size in place, it just didn't account for empty strings properly (not counting them towards the packet size at all). Thanks for pointing that out!

**Comment by SolraBizna** [comment]
Even making empty strings count as one byte doesn't fully solve the problem, as an empty string in a table / on the stack has far more than one byte of overhead, and can quickly overwhelm available memory if there are 8192 of them.

**Comment by fnuecke** [comment]
While that may be true, a system would have to cutting it pretty close wrt. its memory usage for that to become an issue, no? Alternatively I guess the minimum could be increased a bit, or maybe more generic, the number of entries in the packet can be counted into its size (something like `size = currentComputerValue + someFactor * data.length`)?

**Comment by SolraBizna** [comment]
In my tests, a 1MB server running nothing but OpenOS and a simple packet sniffer gets instantly crashed by a message containing 8192 empty strings.

**Comment by SolraBizna** [comment]
Forgot to mention that the current situation where elements don't "take up" any space other than that used by their basic representation would cause problems for a [more hardcore](http://oc.cil.li/index.php?/topic/430-real-cpu-for-opencomputers-interested/) architecture. Adding two bytes per element to the effective size would create room for a 16-bit tag (0-65531 = string of that length, 65532=double, 65533=boolean false, 65534=boolean true, 65535=nil for instance); even if that representation is never actually used by OpenComputers itself, a hardcore architecture could synthesize the tags and the buffer space taken up by a given message (with tags) would exactly equal its wire size.

**Comment by fnuecke** [comment]
Right. So just to be clear, add `2 * data.length` and we're good?

**Comment by SolraBizna** [comment]
Adding `2 * data.length` would fix that other hypothetical issue (which I should really make a separate issue for). Unfortunately, testing just now showed that it wasn't strict enough to prevent this issue.

I used 4096-element "bombs" (simulating a size limit of 8192 and two bytes of overhead per empty string) and it still killed servers below 768KiB of RAM. Modifying the packet sniffer to discard all but the first few elements helped, but an 8192-element bomb still killed it. It's difficult to measure the exact memory overhead here, as the fatal blow can occur outside modifiable code, and the very act of checking memory usage can consume/reclaim memory.

_In addition_ to adding per-value overhead to the size calculation, I'd recommend a fairly small limit on the number of values in a message&mdash;10 values? Maybe fewer? There are reasons to support more values, but I can't think of any _sane_ use case that requires more than 10. (It should be configurable in case players decide 10 is too few.)

**Comment by fnuecke** [comment]
Ah, I see your point (what a little bit of sleep does for the mind!)

Yeah, I'm not sure most people even use the ability to send more than _one_ argument. 10 seems quite enough. I think I'll actually go for 8 because... y'know. And yes, definitely will be configurable.

**Comment by Tapmemer** [comment]
send 999^40 and make it calculate
