### ISSUE TITLE
[Debug Card] World.removeItem, issue with Robots.

### ISSUE THREAD

**Issue by TinkerWorX** [MightyPirates/OpenComputers#878]
It appears that `World.removeItem` doesn't work on robots. It works perfectly fine on chests.

Steps to reproduce
1. A robot with inventory and a debug card and OpenOS
2. Put an item in the first slot of the robot
3. Run the code below

```
require("component").debug.getWorld().removeItem(debug.getX() - 0.5, debug.getY() - 0.5, debug.getZ() - 0.5, 1, 1)
```

Expected results: The item in the first slot gets removed.
Actual results: The item in the first slot doesn't get removed.

**Comment by fnuecke** [comment]
That's because the "real" inventory layout of a robot is structured like this:
0 = Tool
1-2 = Containers
3-X = Inventory

So you'll probably really want `..., 5, 1)` in this case.

**Comment by MyNameIsKodos** [comment]
Commenting here so that I can easily find this info for future use.
