### ISSUE TITLE
Custom filesystems no longer possible

### ISSUE THREAD

**Issue by SolraBizna** [MightyPirates/OpenComputers#879]
In previous versions of the filesystem library, one could implement a custom filesystem by constructing a Filesystem-like fake proxy object and passing it to `filesystem.mount`. [This commit](https://github.com/MightyPirates/OpenComputers/commit/42040e2da654d23a74386c5f188aa0053646c100) removed the ability to do this. One can monkey-patch `component.proxy` as a temporary workaround.

This issue can either be fixed by restoring the ability to pass something other than a real component proxy to `filesystem.mount`, or by adding support for software-defined components to the `component` library.

**Comment by fnuecke** [comment]
Ah, yes, that. The original intent was to prepare for persisting the whole virtual filesystem, to keep mounts and symlinks across reboots... never got around to finish that; probably won't so I might as well undo that... will look into it.

**Comment by SolraBizna** [comment]
I have tested 8092fae and it does indeed fix the issue. Thanks!
