### ISSUE TITLE
Bug: Cannot craft iron nugget.

### ISSUE THREAD

**Issue by rmellema** [MightyPirates/OpenComputers#88]
I am somehow not able to craft an iron nugget. It also doesn't show the recipe in NEI, so I guess that it isn't registered or something? 
I haven't changed default.recipes or user.recipes. 
It is the only recipe that doesn't show up in NEI
EDIT: I am using version 1.1.3

**Comment by fnuecke** [comment]
Confirmed that iron nugget recipe is derped. Seems I've only been testing when other mods that add their own iron nuggets were present recently. Thanks for reporting!
If it doesn't show in NEI some other mod's iron nugget should be present, though (and the recipes all use the oredict for the iron nugget)?
