### ISSUE TITLE
Visual Bug with shaders

### ISSUE THREAD

**Issue by MrGreenTea** [MightyPirates/OpenComputers#884]
When I use the mod [psychedelicraft](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1276287-ivorius-mods-structures-dungeons-drugs-statues) and have shaders enabled, i get this visual bug with some of OC blocks.
Here are two pictures of all the blocks affected:
[shaders enabled](https://i.imgur.com/CvLhsml.png)
[shaders disabled](https://i.imgur.com/cnbq4HW.png)

Everything looks right when only having Shaders2D enabled, btw.

I also reported it to the guy who made psychedelicraft, here is what he said: [link](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1276287-ivorius-mods-structures-dungeons-drugs-statues?comment=3455)

This doesn't seem to be hardware specific, because I get this bug on my desktop pc and laptop and one has a Nvidia and the other an AMD graphics card.
If you need more info, please let me know!

**Comment by fnuecke** [comment]
Please try [build 395](http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/), that should fix it (at least it does on my system).

**Comment by fnuecke** [comment]
Well, it was fixed in the tests I did, so I'm closing this. If you still encounter issues let me know.
