### ISSUE TITLE
Animation issue with Mystcraft and OC.

### ISSUE THREAD

**Issue by TinkerWorX** [MightyPirates/OpenComputers#886]
![Animation Issue](http://i.imgur.com/eyC1pqE.gif)
As you can see, the robots seems to not animate properly in Mystcraft ages.
This has been tested with
- Forge 10.13.1.1258
- OC 1.4.7.390
- Mystcraft 0.11.0.00

To reproduce the issue, simply create a random age, and turn on a robot.

**Comment by fnuecke** [comment]
This seems to be caused by the `getTotalWorldTime` to always be zero on the client side in Mystcraft ages. Not sure if this is intentional or a bug, yet.

Edit: this also leads to beacon beams not being animated in Mystcraft worlds, so yeah, I'd say that's a bug in Mystcraft.

**Comment by TinkerWorX** [comment]
Alright. Have you made any contact with the author of Mystcraft, or should I do that?

**Comment by fnuecke** [comment]
I've dropped a message in IRC, don't know if he read it yet. Haven't posted it on the forums / bug tracker, yet, though, so could do that.

**Comment by TinkerWorX** [comment]
I found this on the issue: https://github.com/XCompWiz/Mystcraft-Issues/issues/29

**Comment by fnuecke** [comment]
Huh, well it doesn't appear to be fixed in 0.11.0.00... I'll comment there.
