### ISSUE TITLE
gpu.bind() killing left click and scroll

### ISSUE THREAD

**Issue by Dylanavo** [MightyPirates/OpenComputers#887]
I have 3 monitors controlled with 1 gpu. 

I use one main big screen, with two smaller screens to act as walk buttons.

The problem is switching to the first and second button screens to set up the display, then switching back to the main screen again, all using gpu.bind(screenAddress). While it does set up the screens fine and change back to the main screen without a problem, I've noticed it seems to stop left clicking and scrolling in the terminal, and when editing programs from that point on (at least until a reboot).

Is this a bug, or do I need to somehow rebind click/scroll functionality to a screen when I swap back to it?

Regards,
Daraketh

**Comment by fnuecke** [comment]
Since it works fine when I'm using the `primary` program, I'm guessing this is an issue with one of the secondaries being picked as the primary screen. Try setting the main one as the primary screen in addition to binding it on the gpu (i.e. `component.setPrimary("screen", mainAddr)`).

**Comment by Dylanavo** [comment]
That did the trick, thanks muchly fnuecke!

**Comment by fnuecke** [comment]
Great :-)
