### ISSUE TITLE
[Suggestion] Flatbed Scanner

### ISSUE THREAD

**Issue by paulbatum** [MightyPirates/OpenComputers#891]
I play on a server that has a market plugin that outputs a Book And Quill for every sale made and I want to write a program that can read these books and do some useful things :)

As far as I can tell there is no way to do this through OpenComputers today. I was thinking that the most flavorful way to implement this would be to add a "Flatbed Scanner" block that has a component API that allows the computer to obtain the contents of the book.

I'm looking for feedback on whether this idea makes sense, and if you would be open to it as an addition to OpenComputers itself, or whether I should be looking to get it added to Computronics or somewhere else.

**Comment by Techokami** [comment]
IIRC, a Scanner peripheral is planned for a future update of the [OpenPrinter mod](https://github.com/PC-Logix/OpenPrinter).

**Comment by MyNameIsKodos** [comment]
You'd have to ask @MichiyoRavencroft about that addon.

**Comment by CaitlynMainer** [comment]
The printer can currently scan it's just really crappy...

**Comment by paulbatum** [comment]
Thanks for the help guys! Unfortunately the server I'm playing on does not have OpenPrinters so it looks like I am out of luck for now. I'll see if I can convince them to add it :)
