### ISSUE TITLE
Item duplication by robot

### ISSUE THREAD

**Issue by MaHuJa** [MightyPirates/OpenComputers#898]
Context: I was using my robot to drop blocks of coal coke (from railcraft) for the botania endoflame flowers. They burn for a long time, so the items would simply despawn, which is where the robot comes in.

Initial state: Tier 1 robot, a bunch of single objects in most slots until slot 10-12 or so where there was a full stack. Single t1.5 memory, else t1. Inventory, keyboard, screen, disk drive. Booted from floppy, containing OpenOS 1.4 and a program to follow. Total about 1.2 stacks of coal coke.

Process: The program tries to dump a single item, and if it hasn't been taken away in a few seconds (consumed by the endoflame), suck it back up. (The next iteration would be redstone controlled.) 

End state: I came back to find several stacks (at least 20) of coal coke on the ground, in addition to the robot's inventory being absolutely filled with 16 more.

```
robot = require("robot")
sleep = os.sleep

function drop()
  for i = 1,16 do
    if robot.count(i) > 0 then
      robot.select(i);
      if robot.drop(1) then return true
      end
    end
  end
  return false, "Could not drop. Empty?";
end

function pickup()
  robot.suck()
end

function cycle()
  drop()
  sleep(4)
  pickup()
  sleep(11)
end

while true do cycle() end 
```

Speculation: robot.drop(1) drops a whole stack while only removing 1 from the inventory.

Mods installed: DNS Techpack 7.5.4.9 + manually added computronics.

**Comment by Vexatos** [comment]
Try using the latest OC version, I am 99% sure it has been fixed.

**Comment by MaHuJa** [comment]
I overlooked the "maybe a newer version fixes it" option. And it seems it does. Closing.
