### ISSUE TITLE
Wrong tonumber() function behavoir

### ISSUE THREAD

**Issue by PowerOfTech** [MightyPirates/OpenComputers#906]
Tonumber() returns nil, when when it translates string,that contains float separated with point(like "123.456")(this is default lua behavoir),but when it translates string,that contains float separated with comma(like "123,456"),all works well.

**Comment by fnuecke** [comment]
Duplicate of #800. As discussed just earlier on IRC with @SoniEx2 I'm willing to pull that under the additional condition that it gets a config option to allow disabling it, in case it turns out it _does_ cause issues otherwhere.
