### ISSUE TITLE
Update to UE 3.0

### ISSUE THREAD

**Issue by calclavia** [MightyPirates/OpenComputers#91]
Hey, just to let you know UE 3.0 has been released for MC 1.6.4. It'll be nice if you update to it!

Great to finally see a computer mod that interacts with my system. :) Documentations on UE 3.0 are on the UE Github wiki.

-- Regards, Calclavia

**Comment by Vexatos** [comment]
UE github wiki: https://github.com/Universal-Electricity/Universal-Electricity/wiki

**Comment by fnuecke** [comment]
Sweet! `@UniversalClass` looks pretty fantastic, trying it out right now.

**Comment by Vexatos** [comment]
@calclavia The annotation was the best addition UE got this update. Great job :+1:

**Comment by calclavia** [comment]
That was fast! :) Note you'll be dependent on the UE core to get things working with other systems, that's all.

**Comment by fnuecke** [comment]
Good timing ;-)

And yes, I'm aware of the dependency, and I think it's worth it. Almost nobody I asked had a problem with it, either. And if it isn't there I just disable power use and display a chat message on login explaining that.
