### ISSUE TITLE
"Too Many Components" with RotaryCraft

### ISSUE THREAD

**Issue by WazWaz** [MightyPirates/OpenComputers#910]
RotaryCraft nicely supports OC on all its machines...... even pipes. Unfortunately this means all but the most trivial machines cannot be connected! (over 100 components for a very basic setup). Even setting up for power is painful: I got it working by:

[RotaryCraft Redstone Flux dynamo] [Assembler] [PowerDistributor] [Computer] - effectively putting the Assembler into the 100+ components network and the actual computer in another (I don't actually need an assembler this game - no robots for a change!).

I think components outside the computer should be explicitly loaded by the OS and not count until then.

**Comment by gjgfuj** [comment]
It.... Has them as native support?

**Comment by gjgfuj** [comment]
Nonetheless, blame Reika, that is not how you do components that aren't inherently designed to be used with computers.

**Comment by Vexatos** [comment]
Indeed, Shafts should not be a component, just a simple node, I think.

**Comment by gjgfuj** [comment]
They shouldn't be nodes at all, without good reason, why do they have nodes
on them?

**Comment by fnuecke** [comment]
I thought he had changed that some time ago (making nodes in shafts not connect to each other), maybe not, maybe it's a regression. I'll ask him. Either way, this definitely falls into the category "not the way it's meant to be done".
