### ISSUE TITLE
Parallel execution for coroutine threads (multithreading)

### ISSUE THREAD

**Issue by glebqip** [MightyPirates/OpenComputers#913]
I think, with this improvement will be good to create a lot of cool things, such as multitasking OS

**Comment by Vexatos** [comment]
I don't think this is how Lua works or should work...

**Comment by GopherAtl** [comment]
I must again point out, as this comes up a lot... we may take multi-core processors for granted, but there were multitasking OSs long before the average computer had 2 or more processors. What is missing generally in lua isn't "true parallel execution," it's interrupts, and as long as programs are properly written, cooperative multitasking can work just as well as preemptive.

**Comment by fnuecke** [comment]
You can use coroutines to do this, pretty much. There are some cases where it won't go quite as smoothly in OpenOS, because it's built around its event system for parallelism, but you could create a custom OS (e.g. by adapting OpenOS) for a fully "yield-based" parallelism.
