### ISSUE TITLE
Reassigning Sneak to a mouse button breaks OC tooltips in NEI

### ISSUE THREAD

**Issue by pwholmes** [MightyPirates/OpenComputers#914]
Sounds absurd, but I can reproduce this 100% of the time in my game world.  Remapping Sneak breaks the OC tooltips in NEI so that they just say "Unnamed" -- but _only_ if you map it to a mouse button (e.g., "Button3").  It still works properly if you map it to any other key, including a key with an equally long name (e.g., "NUMPAD0").  Resetting the mapping causes the tooltips to work again.

**Comment by fnuecke** [comment]
I... why would you... uhh. Yeah, the code doesn't handle mouse bindings properly right now, will fix.
