### ISSUE TITLE
Assembler Tower Defense

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#917]
> Sangar, I already considered making the Assembler attract creepers while it's assembling. The more complex the thing to assemble, the further the attraction range. Also make creepers explode their way towards the assembler. Will turn your robot assembly into a tower defense game

Also make the Assembler, if assembling with a certain complexity, actually spawn creepers 30-40 blocks away and attract them immediately. Basically, if the creeper runs towards the assembler but hits a wall inbetween, it'll blow up anyway, making a hole for other creepers to pass through.

When the assembler has finished, it will stop any activity/attraction. It won't do anything when not assembling stuff.

This is so evil, make it a config option.

**Comment by Vexatos** [comment]
Also make sure to have it still do those evil things if it isn't constantly getting power, so a lack of energy doesn't stop the whole game :)

**Comment by DrZed** [comment]
I like it! Give me NAO!!!!

**Comment by MFernflower** [comment]
Perhaps make it trigger on April 1st.

**Comment by fnuecke** [comment]
Considering just how evil this is (which I really like) I am infinitely scared of making it the default, so if / when this makes it in, I'm thinking it'd be an optional thing - checkbox in the GUI or so - that has some benefit, like making the thing cost only 50% of the energy it'd normally take to assemble or something along those lines.

Edit: taking the idea a little further, maybe an extra slot for catalyst items, which would e.g. be monster heads. Depending on the type there'd be different bonuses (zombie 10% cheaper, skeleton 25%, creeper 50%, you get the idea).

**Comment by MFernflower** [comment]
@fnuecke What about certain heads for speed and certain ones for power benefit? Maybe even certain mob or Nether/Ender drops can be used as perks? Perhaps that's a better mechanic to implement then the whole "Tower Defense" thing.

**Comment by fnuecke** [comment]
Yeah, I guess it could be something somewhat similar to [Bastion's Idol system](http://bastion.wikia.com/wiki/Idols)?

Damn... now I want to make a power generator based around that idea >_>

**Comment by DrZed** [comment]
I love it more Gimme now!!!!! And I want it implemented into API so I can mess with adding things to it or making things funner! !_!

**Comment by payonel** [comment]
as fun as this sounds, i dont want to add a feature that is disabled by default - and i agree this shouldn't be enabled by default :)
