### ISSUE TITLE
RAM Tiers Bugged:  Tier 1.5 = Tier 1, All Other Tiers Reduced a Step

### ISSUE THREAD

**Issue by Eunomiac** [MightyPirates/OpenComputers#919]
It appears that each Tier of RAM is taking the capacity of the tier directly below, with the exception of Tier 1 (which remains unchanged and, as a result, equal to Tier 1.5):

With config settings as follows:

```
      ramSizes=[
        192,
        256,
        384,
        512,
        16384,
        1024
      ]
```

... I get these values for 4 sticks of each tier of RAM:
- Tier 1 --- 786 KB (196 per stick)
- Tier 1.5 --- 786 KB (196 per stick)
- Tier 2 --- 1048 KB (262 per stick)
- Tier 2.5 --- 1572 KB (383 per stick)
- Tier 3 --- 2097 KB (524 per stick)
- Tier 3.5 --- 67.1 MB (16777 per stick)

Disregard the out-of-place 16 MB setting---that was just a further test as I looked into this.  I can confirm the problem exists even when the values are unchanged from the defaults.

(Fun fact:  Stumbled on this when my program ran out of memory despite 4 sticks of 16 MB RAM!  I feared my half-megabyte of code had finally reached the limit ;) )

**Comment by fnuecke** [comment]
Oops, was introduced by the change in how memory sizes are defined in 1.5.
