### ISSUE TITLE
uC EEPROM swap via shift-click

### ISSUE THREAD

**Issue by magik6k** [MightyPirates/OpenComputers#920]
It should be possible to swap EEPROM's in uC shift rignt-clicking, when holding EEPROM in hand, as current way of swapping them is really annoying when developing complicated program that may error in multiple places.

**Comment by fnuecke** [comment]
You mean alike to the tablet's GUI for accessing the container slot? Hmm, yeah. I want to wrap up 1.5 and in particular the 1.8 port for now, but I'll have a look into it when I can.
Edit: I was enlightened this is meant to allow switching the EEPROM by rightlicking one on an MCU in the world. Which seems to make sense, and should be easier to do, too.
