### ISSUE TITLE
Howto query block id

### ISSUE THREAD

**Issue by PaulGWebster** [MightyPirates/OpenComputers#922]
Good day,

How can I retrieve information of the block infront,below,at the size of or above me, such as its ID not type

**Comment by magik6k** [comment]
For questions, there's forum at http://oc.cil.li/index.php?/index and wiki at http://ocdoc.cil.li/ Issues on github should be only used for.. issues, and feature requests

also youre probably looking for component.inventory_controller.getStackInSlot(sides.back, slot)

http://ocdoc.cil.li/component:inventory_controller

**Comment by fnuecke** [comment]
I think you're looking for the Geolyzer: http://ocdoc.cil.li/component:geolyzer
In particular the `analyze` method.
Also, what magik6k said: please prefer using the forum for support, thanks!
