### ISSUE TITLE
[Suggestion] Please update Lua to 5.3

### ISSUE THREAD

**Issue by evieluvsrainbows** [MightyPirates/OpenComputers#925]
I know it might take a while to port OpenComputers to Lua 5.3, but could you guys please try & do it? I'd love it if OC was ported to Lua 5.3, as it adds a bunch of awesome new features. Here's the changelog for Lua 5.3: http://www.lua.org/manual/5.3/readme.html#changes

**Comment by magik6k** [comment]
Duplicate of #811, please look at at existing issues before opening one. ;)
