### ISSUE TITLE
Robot move behavior is not as written

### ISSUE THREAD

**Issue by Namarius** [MightyPirates/OpenComputers#927]
So after these rules
1. Robots may only move if the start or target position is valid (e.g. to allow building bridges).
2. The position below a robot is always valid (can always move down).
3. Positions up to <flightHeight> above a block are valid (limited flight capabilities).
4. Any position that has an adjacent block with a solid face towards the position is valid (robots can "climb").

Rule 3 is not implemented as expected. Actually the robot searches for n blocks in the opposite direction of the intended movement. So on a flat surface it is not possible to move forward when the robot currently "flying" at least one block above ground.
So ether change "above" with opposite movement direction or robots need a fix.

**Comment by fnuecke** [comment]
Gah, forgot to backport that from [the 1.8 branch](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.8/src/main/scala/li/cil/oc/common/event/RobotCommonHandler.scala#L39). Will fix ASAP.
