### ISSUE TITLE
Suggestion: Access Tablet via Media Drive

### ISSUE THREAD

**Issue by GoneNomad** [MightyPirates/OpenComputers#929]
Problem:
It feels awkward and counter-intuitive to use a Charger to get access to the Hard Drive in a tablet.

Suggestion:
Make the Disk Drive into a Media Drive or make a Tier 2 Media Drive.

Allow it to interface with a single Hard Drive, Tablet, EEPROM, Floppy Disk and whatever else you come up with for portable storage. It would be nice to be able to put a Microcontroller or Drone in there and get access to the EEPROM.

I see this as a media hub with all the interfaces built in, but only one can be used at a time.

Side Note: I have learned more about the basics of Linux from your mod than I would have believed and I've been running Kubuntu for three years. I've already got notes started for the next dozen tutorials.

**Comment by fnuecke** [comment]
Well, the name is what it is for legacy reasons, obviously. Renaming it to, say "Docking Bay" or something might be more intuitive? I'm adding a note to the tooltip for now, thought I had already done that.

As for EEPROM access, I do not want to have more than one EEPROM component exposed to computers at a time, to keep booting deterministic. And to avoid only supporting the built-in one it'd need some rather... "hacky" code, so... I'll have to sleep over this some.

Taking that into account, I'm not overly keen on adding an extra block for this, hence the suggestion to rename the charger.

> I've already got notes started for the next dozen tutorials.

Awesome!

**Comment by GoneNomad** [comment]
I like Charger, says exactly what it does. If there is something in the Charger's tooltip or interface about the tablet, that should be good enough.

I haven't gone near EEPROMs yet, that is a whole other level of programming. Looking through the wiki, I found no mention of how to read/write one. If there is a way already then I'm happy.

**Comment by gjgfuj** [comment]
Eeproms are just component.eeprom.get/set

**Comment by GoneNomad** [comment]
Which works on the EEPROM in the computer. Comprehension dawns, thank you. SO much to learn (and write tutorials about)!
