### ISSUE TITLE
Suggestion: Let Charger top off 

### ISSUE THREAD

**Issue by GoneNomad** [MightyPirates/OpenComputers#932]
Problem: When using the Charger to recharge a robot, it tends to leave 1-3% uncharged.

Suggestion: If the amount to be charged is less then the charge given, lose that tiny extra.

Also, why does the Charger have different power levels? If there was a small percentage of energy always used while on it would make sense, but I do not see that happening.

Last one tonight, I promise. Just clearing out my notebook.

**Comment by fnuecke** [comment]
This is actually a display issue. The energy status is only sent to the client if it changed significantly to reduce bandwidth usage, so if the last status sent was > 95% it won't sent an update when it changes to 100%. Will add a check to periodically force sending the energy info if it changed even slightly.

**Comment by fnuecke** [comment]
Oh and as for

> Also, why does the Charger have different power levels?

That's to allow some control over how quickly the charger can drain energy from the network. Mostly to avoid peaks in power usage when you don't have a big capacitor bank or high-end power-supply.
