### ISSUE TITLE
Print should use io.output()

### ISSUE THREAD

**Issue by magik6k** [MightyPirates/OpenComputers#933]
https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/OpenOS/boot/00_base.lua#L30

Currently it only uses only io.stdout.

**Comment by fnuecke** [comment]
As discussed on IRC, this is standard Lua behavior: http://www.lua.org/manual/5.2/manual.html#pdf-print

> Receives any number of arguments and prints their values to stdout
