### ISSUE TITLE
Charger does not provide filesystem for renamed tablet

### ISSUE THREAD

**Issue by kayila** [MightyPirates/OpenComputers#935]
If a tablet is renamed at an anvil, then placed into a charger, it's file system no longer appears on the computer attached into the charger.

Using OpenOS 1.5
OpenComputers 1.5.0.6
Forge 1.7.10

**Comment by fnuecke** [comment]
Can't reproduce, are you sure the charger is properly connected to the computer?

**Comment by kayila** [comment]
Ahh, I see now. I was expecting it to show up as the tablet UID but instead it's showing up as the hard drive UID. Sorry for the confusion

http://imgur.com/XfDuqzO,JLVqfLp,fL0MkkX,86N6XbC#0

**Comment by kayila** [comment]
Closing the issue as it was user error
