### ISSUE TITLE
recipe over-rides in 1.8 version

### ISSUE THREAD

**Issue by kreezxil** [MightyPirates/OpenComputers#937]
Really wished that last issue wasn't closed out so quickly, because nothing is resolved yet. here is more data on the subject:

Once I got the recipes reading in I discovered that it still didn't like my
recipes I've tried making the recipe with {item="basemetals:copper_nugget"}
and "basemetals:copper_nugget" quotes included in both cases. No effect, OC
still registers it's own nugget and still insists that all of the recipes
where I wanted to use basemtals:copper_nugget were replaced with its own
nugget.

On top of that, OC refuses to acknowledge any recipe using 'button'.

the only reason I was even trying to use metal from another mod was because as originally stated OC insists on its own nugget. But something else is going on here.

btw, in creative I can do /give Kreezxil basemetals:copper_nugget 10 and get 10 of those; knowing that should've helped me to formulate the recipes, but perhaps there is something about the config that still baffles me. :(

My "your_custom.recipe" file is http://paste.ee/p/NSttt

**Comment by fnuecke** [comment]
See my reply to #934, you can still discuss it there, I'll reopen it if necessary, but it really looks like something else is wrong on your end, because it works perfectly fine in my installation of MC (using vanilla launcher and all that, so it's not because I'm in dev-env or anything).
