### ISSUE TITLE
Robots filling buckets

### ISSUE THREAD

**Issue by kayila** [MightyPirates/OpenComputers#938]
There are some types of blocks that can't be interacted by placing water(or other fluids) on them and need to directly be right clicked with a water bucket.

For these types of blocks that support no piping mechanism, I think it'd be useful if robots had a function to fill a bucket from it's internal tank. That way a robot could drive over to a tank or pool, fill up it's buffer, then head to the machine or block that requires the bucket to be used and repetively empty the bucket into the block, refueling from it's internal buffer

**Comment by fnuecke** [comment]
You'll be happy to hear, there already is, using the tank controller: `component.tank_controller.fill()` moves fluid from an internal tank to a tank item in the selected slot, including buckets.

**Comment by kayila** [comment]
Oh, huh... Missed that part of the API. Thanks! You do some awesome work!
