### ISSUE TITLE
1.5.0 update breaks existing robots and tablets

### ISSUE THREAD

**Issue by kayila** [MightyPirates/OpenComputers#940]
Should there be a way to reprogram the bios in a built device such as a robot and tablet in order to recover those devices after the update?

**Comment by Ameliorate** [comment]
Try crafting the robot or tablet with a new ROM.

**Comment by fnuecke** [comment]
Huh, I thought there was a recrafting recipe for robots (to swap the rom), apparently there isn't. Will add that. And for tablets. Oops. If it's urgent, use the disassembler, then reassemble the thing with a new BIOS.
