### ISSUE TITLE
system tries to call redlogic when redlogic is not installed

### ISSUE THREAD

**Issue by moTechPlz** [MightyPirates/OpenComputers#941]
When i connect a ic_circuit from this mod [http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2352247-integrated-circuits-alpha-ics-for-minecraft] to the computer i get this message: 
![2015-02-26_01 30 51](https://cloud.githubusercontent.com/assets/11203133/6384158/fefbf414-bd58-11e4-9036-f05d4f6cca50.png)
http://pastebin.com/hPhhAHms
If i install redlogic this error goes away and i can access ic_circuit just fine. But i have the project_red mod installed and i don't need another set of logic gates from the redlogic mod. I have tried to add 'RedLogic' to the integration.modBlacklist option in OpenComputers.cfg but that didn't work.

log http://pastebin.com/XPH7rDjK http://pastebin.com/MV5VpapU http://pastebin.com/uissAX5E

**Comment by MyNameIsKodos** [comment]
EDIT: I am an idiot. Ignore this post.

**Comment by skyem123** [comment]
This is a known bug with ICs.
/me pokes @Victorious3 to fix it

**Comment by fnuecke** [comment]
So it's on IC's side? Wonderful, less work for me ;-)

(Possibly missing `@Optional.Method` on [these](http://git.io/AxQp) [lines](http://git.io/AjYq)?)
