### ISSUE TITLE
cable turns black when placed in a block with a forgeMultiBlock in it

### ISSUE THREAD

**Issue by moTechPlz** [MightyPirates/OpenComputers#942]
Visual bug;

Cable turns black when placed in a block with a forgeMultiBlock in itI. f your remove the multiBlock it remains black. However, if you place the cable first, the cable remains grey when you add the multiBlock. ![2015-02-26_19 52 32](https://cloud.githubusercontent.com/assets/11203133/6399887/a2739538-bdf5-11e4-8f2a-d0395c7255a2.png)
This also happens with projRed cables. Not sure but i guess it also uses forgeMultiBlock. 
![2015-02-26_19 47 28](https://cloud.githubusercontent.com/assets/11203133/6399904/c4243304-bdf5-11e4-8140-756864afa603.png)

**Comment by gjgfuj** [comment]
Yep, its a problem on the FMP side, has been for all eternity, with
everything FMP.

**Comment by magik6k** [comment]
For me this also seems to happen when I dye the cable(At least using color applicator from AE2)
