### ISSUE TITLE
Allow microcontrollers to use T1 graphics cards rather than none at all.

### ISSUE THREAD

**Issue by MFernflower** [MightyPirates/OpenComputers#945]
Always see people using small LCD displays on there micro controller projects. So why not make it possible in OC?

**Comment by Vexatos** [comment]
I'd not want them to have any graphics. That one line of text should be enough.

**Comment by fnuecke** [comment]
Since they cannot connect to external components, having a GPU in them is kind of pointless.
Regarding status in general from MCUs, see #946.

**Comment by MFernflower** [comment]
Sorry if this sounds stupid but I havent used OC alot recently (but I want
to!) - Im more used to MFR gate arrays and CC code but I digress. Care to
expain this single line of text? Also arent T1 cards (the grey ones) text
only?

**Comment by fnuecke** [comment]
Not sure about that either, maybe he meant drones (which have two short lines of text for status messages in their GUI).

(Don't want to add a GUI to the MCUs though, so see my previous post.)

**Comment by MFernflower** [comment]
That would be a good idea. To give MCU's a small gui for status messages
and pROM insertion and removal. (Think drone gui)
