### ISSUE TITLE
Add card to add customized message to analyzer output

### ISSUE THREAD

**Issue by nmarshall23** [MightyPirates/OpenComputers#946]
I would like to have a Tier I card to change a computer's Waila Message. I was thinking two 20 character lines, that you could change from the default. 

I am not sure if this message would also show on any attached Components like Screens.

This would let us set status messages for things like micro controllers, #945 and any other headless Computers.

**Comment by fnuecke** [comment]
Hrrm, I'm not too keen on limiting this to be for Waila only. I could see this as being a thing in combination with the analyzer, though. I.e. have a card that allows defining some text to be included in the analyzer's output when used on the device.

**Comment by MFernflower** [comment]
I prefer fnuecke's idea instead of removing the T1 video card from the mod!

**Comment by Inari-Whitebear** [comment]
So I'm looking at implementing this.

Should it be able to also read the message that is currently set? If so, it would act as an extra data storage, so the message size should be limited. Though it maybe should be limited either way. E.g. 128 chars or so.

**Comment by payonel** [comment]
128 seems a bit small. 1k seems fair

**Comment by Inari-Whitebear** [comment]
Sounds good. Now naming... I went with "Analyzer Card" so far but it sounds a bit too much like being a card that has the same functionality as the "Analyzer"?

AshIndigo suggested Info Card maybe.
