### ISSUE TITLE
monochrome intensity bit

### ISSUE THREAD

**Issue by moTechPlz** [MightyPirates/OpenComputers#948]
an extra bit giving the color intensity for monochrome displays
- 0 = low intensity (standard)
- 1 = high intensity

so you can do things like this;

![man_screenshot01](https://cloud.githubusercontent.com/assets/11203133/6432299/1fda1ea4-c04c-11e4-896d-11efa9b3a076.png)
![msdos_edit](https://cloud.githubusercontent.com/assets/11203133/6432301/20730bd2-c04c-11e4-8286-fd6fc022bb79.png)
![msdos_vde_shareware](https://cloud.githubusercontent.com/assets/11203133/6432302/2160b99a-c04c-11e4-8924-402095a090d0.gif)

see http://en.wikipedia.org/wiki/IBM_Monochrome_Display_Adapter

**Comment by fnuecke** [comment]
You can use a T2 GPU+Screen for this by changing the color palette accordingly.

**Comment by moTechPlz** [comment]
Yeah i know. But old hardware could do that so i thought that would be a good addition.

**Comment by fnuecke** [comment]
While it could be neat for the T1 to give it just a little more expressiveness, it'd break too many things on a code level - API changes, internals, constants, too many dependencies at this point, really.
