### ISSUE TITLE
tablet reboot

### ISSUE THREAD

**Issue by moTechPlz** [MightyPirates/OpenComputers#949]
For his bug it was hard to retrace the steps down to reproduce it. The best sequence i found for now :
-  set bufferChanges=false (i've notticed the reset also with set to true, but much less often)
- run minecraft in windowed mode
- exit the tablet gui [esc]
- exit minecraft [esc]
- add a file of >6k to the tablet disk directory, differentiate the name if tried earlier
- open minecraft
- wait 5 sec
- open tablet gui

Like said it is hard to get the steps to reproduce this, some may not actually matter. It may need multiple tries. Hope you can reproduce it.

**Comment by MFernflower** [comment]
Im not a dev for OC, But I kinda wanna see a video of this inaction.

**Comment by moTechPlz** [comment]
Ok, so it seems you actually don't have to do much. Here i closed the tablet, opened the gameMenu[esc], wait a while, click backToGame and opened the tablet again; https://vid.me/8Y66
- tested in windowed and fullScreen mode
- tried with bufferChanges=true
- minimum test install i used
  - CodeChickenCore-1.7.10-1.0.4.35-universal.jar
  - CodeChickenLib-1.7.10-1.1.3.127-universal.jar
  - ForgeMultipart-1.7.10-1.1.1.323-universal.jar
  - NotEnoughItems-1.7.10-1.0.4.90-universal.jar
  - OpenComputers-MC1.7.10-1.5.2.8-universal.jar
  - Waila-1.5.9_1.7.10.jar

**Comment by fnuecke** [comment]
I'm assuming this is in single player? So the game is paused? The tablet is probably pruned from the cache in that case, because the item gets no updates while the game is paused. Avoiding that will be... interesting.

**Comment by moTechPlz** [comment]
Yes, singlePlayer. And a 'computerCase' computer does not have this problem as far as i can tell.

**Comment by fnuecke** [comment]
Yeah, because it's state doesn't need to live in a weakly keyed hashtable, unlike the one for tablets. Well, I'll look into it. Can't promise a quick fix. I'd recommend not pausing the game if the reboots are a problem, in the meantime :P
