### ISSUE TITLE
Computers and robots do not stay on pass server reboot

### ISSUE THREAD

**Issue by kayila** [MightyPirates/OpenComputers#950]
Can this be fixed?

Or....

Can there be a way to restart computers on server reboot, even if not restarting the original program?

**Comment by gjgfuj** [comment]
They should stay on past server reboot, how have you got the server and
configs setup?

**Comment by Pwootage** [comment]
The situation when this happens to me is generally when my computer is consuming a lot of power and the power network takes a moment to connect.

It may be worth adding a power-usage delay, actually, even though power networks are _supposed_ to immediately connect, they may not in large networks.

**Comment by LizzyTrickster** [comment]
You could add some capacitors to your network, that way it has a bit of a buffer before the energy nets reconnect

 --SNIP stupid outlook --

**Comment by kayila** [comment]
What's weird is it IS connected to a capacitor. I have the computer controlling a big reactor and it seems that whenever I reboot the server, I need to kick the computer. I have access to all the server and config files.

**Comment by fnuecke** [comment]
Could you please check your logs to see if there's anything wrt. computers' state failing to be restored?

**Comment by kayila** [comment]
Ok, it looks like they do stay on past reboot. There must be something else getting bugged in the system. I'm now wondering about maybe something staying chunkloaded when it shouldn't be, cutting the reactor off from the computer. I'll poke it a bit more. Thanks for the info guys! Going to mark this as closed as I no longer think it's a problem with opencomputers.
