### ISSUE TITLE
Arbitrary pitch/yaw control for bow firing on robots

### ISSUE THREAD

**Issue by pingbird** [MightyPirates/OpenComputers#952]
would allow us to make automated sentries

**Comment by pingbird** [comment]
if you are wondering how the math for making a sentry would be done:

subtract the targets position from the robot's position
rotate the xz plane so that x+ is forward and z+ is right
then rotate math.atan2(x,z) by the robot's yaw, this is your firing yaw
and math.atan2(y,x) is your firing pitch

**Comment by sirdabalot** [comment]
How're you planning to get the targets position?

**Comment by vifino** [comment]
Lasers, obviously.

**Comment by Vexatos** [comment]
Computronics Radar Upgrade?
Just an idea :wink:

**Comment by MyNameIsKodos** [comment]
Can't vanilla OC radar do this as well?

**Comment by Vexatos** [comment]
OC doesn't have a radar. It's got a Motion Sensor, though.

**Comment by MyNameIsKodos** [comment]
I think that would be a neat balance for PvP.  If you stood absolutely still, a robot sentry couldn't find you. The second you move though, _thunk_ ~~boot~~ arrow to the head.

**Comment by pingbird** [comment]
the algorithm i showed calculates a straight line towards the target position, i need to find the trajectory algorithm of a arrow in order to make it work from a long distance and account for the target's velocity

**Comment by CoolCat467** [comment]
More control over projectiles for the robots is what they want I think

**Comment by payonel** [comment]
open for adaption expired :)
