### ISSUE TITLE
Last Error:No RAM installed in the computer bug

### ISSUE THREAD

**Issue by PotatoOMG39** [MightyPirates/OpenComputers#954]
The computer says he has no memory installed and I installed two RAM modules, but still says it has no memory installed. It's a bug or something like that?

**Comment by magik6k** [comment]
MC/OC Version? Screensoots? Anything?

**Comment by PotatoOMG39** [comment]
Minecraft 1.7.10 with forge, OpenComputers-MC1.7.10-1.5.2.8-universal,i have nothing of screenshots

**Comment by PotatoOMG39** [comment]
is that message when the computer has no memory

**Comment by PotatoOMG39** [comment]
help please i want to play with that mod,is very very cool

**Comment by skyem123** [comment]
Can't you take a screenshot of the error?
Do you know know to?

**Comment by PotatoOMG39** [comment]
![2015-03-08_16 02 32](https://cloud.githubusercontent.com/assets/11368472/6547110/ffa43a12-c5a4-11e4-881e-068ababb6a81.png)

**Comment by skyem123** [comment]
Yeah. That looks like a bug.

**Comment by PotatoOMG39** [comment]
in older versions of OpenComputers this bug was not in the mod
