### ISSUE TITLE
OC crashes with Java 9

### ISSUE THREAD

**Issue by Shegorath123** [MightyPirates/OpenComputers#955]
When OpenComputers 1.7.10 and Java 9 are installed, Minecraft crashes while generating a new world. 

http://pastebin.com/EGvhHAhk

Ironically, the Java version checker OC is trying to call isn't there anymore. I'm not sure what checker other mods use, but OC was the only mod out of my ~200 other jarmods that wouldn't start with Java 9. 

With Java 9 being experimental and all, this is obviously a low priority issue. But fixing it now would help us find more Java 9 bugs in the future :)

**Comment by gjgfuj** [comment]
I'm guessing its a problem with apache commons not being java 9, rather
than OC.

**Comment by Shegorath123** [comment]
I think you're right.

https://issues.apache.org/jira/browse/LANG-1027

Looks like an old issue though.

Anything I could do on my end to work around the issue? Or would we have to add a workaround here:
https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/common/SaveHandler.scala#L201

EDIT: _facepalm_ I'll try updating the libs, 1 sec. 

EDIT2: Lang 3.4 isn't out yet, I'll have to try building it myself. :(

**Comment by Shegorath123** [comment]
Yup, confirmed the issue isn't with OpenComputers. I built Apache Lang 3.4 myself, and Java 9/OC works fine.

**Comment by asiekierka** [comment]
I blame Cirno.

![](http://safebooru.org//samples/1055/sample_424e168ed990e8c6f6fce9984305a2520fd54f82.png?1093820)
