### ISSUE TITLE
Unable to craft a Lua BIOS

### ISSUE THREAD

**Issue by immortaleeb** [MightyPirates/OpenComputers#957]
I'm using OpenComputers 1.5.2.9 (included in the FTB infinity pack version 1.2.1) and when trying to craft a Lua BIOS, I get an empty EEPROM instead.
When installing it in a computer it gives the error "install a configurable EEPROM" when using the analyzer.
I'm pretty sure the crafting recipe is just broken, since cheating in the item seems to make it work.

**Comment by gjgfuj** [comment]
A lua bios is an empty eeprom with a book. Are you sure you're crafting it
right?

**Comment by immortaleeb** [comment]
Haha, my mistake: When looking at the recipe for a Lua ROM in NEI, the first crafting recipe it shows is for an empty EEP rom, I never noticed that there was a second page.
Nothing to see here, carry on.
