### ISSUE TITLE
Redstone Event Returning Colors

### ISSUE THREAD

**Issue by natedogith1** [MightyPirates/OpenComputers#958]
taken from http://oc.cil.li/index.php?/topic/490-using-bundled-cables-quickly/
For bundled cables redstone_changed should indicate which color changed. There should also be an api function that returns all the values of the bundled cable in a single call.

**Comment by fnuecke** [comment]
Huh, thought there was a getter for that already, guess I forgot that when adding setting all colors at once. Will add that.

Passing the actual channel / color in the event would need some relatively deep changes, and after adding a getter for the full state in one go I think the gain doesn't validate the potential introduction of incompatibilities or new bugs.
