### ISSUE TITLE
Angel Upgrade not working

### ISSUE THREAD

**Issue by Jalopy43** [MightyPirates/OpenComputers#960]
I have a robot with an angel upgrade and it won't place blocks in the air. I am using OpenComputers v1.5.2.9.

to replicate it you get a robot with an angel upgrade, then try to make it place a block without a reference block.

**Comment by theArhar** [comment]
Still not fixed in 1.7.1.43

**Comment by payonel** [comment]
@theArhar the problem was reintroduced in 1.12, it is fine in 1.7.10
