### ISSUE TITLE
Drone or sentry robot long range bamboo stick?

### ISSUE THREAD

**Issue by excelcrafter** [MightyPirates/OpenComputers#961]
What about some nice laser on drone or robot?
Lock the target, exception owner, friendlist, passive mob, poke the target with some nice beam...
Using beam will consume energy...not enough energy, return to dock and charge...
hacking robots or drones with wireless connection...
capture drone controls, kill the maker :-D drop the nuke and count to ZERO :-D

**Comment by fnuecke** [comment]
This sounds like something that would be better placed in an addon or as a bridge mod adding integration for stuff from another mod that already provides weaponry.
