### ISSUE TITLE
Suggestion: robot.chestCount()

### ISSUE THREAD

**Issue by GoneNomad** [MightyPirates/OpenComputers#964]
Have a situation where I want the program to confirm 2 or more Inventory Upgrades are installed. 

robot.chestCount(): number
Returns the number (0-4) of usable InventoryUpgrades currently available.

**Comment by fnuecke** [comment]
Use `robot.inventorySize()`.

If you need the actual number of inventory upgrades, since AFAIK there are none except the OC built-in ones you could do `function chestCount() return robot.inventorySize() / 16 end`.
