### ISSUE TITLE
Odd slow performance rate

### ISSUE THREAD

**Issue by BrotherLavarius** [MightyPirates/OpenComputers#965]
Hi!
I got a problem thou i can't understand why it's happening.
I moved my server from one hosting to another
! same machine parameters <- that's important please note this!

Same CentOS 7 and java 8 from oracle distribution

I get perfect server performance both for some reason Lua processing in OC (OpenComputers) seem's oddly bad. I get 15second timeout before text appears and commands run.

I tryed to force native = same stuff
LuaJ = same stuff
increasing quota of proccessor = same lag not even using the cpu!
we tested memory access and harddrive I\O and just nothing
It's pretty strainge, can you assist please?

Also tryed downgrade to 1.4.9 = Same stuff there

**Comment by BrotherLavarius** [comment]
Also i found that the OC cant allocate memory for the Lua for some strainge

**Comment by fnuecke** [comment]
> I get 15second timeout before text appears and commands run.

As in that's how long it takes for OpenOS to boot? Or are you running some custom code (startup script e.g.?)

> Also i found that the OC cant allocate memory for the Lua for some strainge

What?

**Comment by Vexatos** [comment]
@fnuecke First one probably is that weird lag spike you get when turning on a computer for the first time because you're initializing some stuff there.

**Comment by fnuecke** [comment]
Except I'm not... anymore. Sounds are preloaded, have been for a while now. I have no clue what that lag is. And it certainly shouldn't 15 seconds.

**Comment by BrotherLavarius** [comment]
> Also i found that the OC cant allocate memory for the Lua for some strainge
> Yes! I see on your MOTD in your OpenOS 0k memory. I found that with launching as root user fixes this issue.
> 
> As in that's how long it takes for OpenOS to boot? Or are you running some custom code (startup script e.g.?)

Load of the os is like 30-40 sec.
15 sec it the input lag. I can type something and it will appear after 15 second + 3-4 to run (even command)

I most sertain it's caused by Main OS of the Host, i will test this on debian branch and post an update.

**Comment by fnuecke** [comment]
Sounds like the worker threads are not getting a lot of CPU time to work with. I've added a setting to allow specifying a custom priority for the worker threads, please [get build 459](http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/) and set `threadPriority` to 5 or so. If that does help, I'd say something is a bit wonky with your new servers thread scheduling.

**Comment by BrotherLavarius** [comment]
> Sounds like the worker threads are not getting a lot of CPU time to work with. I've added a setting to allow specifying a custom priority for the worker threads, please get build 459 and set threadPriority to 5 or so. If that does help, I'd say something is a bit wonky with your new servers thread scheduling.

Sad news, not helped, i will look in to this deeply on OS side and move to diffirent branch, do you need updates on my testing? If yes do a reply else close the issue.

**Comment by fnuecke** [comment]
While it seems odd, I can't help but think it's something with your server, since I haven't had any reports of such massive delays from anyone else :-/
Would still be interested in what it was if you figure it out. If I can help in testing, let me know.
