### ISSUE TITLE
left/right mixup

### ISSUE THREAD

**Issue by gozulio** [MightyPirates/OpenComputers#966]
i tell the redstone card to output to the left and it outputs to the right when using the sides api
NOTE: i cought that in the top screenshot, im using version 1.5.3.10 not 1.5.2.9
![2015-03-19_22 59 29](https://cloud.githubusercontent.com/assets/10771387/6745293/bcad5ad2-ce8b-11e4-8e61-8b2aac3f7db7.png)
I define com1 as sides.left
![2015-03-19_23 00 01](https://cloud.githubusercontent.com/assets/10771387/6745302/c5d674ea-ce8b-11e4-82af-a06c474367ee.png)
machines outputs to the right.

**Comment by MyNameIsKodos** [comment]
The Sides API is referring to the sides from the computer's perspective, not yours.  So this is working as intended.

**Comment by gozulio** [comment]
the computers perspe- ...oh... im a derp...
