### ISSUE TITLE
Open Computers TE Memory Leak

### ISSUE THREAD

**Issue by lumien231** [MightyPirates/OpenComputers#968]
Using the latest 1.8 dev version of oc in my dev environment i noticed that my mods tile entitys are not being garbage collected when the chunk they are in is unloaded / i exit the world. Removing OC fixes this so i assume oc keeps a reference to them somewhere.

**Comment by fnuecke** [comment]
Which version of OC is this with? There were some leak related fixes very recently.

**Comment by lumien231** [comment]
OpenComputers-MC1.8-1.5.3.53-dev-dev.jar The latest dev version.

**Comment by fnuecke** [comment]
OK, will try to reproduce.

**Comment by Kubuxu** [comment]
@fnuecke it might be same problem as ours.

**Comment by fnuecke** [comment]
Hrm, didn't it only happen for Microcontrollers in your case, though?
@lumien231 any OC block in particular that seems to cause it?

**Comment by lumien231** [comment]
I don't have to place any oc blocks for it to happen. The blocks it happens with also aren't components.

**Comment by Kubuxu** [comment]
@fnuecke It was happening with everything connected to those uC.

**Comment by fnuecke** [comment]
Wait, so chunks fail to unload only by OC being _present_? That's... I have no idea what could cause that. Do the chunks fail to unload or are they immediately reloaded again? In the latter case, mind checking in `validate()` what keeps it loaded / reloads it?

**Comment by lumien231** [comment]
So i didn't look into it THAT much to be honest, will see whether i can find out what exactly keeps it loaded. I just know that my tes aren't being garbage collected with oc installed.

**Comment by fnuecke** [comment]
Hrm, if the chunks actually are getting unloaded, maybe create a heap dump with VisualVM to figure out which GC root keeps them alive?

**Comment by lumien231** [comment]
Okay now i can't reproduce this anymore :P, will reopen this if it happens again.

**Comment by fnuecke** [comment]
Allrighty.
inb4 vanilla bug :P
