### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by DrummerMC** [MightyPirates/OpenComputers#970]
When placing a block on a siede of the opencomputers-adapter the client will crash.
I think it's a problem with GT6
Crash Report: http://pastebin.com/U9tGJdB7

https://github.com/BakermanLP/ProjectPhoenix/issues/108

**Comment by Vexatos** [comment]
GregTech 6 is still considered alpha, so noone should update mod integration to it yet. You should probably just stick with GregTech 5 for now...

**Comment by fnuecke** [comment]
For now you'll have to disable integration manually in the OC config (add `"gregtech"` to the `integration.modBlacklist` list). The last time I checked I couldn't automatically disable it, because GT only reported `MC1.7.10` as its version, not the actual GT version.

**Comment by Vexatos** [comment]
@fnuecke It still does, you would have to check for GregTech_API.VERSION or something similar, can't exactly remember.

**Comment by fnuecke** [comment]
That's... meh. But I'll have a look at it, thanks for the pointer.
