### ISSUE TITLE
Drone detection and false positivies

### ISSUE THREAD

**Issue by MisterErwin** [MightyPirates/OpenComputers#972]
The drone's detect method returns false positives on blocks where a robot couln't pass through but a drone could, e.g. levers.

Here you can see the surrounding.
![](http://i.gyazo.com/3710c003937ac5c754f29cb8ede7daba.png)

And here is a picture of the remote drone shell
![](http://i.gyazo.com/dec31beba93b3996c0ed9aed95cea96d.png)

Greetings and happy 3D modelling ;)

(I used version 1.5.4.471-dev, but according to the commits nothing was changed except some 3d stuff)

**Comment by fnuecke** [comment]
Well, "solid" technically just means it isn't air ;-)

Hmm, properly checking if a block is "passable" for a drone might be overkill, but I'll add a check whether a block returns no collision bounds at all, that should work for most scenarios (such as levers, buttons and torches).

**Comment by fnuecke** [comment]
Done. Beware it'll still return `true, "passable"`, so you'll have to check for that second value.

**Comment by MisterErwin** [comment]
Thanks for fixing, but you might want to change that or the docs:

> Returns: true if the robot if whatever is in front of the robot would prevent him from moving forward (a solid block or an entity), false otherwise. 

[See ocdoc.li](http://ocdoc.cil.li/api:robot)

€: looks ;)

**Comment by fnuecke** [comment]
If I still remember it in a few minutes I will ;-) (You could also register and change it, wiki is open for registration and everyone can edit)

**Comment by MisterErwin** [comment]
Work successfully outsourced ;)

But other than that, the block in front doesn't prevent the drone from moving, so shouldn't the boolean return be false?

But I'm going to add "passable" as soon as I get the master's answer  ;)

**Comment by fnuecke** [comment]
Great, thanks ;)

The thing is, this is the same method for all agents - it's the exact same code that's used for `robot.detect()`. And those can't move in there. So for compatibility reasons and to avoid special cases this is how it is.

**Comment by MisterErwin** [comment]
Report from slaved worker: D(r)one ;)

And thanks again

**Comment by fnuecke** [comment]
:+1:
