### ISSUE TITLE
Odd Error

### ISSUE THREAD

**Issue by kreezxil** [MightyPirates/OpenComputers#976]
I was mining iron ore in the depths of my world and this error happened.

https://paste.ee/p/UejX2

Lower down in the stack trace section it references open computer classes. Not sure if it is related to you or not.

Also, this happened on Forge b1341

**Comment by pingbird** [comment]
-snip- derp

**Comment by fnuecke** [comment]
Huh, no clue in what context the block position would be null in the highlight rendering callback (which is what's causing this), but simple enough to catch with a check. Next build should this. Thanks for reporting!
