### ISSUE TITLE
io.lines not properly implemented

### ISSUE THREAD

**Issue by SoniEx2** [MightyPirates/OpenComputers#977]
`io.lines(nil, ...)` doesn't work as it should

**Comment by fnuecke** [comment]
What does it do, what do you expect it to do?

**Comment by SoniEx2** [comment]
It calls `io.input():lines()`, I expected it to call `io.input():lines(...)`

**Comment by fnuecke** [comment]
[The Lua manual](http://www.lua.org/manual/5.2/manual.html#pdf-io.lines) doesn't really mention this use-case, it does say however:

> The call io.lines() (with no file name) is equivalent to io.input():lines()

Is the manual wrong / incomplete? Does it actually behave the way you want it to in vanilla Lua?

**Comment by SoniEx2** [comment]
Well I found the OC bug while porting Lua 5.2's IO lib (the C code) to LuaJIT/FFI

**Comment by fnuecke** [comment]
If it behaves different to "vanilla" Lua, feel free to make a pull request to change it, with an example use-case and way to reproduce the discrepancy. Since it's basically undocumented behavior, I don't really think it's critical, though.

**Comment by SoniEx2** [comment]
Well you could say

> The call io.lines() **(with no file name)** is equivalent to io.input():lines() _(Emphasis mine)_

Would allow io.lines(nil) to be equivalent to io.input():lines(), thus io.lines(nil, ...) should be equivalent to io.input():lines(...).
