### ISSUE TITLE
Basic Case crash on place.

### ISSUE THREAD

**Issue by N00byEdge** [MightyPirates/OpenComputers#98]
I crashed my server when I placed a basic case, and the server crashes again on world load, since the area is chunkloaded. It is a MCPC+ server, but the issue is persistent on my client too. I am using OpenComputer 1.1.3, and the other mods are Direwolf20 pack with Gregtech and Redstone in Motion. It also crashes without GregTech, already tested.

Crash log (from MCPC+ server):
http://pastebin.com/tKp0T5we

Client (Without GregTech):
http://pastebin.com/K8ZaM7jC

Client (With GregTech):
http://pastebin.com/LJs2cP0v

**Comment by fnuecke** [comment]
See #85, update your version of Project: Red. The next version of OC will have a check for that to avoid crashing.

**Comment by N00byEdge** [comment]
Thank you for the quick response! I'll get right to it! :D
