### ISSUE TITLE
Damage when removing components when computers still work...

### ISSUE THREAD

**Issue by SeniorFight** [MightyPirates/OpenComputers#981]
In real life (let's be realistic) if the computer is on, and we remove manually without rubber protection like the CPU, we should get a punch of electricity, and it shouldn't be possible to remove (SOME) components when computer is running, like the CPU.

Players in survival should have some rubber protection (like in IC2) or anything else to remove while computer running, otherwise should get random damage when removing and a warning message, and cause maybe a screen flicker or something in the computer to show that it's bad to do so.

It's a feature I think should be in.

Also thanks for the like in the forums, Sangar ;)

**Comment by SoniEx2** [comment]
In real life, if the computer is ON, at most you'll get 24v, which's not enough to give you a shock. At most, removing a component while the computer is ON will permanently damage the component.

**Comment by skyem123** [comment]
Actually, on modern computers it's 12v, however the ampage could be nasty (not too sure on that...)

**Comment by SoniEx2** [comment]
We're talking about skin conductivity/resistance (a few thousands to hundreds of thousands of ohms), you would have to have your hands/fingers bleeding (blood is very conductive) to get a shock from that. (assuming you wouldn't be licking it, as that'd also give you a shock)

And well, on modern PSUs there's a +12v and a -12v rail, and between the 2 you have 24v. (altho putting a load between them will more than likely trip the PSU)

**Comment by skyem123** [comment]
If I remember correctly, -12v (and so 24v) have a very low current limit.

**Comment by SoniEx2** [comment]
Indeed, but it's still there.

**Comment by skyem123** [comment]
Well, sorry...

**Comment by fnuecke** [comment]
If this has no other gameplay value than to annoy players, I'm not sure it'd be worth the effort to implement it ;-) It kind of falls into the category of "hard-mode" features like computers not being water-proof. And I decided to invest my time in actually useful features some time ago, so I will _probably_ not be implementing this (as usual, subject to change).

If someone were to implement hard-mode features with a corresponding config entry I'd be willing to merge that, though.

**Comment by fnuecke** [comment]
All right, so. After thinking about this topic for quite a bit, here's my stance on "hard mode" features: I don't plan on adding them in the foreseeable future. So I'm gonna close issues I feel that fall into that category as duplicates of #1043. While not entirely serious, that issue can serve as a place to pool "hard mode" ideas, in case someone wants to get working on an addon that does that, or I change my mind in the future.

**Comment by elfifae** [comment]
@SoniEx2 No it isn't. The -12V rail has been deprecated since the removal of ISA, and I don't think ANY PSUs made in the last decade have it.

**Comment by SoniEx2** [comment]
@lamialily they do... especially cheap ones

**Comment by lordjoda** [comment]
Well since OpenComputers only uses state of the art and very expensive components this is a non issue!

**Comment by Vexatos** [comment]
State-of-the-art iron-insulated cables. I approve. :+1:
