### ISSUE TITLE
Installing and setting up sources fails

### ISSUE THREAD

**Issue by KJA1582** [MightyPirates/OpenComputers#984]
When trying to set up the sources like described in the read me, the project is missing three dependencies (CoFH, MFR and RotaryCraft). This leads to compile errors and generally does make the Tasks in Intellij IDEA fail (reobfuscating for example).

**Comment by fnuecke** [comment]
Should have fixed those dependencies. I really don't want to do a cache clean, so I can't say what else might be broken; if anything is, let me know.

**Comment by KJA1582** [comment]
Thanks a lot. I will try it out and report back if something else fails.

PS: This mod is great for automating AE2.

**Comment by KJA1582** [comment]
Works fin but now I get following error:

Error:(213, 38) value instance is not a member of object appeng.core.Api
        (nbt: NBTTagCompound) => Api.instance.storage.loadCraftingLink(nbt, this))
                                     ^

in following file:

src/main/scala/li/cil/oc/integration/appeng/DriverController.scala

**Comment by fnuecke** [comment]
Uhh, [that's not what that line says anymore](http://git.io/jPKC) (since a couple of commits back), so I'd guess you didn't pull, but then I'm wondering how the dependency issue is gone?

**Comment by KJA1582** [comment]
Yeah sorry, should have said that I needed v1.5.2. Nevertheless, thanks for the support. Dependency Issue is fully solved, just getting some Scala warnings.

**Comment by fnuecke** [comment]
Ah, then you'll have to adjust that, yeah. The Scala warnings are fine, nevermind those ;-)
