### ISSUE TITLE
Make Angel Upgrade work in Drones

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/OpenComputers#985]
The Angel Upgrade currently doesn't work correctly in drones (which why it'll stay disabled for them for now), which is because placement uses the standard placement logic, which places blocks against other blocks. This works for robots, because in that case they basically "place it against themselves". That doesn't work for drones though. Will need to find a non-ugly workaround / alternative for that case.

**Comment by MyNameIsKodos** [comment]
How does it work for players?

**Comment by fnuecke** [comment]
I don't know. But I'm assuming special cases wrt to how the coordinates for the call are chosen. Which is what this'll probably boil down to, too, but I really really want to avoid making this robot/drone specific, and keep it generic for all kinds of agents (since that code is shared).

**Comment by Keridos** [comment]
@Kodos-Atoz if you mean the original angel block from ExU it just places itself in the block you are standing on (the first of the 2 blocks below you that is free)

**Comment by payonel** [comment]
adding support in 1.12 only, now in latest 1.12 dev builds
