### ISSUE TITLE
Change the CoFH DriverEnergyHandler to DriverEnergyProvider and DriverEnergyReceiver

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/OpenComputers#989]
This would add integration to a lot of blocks that are not IEnergyHandlers. See [this]() and [this](https://github.com/asiekierka/Computronics/blob/master/src/main/java/pl/asie/computronics/integration/cofh/DriverEnergyProvider.java) for how to do it. I recommend preferring one (I preferred IEnergyReceiver) and put a `!(te instanceof IEnergyReceiver)` into the IEnergyProvider driver so the methods do not get added twice unnecessarily.
Make sure you depend on version 1.0.0 or later of the CoFH API for this.

**Comment by fnuecke** [comment]
Thanks for the reminder! I think this should cover everything, and remain backwards compatible.
