### ISSUE TITLE
Component health

### ISSUE THREAD

**Issue by SeniorFight** [MightyPirates/OpenComputers#990]
Add health to every component and cards.

Add heat vents to prevent heat damage on them.

Add possibility to repair them before total destruction of an component.

Add random component damage if computer is submerged under water.

Add module random errors (screen flicker for graphics card for example) if module is below 5 ~ 10 % health (in scripting it will be like 5 uses lefts out of 100).

Add time-usage, the longer you use it, the more it gets damaged, except for tier 3 and creative, which would only get damage from water and heat.

Add heat cooling if feature is added (a module that will use a liquid to cool down components, or an external heat vent to keep high-tier components cooled, the more components in, the more heat produced, don't even think about heat generation for IC2...)

**Comment by Kubuxu** [comment]
Can I ask you: Where is fun in randomly failing components?

**Comment by SeniorFight** [comment]
The fun is to make manageable heat vents (scriptable, so they can work faster/slower depending of the BIOS),

the fun is to repair components,

the realism in hard-core mode is to lose them, which is part of the "reality" in our real life.

the fun is to make it more realistic. This of course can be toggled normal = off/hardcore = on by the player in the config I think it's the best solution.

**Comment by Techokami** [comment]
I thought the fun was with running computers in Minecraft.

Sent from my Windows Phone

**Comment by Vexatos** [comment]
I doubt this is worth the effort...

**Comment by SeniorFight** [comment]
For me it would be fun to make modules that get damaged if submerged under water or works haaaard without vents (computers have already vents installed, but using high-end modules on low-end computers should make these vents not enough to cool down)

Why people doesn't like it, it's cool and it makes it realistic. Running computers is good, modular system is good to, but damage to these modules should be even more realistic and CAN BE TOGGLED ON/OFF in the config!!! So not everyone will get embarassed if they won't.

**Comment by Kubuxu** [comment]
@SeniorFight but this all requires much of precious development time. It would require major rewrite of component/upgrade system.

And what with robots. Should their component also take damage. You can't change them easily.

**Comment by SeniorFight** [comment]
@Kubuxu Robots should have "waterproof plates" to protect modules from water corrozion.

Robots also should have integrated heat vents, those would cool down these modules.

And no, we don't need majoooor rewrites, just add "uses" to every module, and add cooling/heating/damaging system to modules.

IT would be like a fun-part of this mod.

**Comment by fnuecke** [comment]
Let's just agree that what's fun is different for each person. I personally don't enjoy an overabundance of "pure maintenance" when automating things (which this would fall under, in my opinion). So unless there's major demand for this, I won't add this myself. This also falls into a kind of "hard mode" set of features, like #981.  As mentioned in that issue, if someone were to make a good pull request, I'd be willing to merge that.

**Comment by SeniorFight** [comment]
@fnuecke You said by yourself, that you'll maybe add computer "electrick shock" or something when under water, which would be logicall, as we see on both sides of the computer that there are vents, and water "could" enter through those wents and if computer is running should shut it down.

**Comment by fnuecke** [comment]
All right, so. After thinking about this topic for quite a bit, here's my stance on "hard mode" features: I don't plan on adding them in the foreseeable future. So I'm gonna close issues I feel that fall into that category as duplicates of #1043. While not entirely serious, that issue can serve as a place to pool "hard mode" ideas, in case someone wants to get working on an addon that does that, or I change my mind in the future.
