### ISSUE TITLE
Question on AE2 ExportIntoSlot functionality with 1.5.5

### ISSUE THREAD

**Issue by theron61** [MightyPirates/OpenComputers#997]
I have a question in regards to the AE2 ExportIntoSlot call.  What is the recommended way to keep a export bus from performing operations all of the time to make this call useful?  I used a redstone card that disabled the bus on prior versions and that seemed to work.  This no longer works with the latest 1.5.5 release.

**Comment by fnuecke** [comment]
Works absolutely fine for me (tested with latest OC and AE2 rv2-beta-18). Are you sure nothing has changed in your configuration, and it's not an issue on AE2's side? (i.e. it works if you apply a redstone signal using a redstone torch or so?)

**Comment by theron61** [comment]
I am using AE2 rv2-beta-18 as well.  

I changed the redstone card to one operation per pulse and it acted like the setConfiguration changes were being queued; each pulse changed the configuration to what the script called for.  It did not deposit the item in the requested slot.

I'll re-test with the latest OC dev build and respond back.  The configuration (as far as I know) has not been changed from OC 1.5.4.

**Comment by theron61** [comment]
It looks like the issue is persisting with the latest 1.5.5 build.  How can I help troubleshoot this?

**Comment by fnuecke** [comment]
Screenshots of a minimal build that reproduces this, of the inventory of the computer and bus, as well as the code you're running would be a good start.

**Comment by theron61** [comment]
I see this if I print the result of the exportIntoSlot code (see attached screenshot).
![oc-error](https://cloud.githubusercontent.com/assets/2978338/6990693/ca7c6a2e-da37-11e4-8fa1-c711d425457a.png)

Working on the other items.

**Comment by fnuecke** [comment]
Ah, I misunderstood earlier. Can reproduce, looking into it. Thanks!
