### ISSUE TITLE
Forge b1348 breaks OpenComputers

### ISSUE THREAD

**Issue by kreezxil** [MightyPirates/OpenComputers#998]
"fml causes duplicate entries in some mods"

server crash report: http://pastebin.com/nF3mqrLh
server fml latest: http://pastebin.com/qqwKvzjG

The client says it's something to do with an ImmutableMap

client crash report: http://paste.ee/p/7S6u5
client fml latest: https://paste.ee/p/Ryjht

This is the similar behavior as was with b1344 issue. I'll report it to forge team as well.

**Comment by SeniorFight** [comment]
I confirm.

**Comment by kreezxil** [comment]
Dieson07 confirmed it was supposed to  be fixed but that Lex failed to add it to FML.

-----Original Message-----

**Comment by fnuecke** [comment]
OK, so we can expect this to be fixed in one of the next Forge builds? Will keep this open until a working build is out, then.

**Comment by kreezxil** [comment]
Yep

-----Original Message-----

**Comment by fnuecke** [comment]
According to the change log this should be fixed in 1349, can someone confirm, please?

**Comment by kreezxil** [comment]
I'll check this out and report back as soon as get back to my server. Likely within an hour of this response.

-----Original Message-----

**Comment by kreezxil** [comment]
Build 1350 was available when I got back and it works beautifully!

**Comment by fnuecke** [comment]
Great, thanks for confirming!
