### ISSUE TITLE
Antennas (esthetic) as wi-fi bridges

### ISSUE THREAD

**Issue by SeniorFight** [MightyPirates/OpenComputers#999]
I would like an antenna-looking (or dish) block, that would transfer wi-fi at a range of 500 maybe, less during storm and maybe attract lightnings!

It's just esthetic, nothing else...

**Comment by gjgfuj** [comment]
Sounds interesting, but, the use case is probably a bit small.

**Comment by SeniorFight** [comment]
@gjgfuj It's, as I said esthetic and I leave the creator's will to make evil things on it...

**Comment by LordFokas** [comment]
Does it work (transfer WIFI, attract lightning) or is it aesthetic (purely decorative, doesn't do anything)?
You have to chose one, an aesthetic block that works is a paradox. It's either aesthetic, or it works. Mutually exclusive.

**Comment by gjgfuj** [comment]
Well no, aesthetics and working aren't mutually exclusive. What I'm saying
is that transferring WiFi is sorta unnecessary.

**Comment by fnuecke** [comment]
Sooo... basically you want a model for the Access Point that also attracts lightning? Ehh... make it an addon :P Feels like there's too much overlap with the Access Point, really.

**Comment by SeniorFight** [comment]
Does... @fnuecke you don't like to make new things, you would only upgrade/fix them :/
Not everyone out here can make an addon, and update it you know...

**Comment by fnuecke** [comment]
Replace "new things..." with "things that have too much overlap with existing features, when I could instead be working on something more interesting (to me)", then yes, you're absolutely right ;-)

**Comment by MisterErwin** [comment]
@SeniorFight Suggestion: Use a 3d printed block if you just want it for esthetic reasons. 
Otherwise use computers as repeaters to have a longer range.
